src/app/Components/Input/PhoneInput/PhoneInput.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhoneNumber.tests.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhoneNumber.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkFormEdit.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx

This PR resolves [ONYX-1011] 
This PR adds the "Add phone number" step to the new Submission artwork form. The phone number will not be validated and is not required.
| | |
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-05-30 at 16 17 05](https://github.com/artsy/eigen/assets/4691889/e6b88574-f2e3-47c9-8cbe-30e417648fa7) |![Simulator Screenshot - iPhone 15 Pro - 2024-05-30 at 16 17 12](https://github.com/artsy/eigen/assets/4691889/a91c44ab-4159-4b58-a369-87345df01a21) |
- Add phone number step to new SWA artwork form (behind ff)- ole
-
-
-
</details> …

feat: Add phone number step to Submission artwork form

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx

This PR resolves [ONYX-1033]
Make "Upload Photos" step placeholders clickable
https://github.com/artsy/eigen/assets/3934579/3353af91-dbf3-429d-84a3-f344ae189d03
<details>
#nochangelog
</details>
[ONYX-1033]: https://artsyproduct.atlassian.net/browse/ONYX-1033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1033): swa upload photos placeholders clickable

---

src/app/Scenes/SellWithArtsy/Components/Header.tsx
src/app/Scenes/SellWithArtsy/Hooks/useSubmitArtworkTracking.ts
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

This PR resolves [ONYX-1030] 
This PR updates the "Continue Previous Submission" CTA on the `Sell` screen. If there is a draft submission after the user clicks "Exit & Save" in the submission form, this CTA displays the artist and the artist name and let's the user continue the submission.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-06-03 at 15 22 53](https://github.com/artsy/eigen/assets/4691889/0b815415-ee31-4348-b1b8-9f6313f7d270) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-03 at 15 57 42](https://github.com/artsy/eigen/assets/4691889/e82d7c7d-f4d7-4bf5-8131-5931932d6a2f)|
- "Continue Previous Submission" CTA design update on Sell screen (behind ff) - ole
-
-
-
</details> …

feat: "Continue Previous Submission" CTA update

---

ios/Podfile.lock
package.json
yarn.lock

This PR resolves [PHIRE-957] 
build(deps): bump @shopify/flash-list and palette-mobile
-
-
-
- bump @shopify/flash-list and react-native-collapsible-tab-view - gkartalis
</details>
[PHIRE-957]: https://artsyproduct.atlassian.net/browse/PHIRE-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build(deps): bump @shopify/flash-list and palette-mobile

---

fastlane/utility_fastlane.rb
scripts/deploys/latest-betas

This PR resolves [PHIRE-962] 
Brings over small enhancement to the latest betas script to output the tags and suggested commands to create release candidate branch from folio. Props @damassi for suggestion!
```
~/C/eigen (brian/latest-betas-update|✔) $ ./scripts/deploys/latest-betas                                                                                                                                       (base) 
[✔] 🚀 
[15:12:18]: Parent latest version: 8.42.0
[15:12:18]: iOS latest version: 2024.6.3.12 (tag: ios-8.42.0-2024.06.03.12)
[15:12:18]: Android latest version: 1674645716 (tag: android-8.42.0-1674645716)
[15:12:18]: If you are creating a release candidate branch:
[15:12:18]: git checkout ios-8.42.0-2024.06.03.12
[15:12:18]: git checkout -b 8.42.0-release-candidate
``` …

build(release-tools): latest betas add tags and checkout command suggestion #trivial

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tests.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkStartFlow.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx

This PR resolves [ONYX-1032] 
Update copy on some of the screens
| --- | --- |
| ![image](https://github.com/artsy/eigen/assets/36167539/0d925767-2ef8-494d-9349-dbb072fdb865) | ![image](https://github.com/artsy/eigen/assets/36167539/67579a96-6a29-4425-99d2-8da2debb8044) |
| --- | --- |
| ![image](https://github.com/artsy/eigen/assets/36167539/1d29c86c-2ffa-4dd2-9710-8c5a8e7038ef) | ![image](https://github.com/artsy/eigen/assets/36167539/ce88760b-2de6-48ff-ab4e-3b079bcdd822) |
| before | after | 
| --- | --- |
| ![image](https://github.com/artsy/eigen/assets/36167539/683a0e0d-50a1-4969-bb84-83f94d550db7) | ![image](https://github.com/artsy/eigen/assets/36167539/407ebd78-65c1-4eee-b1bc-c60f0adcac17) |
Navigate to the Contact a Specialist screen and …

fix(ONYX-1032): copy updates, navigate to the Contact a Specialist screen and pre-fill the user data

---

src/app/Scenes/SellWithArtsy/Components/Header.tsx

This reduces the spacing below the "Finnish previous submission" CTA on the Sell screen so the title is always visible.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-06-05 at 12 57 10](https://github.com/artsy/eigen/assets/4691889/7ff28286-356b-4d2e-a780-a7930f722e22) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-05 at 12 56 47](https://github.com/artsy/eigen/assets/4691889/1d45f68a-ec9f-453b-bf9f-5d7925a632d2)|
-
-
-
-
</details>

fix: Reduce spacing below "Finnish previous submission" CTA on Sell screen

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialSubmissionValues.ts

When continuing a draft submission the value `isYearUnknown` does not get initialized correctly because we don't store the value on the backend. This breaks the validation on the "Artwork Details" step.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-06-05 at 13 34 07](https://github.com/artsy/eigen/assets/4691889/18ad867e-e862-4e0d-86bc-4efcb833c8e5) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-05 at 13 33 30](https://github.com/artsy/eigen/assets/4691889/e3f49fb8-4a78-4c04-a832-75fab97d07dc)|
-
-
-
-
</details> …

fix: Correctly initialize isYearUnknown when editing a submission

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts

- Make last step text "submit artwork"
- Update copy on the last step
-
-
-
-
</details>

chore: address UI QA comments

---

src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx

This disables gestures on the "Artist Reject  step in the submission form. When allowing gestures, [the current step doesn't get set correctly](https://github.com/artsy/eigen/blob/e2523fc3e7cf5d8d60fa2ca5c4b2415c89f6bdca/src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts#L91) in the context. Without the step correctly set, the navigation in the form doesn't work anymore.
- Create new submission
- Type `banksy` in "artist name" input
- Click on `hanksy`
- Use swipe gesture to go back from the "Artist Reject" screen
- Type `banksy` in "artist name" input again
- Click on `banksy`
- Go back on the "Add title" screen
- Click on `banksy`
- -> Landing on a random step in the flow and not on the "Add title" step as expected
-
-
-
- …

fix: Do not allow guestures to go back on SWA artist reject screen

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx

This resolves https://www.notion.so/artsy/Duplicate-images-in-photo-step-from-MyC-c7cd23027d3c455db6b830ceeb669fb1?pvs=4
This adds a check to avoid photo duplications when submitting an artwork from My Collection.
| --- | --- |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-06-05 at 19 12 55](https://github.com/artsy/eigen/assets/4691889/0ac61ae2-6a8e-4313-8f68-970467d9a2a4)|![Simulator Screenshot - iPhone 15 Pro - 2024-06-05 at 19 02 36](https://github.com/artsy/eigen/assets/4691889/2c3087e2-455d-47ab-ac98-49c61b867b21) |
-
-
-
-
</details> …

fix: Avoid photos duplications when submitting an artwork from My Collection

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkProgressBar.tsx

This PR resolves [ONYX-997] 
Update the copy and UI of the Thank you screen
- Update the copy and UI of the Thank you screen -daria
-
-
-
</details>
[ONYX-997]: https://artsyproduct.atlassian.net/browse/ONYX-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-997): adjust the thank you screen

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts

This PR resolves [(ONYX-1045] 
- make the "is the work signed?" field mandatory -daria
-
-
-
</details>

chore:(ONYX-1045): make the "is the work signed?" field mandatory

---

package.json
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
yarn.lock

- Update the text font size to match palette
- Tapping on signature was slow, I made it faster
- Make the signature mandatory
https://github.com/artsy/eigen/assets/11945712/857ffdd4-fe7d-4eae-a42f-5ef693cb32b5
#nochangelog

fix: signature issues

---

package.json
yarn.lock

This PR updates sentry CLI from `2.31.2` to `2.32.1`
-
-
-
- bump sentry-cli from 2.31.2 to 2.32.1 - mrsltun
</details>

build(deps): bump sentry-cli from 2.31.2 to 2.32.1

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts

This PR comes as a follow-up on the conversation with design to make the signature not required until we find a good pattern of showcase required radio buttons.
-
-
-
-
</details>

chore: make signature not required

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialNavigationState.ts
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx

This PR resolves [ONYX-995] 
This PR allows users to find themselves directly in the title step when they are about to submit an artwork from their collection.
https://github.com/artsy/eigen/assets/11945712/0bae37c9-cf04-4819-97e9-ec6c88cc80fa
- navigate to artwork title when the process starts from my collection - mounir
-
-
-
</details>
[ONYX-995]: https://artsyproduct.atlassian.net/browse/ONYX-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: navigate to artwork title when the process starts from my collection

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
src/app/store/config/features.ts

This PR resolves [ONYX-952] 
https://github.com/artsy/echo/pull/630
-
-
-
-
</details>
[ONYX-952]: https://artsyproduct.atlassian.net/browse/ONYX-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: enable new submission flow [Do not merge]

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTipsForTakingPhotos.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/InfoModal/InfoModal.tsx

- Update dimensions order to match my c
- Refresh my collection after submission
- Add spacing after provenance
- Fix screen cropping after scrolling
- Make the photos tips modal match the designs
#nochangelog

fix: UI issues on SWA flow

---

docs/convert_image.md

#nochangelog
-
-
-
-
</details>

chore: adjust the path to the script convert-png-images-to-webp.ph

---

src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/app/Scenes/MyProfile/MyProfileEditForm.tsx

This PR adds disclaimer text to inform users that their profile will be shared with galleries when they send inquiries.
|---|------|-----|
| Inquiry Modal (iOS) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-07 at 05 13 23](https://github.com/artsy/eigen/assets/44589599/a500158d-160f-44af-9415-7ce2c13a2912) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-07 at 05 25 17](https://github.com/artsy/eigen/assets/44589599/26f65303-5b1d-451e-b8b0-84ad2ca02dc8) |
| Edit Profile (iOS) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-07 at 05 13 56](https://github.com/artsy/eigen/assets/44589599/c25169da-350f-43c3-8913-bd97c605e06a) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-07 at 05 14 41](https://github.com/artsy/eigen/assets/44589599/05c3dba8-d38f-48a7-ba5f-d …

feat: inform users that their profile will be shared with galleries when they send inquiries (DIA-674)

---

src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx

This PR resolves [ONYX-977] 
This PR makes the content on tablet limited to 800 pixels (or less if it's a really small one). This came from the conversation with Barney
#nochangelog
[ONYX-977]: https://artsyproduct.atlassian.net/browse/ONYX-977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: limit width on tablet

---

src/app/Scenes/SellWithArtsy/Components/Header.tsx

This PR resolves this [comment](https://www.notion.so/artsy/Ability-to-delete-a-WIP-submission-31cda3b563ec4d8aa003a4bc46f44fb3?pvs=4)
This PR allows users to delete WIP submissions using long press.
https://github.com/artsy/eigen/assets/11945712/8773139d-7851-4ff3-96fa-f9ef6d4ccee2
- allow users to delete wip submissions - mounir
-
-
-
</details>

feat: allow users to delete wip submissions

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx

Fix gap between photos on small devices. I am adjusting the approach to use a smaller value for smaller devices
-
-
-
-
</details>

fix: gap between photos on small devices

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts

This PR resolves [ONYX-1059] 
With this update, we correctly carry over the (new) auto-completed collector location when submitting a MyC artwork.
- Carry over auto-completed location when submitting a MyC artwork - ole
-
-
-
</details>
[ONYX-1059]: https://artsyproduct.atlassian.net/browse/ONYX-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Carry over auto-completed location when submitting a MyC artwork

---

package.json
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
yarn.lock

This PR resolves [ONYX-1075] 
This PR improves the scroll performance on the SWA landing page. This is thanks to using `Flatlist` instead of `ScrollView`. 
FlatList renders only the visible items, optimizing performance with large datasets. ScrollView renders all items at once, potentially causing performance issues on devices with limited processing power.
The difference in performance between the videos is not so big but it would be pretty noticeable on an old android device.
**Before**
https://github.com/artsy/eigen/assets/11945712/3dbfc205-8403-4344-bc0a-1c29cfaa76cf
**After**
https://github.com/artsy/eigen/assets/11945712/19c3ee7a-6fbe-49ad-8b99-3d5c68346430
-
-
-
-
</details> …

fix(ONYX-1075): scroll performance on SWA landing page

---

src/app/system/devTools/DevMenu/Components/DevTools.tsx

Fixes dev menu - migration section wasn't usable - not sure when broke but bringing it back with this PR
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 14 Pro - 2024-06-18 at 16 03 36](https://github.com/artsy/eigen/assets/21178754/bd289714-46e8-42f5-ad33-bc8f3b3b214e)|![Simulator Screenshot - iPhone 14 Pro - 2024-06-18 at 16 03 18](https://github.com/artsy/eigen/assets/21178754/312551bb-c4a0-4440-aab3-41fac04f1a64)|
-
-
-
- fixes dev menu migration broken switcher - gkartalis
</details>
[docs]: …

fix: migration version

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx

This PR resolves [AMBER-725] 
If the partner has the new price display flag enabled, we hide the `saleMessage` from the artwork grid.
Solution submitted by @Mitch-Henson 
Before
After
- Do not show the sale message in case of artworks with a price display set to "inquiry about availability"
-
-
-
</details>
@artsy/amber-devs 
[AMBER-725]: https://artsyproduct.atlassian.net/browse/AMBER-725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Ensure that inquire sale message is not shown in the grid

---

package.json
yarn.lock

see here more [info](https://github.com/artsy/eigen/security/dependabot/162)
#nochangelog

build(deps): bump braces indirect dependency due to dependabot alert

---

src/app/AppRegistry.tsx
src/app/Components/HeaderArtworksFilter/HeaderArtworksFilter.tsx
src/app/Components/HeaderArtworksFilter/HeaderArtworksFilterWithTotalArtworks.tsx
src/app/Components/ShareSheet/ShareSheet.tsx
src/app/Components/ShareSheet/helpers.ts
src/app/Components/ShareSheet/types.ts
src/app/Scenes/Collection/Collection.tsx
src/app/Scenes/Collection/Components/CollectionArtworksFilter.tsx
src/app/Scenes/Collection/Components/FeaturedArtists.tsx
src/app/Scenes/Collection/Screens/CollectionArtworks.tsx

This PR comes as a follow-up to this feedback on slack: https://artsy.slack.com/archives/C03N12SR0RK/p1710709509110609
This PR adds the share icon to the collection screen.
Next, I am thinking about how we can have allow sharing all screens easily. I already did the hard work here: https://github.com/artsy/eigen/pull/10199 so it shouldn't be hard to pull.
https://github.com/artsy/eigen/assets/11945712/93d7ad24-7ac5-4309-9ac8-446c8eacc372
- allow sharing collections - mounir
-
-
-
</details>

chore: add share icon to collection

---

src/app/Scenes/Artwork/Artwork.tsx

This PR resolves [AMBER-760] 
We have custom pageview tracking on the artwork page capturing specific data for analytics purposes. Add saleMessage to the collected data.
-
-
-
- Add the artwork price display (sale message) to the artwork pageview properties
</details>
Equivalent PR in Force: https://github.com/artsy/force/pull/14038
cc @artsy/amber-devs 
[AMBER-760]: https://artsyproduct.atlassian.net/browse/AMBER-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

chore(AMBER-760): Add saleMessage as price_display to artwork pageview

---

ios/Podfile.lock
package.json
yarn.lock

There was an email from Google play colsole to update Play Core Maven dependency to an Android 14 compatible version.
We don't have a direct dependency with com.google.android.play:core, but we have a transitive one through react-native-in-app-review lib 
To update the transitive dependency I update the react-native-in-app-review to the latest version of com.google.android.play:core
react-native-in-app-review dependencies before
```
+--- project :react-native-in-app-review
|    +--- com.facebook.react:react-native:+ -> com.facebook.react:react-android:0.72.12 (*)
|    +--- com.google.android.play:core:1.9.0
|    \--- com.google.android.gms:play-services-base:17.5.0 -> 18.0.1 (*)
```
react-native-in-app-review dependencies after:
```
+--- project …
```

chore: Update your Play Core Maven dependency to an Android 14 compatible version

---

ios/Artsy/App_Resources/Artsy.Store.entitlements
ios/Artsy/App_Resources/Artsy.entitlements
src/app/utils/useDeepLinks.ts

This PR resolves [PHIRE-992] 
- Adds email-link to entitlements for iOS
- adds email-link to useDeepLink hook in order to decode the url 
> [!WARNING]  
> Still need to test on Android before merging ⚠️
- enables email-link deeplinks - george brian
-
-
-
</details>
[PHIRE-992]: https://artsyproduct.atlassian.net/browse/PHIRE-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: email-link.artsy.net deeplinks 

---

src/app/Scenes/BottomTabs/BottomTabsButton.tsx

Co-authored-by: George <g.kartalis7@gmail.com>
This PR improves the performance of the bottom tabs animation.
https://github.com/artsy/eigen/assets/11945712/88ee2695-d64a-4d64-8c74-beeb49d6241d
- improve animation between tabs - mounir, george
-
-
-
</details>

chore: improve animation between tabs

---

src/app/Scenes/Collection/Collection.tsx

https://github.com/artsy/eigen/assets/11945712/79b80560-1766-43b0-aac9-2595200bed54
#nochangelog

fix: share my collection

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Form/useArtworkForm.ts
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx

This PR resolves [ONYX-1096] 
This PR fixes Edit My Collection Artwork Saving
https://github.com/artsy/eigen/assets/11945712/a57580ce-1e10-4672-b105-db0b241e8089
- broken edit my collection artwork - mounir
-
-
-
</details>
[ONYX-1096]: https://artsyproduct.atlassian.net/browse/ONYX-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: broken edit my collection artwork

---

src/app/Scenes/Home/useHomeModules.ts
src/app/store/config/features.ts

Remove unused `meetYourNewAdvisor` module. It causes separator duplication (extra space) on the home screen:
| With it | Without |
|---|---|
| ![Simulator Screenshot - iPhone 15 Pro - 2024-06-28 at 14 42 21](https://github.com/artsy/eigen/assets/3934579/4319692e-873b-4171-a6b4-2bf26d23d6e0) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-28 at 14 42 52](https://github.com/artsy/eigen/assets/3934579/f6536c01-83dd-45cc-9842-b122adaa476d) |
-
-
-
- chore: remove unused home module Meet Your Advisor - @nickskalkin 
</details>
[docs]: …

chore: remove unused home module Meet Your Advisor

---

src/app/Scenes/Collection/Collection.tsx

This PR resolves [this bug report](https://artsy.slack.com/archives/C03N12SR0RK/p1719942428131239)
Replaces the hard-coded title in the sticky header with the collection's actual `title` attribute.
https://github.com/artsy/eigen/assets/140521/8be664df-32d1-41b6-90c3-f5e9280da77d
- Fix incorrect title on collection screen - roop
-
-
-
</details>

fix: hard-coded collection title

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFromMyCollection.tests.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFromMyCollectionArtworks.tsx
src/app/store/config/features.ts

**Context:** [Slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1719218590850099?thread_ts=1718205379.558919&cid=C05EQL4R5N0) 🧵
This PR addresses the latest design comments on Submit Artwork from My Collection. I also had to remove the stuff that we built before and we no longer want
___
**Screenshot**
-
-
-
-
</details>

chore: address design comments on submit artwork from my collection

---

ReactotronConfig.js
package.json
src/app/App.tsx
yarn.lock

This PR resolves [PHIRE-1039] 
Adds [reactotron ](https://github.com/infinitered/reactotron) as a dev dependency since react native is going to [decouple flipper](https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0641-decoupling-flipper-from-react-native-core.md) from the next major release.
-
-
-
- introducing reactotron dev dependency - gkartalis
</details>
[PHIRE-1039]: https://artsyproduct.atlassian.net/browse/PHIRE-1039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

feat(debugging): introducing reactotron dev dependency

---

.circleci/config.yml

This reverts commit bdbc3c44eba99b4439eaa88972647f131c775880.
Reverting the bump that broke android betas
-
-
-
- revert bump android cimg docker tag - gkartalis
</details>

chore(REVERT-deps): update cimg/android docker tag to v2024.07.1

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
src/app/store/config/features.ts

This PR resolves [ONYX-1124] 
This PR retires `AREnableSaveAndContinueSubmission` feature flag
-
-
-
- retire AREnableSaveAndContinueSubmission feature flag - mounir
</details>
[ONYX-1124]: https://artsyproduct.atlassian.net/browse/ONYX-1124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: retire AREnableSaveAndContinueSubmission

---

src/app/utils/PushNotification.ts

@dariakoko noticed [this issue](https://artsy.slack.com/archives/C02BAQ5K7/p1720769912001969) bubbling up in sentry and we decided to add a try catch block and an info level captureMessage to prevent bubbling the error this way and have a less scary error message.
-
-
-
- handle error when saving push notification token - darianorge
</details>

chore: handle error when saving push notification token

---

src/app/Components/Bidding/Screens/CreditCardForm.tsx
src/app/Components/CreditCardField/CreditCardField.tsx
src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx

**[Future Friday]**
This PR updates the credit card input component to use the new input component design
https://github.com/user-attachments/assets/e406a996-2a50-4975-b652-99f27aabc4f7
**Note:** I am hiding the credit card label when the input is focused because - one, we don't have access to the tapable area in the input, so I couldn't make the entire label clickable. 2 - Because we would be intersecting touches, the user might end up having the month/year input activated instead of the number. I know this is not 100% ideal but it's better than what we have now.
- update credit card input component - mounir
-
-
-
</details> …

feat: update credit card input component

---

fastlane/Fastfile

Missed a spot after removing jetifier package
#nochangelog
-
-
-
-
</details>

fix(releases): remove missed jetifier call #trivial

---

src/app/store/config/features.ts

This PR relates to [EMI-1966]
#minor #squashongreen
This PR creates the following feature flags for collector signals:
- AREnablePartnerOfferSignals
- AREnableAuctionImprovementsSignals
- New feature flags for collector signals
</details>
[EMI-1966]: https://artsyproduct.atlassian.net/browse/EMI-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-1966): create feature flags for collector signals

---

android/gradle.properties

Follow up from https://github.com/artsy/eigen/pull/10485 bumps gradle memory
#nochangelog

chore: bump gradle memory

---

docs/deploy_a_hotfix.md

Updates codepush docs with some gotchas I ran into on the latest hotfix. 
-
-
-
- codepush doc updates - brian 
</details>

chore(docs): codepush doc updates #trivial

---

src/app/AppRegistry.tsx
src/app/Components/LegacyTabs/LegacyNavigationalTabs.tsx
src/app/Components/ReadMore.tsx
src/app/Scenes/Fair/Components/FairArtworks.tsx
src/app/Scenes/Fair/Components/FairExhibitors.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/Fair/FairMoreInfo.tsx

Since we have a major upcoming fair - I thought it's about time to fix the issues in the screen as well as allow users to share the fair link. Below is a list of changes:
- Fix broken tap on **Read more**
- Add Share fair URL
- Fix broken padding between sections
- Remove additional separator 
- Add `nestedScrollEnabled` for a small performance improvements (I doubt it will be noticeable but better have it than not)
- Align sort and filter experience with other screens (show number of artwork in bold instead of `Showing X artwork`)
- Use `Screen` component in both `Fair` and `FairInfo`screens.
- Fix back button covering content in both `Fair` and `FairInfo` screens
| <Video …

chore: fair screen fixes

---

src/app/Scenes/MyAccount/updateMyUserProfile.ts
src/app/Scenes/MyProfile/Components/UserProfileFields.tsx
src/app/Scenes/MyProfile/MyProfileEditForm.tsx

Before we didn't allow the users to clean up their location, this PR enables that.
https://github.com/user-attachments/assets/7a465589-95ff-478e-b0b7-b24590da8282
- fix: allow collectors to clean up their location - araujobarret
-
-
-
</details>

fix(AccountSettings): allow user to clear their location

---

src/app/Components/ArtworkFilter/useArtworkFilters.ts
src/app/Scenes/Fair/Components/FairArtworks.tsx
src/app/Scenes/Fair/Components/FairEditorial.tsx
src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
src/app/Scenes/Fair/Components/FairHeader.tsx
src/app/Scenes/Fair/Components/FairTiming.tsx
src/app/Scenes/Fair/Fair.tests.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/Fair/FairAllFollowedArtists.tests.tsx
src/app/Scenes/Fair/FairAllFollowedArtists.tsx
src/app/Scenes/Fair/FairArtworks.tests.tsx
src/app/Scenes/Fair/FairHeader.tests.tsx
src/app/Scenes/Fair/FairOverview.tests.tsx
src/app/Scenes/Fair/FairOverview.tsx
src/app/Scenes/VanityURL/VanityURLEntity.tests.tsx
src/app/Scenes/VanityURL/VanityURLEntity.tsx

This PR refactors the Fair and FairFollowedArtists screens, which the 1st was breaking on Android and supper laggy to incorporate the new Masonry element as a grid viewer. The refactoring on the 2nd screen was necessary because it used the fragment container from the 1st screen.
The 1st commit contains the refactor and the 2nd is the pulling of #10504 adapted to the refactor.
There are follow-ups to be made re polishing the UI, and some shifting happening around but we should prioritize shipping this boost, especially because of the crashes, and to work on them later.
<details>
<summary>Android</summary>
https://github.com/user-attachments/assets/e017d029-05e0-4f0f-a6e8-da8995ec08db
</details>
<details>
<summary>iPhone</summary>
https://github.com/user-attachments/assets/536d2637-f3a0-41da …

refactor(Fair): Add Masonry to the Fair and FairFollowedArtists screen

---

src/app/AppRegistry.tsx

This PR fixes the issue of the hidden top navigation on Android on register to bid modal
- do not hide register to bid modal on android - mounir
-
-
-
</details>

fix: do not hide register to bid modal on android

---

src/app/AppRegistry.tsx
src/app/Scenes/Fair/Components/FairExhibitors.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/VanityURL/VanityURLEntity.tsx

Fixes:
1. broken exhibitors scroll
|Before|After|
|---|---|
|<video width={400} src="https://github.com/user-attachments/assets/3aa68cb2-f061-42e5-8c8b-d6e2de2cfc84" />|<video width={400} src="https://github.com/user-attachments/assets/14c2adda-22b8-4bf8-a37b-87eb67f8ee34" />|
3. FetchQuery vs LazyLoad
|Before|After|
|---|---|
|<video width={400} src="https://github.com/user-attachments/assets/36d9a134-84cb-430a-9e4d-82335ca7e6fd" />|<video width={400} src="https://github.com/user-attachments/assets/34a6a534-3f1e-4520-964c-00cf7cc175af" />|
- fair exhibitors scroll fix + perf improvements - gkartalis
-
-
-
</details> …

fix: fair exhibitors

---

ios/Artsy/App/ARAppNotificationsDelegate.m

Fixes braze push notifications not properly deeplinking, looking at the docs it is not clear that this is required but the openURL app delegate call is not being called without this so deeplinks are not happening from braze. 
https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/advanced_use_cases/linking/
-
- fix braze deeplinks from push - brian 
-
-
</details>

fix: broken braze push deeplinks

---

data/schema.graphql
src/app/AppRegistry.tsx
src/app/Scenes/Home/HomeContainer.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/ArtworksRailHomeViewSection.tsx
src/app/Scenes/HomeView/Sections/GenericHomeViewSection.tsx
src/app/Scenes/HomeView/Sections/NewWorksForYouSection.tsx
src/app/Scenes/HomeView/Sections/Section.tsx
src/app/store/config/features.ts

Depends on https://github.com/artsy/metaphysics/pull/5865
This is a small proof of concept to validate how easy it is to add (in this case reuse) components to the new home view. I've mostly re-used existing [NewWorksForYouRail](https://github.com/artsy/eigen/blob/main/src/app/Scenes/Home/Components/NewWorksForYouRail.tsx) (removed some code for simplicity, but maybe it should be brought back).
TODO:
#nochangelog
</details>

feat: add New Works for You (and potentially other artwork-based rails) to new home view screen

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkProgressBar.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts

- update SWA tier 2 - thank you screen copy - mounir
-
-
-
</details>

chore: update thank you screen copy

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/Section.tsx

This PR resolves [ONYX-1168] 
This PR adds pagination to the new home view
Please be mindful that the skeletons **will** change, I didn't factor that in mind in this PR
https://github.com/user-attachments/assets/e312a702-a484-4d6c-849f-57cf1c35399c
- paginate the home view - mounir
-
-
-
</details>
[ONYX-1168]: https://artsyproduct.atlassian.net/browse/ONYX-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-1168): paginate the home view

---

src/app/AppRegistry.tsx
src/app/Components/ArtworkFilter/FilterModal.tests.tsx
src/app/Scenes/Collection/Collection.tests.tsx
src/app/Scenes/Collection/Collection.tsx
src/app/Scenes/Collection/CollectionOverview.tsx
src/app/Scenes/Collection/Screens/CollectionArtworks.tests.tsx
src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
src/app/Scenes/Collection/Screens/CollectionHeader.tests.tsx
src/app/Scenes/Collection/Screens/CollectionHeader.tsx

Refactors Collections screen to use `Tabs.Masonry` implementation.
Also moves the description featured artists and linked collections to an overview tab and adds an artwork tab for the artworks to be more performant
- refactor collections page to use performant tabs.masonry - gkartalis
-
-
-
</details>

refactor(Masonry): refactor collections page to use performant tabs.masonry

---

package.json
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
yarn.lock

- Related Cohesion PR: https://github.com/artsy/cohesion/pull/517
Add screen tracking to Sell flow completed step.
-
-
-
- Add screen tracking to the Sell flow's "Thank You" step - ole
</details>

chore: Add screen tracking to Sell flow completed step

---

src/app/Scenes/Collection/Collection.tsx

This PR resolves [bug fix] 
Rollback the overview tab for collections
-
-
-
- overview tab fixes - egdbear
</details>

fix: rollback overview tab for collections

---

ios/Podfile.lock
package.json
patches/react-native-image-crop-picker+0.41.2.patch
yarn.lock

This PR resolves [PHIRE-627] 
Bumps react-native-image-crop-picker from 0.40.3 to 0.41.2.
This would theoretically solve the [PHIRE-627] ticket.
@brainbicycle if you have time could we pair on trying to repro the issue on your device to see if it was solved (in my device/emulator it wasn't reproducible)
-
-
-
- react-native-image-crop-picker from 0.40.3 to 0.41.2 - gkartalis
</details>
[PHIRE-627]: https://artsyproduct.atlassian.net/browse/PHIRE-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

build(deps): bump react-native-image-crop-picker from 0.40.3 to 0.41.2

---

src/app/Scenes/MyCollection/Components/SubmissionStatus.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmissionStatus.tests.tsx

Addresses [Notion card](https://www.notion.so/artsy/App-Web-listed-status-does-not-show-up-correctly-57fd57c86b8c427eb209f8fc049407bb?pvs=4) - listed status does not show up correctly
| Before | After | 
| --- | --- |
| ![IMG_4224 PNG](https://github.com/user-attachments/assets/35e34131-9f7b-4e72-844b-f2bf08b14d4c) | ![image](https://github.com/user-attachments/assets/fdcccf7d-b6ad-41af-bae6-72d4033dcf4b) |
- fix listed status does not show up correctly - daria
-
-
-
</details>

fix: adjust action label data when listed

---

src/app/Scenes/MyCollection/Components/SubmissionStatus.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
src/app/utils/refreshHelpers.tsx

Refresh MyCollection Artwork after submitting new data
Resolves [Notion ticket](https://www.notion.so/artsy/App-Submission-status-not-updated-post-submission-I-needed-to-refresh-5089c26a3cf1446f9995e753d3076913?pvs=4) (Submission status not updated post-submission ⇒ I needed to refresh)
https://github.com/user-attachments/assets/6ac8f780-c514-4e27-aafc-864c6269eae3
- Refresh MyCollection Artwork after submitting new data -daria
-
-
-
</details>

feat: add MyCollectionArtwork refresh method

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/updateMyCollectionArtwork.ts
src/app/utils/refreshHelpers.tsx

Revert https://github.com/artsy/eigen/pull/10567 as there was already a method to update MyCollection Artwork details
-
-
-
-
</details>

fix: spread fragment to update mycollection artwork

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCondition.tsx

Resolves:
[Notion card](https://www.notion.so/artsy/app-web-The-edit-artwork-CTA-needs-to-be-removed-for-any-myC-artworks-that-are-submitted-for-sale-da171fb6b103459aaa1d6ac91c1fa0e8?pvs=4): remove the edit artwork CTA for any myC artworks that is submitted for sale
[Notion card](https://www.notion.so/artsy/App-Lorem-Ipsum-copy-on-submit-artwork-condition-d234d1023d044ec6b72d459f3222aff2?pvs=4): edit copy on the condition screen
- remove the edit artwork CTA for any myC artworks that is submitted for sale, edit copy on the condition screen -daria
-
-
-
</details> …

chore: hide edit button for submissionsm update condition copy

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts

Resolves https://www.notion.so/artsy/App-upload-of-documents-is-mandatory-in-the-app-but-should-not-be-446a60bc8b3c499baed53489572f478f?pvs=4 
This makes adding additional documents optional in the new Sell flow.
- Make additional documents optional in Sell flow (behind ff) - ole
-
-
-
</details>

fix: Make additional documents optional in Sell flow

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx

This PR resolves [] ### Description
https://github.com/user-attachments/assets/c51df2a6-6d21-472c-bde0-cec20e65203f
- add pull to refresh support in my collection artwork screen - mounir
-
-
-
</details>

chore: support pull to refresh in my collection artwork

---

src/app/store/config/features.ts

Toggles the AREnableNewCollectorSettings as readyForRelease. 
- feat: turns on the ff AREnableNewCollectorSettings - araujobarret
-
-
-
</details>

feat(CollectorProfile): toggle AREnableNewCollectorSettings feature flag

---

babel.config.js
package.json
yarn.lock

Removes console logs from production builds. We keep the console.errors for sentry though - might need to revisit if we use for sentry console.log instead of console.error in some places. Will probably do it on a follow up commit in the same PR.
We expect to see really minor performance improvements from this one but not sure how to measure it.
It's an industry standard though so we should do this.
-
-
-
- remove console logs from prod builds - gkartalis
</details>

build(logs): remove console logs from prod builds

---

dangerfile.ts

This PR skips the check for changelog in the PR description if the PR is a draft
-
-
-
- skip danger changelog check for draft PRs - mrsltun
</details>

fix(FF): Skip Changelog check for draft PRs

---

.secrets.baseline
src/app/Components/Home/ArtistRails/ArtistCard.tests.tsx
src/app/Components/Home/ArtistRails/ArtistCard.tsx
src/app/Components/Home/ArtistRails/RecommendedArtistsRail.tests.tsx
src/app/Components/Home/ArtistRails/RecommendedArtistsRail.tsx
src/app/Components/PrefetchFlatList.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/ArtistsRailHomeViewSection.tsx
src/app/Scenes/HomeView/Sections/Section.tsx

This PR resolves [ONYX-1167] 
This PR adds the artists generic rail to `Section`. This rail's goal is to render `ArtistsRailHomeViewSection`.
https://github.com/user-attachments/assets/f35cda56-9c0b-4083-9478-4ca6e4269723
-
-
-
-
</details>
[ONYX-1167]: https://artsyproduct.atlassian.net/browse/ONYX-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add home view artists rail

---

src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx

This PR fixes an issue with the switching from List to Grid view
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/83b65914-7206-455b-9979-f5edd3d3b1e2" /> | <video src="https://github.com/user-attachments/assets/ffc04ac9-c9b4-4eea-84e9-52c509bf2d2d" /> |
| iOS | <video src="https://github.com/user-attachments/assets/3fda00bb-febc-4688-b730-cd3afb510e58" /> | <video src="https://github.com/user-attachments/assets/f5bb7711-9e31-4b9d-875c-5a8915f15617" /> |
- Fix the issue when switching from artwork grid to list view - mrsltun
-
-
-
</details> …

fix(FF): Switching from Grid to List is not working properly

---

src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx

This PR updates the MyProfileSettings test to stop breaking in `main`
-
-
-
- Update MyProfileSettings tests - mrsltun
</details>

fix: Update MyProfileSettings tests

---

src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx

This PR fixes the unstable `InquiryModal` tests.
-
-
-
- fix unstable inquiry modal test - mounir
</details>

fix: unstable inquiry modal test

---

renovate.json
src/app/Scenes/MyProfile/MyProfilePayment.tsx

Ignore ci image updates for android, this has broken ci a few times now, let's upgrade manually.
-
-
-
- ignore android ci image updates - brian, george
</details>

chore(ci): ignore ci android images in renovate

---

.circleci/config.yml
src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx

This reverts commit c6823e7144731235ee75e194bd0283b11fd6ce21.
Reverts ci update from renovate that broke android builds.
-
-
- 
- revert android ci update, comment flaky test - brian 
</details>

fix(ci): revert android ci update

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx

Resolves https://www.notion.so/artsy/Web-Fulfil-or-Fulfill-f36f9af164cb4f59956b325a52a74511?pvs=4
`fulfil` -> `fulfill`.
-
-
-
-
</details>

fix: fulfil to fulfill

---

.circleci/config.yml

Temporary disables failing maestro jobs that prevent the nightly betas from suceeding
-
-
-
- disable maestro nightly builds. - gkartalis
</details>

build(maestro): disable maestro builds for a bit

---

src/app/Scenes/Home/Components/HeroUnitsRail.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/HeroUnitsRailHomeViewSection.tsx
src/app/Scenes/HomeView/Sections/Section.tsx

This PR resolves [ONYX-1188]
Adds hero units section:
Blocked by https://github.com/artsy/metaphysics/pull/5906
-
-
-
-
</details>
[ONYX-1188]: https://artsyproduct.atlassian.net/browse/ONYX-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1188): add hero units to new home view screen

---

src/app/system/relay/middlewares/checkAuthenticationMiddleware.ts

This PR resolves [PHIRE-1102] 
Removes remove erroneous network unavailable alert since it is not working properly and it is lying 🤥
- remove network problem alert in checkAuthenticationMiddleware - gkartalis
-
-
-
</details>
[PHIRE-1102]: https://artsyproduct.atlassian.net/browse/PHIRE-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove network problem alert in checkAuthenticationMiddleware

---

src/app/Components/Select/Components/SelectButton.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx

Resolves [Notion card](https://www.notion.so/artsy/App-what-s-is-this-hitslop-too-small-it-s-hard-to-tap-e1874cddddb94f13beed601521a2572c?pvs=4): Add `hitSlop` to `What's this?` link
- Add hitSlop to What's this? link -daria
-
-
-
</details>

chore: add hitslop to whats this link

---

src/app/Scenes/MyCollection/Components/SubmissionStatus.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCondition.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmissionStatus.tests.tsx

Addresses:
1. [‘Submission Unsuccessful’ should not appear on the grid.  This is so a user is not stuck with negative messaging if they want to share MyC](https://www.notion.so/artsy/Submission-Unsuccessful-should-not-appear-on-the-grid-This-is-so-a-user-is-not-stuck-with-negativ-fffcab0764a08098afddd316e2c3eb96?pvs=4)
2. [Body copy should be SM Text (line height 26px)](https://www.notion.so/artsy/Body-copy-should-be-SM-Text-line-height-26px-0ba4727b87504865bba230ce61f3cfe6?pvs=4)
3. [‘Complete Listing’ should be same weight as the text above](https://www.notion.so/artsy/Complete-Listing-should-be-same-weight-as-the-text-above-87d917e01c6e411ea0c5328d924e6609?pvs=4)
4. [Body copy should be ‘Core sm text’ (line height 26px). Currently it is too tight …

fix: UI bugs on the submission flow

---

src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggest.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggestItem.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggestListHeader.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPrompt.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPromptBody.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPromptFooter.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/__tests__/MyCollectionArtistsAutosuggest.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/__tests__/MyCollectionArtistsAutosuggestItem.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/__tests__/MyCollectionArtistsAutosuggestListHeader.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/__tests__/MyCollectionArtistsPromptFooter.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistsPrompt.tsx
src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsStore.tsx
src/app/Scenes/MyCollection/hooks/useAddUserInterestArtists.ts
src/app/Scenes/MyCollection/hooks/useCreateArtists.ts
src/app/Scenes/MyCollection/hooks/useSubmitMyCollectionArtists.ts
src/app/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
src/app/utils/ArtworkInquiry/ArtworkInquiryTypes.ts

This PR resolves [DIA-717] 
This PR introduces the Collected Artists prompt, which has not yet been wired up to any screens.
Main changes:
- Adds the BottomSheet prompt to Eigen 
- reuses some areas from Collected Artists 
- refactors the Collected Artists logic to share the code with the prompt
Android:
https://github.com/user-attachments/assets/05c8666b-fb31-41fc-affb-aafb79f2afd9
iOS 
https://github.com/user-attachments/assets/2ebe3b5e-3179-48c5-888c-983a88c5731f
- feat: add collected artists prompt(not wiring it to any screen yet) - araujobarret
-
-
-
</details> …

feat: add add my collection artists prompt

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFrameInformation.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx

[Adjust padding and text size on the submission flow](https://www.notion.so/artsy/Radio-buttons-copy-should-be-16px-Save-Exit-copy-should-be-13px-Also-different-padding-between--804c3d02e8f04e198b270be740b594f6?pvs=4) 
- [] I have tested my changes on **iOS** and **Android**.
- adjust padding and text size on the submission flow -daria
-
-
-
</details>

fix: adjust padding and text size

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhoneNumber.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddTitle.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAdditionalDocuments.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCondition.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFrameInformation.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkShippingLocation.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkStartFlow.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts
src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/useSubmissionContext.ts
src/app/Scenes/SellWithArtsy/Hooks/useSubmitArtworkTracking.ts

Resolved [Notion card](https://www.notion.so/artsy/App-When-we-click-on-Add-Additional-Information-events-for-all-previous-screens-are-fired-d8cec042ab2044e99845e85bcf15cea1?pvs=4): When we click on Add Additional Information, events for all previous screens are fired
Track every screen using UseEffect
https://github.com/user-attachments/assets/93001122-63e7-4cc4-8944-90f1e568a0c6
- fix screens tracking on submission flow -daria
-
-
-
</details>

fix: fix screens tracking on submission flow

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/store/config/features.ts

This PR resolves [EMI-2019] 
Similar to https://github.com/artsy/force/pull/14338
For displaying the expired offer banner, instead of not getting a partner offer in the backend response and assuming that the partner offer is expired, we can return the partner offer and show the banner if it's not available. This would cover the case when a user is logged in with a different user.
- Fix check for partner offer expiration - leamotta
-
-
-
</details>
[EMI-2019]: …

fix(EMI-2019): check if offer is expired

---

src/app/store/config/features.ts

Mark collection without header as ready for release
#nochangelog

chore: mark collection without header as ready for release

---

src/app/store/config/features.ts

This PR marks `AREnablePartnerOfferSignals` as `readyForRelease` 
-
-
-
- mark AREnablePartnerOfferSignals as ready for release - mrsltun
</details>

chore: Mark AREnablePartnerOfferSignals as readyForRelease

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkRail/LargeArtworkRail.tsx
src/app/Components/ArtworkRail/SmallArtworkRail.tsx
src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tsx
src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
src/app/Scenes/Fair/FairExhibitorRail.tests.tsx
src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/Home/homeAnalytics.ts
src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx

This PR resolves [EMI-2025] 
This PR adds tracking for Limited-Time Offer signal tracking
⚠️ It also updates some of the deprecated tracking functions for artwork grid item
Please let me know if you have any concerns or questions about my code, naming, or ways of adding fields :) 
-
-
-
- Update tracking for artwork taps + add tracking for Limited-Time Offer signals - mrsltun
</details>
[EMI-2025]: https://artsyproduct.atlassian.net/browse/EMI-2025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

chore(EMI-2025): Add tracking for Limited-Time Offer signals

---

src/app/store/config/features.ts

Mark expired partner offers as ready for release
#nochangelog

chore: mark expired partner offers ready for release

---

src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx

This PR resolves [EMI-2019] 
Follow up for #10607 
- Check that partner offer is active for make offer button - leamotta
-
-
-
</details>
[EMI-2019]: https://artsyproduct.atlassian.net/browse/EMI-2019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2019): check if partner offer is active for make offer button

---

src/app/Scenes/MyProfile/MyProfileHeader.tsx

Keep the icon size consistent with the rest of the icons.
Before
https://github.com/user-attachments/assets/186fceda-21a4-41da-b4c7-f323075439bb
After
https://github.com/user-attachments/assets/5b30ce1f-ae78-4c37-bbeb-026fda64fb10
- fix: adjust settingsIcon size on Profile screen - araujobarret
-
-
-
</details>

fix(CollectorProfile): adjust settingsIcon size on profile screen

---

src/app/store/config/features.ts

Resolves https://www.notion.so/artsy/Post-approval-Sell-flow-feature-flag-is-not-enabled-in-Eigen-which-is-needed-to-make-it-ready-for-t-5fa786c470c74012a82c4c4baf8cd0ee?pvs=4
- Echo PR: https://github.com/artsy/echo/pull/661
Make AREnableSubmitArtworkTier2Information ready for release.
-
-
-
-
</details>

chore: Mark AREnableSubmitArtworkTier2Information as ready for release

---

src/app/Scenes/CompleteMyProfile/ChangesSummary.tsx

This PR resolves [DIA-803] 
The link was using the wrong route, it should have redirected the collectors to the collected artists' screen. This PR fixes it with the right route.
https://github.com/user-attachments/assets/f946527a-60a2-484e-83bd-6268b7e3c71c
- fix: summary screen link to collected artists screen - araujobarret
-
-
-
</details>
[DIA-803]: https://artsyproduct.atlassian.net/browse/DIA-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-803): navigation to collected artists during complete my profile

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts

This PR fixes the broken progress percentage post submission
- Fix broken progress bar on complete your submission - mounir
-
-
-
</details>

fix: broken progress percentage post submission

---

src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/CompleteProfilePrompt.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/app/Scenes/Artwork/Components/PartnerCard.tests.tsx
src/app/Scenes/Artwork/Components/PartnerCard.tsx
src/app/Scenes/Artwork/Components/Questions.tests.tsx
src/app/Scenes/Artwork/Components/Questions.tsx
src/app/Scenes/Artwork/Components/ShortContactGallery.tsx
src/app/Scenes/Artwork/hooks/__tests__/useSendInquiry.tests.tsx
src/app/Scenes/Artwork/hooks/useSendInquiry.ts
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPromptBody.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPromptFooter.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/__tests__/MyCollectionArtistsPromptFooter.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistsPrompt.tsx
src/app/Scenes/MyProfile/MyProfileEditModal.tsx
src/app/Scenes/MyProfile/useUpdateUserProfileFields.tsx
src/app/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
src/app/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
src/app/utils/collectorPromptHelpers.tests.ts
src/app/utils/collectorPromptHelpers.ts
src/app/utils/mutations/useUpdateCollectorProfile.ts
src/app/utils/tests/collectorPromptHelpers.tests.ts

This PR resolves [DIA-707]
Continuing of the prompt work, after inquiring on an Artwork if the collector hasn't been prompted in the last 30 days and has no items in his collection, we show the prompt.
Main changes:
- refactored the InquiryModal to be simpler by using the hook to control its behavior isolatedly(easier to test and read)
- changed the order of the prompts(agreed with the product) now we show the edit profile prompt before the collection(it's easier for the collector to fill in their information rather than initially having a collection)
https://github.com/user-attachments/assets/ae887f90-e87d-4f22-b53d-5fbbd6bd2df1
- feat: wire collected artists prompt to inquiry(ff hidden) - araujobarret
-
-
-
</details>
Need help with …

feat(DIA-707): wire up collected artists prompt to inquiry

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts

Resolves [Notion card](https://www.notion.so/artsy/progress-bar-is-not-at-100-after-completing-SWA-flow-Tier-1-and-Tier-2-9785c0c4ae524843924a6ab634adb733?pvs=4): progress bar is not at 100% after completing SWA flow
Follow-up on [PR](https://github.com/artsy/eigen/pull/10637)
| --- | --- |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-08-22 at 14 36 44](https://github.com/user-attachments/assets/fd9f0363-d723-4402-902d-c0af0dcd25de) | ![Simulator Screenshot - iPhone 15 Pro - 2024-08-22 at 14 36 00](https://github.com/user-attachments/assets/551c287b-7688-4ad9-a9b6-0077ca0f1a02) |
-
-
-
-
</details> …

fix: broken progress percentage approved submission

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/ArticlesRailHomeViewSection.tests.tsx
src/app/Scenes/HomeView/Sections/ArticlesRailHomeViewSection.tsx
src/app/Scenes/HomeView/Sections/Section.tsx

This PR resolves [ONYX-1214] 
This PR adds the latest articles rail to the home view. We worked on this during KS before I went on holidays.
Co-authored by: @gkartalis @araujobarret  @olerichter00 @MrSltun
Related MP PR: https://github.com/artsy/metaphysics/pull/5904
-
-
-
-
</details>
[ONYX-1214]: https://artsyproduct.atlassian.net/browse/ONYX-1214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add latest articles section

---

src/app/Components/Bidding/Components/PaymentInfo.tests.tsx
src/app/Components/Bidding/Components/PaymentInfo.tsx
src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
src/app/Components/Bidding/Screens/CreditCardForm.tests.tsx
src/app/Components/Bidding/Screens/CreditCardForm.tsx
src/app/Components/Bidding/Screens/Registration.tests.tsx
src/app/Components/Bidding/Screens/Registration.tsx
src/app/Components/Bidding/Utils/creditCardFormFields.ts
src/app/Components/Bidding/Validators/creditCardFormFieldsValidationSchema.ts
src/app/Components/Stack.tsx
src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx

This PR refactors the credit card form in the Auction registration to include the Billing Address, which is needed when creating a token with Stripe
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/d76cac6d-c2ec-4d4a-a4f8-e813218e951a" /> | <video src="https://github.com/user-attachments/assets/3f36c96f-eef6-4623-b5f1-924e76a3e800" /> |
| iOS | <video src="https://github.com/user-attachments/assets/ce7abe69-c471-4a11-b31b-36589f8f172f" /> | <video src="https://github.com/user-attachments/assets/b849bbbe-691b-4fcb-9b6b-26fdf40d9954" /> |
- refactor credit card form in auction registration - mrsltun
-
-
-
</details>
Need help with something? Have a look at our [docs], or …

fix: refactor CreditCardForm for auction registration

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/FairRailItem.tsx
src/app/Scenes/HomeView/Sections/MarketingCollectionRailItem.tsx
src/app/Scenes/HomeView/Sections/MarketingCollectionsRailHomeViewSection.tsx
src/app/Scenes/HomeView/Sections/Section.tsx

This PR resolves [ONYX-1219]
Do not merge until https://github.com/artsy/metaphysics/pull/5934 is merged!
#nochangelog
</details>
[ONYX-1219]: https://artsyproduct.atlassian.net/browse/ONYX-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1219): add Collections home view rail

---

src/app/Components/CreditCardField/CreditCardField.tsx

This PR shows the user input for the credit card field
>[!NOTE]
> This issue happens only on iOS
|---|---|
| <video src="https://github.com/user-attachments/assets/b103f317-b9c1-41e0-9612-4241f239b7a3" /> | <video src="https://github.com/user-attachments/assets/d2c25ee8-7ad0-49c4-aa1b-9a793124b086" /> |
-
- Show credit card input when the device is on Dark Mode - mrsltun
-
-
</details>

fix: Show user input inside credit card field

---

src/app/Scenes/Home/Components/ShowsRail.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/Section.tsx
src/app/Scenes/HomeView/Sections/ShowsRailHomeViewSection.tests.tsx
src/app/Scenes/HomeView/Sections/ShowsRailHomeViewSection.tsx

This PR resolves [ONYX-1225]
This PR adds Shows for You rail to the new schema. We agreed to not add full Metaphysics support for this section (basically skip adding showsConnection). In this particular case it was very convenient to reuse existing component.
-
-
-
-
</details>
[ONYX-1225]: https://artsyproduct.atlassian.net/browse/ONYX-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1225): add Shows for You home view section

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/Section.tsx
src/app/Scenes/HomeView/Sections/ViewingRoomsRailHomeViewSection.tests.tsx
src/app/Scenes/HomeView/Sections/ViewingRoomsRailHomeViewSection.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx

This PR resolves [ONYX-1232] 
Blocked by https://github.com/artsy/metaphysics/pull/5942
This PR adds the viewing rooms rail to the home view section
https://github.com/user-attachments/assets/843f0518-600b-459b-be44-e334d2da7120
- Add viewing rooms rail - mounir
-
-
-
</details>
[ONYX-1138]: https://artsyproduct.atlassian.net/browse/ONYX-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-1232]: https://artsyproduct.atlassian.net/browse/ONYX-1232?atlOrigin=e …

feat: add viewing rooms home view section

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/ArticlesCardsHomeViewSection.tests.tsx
src/app/Scenes/HomeView/Sections/ArticlesCardsHomeViewSection.tsx
src/app/Scenes/HomeView/Sections/Section.tsx

This PR resolves [ONYX-1238] 
Depends on https://github.com/artsy/metaphysics/pull/5946
This adds the News card to the new home view:
https://github.com/user-attachments/assets/426a5844-1da5-45f5-9832-16f7a59b2c2b
There are some TODOS in the code to indicated follow-ups re: view-all behavior
- Add news card to home view - roop
-
-
-
</details>
[ONYX-1238]: https://artsyproduct.atlassian.net/browse/ONYX-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add News home view section

---

src/app/Scenes/Activity/ActivityContent.tsx
src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/Activity/components/CollectorProfilePrompt.tsx
src/app/Scenes/Activity/components/CollectorUpdateNotification.tsx
src/app/Scenes/Activity/components/ExpiresInTimer.tsx
src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
src/app/Scenes/Activity/components/__tests__/CollectorUpdateNotification.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/app/Scenes/Home/Components/ActivityRailItem.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPromptFooter.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/__tests__/MyCollectionArtistsPromptFooter.tests.tsx

This PR resolves [DIA-696] [DIA-703] [DIA-708] [DIA-710]
This PR implements the Activity Items for the collector profile update notifications.
https://github.com/user-attachments/assets/9ca13dfc-71c7-4251-a851-32bfdbfe4995
- feat: add activity items given collector update notifications - araujobarret
-
-
-
</details>
[DIA-696]: https://artsyproduct.atlassian.net/browse/DIA-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIA-708]: …

feat: add activity card for collector update notification

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx

The "Save & Exit" text was too small, it has to be `sm`
- fix Save & Exit text variant on the submission flow top navigation component -daria 
-
-
-
</details>

fix: fix Save & Exit text variant

---

src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx

This is a follow-up on #10669 
This PR updates the watchers text to be plural if the count is more than 2
- update watchers string in Artwork screen to be plural if count is more than 2 - mrsltun 
-
-
-
</details>

fix: update watchers pluralization in Artwork screen

---

ios/Artsy/App/ARAppNotificationsDelegate.m

Fixes a tracking issue with braze push notifications not including urls due to different format. 
-
- 
-
- fix braze push tracking to include url - brian 
</details>

fix: braze push tracking not including url

---

src/app/store/config/features.ts

Release the collector prompts
- feat: release the AREnableCollectorProfilePrompts - araujobarret
-
-
-
</details>

feat(Prompt): release AREnableCollectorProfilePrompts

---

src/app/Scenes/Search/SearchArtworksContainer.tests.tsx
src/app/__fixtures__/ArtworkFixture.ts

This PR fixes broken tracking tests after releasing Limited-Time Offer 
#nochangelog

fix: Update broken Collector Signals tracking tests

---

src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
src/app/Scenes/Search/SearchArtworksContainer.tests.tsx

This PR fixes another test 😅 
#nochangelog

chore: fix broken tests

---

src/app/store/config/features.ts

This PR marks the feature flag `AREnableAuctionImprovementsSignals` as `readyForRelease`
-
-
-
- mark AREnableAuctionImprovementsSignals as ready for release - mrsltun
</details>

chore: mark AREnableAuctionImprovementsSignals feature flag as ready for release

---

src/app/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tests.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesHeader.tests.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesMeta.tests.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tests.tsx

This PR fixes broken type checks
It also refactors few tests to be aligned with eslint rules
#nochangelog

chore: fix broken typechecks

---

src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx

This PR resolves [EMI-2050] 
Replace watch lot icon with heart icon
I am not hiding this change behind a feature flag as it is not directly dependent on the main work on [the feature](https://artsyproduct.atlassian.net/browse/EMI-1933) and can be released separately
- replace watch lot icon with heart icon -daria
-
-
-
</details>
[EMI-2050]: https://artsyproduct.atlassian.net/browse/EMI-2050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2050): replace watch lot icon with heart icon

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/constants.ts

This PR resolves [EMI-2051] 
| --- | --- | 
| ![Simulator Screenshot - iPhone 15 Pro - 2024-09-04 at 13 50 46](https://github.com/user-attachments/assets/8bc39355-e017-49cb-a2b4-2904667424c6)| ![Simulator Screenshot - iPhone 15 Pro - 2024-09-04 at 13 51 28](https://github.com/user-attachments/assets/c2aed179-00d6-4c62-9ffc-85f616d571e5) |
- adjust icon size on artwork rail card component -daria
-
-
-
</details>
[EMI-2051]: https://artsyproduct.atlassian.net/browse/EMI-2051?atlOrigin=eyJpIjo …

fix(EMI-2051): adjust icon size on artwork rail card component

---

src/app/Scenes/Inbox/Components/Conversations/Conversations.tsx

This PR updates the check on `me` prop inside Conversations, which was causing an issue with opening a conversation notification from a closed state resulting to an unable to load 
|---|---|
| <video src="https://github.com/user-attachments/assets/eb2c2a2a-618e-4646-93a1-721801b75d49" /> | <video src="https://github.com/user-attachments/assets/5ad61040-13a9-4c57-9517-32b8c1151bb2" /> |
- fix unable to load when opening a conversation notification from closed state - mrsltun
-
-
-
</details>
[docs]: …

fix: fix Conversation unable to load

---

src/app/Scenes/HomeView/Components/HomeHeader.tsx

Small proposed addition to https://github.com/artsy/eigen/pull/10701.

feat: hook up an info button/modal to the New/Alpha badge on the homeview

---

src/app/Scenes/HomeView/Components/ActivityIndicator.tests.tsx
src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
src/app/Scenes/HomeView/Components/HomeHeader.tests.tsx
src/app/Scenes/HomeView/Components/HomeHeader.tsx
src/app/Scenes/HomeView/HomeView.tsx

This PR resolves [ONYX-1251] and [ONYX-1252]
- Ensures consistent vertical spacing with old home screen
- Adds a standard home header component
- Adds a simple `New` indicator so that it's clear which home screen you are viewing
|Before|After|
|---|---|
|![before](https://github.com/user-attachments/assets/1d2dccc3-a9b1-49bf-90b8-541a657d2ce1)|![aftererer](https://github.com/user-attachments/assets/3421beb0-be93-4fc3-a19b-4a3edcd78e7b)|
- Ensure consistent section spacing - Roop
-
-
-
</details>
[ONYX-1251]: …

feat: improve visual parity with existing home screen

---

app.json

chore: Prepare for v8.51.0

---

src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx

Updates the (broken)tests by injecting the ff ahead of time, once echo is deployed we can wipe it out with the ff cleanup ticket.
#noChangelog
-
-
-
-
</details>

test(Prompt): fix broken prompt tests(before echo deploy)

---

src/app/Components/Button/CTAButton.tsx
src/app/Components/Button/LinkButton.tsx
src/app/Components/Button/index.ts
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx

Related to https://github.com/artsy/palette-mobile/pull/249
Prepares Eigen to receive Palette button bump removing legacy code and replacing LinkButton with a simple Text element.
-
-
-
- recator: replace LinkButton with Text and remove dead components - araujobarret
</details>

refactor(LinkButton): removes dead components and replace LinkButton usage

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
src/app/Scenes/Fair/FairExhibitorRail.tests.tsx
src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx

This PR updates the tests after releasing the Auction Signals
-
-
-
- update tests after releasing auction signals on Eigen - mrsltun
</details>

chore: Fix breaking tests after releasing Auction Signals

---

src/app/Scenes/Home/homeAnalytics.ts
src/app/Scenes/HomeView/Sections/FairRailItem.tsx
src/app/Scenes/HomeView/Sections/FairsRailHomeViewSection.tests.tsx
src/app/Scenes/HomeView/Sections/FairsRailHomeViewSection.tsx

This PR resolves [ONYX-1264] 
This PR adds legacy tracking to fairs rail sections.
https://github.com/user-attachments/assets/b3bec2b0-5025-4d41-823f-916bb43be3cb
-
-
-
- add new home view fairs tracking - mounir
</details>
[ONYX-1264]: https://artsyproduct.atlassian.net/browse/ONYX-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add new home view fairs tracking

---

src/app/Scenes/Home/Components/ShowsRail.tsx
src/app/Scenes/HomeView/Sections/ShowsRailHomeViewSection.tests.tsx
src/app/Scenes/HomeView/Sections/ShowsRailHomeViewSection.tsx

This PR resolves [ONYX-1262] 
This PR adds legacy tracking to shows rails sections.
https://github.com/user-attachments/assets/15cc66cb-3bfe-40c2-b400-91832e74d2fe
-
-
-
- add ShowsRailHomeViewSection tracking - mounir
</details>
[ONYX-1262]: https://artsyproduct.atlassian.net/browse/ONYX-1262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add ShowsRailHomeViewSection tracking

---

src/app/Components/ProgressiveOnboarding/useDismissSavedHighlight.ts
src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tsx
src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/app/store/config/features.ts

This PR resolves [DIA-556] 
Removes legacy code from collector settings(before ff)
#nochangelog
-
-
-
-
</details>
[DIA-556]: https://artsyproduct.atlassian.net/browse/DIA-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-556): remove collector settings ff dead code

---

src/app/Scenes/Onboarding/Onboarding.tsx

This PR resolves https://artsy.slack.com/archives/C02BAQ5K7/p1726147009970259
This PR fixes an issue affecting the logged out experience when showing the dev menu
-
-
-
- fix broken dev menu padding on onboarding - mounir
</details>

fix: broken dev menu padding on onboarding

---

ios/Podfile.lock
package.json
src/app/Scenes/Inbox/Components/Conversations/Composer.tsx
src/app/system/navigation/useReloadedDevNavigationState.ts
src/app/utils/PushNotification.ts
yarn.lock

Resolves a few annoying yellowbox warnings I was getting on Android:
- unhandled promise rejection, trying to register push token before logged in and the method was not marked async
- add native event listener without required methods, coming from react-native-localize and fixed in an update
- passing a number without unit to a styles object in conversations
- dev reload state hook accessing launchCount which is sometimes undefined
-
-
-
- fix some yellowbox warnings - brian 
</details>

chore: fix a few yellowbox warnings

---

src/app/App.tsx

I introduced a warning with the sentry change, calling wrap in dev and init not being called. 
This just doesn't wrap the app in dev mode. 
#nochangelog
-
-
-
-
</details>

fix: sentry warning, only wrap app when not in dev #trivial  #nochangelog

---

src/app/Scenes/Collection/Screens/CollectionArtworks.tests.tsx
src/app/Scenes/Collection/Screens/CollectionArtworks.tsx

This PR resolves [EMI-2079] 
This PR hides the Increased Interest and Curators’ Pick signals in Trending Now collection
|---|---|
| <img width="455" alt="image" src="https://github.com/user-attachments/assets/04bbc7cd-deb1-482e-a65a-d7f683f5c81f"> | <img width="455" alt="image" src="https://github.com/user-attachments/assets/0e3b6630-66f8-4b3b-9f29-1b27cc179fbf"> |
- hide increased interest and curators' pick in Trending Now collection - mrsltun
-
-
-
</details>
[EMI-2079]: …

fix(EMI-2079): Hide signals in the Trending Now collection

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
src/app/Components/ArtworkGrids/ArtworkSocialSignal.tests.tsx
src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tsx

This PR flips the Curators' Pick and Increased Interest signals prioritization
- flip Increased Interest and Curators' Pick prioritization - mrsltun
-
-
-
</details>

fix: Flip Increased Interest and Curators' Pick prioritization

---

src/app/Scenes/HomeView/HomeView.tsx

This PR resolves [ONYX-1283]
Added pull-to-refresh and also click on Home icon scrolls to the top of the screen.
Had to use `fetchQuery` to avoid Suspense ([as relay docs recommend it](https://relay.dev/docs/v16.0.0/guided-tour/refetching/refreshing-queries/#if-you-need-to-avoid-suspense-1)). Also props to @gkartalis for pointing me to the similar implementation we have in Eigen: https://github.com/artsy/eigen/blob/main/src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx#L65
<video src="https://github.com/user-attachments/assets/ac1f4203-5591-43e2-b859-c26f2244d374" />
#nochangelog
</details> …

feat(onyx-1283): pull-to-refresh for new home view screen

---

src/app/store/config/features.ts

This PR marks `AREnableCuratorsPicksAndInterestSignals` feature flag as ready for release
-
-
-
- mark AREnableCuratorsPicksAndInterestSignals as ready for release - mrsltun
</details>

chore: Mark AREnableCuratorsPicksAndInterestSignals as ready for release

---

fastlane/Fastfile
fastlane/sentry_fastlane.rb
package.json
yarn.lock

This PR resolves [PHIRE-1191] 
Usually when `@sentry/cli` needs an update it breaks betas throws errors and we need to stop what we are doing - open a bump PR and afterwards rebase our work etc.
This PR solves that by removing `@sentry/cli` from the `package.json` file and downloads it when it is needed, in the fastlane file.
-
-
-
- remove sentry cli from packagejson - gkartalis
</details>
[PHIRE-1191]: https://artsyproduct.atlassian.net/browse/PHIRE-1191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

build(deps): remove sentry cli from packagejson

---

src/app/App.tsx
src/app/AppRegistry.tsx
src/app/Scenes/HomeView/HomeView.tsx

This PR adds prefetching to the new home view.
This saves us about `400ms`of waiting the home query.
https://github.com/user-attachments/assets/878de37d-98ab-4897-a248-e7488b2422ec
-
-
-
- prefetch new home view query - mounir
</details>

feat: prefetch home view query

---

src/app/system/devTools/DevMenu/Components/DevTools.tsx
src/app/utils/requestPushNotificationsPermission.ts

Adds a dev tool to manually request push permissions for easier QA.
-
-
-
- add request push permissions dev tool - brian 
</details>

chore: add dev tool to request push permissions #trivial

---

src/app/system/errorReporting/setupSentry.ts

Turns off sentry user interaction tracking for now, breadcrumbs are noisy and too generic to be useful right now, will revisit in the future. 
-
-
-
- turn off sentry user interaction tracking - brian 
</details>

chore: turn off sentry user interaction tracking for now #trivial

---

src/app/system/navigation/navigate.tests.tsx
src/app/system/navigation/navigate.ts

Fixes deeplinks not being followed from killed app state. Wraps push request in a requestAnimationFrame, I believe the main thread is overloaded causing the call to be ignored otherwise.
<details>
<summary>
Before
</summary>
https://github.com/user-attachments/assets/083ad429-eca9-4aa7-a163-9c17e5c94f73
</details>
<details>
<summary>
After
</summary>
https://github.com/user-attachments/assets/952e589e-0acb-4c87-9e06-6c86f4f60c1a
</details>
- fix broken push deeplink follow from killed state - brian 
-
-
-
</details> …

fix: wait for animations to avoid dead deeplinks

---

src/app/Scenes/HomeView/HomeView.tsx

This PR resolves [ONYX-1276]
Restores missing tooltips:
#nochangelog
</details>
[ONYX-1276]: https://artsyproduct.atlassian.net/browse/ONYX-1276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1276): restore progressive onboarding tooltips for new home view

---

src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
src/app/Scenes/HomeView/useHomeViewTracking.ts

Follow-up from [artsy/metaphysics#6004][]: we can now use schema-provided contextModule values for home view sections.
[artsy/metaphysics#6004]: https://github.com/artsy/metaphysics/pull/6004
-
-
-
- chore(analytics): use schema-provided contextModule for home view sections
</details>

chore(analytics): use schema-provided contextModule for home view sections

---

src/app/Scenes/Activity/Activity.tests.tsx
src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Activity/ActivityContent.tsx
src/app/Scenes/Activity/ActivityScreen.tsx

This PR is an attempt to fix the flaky tests on the Activity Screen
#nochangelog

fix: attempt to fix activity screen flaky tests

---

src/app/Scenes/HomeView/HomeView.tests.tsx
src/app/Scenes/HomeView/HomeView.tsx

This PR resolves [ONYX-1280]
#nochangelog
</details>
[ONYX-1280]: https://artsyproduct.atlassian.net/browse/ONYX-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1280): request push notifications permission from new home view screen

---

src/app/Components/ArtistListItem.tsx
src/app/Scenes/Favorites/FavoriteArtists.tsx

Boosts performance of Favorite artists surface by:
- converting to func component
- using flashlist over flatlist
- memoizing the list
- useCallback for listItem and keyExtractor
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/8ebf4ca8-0d59-4a4a-b48a-1b33c8a4e469" width={400} />|<video src="https://github.com/user-attachments/assets/eb3885d1-234d-4a73-ab89-0595935a75ab" width={400} />|
-
-
-
- boost Favorite artists perf - gkartalis
</details>

perf(boost): Favorite artists perf

---

.circleci/config.yml

Removes rosetta from ci since we probably don't need that.
-
-
-
-  remove rosetta from ci - gkartalis
</details>

build(deps): remove rosetta from ci

---

ios/Podfile.lock
package.json
yarn.lock

This PR upgrades React Native Sentry to v5.24.1 to support building Eigen on XCode v16
-
-
-
- upgrade sentry to v5.24.1 - mrsltun
</details>

chore: upgrade Sentry to v5.24.1

---

src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx

This PR resolves [APPL-1107] 
This PR fixes the issue with the Android back button on Offer Settings and Create New List
|---|---|
| <video src="https://github.com/user-attachments/assets/04691573-c2b0-43cd-aca8-a86b9c3bede8" /> | <video src="https://github.com/user-attachments/assets/a97c78c1-dd55-4c75-a758-39c74d33fb7d" /> |
-
-
- Fix Android back button handler for Offer Settings / Create New List modal - mrsltun
-
</details>
[APPL-1107]: …

fix(APPL-1107): Dismiss Create New List/Offer Settings modal on Android back

---

src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/Activity/components/CollectorUpdateNotification.tsx
src/app/Scenes/Activity/components/__tests__/CollectorUpdateNotification.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPrompt.tsx
src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistsPrompt.tsx

This PR resolves [APPL-1111] 
Fixes 2 bugs:
- Screen was suspending when tapping the collection activity item
- Android wasn't bubbling up the event from the `CollectorUpdateNotification` and consequentially not marking the notification as read or tracking it
iOS
https://github.com/user-attachments/assets/af35d6ea-74e6-40d3-8d0d-fd41d215be69
Android
https://github.com/user-attachments/assets/4083f5d3-12da-4780-b1b9-48102743717b
- fix: activity screen suspending given collection prompt item - araujobarret
-
-
-
</details>
[docs]: …

fix(ActivityScreen): activity screen suspending

---

EXAMPLES.md

Believe that is the correct link that we wanted here.
And I think this one can go without Android screenshots 😉 
-
-
-
- Minor doc update
</details>

docs: update EXAMPLES.md

---

package.json
yarn.lock

Bumps palette-mobile to get some of the latest fixes. 
- bump palette mobile - brian 
-
-
-
</details>

chore: bump palette mobile #trivial 

---

docs/getting_started.md

Adding migration steps to react-native 0.73.9 on our getting started page for future reference
#nochangelog

docs: add upgrade steps for rn 73 #trivial

---

android/build.gradle
android/gradle.properties

People's mapbox downloads started failing recently when setting up eigen for the first time or upgrading rn. 
Then env var was no longer loading correctly. 
Need more investigation as to why all the sudden this is necessary and ideally get rid of the plugin, but let's fix the block
until then. 
-
-
-
- fix mapbox download issue - brian 
</details>

fix: add env gradle plugin to fix mapbox download problems

---

package.json
src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tests.tsx
src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tsx
src/app/utils/hooks/withSuspense.tsx
yarn.lock

feat(Revert-POC): add error boundary to withSuspense

---

package.json
src/app/Scenes/HomeView/Components/ActivityIndicator.tests.tsx
src/app/Scenes/HomeView/useHomeViewTracking.ts
src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tests.tsx
src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
yarn.lock

- chore(analytics): switch to use tappedNotificationBell
- chore(analytics): update HomeViewSectionScreenArtworks ownerType value
-
-
-
- chore(analytics): switch to use tappedNotificationBell
- chore(analytics): update HomeViewSectionScreenArtworks ownerType value
</details>

chore(analytics): update a couple home view analytics events

---

src/app/Scenes/Home/Home.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tests.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tests.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
src/app/Scenes/ViewingRoom/ViewingRoomsList.tests.tsx
src/app/Scenes/ViewingRoom/ViewingRoomsList.tsx

This PR resolves [ONYX-1304]
I want to remove viewingRooms (which is deprecated) query from gravity to simplify un-stitching. Not attaching screenshots because nothing has changed visually. I've compared before / after side by side and everything looks normal.
- [] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.
-
-
-
- refactor: use viewingRoomsConnection instead of deprecated viewingRooms query - @nickskalkin 
</details>
[ONYX-1304]: …

refactor(onyx-1304): use viewingRoomsConnection instead of deprecated viewingRooms query

---

src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/Disappearable.tsx
src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
src/app/Scenes/HomeView/helpers/constants.ts

This PR resolves [ONYX-1290] 
This PR includes a few artwork rail code simplifications in preparation for the redesign.
- Artwork rail code simplifications (refactoring) - ole
-
-
-
</details>
[ONYX-1290]: https://artsyproduct.atlassian.net/browse/ONYX-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Simplify artwork rail code II

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
src/app/Components/ArtworkRail/LegacyArtworkRailCardImage.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx

This PR resolves [ONYX-1321] 
This PR comes as a follow-up on the recent refactorings we made to the artwork rail card. In this one, I am making the following changes:
- Extract the image dimensions helper to use in future PRs.
- Extract the artwork meta into a standalone component
-
-
-
- separate artwork card meta - mounir
</details>
[ONYX-1321]: https://artsyproduct.atlassian.net/browse/ONYX-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: separate artwork card meta

---

src/app/Scenes/Activity/components/PartnerOffeBadge.tsx

This PR resolves [EMI-2083] 
This PR adds bottom padding to the Limited-Time Offer badge
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/17934692-ceac-4dce-9b1c-e4760fa5bc4f) | ![image](https://github.com/user-attachments/assets/e43d8cf8-7b80-4dc8-85eb-4c346a77d096) |
| iOS | ![image](https://github.com/user-attachments/assets/7721c24e-0dfc-42c1-87c4-f36faa6d5a2a) | ![image](https://github.com/user-attachments/assets/2cf5e1f3-ab64-439c-9464-2255561f6b6a) |
- add bottom padding to limited-time offer badge - mrsltun
-
-
-
</details> …

fix(EMI-2083): Add bottom padding to Limited-Time Offer badge

---

src/app/Components/Recaptcha/Recaptcha.tsx
src/app/Components/Recaptcha/RecaptchaWebView.tsx

This PR resolves [DIA-806] 
Adds a simple Recaptcha mechanism to be user within the verify email flow.
The hook is simple, just import it and place the recaptcha element in the component tree.
PS: citadel .env.shared was already updated 🔢 
- feat: add recaptcha mechanism - araujobarret
-
-
-
</details>
[DIA-806]: https://artsyproduct.atlassian.net/browse/DIA-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-806): Recaptcha mechanism

---

src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
src/app/Components/Bidding/Screens/Registration.tests.tsx
src/app/Scenes/About/About.tests.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tests.tsx
src/app/Scenes/Onboarding/OnboardingSocialPick.tests.tsx

Fixes broken tests after deploying AREnableNewTermsAndConditions echo feature flag
-
-
-
- fixes broken tests after deploying AREnableNewTermsAndConditions - gkartalis
</details>

fix: tests after AREnableNewTermsAndConditions release

---

package.json
src/app/AppRegistry.tsx
src/app/Scenes/Articles/Articles.tsx
src/app/Scenes/Articles/ArticlesList.tsx
src/app/Scenes/Articles/News/ArticlesCards.tsx
src/app/Scenes/Articles/News/News.tsx
src/app/Scenes/ArtistArticles/ArtistArticles.tsx
yarn.lock

-
-
-
- chore(analytics): ensure differentiation between marketNews and articles 
- chore(analytics): use different screen ownerType for Artist > Articles
</details>

chore(analytics): Ensure differentiation between marketNews and articles

---

src/app/Components/SectionTitle.tsx

This PR resolves [https://www.notion.so/artsy/Art-Advisor-Home-View-Feedback-abc1123548504ae58051405627fb6c9f] 
This PR updates the hitslop of the section title to make it easier to tap.
| ![Simulator Screenshot - iPhone 16 Pro - 2024-09-26 at 18 01 43](https://github.com/user-attachments/assets/8783e584-9987-48dc-b6ab-5a6119fee2da) | ![Simulator Screenshot - iPhone 16 Pro - 2024-09-26 at 18 01 35](https://github.com/user-attachments/assets/fbe71029-4117-45c1-bb31-4db39edde829) |
- increase hitslop of section titles - mounir
-
-
-
</details> …

feat: increase hitslop of section title

---

src/app/App.tsx
src/app/utils/useAndroidAppStyling.ts

Fixes android status bar and bottom nav styling.
- noticed there is a bit of a bug where some tabs show dark status bar but others don't effectively hiding status bar, believe this is existing bug but should be fixed
-
-
- fix android status bar and bottom nav styling - brian 
-
</details>

fix: bring back android app styling

---

src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx

We are overriding back button behavior in bottom modal but this is rendered even when not presented, check if presented if so dismiss if not let the default back behavior happen.
https://github.com/user-attachments/assets/41640070-90fa-4998-b2b2-4789ae287f60
- my test device is very old but there is a noticeable lag on pressing back button, should be more instant
-
-
- fix back button not working in screens with modal - brian 
-
</details>

fix: android back button - use default back behavior when modal not presented

---

src/app/Components/Home/ArtistRails/ArtistCard.tsx

This PR brings back the Artist card follow button to be rendered in the legacy home view
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/cc35bf88-203a-4c78-a0b7-fb8e56bdb446) | ![image](https://github.com/user-attachments/assets/0518050c-d58b-45b3-b8e4-3c93260ee676) |
| iOS | ![image](https://github.com/user-attachments/assets/5af36931-d12a-4816-a29b-0991475bd3cc) | ![image](https://github.com/user-attachments/assets/0ece1be1-6f32-42e2-b71e-4154d350f121) |
- bring back artists card follow button - mrsltun
-
-
-
</details> …

fix: Bring back Artist follow button

---

.github/dependabot.yml
docs/getting_started.md

This PR adjusts the list of assignees
#nochangelog

chore: adjust assignees

---

src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
src/app/utils/getSaleMessgeOrBidInfo.ts

This PR resolves [https://www.notion.so/artsy/Auction-lots-for-you-shows-undefined-price-10ecab0764a080d2a834dfb409fbfb9a?pvs=4] 
This PR comes as an attempt at solving `undefined` lot count. I don't know yet why this could happen but this seems to solve it for me.
-
-
-
- attempt at solving undefined lot count - mounir
</details>

fix: attempt at solving undefined lotCount

---

src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx

This PR resolves https://www.notion.so/artsy/Dots-under-hero-units-don-t-update-when-i-scroll-horizontally-10ecab0764a080e0af3ad161553969b5
Fixes the pagination by dot UI by ensuring current index of the carousel is set correctly:
| <video src="https://github.com/user-attachments/assets/2b57a45f-a591-429d-b882-63c9b3ea43b0" /> | <video src="https://github.com/user-attachments/assets/61743b74-75bb-4b42-ac18-1b456d0411d7" /> |
- Fix pagination indicator on home view hero unit section — Roop
-
-
-
</details> …

fix: numeric guard for carousel index

---

src/app/Scenes/Home/Components/RecommendedAuctionLotsRail.tsx
src/app/Scenes/Home/Home.tsx
src/app/Scenes/Sales/Sales.tsx

This PR resolves [ONYX-1290] 
Cleanup Auction Lots For You rail - remove no longer use size prop
-
-
-
- Cleanup Auction Lots For You rail - remove no longer use size prop - daria
</details>
[ONYX-1290]: https://artsyproduct.atlassian.net/browse/ONYX-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove artwork size prop from Auction Lots For You rail

---

src/app/store/config/features.ts

add AREnableArtworkRailRedesignImageAspectRatio echo flag, make it ready for release
-
-
-
- add AREnableArtworkRailRedesignImageAspectRatio echo flag, make it ready for release - daria
</details>

chore: add AREnableArtworkRailRedesignImageAspectRatio echo flag, make it ready for release

---

src/app/Scenes/Sale/BuyNowArtworksRail.tests.tsx
src/app/Scenes/Sale/Components/BuyNowArtworksRail.tsx
src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tests.tsx
src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tsx

This PR resolves [DIA-907] 
Before 
After 
Change buy now copy to inquire for sales rail - dejuanito 
-
-
-
-
</details>
[DIA-907]: https://artsyproduct.atlassian.net/browse/DIA-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use inquire copy for sales rail

---

src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggest.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggestListHeader.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPrompt.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/__tests__/MyCollectionArtistsAutosuggest.tests.tsx
src/app/utils/useClientQuery.ts
src/app/utils/useUpdateEffect.ts

This PR fixes the scrolling issue due to some suspense problems.
Changes:
- changes `useLazyLoadQuery` in favor of `useClientQuery` and avoid an extra request when opening the prompt
- update `useClientQuery` to be as it is in Force, it had a bug once we changed the variables the data wasn't re-fetched
https://github.com/user-attachments/assets/d3b2fa20-23b1-4096-a2c8-d273bc028058
- fix: collection prompt search results scroll - araujobarret
-
-
-
</details>

fix(ArtistsCollectionPropmt): fix scrolling

---

fastlane/utility_fastlane.rb

Noticed that adding submission tags was failing locally on pre-push hook because I didn't have dependencies installed, tags should be safe to skip the hook.
-
-
-
- fix submission tags - brian 
</details>

fix(releases): fix submission tags

---

src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx

This PR resolves https://www.notion.so/artsy/In-recomendad-artists-view-seems-to-be-no-right-padding-after-the-last-element-It-bumps-into-end--10ecab0764a08094a76ad822936da286
Adds missing padding to the end of the artist section's flat list.
| <video src="https://github.com/user-attachments/assets/839636d1-6cae-448c-8e8d-6e7470de914b" />| <video src="https://github.com/user-attachments/assets/cc461fcf-1a40-436c-9946-348149dfddb4" />  |
- Fixes whitespace in home screen artist rail  — Roop
-
-
-
</details> …

fix(home view): whitespace at end of artist sections

---

src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginOTPStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx

Noticed some misc validation issues in the flow, so this smooths things out and the user no longer gets stuck at 2fa (if going back and forward, etc). 
Also adds a bit more polish:
- fake wait step before new user password -> name: keep things consistent feeling 
- add isSubmitting loader
- make sure we properly clear out forms on back
cc @artsy/diamond-devs

fix(auth2): Fix misc validation issues

---

src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx

This PR adds a way for users to authenticate if email verification fails unexpectedly. If there is a problem with the network or recaptcha token, the user will be taken to the login screen, with the option to go to the sign up screen by tapping a link.
| https://github.com/user-attachments/assets/661c413d-493e-43a1-bf97-cd1c02ab2dc4 | [android.webm](https://github.com/user-attachments/assets/4bcd00f8-44a5-47ad-b5c2-3cd5417d6c83) |
-
-
-
- provide a way to recover from email verification failures - iskounen
</details> …

feat: provide a backup login flow when recaptcha is unavailable

---

.circleci/config.yml
scripts/setup/update-staging-echo

Adding a new workflow to be triggered when we open a deploy PR in echo in order to see if tests pass or fail before actually breaking the tests in eigen
-
-
-
- run eigen tests when we open an echo deploy PR - gkartalis
</details>

feat: run eigen tests when we open an echo deploy PR

---

src/app/Components/SectionTitle.tsx
src/app/Scenes/Home/Components/ShowsRail.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx

Resolves [Notion card](https://www.notion.so/artsy/Placeholders-of-some-of-the-components-are-incorrect-10ecab0764a080c0b726e3f584bb4599)
Fix placeholders on the new home view
| Activity Placeholder Before | Activity Placeholder After | 
| --- | --- |
| <img width="350" alt="image" src="https://github.com/user-attachments/assets/b947eef5-21b6-4af2-a407-2379ddcd2866"> | <img width="350" alt="image" src="https://github.com/user-attachments/assets/70d2a990-14f8-4fd6-b599-671152d9d94d"> |
| Artworks Rail Placeholder Before | Artworks Rail Placeholder After | 
| --- | --- |
| <img width="350" alt="image" src="https://github.com/user-attachments/assets/bf701585-ee91-487e-80c5-a61cc5e509f7">) | <img width="350" alt="image" …

fix: fix placeholders on the new home view

---

.circleci/config.yml

Add a param to avoid running test-build-deploy when trying to trigger echo job. 
-
-
-
-
</details>

fix: add param to avoid running test-build-deploy

---

src/app/Components/Tasks/Task.tests.tsx
src/app/Components/Tasks/Task.tsx

This PR resolves [EMI-2097] 
This implements the `Task` component. It hasn't been finalized yet and will change in the next iteration.
-
-
-
- Add Task component (not yet used) - ole
</details>
[EMI-2097]: https://artsyproduct.atlassian.net/browse/EMI-2097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add Task component

---

src/app/store/config/features.ts
src/app/system/relay/helpers/cacheHeaderMiddlewareHelpers.ts
src/app/system/relay/middlewares/cacheHeaderMiddleware.ts
src/app/system/relay/middlewares/metaphysicsMiddleware.ts

This PR prepares MP CDN and `@cacheable` directive to be used in MP.
Because the MP CDN feels (to me), a safe switch, I am separating the feature flag from the `@cacheable` directive. 
**Screenshots of how this will look like in practice**
| Case | Screenshot |
| MP CDN ff disabled + @cacheable ff enabled/disabled | <img width="782" alt="Screenshot 2024-10-08 at 16 48 23" src="https://github.com/user-attachments/assets/945f9db1-4a35-47ab-a357-9311e3b17e5b"> |
| MP CDN ff enabled + @cacheable ff disabled | <img width="807" alt="Screenshot 2024-10-08 at 16 48 57" src="https://github.com/user-attachments/assets/867f322a-fd6b-4a80-85ca-f8add35f2d78"> |
| MP CDN ff enabled + @cacheable ff enabled | <img width="846" alt="Screenshot 2024-10-08 at 17 11 …

feat: set feature flags as ready

---

src/app/Scenes/HomeView/HomeView.tsx

This PR resolves [ONYX-1328] 
Handle home screen network errors.
-
-
-
-
</details>
[ONYX-1328]: https://artsyproduct.atlassian.net/browse/ONYX-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Handle home screen network errors

---

package.json
yarn.lock

bump easy-peasy from 6.0.0 to 6.0.5
-
-
-
- bump easy-peasy from 6.0.0 to 6.0.5 - gkartalis
</details>

build(deps): bump easy-peasy from 6.0.0 to 6.0.5

---

src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx

This PR resolves [https://www.notion.so/artsy/for-artwork-screens-the-screen-title-doesn-t-show-up-after-I-scroll-down-11acab0764a080ada1a8f0e9d32ef35a] 
This PR fixes an issue with the title not showing up in artwork screens when the user scrolls down
https://github.com/user-attachments/assets/ce4a4897-3b3e-4e4c-81e9-b0738dbaeba2
- fix: show title on scroll down - mounir
-
-
-
</details>

fix: show title on scroll down

---

docs/pull_request_template.md
package.json
scripts/changelog/generateChangelog.ts
scripts/changelog/parsePRDescription.ts
yarn.lock

This PR resolves [PHIRE-1265] 
- Adds github usernames to changelog output as suggested by @dblandin 
- Replaces ts-node with tsx to workaround this issue without additional config: https://artsy.slack.com/archives/C02BAQ5K7/p1727438708031879
-
-
- 
- add username to changelog - brian 
</details>
[PHIRE-1265]: https://artsyproduct.atlassian.net/browse/PHIRE-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(releases): add username to changelog

---

src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx

This PR tidies up validation for the new sign-up flow.
- Adds a Yup schema for the required checkbox
- Disables the continue button until the form is valid
[android.webm](https://github.com/user-attachments/assets/bc4395a1-c6f4-4c0c-a95f-93b16ad267d6)
- 
-
-
- tidied-up validation for new sign-up flow - iskounen
</details>

fix(DIA-898): tidy-up validation for new sign-up flow

---

package.json
src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tests.tsx
src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworksPlaceholder.tsx
src/app/utils/PlaceholderList.tsx
yarn.lock

This PR resolves [https://www.notion.so/artsy/for-artwork-screens-Implement-display-style-toggle-to-switch-between-grid-and-full-width-11acab0764a0809f8e81dc0c0324d1eb?pvs=4] 
This PR adds support of grid/list view modes to artwork screens.
This is currently a feature that we support for the legacy screens but we forgot to add to the new home view artwork screens.
https://github.com/user-attachments/assets/a912798a-5f46-4d90-b5d2-7fae1ae26201
- support grid / list view mode for artwork screens
-
-
-
</details>
[docs]: …

feat: add grid/list view mode for artwork screens

---

src/app/Scenes/HomeView/HomeView.tests.tsx
src/app/Scenes/HomeView/HomeView.tsx

Port this banner from the existing home screen to the new home view.
https://github.com/user-attachments/assets/c64865f6-3ce7-45ee-a2c0-cd318c28dc8f
- feat: add email confirmation banner to new HomeView
-
-
-
</details>

feat: add email confirmation banner to new HomeView

---

src/app/Components/ShowCard.tsx

This PR resolves [https://www.notion.so/artsy/Images-for-shows-in-Shows-For-You-rail-appear-low-resolution-11acab0764a080ff98b3c0f80040f460?pvs=4] 
This PR fixes an issue with the shows rail where the images are very low quality
| ![Simulator Screenshot - iPhone 16 Pro - 2024-10-11 at 11 10 46](https://github.com/user-attachments/assets/1dc16916-80d5-47bc-936d-27aadd8a466c) | ![Simulator Screenshot - iPhone 16 Pro - 2024-10-11 at 11 11 50](https://github.com/user-attachments/assets/dcd91349-a304-4699-b288-a89cf1d2c82f) |
- fix shows rail images poor quality on home - mounir
-
-
-
</details> …

fix: show images low quality

---

src/app/Components/ArticleCard.tsx
src/app/Components/ShowCard.tsx
src/app/Scenes/Home/Components/ShowsRail.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx

- feat: update typography of ArticleCard 
- feat: update typography/spacing for ShowCard 
- feat: update spacing between home view section from 60 to 40px
Paired with Jimi (design), Barney (design) and @MounirDhahri on this.
- feat: update typography of ArticleCard 
- feat: update typography/spacing for ShowCard 
- feat: update spacing between home view section from 60 to 40px
-
-
-
</details>

feat: update typography+spacing for Artsy Editorial and Shows for you home rails

---

src/app/Components/ShowCard.tsx

Our Image components often trigger on-the-fly image resizing via Gemini and this larger image should be a better original source to crop/resize from.
Follow up to #10944.
- feat: bump ShowCard image size from large to larger
-
-
-
</details>

feat: bump ShowCard image size from large to larger

---

src/app/Scenes/Onboarding/Auth2/AuthContext.tsx
src/app/Scenes/Onboarding/Auth2/hooks/useAuthNavigation.tsx
src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx

This PR tidies up the Forgot Password? step of the new authentication flow.
- Pre-populate the email address
- Return users to the password step for back navigation and "Return to login" buttons
https://github.com/user-attachments/assets/6d1f0cc5-a248-4669-a01a-adddea92ee5c
-
-
-
- Added touch-ups to auth2 forgot password step - iskounen
</details>

fix(DIA-901): tidy-up forgot password step [WIP]

---

src/app/Scenes/Home/Components/ActivityRailItem.tests.tsx
src/app/Scenes/Home/Components/ActivityRailItem.tsx

I've been noticing some odd text clipping for these activity rail items and this is an attempt to ensure we're using numberOfLines={2} for all items.
_Also includes a new spec file and a bit of refactoring to headline formatting._
| Current | Proposed |
| ![signal-2024-10-11-184908](https://github.com/user-attachments/assets/4a0ca28b-c203-4ac7-9f11-1bc5431875a6) | ![Simulator Screenshot - iPhone 16 - 2024-10-11 at 18 48 20](https://github.com/user-attachments/assets/2a86567b-681c-4f6e-952c-09ac8bf5afd9) |
| Cell | Cell | 
- feat: ensure a max of 2 lines for activity rail items
-
-
-
</details> …

feat: ensure a max of 2 lines for activity rail items

---

src/app/AppRegistry.tsx
src/app/utils/useAndroidAppStyling.ts

- fixes androidAppStyling hook, was not watching logged in state or setting status bar color correctly
- removes screen option competing with hook settings, should be handled by hook
-
-
- fix android status bar color in main tabs - brian 
-
</details>

fix: android status bar color

---

src/app/Components/Swipeable/Swipeable.tests.tsx
src/app/Components/Swipeable/Swipeable.tsx
src/app/Components/Tasks/Task.tsx

This PR resolves [EMI-2127] 
This PR improves the swipe-to-interact animation of the Swipeable component. It is used for the task list ("Act Now" section on the home view).
| --- | --- |
|![simulator_screenshot_3F58125C-CAF2-4D0F-A48B-4B4595E668F6](https://github.com/user-attachments/assets/9e5caada-0b33-47a6-921c-196d0ae1074c) | ![simulator_screenshot_75523489-A46E-4BF6-839A-B53C2A7466DB](https://github.com/user-attachments/assets/b15a3a8f-4701-405c-a128-741f06894690)|
-
-  Improve swipeable task animation (behind feature flag) - ole
-
-
</details> …

feat: Improve swipeable task animation

---

src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx

This PR fixes the issue of cutting the artwork price text on the Artwork Rail Card
|---|---|---|
| Android | ![before](https://github.com/user-attachments/assets/6e67f538-58dc-4738-9cd0-a94479d80230) | ![after](https://github.com/user-attachments/assets/c622393a-4d11-454c-9261-8e323659ec35) |
| iOS | ![image](https://github.com/user-attachments/assets/6e7cb2fe-1ed4-4b84-84f8-0b12dca07598) | ![image](https://github.com/user-attachments/assets/003e1bbe-9613-4532-8d00-6f4c3aa69642) | 
- stop cutting artwork price text on artwork rail cards - mrsltun
-
-
-
</details> …

fix: uncut artwork rail card price text

---

src/app/Components/Swipeable/Swipeable.tsx
src/app/Components/Tasks/Task.tsx

Follow up for https://github.com/artsy/eigen/pull/10956
This fixes the Swipeable action color definition.
-
-
-
-
</details>

fix: Swipeable action color definition

---

src/app/Scenes/Partner/Components/PartnerOverview.tests.tsx
src/app/Scenes/Partner/Components/PartnerOverview.tsx
src/app/Scenes/Partner/Partner.tsx

This PR fixes an issue with the Institution screen where we were applying an optimisation that was breaking. The reason behind that is that we based our params on a prop that comes during runtime so it confuses relay-runtime.
There are probably better ways to fix this but for the sake of time, I figured out it's fine to remove this optimisation for now on a screen that doesn't get much traffic. Also this is fairly a new optimisation.
- fix broken institution screen - mounir
-
-
-
</details>
[docs]: …

fix: broken institution screen

---

src/app/utils/useHideSplashScreen.ts

This PR fixes an issue affecting the feature flagging logic on the new home view. If the feature flag is disabled, the splash screen doesn't disappear. 
|  <Video src="https://github.com/user-attachments/assets/10f37e62-0b62-4168-b298-581ceed130cc" />  |  <Video src="https://github.com/user-attachments/assets/211c897a-9760-41e1-a07e-ec901f98be86" /> | 
- fix hide splash screen on legacy home view - mounir
-
-
-
</details>

fix: hide splash screen on legacy home view

---

src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx

This PR resolves [EMI-2122] 
This PR fixes an issue with padding in the collector signals section in the Artwork Details screen
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/4e650d56-bd4e-4b21-8bf1-f7af620b4c90) | ![image](https://github.com/user-attachments/assets/71919e8a-1cc5-4433-a4fb-28f53cd979da) |
| iOS | ![image](https://github.com/user-attachments/assets/adda91dd-de5c-43d5-bbe2-c5cd9a259d4b) | ![image](https://github.com/user-attachments/assets/b045a551-1531-4572-a89c-65e1c05d02f0) |
- Fix padding issue in collector signals section in artwork details screen - mrsltun
-
-
-
</details> …

fix(EMI-2122): Fix padding issue in collector signals in Artwork Details screen

---

android/app/src/main/res/values/styles.xml

This PR sets the navigation bar color to whilte all over the app. This is inconvenient in case we want to  set it by screen but it's what we had since we released android and we can adjust it later
-
-
- fix broken navigation bar color on android - mounir
-
</details>

fix: broken navigation bar color

---

src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginOTPStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginOTPStep.test.tsx
src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginOTPStep.tests.tsx

These are things that I will tidy up in this PR:
-
-
-
- Tidied-up the auth2 login with OTP step - iskounen
</details>

fix(DIA-930): tidy-up login with OTP step [WIP]

---

src/app/Scenes/CollectionsByCategory/Body.tsx
src/app/Scenes/CollectionsByCategory/CollectionsByCategory.tsx
src/app/Scenes/CollectionsByCategory/CollectionsChips.tsx
src/app/Scenes/CollectionsByCategory/Footer.tsx
src/app/Scenes/CollectionsByCategory/__tests__/CollectionsChips.tests.tsx
src/app/Scenes/CollectionsByCategory/__tests__/Footer.tests.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCards.tests.tsx
src/app/utils/hooks/withSuspense.tsx

This PR is related to  [DIA-931]
- Adds the chips element to the collections by category screen
- Footer on the category screen
- Adds component typings to the withSuspense fn
iOS
https://github.com/user-attachments/assets/a0a22fe3-f60c-4fa6-8d2a-92ac28e58108
Android
https://github.com/user-attachments/assets/86e9a973-c621-4440-9771-9240c9969261
- feat: add chips and footer to collections by category screen
-
-
-
</details>
[DIA-931]: https://artsyproduct.atlassian.net/browse/DIA-931?atlOrigin=eyJpIjoiNWRkNTl …

feat(DIA-931): implement the chips and footer of collections by category screen

---

package.json
scripts/utils/exportNotionTicketsToJira.ts

Adds a utility script for exporting cards found in our mobile qas to jira.
Example:
`yarn setup:releases` 
`yarn export-notion-to-jira <database-id>`
See comment for how to find db id.
This will create tickets from cards in the bugs board on in the Applause jira project.
Example:
-
-
-
- add util script for exporting notion cards to jira - brian 
</details>

chore: util script for exporting notion cards to jira

---

src/app/Scenes/Activity/ActivityItemScreen.tsx

This PR resolves [ONYX-1314] 
Currently, we render the screen tracking component in the placeholder instead of the actual component. This is why it only fired the first time the user entered the screen.
This PR moves it to the actual screen.
-
-
-
- Track Activity item screen event correctly - ole
</details>
[ONYX-1314]: https://artsyproduct.atlassian.net/browse/ONYX-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Track Activity item screen event correctly

---

src/app/Components/Tasks/Task.tests.tsx
src/app/Components/Tasks/Task.tsx
src/app/utils/mutations/useAcknowledgeTask.ts

This PR resolves [EMI-2147] 
This PR adds the mutation to acknowledge a task when tapping on it
It also adds test for dismissing and acknowledging a tasks
|---|---|
| <video src="https://github.com/user-attachments/assets/a0ddf25f-7971-4a3b-a3f2-51548a36791a" /> | <video src="https://github.com/user-attachments/assets/4e6a032f-4f49-4f36-8c29-5bc127181abe" /> |
- acknowledge tasks when tapping on tasks - mrsltun
-
-
-
</details>
[EMI-2147]: …

feat(EMI-2147): Acknowledge tasks when tapping on them

---

dangerfile.ts

This PR is a follow-up on #10911
This PR updates the Danger's changelog message to reflect the way it will show when running the generateChangelog script
-
-
-
- update danger's PR changelog message
</details>

feat: Update Danger's changelog message in PRs

---

src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Scenes/CollectionsByCategory/Body.tsx
src/app/Scenes/CollectionsByCategory/CollectionRail.tsx
src/app/Scenes/CollectionsByCategory/__tests__/Body.tests.tsx
src/app/Scenes/CollectionsByCategory/__tests__/CollectionRail.tests.tsx
src/app/Scenes/Home/Home.tsx

This PR resolves [DIA-931] 
This PR adds the Artworks rails to the Collections by Category screen, it has a mechanism to load the next rails only when they're closer to be visible to avoid the heavy fetch at the beginning.
https://github.com/user-attachments/assets/b5e9a25a-764e-408e-b659-4c5391f922b2
- feat: add artworks rail to the collections by category screen
-
-
-
</details>
[DIA-931]: https://artsyproduct.atlassian.net/browse/DIA-931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

feat(DIA-931): add collection artwork rails

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
src/app/Scenes/Fair/FairExhibitorRail.tests.tsx
src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
src/app/Scenes/Search/components/EntitySearchResults.tests.tsx
src/app/store/config/features.ts

This is just beginning of clean up tasks to remove feature flags for signals works.
-
- 
-
- remove AREnablePartnerOfferSignals feature flag - oxaudo
</details>

chore: remove AREnablePartnerOfferSignals

---

ios/Podfile.lock
package.json
yarn.lock

bump @braze/react-native-sdk from 8.4.0 to 11.0.0 in order to fix the Invalid privacy manifest and Invalid tracking information apple warning.
-
-
-
- bump @braze/react-native-sdk from 8.4.0 to 11.0.0
</details>

build(deps): bump @braze/react-native-sdk from 8.4.0 to 11.0.0

---

src/app/Components/Tasks/Task.tests.tsx
src/app/Components/Tasks/Task.tsx
src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionTasks.tests.tsx
src/app/Scenes/HomeView/useHomeViewTracking.ts

This PR resolves [EMI-2098] 
This PR is a follow up on artsy/cohesion#533
This PR adds tracking for tasks, for both acknowledging or dismissing tasks
|---|---|---|
| tappedNotification | ![image](https://github.com/user-attachments/assets/95ac159c-0f28-4ad2-bffc-3261eb38f7fa) | ![image](https://github.com/user-attachments/assets/ab5c6358-2fdf-4307-907f-370635670552) |
| tappedClearNotification | ![image](https://github.com/user-attachments/assets/292fcff4-af47-433a-9fd5-b2b2be48ca17) | ![image](https://github.com/user-attachments/assets/a9ed05b1-d7c8-462b-8bf1-beba445b7e37) |
-
-
-
- Add tracking for tasks in HomeView
</details>
[app state …

feat(EMI-2098): Add tracking for Tasks

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
src/app/Scenes/Search/components/EntitySearchResults.tests.tsx

This PR tries to fix the flaky tests in the CI by increasing the timeout for the `waitForElementToBeRemoved`
-
-
-
- attempt to fix flaky tests
</details>

fix: Increase timeout in flaky tests

---

src/app/Components/LoadFailureView.tsx

This PR resolves [PHIRE-1280] 
Minor update to the unable to load tracking to send screen name if present, tab otherwise, attach the extras to the event. 
-
-
-
- update unable to load tracking - brian 
</details>
[PHIRE-1280]: https://artsyproduct.atlassian.net/browse/PHIRE-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update unable to load tracking - send screen message if screen present, tab otherwise

---

src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx

This PR removes the size argument of the chips in the "Discover Something New" component, allowing us to fully utilize the server-driven architecture by controlling the size through Metaphysics.
Before 
After 
update the chips count for Discover something new
-
-
-
-
</details>

fix: update the size argument for Discover something new chips

---

src/app/Scenes/Feature/Feature.tsx

This PR resolves [PBRW-105] 
Fixes a display issue where Markdown is not supported properly on the Feature screen's associated Sets
Currently highly visible due to **Vanguard 2025**
| <img width=200 src="https://github.com/user-attachments/assets/bbe3df4e-d75e-4c74-b921-2c909a2d7a49" /> | <img width=200 src="https://github.com/user-attachments/assets/7909f0f5-a97f-41f8-81f9-751793c7908e" /> | 
- Improve rendering of rich text on feature screens — Roop
-
-
-
</details> …

fix(feature): rendering of associated set's markdown

---

src/app/Components/Recaptcha/Recaptcha.tsx
src/app/Scenes/Onboarding/Auth2/components/AuthModal.tsx
src/app/Scenes/Onboarding/Auth2/hooks/useAuthNavigation.tsx
src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx

This PR resolves [DIA-938] and [DIA-939] and [DIA-940].
- Decrease the corner rounding from 20px to 10px
- Increase the line height of the disclaimer text from 14px to 16px
- Return to the email step from the forgot password step
- Memoize the recaptcha component definition
|--------|------|
| ![20px - 14x](https://github.com/user-attachments/assets/90d1ddd3-2e46-4f64-a21f-e0b939ef1664) | ![10px - 16px](https://github.com/user-attachments/assets/5a1feb08-80b7-466f-942f-62b39db18099) |
-
-
-
-
</details>
[docs]: …

fix: design QA fixes omnibus

---

src/app/Scenes/CollectionsByCategory/CollectionRail.tsx
src/app/Scenes/CollectionsByCategory/CollectionsByCategory.tsx
src/app/Scenes/CollectionsByCategory/CollectionsChips.tsx
src/app/Scenes/CollectionsByCategory/__tests__/CollectionRail.tests.tsx
src/app/Scenes/CollectionsByCategory/__tests__/CollectionsChips.tests.tsx
src/app/Scenes/CollectionsByCategory/hooks/useCollectionByCategoryTracking.ts
src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCards.tests.tsx
src/app/Scenes/HomeView/useHomeViewTracking.ts
src/app/store/config/features.ts
src/app/utils/track/schema.ts

This PR resolves [DIA-863] 
Fixes home view tracking and add missing pieces of tracking to the Explore By and Discover Something New.
- feat: fixes home view tracking and add missing pieces on Discover/Explore sections
-
-
-
</details>
[DIA-863]: https://artsyproduct.atlassian.net/browse/DIA-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ExploreBy): fix and add missing tracking

---

package.json
src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
yarn.lock

This PR adds tracking to OrderHistory part of this issue [EMI-2131](https://artsyproduct.atlassian.net/browse/EMI-2131)] 
-
-
-
- add tracking to OrderHistory fixed failed payment button click - oxaudo
</details>
[EMI-2131]: https://artsyproduct.atlassian.net/browse/EMI-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add tracking to fix payment click

---

src/app/Scenes/SavedArtworks/SavedArtworks.tsx

This PR resolves [ONYX-1320] 
Add screen tracking to Saves screen.
-
-
-
-
</details>
[ONYX-1320]: https://artsyproduct.atlassian.net/browse/ONYX-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add screen tracking to Saves screen

---

ios/Artsy.xcodeproj/project.pbxproj

This PR brings back some missing native modules that we accidentally removed. 
https://github.com/user-attachments/assets/d5f0b88e-4a61-4129-b319-b6d63ee027d0
-
-
-
- fix - bring back missing native modules
</details>

fix: bring back missing native modules

---

docs/getting_started.md

Point to the correct React Native documentation in the getting started docs. The docs currently link to "Start a new React Native project with Expo." I suppose older documentation is needed because we don't use Expo.
-
-
-
-
</details>

chore: Point to correct react native docs in getting started docs

---

src/app/Scenes/CollectionsByCategory/CollectionRail.tsx

Fixes [this issue](https://www.notion.so/artsy/2024-10-25-Mobile-App-QA-version-8-55-0-iOS-build-2024-10-25-11-Android-build-1674645902-12acab0764a080bc82aad9d830a05888?p=12acab0764a0807eaf55e556a603bfc4&pm=s)
It adds the sort for collection rail and matches the artworks on collection page.
https://github.com/user-attachments/assets/30c861d1-abcf-451d-acff-e13f2634c5d2
fixes the sorting for collection rail in Explore by component
-
-
-
-
</details>

fix: update the sorting on collection rail

---

src/app/Components/ErrorView/SimpleErrorMessage.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/Inbox/Screens/Conversation.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
src/app/Scenes/Search/SearchArtworksContainer.tests.tsx
src/app/Scenes/Search/SearchArtworksContainer.tsx
src/app/Scenes/Search/components/EntitySearchResults.tsx

This PR resolves [PHIRE-1295] 
Fixes a few cases of unable to loads.
| Screen | Before | After |
|--------|--------|--------|
| MyCollection Artist Suggest |  ![mycollection-artist-autosuggest-before](https://github.com/user-attachments/assets/48fe189b-71a7-4363-a232-a467ae29f201) |  ![mycollection-artist-autosuggest-after](https://github.com/user-attachments/assets/3fdad124-0247-47ba-9e5a-a3ac1146db6e) |
| Conversation | ![conversation-before](https://github.com/user-attachments/assets/491333a8-050c-4a73-a369-284b23274e2a) | ![conversation-after](https://github.com/user-attachments/assets/2d1ec64c-61bd-4335-a5cf-53c1d44ac0f5) |
| Autosuggest | ![autosuggest-before](https://github.com/user-attachments/assets/810d7964-6d94-45d8-b24f-b7499af85d43) | …

fix: unable to load fixes

---

package.json
src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/Bidding/Screens/CreditCardForm.tsx
src/app/Components/Stack.tsx
src/app/Scenes/Activity/ActivityEmptyView.tsx
src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
src/app/Scenes/Articles/News/ArticlesCards.tsx
src/app/Scenes/CollectionsByCategory/Body.tsx
src/app/Scenes/CollectionsByCategory/CollectionsByCategory.tsx
src/app/Scenes/CollectionsByCategory/CollectionsChips.tsx
src/app/Scenes/CollectionsByCategory/Footer.tsx
src/app/Scenes/CompleteMyProfile/ChangesSummary.tsx
src/app/Scenes/CompleteMyProfile/Header.tsx
src/app/Scenes/CompleteMyProfile/IdentityVerificationStep.tsx
src/app/Scenes/CompleteMyProfile/ImageSelector.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/Fair/FairOverview.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggest.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggestItem.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPrompt.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPromptFooter.tsx
src/app/Scenes/MyProfile/Components/UserProfileFields.tsx
src/app/Scenes/MyProfile/MyProfileEditForm.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tsx
src/app/Scenes/SavedArtworks/SavedArtworks.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAdditionalDocuments.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
yarn.lock

This PR bumps palette-mobile with the latest changes and adjusts the gaps to the tokens.
2 minor changes:
- removed the unnecessary gap of 1dp on the credit card screen(screenshots)
- fixed the artwork rails placeholder that was using 15px instead of our 2(20px/dp)
Before:
After:
- refactor: adjust gaps to our tokens
-
-
-
</details>

feat(gap): replace gap calls with our spacing tokens

---

src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx

This PR resolves [ONYX-1374] 
After an offline discussion with @dariakoko we decided to address that here and open a thread (link pending) and fix the issue on another PR on palette level.
Reasoning:
- our text component has some issues in its implementation and does not respect some prop inheritance
- moving the selectable from the text in palette does fix this issue but creates another issue of people not being able to select and copy text in ios and android apps.
-
-
- partner name android not truncated properly 
-
</details>
[docs]: …

fix: partner name android not truncated properly

---

src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx

This PR resolves [EMI-2170] 
This PR updates the task's animation on tapping/clearing
> [!tip]
> I hid the videos behind a toggle to make the PR description neat, but please check them out
<details>
<summary>## Videos </summary>
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/5b60e29a-1fda-4fb5-bc43-8b795533d3c6" /> | <video src="https://github.com/user-attachments/assets/e0773c58-674e-42fa-a2fd-8df4ab7f15ff" /> |
| iOS | <video src="https://github.com/user-attachments/assets/facf65a3-45de-4581-8295-2fd6a9fe7bec" /> | <video src="https://github.com/user-attachments/assets/bbe880f9-9e99-4427-abdc-57a6718ef8af" /> |
</details> 
<details>
<summary>## Videos </summary>
|---|---|---|
| Android | <video …

fix(EMI-2170): Fix Android ghost task after tapping on it

---

src/app/store/config/features.ts

mark AREnablePaymentFailureBanner as ready for release
-
-
-
- mark AREnablePaymentFailureBanner as ready for release - oxaudo
</details>

feat: mark AREnablePaymentFailureBanner as ready for release

---

src/app/system/errorReporting/setupSentry.ts

Lower transaction sample rate for sentry. 
-
-
-
- lower transaction sample rate - brian 
</details>

chore: lower sentry transaction sample rate #trivial

---

src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
src/app/Scenes/Onboarding/Onboarding.tsx
src/app/utils/auth/socialSignInHelpers.ts

This PR resolves [DIA-973] 
This PR adds social account linking to auth2. It does so by adding the Link Accounts screen to the navigator, and makes the navigator accessible to the error-handling code by turning it into a hook.
https://github.com/user-attachments/assets/b9af601d-dfec-46b7-b2d1-934111183352
-
-
-
- Added social account linking to auth2.
</details>
[DIA-973]: https://artsyproduct.atlassian.net/browse/DIA-973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

feat(DIA-973): add social account linking to auth2

---

src/app/Scenes/Artist/Artist.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
src/app/Scenes/Partner/Partner.tsx
src/app/system/relay/helpers/cacheHeaderMiddlewareHelpers.ts

This PR comes to address the comments during the QA session here https://www.notion.so/artsy/2024-10-10-Mobile-Feature-QA-Metaphysics-CDN-and-cacheable-directive-11bcab0764a08097bd33cc1179d4d6a9
Here: I am removing the `@cacheable` flag from any query that is requesting content that is not cacheable. This includes for example:
- Shows for You rail
- Queries containing artwork grids which display (`isSaved`)
- 
-
-
- remove @cacheable from non cacheable requests - mounir
</details>

fix: remove @cacheable from non cacheable requests

---

src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
src/app/Navigation/Navigation.tsx
src/app/Scenes/Onboarding/Onboarding.tsx
src/app/system/devTools/DevMenu/DevMenu.tsx

This PR adds the unauthorized routes to the new navigation stack.
What to take into consideration: I didn't change the way the routes are defined although I **strongly** feel like we can align those to be within one `Navigator` instead of their own independent `NavigationContainer`. That will allow us to deep link to them, to offer a better DX and align with the authorized stack routes. However since we are actively working on this screens, I decided to keep that work until this effort passes QA.
**Sign In**
https://github.com/user-attachments/assets/ceddccaa-fdbd-4293-9409-60e4c757d31b
___
**Sign Up**
https://github.com/user-attachments/assets/56c41d24-6633-43d2-99ab-7f433548569e
___
**Dev Menu**
https://github.com/user-attachments/assets/209d7787-7892-4d96-972a-abb6f5760b2e …

feat: add Unauthorized routes to Navigation

---

src/app/Scenes/Onboarding/Auth2/AuthApp.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginOTPStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
src/app/Scenes/Onboarding/OnboardingSocialLink.tsx

This PR resolves some launch blocking items in the new auth flow, including:
- Made the status text at the top of the screen white on Android when the user is on the welcome screen
- Made password managers work on Android
- Allowed OTP step to be submitted by pressing "Done" on the keyboard
- Removed clear icon from the link account screen
- Allowed OTP step to be submitted by pressing "Done" on the keyboard
- Removed clear icon from the link account screen
- 
- Made the status text at the top of the screen white when the user is on the welcome screen
- Made password managers work with new auth flow
-
</details> …

fix: auth2 QA omnibus

---

src/app/Scenes/HomeView/Sections/Section.tsx
src/app/store/config/features.ts

This PR marks the feature flag `AREnableHomeViewTasksSection` to be ready for release
It also updates the name of the feature flag to fix a typo
-
-
-
- mark AREnableHomeViewTasksSection as ready for release
</details>

chore: mark AREnableHomeViewTasksSection as ready for release

---

src/app/Scenes/Home/Components/ActivityRailItem.tests.tsx

This PR fixes a test that was set to a date that became in the past
-
-
-
- update old date test
</details>

fix: fix broken test

---

src/app/store/config/features.ts

This PR sets the `@cacheable` directive feature flag as ready for release.
We can follow-up on this later by extracting personalized content to separate query renderers. Here I am speaking of the follow button for example and saved status on artworks.
-
-
-
- set `@cacheable` feature flag as ready for release - mounir
</details>

feat: make AREnableCacheableDirective ready for release

---

src/app/Components/ArtworkLists/useArtworkListsToast.ts
src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Activity/components/AlertNotification.tsx
src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
src/app/Scenes/Activity/components/__tests__/AlertNotification.tests.tsx
src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tsx
src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tests.tsx
src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tests.tsx
src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
src/app/routes.ts
src/app/system/navigation/navigate.tests.tsx

Resolves [ONYX-1386](https://artsyproduct.atlassian.net/browse/ONYX-1386)
* Slack Thread: https://artsy.slack.com/archives/C05EQL4R5N0/p1731317405486329
* Related Force PR: https://github.com/artsy/force/pull/13820
This PR updates the `/alert` and `/saves` routes to match the updated routes in Force and make deep linking work again (https://github.com/artsy/force/pull/13820).
Before | After
-- | --
settings/alerts | favorites/alerts
settings/alerts/:id/edit | favorites/alerts/:id/edit
settings/alerts/:id/artworks | favorites/alerts/:id/artworks
settings/saves | favorites/saves
settings/saves/:id | favorites/saves/:id
-------
Even with redirects in force, deep linking does not currently work with the new routes (e.g., "Edit Alert" button from the marketing email).
| --- …

fix(ONYX-1386): Update routes for alerts and saves to match web and fix deep linking

---

Gemfile
Gemfile.lock

Update fastlane to latest
#nochangelog #no-changelog
-
-
-
-
</details>

chore(deps): update fastlane

---

src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tsx

This PR resolves https://www.notion.so/artsy/The-modal-dialog-pushes-the-main-app-backwards-13bcab0764a080749e8bcddaedcd0e48?pvs=4
Fix make offer modal presentation 
**Before**
**After**
https://github.com/user-attachments/assets/cb91fc42-09c6-4f61-9593-89316b714c18
- fix make offer modal - mounir
-
-
-
</details>

fix: make offer modal

---

src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx

This PR resolves https://www.notion.so/artsy/Android-Auctions-sort-and-filter-button-is-hidden-behind-bottom-tabs-13bcab0764a080c0bf26c0f692bb4bec?pvs=4
This PR fixes an issue with the animated filter button getting covered in the new navigation infra
| <img width="400" src="https://github.com/user-attachments/assets/0638881d-fa6c-47af-9039-ec398ce5d57f" /> | <Video src="https://github.com/user-attachments/assets/923286ef-b911-4e63-95a9-5e38c88e1252" /> | 
- fix animated button position on auction screen - mounir
-
-
-
</details> …

fix: animated button position on auction screen

---

src/app/Components/Containers/BidFlow.tsx

This PR resolves https://www.notion.so/artsy/Android-big-padding-on-max-bid-modal-13bcab0764a080fe8bb0df85bab542b6?pvs=4
This PR fixes an issue with place max bid screen padding on android.
| Header | Header |
| <img src="https://github.com/user-attachments/assets/229ad454-ca91-4481-aac1-e243cf8ca3b7" /> | <img src="https://github.com/user-attachments/assets/95069fc4-4f12-4711-92c5-b26e00083371" /> | 
- 
-
- fix broken android padding inside max bid - mounir
-
</details>

fix: android broken padding inside max bid

---

src/app/AppRegistry.tsx
src/app/Scenes/Collection/Components/FullFeaturedArtistList.tsx

This PR resolves https://www.notion.so/artsy/Android-double-header-in-Contemporary-Pop-Overview-tab-View-all-featured-artists-q-13bcab0764a080c8ad19d9f184a50b14?pvs=4
This PR fixes the issue with the featured collected artists header screen
| <img src="https://github.com/user-attachments/assets/3ffba553-52d3-4a45-a071-5ce0764b1852" /> | <img src="https://github.com/user-attachments/assets/4414aadf-1e90-484a-a13f-baee9f6baa19" /> | 
- fix header title on collected artists - mounir
-
-
-
</details>
[docs]: …

fix: header title on collected artists

---

src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx

Link: https://www.notion.so/artsy/Go-to-any-page-without-having-your-screen-orientation-locked-turn-around-the-phone-we-get-this-f-13dcab0764a0802b9646de4dbbd81fc9?pvs=4
This PR fixes an issue with the screen orientation after enabling the new navigation infra.
| After | Before |
| <Video src="https://github.com/user-attachments/assets/2f8edc17-749d-43e3-80b9-5d7af976e0c5" /> | <Video src="https://github.com/user-attachments/assets/ac463118-4f1d-4b05-9088-907b45295789" /> | 
-
-
-
- fix screen orientation on new navigation - mounir
</details> …

fix: screen orientation

---

src/app/Scenes/Show/Components/ShowArtworks.tsx
src/app/Scenes/Show/Show.tsx
src/app/Scenes/Show/ShowArtworks.tests.tsx

This PR fixes some pretty old issues with the shows screen
- The separator padding after the artworks section (should have no padding instead of having a padding of 20)
- When no artworks are available, it should show no artworks are available instead of saying clear filter
| <img src="https://github.com/user-attachments/assets/958a5f97-e6fa-423b-a149-0c7160d20c01" /> | <img src="https://github.com/user-attachments/assets/c2430111-8f20-4313-9263-b73c1a54e22c" /> | 
- fix broken empty state of artworks on show screen - mounir
-
-
-
</details> …

fix: broken artworks empty state on show screen

---

src/app/Scenes/Artwork/Components/CertificateAuthenticity.tsx

This PR resolves https://www.notion.so/artsy/Extra-padding-or-header-on-the-modals-on-the-artwork-screen-13bcab0764a080e6bd3be0b5be85bbc7?pvs=4
This PR fixes the header on the attribution class screen
**Before**
___
**After**
- fix attribution class screen header on new navigation infra - mounir
-
-
-
</details>

fix: attribution class header

---

src/app/AppRegistry.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
src/app/Scenes/ViewingRoom/ViewingRoom.tsx

Prefetch viewing rooms on home screen.
- Prefetch viewing rooms on home screen - ole
-
-
-
</details>

feat: Prefetch viewing rooms on home screen

---

src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx

This PR comes as a follow-up to https://github.com/artsy/palette-mobile/pull/281
Here I am making the input uncontrolled. You can see the performance benefits of that [here](https://github.com/artsy/palette-mobile/pull/281)
- improve auth flow inputs performance - mounir
-
-
-
</details>

fix: auth flow performance

---

src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx

This PR resolves [https://www.notion.so/artsy/Android-Title-less-headers-with-shadows-in-Artwork-category-13bcab0764a08005beaed0ace78fa005?pvs=4] 
This PR removes the default bottom shadow from the navigation header on android. 
**Note:** It looks fine on iOS and it looks like our design system so I kept it there
-
-
- remove header shadow on android - mounir
-
</details>

fix: header shadow on android

---

ios/Podfile.lock

fixes podfile lock diff that many devs had
#nochangelog

fix: podfile lock diff

---

src/app/Components/AutosuggestResults/AutosuggestResults.tests.tsx
src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
src/app/Scenes/BottomTabs/BottomTabsButton.tests.tsx
src/app/Scenes/BottomTabs/BottomTabsNavigator.tests.tsx
src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx
src/app/Scenes/Search/Search.tsx
src/app/store/config/features.ts

This PR sets AREnableNewNavigation as ready for release.
-
-
-
- set AREnableNewNavigation as ready for release - mounir
</details>

chore: set AREnableNewNavigation as ready for release

---

docs/debugging.md
docs/generate_a_release_build_for_local_testing.md
docs/getting_started.md
package.json

This PR resolves [PHIRE-1348] 
Updates debugging docs to point to react native docs.
Also adds commands in `package.json`:
`yarn react-devtools` and `yarn start-dev` to access the new rn tools.
-
-
-
- update debugging docs 
</details>
[PHIRE-1348]: https://artsyproduct.atlassian.net/browse/PHIRE-1348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: debugging docs

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx

Resolves [Text missing on artwork grid items on the Artwork screen's](https://www.notion.so/artsy/Text-missing-on-artwork-grid-items-on-the-Artwork-screen-s-Other-works-by-section-iOS-variant-13ecab0764a08093affde5079e113e60?pvs=4)  
| --- | --- |
| <img width="301" alt="image" src="https://github.com/user-attachments/assets/8b306555-a73b-413a-ba72-94a1a370b95d"> |  <img width="301" alt="image" src="https://github.com/user-attachments/assets/72d71983-04ed-4825-88c0-151be1edebc6"> |
-  fix meta data is not shown at some artwork grids (ff AREnableNewSaveAndFollowOnArtworkCard)
-
-
-
</details> …

fix: remove redundant flex component

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsPromotionalCard.tsx

This PR resolves [https://www.notion.so/artsy/Android-extra-padding-for-My-Collection-insights-modal-13bcab0764a080aeaaa0c67686538bc5?pvs=4] 
This PR fixes an issue affecting my collection insights on Android
| <img src="https://github.com/user-attachments/assets/342c7e7a-d5d0-4fe3-b4cd-dba763ff1e5b" > | <img src="https://github.com/user-attachments/assets/b42e1ba6-3cdf-4f2f-94a9-71cbd6e9bfa0" >
| 
-
-
- my collection insights extra padding on android - mounir
-
</details>
[docs]: …

fix: my collection insights extra padding on android

---

src/app/Components/Tasks/Task.tests.tsx
src/app/Components/Tasks/Task.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
src/app/Scenes/HomeView/Sections/Section.tsx
src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionTasks.tests.tsx

This PR resolves [EMI-2174] 
This PR allows the refetching of the tasks in the home view
|---|---|
| <video src="https://github.com/user-attachments/assets/007ffbcf-e2bc-46af-9adc-a9b984dca079" /> | <video src="https://github.com/user-attachments/assets/ec02eb12-8130-400f-b1b5-b6dae2aafa19" /> |
- allow refetching of the home view tasks
-
-
-
</details>
[EMI-2174]: https://artsyproduct.atlassian.net/browse/EMI-2174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

fix(EMI-2174): Refetch tasks on the home view

---

package.json
src/app/Components/GlobalSearchInput/GlobalSearchInput.tsx
yarn.lock

This PR comes as a follow-up to the search bar on the home view. 
In this PR I increase the hitslop of the search bar to make interaction with it "cooler".
| <img src="https://github.com/user-attachments/assets/7b3fda79-f18f-45e8-a39d-02a0d9b21133" /> | <img src="https://github.com/user-attachments/assets/138f4d54-cf3d-4aa2-b1ee-6febfcaf1a91" /> | 
- increase search bar hitslop - mounir
-
-
-
</details>

chore: increase search button hitslop

---

src/app/Components/ArtworkRail/ArtworkRail.tsx

Reverts artsy/eigen#11142
see [this thread](https://artsy.slack.com/archives/C02BAQ5K7/p1732116471982649) for context
#nochangelog

chore(Revert): "refactor: replace prefetchFlashList with PrefetchFlatList on rails"

---

src/app/Components/GlobalSearchInput/GlobalSearchInputOverlayEmptyState.tsx

chore: update copy on search modal overlay

---

src/app/Scenes/Search/components/AutosuggestSearchResult.tsx

https://www.notion.so/artsy/Slight-delay-between-result-tap-and-navigation-animation-feedback-144cab0764a0803d83cfce399f1e40e6?pvs=4
In this PR, I remove the not needed anymore blur and timeout before navigating to the next screens. With the new navigation infra, we dismiss the keyboard after switching tabs by default
https://github.com/user-attachments/assets/33b9ff07-6879-456b-8547-b1e4acf43917
#nochangelog

chore: do not wait on search result tap

---

src/app/Components/Bidding/Screens/Registration.tests.tsx
src/app/Components/Bidding/Screens/Registration.tsx
src/app/Scenes/About/About.tests.tsx
src/app/Scenes/About/About.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tests.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
src/app/Scenes/Onboarding/OnboardingSocialPick.tests.tsx
src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
src/app/store/config/features.ts

This PR resolves [DIA-629] 
- This PR removes `AREnableNewTermsAndConditions` for real.
- It also suppresses some ESLint errors in the bidding registration test suite.
-
-
-
- Deprecated AREnableNewTermsAndConditions feature flag
</details>
[DIA-629]: https://artsyproduct.atlassian.net/browse/DIA-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(DIA-629): retire AREnableNewTermsAndConditions for real

---

src/app/Scenes/Inbox/Components/Conversations/NoMessages.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/NoMessages.tsx

This PR fixes the issue with the Explore Works link that was reported here in [Slack](https://artsy.slack.com/archives/C02BAQ5K7/p1732213594705919)
https://github.com/user-attachments/assets/71e036fd-b155-432c-895f-815de893b765
-
-
-
- fix explore works link on Inbox - mounir
</details>

fix: explore Works Link on Inbox

---

.circleci/config.yml

This PR attempts to fix the issue with the nightly job
#nochangelog
-
-
-
-
</details>

fix: attempt to fix nightly job

---

src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginWelcomeStep.test.tsx
src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginWelcomeStep.tests.tsx

This PR partially resolves [DIA-942] 
This PR adds tests for the behavior in the LoginWelcomeStep of the new auth flow. It was very difficult to mock the navigation, but now that I've figured it out for this step I hope the following steps are easier.
-
-
-
- Added tests for LoginWelcomeStep
</details>
[DIA-942]: https://artsyproduct.atlassian.net/browse/DIA-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(DIA-942): test auth2 login welcome step

---

src/app/store/config/features.ts

Set AREnableNewSaveAndFollowOnArtworkCard ready for release
-
-
-
- Set AREnableNewSaveAndFollowOnArtworkCard ready for release
</details>

chore: set AREnableNewSaveAndFollowOnArtworkCard ready for release

---

src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx

In this [PR](https://github.com/artsy/eigen/pull/11178): I updated the logic of showing/hiding the header to be matching react-navigation best practices. After testing, everything seems alright.
However, It turned out that metro was behind and I wasn't seeing the latest changes. 
It turned out that i updated the logic, without updating the method that relied on it. Which is what I am doing now.
https://github.com/user-attachments/assets/37b3a376-7d32-47ed-b830-3a0e38239385
-
-
-
-
</details>

fix: hide hidden header logic

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx

This PR resolves [ONYX-1396] 
Adjust SellWithArtsyRecentlySold rail card height
| --- | --- |
| ![image](https://github.com/user-attachments/assets/78c9e4cf-d389-467e-b09a-73929709ab35) | ![image](https://github.com/user-attachments/assets/383152ad-6468-49a1-abd4-47115cb7278b) |
- adjust SellWithArtsyRecentlySold rail card height
-
-
-
</details>
[ONYX-1396]: https://artsyproduct.atlassian.net/browse/ONYX-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

fix: adjust SellWithArtsyRecentlySold rail card height

---

src/app/Components/PrefetchFlashList.tsx
src/app/utils/queryPrefetching.ts
src/app/utils/useHideSplashScreen.ts
src/setupJest.tsx

Refactor and simplify query prefetching.
-
-
-
-
</details>

chore: Refactor and simplify query prefetching

---

.circleci/config.yml
ios/Podfile.lock
package.json
yarn.lock

Updates mapbox to latest to workaround bitcode issue with beta submissions: 
https://github.com/mapbox/mapbox-maps-ios/issues/2233
Going to merge since betas are currently blocked 🙈 but if any comments or changes wanted I will follow up!
-
-
-
- update mapbox to fix beta builds - brian 
</details>

fix(betas): update mapbox to fix bitcode submission issue

---

src/app/Scenes/Search/RecentSearches.tests.tsx
src/app/Scenes/Search/Search.tests.tsx
src/app/Scenes/Search/components/AutosuggestSearchResult.tests.tsx
src/setupJest.tsx

This PR comes as a follow-up to https://github.com/artsy/echo/pull/737 and fixes the broken tests

fix: broken new search tests

---

ios/Podfile.lock
package.json
yarn.lock

This PR upgrades `react-native-reanimated` to `3.16.3`. This should help us avoid some of the warning they introduce at `3.16.0`
**Context:** https://artsy.slack.com/archives/C02BAQ5K7/p1732707812868539?thread_ts=1731950095.965869&cid=C02BAQ5K7
-
-
-
- [minor] upgrade reanimated to 3.16.3
</details>

chore: upgrade reanimtaed to 3.16.3

---

.github/workflows/release.yml

Adds a automated releases on github for testing purposes - this will not work 100% but will verify that we are on the right track
-
-
-
-  add release gh action
</details>

feat: add release gh action

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx

Resolves issue reported on slack: https://artsy.slack.com/archives/C05EQL4R5N0/p1732719691127379 (Save and Follow CTAs are cut off)
| Before Artworks Rail | Before Previously Sold Rail | After Artworks Rail | After Previously Sold Rail | After Artworks Rail Android | After Previously Sold Rail Android |
| --- | --- | --- | --- | --- | --- |
| ![IMAGE 2024-11-28 11:24:41](https://github.com/user-attachments/assets/c5a25335-a82d-4252-ba1c-2fb04c337305) | ![IMAGE 2024-11-28 11:24:45](https://github.com/user-attachments/assets/74d55f33-a314-421e-ae8c-f3e7e476f8c9) | ![IMAGE 2024-11-28 11:22:34](https://github.com/user-attachments/assets/7e71450c-7b50-4b0b-967c-2db60e20651b) | ![IMAGE 2024-11-28 11:22:38](https://github.com/user-attachments/assets/5f76a027-a786-49c1-9f08-3b …

chore: support font scaling on artwork rail cards

---

src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx

|Before|After|
|---|---|
|![Screenshot_1732804895](https://github.com/user-attachments/assets/b041b35f-38f1-40e7-a8df-7235593cd5a6)|![Screenshot_1732804953](https://github.com/user-attachments/assets/bf4326e5-29ca-4b45-aae6-db0fa56c76e7)|
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 15 - 2024-11-28 at 15 48 06](https://github.com/user-attachments/assets/1df6947d-2a7b-4f39-a273-4cf4d699a205)|![Simulator Screenshot - iPhone 15 - 2024-11-28 at 15 48 05](https://github.com/user-attachments/assets/f508a018-5c5e-477d-8809-00c316bbf07d)|
-
-
- bottom sheet edit alert
- 
</details> …

fix: bottom sheet edit alert

---

.github/workflows/release.yml
.gitignore

Adds github release and changelog as notes to github everytime that a new submission is released
#nochangelog

feat: test out release with changelog noteS

---

.github/workflows/release.yml

- Adds the real submission tags
- Adds sentry monitoring links to changelog
#nochangelog

feat: gh action release

---

src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx

This PR resolves [ONYX-1415] 
Correct artwork count update on the Artist screen's artwork grid.
| --- | --- |
| ![Simulator Screenshot - iPhone 16 - 2024-11-29 at 09 28 24](https://github.com/user-attachments/assets/1d334ae7-0be1-4b1d-a3b1-90b71df12535)| ![Simulator Screenshot - iPhone 16 - 2024-11-29 at 09 26 04](https://github.com/user-attachments/assets/b3f2031b-e712-44ba-8d21-36a48aea9251)|
- Correct artwork count update on the Artist screen's artwork grid - ole
-
-
-
</details> …

fix: Correct artwork count update on the Artist screen's artwork grid

---

src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx

Removing an extra line of code...
Follow-up on https://github.com/artsy/eigen/pull/11214
#nochangelog
-
-
-
-
</details>

chore: remove -redundant line of code

---

ios/Podfile.lock
package.json
yarn.lock

Bumps react-native-image-crop-picker from 0.41.2 to 0.41.6
-
-
-
- Bumps react-native-image-crop-picker from 0.41.2 to 0.41.6
</details>

build(deps): bump react-native-image-crop-picker from 0.41.2 to 0.41.6

---

src/app/Scenes/Search/components/EntitySearchResults.tsx

This PR resolves [ONYX-1420] 
This adds bottom padding to search results in order to make the last item visible. "Top" results and artwork results look fine and don't need adjustment.
| --- | --- |
| ![Simulator Screenshot - iPhone 16 - 2024-12-03 at 11 01 32](https://github.com/user-attachments/assets/d8074156-952b-40c4-a750-8b685cc7ff3a)| ![Simulator Screenshot - iPhone 16 - 2024-12-03 at 10 59 53](https://github.com/user-attachments/assets/8649af1e-8134-42a1-b068-f3821b5d4baf)|
- Add bottom padding to search results - ole
-
-
-
</details> …

fix: Add bottom padding to search results

---

src/app/Navigation/AuthenticatedRoutes/Tabs.tsx

In this PR, I am improving the performance of the tab event.
While working on dev, I started investigating why is the transition between tabs slow. We are no longer using the old infra so it should be that bad. This led me to notice that the tabPress event function was being computed everytime and it affected the performance.
**Note:** on prod, the performance is fine. It's only on dev that we notice this.
https://github.com/user-attachments/assets/f5bde761-f18b-406c-8884-5f2ae7820d02
-
-
-
- improve tab press event performance - mounir
</details> …

chore: improve tab press event performance

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tsx

Use primary color for the saves count, adjust rail card height
| --- | --- |
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-12-03 at 16 53 12](https://github.com/user-attachments/assets/615cf295-9cbb-4fda-91e9-28987e66c6a6) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-12-03 at 16 50 37](https://github.com/user-attachments/assets/603024c1-e487-4667-a913-04345ced5ab7) |
- fix: use primary color for the saves count, adjust rail card height
-
-
-
</details>

fix: use primary color for the saves count, adjust rail card height

---

src/app/AppRegistry.tsx
src/app/Components/ArtsyWebView.tsx
src/app/Components/Containers/BidFlow.tsx
src/app/Components/Containers/RegistrationFlow.tsx
src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tests.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/UnlistedArtworksFAQScreen.tsx
src/app/Scenes/ArtworkList/ArtworkList.tsx
src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
src/app/Scenes/Fair/Components/FairHeader.tsx
src/app/Scenes/Fair/FairAllFollowedArtists.tests.tsx
src/app/Scenes/Fair/FairAllFollowedArtists.tsx
src/app/Scenes/Fair/FairArticles.tsx
src/app/Scenes/Inbox/Components/Conversations/PurchaseModal.tsx
src/app/Scenes/Inbox/ConversationNavigator.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
src/app/Scenes/PriceDatabase/PriceDatabase.tsx
src/app/Scenes/Sales/Sales.tsx
src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
src/app/Scenes/ViewingRoom/ViewingRoom.tests.tsx
src/app/Scenes/ViewingRoom/ViewingRoom.tsx
src/app/Scenes/ViewingRoom/ViewingRoomsList.tsx
src/app/routes.ts
src/app/system/navigation/navigate.tests.tsx

This PR is a follow-up to previous navigation infra improvements.
In this PR, I work on removing some custom prop that we use for defining screens safe edges: the famous `fullbleed`. This prop although is very intuitive to use. You first need to learn, then you would have to guess that you need to define it with your route **instead** of within the screen itself. Of course that led to it being very coupled to screens layout.
Soo, I removed its usage from the new navigation infra then I went through every screen that doesn't define `fullbleed` around 100 😄 and updated all the ones that broke.
The ideal `viewOptions` props that a screen would need, should be no props other than the default `screenOptions` from `react-navigation`
**Bonus:**
I aligned the navigation …

chore: deprecate fullbleed prop

---

src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx
src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
src/app/Scenes/MyCollection/hooks/useAddUserInterestArtists.ts

This PR resolves [ONYX-400] 
Automatically opt into sharing collected artists with galleries.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2024-12-05 at 16 02 27](https://github.com/user-attachments/assets/b17633af-e2a0-4e03-a9af-effa46b4b28b) |![Simulator Screenshot - iPhone 16 - 2024-12-05 at 16 01 16](https://github.com/user-attachments/assets/c0ae881f-0b90-4844-a2cb-e1231f2fa189) |
- Automatically opt into sharing collected artists with galleries - ole
- My Collection Add Artist Search screen layout fix - ole
-
-
-
</details> …

feat: Automatically opt into sharing collected artists with galleries and layout fix

---

src/app/system/devTools/DevMenu/DevMenu.tsx

Fixes broken dev menu due to extra char. 
#nochangelog
-
-
-
-
</details>

fix: erroneous char in devmenu #trivial

---

src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx

This PR fixes a bunch of bugs that happened due to the last navigation cleanup.
**Context:** https://artsy.slack.com/archives/C02BAQ5K7/p1733472979842869
-
-
-
- fix screen presentation issues - mounir
</details>

fix: screen presentation issues

---

.github/workflows/release.yml

Attempt to fix the gh action to match submissions with regex, previously it wasn't triggered with the `ios-*-submission` probably due to the complexity of the tag
#nochangelog

refactor: use regex #trivial

---

src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx

This PR resolves [EMI-2227] 
This PR attempts to solve HomeView Tasks sluggish animation by speeding it up a bit
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/16325c6c-f5f1-4c9c-8ef4-773090dc6301" /> | <video src="https://github.com/user-attachments/assets/274ca89c-f406-4e32-bb6d-c5abbef97742" /> |
| iOS | <video src="https://github.com/user-attachments/assets/01a5f25b-9305-42a6-9245-7086fa97b1f6" /> | <video src="https://github.com/user-attachments/assets/cb155395-ec0e-416f-a866-7c648bda067c" /> |
- update HomeView Tasks animation
-
-
-
</details> …

fix(EMI-2227): Attempt to fix tasks animation sluggishness

---

src/app/AppRegistry.tsx

This PR fixes some issues with the art quiz UI.
-
-
-
- hide header on art quiz - mounir
</details>

fix: hide header on art quiz

---

src/app/Scenes/Search/SearchArtworksGrid.tsx
src/app/Scenes/Search/SearchResults.tsx

Resolves https://www.notion.so/artsy/Search-results-artworks-is-missing-an-artwork-count-154cab0764a080258ceae7ed5c369cdf?pvs=4 
This PR adds the number of artworks to the Search artwork grid.
| | |
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2024-12-10 at 15 36 49](https://github.com/user-attachments/assets/37f3472c-46b2-40e9-9f22-a50cb68952cc) |![Simulator Screenshot - iPhone 16 - 2024-12-10 at 15 36 34](https://github.com/user-attachments/assets/a9047e19-fdd6-442d-b6d9-ed3f903916da) |
- Add number of artworks to Search artwork grid - ole
-
-
-
</details> …

feat: Add number of artworks to Search artwork grid

---

src/app/Components/Swipeable/Swipeable.tsx

This PR resolves [EMI-2201] 
This PR fixes sending multiple tracking events when swiping on a task
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/94c90ea6-0f9d-4ed6-93d4-7454696898ff" /> | <video src="https://github.com/user-attachments/assets/033647ca-1c00-4355-b432-0acc3d2ca662" /> |
| iOS | <video src="https://github.com/user-attachments/assets/a672be7b-1f6c-46bc-8197-29fba8950897" /> | <video src="https://github.com/user-attachments/assets/74b354de-85da-41f3-8059-59b058352021" /> |
- send only one analytics event on task swipe
-
-
-
</details> …

fix(EMI-2201): fix sending multiple analytics events on task swipe

---

src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/Containers/Inbox.tsx
src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
src/app/Scenes/Activity/Activity.tests.tsx
src/app/Scenes/Articles/Articles.tests.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
src/app/Scenes/MyProfile/MyProfile.tsx
src/app/Scenes/Search/Search.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/utils/index.tsx

**Context:** https://artsy.slack.com/archives/C05EQL4R5N0/p1733916954506419
TLDR;
In this PR, I worked on fixing the home view screen performance and make it more snappy. The time went from 300-500ms to 50-100ms.
**What led to this?**
- many more new home view components
- no memoisation in place
- we rolled back some virtualised lists improvements in this [PR](https://github.com/artsy/eigen/pull/11207) - which led to fixing some bugs on Android and iOS getting slower
**Bonus work:**
Follow react-navigation [optimisation tips](https://reactnavigation.org/docs/6.x/screen#getcomponent) for the main tabs. 
| <Video src="https://github.com/user-attachments/assets/0b8ecb83-0414-4a03-b2ef-251869317d16" /> | <Video …

fix: home view performance

---

src/app/Scenes/City/Components/FairEventSection/Components/FairEventSectionCard.tsx
src/app/Scenes/Inbox/Components/ActiveBids/ActiveBid.tsx
src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
src/app/Scenes/Inbox/Components/Conversations/Preview/Attachment/AttachmentPreview.tsx
src/app/Scenes/Inbox/Components/Conversations/Preview/Attachment/ImagePreview.tsx

This PR resolves [PHIRE-1411] 
Fixes a few broken images I missed in the OpaqueImageView migration. Mostly due to trying to pass pixel values via styled components to height and width.
- Image previews for attachments in convos
- Conversation images
- Fair card in city guide
- Active bid previews
<p>
assets/d7431006-4d88-4a11-a536-9168a3424e9c)
</p>
</details> 
- fix broken image layouts - brian 
-
-
-
</details>
[PHIRE-1411]: …

fix: broken image layouts

---

ios/Podfile.lock
src/app/Scenes/MyAccount/MyAccountDeleteAccount.tsx
src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx

https://platform.applause.com/company/13083/products/27879/community-issues/6695639
https://platform.applause.com/company/13083/products/27879/community-issues/669690
These broke with switch to uncontrolled inputs, probably worth a look at some more pages with multiple inputs to make sure all okay!
<p>
https://github.com/user-attachments/assets/5b857235-5e5e-40d5-b3a1-44a7fd1a9b8a
</p>
</details> 
- fix inputs persistence in add new card and delete account - brian 
-
- 
-
</details> …

fix: input clearing on selecting next field

---

src/app/Components/Bidding/Screens/CreditCardForm.tests.tsx
src/app/Components/Bidding/Validators/creditCardFormFieldsValidationSchema.ts

This PR updates the credit card form validation to disable the Save button if the credit card input is empty
> [!note]
> One caveat about this fix: The validation is on (the red message of "credit card is required") shows up when the user is typing the credit card info
|---|---|---|
| Android | <img width="407" alt="image" src="https://github.com/user-attachments/assets/1d28abcd-5c45-4b47-ad2f-3734d35fdafb" /> | <img width="407" alt="image" src="https://github.com/user-attachments/assets/069e8911-80d4-4872-9dd7-c34f8939a068" /> |
| iOS | <img width="407" alt="image" src="https://github.com/user-attachments/assets/b936914e-9d69-4e64-a223-df0771c9532d" /> | <img width="407" alt="image" src="https://github.com/user-attachments/assets/40e814b1-c361-457 …

fix: update credit card form validation

---

src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsEmptyTabs.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx

This PR fixes the bug reported here: https://artsy.slack.com/archives/C02BAQ5K7/p1734105398538419?thread_ts=1734104954.270129&cid=C02BAQ5K7
https://github.com/user-attachments/assets/8e833db1-a86b-404f-af42-2a6b2b9a0c2c
#nochangelog

fix: artwork quiz link back button

---

src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFromMyCollectionArtworks.tsx

Resolves [Notion card](https://www.notion.so/artsy/Start-selling-from-my-collection-no-artist-step-starts-with-add-title-step-15bcab0764a080eaa480e4f950633d17?pvs=4)
Navigate to the add artist step when starting submission
| --- | --- |
| https://github.com/user-attachments/assets/1b61c386-b0b4-420e-a93a-cbb4a55b64e0 | https://github.com/user-attachments/assets/7fcc7a5d-ffcc-4fdf-b7f0-5364f6ace12a |
- navigate to the add artist step when starting submission
-
-
-
</details>
[docs]: …

fix: navigate to the add artist step when starting submission

---

src/app/Components/ImageWithFallback/ImageWithFallback.tests.tsx

use preferred practice for test
#nochangelog 
#trivial

chore: preferred pattern for image tests #trivial #nochangelog

---

ios/Podfile.lock
src/app/Scenes/Onboarding/Auth2/AuthContext.tsx
src/app/Scenes/Onboarding/Auth2/__tests__/AuthContext.tests.tsx

This PR fixes a bug where double-tapping the back button on the password step of the auth flow crashes the app.
This happens because tapping back "pops" the last screen from a list of previous screens and sets it as the current screen, but we do not guard that operation against an empty list of previous screens. This PR solves that by not allowing the user to double-tap past the first screen in the auth flow.
| BEFORE | AFTER |
|----------|-------|
| https://github.com/user-attachments/assets/8c08b24b-3d74-4767-92ca-43ac2f9f9d87 | https://github.com/user-attachments/assets/93f22d74-58d0-40ec-aa0d-85c5a5674550 |
- Fixed a bug that could cause the authentication flow to crash
-
-
-
</details> …

fix(APPLAUSE-6697021): auth2 back button double tap crash

---

src/app/Components/ImageWithFallback/ImageWithFallback.tsx

Fixes missing img placeholder in cases where gallery doesn't have an image on `galleries for you`
|Before|After|
|---|---|
|iOS||
|![Simulator Screenshot - iPhone 15 - 2024-12-19 at 12 03 19](https://github.com/user-attachments/assets/589a1c5a-5647-45c5-aa22-63bf6254dbb5)|![Simulator Screenshot - iPhone 15 - 2024-12-19 at 12 02 56](https://github.com/user-attachments/assets/b6a79c33-dec1-4824-bd48-aa828da7c384)|
|Android||
|![Screenshot_1734606673](https://github.com/user-attachments/assets/bc5ee281-3d5f-43d0-846a-c73691638a21)|![Screenshot_1734606576](https://github.com/user-attachments/assets/c778324d-cad3-487b-a458-139c94c6cf15)|
- gallery placeholder height in case of no image 
-
-
- 
</details>
Need help with …

fix: gallery placeholder height in case of no image

---

Gemfile
Gemfile.lock

This PR downgrades fastlane to fix an issue with the Google Play rollout method that was mentioned in this [Github issue](https://github.com/fastlane/fastlane/issues/28995)
-
-
-
- downgrade fastlane to 2.225.0
</details>

fix(deps): Downgrade fastlane to 2.225.0

---

HACKS.md

Removes a few hacks entries for hacks no longer in use 🎉 !
-
-
-
- remove unused hacks entries - brian 
</details>

chore(cleanup): remove stale hacks entries

---

docs/debugging.md

Updates debugging doc links
#nochangelog

docs: update debugging doc links

---

src/app/Components/Buttons/InfoButton.tsx
src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
src/app/Scenes/Favorites/Favorites.tsx
src/app/Scenes/SavedArtworks/SavedArtworks.tsx
src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx

This PR resolves [ONYX-1458] 
Add information and guidance to the saves, follows and alerts screens. Used InfoButton component where possible, refactored InfoButton component extracting the modal into a separate component
https://github.com/user-attachments/assets/45f4563e-1cf5-45d3-babd-394a5fff7569
- add information and guidance to the saves, follows and alerts screens
-
-
-
</details>
[ONYX-1458]: https://artsyproduct.atlassian.net/browse/ONYX-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

feat(ONYX-1458): add information and guidance to the saves, follows and alerts screens

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
src/app/Scenes/Artwork/Components/ArtworkPrice.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkPrice.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/app/store/config/features.ts

This PR resolves [https://artsyproduct.atlassian.net/browse/EMI-2240]
Remove the AREnablePartnerOfferOnArtworkScreenfeature flag. Will follow up with Echo Pr as well.
-
-
-
- Remove the AREnablePartnerOfferOnArtworkScreenfeature flag
</details>

chore: Remove the AREnablePartnerOfferOnArtworkScreenfeature flag from Eigen

---

package.json
src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
src/app/Scenes/Favorites/Favorites.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tests.tsx
src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
yarn.lock

This PR resolves [ONYX-1458] 
Add tracking
- add tracking of the new info modal for Saves, Follows, Alerts screens
-
-
-
</details>
[ONYX-1458]: https://artsyproduct.atlassian.net/browse/ONYX-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-1458): add tracking

---

src/app/Scenes/Sales/Sales.tests.tsx

Removes faulty test 
#nochangelog

chore: remove flaky test

---

src/app/store/AuthModel.ts
src/app/utils/experiments/UnleashProvider.tsx
src/app/utils/experiments/unleashClient.ts

This PR resolves [PHIRE-1447] 
- Fetch unleash data **after** user logs in in order to respect the default stickiness for experiments
- Starts different unleash client for each user that logs in to prevent caching previous users variants / toggles
-
-
-
- fetch unleash toggles/variants after user has logged in
</details>
[PHIRE-1447]: https://artsyproduct.atlassian.net/browse/PHIRE-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fetch unleash toggles/variants after user has logged in

---

src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/HomeView/Components/ActivityRail.tests.tsx

Resolves https://artsy.slack.com/archives/C02BAQ5K7/p1736174715600129 
fix flaky Activity rail tests.
-
-
-
-
</details>

chore: fix flaky Activity rail tests

---

src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/store/config/features.ts

Avoid double spacing when hiding artwork in the artwork rail by moving the container with the padding inside the Disappearable component.
- Avoid double spacing when hiding artworks (tapping "Not interested" in long-press menu) in the "New for You" rail - ole
-
-
-
</details>

fix: Avoid double spacing when hiding artwork in rail

---

src/app/Navigation/routes.tsx
src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tsx

This PR fixes issues related to Add new artist screen.
**Before**
**After**
https://github.com/user-attachments/assets/e18f0fd9-ee2d-4edb-af52-e47aed9fb304
- fix new artist broken header - mounir
-
-
-
</details>

fix: add new artist broken header

---

.circleci/config.yml

Clears caches aggressively to fix betas
#nochangelog

chore: clear cache

---

.github/workflows/release.yml

This PR changes the changelog github action file to try to fix it
-
-
-
- attempt to fix generate changelog github action 
</details>

chore(github-actions): Update changelog Github action commands

---

.github/workflows/release.yml

This PR attempts to fix the issue with running `git fetch --tags` to limit it to the latest 300 tags
-
-
-
- attempt to fix the generate changelog github action 2.0
</details>

chore(github-actions): Update changelog Github action commands 2.0

---

.github/workflows/release.yml

Another attempt to fix the changelog github action command
-
-
-
- attempting to fix generate changelog github action 3.0
</details>

chore(github-actions): Update changelog Github action commands 3.0

---

.github/workflows/release.yml

This PR attempts to fix the generate changelog github action, attempt 4 😅 
-
-
-
- attempt to fix generate changelog github action 4.0
</details>

chore(github-actions): Update changelog Github action commands 4.0

---

src/app/Scenes/ArtworkLists/SavesTabHeader.tsx

Fix a typo noted by Joey here https://artsy.slack.com/archives/C01CAM2QS3U/p1736497206391209
#nochangelog
-
-
-
-
</details>

fix: fix typo

---

src/app/Scenes/HomeView/Components/RecommendedAuctionLotsRail.tsx
src/app/Scenes/Sales/Sales.tsx

This PR resolves [ONYX-1483] 
This PR resolves the flickering of the "Auction Lots for You" rail on the "Auctions" screen and improves the functionality of the "Watch lot" button in the long-press context menu.
https://github.com/user-attachments/assets/cfc96cd6-92fb-436b-a254-950173aa7692
- "Auction Lots for You" rail flickering fix on "Auctions" screen - ole
-
-
-
</details>
[ONYX-1483]: https://artsyproduct.atlassian.net/browse/ONYX-1483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

fix: Auction Lots for You rail flickering

---

src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx

This removes extra padding on Previously sold on Artsy rail.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-01-13 at 16 44 35](https://github.com/user-attachments/assets/d4b2a250-3437-47c4-950b-2e1ebb9151c0) |![Simulator Screenshot - iPhone 16 - 2025-01-13 at 16 47 03](https://github.com/user-attachments/assets/061790a9-72d3-4355-b919-d733f7b913d9) |
- Remove extra padding on "Previously sold on Artsy" artwork rail on Sell screen - ole
-
-
-
</details>

fix: Remove extra padding on Previously sold on Artsy rail

---

docs/debugging.md
docs/getting_started.md
package.json

This PR resolves [PHIRE-1462] 
Update debugging docs
#nochangelog
[PHIRE-1462]: https://artsyproduct.atlassian.net/browse/PHIRE-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: update debugging docs

---

docs/debugging.md

Super minor :) #nochangelog
-
-
-
-
</details>

chore: Update debugging.md

---

src/app/Components/Containers/Inbox.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
src/app/Scenes/Search/Search.tsx
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
src/setupJest.tsx

This PR resolves [PHIRE-1433] 
Sentry - add explicit TTID to all tab screens (for testing purposes now)
-
-
-
- add ttid to all tab screens 
</details>
[PHIRE-1433]: https://artsyproduct.atlassian.net/browse/PHIRE-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add ttid to all tab screens

---

src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx

Remove italic prop from title on artwork context menu.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-01-14 at 15 47 44](https://github.com/user-attachments/assets/68ce4311-5e3d-4d3f-9899-ecf9a766da93) |![Simulator Screenshot - iPhone 16 - 2025-01-14 at 15 51 02](https://github.com/user-attachments/assets/4bfa9603-8478-4a4a-9606-93d43a0b8b2a) |
-
-
-
-
</details>

fix: Remove italic prop from title on artwork context menu

---

src/app/Components/ContextMenu/ContextMenuArtworkPreviewCardImage.tsx

This makes the Artwork context menu max image height dependent on the screen height for smaller devices.
| --- | --- |
|![simulator_screenshot_0949A0F4-920D-44F0-A8CD-9EEC3518D9EE](https://github.com/user-attachments/assets/cb2dc5a8-b575-4199-a76e-da6f697b4577) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2025-01-15 at 13 48 15](https://github.com/user-attachments/assets/c8fedd43-1c6e-4c13-9e07-7db0f9a8985a)|
-
-
-
-
</details>

fix: Artwork context menu max image height for smaller screens

---

src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx

This PR resolves [ONYX-1488]
QA session turned up some blurry images in these artist rails on the home view:
| ![before](https://github.com/user-attachments/assets/c30b057c-d3d3-4f05-ac9b-d84445b554b9) | ![after](https://github.com/user-attachments/assets/f0ede6bf-88c8-4a6d-a3cd-cbac4939942e) | 
- Improve resolution of artist images on home screen
-
-
-
</details>
[ONYX-1488]: https://artsyproduct.atlassian.net/browse/ONYX-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

fix: ensure better resolution for ArtistCard images

---

ios/Artsy/App/ARAppNotificationsDelegate.m

This PR resolves [PHIRE-1477] 
Seems like we didn't have one important step in place to track the direct opens for Braze campaigns push notifications, after talking with the Braze support (we have are following the manual braze setup in eigen) they pointed us to one step of the guide that we missed (?) or was there before and got removed at some point (?) or changed between braze bumps (?). 
|Before|After|
|---|---|
|![b4](https://github.com/user-attachments/assets/86b59095-c7ad-4348-9309-e6b94388752e)|![after](https://github.com/user-attachments/assets/a9d6a1f0-4fc0-4449-b613-ed684b3c6d5b)|
This **_needs_** to be included on the next release.
Did we miss any other step that we need to have? i.e. I don't see anywhere in the native code where we handle foreground push for braze (we might …

fix: direct opens tracking for braze

---

src/app/Scenes/MyAccount/MyAccountEditPhone.tsx

Previously users were able to save an empty phone number - now they are not.
Fixes [this notion bug report](https://www.notion.so/artsy/Phone-Input-Collectors-can-save-the-phone-input-with-an-error-17ecab0764a080b4893fc2a7d24f5ad8?pvs=4) from mobile QA
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/4d64e73b-596c-46a3-95b2-3f4af6b896d6" width={400} />|<video src="https://github.com/user-attachments/assets/2c58da5b-9d14-4e6c-bf6a-a68cef2982b3" width={400} />| 
- prevent users from saving empty phone number
-
-
-
</details> …

fix: prevent users from saving empty phone number

---

ios/Artsy/App/ARAppNotificationsDelegate.m
ios/Podfile.lock
package.json
yarn.lock

Bumps Braze dependency to latest and adds forward push handling.
Co-authored-by: brainbicycle <brian.beckerle@artsymail.com>
Test thoroughly before merging
-
-
-
- bump braze + forward push handling
</details>

build(deps): bump braze + forward push handling

---

ios/Artsy.xcodeproj/project.pbxproj
ios/ArtsyWidget/FullBleed/FullBleed+View.swift
ios/Podfile

This PR is motivated by wanting to work on the iOS widget but struggling with all the availability checks. A lot has changed since we created our widget so I'm hoping to get it more modernized and this will help so that I don't have to have quite so many checks.
More on Slack:
https://artsy.slack.com/archives/C02BAQ5K7/p1737471720672939
/cc @artsy/amber-devs

chore: Bump minimum iOS version requirement

---

.circleci/config.yml

chore: refresh caches

---

src/app/Scenes/CompleteMyProfile/hooks/useCompleteProfile.ts

This PR resolves [PBRW-358] 
This PR fixes the "Save and Exit" buttons in the "Complete My Profile" flow.
| | |
| --- | --- |
|![Simulator Screenshot - iPhone SE (3rd generation) - 2025-01-22 at 14 24 29](https://github.com/user-attachments/assets/4f963e16-ee03-43e4-b5a5-9c3244da5bba) |![Simulator Screenshot - iPhone SE (3rd generation) - 2025-01-22 at 14 24 24](https://github.com/user-attachments/assets/18ceceba-fadd-4091-9e44-2cce47f261db) |
-
-
-
-
</details>
[PBRW-358]: …

fix: Complete My Profile flow "Save and Exit" buttons

---

src/app/Scenes/Fair/Fair.tsx

Remove cacheable from fair page to fix artworks not being returned. 
- remove cacheable flag from fairs page, fix artworks - brian, dejan, george, sultan, adam
-
-
-
</details>

fix: remove cacheable from fair page

---

src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/ArtworkListOfferSettingsView.tsx

This PR resolves [PBRW-342] 
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/7913ac6c-3c6c-4f79-927b-ddc22c7e600d" width="400" />|<video src="https://github.com/user-attachments/assets/b95d29bc-97c7-4409-950c-43adddcb421f" width="400" />|
- interaction with toggles messes with offer modal
-
-
-
</details>
[PBRW-342]: https://artsyproduct.atlassian.net/browse/PBRW-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: interaction with toggles messes with offer modal

---

ios/Podfile.lock
package.json
yarn.lock

Bumps react-native-keychain to latest
-
-
-
- bump react-native-keychain to latest
</details>

build(deps): bump react-native-keychain to latest

---

.circleci/config.yml

This PR resolves [PHIRE-1486] 
This job is failing and noisy because it doesn't support token auth, let's remove it for now.
-
-
-
- remove buggy license agreement job 
</details>
[PHIRE-1486]: https://artsyproduct.atlassian.net/browse/PHIRE-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove buggy license agreement check for now #trivial

---

src/app/Scenes/HomeView/HomeView.tsx

This PR fixes the back navigation on the art quiz post-onboarding
https://github.com/user-attachments/assets/5ffe737a-0789-4838-9358-e58d83a0d455
- fix back navigation on art-quiz results - mounir
-
-
-
</details>

fix: navigate to home on back press quiz

---

src/app/Scenes/Sale/Sale.tests.tsx
src/app/Scenes/Sale/Sale.tsx

This PR resolves [PBRW-375] 
Fix navigation on the cascade bidding auction screen
https://github.com/user-attachments/assets/fadadc1c-c229-4830-878e-0234b9e65bad
- fix navigation on the cascade bidding auction screen
-
-
-
</details>
[PBRW-375]: https://artsyproduct.atlassian.net/browse/PBRW-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(PBRW-375): navigation on the cascade bidding auction screen

---

src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx

This PR resolves [PHIRE-1492] 
Fixes skip button not working on the ArtQuizWelcome screen.
https://github.com/user-attachments/assets/95a33b94-fb61-4891-83fd-4e21069bd74d
- cannot skip onboarding art quiz
-
-
- 
</details>
[PHIRE-1492]: https://artsyproduct.atlassian.net/browse/PHIRE-1492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cannot skip onboarding art quiz

---

src/app/Scenes/MyAccount/MyAccountEditPhone.tsx

This PR resolves [PBRW-382] 
Fixes not being able to save valid numbers in account settings.
https://github.com/user-attachments/assets/86bfab25-d912-4c9d-9780-fcb4451c92cb
- fix not being able to save phone number in account settings - brian 
-
-
-
</details>
[PBRW-382]: https://artsyproduct.atlassian.net/browse/PBRW-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix logic for canSave

---

ios/Podfile.lock

fixes podfile diff
Feel free to run `cd ios && bundle exec pod update DoubleConversion glog --no-repo-update` to see if this persists before merging
#nochangelog

fix: podfile diff

---

docs/README.md
docs/routing.md
src/app/system/navigation/RouterLink.tsx

This PR adds some very basic documentation around routing and the new `RouterLink` component.
-
-
-
- 
</details>

chore: Add Routing and RouterLink docs

---

ios/Artsy.xcodeproj/project.pbxproj
ios/Podfile.lock

This PR updates some artifacts from a recent `git pull` and `yarn install:all`.
-
-
-
-
</details>

chore: commit artifacts that appeared in project after git pull && yarn install:all

---

src/app/store/config/features.ts

set AREnableProgressiveOnboardingAlerts readyForRelease to true
-
-
-
- set AREnableProgressiveOnboardingAlerts readyForRelease to true
</details>

chore: set AREnableProgressiveOnboardingAlerts readyForRelease to true

---

src/app/store/config/features.ts

make AREnableFramedFilter ready for release
- make AREnableFramedFilter ready for release - mounir
-
-
-
</details>

chore: make AREnableFramedFilter ready for release

---

src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx

I forgot to commit a few code review changes before merging #11439 so I am doing that here.
-
-
-
- Replaced EntityHeader with ArtistListItemContainer and removed magic numbers
</details>

fix: add code review fixes that i forgot to commit

---

src/app/store/config/features.ts

Set AREnableArtworkCardContextMenuAndroid ff as ready for release.
-
-
-
-
</details>

chore: Set AREnableArtworkCardContextMenuAndroid ff as ready for release

---

src/app/Components/FancySwiper/FancySwiper.tsx
src/app/Components/FancySwiper/FancySwiperCard.tsx
src/app/Components/FancySwiper/FancySwiperIcons.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

This PR allows users to swipe Infinite Discovery artwork cards in any direction by:
- Adding a `onSwipeAnywhere` prop to FancySwiperCard that is fired on a full swipe in any direction
This PR also sneaks in the following changes:
- Added `onSwipeUp` and `onSwipeDown` props to FancySwiperCard. These are not needed at the moment since, but it keeps the interface consistent.
- Added some documentation to animation code in FancySwiperCard.
- Removed unused GraphQL query fields.
https://github.com/user-attachments/assets/6770e8c5-6416-42a4-8e5c-fb0dae63e0d9
-
-
-
- Allow users to swipe FancySwiperCards in any direction
</details> …

feat(DIA-1103): allow users to swipe FancySwiperCards in any direction

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx

This PR resolves [DIA-1105]
Users can save artworks by tapping a ♡ icon while viewing artworks in Infinite Discovery. However, these artworks are all saved to the default list, so we want to display a toast that will allow them to select the list that they save artworks to. 
If the user saves an artwork to a list and then un-saves it, we should also show the list dialog.
<video src="https://github.com/user-attachments/assets/8dba2393-dfb7-4950-9de8-ab13f3bb3012" width="400px" />
<video src="https://github.com/user-attachments/assets/299fd57e-2172-4136-af85-7657b7e09c97" width="400px" />
- Infinite discovery: save artworks to lists - @nickskalkin 
-
-
-
</details> …

feat(dia-1105): infinite disco - save artworks to lists

---

src/app/Scenes/Inbox/Components/Conversations/Composer.tsx
src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx

This PR resolves [PBRW-398] [PBRW-436] 
Fixes issues with keyboardavoidingview on:
- inbox composer
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 16 Pro - 2025-02-04 at 16 38 47](https://github.com/user-attachments/assets/e6dc9f61-68ae-47e4-82a8-6db3274e3cb5)|![Simulator Screenshot - iPhone 16 Pro - 2025-02-04 at 16 38 24](https://github.com/user-attachments/assets/182fff63-4446-4d02-9dd5-a9ab88f58bad)|
|![Screenshot_1738681530](https://github.com/user-attachments/assets/a4f37fc0-44dc-497a-aa46-fb3dede45705)|![Screenshot_1738681457](https://github.com/user-attachments/assets/7cb0bdfe-a75e-4087-98d9-bbb8846ffc1c)|
- sell with artsy flow
|Android|After|
|---|---|
|![Screenshot_20250204-163621](https://github.com/user-attachments/assets/366d8331-c161-4870-ae4e-b708870dda7c)|![Scre …

fix: keyboardavoidingview issues

---

src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx

As discussed [here](https://www.notion.so/artsy/App-Progressive-onboarding-18bcab0764a08025acc8c06615af382c?p=190cab0764a080b68da6f2e56287d7d9&pm=s), dismiss alert-finish on modal close, so the user can proceed with the next onboarding step
Without this addition the dismiss action is called only of the user clicks on the tooltip itself or on the child element of the tooltip which is the Create Alert cta on the filters screen
- dismiss alert-finish tooltip on modal close (progressive onboarding)
-
-
-
</details>
[docs]: …

chore: dismiss alert-finish tooltip on modal close

---

src/app/Components/FancySwiper/FancySwiper.tsx
src/app/Components/FancySwiper/FancySwiperCard.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

This PR adds a shadow to the artwork cards in Infinite Discovery as they are being dragged.
| <img width="567" alt="Screenshot 2025-02-05 at 12 42 31 PM" src="https://github.com/user-attachments/assets/2e6b0d23-c467-4bbb-bb5d-98408fdb73ba" /> |  <img width="535" alt="Screenshot 2025-02-05 at 12 44 41 PM" src="https://github.com/user-attachments/assets/e4b79241-4142-40ec-b20b-7c7b3c66df89" /> |
-
-
-
- cast a shadow while an artwork card is being swiped in infinite discovery
</details>
[docs]: …

feat(DIA-1101): cast a shadow while an artwork card is being swiped

---

src/app/Scenes/Sales/Components/SaleListActiveBids.tests.tsx
src/app/Scenes/Sales/Components/SaleListActiveBids.tsx
src/app/Scenes/Sales/Sales.tsx

This PR resolves [ONYX-1510] 
This PR adds your active bids as a new rail to the sales screen.
- add your active bids to the sales screen - mounir
-
-
-
</details>
[ONYX-1510]: https://artsyproduct.atlassian.net/browse/ONYX-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add your active bids section to sales screen

---

src/app/Components/Buttons/InfoButton.tsx

This sets the InfoButton's modal maximum content size so all the content is visible when scrolling (on iOS).
| --- | --- |
| ![Simulator Screenshot - iPhone 16 - 2025-02-07 at 10 45 12](https://github.com/user-attachments/assets/ea639714-0f1a-4fb7-b6f1-ac1d5f576102)| ![Simulator Screenshot - iPhone 16 - 2025-02-07 at 10 54 26](https://github.com/user-attachments/assets/78e4a0e4-e106-4aa9-9498-9ee7477b1b7d)|
-
- Fix Market Stats info modal content size on Artist's Auction Results screen - ole
-
-
</details>
[docs]: …

fix: Info button modal max content size for iOS

---

src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/app/Components/ArtworkFilter/Filters/FramedOptions.tests.tsx

This PR resolves https://www.notion.so/artsy/mWeb-last-filter-group-signed-remains-hidden-when-expanded-18ccab0764a080c3afa6cb099e8b3f1c?pvs=4
This PR aligns the experience of the framed filter with Web.
- Rename **Frame** to **Framed**
- Move framed to be the last filter
https://github.com/user-attachments/assets/286a2a8b-d397-4850-ac1b-3395d5ac5382
- align framed experience  with web - mounir
-
-
-
</details>

chore: align framed experience with web

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx

This PR resolves [PBRW-424] 
Fixes another instance of android not truncating text properly
|Before|After|
|---|---|
|![Screenshot_1738931782](https://github.com/user-attachments/assets/ad2ef65b-fffe-47b2-9f0d-390c0e5cce87)|![Screenshot_1738931795](https://github.com/user-attachments/assets/dee89d20-237c-45be-950b-6c344e26d2a2)|
-
-
- fix truncated title on artworkgriditem
-
</details>
[PBRW-424]: https://artsyproduct.atlassian.net/browse/PBRW-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

fix: truncated title on artworkgriditem

---

src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscovery.tests.tsx

This PR resolves [DIA-1106] 
I've changed the 'back' and 'exit' text for infinite discovery swiping to icons. The ArrowBackIcon was added to palette-mobile [here](https://github.com/artsy/palette-mobile/pull/301)
https://github.com/user-attachments/assets/a5bce8ae-46be-4192-a327-9c1a3005e425
-
-
-
- changed the 'back' and 'exit' text for infinite discovery swiping to icons
</details>
[DIA-1106]: https://artsyproduct.atlassian.net/browse/DIA-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

feat(DIA-1106): updating 'back' and 'exit' icons for infinite discovery

---

fastlane/metadata/android/en-US/full_description.txt
fastlane/metadata/android/en-US/title.txt
fastlane/metadata/en-US/description.txt
fastlane/metadata/en-US/keywords.txt
fastlane/metadata/en-US/name.txt

Update app metadata to remove mentions of sell or consign. 
- change app metadata to remove mentions of sell - brian 
-
-
-
</details>

chore: app metadata updates #trivial

---

scripts/utils/exportNotionTicketsToJira.ts

This PR resolves [PHIRE-1568] 
Updates our notion export script to add the bug priority and components field to be better citizens of the shared bug workflow. 
When the fields have not been filled will throw an error. 
-
-
-
- update notion export to use shared bug fields - brian, george
</details>
[PHIRE-1568]: https://artsyproduct.atlassian.net/browse/PHIRE-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(tools): update notion export to use shared bug fields

---

src/app/Components/ArtworkLists/useArtworkListsToast.ts
src/app/Components/Toast/ToastComponent.tsx
src/app/Scenes/Artwork/Components/ArtworkPrice.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

https://artsyproduct.atlassian.net/browse/DIA-1134
https://artsyproduct.atlassian.net/browse/DIA-1138
https://artsyproduct.atlassian.net/browse/DIA-1137
This PR makes the following fixes:
- Increase buttons hitslop
- add haptic feedback to buttons
- make the price not selectable
- update the saved artwork toast copy
- infinite discovery issues - mounir
-
-
-
</details>

fix: infinite discovery issues

---

package.json
yarn.lock

This PR upgrade palette-mobile version to latest after reanimated upgrades
-
-
-
-
</details>

chore: upgreade palette version to latest

---

package.json
src/app/Components/CreditCardField/CreditCardField.tsx
src/app/Components/Select/Components/SelectButton.tsx
src/app/Scenes/HomeView/Components/HomeViewSectionCardsCard.tsx
yarn.lock

Because this PR removes `INPUT_VARIANTS`, we had to replace them as well in Eigen to make sure nothing breaks. 
-
-
-
- refactor input variants style logic - mounir
</details>

chore: refactor input variants

---

src/app/utils/useHideSplashScreen.ts

Fixes [this](https://play.google.com/console/u/0/developers/6449739225222972501/app/4975007939329818983/pre-launch-report/details?tab=stability&artifactId=4860029332795025915) google prelaunch report issue.
The issue was that android logged out users were seeing a white screen right after the splash screen - prob because of navigation not being ready.
-
-
-
- prelaunch report issue about splashscreen 
</details>

fix: prelaunch report issue about splashscreen

---

src/app/Components/FancySwiper/FancySwiper.tsx
src/app/Components/FancySwiper/FancySwiperCard.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

https://artsyproduct.atlassian.net/browse/DIA-1140
https://artsyproduct.atlassian.net/browse/DIA-1143
We want to prevent users from swiping artwork cards up and down, but still allow them to swipe artwork cards diagonally to the left or right. As a result, we now check whether a swipe is 60º (or π/3 in code) above or below the horizontal axis to be considered a valid swipe.
| Explanation | Demonstration |
|-------------|----------------|
| ![Simulator Screenshot - iPhone 16 Plus - 2025-02-12 at 13 41 10](https://github.com/user-attachments/assets/147deeec-e8b2-4dc0-84ed-073710b15392) | https://github.com/user-attachments/assets/e4f2dbf6-f1cd-4815-8d1c-03803cd2b619 |
It also addresses two other issues:
- Make the scaling animation on the second artwork card more prominent …

feat(DIA-1143): prevent users from swiping artwork cards up or down

---

package.json
yarn.lock

This PR upgrades palette mobile to the latest version. This is required to fix issues with the input
-
-
-
-
</details>

chore: upgrade palette mobile

---

src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx

This PR resolves [PHIRE-486] 
|Before|After|
|---|---|
|iOS||
|![Simulator Screenshot - iPhone 16 Pro - 2025-02-17 at 16 14 23](https://github.com/user-attachments/assets/7c7a99fa-30e8-4541-b2bb-2741c9a2a3fb)|![Simulator Screenshot - iPhone 16 Pro - 2025-02-17 at 16 13 40](https://github.com/user-attachments/assets/d5c57c3c-4efd-43e4-b188-86bbcabf3d81)|
|Android||
|![Screenshot_20250217-163308](https://github.com/user-attachments/assets/80f6ce67-3591-4dff-b5e7-78a0b0763d75)|![Screenshot_20250217-163136](https://github.com/user-attachments/assets/a346b285-effe-483f-81be-420284d20631)|
- fix margins on browseSimilarScreen 
-
-
-
</details> …

fix: margins on browseSimilarScreen

---

src/app/system/devTools/DevMenu/Components/NavigateTo.tsx

Fixes navigate to input in dev menu android that was unusable.
We might need to check why this is not working as expected on our palette input at some point
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/86203446-6ddc-4461-a0e3-7dd516b59367" width="300" />|<video src="https://github.com/user-attachments/assets/c0c1442b-60b9-484c-9593-0022085f2e6d" width="300" />|
-
-
-
- android dev menu navigateTo input
</details>

fix: android dev menu navigateTo input

---

scripts/utils/doctor.js

Was unintentionally erroring out when determining the installed XCode version and the versions mismatch.
**Expected**
```
🟡 Xcode is installed but the version is incorrect. Installed: 16.2, Expected: 16.1
```
**Actual**
```
ReferenceError: desiredVersion is not defined
at checkXcodeVersion (/Users/devon/code/artsy/eigen/scripts/utils/doctor.js:244:103)
at main (/Users/devon/code/artsy/eigen/scripts/utils/doctor.js:287:3)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
🔴 Xcode is not installed or there was an error determining the version.
```
- fix yarn:doctor script
</details> …

chore: fix yarn:doctor script

---

src/app/Components/ArtistListItem.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetTabs.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

This PR resolves [DIA-1025]
Adds tracking events (except bottom sheet) from [this doc](https://docs.google.com/spreadsheets/d/1cLefOz5i9uvC3JAeXFqG6_5U-4hdgY7CBElZ4nDjGSU/edit?gid=827314299#gid=827314299).
-
-
-
- tracking for infinite discovery - @nickskalkin 
</details>
[DIA-1025]: https://artsyproduct.atlassian.net/browse/DIA-1025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-1025): infinite discovery tracking

---

src/app/Scenes/Onboarding/Auth2/components/AuthBackground.tsx

This PR sets the text color on the onboarding to white regardless of the theme. 
- auth flow image text color - mounir
-
-
-
</details>

fix: text color on onboarding welcome screen in dark mode

---

ios/Artsy/App/ARAppDelegate.mm

This PR resolves [PBRW-483] 
Accidentally were using the staging key for prod after the react native keys migration which broke push notifications on iOS.
-
- fix braze push notifications - brian 
-
-
</details>
[PBRW-483]: https://artsyproduct.atlassian.net/browse/PBRW-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: wrong key for braze prod

---

src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheet.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetHandle.tsx

This PR fixes some infinite discovery dark mode issues
| <img src="https://github.com/user-attachments/assets/27069cb4-1fc0-47b0-83ff-4dccd1eb9674" /> | <img src="https://github.com/user-attachments/assets/c951b432-657b-437a-ab17-be84b5851e21" /> | 
- fix dark mode issues on infinite discovery - mounir
-
-
-
</details>

fix: dark mode issues on infinite discovery

---

ios/Artsy.xcodeproj/project.pbxproj

Fix project.pbxproj file diff
#nochangelog

chore: fix project.pbxproj diff

---

src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingOfferSettings.tsx

This PR fixes the progressive onboarding issues on the saves page on Android.
| iOS | Android (real device) |
| <video src="https://github.com/user-attachments/assets/8ceb3eef-7d1f-4775-ac4a-674e8926455f" /> | <video src="https://github.com/user-attachments/assets/a97805a6-fd8d-46d3-b2fe-ca549debe9f5" /> | 
- 
-
- fix progressive onboarding on android - mounir
-
</details>

fix: progressive onboarding on android

---

src/app/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx

This PR refactors the make offer button to remove an old issue affecting DX
| ![Simulator Screenshot - iPhone 16 Pro - 2025-02-12 at 12 12 23](https://github.com/user-attachments/assets/868e1005-0691-4194-b1e8-c8fad7b351b4) | ![Simulator Screenshot - iPhone 16 Pro - 2025-02-12 at 12 19 23](https://github.com/user-attachments/assets/4ef8d35f-1932-4075-8771-f81d08e2038e) | 
**Before**
**After**
-
-
-
- refactor make offer button - mounir
</details>

chore: refactor make offer button

---

android/app/src/main/AndroidManifest.xml

- This PR allows us to deep link users to `/infinite-discovery` on android. On iOS, this is working already
#nochanges

chore: add deep link to infinite discovery on android

---

src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx

This PR updates the placement of button on the `HomeViewSectionCard`.
#nochanges

chore: update entry point button placement

---

src/app/Navigation/routes.tsx
src/app/Scenes/MyProfile/DarkModeSettings.tsx
src/app/Scenes/MyProfile/DevicePrefsModel.ts
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/app/store/__tests__/migration.tests.ts
src/app/store/migration.ts
src/app/system/devTools/DevMenu/Components/NavigateTo.tsx
src/app/system/devTools/DevMenu/DevMenu.tsx

This PR updates the dark mode settings menu and updates its logic to follow best practices.
- Now we have a simple menu to select just one option
- For better DX, one can now set the appearance from the dev menu
- Refactor and simplify logic of dark mode to be based on a state machine instead of booleans
| Dark Mode Screen | Dev Menu |
| ![Simulator Screenshot - iPhone 16 Pro - 2025-02-21 at 13 34 22](https://github.com/user-attachments/assets/f9d14231-9c79-4694-9341-4b76439448e4) | ![Simulator Screenshot - iPhone 16 Pro - 2025-02-21 at 13 43 56](https://github.com/user-attachments/assets/4f6f99e0-9f85-4a75-b365-0e1ee053c079) | 
- update dark mode settings menu - mounir
-
-
-
</details> …

chore: update dark mode settings menu

---

src/app/store/InfiniteDiscoveryModel.ts

This PR resolves [DIA-1149]
Only store the 1000 most recent "discovered" artwork IDs in local storage to prevent infinite local storage growth
-
-
-
- infinite discovery - Only store the 1000 most recent "discovered" artwork IDs in local storage to prevent infinite local storage growth - @nickskalkin 
</details>
[DIA-1149]: https://artsyproduct.atlassian.net/browse/DIA-1149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-1149): store up to 1000 discovered artworks in local storage

---

src/app/Components/Buttons/InfoButton.tsx

This PR resolves [ONYX-1559] 
Fix padding on the info modal
| --- | --- |
| ![image](https://github.com/user-attachments/assets/badf7037-ebf2-4a4d-9ff5-cbfe44d97bb4) | ![image](https://github.com/user-attachments/assets/4322aa64-8739-4285-887d-5f0b55c71fe7) |
- fix padding on the info modal
-
-
-
</details>
[ONYX-1559]: https://artsyproduct.atlassian.net/browse/ONYX-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-1559): fix padding on the info modal

---

scripts/deploys/check_build_status
scripts/deploys/check_version_synced
scripts/deploys/deploy-beta-android
scripts/deploys/deploy-beta-both
scripts/deploys/deploy-beta-ios

If you try to push a beta and the version in app.json is out of date this will fail but only after going through all the steps to test, build and deliver that beta which takes ~40 min. This checks if the version in the branch is in sync with main before proceeding with the beta to catch this quickly. 
Also moved the build in progress check to a separate script. 
-
-
-
- add version sync check to beta deploys - brian 
</details>

chore(tools): add version check to beta scripts, minor cleanup

---

src/app/Scenes/Artwork/Components/ArtworkPartnerOfferNote.tsx

This PR resolves [PBRW-503] 
This PR fixes an issue with the partner offer note in the artwork screen extending over the note space
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/961401bf-c8a0-482c-9adc-832d8c63e33c) | ![image](https://github.com/user-attachments/assets/74afe8b6-2b61-4a9e-94ff-3c465e8bd55a) |
| iOS | ![image](https://github.com/user-attachments/assets/d96f42c7-7728-49b3-8cfb-f8428c123cbd) | ![image](https://github.com/user-attachments/assets/00f24cac-b696-4188-bcd5-9637a1ac0b2f) |
- fix an issue with the partner offer note on the artwork screen
-
-
-
</details> …

fix(PBRW-503): Fix artwork partner offer note issue

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx

Track quick links experiment from home view component and make sure we track both `control` and `experiment` variants
Slack thread: https://artsy.slack.com/archives/C05EQL4R5N0/p1740581450376129?thread_ts=1740151277.447429&cid=C05EQL4R5N0
- fix - track quick links experiment from home view component
-
-
-
</details>

fix: track quick links experiment from home view component

---

ios/Podfile.lock
src/app/Components/ArtistListItem.tsx
src/app/Components/AutosuggestResults/AutosuggestResults.tsx
src/app/Scenes/Collection/Components/FeaturedArtists.tests.tsx
src/app/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
src/app/Scenes/Search/components/AutosuggestSearchResult.tsx

This PR resolves [DIA-1002] 
This change allows for the `coverArtwork` image to be prioritized when returning artist search results, and falls back to `imageUrl` if there is no `coverArtwork`. 
**Before:**
(Search Thumbnail):
(Artist Page Cover Artwork):
**After:** 
(Search Thumbnail matches artist page cover artwork):
-
-
-
- Allowing for coverArtwork for avatar images on artist search results
</details>
[DIA-1002]: https://artsyproduct.atlassian.net/browse/DIA-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

fix(DIA-1002): Allowing for coverArtwork for avatar images on artist search results

---

src/app/Scenes/Fair/FeaturedFairsScreen.tsx
src/app/Scenes/HomeView/Components/ShowsRail.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionFairs.tests.tsx

- add missing href to the featured fairs home view component
since we have the featured fairs screen now why not navigating to it from the homeview
- adjust the header on the featured fairs screen 
the header had an extra space under it, it had to be removed and replaced with a padding of the flatlist component
- adjust featured fairs screen and add href to featured fairs homeview component
-
-
-
</details>

chore: adjust featured fairs screen and add href to featured fairs homeview component

---

src/app/Scenes/Onboarding/Auth2/components/AuthBackground.tsx
src/app/Scenes/Onboarding/OnboardingWelcome.tsx

This PR resolves [PBRW-567] 
This PR removes "sell" from the auth screen
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/32a33cae-5185-47ce-b374-d94102718911) | ![image](https://github.com/user-attachments/assets/5bb6f855-849a-4d56-a16b-b3ba50128ea3) |
| iOS | ![image](https://github.com/user-attachments/assets/9093bc70-8ce6-4137-8451-0f7fc6e9e002) | ![image](https://github.com/user-attachments/assets/2028cb01-091d-47b7-9aa7-642dbc9b097d) |
- Remove "sell" from the auth screen
-
-
-
</details> …

fix(PBRW-567): Remove "sell art" from the login screen

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
src/app/store/InfiniteDiscoveryModel.ts
src/app/store/__tests__/migration.tests.ts
src/app/store/migration.ts
src/app/system/devTools/DevMenu/Components/DevTools.tsx

**_Updated description March 5th_**
This PR resolves [DIA-1150] [DIA-1152] 
This PR is a placeholder for the infinite discovery onboarding.
Once we get the interaction specs, we can add it here directly.
https://github.com/user-attachments/assets/14b07d14-9c74-42e9-a214-1df90a3b3d74
- add infinite discovery onboarding skeleton - mounir
-
-
-
</details>
[DIA-1150]: https://artsyproduct.atlassian.net/browse/DIA-1150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

feat: add infinite discovery onboarding skeleton

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/store/config/features.ts

Prepare quick links for release - something that slipped 🙃 
-
-
-
- Prepare quick links for release
</details>

feat: prepare quick links for release

---

src/app/Components/ArtistFollowButton.tsx
src/app/Components/PartnerFollowButton.tsx
src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryAboutTheWorkTab.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetFooter.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryMoreWorksTab.tsx
src/app/system/analytics/AnalyticsContext.tsx

This PR resolves [DIA-1067]
Adding tracking to some of Infinite Discovery bottom sheet controls:
- Follow / unfollow an artist
- Follow / unfollow a Gallery
- Contact Gallery button
- Save an artwork in Other works tab
- Purchase button
- Make offer button
-
-
-
- infinite discovery - bottom sheet tracking - @nickskalkin 
</details>
[DIA-1067]: https://artsyproduct.atlassian.net/browse/DIA-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-1067): infinite disco bottom sheet tracking (demo)

---

ios/Artsy/App/ARAppNotificationsDelegate.m
ios/Podfile.lock
package.json
yarn.lock

This reverts commit 1621e2ee8a46e2fdf9455399a11a0b12c010473c.
This reverts #11415
-
-
-
- revert braze sdk bump - brian 
</details>

chore: revert bump braze + forward push handling

---

src/app/Navigation/routes.tsx

This PR resolves [DIA-1171] 
This PR fixes an issue happening to users when they are dismissing the infinite discovery
**FYI:** I will merge this so it makes it to the QA later. Happy to address feedback later
https://github.com/user-attachments/assets/1ca3f165-2303-4ca1-93d3-0d9f95b40ed1
- prevent users from seeing rewinded cards on infinite discovery - mounir
-
-
-
</details>
[DIA-1171]: https://artsyproduct.atlassian.net/browse/DIA-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

fix: prevent users from seeing rewinded cards

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx

This PR resolves [DIA-1200] 
- Adjust the animation to follow guidelines from design
- Allow users to dismiss the onboarding where they press on the screen
https://github.com/user-attachments/assets/2000d49b-4f17-48c5-bc1b-08105c99db8f
-
-
-
-
</details>
[DIA-1200]: https://artsyproduct.atlassian.net/browse/DIA-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: infinite discovery onboarding issues

---

src/app/Navigation/routes.tsx

This PR resolves [DIA-1170] 
This PR disables gestures on infinite discovery screen
- disable gestures on infinite discovery - mounir
-
-
-
</details>
[DIA-1170]: https://artsyproduct.atlassian.net/browse/DIA-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(InfiniteDiscovery): disable gestures on infinite discovery

---

src/app/Navigation/routes.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

This PR resolves [DIA-1204] 
- Improve the first time open performance of the infinite discovery
- Send the first artwork as seen (instead of the last one in the array)
https://github.com/user-attachments/assets/1ca0a37f-b361-47ef-8911-e78c68c50725
- fix send top artwork as seen - mounir, carlos, adam
-
-
-
</details>
[DIA-1204]: https://artsyproduct.atlassian.net/browse/DIA-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(InfiniteDiscovery): send top artwork as seen

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheet.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetBackdrop.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetFooter.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetHandle.tsx
src/app/Scenes/InfiniteDiscovery/hooks/useBottomSheetAnimatedStyles.ts

This PR resolves: [DIA-1178], [DIA-1185], [DIA-1186]
This PR fixes some outstanding issue with the backdrop. Mainly the following:
- Update the handle to be a arrow instead of a dash
- Update the padding to be matching the design preferences
- Add animation to the new arrow
- Add opacity animation to swipe up for more details
- Fix issues with the footer padding on small devices
- Make sure that the status bar color matches the backdrop opacity
- fix infinite discovery bottom sheet issues - mounir, adam
-
-
-
</details>
[docs]: …

fix(InfiniteDiscovery): infinite discovery bottom sheet issues

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
src/app/Scenes/InfiniteDiscovery/Components/Swiper/AnimatedView.tsx

This PR resolves [DIA-1201] by reintroducing artwork card rotation and rounded corners that got removed during recent work. It is similar to #11660 but uses the optimized AnimatedView instead.
- Reintroduce artwork card rotation and rounded corners
-
-
-
</details>
[DIA-1201]: https://artsyproduct.atlassian.net/browse/DIA-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-1201): reintroduce artwork card rotation and rounded corners

---

src/app/Components/Toast/types.ts
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

This PR resolves [DIA-1189] and [DIA-1198] 
Updated the saved artworks toast and made some other tiny copy fixes. 
-The header now says "Discover Daily" instead of "Discovery"
-The onboarding animation now says "Welcome to Discover Daily" instead of "Discovery"
-The Saved Artworks toast and link to saved folder have been updated to align with latest design.
-Homeview design updated (Metaphysics changes here: https://github.com/artsy/metaphysics/pull/6501)
-
-
-
- Updated the saved artworks toast and made some other tiny copy fixes. 
</details> …

fix(DIA-1189): Additional copy and creative fixes for Discovery Daily

---

package.json
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetFooter.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryMoreWorksTab.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
yarn.lock

This PR resolves: [DIA-1127], [DIA-1172], []
This PR adds and fixes some missing analytics events raised by Louis here: https://artsy.slack.com/archives/C05EEBNEF71/p1741717435032189?thread_ts=1741639324.698749&cid=C05EEBNEF71
| Screenshot |
|--------|
| <img src="https://github.com/user-attachments/assets/1fc728b8-2f6a-4db6-89fa-47baa883b29e" /> |
| <img width="361" alt="Screenshot 2025-03-12 at 18 11 15" src="https://github.com/user-attachments/assets/bdfd1ce2-5ed5-4d15-ae30-cee39c764890" /> |
| <img width="365" alt="Screenshot 2025-03-12 at 18 10 41" src="https://github.com/user-attachments/assets/11887e29-06df-48f7-a371-8c20b8f0e104" /> |
| <img src="https://github.com/user-attachments/assets/18c5755b-0cbe-4717-b2c7-aa32541d441b" /> |
| <img …

chore: add missing analytics events to infinite discovery

---

src/app/Components/ArtistFollowButton.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryAboutTheWorkTab.tsx

This PR addresses the analytics comments raised by Luis here https://artsy.slack.com/archives/C05EEBNEF71/p1741877421571539?thread_ts=1741639324.698749&cid=C05EEBNEF71
| Screenshot |
|--------|
| <img  width="300" src="https://github.com/user-attachments/assets/6a6e23b7-9a12-4dc1-b3a3-7567fafcf6c1" /> |
| [<img  width="300" src="https://github.com/user-attachments/assets/6a6e23b7-9a12-4dc1-b3a3-7567fafcf6c1" />](https://github.com/user-attachments/assets/720475a6-d9d8-4238-9d18-ac3fc3cb1888) | 
#nochangelog

chore(InfiniteDiscovery): address analytics

---

src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx

This PR updates the back button behaviour on Android. The behaviour now is as follows:
- If the user has no previous cards - the back button does nothing
- if the user has previous cards - rewind previous cards
| Scenario | Video |
| Card gets dismissed on back button press | <video src="https://github.com/user-attachments/assets/da131c76-05cc-4035-aa4a-bc607241b72e" /> |
| Do not dismiss screen on back button press | <video src="https://github.com/user-attachments/assets/11aec045-3b49-4905-8afb-7baf14f58d2c" /> | 
-
-
- improve back button behaviour on infinite discovery - mounir
-
</details> …

feat(InfiniteDiscovery): update back button behaviour on android

---

src/app/utils/experiments/UnleashProvider.tsx

This PR resolves [ONYX-1615]
Small change to follow Unleash documentation's [recommendation](https://docs.getunleash.io/reference/sdks/javascript-browser#:~:text=PS!,loosing%20important%20events)
`client.start()` should follow all the `client.on("…")` event handler setup.
Not necessarily expecting this to solve our current issues, but seems worthwhile in any case.
-
-
-
- Change Unleash start logic to match best practice
</details>
[ONYX-1615]: https://artsyproduct.atlassian.net/browse/ONYX-1615?atlOrigin=eyJ …

fix: Unleash client start sequence

---

src/app/Components/RetryErrorBoundary.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheet.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

This PR brings some optimisations to our queries and error boundary logic.
- Show a nice error within the infinite discovery bottom sheet
- Allow users to close the screen if an error comes
| <img src="https://github.com/user-attachments/assets/b6a484ab-5e72-4f1f-91e6-9a8ddacd1350" /> | <img alt="Screenshot 2025-03-14 at 10 23 28" src="https://github.com/user-attachments/assets/8cc5e4b4-98e0-4770-945e-fc3da8c0471f" />
|
- improve error boundary logic within infinite discovery - mounir
-
-
-
</details> …

feat(InfiniteDiscovery): improve error boundary logic

---

src/app/store/config/features.ts

this PR sets infinite discovery feature flag as ready for release
#nochangelog

feat: set infinite discovery feature flag as ready for release

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
src/app/system/devTools/DevMenu/DevMenuWrapper.tsx

This PR increases the duration between two consecutive touches.
- decrease interaction duration between taps - mounir
-
-
-
</details>

chore(InfiniteDiscovery): decrease interaction duration between taps

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheet.tsx

This PR resolves [DIA-1217] 
We reset the tabs once the top artwork changed but the remaining state of the footer was kept, this PR fixes that.
Before
https://github.com/user-attachments/assets/0207837c-11fe-4803-81f9-60e0257dcde1
After
https://github.com/user-attachments/assets/6a6cb9ed-ca08-477d-a2c0-0abc5acc680f
- fix: infinite disco resets footer visibility given top artwork changed
-
-
-
</details>
[DIA-1217]: https://artsyproduct.atlassian.net/browse/DIA-1217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

fix(InfiniteDiscovery): resets the footer visibility to true given top artwork changed

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx

This PR makes sure that only the header part of the artwork is tappable instead of just the image.
https://github.com/user-attachments/assets/bc2753da-6e81-4831-9605-a399b550376e
- fix(infinite-discovery): make only artwork image tappable - mounir
-
-
-
</details>

fix: make only artwork image tappable

---

src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx

Prefetch home view navigation pill links.
****After*:***
https://github.com/user-attachments/assets/513eda5b-ef74-49b4-850d-aff1f68f015f
**Before:**
https://github.com/user-attachments/assets/f9e1c0eb-824e-418d-9dbb-ec54b03215d2
-
-
-
-
</details>

feat: Prefetch home view navigation pill links

---

src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx

Updating this component to take in the default values from palette-mobile. 
-
-
-
- Updating this component to take in the default values from palette-mobile. 
</details>

fix: using default values for hitSlop on Touchable components 

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/system/flags/experiments.ts

Add a non-visible experiment to test variant assignment from a multi-variant setup.
Backed by the Unleash [onyx_internal-testing-experiment](https://unleash.artsy.net/projects/default/features/onyx_internal-testing-experiment) feature flag configuration.
-
-
-
- add a non-visible internal testing experiment, powered by Unleash
</details>

chore: setup internal testing experiment

---

ios/Artsy/App/ARAppDelegate.mm
ios/Artsy/App/ARAppNotificationsDelegate.h
ios/Artsy/App/ARAppNotificationsDelegate.m
ios/ArtsyTests/App_Tests/ARAppNotificationsDelegateTests.m

This reverts commit f302133dbccb7bf39105827d07096ec2c40626fb.
This PR comes as an action item on #inc-218
**Context:** https://artsy.slack.com/archives/C08HWB3FR1N/p1742312970877799
https://github.com/artsy/eigen/pull/11642
- update iOS in-app push notification style
-
-
-
</details>

chore: revert revert - update iOS in-app push notification style

---

HACKS.md
ios/Artsy.xcodeproj/project.pbxproj
ios/Artsy/App/ARAppDelegate.mm
ios/Artsy/App/ARAppNotificationsDelegate.m
ios/Artsy/ArtsyUIButtons/ARButtonSubclasses.m
ios/Artsy/Extraction/ARSpinner.m
ios/Artsy/Resources/Artsy-Bridging-Header.h
ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRSetupViewController.m
ios/Artsy/View_Controllers/ARVIR/Views/ARInformationView.m
ios/Artsy/View_Controllers/Util/ARNavigationController.m
ios/Artsy/View_Controllers/Util/Logging/ARLogger.h
ios/ArtsyTests/App_Tests/ARAppNotificationsDelegateTests.m
ios/Podfile
ios/Podfile.lock

This PR reverts the modular headers changes Revert
**Context:** https://artsy.slack.com/archives/C08HWB3FR1N/p1742312970877799
**Previous PR**: https://github.com/artsy/eigen/pull/11638
-
- modular headers
- 
-
</details>

chore: revert revert modular headers

---

ios/Artsy/App/ARAppNotificationsDelegate.m
ios/Podfile.lock
package.json
yarn.lock

Old PR: https://github.com/artsy/eigen/pull/11641
-
-
-
-
</details>

chore: revert revert bump braze version + forward push

---

src/app/Scenes/Activity/ActivityEmptyView.tsx
src/app/Scenes/Activity/components/AlertNotification.tsx
src/app/Scenes/Activity/components/ArticleFeaturedArtistNotification.tsx
src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
src/app/Scenes/Activity/components/ViewingRoomPublishedNotificationsList.tsx
src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx

This PR resolves [ONYX-1626] 
Prefetch all links on Activity screen.
- Prefetch all links on Activity screen - ole
-
-
-
</details>
[ONYX-1626]: https://artsyproduct.atlassian.net/browse/ONYX-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Prefetch all links on Activity screen

---

src/app/Scenes/HomeView/HomeView.tsx
src/app/system/flags/experiments.ts

Follow up to https://github.com/artsy/eigen/pull/11714.
Accidentally used a snake-cased key where the pattern is `{team}_my-experiment-flag-key`.
-
-
-
- chore: update key of onyx internal testing experiment
</details>

chore: update key of onyx internal testing experiment

---

app.json

chore: set app version to 8.68.0

---

src/app/Components/ArtistListItemShort.tsx
src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/BrowseMoreRailCard.tsx
src/app/Components/LatestAuctionResultsRail.tsx
src/app/Components/MenuItem.tsx
src/app/Components/PartnerEntityHeader.tsx
src/app/Components/PartnerListItemShort.tsx
src/app/Components/ShowItem.tsx
src/app/Scenes/About/About.tsx
src/app/Scenes/ArtworkLists/ArtworkListItem.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
src/app/Scenes/MyAccount/MyAccount.tsx
src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkArticles.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
src/app/Scenes/MyProfile/MyProfilePayment.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/app/Scenes/PriceDatabase/components/PriceDatabaseBenefits.tsx
src/app/Scenes/Sale/Components/SaleArtworkListItem.tsx
src/app/Scenes/SaleInfo/SaleInfo.tsx
src/app/Scenes/Sales/Components/SaleListItem.tsx
src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
src/app/Scenes/Search/components/CityGuideCTA.tsx

Adresses [ONYX-1493](https://artsyproduct.atlassian.net/browse/ONYX-1493) 
This PR replaces all remaining `Touchable` components that call `navigate` with `RouterLink` (to enable prefetching).
There are still a few buttons and text links that use `navigate` for navigation. I will address them in another PR.
- Replace remaining Touchable components with RouterLink for navigation (prefetching) - ole
-
-
-
</details>
[ONYX-1493]: https://artsyproduct.atlassian.net/browse/ONYX-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

feat: Replace remaining Touchables with RouterLink for navigation

---

src/app/Navigation/routes.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tsx

Adresses [ONYX-1594](https://artsyproduct.atlassian.net/browse/ONYX-1594) 
This fixes **Profile** tab route prefetching by adding the correct queries to routes.tsx and updating the cache config and fetch policy. 
- Fix **Profile** tab route prefetching - ole
-
-
-
</details>
[ONYX-1594]: https://artsyproduct.atlassian.net/browse/ONYX-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: "Profile" tab prefetching

---

src/app/utils/masonryHelpers/index.tsx

This PR resolves [ONYX-1629] 
* [Slack Thread](https://artsy.slack.com/archives/C02BAQ5K7/p1742550961154439)
This increases the artwork grid's page size and "end reached threshold" to improve scroll performance.
**Before and after:**
https://github.com/user-attachments/assets/b19628d3-b160-4a4a-8f03-f854ee4a2bbd
- Increase Artwork grid page size and "end reached" threshold (performance improvement) - ole
-
-
-
</details>
[ONYX-1629]: https://artsyproduct.atlassian.net/browse/ONYX-1629?atlOrigin=eyJpIjoiNWRkNT …

fix: Increase Artwork grid page size and threshold

---

.circleci/config.yml

Removes remains of `react-native-config` from ci 
-
-
-
- remove react-native-config from ci
</details>

build(ci): remove react-native-config remains

---

ios/Podfile.lock
package.json
yarn.lock

Bumps flashlist to latest and palette-mobile PR with the latest flashlist
-
-
-
- bumps flashlist to latest
</details>

build(deps): bumps flashlist and palette-mobile to latest

---

package.json
yarn.lock

This PR bumps @gorhom/bottom-sheet from 5.0.5 to 5.1.2.
-
-
-
- Bump @gorhom/bottom-sheet from 5.0.5 to 5.1.2
</details>

chore: bump @gorhom/bottom-sheet from 5.0.5 to 5.1.2

---

src/app/Components/PartnerListItemShort.tsx

Resolves https://artsy.slack.com/archives/C02BAQ5K7/p1742823104963939?thread_ts=1742823069.316889&cid=C02BAQ5K7
This fixes a `PartnerListItemShort` layout issue that was introduced with https://github.com/artsy/eigen/pull/11720.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-03-24 at 15 00 02](https://github.com/user-attachments/assets/c5a6f97e-f8ba-42a1-b2b3-60d3a47158f6) | ![Simulator Screenshot - iPhone 16 - 2025-03-24 at 14 59 55](https://github.com/user-attachments/assets/c67a9e71-3d1f-4865-848a-d9d7e5bd7321)|
- fix PartnerListItemShort layout on Infinite Discovery screen - ole
-
-
-
</details> …

fix(DIA-1243): PartnerListItemShort layout

---

src/app/Navigation/routes.tsx
src/app/Scenes/Artist/SearchCriteria.tsx
src/app/Scenes/ArtistShows/ArtistShows.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/AuctionResults/AuctionResultsForArtistsYouFollow.tsx
src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
src/app/Scenes/Collection/Components/FullFeaturedArtistList.tsx
src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
src/app/Scenes/MyProfile/MyProfilePayment.tsx
src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
src/app/Scenes/SavedSearchAlert/queries/getAlertByCriteria.ts
src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx

This PR resolves [ONYX-1630](https://artsyproduct.atlassian.net/browse/ONYX-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Related PR: https://github.com/artsy/eigen/pull/11744
This PR refectors more screens to use Relay's network policy instead of cache config (to enable prefetching).
-
-
-
- Refactor screens to use network policy instead of cache config - ole
</details>
[ONYX-1630]: https://artsyproduct.atlassian.net/browse/ONYX-1630?atlOrigin=eyJpIjoiNWRk …

chore: Refactor screens to use network policy instead of cache config

---

src/app/Scenes/Favorites/Components/CollapseWithTitle.tsx
src/app/Scenes/Favorites/Components/FavoritesLearnMore.tsx
src/app/Scenes/Favorites/Favorites.tsx

This PR resolves [ONYX-1608] 
This PR adds Learn More bottom sheet to Favorites Tab.
| <video src="https://github.com/user-attachments/assets/e7c5ef77-d0f4-4d99-849c-eea364ef6227" /> | <video src="https://github.com/user-attachments/assets/f932fd8d-f9b1-4d1b-8a08-f830a844d2f2" /> |
- feat add Learn more bottom sheet to Favorites Tab - mounir
-
-
-
</details>
[ONYX-1608]: https://artsyproduct.atlassian.net/browse/ONYX-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …

feat: add Learn more bottom sheet to Favorites tab

---

src/app/Scenes/Artwork/Artwork.tsx

This PR resolves [EMI-2347] 
This PR removes the lot's estimated value if the bidding on that lot has closed
|---|---|---|
| Android | <img width="417" alt="image" src="https://github.com/user-attachments/assets/39d417c5-4296-48d7-91ae-f254a2c5a2d1" /> | <img width="417" alt="image" src="https://github.com/user-attachments/assets/ee0c03d3-5299-40d4-bd8b-6aebb6be0fbc" /> |
| iOS | ![image](https://github.com/user-attachments/assets/1d767b4d-44cd-498a-b9cc-61bf9106b063) | ![image](https://github.com/user-attachments/assets/42d20bbc-d8ff-4887-92c3-53665693970d) |
- Remove Lot's estimated value when the bidding has closed
-
-
-
</details>
[app state …

fix(EMI-2347): Remove estimated values when bidding has closed

---

package.json
src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Favorites/Favorites.tsx
src/app/Scenes/Favorites/FollowsTab.tsx
yarn.lock

This PR updates the items bottom sheet radio button styles to match the designs
| <img src="https://github.com/user-attachments/assets/db93934e-bdaa-4f60-9eba-cedc723cdce8" /> | <img src="https://github.com/user-attachments/assets/8d1ec0c5-150a-4426-a3f8-183d880fe278" /> | 
- update follows radio buttons - mounir
-
-
-
</details>

chore: update follows radio buttons

---

ios/Podfile.lock
package.json
yarn.lock

Bumps react-native from 0.76.5 to 0.76.7 to take advantage of the fixes of these patch releases:
- [0.76.6](https://github.com/facebook/react-native/releases/tag/v0.76.6)
- [0.76.7](https://github.com/facebook/react-native/releases/tag/v0.76.7)
-
-
-
- bump react-native to 0.76.7 
</details>

build(deps): bump react-native to 0.76.7

---

src/app/Components/PartnerListItemShort.tsx
src/app/Scenes/Favorites/Components/FavoritesLearnMore.tsx
src/app/Scenes/Favorites/Components/FollowedArtists.tsx
src/app/Scenes/Favorites/Components/FollowedGalleries.tsx
src/app/Scenes/Favorites/Components/FollowedShows.tsx
src/app/Scenes/Favorites/Favorites.tsx
src/app/Scenes/Favorites/FollowsTab.tsx
src/app/Scenes/Favorites/SavesTab.tsx

- adjust margins in the header
- adjust the More Info modal
- adjust Artists list (avatar size and separator component)
- adjust Galleries list (avatar size and separator component)
| --- | --- |
| <video width="300" src="https://github.com/user-attachments/assets/98350455-172e-463f-bea2-3b4cc198a953" /> | <video width="300" src="https://github.com/user-attachments/assets/d8139716-3b05-40a1-9b47-675f4bd6beb1" /> |
- UI adjustments to the Favorites hub screens
-
-
-
</details>
[docs]: …

fix: UI adjustments to the Favorites hub screens

---

src/app/Scenes/About/About.tsx
src/app/Scenes/MyProfile/Components/MyProfileHeader.tsx
src/app/Scenes/MyProfile/MyProfile.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/app/store/config/features.ts
src/app/system/devTools/useSetDevMode.tsx

This PR resolves [ONYX-1638] [ONYX-1639] 
This PR adds a skeleton to facilitate the upcoming settings tab redesign.
Please note: the patterns here are not set in stone, a lot of them might change as we start adding stuff, the goal from this is to enable doing the future work in parallel.
https://github.com/user-attachments/assets/ca8480f6-8222-4cd7-8fc2-0e4089e3e91a
-  prepare settings tab redesign - mounir
-
-
-
</details>
[ONYX-1638]: https://artsyproduct.atlassian.net/browse/ONYX-1638?atlOrigin=eyJpIjoiNWR …

feat: prepare settings tab redesign

---

src/app/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx

This PR resolves [PHIRE-1666] 
Fixes erroneous analytics from triggering
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/e0ce7957-a118-4c44-abac-f918c515d674" width="300" />|<video src="https://github.com/user-attachments/assets/e23fc772-080b-4679-9ec9-154b9e8de88f" width="300" />|
-
-
-
- fix erroneous grid tracking
</details>
[PHIRE-1666]: https://artsyproduct.atlassian.net/browse/PHIRE-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

refactor(ContextGridCTA): convert class component to functional component and fix tracking

---

src/app/Scenes/MyProfile/MyProfileSettings.tsx

This PR resolves [ONYX-1580] 
This PR adds tracking to account settings
https://github.com/user-attachments/assets/2af5cad5-e5b6-463c-96c7-c2418e672f1d
-
-
-
- add tracking to account settings - mounir
</details>
[ONYX-1580]: https://artsyproduct.atlassian.net/browse/ONYX-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add tracking to account settings

---

src/app/Navigation/routes.tests.ts
src/app/Navigation/routes.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tsx

Co-authored-by: Mounir Dhahri <soussouheros@gmail.com>
Remove new favorites route, hide activity if ff is enabled
Follow up on https://github.com/artsy/eigen/pull/11686 and https://github.com/artsy/eigen/pull/11791 and https://github.com/artsy/eigen/pull/11792 😅 
- Remove new favorites route, hide activity if ff is enabled
-
-
-
</details>

chore: remove new favorites route, hide activity if ff is enabled

---

src/app/Components/ContextMenu/ContextMenuArtwork.tsx
src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tests.tsx

Resolves [PBRW-610](https://artsyproduct.atlassian.net/browse/PBRW-610) 
Fixes broken artwork context menu on Android and adds tests for it.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-03-28 at 16 11 46](https://github.com/user-attachments/assets/c9abc75a-012b-442f-81f5-a7ff308f20b2) |![Simulator Screenshot - iPhone 16 - 2025-03-28 at 16 11 33](https://github.com/user-attachments/assets/c254d822-17c7-45db-af8a-510a82116e69) |
- Fix broken artwork context menu on Android - ole
-
-
-
</details>
[docs]: …

fix(PBRW-610): Broken artwork context menu on Android

---

ios/Podfile.lock
package.json
yarn.lock

Bumps react-native-blurhash to latest
#nochangelog

build(deps): bump react-native-blurhash to latest

---

ios/Podfile.lock
package.json
yarn.lock

This PR resolves [PHIRE-1677] 
Bumps react-native-share to latest includes a bunch of bug fixes.
|---|---|---|
| Android | ![Screenshot_20250331-121508](https://github.com/user-attachments/assets/e923a33c-7b78-43d6-99ae-8c3657272517) | ![Screenshot_20250331-122715](https://github.com/user-attachments/assets/cf2f38a9-9c21-402e-a87e-27bd501027b4) |
| iOS | ![IMG_4041](https://github.com/user-attachments/assets/ce607168-69c1-4601-be62-a076732906ef) | ![IMG_4042](https://github.com/user-attachments/assets/d90aaafe-c716-471d-873d-3696e8ebd804) |
-
-
-
-  bump react-native-share to latest
</details> …

build(deps): bump react-native-share to latest

---

src/app/Components/AbandonFlowModal.tests.tsx
src/app/Components/AnimatedBottomButton.tests.tsx
src/app/Components/CountrySelect.tests.tsx
src/app/Components/Disappearable.tests.tsx
src/app/Components/EmbeddedCarousel.tests.tsx
src/app/Components/Expandable.tests.tsx
src/app/Components/FadeIn.tests.tsx
src/app/Components/FiveUpImageLayout.tests.tsx
src/app/Components/FullScreenLoadingImage.tests.tsx
src/app/Components/HeaderButton.tests.tsx
src/app/Components/LoadFailureView.tests.tsx
src/app/Components/MenuItem.tests.tsx
src/app/Components/PageWithSimpleHeader.tests.tsx
src/app/Components/PaginationDots.tests.tsx
src/app/Components/PartnerBanner.tests.tsx
src/app/Components/Stack.tests.tsx
src/app/Components/SwitchMenu.tests.tsx
src/app/Components/TabEmptyState.tests.tsx
src/app/Components/ThreeUpImageLayout.tests.tsx
src/app/Components/TouchableRow.tests.tsx
src/app/Components/WithCurrentTime.tests.tsx

Using [Claude](https://claude.ai/) to add basic tests for all components that currently lack any tests.
Most tests are quite simple, but they will at least ensure that all components render without issues.
-
-
-
- Add simple tests for all components that currently lack tests - ole
</details>

chore: Add basic tests for all components that currently lack tests

---

src/app/Scenes/Favorites/Components/Alerts.tsx
src/app/Scenes/Favorites/Components/AlertsList.tests.tsx
src/app/Scenes/Favorites/Components/AlertsList.tsx
src/app/Scenes/Favorites/Components/AlertsSortByModal.tsx
src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
src/app/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx

Co-authored-by: dariakoko <nargle30@gmail.com>
This PR resolves [ONYX-1650] 
This PR fixes the high priority issues reported inside the alerts view screen.
| Test Case | iOS | Android |
|--------|--------|--------|
| Artwork delete fixes - Low image quality - delete button on tap | <video src="https://github.com/user-attachments/assets/ec565331-fbf3-4413-9045-11fee2a40a3c" width="400" /> | <video src="https://github.com/user-attachments/assets/fc850c47-eb3f-4c88-99fd-c18bf5173221" width="400" /> |
| - Bottom sheet modal Radio button block - Title no more bold -  | <img src="https://github.com/user-attachments/assets/3245f199-e81a-4043-b504-bf4e825aa4f5" width="400" /> | <img src="https://github.com/user-attachments/assets/bf2b09f4-9327-4cca-ae91-6692c971b448" width="400" /> | …

fix: alerts view screen fixes

---

docs/routing.md

Update and fix routing docs.
-
-
-
- Update and fix routing docs - ole
</details>

chore: Update and fix routing docs

---

package.json
yarn.lock

bumps pod-install to latest
#nochangelog

build(deps): bump pod-install to latest

---

src/app/Scenes/Collection/Screens/CollectionArtworks.tsx

Do not allow creating alerts on collections (like New This Week). Backend currently doesn't support alerts without `artist_id` being a part of search criteria.  `shouldShowCreateAlertButton` got there by mistake.
|---|---|
| <img src="https://github.com/user-attachments/assets/67d28335-ce4a-4ce2-84e7-47de58dc15c4" /> | <img src="https://github.com/user-attachments/assets/94f17db1-55c3-427a-8c25-97e3cbe76a86" /> |
- fix: do not allow creating alerts on collections - @nickskalkin 
-
-
-
</details>
[docs]: …

fix: do not allow creating alerts on collections

---

src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx

This PR comes after the react-navigation update. It fixes padding issues on android
|---|---|---|
| Android | <img src="https://github.com/user-attachments/assets/983707af-83d3-41fb-bd61-426776157318" width="400" /> | <img src="https://github.com/user-attachments/assets/c4559e78-330b-4233-9112-1f7691f60bf5" width="400" /> |
-
-
- broken top padding on create alert and filter modals - mounir
-
</details>

fix: broken top padding on modals

---

ios/Podfile.lock
package.json
src/app/Navigation/Navigation.tsx
src/app/system/errorReporting/setupSentry.ts
yarn.lock

This PR resolves [PHIRE-1688] 
Updates sentry to fix compilation error on Xcode 16.3
https://github.com/getsentry/sentry-react-native/issues/4715
-
-
-
- update sentry to fix compilation error - brian 
</details>
[PHIRE-1688]: https://artsyproduct.atlassian.net/browse/PHIRE-1688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update sentry to fix compilation error

---

fastlane/sentry_fastlane.rb

Updates the sentry release monitoring links that we post in #practice-mobile after we submit the apps to point to the production environment.
Noticed that we were taking the devs before to the same url but without a pre-selected environment that caused slight confusion if you check the metrics without selecting the environment.
-
-
-
- update sentry slack release links to point to production
</details>

build(releases): update sentry url to production

---

src/app/Components/AnimatableHeader/AnimatableHeader.tsx
src/app/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
src/app/Components/NavigationHeader.tsx
src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/TimeSince.tsx

This PR resolves [ONYX-1635](https://artsyproduct.atlassian.net/browse/ONYX-1635)
* Related palette-mobile PR: https://github.com/artsy/palette-mobile/pull/325
This replaces the `black30` text color with `black60` for higher contrast. The `color30` is intended for background use only, as the contrast is too low ([GitHub](https://github.com/artsy/palette/blob/95eada21eac3e38756cf9e8a40b11dae04b21fcd/packages/palette-tokens/src/themes/v3.tsx#L41)).
| --- | --- |
| ![Simulator Screenshot - iPhone 16 - 2025-04-07 at 12 49 38](https://github.com/user-attachments/assets/1b2a7a23-2f7e-4cf5-aa0c-84feb27c0f93) |![Simulator Screenshot - iPhone 16 - 2025-04-07 at 12 49 24](https://github.com/user-attachments/assets/700cfcdd-0e88-4077-b7c4-0f5e2a73cace) |
| --- | --- |
|![Simulator …

fix: Replace black30 text color with black60 for higher contrast

---

src/app/Scenes/ArtworkLists/ArtworkLists.tsx
src/app/Scenes/Favorites/Components/FavoritesLearnMore.tsx
src/app/Scenes/Favorites/SavesTab.tsx

This PR resolves [ONYX-1652] 
This PR fixes the issue with the favorites tab wrapper
- fix favorites tab Wrapper issues - mounir
-
-
-
</details>
[ONYX-1652]: https://artsyproduct.atlassian.net/browse/ONYX-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: favorites tab Wrapper issues

---

src/app/Scenes/Favorites/Components/FavoritesLearnMore.tsx

This PR updates the copy on the favourites modal

chore: update copy on favourites

---

src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsPayment.tsx

This PR removes the Apple Pay logo
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/68c393e9-d7c3-4515-9fd0-ef359879aa2d) | ![image](https://github.com/user-attachments/assets/8e56c21e-bafd-49ae-9e8b-3030e5cfd0ba) |
| iOS | ![image](https://github.com/user-attachments/assets/68200180-490f-4713-820b-0859de119a33) | ![image](https://github.com/user-attachments/assets/aaa7e21d-a701-404c-bb4d-8dde9cd4e75c) |
- Remove Apple Pay logo from order history
-
-
-
</details>
[docs]: …

fix: remove Apple Pay Mark Icon

---

ios/Podfile.lock
package.json
yarn.lock

This PR resolves [PHIRE-1713] 
Fixes this sentry [**crash** ](https://artsynet.sentry.io/issues/6427732630/events/2401229464454d7db05805d7f972b145/) by bumping to latest `react-native-bootsplash`. 
In [this issue](https://github.com/zoontek/react-native-bootsplash/issues/637) they mention that this crash should not persist in versions 6.2.0 or above.
Didn't add screenshots since the issue is non reproducible.
-
-
-
- bootsplash sentry crash 
</details>
[PHIRE-1713]: …

fix: bootsplash sentry crash report

---

package.json
src/app/Scenes/Favorites/Components/FollowedArtists.tsx
src/app/Scenes/Favorites/Components/FollowedGalleries.tsx
src/app/Scenes/Favorites/useFavoritesTracking.ts
yarn.lock

Add TappedFollowsGroup event
Document with the tracking data: https://docs.google.com/spreadsheets/d/1WCwrSR9DgHiWYNuMEWNX6NefsGgtg36aN81-gP5gGy8/edit?gid=0#gid=0
| Artist | Gallery |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c8159fe2-e6b6-4d47-a984-d6d6f7eca4d4) | ![image](https://github.com/user-attachments/assets/0d37e0fb-ea1f-4535-b98f-6e616b320c0b) |
- add TappedFollowsGroup event
-
-
-
</details>

chore: add TappedFollowsGroup event

---

src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
src/app/Scenes/ArtworkList/ArtworkList.tsx
src/app/Scenes/Favorites/Components/FollowedArtists.tsx
src/app/Scenes/Favorites/Components/FollowedGalleries.tsx
src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx

Address comments raised by data after QAing of the Favorites tab tracking 
https://artsy.slack.com/archives/C05EQL4R5N0/p1744308674546949?thread_ts=1742927066.401229&cid=C05EQL4R5N0
- 
-
-
- address favorites tracking comments
</details>

fix: address favorites tracking comments

---

src/app/Scenes/Favorites/Favorites.tsx

This PR addresses this comment https://github.com/artsy/eigen/pull/11890#discussion_r2039528171
#nochangelog

chore: add comment on navigation emittence

---

.circleci/config.yml

Abstracts cache keys to parameters in order to upgrade only one string instead of two in order to avoid breaking caching of workflows and jobs. 
-
-
-
- abstract cache keys to parameters / ci
</details>

build(CI): abstract cache keys to parameters

---

src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

This PR increases the size of the share icon that we are using in the Discover Daily header, and uses the default hit slop provided by Palette Mobile.
|-------|-------|
| ![Simulator Screenshot - iPhone 16 Plus - 2025-04-11 at 12 02 24](https://github.com/user-attachments/assets/b65613d0-82b8-4560-94aa-adb5313529dc) | ![Simulator Screenshot - iPhone 16 Plus - 2025-04-11 at 12 02 40](https://github.com/user-attachments/assets/c0b77a20-6258-41a3-84e3-51e852743351)|
- Increase the size and hit slop of Discover Daily share button
-
-
-
</details> …

fix(QA): increase share icon size and use default hit slop

---

src/app/Navigation/routes.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/utils/queryPrefetching.ts

Instead of just defining variables in routes, we need a way to prepare them based on the URL parameters for the Auction screen. This is a quite simple solution and could be a first step towards having a standard way to prepare variables for a given route.
-
-
-
-
</details>

fix: Add prefetching variable preparation to routes

---

src/app/Navigation/routes.tsx

Add prepareVariables to follows route.
-
-
-
-
</details>

fix: Add prepareVariables to follows route

---

HACKS.md
ios/Artsy.xcodeproj/project.pbxproj
ios/Artsy/App/ARAppDelegate.mm
ios/Artsy/App/ARAppNotificationsDelegate.m
ios/Artsy/ArtsyUIButtons/ARButtonSubclasses.m
ios/Artsy/Extraction/ARSpinner.m
ios/Artsy/Resources/Artsy-Bridging-Header.h
ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRSetupViewController.m
ios/Artsy/View_Controllers/ARVIR/Views/ARInformationView.m
ios/Artsy/View_Controllers/Util/ARNavigationController.m
ios/Artsy/View_Controllers/Util/Logging/ARLogger.h
ios/ArtsyTests/App_Tests/ARAppNotificationsDelegateTests.m
ios/Podfile
ios/Podfile.lock

This reverts commit c17fa17acad6606cd3655232a68e703f28cd4731.
This PR resolves [PHIRE-1729] 
I believe this is the cause of the slow beta-ios builds, this is because this setting applies to all dependencies and they need to be compiled and included in the application. This is a bit unfortunate because it is the recommendation from firebase: https://rnfirebase.io/#altering-cocoapods-to-use-frameworks
Once we have less iOS deps we should look into bringing this back. 
You can see a job completing much faster here after the change: 
https://app.circleci.com/pipelines/github/artsy/eigen/68605/workflows/c13d8f0d-b9e4-4591-b763-b063162e13fe/jobs/237852
-
-
-
- revert modular headers hack, stop using static frameworks for now - brian 
</details>
Need …

chore: revert modular headers (#11718)"

---

src/app/Components/AbandonFlowModal.tsx
src/app/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
src/app/Components/Buttons/InfoButton.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx

This PR fixes issues with the safe area view inside the infinite discovery logic. The issue comes from a change in `react-native-safe-area-context` API, we now need to specify all edges for it work (instead of nothing). To avoid any future drama with the same component, I updated the instances where we don't specify any edge, to use `SafeAreaView` from RN instead.
| <img src="https://github.com/user-attachments/assets/fe195fa9-bff6-41b8-9805-b588f50bfa77" /> | <img src="https://github.com/user-attachments/assets/638ca6f3-eca6-42c0-8499-172002222df2" /> | 
- infinite discovery onboarding safe area view - mounir
-
-
-
</details> …

fix: infinite discovery onboarding safe area view

---

fastlane/Fastfile
fastlane/sentry_fastlane.rb

Updates a few deprecated fastlane methods we were getting warnings about to their modern equivalents. 
-
-
-
- update deprecated fastlane methods - brian
</details>

chore: deprecated fastlane methods #trivial

---

src/app/Components/PartnerListItemShort.tsx

Addresses a notion card https://www.notion.so/artsy/Favorites-tab-Follows-galleries-the-gallery-image-is-blurry-1d2cab0764a080178f48c9f2bf6b6742?pvs=4
Before: 
| Gallery in the artwork description | Favorites | 
| --- | --- | 
| ![before 1](https://github.com/user-attachments/assets/f1809949-0a5b-4e92-8541-d6ee349e41af) | ![before faves](https://github.com/user-attachments/assets/205b1fa8-d5e6-409f-ac0d-30dfb8e4688a) | 
After: 
| After artwork description Android | After Favorites Android | After artwork description iOS | After Favorites iOS |
| <img src="https://github.com/user-attachments/assets/f2f3098a-e76a-4806-b9c0-8da85c9cec8f" width="400" /> | <img src="https://github.com/user-attachments/assets/14d4ef0a-eb2c-42e3-b4c2-c4e9a457a84b" …

fix: fix gallery cover image is blury

---

src/app/Components/ArtsyWebView.tests.tsx
src/app/Components/ArtsyWebView.tsx

This PR resolves [ONYX-1672] 
This adds Dark mode support to web views.
| iOS | iOS | Android | Android
|![Simulator Screenshot - iPhone 16 - 2025-04-15 at 10 51 49](https://github.com/user-attachments/assets/1c80479c-0736-4d80-abc9-36725ed85bd0) |![Simulator Screenshot - iPhone 16 - 2025-04-15 at 10 52 10](https://github.com/user-attachments/assets/b57d0815-b239-468f-9b2d-ea4a0e50a00b) |![Screenshot_1744720228](https://github.com/user-attachments/assets/7ab78a75-b875-4ec4-8b17-1c5c02764413) |![Screenshot_1744720020](https://github.com/user-attachments/assets/71e57851-f4db-417f-87c1-ee88f75fbb32) |
- Dark mode support for web views - ole
-
-
-
</details> …

feat: Add dark mode support to web views

---

src/app/Navigation/AuthenticatedRoutes/Tabs.tsx

This PR resolves [PBRW-669] 
This PR fixes the issue of the label position on tablets. This is actually a weird one 😄 , so it looks like the default position of the label on tablets, is next to the icon, not below it.
- tab bar label position on tablets - mounir
-
-
-
</details>
[PBRW-669]: https://artsyproduct.atlassian.net/browse/PBRW-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: tab bar label position on tablets

---

src/app/Components/SectionTitle.tsx
src/app/Navigation/routes.tsx
src/app/Scenes/MyAccount/MyAccount.tests.tsx
src/app/Scenes/MyAccount/MyAccount.tsx
src/app/Scenes/MyAccount/MyAccountEditEmail.tests.tsx
src/app/Scenes/MyAccount/MyAccountEditEmail.tsx
src/app/Scenes/MyAccount/MyAccountEditPassword.tests.tsx
src/app/Scenes/MyAccount/MyAccountEditPassword.tsx
src/app/Scenes/MyAccount/MyAccountEditPhone.tests.tsx
src/app/Scenes/MyAccount/MyAccountEditPhone.tsx
src/app/Scenes/MyProfile/Components/MyProfileScreenWrapper.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/app/Scenes/Onboarding/OnboardingSocialLink.tsx
src/app/utils/LinkedAccounts/apple.ts
src/app/utils/LinkedAccounts/facebook.ts
src/app/utils/LinkedAccounts/google.ts
src/app/utils/hooks/withSuspense.tsx

This PR resolves [ONYX-1640] 
This PR updates the screens within **Login & Security** to match the new designs
| <video src="https://github.com/user-attachments/assets/6c614b8f-cfb1-4733-8c4e-3ebf6a525577" /> | <video src="https://github.com/user-attachments/assets/74870868-74db-412d-b9ac-13c54fece20f" /> |
- [behind feature flag] update login and security screen UI - mounir
- [behind feature flag] update edit phone screen UI - mounir
- [behind feature flag] update edit password screen UI - mounir
- [behind feature flag] update edit email screen UI - mounir
-
-
-
</details> …

feat: update login and security screens UI

---

.eslintrc.js
src/app/Providers.tsx

Resolves https://www.notion.so/artsy/Discover-Something-New-pills-look-strange-immediately-after-toggling-dark-mode-1d7cab0764a0806e820cfbfd83155cc1?pvs=4
With this change, a theme change (dark mode) will force the whole app to re-render. This fixes an issue where components that store color values in their state don't update when the theme changes ([example](https://github.com/artsy/palette-mobile/blob/e83972356683a21a62401ed5b2c3a134bf7a250e/src/elements/Chip/Chip.tsx#L26)).
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-04-17 at 14 16 18](https://github.com/user-attachments/assets/cc07055d-c6de-4b42-b806-e468d483985c) | ![Simulator Screenshot - iPhone 16 - 2025-04-17 at 14 12 54](https://github.com/user-attachments/assets/30d48986-014c-453d-87f4-2154e790f70f …

fix: Re-render app on theme change

---

src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

Fixes https://www.notion.so/artsy/Success-toasts-are-inconsistent-in-light-vs-dark-mode-1d7cab0764a080a2bb12d43302fc6003?pvs=4
White color on save artwork toast in dark mode.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-04-17 at 14 39 16](https://github.com/user-attachments/assets/8f2ff1e4-277c-4a74-9e12-beaff8acd468) |![Simulator Screenshot - iPhone 16 - 2025-04-17 at 14 39 23](https://github.com/user-attachments/assets/7696d218-5186-43bf-8357-b89258bd8eb8) |
- Fix text color on save artwork toast for Infinite Discovery in dark mode - ole
-
-
-
</details>
[feature …

fix: Text color on save artwork toast in dark mode

---

ios/Artsy/App_Resources/Info.plist

This PR resolves [ONYX-1682] 
The Dark Mode "Sync with system" option isn't working correctly on iOS. This updates `UIUserInterfaceStyle` to `Automatic` to adopt the system color theme instead of always using the light theme.
* https://developer.apple.com/documentation/bundleresources/information-property-list/uiuserinterfacestyle
* https://stackoverflow.com/questions/61124229/react-native-0-62-2-appearance-return-wrong-color-scheme
-
-  Set UIUserInterfaceStyle to Automatic to adopt system color theme (automatic dark mode) - ole
-
-
</details> …

fix: Set UIUserInterfaceStyle to Automatic to adopt system color theme

---

src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/app/Scenes/Artist/Artist.tsx
src/app/Scenes/Search/components/AutosuggestSearchResult.tests.tsx
src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
src/app/system/navigation/navigate.ts
src/setupJest.tsx

This PR resolves [ONYX-1592] 
This PR adds prefetching to search results and cleans up related code.
* This PR does not contain any UI changes  🖼️
-  Prefetch Search result items - ole
-
-
-
</details>
[ONYX-1592]: https://artsyproduct.atlassian.net/browse/ONYX-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Prefetch Search result items

---

src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx

Prefetch partner list item.
-
-
-
-
</details>

fix: Prefetch partner list item

---

src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
src/app/system/navigation/navigate.ts

Co-authored-by: Mounir Dhahri <soussouheros@gmail.com>
As discussed in this Slack thread, do not track the favorites tab screen
https://artsy.slack.com/archives/C05EQL4R5N0/p1744919145046069
-
-
-
- do not track favorites tab screen
</details>

fix: do not track favorites tab screen

---

package.json
yarn.lock

bumps pod install dep
#nochangelog

build(deps): bump pod-install dep to latest

---

src/app/store/config/features.ts

This PR resolves [ONYX-1695] 
Add ARDarkModeSupport echo flag key.
-
-
-
- Make Dark Mode ready for release (with echo ff) - ole
</details>
[ONYX-1695]: https://artsyproduct.atlassian.net/browse/ONYX-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add ARDarkModeSupport echo flag key

---

.eslintrc.js
.vscode/settings.json
eslint-local-rules.js
package.json
yarn.lock

This PR resolves https://github.com/artsy/palette-mobile/pull/334#issuecomment-2824030547 
This PR comes as a follow-up to this comment https://github.com/artsy/palette-mobile/pull/334#issuecomment-2824201563
The goal from this PR is to make sure that we no longer import icons from `@artsy/palette-mobile`, and instead always import them from `@artsy/icons`.
This required the addition of a new eslint rule that will be only available for devs, and it required the addition of a new root configuration file. I tried to move that around to a better folder but I failed.
- 
-
-
- add artsy icons check eslint rule - mounir
</details> …

chore: add artsy icons check eslint rule

---

src/app/store/config/features.ts

This PR resolves [ONYX-1695] 
Mark ARDarkModeSupport as ready for release (it's still disabled in [Echo](https://github.com/artsy/echo/blob/2d27f5d13093c5a3db066078da399d172be9f225/Echo.json5#L216)).
-
-
-
-
</details>
[ONYX-1695]: https://artsyproduct.atlassian.net/browse/ONYX-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Mark ARDarkModeSupport as ready for release

---

package.json
yarn.lock

Upgrade palette-mobile to v17.2.0
-
-
-
- Upgrade palette-mobile to v17.2.0 - ole
</details>

chore: Upgrade palette-mobile to v17.2.0

---

ios/Artsy.xcodeproj/project.pbxproj
src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx

1. Fix a bug introduced in #11944 that made the Discover Daily home view section disappear
2. Added a `utm_medium=product-share` URL param to artworks shared in Discover Daily as requested by the Marketing team
3. Imported icons from the @artsy/icons repo instead of @artsy/palette-mobile
- Fixed miscellaneous bugs with Discover Daily
-
-
-
</details>

fix: discover daily missing from home view

---

src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx

This PR makes some follow-up tweaks to the work started in #11945.
1. Add an `artworkImageSwiped` tracking event when the image changes
2. Display a blurhash while images are loading
3. Decreased the tap areas from 33% of the screen to 20% on the left and right
4. Prevent the pagination bar from pushing the "save" button down
https://github.com/user-attachments/assets/f7a44a60-a18b-4e8a-80a0-065fdf6f45bc
- follow-up tweaks for multiple artwork images in Discover Daily
-
-
-
</details>

fix(DIA-1249): follow-up tweaks for multiple artwork images in Discover Daily

---

src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx

Increase quick links animations duration
https://github.com/user-attachments/assets/b9ebb295-b34c-467c-b011-437cf8a918cd
-
-
-
-
</details>

chore: increase quick links animation duration

---

src/app/Scenes/MyProfile/DevicePrefsModel.ts

Tapping on "Sync with System" in dark mode settings does not have an immediate effect because we are overriding the default system color scheme. 
This PR removes the overriding.
**Before:**
https://github.com/user-attachments/assets/3091057d-564a-464c-9b30-1af1c688fcf4
**After:**
https://github.com/user-attachments/assets/8af36397-1695-49da-9a86-3344b5e43907
- fix Sync with System dark mode setting - ole
-
-
-
</details>

fix: Sync with System dark mode setting

---

src/app/Scenes/Favorites/Components/FollowedArtists.tsx
src/app/Scenes/MyProfile/Components/MyProfileScreenWrapper.tsx
src/app/Scenes/MyProfile/MyProfilePayment.tsx

This PR fixes the refresh control on the payment screen
It was broken because of the nested inside of the scrollview (in MyProfileScreenWrapper) FlatList component. Moving the refresh control inside of the MyProfileScreenWrapper solved the issue
| Platform | After |
|---|---|
| Android | <video src="https://github.com/user-attachments/assets/d0579211-1dcd-4091-85f6-f18805e68cf7" width="400" /> | 
| iOS | <video src="https://github.com/user-attachments/assets/c5bd0317-cfeb-4e3f-b48d-694a7ed8c4f6" width="400" /> | 
-->
- fix refresh control on the payment screen (new account redesign)
-
-
-
</details> …

fix: fix refresh control on the payment screen

---

src/app/Scenes/HomeView/HomeView.tsx

This PR attempts to fix the issue with the home screen tracking 
|---|---|---|
| App Open | <video src="https://github.com/user-attachments/assets/fb5cd77c-6c75-40aa-81ac-c24d3e8fd8ad" /> | <video src="https://github.com/user-attachments/assets/f99f46f6-6563-4ea0-b5d0-203eb2b767bd" /> |
| Deeplinking | <video src="https://github.com/user-attachments/assets/eb8d6a7b-a9be-4ad4-90c4-16453490fb52" /> | <video src="https://github.com/user-attachments/assets/5aeb3101-1b91-4721-86af-5b153af37274" /> |
</details> 
|---|---|---|
| App Open | <video src="https://github.com/user-attachments/assets/cbd6b3d7-5801-4090-9eab-b4005ae5aeca" /> | <video …

fix: Fix home tracking issue

---

src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
src/app/Scenes/BottomTabs/BottomTabsIcon.tsx

This PR fixes accessibility issues with the Bottom Tabs.
| <img src="https://github.com/user-attachments/assets/3fb53d06-a869-496e-8312-9da2ec516736" /> | <img src="https://github.com/user-attachments/assets/1291f093-8d10-4308-b39c-0eea7966e572" /> | 
- fix accessibility issues on bottom tabs - mounir
-
-
-
</details>

fix: accessibility issues on bottom tabs

---

src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx

This PR resolves [PHIRE-1775] 
Fixes some navigation issues on android on the homeview search portal. This change does not affect iOS in any way
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/ee66c5fc-20a5-46fb-b94c-04717e9989b8" width="400" /> | <video src="https://github.com/user-attachments/assets/44dbb4d3-3ddd-4a6f-873e-92a937c11eeb" width="400" /> |
-
-
- fix navigation goBack issues on search portal
-
</details>
[PHIRE-1775]: …

fix: navigation goBack issues on search portal

---

src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx

This PR resolves [ONYX-1700] 
- Adds support for the icons required by [Quick Links v2](https://github.com/artsy/metaphysics/pull/6683) ([Figma](https://www.figma.com/design/Z9legdjhKORHt0vOGpvBg3/App%E2%80%A8IA-and-Shortcuts?node-id=3173-101361))
- Also refactors the icon imports to `@artsy/icons/native`
| Android  | iOS |
|---|---|
| <img src="https://github.com/user-attachments/assets/23943c23-f898-40ec-a297-a9d397bdffa1" height ="400" /> | <img src="https://github.com/user-attachments/assets/456dcbc6-0ca7-4af2-b851-24bbac1a58a1" height ="400" /> |
- Adds support for new home view quick link icons
-
-
-
</details> …

feat(home view): add support for additional nav pill icons

---

.eslintrc.js

This change will restrict the import of `navigate` using the ESLint "no-restricted-imports" rule ([docs](https://archive.eslint.org/docs/rules/no-restricted-imports)) to ensure that `RouterLink` is used instead. 
If it is necessary to use `navigate` directly, you can do so with an `eslint-ignore-next-line` comment above the import.
```typescript
// eslint-disable-next-line no-restricted-imports
import { navigate } from "app/system/navigation/navigate"
.....
navigate("honolulu")
``` 
-
-
-
- Restrict using `navigate` in favor of `RouterLink` with eslint - ole
</details> …

chore: Restrict using `navigate` in favor of `RouterLink` with eslint

---

src/app/store/config/EnvironmentModel.tsx
src/app/system/devTools/DevMenu/Components/EnvironmentOptions.tsx

This PR adds some instructions on how allow devs to use a local endpoint on android. I believe the hint and comment should be clear to everyone.
_I am open for other suggestions if you feel there is a better way._
-
-
-
- add instructions on how to use local endpoint on android - mounir
</details>

chore: add instructions on how to use local endpoint on android

---

src/app/Scenes/MyProfile/MyProfilePreferences.tsx

Hide dark mode preferences behind a ff, otherwise changing it does not do anything
- hide dark mode preferences behind a ff
-
-
-
</details>

fix: hide dark mode preferences behind a ff

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/MyCollectionArtworkFormDeleteArtworkModal.tsx

This PR resolves [PBRW-732] 
Delete artwork background color in dark mode.
| Before | After | After (light)
|![Simulator Screenshot - iPhone 16 - 2025-05-02 at 12 21 35](https://github.com/user-attachments/assets/0001f0a2-beb2-4334-963c-1ea3b1092214) |![Simulator Screenshot - iPhone 16 - 2025-05-02 at 12 19 11](https://github.com/user-attachments/assets/f5149e5a-65b7-484d-8202-a624da5234b4) |![Simulator Screenshot - iPhone 16 - 2025-05-02 at 12 22 02](https://github.com/user-attachments/assets/1d5a68a6-e4af-4d18-a600-c911699c6ab3)|
-
-
-
-
</details> …

fix: Delete artwork background color in dark mode

---

src/app/Scenes/MyProfile/Components/UserAccountHeader/MyCollectionBannerEmptyState.tsx

fix my collection empty state banner
| --- | --- | 
| ![image](https://github.com/user-attachments/assets/4d579309-0789-42f2-a19a-0939c0206c42) | ![image](https://github.com/user-attachments/assets/cf7f35a5-4104-4b51-bb67-f1ccecf72ea0) | 
- fix my collection empty state banner
-
-
-
</details>

fix: fix my collection empty state banner

---

src/app/Scenes/Artwork/Components/CommercialButtons/ShippingModal.tsx

This PR resolves [PBRW-714] 
Fix Shipping modal dark mode background.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-05-02 at 11 42 57](https://github.com/user-attachments/assets/37d0b437-e9ed-474b-8445-1ec0e914e968) | ![Simulator Screenshot - iPhone 16 - 2025-05-02 at 11 42 41](https://github.com/user-attachments/assets/9acdd0ea-6ee0-4b89-8803-5adc35b01ad5)|
- Fix Shipping modal dark mode background. - ole
-
-
-
</details>
[PBRW-714]: …

fix: Shipping modal dark mode background

---

src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/app/Scenes/ArtworkLists/ArtworkLists.tsx
src/app/Scenes/Favorites/Favorites.tsx

This PR resolves [PBRW-715] 
Fixes berghain mode on add location contact gallery.
Note no screenshots / videos as it was not reproducible on most devices
-
-
- berghain mode in contact gallery location android
-
</details>
[PBRW-715]: https://artsyproduct.atlassian.net/browse/PBRW-715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: berghain mode

---

src/app/Components/States/ZeroState.tsx
src/app/Scenes/ArtworkLists/ArtworkLists.tsx
src/app/Scenes/Favorites/Components/AlertsList.tsx
src/app/Scenes/Favorites/Components/FollowedArtists.tsx
src/app/Scenes/Favorites/Components/FollowedGalleries.tsx
src/app/Scenes/Favorites/Components/FollowedShows.tsx
src/app/Scenes/Favorites/Favorites.tsx
src/app/Scenes/Favorites/SavesTab.tsx
src/app/Scenes/MyCollection/Components/MyCollectionZeroState.tsx

This PR fixes the favorites tab scroll issues on Android.
https://github.com/user-attachments/assets/f73dda34-c657-4729-8114-57fbff993c71
- favourites scroll issues on android - mounir
-
-
-
</details>

fix: favourites scroll issues on android

---

src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx

This PR resolves [PBRW-719] 
Add bottom safe area for Add ARtists screen on Android.
**Screenshots will follow.....**
-
-
-
- Add bottom safe area for Add ARtists screen on Android - ole
</details>
[PBRW-719]: https://artsyproduct.atlassian.net/browse/PBRW-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add bottom safe area for Add Artists screen on Android

---

src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtists.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsOverview.tsx

This PR resolves [ONYX-1679] 
This adds the Insights tab to the new My Collection screen.
| Old (iOS) | New (iOS) |
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-04-30 at 10 31 28](https://github.com/user-attachments/assets/323d2c1a-6906-4df6-827f-5acad47de387) | ![Simulator Screenshot - iPhone 16 - 2025-04-30 at 10 30 56](https://github.com/user-attachments/assets/e4d3b57e-8d2a-4577-a386-95029828cade)|
| Old (Android) | New (Android) |
| --- | --- |
| ![Screenshot_1746002176](https://github.com/user-attachments/assets/a88ee279-5e37-4dec-afac-f7e6dba0655b)| ![Screenshot_1746002147](https://github.com/user-attachments/assets/0a2173ec-689b-43db-a011-b9517d76b432)| 
- New My Collection Insights Tab (behind ff) - ole
- New My Collection …

feat: Add new My Collection Insights tab

---

src/app/Scenes/Onboarding/Auth2/components/AuthBackground.tsx

https://www.notion.so/artsy/White-space-in-auth-screen-with-Dark-Mode-on-1eacab0764a080cba426d60ab85bbba6?pvs=4
Set Onboarding screen background to black in light and dark mode.
- fix: Set Onboarding screen background to black in light and dark mode - ole
-
-
-
</details>

fix: Set Onboarding screen background to black in light and dark mode

---

src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx
src/app/Scenes/LegacyFavorites/LegacyFavorites.tsx

This PR resolves [MOPRAT-848]
Follow up to https://github.com/artsy/icons/pull/74 which migrated the `FollowArtistIcon`
No visual change, this is a pure refactor.
This updates that import, as well as a couple of others in the same file, that were already accessible from the preferred location in `@artsy/icons`.
| ![beforeicons](https://github.com/user-attachments/assets/68a3a230-25a0-4a3d-a1e0-ff354207b6dc) | ![after icons](https://github.com/user-attachments/assets/19826a81-0f72-4c9d-86e3-d67df0795b8c) | 
-
-
-
- Updated FollowArtist and other icon imports
</details> …

refactor(icons): update FollowArtistIcon

---

src/app/Scenes/CompleteMyProfile/IdentityVerificationStep.tsx

This fixes the FAQ link on the Profile Verifiy your ID step.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-05-06 at 16 35 28](https://github.com/user-attachments/assets/20bb0fa3-cc3d-45c3-b182-8c99730fbcaf) |![Simulator Screenshot - iPhone 16 - 2025-05-06 at 16 35 22](https://github.com/user-attachments/assets/7964ddb5-3cfb-44a5-9052-01a31e333f16) |
- fix FAQ link on Verifiy your ID Profile step - ole
-
-
-
</details>

fix: FAQ link on Verifiy your ID step

---

.circleci/config.yml

[WAITING FOR EARLY FEEDBACK]
This PR is an attempt to make our JS tests run faster. This is currently just a draft until the job runs and I collect more insights if it makes sense or not.
**Before**
**After**
**Why wasn't the impact of this bigger?**
It looks like our individual tests are slow, some take more than 150 seconds to fully run! this is where I believe we should focus next. Any small improvement there could help us cut a minute or two of the total wait time
**Still open questions**
- Implications on this on 💵 ? any idea @brainbicycle 
-
-
-
- increase parallelism limit and use larger resource class for js tests -  mounir
</details> …

chore: increase parallelism limit and use larger resource class for js tests

---

src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

This pull request introduces a fix to the issue where newly added artworks do not show up in my collection
**iOS**
https://github.com/user-attachments/assets/1ffcce24-ba08-4536-9a21-89e9a32865ff
**Android**
https://github.com/user-attachments/assets/247afe21-9ffd-4325-a3dc-9b7f783ba655
- show newly added artworks in my collection - mounir
-
-
-
</details>

fix: show newly added artwork

---

src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tsx
src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
src/app/Scenes/MyCollection/MyCollection.tsx

This PR resolves https://www.notion.so/artsy/Header-is-not-greyed-out-when-i-open-a-bottom-view-1ebcab0764a0801b94d5c717975641c2?pvs=4
This PR fixes the header colour inside the bottom sheet
| <img src="https://github.com/user-attachments/assets/e1d630ac-a7cf-478d-8b2b-c22e8d2af2da" /> | <img src="https://github.com/user-attachments/assets/8bb36d91-5c28-455e-ad57-67ade558f8a8" /> | 
- fix gray header on my collection bottomsheet - mounir
-
-
-
</details>

fix: gray header on my collection bottomsheet

---

src/app/Navigation/routes.tsx
src/app/Scenes/HomeView/HomeView.tsx
src/app/Scenes/MyProfile/Components/UserAccountHeader/MyCollectionPreview.tsx
src/app/Scenes/MyProfile/Components/UserAccountHeader/UserAccountHeader.tsx

This PR resolves https://www.notion.so/artsy/My-profile-my-collection-preview-card-are-not-prefetched-1ebcab0764a080c28919c5430ccaea22?pvs=4
This PR addresses 
<video src="https://github.com/user-attachments/assets/3fce3a0f-76a8-47f9-8b5c-5c498a8f15be" />
-
-
-
-
</details>

chore: fix prefetching on profile

---

src/app/Scenes/MyProfile/MyProfileEditForm.tsx
src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx

This PR resolves [ONYX-1715] 
Adjust id and email verifications component according to the new design
| verified | not verified |
| --- | --- |
| ![IMAGE 2025-05-06 14:15:08](https://github.com/user-attachments/assets/ffc516a9-f6f9-4a7d-85e8-03b2532119a2) | ![IMAGE 2025-05-06 14:15:12](https://github.com/user-attachments/assets/42b119ff-6a68-4cd3-bd27-ca9a5702913c) |
- adjust id and email verifications component
-
-
-
</details>
[ONYX-1715]: https://artsyproduct.atlassian.net/browse/ONYX-1715?atlOrigin=eyJpIj …

feat(ONYX-1715): adjust id and email verifications component

---

src/app/store/__tests__/GlobalStoreModel.tests.ts

unblocking main after merging ARDarkModeEnabled in echo
#nochangelog

fix: darkmode ff tests

---

src/app/Scenes/CompleteMyProfile/IdentityVerificationStep.tsx

Complete Profile Identity Verification Step FAQ link layout on Android.
| --- | --- |
| | ![Screenshot_1746608066](https://github.com/user-attachments/assets/f817ab44-87f5-4e04-ac1a-c669c6903c0c)
|
- fix: Complete Profile Identity Verification Step FAQ link layout on Android - ole
-
-
-
</details>

fix: Complete Profile Identity Verification Step FAQ link layout on Android

---

src/app/Navigation/Navigation.tsx

Fixes typo that has been bugging me for a while - only visible in dev mode so no changelog needed
#nochangelog

fix: typo only visible in dev mode

---

src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tests.tsx
src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx

Trivial copy change to adopt standard casing: "Galleries For You" → "Galleries for You"
|<img height="400" alt="Screenshot 2025-05-06 at 5 17 44 PM" src="https://github.com/user-attachments/assets/a1ce05fe-006c-411e-a676-56887898108b" /> | <img height="400" alt="Screenshot 2025-05-06 at 5 17 44 PM" src="https://github.com/user-attachments/assets/9f0554a0-0054-4663-902f-76ab949c01e9" /> | 
- Galleries for You casing
-
-
-
</details>

fix: Galleries for You casing

---

app.json

Prep for version 8.72.0
#trivial #nochangelog

chore: update version number to prep for version 8.72.0

---

src/app/Components/ArtistListItem.tests.tsx
src/app/Components/ArtistListItem.tsx
src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtists.tsx
src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx

Fixes [Ellipsus needed for artist list](https://www.notion.so/artsy/Ellipsus-needed-for-artist-list-1ebcab0764a08017a8fae7daa59949d2?pvs=4)
| --- | --- | 
| https://github.com/user-attachments/assets/659c8dfb-2efe-4ac3-8748-d32d9170faa0 | [123.webm](https://github.com/user-attachments/assets/f13f293b-d2e9-4caa-97b9-d250cc1278fa) |
- add MoreIcon to the artist item component
-
-
-
</details>

fix: add MoreIcon to the artist item component

---

src/app/Scenes/Onboarding/Auth2/scenes/__tests__/ForgotPasswordStep.tests.tsx

Still failing periodically and not sure why, commenting for now. 
#nochangelog

chore: disable flaky test for now #trival #skipci

---

src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
src/app/store/config/features.ts

Mark AREnableRedesignedSettings as ready for release
-
-
-
- mark AREnableRedesignedSettings as ready for release
</details>

chore: mark AREnableRedesignedSettings as ready for release

---

Gemfile.lock
ios/Podfile.lock

This PR commits some changes to Gemfile.lock and Podfile.lock found after running `yarn install:all` on the main branch.

chore: commit changes to Gemfile.lock and Podfile.lock

---

src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtists.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/Scenes/MyCollection/MyCollectionLegacy.tsx
src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
src/app/utils/refreshHelpers.tsx

Resolves https://www.notion.so/artsy/When-i-add-new-artists-i-collect-they-dont-show-up-in-my-collection-1ebcab0764a0806a844eea7fffad7f7f?pvs=4
With this change, the app correctly updates the list of collected artists when an artist is added or removed.
| Add | Remove |
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-05-12 at 19 31 05](https://github.com/user-attachments/assets/4e568663-4ce1-4a99-b2d0-69e6b7be6d82) | ![Simulator Screenshot - iPhone 16 - 2025-05-12 at 19 31 20](https://github.com/user-attachments/assets/5375a611-a34b-4558-9662-152b18ca7e43)|
- fix: Update list of collected artists when artist gets added or removed in My Collection - ole
-
-
-
</details> …

fix: Update list of collected artists when artist gets added or removed

---

package.json
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyProfile/Components/UserAccountHeader/UserAccountHeader.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
yarn.lock

For more context: https://artsy.slack.com/archives/C05EQL4R5N0/p1747082377247229?thread_ts=1746812579.717129&cid=C05EQL4R5N0
| trackTappedMyCollection | trackTappedEditedProfile | 
| --- | --- |
| ![1](https://github.com/user-attachments/assets/9893c4cb-d528-43bc-9fd1-ecb2c24f5d63) | ![2](https://github.com/user-attachments/assets/c25a3c78-d234-48f2-994a-9a4dd7b3e1e4) |
-
-
-
- add trackTappedMyCollection and trackTappedEditedProfile events
</details>

feat: add missing new profile and myc tracking

---

package.json
src/app/Components/Bidding/Screens/Registration.tests.tsx
src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
yarn.lock

This PR resolves [PHIRE-1813] 
follow up to https://github.com/artsy/palette-mobile/pull/346
Nothing changes ui wise - will follow up with some screenshots of the changed areas
|---|---|---|
| Android | <img src="https://github.com/user-attachments/assets/b5aff8e6-0163-4195-8fa5-94c5ecc4ca3f" width="400" /> | <img src="https://github.com/user-attachments/assets/b5aff8e6-0163-4195-8fa5-94c5ecc4ca3f" width="400" /> |
| iOS | <img src="https://github.com/user-attachments/assets/d1be9165-6f2d-46c7-ae8a-1111fa0377e7" width="400" /> | <img src="https://github.com/user-attachments/assets/d1be9165-6f2d-46c7-ae8a-1111fa0377e7" width="400" /> |
- 
-
-
- remove non valid a11y props and excess containers
</details>
Need help …

chore: remove non valid a11y props and excess containers

---

data/schema.graphql
src/app/Scenes/OrderHistory/OrderDetail/OrderDetail.tsx

-
-
-
- update metaphysics schema
</details>

chore: update metaphysics schema

---

app.json

Previous version number update failed, will look into.

fix: update version number #trivial #skipci

---

src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx

Fix MyCollectionAddCollectedArtists to make sure main is not failing when we release AREnableRedesignedSettings
More context: https://artsy.slack.com/archives/C02BGCPUJ/p1747394801324159?thread_ts=1747394361.064629&cid=C02BGCPUJ
#nochangelog
-
-
-
-
</details>

chore: fix MyCollectionAddCollectedArtists test

---

src/app/Scenes/MyCollection/Components/MyCollectionZeroArtists.tsx
src/app/Scenes/MyCollection/Components/MyCollectionZeroState.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx

- one failing test was a real bug, the analytics call was in Button onPress in ZeroState which was swallowed by RouterLink causing it not to be fired.
- minor capitalization difference in new design
- minor copy difference in new design
- fix broken analytics in MyCollection zero state - brian 
-
-
-
</details>

fix: broken myCollection tests after flag enabled

---

app.json

Prepare for next release
#nochangelog #trivial

chore: update version number #trivial #skipci

---

src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
src/app/Scenes/Search/Search.tsx

This PR fixes the broken padding below the search input on search tab.
**Before**
**After**
-
-
-
- fix broken padding on search tab - mounir
</details>

fix: broken padding on search tab

---

src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx

Adds a11y labels to social logins
Also replaces icon imports to use `@artsy/icons/native`
nothing changes ui wise
-
-
-
- artsy icon imports
</details>

fix: a11y labels on socials + artsy icon imports

---

src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx

This PR resolves [ONYX-1724]
Fixes the broken notification preference toggles in the Profile area.
Currently every attempt to toggle one of the notification preferences produces an error because the mutation is failing, due to unexpected input.
This clip shows a staging Gravity console on the left displaying my user's settings changing in realtime as I toggle the switches, demonstrating the the mutation succeeds now:
https://github.com/user-attachments/assets/56968358-a5ac-43df-8199-c85b9e96547c
- Fixes notification preferences toggles
-
-
-
</details> …

fix: notification preferences

---

ios/Artsy.xcodeproj/project.pbxproj
src/app/system/devTools/DevMenu/Components/ExpoUpdatesOptions.tsx

Mounir noticed an issue on iOS!
- Updating runtime version on iOS was broken due to node requirement in build script, remove node requirement
- The app closing after changing channel was causing channel not to be persisted, read from active deployment
-
-
-
- fix iOS expo updates channel switch - brian 
</details>

chore(releases): updates qa build follow ups

---

src/app/utils/useHideSplashScreen.ts

This PR resolves [PBRW-815] 
Fixes the bug that we encountered during qa - https://github.com/artsy/eigen/pull/10951/files#diff-b856e7fd1467b5e6d9b4ce08c250275c00ed4d9a7d706f0e163706d1ac0db18cL45
[The line and the pr](https://github.com/artsy/eigen/pull/10951/files#diff-b856e7fd1467b5e6d9b4ce08c250275c00ed4d9a7d706f0e163706d1ac0db18cL45) that this was introduced 
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/a022206a-47af-47c9-83c9-26b9ea18c554" width="400" /> | <video src="https://github.com/user-attachments/assets/8077ae46-6dd1-4169-98e2-6598090bcf76" width="400" /> |
- fix splash screen stuck in onboarding
-
-
-
</details> …

fix: stuck splash screen in onboarding

---

src/app/Scenes/CompleteMyProfile/IdentityVerificationStep.tsx

This PR resolves [ONYX-1727] 
This PR fixes an issue with the FAQ link text on complete profile modal
**Before**
| <img src="https://github.com/user-attachments/assets/a5338a70-199e-4e65-941a-9dcd0125ecfa" /> | <img src="https://github.com/user-attachments/assets/48b3a7e4-d8a5-4c27-8be5-2f9babab7e95" /> | 
- fix FAQs link text on complete profile - mounir
-
-
-
</details>
[ONYX-1727]: https://artsyproduct.atlassian.net/browse/ONYX-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

fix: faq link text on complete profile

---

ios/Artsy.xcodeproj/project.pbxproj

Fixes pbxproj file diffs
#nochangelog

fix: pbxproj diff

---

src/app/Scenes/Artwork/Components/ArtworkDimensionsClassificationAndAuthenticity/ArtworkClassification.tsx

Resolves https://artsyproduct.atlassian.net/browse/PBRW-854
Fixes Artwork classification info text link alignment.
|---|---|---|
| Android | <img width="627" alt="Screenshot 2025-05-27 at 18 03 37" src="https://github.com/user-attachments/assets/d8c0993a-152a-4524-97ae-d88a814670ac" /> | <img src="https://github.com/user-attachments/assets/30b0bad2-353a-4f97-9e53-c33b2ce41f4b" width="400" /> |
**Steps to reproduce:**
1. Open the app
2. Search for Marilyn MInter
3. Open her artwork, e.g. Sweetheart
4. Scroll the page
- Artwork classification info text link alignment
-
-
-
</details> …

fix(PBRW-854): Artwork classification info text link alignment

---

src/app/Scenes/HomeView/Components/ModalCarouselComponents/ModalCarouselContainer.tsx

This PR resolves [PBRW-823] 
This PR fixes dark mode issues on the learn more modal.
| <img src="https://github.com/user-attachments/assets/05d842ad-c82f-4469-8deb-b73fd6ed9b3a" /> | <img src="https://github.com/user-attachments/assets/14dde5e4-ea70-4eed-b991-02e710248af1" /> | 
- fix: dark mode on learn more modal - mounir
-
-
-
</details>
[PBRW-823]: https://artsyproduct.atlassian.net/browse/PBRW-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

fix: dark mode on learn more modal

---

src/app/Navigation/AuthenticatedRoutes/ProfileTab.tsx
src/app/Navigation/routes.tsx

This PR brings back the old behaviour of only showing my collection inside the profile tab.
https://github.com/user-attachments/assets/e5fdbca1-c455-4efa-bc76-a30881a55d53
- show my collection only on profile tab - mounir
-
-
-
</details>

chore: show my collection only on profile tab

---

.eslintrc.js

This PR enables again react hooks exhaustive deps eslint warning again.
-
-
-
- enable react hooks exhaustive deps warning again - mounir
</details>

chore: enable react hooks exhaustive deps warning again

---

src/app/Navigation/routes.tsx
src/app/Providers.tsx
src/app/Scenes/MyProfile/DarkModeSettings.tsx

This PR improved the UX of dark mode in the app. 
Currently, if you change the appearance from light to dark mode, the app takes you back to the home view. 
This change is inspired Urban Sports App experience.
| Experience from Urban Sports App | Our experience now |
| <video src="https://github.com/user-attachments/assets/30778091-5d88-422b-97af-7f10d2c87a87" /> | <video src="https://github.com/user-attachments/assets/d3c1016c-ba54-4045-b99c-7909cf2c64e6" /> | 
- Improve Dark Mode UX - mounir
-
-
-
</details> …

chore: Improve Dark Mode UX

---

src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/app/Components/ArtworkFilter/FilterModal.tests.tsx
src/app/Components/ArtworkFilter/Filters/ColorsOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx
src/app/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.tests.ts
src/app/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
src/app/Components/Gene/GeneArtworks.tsx
src/app/Navigation/routes.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
src/app/Scenes/Collect/Collect.tsx
src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
src/app/Scenes/Fair/Components/FairArtworks.tsx
src/app/Scenes/Fair/FairAllFollowedArtists.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx
src/app/Scenes/Partner/Components/PartnerArtwork.tsx
src/app/Scenes/Search/SearchArtworksGrid.tsx
src/app/Scenes/Tag/TagArtworks.tsx

https://www.notion.so/artsy/App-Art-under-X-quick-link-and-the-Collect-screen-1fbcab0764a08069833ad682209e0cd5?p=1fbcab0764a080ee8ad9e74b0cb96079&pm=s
This PR fixes some issues happening at the Collect screen and describes how I could debug things.
**TLDR:**
- The query was timing out because we were querying for too many aggregations.
**Debugging process:**
1. I took the query to try it out in Insomnia, and it was still timing out. I assumed there is either something wrong with my input, or the payload we are sending
2. After removing some of the aggregations, the query started to work and the more I removed, the faster the query became
3. I went to Force to inspect the query because it's working fine there
4. I noticed that we are using less aggregations there! Yet still showing the …

chore: fix artwork grid filtering on collect

---

src/app/App.tsx
src/app/Scenes/MyProfile/DevicePrefsModel.ts
src/app/system/navigation/useReloadedDevNavigationState.ts
src/app/utils/useListenToThemeChange.ts

This PR resolves [PBRW-887] 
This PR fixes an issue where the app doesn't listen to system theme updates.
<video src="https://github.com/user-attachments/assets/0444d670-ab82-477f-bae1-6f5824f537a0" />
- fix: listen to system theme update - mounir
-
-
-
</details>
[PBRW-887]: https://artsyproduct.atlassian.net/browse/PBRW-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: listen to system theme update

---

src/app/Scenes/Collect/Collect.tsx

This PR resolves [https://www.notion.so/artsy/App-Art-under-X-quick-link-and-the-Collect-screen-1fbcab0764a08069833ad682209e0cd5] 
This PR fixes pagination issues on the collect screen. 
**Debugging instructions:**
- Pagination was broken, so i thought we are either sending different params or the query itself is broken. I didn't assume that MasonryGrid is broken since we use it everywhere
- I opened Reactron to debug pagination requests, but everything seems fine. The payload made sense and the cursor and the pages also made sense
- I noticed that when the pagination fails, the query as well fail. Tada! it's a query issue then
- I took the payload from Reactron and pasted it inside Insomnia
- The query timed out!
- I started tweaking the query, then I noticed that we are querying for the …

fix: broken pagination on collect screen

---

src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
src/app/Scenes/Collect/__tests__/Collect.tests.tsx

While working on the previous bugs on the Collect route, I noticed that we have no tests for it. This PR fixes that.
#nochangelog

chore: add tests to Collect screen

---

src/app/store/config/features.ts

• Remove 8 feature flag definitions that are no longer referenced in the codebase
This PR removes the following unused feature flags from src/app/store/config/features.ts:
1. AREnableEditorialNews - Enable news app in the home screen
2. AREnableGalleriesForYou - Enable Galleries For You
3. AREnableLatestActivityRail - Enable Latest Activity Rail
4. AREnableAlertDetailsInput - Enable 'details' text input for alerts
5. AREnableAlertsSuggestedFilters - Enable alerts suggested filters
6. AREnableArtistSeriesSuggestions - Enable artist series suggestions
7. AREnableAlertsFiltersArtistSeriesFiltering - Enable artist series
selection on "More Filters" screen
8. AREnableArtworksFeedView - Enable artworks feed view
These feature flags had zero references in the codebase (excluding their …

chore: remove all unreferenced feature flags 

---

src/app/Scenes/MyAccount/MyAccountEditPassword.tsx

This PR resolves [PHIRE-1862] 
Removes the `enableClearButton` since it is not designed to work along with the `secureTextEntry` prop since the two icons (show / hide password) and clear icon overlap each other.
In the login/signup screen we have the same behavior.
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/233df936-f62b-4dd6-8fcb-3ba0f24087ec" width="400" /> | <video src="https://github.com/user-attachments/assets/36d44ca7-25ae-4215-9081-6a410f197d94" width="400" /> |
- remove clear button from password input
-
-
-
</details> …

fix: remove clear button from password input

---

src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingCuratedArtworks.tsx

This is a follow-up to #12271 that amends the copy change made in that PR.

fix(DIA-1364): curators picks subtitle once more

---

src/app/Scenes/Search/Search.tsx

This PR fixes the scroll issues on the Search Tab on iOS.
| <video src="https://github.com/user-attachments/assets/fd0b66c8-d638-45e0-ab1c-ead0e7c7eb8f" /> | <video src="https://github.com/user-attachments/assets/83f4f0dd-a748-4879-b365-ec05ceda3692" /> | 
- fix scroll on search tab on iOS - mounir
-
-
-
</details>

fix: scroll on search tab on iOS

---

fastlane/Fastfile

This PR adds the missing path to Fastfile. thanks @gkartalis
#nochangelog

add missing path to fastfile

---

fastlane/sentry_fastlane.rb
src/app/Components/ArtworkRail/ArtworkRailCard.tsx

get rid of the last sentry cli reference
#nochangelog

chore: get rid of the last sentry cli reference

---

ios/Podfile.lock
package.json
yarn.lock

Bumps `react-native-launch-arguments` to latest
#nochangelog

build(deps): bump react-native-launch-args

---

app.json
fastlane/Fastfile
fastlane/sentry_fastlane.rb
metro.config.js

This PR resolves [PHIRE-1869] 
Fixes the issue with expo updates sourcemaps not working. You can find a working example [here](https://artsynet.sentry.io/issues/5462687657/events/a7ebc40cee2541428333176c1052851d/)
Removed `upload_expo_sourcemaps` custom lane with `npx npx sentry-expo-upload-sourcemaps dist` 
Adds also some missing expo sentry configuration.
After this gets merged we need to check that the sourcemaps of the main non expo updates beta work as expected without issues.
-
-
-
- Fixes expo updates ios sourcemaps
</details>
[docs]: …

fix: sourcemaps on ios for expo updates

---

src/app/system/relay/defaultEnvironment.ts

This PR improves the returned error on Eigen. I noticed this while debugging the discover now and it was pretty annoying
| Header | Header |
| <img src="https://github.com/user-attachments/assets/66c083a2-8c4c-4f76-bb6c-23fa081dbb9c" /> | <img src="https://github.com/user-attachments/assets/6237c490-ea94-47c8-922d-ef0ff57b40e9" /> | 
-
-
-
- simplify relay errors formatting - mounir
</details>

chore: simplify relay errors 

---

src/app/Components/LocationMap/LocationMap.tsx
src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
src/app/Scenes/Partner/Components/PartnerMap.tsx
src/app/utils/hooks/useAndroidActionSheetStyles.ts
src/app/utils/visualizer.ts

This PR fixes the action sheet issues on the activity screen. It also exposes helpers to make sure we can use the right style in a functional component and also outside of a component
| <img src="https://github.com/user-attachments/assets/1771dfad-b4ac-4208-a0a0-ee861320c095" /> | <img src="https://github.com/user-attachments/assets/ca36f8b4-98a5-4a69-817d-3bdc28387c65" /> | 
-
-
- fix dark mode on action sheets - mounir
-
</details>

fix: dark mode on action sheets

---

src/app/Scenes/OrderHistory/OrderDetail/Components/BrandCreditCardIcon.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailPaymentInfo.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailPaymentInfo.tests.tsx
src/app/Scenes/OrderHistory/OrderDetail/OrderDetail.tsx

This PR resolves [EMI-2490] 
> [!NOTE]
This PR adds payment method details in the Order Details
|---|---|---|
| Apple Pay | ![image](https://github.com/user-attachments/assets/5a5987e6-55af-4a22-964d-9e0a4731cf02) | ![image](https://github.com/user-attachments/assets/54368692-9be3-4669-93b2-80d69257b1ed) |
| Google Pay | ![image](https://github.com/user-attachments/assets/7e198584-1642-4f9c-8cb0-5b6c15a817e7) | ![image](https://github.com/user-attachments/assets/56ca687f-1b3d-4cc9-ad82-eb8cd0cd7fa4) |
| Visa | ![image](https://github.com/user-attachments/assets/aa9b1a33-1f20-4baa-b977-ede4eda47ca5) | ![image](https://github.com/user-attachments/assets/604aef10-c …

feat(EMI-2490): Add payment details in Order Details

---

src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailFulfillment.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailFulfillment.tests.tsx
src/app/Scenes/OrderHistory/OrderDetail/OrderDetail.tsx

This PR resolves [EMI-2491] 
> [!NOTE]
This PR adds the fulfillment details in the Order Details screen
|---|---|---|
| Shipping (EU) | ![image](https://github.com/user-attachments/assets/dbf71dba-dd4c-4274-baf7-51fe52d4539d) | ![image](https://github.com/user-attachments/assets/c7d31c3c-f717-4124-a92a-4398bb906ba7) |
| Shipping (US) | ![image](https://github.com/user-attachments/assets/de6fa5e1-f5e3-41d6-a1c9-1a5959e62769) | ![image](https://github.com/user-attachments/assets/dc08af61-4ab3-4c41-9e00-eed015e42f88) |
| Pickup | ![image](https://github.com/user-attachments/assets/88b2f020-62d9-4045-aba4-139ededfd2fe) | ![image](https://github.com/user-attachments/assets/26413bed-991c-41a1-b13c-942e51749 …

feat(EMI-2491): Add fulfillment details to Order Details

---

src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx

This PR resolves [ONYX-1566] 
Make the My Collection artist details bottom sheet scale height automatically depending on the content - use AutoHeightBottomSheet component for this purpose
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/509c1d2a-5329-4082-9c43-6ec0817303dd" width="400" /> | <video src="https://github.com/user-attachments/assets/3890edc8-8e08-41a7-8c32-493a9dc44a69" width="400" /> |
| iOS | <video src="https://github.com/user-attachments/assets/aa826651-1138-4e07-b9d3-ab148c7e7e4f" width="400" /> | <video src="https://github.com/user-attachments/assets/abdca865-0637-4e28-b36c-4a2e890fe889" width="400" /> |
- use autoheigh bottom sheet component on the my collection …

fix(ONYX-1566): use autoheigh bottom sheet component on the my collection artists screen

---

src/app/Scenes/Article/Components/ArticleSection.tsx
src/app/Scenes/Article/Components/Sections/ArticleSectionEmbed.tsx

This PR resolves [DIA-1275] 
Addresses a bug on mobile where embedded media (Artsy Podcast) was not appearing in certain articles. This PR creates a new component and includes `ArticleSectionEmbed` to appear along with text and images.
Also, we are now only rendering the spotify embed for Android's WebView. I've added a small check to make sure that Apple embeds only render in IOS. 
Before: "The Artsy Podcast: When Will Great Women Artists Get Their Due?"
After:
IOS 
Android
-
-
-
- Allows embedded media players to appear in Editorial articles in app
</details> …

fix(DIA-1275): Allows embedded media players to appear in Editorial articles in app

---

src/app/Scenes/OrderHistory/OrderDetail/Components/MessageDetails.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailBuyerProtection.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailHelpLinks.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailBuyerProtection.tests.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailHelpLinks.tests.tsx
src/app/Scenes/OrderHistory/OrderDetail/OrderDetail.tsx
src/app/Scenes/OrderHistory/OrderDetail/hooks/useOrderDetailTracking.ts

This PR resolves [EMI-2509] 
> [!NOTE]
This PR adds tracking to links in the Order details screen
As well as fixing an issue with timezones text in the Order details message
| Event | Android | iOS |
|---|---|---|
| Artsy buyer protection tap | ![image](https://github.com/user-attachments/assets/623f6ca5-ccb9-4e03-9e65-db2fcd636ca1) | ![image](https://github.com/user-attachments/assets/c47e314f-8749-413b-b97e-e2030046e0ee) |
| Help center tap | ![image](https://github.com/user-attachments/assets/68ff9405-966c-489e-bc1f-243fe4ad3c45) | ![image](https://github.com/user-attachments/assets/0cda1a80-5d2e-454d-a20d-ffea0c9ed8a8) |
- Add tracking to Order Details
-
-
- 
</details> …

feat(EMI-2509): Add tracking to Order Details

---

src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/app/Components/Artist/__tests__/ArtistHeaderNavRight.tests.tsx
src/app/Components/ArtistListItemShort.tsx
src/app/Components/FadeIn.tsx
src/app/Components/LoadFailureView.tsx
src/app/Components/SkeletonPill/SkeletonPill.tsx
src/app/Navigation/routes.tsx
src/app/Scenes/Artist/Artist.tsx
src/app/Scenes/Artist/__tests__/Artist.tests.tsx
src/app/Scenes/Artist/__tests__/ArtistSavedSearch.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkMakerTitle.tsx
src/app/Scenes/Artwork/Components/__tests__/ArtworkMakerTitle.tests.tsx
src/app/utils/hooks/withSuspense.tsx
src/app/utils/placeholderGrid.tsx

This PR brings multiple improvements to artist screen in order to improve its performance
- Separate Artworks Query From the above the fold query
- Do not query for aggregations at each page
- Do not query for artworks before the artist cover image and important metadata
- Prefetch artworks query
- Refactor the component into a functional component
- Better skeleton - especially for when an artist is featured
- Fade into withSuspense content: this looks sooo good - it fixed the flash between content and placeholder
According to Reactotron, I see a drop of 30% in the query time, I do however think the drop will be bigger. I will report back after we get this in prod and see things in Datadog
**More Context:**
https://artsy.slack.com/archives/C05EQL4R5N0/p1751035602351999 …

chore: improve performance of artist screen

---

src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailFulfillment.tsx

This PR resolves [EMI-2606] 
Phone number displays country code
|---|---| 
- phone number displays country code in order details
-
-
-
</details>
[EMI-2606]: https://artsyproduct.atlassian.net/browse/EMI-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMI-2606]: https://artsyproduct.atlassian.net/browse/EMI-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2606): phone number displays country code in order details

---

src/app/Scenes/OrderHistory/OrderDetail/OrderDetail.tsx

> [!NOTE]
This PR adds a loading skeleton for the 
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/b684246c-f3e0-4df1-861b-0bff241f4fbb" /> | <video src="https://github.com/user-attachments/assets/e6baeb4f-9943-4bab-865d-32c859cfe937" /> |
| iOS | <video src="https://github.com/user-attachments/assets/91cd4997-1937-4b28-a282-65e47e4937e0" /> | <video src="https://github.com/user-attachments/assets/bbb9c018-3f66-4c2e-9daa-9f80fa027350" /> |
- Add loading skeleton for Order Details
-
-
-
</details> …

chore: Add loading skeleton to Order Details

---

docs/best_practices.md

Co-authored-by: @MrSltun 
This RFC comes as an action item on https://artsy.slack.com/archives/C02BAQ5K7/p1749213588102729
Our current docs are kinda outdated and we started to have multiple patterns of organising folders in the app. So the goal from this RFC is to align again on best practices. IMO, there is not best way to organise folders, but there are bad ways, and inconsistency is one of them. 
-
-
-
- chore update folder structure best practices - mounir
</details>

RFC: align on folder structure best practices

---

.circleci/config.yml

This PR resolves [PHIRE-1911] 
This PR resolves [PHIRE-1910]
Adds asset downloads back to prep-android-env, this was breaking some android jobs, possibly removed in bad merge.
Successful runs here:
https://app.circleci.com/pipelines/github/artsy/eigen/71572/workflows/6c0bc640-9898-4fd7-8add-a648f4175891
-
-
- 
- fix android native tests - brian 
</details>
[PHIRE-1911]: https://artsyproduct.atlassian.net/browse/PHIRE-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

fix: move asset download to prep-android-env

---

src/app/Scenes/MyAccount/MyAccount.tsx

This PR resolves [PBRW-975] 
Fixes apple icon color under Login & Security.
|---|---|---|
| iOS light mode | ![Simulator Screenshot - iPhone 16 Pro - 2025-07-08 at 18 24 30](https://github.com/user-attachments/assets/11d07059-7dda-4412-9324-3556a64ef035) | ![Simulator Screenshot - iPhone 16 Pro - 2025-07-08 at 18 24 03](https://github.com/user-attachments/assets/1ad959da-d080-462b-9eb3-4c741268178c) |
| iOS dark mode | ![Simulator Screenshot - iPhone 16 Pro - 2025-07-08 at 18 24 23](https://github.com/user-attachments/assets/52b50da5-6100-43ca-a3dc-fb91181e63c4) | ![Simulator Screenshot - iPhone 16 Pro - 2025-07-08 at 18 24 08](https://github.com/user-attachments/assets/6bdecc9d-d288-49b9-89ae-e73473ad0f81) |
> [!NOTE]  
> I didn't remove the …

fix: apple icon not visible on dark mode

---

src/app/Components/Artist/ArtistInsights/ArtistsInsightsEmpty.tsx

This PR resolves [PBRW-981] 
This PR fixes the view artsy price database link.
https://github.com/user-attachments/assets/df072839-2e2c-45a1-8f9a-92abd6dad0cd
- fix broken view artsy price database link - mounir
-
-
-
</details>
[PBRW-981]: https://artsyproduct.atlassian.net/browse/PBRW-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(PBRW-981): broken view artsy price database link

---

src/app/Scenes/Artist/Artist.tsx

This PR resolves [PBRW-978] 
This PR fixes the follow button on the artist list item.
| <video src="https://github.com/user-attachments/assets/e819aeae-96fd-49bd-af6b-63e317bd9211" /> | <video src="https://github.com/user-attachments/assets/d7f979bc-10d1-4c9d-87ac-e27fbd5e664d" /> | 
- broken follow button on artist list item - mounir
-
-
-
</details>
[PBRW-978]: https://artsyproduct.atlassian.net/browse/PBRW-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

fix(PBRW-978): broken follow button on artist list item

---

ios/Podfile.lock
package.json
yarn.lock

bump @react-native-async-storage/async-storage from 2.1.2 to 2.2.0
-
-
-
- bump @react-native-async-storage/async-storage from 2.1.2 to 2.2.0
</details>

build(deps): bump @react-native-async-storage/async-storage from 2.1.2 to 2.2.0

---

src/app/Components/Artist/ArtistHeaderNavRight.tsx
src/app/Components/Artist/__tests__/ArtistHeaderNavRight.tests.tsx
src/app/Navigation/routes.tsx
src/app/Scenes/Artist/Artist.tsx

This PR brings back the artist title to the artist screen after a user scrolled down.
https://github.com/user-attachments/assets/02b70407-7201-461d-b66a-85f54cafaaa0
- fix: add artist title to artist screen - mounir
-
-
-
</details>

fix: add artist title to artist screen

---

android/build.gradle

This PR resolves [PHIRE-1933] 
Bumps android target sdk to 35 to comply with PlayStore requirements `App must target Android 15 (API level 35) or higher`
-
-
-
- Bumps android target sdk to 35
</details>
[PHIRE-1933]: https://artsyproduct.atlassian.net/browse/PHIRE-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: bump target sdk version to 35

---

ios/Podfile.lock
package.json
yarn.lock

Bumps bootsplash dep
-
-
-
- bump react-native-bootsplash from 6.3.4 to 6.3.10
</details>

build(deps): bump react-native-bootsplash from 6.3.4 to 6.3.10

---

package.json
src/app/Components/Input/MoneyInput/MoneyInput.tsx
src/app/Components/Input/PhoneInput/PhoneInput.tsx
src/app/Components/Select/Components/SelectButton.tsx
src/app/Components/Select/SelectV2.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
yarn.lock

This PR resolves [MOPRAT-859] 
This PR updates the imports of TriangleDown in Eigen
|---|---|
| <img width="445" height="975" alt="image" src="https://github.com/user-attachments/assets/436f6085-58c9-47b4-845a-f17a470c3db2" /> | <img width="445" height="975" alt="image" src="https://github.com/user-attachments/assets/da7162fa-faf8-4105-ac2f-c5c8c449f410" /> |
| <img width="445" height="975" alt="image" src="https://github.com/user-attachments/assets/5dd0087f-65fd-48b7-bc0a-c2576031f030" /> | <img width="445" height="975" alt="image" src="https://github.com/user-attachments/assets/7e841f01-d54e-45c5-bab4-fc023f6ef4c1" /> |
| <img width="445" height="975" alt="image" src="https://github.com/user-attachments/assets/8aef51d5-49b9-438b-8f65-2074155933d0" /> | <img …

feat(MOPRAT-895): Update TriangleDown icon imports

---

ios/Podfile.lock
package.json
yarn.lock

bump react-native-webview to latest
-
-
-
- bump react-native-webview to latest
</details>

build(deps): bump react-native-webview to latest

---

scripts/utils/assignPBRWTicketsToTeams.ts

This PR resolves [PHIRE-1945] 
Updated release captain docs to include running the script and also updated the script to target the right tickets from PBRW board.
Once we’ve met and identified the launch blockers, we export all bug tickets—including those that aren’t launch-critical—to the PBRW board in Jira and we run from eigen this script:
```jsx
yarn setup:releases
yarn assign-team-labels-pbrw-tickets
```
to ensure Applause tickets are assigned to the correct teams on the PBRW board.
-
-
-
- assign bugs to teams script adjustments
</details> …

chore: assign bugs to teams script adjustments

---

fastlane/Fastfile

This PR resolves [PHIRE-1940] 
Adds a flag to timeout when build processing takes a very long time, this happens from time to time:
https://app.circleci.com/pipelines/github/artsy/eigen/71536/workflows/f3b76dc8-1781-45f1-8b07-47c46ddd8452/jobs/249764
Most jobs take ~10 minutes so setting to 15 should avoid the outliers running for an hour and the job should fail with an error. 
This does mean the build in question won't be distributed to external testers so we will have to manually do that if we want it accessible there. 
-
-
-
- add timeout for beta build processing - brian 
</details>
[feature …

chore: add timeout for build processing

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Scenes/Favorites/Favorites.tsx

This PR resolves [ONYX-1760] 
Fix broken back navigation on the favorites tab (remove back actions)
Adding `backBehavior="none"` to `FavoriteTopNavigator.Navigator` component fixed the issue 
| Android before | Android after |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/cdafa257-c1d1-41a1-b4c8-3224bfa10e2b" width="400" /> | <video src="https://github.com/user-attachments/assets/0138d93e-82b9-4408-8613-ce24abda97f2" width="400" />) |
-
-
- fix broken back navigation on the favorites tab (remove back actions)
-
</details> …

fix(ONYX-1760): fix broken back navigation on the favorites tab (remove back actions)

---

src/app/Navigation/AuthenticatedRoutes/Tabs.tsx

This PR resolves [PBRW-1012] 
Fixes double tracking home screen views on tab switch. 
|---|---|---|
| iOS | <video src="https://github.com/user-attachments/assets/669c9008-bc6e-4624-abbc-9032e2bb7fd0" width="400" /> | <video src="https://github.com/user-attachments/assets/29aded4c-9834-4dfb-9cbe-e3a28ea23c47" width="400" /> |
- fix double track of home on tab switch - brian
-
-
-
</details>
[PBRW-1012]: https://artsyproduct.atlassian.net/browse/PBRW-1012?atlOrigin=eyJpIjoiNWRkNTl …

fix(analytics): don't track home view on tab switch

---

src/app/App.tsx
src/app/utils/useTrackAppState.ts

Resolves [ONYX-1809]
This PR adds app state tracking events.
**Context:** https://artsy.slack.com/archives/C0KEQD4B0/p1751566622807889
-
-
-
- track app state changes - mounir
</details>
[ONYX-1809]: https://artsyproduct.atlassian.net/browse/ONYX-1809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: track app state changes

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/constants.ts
src/app/Navigation/routes.tsx
src/app/Scenes/Artwork/Components/__tests__/ArtworksInSeriesRail.tests.tsx
src/app/Scenes/Fair/Components/FairArtworks.tsx
src/app/Scenes/Fair/Components/FairCollections.tsx
src/app/Scenes/Fair/Components/FairEditorial.tsx
src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
src/app/Scenes/Fair/Components/FairExhibitors.tsx
src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
src/app/Scenes/Fair/Components/FairTabError.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/Fair/FairOverview.tsx
src/app/Scenes/Fair/__tests__/Fair.tests.tsx
src/app/Scenes/Fair/__tests__/FairExhibitorRail.tests.tsx
src/app/Scenes/Fair/__tests__/FairExhibitors.tests.tsx
src/app/Scenes/Fair/__tests__/FairFollowedArtistsRail.tests.tsx
src/app/Scenes/HomeView/Components/HeroUnit.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
src/app/Scenes/VanityURL/__tests__/VanityURLEntity.tests.tsx

**Context:** https://artsy.slack.com/archives/C02BAQ5K7/p1752761208038099
I promise to hold a KS to go through these. 
This PR brings a bunch of improvements to the Fair screen such as:
- Make TTI faster
- Went down from 10/11 seconds for non prefetched to under 200ms
- Improve the scroll performance
- FPS from occasional 0 drops and under 10fps to above 50-60fps
- Fix some UI bugs
<details><summary>Broken padding on artwork rails</summary>
<p>
</p>
</details> 
<details><summary>Dropped frames when scrolling</summary>
<p>
<video src="https://github.com/user-attachments/assets/30cee2df-a273-407b-8798-6a063f523f64" />
| <video src="https://github.com/user-attachments/assets/6796b127-e038-4659-a8c6-5047e0788b97" /> | <video …

chore(DIA-1378): improve fair screen performance

---

src/app/Components/Icons/DarkModeIcon.tsx
src/app/Scenes/MyAccount/MyAccountEditPriceRange.tsx
src/app/Scenes/MyAccount/__tests__/MyAccountEditPriceRange.tests.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/app/Scenes/MyProfile/__tests__/MyProfileSettings.tests.tsx
src/app/store/config/features.ts

This PR sets the price raneg onboarding to ready for release and makes some minor UI changes based on design feedback:
Designs: https://www.figma.com/design/xqc2S6v0iOtz8iayTlhacp/Price-Preference?node-id=306-8612&p=f&m=dev 
-
-
-
-
</details>

chore: set price range onboarding to ready for release

---

src/app/Scenes/HomeView/Components/HomeHeader.tsx

This PR fixes the unnecessary re-renders on the home view header component:
| <video src="https://github.com/user-attachments/assets/3406449a-ea1a-4dd7-af38-f3c1f3bef805" /> | <video src="https://github.com/user-attachments/assets/2bbfddc4-a028-43d2-ac88-de799ba9bead" /> | 
-
-
-
- [HomeView Performance]  do not re-render Header - mounir
</details>

chore: [HomeView Performance]  do not re-render Header

---

src/app/Components/PaginationDots.tsx
src/app/Scenes/HomeView/Components/HeroUnit.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx

This PR improves the hero units rail performance and fixes the re-renders
| <video src="https://github.com/user-attachments/assets/7db76a6f-4985-4cb8-bc2e-3e605b42c201" /> | <video src="https://github.com/user-attachments/assets/5f6d8951-ce41-4907-ad71-350d9e644e4e" /> | 
-
-
-
- [HomeView Performance] do not re-render hero units - mounir
</details>

chore: [HomeView Performance] do not re-render hero units

---

src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx

This PR fixes the unnecessary re-renders happening on the artists rails in home view
| <video src="https://github.com/user-attachments/assets/a5636fcd-2c36-44fe-8d4e-8d51ac785236" /> | <video src="https://github.com/user-attachments/assets/8c9735c8-bb57-420a-afe9-d947c3d5b380" /> | 
-
-
-
- [HomeView Performance] do not re-render artists - mounir
</details>

chore: [HomeView Performance] do not re-render artists

---

src/app/Components/ArticleCard.tsx
src/app/Scenes/HomeView/Components/ArticlesRail.tsx
src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx

This PR improves the editorial rail perofmance and fixes some of the re-rerenders
| <video src="https://github.com/user-attachments/assets/4b3ebf35-8f77-41dc-b82b-3f42a5e18dc2" /> | <video src="https://github.com/user-attachments/assets/b2be4bca-23ab-4212-90f9-831966629f7e" /> | 
-
-
-
- [HomeView Performance] do not re-render articles - mounir
</details>

chore:  [HomeView Performance] do not re-render articles

---

src/app/Scenes/MyAccount/MyAccountEditPriceRange.tsx

This PR resolves [ONYX-1848] 
This PR adds the price range saved tracking event. This was requested by Data and the event was added here 
https://github.com/artsy/cohesion/pull/621
-
-
-
- add price range saved tracking - mounir
</details>
[ONYX-1848]: https://artsyproduct.atlassian.net/browse/ONYX-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add price range saved tracking

---

src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx

This PR updates our impressions tracking implementation to not call `useImpressionsTracking` hook unless `trackItemsImpression` is enabled.
-
-
-
- [HomeView Performance] do not use impressionsTracking infra unless enabled - mounir
</details>

chore: [HomeView Performance] do not use impressionsTracking infra unless enabled

---

src/app/Scenes/OrderHistory/OrderDetail/Components/MessageDetails.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailMessage.tsx
src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailMessage.tests.tsx
src/app/Scenes/OrderHistory/OrderDetail/hooks/useOrderDetailTracking.ts

This PR resolves [EMI-2488] 
This PR adds a link to conversations for the Order Details screen if the order is an offer
|---|---|---|
| Interaction | <video src="https://github.com/user-attachments/assets/8da0ca2a-9ca3-44fe-a19b-ad4571443ab2" />	 | <video src="https://github.com/user-attachments/assets/80e2f12c-4c46-40ee-bf2d-7df376bc8ce2" /> |
| Tracking data (cc @xander-pero) | <img width="420" height="910" alt="image" src="https://github.com/user-attachments/assets/f5de5b41-f2e3-4e66-97f8-324f3262972f" /> | <img width="420" height="910" alt="image" src="https://github.com/user-attachments/assets/aef6aaff-7691-41ed-9711-02a16aaa0048" /> |
- Add contact gallery link to Order Details for offers
-
-
-
</details>
Need help …

feat(EMI-2488): Add conversation link to order details

---

src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx

This PR resolves [PBRW-956] 
Artist screen shipping and taxes learn more layout issue for Android.
-
-
-Fix Artist screen "shipping and taxes" section "Learn more" link layout issue for Android - ole
-
</details>
[PBRW-956]: https://artsyproduct.atlassian.net/browse/PBRW-956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Artist screen shipping and taxes learn more layout issue for Android

---

fastlane/Fastfile

Pass params to explicitly skip apk and aab uploads. @MounirDhahri ran into an issue where if you have an apk locally supply will try to upload that instead of just promoting the selected version code. 
https://artsy.slack.com/archives/C02BAQ5K7/p1753372628833359
-
-
-
- fix case where supply would upload wrong local build - brian
</details>

fix: skip aab + apk uploads to prevent accidental uploads

---

src/app/utils/track/AddAppNamePlugin.ts

little pr review follow up to clean up the plugin
#trivial #skipci #nochangelog

chore: cleaner name setting

---

fastlane/metadata/android/en-US/title.txt
fastlane/metadata/en-US/name.txt

Updates our app title
#trivial #skipci
- update app title - brian
-
-
-
</details>

chore: update app title

---

src/app/Scenes/Onboarding/Onboarding.tsx
src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuiz.tsx

This PR resolves [PHIRE-2043] 
A leftover issue from the migration to navigation days - we forgot to lock the orientation on phones for the onboarding stack. This pr should fix this - thanks to @leamotta for reporting
|---|---|---|
| iOS | <video src="https://github.com/user-attachments/assets/851473b3-3209-4d23-81d3-b1f8dfa3d428" width="400" /> | <video src="https://github.com/user-attachments/assets/671c0c25-1b72-41f1-bdd0-affee5f40e49" width="400" /> |
-
-
-
- fix: update onboarding navigation to use native stack and adjust screen options for orientation
</details> …

fix: update onboarding navigation to use native stack and adjust screen options for orientation

---

src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx

Fix warning `Encountered two children with the same key`
Apparently it happens that we use the same image twice on the Artwork page
To ensure that the key is unique, add index to the string as well: `keyExtractor={(item, index) => item?.url ? '${item.url}${index}' : index.toString()}`
-
-
-
- make sure the children keys are unique, artwork screen, ImageCarousel
</details>

fix: make sure the children keys are unique, artwork screen, ImageCarousel

---

fastlane/utility_fastlane.rb

This PR adds a condition to skip sending a message in slack about the feature flags in caset here aren't any hidden ones
-
-
-
- Skip hidden feature flags slack message if there are none
</details>

chore: Skip message about hidden feature flags if there are none

---

src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionShows.tests.tsx

This PR attempts to fix a flaky test from timing out
-
-
-
- Attempt to fix flaky test
</details>

fix: Attempt to fix flaky test

---

src/app/Components/__tests__/ArtsyWebView.tests.tsx
src/app/Scenes/About/About.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/app/store/config/EchoModel.tsx
src/app/system/devTools/DevMenu/DevMenu.tsx
src/app/system/errorReporting/setupSentry.ts
src/app/system/relay/usePurgeCacheOnAppUpdate.ts
src/app/utils/appVersion.tests.ts
src/app/utils/appVersion.ts

Replaces scattered usage of `appJson().version` and `DeviceInfo.getVersion()` with a unified `getAppVersion()` utility that tries `DeviceInfo` first and falls back to `app.json` for simulator compatibility.
- Add `src/app/utils/appVersion.ts` with `getAppVersion()` and `getBuildNumber()`
- Add comprehensive tests covering all fallback scenarios
- Update 9 files to use new consolidated API
- Ensures reliable version access across real devices and simulators
Prerequisite to https://github.com/artsy/eigen/pull/11730, as it's important to have a reliable version number through a consolidate interface for that feature.
- feat: consolidate app version handling with fallback mechanism
</details>
Need help with something? Have a look at our [docs], or …

feat: consolidate app version handling with fallback mechanism

---

ios/Podfile.lock
package.json
yarn.lock

This PR resolves [PHIRE-2074] 
This PR upgrades @stripe/stripe-react-native to the latest version, which has the new architecture support
| <video src="https://github.com/user-attachments/assets/38352243-2877-466d-93c6-64ca271e2899" /> | <video src="https://github.com/user-attachments/assets/2bc52b8c-f8d9-458c-8a54-c658900a54a3" /> | 
-
-
-
- [QA Required] upgrade @stripe/stripe-react-native - mounir
</details>
[PHIRE-2074]: …

chore: upgrade @stripe/stripe-react-native

---

src/app/Scenes/OrderHistory/OrderDetails/OrderDetails.tsx

This PR resolves [EMI-2739] 
This PR adds an empty state to the Order Details screen in case the query doesn't return data
It also adds an Unable to Load handler in case the query fails
|---|---|---|
| Empty State | <img width="360" height="787" alt="image" src="https://github.com/user-attachments/assets/32fcba2b-775f-4824-8c35-125e831f397b" /> | <img width="360" height="787" alt="image" src="https://github.com/user-attachments/assets/c9df806b-829d-45d5-b6af-3e1587dfb9b4" /> |
| Error State | <img width="360" height="787" alt="image" src="https://github.com/user-attachments/assets/9f5c9dc5-1351-402f-a67b-567d71ad579c" /> | <img width="360" height="787" alt="image" src="https://github.com/user-attachments/assets/927b19dd-c6bc-42a6-8959-94bf0191ea96" /> | …

fix(EMI-2739): Add empty state and error state for Order Details screen

---

src/app/Scenes/ForceUpdate/ForceUpdate.tsx
src/app/Scenes/Shows/__tests__/ShowsForYou.tests.tsx

Add build details on force update screen for debugging purposes, build number is unavailable on the simulator.
Bonus: flaky test fix
-
-
-
- add debugging details on force update staging screen
</details>

build(dev): staging build details on force update screen

---

src/app/Components/BottomSheet/AutoHeightBottomSheet.tsx

When working on something unrelated got this TS error when trying to push:
```sh
$ /Users/georgioskartalis/Artsy/eigen/node_modules/.bin/tsc
src/app/Components/BottomSheet/AutoHeightBottomSheet.tsx:17:7 - error TS2590: Expression produces a union type that is too complex to represent.
17       <BottomSheetView>{children}</BottomSheetView>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in src/app/Components/BottomSheet/AutoHeightBottomSheet.tsx:17
```
Updated the types to be happy and more explicit about the children
-
-
-
- add children prop to AutoHeightBottomSheet for better typing #trivial
</details> …

fix(types): add children prop to AutoHeightBottomSheet for better typing

---

.circleci/config.yml
ios/Podfile.lock
package.json
yarn.lock

This PR resolves [PHIRE-2079] 
bump react-native-localize to a version that supports new architecture of react native
-
-
-
- bump react-native-localize to a version that supports newarch
</details>
[PHIRE-2079]: https://artsyproduct.atlassian.net/browse/PHIRE-2079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build(deps): bump react-native-localize to a version that supports newarch

---

ios/Podfile.lock
package.json
yarn.lock

This PR resolves [PHIRE-2102] 
Updates react native document picker to fix a compilation error on the new architecture:
https://github.com/react-native-documents/document-picker/releases/tag/v9.3.1
Side note:
This library was rewritten and the package renamed, we should probably migrate to the newer version:
https://www.npmjs.com/package/react-native-document-picker
-
-
-
- update react native document picker - brian
</details>
[PHIRE-2102]: https://artsyproduct.atlassian.net/browse/PHIRE-2102?atlOrigin=eyJpI …

chore: update react-native-document picker to fix compilation on new arch

---

.circleci/config.yml
.github/workflows/build-maestro-android.yml
.github/workflows/build-maestro-ios.yml
fastlane/Fastfile
fastlane/utility_fastlane.rb

Updates `build-maestro-ios.yml` and `build-maestro-android.yml` to use fastlane for bumping the versions properly and for consistency.
-
-
-
- maestro builds with fastlane instead of local
</details>

build(refactor): maestro builds with fastlane instead of local 

---

package.json
yarn.lock

Part 2 of some PRs that we need to do in order to be able to use rozenite without issues. The issue wasn't rozenite exactly but npm package conflicts that were preventing the proper initialization of rozenite.
This PR bumps react-use to use the latest version
-
-
-
- bump react-use to latest
</details>

build(deps): bump react-use to latest

---

package.json
src/app/Components/ProgressiveOnboarding/__tests__/useDismissSavedArtwork.tests.tsx
src/app/Navigation/utils/__tests__/useBottomTabsBadges.tests.ts
src/app/Scenes/CompleteMyProfile/hooks/__tests__/useCompleteMyProfileSteps.tests.tsx
src/app/Scenes/CompleteMyProfile/hooks/__tests__/useCompleteProfile.tests.tsx
src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/config.tests.ts
src/app/system/flags/hooks/__tests__/useUnleashInitializer.tests.ts
src/app/utils/__tests__/useEventTiming.tests.ts
src/app/utils/__tests__/useGlobalState.tests.tsx
src/app/utils/__tests__/usePreferredThemeTracking.tests.ts
src/app/utils/__tests__/useScreenReaderAndFontScaleTracking.tests.ts
src/app/utils/__tests__/useWebViewEvents.tests.ts
src/app/utils/hooks/__tests__/useBackHandler.tests.ts
src/app/utils/hooks/__tests__/useIsDeepLink.tests.ts
src/app/utils/hooks/__tests__/useStableShuffle.tests.ts
yarn.lock

Part 1 of some PRs that we need to do in order to be able to use rozenite without issues.
This one removes `@testing-library/react-hooks` and refactors tests to use `@testing-library/react-native` since it now includes the functions that we were using for `@testing-library/react-hooks`.
-
-
-
- remove @testing-library/react-hooks library and refactor hook tests
</details>

refactor(testing-library): remove testing library react hooks

---

Gemfile.lock
fastlane/Pluginfile

bumps fastlane deps and removes obsolete fastlane-plugin-appcenter.
-
-
-
- bump fastlane deps
</details>

build(deps): bump fastlane deps & remove fastlane-plugin-appcenter

---

fastlane/Fastfile
fastlane/utility_fastlane.rb

Refactor in order to  send slack alert on build failure of beta or maestro builds on gh actions.
Replaced circle ci workflow links for slack with gh actions links.
-
-
-
-  send slack alert on build failure of beta or maestro builds
</details>

feat: send slack alert on build failure of beta or maestro builds

---

src/app/Components/ArtworkFilter/Filters/YearOptions.tsx

This PR aligns the checkbox withing auction results date filter with the rest of the app
| unchecked | checked |
| <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-09-17 at 11 05 54" src="https://github.com/user-attachments/assets/df5db7c5-7431-4045-a547-747972c51156" /> | <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-09-17 at 11 05 56" src="https://github.com/user-attachments/assets/85155b49-2c9d-4294-a893-de2b2c9fab52" /> | 
- align checkbox on auction results date filter - mounir
-
-
-
</details> …

chore: align checkbox on auction results date filter

---

src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx

When throthling, we could see an unwanted Spinner on the search overlay. This PR sets it to null to avoid this UI glitch.
cc @artsy/diamond-devs 
|---|---|---|
| iOS | <video src="https://github.com/user-attachments/assets/d06ff64b-8cac-43b2-8444-13e1321d0c75" width="400" /> | <video src="https://github.com/user-attachments/assets/ac214e50-4854-4606-91a5-df3c8e954209" width="400" /> |
- fix: use null loading fallback on GlobalSearchInputOverlay
-
-
-
</details>

fix(Search): remove Spinner from GloabalSearchInputOverlay

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkGrids/ArtworkSaveIconWrapper.tsx

This PR fixes CI after the last save icon echo flag release
-
-
-
-
</details>

fix: broken test

---

.gitignore

This PR adds `.cursor/mcp.json` to `.gitignore`. The file gets added automatically by Cursor on open and it's annoying to keep removing it
-
-
-
- add .cursor/mcp.json to .gitignore - mounir
</details>

chore: add .cursor/mcp.json to .gitignore

---

android/app/build.gradle

This PR resolves [PHIRE-2322] 
This PR upgrades our implementation of WebP to support 16 KB Page sizes. See Jira ticket for more context
-
-
-
- upgrade webp implementation to support 16KB page sizes - mounir
</details>
[PHIRE-2322]: https://artsyproduct.atlassian.net/browse/PHIRE-2322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: upgrade webp implementation to support 16KB page sizes

---

e2e/perf/perf-test-home.yml
e2e/perf/run-perf-tests.sh

Still wip, but:
This PR introduces a flashlight maestro script and a simple performance test which opens the app and scrolls to the bottom and back up.
You can run it locally by `./e2e/perf/run-perf-tests.sh`.
It generates two files:
1. A JSON file with performance results, named with a timestamp (e.g., flashlight_results_2025-09-23_15-42-10.json).
2. A video recording of the test run, saved in the current directory (e.g ., flashlight_recording_2025-09-23_15-42-10_iteration_01758644695384.mp4).
You can see the performance results by running after you run the test the following:
```bash
flashlight report flashlight_results_2025-09-23_15-42-10.json
```
Or if you want to compare between two runs:
```bash
flashlight report flashlight_results_2025-09-22_14-30-05.json …
```

feat: add simple flashlight performance test for now

---

.yarnrc.yml

This PR resolves [PHIRE-2288] 
Disable postinstall scripts from 3rd parties, our own postinstall scripts still run.
We can add exceptions if needed like so:
```
enableScripts:
- package-name
```
#trivial 
-
-
-
- disable 3rd party postinstall scripts - brian 
</details>
[PHIRE-2288]: https://artsyproduct.atlassian.net/browse/PHIRE-2288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: disable 3rd party postinstall scripts #trivial

---

.yarnrc.yml

Add missed internal packages to exclude from age gate. 
-
-
-
- missed package exclusions for yarn age gate - brian
</details>

chore: missed internal package exclusions #trivial #skipci

---

src/app/Scenes/MyAccount/MyAccountDeleteAccount.tsx

This PR resolves [DIAM-27] 
Fixes an issue causing the keyboard avoiding view not to function properly in the account delete page. 
Stole some implementation details from @MrSltun in working credit card form
- added behavior prop to KeyboardAvoidingView, contentStyle props to ScrollView
- main change to get it working is moving the bottom buttons outside the scrollview
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/a81577e5-9ec2-446e-adb3-98e251a41986" width="400" /> | <video src="https://github.com/user-attachments/assets/12f61815-b7e9-468f-bf22-973a5a8227d9" width="400" /> |
| iOS | <video src="https://github.com/user-attachments/assets/15cf7c0d-0168-467a-9b94-95b67e1c57e5" width="400" /> | <video …

fix: keyboard blocks password field in account delete

---

HACKS.md
ios/Podfile.lock
package.json
patches/react-native-reanimated+3.17.5.patch
yarn.lock

Downgrade reanimated to 3.17.5
-
-
-
-
</details>

chore: downgrade reanimated
