src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/__tests__/MyCollectionArtworkDemandIndex-tests.tsx

This PR resolves [CX-783]
Update upper limit label for demand index progress bar.
[CX-783]: https://artsyproduct.atlassian.net/browse/CX-783

fix: fix upper limit label of demand rank #trivial

---

src/lib/Scenes/Sale/Sale.tsx

This PR resolves [CX-803]
- Adds screen tracking for the new sale screen
- Centralizes the tracking code in the Sale component to match the recommendations in [the analytics and tracking docs](https://github.com/artsy/eigen/blob/master/docs/analytics_and_tracking.md#inside-react-components).
Tracked event in action: 
The event details: 
[CX-803]: https://artsyproduct.atlassian.net/browse/CX-803

fix: Add screen tracking for sale screen

---

src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/Field.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx

This PR resolves [CX-778]
Adds flex: 1 to make text components respect Flexbox, updates number of lines and maxWidth where applicable.
[CX-778]: https://artsyproduct.atlassian.net/browse/CX-778

fix: text wrapping fixes in my collection #trivial

---

CHANGELOG.yml
src/__generated__/Fair2CollectionsTestsQuery.graphql.ts
src/__generated__/Fair2Collections_fair.graphql.ts
src/__generated__/Fair2Query.graphql.ts
src/__generated__/Fair2TestsQuery.graphql.ts
src/__generated__/Fair2_fair.graphql.ts
src/__generated__/VanityURLEntityQuery.graphql.ts
src/lib/Scenes/Fair2/Components/Fair2Collections.tsx
src/lib/Scenes/Fair2/Fair2.tsx

Follow-up to similar web PR: https://github.com/artsy/force/pull/6609
This commit bumps the max number of marketing collections fetched from 4 to 5.
Slack thread: https://artsy.slack.com/archives/C9SATFLUU/p1604617773492800

feat(fair): show up to 5 marketing collections on fair screen

---

src/__generated__/Show2ArtworksEmptyStateTestsQuery.graphql.ts
src/__generated__/Show2ArtworksEmptyState_show.graphql.ts
src/__generated__/Show2Query.graphql.ts
src/__generated__/Show2TestsQuery.graphql.ts
src/__generated__/Show2_show.graphql.ts
src/lib/Scenes/Show2/Components/Show2ArtworksEmptyState.tsx
src/lib/Scenes/Show2/Components/Show2ContextCard.tsx
src/lib/Scenes/Show2/Show2.tsx
src/lib/Scenes/Show2/__tests__/Show2ArtworksEmptyState-tests.tsx

This PR resolves [FX-2413]
Pretty much the same implementation as web
[FX-2413]: https://artsyproduct.atlassian.net/browse/FX-2413

fix(fx-2413): handles empty state for shows/booths without artworks

---

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts

This PR resolves a bug found in QA. [PURCHASE-2223](https://artsyproduct.atlassian.net/browse/PURCHASE-2223]) is the one I set out to address (shipping checkbox gets its logic flipped if you exit/enter the form with it checked) but I think this actually will fix another bug where the 'send' button gets similarly messed up. I don't know if that was found in QA since I reported the former and assumed they were the same thing - they are not.
On an implementation level it:
- Extracts the 'inquiry question' checkbox into its own component
- cleans up some logic within the component, moving Animation setup into `useLayoutEffect`
- resets the form when exiting the inquiry modal, which prevents another bug causing the shipping checkbox to get flipped after exiting …

fix: reset form when returning to artwork screen

---

CHANGELOG.yml
src/lib/AppRegistry.tsx

Adds `hasOwnModalCloseButton` property to consignments and inquiry modals registration, without this property a close button is added to the top of screen pushing content down. For these screens this cause the close/done button that is supposed to hover above the keyboard to be pushed below the keyboard making it untappable.

fix: set close button property in modals

---

CHANGELOG.yml
src/lib/Scenes/Show2/Show2.tsx

This PR resolves [CX-818]
- Fix Skeleton loader on Shows page to match actual layout
[CX-818]: https://artsyproduct.atlassian.net/browse/CX-818

fix: show 2 skeleton adjustment

---

CHANGELOG.yml
src/lib/Scenes/Show2/Show2.tsx
src/lib/Scenes/Show2/__tests__/Show2-tests.tsx

This PR resolves [FX-2437]
Hide the (sort/filter) control unless there are artworks present to
sort/filter.
[FX-2437]: https://artsyproduct.atlassian.net/browse/FX-2437
Show in screenshots: https://www.artsy.net/show/annka-kultys-gallery-group-show-quid-est-veritas-curated-by-anton-svyatsky

fix(show): only display sort/filter control if eligible artworks present

---

CHANGELOG.yml
src/lib/Scenes/Show2/Show2.tsx

This PR resolves [CX-817]
- Add extra padding to new show screen
**Before**
___
**After**
[CX-817]: https://artsyproduct.atlassian.net/browse/CX-817

fix: add extra padding to new show screen

---

CHANGELOG.yml
src/lib/Scenes/Show2/Show2.tsx

This PR resolves [CX-816]
- Link sort and filter screen to scroll position on new show screen
[CX-816]: https://artsyproduct.atlassian.net/browse/CX-816

fix: link sort and filter screen to scroll position on new show screen

---

CHANGELOG.yml
src/lib/Scenes/Sale/Sale.tsx

This PR is related to [CX-805]
We were passing the artwork slug where we should be passing the artwork ID when tracking taps on the sale home grid. This PR resolves that issue.
What the event looks like now:
[CX-805]: https://artsyproduct.atlassian.net/browse/CX-805

fix: pass id into  event instead of slug

---

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts

[PURCHASE-2181] 
Adds an error message to the modal view when the `SubmitInquiryRequest` mutation errors out
paired with @erikdstock on tests
Error message is dismissed on modal close or successful send
[PURCHASE-2181]: https://artsyproduct.atlassian.net/browse/PURCHASE-2181

Display error message when an inquiry is unable to be sent

---

Artsy/App/ARAnalyticsConstants.h
Artsy/App/ARAnalyticsConstants.m
Artsy/View_Controllers/Util/ARNavigationController.m
CHANGELOG.yml

The type of this PR is: **Deprecation**
This PR resolves [CX-824]
We were tracking every tap of the back arrow, but per @mikehrom no one was using it. This PR removes that tracking to help prevent us from reaching our tracking event budget. 
_This gif demonstrates that I've got on-screen analytics enabled, but no event is being tracked on tap of back-arrow:_
[CX-824]: https://artsyproduct.atlassian.net/browse/CX-824

chore: remove back arrow analytics tracking

---

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/LocationAutocomplete.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/ShippingModal.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/LocationAutocomplete-tests.tsx
src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
src/lib/utils/__tests__/googleMaps-tests.ts
src/lib/utils/googleMaps.ts

This PR resolves [PURCHASE-2226]
When a user checks the shipping quote checkbox and adds a shipping location, the location was not being persisted through to the Inquiry Request instance in gravity. This is caused by two bugs:
1. The way we were previously assigning the shipping location to details was incorrect.
2. We were passing the shipping location as a string when the backend expects an object/hash.
The new implementation makes an additional api request to get an object that represents the city location and handles updating the shipping quote inquiry questions with details in the submit function when we have all the necessary data. 
Paired with @erikdstock 
[PURCHASE-2226]: https://artsyproduct.atlassian.net/browse/PURCHASE-2226

fix: persist shipping location for inquiry requests

---

src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistArticles-tests.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/WhySell.tsx

This PR resolves [CX-781]
Minor visual qa fixes for my collection:
- Respect margins in lists on artwork page
- Update separators to be 1 px
- List view padding and additional details padding mentioned in ticket were fixed already in previous PRs
[CX-781]: https://artsyproduct.atlassian.net/browse/CX-781

fix: my collection visual qa #trivial

---

src/__generated__/InquiryButtonsTestsQuery.graphql.ts
src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryButtons-tests.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts

This PR resolves [PURCHASE-2099]
Enables a 2 second notification after an inquiry message mutation successfully completes.
[PURCHASE-2099]: https://artsyproduct.atlassian.net/browse/PURCHASE-2099

[PURCHASE-2099] Enhancement: Enable inquiry request notifications

---

src/lib/Components/ArtworkFilterOptions/PriceRangeOptions.tsx
src/lib/Components/ArtworkFilterOptions/__tests__/PriceRangeOptions-tests.tsx
src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts

This PR resolves [FX-2398]
This tackles two of the tasks in the associated ticket:
- Change the title of the price range filter from "Price/estimate range"
- Change the ordering of the price buckets from highest to lowest
After looking into it, this PR _punts on_ the following change from the ticket, since this appears to require upstream changes to Gravity ~and Metaphysics(?)~ (I will split out the ticket accordingly):
- Split the USD 10,000–50,000 bucket into 10,000–25,000 and 25,000–50,000
While the change was ticketed for Fairs…
…it is also intended to take effect globally (artist, series, collection, show), which these screen caps partly demonstrate: 
The one exception is the auction filters, which should continue to show the "Price/estimate" …

feat: change title and ordering of artwork price range filter

---

src/lib/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
src/lib/Scenes/Inbox/Components/Conversations/Messages.tsx

This PR resolves [PURCHASE-2234]
@xtina-starr noticed that inquiries sent w/ no message caused the artwork preview not to display at the beginning on the conversation. 
[PURCHASE-2234]: https://artsyproduct.atlassian.net/browse/PURCHASE-2234

fix: Ensure image still renders if first message empty

---

src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx

Moved the trim to the submit to avoid it getting triggered on every keyup. Otherwise, every time the user would put in a space between words the trim would trigger.

fix: Move first inquiry message trim

---

Artsy/App/ARScreenPresenterModule.m
CHANGELOG.yml
src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
src/lib/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx

This PR resolves 
- https://www.notion.so/artsy/Profile-Account-updating-phone-number-or-name-probably-others-doesn-t-dismiss-edit-field-scree-e46392df7c214ea388e1c4f11ee3d1c6
- https://www.notion.so/artsy/Profile-Payment-Add-new-card-error-message-doesn-t-appear-or-appears-for-only-a-split-second--2818c677b1b643c4a0527199d897593d
These bugs were triggered when react-native changed the way `Modal#onDismiss` is invoked. It used to be called whenever the native modal was hidden (controlled by the `visible` prop), and now it is only called when the react component unmounts. https://github.com/facebook/react-native/commit/bd2b7d6c0366b5f19de56b71cb706a0af4b0be43
On this edit screen we use the `onDismiss` callback to trigger alerts or navigation actions safely (these can cause bugs if …

fix(MyAccount): field edit nav issues

---

src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkPriceEstimateTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkPriceEstimate_artwork.graphql.ts
src/__generated__/MyCollectionArtworkPriceEstimate_marketPriceInsights.graphql.ts
src/__generated__/MyCollectionArtworkQuery.graphql.ts
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx

Paired with @pepopowitz on this.
This PR resolves [CX-632]
Use artwork size bucket to choose price estimates from Metaphysics/Diffusion.
[CX-632]: https://artsyproduct.atlassian.net/browse/CX-632

feat: respect artwork size when showing price estimates

---

src/__generated__/InboxOldQuery.graphql.ts
src/__generated__/InboxOldRefetchQuery.graphql.ts
src/__generated__/InboxOld_me.graphql.ts
src/__generated__/InboxQuery.graphql.ts
src/__generated__/InboxRefetchQuery.graphql.ts
src/__generated__/InboxTestsQuery.graphql.ts
src/__generated__/Inbox_me.graphql.ts
src/lib/Containers/Inbox/Inbox.tsx
src/lib/Containers/Inbox/InboxOld.tsx
src/lib/Containers/Inbox/index.tsx
src/lib/Containers/__tests__/Inbox-tests.tsx
src/lib/Containers/__tests__/InboxOld-tests.tsx
src/lib/Containers/__tests__/InboxWrapper-tests.tsx

This is a PR to your development branch @lilyfromseattle - totally your call on whether to incorporate it, and I'm not sure if it would be considered best practice or not so tagging some others as well.
I was thinking about the sort of complicated display logic in our Inbox component and in particular how we are fetching both  the old `lotStandings` (from gravity) and the new `auctionsLotStandingConnection`* and wondered if we can separate these out, so I made a PR to do that.
In short, I split `Inbox.tsx` into a directory with `Inbox` & `InboxOld` (the version of `Inbox.tsx` currently on master) plus an `InboxWrapper` (which checks the AREmissionOptions to decide which to display. 
As a side benefit we are working with a new single component now so can iterate on it without worrying …

chore: split old and new inboxes

---

package.json
src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Bidding/__tests__/Helpers/FakeNavigator.tsx
src/lib/Components/Disappearable.tsx
src/lib/Components/Select.tsx
src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
src/lib/utils/__tests__/ExecutionQueue-tests.ts
yarn.lock

The main breaking change was that function signatures like  `blah(arg: any): whatever` can no longer be called without an explicit argument like `blah()`. You have to explicitly declare the parameter as having type `void`.
This was so painless 🙌

chore: upgrade typescript

---

CHANGELOG.yml
src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
src/__generated__/MyCollectionArtworkQuery.graphql.ts
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkInsights-tests.tsx

This PR resolves [CX-776]
Builds text based on artist, category and size in the `Price and market insights` subsection.
[CX-776]: https://artsyproduct.atlassian.net/browse/CX-776

feat(my collection): dynamic helper text

---

CHANGELOG.yml
src/lib/Components/FancyModal/FancyModal.tsx
src/lib/Components/FancyModal/FancyModalCard.tsx
src/lib/Components/FancyModal/FancyModalContext.tsx

This PR resolves [CX-765]
This ticket makes it so that half-page (non-fullscreen) fancy modals do not cause their backgrounds to shrink.
Fancy Modal is implemented as a stack of cards, of arbitrary depth. Before this change each card would shrink to a linear degree when it was below the top card. Now not all cards shrink relative to the card above, so it's no longer a linear calculation. Now we need to look at the whole stack and kinda merge the cards that don't shrink into the cards above them.
[CX-765]: https://artsyproduct.atlassian.net/browse/CX-765

fix: avoid shrinking the background on non-fullscreen fancy modals

---

CHANGELOG.yml
patches/@types+relay-test-utils+6.0.1.patch
src/lib/Scenes/Sale/__tests__/RegisterToBidButton-tests.tsx
src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomSubsections-tests.tsx
src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx
src/lib/tests/mockEnvironmentPayload.ts

The motivation for this PR was me wanting to test without having to fill all the required fields, and ideally no fields at all. I guess it's kinda RFC too?
- I added `DefaultMockResolvers` for `ID` and `String` fields, so that they generate mock data like 
```
{
id: "id-1",
title: "title-1"
}
```
- One extra thing here is that if we have something with possible duplicate names, it will fix it like so:
```
{
artist: {
id: "id-1"
name: "name-1",
artworks: {
edges: [
{ node: {
id: "artworks.id-1",
slug: "slug-1"
}},
]
}
}
}
```
- Also, in an `edges` array, this will generate this like `id-1`, `title-1` for the first item, `id-2`, `title-2` for the second etc.
- Lastly, I added a `mockArray` that takes a number for the length of …

tooling(relay-tests): add default mock resolvers and an array generator and some helpers

---

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx

This PR resolves [PURCHASE-2229]
before:
after: 
[PURCHASE-2229]: https://artsyproduct.atlassian.net/browse/PURCHASE-2229

Fix: Contact gallery should be primary

---

Podfile.lock
src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx

#minor
Fixes [PURCHASE-2225]
This PR adds a ScrollView wrapper to the main content of the inquiry modal. The GIF below shows it working with a bunch of spaces added in. The spacers illustrate that the cause of this is not the expanded artwork details but just any content too big to fit on the modal.
I'm not sure if i used the scrollview correctly - it was the first thing I tried after looking over the react-native docs.
[PURCHASE-2225]: https://artsyproduct.atlassian.net/browse/PURCHASE-2225

Fix: add ScrollView to modal content

---

src/lib/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CollapsibleArtworkDetails-tests.tsx
src/palette/elements/Collapse/Collapse.tsx

This PR resolves [PURCHASE-2248]
Replaced the makeshift component with Pallette's collapse to avoid issue where artwork information would visually overlap. See ticket for former behaviour. Current behaviour:
[PURCHASE-2248]: https://artsyproduct.atlassian.net/browse/PURCHASE-2248

fix: Fix artwork information overlap in first inquiry collapse

---

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx

This PR resolves [PURCHASE-2253](https://artsyproduct.atlassian.net/browse/PURCHASE-2253)
Inquiry question border should be black100/#FFFFF when selected. This PR adds a prop to enable this.

[PURCHASE-2253] Fix: enable active state on border when inq question selected

---

fastlane/Fastfile

Added this based on the Lunch&Learn. It was added to Sentry's fastlane plugin here: https://github.com/getsentry/sentry-fastlane-plugin/pull/54 I think I'm adding in some extraneous properties here, but better safe than sorry. I've kicked off a beta to test this here: https://app.circleci.com/pipelines/github/artsy/eigen/7528/workflows/532a48c0-562f-40e1-9e1b-198fa5056c1d

chore: add Sentry commit integration

---

CHANGELOG.yml
src/lib/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx

This 'X' is intended to dismiss the modal but because this delay is short tapping the 'X' in the 'Toast' is mainly just linking me to the inbox as its a very quick tap. We should remove the 'X' to eliminate confusion. 
_It now looks like this:_ 
[PURCHASE-2273]: https://artsyproduct.atlassian.net/browse/PURCHASE-2273

enhancement: Remove the 'X' to exit the confirmation modal

---

Podfile.lock
src/lib/Scenes/Artwork/Artwork.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/LocationAutocomplete.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/ShippingModal.tsx

#minor
This PR resolves [PURCHASE-2250]
This PR fixes a bug where the user, when trying to tap a search suggestion, must tap twice since the first dismisses the keyboard. It also includes an optimization for autofocusing the input.
It requires adding a prop at the very top of the Artwork Scene component hierarchy, so we should be aware if there are any unusual keyboard behaviors within an artwork view that we want to avoid. I'm not aware of any.
[PURCHASE-2250]: https://artsyproduct.atlassian.net/browse/PURCHASE-2250

fix: selecting search suggestion requires double tap (to clear keyboard)

---

src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx

This PR resolves [CX-772]
This is a bug that only happens when running directly on a device (i.e. not when debugging on the device). I'm guessing that this is some problem with JavascriptCore, the iOS JS engine, although I tried debugging with Safari, which usually picks up problems specific to JavascriptCore. So I think we should try merging this, and then test it once it's been deployed to a beta.
[CX-772]: https://artsyproduct.atlassian.net/browse/CX-772

fix(my collection): save changes button state #trivial

---

src/lib/Containers/Inbox/Inbox.tsx
src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx

[PURCHASE-2275]
The conversation order does not update on refresh - for example, a convo with a new reply from the gallery doesn't appear at the top of the inbox. This PR fixes that.
After struggling with this for hours, I paired with @ashleyjelks who solved it in 10 minutes!
UPDATE: Ended up changing my implementation entirely after realizing that leftover `activeBids` stuff in `Inbox` was preventing the existing refresh logic from working
[PURCHASE-2275]: https://artsyproduct.atlassian.net/browse/PURCHASE-2275

Bugfix: Conversation does not move to the top of the inbox when a gallery responds

---

CHANGELOG.yml
Podfile
Podfile.lock

This PR resolves [CX-875]
The Pulley dependency we use for the city guide UI had some issues on iOS 14 with updating certain properties causing an autolayout loop that would cause the UI to hang here: https://github.com/52inc/Pulley/issues/390 and this is what is causing city guide not to launch. We are using a fork of the original repo that exposes some properties to Objective-C and addresses some bugs here:  https://github.com/l2succes/Pulley. The issues have since been fixed in the original repo. This PR points to a fork that pulls in those changes. Also opened a PR in the fork we are using here: https://github.com/l2succes/Pulley/pull/4, if that gets merged we can point to that fork again.   
[CX-875]: https://artsyproduct.atlassian.net/browse/CX-875

fix: point to Pulley fork with iOS 14 fixes

---

src/lib/Components/Bidding/Components/Checkbox.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx

This PR resolves [PURCHASE-2272]
This PR makes the whole area, not just the checkbox, clickable for first inquiry fields. It also adds functionality to the checkbox component to change when the `checked` prop changes.
[PURCHASE-2272]: https://artsyproduct.atlassian.net/browse/PURCHASE-2272

feat: wrap first inquiry checkbox with touchable

---

CHANGELOG.yml
src/lib/Components/TextArea.tsx

This PR resolves [PURCHASE-2285]
While QA'ing during Sprintly CX Mobile App QA Session we noticed that the keyboard was hiding the textarea again. This was because we were overriding the onFocus prop in the TextArea component. This PR makes sure to call the `onFocus` and `onBlur` functions if they are present on `props`.
[PURCHASE-2285]: https://artsyproduct.atlassian.net/browse/PURCHASE-2285

fix: ensure we do not override the onFocus prop

---

CHANGELOG.yml
fastlane/Fastfile

Adds a slack notification when beta lane fails for any reason based on discussion in retro and feedback at front-end-ios (now mobile) practice.

feat(ci): add slack notification when betas fail

---

src/lib/Components/Bidding/Components/Checkbox.tsx

This PR resolves [PURCHASE-2297]
This is a small fix for the `Checkbox` component. To change the checkbox programatically, it was relying on a check of the `props.checked` value, which would return `false` if it was indeed not checked. This fix checks if it's present rather than its value.
[PURCHASE-2297]: https://artsyproduct.atlassian.net/browse/PURCHASE-2297

fix: Fix check for checked property on Checkbox

---

Makefile

The other day, I had to run `make promote_beta_to_submission` because I had previously checked out older code with outdated node modules. This PR adds `--no-verify` to appropriate Makefile tasks.

chore: adds --no-verify to Makefile commands #trivial

---

src/lib/Containers/Inbox/Inbox.tsx
src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx

This PR resolves [PURCHASE-2303]
Fixes an issue that would cut the messages when there were only a few present and pulling to refresh (see ticket). Now looks like this:
[PURCHASE-2303]: https://artsyproduct.atlassian.net/browse/PURCHASE-2303

fix: Allow conversations to take up full height

---

src/lib/Scenes/MyBids/Components/ActiveLot.tsx
src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx

[PURCHASE-2293]
This pr fixes an issue where live auctions would show all winning lots as 'reserve not met.' in fact, reserve is never met in a live auction. This PR fixes the property check. The test was written in a way that it passed wrongly.
#squashongreen
[PURCHASE-2293]: https://artsyproduct.atlassian.net/browse/PURCHASE-2293

Fix: live lots a user is winning always appear as 'reserve not met'

---

src/__generated__/ActiveLot_lotStanding.graphql.ts
src/__generated__/ClosedLot_lotStanding.graphql.ts
src/__generated__/InboxQuery.graphql.ts
src/__generated__/InboxRefetchQuery.graphql.ts
src/__generated__/InboxTestsQuery.graphql.ts
src/__generated__/MyBidsPaginatedQuery.graphql.ts
src/__generated__/MyBidsQuery.graphql.ts
src/__generated__/MyBidsTestsQuery.graphql.ts
src/__generated__/MyBids_me.graphql.ts
src/lib/Scenes/MyBids/Components/ActiveLot.tsx
src/lib/Scenes/MyBids/Components/ClosedLot.tsx
src/lib/Scenes/MyBids/MyBids.tsx
src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx
src/lib/Scenes/MyBids/__tests__/ClosedLot-tests.tsx
src/lib/Scenes/MyBids/__tests__/MyBids-tests.tsx
src/lib/Scenes/MyBids/helpers/timely.ts

This PR completes [PURCHASE-2294]
#minor
In short this pr switches to use `sellingPrice` rather than `floorSellingPrice` (which only respects bids recognized by the live floor auctioneer) on the my bids screen. It also switches to use `LotStanding.lot` over the deprecated `lotState` field. It's mostly a find/replace and removing some aliased field names.
To QA: Verify that artworks display with identical current bid amount on both my bids and the artwork's screen. Bid count, also included in the jira ticket, should also match.
[PURCHASE-2294]: https://artsyproduct.atlassian.net/browse/PURCHASE-2294

fix: switch to preferred lot and sellingPrice fields

---

src/__generated__/ConversationsTestsQuery.graphql.ts
src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
src/lib/Scenes/Inbox/Components/Conversations/NoMessages.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/Conversations-tests.tsx

This PR resolves [PURCHASE-2304]
This PR adds a missing screen for when a user has no messages on the new inbox.
[PURCHASE-2304]: https://artsyproduct.atlassian.net/browse/PURCHASE-2304

feat: Add empty messages notice and cta for new inbox

---

src/lib/Containers/Inbox/Inbox.tsx
src/lib/Scenes/MyBids/Components/Lot.tsx
src/lib/Scenes/MyBids/Components/SaleCard.tsx
src/lib/Scenes/MyBids/MyBids.tsx

This PR resolves [PURCHASE-2305]
Context [here](https://www.notion.so/artsy/Visual-QA-f9e712e683d94b41a4bf36ed511a1d01).
This PR fixes a few small issues found while QAing. [Context](https://www.notion.so/artsy/Visual-QA-f9e712e683d94b41a4bf36ed511a1d01).
1. Fixes issue that would show bids aligning centre instead of on top.
2. Wrapping on lot first column was incorrectly calculated. This allows for more space for the artist name.
3. Adjusts margins on top of Inbox to fit with My Profile top.
4. Added margin on top of registration CTA to make it look more even (not in GIF).
[PURCHASE-2305]: https://artsyproduct.atlassian.net/browse/PURCHASE-2305

fix: Visual QA fixes for new Inbox

---

CHANGELOG.yml
emission/Pod/Classes/EigenCommunications/ARPHPhotoPickerModule.m
src/__generated__/MyCollectionArtworkHeaderTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
src/__generated__/MyCollectionArtworkImagesQuery.graphql.ts
src/__generated__/MyCollectionArtworkImages_artwork.graphql.ts
src/__generated__/MyCollectionArtworkQuery.graphql.ts
src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAddPhotos.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkImages/MyCollectionArtworkImages.tsx
src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx

This PR resolves [CX-889]
Fixes an issue that was causing artwork images to appear grainy in My Collection. The url we were using from metaphysics was not the gemini url with ":version" component so we were getting the wrong processed  image to display.
- Uses `imageURL` with version component rather than `url` from metaphysics
- Passes in explicit compression options to avoid unnecessary compression in native module 
[CX-889]: https://artsyproduct.atlassian.net/browse/CX-889

fix: low quality my collection images

---

src/lib/Containers/Inbox/Inbox.tsx
src/lib/Scenes/Inbox/Components/Conversations/NoMessages.tsx
src/lib/Scenes/MyBids/Components/ActiveLot.tsx
src/lib/Scenes/MyBids/Components/Lot.tsx
src/lib/Scenes/MyBids/Components/NoBids.tsx
src/lib/Scenes/MyBids/Components/SaleCard.tsx
src/lib/Scenes/MyBids/MyBids.tsx

This PR resolves [PURCHASE-2312]
Resolves the items marked `visual` [here](https://www.notion.so/artsy/Bid-Management-5c1c86e18ded47be9c76d3d109b0c988).
This PR resolves the visual issues found during the second round of My Bids QA:
- Animates opacity of tabs when switching back and forth
- Adds border radius to thumbnails
- Corrects right margin on thumbnail
- Removes border radius on banner image
- Adds horizontal margin on empty bids and inquiries pages
[PURCHASE-2312]: https://artsyproduct.atlassian.net/browse/PURCHASE-2312

fix: MyBids visual QA round 2

---

src/lib/AppRegistry.tsx

tiny visual change for the back button to not overlap the title.
before:
after:

styling(safe area): tiny fix

---

src/__generated__/MyCollectionArtworkHeaderTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
src/__generated__/MyCollectionArtworkQuery.graphql.ts
src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/__tests__/MyCollectionArtworkHeader-tests.tsx

Added analytics tracking to `TappedCollectionArtworkImages`, as part of @pepopowitz's [PR #4259](https://github.com/artsy/eigen/pull/4259). In MyCollection, this action is on an artwork view when a user taps the main image. The change includes a test.

feat: Add analytics tracking to image click in MyCollectionArtworkHeader

---

Artsy/App/ARScreenPresenterModule.m
CHANGELOG.yml
src/lib/AppRegistry.tsx
src/lib/Scenes/BottomTabs/BottomTabType.ts

This unblocks some purchase work on Inbox/MyBids. The `isVisible` prop set in objective-c is not totally reliable when switching tabs because, as an implementation detail, we sometimes have more than one tab stack VC mounted at once, even if only one is visible.
So we want to make sure that `isVisible` is true when
1. The view is the topmost view in a nav stack
2. The view is in the stack for the currently-visible tab
To do this a view needs to know three things
1. "Am I the topmost view on a nav stack?" — Already taken care of in `ARComponentViewController` by setting a prop on the root react component: `isVisible`.
2. "Which tab am I a view in?" — Not previously available, now taken care of in `ARScreenPresenterModule` by setting a new prop on the root react component: `navStackID`.
3. …

fix(infra): make isVisible prop respect tab switches.

---

jest.config.js
package.json
yarn.lock

#minor
This PR includes a new dependency - totally up to the repo bosses if we want to merge it or not. It adds [jest-watch-typeahead](https://github.com/jest-community/jest-watch-typeahead) which gives a preview to the `jest --watch` command when typing a file or test name pattern. It's straightforward to use and i have found it convenient in the past.  Again, no pressure to adopt it if we don't want to.

chore: add jest-watch-typeahead (optional)

---

src/lib/Scenes/MyCollection/MyCollection.tsx

This PR resolves [CX-767]
Vertically centres the empty state component, as shown in the image below:
[CX-767]: https://artsyproduct.atlassian.net/browse/CX-767

fix(my collection): centre empty state msg #trivial

---

src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx

The type of this PR is: **Bug**
This PR resolves [CX-914]
Added 4px to height of container box in `DemandRankScale` to match height of purple linear gradient.
[CX-914]: https://artsyproduct.atlassian.net/browse/CX-914

bug: Increase height of DemandRankScale box to match purple linear gradient

---

src/palette/elements/EntityHeader/EntityHeader.tsx

The type of this PR is: **Bug**
This PR resolves [CX-797]
Centered the flexbox that contains the artist name and metadata and only the `meta` div if `meta` is present. This centers the artist name when there is no `meta` present. 
[CX-797]: https://artsyproduct.atlassian.net/browse/CX-797

bug: Center artist name and metadata on artwork page About the artist section

---

src/__generated__/MyCollectionArtworkArtistArticlesTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkArtistArticles_artwork.graphql.ts
src/__generated__/MyCollectionArtworkArtistAuctionResultsTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkArtistAuctionResults_artwork.graphql.ts
src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkQuery.graphql.ts
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistArticles-tests.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistAuctionResults-tests.tsx

This PR resolves [CX-916]
Added artist name to graphQL queries on `MyCollectionArtworkArtistAuctionResults` and `MyCollectionArtworkArtistArticles.tsx` to include artist name. Added dynamic text to include in the headers for the sections. Added check in tests to ensure it is filling in the artist name correctly.
[CX-916]: https://artsyproduct.atlassian.net/browse/CX-916

chore: Add artist name to auctions and articles section in my collection artwork view

---

src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx

This PR resolves [CX-913]
Change empty state auction result image in the MyCollections artwork view to include `<MissingArtworkIcon` in a square instead of a rectangle. I think @samchieng and @admbtlr were discussing reusing the `ArtistInsightsAuctionResult` component, which would require some refactoring of the `auctionResult` being passed and the formatting of the component to fit in this place. For now, keeping this change small :)
[CX-913]: https://artsyproduct.atlassian.net/browse/CX-913

chore: Add missing artwork placeholder in My Collection Artwork page for empty state

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResult.tsx

This PR resolves [CX-792]
New logic is to swap the check of bought in with the past month check. 
[CX-792]: https://artsyproduct.atlassian.net/browse/CX-792

logic(bought-in): change the logic for the string in auction insights results

---

CHANGELOG.yml
docs/analytics_and_tracking.md
docs/preferred_practices.md
src/__generated__/MyCollectionArtworkArtistArticlesTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkArtistArticles_artwork.graphql.ts
src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts
src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkMetaTestsQuery.graphql.ts
src/__generated__/MyCollectionArtworkMeta_artwork.graphql.ts
src/__generated__/MyCollectionArtworkQuery.graphql.ts
src/lib/Scenes/MyCollection/MyCollection.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistArticles-tests.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistAuctionResults-tests.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkMeta.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/__tests__/MyCollectionArtworkMeta-tests.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/__tests__/MyCollectionArtwork-tests.tsx
yarn.lock

The type of this PR is: **Analytics**
This PR resolves [CX-923]
Adds tracking events for taps and screen views in my collection
- adds screen tracking for:  **MyCollection, MyCollectionArtwork** 
- tap tracking for:
- **TappedSell**
- **TappedShowMore for ‘Learn more’**
- **TappedShowMore for ‘See all articles’**
- **TappedShowMore for ‘Explore auction results’**
- **TappedShowMore for ‘View more’**
- updates cohesion to get latest schema
- updates our analytics docs
Tap tracking for:
All these events should be implemented, just keeping a draft until I have addressed follow-ups below.
[CX-923]: https://artsyproduct.atlassian.net/browse/CX-923

chore: my collection analytics part 2 

---

src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkInsights-tests.tsx
src/lib/Scenes/MyCollection/utils/__tests__/pluralizeArtworkMedium-tests.ts
src/lib/Scenes/MyCollection/utils/pluralizeArtworkMedium.ts

This PR resolves [CX-897]
Updated the copy on artwork view page under "Price and market insights" to read "[Size] [medium-plural] by [artist]". 
Pluralizing the medium required mapping the medium to its pluralized version. Would love feedback on how I did that. Feeling like my method was not all that elegant/scalable. 
[CX-897]: https://artsyproduct.atlassian.net/browse/CX-897

chore: Edit order of size, medium (pluralize), and artist copy in market insights in My Collection artwork view

---

fastlane/Fastfile

Don't send a slack notification when App Store connect warns us about dev account expiration date. This notification is meant to be for new license agreements that need to be reviewed.

fix: ignore membership expiration warnings for message notifications #trivial

---

src/lib/navigation/__tests__/routes-tests.tsx
src/lib/navigation/routes.tsx

This PR resolves [CX-925]
- Add support for encoded URIs
PS: Not sure if this is required in case we want the params to be distinguishable (https://artsy.slack.com/archives/C04KVDZU6/p1609168424086400?thread_ts=1608808952.082700&cid=C04KVDZU6)
https://user-images.githubusercontent.com/11945712/103544265-18a2fa00-4ea0-11eb-8c21-ea706223ed9b.mov
[CX-925]: https://artsyproduct.atlassian.net/browse/CX-925

feat: add support for encoded URIs

---

CHANGELOG.yml
src/lib/Scenes/Map/GlobalMap.tsx

This PR resolves [CX-927]
Check for undefined values rather than explicitly null values. A crash was occurring on entering city guide and giving location permission, best guess is the first location update callback was returning an  empty/undefined location object and the location.coords check was then causing a crash accessing an undefined property.
[CX-927]: https://artsyproduct.atlassian.net/browse/CX-927

fix: safer empty location check #trivial

---

CHANGELOG.yml
Podfile.lock
src/lib/Scenes/Home/Components/FairsRail.tsx
src/lib/Scenes/Home/Components/SalesRail.tsx
src/lib/Scenes/Home/Components/__tests__/FairsRail-tests.tsx

This PR resolves [CX-924]
Fix fairs rail empty state in homepage
[CX-924]: https://artsyproduct.atlassian.net/browse/CX-924

fix: fix fairs rail empty state in homepage

---

src/lib/Scenes/Home/Components/FairsRail.tsx

This PR resolves [CX-930]
Looks like there is an alignment issue with the list header prop for horizontal rails. This uses the same logic of the but moves header outside this prop. 
[CX-930]: https://artsyproduct.atlassian.net/browse/CX-930

fix: alignment issue with fairs header #trivial

---

CHANGELOG.yml
patches/@types+react-native+0.63.25.patch
src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
src/__generated__/ArtistHeaderTestsQuery.graphql.ts
src/__generated__/ArtistInsightsTestsQuery.graphql.ts
src/__generated__/ArtistInsights_artist.graphql.ts
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistHeader.tsx
src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsightsAuctionResults-tests.tsx
src/lib/Components/Artist/ArtistShows/ArtistShows.tsx
src/lib/Components/Artist/__tests__/ArtistHeader-tests.tsx
src/lib/Components/ArtworkFilterOptions/SortOptions.tsx
src/lib/Components/FilterModal/FilterModal.tsx
src/lib/Components/FilterModal/__tests__/FilterModal-tests.tsx
src/lib/Components/FilterModal/__tests__/FilterTestHelper.tsx
src/lib/Scenes/Artist/Artist.tsx
src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
src/lib/tests/renderWithWrappers.tsx
src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx
src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
src/setupJest.ts

This PR resolves [CX-843]
**Add filtering to auctionResults**
[CX-843]: https://artsyproduct.atlassian.net/browse/CX-843

feat: add auctionResults filters button and empty screen

---

CHANGELOG.yml
src/__generated__/ArtistAboutShowsTestsQuery.graphql.ts
src/__generated__/ArtistAboutShows_artist.graphql.ts
src/__generated__/ArtistAboutTestsQuery.graphql.ts
src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
src/lib/Components/Artist/ArtistAbout/ArtistAboutShows.tsx

This PR resolves [CX-932]
Previously the heading of the `Shows` section of the `About` tab of the `Artist` screen had the heading `Shows featuring Nicholas Parry`, no matter who the artist was. Also the `See all past shows` button didn't work. Now it does.
[CX-932]: https://artsyproduct.atlassian.net/browse/CX-932

fix(artist): show correct name + link to past shows

---

CHANGELOG.yml
src/lib/Components/Lists/AuctionResult.tsx
src/lib/Components/Lists/__tests__/AuctionResult-tests.tsx
src/lib/Scenes/AuctionResult/AuctionResult.tsx
src/lib/Scenes/AuctionResult/__tests__/AuctionResult-tests.tsx

Collaboration with @The-Beez-Kneez!!!
This PR resolves [CX-943]
The sale date is parsed as a local timestamp, so dates were getting nudged off by 1 (for those of us west of gmt). 
In this PR we convert to UTC before displaying them.
Auction result list: 
(The Andy Warhol "Wine Label" items were previously showing Dec 14)
Auction result detail:
(This was previously showing Dec 14)
[CX-943]: https://artsyproduct.atlassian.net/browse/CX-943

fix: Display correct sale date for auction results

---

CHANGELOG.yml
src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts
src/__generated__/ArtistInsightsTestsQuery.graphql.ts
src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/ArtworkFilterOptions/MultiSelectCheckOption.tsx
src/lib/Components/ArtworkFilterOptions/SizesOptions.tsx
src/lib/Components/ArtworkFilterOptions/__tests__/SizesOptions-tests.tsx
src/lib/Components/FilterModal/FilterModal.tsx
src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx
src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts

This PR resolves [CX-846]
- Add size filtering to Artist Insights Auction Results 
https://user-images.githubusercontent.com/11945712/104589779-acc44c80-566a-11eb-84e0-1d1d2c7fa938.mov
[CX-846]: https://artsyproduct.atlassian.net/browse/CX-846

feat: add size filtering to Artist Insights Auction Results #4327

---

CHANGELOG.yml
package.json
src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts
src/__generated__/ArtistInsightsTestsQuery.graphql.ts
src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/ArtworkFilterOptions/MultiSliderCustomLabel.tsx
src/lib/Components/ArtworkFilterOptions/YearOptions.tsx
src/lib/Components/ArtworkFilterOptions/__tests__/YearOptions-tests.tsx
src/lib/Components/FilterModal/FilterModal.tsx
src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx
src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
yarn.lock

- Add year picker filter to artist insights auction results filtering
https://user-images.githubusercontent.com/11945712/104727940-76540380-5736-11eb-86c5-67b75a1cbfff.mov

feat: Add year picker filter to artist insights auction results filtering

---

CHANGELOG.yml
src/lib/Scenes/AuctionResult/AuctionResult.tsx
src/lib/utils/useStickyScrollHeader.tsx

Makes it easier to use StickyScrollHeader by allowing a simple string value for the header instead of a whole component. `useStickyScrollHeader` will then create the required component. Also, more versatile setting of `fadeInStart` value, with calculated `fadeInEnd`.

feat: improve StickyScrollHeader props

---

Makefile

The `make flip_table` command was failing because node modules need to be installed before calling `yarn prettier`. This PR updates the script.
https://artsy.slack.com/archives/C02BAQ5K7/p1610750140007000

fix: Add yarn install to make flip_table script

---

CHANGELOG.yml
src/lib/Components/AnimatedBottomButton.tsx
src/lib/Components/Artist/ArtistHeader.tsx
src/lib/Components/ArtistListItem.tsx
src/lib/Components/Home/ArtistRails/ArtistCard.tsx
src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
src/lib/Scenes/Artwork/Components/ContextCard.tsx
src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
src/lib/Scenes/Artwork/Components/PartnerCard.tsx
src/lib/Scenes/Consignments/ConsignmentsHome/Components/Footer.tsx
src/lib/Scenes/Consignments/ConsignmentsHome/Components/Header.tsx
src/lib/Scenes/Consignments/Screens/Overview.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx
src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
src/palette/elements/EntityHeader/EntityHeader.tsx

This PR resolves [CX-550]
After the feedback in https://artsyproduct.atlassian.net/browse/CX-550?focusedCommentId=34269:
- made all haptics use the default strength, same as the "save work".
- fixed a small layout bug:
before:
after:
- added haptic on the contact gallery special case
[CX-550]: https://artsyproduct.atlassian.net/browse/CX-550

additions(haptics): make all haptics be the same, the stronger version

---

CHANGELOG.yml
src/__generated__/AndroidAppQuery.graphql.ts
src/lib/AndroidApp.tsx
src/lib/NativeModules/ArtsyNativeModules.tsx
src/lib/NativeModules/GraphQLQueryCache.ts
src/lib/relay/RelayCache.ts
src/lib/relay/__tests__/RelayCache-tests.tsx
src/lib/relay/middlewares/cacheMiddleware.ts
src/lib/store/ConfigModel.ts
src/lib/store/GlobalStore.tsx
src/setupJest.ts

This PR resolves [CX-870]
<em>Note: This was originally supposed to be part of #4346 but I decided to split it into a separate PR.</em>
This PR makes metaphysics work on android, and sets up a new GraphQL cache based on `AsyncStorage` (since our current ios one is in obj-c). We can probably already replace the obj-c one but I'll leave that until after we've migrated the admin menu since there's an option there to clear the cache which I occasionally use at least.
I added a POC query renderer to the main android page to show the user's name
[CX-870]: https://artsyproduct.atlassian.net/browse/CX-870

feat(android): configure metaphysics + relay

---

CHANGELOG.yml
src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts
src/__generated__/ArtistInsightsTestsQuery.graphql.ts
src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsightsAuctionResults-tests.tsx

This PR resolves [CX-967]
- show FilteredArtworkGridZeroState when no results are available
[CX-967]: https://artsyproduct.atlassian.net/browse/CX-967

fix(ArtistInsightsAuctionResults): show FilteredArtworkGridZeroState when no results are available 

---

.circleci/config.yml

This adds a short-circuiting step to the android build task on circle-ci. It stops if nothing which affects the android app build has changed.

chore: Add early success task to android circle job

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx

This PR resolves [CX-972]
- Add extra bottom padding to auction result
- Remove separator from the last auction result
[CX-972]: https://artsyproduct.atlassian.net/browse/CX-972

fix: auction results end QA fixes

---

fastlane/Fastfile
src/lib/ErrorReporting.ts

This PR resolves [CX-956]
Follow-up to https://github.com/artsy/eigen/pull/4368 which correctly uploaded the artifacts to the right release but still weren't getting deobfuscated js code in errors. 
This
- adds a tilde '~' to the source file upload which is a special character in sentry to ignore protocol when matching sources to errors
- calls `setRelease` explicitly to workaround an issue in sentry lib that was not respecting release param in init call
[CX-956]: https://artsyproduct.atlassian.net/browse/CX-956

fix: add '~' to sentry source path #trivial

---

CHANGELOG.yml
src/lib/Containers/Inbox/Inbox.tsx

This PR resolves [PURCHASE-2422]
This PR fixes a layout issue causing the Inbox's pull to refresh functionality to not work as expected.
Also, it adds a line missing from the changelog - as per Erik.
Done with @lilyfromseattle and @erikdstock 
[PURCHASE-2422]: https://artsyproduct.atlassian.net/browse/PURCHASE-2422

bugfix: Fix layout issue preventing Inbox pull to refresh

---

src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx

This PR fixes an issue with Conversations on Inbox that prevented pagination to work correctly, and that blocked the bottom part of the container.
@artsy/purchase-devs

fix: Conversation layout and pagination issues

---

fastlane/Fastfile

Apple has started enforcing 2fa on all accounts in App Store connect, and this broke our beta deploys. This PR uses an App Store connect api key rather than user password login.

fix: use api key for beta deploy #trivial

---

.circleci/config.yml
CHANGELOG.yml
fastlane/Fastfile

Use new app store connect API Key auth for promote beta lane.
Also removes the check developer agreements step from our nightly builds because there is not a corresponding App Store connect api as far as I can tell so will fail when prompted for 2fa.

fix: use api key for fastlane promote beta

---

src/lib/Scenes/AuctionResult/AuctionResult.tsx

The type of this PR is: **UI nudge**
This PR resolves [CX-995].
Uses the `mediumText` variant for the AuctionResult nav title
[CX-995]: https://artsyproduct.atlassian.net/browse/CX-995

chore: use a different text variant for auction result nav title

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistInsights/MarketStats.tsx

This PR partially resolves [CX-738]
Adds a proper loading skeleton for the Market Stats component, in case someone taps quickly to the Insights tab before the insights load. 
Note: the skeleton toggle button in this video was temporarily added for local development. It's not included in the PR. 
https://user-images.githubusercontent.com/1627089/106810300-5f684900-6632-11eb-86c9-64a36a62c561.mp4
[CX-738]: https://artsyproduct.atlassian.net/browse/CX-738

feat: add a loading skeleton for Market Stats

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
src/lib/Components/Artist/ArtistInsights/__tests__/MarketStats-tests.tsx

Note: this PR is currently targeted against the branch from #4394 to maximize signal:noise. We can merge this into that branch first, or change the base on this PR after #4394 is merged.
This PR resolves [CX-1003]
This updates the logic for displaying up/down arrows on the Market Stats module. 
Since the number showing is percentage _over_ median estimate, the icon displayed is: 
[CX-1003]: https://artsyproduct.atlassian.net/browse/CX-1003

fix: show correct arrows on MarketStats sale price over estimate

---

CHANGELOG.yml
android/app/src/main/AndroidManifest.xml
src/lib/AndroidApp.tsx

Quick fix to allow us to navigate to screens without needing to go through the UI, for testing purposes. 
You can open a deep link from the terminal by doing
npx uri-scheme open artsy:///my-profile --android
https://user-images.githubusercontent.com/1242537/106931558-a166bd00-670e-11eb-9544-99e97fe42f30.mp4
I've added a ticket to handle launching the app from deep links to JIRA: https://artsyproduct.atlassian.net/browse/CX-1015

feat(android): set up basic deep link handling

---

src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
src/lib/Components/Artist/ArtistInsights/MarketStats.tsx

This PR resolves [CX-1002]
Moves markets stats + auction results out of Join component and instead adds separator at end of market stats to avoid showing separator when Market Stats is not present.
[CX-1002]: https://artsyproduct.atlassian.net/browse/CX-1002

fix: move separator to market stats module #trivial

---

src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
src/lib/Components/Buttons/InfoButton.tsx
src/lib/Scenes/AuctionResult/AuctionResult.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx

This PR resolves [CX-997]
Moves spacer element outside of info button to allow scrollview content to behave nicely / not be clipped.
[CX-997]: https://artsyproduct.atlassian.net/browse/CX-997

fix: move spacer into modal content #trivial

---

src/lib/Components/Lists/AuctionResult.tsx

This PR resolves [CX-955]
- ~~Lighten the divider color~~
- Reduce the text size on the artwork title and price to “Caption” (Sans 3, or 14px)
- Extending the artwork title to 2 lines if needed and make sure to show the year
[CX-955]: https://artsyproduct.atlassian.net/browse/CX-955

fix: auction result text QA fixes

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistInsights/MarketStats.tsx

This PR resolves [CX-1004]
Corrects the display value of Average Value Sold by converting cents to dollars before formatting. 
[CX-1004]: https://artsyproduct.atlassian.net/browse/CX-1004

fix: convert cents to dollars in MarketStats

---

src/lib/Components/Artist/ArtistInsights/MarketStats.tsx

This PR resolves [CX-1018]
- Remove heritage from the market stats text
[CX-1018]: https://artsyproduct.atlassian.net/browse/CX-1018

fix: remove heritage from the market stats text #trivial

---

fastlane/Fastfile

Use environment vars for issuer id, key id in fast file, these are not sensitive values but is cleaner to have them outside the file.

chore: use env vars in fastfile #trivial

---

src/lib/Components/ArtworkFilterOptions/YearOptions.tsx
src/lib/Components/ArtworkFilterOptions/__tests__/YearOptions-tests.tsx
src/lib/Components/CircleWithBorder/CircleWithBorder.tsx

This PR resolves [CX-999]
**Design adjustment for year created**
- Change hyphen between years to an "en-dash"
- Make toggle switches border radius black instead of grey
- Add haptic feedback on value change for slider ✨ (the only way to test this is on real device)
- Update double divider to single divider (1px) between the slider and the "Include lots without year created info"
- Decrease left-padding to be 20px when the slider is active
https://user-images.githubusercontent.com/11945712/107047596-472a3280-67c8-11eb-98b2-a817ac2f126d.mov
[CX-999]: https://artsyproduct.atlassian.net/browse/CX-999

fix: year created design updates #trivial

---

src/__generated__/PartnerArtworkInfiniteScrollGridQuery.graphql.ts
src/__generated__/PartnerArtworkTestsQuery.graphql.ts
src/__generated__/PartnerArtwork_partner.graphql.ts
src/__generated__/PartnerQuery.graphql.ts
src/__generated__/PartnerRefetchQuery.graphql.ts
src/__generated__/VanityURLEntityQuery.graphql.ts
src/lib/Components/FilterModal/FilterModal.tsx
src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
src/lib/Scenes/Partner/Partner.tsx
src/lib/Scenes/VanityURL/VanityURLEntity.tsx
src/lib/utils/ArtworkFilter/useArtworkFilters.ts

This PR resolves [FX-2557]
[FX-2557]: https://artsyproduct.atlassian.net/browse/FX-2557

feat(fx-2557): adds filter to partner artworks screen

---

src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
src/lib/Components/ArtworkFilterOptions/YearOptions.tsx
src/lib/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
src/lib/Components/AuctionResult/AuctionResultMidEstimate.tsx
src/lib/Components/Lists/AuctionResult.tsx
src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesArtworks-tests.tsx
src/lib/Scenes/AuctionResult/AuctionResult.tsx
src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx
src/lib/Scenes/Fair/__tests__/FairArtworks-tests.tsx
src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts

This PR resolves [CX-947] [CX-1022][CX-1024]
<details>
<summary>Format big mid-estimate percentages!</summary>
</details>
___
<details>
<summary>Reduce the space between the title and the medium+data+auction house</summary>
</details>
___
<details>
<summary>Reduce the space between the title and the medium+data+auction house</summary>
</details>
___
<details>
<summary>make mid estimate size bigger on auction result details</summary>
**After**
**Before**
</details>
___
<details>
<summary>make divider color lighter</summary>
**After**
**Before**
</details>
___
<details>
<summary>Copy updates</summary>
**1. Change “Year created” → “Artwork date” on:**
a. Details Page
b. Filter sheet (menu option in list and title on filter panel when selected)
c. On the …

fix: auction results more QA fixes

---

CHANGELOG.yml
src/__generated__/MarketStatsQuery.graphql.ts
src/lib/Components/Artist/ArtistInsights/MarketStats.tsx

This PR resolves [CX-1050]
This PR resolves [CX-1051]
This PR resolves [CX-1053]
- Multiplies sell-through rate by 100 and displays at most 2 decimal places (doesn't display trailing 0s)
- Updates sort for market stats query to ANNUAL_VALUE_SOLD_CENTS_DESC
- Uses absolute value for sale price over estimate to avoid negative symbol (we already have down arrow)
This is the quick fix but I am going to try to follow-up with moving some of this formatting to metaphysics and serving display values as strings to the app, if anyone wants to pair on that let me know!
[CX-1050]: https://artsyproduct.atlassian.net/browse/CX-1050
[CX-1051]: https://artsyproduct.atlassian.net/browse/CX-1051
[CX-1053]: https://artsyproduct.atlassian.net/browse/CX-1053

fix: markets stats qa fixes

---

src/__generated__/ConversationQuery.graphql.ts
src/__generated__/Conversation_me.graphql.ts
src/lib/Scenes/Inbox/Components/Conversations/Composer.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/Composer-tests.tsx
src/lib/Scenes/Inbox/Screens/Conversation.tsx

This PR resolves [Purchase-2414]
This PR includes `isOfferableFromInquiry` in the artwork query for conversations to conditionally render the Make Offer button.
cc: @artsy/purchase-devs

chore: use isOfferableFromInquiry to conditionally render make offer button

---

.circleci/config.yml
.gitignore
CHANGELOG.yml
scripts/download-fonts
scripts/setup-env-for-artsy

Co-authored-by: Steven Hicks <steven.j.hicks@gmail.com>
This PR resolves [CX-1010]
- Uploaded the fonts to the Eigen s3 bucket and made sure it's only accessible by artsy engineers
- Added script to download fonts and extract them to the assets directory
- Upgraded CI script to download fonts before building the android app
[CX-1010]: https://artsyproduct.atlassian.net/browse/CX-1010

feat: add fonts to android

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAbout-tests.tsx
src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAboutShows-tests.tsx
src/lib/Scenes/Artist/Artist.tsx
src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
src/lib/navigation/routes.tsx
src/lib/store/features.ts

This PR resolves [CX-1066]
- Update artist insights flag
- Set the ready to release to true
[CX-1066]: https://artsyproduct.atlassian.net/browse/CX-1066

chore: update artist insights flag

---

Artsy/View_Controllers/Web_Browsing/ARInternalWebView.h
Artsy/View_Controllers/Web_Browsing/ARInternalWebView.m
Artsy/View_Controllers/Web_Browsing/ARInternalWebViewManager.h
Artsy/View_Controllers/Web_Browsing/ARInternalWebViewManager.m
CHANGELOG.yml
src/lib/Components/ArtsyWebView.tsx
src/lib/Components/InternalWebView.tsx
src/lib/Scenes/Inbox/Screens/Checkout.tsx

Use native webview rather than react-native-webview in order to share auth credentials and prevent users from being prompted to login in checkout flows.
- Adds a prop `showFullScreen` to native webview to allow showing header
- Replaces react-native-webview with our own native webview in Checkout
https://user-images.githubusercontent.com/49686530/108123341-b24ef100-7073-11eb-865c-2c3b69095752.mp4
https://user-images.githubusercontent.com/49686530/108123346-b418b480-7073-11eb-9f62-77f1d3aeaac1.mp4

fix: use native webview for checkout to share auth creds

---

src/lib/Components/Artist/ArtistInsights/MarketStats.tsx

Market Signals view is render the retry view when getting and error and rendering poorly, I think in this case we can just not show the module.

fix: don't render retry view for market stats #trivial

---

fastlane/metadata/en-US/release_notes.txt

Updates release notes ahead of 6.7.8 submission.

chore: release prep 6.7.8

---

Gemfile
Gemfile.lock
HACKS.md
patches/relay-compiler+10.0.1.patch

This fixes the long-standing issue of metro's Fast Reload feature not working properly.
It turns out that relay rewrites all generated files every time you touch _any_ file in `src`, which in turn triggers a cascade of 'file updated' notifications to metro's Fast Reload service. On iOS this sudden influx seems to raise a flag, and instead of doing hundreds of Fast Reload operations it bails out and does one normal full reload. On android it doesn't bail out that way and instead just applies all the Fast Reload operations sequentially, which takes like 20s most of the time.
Anyway we can prevent the whole mess by making it so that relay only rewrites files that have actually changed.

fix fast reload

---

CHANGELOG.yml
src/lib/Scenes/BottomTabs/BottomTabsModel.ts
src/lib/navigation/useReloadedDevNavigationState.ts
src/lib/store/GlobalStore.tsx

Co-authored-by: David Sheldrick <djsheldrick@gmail.com>
This PR resolves an issue we had with the bottoms tabs nav state management after Fast Refresh. 
The videos below show how the app behaves after updating the user name under my profile tab.
**Before**
https://user-images.githubusercontent.com/11945712/108498852-bebe8e00-72ad-11eb-8607-f56e517a6622.mov
**After**
https://user-images.githubusercontent.com/11945712/108498840-bc5c3400-72ad-11eb-80d6-ed0a552c14e2.mov

fix: improve bottom tabs dev state management

---

CHANGELOG.yml
android/app/build.gradle

This PR resolves [CX-1057]
This PR enabled hermes on Android. It all seems to work fine, I used it for a couple of days doing heavy infra work.
After merging devs will need to clean and rebuild the android app:
cd android && ./gradlew clean & cd ../ && yarn android
I'll publicise this in #mobile-practice
[CX-1057]: https://artsyproduct.atlassian.net/browse/CX-1057

chore: enable hermes on android

---

CHANGELOG.yml
android/app/build.gradle

I didn't check thoroughly, it turns out Hermes doesn't support `Intl` yet 😭 but it's being developed now so maybe in a couple of RN releases we'll be able to switch. We could also switch earlier by replacing our current (very limited) `Intl` usage with lightweight npm packages for number/date formatting until Hermes `Intl` support drops. I'll bring that up at Knowledge Share on thursday.

chore: disable hermes, enable JSC with intl

---

scripts/download-fonts

Running `make artsy` was accidentally running the linux CI setup script, so this PR prevents that.
You'll need to reinstall the `aws` cli tool if you fell victim to this. https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html

fix: prevent CI setup script running for devs

---

src/lib/Scenes/SaleInfo/SaleInfo.tsx

This PR resolves [CX-1104]
Use the same timezone that the overview page uses.
[CX-1104]: https://artsyproduct.atlassian.net/browse/CX-1104

fix:use correct time zone for start of bidding on Auction More Info screen

---

CHANGELOG.yml
android/app/src/main/java/net/artsy/app/MainActivity.java
android/app/src/main/res/values/styles.xml
package.json
src/lib/LogIn/LogIn.tsx
src/lib/navigation/BackButton.tsx
src/lib/navigation/NavStack.tsx
yarn.lock

We forgot to make the app full-bleed when setting it up. It's now blocking progress on the new header/back-button work, so here we go 🚀

chore: make android app full-bleed

---

Podfile
Podfile.lock

This PR upgrades us to the latest FB SDK. I paired with @brainbicycle on this and he's helping me by taking the task to (potentially) update our app store privacy report thingy.
https://artsyproduct.atlassian.net/browse/GRO-29

chore: Upgrade Facebook SDK GRO-29

---

src/lib/Scenes/MyBids/Components/WatchedLot.tsx

Follow-up to https://github.com/artsy/metaphysics/pull/3026 which guards against `null` watched lots (which should only ever happen in staging).

feat: [WatchedLot] Guard against null

---

.circleci/config.yml

This check is randomly failing due to puppeteer sign-in problems. I don't want these failures to impact non-cx developers' workflows so I'm going to quickly move this to a cron job where we can monitor it's robustness. Currently running every 2 hours. Gonna self-merge.

chore: move MP freshness check to cron job

---

CHANGELOG.yml
src/lib/store/migration.ts

This fixes a bug we pushed to production that was switching users environments to staging. We should try to ask apple for a hotfix release.
This will force all users in beta and prod into the production env.

fix: env migration issue

---

CHANGELOG.yml
src/lib/utils/__tests__/extractNodes-tests.ts
src/lib/utils/extractNodes.ts

We had some bug reports about favourites disappearing, and we saw that metaphysics was returning `null` as node values for a shows connection, which should not be happening. We'll fix that separately, and try to add some tooling in metaphyiscs to prevent it happening again. But in case it does happen again in the future we can add this extra helper in `extractNodes` to filter out null/undefined.
Slack context: https://artsy.slack.com/archives/C01B2P6LJUU/p1615324641014600

fix: add safety valve in extractNodes

---

CHANGELOG.yml
src/lib/Components/FancyModal/FancyModal.tsx

This PR resolves [CX-1205]
- Fix fancy modal status bar
[CX-1205]: https://artsyproduct.atlassian.net/browse/CX-1205

fix: fancy modal status bar

---

CHANGELOG.yml
src/lib/store/config/features.ts

The type of this PR is: Feature (flag)
This PR addresses: [FX-2719](https://artsyproduct.atlassian.net/browse/FX-2719)
The FX team is adding a feature flag for the new filters that we will be adding to artwork grids.
Follow-up work pre-release: [FX-2720](https://artsyproduct.atlassian.net/browse/FX-2720)
Follow-up work post-release: [FX-2721](https://artsyproduct.atlassian.net/browse/FX-2721)

chore: add a feature flag for the new artwork filters

---

CHANGELOG.yml
src/lib/Components/FancyModal/FancyModalCard.tsx

This PR resolves [CX-1208]
- Fix fancy modal border radius animating on non shrinking backgrounds
Note: This happens also on iOS
**Before**
https://user-images.githubusercontent.com/11945712/110926364-97933380-8324-11eb-80a4-f5078f702fb4.mov
**After**
https://user-images.githubusercontent.com/11945712/110926269-76cade00-8324-11eb-9339-b12b3c7d1266.mov
[CX-1208]: https://artsyproduct.atlassian.net/browse/CX-1208

fix: fancy modal border radius animating on non shrinking backgrounds

---

CHANGELOG.yml
src/lib/Components/ArtworkFilterOptions/MultiSelectOption.tsx

When a user scrolls to the bottom of a long multi-select filter (like the categories filter on an artwork grid) they are not able to keep the bottom 2 options in view long enough to select them before the snap to hide behind the "Apply" button.

fix: allow users to scroll to bottom of multis-elect filters

---

CHANGELOG.yml
src/lib/Components/ArtworkFilterOptions/MultiSelectOption.tsx
src/lib/Components/ArtworkFilterOptions/__tests__/AdditionalGeneIDsOptions-tests.tsx
src/lib/Components/ArtworkFilterOptions/__tests__/ArtistIDsArtworksOptions-tests.tsx

When a user opens the category filters on an artwork grid, they see 4 filter options load before the rest. This PR removes the `initialNumToRender` prop that controls this behavior on a `MultiSelectOption` component because it looks glitchy.

fix: load all filter options at once

---

CHANGELOG.yml
src/lib/Components/ArtworkFilterOptions/TimePeriodMultiOptions.tsx
src/lib/Components/ArtworkFilterOptions/__tests__/TimePeriodMultiOptions-tests.tsx
src/lib/Components/FilterModal/FilterModal.tsx
src/lib/Components/FilterModal/__tests__/FilterModal-tests.tsx
src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx
src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
src/lib/utils/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx

This PR resolves [FX-2624]
This PR is the work of @dzucconi, @dblandin, and @anandaroop 
- Allows multiple selection of time period (a.k.a. major period) filters on artwork grids.
</details>
</details>
[FX-2624]: https://artsyproduct.atlassian.net/browse/FX-2624

feat: multi-selection time period filters

---

Artsy/App/ARAppDelegate+Emission.m
Artsy/Networking/API_Modules/ARUserManager.h
Artsy/Networking/API_Modules/ARUserManager.m
CHANGELOG.yml
emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
src/lib/NativeModules/LegacyNativeModules.tsx
src/lib/relay/middlewares/checkAuthenticationMiddleware.ts
src/lib/store/GlobalStoreModel.ts

Co-authored-by: Mounir Dhahri <mounir.dhahri@ensi-uma.tn>
This PR resolves [CX-1222]
This fixes a race condition where, upon sign out, the onboarding flow was being shown before the user data was being cleared.
[CX-1222]: https://artsyproduct.atlassian.net/browse/CX-1222

fix(signout): await clearUserData

---

CHANGELOG.yml
android/app/src/main/res/values/styles.xml

This PR resolves [CX-1201]
- Set system navigation bar color to white on modals for android
[CX-1201]: https://artsyproduct.atlassian.net/browse/CX-1201

fix: set system navigation bar color to white on modals for android

---

Artsy/Constants/ARDefaults.m
CHANGELOG.yml

This PR resolves [CX-1223]
We are overly aggressively clearing out all user defaults on logout, including launchCount. This is causing the first install analytics event to be fired more than once per device install. This PR saves the value and rewrites it to defaults on logout. This has been broken for a while we were just made aware of it recently due to the staging issue causing many logouts.
[CX-1223]: https://artsyproduct.atlassian.net/browse/CX-1223

fix: don't clear launch count on logout

---

Artsy/App/ARScreenPresenterModule.m
CHANGELOG.yml
package.json
src/lib/AppRegistry.tsx
src/lib/Components/ArtsyReactWebView.tsx
src/lib/Components/ArtsyWebView.tsx
src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
src/lib/Scenes/VanityURL/VanityURLPossibleRedirect.tsx
src/lib/navigation/ModalStack.tsx
src/lib/navigation/__tests__/routes-tests.tsx
src/lib/navigation/routes.tsx
src/lib/store/GlobalStore.tsx
src/lib/store/config/features.ts
yarn.lock

This PR contributes towards [CX-436]
This PR
- adds a ReactWebView app module to use behind a feature flag while we transition to react-native-webview
- turns on the feature flag by default on Android.
- adds tooling in `routes.tsx` for making it easier to define web view routes
- gives Android a user agent that will let force know it's receiving requests from eigen.
- adds a `isPresentedModally` prop for screen components to receive.
Follow-up PRs will add support for navigation request interception, authentication, and so on.
https://user-images.githubusercontent.com/1242537/111620184-4977a780-87de-11eb-8a3f-f78f7315a512.mp4
https://user-images.githubusercontent.com/1242537/111620211-51cfe280-87de-11eb-808c-03b4914abae9.mp4
https://user-images.githubusercontent.com/1242537/111621757-454c …

feature: add react web view module

---

.circleci/config.yml

This job is creating a lot of failure emails and we have had complaints. I'm going to switch it off for now. We should fix the stability issues and re-enable later.

chore: disable metaphysics-check job

---

CHANGELOG.yml
Podfile.lock
package.json
src/lib/AndroidApp.tsx
src/lib/AppRegistry.tsx
src/lib/Components/ArtsyReactWebView.tsx
src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
src/lib/store/GlobalStoreModel.ts
src/lib/store/__tests__/GlobalStoreModel-tests.ts
src/setupJest.ts
yarn.lock

This PR contributes towards [CX-436]
This PR adds user authentication for `react-native-webview` web views.
It does that by setting up shared cookies between `fetch` and `webkit` by making `HEAD` `fetch`  requests to force and prediction, including the user's access token in the `x-access-token` header. It does this whenever the access token changes, and we also clear the app's cookies when the user logs out.
https://user-images.githubusercontent.com/1242537/112020112-ff692b80-8b27-11eb-8ab1-499b75374ff4.mp4
https://user-images.githubusercontent.com/1242537/112020157-03954900-8b28-11eb-9ea4-5ee5c1cf768a.mp4
[CX-436]: https://artsyproduct.atlassian.net/browse/CX-436

feat: react web view cookies

---

CHANGELOG.yml
scripts/download-fonts
src/lib/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx

The type of this PR is: **UI fix**
Quick fix for the conversation messages count (mostly for iPad).
Before
After

fix(UI): quick fix in the Inquiries UI

---

CHANGELOG.yml
src/lib/Components/ArtsyReactWebView.tsx
src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
src/lib/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/InquiryMakeOfferButton-tests.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx
src/lib/Scenes/Inbox/Screens/Checkout.tsx
src/lib/navigation/routes.tsx

This PR contributes towards [CX-436]
This PR adds support for handling web view navigation events properly.
The semantics are as follows:
- if we can navigate to a native version of the view, we push it on to the nav stack.
- if the url is external (non-artsy) we open the link with `Linking.openURL`
- if the link points to a page that the app would normally render in a web view anyway, we use the normal web view navigation history.
We also add the ability for the back button to trigger web view back actions (by calling `goBack` on the web view ref), along with a prop to be able to turn that ability off (for flows like BNMO where you want only a 'cancel/close' button).
It also pre-evaluates google ads links to avoid the indirection, because otherwise if the link points back to artsy it …

feat: react web view navigation

---

src/lib/Scenes/SaleInfo/SaleInfo.tsx

This PR resolves [CX-1239]
Added a rounding function similar to the one in [Force](https://github.com/artsy/force/pull/2248/files#diff-b7eb4d941f9c0f248da97443ea83094b82fd13992ac463479766d91f4d74f410R6).
[CX-1239]: https://artsyproduct.atlassian.net/browse/CX-1239

fix:round buyer's premium correctly on SaleInfo screen

---

CHANGELOG.yml
src/lib/Components/ModalHeader.tsx
src/lib/utils/__tests__/hardware-tests.ts
src/lib/utils/__tests__/platformUtil-tests.ts
src/lib/utils/hardware.ts
src/lib/utils/platformUtil.ts
src/lib/utils/requestPhotos.ts

This PR resolves [CX-1268]
Our os version check in the consignments flow was faulty and trying to coerce a version string "14.4.1" into a number which resulted in NaN. This uses an osMajorVersion util instead that parse the version correctly, also moved this to platfromUtil file because it feels like it fits there a bit better.
[CX-1268]: https://artsyproduct.atlassian.net/browse/CX-1268

fix: fix os version check in modal header

---

CHANGELOG.yml
android/app/build.gradle
android/app/src/main/AndroidManifest.xml

This PR resolves [CX-1154]
Follow-up to https://github.com/artsy/eigen/pull/4535 which worked for selecting from library but missed some necessary permissions for using camera on Android.
Adds some camera permissions to the android manifest as per setup instructions here:
https://github.com/ivpusic/react-native-image-crop-picker#android
https://user-images.githubusercontent.com/49686530/112543874-b9f96800-8d8c-11eb-81a1-efb8db35f350.mp4
[CX-1154]: https://artsyproduct.atlassian.net/browse/CX-1154

fix: add camera permissions setup for android

---

CHANGELOG.yml
package.json
src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
src/lib/Components/Artist/ArtistInsights/__tests__/MarketStats-tests.tsx
src/lib/Scenes/AuctionResult/AuctionResult.tsx
yarn.lock

- Use `artistAuctionResults` instead of `artistInsights` for artist insights `contextScreenOwnerType`
Related cohesion changes PR: https://github.com/artsy/cohesion/pull/175

fix: use artistAuctionResults instead of artistInsights for contextScreenOwnerType

---

scripts/setup-distribute-linux

Sentry cli installation fails with exit code 1 if already present, this checks first if the command is present and doesn't install if it is.

fix: conditional installation of sentry-cli to avoid non-zero exit #trivial

---

src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx

This PR resolves [CX-1189]
We have a custom UIScrollView extension on iOS that forwards scroll events to nested scroll views. This allows the `InifiniteScrollArtworksGrid` component to load more elements even though the user never actually causes the inner scroll view to scroll (i.e. the `contentInset` on the  `InifiniteScrollArtworksGrid`'s `ScrollView` component will always have y-offset 0, while the parent scroll view will be the one actually scrolling. And the parent scroll view is usually the main scroll view for whichever screen you're looking at)
Unfortunately we don't, and probably can't, and definitely shouldn't, have the same thing on Android. 
The 'right' solution IMO would be to refactor the infinite scroll artworks thing into a hook which returns elements that a flat list can …

fix: use 'show more' button on all artwork grids on android

---

src/lib/Scenes/Inbox/Components/Conversations/Composer.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/Composer-tests.tsx
src/lib/Scenes/Inbox/Screens/Conversation.tsx
src/lib/Scenes/Inbox/Screens/__tests__/Conversation-tests.tsx

I addressed several tickets in this PR, all related to the keyboard and semi-dependent on each other. I also added tap to close functionality to the keyboard - if there is an existing ticket for this please let me know
https://user-images.githubusercontent.com/5643895/113346241-96409f80-9301-11eb-8be7-5aec026dbc38.mov
. Shoutout to @ashleyjelks for test help!
Within initial inquiry view, keyboard is expanded (showing) by default
https://www.notion.so/artsy/Within-initial-inquiry-view-keyboard-is-expanded-showing-by-default-499d5576f5dc4f01aa794f0f0ce31d85
When the keyboard is active can the make offer button hide? And when the keyboard is hidden the button is back.
https://www.notion.so/artsy/When-the-keyboard-is-active-can-the-make-offer-button-hide-And-when-the-keyboard-is-hidden-the-but …

Keyboard fixes

---

CHANGELOG.yml
src/lib/Scenes/Inbox/Components/Conversations/Messages.tsx

This PR resolves [PURCHASE-2535]
We noticed in some cases the messages (including order events) would be displayed in the wrong order. It turns out we were only inverting the `FlatList` when the content is taller than the scroll view, and in cases the content is shorter, the messages were displayed in the wrong order.
This fixes it by always inverting the `FlatList` and uses flexbox `justifyContent` to align content to the top when the content is shorter than the scroll view. More details inline.
**Before**
**After**
[PURCHASE-2535]: https://artsyproduct.atlassian.net/browse/PURCHASE-2535

fix: fix incorrect message order when content is shorter than the scroll view (PURCHASE-2535)

---

emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
src/lib/NativeModules/LegacyNativeModules.tsx
src/lib/Scenes/About/About.tsx
src/setupJest.ts

Use app version for version display in about menu on Android and remove the native module that only supported iOS.

fix: use appJson for version remove legacy module #trivial

---

src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx

Make Offer (Initial View) - Title "Make Offer with Artsy Pay" is missing / Cancel link is in nav and should be ONLY the CTA (below "Confirm')
__Before:__
__After:__

Add missing overlay page title to MO modal and remove cancel button in modal header

---

CHANGELOG.yml
src/lib/Scenes/Inbox/Components/Conversations/Messages.tsx
src/lib/Scenes/Inbox/Screens/Conversation.tsx
src/lib/Scenes/Inbox/Screens/__tests__/Conversation-tests.tsx

This PR resolves [PURCHASE-2516]
We noticed the keyboard fix in https://github.com/artsy/eigen/pull/4592 caused the conversation screen to be not scrollable. This reverts the introduction of `TouchableWithoutFeedback` and, instead, uses `keyboardShouldPersistTaps` to dismiss the keyboard.
[PURCHASE-2516]: https://artsyproduct.atlassian.net/browse/PURCHASE-2516

fix: fix conversation scrolling after the keyboard fix (PURCHASE-2516)

---

docs/preferred_practices.md

The type of this PR is: Documentation
This PR fixes a broken link to the analytics docs in `preferred_practices.md`

fix: update broken analytics link in preferred_practices.md

---

src/__generated__/MakeOfferModalQuery.graphql.ts
src/__generated__/MakeOfferModalTestsQuery.graphql.ts
src/__generated__/MakeOfferModal_artwork.graphql.ts
src/lib/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
src/lib/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/MakeOfferModal-tests.tsx

This PR resolves [PURCHASE-2373]
User is now able to confirm edition set during inquiry checkout
@artsy/purchase-devs 
[PURCHASE-2373]: https://artsyproduct.atlassian.net/browse/PURCHASE-2373

feat: Add edition select for inquiry checkout

---

src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx

This PR resolves [PURCHASE-2517]
**Issue:**
The screen track event was firing twice for `<MakeOfferModal>`. Once when you navigate to the view/modal and once when navigating away from the view. The second fire was not an expected behavior. 
The  `<MakeOfferModal>` was getting re-rendered. We aren't sure why this is happening but I scheduled more time with the mobile practice team to dig into this a bit more. 
**Fix:**
In the mean time we've moved the `<ProvideScreenTrackingWithCohesionSchema>`  component to wrap the QueryRenderer and this prevents the event from firing more than once.
[PURCHASE-2517]: https://artsyproduct.atlassian.net/browse/PURCHASE-2517

fix: prevent MakeOfferModal screen tracking from double firing

---

CHANGELOG.yml
src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts

This PR resolves [FX-2740]
Renames the Category filter on artwork grids to Medium.
[FX-2740]: https://artsyproduct.atlassian.net/browse/FX-2740

chore: rename the category filter to medium

---

CHANGELOG.yml
src/lib/Scenes/MyProfile/MyProfile.tsx
src/lib/Scenes/MyProfile/__tests__/MyProfile-tests.tsx

This PR resolves [CX-1273]
Since we are not supporting push notifications for Android v1 we should hide this section of the profile menu. 
| --- | ---|
|![image](https://user-images.githubusercontent.com/4691889/114021770-59305c00-9871-11eb-8032-965520f16164.png)|![image](https://user-images.githubusercontent.com/4691889/114021935-8a109100-9871-11eb-87f5-af0377d9c844.png)|
[CX-1273]: https://artsyproduct.atlassian.net/browse/CX-1273

fix: hide push notifications section in android

---

src/lib/Components/Toast/__tests__/Toast-tests.tsx

We are seeing intermittent test failures in Toast component.
Worked on in knowledge share with @artsy/collector-experience it looks like the problem is not with the Toast component but with some recent changes to the Button component here: https://github.com/artsy/eigen/pull/4591, 
Only theory which is kind of vague right now is the loading style now being passed is causing button component to animate which is causing the timer recursion issue but beyond that I am still unclear exactly what is going on. I didn't want to sink too much time into investigation so I just used a different component in this test.

fix: fix toast test, don't use button

---

src/lib/Scenes/Inbox/Screens/Conversation.tsx

This commit should have been included in https://github.com/artsy/eigen/pull/4612.
This PR resolves [PURCHASE-2558]
I did a visual QA of the inquiry checkout header with @ArvindLall and we opted to add these small tweaks to the header text to center it on the screen. The back button creates a bit of asymmetry that we are fixing here.
*The border has been removed, its there to use with Photoshop for centering properly.*

chore: adds 10px of space to center inq chk header text

---

CHANGELOG.yml
package.json

This PR resolves [CX-1308]
Removes last step in our bundle script that removes node_module assets from the Pod assets directory which was causing these icons not to be found when using bundled emission in release builds. I am not clear why we were doing this in the first place, I found [this fairly ancient commit](https://github.com/artsy/eigen/commit/0e670329c82b89902dafbc7289d5347f7dbc27bb) that first added it but not totally clear on the problem it solved. The node module assets directory is pretty small and as far as I can tell these assets aren't being copied anywhere else.
[CX-1308]: https://artsyproduct.atlassian.net/browse/CX-1308

fix: don't remove node_module assets when bundling

---

CHANGELOG.yml
src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarouselEmbedded-tests.tsx

This PR resolves [CX-1275]
Tapping an artwork to view it in deep-zoom fails on Android (see linked JIRA ticket). This PR suppresses deep-zoom taps on Android so that the user doesn't see an error. 
https://user-images.githubusercontent.com/1627089/114219025-c6a2c200-992f-11eb-9eb2-d3664b603048.mp4
[CX-1275]: https://artsyproduct.atlassian.net/browse/CX-1275

fix: suppress deepZoom taps on Android

---

CHANGELOG.yml
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/net/artsy/app/ArtsyNativeModule.java
src/lib/AppRegistry.tsx
src/lib/Components/ArtsyKeyboardAvoidingView.tsx
src/lib/Components/ArtsyReactWebView.tsx
src/lib/Components/Bidding/Screens/BillingAddress.tsx
src/lib/Components/Bidding/Screens/CreditCardForm.tsx
src/lib/Components/Bidding/Screens/Registration.tsx
src/lib/Components/Buttons/BottomAlignedButtonWrapper.tsx
src/lib/Components/FancyModal/FancyModal.tsx
src/lib/NativeModules/ArtsyNativeModule.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
src/lib/Scenes/Consignments/Components/BottomAlignedButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/Composer.tsx
src/lib/Scenes/Inbox/Screens/Checkout.tsx
src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
src/lib/Scenes/Onboarding/OldLogIn/LogIn.tsx
src/lib/Scenes/Onboarding/Onboarding.tsx
src/lib/Scenes/Search/Search.tsx
src/lib/navigation/NavStack.tsx

This PR resolves [CX-1280] [CX-1295] [CX-1281]
This PR takes care of our keyboard avoidance woes by
- Replacing `android:windowSoftInputMode="adjustPan"` with `android:windowSoftInputMode="adjustResize"` in AndroidManifest.xml
This was our main problem on Android. `"adjustPan"` causes the main activity to scroll away when the keyboard opens, which is not how any of our keyboard avoidance interactions should work.
- Creating a two-mode version of `KeyboardAvoidingView` which handles iOS 13+ modals and requires less babysitting.
The react-native built-in `KeyboardAvoidingView` calculates the keyboard displacement based on the assumption that the top of the view is at the top of the screen. To account for situations where this is not true it provides the `keyboardVerticalOffset` prop. …

fix: keyboard avoiding

---

src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx

CTA should link to {orderID}/payment/new only in case of failed payment. Also changed modal header title in this case to be "Retry Payment" as per this discussion https://artsy.slack.com/archives/C9YNS4X32/p1618337020223300

Link CTA to failed payment page

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsights-tests.tsx
src/lib/Components/StickyTabPage/StickyTabPage.tsx
src/lib/Scenes/Artist/Artist.tsx

This PR resolves [CX-1327]
When opening the Artist Insights Tab we track the following event: 
```
[Event tracked] {
"context_screen": "artistAuctionResults",
"context_screen_owner_type": "artistAuctionResults",
"context_screen_owner_slug": "hunt-slonem",
"context_screen_owner_id": "506b34214466170002001a46"
}
```
[CX-1274]: https://artsyproduct.atlassian.net/browse/CX-1274
[CX-1327]: https://artsyproduct.atlassian.net/browse/CX-1327

feature: track artist insights screen views

---

CHANGELOG.yml
src/lib/Components/FancyModal/FancyModal.tsx

This PR resolves [CX-1192]
This PR makes the android back button dismiss fancy modals.
https://user-images.githubusercontent.com/1242537/115209519-96a8ab00-a0f5-11eb-8084-da140e8fdb46.mp4
[CX-1192]: https://artsyproduct.atlassian.net/browse/CX-1192

fix: android back button in fancy modals

---

src/lib/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/ConversationCTA-tests.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx

This PR addresses some small tweaks to the CTA copy and modal headers that Arvind requested, as well as a small alignment adjustments to the order update icon
- Icon next to copy in Inline message needs to be bumped up by a pixel. Not fully aligned
- Update modal header titles
- Update modal copy
- Handle countdowns under 1 hr (currently `hr` is hardcoded)
_Icon after adjustments:_
_CTA with expiration in minutes:_
having uploading issues...DM me for screenshot

CTA/Order Update Tweaks

---

src/__generated__/ArtistAboutTestsQuery.graphql.ts
src/__generated__/ArtistAbout_artist.graphql.ts
src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAbout-tests.tsx

This PR resolves [CX-1331]
- Remove Auction Results link on Artist overview page
[CX-1331]: https://artsyproduct.atlassian.net/browse/CX-1331

fix: remove Auction Results link on Artist overview page (CX-1331)

---

CHANGELOG.yml
src/lib/Components/Spinner.tsx

This PR resolves [CX-1126]
- fix RenderWithPlaceholder on android
https://user-images.githubusercontent.com/11945712/115547206-50467e00-a2a6-11eb-82f7-dd3ce9eaa284.mov
[CX-1126]: https://artsyproduct.atlassian.net/browse/CX-1126

fix(CX-1126): renderWithPlaceholder on android

---

CHANGELOG.yml
android/app/src/main/AndroidManifest.xml
src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx

This PR resolves [CX-1276]
Fixes sharing on Android, we had 2 issues. 1 sharing was very slow because we were fetching a large image, 2 we were passing a non-base64 encoded url to urls array which was causing the base64 string to be shared instead of the image. 
- Fixes a small image instead
- Moves details url out of urls array and adds it to end of share message
https://user-images.githubusercontent.com/49686530/115553878-e5804d00-a27b-11eb-8c86-eb96f58136ac.mp4
[CX-1276]: https://artsyproduct.atlassian.net/browse/CX-1276

fix: fix android share

---

CHANGELOG.yml
src/lib/AppRegistry.tsx
src/lib/Components/ArtsyKeyboardAvoidingView.tsx
src/lib/Components/FancyModal/FancyModal.tsx
src/lib/navigation/NavStack.tsx

This is a follow-up to #4619
This fixes an issue where iOS 13+ pageSheet modals had too much bottom padding added when the keyboard is visible
No idea how I missed this before, I even posted a screenshot that showed this same screen working as expected in the original PR. 🤷🏼
Anyway this change makes perfect sense to me so I'm also confused how it was ever working for that screenshot. Maybe I had some weird simulator state.
I checked this on iOS 12 and android and everything there is still 👍🏼

fix: keyboard avoidance for iOS13 modals

---

CHANGELOG.yml
src/lib/Components/Bidding/Components/Input.tsx
src/lib/Components/FancyModal/FancyModalHeader.tsx
src/lib/Components/Input/Input.tsx

This PR resolves [CX-1187]
Fixed these during Android Bug Bash, together with @ds300, @MounirDhahri, @brainbicycle, @thomasmeerschwam.
- Header not breaking:
And InputText on "New card" and "Billing Address" screens don't scroll anymore like the ticket video.
[CX-1187]: https://artsyproduct.atlassian.net/browse/CX-1187

bugfix(styling): Input scrolling and title header spacing

---

src/lib/Scenes/Onboarding/Onboarding.tsx

The type of this PR is: Fix
This PR adds the missing `bottomOffset` value for the onboarding `ArtsyKeyboardAvoidingViewContext.Provider`.
Tests are failing after this PR got merged:
PR: https://github.com/artsy/eigen/pull/4647/files#diff-d9a1e624b572abd4693c1db5ec9a3d39412a622f2df268778919dfa5d1aaa515R34
Failing Build: https://app.circleci.com/pipelines/github/artsy/eigen/11253/workflows/4e00ce0f-a903-43f8-b381-78d661eedc16/jobs/32062

fix: Add missing keyboard provider offset

---

CHANGELOG.yml
src/__generated__/ArtistAboutTestsQuery.graphql.ts
src/__generated__/ArtistAbout_artist.graphql.ts
src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx

This PR resolves [CX-1351]
- Add missing query param to articles connection
[CX-1351]: https://artsyproduct.atlassian.net/browse/CX-1351

fix (CX-1351): add missing query param to articles connection

---

src/lib/Components/ArtworkFilter/Filters/__tests__/TimePeriodOptions-tests.tsx

This PR resolves [FX-2867]
Removes the `ARUseImprovedArtworkFilters` feature flag from time period filter tests that were missed in #4645 
[FX-2867]: https://artsyproduct.atlassian.net/browse/FX-2867

fix: remove feature flag from time period filter tests

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx

This PR resolves [FX-2716]
We were previously using `artist.id` which is a "globalID" for Relay. This PR switches it to using our `internalID` which corresponds with Gravity IDs.
[FX-2716]: https://artsyproduct.atlassian.net/browse/FX-2716

fix(analytics): uses internalID

---

CHANGELOG.yml
Podfile.lock
src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/AdditionalGeneIDsOptions-tests.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/AggregationOptionCommonValidation.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/ArtistIDsArtworksOptions-tests.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/AttributionClassOptions-tests.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/PriceRangeOptions-tests.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/SortOptions-tests.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/TimePeriodOptions-tests.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/WaysToBuyOptions-tests.tsx
src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx
src/lib/Components/TouchableRow.tsx

This PR resolves [FX-2871]
This PR removes style changes to the artwork filter modal. (For Artsy engineers, the design specs can be found [here](https://www.figma.com/file/zG9cduJdOaTQAw886QcOwn/Filters?node-id=1376%3A15695).)
- The "Apply (N)" button now simply shows "Show results"
- The separator lines between rows have been removed
- Rows are highlighted when a user taps on them
- Default values "All" and "Default" are no longer shown
- Multi-select filters have changed from toggle switches to checkboxes
- Single-select filters have changed from check marks to radio buttons
[FX-2871]: https://artsyproduct.atlassian.net/browse/FX-2871

feat: release improved artwork filter style

---

src/lib/Components/Bidding/Screens/BidResult.tsx
src/lib/Components/Bidding/Screens/RegistrationResult.tsx

This PR resolves [CX-1191] [CX-1190]
Fixed this with @ds300 and @brainbicycle during bugbash.
When we show a "confirmation" screen, like bid success or registration success, then the android hw back button should take us all the way back, by just dismissing the modal.
[CX-1191]: https://artsyproduct.atlassian.net/browse/CX-1191
[CX-1190]: https://artsyproduct.atlassian.net/browse/CX-1190

fix(nav flow): hardware back button is closing modals when needed

---

CHANGELOG.yml
src/palette/elements/Button/Button.tsx

This PR resolves [CX-1356]
On iOS, the palette button disabled state looks broke. This was happening because of dropping the text opacity too much (0.1). This PR reverts those changes and removes the opacity same as it was before. 
- [xo] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.
[CX-1356]: https://artsyproduct.atlassian.net/browse/CX-1356

fix(CX-1356): Palette button disabled state on iOS

---

src/lib/utils/__tests__/saleTime-tests.ts
src/lib/utils/saleTime.ts

cc: @DagmarK @artsy/purchase-devs 
This PR resolves [Purchase-2427]
Old functionality: When the time to the start of an auction is less then an hour the view would display "starts in 0 hours". 
Updated functionality: The view will display the remaining minutes. The code will switch to display minutes and not hours when (now - live_start_at < 60 min).

feat: show minutes if less than one hour remaining until sale start

---

CHANGELOG.yml
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/palette/elements/Button/Button.tsx

This PR resolves [CX-1358]
- Fix auction results filter modal title
___
- Fix palette button loading state
**Before**
https://user-images.githubusercontent.com/11945712/116124643-d73f9000-a6c4-11eb-9887-20299a391bf6.mov
**After**
https://user-images.githubusercontent.com/11945712/116124634-d4dd3600-a6c4-11eb-88f1-665bcae53014.mov
[CX-1358]: https://artsyproduct.atlassian.net/browse/CX-1358

Fix bugs caught on QA

---

src/lib/Scenes/Inbox/Components/Conversations/Messages.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/Messages-tests.tsx

_From the Jira ticket:_
Failed payment displayed as "offer accepted" in inline order history
When testing a failed payment scenario, failed transaction got displayed as “Offer Accepted” in the inline history. See the screenshot below for an example: I submitted the offer with a test card that’ll fail when capturing. I accepted partner’s counteroffer 2 times (both were failed) and they were displayed as accepted in the history.
------
In this PR I am filtering out `APPROVED` state change updates when they are followed by `SUBMITTED` updates because they only occur in this order when payment fails (order goes to approved state then is reverted to submitted state when payment fails). While this solution may not be ideal, it solves the problem, and after discussing with team members I …

Failed payment notification

---

src/lib/Scenes/Inbox/Screens/Conversation.tsx
src/lib/Scenes/Inbox/Screens/__tests__/Conversation-tests.tsx
src/lib/navigation/navigate.ts
src/setupJest.ts

Team effort with @xtina-starr @jo-rs @lilyfromseattle @ds300 
This PR resolves [PURCHASE-2574]
After submitting an offer and closing the modal, the user lands back in the conversation chat with the make offer button still visible. This provides a confusing UX experience. This PR adds a new event emitters to listen for the modal dismiss event and refreshes the conversation view to the up-to-date state.
[PURCHASE-2574]: https://artsyproduct.atlassian.net/browse/PURCHASE-2574

feat: listen for modal close events to refresh conversation

---

CHANGELOG.yml
src/lib/Components/ArtworkFilter/Filters/GalleriesAndInstitutionsOptions.tsx
src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/MultiSelectOption-tests.tsx

This PR resolves [FX-2713]
https://user-images.githubusercontent.com/112297/116305936-72427380-a772-11eb-9140-72af8b93cb16.mov
[FX-2713]: https://artsyproduct.atlassian.net/browse/FX-2713

feat(fx-2713): allows multi-select filters to be searchable

---

CHANGELOG.yml
Podfile.lock
src/__generated__/ArtistAboutTestsQuery.graphql.ts
src/__generated__/ArtistAbout_artist.graphql.ts
src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
src/__generated__/ArtistArtworksQuery.graphql.ts
src/__generated__/ArtistArtworks_artist.graphql.ts
src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tsx
src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
src/lib/Components/GenericArtistSeriesRail.tsx
src/lib/Scenes/Artist/Artist.tsx

- The type of this PR is: Refactor
- This PR resolves [FX-2904]
This PR changes the title of the artist "About" tab to "Overview" and moves the rails from the "Artworks" tab to "Overview".  These rails include the _Artist Series_, _Notable Works_, and _Iconic Collections_ rails. This is done in preparation of removing the "Sort & Filter" pill and moving it to the sticky header to increase usage of filters.
These rails can now be found below the _Biography_ section and above the consignments call-to-action in the same order.
[FX-2904]: https://artsyproduct.atlassian.net/browse/FX-2904

refactor: move rails on artist artwork tab to overview (about) tab

---

src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
src/lib/Scenes/Onboarding/OnboardingLogin.tsx

This PR resolves [CX-1368]
In order to hide the text when the button is disabled, we need to remove the `color` prop from the `Text` inside of the `Button`. Instead we can use `variant="primaryBlack"`.
| Login (new button (top), old button(bottom))| Create Account (new button) |
|---|---|
|![login-button](https://user-images.githubusercontent.com/4691889/116985358-a23acb00-accc-11eb-80c1-e3ba8ba5bcea.gif)|![image](https://user-images.githubusercontent.com/4691889/116986235-d06cda80-accd-11eb-8a9c-a13eabb24305.png)
|
[CX-1368]: https://artsyproduct.atlassian.net/browse/CX-1368

fix: Stop showing text on loading login button

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/lib/Scenes/Fair/Components/FairArtworks.tsx
src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
src/lib/Scenes/Show/Components/ShowArtworks.tsx

This PR resolves [CX-1365]
This PR adds a spinner and padding to the partner artworks page similar to the artist artworks page (https://github.com/artsy/eigen/blob/master/src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx#L168).
The change fixes the missing space below the "Show More" button and makes the visual experience consistent with the artist artworks page. 
|---|---|
| | |
| ![image](https://user-images.githubusercontent.com/4691889/117011052-bcd16c00-aced-11eb-9e44-684ced47598f.png) |![image](https://user-images.githubusercontent.com/4691889/117011717-66186200-acee-11eb-955b-bf1094ae3c34.png)|
iOS: https://user-images.githubusercontent.com/4691889/117011263-f1ddbe80-aced-11eb-9209-fc520b75c019.mp4
**Affected screens:**
- I …

fix: add spinner and padding to infinite scroll artworks grid

---

src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx

- The type of this PR is: Fix
I was not able to tap the X to close the filter modal screen or the "Clear all" button to clear selections. This was caused by the "Sort & Filter" title covering both of those elements after their `position` was set to `"absolute"`.

fix: make filter modal close and clear all tappable again

---

CHANGELOG.yml
src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
src/lib/Scenes/Onboarding/OnboardingLogin.tsx

- Fix screen transition not fading when transitioning from Sign up to login
- Clear timeout when the user immediately navigates back to the welcome screen after they navigate to the login screen

fix: screen transition not fading when transitioning from sign up to login

---

CHANGELOG.yml
Podfile.lock
src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
src/__generated__/ArtistArtworksQuery.graphql.ts
src/__generated__/ArtistArtworks_artist.graphql.ts
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx

- The type of this PR is: Refactor
- This PR resolves [FX-2880]
This PR adds a header component to the artist artworks grid that will contain the total number of works in the grid and a button to allow users to sort and filter the grid. The purpose of this change is to make the sort and filter action more prominent and encourage users to find art that they love.
[FX-2880]: https://artsyproduct.atlassian.net/browse/FX-2880

refactor: move artist artworks sort & filter button into header

---

Artsy/App/ARModalViewController.m
CHANGELOG.yml
emission/Pod/Classes/EigenCommunications/ARNotificationsManager.h
emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m
src/lib/Scenes/Inbox/Screens/Conversation.tsx
src/lib/Scenes/Inbox/Screens/__tests__/Conversation-tests.tsx
src/lib/navigation/navigate.ts
src/lib/store/NativeModel.ts

paired with: @lilyfromseattle @ds300
The type of this PR is: **FEAT**
This PR resolves [PURCHASE-2574]
This is follow up to https://github.com/artsy/eigen/pull/4648 and adds a new native modal dismissed event and uses that in the conversation to determine when we need to refetch conversation data. Previously we were hooking into the local modalDismissed and goBack events in eigen. With this implementation those are no longer needed.
https://user-images.githubusercontent.com/5201004/117042864-7f171800-acda-11eb-8cc6-a5170de842ec.mp4
[PURCHASE-2574]: https://artsyproduct.atlassian.net/browse/PURCHASE-2574

[PURCHASE-2574]: Swipe down dismiss modal

---

jest.config.js
scripts/changelog/changelog-types.d.ts
scripts/changelog/generateChangelogSectionTemplate.js
scripts/changelog/parsePRDescription-tests.ts
scripts/changelog/parsePRDescription.js
tsconfig.json

This PR resolves [CX-1211]
This creates a parser for PR descriptions, to extract the changelog information that folks will be able to add soon. See the RFC #4499 for more info.
This parser will be used in two places:
- In a danger rule to make sure folks are providing changelog information in their PR descriptions
- In a changelog compiler that will automatically generate a CHANGELOG.md file for each platform, based on the PRs merged between releases.
I implemented the parser in plain JS with JSDoc-based type annotations, checked by `tsc`. 
Because the parser depends on the exact wording of the [PR template header descriptions](https://github.com/artsy/eigen/blob/53f8f05cb8db1acd51c447e2cbb2e798fe3865bf/scripts/changelog/generateChangelogSectionTemplate.js#L3-L8), I added a function which …

feat: add PR description parser for changelog generation

---

src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx

This PR resolves [PURCHASE-2599]
This is follow up to the issue where a stale version of `isOfferableFromInquiry` was return. This PR fixes the cache issue that happens when a user goes out and come back to the conversation screen and the make offer button isn't update.
[PURCHASE-2599]: https://artsyproduct.atlassian.net/browse/PURCHASE-2599
[PURCHASE-2599]: https://artsyproduct.atlassian.net/browse/PURCHASE-2599

fix: address cache issue for make offer button

---

CHANGELOG.yml
src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/OpenInquiryModalButton-tests.tsx

[PURCHASE-2538] 
This ticket adds a message about and link to the buyer guarantee page to the inquiry make offer button area. I also made small style adjustments to the CTA to fix a padding issue.
__Buyer guarantee message:__
__CTA padding issue__
_Before:_
_After:_
[PURCHASE-2538]: https://artsyproduct.atlassian.net/browse/PURCHASE-2538

Add buyer guarantee message and link to inquiry make offer button

---

fastlane/Fastfile

For some reason the base64 encoded key is not being recognized in circle, attempting to revert to get betas working again.

fix: revert base64 encode of key for beta ship

---

fastlane/Fastfile

Adds an environment variable to silence beta build failures in circle while I debug build failures.

feat: add env var to silence beta failures #trivial

---

CHANGELOG.yml
src/lib/Components/Spinner.tsx

Co-authored-by: Kizito Egeonu <kizito.egeonu@gmail.com>
This PR resolves [CX-1436]
- We were registering the same native component every time the spinner props change and this lead to an issue were the native component gets registered more than once and leads to the app crashing. 
- We solved that by making sure that the component is only registered once on iOS and avoiding the native registration on android in favor of ActivityIndicator.
https://user-images.githubusercontent.com/11945712/117629036-0ac8f280-b17a-11eb-8264-8fca8fdf2a78.mov
[CX-1436]: https://artsyproduct.atlassian.net/browse/CX-1436

fix(CX-1436): User unable to search on iOS

---

src/palette/elements/Avatar/Avatar.tsx

The type of this PR is: fix
This PR resolves [CX-1375]
This PR fixes square-like artist icons in the saves and follow section
[CX-1375]: https://artsyproduct.atlassian.net/browse/CX-1375

fix(CX-1375) Artist Icon is not round

---

src/lib/Scenes/Inbox/Screens/Conversation.tsx
src/lib/Scenes/Inbox/Screens/__tests__/Conversation-tests.tsx
src/lib/navigation/navigate.ts

The type of this PR is: **CHORE**
This PR resolves [PURCHASE-2574]
This PR is follow up work to adding a dismiss modal event and addresses https://github.com/artsy/eigen/pull/4712#issuecomment-832507487. This PR specifically emits `dismissModal` and `goBack` events for andriod.
[PURCHASE-2574]: https://artsyproduct.atlassian.net/browse/PURCHASE-2574

chore: handle dismiss modal for andriod

---

src/lib/Scenes/Home/Components/SaleArtworksHomeRail.tsx
src/lib/Scenes/Home/Components/__tests__/SaleArtworksHomeRail-tests.tsx

This PR resolves [CX-1438]
Update section copy to: “Auction lots for you ending soon”.
No changelog required - we already have it there.
[CX-1438]: https://artsyproduct.atlassian.net/browse/CX-1438

feat: Change home screen "lots for you" copy

---

src/lib/AndroidApp.tsx

This might be the smallest PR I've ever done on eigen :D.
Basically, on first launch after fresh install of the app, the launchCount is 1. That if was returning, skipping the event sending.
So now it appears:

fix(analytics): fix off by one error, the fresh install event was not firing.

---

CHANGELOG.yml
android/app/src/main/java/net/artsy/app/ArtsyNativeModule.java
src/lib/AndroidApp.tsx
src/lib/NativeModules/ArtsyNativeModule.tsx

This PR resolves [CX-1226]
- Support lock screen orientation to portrait on android phones
**_I tested my changes on a physical device_**
[CX-1226]: https://artsyproduct.atlassian.net/browse/CX-1226

feat: lock screen orientation to portrait on android phones

---

src/lib/Scenes/Artwork/Artwork.tsx

A small PR to add the id of the artwork. This shows up when the `Quick Access` DevToggle is enabled.

chore(dev): some quick access info for artwork

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistHeader.tsx
src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx

This PR resolves [CX-1322]
This PR fixes incorrectly firing action_name for success event
[CX-1322]: https://artsyproduct.atlassian.net/browse/CX-1322

fix(CX-1322): incorrect action name

---

src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
src/lib/Scenes/Inbox/Components/ShadowSeparator.tsx
src/lib/Scenes/Inbox/Screens/Conversation.tsx

This PR resolves [PURCHASE-2669]
* Adds light grey keyline below header.
* Removes extra space around make offer button
* Fixes make offer info text alignement issue
Before:
After:
iPhone SE:
iPhone 12:
Regular conversation:
</details>
[PURCHASE-2669]: https://artsyproduct.atlassian.net/browse/PURCHASE-2669

UI tweaks to coversation page for make offer button

---

src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/OpenInquiryModalButton-tests.tsx
src/lib/navigation/routes.tsx

This PR resolves [PURCHASE-2665]
This adds an add webViewRoute for the buyer guarantee page.
[PURCHASE-2665]: https://artsyproduct.atlassian.net/browse/PURCHASE-2665

fix: add webViewRoute for buyer guarantee page

---

src/lib/Components/Lists/AuctionResultListItem.tsx

This PR resolves [CX-1048]
Add border radius to images in auction result rows 
_before_
_after_
_before_
_after_
[CX-1048]: https://artsyproduct.atlassian.net/browse/CX-1048

fix: add border radius for auction image item

---

CHANGELOG.yml
src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx

Currently when fetching an artwork fails (e.g. artwork being unpublished or deleted) on the conversation screen, we raise an error (on beta it shows a blank screen). We should still allow partner and collector to keep talking in the conversation even when the artwork is unavailable. This updates the error handling to simply not render the Make Offer button in this situation, and both parties can keep chatting in the conversation.
This PR resolves [PURCHASE-2685]
[PURCHASE-2685]: https://artsyproduct.atlassian.net/browse/PURCHASE-2685

feat: do not render make offer button when fetching artwork fails (PURCHASE-2685)

---

CHANGELOG.yml
src/lib/Components/ArtworkFilter/ArtworkFilter.tsx

This PR resolves [FX-2933]
Just removes the maxHeight. [Discussion here](https://artsy.slack.com/archives/C9SATFLUU/p1620943281438500) — Makes more sense, the filters actually fit on screen now, etc. 
https://user-images.githubusercontent.com/112297/118284925-f862f780-b49e-11eb-8b2b-5d475e75cb96.mov
[FX-2933]: https://artsyproduct.atlassian.net/browse/FX-2933

fix(filters): removes max height on modal

---

Artsy/App/ARAppNotificationsDelegate.m
CHANGELOG.yml

This PR resolves [CX-1477]
Fixes a bug with our push token registration. 
When a user logs out we delete the users push token from our servers, previously we had also been clearing out all the users NSUserDefaults which was causing us to prompt for and register for push notifications every time the user logs in: https://artsyproduct.atlassian.net/browse/CX-841. When we fixed this bug it uncovered this new bug 🐛. Falling back to registering every time a user logs in. 
[CX-1477]: https://artsyproduct.atlassian.net/browse/CX-1477

fix: reregister for push notifications on login every time

---

src/lib/store/config/features.ts

This PR resolves [PX-4061]
Added "AREnableOrderHistoryOption" feature flag so that admin can toggle it. Will be used to enable “Order History” option in settings.
[PX-4061]: https://artsyproduct.atlassian.net/browse/PX-4061

feat(PX-4061): Order history feature flag

---

src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx

After merging #4753, pages with tabs started crashing. It seems that when @MounirDhahri and I were working on tweaking the conditional, we made a mistake that allowed a `null` value to creep in. Switching back to the original version.

fix: stop crashing when rendering artworks tabs

---

fastlane/Fastfile

This PR resolves [CX-1109]
Android versions were not matching our sourcemaps in sentry because I was updating the app.json after bundling the apk, 🤦 this adds a helper function and update the app.json before bundling the apk.
[CX-1109]: https://artsyproduct.atlassian.net/browse/CX-1109

fix: sentry error tagging, update app.json before bundling apk

---

CHANGELOG.yml
src/lib/store/GlobalStore.tsx

Using `getUserAgentSync()` breaks the Chrome Debugger, so we use a string instead when running the app in a simulator.

fix: Use string for user agent when debugging

---

CHANGELOG.yml
android/app/src/main/res/values/styles.xml

This PR resolves [CX-1485]
Stops forcing of dark mode on users. This allows us to override the user's dark mode choice.
https://user-images.githubusercontent.com/18648835/119120134-35ddfc80-ba2c-11eb-8110-ceb0ef482766.mp4
https://user-images.githubusercontent.com/18648835/119120385-8190a600-ba2c-11eb-9588-ef01d3ee58dd.mp4
[CX-1485]: https://artsyproduct.atlassian.net/browse/CX-1485

Fix(cx-1485): ensure android dark mode can overridden inapp

---

CHANGELOG.yml
src/lib/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tsx
src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx

This PR resolves [FX-2646]
- As a user I can type into the search bar and as I type the long list of values are narrowed according to my query.
- If there are no results that match my query I  see “No results found” in the list w/ no other options
- If I find value(s) from the search box that I want to apply I have to tap the checkbox and tap the “Show # results” button. 
- If I don’t select a value from the list I have to click X to clear the search box.
- To remove an applied values I can unselect the check marks or tap “Clear all”.
- When a collector applies a value(s) **it is pinned to the top of the list**
[Material filter search](https://user-images.githubusercontent.com/3513494/119138208-5026d300-ba4a-11eb-8cc4-7a422877562d.mp4)
[CX-434]: …

feat(FX-2646): add material filter with search UI

---

android/app/src/main/AndroidManifest.xml

This PR resolves [CX-1454]
Add a list of `pathPrefix` entries that should work as a whitelist, so that only artist, artwork, auction, fair and gallery URLs are opened in the app.
[CX-1454]: https://artsyproduct.atlassian.net/browse/CX-1454

chore: add whitelist paths for android applinks

---

src/lib/Components/Input/Input.tsx
src/lib/Components/SearchInput.tsx

While working on the search input placeholder, I saw this bug and fixed it.
Notice, when hitting `Cancel`, the `X` button doesn't go away, when it should
Before
https://user-images.githubusercontent.com/100233/119155391-0c809900-ba4b-11eb-8aa6-872859e4963a.mov
After
https://user-images.githubusercontent.com/100233/119155524-32a63900-ba4b-11eb-954e-e43641e7a87e.mov

fix(search input): fix a bug in search where the clear button doesnt go away

---

CHANGELOG.yml
src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx

The type of this PR is: **Bugfixes**
This PR resolves [FX-2934]
Add ability to unselected "ways to buy" filter options
https://user-images.githubusercontent.com/3513494/119193114-ceef3080-ba89-11eb-95d4-20b7d042a1a1.mp4
[FX-2934]: https://artsyproduct.atlassian.net/browse/FX-2934

fix(FX-2934): add ability to unselected ways to buy options

---

src/lib/utils/track/SegmentTrackingProvider.ts

Silly me, I was sending all analytics events to staging/dev, when I should be sending to prod/release too!

analytics(android): send to segment release when not in __DEV__

---

src/lib/Scenes/Onboarding/ForgotPassword.tsx
src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
src/lib/Scenes/Onboarding/OnboardingLogin.tsx
src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx

I noticed that for smaller screens it just looks funky, like:
Ignore the button and checkbox being too far to the left. Fixed here: https://github.com/artsy/eigen/pull/4847
Notice that the back button almost not visible, all the way at the top (I have a ticket here https://artsyproduct.atlassian.net/browse/CX-1504). I spend like a minute trying to see what's happening while filling in the input, until I figured out I can actually scroll that screen. It totally seemed like I can't.
No idea why this was there, but now it's way more user friendly.
Before:
https://user-images.githubusercontent.com/100233/119351091-003d4b80-bc98-11eb-88b9-9dad5f74ecf9.mov
After:
https://user-images.githubusercontent.com/100233/119351107-059a9600-bc9 …

Enhancement(layout): add the scrollbar bar for smaller screens

---

CHANGELOG.yml
src/lib/Components/Input/Input.tsx

This PR resolves [CX-1506]
This PR delays the placeholder text update when the size of the input increases to prevent it from being rendered on multiple lines on Android. 
If the placeholder text gets changed in `onLayout()` it will be rendered before the size of the input increases which can cause the placeholder to be rendered on multiple lines on Android (see screenshot in [CX-1506]).
https://user-images.githubusercontent.com/4691889/119473804-cded2600-bd4b-11eb-8ceb-03b51d4b02e9.mp4
[onLayout Documentation](https://reactnative.dev/docs/view#onlayout)
[CX-1506]: https://artsyproduct.atlassian.net/browse/CX-1506
[CX-1506]: https://artsyproduct.atlassian.net/browse/CX-1506

fix: Prevent multiline input placeholder on Android

---

CHANGELOG.yml
src/palette/elements/Touchable/Touchable.tsx
src/setupJest.ts

This PR resolves [FX-2885]
Users can swipe on rows in the filters modal to enter a filter facet or return to the filters overview. When a user does this, it selects the filter facet that was pressed to swipe. The problem is that the filter navigation container is rendered [inside React modal component](https://github.com/artsy/eigen/blob/dimatretyak/fix-select-filter-item-on-swipe/src/lib/Components/ArtworkFilter/ArtworkFilter.tsx#L142) (see attached videos).
https://user-images.githubusercontent.com/3513494/119384422-5aa4cf00-bccd-11eb-91b4-02baffd55bc1.mp4
https://user-images.githubusercontent.com/3513494/119385657-1dd9d780-bccf-11eb-9eeb-bcc0c67770ec.mp4
1. [Disable the swipe back gesture](https://reactnavigation.org/docs/stack-navigator/#gestureenabled) …

fix: select filter item on swipe

---

src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/MakeOfferModal-tests.tsx

[PURCHASE-2723]
As per [this discussion]("https://artsy.slack.com/archives/C9YNS4X32/p1622137949282200"), it is clear this is happening for edition works with only 1 edition. For editioned works, we hide the edition selector when `editionSets` has a length of 1,  but we also disable the button unless an edition has been selected. To fix this, I set `selectedEdition` to be the only edition in `editionSets`.
__Before:__
__After:__
[PURCHASE-2723]: https://artsyproduct.atlassian.net/browse/PURCHASE-2723

fix disabled button bug for works with only one edition

---

CHANGELOG.yml
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx

This PR resolves [FX-2926]
As a user, when I press “clear all” I expect the following to happen:
1. The active filters should be removed
2. The clear operation should be applied
3. The modal should close
https://user-images.githubusercontent.com/3513494/120184720-f7a9bf80-c219-11eb-8506-f749c815f4e0.mp4
https://user-images.githubusercontent.com/3513494/120184705-f1b3de80-c219-11eb-88f8-2d22066a3810.mp4
[FX-2926]: https://artsyproduct.atlassian.net/browse/FX-2926

fix: apply "cancel all" instantly

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx

This PR resolves [FX-2964] and [FX-2965]
As an admin,
**When** I visit the artist artworks tab with _the "saved search" feature flag enabled_
**I see** a banner with a toggle
Acceptance criteria/approach
* Toggle on/off changes banner background and text color
* Is sticky with the filter bar, staying at the top of the screen as the user scrolls down and up the screen
* Not in scope: conditional display. For this ticket, banner is always shown (when feature flag is on). 
* Not in scope: any querying or mutations. This ticket is UI-only
As an admin with _the saved search feature flag enabled_
**When** I visit the artworks tab for an artist
**I do not see** the saved search banner
**And when** I apply a set of filters
**I see** the saved search banner …

feat: admin sees saved search banner

---

CHANGELOG.yml
src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx

This PR resolves [FX-2888]
When either “Ways to buy”, “size” or “price range” filter is selected, selecting another filter resets their value in the analytics event
https://user-images.githubusercontent.com/3513494/120470555-556e1100-c3ac-11eb-9f57-b62a0e798cb2.mp4
[FX-2888]: https://artsyproduct.atlassian.net/browse/FX-2888

fix: send only changed filter params in the analytics event

---

CHANGELOG.yml
src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx

This PR resolves [PX-4065]
Fixed wrong displaying in Order History when fields are too long.
[PX-4065]: https://artsyproduct.atlassian.net/browse/PX-4065

fix: wrong displaying in Order History when fields are too long (PX-4065)

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistConsignButton.tsx
src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
src/lib/Scenes/Consignments/index.tsx
src/lib/navigation/navigate.ts

This PR resolves [CX-1289]
I fixed an issue where pressing the android native button back would return us to the home tab. Now, if we switched to the sales tab from the search tab when we click the android native back button, we return to the search tab:
https://user-images.githubusercontent.com/30176348/120526543-f75c2080-c3e1-11eb-81be-89dc211f38b3.mov
[CX-1289]: https://artsyproduct.atlassian.net/browse/CX-1289

fix android native go back from sale tab to search

---

CHANGELOG.yml
src/lib/Scenes/Home/Home.tsx
src/lib/utils/placeholders.tsx

This PR resolves [CX-1027]
Prevent home screen placeholders from rerendering and changing the size before the real content is visible
https://user-images.githubusercontent.com/4691889/120608205-38d7e480-c451-11eb-9577-86d6a53364b3.mp4
[CX-1027]: https://artsyproduct.atlassian.net/browse/CX-1027

fix: prevent home screen placeholders from rerendering

---

CHANGELOG.yml
docs/pull_request_template.md

This PR removes the PR template reference to CX-434 in the comment above this line, which causes Peril to attach an unrelated ticket to every PR.
In the PR description below is the link that was automatically attached (along with the `jira synced` label): 

chore: update pr template jira reference

---

CHANGELOG.yml
src/__generated__/ArtistArtworksContainerCreateSavedSearchMutation.graphql.ts
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/lib/Components/ArtworkFilter/Filters/helpers.ts
src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx

This PR resolves [FX-2971]
As an admin,
When I toggle the on/off switch on the saved search banner
A new searchCriteria and userSearchCriteria are created in Gravity
With the exact combination of filters I have selected in the UI
* Toggling the switch "on" _executes the mutation_
* For the purposes of this ticket, it's sufficient to check that the `searchCriteria` and `userSearchCriteria` were created using a console
* _Not in scope_: handling failure
* _Not in scope_: preserving banner "on" state on reload/reapplication of same filters
* _Not in scope_: deletion of previously saved searchCritera on toggle off
https://user-images.githubusercontent.com/3513494/120678920-4917b000-c4a1-11eb-8042-5fb55b7ee6b3.mp4 …

feat: create save search mutation

---

CHANGELOG.yml
src/__generated__/ArtistArtworksContainerDeleteSavedSearchMutation.graphql.ts
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx

This PR resolves [FX-2973]
As an admin with the saved search flag enabled,
**When** viewing the artworks grid with an existing saved search
**I can** toggle to "off"
**And** the saved search will be deleted
* Toggling to "off" deletes UserSearchCriteria, leaves SearchCriteria intact
* Out of scope: error handling
* Out of scope: saved search persistence/finding a previously existing saved search. This ticket assumes that a user has just created a saved search by toggling "on", _then immediately toggles_ "off"
https://user-images.githubusercontent.com/3513494/120839344-7d5aa180-c571-11eb-9f86-4b9e85bb65a8.mp4
[FX-2973]: https://artsyproduct.atlassian.net/browse/FX-2973

feat: delete saved search mutation

---

fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/name.txt
fastlane/metadata/en-US/release_notes.txt
fastlane/metadata/en-US/subtitle.txt

- Updates release notes for version 6.9.4 on both Android and iOS
- Updates title and subtile of app to new copy from marketing

chore: 6.9.4 release prep

---

CHANGELOG.yml
src/__generated__/SavedSearchBannerCreateSavedSearchMutation.graphql.ts
src/__generated__/SavedSearchBannerDeleteSavedSearchMutation.graphql.ts
src/__generated__/SavedSearchBannerQuery.graphql.ts
src/__generated__/SavedSearchBannerTestsQuery.graphql.ts
src/__generated__/SavedSearchBanner_me.graphql.ts
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts

This PR resolves [FX-2967]
As an admin with the saved search feature flag enabled
_When I_ apply filters on the artist artwork screen
_A query_ is executed that checks if I have a saved search with those filters
* Every time a user with the saved search flag applies filters, a query is executed that checks if that user has an existing saved search with those filters
* End result of this ticket could just be logging out the result of that query
https://user-images.githubusercontent.com/3513494/121049697-9e650180-c7c0-11eb-9c11-e93e46673b2e.mp4
https://user-images.githubusercontent.com/3513494/121050503-4c70ab80-c7c1-11eb-8feb-832316e97550.mp4
[FX-2967]: https://artsyproduct.atlassian.net/browse/FX-2967

feat: check savedSearch query field

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/lib/Components/ArtworkFilter/Filters/__tests__/helpers-tests.tsx
src/lib/Components/ArtworkFilter/Filters/helpers.ts
src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx

This PR resolves [FX-3001]
As an admin,
When I switch on the saved search banner
A new searchCriteria and userSearchCriteria are created in Gravity
With the specified size filter values I have selected in the UI
Acceptance criteria:
* Toggling the switch "on" executes the mutation
* For the purposes of this ticket, it's sufficient to check that the searchCriteria and userSearchCriteria were created with specified size filter values
* Not in scope: handling failure
* Not in scope: preserving banner "on" state on reload/reapplication of same filters
* Not in scope: deletion of previously saved searchCritera on toggle off
https://user-images.githubusercontent.com/3513494/121169421-aa060600-c85c-11eb-90d1-d8fe16960ee0.mp4
[FX-3001]: …

feat: size filter for saved search

---

CHANGELOG.yml
Podfile.lock
src/lib/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/ConversationCTA-tests.tsx

This PR resolves [PURCHASE-2681] by continuing to show the offer approved CTA when an order has been fulfilled. It also corrects a likely bug where we will not show any CTA for an offer approved by the seller that does not define the order total (ie, the total was already available).
[PURCHASE-2681]: https://artsyproduct.atlassian.net/browse/PURCHASE-2681

fix: show approved cta when fulfilled

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx

This PR resolves [FX-3000]
User Story:As a collector, when I click "clear all" when filtering I expect the filter options to clear without closing the modal so I can immediately choose a new set of them. 
https://user-images.githubusercontent.com/3513494/121177984-b1321180-c866-11eb-9b98-cb830b943694.mp4
[FX-3000]: https://artsyproduct.atlassian.net/browse/FX-3000

feat: don’t close modal when “clear all” tapped

---

src/lib/Components/ArtsyReactWebView.tsx

This PR resolves [CX-1567]
I accidentally removed the top padding in `ArtsyReactWebViewPage` instead of `ArtsyReactWebView` in a previous [fix](https://github.com/artsy/eigen/pull/4938). This PR moves the top padding back.
|Before|Article|Auction FAQs|
|---|---|---|
|![Simulator Screen Shot - iPhone 8 - 2021-06-09 at 13 51 01](https://user-images.githubusercontent.com/4691889/121349403-c15ef500-c929-11eb-8433-cce5d2627133.png)|![Simulator Screen Shot - iPhone 8 - 2021-06-09 at 12 38 47](https://user-images.githubusercontent.com/4691889/121340230-a7b8b000-c91f-11eb-9f8d-bb916823fe33.png) |![Simulator Screen Shot - iPhone 8 - 2021-06-09 at 12 39 32](https://user-images.githubusercontent.com/4691889/121340302-c159f780-c91f-11eb-859f-e85493c124d0.png) |
The PR …

fix: move artsy web view padding to correct place

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx

This PR resolves [FX-3003]
As an admin with the saved search feature flag enabled
When I visit the artworks tab for an artist
I do not see the saved search banner
And when I apply only sort filter
I don’t see the saved search banner
When I apply other set of filters
I see the saved search banner
https://user-images.githubusercontent.com/3513494/121387487-60e4ad80-c953-11eb-80bf-594d3dd3ab6f.mp4
[FX-3003]: https://artsyproduct.atlassian.net/browse/FX-3003

feat: don't show saved search for only sort filter

---

src/lib/Scenes/Home/Components/ArticlesRail.tsx

https://artsyproduct.atlassian.net/browse/CX-1596
This PR resolves [CX-1596]
Hide scrolling indicator for Market News rail to avoid overlapping.
https://user-images.githubusercontent.com/27921300/121891809-39f3f600-cd1c-11eb-84f7-1e53c183dfc9.mov
[CX-1596]: https://artsyproduct.atlassian.net/browse/CX-1596

remove horizontal scrolling indicator

---

CHANGELOG.yml
src/lib/Components/Buttons/InfoButton.tsx

This PR resolves [CX-1614]
The Info icon on the artist insights tab is not aligned with the text next to it. The same goes for the other references of the same Button.
Fixed the alignment issues
|Android|iphone SE (1st gen)| iphone 8 | iphone 12 pro|
|![Screenshot_1623848731](https://user-images.githubusercontent.com/21178754/122226029-dac9e900-ceb5-11eb-9080-8f2ad330fb51.png)|![Simulator Screen Shot - iPhone SE (1st generation) - 2021-06-16 at 14 55 09](https://user-images.githubusercontent.com/21178754/122226027-dac9e900-ceb5-11eb-8fe5-60d4d34a6a63.png)|![Simulator Screen Shot - iPhone 8 - 2021-06-16 at 14 48 34](https://user-images.githubusercontent.com/21178754/122226017-d8678f00-ceb5-11eb-9c1f-99eccb3082e4.png)|![Simulator Screen …

fix: align InfoCircleIcon inside InfoButton

---

src/lib/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx

This PR resolves [CX-962]
The ```<AnimatedBottomButton />``` was missing required styles to be rounded and as a result when pressed it had a square background with white color.
Noticed that it is being used also [here](https://github.com/artsy/eigen/blob/7aba7148840758f94da89730845ad9b5f5aa9dbf/src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx) properly rounded so I replicated the usage at the ```<ArtworkFilterOptionScreen />``` where we had the issue.
|Android|iOS|
|---|---|
|![Screenshot_1623744894](https://user-images.githubusercontent.com/21178754/122017930-b2ad8d80-cdc2-11eb-8bf0-36666dac0e48.png)|![Simulator Screen Shot - iPhone 12 Pro - 2021-06-15 at 10 13 25](https://user-images.githubusercontent.com/21178754/122017940-b50fe780-cdc2-11e …

fix: add roundedButtonStyle to floating button

---

CHANGELOG.yml
src/lib/Scenes/Consignments/Screens/Overview.tsx

This PR resolves [CX-1536]
The 'Next' button should be aligned to center
Before:
After:
[CX-1536]: https://artsyproduct.atlassian.net/browse/CX-1536

fix(CX-1536): align the button to center in the 'sell work' menu

---

CHANGELOG.yml
src/__generated__/OrderDetailsQuery.graphql.ts
src/__generated__/OrderDetailsTestsQuery.graphql.ts
src/__generated__/OrderDetails_order.graphql.ts
src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
src/lib/Scenes/OrderHistory/OrderDetails/Components/ShipsToSection.tsx
src/lib/Scenes/OrderHistory/OrderDetails/Components/SummarySection.tsx
src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetails-tests.tsx
src/lib/Scenes/OrderHistory/OrderDetails/__tests__/ShipsToSection-tests.tsx

This PR resolves [PX-4212] and [PX-4212] (reopened) with small fixes
1. Name from shipping address should be displayed instead of the account name
2. Country should be written with the full name 
3. “Shipping” and “Tax” fields names should be returned back
4. Order Summary paddings fix
[PX-4212]: https://artsyproduct.atlassian.net/browse/PX-4212
[PX-4212]: https://artsyproduct.atlassian.net/browse/PX-4212

fix: Invalid user name + acronym for country name (PX-4241) and OrderSummary fixes (PX-4212)

---

src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/helpers-tests.tsx
src/lib/Components/ArtworkFilter/Filters/helpers.ts

Rounding the value when converting from inches to centimeters globally

fix: correct round cm values during inch convert

---

CHANGELOG.yml
src/__generated__/OrderDetailsQuery.graphql.ts
src/__generated__/OrderDetailsTestsQuery.graphql.ts
src/__generated__/SoldBySectionTestsQuery.graphql.ts
src/__generated__/SoldBySection_soldBy.graphql.ts
src/lib/Scenes/OrderHistory/OrderDetails/Components/SoldBySection.tsx
src/lib/Scenes/OrderHistory/OrderDetails/__tests__/SoldBySection-tests.tsx

This PR resolves [PX-4257]
"Pick up ..." - are displayed when "Pick up" fulfillment chosen
"Ships from..." - are displayed when "Shipping" fulfillment chosen
[PX-4257]: https://artsyproduct.atlassian.net/browse/PX-4257

fix: Order History. Sold by: "Ships from" is displayed for "Pickup" fulfillment (PX-4257)

---

CHANGELOG.yml
src/lib/store/config/features.ts

This PR makes the Order History feature configurable via an echo flag. (Corresponding echo PR here: https://github.com/artsy/echo/pull/95)

feat: Adds flag for order history feature

---

CHANGELOG.yml
src/lib/Components/ArtsyReactWebView.tsx
src/lib/Components/StyledWebView.tsx

This PR resolves [CX-1613]
Sets the deceleration rate for web views to normal (default is fast). This aligns scroll behaviour in web views to the rest of the app.
[CX-1613]: https://artsyproduct.atlassian.net/browse/CX-1613

feat: set web view deceleration rate to normal

---

CHANGELOG.yml
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx

This PR resolves [FX-3007] and [FX-3006]
**createSavedSearch**
Check the UI update for the saved search banner when the user clicks the "enable" button and performs the create saved search mutation
**deleteSavedSearch** 
Check the UI update for the saved search banner when the user clicks the "disable" button and performs the delete saved search mutation
[FX-3007]: https://artsyproduct.atlassian.net/browse/FX-3007
[FX-3006]: https://artsyproduct.atlassian.net/browse/FX-3006

chore: add specs for deleteSavedSearch and createSavedSearch mutations

---

CHANGELOG.yml
package.json
src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
yarn.lock

This PR resolves [FX-3014]
Use the new `toggledSavedSearch` event in @artsy/cohesion to track when a user enables+disables a saved search.
[FX-3014]: https://artsyproduct.atlassian.net/browse/FX-3014

chore: add saved search analytics tracking

---

src/lib/store/GlobalStore.tsx

This PR resolves https://artsy.slack.com/archives/CP9P4KR35/p1624443687243500
As Redux-flipper wasn't mocked it was breaking the globalstore initiation. I was going to mock it but it seemed unnecessary for me as it's only part of the dev process. So I just disabled it while testing.

fix: broken test due to missing redux-flipper

---

Podfile.lock
src/lib/Components/HeaderArtworksFilter.tsx
src/lib/Components/__tests__/HeaderArtworksFilter-tests.tsx
src/lib/Scenes/Collection/Components/CollectionArtworksFilter.tsx
src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
src/lib/Scenes/Show/Components/ShowArtworks.tsx
src/lib/Scenes/Show/Components/ShowArtworksFilter.tsx
src/lib/Scenes/Show/Show.tsx
src/lib/Scenes/Show/__tests__/Show-tests.tsx
src/lib/Scenes/Show/__tests__/ShowArtworksFilter-tests.tsx

[FX-2908]
I incapsulated logic of sticky header from [here](https://github.com/artsy/eigen/pull/4932) and applied for Show screen
**Before**
**After**
[FX-2908]: https://artsyproduct.atlassian.net/browse/FX-2908

feat: Sticky header on show screen

---

CHANGELOG.yml
src/lib/Components/Gene/Header.tsx

This PR resolves [CX-1532]
User was is to unfollow a category - it remains being followed after refresh.
**The bug**
https://user-images.githubusercontent.com/27921300/123100356-576b4300-d433-11eb-87de-0cbdc1edf4f1.mov
**The fix**
https://user-images.githubusercontent.com/27921300/123099972-f80d3300-d432-11eb-88a0-5657657da7ed.mov
[CX-1532]: https://artsyproduct.atlassian.net/browse/CX-1532

fix (CX-1532): user can't unfollow category

---

src/lib/Scenes/Inbox/Components/Conversations/Preview/ArtworkPreview.tsx

This PR resolves [PURCHASE-2733]
Remove line, that causes a problem on iOS. After removing it looks fine on iOS and Android on different devices. 
Narrow android example:
Wide iOS example:
[PURCHASE-2733]: https://artsyproduct.atlassian.net/browse/PURCHASE-2733

fix: iOS artwork preview misalignment

---

src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx

This PR resolves [FX-3035]
That copy that is displayed on the banner where users can enable or disable a saved search does not match the design specs.
Currently, this banner shows “New works alert for this search” but the design specs indicate that this copy should be “Set alert for this artist” in the disabled state, and “Remove alert for this artist” in the enabled state.
https://user-images.githubusercontent.com/3513494/123254699-a37fbb80-d4f7-11eb-8d50-9d009bbdb4b6.mp4
https://user-images.githubusercontent.com/3513494/123254735-ae3a5080-d4f7-11eb-9a4e-25510d8bbd76.mp4
- Update the saved search banner label for enable/disable states - dzmitry tratsiak
[FX-3035]: https://artsyproduct.atlassian.net/browse/FX-3035

fix: toggle saved search banner label by enable/disable state

---

src/lib/Components/PopoverMessage/PopoverMessage.tsx

This PR resolves [FX-3036]
The copy in the toast message that is displayed after a user enables an alert does not match how it is laid out in the design spec (see the attached image in Jira ticket). In the design spec, there is a wide margin between the copy and the right edge of the toast box. However, the current implementation has the text folding at the edge, and crowds the X to close the toast.
- Update the design for Popover Message component – dzmitry tratsiak 
[FX-3036]: https://artsyproduct.atlassian.net/browse/FX-3036

fix: update popover message markup

---

CHANGELOG.yml
src/lib/Components/LocationMap/index.tsx

This PR resolves [CX-1621]
STR:
1. Open app
2. Click on search 
3. Search for Secret Art Ltd
4. Click "Overview"
5. Click "See all location details"
6. On Locations page, click any location to open menu
7. Click any options on the menu
**Actual result:**
Links are not mapped correctly with the menu options.
"Open in Apple Maps", no response (does not open Apple Map)
"Open in City Mapper", opens Apple Map
"Open in Google Map", option opens City Mapper
"Copy Address", opens Google Map
**Expected result:**
When clicking on an option, the app redirects to the relevant page accordingly
**After the fix:**
https://user-images.githubusercontent.com/27921300/123621145-35930700-d80b-11eb-8a29-01da63aa75d8.mov
[CX-1621]: …

fix (CX-1621): locations menu does not redirect correctly

---

src/lib/Containers/Gene.tsx

This PR resolves [FX-3043]
The purpose of this ticket is to hide the “Refine” button so that users don’t experience this bug until we can refactor the filter modal associated with it.
- Hide "Refine" button on category screen header – dzmitry tratsiak
[FX-3043]: https://artsyproduct.atlassian.net/browse/FX-3043

feat: show refine button only for iOS

---

src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesFullArtistSeriesList-tests.tsx
src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesListItem-tests.tsx
src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesMoreSeries-tests.tsx
src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx

This PR resolves [FX-2254]
ArtistSeriesListItem was using `TouchableOpacity` from `react-native` and not `Touchable` from palette.
Furthermore the `underlayColor` wasn't the same as other parts of the app so added "black5" to match the other Touchables.
The screenshots below show the touchable behaviour when the user is pressing the button.
Also made the `<ArtistSeriesListItem />` to take 100% width of the list and adjusted margins accordingly for consistensy as suggested from design [here](https://artsy.slack.com/archives/C9SATFLUU/p1624960749370100)
|Android|iOS|
|---|---|
|![android](https://user-images.githubusercontent.com/21178754/123755168-f07add80-d8bb-11eb-9d73-f881bc9aca61.png)|![ios](https://user-images.githubusercontent.com/21178754/12375 …

fix: use palette touchable /w underlayColor & consistency style changes in ArtistSeriesListItem

---

CHANGELOG.yml
HACKS.md
android/app/src/main/java/net/artsy/app/MainActivity.java

This PR resolves [CX-1660]
There is a [known issue](https://github.com/software-mansion/react-native-screens/issues/17) in rn-screens that causes a crash when restoring the application from background in release builds, this is the recommended fix: https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067
Tested locally, I'll test once this goes live in a beta and follow-up with a hot fix if all goes okay. 
-
-
- Fixes a crash when opening app from background - brian
-
[CX-1660]: https://artsyproduct.atlassian.net/browse/CX-1660

fix: android rn screen crash

---

CHANGELOG.yml
src/lib/Scenes/MyProfile/MyProfile.tsx
src/lib/store/config/features.ts

This PR resolves [PURCHASE-2800](https://artsyproduct.atlassian.net/browse/PURCHASE-2800) which is a pre-cursor to [PURCHASE-2759](https://artsyproduct.atlassian.net/browse/PURCHASE-2759) _"add empty state for saved addresses page"_.
This adds a feature flag to enable _Saved Addresses_. See video:
https://user-images.githubusercontent.com/29984068/124023382-dcb6a080-d9bb-11eb-90ff-e46af936024c.mov
- Add a feature flag to toggle Saved Addresses.

feat: (PURCHASE-2800) Feature flag for saved addresses

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx

This PR resolves [FX-3040]
Added `context_screen_owner_slug` to `toggleSavedSearch`
#nochangelog
[FX-3040]: https://artsyproduct.atlassian.net/browse/FX-3040

feat: add context_screen_owner_slug to toggleSavedSearch analytics payload

---

CHANGELOG.yml
src/lib/Components/ArtsyReactWebView.tsx
src/lib/Scenes/Artwork/Artwork.tsx

This PR resolves [CX-958]
**The issue:**
As a collector, when I buy an artwork, the artwork screen should automatically refresh to show I've purchased it so that I'm sure I bought it.
Without refresh "Buy now" button is still available and we don't display "Sold" status.
**The fix:**
https://user-images.githubusercontent.com/27921300/123959866-f00f3f00-d9ae-11eb-8527-6c626b8d80c1.mov
-
-
-
-
[CX-958]: https://artsyproduct.atlassian.net/browse/CX-958

fix (CX-958): refresh artwork after purchase

---

src/lib/Components/StickyHeaderPage.tsx

This PR resolves [FX-2907]
Some fixes for #4951. Fixed the problem of the sticky header disappearing when the user fetched the next portion of data, and the header also remained sticky in the footer area
https://user-images.githubusercontent.com/3513494/124199886-b177a280-dadc-11eb-9493-73498b41b1f6.mp4
https://user-images.githubusercontent.com/3513494/124200199-64480080-dadd-11eb-82a4-065d52baa7ec.mp4
https://user-images.githubusercontent.com/3513494/124199599-f51ddc80-dadb-11eb-985f-1dc639fb62f0.mp4
https://user-images.githubusercontent.com/3513494/124199955-db30c980-dadc-11eb-9942-207fe35bab1c.mp4
-
-
-
-
[FX-2907]: https://artsyproduct.atlassian.net/browse/FX-2907

fix: disappearing sticky header

---

android/app/src/main/res/values/braze.xml

This is a follow up to https://github.com/artsy/eigen/pull/4952 that updates the Braze app id for Android production builds. We did this as sort of an experiment and used the staging key but it's working so this PR updates it to the production key.
Updating like this is good because it properly attributes production sessions BUT it also means that dev and beta builds will also phone home to Braze as if they were the production app. What would be better would be to switch this key depending on the build we're making but I don't really know how to do that.
There was some chatter on Slack here about ways to do this:
https://artsy.slack.com/archives/C02BAQ5K7/p1623248720272400?thread_ts=1623248529.271200&cid=C02BAQ5K7
So if doing that is easier/faster than what I've got here, happy to close …

feat: Use correct Braze app id for android prod GRO-262

---

CHANGELOG.yml
src/lib/Components/Lists/AuctionResultListItem.tsx
src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
src/lib/Scenes/Home/Components/__tests__/AuctionResultsRail-tests.tsx

This PR resolves [CX-1674]
- Prevents auctionResultsRail from showing a spinner if there are no auction results
- Checks if artist name is not null 
-
-
-
-
[CX-1674]: https://artsyproduct.atlassian.net/browse/CX-1674

fix: don't show spinner when user has no auction results by followed artists

---

CHANGELOG.yml
src/lib/Scenes/Home/Components/CollectionsRail.tsx

This PR resolves [CX-1677]
Prevents the collections home rail from showing a spinner if no collections are available.
-
-
-
-
[CX-1677]: https://artsyproduct.atlassian.net/browse/CX-1677

fix: Dont show home collections rail spinner

---

android/app/src/main/AndroidManifest.xml
src/__generated__/SavedAddressesQuery.graphql.ts
src/__generated__/SavedAddressesRefetchQuery.graphql.ts
src/__generated__/SavedAddressesTestsQuery.graphql.ts
src/__generated__/SavedAddresses_me.graphql.ts
src/lib/AppRegistry.tsx
src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx

This PR resolves [PURCHASE-2758](https://artsyproduct.atlassian.net/browse/PURCHASE-2758)
Most of this work was already merged via [#5087](https://github.com/artsy/eigen/pull/5087) and [#5070](https://github.com/artsy/eigen/pull/5070). This PR adds the `refetchContainer` which was explicitly mentioned in the ticket. As discussed, this satisfies the ask and will likely be replaced by `paginationContainer` in the work that follows.
> Note that I ended up [forcing the refetch](https://github.com/artsy/eigen/compare/ovasdi/PURCHASE-2758/saved-addresses-refetch?expand=1#diff-e7e6e031fb7544333964ce2fc7419c4b965c7c48bea7cc6470bc17d464ebac05R26) as relay was holding on to and serving cached values during development. Since this will likely be changed soon, I …

feat: (PURCHASE-2758) add refetch to saved addresses

---

Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
CHANGELOG.yml

The type of this PR is: Fix
This PR resolves [CX-1604](https://artsyproduct.atlassian.net/browse/CX-1604)
1. Create an account in staging using Facebook auth
2. Log out
3. Log back in using Facebook auth
4. Observe you get error ‘Couldn’t link Facebook account'
If we login via Facebook for the first time, we don’t have the gravity_session_id cookie (1 screenshot), but before the second login it is (2 screenshots), and because of its presence when sending a request for gravity -> device will authorize us by session ID and sets the value for current_user -> returns an error that the user already exists (3 screenshots).
Since the failed login is only affected by the session cookies, I decided to delete them before logging in with facebook.
I'm not sure if the solution with deleting cookies …

fix[CX-1604] Facebook login is failing after signing up for a new account

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/ArtworkFilter/Filters/SortOptions.tsx
src/lib/Scenes/Artist/Artist.tsx
src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx

This PR resolves [FX-3075]
- As a user
- When I receive a saved search push notification
- And tap on that notification
- I am taken to the artist artworks tab
- And after a brief load,
- And if I tap the sort & filter button
- I see that the sort by filter is applied to the “Recently added“
https://user-images.githubusercontent.com/3513494/125116758-daf48780-e0f5-11eb-89a6-6ffac7b4dfd0.mp4
- Display "Recently added" sort by filter value when tap open saved search notification - dzmitry tratsiak
-
-
-
</details>
[FX-3075]: https://artsyproduct.atlassian.net/browse/FX-3075

fix(FX-3075): apply default sort for saved search

---

.circleci/config.yml

- do not run ci on update-changelog branch
-
-
-
- Do not run ci on update-changelog branch
</details>

chore: do not run ci on update-changelog branch

---

src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
src/lib/Scenes/AuctionResultsForYou/__tests__/AuctionResultsForYou-tests.tsx

This PR resolves [[CX-1693](https://artsyproduct.atlassian.net/browse/CX-1693)] 
Changing the screen title from **Auction Results for You** to **Auction Results for Artists You Follow**.
Before | After
---- | ----
- Change the screen title from "Auction Results for You" to "Auction Results for Artists You Follow".
</details>

fix [CX-1693]: [Auction Results for Artists You Follow] Change screen title

---

src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
src/lib/Components/PopoverMessage/PopoverMessage.tsx
src/lib/Components/PopoverMessage/PopoverMessageProvider.tsx
src/lib/Components/PopoverMessage/__tests__/PopoverMessage-tests.tsx

This PR resolves [FX-3072]
* Multiple toasts onscreen at the same time results in somewhat jerky movement of the toasts when one disappears. We would like to prevent this movement so that the user has a smooth experience. 
* We only need one single toasts as its a toggle and should reflect the last action for clarity. So a new toast would move in and replace the current.
https://user-images.githubusercontent.com/3513494/125271415-67c85c80-e313-11eb-82bd-47994ad255fc.mp4
https://user-images.githubusercontent.com/3513494/125272300-5b90cf00-e314-11eb-9c7b-b052a7ed60be.mp4
- Stop jerky movement of multiple toasts - dzmitry tratsiak
-
-
-
</details>
[FX-3072]: https://artsyproduct.atlassian.net/browse/FX-3072

fix(FX-3072): jerky popover message

---

src/lib/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
src/lib/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx

This PR resolves [FX-3104]
The user is not able to type any amount in the USD minimum and USD maximum and when the user taps on the USD minimum or maximum the custom is not staying there.
The problem is that we have a `FlatList` rendered inside the `ArtsyKeyboardAvoidingView`
https://user-images.githubusercontent.com/3513494/126776743-c5084d27-aac2-4831-b3ce-b93c55adbd27.mp4
If we render the `ScrollView` inside the `ArtsyKeyboardAvoidingView` (as it happens in most places in the code), there are no such problems
https://user-images.githubusercontent.com/3513494/126776856-37b52072-c156-45f6-8800-2824d21e4257.mp4
Added the ability to use `ScrollView` instead of `FlatList` for `SingleSelectOption`. In our case, the `Size` and `Price` filters will have a …

feat(FX-3104): ability to use ScrollView instead of FlatList

---

src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/SizeOptions-tests.tsx
src/lib/Components/ArtworkFilter/SavedSearch/__tests__/convertersToFilterParams-tests.ts

This PR resolves [FX-3103]
In the Medium all data is showing 40cm to 100 cm and it's not appropriate under 40 cm in the medium size because in the small size already available under 40 cm.
- Update the medium size label – dzmitry tratsiak
-
-
-
</details>
[FX-3103]: https://artsyproduct.atlassian.net/browse/FX-3103

fix(FX-3103): update size options label

---

src/__generated__/SavedSearchButtonQuery.graphql.ts
src/__generated__/SavedSearchButtonTestsQuery.graphql.ts
src/__generated__/SavedSearchButton_me.graphql.ts
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx
src/lib/store/config/features.ts
src/palette/elements/Button/Button.tsx

This PR resolves [FX-3089]
As an admin with the saved search M2 feature flag enabled,
If I am viewing an artist artworks grid,
I always see the "create alert" button
* This ticket includes introduction of a feature flag for M2 and hides these changes behind it
* Button is disabled when no filters are applied
* Button is enabled when filters are applied but no search criteria with those filters exists
* Button is disabled when search criteria with existing filters exists
https://user-images.githubusercontent.com/3513494/126628736-b7733313-3b04-44b1-bc3a-f9deddb20a8d.mp4
https://user-images.githubusercontent.com/3513494/126629723-bf05d0f3-7c2b-489e-bcd9-7c8d5d29c980.mp4
- 
-
-
- Saved search banner M2 – …

feat(FX-3089): create saved search alert button

---

package.json
src/lib/Components/ArtistListItem.tsx
src/lib/Components/__tests__/ArtistListItem-tests.tsx
src/lib/store/config/features.ts
src/lib/utils/AdminMenu.tsx
src/lib/utils/track/SegmentTrackingProvider.ts
src/palette/PaletteFlag.tsx
src/palette/Theme.tsx
src/palette/elements/Avatar/Avatar.tsx
src/palette/elements/BorderBox/BorderBox.tsx
src/palette/elements/Flex/Flex.tsx
src/palette/elements/Message/Message.tsx
src/palette/elements/Typography/Typography.tsx
src/palette/hooks.ts
src/palette/platform/primitives.ts
yarn.lock

This PR resolves the issue here https://artsy.slack.com/archives/C02BAQ5K7/p1627387196273400.
easy-peasy/redux cause a lot of require cycles, but usually they don't cause problems. The latest flag for palette v3 just broke that limit. iOS was ok with that but not Android.
The main problem was that, starting from `Theme`, we have a hook that needs to check a flag. That flag lives in GlobalStore, that requires NativeModel. NativeModel needs `navigate`, and that needs `AppRegistry`. That file imports all screens, and of course a lot of them use Theme. And this is a nice require cycle that breaks our stuff.
One of the two possible solutions was to remove the flag, but I didn't want that. Code listens to me, not the other way around 😆. So the other solution …

fix(palette flag): separated the temporary palette flag

---

Artsy/App/ARAppDelegate.m
Artsy/App/ARAppNotificationsDelegate.h
Artsy/App/ARAppNotificationsDelegate.m

Fixes an issue with our push notifications not deeplinking correctly, this was due to us implementing some new notification center delegate methods as part of the braze integration and as a result our old delegate methods were not getting called. Tested both braze push and a local push and both seem to be working now.
-
- Fix push notification deeplinking - Brian
-
-
</details>

fix: remove extra notification delegate handling

---

jest.config.js
package.json
src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
src/lib/Scenes/Home/__tests__/Home-tests.tsx
src/lib/Scenes/Inbox/Components/Conversations/__tests__/Composer-tests.tsx
src/lib/Scenes/MyProfile/__tests__/LoggedInUserInfo-tests.tsx
src/lib/Scenes/MyProfile/__tests__/MyProfilePushNotifications-tests.tsx
src/lib/Scenes/Onboarding/OnboardingCreateAccount/__tests__/OnboardingCreateAccount-tests.tsx
src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetails-tests.tsx
src/lib/Scenes/OrderHistory/__tests__/OrderHistory-tests.tsx
src/lib/Scenes/Sale/__tests__/Sale-tests.tsx
src/lib/Scenes/Search/__tests__/AutosuggestResults-tests.tsx
src/lib/Scenes/VanityURL/__tests__/VanityURLEntity-tests.tsx
src/lib/Scenes/VanityURL/__tests__/VanityURLPossibleRedirect-tests.tsx
src/lib/relay/middlewares/__tests__/metaphysicsMiddleware-tests.ts
src/lib/tests/fetchMockHelpers.ts
src/lib/tests/renderWithWrappers.tsx
src/lib/utils/__tests__/googleMaps-tests.ts
src/setupJest.ts
yarn.lock

- Added @testing-library/react-native
- Fixed problems with timers
- Fixed relay mockenvironment problems that were surfaced
Another thing that is worth mentioning here is that the version is one minor release behind the latest cause of [this issue](https://github.com/callstack/react-native-testing-library/issues/708) fixed in [this PR](https://github.com/callstack/react-native-testing-library/pull/697) but not yet released.
~~The problem at the moment is that 4 tests are failing more specifically:~~
1. ~~OrderDetails-tests.tsx~~
1. ~~RegistrationFlow-tests.tsx~~
1. ~~MyBids-tests.tsx~~
1. ~~Consignments/__tests__/index-tests.tsx~~
~~Reason: ~~
~~`Failed: "TypeError: Cannot read property '_responseForQueryIDWithVariables' of …

feat: Add @testing-library/react-native

---

src/lib/Scenes/AuctionResult/AuctionResult.tsx

This PR resolves [CX-1776]
This PR prevents the auction result screen from showing a `NoArtworkIcon` while the image size is being calculated. With this change, we just show the NoArtworkIcon when the auction result doesn't have an image.
- Don't show broken image when auction result screen loads - ole
-
-
-
</details>
[CX-1776]: https://artsyproduct.atlassian.net/browse/CX-1776

fix(CX-1776): Dont show broken image when auction result screen loads

---

src/lib/Scenes/SavedSearchAlert/Components/Form.tsx

This PR resolves an issue where we show the label for the saved filters as "1 filters" instead of "1 filter". I mislead you with my comment [here](https://github.com/artsy/eigen/pull/5202#discussion_r683480110) and I only noticed it today's morning 
- Fix pluralising applied filters
-
-
-
</details>

fix: filters count label

---

src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx
src/palette/elements/Button/Button.stories.tsx
src/palette/elements/Button/Button.tsx
src/palette/elements/Button/ButtonV2.stories.tsx
src/palette/elements/Button/ButtonV2.tsx
src/palette/elements/Button/index.tsx

Small PR to simplify the way Button works.
- Removed the `from` part from the animation, since it's not needed. `to` is enough, and it's reversed on untap.
- unexport some things that we don't use, like default variants etc.
- remove `textColor` from variants since it's not used. same for `size` for the `getSize` func.
- make the main `Button` wrapper accept v2 or v3 props, and try to guess the right ones and use that button.
To explain this a bit better:
- If the palette v3 flag is off, Button will point to v2, nothing to worry about.
- If flag is on, Button will point to v3. If it gets v3 props, it will use them. If it gets v2 props, it will convert them to v3 based on the mappings we have.
- If flag is on and we want to use a …

enhancement(button): easy to use v2 and v3 props

---

src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
src/lib/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx

This PR resolves [FX-3144]
* As a user,
* When I am creating or updating the name of a saved search
* I cannot save the form with over 75 characters in the name field
* Additional discussion of the [task implementation](https://artsy.slack.com/archives/C9SATFLUU/p1628689788332800)
* User cannot enter characters beyond the limit
* Without a counter of the entered characters (at the moment)
* If the name field is blank on-submit, auto populate it with a generated (placeholder) name (in grey) and continue with submission
https://user-images.githubusercontent.com/3513494/129060966-fca878b5-a1a7-4d12-9037-e991731db554.mp4
https://user-images.githubusercontent.com/3513494/129061032-fc6a4451-025e-459f-a5eb-4d4131046951.mp4 …

feat(FX-3144): saved search name input is limited to 75 characters

---

src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/AdditionalGeneIDsOptions-tests.tsx
src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx

The type of this PR is: enhancement 
This PR resolves [FX-3162]
Reorder artwork for sale filters to remain consistent with desired order.
- Reorder artwork for sale filters on artist screen for iOS and Android apps - rquartararo
-
-
-
</details>
[FX-2613]: https://artsyproduct.atlassian.net/browse/FX-2613
[FX-3162]: https://artsyproduct.atlassian.net/browse/FX-3162

feat: reorder artwork for sale filters on artist screen

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx

This PR resolves [FX-3190]
* Use the Saved Search M2 banner design for the M1 version
* This is necessary in order to see if it increases engagement to see the button visible before any filters are applied.
* For Android saved search banner, the old version of the banner will be displayed
* User lands on artist screen
* Sees “Create alert” button disabled/gray
* Apply filters
* User sees “Create alert” button tappable/black
* User can tap button to enable alert
* toast appears
* button updates to “Remove alert” (white outline)
* User can tap button again to disable alert
* toast appears
* button reverts to “Create alert”
https://user-images.githubusercontent.com/3513494/129233637-03953e86-dd4b-471c-b503-a4282ba7528c.mp4 …

feat(FX-3190): use saved search banner M2 design for M1

---

src/lib/Components/PhoneInput/PhoneInput.tsx
src/lib/store/config/features.ts

https://artsyproduct.atlassian.net/browse/PURCHASE-2886
From the mobile team weekly QA it was suggested to put this phone validation messaging behind a feature flag until the rest of the feature is fully built out as users can still save an invalid phone number.
cc @artsy/purchase-devs @MounirDhahri 
Without flag:
With flag:
- 
-
-
- Adds a feature flag to the PhoneInput component to toggle phone validation error messaging
</details>
[PURCHASE-2886]: https://artsyproduct.atlassian.net/browse/PURCHASE-2886

chore: adds feat flag to phone validation error msg

---

src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
src/__generated__/ArtistArtworksQuery.graphql.ts
src/__generated__/ArtistArtworks_artist.graphql.ts
src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Scenes/Artist/SearchCriteria.tsx
src/lib/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/__tests__/EditSavedSearchAlert-tests.tsx

This PR resolves [FX-3191]
* As an user with the saved search M2 feature flag enabled,
* After opening a edit saved search alert form
* And if I tap “view artworks“ button,
* I am taken to the artist screen
* And I see the artworks grid with the saved search filters applied
https://user-images.githubusercontent.com/3513494/129351066-0f220fd5-2100-451e-9028-b7a8251314ca.mp4
https://user-images.githubusercontent.com/3513494/129351096-f8577034-c3cc-43a2-bf23-dcae2c8a78e0.mp4
-  Add “View artworks” button for edit saved search alert screen - dzmitry tratsiak
-
-
-
</details>
[FX-3191]: https://artsyproduct.atlassian.net/browse/FX-3191

feat(FX-3191):  add “View artworks” button for edit saved search alert screen

---

src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/lib/Components/ArtworkFilter/Filters/__tests__/GalleriesAndInstitutionsOptions-tests.tsx

This PR resolves [FX-3196]
This PR standardises the use of ampersands in filter names, specifically changing "Galleries **and** Institutions" to "Galleries **&** Institutions"
- "Galleries and Institutions" filter renamed to "Galleries & Institutions" - rquartararo
-
-
</details>
###Screenshots
[FX-3196]: https://artsyproduct.atlassian.net/browse/FX-3196

chore: standardize ampersands in filter titles

---

src/__generated__/ShowArtworksInfiniteScrollGridQuery.graphql.ts
src/__generated__/ShowArtworksTestsQuery.graphql.ts
src/__generated__/ShowArtworks_show.graphql.ts
src/__generated__/ShowQuery.graphql.ts
src/__generated__/ShowTestsQuery.graphql.ts
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Scenes/Show/Components/ShowArtworks.tsx

This PR resolves [FX-3160]
Follow-up to https://github.com/artsy/eigen/pull/5250
The filter options were updated in a previous commit but these aggregations need to be updated as well.
- update aggregations for artworks on show screen to support artists filter - dblandin
-
-
-
</details>
[FX-3160]: https://artsyproduct.atlassian.net/browse/FX-3160

chore: update aggregations for show artworks

---

src/__generated__/ViewingRoomQuery.graphql.ts
src/__generated__/ViewingRoomTestsQuery.graphql.ts
src/__generated__/ViewingRoom_viewingRoom.graphql.ts
src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx

This came from https://artsy.slack.com/archives/C020VBMEJC8/p1629034697186700 and the message above.
It just feels wrong.
before
after
- remove viewing room artworks rail if 0 artworks - pavlos
-
-
-
</details>

fix(viewing room): dont show artwork rail if 0 artworks

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
src/lib/Scenes/SavedSearchAlert/__tests__/CreateSavedSearchAlert-tests.tsx
src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
src/lib/utils/track/schema.ts

This PR resolves [FX-3202]
* `tappedCreateAlert` → initial tap to record the interest/intent
* `editedSavedSearch` → when the edit action is performed
* `deletedSavedSearch` → when the delete action is performed
* `SavedSearchEdit` → User views a Saved Search Edit screen
* `SavedSearchList` → User views the Saved Search List view
Add support for the following events:
* `editedSavedSearch`
* `deletedSavedSearch`
* `tappedCreateAlert`
* `SavedSearchEdit`
* `SavedSearchList`
-
-
-
- Add analytics for saved search M2 - dzmitry tratsiak
</details>
[FX-3202]: https://artsyproduct.atlassian.net/browse/FX-3202

feat(FX-3202): add analytic events for saved search M2

---

src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts

Co-authored-by: George Kartalis <g.kartalis7@gmail.com>
This PR resolves [FX-2936] and [FX-3199]
This PR fixes the "All" showing up in the filter helpers and the incrementing issue when selected more than one Artist. Eg. when only one artist was selected the helper would show "Selected Artist, 1 more". 
Note: This was a quick fix, however the artwork filter helpers and filter selection logic does eventually need to be refactored as defined here: [FX-3205]
- The artwork filter helpers increment and "All" issue has been fixed -rquartararo 
-
-
-
</details>
[FX-2936]: https://artsyproduct.atlassian.net/browse/FX-2936
[FX-3199]: https://artsyproduct.atlassian.net/browse/FX-3199
[FX-3205]: …

fix: artwork filter helpers increment and "All" issue 

---

src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx

This PR resolves [FX-3214]
* When a user
* Clicks the "delete alert" button on the edit saved search page
* Delete modal should be displayed with the following params:
* title: Delete Alert
* description: Once deleted, you will no longer receive notifications for these filter criteria.
* buttons:
* Cancel - close modal
* Delete – must perform a deletion operation
https://user-images.githubusercontent.com/3513494/130479557-109998e5-0946-42ca-ba89-5e980071d297.mp4
https://user-images.githubusercontent.com/3513494/130483347-f2061103-0e1d-4ca7-9379-1329f8b3a52d.mp4
- Apply custom Dialog for confirm saved search delete - dzmitry tratsiak
-
-
-
</details>
[FX-3214]: …

feat(FX-3214): apply custom Dialog for confirm saved search delete

---

src/lib/Scenes/Sale/Sale.tsx

This is likely the wrong way to do this because it's not using Cohesion, but what I'm trying to match is this event in Force:
https://github.com/artsy/force/blob/master/src/lib/analytics/trackPageView.ts#L52
https://artsyproduct.atlassian.net/browse/GRO-363

feat: Track separate event for auction screen view GRO-363

---

src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx

As suggested by Devon [here](https://github.com/artsy/eigen/pull/5305#discussion_r693892850), I added tracking of the `savedSearches` event, when the user goes to the screen with a list of all saved searches
#nochangelog

feat: track OwnerType.savedSearches

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx

This PR resolves [FX-3210]
We’d like to hiding the "Create Alert" button until a filter has been applied, at which point the button would appear and be clickable.
https://user-images.githubusercontent.com/3513494/130491642-194f1618-3573-45c3-9c91-a84c8b2dc7e8.mp4
https://user-images.githubusercontent.com/3513494/130491664-52ec81a0-7e01-4201-bd73-5eb8b2f34f81.mp4
- Show the saved search button only when there are applied filters - dzmitry tratsiak
-
-
-
</details>
[FX-3210]: https://artsyproduct.atlassian.net/browse/FX-3210

feat(FX-3210): show SS only when applied filters

---

src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
src/lib/Scenes/SavedSearchAlert/__tests__/CreateSavedSearchAlert-tests.tsx
src/lib/Scenes/SavedSearchAlert/mutations/createSavedSearchAlert.ts
src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts

This PR resolves [FX-3235]
Track the `toggleSavedSearch` event when the user clicks the "create alert" button in the form of creating a new saved search alert
-
-
-
- Fix saved search m2 analytics to properly track alert creation - dzmitry tratsiak
</details>
[FX-3235]: https://artsyproduct.atlassian.net/browse/FX-3235

fix(FX-3235): track toggle saved search event

---

Artsy.xcodeproj/project.pbxproj
Podfile.lock

This PR resolves [CX-1854]
This PR ensures the frameworks added for attribution tracking with link status as required are not required when building on incompatible iOS versions
-
-
-
- Ensure Added Attribution and Ads Frameworks on iOS are not required when running incompatible target - kizito
</details>
[CX-1854]: https://artsyproduct.atlassian.net/browse/CX-1854

Bugfix(CX-1854): Ensure Added Attribution and Ads Frameworks on iOS are compatible with Eigen min deployment target

---

src/__generated__/Search2Query.graphql.ts
src/lib/Scenes/Search2/Search2.tsx
src/lib/Scenes/Search2/__tests__/Search2-tests.tsx

This PR resolves [FX-3226]
- adds __typename field to system query as a follow up on: https://github.com/artsy/metaphysics/pull/3374
- render dynamically pills from algolia indices that we get from metaphysics
- render dynamically pills from algolia indices that we get from metaphysics - gkartalis
-
-
-
</details>
[FX-3226]: https://artsyproduct.atlassian.net/browse/FX-3226

feat(FX-3226): add dynamic rendering of indices

---

src/lib/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx
src/lib/Components/ArtworkFilter/Filters/CategoriesOptions.tsx
src/lib/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx
src/lib/Components/ArtworkFilter/Filters/SizesOptions.tsx

This PR resolves [FX-3223]
PR contains an error fix when the previously selected auction house/medium filter values were not visually marked as selected
https://user-images.githubusercontent.com/3513494/131489683-00d6b514-333a-460c-886b-305e120aa79c.mp4
https://user-images.githubusercontent.com/3513494/131489124-58ec9968-41f6-436b-8f62-bb29f6a95a7d.mp4
- Correct logic for displaying the selected insight filters - dimatretyak
-
-
-
</details>
[FX-3223]: https://artsyproduct.atlassian.net/browse/FX-3223

fix(FX-3223): correct logic for displaying the selected insight filters

---

android/app/src/main/AndroidManifest.xml
src/__generated__/AuctionResultsForArtistsYouFollowContainerPaginationQuery.graphql.ts
src/__generated__/AuctionResultsForArtistsYouFollowContainerQuery.graphql.ts
src/__generated__/AuctionResultsForArtistsYouFollowTestsQuery.graphql.ts
src/__generated__/AuctionResultsForArtistsYouFollow_me.graphql.ts
src/lib/AppRegistry.tsx
src/lib/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx
src/lib/Scenes/AuctionResultsForArtistsYouFollow/__tests__/AuctionResultsForArtistsYouFollow-tests.tsx
src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
src/lib/Scenes/Home/Components/__tests__/AuctionResultsRail-tests.tsx
src/lib/navigation/routes.tsx

The type of this PR is: chore
This PR resolves [CX-1790]
Adds a skeleton loader for the Auction results by artists you follow screen.
Changes the name of the component from AuctionResultsForYou to AuctionResultsForArtistsYouFollow.
iOS
------------ | -------------
iPad
------------ | -------------
- Added a skeleton loader for the "Auction results by artists you follow" screen- Leandro L
-
-
- Changed name of the component AuctionResultsForYou to AuctionResultsForArtistsYouFollow- Leandro L
</details>
[CX-1790]: https://artsyproduct.atlassian.net/browse/CX-1790

chore(CX-1790): Add skeleton loader on Auction results by artists you follow

---

src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
src/lib/Components/ArtworkFilter/Filters/ArtistIDsArtworksOptions.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/ArtistIDsArtworksOptions-tests.tsx
src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx

This PR resolves [FX-3246], [FX-3275]
In the current implementation, each selected artist is stored as a separate filter entity, which complicates the readability of the code, its support, and so on. @iskounen [suggested](https://github.com/artsy/eigen/pull/5351#pullrequestreview-743174613) refactoring the artists filter to work as other multi-select filters do. 
```javascript
[
{
paramName: "artistIDs",
displayText: "Alex Katz, Alex Merritt, Amze Emmons",
paramValue: ["alex-katz", "alex-merritt", "amze-emmons"],
},
{
displayText: "All Artists I Follow",
paramName: "includeArtworksByFollowedArtists",
paramValue: true,
},
]
```
https://user-images.githubusercontent.com/3513494/131716377-6ff1bae8-a494-46c5-8e66-a2b9c2c771b0.mp4 …

refactor(FX-3246, FX-3275): keep `artistIDs` in one filter entity

---

Podfile.lock
src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/MultiSelectOption-tests.tsx

This PR resolves [FX-3255]
Previously, it was possible to select a filter option that was disabled (there were only visual changes). This bug is fixed in this PR and the user cannot click on the disabled element
https://user-images.githubusercontent.com/3513494/131998152-039b2811-1340-4791-be51-2ed6791091bf.mp4
https://user-images.githubusercontent.com/3513494/131997542-c9a215d0-7506-4e49-b6e1-1134f216b009.mp4
- Disabled filter options cannot clicked - dimatretyak
-
-
-
</details>
[FX-3255]: https://artsyproduct.atlassian.net/browse/FX-3255

fix(FX-3255): disabled options cannot clicked

---

src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
src/lib/Scenes/SavedSearchAlertsList/Components/__tests__/SavedSearchesList-tests.tsx

This PR resolves [FX-3274]
- Display fallback name for saved search alert without name - dimatretyak
-
-
-
</details>
[FX-3274]: https://artsyproduct.atlassian.net/browse/FX-3274

feat(FX-3274): fallback name for saved search alert without name

---

fastlane/Fastfile

- Explicitly pass aab path to firebase app distribution
- Explicitly pass artifact path to firebase app distribution - brian
-
-
-
</details>

fix: explicitly pass aab path #trivial

---

Podfile.lock
src/lib/Components/ArticleCard.tsx
src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
src/lib/Components/ArtworkTileRail/__tests__/ArtworkTileRailCard-tests.tsx
src/lib/Components/Lists/AuctionResultListItem.tsx
src/lib/Components/PageWithSimpleHeader.tsx
src/lib/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
src/lib/Components/SectionTitle.tsx
src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
src/lib/Scenes/Home/Components/FairsRail.tsx
src/lib/Scenes/Home/Components/SalesRail.tsx
src/lib/Scenes/Home/Home.tsx
src/palette/elements/Cards/MediumCard.tsx

This PR resolves [CX-1917]
This PR fixes the Palette V3 text and other minor issues in several places according to the Figma design:
**Changes:**
- Changes text sizes and weight in several rails and grids
- Moves auction result rail margin into separator component
- Aligns text and image for auction result items
- Adds bottom space to simple header component (back button is not overlapping anymore)
- Increases space between home screen modules.
| | | |
|---|---|---|
|![simulator_screenshot_3809DEED-7DD8-40FC-B802-03B84C048127](https://user-images.githubusercontent.com/4691889/132693510-32953b98-4b00-4b46-aa45-2dae53ab56b6.png) |  ![simulator_screenshot_3D3ED1CF-D600-4F97-A834-1EBBE848B332](https://user-images.githubusercontent.com/4691889/132693543-50dbd3 …

fix: Align Palette V3 text and other details with Figma design

---

src/lib/Components/PhoneInput/PhoneInput.tsx
src/lib/Components/PhoneInput/__tests__/PhoneInput-tests.tsx
src/lib/Scenes/MyAccount/MyAccountEditPhone.tsx
src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx

This PR resolves [PURCHASE-2911](https://artsyproduct.atlassian.net/browse/PURCHASE-2911)
This PR resolves [PURCHASE-2891](https://artsyproduct.atlassian.net/browse/PURCHASE-2891)
We already have phone validation error messaging from https://github.com/artsy/eigen/pull/5238, this PR enhances that work by disabling the submit button when a phone number is invalid. This behavior is intentionally omitted from the Phone Input field in the Consignments flow.
**When changing number in Collector Profile form**
**When changing number in Saved Addresses form**
**When changing number in Consignments form**
- Disable submitting form when numbers entered into Phone Input component are …

enhancement: disable form when submitting invalid phone number

---

src/lib/Scenes/Sale/Sale.tsx

This is a placeholder - please update with an awesome PR description!
https://artsyproduct.atlassian.net/browse/GRO-363
/cc @artsy/grow-devs @abhitip

fix: Use correct name of auction event GRO-363

---

src/__generated__/SearchArtworksGridQuery.graphql.ts
src/__generated__/SearchArtworksGridRefetchQuery.graphql.ts
src/__generated__/SearchArtworksGrid_artworks.graphql.ts
src/lib/Scenes/Search2/Search2.tsx
src/lib/Scenes/Search2/SearchArtworksGrid.tsx

This PR resolves [FX-3283]
This is the initial implementation including:
- showing the artwork pill (independed from algolia indices since we're getting the artworks from metaphysics)
- will add to the component keyword as input to filter through the artworks afterwards but this is why I added the refetch container.
> **note:** This is hidden behind a feature flag 
|Android|iOS|
|---|---|
|<img width="383" alt="Screenshot 2021-09-09 at 10 46 29" src="https://user-images.githubusercontent.com/21178754/132653990-39ddb48c-397a-4bf2-ace5-879465d14a11.png">|![Simulator Screen Shot - iPhone 8 - 2021-09-09 at 10 40 40](https://user-images.githubusercontent.com/21178754/132653254-3d6831b6-337d-4eb5-bdc4-ccec86be41b1.png)| …

feat: add artwork pill and show artwork grid when selected

---

src/lib/Scenes/Artwork/Components/CommercialEditionSetInformation.tsx
src/lib/Scenes/Artwork/Components/__tests__/CommercialEditionSetInformation-tests.tsx
src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx

This PR resolves [CX-1912]
Artworks with V3 Radiobutton to choose between multiple editions size.  
- Add V3 Radio button component for multiple edition artworks- rajsam003
-
-
-
</details>
[CX-1912]: https://artsyproduct.atlassian.net/browse/CX-1912

fix: Multiple edition works with Radiobutton V3

---

src/lib/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx

This PR resolves [CX-1918]
Aligns context grid CTA text with icon.
|Before |small font |normal font | big font |
|![Simulator Screen Shot - iPhone 12 mini - 2021-09-10 at 11 58 19](https://user-images.githubusercontent.com/4691889/132838162-45d4bbd0-d290-4351-ac21-4bc7a3758478.png) |![Simulator Screen Shot - iPhone 12 mini - 2021-09-10 at 12 04 44](https://user-images.githubusercontent.com/4691889/132838171-30a6b9e8-48ad-4736-96b6-983494c93670.png) |![Simulator Screen Shot - iPhone 12 mini - 2021-09-10 at 12 04 56](https://user-images.githubusercontent.com/4691889/132838181-b1a7ca81-8625-4191-ad26-1be1614789d2.png) |![Simulator Screen Shot - iPhone 12 mini - 2021-09-10 at 12 04 …

fix: Align context grid CTA text with icon

---

src/lib/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx

This PR resolves [CX-1922]
Adds padding between items on "Auction Results for Artists You Follow" screen.
-
-
-
-
</details>
[CX-1922]: https://artsyproduct.atlassian.net/browse/CX-1922

Add padding between items on auction results for you screen

---

.circleci/config.yml

Continued effort to fix circle android beta deploys, we had a couple failures after restricting memory limits related to output timeouts, extending the limit to see if it helps.
- 
-
-
- Extend circle no output timeout for android beta builds - brian
</details>

chore: extend no output timeout for android betas #trivial

---

src/lib/Scenes/MyAccount/MyAccountEditPhone.tsx

Puts canSave check behind phone validation feature flag so users can save numbers with feature flag disabled.
- Put phone canSave check behind feature flag - brian
-
-
-
</details>

fix: put phone validation behind feature flag

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/Components/ArtworkFilter/useArtworkFilters.ts
src/lib/Components/Gene/GeneArtworks.tsx
src/lib/Components/Tag/TagArtworks.tsx
src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
src/lib/Scenes/Fair/Components/FairArtworks.tsx
src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
src/lib/Scenes/Sale/Components/SaleLotsList.tsx
src/lib/Scenes/Show/Components/ShowArtworks.tsx

This PR resolves [FX-3288]
In the current implementation, each artworks page (except partner page) duplicates logic of remembering aggregations on first request and refetching data
Instead of
```
useEffect(() => {
setAggregationsAction(artworks?.aggregations)
}, [])
useEffect(() => {
if (relay !== undefined && applyFilters) {
relay.refetchConnection(
10,
(error) => {
if (error) {
throw new Error("ArtistSeries/ArtistSeriesArtworks filter error: " + error.message)
}
},
{ input: prepareFilterArtworksParamsForInput(filterParams) }
)
}
}, [appliedFilters])
```
in each artworks page component we can (in most cases) use
```
useArtworkFilters({
relay,
aggregations: artworks?.aggregations,
componentPath: "ArtistSeries/ArtistSeriesArtworks",
pageSize: 10,
})
``` …

refactor(FX-3288): Refactor useArtworkFilters and use it on artwork pages

---

src/lib/Components/ArtworkFilter/Filters/ArtistIDsSaleArtworksOptionsScreen.tsx
src/lib/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx

The type of this PR is: **Bugfix, Refactor**
This PR resolves [FX-3254]
* As a user
* When I navigate to the auction page
* And click the “sort & filter“ button
* And select some values in the artists filter
* And click on the “show results“ button
* And click the “sort & filter“ button again
* And change some values in the artists filter
* Then you will see the strange behavior of the artists filter
https://user-images.githubusercontent.com/3513494/132230644-9e747cc1-5ed5-41a5-aac3-64405fd2625f.mp4
https://user-images.githubusercontent.com/3513494/132232195-45840470-4039-41a1-8e8a-cada2f751d02.mp4
- Selected values of the artists filter are displayed correctly on the auction page - dimatretyak
-
-
-
</details>
[FX-3254]: …

fix(FX-3254): Artists filter displays wrong selections on the auction page

---

src/lib/Components/ArtworkFilter/useArtworkFilters.ts

Refetch was executed every time the component was re-rendered, since `filterParams` had a new reference type each time
-
-
-
- refetch artworks only when applying new filters – dimatretyak
</details>

fix: refetch only when applying new filters

---

src/lib/Components/Artist/ArtistHeader.tsx
src/lib/Components/ArtistListItem.tsx
src/lib/Components/Gene/Header.tsx
src/lib/Components/Home/ArtistRails/ArtistCard.tsx
src/lib/Scenes/Artwork/Components/ContextCard.tsx
src/lib/Scenes/Artwork/Components/PartnerCard.tsx
src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx

This PR resolves [CX-1939]
Use optimistic response for all follow buttons and don't show a loading spinner anymore.
**Screens/Components:**
- Artist Screen Header
- Artist List Item Component
- Gene Screen Header
- Artist Rail Component
- Artwork Context Card Component
- Partner Card Component
- Partner Screen
| Succeeding | Not Succeeding |
| --- | --- |
| <video src="https://user-images.githubusercontent.com/4691889/133433484-efaef5e8-fc4d-40ee-8b80-cf47fa392721.mp4"/> | <video src="https://user-images.githubusercontent.com/4691889/133433602-48ba431e-87f7-459f-83ad-7dcde81ea9e5.mp4"/> |
- Use optimistic response instead of loading spinner for all follow buttons - ole
-
-
-
</details>
[CX-1939]: …

feat: Use optimistic response for all follow buttons

---

src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlert/__tests__/EditSavedSearchAlert-tests.tsx

This PR resolves [FX-3257]
If user deletes an alert and then comes back to artist page with the same filters applied, "Create Alert" button is disabled, the alert doesn't exist anymore though.
This fixes current behavior via emitting `refetch` event after editing an alert and refetching fresh data on this event
**Before**
**After**
- Enable "Create Alert" button if alert doesn't exist - anastasiapyzhik
-
-
-
</details>
[FX-3257]: https://artsyproduct.atlassian.net/browse/FX-3257

fix(FX-3257): Enable "Create Alert" button after deleting an alert

---

src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx

This PR resolves [CX-1907]
Adds horizontal padding to the auction confirmation step bottom text.
**Palette V3**
| --- | --- | 
| ![Simulator Screen Shot - iPhone 8 - 2021-09-09 at 15 55 37](https://user-images.githubusercontent.com/4691889/132701281-3ebd3d8a-e077-49d2-ba3d-efa2c7a651e2.png) |  ![Simulator Screen Shot - iPhone 8 - 2021-09-09 at 16 06 31](https://user-images.githubusercontent.com/4691889/132701209-2c50dc96-5b41-45da-bd04-2acf50645443.png) |
**Palette V2**
| --- | --- | 
| ![Simulator Screen Shot - iPhone 8 - 2021-09-10 at 08 58 08](https://user-images.githubusercontent.com/4691889/132813123-657cece0-688c-489c-aec0-6526c6d4ed76.png) |  ![Simulator Screen Shot - iPhone 8 - 2021-09-10 at 08 58 …

fix: Add horizontal padding to auciton confirmation step bottom text

---

src/lib/Scenes/Search2/Search2.tsx
src/lib/Scenes/Search2/__tests__/SearchPills-tests.tsx
src/lib/Scenes/Search2/components/SearchPills.tsx
src/lib/Scenes/Search2/types.ts

The type of this PR is: **Refactor, Chore**
This PR resolves [FX-3322]
https://user-images.githubusercontent.com/3513494/133794596-c0524f4c-914d-4d8a-8f91-d856451b598f.mp4
-
-
-
- Split search pill into separated component - dimatretyak
</details>
[FX-3322]: https://artsyproduct.atlassian.net/browse/FX-3322

chore(FX-3322): split search pills into separated component

---

src/palette/elements/Tabs/ContentTabs.tsx
src/palette/elements/Tabs/NavigationalTabs.tsx
src/palette/elements/Tabs/StepTabs.tsx

This PR resolves [CX-1943]
https://user-images.githubusercontent.com/18648835/133807751-e018e722-2078-4ee6-bc75-087b2e51d135.mp4
- Fix Navigational Tabs width update on Tablets when device is rotated - kizito
-
-
-
</details>
[CX-1943]: https://artsyproduct.atlassian.net/browse/CX-1943

Bugfix(CX-1943): Fix Navigational Tabs width update on Tablets when device is rotated

---

src/lib/Scenes/Search2/Search2.tsx
src/lib/Scenes/Search2/__tests__/Search2-tests.tsx

This PR resolves [FX-3321]
Add debounce to reduce requests
**Before:**
https://user-images.githubusercontent.com/21178754/133793806-109861ca-e173-41a8-bb6f-e5fb2f873e16.mov
**After:**
https://user-images.githubusercontent.com/21178754/133793900-ba882081-2066-464f-b084-68968a8beb43.mov
-
-
-
- add debounce to reduce requests on improved search - gkartalis
</details>
[FX-3321]: https://artsyproduct.atlassian.net/browse/FX-3321

feat(FX-3321): add debounce to onchangetext requests in improved search

---

src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
src/lib/Scenes/Home/Components/SaleArtworksHomeRail.tsx
src/lib/Scenes/Home/Components/SalesRail.tsx
src/lib/Scenes/Home/Components/__tests__/SalesRail-tests.tsx
src/lib/Scenes/Home/Home.tsx

This PR resolves [CX-1929]
This PR fixes the spacing issues between rails on the home page, specifically when a new user does not have all of the rails yet.  
Note: make a new account to test. 
- Spacing issues between home page rails is fixed - rquartararo
-
-
-
</details>
https://user-images.githubusercontent.com/50849237/133589242-1ddc6c02-0afc-4838-8151-e38f8d443372.mp4
[CX-1929]: https://artsyproduct.atlassian.net/browse/CX-1929

fix(CX-1929): home page spacing fix

---

src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/ArtistAutosuggest.tsx
src/lib/Scenes/Search/AutosuggestResults.tsx
src/lib/Scenes/Search/Search.tsx
src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx

This PR resolves [CX-1717]
Removes quick nav buttons from artist autocomplete in my collection. 
**My Collection**:
**Main search**:
</details>
-
- Remove quick nav links from my collection autosuggest - Brian
-
-
</details>
[CX-1717]: https://artsyproduct.atlassian.net/browse/CX-1717

fix: remove search quick links

---

src/lib/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
src/lib/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/PriceRangeOptions-tests.tsx

This PR resolves [FX-3302]
* More context you can find in [Slack](https://artsy.slack.com/archives/C9SATFLUU/p1631633628141600)
* Figma [design](https://www.figma.com/file/zG9cduJdOaTQAw886QcOwn/Filters?node-id=3114%3A31607)
https://user-images.githubusercontent.com/3513494/133614212-e8bab4a4-4b2d-4981-85b9-f861c67611b5.mp4
https://user-images.githubusercontent.com/3513494/133616295-1c7abfc6-03a4-4c2c-97f9-5125deac109c.mp4
- Move custom price filter to top and default expand - dimatretyak
-
-
-
</details>
[FX-3302]: https://artsyproduct.atlassian.net/browse/FX-3302

feat(FX-3302): Move custom price filter to top and default expand

---

src/lib/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
src/lib/Components/ArtworkFilter/Filters/__tests__/SizeOptions-tests.tsx

This PR resolves [FX-3278]
* Populate the custom size filter only when we have at least one filled input
* Shouldn't let the user press `Show Results` button unless the custom height and width is specified
https://user-images.githubusercontent.com/3513494/134040129-f88fdbc7-3b6d-4fa2-880b-b7084a501a25.mp4
https://user-images.githubusercontent.com/3513494/134044392-10ef1d78-a846-484a-9c1e-9e4bd5623af4.mp4
-
-
-
- Fix custom size filter behaviour - dimatretyak
</details>
[FX-3278]: https://artsyproduct.atlassian.net/browse/FX-3278

fix(FX-3278): Artworks Size filters custom size doesn't behave as expected

---

src/__generated__/OrderDetailsQuery.graphql.ts
src/__generated__/OrderDetailsTestsQuery.graphql.ts
src/__generated__/OrderDetails_order.graphql.ts
src/__generated__/TrackOrderSectionTestsQuery.graphql.ts
src/__generated__/TrackOrderSection_section.graphql.ts
src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
src/lib/Scenes/OrderHistory/OrderDetails/Components/TrackOrderSection.tsx
src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetails-tests.tsx
src/lib/Scenes/OrderHistory/OrderDetails/__tests__/TrackOrderSection-tests.tsx
src/lib/utils/getTrackingUrl.ts

Design 🎨  : [Figma](https://www.figma.com/file/J5bIQj4a0l7wYAHnhbVGTp/%5BCollector%5D-Checkout-Shipping?node-id=2826%3A0) 
This PR resolves [PX-4210]
This PR is adding a new `TrackOrderSection` to the OrderDetails page and allows users to see tracking and timing info about their order. Also, this PR returns correct bold text for sections titles.
We need to doublecheck backend fields for `Shipped on`, `Estimated Delivery` and `Delivered on` fields in this section. So please, correct this if it's wrong and let me know:point_down:
1. If CommerceShip:
- Shipped on -> `createdAt` on `CommerceFulfillment`
- Estimated Delivery -> `estimatedDelivery` on `CommerceFulfillment`
- if status "delivered" then `Delivered on` -> :question::question::question: on …

feat: Order detail: User can see more shipping info for their order [PX-4210]

---

src/lib/Scenes/SavedSearchAlert/__tests__/helpers-tests.ts
src/lib/Scenes/SavedSearchAlert/helpers.ts

This PR resolves [FX-3325]
More context you can find in [Slack](https://artsy.slack.com/archives/C9SATFLUU/p1632216208334400)
* Values
* minimum width `5`
* minimum height `10`
* maximum height `15`
* Labels
* `w: from 5 in` or `w: from 5 cm`
* `h: 10-15 in` or `h: 10-15 cm`
* Values
* minimum width `5`
* maximum width `10`
* minimum height `15`
* maximum height `20`
* Label
* `w: 5-10 in` or `w: 5-10 cm`
* `h: 15-20 in` or `h: 15-20 cm`
* Values
* minimum width `5`
* minimum height `15`
* Label
* `w: from 5 in` or `w: from 5 cm`
* `h: from 15 in` or `h: from 15 cm`
* Values
* maximum width `5`
* maximum height `15`
* Label
* `w: to 5 in` or `w: to 5 cm`
* `h: to 15 in` or `h: to 15 cm`
https://user-images.githubusercontent.com/3513494/134199053-8fb78eb6 …

feat(FX-3325): Update the display of size filter labels for saved search M2

---

src/lib/Scenes/Search2/Search2.tsx
src/lib/Scenes/Search2/__tests__/Search2-tests.tsx

This PR resolves [FX-3326]
When the user clicks on the "search" button, we need to make the artwork tablet active and show the search results for this pill
https://user-images.githubusercontent.com/3513494/134339894-0ef07bf3-5af4-4f04-87c4-3a9fb430e86e.mp4
https://user-images.githubusercontent.com/3513494/134340822-1fdd46d8-8e02-406f-bdb4-0dc7ef22b180.mp4
- Select artworks pill when search button is clicked - dimatretyak
-
-
-
</details>
[FX-3326]: https://artsyproduct.atlassian.net/browse/FX-3326

feat(FX-3326): select artworks pill when search button is clicked

---

src/lib/Scenes/Search/RecentSearches.tsx
src/lib/Scenes/Search/__tests__/RecentSearches-tests.tsx
src/lib/Scenes/Search2/__tests__/Search2-tests.tsx

This PR resolves [FX-3331]
| Before  | Current |
| ![image](https://user-images.githubusercontent.com/56556580/134671646-0990c396-3936-4433-acfa-c9c8cd3358f4.png) | ![image](https://user-images.githubusercontent.com/56556580/134670185-8f20fc25-0208-415e-9d97-f9f0d92c4694.png)
- make "Recent searches" title case
</details>
[FX-3331]: https://artsyproduct.atlassian.net/browse/FX-3331

feat(FX-3331): make recent searches title case

---

src/__generated__/OrderDetailsQuery.graphql.ts
src/__generated__/OrderDetailsTestsQuery.graphql.ts
src/__generated__/SummarySectionTestsQuery.graphql.ts
src/__generated__/SummarySection_section.graphql.ts
src/lib/Scenes/OrderHistory/OrderDetails/Components/SummarySection.tsx
src/lib/Scenes/OrderHistory/__tests__/SummarySection-tests.tsx

This PR resolves [PX-4579]
This PR fixes pricing for offer orders. Added last offer and list price values.
- Added last offer and list price on order details page - kirill-zubarau
</details>
[PX-4579]: https://artsyproduct.atlassian.net/browse/PX-4579

fix(PX-4579): show last offer on offer orders page

---

src/__generated__/OrderHistoryPaginationQuery.graphql.ts
src/__generated__/OrderHistoryQuery.graphql.ts
src/__generated__/OrderHistoryRowTestsQuery.graphql.ts
src/__generated__/OrderHistoryRow_order.graphql.ts
src/__generated__/OrderHistoryTestsQuery.graphql.ts
src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
src/lib/Scenes/OrderHistory/__tests__/OrderHistoryRow-tests.tsx

This PR resolves [PX-4577]
This PR allows changing the `button title` depending on the `order mode` if state is `SUBMITTED`.
❓  Maybe we should also need to change the title of the `OrderDetails` page?
- Order History: added "View Offer" title if the order is made as "Make offer"
-
-
-
</details>
https://user-images.githubusercontent.com/55637696/134636373-779ed495-9c56-44a3-aa1a-159f10973448.mov
[PX-4577]: https://artsyproduct.atlassian.net/browse/PX-4577

feat: Order History: rename button "View Order" if order is made as "Make offer" [PX-4577]

---

src/palette/elements/Button/Button.tsx

This PR resolves [CX-1974]
We renamed text props from size -> variant as part of paletteV3 migration, missed one spot in Button component which was leading to the issues we were seeing. 
</details>
<details>
<summary>After</summary>
</details>
- Fix text cutoff in small buttons - brian
-
-
-
</details>
[CX-1974]: https://artsyproduct.atlassian.net/browse/CX-1974

fix: rename prop for button animated text

---

src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx

This PR resolves [CX-1975]
Adds a top and bottom spacer to auction results in My Collection. 
</details>
</details>
-
- fix spacing in my collection auction results - Brian
-
-
</details>
[CX-1975]: https://artsyproduct.atlassian.net/browse/CX-1975

fix: give my collection auction results some space #trivial

---

src/lib/Scenes/MyCollection/MyCollection.tsx
src/lib/Scenes/MyProfile/MyProfile.tsx

This PR resolves [CX-1977]
This PR ensures that when MyCollection feature flag is enabled the old MyProfile loading skeleton is not momentarily displayed. And vice-versa.
https://user-images.githubusercontent.com/18648835/134907422-f5f26b62-1877-4a6c-9435-f280b83dfef9.mp4
- sync MyCollection and old MyProfile loading skeletons - kizito
-
-
-
</details>
[CX-1977]: https://artsyproduct.atlassian.net/browse/CX-1977

Bugfix(CX-1977): sync MyCollection and old MyProfile loading skeletons

---

src/lib/Components/Input/Input.tsx
src/lib/Components/SearchInput.tsx
src/lib/Scenes/Search2/Search2.tsx
src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
src/lib/Scenes/Search2/__tests__/SearchPills-tests.tsx
src/lib/Scenes/Search2/types.ts
src/lib/utils/useAlgoliaClient.ts

The type of this PR is: **Refactor**, **Feature**
This PR resolves [FX-3327], [FX-3330]
* As a user when I 
* delete my search term 
* press `x` input button 
* press `cancel` button
* I want to be able to start a search from scratch without any pill selected. 
```javascript
{
type: "elastic" | "algolia",
displayName: string,
name: string
}
```
https://user-images.githubusercontent.com/3513494/134516874-340a67b2-7b45-4363-970e-50b4b29e42c8.mp4
https://user-images.githubusercontent.com/3513494/134525365-85ad5e1a-8c57-4c76-b118-bd0e73654fc5.mp4
- Reset the state of the pills when the search query is cleared/empty - dimatretyak
-
-
- Keep selected search pill as one entity - dimatretyak
</details>
[FX-3327]: …

feat(FX-3327, FX-3330): Keep selected pill as one entity, Reset the state of the search pills

---

src/lib/Components/ArtsyReactWebView.tsx
src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx

This PR resolves [CX-1986]
- Fix issue on market news where users are unable to share articles
- Add test to avoid the same future regression
https://user-images.githubusercontent.com/11945712/135044554-237c64a0-1792-4943-a96b-e4e5911532f2.mov
- Fix unable to share article on market news
-
-
- 
</details>
[CX-1986]: https://artsyproduct.atlassian.net/browse/CX-1986

fix(1986): unable to share articles

---

src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
src/lib/Scenes/Search2/SearchArtworksGrid.tsx

This PR resolves [FX-3227]
This work is behind a feature flag.
- introduced `ArtworkFilterMode.Search`
- ArtworkFilterNavigator can take null as id and slug since this artworks grid is standalone and not a subset of artworks of a specific artist, gallery, show etc
- you can find more info about `the why null` [here](https://artsy.slack.com/archives/C0KEQD4B0/p1632735287184400)
-
-
-
- add analytics for searchArtworksGrid filtering - gkartalis
</details>
[FX-3227]: https://artsyproduct.atlassian.net/browse/FX-3227

feat(FX-3227): Add analytics for searchartworksgrid filters

---

src/lib/Scenes/Home/Components/CollectionsRail.tsx
src/lib/Scenes/Home/Home.tsx

This PR resolves the following error message that occurs when you scroll down in the home screen
We are updating the Flatlist props before we render the item and that was causing us an unharmful error that we better fix.
- 
-
-
- fix update state during transition warning - mounir
</details>

fix: remove update state during transition warning

---

src/lib/Scenes/Search2/Search2.tsx
src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
src/lib/Scenes/Search2/components/SearchPills.tsx
src/lib/Scenes/Search2/types.ts
src/palette/elements/Pill/Pill.stories.tsx
src/palette/elements/Pill/Pill.tsx
src/palette/elements/Pill/__tests__/Pill-tests.tsx

This PR resolves [FX-3335]
* The top pill is selected by default
* We can’t untoggle pill, we can only select another one
* We should show the multi-index search (`AutosuggestResults` component) if the query has changed by 1 character (for example, from ab to abc)
* When the user presses the `search` keyboard button, then we need to make the top pill active
* More context you can find in [Slack](https://artsy.slack.com/archives/C9SATFLUU/p1632748608053900)
https://user-images.githubusercontent.com/3513494/135077960-b93d5adc-aaba-4050-a62e-14e101e262d3.mp4
https://user-images.githubusercontent.com/3513494/135078587-688deb96-e30f-4f84-af20-1c87c7665b01.mp4
- Prevent search pill untoggle, show the multi-index …

feat(FX-3335): prevent pill untoggle

---

src/lib/Scenes/Search2/SearchResults.tsx

https://user-images.githubusercontent.com/3513494/135088299-bed8c470-c30f-4379-9899-7be092f78cad.mp4
-
-
- Correct scroll to top of search list for android - dimatretyak
-
</details>

fix: correct scroll to top of search list for android

---

dangerfile.ts
src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
src/lib/tests/renderWithWrappers.tsx

After a great suggestion from @gkartalis to officially deprecate test-renderer, same as enzyme, we made this PR. It can still be used, but danger will nudge us when new files use it, same as enzyme.
-
-
-
- deprecate test-renderer for tests, in favor of testing-library - george, pavlos
</details>

refactor(tests): deprecate test-renderer in favor of testing-library

---

src/lib/Components/WorksForYou/__tests__/Notification-tests.tsx

#nochangelog
-
-
-
-
</details>

fix(test): unfocus random focused test

---

src/lib/Scenes/Consignments/ConsignmentsHome/ConsignmentsHome.tsx
src/lib/Scenes/Home/Home.tsx
src/lib/Scenes/MyProfile/MyProfile.tsx
src/lib/navigation/navigate.ts

This PR resolves [CX-303]
Fixes issue causing screen views in our main tabs to only be fired the first time a tab is tapped.
The issue is that our screen tracking by default happens when the screen component mounts. For most screens this is okay but our tabs are lazily mounted so they are not triggering the event on subsequent taps. This pr just removes the typical screen tracking from our tab screens and instead fires the event in the switchTab function. 
https://user-images.githubusercontent.com/49686530/135333768-d1f9c694-fdae-4903-94cf-c7845f263e97.mp4
https://user-images.githubusercontent.com/49686530/135333777-a9e68efa-e944-42cb-aec6-c67b5f953f04.mp4
- Fix tab screen tracking - Brian
-
-
-
</details> …

fix: fix tab screen tracking only on first tap

---

patches/react-native-credit-card-input+0.4.1.patch

This PR resolves [CX-1938]
This PR patches react-native-credit-card-input's LiteCreditCardInput component to have it look like Palette V3 input. 
<div>
</div>
<div>
</div>
The user-facing credit card input is updated for both IOS and Android. 
</details>
[CX-1938]: https://artsyproduct.atlassian.net/browse/CX-1938

Enhancement: [CX-1938] Patch react-native-credit-card-input

---

src/lib/Scenes/MyBids/Components/ActiveLotStanding.tsx
src/lib/Scenes/MyBids/Components/ClosedLotStanding.tsx
src/lib/Scenes/MyBids/Components/Lot.tsx
src/lib/Scenes/MyBids/Components/WatchedLot.tsx
src/lib/Scenes/Sale/Components/SaleActiveBidItem.tsx

This PR resolves [PURCHASE-2833]
This PR resolves the overlapping artist and bid price text on the lot statuses when the artist name and/or bid price is too long. 
**New behaviour**: If the artist name is very long, it will move to the next line, and if it exceeds the second line it will ellipsis. I did this by refactoring the flexboxes. 
- Lot status text no longer overlaps when text is too long -rquartararo
-
-
-
</details>
[PURCHASE-2833]: https://artsyproduct.atlassian.net/browse/PURCHASE-2833

fix(PURCHASE-2833): overlapping text on lot statuses

---

src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx

This PR resolves [FX-3278]
https://user-images.githubusercontent.com/3513494/135315790-96be0ce3-1364-4e06-8744-0b85aa72857a.mp4
https://user-images.githubusercontent.com/3513494/135315655-c96a8544-50e9-428c-a4c3-13ee3993c451.mp4
-
-
-
- keep the "show alerts" button disabled when the user selects the custom price again - dimatretyak
</details>
[FX-3278]: https://artsyproduct.atlassian.net/browse/FX-3278

fix(FX-3278): keep the "show alerts" button disabled when the user selects the same custom price again

---

CHANGELOG.legacy.yml
Podfile.lock
src/__generated__/SavedAddressesFormQuery.graphql.ts
src/__generated__/SavedAddressesFormTestsQuery.graphql.ts
src/__generated__/SavedAddressesForm_me.graphql.ts
src/lib/Components/PhoneInput/PhoneInput.tsx
src/lib/Scenes/Consignments/Screens/__tests__/ConfirmContactInfo-tests.tsx
src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx

The type of this PR is: BUGFIX
[PURCHASE-2898]
Paired with @copperkraft 
When editing an address, the phone input is always empty and with the incorrect country code, even if there’s an existing phone number. So, saving, even if there were no changes, overrides the existing one with an empty one.
- fix populating phone number on editing saving adress - lilyfromseattle
-
-
-
</details>
[PURCHASE-2898]: https://artsyproduct.atlassian.net/browse/PURCHASE-2898

Fix: Phone number doesn't populate field on edit

---

src/lib/Scenes/Search2/SearchArtworksGrid.tsx

This PR resolves [FX-3324]
This is a follow-up fix from https://github.com/artsy/eigen/pull/5533.
-
-
-
- fix broken analytics on searchable artwork grid - gkartalis
</details>
[FX-3324]: https://artsyproduct.atlassian.net/browse/FX-3324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-3324): broken analytics on artworks grid

---

src/lib/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tsx

This PR resolves [PURCHASE-2670](https://artsyproduct.atlassian.net/browse/PURCHASE-2670)
The CMS doesn't allow Artworks without `date` but I can't guarantee that behavior from old data, in order to fix the extra comma we do some checks before displaying it.
iOS
Android
- When date is null or "" don't display ", " in the Make Offer Modal
-
-
-
</details>

fix(PURCHASE-2670): Don't show the date is not present

---

src/lib/Components/SearchInput.tsx

This PR resolves [CX-2122]
The error happening before was caused by a typecast assuring the ref was present and wrongly typecasting it to `RefObject<T>` when the real type is `Ref<T>` and the latter doesn't expose any methods.
This PR addresses an error when calling forwarded refs methods, like focus, blur, these values are not present if you omit the ref from the place you're using the component causing the issue described in Sentry when you for example tap in the clear button of the SearchInput of the onboarding flow.
When we need to call exposed functions from forwarded refs the recommended pattern is to use `useImperativeHandle` to use, focus, blur, etc.
https://user-images.githubusercontent.com/15792853/139397144-dc974371-0529-4fcc-a4e9-198a3abfb63c. …

fix(CX-2122): fix broken ref handling

---

src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
src/__generated__/AutosuggestResultsPaginationQuery.graphql.ts
src/__generated__/AutosuggestResultsQuery.graphql.ts
src/__generated__/AutosuggestResults_results.graphql.ts
src/lib/Scenes/Artist/Artist.tests.tsx
src/lib/Scenes/Artist/Artist.tsx
src/lib/Scenes/Search/AutosuggestResults.tsx
src/lib/Scenes/Search/AutosuggestSearchResult.tsx
src/lib/Scenes/Search/AutosuggestedSearchResult.tests.tsx

This PR resolves [CX-2087]
Use `ArtistStatuses` interface to tell if an artist has artworks, articles or auction results instead of counts
This PR comes us a follow-up on some performance issues we had related to rendering the auction results button and that was resulting in diffusion breaking and returning to high latencies and some screens breaking in Eigen
-
-
-
- improve logic of showing auction results by using isDisplayAuctionLink - mounir
</details>
[CX-2087]: https://artsyproduct.atlassian.net/browse/CX-2087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2087): improve logic of showing auction results

---

src/lib/Components/ArtworkGrids/FilterHeader2.tests.tsx
src/lib/Components/ArtworkGrids/FilterHeader2.tsx
src/lib/Scenes/Search2/SearchArtworksGrid.tsx

This PR resolves [FX-3523]
This pr changes the label of the Filter Button under SearchableArtworkGrid from `Sort & Filter` to `Filter` since we don't provide a sorting functionality on artwork grids with keyword search yet.
- Add title optional prop to `FilterHeader2` component that resolves to "Sort & Filter" when not passed
- Pass title = "Filter" when on Searchable Artwork Grid under mobile search
more context here [slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1635781485373200)
|Before|After|
|---|---|
|![simulator_screenshot_B09A9E0A-2239-4E16-A6CF-46E12F772FBF](https://user-images.githubusercontent.com/21178754/139709749-e5f66750-e119-47fd-a541-cf992d393fed.png)|![Simulator Screen Shot - iPhone 8 - 2021-11-01 at 17 52 …

chore(FX-3523): copy change filter on searchableartworkgrid

---

src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Scenes/Search2/SearchArtworksGrid.tests.tsx
src/lib/Scenes/Search2/SearchArtworksGrid.tsx
src/lib/store/config/features.ts

This PR resolves [FX-3526]
⚠️ Changes behind a feature flag
* As a user
* When I open the improved search screen
* And when the feature flag is enabled
* And when I press the "sort & filter" button on the artworks pill
* I see the Sort By option and I can specify a sort filter
* Changes are available under the feature flag
* if feature flag is **enabled**, display **Sort & Filter** label
* if feature flag is **disabled**, display **Filter** label
* Changes should be behind a feature flag
* [Slack](https://artsy.slack.com/archives/C9SATFLUU/p1635860066395500)
https://user-images.githubusercontent.com/3513494/139913321-74d8425e-f388-4bb9-b851-b57b5a6ca84d.mp4
https://user-images.githubusercontent.com/3513494/139913352-c0fc8ab1-5476-440d-8af7-f456d7b4fd3a.m …

feat(FX-3526): enable the Sort By option for the Artworks pill when feature flag is enabled

---

src/palette/elements/Input/Input.stories.tsx
src/palette/elements/Input/Input.tsx

This PR resolves [[Slack discussion](https://artsy.slack.com/archives/C01B2P6LJUU/p1635959068347300)]
This PR is a bug fix for the displayed limit of the Input components with props `maxLength`. t's a follow up of #5699
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/140291860-d2ed9c33-ee2e-45c8-881c-927539863f2b.png)|![image](https://user-images.githubusercontent.com/17421923/140291721-4579aec3-3f18-423c-a2d9-4b9e046d7dae.png)|
- Limit will not show for the Input components unless `showLimit` prop is passed - sam
-
-
-
</details>

fix: Input with limit

---

Artsy/App/ARAppActivityContinuationDelegate.m

After lots of trial and error @brainbicycle and I were able to figure out that we need to convert the Adjust universal links to match our quirky schema. What you see here does that conversion: either the link is not an Adjust link and we skip to the else branch or it is and Adjust link and we do some converting.
We tested this via the simulator and commands like this:
```
$ xcrun simctl openurl booted "https://wvxa.adj.st/artwork/ray-parker-number-6?adj_t=n4sw6qk&adj_campaign=best-campaign&adj_adgroup=awesome-group&adj_creative=super-creative&adj_label=jon-test"
$ xcrun simctl openurl booted "https://www.artsy.net/artist/kaws"
```
https://artsyproduct.atlassian.net/browse/GRO-419

feat: Convert Adjust universal links GRO-419

---

src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/Search/Search.tests.tsx
src/lib/Scenes/Search/Search.tsx
src/lib/Scenes/Search/components/SearchPills.tests.tsx
src/lib/Scenes/Search/components/SearchPills.tsx
src/lib/Scenes/Search/types.ts
src/lib/utils/useAlgoliaIndices.ts
src/palette/elements/Pill/Pill.stories.tsx
src/palette/elements/Pill/Pill.tsx

This PR resolves [FX-3521]
It was decided to disable search pills of categories with no results instead of hiding them because we need to avoid user to land on screen and see _no results_ state and flickering pills might be a bad UX. So now pill will be disabled if i has no results or if the query for the information about all pills state is pending.
https://user-images.githubusercontent.com/44819355/140509440-48c998bb-284e-4439-9214-0438df87262e.mp4
Along with that this PR updates Pill view across the app, adds 2 states: active and disabled.
Changes are available with `AREnableImprovedSearchPills` flag enabled
- add disabled and active states to pill - anastasiapyzhik
- disable search pills when loading and …

feat(FX-3521): Disable search pills

---

src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tests.tsx

-
-
-
- failed test for OnboardingPersonalization - dimatretyak
</details>

fix: failed test for OnboardingPersonalization

---

src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
src/palette/elements/Checkbox/Check.tsx

This PR resolves [FX-3587]
When I get on artworks filters
and go to some multi select options filter
which has some option with text long enough to reach the checkbox on the right
I see that the checkbox is shifted and not aligned with the others
We should prevent checkboxes from being misaligned
|Before|After|
|---|---|
|![Screenshot_20211116-114438_Artsy](https://user-images.githubusercontent.com/44819355/141973160-74aa7041-5fa2-41fb-b61f-c701426ecca6.jpg)|![Screenshot_20211116-135925_Artsy](https://user-images.githubusercontent.com/44819355/141973633-8b5ddaca-8675-4370-8719-b98b40fac824.jpg)|
- fix multi select filter option layout - anastasiapyzhik
</details>
[FX-3587]: …

fix(FX-3587): Multi select option checkbox

---

src/lib/Scenes/Favorites/FavoriteArtists.tsx
src/lib/Scenes/Favorites/FavoriteCategories.tsx
src/lib/Scenes/Favorites/FavoriteShows.tsx

This PR resolves [CX-2158]
This is a quick fix for the major layout issue here but there is another bug, the refresh controls are getting rendered too high up on the page so they don't show up when you pull down. Seems to affect here and MyCollection which is also using a refreshControl in StickyTabPageScrollView.
ticket here: https://artsyproduct.atlassian.net/browse/CX-2172
</details>
</details>
- Fix empty state layout in saves screens - Brian 
-
-
-
</details>
[CX-2158]: https://artsyproduct.atlassian.net/browse/CX-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cut off empty states on saves pages #trivial

---

src/lib/Scenes/Search/components/SearchResultImage.tsx

This PR resolves [FX-3599]
In eigen in order to render images (more specifically to render the algolia list items) we use the [`OpaqueImageView` component](https://github.com/artsy/eigen/blob/2d141d230e406eae3f0b5b741500914044a54930/src/lib/Scenes/Search/components/SearchResultImage.tsx#L6).
In positron when we index articles we index `image_url` like [that](https://github.com/artsy/positron/blob/86d00affde2f84f1af1f88bc302ba4879553996c/src/api/apps/articles/model/distribute.coffee#L135) and we use the [crop function](https://github.com/artsy/positron/blob/86d00affde2f84f1af1f88bc302ba4879553996c/src/api/apps/articles/model/distribute.coffee#L167-L169) which creates the url for the article to be indexed (structures the url in order to fetch it from …

fix(FX-3599): useRawURL of images that come from articles algolia

---

src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx

This PR resolves [CX-2161]
This PR fixes a bug where the value of some inputs was not populated correctly depending on the "isEdition" field.
- Fix "My Collection" Additional Details isEdition value bug - ole
-
-
-
</details>
[CX-2161]: https://artsyproduct.atlassian.net/browse/CX-2161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: My Collection Additional Details form value bug

---

.secrets.baseline
src/lib/Scenes/Search/SearchModel.tsx
src/lib/store/AuthModel.tests.ts
src/lib/store/AuthModel.ts
src/lib/store/GlobalStoreModel.tests.ts
src/lib/store/GlobalStoreModel.ts
src/lib/store/migration.tests.ts
src/lib/store/migration.ts

This PR resolves [FX-3586]
Currently if user is logged out and back into the app they can't see their recent searches.
This PR keeps recent searches in async storage after log out and only removes them if previous user and newly logged in one are not the same.
https://user-images.githubusercontent.com/44819355/142632808-7954e2e0-bb7c-4bfa-b497-500d12b62cf6.mp4
- keep recent searches after log out - anastasiapyzhik
</details>
[FX-3586]: https://artsyproduct.atlassian.net/browse/FX-3586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-3586): Keep recent searches if log in to the same account

---

src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/lib/store/config/features.ts

This PR resolves [CX-1767]
Removes the AREnableAuctionResultsKeywordFilter feature flag which is no longer needed.
-
-
-
- remove AREnableAuctionResultsKeywordFilter feature flag - ole
</details>
[CX-1767]: https://artsyproduct.atlassian.net/browse/CX-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove AREnableAuctionResultsKeywordFilter feature flag

---

src/__generated__/CreateSavedSearchAlertScreenRefetchQuery.graphql.ts
src/__generated__/CreateSavedSearchAlertScreen_me.graphql.ts
src/__generated__/CreateSavedSearchAlertTestsQuery.graphql.ts
src/__generated__/SavedSearchButtonQuery.graphql.ts
src/__generated__/SavedSearchButtonRefetchQuery.graphql.ts
src/__generated__/SavedSearchButtonTestsQuery.graphql.ts
src/__generated__/SavedSearchButton_me.graphql.ts
src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tests.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
src/lib/Scenes/SavedSearchAlert/screens/CreateSavedSearchAlertScreen.tsx
src/lib/Scenes/SavedSearchAlert/screens/EmailPreferencesScreen.tsx
src/lib/navigation/routes.tests.tsx
src/lib/navigation/routes.tsx

This PR resolves [FX-3576]
⚠️ Changes behind a feature flag
- “Update email preferences” button should be displayed only when  the “Email Alerts” toggle is on
- The button directs user to web view (see below screenshot) with the 4 email preference options
- We should to get the up-to-date status of "email preferences" every time a user opens the “create an alert” view (Only for Create Alert Flow)
- This is where a link should live
- Edit flow: SETTINGS > SAVED ALERTS > click any ALERT > under the email toggle
- Create flow: ARTIST > Specify some filters > click “Create an alert” button  > under the email toggle
https://user-images.githubusercontent.com/3513494/143445357-2fc89063-1baa-4f10-b97e-95a6e56fdebf.mp4 …

feat(FX-3576): Create link for user to view/update email preferences

---

src/lib/Components/Home/ArtistRails/ArtistRail.tsx
src/lib/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tests.tsx
src/lib/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
src/lib/Scenes/Home/Components/ArticlesRail.tsx
src/lib/Scenes/Home/Components/ArtworkRail.tsx
src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
src/lib/Scenes/Home/Components/CollectionsRail.tsx
src/lib/Scenes/Home/Components/FairsRail.tsx
src/lib/Scenes/Home/Components/NewWorksForYouRail.tsx
src/lib/Scenes/Home/Components/SalesRail.tsx
src/lib/Scenes/Home/Components/ShowsRail.tsx
src/lib/Scenes/Home/Components/Trove.tsx
src/lib/Scenes/Home/Home.tsx
src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx

This PR resolves [CX-2012]
Moves home screen module separators into the modules/rails to avoid rendering two separators in the case a module doesn't show anything.
| Personalized | Not Personalized |
| --- | --- |
| ![Simulator Screen Shot - iPhone 8 - 2021-11-29 at 15 14 36](https://user-images.githubusercontent.com/4691889/143883637-c35839da-7f16-4d5d-b6df-43ffd513563f.png) | ![Simulator Screen Shot - iPhone 8 - 2021-11-29 at 15 16 26](https://user-images.githubusercontent.com/4691889/143883770-bcb839fc-12b2-4da3-b8e7-7c3067f218c1.png) |
- Fix "too much space between modules" issue on home screen - ole 
-
-
-
</details>
[CX-2012]: https://artsyproduct.atlassian.net/browse/CX-2012?atlOrigin=eyJpIjoiNWRkNTljN …

feat: Move home screen separators into modules

---

src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/helpers.tests.ts
src/lib/Scenes/SavedSearchAlert/helpers.ts

This PR resolves [FX-3615]
⚠️ This work is behind `AREnableImprovedAlertsFlow` feature flag
- renders artist pill in create/edit alert forms
- artist pill is not editable
- matches visual ac's in [figma](https://www.figma.com/file/zbEFZqjKgKquZwtU8U44j9/Alerts?node-id=3147%3A7315)
|Android|iOS|
|---|---|
|![Screenshot_1638435636](https://user-images.githubusercontent.com/21178754/144390452-5df58adf-f8a6-43b0-a951-76231758beed.png)|![Simulator Screen Shot - iPhone 8 - 2021-12-02 at 09 55 29](https://user-images.githubusercontent.com/21178754/144389966-1c5af052-7cda-443c-b768-fe36d5ca8a08.png)|
|![Screenshot_1638435612](https://user-images.githubusercontent.com/21178754/144390456-680207f8-cf6c-4526-8163-7dbb87494177.png)|![Simulator Screen Shot - iPhone 8 …

feat(FX-3615): Display artist name as pill in create/edit alert forms

---

src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
src/lib/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tests.tsx
src/lib/Components/ArtworkFilter/Filters/AttributionClassOptions.tests.tsx
src/lib/Components/ArtworkFilter/Filters/ColorsOptions.tsx
src/lib/Components/ArtworkFilter/Filters/GalleriesAndInstitutionsOptions.tests.tsx
src/lib/Components/ArtworkFilter/Filters/LocationCitiesOptions.tests.tsx
src/lib/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tests.tsx
src/lib/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx
src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
src/lib/Components/ArtworkFilter/Filters/TimePeriodOptions.tests.tsx
src/lib/Components/ArtworkFilter/Filters/WaysToBuyOptions.tests.tsx
src/lib/Components/ArtworkFilter/Filters/YearOptions.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterBackHeader.tests.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterBackHeader.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionItem.tests.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionItem.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tests.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tsx
src/lib/Components/ArtworkFilter/types.ts
src/lib/Components/Gene/GeneArtworks.tests.tsx
src/lib/Components/Header.tests.tsx
src/lib/Components/Header.tsx
src/lib/Components/Tag/TagArtworks.tests.tsx

This PR resolves [FX-3614]
* Update the visual design to match the spec in [Figma](https://www.figma.com/file/zbEFZqjKgKquZwtU8U44j9/Alerts?node-id=3321%3A6866)
* Only the "Apply Filters" button should be displayed at the bottom (without “Create Alert“ button)
* Artwork grid filter menu should open at full height
* Top header on the filters screen (for example, Materials, Medium, Sort By) should match the spec in [Figma](https://www.figma.com/file/zG9cduJdOaTQAw886QcOwn/Filters?node-id=2737%3A11807)
* Updated design should be displayed on all screens, not just for artist artworks
https://user-images.githubusercontent.com/3513494/145037815-e3412871-36f7-4605-b7a7-b43bc2b66929.mp4
https://user-images.githubusercontent.com/3513494/145037969-141e45ee-3295-4e …

feat(FX-3614): Update visual design of artwork grid filter menu

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV2.tsx

This PR resolves [FX-3613]
Under a feature flag, enable new behavior for the “Create alert” trigger on the Artist screen’s artwork grid.
* Create alert button on the grid opens up the filter menu (just like clicking Filter + Sort)
* New button is visible within the filter menu for creating an alert with the “selected” and “applied” filters set (next to Apply).
* Changes must be under feature flag
https://user-images.githubusercontent.com/3513494/144844715-cab69bab-743a-4ae1-9c41-3bf34ba1b737.mp4
https://user-images.githubusercontent.com/3513494/144844788-243e96db-ea36-435d-97e4-516e0beaf5db.mp4
- Add "Create alert" button within Artist screen's artwork grid filter menu - dimatretyak
-
-
-
</details> …

feat(FX-3613): Add "Create alert" button within Artist screen's artwork grid filter menu

---

src/lib/Scenes/Home/Home.tsx
src/lib/store/config/features.ts
src/lib/utils/experiments.ts

This PR resolves [CX-2121]
Adds an experiment for the home feed artist recommendation rail A/B test and removes the corresponding feature flag. The feature flag won't be necessary anymore because we can disable the feature via SplitIO.
- Start home feed artist recommendations A/B test - ole
-
-
-
</details>
[CX-2121]: https://artsyproduct.atlassian.net/browse/CX-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add homefeed artist recommendations A/B test

---

src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
src/lib/Components/PopoverMessage/PopoverMessageProvider.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/utils/delay.ts

-
-
-
- failed tests after the release of AREnableSavedSearchToggles flag - dimatretyak
</details>

fix: failed tests after the release of AREnableSavedSearchToggles flag

---

src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

This PR resolves [CX-2222]
- Make the loading modal on my collection add works show up in full screen
- Make the loading modal on my collection add works show up in full screen - mounir
-
-
-
</details>
[CX-2222]: https://artsyproduct.atlassian.net/browse/CX-2222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: loading modal on MyCollection Add works

---

ArtsyWidget/FeaturedArtworks/FeaturedArtworks+LargeView.swift
ArtsyWidget/FeaturedArtworks/FeaturedArtworks+MediumView.swift
ArtsyWidget/FeaturedArtworks/FeaturedArtworks+SmallView.swift
ArtsyWidget/FullBleed/FullBleed+View.swift
ArtsyWidget/LatestArticles/LatestArticles+LargeView.swift
ArtsyWidget/LatestArticles/LatestArticles+MediumView.swift
ArtsyWidget/LatestArticles/LatestArticles+SmallView.swift
ArtsyWidget/LatestArticles/LatestArticles+Timeline.swift

This PR is a series of small updates based on QA feedback. Here's the before/after:
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
In terms of the code this is nearly all visual stuff but there is ONE behavior change: the editorial widget no longer rotates through its items as the day goes by. I thought this rotation was a good idea because it would make the widget feel fresh but I failed to consider that each item has a date associated with it.
If you have the large editorial version installed then it starts the day like this:
```
* Article A / Dec 4
* Article B / Dec 3
* Article C / Dec 2
* Article D / Dec 1
```
Newest article on top and then in descending order. As these things rotate you end up with things like this:
```
* Article C / Dec …
```

fix: Widget QA Items GRO-722

---

src/lib/Components/ReadMore.tsx
src/lib/Scenes/Show/Screens/ShowMoreInfo.tsx
src/palette/elements/EntityHeader/EntityHeader.tsx

This PR resolves [FX-3658]
In some cases the `simple-markdown` library that we are using splits a paragraph that starts with `-` in every punctuation symbol that it finds as a list item. See the issue that I opened in [here](https://github.com/Khan/simple-markdown/issues/112).
Our partners are uploading the `pressRelease` content in our cms as plain text but we render it as markdown.
With this [temporary solution](https://github.com/artsy/eigen/pull/5912/files#diff-8ca64f781dac935a68794d70fcf1963028dc4cd2ec1f96156771232436a6ed8cR46-R59) if the `ReadMore` component is under shows we resolve lists to paragraphs (I doubt that any of our partners upload markdown lists under there.)
While fixing that found a bonus bug ([fixed …

fix(FX-3658): prevent crashes coming from simple-markdown

---

src/lib/AppRegistry.tsx

From what I understand, the way we import storybook causes the imports to freak out and it goes to a stack exceeded error. Moving the import later fixes this.
Since we need to work on some storybook stuff later, this should suffice for now, and later we might make storybook imports cleaner.
-
-
-
- stop RangeError from happening when debugging.
</details>

fix(dx): stop RangeError while debugging

---

ArtsyWidget/LatestArticles/LatestArticles+LargeView.swift
ArtsyWidget/LatestArticles/LatestArticles+MediumView.swift

I don't run dark mode on any of my devices so I had a bit of a blind spot here - luckily @kathytafel noticed it! What was happening was that only for the medium and large editorial widget views I never set a background color. That meant that when a user switched to dark mode then the view was all busted looking. Here's some pictures:
<details>
<summary>before (dark mode)</summary>
</details>
<details>
<summary>before (light mode)</summary>
</details>
<details>
<summary>after</summary>
</details>
I was also chatting with @damassi about some improvements to the layout of the editorial widget, namely vertically centering some text so that's in here too.
https://artsyproduct.atlassian.net/browse/GRO-727

fix: Editorial widget broken with dark mode GRO-727

---

src/lib/Components/ArtworkGrids/ArtworksFilterHeader.tsx
src/lib/Scenes/MyCollection/MyCollection.tsx

This PR resolves [CX-2233]
Remove artwork grid padding on artist's artwork screen.
| --- | --- |
| ![Simulator Screen Shot - iPhone 8 - 2021-12-21 at 11 40 59](https://user-images.githubusercontent.com/4691889/146918951-e5dabbe5-d782-43a9-85ee-abee33e30174.png) |  ![Simulator Screen Shot - iPhone 8 - 2021-12-21 at 11 41 14](https://user-images.githubusercontent.com/4691889/146918838-60722c0d-dd3d-47b4-87ce-0c18eb5843f8.png)  |
- Fix artwork grid padding on the artists' artwork screen - ole
-
-
-
</details>
[CX-2233]: https://artsyproduct.atlassian.net/browse/CX-2233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Remove artwork grid padding on artist artwork screen

---

src/__generated__/SearchQuery.graphql.ts
src/__generated__/SearchRefetchQuery.graphql.ts
src/__generated__/Search_system.graphql.ts
src/lib/Scenes/Search/Search.tests.tsx
src/lib/Scenes/Search/Search.tsx
src/lib/Scenes/Search/SearchModel.tsx

This PR resolves [FX-3649]
We want to be able to handle the artwork index separately and not have it be automatically picked up by the existing code that renders the normal pill / list view components. For this reason it is necessary to render only specific supported indexes
* Artist
* Article
* Auction
* Artist Series
* Collection
* Fair
* Show
* Gallery
-
-
-
- Limit Algolia search indexes exposed in app to a specific supported list - dimatretyak
</details>
[FX-3649]: https://artsyproduct.atlassian.net/browse/FX-3649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-3649): Limit Algolia search indexes exposed in app to a specific supported list

---

src/lib/Components/Lists/AuctionResultListItem.tsx
src/lib/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx
src/lib/Scenes/Home/Components/AuctionResultsRail.tsx

This PR resolves [CX-2015]
Margins are applied to the touchable opacity of 'Action results for artists you follow' items, home and auction results screens, as a result clickable area increased
- Margins are applied to the touchable opacity of 'Action results for artists you follow' items, as a result clickable area increased
-
-
-
https://user-images.githubusercontent.com/36167539/146792266-24ef5d9e-f559-43f6-b2ee-b1235bc6a508.mp4
</details>
[CX-2015]: https://artsyproduct.atlassian.net/browse/CX-2015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2015): change margins (py) for action results, home and auction results screens

---

src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx

This PR resolves [CX-2247]
fix: Handle me being null on Profile screen
- Prevent Profile screen from crashing without local user profile image - ole
-
-
-
</details>
[CX-2247]: https://artsyproduct.atlassian.net/browse/CX-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Prevent Profile screen from crashing without local user profile image

---

src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tests.tsx
src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV1.tsx
src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV2.tsx
src/lib/Scenes/SavedSearchAlert/mutations/createSavedSearchAlert.ts
src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
src/lib/store/config/features.ts

This PR resolves [FX-3666]
Since the `AREnableSavedSearchToggles` flag has been released, it is necessary to clean up the code and remove the use of feature flag
* Remove `AREnableSavedSearchToggles` feature flag
* Clean up the code that works with `AREnableSavedSearchToggles`
-
-
-
- Code cleanup after the release of the AREnableSavedSearchToggles flag - dimatretyak
</details>
[FX-3666]: https://artsyproduct.atlassian.net/browse/FX-3666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-3666): Code cleanup after the release of the AREnableSavedSearchToggles flag 

---

src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tests.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
src/lib/utils/artworkRarityClassifications.ts

This PR resolves [CX-2202]
This PR helps in displaying a modal having rarity types and their explanations by tapping on `What is this?`
- Rarity classification explanation modal tapping on `What is this?` - sam
-
-
-
</details>
[CX-2202]: https://artsyproduct.atlassian.net/browse/CX-2202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Rarity classification type explanation modal 

---

src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx

This PR resolves [CX-2251]
Add keyboard avoiding view to artwork form
- Prevent keyboard from overlapping input in artwork form - ole
-
-
-
</details>
[CX-2251]: https://artsyproduct.atlassian.net/browse/CX-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add keyboard avoiding view to artwork form

---

src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

This PR resolves [CX-2254]
Fixes the back button issue in Add Photos screen when editing an artwork from My Collection
- Fix back button issue in Edit Artwork in My Collection  - mrsltun
-
-
-
</details>
[CX-2254]: https://artsyproduct.atlassian.net/browse/CX-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix[CX-2254]: back button issue in Add Photos when editing artwork

---

src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tests.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx

This PR resolves [CX-2254]
Follow-up on https://github.com/artsy/eigen/pull/5978
- Use `navigation.goBack()` to navigate back from the Add Photos screen
- This approach would help us avoid nested ternary operations and keep the code easier to understand
https://user-images.githubusercontent.com/11945712/148214317-3c2aa77c-9d9b-433b-af6c-1da67b75b57a.mov
-
-
-
- refactor navigating back logic on google photos - mounir
</details>
[CX-2254]: https://artsyproduct.atlassian.net/browse/CX-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: different approach for navigating back on editing photos

---

Artsy/App/ARAppNotificationsDelegate.m

This PR resolves [CX-2249]
- When we were updating to new onboarding we changed the order in which we retrieved previous push token and inadvertently broke push registration. 
- Since we were retrieving the previous token AFTER updating the token the values were always the same so we were never registering tokens with our servers, this just moves the retrieval to before the update as before
-
- Fix push notification registration - Brian 
-
-
</details>
[CX-2249]: https://artsyproduct.atlassian.net/browse/CX-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: get previousToken before updating the token

---

src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx

Fixes design concerns in https://github.com/artsy/eigen/pull/5989
This PR resolves [CX-2253]
Fixes bug where previously selected my collection artwork form details is not cleared if a user goes back and clicks Skip.
https://user-images.githubusercontent.com/18648835/148369006-f9933e12-2d57-4399-a566-08b79c7b14a6.mp4
- fix skip bug in my collection artwork forms - kizito
-
-
-
</details>
[CX-2253]: https://artsyproduct.atlassian.net/browse/CX-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cx-2253): fix skip bug present in my collection artwork forms

---

src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx

This PR resolves [FX-3610]
For the screen view on the `SavedSearchList` screen on an app (the list of all Saved Alerts under settings on the app), we fire a pageview with `context_screen_owner_type` = `SavedSearches` where it **should be** `savedSearch`
-
-
-
- Pass correct owner type to analytics for saved search alerts screen - dimatretyak
</details>
[FX-3610]: https://artsyproduct.atlassian.net/browse/FX-3610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-3610): Pass correct owner type to analytics for saved search alerts screen

---

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tests.tsx
src/lib/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tsx
src/lib/Components/ArtworkFilter/ArtworkFilterNavigator.tsx

This PR resolves [FX-3675]
* we should track the same events `tappedCreateAlert` and `toggledSavedSearch` in improved alerts flow
* `tappedCreateAlert` event should be tracked when the user clicks the "Create Alert" button on artist **artworks grid** with the following values:
* `action: "tappedCreateAlert"`
* `context_screen_owner_type: "artist"`
* `context_screen_owner_id: "artist id"`
* `context_screen_owner_slug: "artist slug"`
* `context_module: "artworkGrid"`
* `tappedCreateAlert` event should be tracked when the user clicks "Create Alert" button on **Sort & Filter** menu with the following values:
* `action: "tappedCreateAlert"`
* `context_screen_owner_type: "artist"`
* `context_screen_owner_id: "artist id"`
* `context_screen_owner_slug: "artist …

feat(FX-3675): update analytics tracking for saved search

---

src/lib/Scenes/Artwork/Artwork.tsx

This PR backs back additional artwork screen tracking fields that have been removed in https://github.com/artsy/eigen/pull/5963.
The fields are actually needed and have been accidentally removed (see [slack thread](https://artsy.slack.com/archives/C01B2P6LJUU/p1641204159089300)).
**Before:**
```
{
"context_screen": "Artwork",
"context_screen_owner_type": "Artwork",
"context_screen_owner_slug": "daniel-arsham-amethyst-eroded-vogue-magazine",
"context_screen_owner_id": "61d8b16cb157b0000ce5eb77"
}
```
**After:**
```
{
"context_screen": "Artwork",
"context_screen_owner_type": "Artwork",
"context_screen_owner_slug": "daniel-arsham-amethyst-eroded-vogue-magazine",
"context_screen_owner_id": "61d8b16cb157b0000ce5eb77",
"availability": "for sale", …
```

fix: Bring back additional artwork screen tracking fields

---

src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/Scenes/SavedSearchAlert/helpers.tests.ts
src/lib/Scenes/SavedSearchAlert/helpers.ts

This PR resolves [FX-3677]
⚠️ Changes behind `AREnableImprovedAlertsFlow` feature flag
* should **not display** "• 1 filter" in name input if no filter is selected and only the artist's name is displayed as a pill (for example, _Banksy_)
* should **display** "• 1 filter" in name input when a user adds a filter (for example, _Banksy • 1 filter_)
https://user-images.githubusercontent.com/3513494/149120849-b99082d3-8b73-45c2-bed4-3db6dd5357e0.mp4
https://user-images.githubusercontent.com/3513494/149122240-8eefe59d-d5e6-408d-a553-6085c4c46f89.mp4
-
-
-
- update the filter counting logic for name input - dimatretyak
</details>
[FX-3677]: https://artsyproduct.atlassian.net/browse/FX-3677?atlOrigin=eyJpIjoiNWRkNTljNzY …

chore(FX-3677): update the filter counting logic for name input

---

src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts

This PR resolves [FX-3634]
Currently, when making changes in a saved alert, we can update only name, email and push. We need to make changes and add the ability to update search criteria attributes on the edit saved search alert screen
* As a collector
* When I’m on the edit alert screen
* And I remove a non-default filter
* And I click Save Alert
* Then my alert is updated to the desired criteria
https://user-images.githubusercontent.com/3513494/150136271-b7d6e1f7-8388-4cbc-b0f9-cbf3875fd9d8.mp4
https://user-images.githubusercontent.com/3513494/150138195-08e953e0-a4eb-4a38-a57c-a6a47c53ae2e.mp4
https://user-images.githubusercontent.com/3513494/150136496-f0083b45-099e-4c18-bc21-92ac71748941.mp4
- Allow to …

feat(FX-3634): Allow to update search criteria attributes from saved alerts screen

---

src/__generated__/EditSavedSearchAlertQuery.graphql.ts
src/__generated__/EditSavedSearchAlertRefetchQuery.graphql.ts
src/__generated__/EditSavedSearchAlert_user.graphql.ts
src/__generated__/SavedSearchAlertQuery.graphql.ts
src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/palette/Theme.tsx

This PR resolves [FX-3699]
There may be a situation when the user previously created a saved search alert and enabled "Email Alerts" toggle, but later set "Email Preferences" to "None". And it would be useful to warn the user about this on edit alert screen
* A warning message is displayed on the edit alert screen if:
* "Email Alerts" toggle **enabled**
* "Email Preferences" are set to "**None**"
* A warning message should be placed **between** "Email Alerts" toggle and "update email preferences" button
* Colors for the message
* background color: `orange10 = #FCF7F3`
* text color: `orange150 = #A8501C`
https://user-images.githubusercontent.com/3513494/150392140-6904ef4c-181e-4332-b4bc-25e49ee6a058.mp4 …

feat(FX-3699): Show a warning message on edit alert screen if a user has set email frequency to None

---

src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tests.tsx
src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
src/lib/store/config/features.ts

This PR resolves [CX-2271]
Remove AREnableVisualProfileIconAndBio feature flag.
-
-
-
- Remove AREnableVisualProfileIconAndBio feature flag - ole
</details>
[CX-2271]: https://artsyproduct.atlassian.net/browse/CX-2271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove AREnableVisualProfileIconAndBio feature flag

---

src/lib/Components/ArtsyReactWebView.tests.tsx
src/lib/Components/ArtsyReactWebView.tsx
src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
src/lib/Scenes/ArtworkMedium/ArtworkMedium.tsx
src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
src/lib/navigation/BackButton.tsx
src/lib/navigation/navigate.ts

In some situations, it would be useful to pass props for `goBack` method. For example, in this way we can specify which screen the user returned from and perform the logic we need.
This PR adds this feature, and also solves the problem with executing unnecessary network requests for Saved Search Alert Flow when `goBack` event for `navigationEvents` is called (now when this event is called, requests are executed to get a list of all alerts + refetch information for a specific alert)
In this example, the `SavedSearchesListQuery` query should not be executed, since this data is not used for the current screen
https://user-images.githubusercontent.com/3513494/150771252-39b08e2e-f443-4d87-8d60-d8b39d7b1c5e.mp4 …

feat: pass go back props

---

src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx

This PR resolves [CX-2265]
This PR fixes the issue when the user is not being able to add an artwork after adding photos
https://user-images.githubusercontent.com/20655703/151140658-27098292-882f-4ec1-a70c-81e0abe0f82f.mp4
-
-
-
- update my collection artwork validation schema - mrsltun 
</details>
[CX-2265]: https://artsyproduct.atlassian.net/browse/CX-2265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix[CX-2265]: unable to save an artwork after adding image in My Collection

---

scripts/setup-distribute

Co-authored-by: Sultan Al-Maari <sultan.al-maari@artsymail.com>
Co-authored-by: Adam Butler <ab@adam-butler.com>
This PR is a follow-up on https://github.com/artsy/eigen/pull/6082
the `setup-distribute-macos` and `setup-distribute-linux` directories were not the right ones and this was resulting in the issue below. The fix was simply to update those imports 
#nochangelog

fix: wrong script directory

---

src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx

Due to the added changes in PR #6072, there was a crash on `Alerts List` screen on Android. Release version (7.1.7) is **not affected**
-
-
-
- Fix crash for alerts flow on android - dimatretyak
</details>

fix: crash for alerts flow on android

---

src/lib/AppRegistry.tsx

**This is a long description for very few lines of code, but it was fun to debug 😄**
This PR resolves [CX-2285]
**Reproduction**
1. Open the app
2. Select an artwork (**Artwork X**)
3. Scroll down to the end of the page to see related artworks
4. Select an artwork (**Artwork Y**)
5. Press back
**Expected result**
Get back to **Artwork X** screen 🍾
**Actual result**
User lands on **Artwork Y** screen 😲
(video below)
**What I noticed**
When I press the back button, the screen is already loaded with the **Artwork Y** Content without any loading at all. Usually, there should be some loading even if its props are cached in the relay store.
**My theory (might be right or might be wrong and might be both right and wrong at the same time 😵‍💫)**
The screen could …

fix: Broken back navigation

---

src/lib/Scenes/Artwork/Artwork.tests.tsx
src/lib/Scenes/Artwork/Artwork.tsx

This PR resolves [NX-3070]
Fixes a bug when coming back from modal on Android that was stuck in the `loading` state of Artwork component. That was happening due to a racing condition from a double `relay.refetch`, one was canceling the other, and since we relied on the callback of one of those refetches to set the loading state to `false` on Android that was canceled and never set back to `false`.
https://user-images.githubusercontent.com/15792853/152151778-599387d5-5d35-4fd3-b0d0-a51bf401c5ec.mov
- trigger only one refetch after dismissing modal from Artwork scene - araujobarret
-
-
-
</details>
[NX-3070]: https://artsyproduct.atlassian.net/browse/NX-3070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

fix: Artwork placeholder stuck bug given dismissed modal event

---

ArtsyWidget/FullBleed/FullBleed+View.swift

We had a call with Apple where they encouraged us to add an Extra Large version of the widget so I did it:
I got lucky there with the artwork being a great fit for that aspect ratio, they don't always cooperate so nicely. Here's an example from the add screen:
I'm good with this but open to ideas...
https://artsyproduct.atlassian.net/browse/GRO-777
/cc @artsy/grow-devs @jpoczik @pvinis @brainbicycle 
- Add an extra large widget - Jon
-
-
</details>

feat: Add an Extra Large Widget GRO-777

---

src/lib/Scenes/Consignments/Screens/Overview-uploading.tests.tsx
src/lib/Scenes/Consignments/Screens/Overview.tests.tsx
src/lib/Scenes/Consignments/Screens/Overview.tsx

This PR resolves [SWA-198]
This PR fixes some cases when consign submission may be submitted without photos
- Fix submission's photos saving 
</details>
https://user-images.githubusercontent.com/79979820/152800069-8fcc9715-a9a0-4e80-98a9-1fc3ae045126.mov
[SWA-198]: https://artsyproduct.atlassian.net/browse/SWA-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SWA-198): submissions without photos

---

patches/@types+react-relay+11.0.3.patch
src/lib/AndroidApp.tsx
src/lib/AppProviders.tsx
src/lib/AppRegistry.tsx
src/lib/Components/RetryErrorBoundary.tsx
src/lib/utils/combineProviders.tests.tsx
src/lib/utils/combineProviders.tsx

This PR is moving the tracking to the AppProviders, and also adds a little helper function to list Providers in a nicer, flatter way. It also allows for Providers that need props, like the relay and the tracking one.
⚠️  Since this has broken before, I would appreciate if at least one of the reviewers runs the app to verify the events fire. I tested it on ios and it seems to be firing, but a second verification would be nice. Also, the android emulator is giving me attitude today, and I cant make it work right now. The changes should be fine there, but again I would like it if one of you runs this on android to verify. ⚠️ 
The way to verify is to enable the analytics inspector dev toggle from the admin menu. then click around and …

feat(tracking): moving the top-level tracking to the AppProviders

---

src/lib/AppRegistry.tsx
src/lib/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
src/lib/Scenes/Inbox/Components/Conversations/OrderUpdate.tests.tsx
src/lib/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
src/lib/navigation/routes.tsx

[NX-3071]
Because users will be pointed to the inbox after making an offer (see [NX-3041](https://artsyproduct.atlassian.net/browse/NX-3041)), we need to make it clear for them where to see the details of the offer. 
- Create conversation details route.
- Allow opening offer order details from the initial offer message.
Twin PR on Force: https://github.com/artsy/force/pull/9292
[Figma file](https://www.figma.com/file/PgmxHwBnoOUS4ybwpK2mTN/Make-Offer-on-all-Eligible-Artworks?node-id=525%3A3575) for reference.
- Add see details link on initial offer message (inbox) - Leandro L
-
-
-
</details>
[NX-3071]: https://artsyproduct.atlassian.net/browse/NX-3071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

feat(NX-3071): Add see details link on initial offer message (inbox)

---

src/__generated__/myCollectionAddArtworkMutation.graphql.ts
src/lib/utils/useAutoCollapsingMeasuredView.tsx

This PR resolves issue with the Artist Screen failing to load and we get the error below
<details>
<summary>Screenshot</summary>
</details>
https://user-images.githubusercontent.com/11945712/152802627-2d7f4094-228e-41d4-a290-e77c50b44f7f.mov
Reanimated failed on Android to animate a value from 0 to a duration set to 0. It's still not yet clear to me why this is the case only on Android, but I think this is not something I should be spending time investigating for now since we can simply remove the animation because we are not animating the header anymore
-
-
-
- refactor disabling the animation approach - mounir
</details>

fix: broken artist screen animation

---

src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx
src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
src/lib/Components/Gene/GeneArtworks.tests.tsx
src/lib/Components/Tag/TagArtworks.tests.tsx
src/lib/Scenes/MyCollection/MyCollection.tests.tsx
src/lib/Scenes/Sale/Sale.tests.tsx
src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/lib/Scenes/SavedSearchAlert/helpers.ts
src/lib/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx

This PR resolves [FX-3731]
The purpose of this pr is to update the Alert Flow copies in the app and adding a View Duplicate button in the Duplicate alert prompt, in order collectors to be able to view with one press of a button the duplicate alert.
|Screenshots||||
|--|--|--|--|
|![Simulator Screen Shot - iPhone 13 mini - 2022-02-09 at 17 14 26](https://user-images.githubusercontent.com/21178754/153245507-1bac53e1-0277-4cee-b02f-f18945b4b3be.png)|![Simulator Screen Shot - iPhone 13 mini - 2022-02-09 at 17 14 21](https://user-images.githubusercontent.com/21178754/153245510-a5b36da8-2ad4-4eef-b629-db305d92f20c.png)|![Simulator Screen Shot - iPhone 13 mini - 2022-02-09 at 17 28 57](https://user-images.githubusercontent.com/21178754/153245477-0052c51c-ea71-4a1 …

chore(FX-3731): Saved Alerts copy updates

---

src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tests.tsx
src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
src/lib/store/config/features.ts

This PR resolves [TX-168]
This PR removes the “VAT included in the price” on some artworks and replaces it with "Taxes may apply at checkout. Learn more" on **all** artworks. 
This update is hidden behind a new "Enable Avalara Phase 2" feature flag. 
- add Avalara phase 2 feature flag and new tax message on all artworks -rquartararo
-
-
-
</details>
[TX-168]: https://artsyproduct.atlassian.net/browse/TX-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-168): add Avalara phase 2 feature flag and new tax message

---

src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx

This PR addresses a bug when we have the offerable feature flag on in Gravity, we never had the situation where artwork is offerable and inquiriable with buttons appearing at the same time, `Make offer` and `Contact Gallery`.
This is a bugfix so we would touch anything else here, but we had a [ticket](https://artsyproduct.atlassian.net/browse/NX-3083) before the bug news that is going to address the refactor of this component, especially this if/else mess.
https://user-images.githubusercontent.com/15792853/154026154-1acd6426-9f46-4cf3-bc03-7f906a7a1479.mov
- enable commercial buttons to show make offer and contact gallery at same time - araujobarret
-
-
-
</details>

fix: render logic of buttons given offerable artwork

---

src/__generated__/FairArticlesQuery.graphql.ts
src/__generated__/FairArticles_fair.graphql.ts
src/__generated__/FairEditorialTestsQuery.graphql.ts
src/__generated__/FairEditorial_fair.graphql.ts
src/__generated__/FairQuery.graphql.ts
src/__generated__/FairTestsQuery.graphql.ts
src/__generated__/Fair_fair.graphql.ts
src/__generated__/VanityURLEntityQuery.graphql.ts
src/lib/Scenes/Fair/Components/FairEditorial.tsx
src/lib/Scenes/Fair/Fair.tsx
src/lib/Scenes/Fair/FairArticles.tsx

This PR resolves [FX-3753]
Restore listing of articles not in the editorial feed to fair screen
| With inEditorialFeed (before)  | Without inEditorialFeed (after) |
| ![before](https://user-images.githubusercontent.com/3513494/154453843-84085460-59e9-40a2-9edf-1f2f98df071a.png)  | ![after](https://user-images.githubusercontent.com/3513494/154453885-ffe9b0dc-bd99-46c9-a7e8-6834b6542fa6.png)  |
- Restore listing of articles not in the editorial feed to fair screen - dimatretyak
-
-
-
</details>
[FX-3753]: https://artsyproduct.atlassian.net/browse/FX-3753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-3753): Restore listing of articles not in the editorial feed to fair screen

---

src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
src/palette/elements/Radio/RadioButton.tsx

This PR resolves [CX-2315]
This PR improves the artwork form metric change performance.
- Improve artwork form metric change performance - ole
-
-
-
</details>
[CX-2315]: https://artsyproduct.atlassian.net/browse/CX-2315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Improve performance of artwork form metric change

---

.secrets.baseline
src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx
src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx
src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/testUtils.ts
src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/validation.ts

This PR resolves [[SWA-249](https://artsyproduct.atlassian.net/browse/SWA-249)]
This PR fixes the form validation in Artwork details step of submission flow. The bug is that when rarity field is selected as limited_edition, we should expect user to type in edition size and number before enabling the save button. 
https://user-images.githubusercontent.com/42584148/155077812-a4ead876-08a0-4517-9cf4-cfe24915b462.mp4
This feature is behind a feature flag, so the changes applicable only to developer for now. 
</details>

[fix]: Rarity validation in Submission flow

---

Artsy/App/ARAppDelegate+Emission.m
Artsy/View_Controllers/Util/ARNavigationController.m
HACKS.md
emission/Pod/Classes/ViewControllers/ARMapContainerViewController.m
src/app/AppRegistry.tsx

This PR resolves [MOPLAT-162]
There were 2 issues here, 1 was that there was a memory leak causing multiple `AREigenMapContainerViewController`s to be created and stay in memory, this would cause react components contained within to get out of sync. The other was that after we started saving props in the PageWrapper prop updates from the native side were not getting propagated to react native. 
- Fixes a memory leak causing citySelection not to work on subsequent entries to cityGuide
- Adds a workaround for prop updates from native side not updating RN side in PageWrapper
-
-  Fixes city not updating in city guide - Pavlos, Brian, Angela, Sultan
-
-
</details>
[MOPLAT-162]: …

fix: use weak self in city guide, fix memory leak

---

src/app/Components/ArtworkFilter/Filters/ColorsOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx
src/app/Components/ArtworkFilter/Filters/ColorsSwatch.tests.tsx
src/app/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.tests.ts
src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts

This PR resolves [FX-3719]
- Adds support for the new colors, while retaining support for old colors, so that this can safely be rolled out during our interim period of indexing both sets of color names
- Once usage of older versions of Eigen drops low enough and we've reindexed all production artworks to new color names only, we can come back and drop support for the `OLD_COLORS` list here
We made some decisions above `foregroundColors` for the new swatches, which determines the color of the check mark in the selected state:
|iOS|Android|
|--|--|
|<img width="400" alt="selected" src="https://user-images.githubusercontent.com/140521/156212001-a831c29f-da6c-4c79-9803-a08d7c1165fa.png">|<img width="300" alt="selected" …

feat(colors): support new color filtering options

---

src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx

This PR resolves [NX-3083]
This PR refactors the CommercialButtons component making it functional, improving test coverage and readability with nested if/else statements. Another follow-up to be addressed is to retire old code from the feature `AROptionsNewFirstInquiry`.
- refactor CommercialButtons - araujobarret
-
-
-
</details>
[NX-3083]: https://artsyproduct.atlassian.net/browse/NX-3083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: commercial buttons

---

package.json
src/app/utils/Wrap.tests.tsx
src/app/utils/Wrap.tsx
src/palette/elements/Button/Button.stories.tsx
yarn.lock

`Wrap` is a helper component we have, and I changed its "api" to be a bit more clear. Also I added tests
#nochangelog
-
-
-
-
</details>

feat(Wrap): tests and better api for Wrap

---

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx
src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx

This PR resolves [SWA-277]
This PR turns 4 inputs (for year, width, height, depth) in the new submission flow form into numeric inputs. 
Changes applicable to devs only as the feature behind a flag. 
</details>
[SWA-277]: https://artsyproduct.atlassian.net/browse/SWA-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[fix]: swa 277/numeric keyboard for inputs in submission flow

---

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx

The type of this PR is: **bug**
Thanks to @kiryl-zubarau for helping with debugging this 🙏
This PR resolves [SWA-278] location autofill result needs two clicks & styling
https://user-images.githubusercontent.com/36475005/156790441-381bc896-e6fd-430a-a6c6-23012496f6e8.mov
-
-
-
</details>
[SWA-278]: https://artsyproduct.atlassian.net/browse/SWA-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug[swa-278] location autofill result needs two clicks & styling

---

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx

The type of this PR is: **BugFix**
This PR resolves [SWA-287]
This PR fixes the problem that after deleting a photo in the Upload Photos step, the Save & Continue button becomes disabled. 
https://user-images.githubusercontent.com/42584148/156786411-c4af53d4-f78f-4208-b63d-7cd285a287e0.mp4
-
-
-
-
</details>
[SWA-287]: https://artsyproduct.atlassian.net/browse/SWA-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: enable save & continue button after photo deletion

---

src/app/Scenes/Map/GlobalMap.tsx

This PR resolves [MOPLAT-166]
Cherry-picking this quick fix from our latest release back to main.
-
- city guide city selector stays visible - pavlos
-
-
</details>
[MOPLAT-166]: https://artsyproduct.atlassian.net/browse/MOPLAT-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(city guide): selector staying visible

---

src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
src/app/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
src/app/Scenes/Inbox/Components/Conversations/utils/groupConversationItems.ts

[NX-3102]
When the conversation starts from Make Offer we don't see events being rendered in the conversation, like the message `You sent an Offer of $XXX`.
Another fix included is to show the conversation CTA to interact with counter offers given conversations starting from Make Offer.
There are some open questions like messages and events that are not grouped at the same time to render but are not related to the scope of this PR.
Here the first 2 conversations started from Make Offer flow, the last one started from Inquiry.
https://user-images.githubusercontent.com/15792853/157627846-625c227b-e669-4ed9-95e2-f41b5633fb1e.mov
Before (Conversation started from MO given counter-offer)
After (Conversation started from MO given counter-offer)
cc …

fix: conversation messages and event order

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx

This PR resolves [CX-2416]
Update artwork form skip button copy "Go to Add Artwork Details".
- Update artwork form skip button copy - ole
-
-
-
</details>
[CX-2416]: https://artsyproduct.atlassian.net/browse/CX-2416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update artwork form skip button copy

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx

This PR resolves [CX-2441]
Added tests
-
-
-
- added tests -daria
</details>
[CX-2441]: https://artsyproduct.atlassian.net/browse/CX-2441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(CX-2441): add tests to MyCollectionWhySell component

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
src/app/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tsx

This PR resolves [CX-2348]
Disable edit option for artwork in my collection coming from SWA
|Artwork not from SWA| Artwork from SWA|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/158828293-022160ad-b46d-4843-8dec-6b10eb13c7be.png)|![image](https://user-images.githubusercontent.com/17421923/158828048-d524bc88-7ce9-472e-aedc-455b83e83b75.png)|
- Disable edit option for artwork in my collection coming from SWA - sam
-
-
-
</details>
[CX-2348]: https://artsyproduct.atlassian.net/browse/CX-2348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disable edit artwork coming from SWA

---

HACKS.md
package.json
yarn.lock

Points to fixed version of `react-native-scrollable-tab-view` commit hash that has not been yet released to npm. Without this we get red screens when the library tries to use now non-existent getNode() function in new version of react-native. 
- 
-
-
- Fix scrollable tab red screen issue - brian
</details>

fix: point to fixed version of scrollable tab library

---

Podfile.lock
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkArtistAuctionResults.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx

This PR resolves [CX-2452] the following issue inside my collection artwork and my collection add artist pages
- This is occurring because we are nesting scrollview and this is an anti pattern that the react-native team strongly advice against using. The reason behind that is that it breaks virtualization and it makes it practically impossible for react native to tell on which level to apply the virtualization and therefore makes scrollview behave in a non deterministic manner. The solution is always to make sure that we don't nest any scrollviews and that all scroll events bubble into only one scrollview.
Both screens are working after the update
-
-
-
- fix virtualization issues inside my collection screens …

fix: virtualization issues inside my collection

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx

This PR resolves [FX-3825]
Removes scrollview from price filter to make it easier for users to use the slider, plus now that we removed all different options from price filter we don't really need the scrollview
- removed scrollview from price filter - gkartalis
-
-
-
</details>
[FX-3825]: https://artsyproduct.atlassian.net/browse/FX-3825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove scrollview from price filter

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx

This PR resolves [CX-2439]
- We want to show the Request For Price Estimate Banner only for Artworks with D-Index of >= 9
<table>
<tr>
<td><b>D-Index >= 9</b></td>
<td><b>D-Index < 9</b></td>
</tr>
<tr>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/159527866-fefee120-726d-496e-be44-8aab9b32112d.png"></td>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/159527885-cf94b545-9f5e-4fd3-9c3f-5a66ca2b688e.png"></td>
</tr>
</table>
- Restrict showing request price estimate banner for D-Index less than nine - kizito
-
-
-
</details>
[CX-2439]: https://artsyproduct.atlassian.net/browse/CX-2439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

feat(cx-2439): Restrict showing request price estimate banner for D-Index less than nine

---

src/app/utils/experiments.ts
src/app/utils/queryPrefetching.ts

Removing the SplitIO QueryPrefetching experiment because we will roll it out to 100% of the users. 
-
-
-
- Remove SplitIO QueryPrefetching experiment - ole
</details>

chore: Remove SplitIO QueryPrefetching experiment

---

src/app/Scenes/Search/RefetchWhenApiKeyExpired.tsx
src/app/Scenes/Search/Search.tests.tsx
src/app/Scenes/Search/Search.tsx
src/app/Scenes/Search/components/SearchInput.tsx
src/app/store/config/features.ts
src/app/utils/useAlgoliaIndices.ts
src/palette/elements/Pill/Pill.tsx

Related PR: #5720
This PR resolves [FX-3750]
Unleash flag: [link](https://unleash.artsy.net/projects/default/features2/eigen-enable-improved-search-pills)
Currently if search pill doesn't contain results we show _no results_ state [like this](https://github.com/artsy/eigen/pull/5654)
This PR implements checking all algolia indices when typing term and only displaying those having results
* update tests
* fix problem with relay cache
* fix problem with displaying loading indicator every time refetch was called
* fix problems for `useAlgoliaIndices` (catch failed responses from algolia, ignore outdated requests to algolia)
* Clean up `AREnableImprovedSearchPills` flag
* Use `eigen-enable-improved-search-pills` flag from Unleash …

refactor(FX-3750): Improved search pills

---

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tests.tsx
src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx

This PR resolves [SWA-318]
In the app submission flow, when a location is selected from the suggested dropdown list, the suggestion box is still rendered with ‘Please try searching again with a different spelling’ message. (see the 'before' video below). 
This is caused by a recent change we have introduced in [this PR](https://github.com/artsy/eigen/commit/3f48bc410abcb0b473bdc39715e2c958194359fd?diff=split). The problem is caused by the fact that the logic returning null from the `LocationPredictions` component is updated from: 
```
if (!predictions.length) {
return null
}
```
to 
```
if (locationValue.length < MIN_LENGTH) {
return null
}
```
This PR updates this logic by: 
- passing the selectedLocation from `LocationAutocomplete` to …

fix: location auto complete dropdown logic

---

src/app/AppRegistry.tsx
src/app/Scenes/Consignments/ConsignmentsHome/ConsignmentsHome.tsx
src/app/Scenes/Favorites/FavoriteArtworks.tsx
src/app/Scenes/Home/Home.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
src/app/utils/queryPrefetching.ts

Right now we're not able to prefetch more than one query per screen. Some of the screens (e.g. the Profile screen) fetch the date with multiple queries. This PR extends the query prefetching implementation to allow prefetching multiple queries per screen and adds a few queries.
-
-
-
-
</details>

feat: Allow prefetching multiple queries per screen

---

src/app/store/config/features.ts

This PR sets the ffs `readyForRelease` to true.
Blocked by https://github.com/artsy/echo/pull/216
-
-
-
- set my collection ffs to readyForRelease to true - mounir
</details>

chore: set my collection ffs to readyForRelease to true

---

src/app/AppRegistry.tsx
src/app/store/AuthModel.ts
src/app/utils/useSyncAuthState.ts

This PR resolves [MOPLAT-140]
Deeplinks are handled on native side of code on iOS, before we route to a deeplink we check the auth state (token, user, expiration), if it is valid we go ahead with the deeplink. If it is not we do nothing. Previously we were syncing this auth state from js side only on sign in. That means if anything goes wrong (e.g app is quit before the token syncs) deeplinks won't work for that user until they sign out and in again, something users probably don't do very often. This instead adds a new hook in the main app, that syncs the token state any time: 1) the app is killed and reopened 2) the token or other auth data changes. That way if something does go wrong there are more chances for it to be corrected. …

fix: sync native auth state more frequently for deeplinks

---

package.json
scripts/algolia-example-galleries-near-me.ts
yarn.lock

Search for gallery locations within 100km of either:
- Your current IP address
- An Artsy recognized city slug
- Specific coordinates
```bash
$ ./scripts/algolia-example-galleries-near-me.ts
$ ./scripts/algolia-example-galleries-near-me.ts los-angeles-ca-usa
$ ./scripts/algolia-example-galleries-near-me.ts 48.1351, 11.5820
```
Jira: [FX-3852](https://artsyproduct.atlassian.net/browse/FX-3852)
cc/ @dimatretyak @erikdstock

chore: add script to execute example algolia location-based queries

---

src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
src/app/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tsx

This PR resolves [CX-2471]
Change My Collection artwork image pagination indicator to dots.
| --- | --- |
|![Simulator Screen Shot - iPhone 12 Pro Max - 2022-04-05 at 09 32 26](https://user-images.githubusercontent.com/4691889/161702316-3d660694-9d24-460b-85cf-3885c99b868e.png) | ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-04-05 at 09 31 20](https://user-images.githubusercontent.com/4691889/161702326-34bcb22d-fbc8-41f2-9d4f-858af607d9b9.png)|
- Change My Collection artwork image pagination indicator to dots - ole
-
-
-
</details>
[CX-2471]: https://artsyproduct.atlassian.net/browse/CX-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Change My Collection artwork image pagination indicator to dots

---

src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/app/Scenes/Sale/Components/SaleLotsList.tsx

When selecting filters, the results were not always displayed correctly (in some cases, there was a message that there were no results, although they were) + a react warning was displayed. The problem was that [fetchNextPage](https://github.com/artsy/eigen/blob/1ff6d2e92bd12ce887bc95a2e69151ae2fde7856/src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx#L188) was called several times due to the fact that there was no additional check
https://user-images.githubusercontent.com/3513494/161828725-814a1214-c707-48b3-9252-3ca6fd8f5b11.mp4
https://user-images.githubusercontent.com/3513494/161828750-87e8c9e1-806e-4d0a-b6ad-7e594e4224f4.mp4
-
-
-
- React warning on Sale page when applying filters - …

fix: react warning on Sale page when applying filters

---

CHANGELOG/android-changelog.md
CHANGELOG/ios-changelog.md
Podfile.lock
src/app/Components/PartnerBanner.tsx
src/app/Scenes/Partner/Components/PartnerHeader.tests.tsx
src/app/Scenes/Partner/Components/PartnerHeader.tsx

This is a followup to [GRO-820](https://artsyproduct.atlassian.net/browse/GRO-820). Design decided that a static banner was preferable to [an animated marquee](https://github.com/artsy/eigen/pull/6305) so I reimplemented the feature here.

Adds black owned banner to partner page

---

src/app/Scenes/Sale/Components/SaleLotsList.tsx

Related PRs: #6558, #6534
The auction team [has raised a problem](https://artsy.slack.com/archives/C02MU3DB3/p1648496726378999) that incorrect bids were displayed on the Sale page. The problem was due to the fact that data from Relay Cache was displayed
This PR contains small additions for PR #6534
https://user-images.githubusercontent.com/3513494/162430765-ac32488a-8dbc-4c60-a91e-d715db2f9a6b.mp4
https://user-images.githubusercontent.com/3513494/162430776-aff6731e-47ac-4628-9e92-4675db64cbb7.mp4
-
-
-
- add `force: true` for load more on sale screen - dimatretyak
</details>

chore: add `force: true` for load more on sale screen

---

src/app/Scenes/Inbox/Components/Conversations/Message.tsx
src/app/Scenes/Inbox/Components/Conversations/Messages.tsx

This PR resolves [NX-3119]
SSO for Google got broken in Force for a while so we ended up with Collectors without a name being registered, that was causing some issues since we are receiving `null` in a GraphQL field that is required.
This PR removes unnecessary props from GraphQL in Conversations that were breaking the UI for these particular collectors.
-
-
-
-
</details>
[NX-3119]: https://artsyproduct.atlassian.net/browse/NX-3119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(NX-3119): broken conversations for Collectors without a name

---

Artsy.xcodeproj/project.pbxproj
Artsy/App/ARScreenPresenterModule.m
Artsy/Constants/ARAppConstants.h
Artsy/Constants/ARAppConstants.m
Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.h
Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m
Artsy_Tests/View_Controller_Tests/Web_Browsing/ARAuctionWebViewControllerTests.m
Podfile.lock

This PR resolves [MOPLAT-213]
This PR resolves [MOPLAT-214]
Adds back native auction web view we use for live auction registration we removed a bit too hastily. 
-
- Add back auction web view for live auction registration - Brian
-
-
</details>
[MOPLAT-213]: https://artsyproduct.atlassian.net/browse/MOPLAT-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-214]: https://artsyproduct.atlassian.net/browse/MOPLAT-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(MOPLAT-213): partial revert of #6386, add back auction web view

---

.secrets.baseline
Artsy/Eigen.playground/playground.xcworkspace/contents.xcworkspacedata
src/app/Components/Bidding/Components/Timer.tests.tsx
src/app/Components/Bidding/Components/Timer.tsx
src/app/Components/Countdown/CountdownTimer.tests.tsx
src/app/Components/Countdown/CountdownTimer.tsx
src/app/Components/Countdown/StateManager.tsx
src/app/Components/Countdown/Ticker.tests.tsx
src/app/Components/Countdown/Ticker.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
src/app/__fixtures__/ArtworkBidAction.ts
src/app/store/config/features.ts
storybook.json

This PR resolves [BX-210](https://artsyproduct.atlassian.net/browse/BID-210)
This PR adds a new timer to cascading end time lots that is formatted differently. This PR also changes the word "Ends" to "Closes" for OO sales that are currently open.
Sale is open and closes in < 2 mins
Sale is open and closes in < 60 mins 
Sale is open and closes in <24 hours and >= 1 hour
Sale is open and closes in >= 24 hours
Sale opens in < 1 day:
Sale opens in >=1 day <2 days
Sale opens in >= 2 days
-
- Display a new countdown on lots that are in sales with cascading end times
-
-
</details>

feat(artwork): Add new countdown timer and label for cascading end time interval sales

---

docs/pull_request_template.md

I've been noticing plenty of PRs lately that are WIP but are actually PRs with engineers assigned to review them and they look ready to be reviewed. Once I review the PR, I get notified later that it's not done yet and all the time that I've spent reviewing was for nothing. The goal of this small change is to make sure we avoid that in the future
#nochangelog 

chore: add convert to draft comment

---

.circleci/config.yml

Whenever we are trying to build a beta - we run the `build-test-js` workflow and we don't really need it. The reason behind that is this workflow already runs on every PR and runs on main as well. This will save us about 15 minutes for andoid and for android as well
-
-
-
- disable build-test-js on beta builds - mounir
</details>

chore: disable build-test-js on beta builds

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx

This PR resolves [FX-3895]
Android keybordType number-pad includes some special characters that iOS does not ( `.` `,` `-` ).
When a user navigated to the price filter screen in an Android device and pressed any of the `.` `,` `-`, the app displayed an error screen 👇  Demo behavior below
https://user-images.githubusercontent.com/21178754/163377922-d9e112f2-fedc-4f72-a2dd-ee532086d769.mp4
This pr fixes this issue by adding an early exit clause in the onChangeText event of the PriceRangeOptions screen to prevent that.
Also added some test cases.
Video demo of behavior after the fix:
https://user-images.githubusercontent.com/21178754/163378613-855d28c6-f634-49ab-9399-d8db65c5bb4e.mp4
-
-
- handle gracefully errors from special characters entered …

fix(FX-3895): handle special characters on pricerangeoptions screen

---

src/app/Components/StickyHeaderPage.tsx
src/app/Components/Tag/TagArtworks.tsx
src/app/Scenes/ArtistSeries/ArtistSeries.tsx
src/app/Scenes/Collection/Collection.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/Show/Show.tsx

This PR resolves [FX-3814]
1.  Open App
2. Tap on Search at bottom navigation bar
3. Type `Bedroom paintings`
4. Click on `Bedroom paintings`
5. Tap on `Sort & Filter`
6. Tap on Price
7. Tap on `Max Price`
8. Enter `500`
9. Tap on Show Results
10. Observe
Tapping on `Show Results` , Results should display.
First time tapping on `Show Results`, Closes num pad.
* Tag artworks
* Artist series artworks
* Collection artworks
* Fair artworks
* Show artworks
_Artist series_
https://user-images.githubusercontent.com/3513494/163802435-4e9adf20-60b0-4eb5-ba3e-bcf448d5e471.mp4
_Tag_
https://user-images.githubusercontent.com/3513494/163802467-a95674bf-6172-4ca4-9d92-51b080aa0483.mp4
_Show_
https://user-images.githubusercontent.com/3513494/163802486-e86e9969-232e-4e05-aa8b-d977a73b7f29.mp4
_Artist …

fix(FX-3814): problem when need to click "Show Results" button twice

---

src/app/Components/Bidding/Components/Timer.tests.tsx
src/app/Components/Bidding/Components/Timer.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx
src/app/Scenes/Sale/Sale.tests.tsx
src/app/Scenes/Sale/Sale.tsx
src/app/__fixtures__/ArtworkBidAction.ts

This PR resolves [BX-349](https://artsyproduct.atlassian.net/browse/BID-349)
Adding cascading end time banner to the lot and sale page if the sale is open and if the sale has cascading end times. The banner shows the "Learn more" link if the env variable is configured to include the link.
Sale page:
Lot Page:
~~1. Because the banner is fit between two pieces of info as part of `ArtworkTombstone`, the margins on either side of the banner seem difficult to avoid but don't match the designs.
It's supposed to look like the following screenshot from figma w/ no margins:
I fixed this with @dzucconi and it looks great now!
2. I chose not to use a feature flag here because the changes seems relatively low risk and if the banner doesn't work properly, it's not a huge deal. But open to other …

feat(BX-349): Add cascading end time banner to lot and sale page

---

src/app/store/config/features.ts

This PR resolves [NX-3127]
Adds Conversational Buy Now feature flag(AREnableConversationalBuyNow)
Sibling of https://github.com/artsy/echo/pull/240
- add AREnableConversationalBuyNow feature flag - araujobarret
-
-
- 
</details>
[NX-3127]: https://artsyproduct.atlassian.net/browse/NX-3127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3127): add AREnableConversationalBuyNow

---

src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
src/app/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx

Replace property `buttonText` with `children` on InquiryMakeOfferButton.
Keep the default value of `Make an Offer`
See [implementation on Force](https://github.com/artsy/force/blob/main/src/v2/Apps/Conversation/Components/ConfirmArtworkButton.tsx#L87).
-
-
-
- Replace property `buttonText` with `children` on InquiryMakeOfferButton - LeandroL
</details>

chore: render children as button content instead of a specific prop

---

src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkGrids/LotCloseInfo.tests.tsx
src/app/Components/ArtworkGrids/LotCloseInfo.tsx
src/app/Components/Countdown/Ticker.tsx
src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
src/app/store/config/features.ts
src/app/utils/useTimer.tsx

This PR resolves [BX-294](https://artsyproduct.atlassian.net/browse/BID-294)
This PR adds the countdown timer to the lot grid on the sale page for sales with cascading end times turned on:
Lots are in the middle of closing:
Lot is less than the cascade end interval (1 min) from closing:
Lots are minutes from closing:
Lots are hours from closing:
When the sale is open but lots are more than a day from closing (formatted lot end time):
When the sale is not yet open (no label):
-
-
-
-
</details>

(BID-294): Add timers sale artwork grid

---

src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tsx
src/app/store/config/features.ts
src/app/store/config/visualClues.ts

This PR resolves [CX-2473]
The PR added an explanatory banner at the top of the Collector Profile screen. It will appear for all the users, new and existing, as long as they have an empty profile and haven’t added any information.
- Explanatory banner for empty Collector Profile - sam
-
-
-
</details>
[CX-2473]: https://artsyproduct.atlassian.net/browse/CX-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Explanatory banner for empty Collector Profile 

---

src/app/Components/Bidding/Screens/BidResult.tests.tsx
src/app/Components/Bidding/Screens/BidResult.tsx
src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
src/app/Components/Bidding/Screens/ConfirmBid/index.tsx

This PR resolves [BX-357](https://artsyproduct.atlassian.net/browse/BID-357)
During QA, we discovered that the app has additional surfaces that use a timer component (on the confirm id modal). That timer component was always receiving the sale's `endAt` date even if the sale had cascading end times turned on. The result was that the the timer countdown showed a negative number when a user placed bids as lots were closing because the sale level end date had passed, but the lots were still open. The fix is to pass in the sale artwork's `endAt` date to the timer if the sale has cascading end times so the countdown will show time left on the lot, not on the sale.
The results: 
-
-
-
-
</details>
Need help with something? Have a look on our [docs], …

Fix (BX-357): Fix negative confirm bid timers

---

patches/react-native-credit-card-input+0.4.1.patch

This PR resolves [FX-3904]
1. Open the app
2. From the Home screen locate the "Auction Lots Ending Soon" section (in this case 'Shared Online - Only Mocktion')
3. Tap the first tile 'LOT 1 Emma Camden Self-Portrait'
4. Tap 'Bid' button > Next
5. Tap 'Add' for Credit card
6. Enter Card number `4242 4242 4242 4242`
7. _or_ just navigate to Profile -> Settings -> Payment -> Add new card
Displaying a component with different [system font size
](https://support.google.com/accessibility/android/answer/11183305?hl=en#fontsize)
| Small | Medium | Large | Largest |
| ------------- | ------------- | ------------- | ------------- |
| ![small](https://user-images.githubusercontent.com/3513494/163828846-eb6738de-313b-4793-a144-f5fce55fa3eb.png) | …

fix(FX-3904): `CVC` text in Card Information is poorly wrapped and truncated

---

src/app/Scenes/Sale/Components/SaleHeader.tsx
src/app/Scenes/Sale/SaleHeader.tests.tsx
src/app/store/config/features.ts
src/app/utils/saleTime.ts

This PR resolves [BX-211](https://artsyproduct.atlassian.net/browse/BID-211)
This work just updates the label that shows the absolute time for the sale and when it's closed and removes the auction closed label so it doesn't appear before the lots finish closing. 
Before the sale opens (shows the sale open time):
After the sale opens (shows the sale end time) and as the lots are closing:
(This currently says the auction is closed, so even though this label isn't ideal, it's much less confusing than the current experience)
After the sale ends (shows that the sale is closed):
-
-
-
-
</details> …

feat(BX-211): Update labels for sale details when a sale has cascading end times turned on

---

src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/app/Components/ArtworkFilter/FilterModal.tests.tsx

- Hides filters when aggregation counts are empty
* [Notion card](https://www.notion.so/artsy/Auctions-Sort-Filter-medium-is-empty-b528af1c5c244d0383ab5b1d93ad49e6)
https://user-images.githubusercontent.com/3513494/164752745-6e3d6641-f2e0-4620-92dd-72a35bd7398a.mp4
https://user-images.githubusercontent.com/3513494/164752666-2ef4290a-19a7-42f9-b6c5-13f28ed9bb8f.mp4
- Hide filters when aggregation counts are empty 
-
-
-
</details>

fix: hide filter menu item when aggregation counts are empty

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
src/app/store/config/features.ts

This PR resolves [CX-2520]
clean up feature flag AREnableMyCollectionComparableWorks
-
-
-
- clean up feature flag AREnableMyCollectionComparableWorks -daria
</details>
[CX-2520]: https://artsyproduct.atlassian.net/browse/CX-2520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(CX-2520): clean up feature flag AREnableMyCollectionComparableWorks

---

src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts

This PR resolves [CX-2438]
https://user-images.githubusercontent.com/18648835/165268042-fbe4d8a6-b3b4-40f4-86ee-2f58782972cd.mp4
- sort and filter for high demand index - kizito
-
-
-
</details>
[CX-2438]: https://artsyproduct.atlassian.net/browse/CX-2438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(cx-2438): sort and filter for high demand index

---

src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
src/app/Scenes/Artwork/Components/Questions.tests.tsx
src/app/Scenes/Artwork/Components/Questions.tsx

This PR resolves [NX-3131]
Adds a small contact block in the artwork screen (hidden under the feature flag AREnableConversationalBuyNow)
before:
after
-
-
-
-
</details>
[NX-3131]: https://artsyproduct.atlassian.net/browse/NX-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3131): add contact gallery small cta for buy now artworks

---

HACKS.md
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tests.tsx
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/app/Components/StickyTabPage/StickyTabPage.tsx
src/app/Components/StickyTabPage/StickyTabPageContext.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtworkList.tsx
src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
src/app/Scenes/MyCollection/MyCollection.tests.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx

This PR resolves [CX-2543]
- MyCollection screen hangs because we try to store yScrollOffset
- Header animation into view is a bit janky
- When moving from FilteredStateZero to another state, SearchBar jumps across the screen from the top to the bottom
- Switching from Grid to List view, search bar jumps from top to bottom
- SearchBar is added to StickyHeader thereby reducing available scrollable area
- Remove need for scrolloffset, instead using staticHeader height to scroll
- Remove hideStaticHeader and showStaticHeader. Instead get a handle on the inner flatlist and perform scroll on it. This removes the jumping from bottom to top.
- Pass the search bar as a header component instead, thereby not reducing the scrollable area.
- contentOffset to initially hide the header.
- When …

fix(CX-2543): Fix performance with my collection search

---

.github/workflows/beta-android.yml
.github/workflows/beta-ios-manual.yml
.github/workflows/beta-ios.yml
.github/workflows/promote-android.yml
.github/workflows/promote-ios.yml
.github/workflows/release-ios-app.yml
.github/workflows/trigger-ci-after-ready-to-review.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

android/app/src/main/AndroidManifest.xml
src/app/AppRegistry.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Inbox/Components/Conversations/CTAPopUp.tsx
src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
src/app/Scenes/Inbox/Components/Conversations/InquiryPurchaseButton.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/InquiryPurchaseButton.tsx
src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
src/app/Scenes/Inbox/Components/Conversations/PurchaseModal.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/PurchaseModal.tsx
src/app/navigation/routes.tsx

This PR resolves [NX-3133]
Adds Purchase button (hidden under feature flag) to conversations when it's `isAcquireable`. Covers unique and edition sets, since we re-used some boilerplate code from MOI it's already covering Edition Sets. Foreword in regards to some code duplication, the way we define the routes in Eigen is kinda funky, so abstracting to reuse the same modal component for example would be tricky and require some not type-safe prop drilling from the AppRegistry, so that's one of the main reasons.
- add purchase button to conversations - araujobarret
-
-
-
</details> …

feat(NX-3133): Add Purchase button to conversations

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx

This PR resolves [SWA-357]
This PR fixes the problem that when a user uploads multiple photos back to back, only 1 photo is shown as uploaded in the UI, although all uploaded photos are sent to the API. With the fix, all uploaded photos are displayed in the UI as expected. 
https://user-images.githubusercontent.com/42584148/167811906-e6646fbb-ed20-4ee6-ad3e-20b1580de5ba.mp4
This bug fix is effective for all users using the submission flow in all platforms. 
-
-
-
</details>
[SWA-357]: …

fix: (SWA-357): Display multiple photos when uploaded in Submission flow

---

HACKS.md
src/app/Scenes/ReverseSearchImageResults/ReverseSearchImageResults.tsx

Related PR #6743
While testing the beta build, I noticed a strange behavior on iOS: when I tried to upload a file, I received an error saying that the maximum allowed file size was exceeded (although the same file was uploaded on Android without any problems). It turned out that the problem has been around for a long time in React Native and and you can find a [discussion of it here](https://github.com/facebook/react-native/issues/27099).
Solution based on [this comment](https://github.com/facebook/react-native/issues/27099#issuecomment-907069335)
https://user-images.githubusercontent.com/3513494/168596308-04b457b0-372d-4bec-a1a9-3b270fafdee9.mp4
https://user-images.githubusercontent.com/3513494/168596257-95cb0d74-627d-4783-8e17-3321517de38c.mp4 …

fix: images posted to server via fetch get their size inflated significantly for iOS

---

src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
src/app/Scenes/Inbox/Components/Conversations/MakeOfferModal.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
src/app/Scenes/Inbox/Components/Conversations/PurchaseModal.tsx

Adjusts the Select Edition Set component used in Inbox to act like a real relay fragment component instead of prop drilling manually from parent components.
-
-
-
-
</details>

refactor: EditionSelectBox conversion to Relay Fragment component

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Sales/index.tsx
src/app/utils/AboveTheFoldQueryRenderer.tsx

Use Relays `network-and-store` fetch policy for the screens Artwork and Sales/Auctions in order to not see stale data.
- Use network-and-store fetch policy for Artwork and Sales/Auctions screen
-
-
-
</details>

fix: Bypass cache for Artwork and Sales/Auctions screens

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/AuctionFaqSection.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/FaqAndSpecialistSection.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx

This PR resolves [FX-3978]
- remove AuctionFaqSection out of FAqAndSpecialistSection component
- use feature flag to conditionally render FaqAndSpecialistSection when ff is on to its own section
- Changes behind `AREnableCreateArtworkAlert` feature flag
|AREnableCreateArtworkAlert = false|||||
|---|---|---|---|---|
|![b4_1](https://user-images.githubusercontent.com/21178754/169055442-a4fac592-cccb-4ef6-b2b7-e87570a5daaa.png)|![b4_2](https://user-images.githubusercontent.com/21178754/169055465-dc76a2fa-a018-4449-bdeb-880c1c19dab1.png)|![b4_3](https://user-images.githubusercontent.com/21178754/169055460-05e82ef1-ce77-482c-9d41-9995c338af07.png)|![b4+4](https://user-images.githubusercontent.com/21178754/169055448-5003fd54-e59b-4b27-ae68-a6c6ed6dcd6a.png)|![b4](https://user-images.githubuserco …

feat(FX-3978): Separate Faq Section from Auction Faq and add it to artwork screen

---

src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/CreateArtworkAlertSection.tests.tsx
src/app/Scenes/Artwork/Components/CreateArtworkAlertSection.tsx

This PR resolves [FX-3954]
* And I can see the Create Alert button
* When I click the Create Alert button
* Then I am presented with the Create Alert modal
* And the name placeholder is specific to the artwork
* And supported filters are preconfigured
* Can not remove the artists in this iteration
* Alert name: “Artworks like: [Title of work]” (do not include year)
* Display the create alert modal window when the “Create Alert“ button on artwork page was pressed
* Should be displayed pre-filled relevant filters in create alert modal
https://user-images.githubusercontent.com/3513494/169017970-966ec49c-0f46-4eb0-a7f5-fb40823a1763.mp4
https://user-images.githubusercontent.com/3513494/169019390-14064287-0d91-4589-86b1-7303fb72cf93.mp4
- Create …

feat(FX-3954): Create Alert button opens up modal pre-filled with relevant filters on artwork screen

---

src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tsx
src/app/Scenes/Artwork/Components/CreateArtworkAlertSection.tsx

This PR resolves [FX-3989]
Changing copy from `piece` -> `work`, the reasoning for this can be found in the jira ticket.
Force also has the same `work` copy 
- copy update on create alert section - gkartalis
-
-
-
</details>
[FX-3898]: https://artsyproduct.atlassian.net/browse/FX-3898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FX-3989]: https://artsyproduct.atlassian.net/browse/FX-3989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …

chore(FX-3989): copy update

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx

| Before  | After |
| ![before](https://user-images.githubusercontent.com/3513494/170553324-514df006-bce8-40d6-a20a-f54d5d7331bc.png) | ![after](https://user-images.githubusercontent.com/3513494/170553416-98462a09-4af2-41f7-8f13-95917ab76be4.png) |
https://user-images.githubusercontent.com/3513494/170553524-97d64ecd-b986-4bf5-9a4f-b07c81e5ff42.mp4
https://user-images.githubusercontent.com/3513494/170553574-d212d4d0-e6af-475b-9bae-ac560873aec6.mp4
-
-
-
- display single "Create Alert" button on artwork page for bidding closed state - dimatretyak
</details> …

fix: display single "Create Alert" button on artwork page for bidding closed state

---

docs/add_a_visual_clue.md
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/store/config/visualClues.ts

This PR removes the `ArtworkSubmissionMessage` session clue from the clue list to prevent the message from being shown when the app starts (see [docs about session clues](https://github.com/artsy/eigen/blob/main/docs/add_a_visual_clue.md#L63)). 
I really think we shouldn't use the logic and data structure of visual clues for these messages. It gets super confusing. 
-
-
-
-
</details>

fix: Remove ArtworkSubmissionMessage session clue from clue list

---

src/app/Components/ArtworkFilter/Filters/ColorsOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx

This PR resolves [FX-3996]
In the color filter screen within the artwork grid's filter modal, Eigen uses the list of aggregated colors coming from upstream  to render a color selection UI, one swatch for each color in the current aggregation.
It can only render colors that it actually knows about, because of various metadata that is hard-coded within [src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx](https://github.com/artsy/eigen/blob/main/src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx)
If it encounters an unrecognized color, it crashes, which was the cause of a defect [back in March](https://artsy.slack.com/archives/C9SATFLUU/p1646667810727089).
We rolled back those changes, so it hasn't been a problem in the meantime. But we are ready to roll forward again, albeit …

fix: handle unrecognized color filter options without crashing

---

src/app/Components/Bidding/Components/Timer.tsx
src/app/Components/Countdown/Ticker.tests.tsx
src/app/Components/Countdown/Ticker.tsx

This PR resolves [BID-402]
- While the Sale page accounts for when Sale starts within less than 24 hours but not on the same day, the Lot detail page doesn't. This PR fixes that for the lot page.
<p><img src="https://user-images.githubusercontent.com/18648835/171709979-8e43135b-e55e-453e-bcae-ff917534d231.png" width="45%" /></p>
- Show the correct end time on lot page for different days - kizito
-
-
-
</details>
[BID-402]: https://artsyproduct.atlassian.net/browse/BID-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

fix(BID-402): Show the correct start time on lot page for different days

---

src/app/Scenes/BottomTabs/BottomTabs.tsx

This PR updates showing the visual clue on the bottom bar to only show it when the `AREnableMyCollectionInsights` is feature flag enabled
-
-
-
- update My Profile bottom bar visual clue logic - mrsltun
</details>

fix: Update bottom bar visual clue logic

---

src/app/Components/ArtworkFilter/Filters/ColorsOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx
src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts

This PR resolves [FX-4011]
Now that [old and new colors are indexed](https://github.com/artsy/gravity/pull/15407) in production, it is safe to drop support for the old colors in future versions of the app
(The ability to support new colors has been out since https://github.com/artsy/eigen/pull/6317, so should have near-universal adoption by now.)
Old and new colors are _both_ indexed to Elasticsearch, as of this writing. But after this change is merged we'll only show the new ones, as on the right hand side of the images below.
|Before|After|
|---|---|
|<img width="646" alt="Screen Shot 2022-06-06 at 11 09 43 AM" src="https://user-images.githubusercontent.com/140521/172190384-8556205a-ced2-4760-a346-36b89626febe.png">|<img width="646" alt="Screen Shot 2022-06-06 at 11 09 10 AM" …

chore(colors): drop support for old color filtering options

---

src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tests.tsx
src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tsx

This PR resolves [FX-3916]
Right now the behavior in size input is not consistent between android and iOS. 
Users in iOS are not able to insert decimal numbers while in Android they can (this comes by design from `keyboardType=”number-pad` prop.
* Prevent the users from entering invalid inputs (like commas, dashes, dots) in the beginning of the input
* Allow to enter floating point values (e.g `123`, `123.45`)
* Allow to enter only 2 digits after floating point
https://user-images.githubusercontent.com/3513494/171634592-89e88a8e-d56e-4eb6-9804-f8db5fc1e2f1.mp4
https://user-images.githubusercontent.com/3513494/171636212-74260835-c234-4508-a7cf-11bbb742b14e.mp4
- Prevent users from entering special chars in size filter input - dimatretyak
-
-
- …

feat(FX-3916): prevent users from entering special chars in size filter input

---

src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/app/Scenes/Artwork/Components/CertificateAuthenticityModal.tests.tsx
src/app/Scenes/Artwork/Components/CertificateAuthenticityModal.tsx
src/app/Scenes/Artwork/Components/Questions.tests.tsx
src/app/__fixtures__/ArtworkFixture.ts

This PR resolves [NX-3129]
Add Certificate of Authenticity modal and atrributionClass of the Artwork to the Screen
https://user-images.githubusercontent.com/15792853/172653057-781b0334-04e4-45fc-bcf3-1fd20c8a33cd.mov
- add attribution class and authenticity data to artwork screen - araujobarret
-
-
-
</details>
[NX-3129]: https://artsyproduct.atlassian.net/browse/NX-3129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3129): Add authenticity modal and icons to Artwork screen

---

src/app/Components/ArtworkFilter/Filters/ColorsOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx

This PR resolves [FX-3779]
Simply adds a new color filtering option for **brown**.
Should be safe to merge, since we display this swatch _only if_ it's in the current artwork results' aggregation. 
(Thus we won't risk showing it prematurely, i.e. before we've reindexed artworks to detect brown. See: https://github.com/artsy/gravity/pull/15433)
- Adds support for filtering artwork results by the color brown
</details>
[FX-3779]: https://artsyproduct.atlassian.net/browse/FX-3779?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

feat(colors): add brown color filter option

---

src/app/Scenes/VanityURL/VanityURLEntity.tests.tsx
src/app/Scenes/VanityURL/VanityURLEntity.tsx
src/app/utils/renderWithPlaceholder.tsx

trying to open https://www.artsy.net/art-appraisals was going to a 404 in the app. after this, it will open a webview.
we also need to put that link to the blocklist so it doesn't open the app, but its a good default to not go to 404 when we have forgotten to block the next one.
-
-
-
-
</details>

fix: links should open a webview when not assigned to a native screen

---

src/app/Scenes/Inbox/Components/Conversations/Composer.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx

This PR resolves [NX-3141]
Relies on orderUpdateState when rendering order events from `CommerceOrderStateChangedEvent` type inside conversations.
-
-
-
-
</details>
[NX-3141]: https://artsyproduct.atlassian.net/browse/NX-3141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3141): add new orderUpdateState to coenversation orders queries

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

This PR resolves [CX-2638]
fix: frozen add artwork modal
https://user-images.githubusercontent.com/11945712/175006004-a7150de3-b239-470a-a335-a3b48d7ba145.mov
- fix frozen add work modal inside my collection - mounir
-
-
-
</details>
[CX-2638]: https://artsyproduct.atlassian.net/browse/CX-2638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: frozen add artwork modal

---

src/app/Components/SearchImageHeaderButton/SearchImageHeaderButton.tsx
src/app/Components/SearchImageHeaderButton/index.ts
src/app/Scenes/Fair/Fair.tests.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/Show/Show.tests.tsx
src/app/Scenes/Show/Show.tsx
src/app/tests/mockEnvironmentPayload.ts
src/app/utils/useImageSearch.ts

This PR resolves [FX-4046]
Right now for QA purposes I've added only one fair and one show in staging env vars in metaphysics using:
```bash
hokusai staging env set REVERSE_IMAGE_SEARCH_ENABLED_SHOW_SLUGS=debra-force-fine-art-abstractions-1930s-1980s
hokusai staging env set REVERSE_IMAGE_SEARCH_ENABLED_FAIR_SLUGS=liste-art-fair-basel-2022
```
for more context check the j[ira ticket](https://artsyproduct.atlassian.net/browse/FX-4046)
> ⚠️ ⚠️ This feature is behind `AREnableImageSearch` feature flag  ⚠️ ⚠️
**What changed**
|eligible show| random show| eligible fair | random fair| ui fix |
|---|---|---|---|---|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-06-22 at 18 21 53](https://user-images.githubusercontent.com/21178754/175071148-b545adf5-6e2d-4521-812b-1b7c52f57de9.png)|![Simulator …

feat(FX-4046): reverse image search control visible only enabled show entities

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

This PR resolves [CX-2611]
Added the logic to display "Generating market data" only when MarketPriceInsights are available. If not available - show inly "Saving artwork" text.
https://user-images.githubusercontent.com/36167539/174878171-5a1ef719-14ca-4929-8139-c5ace5c47812.mp4
- improve saving artwork modal logic -daria
-
-
-
</details>
[CX-2611]: https://artsyproduct.atlassian.net/browse/CX-2611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2611): improve "Generating insights" while saving artwork modal logic

---

src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tests.tsx
src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tsx

This PR resolves [FX-4053]
There are some cases of artworks that **don't have an associated artist**. When a user creates an Alert for those artworks we get a huge activity events (triggering notifications for any artworks that are published).
This pr solves that:
- changes should be for Artwork page **ONLY**
- Create Alert btn should be hidden, not disabled
- Create Alert btn should be hidden when artwork doesn't have any associated artists.
|no artists|with artists|
|---|---|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-06-24 at 11 11 03](https://user-images.githubusercontent.com/21178754/175493286-f627931a-0eb5-428f-ab51-e236681b7791.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-06-24 at 11 11 33](https://user-images.githubusercontent.com/21178754/175493269-62db3816-9dd7-4e8f-b …

feat(FX-4053): hide create artwork alert btn when artwork has no artists

---

src/app/Components/Modal.tests.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tests.tsx
src/app/Scenes/Artwork/Components/ContextCard.tests.tsx
src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tests.tsx
src/app/Scenes/Artwork/Components/CreateArtworkAlertSection.tests.tsx
src/app/Scenes/Artwork/Components/PartnerCard.tests.tsx
src/app/Scenes/Artwork/Components/Questions.tests.tsx
src/app/Scenes/Collection/Screens/CollectionArtworks.tests.tsx
src/app/Scenes/Fair/FairArtworks.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/InquiryPurchaseButton.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/PurchaseModal.tests.tsx
src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tests.tsx
src/palette/elements/Button/Button.tsx

In the button component we use `MeasuredView` in order to prevent the button from changing size when the text changes (eg. save -> saved).
This results in the testing environment to have to select the button element with `getAllByText("btn text")[0]` due to button text being rendered twice in the testing tree snapshot even though in the real environment this is not displayed to the user.
This solution will prevent that.
TODO:
-
-
-
- prevent button text from rendering twice in testing environment - gkartalis
</details> …

refactor(tests): prevent button text rendered twice in testing environment

---

src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx

This PR resolves [NX-3198]
Edition selection modal (MOI) displayed editions as unavailable unless explicitly marked as `isOfferable`. Since the release of MOOAEA, this should've considered both `isOfferableFromInquiry` and `isOfferable`.
| --- | --- |
| ![Select edition set](https://user-images.githubusercontent.com/265560/176207828-c2dac0c7-0807-41ca-9a5d-6030a2c4ec47.png) | ![Select edition set](https://user-images.githubusercontent.com/265560/176207865-99cb2711-3ef2-4893-8674-ff68d11d5dad.png) |
- Edition sets were wrongfully being marked as unavailable on Make Offer on Inquiry - LeandroL
-
-
-
</details>
[app state …

fix(NX-3198): Edition sets were wrongfully being marked as unavailable

---

src/app/relay/createEnvironment.ts
src/app/relay/middlewares/errorMiddleware.tests.ts
src/app/relay/middlewares/errorMiddleware.ts

This PR resolves [MOPLAT-294]
Relay errors in eigen were reporting with their title as the formatted GraphQL errors from relay. The problem with this is this includes url params and error message, so for almost every request it is distinct leading us to have 1000s of 1 time errors reported in Eigen. This changes the title to a shorter version with just the GraphQL request name and the error if we can parse it out. The full formatted error is still in the metadata of the error.
Old Style:
https://sentry.io/organizations/artsynet/issues/3388128437/?project=5867225&query=is%3Aunresolved&statsPeriod=14d
New Style:
https://sentry.io/organizations/artsynet/issues/3385708903/?project=5867225&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox&statsPeriod=14d …

chore: simplify error name for relay errors

---

ios/ArtsyWidget/Fixtures.swift
ios/ArtsyWidget/Models/Artwork.swift
ios/ArtsyWidget/Models/ArtworkImage.swift

Turns out that using the first image in an array is insufficient! 😝 In the case of this artwork:
https://www.artsy.net/artwork/lynne-drexler-untitled-46
The first image in the array is the signature by the artist, not the shot of the work! Instead, you're better off using the `position` property on the `images` array. This PR does that. Pretty pictures:
https://artsyproduct.atlassian.net/browse/GRO-1135

fix: Use first artwork image in widget GRO-1135

---

src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
src/app/Components/ArtworkFilter/Filters/ArtistIDsOptionsScreen.tsx
src/app/Components/ArtworkFilter/Filters/EstimateRangeOptions.tsx
src/app/Components/ArtworkFilter/Filters/SortOptions.tsx
src/app/Scenes/Sale/Components/NewSaleLotsList.tests.tsx
src/app/Scenes/Sale/Components/NewSaleLotsList.tsx
src/app/Scenes/Sale/Sale.tsx
src/app/store/config/features.ts

This PR resolves [FX-4089]
* using `viewer.artworksConnection` instead of `saleArtworksConnection` to get artworks like [on Force](https://github.com/artsy/force/blob/15693e3b173c8daa510d72014eb0bf378a6eacd7/src/v2/Apps/Auction/AuctionApp.tsx#L206)
* displaying the same sort options as [on Force](https://github.com/artsy/force/blob/15693e3b173c8daa510d72014eb0bf378a6eacd7/src/v2/Apps/Auction/Components/AuctionArtworkFilter.tsx#L42-L47)
* changes behind `AREnableArtworksConnectionForAuction` flag
https://user-images.githubusercontent.com/3513494/179784061-6666d468-a06b-4dcc-a13c-3c69b65bcde6.mp4
https://user-images.githubusercontent.com/3513494/179795018-24a35253-f702-4a90-8417-fd552e80cdfa.mp4
| …

feat(FX-4089): replace `saleArtworksConnection` with `viewer.artworksConnection` for Auction screen

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/PartnerLink.tests.tsx
src/app/Scenes/Artwork/Components/PartnerLink.tsx
src/app/Scenes/Artwork/Components/Questions.tests.tsx
src/app/Scenes/Artwork/Components/Questions.tsx

This PR resolves [NX-3183]
Changes the new Contact Gallery component in the Artwork, also incorporating the Partner link to it.
Before
https://user-images.githubusercontent.com/15792853/180398604-05d76d8e-a15b-4193-8b05-99d2de93a457.mov
After
https://user-images.githubusercontent.com/15792853/180398658-4248375b-6167-4649-8b91-ab5ae19aaa5d.mov
- changes contact gallery component order and design - araujobarret
-
-
-
</details>
[NX-3183]: …

feat(NX-3183): adjust order and components of Artwork screen

---

src/app/Scenes/Collection/Collection.tests.tsx
src/app/Scenes/Collection/Collection.tsx

This PR resolves [FX-4104]
* For a collection with `showFeaturedArtists: true`, the Featured artists section should be visible
* For a collection with `showFeaturedArtists: false`, the Featured artists section should be hidden
| `showFeaturedArtists` is true | `showFeaturedArtists` is false |
| ![true](https://user-images.githubusercontent.com/3513494/180779456-ae69c90b-36d0-4fc2-a78e-f7f4f61a259b.png) | ![false](https://user-images.githubusercontent.com/3513494/180780217-544bd16e-0373-45a1-b3b6-e6997108c6a3.png)|
| the featured artists section is hidden |         | staging/production | …

feat(FX-4104): Hide the Featured Artists section when showFeaturedArtists is false

---

.circleci/config.yml
.secrets.baseline
scripts/secrets-generate-baseline

* This updates CI to use `artsy/detect-secrets:1.3.0`
* Regenerate the `.secrets.baseline` under the new version
Last Friday a new version of detect-secrets was [released](https://github.com/Yelp/detect-secrets/releases/tag/v1.3.0) and it trickled down into various projects that use 3rd party image, not Eigen 👏 (Thank you @pvinis). This caused issues in some projects when running in CI as the new version seems to be detecting additional secrets, not detected by v1.2.0.
After rebuilding the `baseline` [in Force](https://github.com/artsy/force/pull/10597) under the new version, I was going to announce in #dev asking developers to upgrade their local version of the tool however, I then realized that Eigen is pinned to v1.2.0. This updates Eigen CI to use the latest version of the tool so …

chore: CI uses detect secrets v1.3.0

---

src/app/Components/ConnectivityBanner.tsx
src/app/Containers/Inquiry.tsx
src/app/Scenes/Inbox/Components/ActiveBids/ActiveBid.tsx
src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
src/app/Scenes/Inbox/Screens/ConversationDetails.tsx
src/app/Scenes/MyBids/Components/SaleInfo.tsx
src/app/Scenes/MyBids/SaleInfo.tests.tsx
src/palette/Theme.tsx

This PR resolves [TX-521] and [TX-522]
This PR updates our conversation view to handle Orders with our new async/incomplete payment state `processing_approval`. In order to do this we need to 
- Add the state to the list of active order states in our queries 
- Show a little timestamped event for those states in the conversation view
Eigen currently uses our v2 theme's `yellow100` and this color is specified in several other components, including as a text color. In order to implement this new color I
- updated `yellow100` to its v3 version
- added `copper100` from our v2 theme [where the two values are aliases](https://github.com/artsy/palette/blob/main/packages/palette-tokens/src/themes/v2.tsx#L87-L106)
- changed previously-existing `yellow100` references to `copper100`.
Tests added for …

feat(TX-521): Erik/tx conversation support offers

---

src/app/Components/StickyTabPage/StickyTabPage.tsx
src/app/Components/StickyTabPage/StickyTabPageContext.tsx
src/app/Components/StickyTabPage/StickyTabPageTabBar.tsx
src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx

This PR resolves [CX-2631]
On screens using the `StickyTabPage` when rotating the device, the content offset doesn't adjust automatically. This can lead to situations where the offset is wrong and the content of two tabs is shown (see screenshot).
This PR adds an effect that adjusts the offset when the screen width changes.
- Correct Sticky Tab Page offset when rotating the device - ole
-
-
-
</details>
[app state …

fix: Correct Sticky Tab Page offset when rotating the device

---

src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/app/Scenes/Sale/Components/NewSaleLotsList.tsx
src/app/Scenes/Sale/Sale.tsx
src/app/relay/middlewares/cacheMiddleware.ts

Slack thread to get more context: https://artsy.slack.com/archives/C9SATFLUU/p1659353897000399?thread_ts=1659342586.520909&cid=C9SATFLUU
If the lot has moved to the “bidding closed” state and the info about this lot is in the cache (for example, the user previously opened this sale screen), then this lot will not be displayed at the end of the list
I think it’s related to [this problem](https://github.com/artsy/eigen/pull/6612#issue-1204382195) with `loadMore` (when only data from the cache is used and the fresh data received by the request is ignored) and some problem with cursor paginations/cache.
For example, in the first attached video, you can observe that **lot 7** and **lot 8** are not displayed at the end of the list until we manually update the data (but even …

fix: cache problems for sale screen

---

src/app/Scenes/Inbox/Components/Conversations/Message.tsx

This PR partially resolves [NX-3251]
We only have attachments preview on iOS, Android has no module for that, in order to keep the attachments being opened from a conversation we are reproducing the same behavior from the conversation details attachments.
https://user-images.githubusercontent.com/15792853/184088945-5eea9e32-70ee-43bb-8539-e732743a2456.mov
-
-
-
-
- conversation attachments opening - araujobarret
-
</details>
[NX-3251]: https://artsyproduct.atlassian.net/browse/NX-3251?atlOrigin=eyJpIjoiNWRkNT …

fix(NX-3251): attachment open inside conversation android

---

src/app/Scenes/OrderHistory/OrderHistory.tsx
src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
src/app/utils/getOrderStatus.ts

This PR resolves [TX-575] by including orders with the 'processing approval' state in a user's order history.
- The order history view (in a user's settings) should show an order whose state is processing approval.
- The easiest way to check this is to create a wire transfer order, then accept it from the partner's side. This will trigger the `'processing_approval'` state until it is manually confirmed via the exchange admin interface.
<details><summary>Before and after:</summary>
</details>
- Show data for new states in the user's order history view
-
-
-
</details> …

feat: Show orders while processing approval

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsPromotionalCard.tsx

This PR resolves [CX-2751]
- Dismiss career highlights modal after adding a new artwork
https://user-images.githubusercontent.com/11945712/184327290-71a987be-27db-4397-b464-d56f7ef642a5.mov
-
-
#nochangelog
[CX-2751]: https://artsyproduct.atlassian.net/browse/CX-2751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2751): dismiss career highlights modal after adding a new artwork

---

src/app/Scenes/Favorites/FavoriteArtworks.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx

This PR resolves [CX-2754]
- the alignment of empty states is fixed, the content is on the centre of the screen
-
- fix alignment of MyC/Insights/Saved empty states -daria 
-
-
-
</details>
[CX-2754]: https://artsyproduct.atlassian.net/browse/CX-2754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2754): MyC / Insights / Saved empty states are not aligned [Android]

---

src/app/Containers/Inbox.tsx
src/app/Scenes/Inbox/Components/Conversations/Conversations.tsx

The last element of Inbox conversations wasn't fully shown on iOS and Android as well, this PR addresses this issue plus removes a border only shown on Android from the `Inbox` text element.
This PR resolves [NX-3269]
*Android*
https://user-images.githubusercontent.com/15792853/184616869-ad3b3a8e-22eb-4052-b376-dc855ccb8aaf.mov
*iOS*
https://user-images.githubusercontent.com/15792853/184616995-02aeb1d2-7f20-4ee0-8ba8-0c5c4d7befa5.mov
-
-
- conversations items respect the bottom tab height - araujobarret
-
-
-
</details>
[docs]: …

fix(NX-3269): conversations list all shown on the list

---

src/palette/organisms/screenStructure/Screen.tsx

This PR resolves [GRO-1217]
-
-
- make back button hitslop of screen header bigger - gkartalis
-
-
-
</details>
[GRO-1217]: https://artsyproduct.atlassian.net/browse/GRO-1217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GRO-1217): back button is difficult to interact with

---

src/app/Scenes/Onboarding/OnboardingV2/Components/AnimatedFadingPill.tsx
src/app/Scenes/Onboarding/OnboardingV2/Components/OnboardingQuestionTemplate.tsx
src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingQuestionTemplate.tests.tsx

This PR resolves [GRO-1205]
On the heels of @pvinis PR adding reanimated to eigen, this PR leverages the new library to smooth out onboarding animations. 
- Animation should be smooth no matter which answers are selected (no “jumping”)
- Answers should be immediately visible upon backward navigation
- Answers should never disappear until the user presses next
-
-
-
-
-
</details>
[GRO-1205]: https://artsyproduct.atlassian.net/browse/GRO-1205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

feat(GRO-1205):replace button animations and smooth out page transitions

---

src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
src/palette/atoms/BackButton/BackButton.tsx
src/palette/organisms/screenStructure/Screen.tsx

This PR resolves [GRO-1225]
https://user-images.githubusercontent.com/21178754/185610151-4014745c-1316-4fbb-8463-96286f49e105.mp4
-
-
- onboarding follows banner appearing after user has followed a gene - gkartalis
-
-
-
</details>
[GRO-1225]: https://artsyproduct.atlassian.net/browse/GRO-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: find follows banner should appear after the user has followed gene

---

src/app/Components/ArtworkFilter/Filters/KeywordFilter.tsx

This PR fixes both launch blocking issues related to the artist auction results
[CX-2800]  Artist Auction Result Keyword filter causes constant refetching
[CX-2765]  Unable to execute search as keyboard keeps collapsing
https://user-images.githubusercontent.com/11945712/186146546-29c98ed8-23fc-45e7-b3c6-b83537766791.mov
-
-
- Unable to execute search as keyboard keeps collapsing on auction results screen - mounir
- Spinner keeps on loading on auction results screen - mounir
-
-
-
</details>
[CX-2800]: …

fix: auction results launch blocking bugs

---

src/app/Components/ArtworkGrids/utils/index.ts
src/app/Components/ArtworkGrids/utils/layout.ts
src/app/Components/ArtworkGrids/utils/sections.ts
src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
src/app/Scenes/Onboarding/OnboardingV2/Components/OnboardingResultsGrid.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingArtistsOnTheRise.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingCuratedArtworks.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingGene.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingTopAuctionLots.tsx
src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingGene.tests.tsx

This PR resolves [GRO-1235]
This PR creates a custom grid to circumvent some of the current limitations w/ our navigation stack, while also allowing users to save artworks during the onboarding flow.
https://user-images.githubusercontent.com/14044896/186535353-e94b1f9c-d004-4fb2-ba9c-fb4dc97363dd.mp4
- Displays artworks in a fashion identical to the in-app artwork grid
- Does not link to artist or artwork pages
- Has a functional “save” button for artworks
-
-
-
-
-
</details>
[GRO-1235]: …

feat(GRO-1235): create a custom onboarding results grid

---

.secrets.baseline
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
src/palette/elements/Message/Message.tsx

Show submission banner inside edit artwork flow 
https://user-images.githubusercontent.com/11945712/187166667-56e9d0f4-f327-41af-a6d0-270d620e2993.mov
-
-
- show artwork is a submission banner while editing it - mounir
-
-
-
</details>

chore: show submission banner inside edit artwork flow

---

package.json
src/palette/elements/LineGraph/LineGraphChart.tsx
src/palette/elements/LineGraph/ScatterPointsContainers.tsx
yarn.lock

- Following product decision to remove support for floating label and revert to static label on the Median Sale Price chart, this PR mostly removes all the logic, Components, scaling etc that was previously necessary to support a floating label on scroll.
https://user-images.githubusercontent.com/18648835/188136094-49ae366b-71de-45c3-a3a2-27d9c4102a4b.mp4
This PR resolves [CX-2818]
-
-
- Remove support for floating label in LineGraph - kizito
-
-
-
</details>
[CX-2818]: …

feat(CX-2818): Remove support for floating label in LineChart

---

src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
src/app/Scenes/MyCollection/Screens/Insights/providers/MedianSalePriceChartDataContext.tsx
src/palette/elements/LineGraph/LineGraphHeader.tsx

- This PR ensures that medium must have at least one median price per year to be included in the categories presented in the median sale chart for artists
https://user-images.githubusercontent.com/18648835/188860371-53f5f971-7691-4090-9e51-e800094f3c0b.mp4
This PR resolves [CX-2908]
-
-
- Exclude Categories without data from MedianSaleChart - kizito
-
-
-
</details>
[CX-2908]: https://artsyproduct.atlassian.net/browse/CX-2908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

fix(CX-2908): Exclude Categories without data from MedianSaleChart

---

src/app/Components/SearchImageHeaderButton/SearchImageHeaderButton.tests.tsx
src/app/Components/SearchImageHeaderButton/SearchImageHeaderButton.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/ReverseImage/ReverseImage.tsx
src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageArtworksRail.tsx
src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageMultipleResults.tsx
src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
src/app/Scenes/ReverseImage/types.ts
src/app/Scenes/Show/Show.tsx

Cohesion PR: artsy/cohesion#348
This PR resolves [FX-4209]
Reverse Image Search Analytics: https://www.notion.so/artsy/reverse-image-search-analytics-d8fcb365752f4cfe9ad326f2280e8b39
* A user taps the reverse image search button on a fair or show screen - `tappedReverseImageSearch`
* A user taps the flash button on the reverse image search camera screen - `tappedToggleCameraFlash`
* A user taps the library button on the reverse image search camera screen - `tappedPickImageFromLibrary`
* A user searches with a reverse image query with results (for single and multiple results) - `searchedReverseImageWithResults`
* A user searches with a reverse image query with no results - `searchedReverseImageWithNoResults`
* A user selects an artwork from reverse image search results - …

feat(FX-4209): setup analytics for reverse image

---

ios/Artsy/ArtsyUIFonts/UIFont+ArtsyFonts.m

Fixes a crash on font registration for iOS 16. 
With the recent iOS 16 update in Xcode the font registration seems to be returning a different error code causing a crash if it is not handled, not sure if we are somehow registering twice but should be safe to check for existence and noop in this case. 
-
-
-
- Fix a crash on font registration for iOS 16 - brian
-
- 
</details>

fix: check for new error code to avoid duplicate registration

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx

Only show size in selected metric on My Collection artwork screen.
This PR resolves [CX-2893]
| cm | in |
| --- | --- |
|![Simulator Screen Shot - iPhone 13 Pro - 2022-09-19 at 15 28 25](https://user-images.githubusercontent.com/4691889/191029349-262e7f42-252d-4266-b5fd-66794b950d82.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-09-19 at 15 28 46](https://user-images.githubusercontent.com/4691889/191029378-4889d558-99f3-43f8-bad7-7dd1580bb80f.png)|
-
-
- Only show size in selected metric on My Collection artwork screen - ole
-
-
-
</details> …

fix: Only show size in selected metric on My Collection artwork screen

---

src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/Messages.tsx

Change copy on fraud prevention banner in conversations.
This PR resolves [NX-3277]
- Copy is changed to `To be covered by the Artsy Guarantee, always communicate and pay through the Artsy platform.`
-
-
-
-
</details>
[NX-3277]: https://artsyproduct.atlassian.net/browse/NX-3277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(NX-3277): change copy on fraud prevention banner

---

src/app/Components/Bidding/Components/Timer.tests.tsx
src/app/Components/Bidding/Components/Timer.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx

This PR resolves [NX-3299]
Just a simple copy change from "last minute", to "last-minute".
N/A
- All instances of "last minute" should now be replaced with "last-minute".
#nochangelog
[NX-3299]: https://artsyproduct.atlassian.net/browse/NX-3299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(NX-3299): Hyphenate 'last-minute'

---

src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
src/app/Scenes/Onboarding/OnboardingV2/Components/MarketingCollectionHeader.tsx
src/app/Scenes/Onboarding/OnboardingV2/Components/OnboardingResultsGrid.tsx
src/app/Scenes/Onboarding/OnboardingV2/Hooks/useNextOnboardingScreen.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingArtistsOnTheRiseCollection.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingCuratedArtworksCollection.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingGene.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingMarketingCollection.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingTopAuctionLotsCollection.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingMarketingCollection.tests.tsx
src/app/store/config/features.ts

~~Will come back and finish the PR checklist on Monday (still gotta set up Android etc.). Opening for review though since I think it's ready for 👀 !~~ OK I think I got it! Phew!
This PR introduces a change (behind a feature flag) to source artworks from collections instead of genes during onboarding. It also removes the "follow" button from those screens since we don't support following collections
This PR resolves [FX-4251]
1. Log in as an admin
2. Flip the feature flag in the admin menu
3. Log out
4. Sign up for a new account
5. Select the following answers: "No, I have not collected before", "Developing my taste in art"
6. Select any of the resulting options to see a collection of artworks, now sourced from a collection instead of a gene
- Both with and without feature flag enabled, …

feat[FX-4251]: replace genes with collections in onboarding

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

This PR resolves [CX-2497]
This PR fixes the issue when discarding the new updates when editing an existing artwork in My Collection, so instead of removing all the old data, it resets the data to be the exact same when the user started editing
Edit an existing artwork from My Collection and update the some of the fields, then discard the new changes
- The artwork should return to its original data before editing
-
-
-
-
- update form reset when editing artwork from My Collection - mrsltun
</details>
https://user-images.githubusercontent.com/20655703/193264792-8c103351-3d38-48d6-8e63-d0210df401f0.mp4
https://user-images.githubusercontent.com/20655703/193264781-2fe204e …

fix(CX-2497): fix discarding when editing an artwork issue

---

src/app/store/config/features.ts

Marks the change from gene-backed works in onboarding to collection-backed works as ready for release in preparation for [the launch](https://www.notion.so/artsy/Curated-collections-launch-plan-8181a3ef06884b66a6b71664e65e5598).
Paired Echo PR: https://github.com/artsy/echo/pull/324
I did one more check on my device (flipping flag on -> going through onboarding) and it looked good to me.
#nochangelog
</details>

feat: mark onboarding collections ready for release

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/navigation/routes.tests.ts
src/app/navigation/routes.ts

This PR resolves [CX-2957]
This PR adds screen tracking to the artwork page.
**Bonus:** After adding the tracking event, I noticed that we are navigating using ids and not slugs, which makes sense to me, I then adjusted the routing accordingly since it was an id and not a slug
https://user-images.githubusercontent.com/11945712/194277457-7a745610-c7a3-4d68-99b1-d0d4777fd0ed.mov
-
-
-
- add screen tracking event to MyC artwork page - mounir
</details>
[CX-2957]: …

chore(CX-2957): add screen tracking to the artwork page

---

src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Activity/ActivityList.tsx
src/app/Scenes/Activity/ActivityTabPlaceholder.tsx

https://user-images.githubusercontent.com/3513494/193255621-e002be35-3edb-47a1-b5ee-2919d1dc9f8f.mp4
https://user-images.githubusercontent.com/3513494/193255646-c7b2d3c1-43f2-4db1-866a-16bf94028d28.mp4
This PR resolves [FX-4311]
-
-
- Loading states for Activity Panel - dimatretyak
-
-
-
</details>
[FX-4311]: https://artsyproduct.atlassian.net/browse/FX-4311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4311): Loading states for Activity Panel

---

src/app/Scenes/Activity/Activity.tests.tsx
src/app/Scenes/Activity/ActivityEmptyView.tsx
src/app/Scenes/Activity/ActivityList.tsx

| All tab | Alerts tab |
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-11 at 14 03 47](https://user-images.githubusercontent.com/3513494/195074044-46b82534-6a98-415e-8ed1-ef0f9485a3be.png) | ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-11 at 14 05 36](https://user-images.githubusercontent.com/3513494/195074262-10d25205-a863-433d-8945-707c0ab29681.png) | 
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-11 at 14 03 47](https://user-images.githubusercontent.com/3513494/195077257-2cf2e1d9-0ff7-4d6c-b2c0-d01f6a8ae725.png) | ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-11 at 14 05 …

feat(FX-4309): Empty states for Activity Panel

---

src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx

This PR resolves [CX-2827]
After a My Collection artwork is created, we show the image in the wrong aspect ratio for some time until the correct version of the artwork is available (Gemini takes a while to process the image). This issue can be fixed by always using the locally stored version of the artwork image (which we store). Through this, we avoid using image versions with a wrong aspect ratio (e.g. squared) during the image processing.
- Upload a new artwork and choose "Scream II, 2022" by "Somaya Critchlos" or a local image with an aspect ratio that is not square and check if the aspect ratio is correct after the artwork got uploaded.
-
-
-
-
-
-
</details> …

fix: Always use local image if it exists in My Collection grid view

---

src/app/relay/middlewares/timingMiddleware.ts

Datadog pointed out that we were spending a lot on custom metrics over and above our contracted amount. We're generating ~22K/mo while our contract covers ~8K. Looking at [our recent usage](https://app.datadoghq.com/billing/usage?category=custom-metrics&data_source=billable&summary_month=2022-10&trends_start_date=2022-10-09&trends_time_frame=weekly), almost 70% of our custom metrics are labeled `eigen.graphql_request_duration.*` (or more than the total overage).
I think this is explained by the `id` tag which is unique to each request. Do we ever slice metrics by this tag? If not, I think we should drop it because each id value will be counted as a distinct metric, compounding our total volume.
Note that datadog also referred us to [this …

fix: remove request id from timing middleware tags, to avoid explosion in number of custom metrics

---

src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx

Added `Purchase Accepted` and `Purchase Expired` states in conversations.
Refactored tests because `renderWithWrappersLEGACY` is deprecated.
This PR resolves [NX-3253](https://artsyproduct.atlassian.net/browse/NX-3253)
Check if `Purchase Accepted` and `Purchase Expired` are showing up after a purchase is made in Conversations.
-
-
-
-
-
-
</details>

fix(NX-3253): add purchase expired and accepted states in conversation

---

.secrets.baseline
src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/FaqAndSpecialistSection.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx
src/app/Scenes/Artwork/Components/CommercialPartnerInformation.tests.tsx
src/app/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
src/app/__fixtures__/ArtworkBidAction.ts
src/app/store/config/features.ts

remove `AREnableCreateArtworkAlert` feature flag since it was released. Also these changes will be useful for [Reorganize Mobile Artwork Screen](https://artsyproduct.atlassian.net/browse/FX-4272) epic
-
-
-
-
-
- remove `AREnableCreateArtworkAlert` feature flag since it was released - dimatretyak
</details>

refactor: remove `AREnableCreateArtworkAlert` feature flag since it was released

---

src/app/Components/RetryErrorBoundary.tsx
src/app/store/config/features.ts
src/app/utils/renderWithPlaceholder.tsx

This PR resolves [CX-3015] 
-
-
-
- cleanup AREnableNotFoundFailureView -daria
</details>
[CX-3015]: https://artsyproduct.atlassian.net/browse/CX-3015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(CX-3015): cleanup AREnableNotFoundFailureView

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx

This PR resolves [CX-3001] 
- Before we successfully migrate previously requested price estimate to the Gravity DB, there is need to ensure that on Eigen the logic that relies on locally stored records of requests works in parity with the remote db stored ones. This entails that if there is no record of request from the Gravity, then fall back on the local one.
- Ensure Previously requested price estimate flow does not break - kizito
-
-
-
</details>
[CX-3001]: …

feat(CX-3001): Ensure Previously requested price estimate flow does not break

---

src/app/Components/ArticleCard.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/app/Components/Home/ArtistRails/ArtistCard.tsx
src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
src/app/store/config/features.ts
src/palette/elements/Cards/MediumCard.tsx

We want to release the new opaqueImageView component in all the grids except the new works for  you grid.
The reason for that is that when a user gets redirected to the new works for you grid from a notification or from an email, the grid with the new image is breaking.
This pr solves that.
Also renews the feature flag to make sure that we don't release it in older versions that have the bug
-
-
- disable new opaque image view on new-works-for-you grid - gkartalis
-
-
-
</details>

fix: disable new image comp on new-works-for-you grid

---

ios/ArtsyWidget/LatestArticles/LatestArticles+LargeView.swift
ios/ArtsyWidget/LatestArticles/LatestArticles+MediumView.swift

Something I had not considered is what the widget does when you tap on areas that are not wrapped with a link. Turns out the app will crash if I don't tell it what to do!
So with this PR all I'm doing is wrapping the "Latest Articles" text and the artsy logo in links directing the user to the home feed.
https://artsyproduct.atlassian.net/browse/GRO-1348

fix: broken tap areas in widget GRO-1348

---

src/app/Scenes/Activity/Activity.tests.tsx
src/app/Scenes/Activity/ActivityList.tsx
src/app/Scenes/Activity/utils/isArtworksBasedNotification.tests.ts
src/app/Scenes/Activity/utils/isArtworksBasedNotification.ts

This PR resolves [FX-4385] 
Related Force PR: artsy/force#11164
-
-
-
- Hide activity panel notifications without artworks - dimatretyak
</details>
[FX-4385]: https://artsyproduct.atlassian.net/browse/FX-4385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4385): Hide activity panel notifications without artworks

---

src/app/utils/volleyClient.tests.ts
src/app/utils/volleyClient.ts

Following up https://github.com/artsy/eigen/pull/7480, I noticed that Eigen metrics are namespaced as `eigen.*` or `eigen_staging.*`. However, this environment info is already captured in the automatic `env:[production|staging]` tag. This PR simplifies the client code to use a single, consistent service name, in line with our other services.
Post-release, [this dashboard](https://app.datadoghq.com/dashboard/8pd-u65-pb3/eigen-graphql-load-times) will need modifying to separate by the `env` tag instead of the namespace.

fix: use consistent 'eigen' service name for custom metric reporting

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateScreen.tsx

This PR fixes the back logic for when a user lands on the Request Price Estimate success screen by:
- Removing the Request Estimate form screen from the nav stack, that way when a user goes back they won't land on that screen again
- Moving the navigation to success screen only when a success response is gotten after requesting price estimate
- Pop user to the root MyCollection screen when they press `Back To My Collection` button
https://user-images.githubusercontent.com/18648835/197474541-2eb824d1-182a-4724-a045-7b3cfc656c12.mov
https://user-images.githubusercontent.com/18648835/197474635-3672687d-6bae-402f-9928-ef05006bde0b.mov
https://user-images.githubusercontent.com/18648835/197474772-af11f1bc-e0a7-418c-a6fd-948ca04c72f6.mp4 …

fix(Request Price Estimate): fix back gesture and back button handling

---

src/app/store/config/features.ts
src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx

Replacing the `isStaging` hook with a dev toggle to be able to render the label on top of the new image component
-
-
-
- add dev toggle for adding label on new opaqueImageView - gkartalis
</details>

refactor: replacing isStaging with devtoggle

---

src/app/Scenes/Home/Components/ContentCards.tsx
src/app/Scenes/Home/Home.tsx

I def missed that items on the homefeed have a standard margin so this PR uses that value to make the content cards look more consistent!
https://artsyproduct.atlassian.net/browse/GRO-1365

fix: Use standard separator height for braze content cards GRO-1365

---

src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/Artist/Artist.tsx

- 
-
-
- "Recently Added" sort option should be preselected when the user clicks on an notification and navigates to the artist artworks screen - dimatretyak
</details>

feat(FX-4418): "Recently Added" sort option should be preselected when the user clicks on an notification

---

src/app/Scenes/Artwork/Components/Questions.tsx
src/app/Scenes/Fair/Components/FairHeader.tsx

This PR resolves [FX-4420] 
Fixes some visual glitches observed while using the Fair app at IFPDA Print Fair
- Minor style updates to fair screen
</details>
[FX-4420]: https://artsyproduct.atlassian.net/browse/FX-4420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

style: minor visual glitches in Fair app

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tsx

This PR resolves [CX-3096] 
- After sending request price estimate, when user taps on Back to My Collection they should return to artwork screen and not My Collection screen
https://user-images.githubusercontent.com/18648835/198990740-f5aae550-04e8-4fce-8a63-b56eee9a197c.mov
- Go back to artwork not MyCollection after sending request price estimate - kizito
-
-
-
</details>
[CX-3096]: https://artsyproduct.atlassian.net/browse/CX-3096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

fix(CX-3096): Go back to artwork not MyCollection after sending request price estimate

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx

This PR resolves [CX-3100] 
This PR adjusts the display logic for the price estimate section on the artist screen to always show a message when a price estimate has been sent for the artwork.
[PR implementing the same in Force](https://github.com/artsy/force/pull/11279)
- Always show a message when a price estimate has been sent - ole
-
-
-
</details>
[CX-3100]: https://artsyproduct.atlassian.net/browse/CX-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Always show message when a price estimate has been sent

---

src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
src/app/utils/getOrderStatus.tests.ts
src/app/utils/getOrderStatus.ts

This PR resolves [PX-5333](https://artsyproduct.atlassian.net/browse/PX-5333)
Discovered that the counter offer modal was not popping up for orders that were being shipped with artsy shipping. Instead, collectors were redirected to the user/purchases/<id> receipt screen with no way to view/submit counter offers, getting stuck forever.
It is because of this mapping that is going on to determine where to direct the user on [this](https://github.com/artsy/eigen/blob/main/src/app/Scenes/OrderHistory/OrderHistoryRow.tsx#L84-L98) button press. Since we were not accounting for `draft` shipments, this was always returning `undefined` and incorrectly directing the user to the `user/purchases/<id>`receipts page. We started building "draft" shipments as part of artsy shipping to collect metadata …

fix: counter offer flow broken for artsy shipping orders

---

src/app/Scenes/Home/Components/NewWorksForYouRail.tsx

After some surprising results and some scratching of heads, we have decided to double the number of artwork recs on the new for you page.
Investigation here:
https://www.notion.so/artsy/Investigate-artwork-rec-differences-eb461849f7d149518497a0ba98c491c5
Chatter here:
https://artsy.slack.com/archives/C033E79AQG4/p1667232723970619
https://artsyproduct.atlassian.net/browse/GRO-1386
/cc @artsy/grow-devs @isakelaris

feat: Double new for you recs GRO-1386

---

src/app/Scenes/Home/Components/ContentCards.tsx

Turns out it's pretty easy to get at the font scale for users that have increased it! Docs here:
https://reactnative.dev/docs/pixelratio#getfontscale
And so @pvinis had the idea to just use this scale to grow the content card height and that does in fact ensure that the button shows up.
<details>
<summary>screenshots</summary>
</details>
https://artsyproduct.atlassian.net/browse/GRO-1403

fix: Improve support for dynamic text in content cards GRO-1403

---

.secrets.baseline
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx

This PR resolves [CX-2727] 
Initialize artist name input field in MyC upload flow.
-
-
-
-
</details>
[CX-2727]: https://artsyproduct.atlassian.net/browse/CX-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Initialize artist name input field in MyC upload flow

---

src/app/Scenes/Activity/ActivityItem.tsx

| ![before](https://user-images.githubusercontent.com/3513494/199778177-9aef7d04-c4cf-4798-8f3b-4cef22b3cbc8.png) | ![after](https://user-images.githubusercontent.com/3513494/199778254-bcfdcd05-cd04-453d-8903-68ea172ef76d.png) |
-
-
-
- small improvements for activity item images - dimatretyak
</details>

chore: small improvements for activity item images

---

src/app/Scenes/Activity/ActivityEmptyView.tsx
src/app/Scenes/Activity/ActivityList.tsx

https://user-images.githubusercontent.com/3513494/199784079-e9034abb-2986-443b-92ea-7e53d986f442.mp4
https://user-images.githubusercontent.com/3513494/199786402-fe116b89-31fb-49a7-8f4a-570f5f62ac35.mp4
-
-
-
- add ability to refetch notifications for empty state - dimatretyak
</details>

feat: add ability to refetch notifications for empty state

---

src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Artwork.tsx

This PR resolves [FX-4280] 
Initial PR: artsy/eigen#7495
> Show the Shipping & Taxes section unless the work is not for sale or the work is at auction (in which case we'd have that other copy above).
Based on [this comment](https://artsy.slack.com/archives/C9SATFLUU/p1667389698306379?thread_ts=1667388418.130119&cid=C9SATFLUU), we should hide the "Shipping and taxes" section if artwork is in auction
https://user-images.githubusercontent.com/3513494/199955447-3a8d2c9d-fdce-414a-b34d-9a4574a7c0f5.mp4
https://user-images.githubusercontent.com/3513494/199955500-b38bd3b7-7338-47c2-94e5-e5431f84a573.mp4
-
-
-
-
</details> …

chore: hide shipping and taxes section if artwork is in auction

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistSearchResult.tsx
src/app/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx

Show initials for artists without images in the My Collection artwork form.
-
-
-
-
</details>

fix: Show initials for artists without images in the MyC

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx

This PR resolves [CX-3126] 
We need to also clear the artist when the user discards the changes to be able to later show the input field for the artist name.
- Reset artist when discarding changes in My Collection form - ole
-
-
-
</details>
[CX-3126]: https://artsyproduct.atlassian.net/browse/CX-3126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Reset artist when discarding changes in My Collection form

---

src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
src/app/Scenes/SellWithArtsy/utils/submissionModelState.tsx
src/app/store/migration.tests.ts
src/app/store/migration.ts

This PR resolves [CX-3127] 
This PR stores the ID of the last submission to ensure that only the artwork in My Collection with this ID displays the image of the submission. Without this correction, any artwork in My Collection without an image set would display the image of the last submission.
- Adjust image logic for My Collection after submitting an artwork - ole
-
-
-
</details>
[CX-3127]: https://artsyproduct.atlassian.net/browse/CX-3127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

fix: Adjust Submission My Collection artwork image logic

---

.secrets.baseline
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx

This PR resolves [CX-2728] 
Initialize artwork title input when skipping the artwork selection in the My Collection artwork flow
- Initialize artwork title input when skipping artwork selection - ole
-
-
-
</details>
[CX-2728]: https://artsyproduct.atlassian.net/browse/CX-2728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Initialize artwork title input when skipping artwork selection

---

src/app/relay/createEnvironment.ts

This reverts commit 04853d3cfacc4d285a1b4c8ff7f52d9f37303631.
Reverts this commit that was accidentally committed to main, after this our build-test-js step started failing on main. Not sure why, will have to investigate. 
https://github.com/artsy/eigen/commits/main
-
-
-
-
</details>

fix: Revert "chore: only use metaphysicsExtensionsLoggerMiddleware on dev" #trivial

---

src/app/Components/ReadMore.tests.tsx
src/app/Components/ReadMore.tsx
src/app/Scenes/Show/Screens/ShowMoreInfo.tsx

[Slack thread](https://artsy.slack.com/archives/C02BAQ5K7/p1667866746452839) for more context.
The ReadMore component broke the app when it was trying to render lists due to a problem with the markdown dependency that we are using (opened an [issue](https://github.com/ariabuckles/simple-markdown/issues/112) a while ago but no one has replied..)
The solution is to prevent the component from rendering the markdown "list" (when it sees dashes it tries to render a markdown list but fails) and default to rendering it as a paragraph which is okay for now (see screenshot below)
- fixed markdown lists from breaking readmore component - gkartalis
-
-
-
</details> …

fix: prevent markdown lists from breaking the readmore component

---

src/app/Scenes/Artwork/Components/ArtworkMakerTitle.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkMakerTitle.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx

Small refactor that removes the artist name component logic from ArtworkTombstone
#nochangelog
</details>

refactor: move ArtworkMaker to different component

---

scripts/update-echo

Following the install docs, after running `yarn setup:artsy` the process crashed due to prettier not being installed globally on my system: 
This PR swaps the `yarn` invocation with `npx`, which is designed for these kinds of cases where packages are used outside of the normal package.json flow.

fix(setup): Invoke prettier via npx to avoid error during repo setup

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

This PR resolves [CX-3089] 
Do not allow submiting the artwork form multiple times.
-
-
-
-
</details>
[CX-3089]: https://artsyproduct.atlassian.net/browse/CX-3089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Do not allow submiting the artwork form multiple times

---

ios/Artsy.xcodeproj/project.pbxproj
src/app/Scenes/Onboarding/OnboardingLoginWithOTP.tsx

This PR resolves [MOPLAT-489] 
Final design pending. Logic ready.
https://user-images.githubusercontent.com/100233/202164088-2cb11f72-2f29-437e-909e-3f56d9bb2dc7.mov
-
-
-
-
</details>
[MOPLAT-489]: https://artsyproduct.atlassian.net/browse/MOPLAT-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add a way to enter recovery codes

---

src/app/Scenes/Artwork/Artwork.tests.tsx

this test has been randomly failing for the last 2 weeks. I'm disabling it for now, and we can fix it and enable it later.
(cc @gkartalis, but you are out today, so don't worry for now 😄)
-
-
-
-
</details>

fix: disable flaky test

---

src/app/Scenes/Artwork/Artwork.tests.tsx

Forgot that one after #7698
-
-
-
-
</details>

fix: second flaky test

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
src/app/Scenes/Search/UserPrefsModel.tsx
src/app/store/RecentPriceRangesModel.ts
src/app/store/migration.tests.ts
src/app/store/migration.ts

This PR resolves [FX-4440] 
https://user-images.githubusercontent.com/3513494/203063717-5cce14ab-ff6b-4257-89d5-6e8f2756f618.mp4
- Pin Collector Profile-sourced price range as the last "recent" price range - dimatretyak
-
-
-
</details>
[FX-4440]: https://artsyproduct.atlassian.net/browse/FX-4440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4440): Pin Collector Profile-sourced price range as the last "recent" price range

---

src/app/Scenes/Search/CuratedCollectionItem.tsx
src/app/Scenes/Search/CuratedCollections.tests.tsx
src/app/Scenes/Search/CuratedCollections.tsx

This PR resolves [FX-4446]
Add analytics tracking when user taps on a curated collection on the Search tab.
https://user-images.githubusercontent.com/3934579/203538018-d99281d2-a5a6-4713-886d-d1190981cdd8.mp4
-
-
-
-
</details>
[FX-4446]: https://artsyproduct.atlassian.net/browse/FX-4446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4446): tracks tap on curated collection

---

src/app/Components/Home/ArtistRails/ArtistCard.tsx
src/app/Scenes/Search/PopularSearches.tsx
src/app/Scenes/Search/Search.tsx
src/app/Scenes/Search/TrendingArtists.tests.tsx
src/app/Scenes/Search/TrendingArtists.tsx
src/app/Scenes/Search/components/TrendingArtistCard.tsx
src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
src/app/Scenes/Search/useDisplayCuratedCollections.ts
src/app/store/config/features.ts

This PR resolves [FX-4452] 
https://user-images.githubusercontent.com/3513494/203583781-d1191052-ef36-4291-ad1e-f29c60ff61d9.mp4
https://user-images.githubusercontent.com/3513494/203583854-0287c63a-51ae-448b-a1c1-14c0636e2696.mp4
- Display trending artists on search screen - dimatretyak
-
-
-
</details>
[FX-4452]: https://artsyproduct.atlassian.net/browse/FX-4452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4452): display trending artists

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tests.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx

This PR resolves [CX-3099] 
- This PR ensures we don't add visual clue that displays the "The new artwork added to your Collection" banner when a user submits an Artwork that is already in their MyCollection
- Do not display Banner after submitting a MyCollectionArtwork - kizito
-
-
-
</details>
[CX-3099]: https://artsyproduct.atlassian.net/browse/CX-3099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix(CX-3099): Do not display Banner after submitting a MyCollectionArtwork

---

src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
src/setupJest.ts

This PR resolves [CX-2493] 
This PR fixes a bug where NoImage Component continues to show after a user adds new images to a MyCollectionArtwork that previously had no images.
https://user-images.githubusercontent.com/18648835/203365183-d8fa4b3a-6e22-46d1-96fe-29cae35ba2be.mp4
https://user-images.githubusercontent.com/18648835/203365834-c3b72ddd-57ad-44a7-ac57-6dadcdb76f3e.mov
- Fix Photo Added in Edit mode not updated on MyCollectionArtwork - kizito
-
-
-
</details>
[CX-2493]: …

fix(CX-2493): Fix Photo Added in Edit mode not updated on MyCollectionArtwork

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx

The spacing between the histogram and the latest price ranges has been reduced, since on devices with a small screen, the price ranges were placed too close to the bottom container
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-11-25 at 14 45 41](https://user-images.githubusercontent.com/3513494/203979493-7f355844-220f-463c-8f6a-ca31ebaa1a11.png) | ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-11-25 at 14 46 13](https://user-images.githubusercontent.com/3513494/203979519-1540fec3-01c5-45cc-9090-89b20e619ec2.png) | 
#nochangelog
</details> …

chore: decreased padding between the histogram and the latest price ranges

---

src/app/Scenes/Search/CuratedCollectionItem.tsx
src/app/Scenes/Search/CuratedCollections.tests.tsx
src/app/Scenes/Search/TrendingArtists.tests.tsx
src/app/Scenes/Search/TrendingArtists.tsx
src/app/Scenes/Search/components/TrendingArtistCard.tsx

Addressed PRs: [FX-4453], [FX-4446]
* use `tappedArtistGroup` for trending artists
* use `tappedCollectionGroup` for curated artsy collections
https://user-images.githubusercontent.com/3513494/203989295-27be5aee-f735-451d-825f-7e15957d97f5.mp4
#nochangelog
</details>
[FX-4453]: https://artsyproduct.atlassian.net/browse/FX-4453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FX-4446]: https://artsyproduct.atlassian.net/browse/FX-4446?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

refactor: analytics for search screen

---

src/app/Components/OpaqueImageView/createGeminiUrl.tsx

This PR resolves [MOPLAT-482] 
Rounding the heights and widths that we send to gemini to avoid sending numbers with as much as 12 decimal points. This will help us take advantage of the Gemini cache
- 
-
-
- round up height/width sizes that we send to gemini - gkartalis
</details>
[MOPLAT-482]: https://artsyproduct.atlassian.net/browse/MOPLAT-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: round up height/width sizes that we send to gemini

---

src/app/Scenes/Search/CuratedCollectionItem.tsx
src/app/Scenes/Search/CuratedCollections.tsx
src/app/Scenes/Search/Search.tests.tsx
src/app/Scenes/Search/Search.tsx
src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx

This PR resolves [FX-4470] 
https://user-images.githubusercontent.com/3513494/203847369-37dafe41-b003-4f57-915d-ea85731d0492.mp4
- Convert Artsy Curated Collections list into a rail - dimatretyak
-
-
-
</details>
[FX-4470]: https://artsyproduct.atlassian.net/browse/FX-4470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-4470): Convert Artsy Curated Collections list into a rail

---

src/app/navigation/navigate.tests.tsx
src/app/navigation/navigate.ts

Follow-up to https://github.com/artsy/eigen/pull/7705
Fixes a bug where marketing deeplinks would open safari if app was in a killed state.
So it turns out that our deeplinks are being handled by both typescript and native code. 
In my testing when the app is killed the deeplink code here gets fired and calls navigate: 
https://github.com/artsy/eigen/blob/f462ca578be55a3e83c946941d5e118c0b80169a/src/app/utils/useDeepLinks.ts#L17
And when the app is in the background it is handled here and calls navigate: 
https://github.com/artsy/eigen/blob/f462ca578be55a3e83c946941d5e118c0b80169a/ios/Artsy/App/ARAppActivityContinuationDelegate.m#L49
I am guessing we can move this all to typescript and it is probably the reason we get double navigation on deeplinks from time to time …

fix: handle marketing deeplinks on typescript side

---

src/app/Components/OpaqueImageView/OpaqueImageView.tsx

Marks old opaqueImageView as deprecated in order to use the palette one as the preferred one 
-
-
-
- add deprecated flag to old opaque image view - gkartalis
</details>

chore: add deprecated flag to old opaque image view

---

src/app/AppRegistry.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkActions.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
src/app/navigation/navigate.tests.tsx
src/palette/atoms/BackButton/BackButton.tsx

This PR resolves [FX-4274] 
- creates new header for artwork screen
- hides it behind a ff
- bonus: add accessibility props to palette back buttons
|With ff false (same as before) |With ff true (after)|
|---|---|
|https://user-images.githubusercontent.com/21178754/204510396-ef9b65b3-42fa-468c-b69c-f302a5205f44.mp4|https://user-images.githubusercontent.com/21178754/204510438-4334d6e2-ae5e-48be-9ed8-637ddaa1c07b.mp4|
When artwork is sold
|Android|iOS|
|---|---|
|![Screenshot_1669720388](https://user-images.githubusercontent.com/21178754/204514708-fabff24e-3de9-42f1-a048-9360e031809c.png)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-11-29 at 12 12 04](https://user-images.githubusercontent.com/21178754/204514577-82306d13-48c1-4367-97a3-f56655beeae4.png)| …

feat(FX-4274): Artwork screen header

---

src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/ArtworkRail/LargeArtworkRail.tsx
src/app/Components/ArtworkRail/SmallArtworkRail.tsx
src/app/Scenes/Home/Components/HomeHeader.tsx
src/app/Scenes/Home/Home.tsx
src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tests.tsx

This PR resolves [CX-3188] 
Fix padding issue on Large rail
https://user-images.githubusercontent.com/11945712/204767812-6bc841cd-63c8-44a4-b898-6ff7e5acb952.mov
-
-
-
-
</details>
[CX-3188]: https://artsyproduct.atlassian.net/browse/CX-3188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3188): padding issue on large rail

---

src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx

This PR resolves [CX-3188] 
This PR adds the save icon to artwork grids
- Add save icon to artworks grid - mounir
-
-
-
</details>
[CX-3188]: https://artsyproduct.atlassian.net/browse/CX-3188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add save icon to artwork grids

---

package.json
src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/utils/calculatePhotoSize.ts
yarn.lock

This PR resolves [CX-3187] 
Blocked by https://github.com/artsy/cohesion/pull/374
This PR adds a track to when the file size is exceeded
-
-
-
-
</details>
[CX-3187]: https://artsyproduct.atlassian.net/browse/CX-3187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: track file size exceeded

---

package.json

This PR raises an alert on Podfile.lock changes instead of installing pods. This will still let those unfamiliar with Eigen know that they need to run `yarn install:all` without running it for them. 
-
-
-
- raise alert on podfile change instead of installing pods - mounir
</details>

chore: raise alert on podfile change instead of installing pods

---

index-common.js
package.json
src/app/Components/ArtsyWebView.tests.tsx
src/app/Components/ArtsyWebView.tsx
src/app/navigation/routes.tests.ts
src/app/navigation/routes.ts
src/setupJest.ts
yarn.lock

This PR resolves [MOPLAT-524] 
- `parseURL` was throwing `deprecated` issues, so I replaced it with the recommendation of just `URL`, and added the polyfill since RN doesn't have the complete thing.
- moved tests to new helpers, and fixed some tests that were green but not testing actually, since things were misconfigured, like `waitFor(() => { expect(..`
- moved the logic from `onShouldStartLoadWithRequest` to `onNavigationStateChange`. Some context [here](https://artsy.slack.com/archives/C02NAJ2CGLW/p1669726228778479), but the main idea is that artsy.net is an SPA, so in the webview the `onShouldStartLoadWithRequest` is mostly not called because of that. The right place to intercept navigation is on `onNavigationStateChange`, which is called always, for every navigation. …

fix: webview should move us to native screens if we have them

---

src/app/Scenes/Artwork/Artwork.tests.tsx

This PR resolves [FX-4394] 
Attempt to fix the flaky tests on the artwork page
-
-
-
- fix the flaky tests on the artwork page - gkartalis
</details>
[FX-4394]: https://artsyproduct.atlassian.net/browse/FX-4394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: flaky tests on artwork page

---

src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx

This PR resolves [FX-4486] 
add sale message for not for sale artworks
> ⚠️ note that the sale message from the commercial information section that is being displayed under the new one (which is the one under the artwork title and artist name) is to be removed in another pr
|Screenshots|||
|---|---|---|
|![Simulator Screen Shot - iPhone 14 - 2022-12-02 at 16 59 12](https://user-images.githubusercontent.com/21178754/205334023-aea617b7-af27-4d63-98b3-a45f1b37ace2.png)|![Simulator Screen Shot - iPhone 14 - 2022-12-02 at 16 59 21](https://user-images.githubusercontent.com/21178754/205334011-4d6c2f96-fcf8-44d4-b3fa-1cfe9ae0aeaa.png)|![Simulator Screen Shot - iPhone 14 - 2022-12-02 at 16 59 03](https://user-images.githubusercontent.com/21178754/205333997-0360de60-a4fd-46bd-96dd-bd939db808a9.png) …

feat(FX-4486): add sale message for not for sale artworks

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
src/app/Scenes/BottomTabs/BottomTabs.tsx
src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
src/app/Scenes/BottomTabs/setBottomTabVisibilityForCurrentScreen.ts
src/app/Scenes/BottomTabs/useBottomTabBarHeight.ts
src/app/navigation/NavStack.tsx

This PR resolves [FX-4305] 
https://user-images.githubusercontent.com/3513494/205075962-6e138520-1512-43ee-b33b-6ce760de1e22.mp4
https://user-images.githubusercontent.com/3513494/205077788-d45d93b6-cf39-4449-b8df-f309818a7c95.mp4
-
-
-
- add ability to hide bottom tabs on specific screen - dimatretyak
</details>
[FX-4305]: https://artsyproduct.atlassian.net/browse/FX-4305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4305): add ability to hide bottom tabs on specific screen

---

src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx

This PR resolves [FX-4477]
Add artworks counts to activity panel notifications
https://user-images.githubusercontent.com/3934579/205677203-441d7382-8778-499f-8058-91f4dcd3bdc2.mp4
- Added artworks counts to activity panel notifications
-
-
-
</details>
[FX-4477]: https://artsyproduct.atlassian.net/browse/FX-4477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4477): add counts to activity panel items

---

src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
src/app/Scenes/Artwork/Components/BelowTheFoldPlaceholder.tsx

This PR resolves [FX-4489] 
https://user-images.githubusercontent.com/3513494/205970514-0fcf0620-0c29-419b-b25e-f0673a3a29ba.mp4
-
-
-
- add loading placeholders for redesigned artwork screen - dimatretyak
</details>
[FX-4489]: https://artsyproduct.atlassian.net/browse/FX-4489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4489): add loading placeholders for redesigned artwork screen

---

src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx

Always use the local image for My Collection images when available to avoid images being shown with a wrong aspect ratio during image processing.
- Fix My Collection grid view image stretching - ole
-
-
-
</details>

fix: Always use local image for My Collection images when available

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx

This PR resolves [CX-3237] 
Reset My Collection form after skipping the artist selection to avoid creating an artwork with a wrong artist.
-
-
-
-
</details>
[CX-3237]: https://artsyproduct.atlassian.net/browse/CX-3237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Reset My Collection form after skipping artist selection

---

src/app/Scenes/Home/Components/ActivityIndicator.tests.tsx
src/app/Scenes/Home/Components/ActivityIndicator.tsx
src/app/Scenes/Home/Components/HomeHeader.tests.tsx
src/app/store/config/features.ts

This PR resolves [FX-4498] 
Echo PR: artsy/echo#381
-
-
-
- Remove `AREnableActivity` feature flag - dimatretyak
</details>
[FX-4498]: https://artsyproduct.atlassian.net/browse/FX-4498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(FX-4498): remove AREnableActivity feature flag

---

src/app/Scenes/Home/Home.tsx

This is a sibling PR of https://github.com/artsy/metaphysics/pull/4605 and just updates Eigen to label the artists rail with Trending and use that type when querying MP. That other PR does the actual work of resolving differently.
https://artsyproduct.atlassian.net/browse/GRO-1381

feat: Use trending artists on home feed GRO-1381

---

src/app/Components/ArtworkFilter/Filters/ArtistIDsSaleArtworksOptionsScreen.tests.tsx
src/app/Components/ArtworkFilter/Filters/ArtistIDsSaleArtworksOptionsScreen.tsx
src/app/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx

This PR resolves [FX-4211] 
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-12-12 at 19 18 08](https://user-images.githubusercontent.com/3513494/207109749-ca1875a7-3807-4b7d-9873-5c206afad32f.png) | ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-12-12 at 19 18 16](https://user-images.githubusercontent.com/3513494/207109714-98f83afa-843b-41cf-8586-650279a41b2f.png)| 
- Sort artists by name in "Artists" filter when artwork is in auction - dimatretyak
-
-
-
</details> …

chore(FX-4211): sort artists by name in "Artists" filter when artwork is in auction

---

src/app/Scenes/Partner/Components/PartnerArtwork.tests.tsx
src/app/Scenes/Partner/Components/PartnerArtwork.tsx

This PR resolves [FX-4399] 
https://user-images.githubusercontent.com/3513494/207589838-b1365f07-13e8-46df-bd87-37bfe3434d38.mp4
https://user-images.githubusercontent.com/3513494/207599363-fc2c025a-ba4c-49cf-b6dc-5e936dd2ad6c.mp4
- Display the empty state for the partner artworks tab if there are no artworks - dimatretyak
-
-
-
</details>
[FX-4399]: https://artsyproduct.atlassian.net/browse/FX-4399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-4399): display the empty state for the partner artworks tab if there are no artworks

---

src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx

This PR resolves [FX-4499] 
remove extra padding from artwork page when no sale message
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 14 - 2022-12-15 at 16 53 50](https://user-images.githubusercontent.com/21178754/207907211-9866de75-6a07-4db4-8af1-4135ff02fb10.png)|![Simulator Screen Shot - iPhone 14 - 2022-12-15 at 16 53 41](https://user-images.githubusercontent.com/21178754/207907223-f43dfa40-204a-4812-b87a-cf9f61fb1717.png)|
-
-
-
-
</details>
[FX-4499]: …

chore: remove extra padding from artwork page when no sale message

---

src/app/Components/AuctionResult/AuctionResultMidEstimate.tests.tsx
src/app/Components/AuctionResult/AuctionResultMidEstimate.tsx
src/app/Components/Lists/AuctionResultListItem.tests.tsx
src/app/Components/Lists/AuctionResultListItem.tsx

This PR resolves [CX-3226] 
This PR updates the auction result list item component to match the new designs
https://user-images.githubusercontent.com/11945712/208158210-5ad0e897-d0cb-4cd3-b8e9-d5040948afed.mov
- update auction result list item component - mounir
-
-
-
</details>
[CX-3226]: https://artsyproduct.atlassian.net/browse/CX-3226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update auction result list item component

---

ios/Artsy/View_Controllers/ARSerifNavigationViewController.m
ios/Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift

This PR resolves [FX-4076] 
* Added the ability to close the modal during loading state
* Fixed the problem when title gets truncated
| ![before](https://user-images.githubusercontent.com/3513494/207865481-8f55c61b-34ff-43a6-8c0a-928fe168ba0a.png) | ![after](https://user-images.githubusercontent.com/3513494/207865600-46868420-57bd-40ab-8032-8e08b9db27c6.png) | 
https://user-images.githubusercontent.com/3513494/207865217-b789dde0-da8e-4138-ae97-30d92e628a9f.mp4
https://user-images.githubusercontent.com/3513494/207865240-0fd634a0-13ad-47c9-90fa-40928a50a9a8.mp4
-
- Improvements for live auction modal - dimatretyak
-
-
</details> …

feat(FX-4076): improvements for live auction modal

---

src/app/Scenes/MyProfile/MyProfileEditForm.tsx

This PR resolves [CX-3255] 
This PR is a follow-up on artsy/cohesion#383
This PR adds the tracking event for the edit profile screen
-
-
-
- adds tracking event to edit profile screen - mrsltun
</details>
[CX-3255]: https://artsyproduct.atlassian.net/browse/CX-3255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3255): Add edit profile tracking event

---

src/app/Components/Lists/AuctionResultListItem.tsx
src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
src/app/Scenes/Home/Home.tsx
src/app/store/config/features.ts

This PR resolves [CX-3228] 
This PR adds upcoming auction results rails to the home page.
https://user-images.githubusercontent.com/11945712/208906298-eeae1cfb-a8fc-4968-9eef-9b3d0dde7246.mov
- add upcoming auction results rail - mounir
-
-
-
</details>
[CX-3228]: https://artsyproduct.atlassian.net/browse/CX-3228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add upcoming auctions rails to the home page

---

src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx

This PR resolves [CX-3229] 
This PR separates between past and future auction results.
https://user-images.githubusercontent.com/11945712/208971597-10e9e046-ea83-4bc0-baa8-b1e6a831281a.mov
- separate between past and future auction results - mounir
-
-
-
</details>
[CX-3229]: https://artsyproduct.atlassian.net/browse/CX-3229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3229): separate between past and future auction results

---

src/app/Components/ArtworkFilter/Filters/ArtistIDsArtworksOptions.tsx
src/app/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
src/app/Components/ArtworkFilter/Filters/MultiSelectOptionItem.tsx
src/app/Components/ArtworkFilter/Filters/useMultiSelect.ts

This PR resolves [FX-4396] 
https://user-images.githubusercontent.com/3513494/208473840-bc210706-c18b-414b-9332-b588fb7c5526.mp4
https://user-images.githubusercontent.com/3513494/208473866-a34b6430-91ad-45ef-9c6f-efa225c486a4.mp4
-
-
-
- Optimization for "Artists" filter screen - dimatretyak
</details>
[FX-4396]: https://artsyproduct.atlassian.net/browse/FX-4396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(FX-4396): Optimization for "Artists" filter screen

---

src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx

This PR resolves [this](https://artsyproduct.atlassian.net/browse/CX-3196?focusedCommentId=53440) comment about tracking in [CX-3196] 
Adjust New Works For You rail artwork rail save icon tracking (`context_screen_owner_type = “artwork”` => `context_screen_owner_type = “home”`).
**New Tracking Event:**
```
{
"context_screen": "Home",
"context_screen_owner_type": "home",
"action_name": "artworkSave",
"context_module": "ArtworkActions",
"context_screen_owner_id": "63963d73856331000b892b42",
"context_screen_owner_slug": "richard-hambleton-untitled-bright-red"
}
```
**Old Tracking Event:**
```
{
"context_screen": "Artwork",
"context_screen_owner_type": "artwork",
"action_name": "artworkSave",
"context_module": "ArtworkActions",
"context_screen_owner_id": "63963d73856331000b892b42", …
```

fix: Adjust New Works rail artwork rail save icon tracking

---

src/app/Components/Lists/AuctionResultListItem.tsx
src/app/Scenes/AuctionResult/ComparableWorks.tsx

This PR fixes an issue making dev on the auction result screen not possible
**Before**
https://user-images.githubusercontent.com/11945712/209173283-1ee1b415-dc88-4a2a-95f7-aec6783bb76b.mov
**After**
https://user-images.githubusercontent.com/11945712/209173387-dbe85457-0697-4a00-a67a-4b216f35dd9d.mov
-
-
-
- fix broken auction result screen on dev - mounir
</details>

fix: broken auction result screen

---

src/app/Components/AuctionResult/AuctionResultMidEstimate.tests.tsx
src/app/Components/AuctionResult/AuctionResultMidEstimate.tsx
src/app/Scenes/AuctionResults/AuctionResultsForArtistsYouFollow.tsx
src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
src/app/Scenes/Home/Components/AuctionResultsRail.tsx
src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
src/app/store/config/features.ts

- Show artist's name within the upcoming auction results rail
- Enable the ff for the upcoming auction results rail
- Shows only past auction results in the latest auction results rail
- Makes sure that the mid estimate is shown together if it spans across two lines
#nochanges

fix: Address QA comments on auction results

---

src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/app/Components/AuctionResult/AuctionResultMidEstimate.tests.tsx
src/app/Components/AuctionResult/AuctionResultMidEstimate.tsx
src/app/Components/AuctionResultsList.tsx
src/app/Components/Lists/AuctionResultListItem.tsx

This PR resolves an issue with padding broken inside the mid-price estimate
#nochanges

fix: padding on mid estimate comp

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts

This PR resolves [CX-3272] 
- Removes Zipcode inn SWA artwork details form
<p>
</p>
- Remove Zipcode in SWA artwork details form - kizito
-
-
-
</details>
[CX-3272]: https://artsyproduct.atlassian.net/browse/CX-3272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3272): Remove Zipcode in SWA artwork details form

---

src/app/NativeModules/ARScreenPresenterModule.tsx

Fixes deeplinks that switch tabs not working when the app is in a killed state:
- Adds request animation frame wrapper to all nav calls to wait for instantiation
- Handles update navState calls before navState exists
https://user-images.githubusercontent.com/49686530/210377836-4a6d4c13-41b3-4c34-b4d9-e28f9333c419.mov
https://user-images.githubusercontent.com/49686530/210377790-4eb60123-aa43-42e0-a816-c924dab8a2ab.mov
- Fix tab switching deeplinks from a killed state - Brian
-
-
-
</details>
[docs]: …

fix: wait for tab instantiation in navActions, handle empty nav state

---

src/app/Scenes/Home/Components/ContentCards.tsx

This PR introduces a "breakpoint" where larger devices get content cards images that are half the width of the screen. This was something we meant to return to after the cards were launched but are just now getting to. Looks like this:
I looked at this live with Lois and we picked 700 as the magic number but if anybody has a better idea I'm open to it!
https://artsyproduct.atlassian.net/browse/GRO-1438
/cc @artsy/grow-devs @kathytafel 
[GRO-1438]: https://artsyproduct.atlassian.net/browse/GRO-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: More closely match designs for content cards on larger devices GRO-1438

---

.circleci/config.yml

By default, the checkout command uses a read-only SSH key to clone the repository during builds. When a build needs a write SSH key to push code/tags back to the GitHub repository via git push, a job can pull it down via the add_write_ssh_key command.

chore: add write SSH key before executing git push commands

---

.circleci/config.yml

read/write SSH key added yesterday seems to have disappeared. Recreated/reconfigured and this PR updates the fingerprint in the Circle CI config.

chore: update read/write SSH key fingerprint for Circle CI

---

fastlane/Fastfile

Replaces the old `FASTLANE_SILENCE_BETA_FAILURES` var with `FASTLANE_SILENCE_BETA_FAILURES_UNTIL`, the var should now be populated with a date, e.g. `2023-01-11`. 
It is pretty easy to set the old var and forget about it which makes us miss beta failures which we want to know about. 
Now instead if you are working on a ci change and don't want to blow up slack with error messages you can set this var to one day in the future and after that date is passed alerts will occur again. Recommend only setting a day at a time. 
https://artsy.slack.com/archives/C02BAQ5K7/p1673264417645639
-
-
-
-
</details> …

ci: silence betas until var 

---

src/app/store/AuthModel.ts

This PR resolves [MOPLAT-501] 
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/211855587-1d34ccf1-203f-4586-ae70-4f85d39f1477.png)|![image](https://user-images.githubusercontent.com/17421923/211855439-7be02a1c-c807-4cbf-b867-22e0ccda5c56.png)|
-
-
-
-
</details>
[MOPLAT-501]: https://artsyproduct.atlassian.net/browse/MOPLAT-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: space between text

---

src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
src/app/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
src/app/Components/ArtworkFilter/FilterArtworksHelpers.tests.tsx
src/app/Components/ArtworkFilter/Filters/SortOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/SortOptions.tsx

This PR resolves [FX-4540] 
| <img width="503" alt="before" src="https://user-images.githubusercontent.com/3513494/212112123-47bcc2ba-6f57-4a62-87ce-8bd5ca75a4f4.png"> | <img width="503" alt="after-1" src="https://user-images.githubusercontent.com/3513494/212112162-10142345-b1a5-48d8-8547-524e5a881ded.png"> | 
-
-
-
-
</details>
[FX-4540]: https://artsyproduct.atlassian.net/browse/FX-4540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

chore(FX-4540): Change "Default" sort option to "Recommended"

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx

This PR resolves [CX-3160] 
fix dirty form check when uploading a new artwork.
- Fix dirty form check when uploading a new artwork - ole
-
-
-
</details>
[CX-3160]: https://artsyproduct.atlassian.net/browse/CX-3160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Adjust dirty form check when uploading a new artwork

---

package.json

After switching branches, I noticed that Podfile warning that we added happens before the `yarn install` step which makes it hard to notice it. This PR reverts it order
#nochanges

chore: reverse order of pull lock

---

ios/Artsy/Emission/EigenCommunications/ARPHPhotoPickerModule.m
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx

This PR resolves [CX-3159] 
When adding local images to MyCollection entry, the Touchables appear frozen. This is because these raw images can be large and loading them can take some time. 
This PR does:
- Refactors the ArtworkAddPhotos page to use Flatlist
- Fixes the frozen touchable issue when tapping photos button on MyCollectionArtworkForm to go  ArtworkAddPhotos page by loading a lighter placeholder first.
- Loading the iOS add image native modal multiple times increases memory usage astronomically. It appears ARPHPhotoPickerModule is not autoreleased (or the pool is not drained in time before the next view is pushed??). Replacing the delegate with a nonretained version improved this part.
- Deleting photo would require that the available photos be reloaded. Until the last image in …

CX(3159): Fix MyCollection Add Photos freeze

---

src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tests.tsx
src/app/store/config/features.ts

This PR set the images deep zoom as ready for release on Android
-
-
- Release deep zoom - mounir
-
</details>

chore: set deep zoom as ready for release

---

.circleci/config.yml

Noticed that we still proceed with the ios and android builds even if tests don't pass; this fixes that. 

ci(builder): Wait until tests pass before build

---

src/palette/elements/Input/MoneyInput/MoneyInput.tests.tsx

Fixes a missing import path that was flagged by tests. Which makes me wonder... are we not typechecking the `palette` directory? (Checked, and we are; maybe a cache issue?) Not sure how its possible this was missed. 

fix(test): Fix missed import path

---

src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx

This PR resolves [FX-4536] 
Adds mutation to mark single notification as read.
https://user-images.githubusercontent.com/21178754/213689656-b3edf869-e245-4a4f-8aa9-44707760ba62.mp4
- mark single activity item notification as read when pressed - gkartalis
-
-
-
</details>
[FX-4536]: https://artsyproduct.atlassian.net/browse/FX-4536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4536): mark single activity item notification as read when pressed

---

ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+Widget.swift
ios/ArtsyWidget/FullBleed/FullBleed+Widget.swift

Just a minor PR to update some copy for the Trove name change. There will be a follow up ticket over on Gravity to alter how the artworks are picked but this at least gets the words to match.
https://artsyproduct.atlassian.net/browse/GRO-1489

chore: Update Widget for Trove name change GRO-1489

---

.secrets.baseline
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

Moving the cleaned input at the top because it overrides apparently some values like `artistIDs` which causes the mutation to fail.
-
-
-
-
</details>

fix: Fix artwork mutation input cleaning

---

src/app/NativeModules/ARScreenPresenterModule.tsx

Turns out the InteractionManager is not exactly the same as requestAnimationFrame, so we bring that latter one back.
some more context: https://artsy.slack.com/archives/C02NAJ2CGLW/p1674494300838879
-
-
-
-
</details>

fix: widget deeplink not working with app killed

---

docs/metaflags.md
src/app/system/relay/createEnvironment.ts
src/app/utils/loggers.ts

This adds a new metaflag, `logRelayVerbose`, which outputs the full output of a relay query, per `relayLoggingMiddleware`.

chore(relay): Add verbose relay logging

---

fastlane/Fastfile

This reverts commit 065a39e838b053317d5df9520ef1e1460f76dc6e.
Sorry reverting this for now as it is causing problems with betas, will look to fix tomorrow. 
Reverts the android specific builds pr while I fix the issue. 
-
-
-
-
</details>

fix: Revert "ci: android specific releases (#7913)"

---

src/app/system/errorReporting/sentrySetup.ts

This fixes an issue that surfaced after we got the debugger working in eigen, which is stack and log traces were being obscured by Sentry tapping into the JS pipeline. Now, we disable the hook in `__DEV__`.
**Before**: 
**After**: 

fix(stack-traces): Disable sentry in __DEV__, fix console and error stack traces

---

src/app/Components/LoadFailureView.tsx

Adds `devpurple` line on RetryErrorBoundary **when staging** to be able to distinguish if it is staging environment quickly.
-
-
-
- add purple line on RetryErrorBoundary screen - gkartalis
</details>

feat: add purple line on RetryErrorBoundary screen

---

package.json
scripts/navigate-to-route

This adds a helpful new command to our `package.json` scripts so that we can navigate directly to a route in eigen:
```
yarn navigate-to-route /artist/andy-warhol
```

chore(scripts): Add `yarn navigate-to-route` script

---

src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx

chore: execute "mark as read" mutation only when notification is unread

---

src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/BottomTabs/BottomTabsModel.ts

This PR resolves [FX-4569] 
https://user-images.githubusercontent.com/3513494/214825542-09a07326-3e61-47b5-a05c-69db9eb92c69.MP4
-
-
-
- Decrease the counter on the app icon by 1 when the user clicks on the activity panel item and this notification is marked as read - dimatretyak
</details>
[FX-4569]: https://artsyproduct.atlassian.net/browse/FX-4569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4569): Decrease the counter on the app icon by 1 when the user clicks on the activity panel item and this notification is marked as read

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/utils/relayHelpers.ts

This PR resolves [CX-3357] 
Refetch artwork after editing
-
-
-
-
</details>
[CX-3357]: https://artsyproduct.atlassian.net/browse/CX-3357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Refetch artwork after editing

---

package.json
scripts/navigate-to-route-android

Related https://github.com/artsy/eigen/pull/8061
Adds a new `yarn navigate-to-route-android` cli command for quickly jumping into deeply nested screens on Android devices. 
**Use**:
- `yarn navigate-to-route-android /artist/andy-warhol`

toolchain(android): Add `yarn navigate-to-route-android` cli command

---

.betterer.results
src/app/Components/OpaqueImageView/OpaqueImageView.tsx

Fixes the annoying type issue coming from old opaque image view comp
|---|---|
|https://user-images.githubusercontent.com/21178754/215467437-9552c72f-d166-4a2a-bd61-1e25b1ccf65f.mp4|https://user-images.githubusercontent.com/21178754/215467798-f6150b2e-788a-4f58-a9c0-12a39da301d2.mp4|
-
-
-
- fix: error with old opaque image view in search - gkartalis
</details>

fix: error with old opaque image view in search

---

src/app/utils/experiments/UnleashProvider.tsx
src/app/utils/experiments/hooks.ts
src/app/utils/experiments/unleashClient.ts
src/app/utils/useIdentifyUser.ts

This PR resolves an issue where the user gets a different variant when the app state changes. 
As we were not testing if the app has finished rehydration, we were initializing unleash client without a userID. This led to sessions that can have a different variant from the variant specified to the user, which gets queried properly when the app is brought to the foreground.
**Before**
https://user-images.githubusercontent.com/11945712/215539486-02df67c4-908f-42c0-aa0e-a53d4b8df4d3.mov
**After**
https://user-images.githubusercontent.com/11945712/215539522-c9818ada-ce08-40cc-bcfe-66af90508992.mov
-
-
-
- make sure app is rehydrated before initializing unleash - mounir
</details> …

chore: make sure app is rehydrated before initializing unleash

---

.betterer.results
metaflags.example.json
src/app/AppRegistry.tsx
src/app/Scenes/Home/Home.tsx
src/app/system/navigation/ModalStack.tsx
src/app/system/navigation/NavStack.tsx
src/app/system/navigation/navigate.ts
src/app/system/relay/middlewares/metaphysicsMiddleware.ts
src/app/utils/loggers.ts
src/app/utils/queryPrefetching.ts
src/setupJest.ts

After noticing the above error and some worrying errors inside Sentry ([here](https://sentry.io/organizations/artsynet/issues/3389526194/?environment=production&project=5867225&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d)), I wanted to know which screens this error is happening at. Unfortunately, it turned out that the old tracking was broken and it was also not capturing all screens (for example if you switch tabs.). This PR adds tracking on Intent (when the `navigate` method is used), and also after successful navigation. 
-
-
-
-
</details> …

chore: track Sentry screen navigation

---

patches/react-native+0.66.5.patch

This PR resolves an issue with building the app when node versions are managed with a brew-installed asdf.
It would be good to have another asdf-user test this. It may also require re-installing the package.
For reference, the oh-my-zsh plugin loads asdf [here](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/asdf/asdf.plugin.zsh#L11-L17) from the `/libexec` subdirectory. I suppose we should check that the non-brew method is similarly the same. At first glance, it appears to be the same.

fix: load asdf from brew prefix + /libexec + /asdf.sh

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx

This PR resolves an issue where the career highlights cards are broken on Android
**Before**
https://user-images.githubusercontent.com/11945712/216008943-db717caa-52cd-4383-b6a6-b29edee39b29.mp4
**After**
https://user-images.githubusercontent.com/11945712/216009542-16a39cbe-85b9-454b-a911-06209f39194c.mov
-
-
- Fix career highlights cards modal - mounir
-
</details>

fix: blank screen on career highlights

---

src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Activity/ActivityList.tsx
src/app/Scenes/Activity/hooks/useMarkNotificationsAsSeen.ts
src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
src/app/Scenes/BottomTabs/BottomTabsModel.ts
src/app/store/migration.tests.ts
src/app/store/migration.ts

This PR resolves [FX-4537] 
https://user-images.githubusercontent.com/3513494/216047480-4f051593-0d18-4fd9-89e2-ebe18b5681c7.mp4
-
-
-
- Hide the global blue dot indicator if there are no unseen notifications - dimatretyak
</details>
[FX-4537]: https://artsyproduct.atlassian.net/browse/FX-4537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4537): Hide the global blue dot indicator if there are no unseen notifications

---

src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx

This PR resolves [TX-1032]
This PR updates the bank account details that we show to buyers in their Order History. 
The update is that we display a different bank account detail, depending on order's currency (GBP, EUR, and default USD).
The changes are cross-platform, applicable to all users. 
-
-
-
</details>
[TX-1032]: https://artsyproduct.atlassian.net/browse/TX-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-1032): Different bank account details per order currency

---

package.json
src/app/Components/Home/ArtistRails/ArtistRail.tsx
src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/Home/homeAnalytics.tests.ts
src/app/Scenes/Home/homeAnalytics.ts
yarn.lock

This PR resolves [CX-3356] 
|                                                                          Change                                                                          |                                                                               Screenshot                                                                              |
|:--------------------------------------------------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| Add Tracking to Upcoming Auction Results Rail …

feat: add missing tracking events to the home screen

---

src/app/store/config/features.ts

Release My Collection artworks from non-Artsy artists feature flag. I'm not sure why this flag isn't overridden by Echo ([Echo flag set to true](https://github.com/artsy/echo/blob/508dd2cac9473c98e7b10b67b37243835742b900/Echo.json5#L116)).
-
-
-
-
</details>

chore: Release My Collection artworks from non-Artsy artists feature flag

---

src/app/Components/OpaqueImageView/OpaqueImageView.tsx

reverts https://github.com/artsy/eigen/pull/8086
#nochangelog
</details>

revert: reverts process color because the color doesn't work

---

src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx

This PR resolves [FX-4606]
Notice tiny +3 counter on CAMERA WORKS notification:
|---|---|
| ![before](https://user-images.githubusercontent.com/3934579/217271981-64b6de79-43a8-4210-8270-c8fe569766aa.png) | ![after](https://user-images.githubusercontent.com/3934579/217272003-fcf2d54f-85d9-4184-b1ce-a7afe4e7bd9f.png)  |
-
-
-
-
</details>
[FX-4606]: https://artsyproduct.atlassian.net/browse/FX-4606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-4606): Don't display +n text in activity panel for non-artwork-based notifications

---

src/app/Scenes/Search/components/ElasticSearchResult.tests.tsx
src/app/Scenes/Search/components/ElasticSearchResult.tsx
src/app/Scenes/Search/components/ElasticSearchResults.tests.tsx
src/app/Scenes/Search/components/ElasticSearchResults.tsx
src/app/Scenes/Search/components/SearchResultImage.tsx
src/app/Scenes/Search/components/placeholders/SingleIndexSearchPlaceholder.tsx

Just adds some tests for the `ElasticSearchResults` and `ElasticSearchResult` components
-
-
-
- add elastic search list and result element tests - gkartalis
</details>

test: add elastic search list and result element tests

---

src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx

This PR resolves [FX-4558] 
On Artwork screen:
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-14 at 14 27 21](https://user-images.githubusercontent.com/21178754/218752339-e25740ef-18ac-4859-a7cb-fdf17a20406d.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-14 at 12 52 02](https://user-images.githubusercontent.com/21178754/218731019-aa9e369f-56f9-4ce2-a7e0-7a69ce0178e0.png)|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-14 at 14 26 27](https://user-images.githubusercontent.com/21178754/218752340-53976ff7-21bd-4b98-8d28-cbe6e77aa3d1.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-14 at 12 52 06](https://user-images.githubusercontent.com/21178754/218731009-746da1f7-82d8-4349-905f-09abe109e6f2.png)|
|![Simulator Screen Shot - iPhone 14 Pro - …

feat(FX-4558): add save/saved label to save artwork button

---

src/app/Scenes/Search/ElasticSearchPills.tsx

This PR resolves [FX-4614] 
[notion card](https://www.notion.so/artsy/pill-response-is-a-little-slow-initially-when-i-typed-in-Kaw-only-the-top-pill-worked-the-rest-we-699b611eec6f4341824a263b9189c32c?pvs=4)
Elastic Search Pills are not disabled when loading to provide a better UX.
https://user-images.githubusercontent.com/21178754/218993421-2d6e4359-8e1f-42e2-b013-f60c5b778a10.mp4
https://user-images.githubusercontent.com/21178754/218993494-861abfd3-3444-4eaf-8cdc-f0d1fe2115f5.mp4
- elastic pills not disabled when loading counts (behind ff) - gkartalis
-
-
-
</details> …

feat(FX-4614): elastic pills not disabled when loading counts

---

src/app/Scenes/Search/SearchResults.tsx

This PR resolves [FX-4616] 
Found during search QA session, top pill had extra 2 top padding when it wasn't supposed to, edited to match the other search result screens.
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 14 - 2023-02-15 at 11 10 59](https://user-images.githubusercontent.com/21178754/219000606-ffc8d016-d785-4a93-9c99-951400aa1451.png)|![Simulator Screen Shot - iPhone 14 - 2023-02-15 at 11 18 00](https://user-images.githubusercontent.com/21178754/219000516-e3028abb-212a-46d8-9f61-62cb3e67802f.png)|
|![Simulator Screen Shot - iPhone 14 - 2023-02-15 at 11 22 12](https://user-images.githubusercontent.com/21178754/219001100-92b35cc6-f932-452a-bde1-46e5238b53bc.png)|![Simulator Screen Shot - iPhone 14 - 2023-02-15 at 11 21 …

fix(FX-4616): remove top padding from top pill results

---

src/app/Scenes/Search/AutosuggestResults.tsx
src/app/Scenes/Search/components/ElasticSearchResults.tsx

This PR resolves [FX-4617] 
Paired on this with @nickskalkin 
Changes behavior of the search results list: if the user has scrolled down and changed the query  we want to return them to the beggining of the list.
⚠️ This affects also the artist results on mycollection flow (added @olerichter00 / @MounirDhahri for this reason and a video of the behavior there)
Search Results:
Top Pill:
https://user-images.githubusercontent.com/21178754/219343334-58e20261-4af4-4d79-9a6e-bdceba276ec5.mp4
ES rest of the Pills:
https://user-images.githubusercontent.com/21178754/219343348-7ece16f4-5e17-402e-bdd7-84d4cc679741.mp4
My collection artist search:
https://user-images.githubusercontent.com/21178754/219340686-e7361a0b-f3a6-43a8-b1b5-2772c9d88715.mp4
- …

fix(FX-4617): position reset search result screen on query change

---

src/app/Scenes/Search/SearchArtworksContainer.tsx
src/app/Scenes/Search/SearchArtworksGrid.tsx

This PR resolves [FX-4619] 
Reduces the amount of artworks that we are initially fetching as results on the artwork pill in order to boost the **TTI** of the artwork result list.
|Before|After|
|---|---|
|<img width="816" alt="Screenshot 2023-02-16 at 12 23 41" src="https://user-images.githubusercontent.com/21178754/219363404-11a4f039-9cf6-48ab-83f2-b83c145a6b07.png">|<img width="1053" alt="Screenshot 2023-02-16 at 12 24 38" src="https://user-images.githubusercontent.com/21178754/219363401-37209ed8-1287-4752-904a-3fd8c1d95fe8.png">|
-  reduce the initial fetched artwork results - gkartalis
-
-
-
</details> …

fix(FX-4619): reduce the initial fetched artwork results

---

src/app/utils/useDeepLinks.ts

Marketing deeplinks are handled and redirected and we were tracking twice, once with encoded url and once with decoded url. This checks the url before tracking to avoid this. 
- 
-
-
- Fix double tracking of marketing deeplinks - Brian
</details>

fix: avoid double tracking marketing links

---

src/app/utils/DevMenu.tsx

Unburies the RN dev menu now that the debugger is no longer broken and moves it to the top to encourage more use: 

chore(devMenu): Move RN dev menu button to top

---

src/app/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
src/app/Scenes/Collection/Screens/CollectionArtworks.tests.tsx
src/app/Scenes/Collection/Screens/CollectionArtworks.tsx

This PR resolves [APPL-312] 
| <video src="https://user-images.githubusercontent.com/3513494/220334942-87c99f2b-18f2-4e29-820f-2279a46475ea.mp4" /> | <video src="https://user-images.githubusercontent.com/3513494/220335044-e1918bcd-232b-4442-bd49-52b88be7a176.mp4" /> | 
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-02-21 at 14 35 07](https://user-images.githubusercontent.com/3513494/220335252-ad4d9af1-26a4-4fe1-9c42-bc6c99064c48.png) | ![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-02-21 at 14 35 00](https://user-images.githubusercontent.com/3513494/220335219-b283815d-bbf8-480c-8124-6704b963bcff.png) | 
- …

fix(APPL-312): improvements for collections screen, empty artworks state

---

src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Artwork.tsx

This PR resolves [FX-4626] 
https://user-images.githubusercontent.com/21178754/220890327-4c7c8337-a67a-4891-84c0-d5080f7aafa0.mp4
https://user-images.githubusercontent.com/21178754/220890360-bbae1d1a-34f7-407d-82a8-64f1ce6f7151.mp4
- display contact gallery button on inquireable partners - gkartalis
-
-
-
</details>
[FX-4626]: https://artsyproduct.atlassian.net/browse/FX-4626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: display contact gallery button on inquireable partners

---

src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx

Came out of QA Session today, the button wasn't  easily pressed on Android only so switched to Touchable and it works correctly now.
There is a hack in place to prevent the jumpy behavior but will fix it properly after the release
|Demo||
|---|---|
|iOS||
|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-23 at 17 47 56](https://user-images.githubusercontent.com/21178754/220975231-cef91ab6-d9b4-4a12-a3e3-16fff73143f0.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-23 at 17 48 00](https://user-images.githubusercontent.com/21178754/220975236-7c5df705-4d63-4b12-9d79-08462f72d169.png)|
|Android||
|![Screenshot_1677170940](https://user-images.githubusercontent.com/21178754/220975285-d0032859-7503-4bcb-bbed-cd3107440c2a.png)|![Screenshot_1677170943](https://user-image …

fix: save button not easily pressed on android

---

src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizButton.tsx

This PR resolves [GRO-1266] 
https://user-images.githubusercontent.com/17421923/221200910-5c63cf64-e132-457e-8e37-946b21ece901.mov
-
-
-
-
</details>
[GRO-1266]: https://artsyproduct.atlassian.net/browse/GRO-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: art quiz icon animation

---

docs/adding_new_components.md
docs/developing_a_feature.md
src/app/AppRegistry.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkGrids/GenericGrid.tests.tsx
src/app/Components/ArtworkGrids/GenericGrid.tsx
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
src/app/Components/PageableScreensView/PageableLazyScreen.tests.tsx
src/app/Components/PageableScreensView/PageableLazyScreen.tsx
src/app/Components/PageableScreensView/PageableScreensContext.tests.tsx
src/app/Components/PageableScreensView/PageableScreensContext.ts
src/app/Components/PageableScreensView/PageableScreensView.tests.tsx
src/app/Components/PageableScreensView/PageableScreensView.tsx
src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
src/app/store/config/features.ts
src/app/system/navigation/useNavigateToPageableRoute.tests.ts
src/app/system/navigation/useNavigateToPageableRoute.ts

This PR resolves [MOPLAT-600]
This adds the ability to swipe between artworks that are present within various contexts such as rails and grids. I've gone through and updated all the obvious surfaces to support this but Eigen is large so likely something was missed somewhere. We can surface it with some QA.
Hidden behind a `AREnablePageableArtworkScreens` feature flag. 
Pageable artwork screens are easy to add:
```tsx
const SomeRail = ({ someConnection }) => {
const artworks = extractNodes(someConnection) 
// Initialize hook with artworks that should be pageable
const { navigateToPageableRoute } = useNavigateToPageableRoute({ artworks })
return (
<>
{artworks.map(artwork => {
return (
<Artwork onPress={() => {
// Then navigate. Uses the same underlying code as `navigate`, so 
// additional …
```

feat(pageable): Add ability to page through artworks

---

src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
src/app/Scenes/Activity/hooks/useMarkNotificationsAsSeen.ts
src/app/Scenes/BottomTabs/BottomTabs.tsx
src/app/Scenes/BottomTabs/BottomTabsModel.ts
src/app/Scenes/Home/Components/HomeHeader.tests.tsx
src/app/Scenes/Home/Components/HomeHeader.tsx

This PR resolves [FX-4539] 
More context here: [Slack Thread](https://artsy.slack.com/archives/C9SATFLUU/p1676391801615959?thread_ts=1676378327.999239&cid=C9SATFLUU)
Previously, we showed the count of **unread** notifications on the app icon. With the current changes, the number of unseen notifications will be displayed
https://user-images.githubusercontent.com/3513494/221618923-b7731cf9-f822-4049-90b4-0d2015d1391b.MP4
-
- show unseen notifications count for app badge - dimatretyak
-
-
</details>
[FX-4539]: …

feat(FX-4539): show unseen notifications count for app badge

---

src/app/Scenes/Search/ElasticSearchPills.tsx

Removes entities from searchConnection when requesting for aggregations because of [this](https://github.com/artsy/gravity/blob/main/app/models/search/queries/global_search_query.rb#L133-L134)
- 
-
-
- remove entities from ESSearchPills query - gkartalis
</details>

fix: remove entities from ESSearchPills query

---

src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsHeader.tsx
src/app/Scenes/OrderHistory/OrderDetails/Components/TrackOrderSection.tsx
src/app/Scenes/OrderHistory/OrderDetails/OrderDetailsHeader.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/TrackOrderSection.tests.tsx
src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
src/app/utils/getOrderStatus.tests.ts
src/app/utils/getOrderStatus.ts

Exchange exposes a `displayState` field that obviates the need for the calculations currently being performed by Eigen's `getOrderStatus` 
use displayState (instead of state + shipment status) for order status calculations - matt & adam
</details>

feat: use displayState (instead of state + shipment status) for order status calculations

---

src/app/Scenes/Home/Home.tsx

Move Home screen articles field to below query because the rail appears below the fold.
- Fixing home screen by moving articles field to below query - ole
-
-
-
</details>

fix: Move Home screen articles field to below query
