- Artsy.xcworkspace/xcshareddata/Artsy.xccheckout
- Artsy/Classes/View Controllers/ARAppSearchViewController.m
I didn't realize you'd already fixed the bug, but additionally, calling super here means that search gets reset both in `super closeSearch` AND the next time you open up search, which is redundant.
> @orta => reset search

- Makefile
You can now run `make pr` to push to an artsy branch and open a chrome browser with the PR. 
Now, I know what you're thinking, you're thinking "who would use Chrome [nowadays](http://www.huffingtonpost.com/2014/05/06/nsa-google_n_5273437.html)" but I couldn't successfully port Github Selfies to Safari. So Deal with it.
> @ashfurrow => Update Keys, and add a Makefile command for PRing.

- Artsy Tests/ARPostFeedItemLinkViewTests.m
- Artsy/Classes/View Controllers/ARFairPostsViewController.m
- Artsy/Classes/View Controllers/ARPostsViewController.m
- Artsy/Classes/Views/ARAspectRatioImageView.h
- Artsy/Classes/Views/ARAspectRatioImageView.m
- Artsy/Classes/Views/ARPostFeedItemLinkView.h
- Artsy/Classes/Views/ARPostFeedItemLinkView.m
Only one line of code change. Line 84 on `ARPostFeedItemLinkView.m `.
The rest is all refactoring to make the class feel less state-y. ( we always ran update right after init. ) We never used the "hasSeperator" either, so that's gone too [YANG](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it). 
My github selfie isn't working. Here's a pug after eating yoghurt instead.
> @ashfurrow => remove auto layout warnings from fair overview VC

- Artsy/Classes/View Controllers/ARFairShowViewController.m
Some minor code golf-ing WRT those height constants for the top. Wonder if it makes sense to move them to be based on a ratio of screen size. However for now I'm keeping pixel perfect to designs.
Does this when dragging down, instead of being white:
> @ashfurrow => use a black background for the show view controller

- Artsy/Classes/Views/ARArtworkView.m
- CHANGELOG.md
I've taken a look into both https://github.com/artsy/eigen/issues/64 and https://github.com/artsy/eigen/issues/58
They revolve around this crashing:
```
-[UIScrollView _getDelegateZoomView] + 76
or
-[UIScrollView _offsetForCenterOfPossibleZoomView:withIncomingBoundsSize:] + 42
```
Which revolve around object accessing in `onFairUpdate` that doesn't exist. My guess is that an dealloc'd artwork view is being referenced but that one of it's container stacks is still alive and that this layoutIfNeeded is triggering delegate methods on the scrollview. It's a push, but it feels pretty reasonable.
> @1aurabrown => deal with setupCallbackCrashes

- Artsy Tests/ARArtworkViewControllerTests.m
- Artsy/Classes/Networking/ARRouter.h
- Artsy/Classes/Networking/ARRouter.m
- Artsy/Classes/View Controllers/ARArtworkViewController+ButtonActions.m
Partially fixes https://github.com/artsy/eigen/issues/27
Artworks that are "acquireable" may be purchased immediately using the martsy order form, rather than inquiring via the inquiry form. These works may have 0, 1 or many "edition sets."
If an artwork has any edition sets, you must provide an edition_set_id when creating an order for that artwork. Until now, we weren't providing this parameter when creating orders, which was resulting in failed POST requests for all works that have editions.
* If an artwork has no edition sets, we won't include the edition_set_id when creating the order.
* If an artwork has one edition set, we can safely assume that we should use the id of that edition set.
* If an artwork has many edition sets, we don't currently have any UI that supports picking …
> @orta => when creating an order, infer edition_set_id if artwork has only one edition

- Artsy/Classes/View Controllers/ARArtworkDetailView.m
- Artsy/Classes/Views/ARArtworkPriceRowView.h
- Artsy/Classes/Views/ARArtworkPriceView.m
Fixes an odd bug around the height not being set for a price. Tests were already working as intended, hard to figure why in reality it wouldn't work.
> @ashfurrow => fix dots on artwork price - fixes #96

- Artsy.xcodeproj/project.pbxproj
- Artsy/Classes/View Controllers/ARFairMapView.h
- Artsy/Classes/View Controllers/ARFairMapView.m
- Artsy/Classes/View Controllers/ARFairMapViewController.m
- docs/BETA_CHANGELOG.md
Separate the various map subviews that use a mix of frame
and Auto Layout code from the scroll view, by moving them
all into a single container view, as per:
https://developer.apple.com/library/ios/releasenotes/General/RN-iOSSDK-6_0/index.html
Fixes #40.
----
Because I’m not sure if it makes sense to _always_ use a container view and because it would break the API, I did not yet move this into NAMapKit. Any thoughts on this?
> @orta => [Fair Map] Fix disappearing callout view on iOS 8.

- Artsy Tests/ARFairMapAnnotationViewTests.m
- Artsy.xcodeproj/project.pbxproj
- Artsy/Classes/View Controllers/ARFairMapAnnotationView.m
- docs/BETA_CHANGELOG.md
Fixes #126.
This makes it so that annotations that are highlighted will only have their label hidden. Because there didn’t appear to be any snapshot tests for maps, I added unit tests instead.
> @orta => [Fair Map] Don't hide annotations when they’re selected.

- Artsy/Classes/View Controllers/ARFairMapViewController.m
- docs/BETA_CHANGELOG.md
On the iPhone only the artwork view should be rotatable.
> @ashfurrow => [Fair Map] Only allow portrait orientation on iPhone.

- Artsy/Classes/Categories/Apple/UIImageView+AsyncImageLoading.m
- Artsy/Classes/Utils/Logging/ARLogger.h
- Artsy/Classes/Utils/Logging/ARLogger.m
This tries to replicate the format used by AFHTTPRequestLogger for SDWebImage:
```
2015-02-13 20:11:05.063 [NETWORK] | [Success] 200 'https://d32dm0rphc51dk.cloudfront.net/sbk-ujRq86RgJLlDoxiHDQ/tall.jpg' [0.0001 s]
2015-02-13 20:11:08.267 [NETWORK] | [Error] 403 'https://d32dm0rphc51dk.cloudfront.net/Cy1tDMUKkF_H-QN4BIDlDA/square.jpg' [0.5112 s]: Error Domain=NSURLErrorDomain Code=403 "The operation couldn’t be completed. (NSURLErrorDomain error 403.)"
```
I’m wondering if re-using the `NETWORK` category is adding too much noise or not. I can change it to e.g. `IMAGE`, but it _is_ really network… Maybe this is just something to keep an eye on and change it later if needed?
----
In addition it slightly refactors the category by making all methods use 1 single entry point.
> @1aurabrown => [AsyncImageLoading] Add request logging and refactor.

- Makefile
When using `whoami` this would yield `eloy` on my machine, but that’s not my GitHub username. So switched to using git’s source instead.
> @orta => [Makefile] Use `git-credential` to determine the username.

- Artsy/Classes/Models/Gene.m
Fixes #90.
Because of time constraints I decided to fix this the easy way for now and delay a possibly more proper fix to #172.
> [Favorites] Make gene images show-up in list again.

- Artsy/Classes/View Controllers/ARFairGuideContainerViewController.m
The problem was involved in the container view controller, which manages a few different things, including the map view controller, the guide view controller, and a white background view. It was this background view that was being misconstrained. 
In `scrollViewDidScroll:`, I noticed a problem where for a single invocation, the controller thought the map was expanding (that is, it thought the user had pulled down enough so that if they let go, the map would become full screen). It updated the constraints on the white background view accordingly. The solution was to limit that conditional branch by forcing it to check if the `oldTopHeight` (the height of the old constrain) was not zero. It is only equal to zero when the scroll view is first pull from the state where `contentOffset.y` is …
> @alloy => Fixes #44.

- Artsy/Classes/View Controllers/ARFairMapView.m
This is a stopgap solution until we figure out what is
triggering the re-layout that is moving the callout back
to the origin of the superview.
Fixes #166.
> @orta => [Fair Map] Show callout on first selection on iOS 8.

- Artsy/Classes/View Controllers/ARArtworkViewController.m
- Artsy/Classes/Views/ARArtworkView.m
Also does the weak->strong dance in the right order.
As discussed I will be doing a bit more investigating, but I think what's happening is:
- ARArtworkView (a UIScrollView subclass) is being retained _longer_ than its VC (ARArtworkViewController).
- UIScrollView's `delegate` property is `assign` not `weak`.
- The UIScrollView implementation tries to message its delegate when it has already been released.
> @orta => Tries to fix #103 and various related tickets.

- Artsy/Classes/Views/ARArtworkView.m
Related to #203
One block was still referencing `self` in a strong fashion.
----
Based on this, I’m not a fan of the `weakify` and `strongify` macros. They do not clearly communicate what's going on in the full scope. It seems to me that making it explicit would make it easier to catch these issues when reading the code:
```objc
__weak __typeof__(self) weakSelf = self;
[self.artwork onArtworkUpdate:^{
__strong __typeof__(weakSelf) strongSelf = weakSelf;
[strongSelf addUnpublishedBanner];
}];
```
The main communication point is about using `weakSelf` and `strongSelf`, so the dance to make these variables can probably be hidden by some simple macros.
@orta @1aurabrown @ashfurrow Thoughts?
> @ashfurrow => [ArtworkView] Don't have any block retain self.

- Artsy/Classes/Models/AuctionLot.h
- Artsy/Classes/Models/AuctionLot.m
fixes https://github.com/artsy/eigen/issues/210. We were using `image_url` to get the image for the auction result without doing anything to replace `:version` in the image URL string.
`image_url` and `image_versions` have been deprecated anyway, in favor of the newer `image_urls` hash, so I made the switch to using that instead. I noticed that a few thumbnail images are still not loading -- this is because they actually don't have any image versions, not due to a code issue. This can be seen in the api response. (I'm using https://api.artsy.net/api/v1/artwork/fernando-botero-family-on-a-beach/comparable_sales since that was the piece used in the original github issue)
> @orta -> fix missing thumbnails on auction results

- Artsy Tests/ARFairFavoritesNetworkModelTests.m
- Artsy/Classes/Models/Profile.m
- Artsy/Classes/Networking/Network Models/ARFairFavoritesNetworkModel.h
- Artsy/Classes/Networking/Network Models/ARFairFavoritesNetworkModel.m
- Artsy/Classes/View Controllers/ARFairGuideViewController.m
The artworks sections of the personalized fair guide should include both works at the fair that you've favorited AND all works by artists you follow who are exhibiting at the fair.
This accomplishes what I want, but has some not so great nested success callbacks. There's probably an elegant way. There's a little bit of existing RAC in this network model, maybe we can make it leverage RAC some more. I'd also like the API to allow you to fetch any of the 3 types of data (works, artists, exhibitors) separately, say when you switch tabs. Needs tests.
> @ashfurrow -> include works by artists you follow in personalized fair guides 'works' section

- Artsy/Classes/View Controllers/ARArtworkViewController.m
- docs/BETA_CHANGELOG.md
Fixes #214.
This was a regression introduced by too paranoiacally nullifying the
scrollview's delegate in 0e06018, which has since been properly
fixed at the root cause in 8db7b1e.
> @1aurabrown => [Artwork] Fix a crash when swiping between artworks.

- Artsy Tests/ARURLItemProviderTests.m
- Artsy.xcodeproj/project.pbxproj
- Artsy/Classes/Networking/ARNetworkConstants.h
- Artsy/Classes/Networking/ARNetworkConstants.m
- Artsy/Classes/Networking/ARRouter+Private.h
- Artsy/Classes/Networking/ARRouter.m
- Artsy/Classes/Utils/ARURLItemProvider.m
fixes https://github.com/artsy/eigen/issues/161
I guess another solution would be to add meta tags on m.artsy.net, but personally I think it's weird and ugly when people tweet/post mobile links. If somebody happens to visit a force link on a phone as a result of a share, they'll just get redirected to mobile anyway.
> @orta -> always use desktop web urls when sharing

- Artsy Tests/ARTopMenuViewControllerSpec.m
- Artsy/Classes/View Controllers/ARTopMenuNavigationDataSource.h
- Artsy/Classes/View Controllers/ARTopMenuNavigationDataSource.m
- Artsy/Classes/View Controllers/ARTopMenuViewController.m
- CHANGELOG.md
- docs/BETA_CHANGELOG.md
When you are logged out and you tap the YOU section, we will show the sign in modal on top of whatever your current view is, instead of taking you to an empty YOU section. 
fixes https://github.com/artsy/eigen/issues/108.
Also includes a bunch of changelog updates.
> @orta => Favorites logged out

- Artsy/Classes/Models/ARHasImageBaseURL.h
- Artsy/Classes/Models/Artist.h
- Artsy/Classes/Models/Artist.m
- Artsy/Classes/Models/Partner.h
- Artsy/Classes/Models/Partner.m
- Artsy/Classes/Networking/Network Models/ARFairFavoritesNetworkModel.m
- Artsy/Classes/View Controllers/ARArtistViewController.m
- Artsy/Classes/Views/ARFavoriteItemViewCell.m
steps towards fixing https://github.com/artsy/eigen/issues/172. doing this change from iamge_url to image_urls incrementally. at some point we should rethink how we structure models with images, because even after this switch, each model handles image versions somewhat differently.
> @ashfurrow -> start using image_urls

- Artsy Tests/ARSharingControllerTests.m
- Artsy/Classes/Utils/ARSharingController.h
- Artsy/Classes/Utils/ARSharingController.m
- Artsy/Classes/View Controllers/ARArtistViewController.m
- Artsy/Classes/View Controllers/ARArtworkViewController+ButtonActions.m
- Artsy/Classes/View Controllers/ARShowViewController.m
- Artsy/Classes/Views/ARGeneViewController.m
- Podfile.lock
- docs/BETA_CHANGELOG.md
On iPad a UIActivityViewController has to be shown in a UIPopoverController.
I chose a somewhat unusual route to not have to retain the popover, because doing so would mean that the callers would have to also retain the ARSharingController and then there would also have to be a delegate for when it can all be released. As it seems that on iOS 8 the popover is retained by the system and we’re moving away from iOS 7 soon anyways, this seemed like a good compromise.
Fixes #239
> @1aurabrown => [Sharing] Fix crash on iPad.

- Artsy/Classes/View Controllers/ARFairViewController.m
- Artsy/Classes/Views/Table View Cells/ARButtonWithImage.m
- CHANGELOG.md
Fixes #256 & #257.
Makes the rows have variable height, defined by the textual content. Because this slightly changes how the `ARButtonWithImage` layout is calculated, it would be great if you can do a quick check through the app to see if any places are negatively affected.
> @1aurabrown => [Fair] Show editorial content.

- Artsy/Classes/View Controllers/ARTopMenuViewController.m
fixes https://github.com/artsy/eigen/issues/267
This was originally written for ios7, which didn't swap frame width and height on rotation for some reason. in iOS 8 they fixed that bug, but our code didn't account for the fix. now it does and it ditches the iOS7 way.
> @ashfurrow => fix nav button placement on rotation

- README.md
Just a small thing but I was just checking out the README and thought it would make sense to have the Build Status badge displaying the master branch instead of the latest build (which might be failing). Please close if intentional.
> Use master branch for build status badge

- Artsy/Classes/View Controllers/ARHeroUnitViewController.m
- CHANGELOG.md
Pretty simple fix – when we get the hero units, download their images.
I've opened a [related issue](https://github.com/rs/SDWebImage/issues/1064) on SDWebImage, our image-caching library.
Fixes #251.
> @1aurabrown => Pre-caches Hero Unit images.

- Artsy/Classes/View Controllers/ARBrowseViewController.m
- Artsy/Classes/View Controllers/ARTopMenuNavigationDataSource.m
let me know if this seems right to you. I still have the VC re-fetching data every time the view appears (this could probably be changed to something less frequent), but now the browse view will be initialized at app launch and its data will be fetched at that time, even if the view doesn't exist yet. Images that it will need are pre-fetched and available immediately for when you hit Browse.
> @ashfurrow -> pre-fetch browse data and images

- Artsy/Classes/Views/ARArtworkView.m
- docs/BETA_CHANGELOG.md
- docs/eigen_tips.md
Fixes #279 
There’s only one right type of overload and it ain’t warnings… ANIMALS!
> @ashfurrow => Only show ‘unpublished’ work warning once.

- Artsy Tests/ARArtworkRelatedArtworksViewTests.m
- Artsy/Classes/Models/Artwork.h
- Artsy/Classes/Views/ARArtworkRelatedArtworksView.m
- docs/BETA_CHANGELOG.md
Related to #277.
Alas the crash is no longer visible on hockey app, as I removed the 1.7.2 beta that was using the incorrect profile, which was the one I had.
> @1aurabrown => Fixes crash caused by assumption that there’s always an artist.

- Artsy Tests/ARPersonalizeWebViewControllerTests.m
- Artsy.xcodeproj/project.pbxproj
- Artsy/Classes/View Controllers/ARPersonalizeWebViewController.m
I think since this was created we now do some analytics stuff on force, they were causing our request handler to run finishing the personalize.
Now we whitelist specifically for the root before finishing.
> @ashfurrow => support analytics URLs in the ARPersonalizeWebViewController

- Artsy/Classes/View Controllers/ARNavigationController.m
- Artsy/Classes/View Controllers/ARTopMenuNavigationDataSource.m
- docs/BETA_CHANGELOG.md
Fix for https://rink.hockeyapp.net/manage/apps/37020/app_versions/149/crash_reasons/31300472.
The child view controller is released without removing all KVO registrations. This is a guesstimated fix, though, and as this seems to be the first time this crash occurred, it’s kinda fishy, but let’s see if @orta can still reproduce the crash after applying this.
> @orta => [Navigation] Remove all KVO registrations on view controllers before dealloc.

- Artsy Tests/ARArtistViewControllerTests.m
- Artsy/Classes/Views/ARTextView.m
- docs/BETA_CHANGELOG.md
It looks like WebKit is running into some internal cache issues,
which is why deferring to the next runloop iteration fixes it.
In addition, Markdown parsing is now performed on a background thread.
Fixes #348.
> @ashfurrow => [ARTextView] Fix a crash related to NSAttributedString+HTML content.

- Makefile
- docs/deploy_to_app_store.md
Updates the docs for deploying to the App Store and a fix so that `make next` doesn’t break the Watch target by changing the device to iPhone/iPad.
> @orta => Release related fixes

- .travis.yml
- Artsy Tests/ARArtistViewControllerTests.m
- Artsy Tests/ARArtworkRelatedArtworksViewTests.m
- Artsy Tests/ARInternalShareValidatorTests.m
- Artsy Tests/ARProfileViewControllerTests.m
- Artsy/Classes/ARAppDelegate.m
- Artsy/Classes/View Controllers/ARProfileViewController.m
- Podfile
- Podfile.lock
- docs/BETA_CHANGELOG.md
In adding support for FairOrganizer for The Armory show 2015 we added the ability to handle routing via a FairProfile owner. This was a stopgap solution, as we want a fair organizer to represent _many fairs_ ( thus moving from one profile to one fair, to one fair organizer to many fairs. 
Force has a page that shows all the older fairs, and some metadata, e.g. https://www.artsy.net/the-armory-show as an overview of the different fairs that the organizer supports. We want to let martsy do that for now, so by removing the fair organizer support we added for Armory 2015, we end up at the expected behavior.
This also fixes a few reds in the test suite.
/cc @broskoski
> @alloy => Support sending new fair profile overview pages to martsy

- Artsy/Classes/View Controllers/ARTopMenuNavigationDataSource.m
https://github.com/artsy/force/pull/2415
Is there a better way that you’d normally guard against such routes breaking for released versions?
> @orta => [Tabs] Fix route used for the magazine, which is now called 'articles'.

- Artsy.xcodeproj/project.pbxproj
- Artsy/Classes/View Controllers/ARInternalMobileWebViewController.m
- Artsy/Classes/View Controllers/ARTopMenuInternalMobileWebViewController.h
- Artsy/Classes/View Controllers/ARTopMenuInternalMobileWebViewController.m
- Artsy/Classes/View Controllers/ARTopMenuNavigationDataSource.m
They are now reloaded when you make their tab active, they are the currently visible view controller (so maintain existing deep view hierarchy), and the previous request was unsuccessful _or_ 1 hour has passed since the last load.
I wanted to touch the existing code as little as possible, as to not introduce any regressions, but the reload implementation in `ARInternalMobileWebViewController` and `ARTopMenuInternalMobileWebViewController` could most probably be shared.
> @orta => Reload root webviews

- Artsy/Classes/View Controllers/ARAuctionArtworkResultsViewController.m
- Artsy/Classes/Views/ARCustomEigenLabels.m
i also made the line-wrapping for the label automatic, rather than hard coded because the text was fixed at iphone-width on ipad.
fixes https://github.com/artsy/eigen/issues/131
> @orta -> auction results warning rotates on ipad

- Podfile
- Podfile.lock
ORStackView has changed the use of string margin predicates to floats, which is perfectly :+1: imo, but this means that we need to explicitly use v2 atm.
https://github.com/orta/ORStackView/pull/27
> @1aurabrown => [Pods] Pin ORStackView to v2, as the API has changed.

- Podfile
- Podfile.lock
Related to #384.
Ran tests locally; only failures were snapshot-related and therefore (probably) not caused by this change.
> @anyone => Updates to ARAnalytics 3.0.0 with Snowplow support

- Artsy/Classes/ARAppDelegate+Analytics.m
- Artsy/Classes/Constants/ARAnalyticsConstants.h
- Artsy/Classes/Constants/ARAnalyticsConstants.m
There are a few questions that need to be answered about this:
1. This tracks user _taps_, not views. So when the app is initially loaded and we show the home screen, it doesn't get tracked. @katarinabatina is that OK? 
1. We track when the _button is tapped_, not when the view is shown. There are two problems with this. If the user taps "Favourites" and they're not logged in, we still track the event. If they tap on the tab that they're already on, then it's still tracked as well.
All of this is malleable – I just need some direction. 
Fixes #381.
> @alloy => Adds main navigation analytics

- Artsy/Classes/View Controllers/models/ARTiledImageDataSourceWithImage.m
- Podfile
- Podfile.lock
- docs/BETA_CHANGELOG.md
Fixes #408.
This currently uses unreleased versions of ARAnalytics and HockeyApp, I’ll update it when those are updated and released.
> @orta => Add breadcrumbs to crash reports, especially around ARTiledImageView.

- Artsy/Classes/View Controllers/ARInternalMobileWebViewController.m
- docs/BETA_CHANGELOG.md
Fixes #351.
At least, this fixes it for just the magazines view, as I understood that to be the main problem, but the #351 ticket is about _all_ martsy views, do you want me to just apply it for all martsy views?
Keep in mind that `DOMContentLoaded` means that not all sub-resources have loaded yet, although the way martsy is currently loading this still means that images have already started loading.
> @1aurabrown => [Martsy] Show web view as soon as DOMContentLoaded state is reached.

- Artsy Tests/ARInternalMobileWebViewControllerTests.m
- Artsy/Classes/ARAppDelegate.h
- Artsy/Classes/ARAppDelegate.m
- Artsy/Classes/Utils/ARSharingController.h
- Artsy/Classes/Utils/ARSharingController.m
- Artsy/Classes/View Controllers/ARInternalMobileWebViewController.m
- Artsy/Classes/View Controllers/ARInternalShareValidator.h
- Artsy/Classes/View Controllers/ARInternalShareValidator.m
- docs/BETA_CHANGELOG.md
Fixes #367 with a technique discussed on that issue. 
Remaining work: 
It's _soooo tiny_ right at the bottom.
> @alloy => Fixes iPad Sharing

- Artsy Tests/ARArtworkRelatedArtworksViewTests.m
- Artsy Tests/AREmbeddedModelsViewControllerTests.m
- Artsy/Classes/View Controllers/ARArtistViewController.m
- Artsy/Classes/View Controllers/ARArtworkFlowModule.m
- Artsy/Classes/View Controllers/ARArtworkMasonryModule.h
- Artsy/Classes/View Controllers/ARArtworkMasonryModule.m
- Artsy/Classes/View Controllers/ARArtworkViewController.m
- Artsy/Classes/View Controllers/AREmbeddedModelsViewController.h
- Artsy/Classes/View Controllers/AREmbeddedModelsViewController.m
- Artsy/Classes/View Controllers/ARFavoriteItemModule.m
- Artsy/Classes/View Controllers/ARFavoritesViewController.m
- Artsy/Classes/View Controllers/ARFeedViewController.m
- Artsy/Classes/View Controllers/ARRelatedArtistsViewController.m
- Artsy/Classes/View Controllers/ARShowViewController.m
- Artsy/Classes/View Controllers/ARTopMenuViewController.m
- Artsy/Classes/Views/ARArtworkRelatedArtworksView.m
- Artsy/Classes/Views/ARFavoriteItemViewCell.h
- Artsy/Classes/Views/ARFavoriteItemViewCell.m
- Artsy/Classes/Views/ARGeneViewController.m
- Artsy/Classes/Views/Table View Cells/iPhone Feed Items/ARModernPartnerShowTableViewCell.h
- Artsy/Classes/Views/Table View Cells/iPhone Feed Items/ARModernPartnerShowTableViewCell.m
- docs/BETA_CHANGELOG.md
the masonry module was previously subscribed to orientation notifications from the notification center. this isn't very elegant. It should be able to respond to size change methods from the VC that it belongs to, and it should be able to calculate its dimensions before the rotation actually has occured (ie as the result of something you call in `viewWillTransitionToSize`), rather than querying the _current_ device orientation
This fixes https://github.com/artsy/eigen/issues/368 and probably will make it easier going forward, especially when it comes to multiple screen sizes. We could easily change this dependency injection to accept arbitrary sizes instead of just a BOOL indicating whether it should lay itself out for landscape vs portrait.
Don't merge yet, I need to update tests and …
> @everybody -> [WIP] fix rotation of masonry views by injecting orientation

- Artsy Tests/ARHeroUnitTests.m
- Artsy/Classes/View Controllers/ARHeroUnitViewController.m
- docs/BETA_CHANGELOG.md
this is a quick fix and could probably use some tests. There is probably a nicer way to tie this in with the pre-fetching and whatever RAC thing is going on when the view loads, but this is simple enough to just ensure that hero units don't go stale. won't disturb the timer or re-render anything if the hero unit data that we get back isn't any different from what we already have.
> @alloy -> re-fetch hero units when hero VC will appear

- Artsy Tests/ARArtworkRelatedArtworksViewTests.m
- Artsy Tests/ARTabContentViewSpec.m
- Artsy/Classes/View Controllers/ARArtworkInfoViewController.m
- Artsy/Classes/View Controllers/ARArtworkMasonryModule.h
- Artsy/Classes/View Controllers/ARArtworkMasonryModule.m
- Artsy/Classes/View Controllers/ARArtworkSetViewController.m
- Artsy/Classes/View Controllers/AREmbeddedModelsViewController.m
- Artsy/Classes/View Controllers/ARFavoritesViewController.m
- Artsy/Classes/View Controllers/ARShowViewController.m
- Artsy/Classes/Views/ARArtworkRelatedArtworksView.m
- Artsy/Classes/Views/ARGeneViewController.m
- Artsy/Classes/Views/ARTabContentView.m
I noticed that when switching tabs, rotating, then switching back, the view that is about to appear still had the old frame size. This is because we were removing navigation controllers from their host when at tab is deselected. If you DON'T remove them and maintain each tab's navigation controller in the VC hierarchy, each tab can respond to rotation/size change events even when they are not visible, and they will also already have the correct view size when they are reselected.
Let me know if you think there would be other problems with doing this. It makes rotation a whole lot easier to keep all the Nav Controllers in the hierarchy even when deselected.
> @orta -> fix shows view not using proper masonry layout

- Artsy/Classes/View Controllers/ARArtworkViewController.m
- Artsy/Classes/Views/ARArtworkMetadataView.h
- Artsy/Classes/Views/ARArtworkMetadataView.m
fixes https://github.com/artsy/eigen/issues/465
Pretty basic solution - fade it out quickly at the beginning of the rotation, fade it back in at the end.
I'm not sure how to accomplish this using the `coordinator`'s `animateAlongsideTranstion`
> @orta -> hide metadata view while rotating artwork view

- Artsy/Classes/Categories/Apple/UIImage+ImageFromColor.h
- Artsy/Classes/Categories/Apple/UIImage+ImageFromColor.m
- Artsy/Classes/View Controllers/ARArtworkPreviewImageView.m
- Artsy/Classes/View Controllers/ARArtworkViewController.m
- Artsy/Classes/Views/ARArtworkMetadataView.m
don't animate the appearance of the action buttons
also use the artwork's aspectRatio to make the grey placeholder image if no cached image is available for the artwork (flawed because this number is sometimes incorrect in the json response)
> @orta -> artwork changes

- Artsy Tests/ARArtworkViewControllerTests.m
- Artsy/Classes/Models/User.m
See discussion [here](https://github.com/artsy/eigen/issues/463#issuecomment-106519283). Before we were requiring two conditions to be considered a "trial user":
- Not be logged in.
- Have a valid XApp token. 
Now we only require the first. 
A larger discussions could be had about renaming `isTrialUser` to be the more accurate `isLoggedOut`. 
Fixes #463.
> @orta => Removes XApp check for trial user condition.

- Artsy/Classes/View Controllers/ARMenuAwareViewController.h
- Artsy/Classes/View Controllers/ARNavigationController.m
This PR does a few things:
1. Removes per-view controller ability to disable nav buttons (a holdover from our old navigation paradigm, which were unused anyway).
1. Stops the disable/re-enable dance when showing a view controller.
I don't see any need to disable the back button during a view controller transition. As far as I know, iOS disables interaction with view controllers during push/pop transitions anyway. 
Fixes #466.
> @1aurabrown => Removes ability to disable back button.

- Artsy/Classes/View Controllers/ARExternalWebBrowserViewController.m
- Artsy/Classes/View Controllers/ARInternalMobileWebViewController.m
This is an effort to try to fix #527 (https://rink.hockeyapp.net/manage/apps/37029/app_versions/34/crash_reasons/37717442)
It looks like your typical ‘delegate messages send to an already deallocated object’ crash,
and indeed the `UIWebView.delegate` property is of type `assign`, but the superclass `TSMiniBrowser` is already nillifying the delegate in its dealloc implementation… So I don’t understand how this can occur.
These changes just add a few more explicit nillifications in hopes that it fixes this somehow, but if it does then I’m currently unsure why it does.
> @ashfurrow => Add more paranoid nillifying of delegates.

- Artsy Tests/ARUserManagerTests.m
- Artsy.xcodeproj/project.pbxproj
- Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme
- Artsy/Artsy.entitlements
- Artsy/Classes/ARAppDelegate.m
- Artsy/Classes/Networking/ARKeychainable.h
- Artsy/Classes/Networking/ARKeychainable.m
- Artsy/Classes/Networking/ARUserManager.m
- CHANGELOG.md
- Gemfile.lock
My Watch App introduced some bugs that are only apparent when using the app store build on a device. Sigh. 
So I've gone and re-created our eigen certs, and ensured that we have consistent access groups between all the apps. In started to work on the tests I ended up in the bushes a bit and created https://github.com/artsy/eigen/issues/533 as I realized that this is outside of the current scope. 
fixes https://github.com/artsy/eigen/issues/530
> @alloy => Ensure that the keychain always works through access groups

- Artsy/Classes/View Controllers/ARArtworkPreviewImageView.m
This is ugly, but will get reverted as soon as the 2.0.1 bugfix release
has been released. It should at least give us some insight into whether
or not this code is in any way related to, as of yet, unreproducible
issue https://github.com/artsy/eigen/issues/526.
> @orta => Temp disable placeholder images at right size in effort to debug crash.

- Artsy/Classes/Utils/ARSwitchBoard.m
- CHANGELOG.md
Fixes: https://github.com/artsy/eigen/issues/529
> @ashfurrow => Route to /auction/ when tapping on a bid button

- Artsy/Classes/View Controllers/ARInternalMobileWebViewController.m
- Gemfile
- Gemfile.lock
- Podfile
- Podfile.lock
- docs/BETA_CHANGELOG.md
If a user would navigate back before the webview fully finished loading,
the VC would be retained by the timer and released once the timer was
invalidated, which in turn would lead to a crash if the VC was
referenced after invalidating the timer.
Fixes #557. (See there for more details.)
Tested on :iphone:
> @orta => [Martsy] Fix crash due to NSTimer based retain cycle.

- Artsy.xcodeproj/project.pbxproj
- Artsy/Tooling/ARAutoLayoutDebugging.m
- Artsy/Tooling/ARFilteredStackTrace.h
- Artsy/Tooling/ARFilteredStackTrace.m
I did not include a function that returns a pretty string, I’m leaving that up to you to see if a default version makes sense or if you always want to do that where you’ll be using the stack trace.
----
```objc
NSLog(@"%@", ARFilteredStackTrace(0, nil));
```
```
2015-07-03 15:39:17.477 Artsy[90093:2106250] (
"Artsy: -[ARAppDelegate application:willFinishLaunchingWithOptions:] (0x100626eaa)",
"Artsy: main (0x10062ac27)"
)
```
----
```objc
NSLog(@"%@", ARFilteredStackTraceWithWhiteList(0, @[[NSBundle mainBundle], @"UIKit"], nil));
```
```
2015-07-03 15:39:17.479 Artsy[90093:2106250] (
"Artsy: -[ARAppDelegate application:willFinishLaunchingWithOptions:] (0x100626f63)",
"UIKit: -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] (0x102cbe721)",
"UIKit: …
```
> @orta => [Debug] Add ARFilteredStackTrace helper.

- Artsy/Views/Artwork/ARArtworkPreviewImageView.m
- docs/BETA_CHANGELOG.md
¯\\\_(ツ)_/¯ hoping that this fixes https://github.com/artsy/eigen/issues/526
Is this new? 
```
@interface UIView (UIConstraintBasedLayoutInstallingConstraints)
- (NSArray *)constraints NS_AVAILABLE_IOS(6_0);
- (void)addConstraint:(NSLayoutConstraint *)constraint NS_AVAILABLE_IOS(6_0); // This method will be deprecated in a future release and should be avoided.  Instead, set NSLayoutConstraint's active property to YES.
- (void)addConstraints:(NSArray *)constraints NS_AVAILABLE_IOS(6_0); // This method will be deprecated in a future release and should be avoided.  Instead use +[NSLayoutConstraint activateConstraints:].
- (void)removeConstraint:(NSLayoutConstraint *)constraint NS_AVAILABLE_IOS(6_0); // This method will be deprecated in a future release and should be avoided.  Instead set …
```
> replace removeConstraints with deactivateConstraints in ARArtworkPreviewImageView

- Artsy/App_Resources/Launch Screen.xib
- docs/BETA_CHANGELOG.md
fixes https://github.com/artsy/eigen/issues/607
First, I'm using the large retina version of the logo.
Second, I'm setting up a size class-specific constraint to limit the size of the logo on phones.
> @alloy -> constrain width of launch logo on iphone

- Artsy/Categories/Apple/UIImage+ImageFromColor.m
- docs/BETA_CHANGELOG.md
The grey placeholder image was alway square, even when we had an accurate aspect ratio with which to make a properly-sized placeholder. This is because a previously-cached square image was always being used.
> @alloy -> don't use cached square image unless requested

- .gitattributes
For everyone else: https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/
and https://twitter.com/orta/status/619139230162362368
> @alloy => Make changelogs use a union merge

- Artsy/Models/Feed_Timelines/ARHeroUnitsNetworkModel.m
- Artsy/Networking/ArtsyAPI.m
- Artsy/View_Controllers/Feed_VCs/ARShowFeedViewController.m
- Artsy_Tests/Model_Tests/Feed_Timeline_Tests/ARHeroUnitsNetworkModelTests.m
- docs/BETA_CHANGELOG.md
Noticed a related problem in the network model where the model only sets its `heroUnits` property if a non-`nil` success block has been passed. This breaks use of the model with KVO, which is how its used. In fact, the method is only called with a success block once, and never with a failure block. Worth entertaining simplifying its API. 
Fixes #669.
> @alloy => Hero units offline loading

- Artsy/Views/Styled_Subclasses/ARCollapsableTextView.m
- docs/BETA_CHANGELOG.md
Looks like it was introduced in [this commit](https://github.com/artsy/eigen/commit/44ec4057e9b9b0131a2893be57620b91ae77568d#diff-3b2cfb2303245110984718f08dcb603d).
Fixes #672.
> @alloy => Fixes infinite recursion on gene text expansion.

- Artsy/View_Controllers/Util/ARNavigationController.m
- Artsy_Tests/View_Controller_Tests/Util/ARNavigationControllerTests.m
- docs/BETA_CHANGELOG.md
The bug appears to have been introduced [here](https://github.com/artsy/eigen/commit/5132299bf86569ab39e4c1aff47c9e9d0690e577#diff-4fa974736d8e8c4f6ac97956648e6f5aL360) and is fixed by observing the `hidesBackButton` key value on the observed view controller. 
Fixes #681.
> @alloy => Hides back button when presenting VIR on iPhone via rotation

- Artsy/App_Resources/Artsy-Info.plist
Add "Renders with edge antialiasing" to Artsy-Info.plist to reduce pixelation on the black rectangle loading animation.
> Add edge antialiasing to .plist

- Makefile
This makes it possible to build with different versions of Xcode and it wasn't really needed, anyways.
> Remove $(DEVICE_HOST) from build command.

- Podfile.lock
There's an issue with imports in older versions, which accidentally used to work with older CP versions, but breaks with >= 0.38.
```
⌦
/var/folders/by/znchwbl51gdfht48wv0m4t6r0000gn/T/eigen/Pods/Analytics/Analytics/SEGAnalyticsIntegration.m:5:9:
'TRVSDictionaryWithCaseInsensitivity.h' file not found with <angled>
include; use "quotes" instead
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Bump version of 'Analytics/Segmentio'

- Artsy/View_Controllers/Util/ARNavigationController.m
- docs/BETA_CHANGELOG.md
Fixes #725.
I could only duplicate this by rapidly pressing the Search/Close buttons a bunch of times, so adding a simple check to make sure the Search VC is not already shown.
> @alloy => [Search] Don't push search view controller before fully dismissed

- Artsy/App/Artsy-Prefix.pch
- Artsy/App/Watch/ArtsyWatchAPI.m
- Artsy/Networking/ARRouter.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- Artsy/View_Controllers/Debug/Quicksilver/ARQuicksilverViewController.m
- Artsy/View_Controllers/Fair/ARFairPopupViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/ARPersonalizeWebViewController.m
- Artsy/View_Controllers/Util/Logging/ARLogger.h
- Gemfile
- Gemfile.lock
- Podfile
- Podfile.lock
Closes #695.
There’s a whole bunch of iOS 9 warnings with Xcode 7, but some of those can’t be fixed without breaking it on Xcode 6 or having to resort to ugly additional macros, so I’m not bothering with that for now until Xcode 7 is GM.
Can you please review this commit specifically, as it’s related to changes you made updating CocoaLumberjack and AFNetworking https://github.com/artsy/eigen/commit/4c209c5884b2fad1fde24c430c51f3b11c404a2b
> @orta => Fix xcode 6.4 warnings

- Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
- docs/BETA_CHANGELOG.md
> @orta => [Internal WebView] Don’t show stuck progress indicators or broken pages.

- Podfile.lock
- docs/BETA_CHANGELOG.md
As stated in the CHANGELOG, remove your Pods checkout and re-install. Or remove the offending pods one by one, but apparently there’s an issue where you also have to remove the header dirs.
> @jorystiefel => [Pods] Update for current CP caching mechanism.

- Artsy/Networking/API_Modules/ARUserManager.h
- Artsy/Networking/API_Modules/ARUserManager.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginViewController.h
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginViewController.m
- Artsy_Tests/Networking_Tests/API_Modules/ARUserManagerTests.m
- Artsy_Tests/Stubs/ARUserManager+Stubs.m
- Artsy_Tests/View_Controller_Tests/Login_and_Onboarding/ARLoginViewControllerTests.m
- docs/BETA_CHANGELOG.md
This will show the available credentials on the login view, if there are any credentials available. It takes a second or two for the alert to show, so that’s a slight UX downer :-/ /cc @katarinabatina
> @jorystiefel => [Authentication] Add support for Shared Web Credentials.

- Artsy/Networking/ARRouter.m
- Artsy_Tests/Networking_Tests/ARRouterTests.m
- docs/BETA_CHANGELOG.md
The problem comes down to our `User-Agent` not identifying itself as any specific type of browser. Adding in these compatibility strings `Mozilla/5.0` and `AppleWebKit/601.1.46 (KHTML, like Gecko)` fixes the font loading issue.
The only minor issue is that I have not found anyway to access the actual `AppleWebKit` version number, so that is hardcoded in the string. Open to suggestions.
Fixes #815.
> @orta => [Web Fonts] add missing browser agent strings for compatibility

- Artsy/App/ARAnalyticsConstants.h
- Artsy/App/ARAnalyticsConstants.m
- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/Networking/API_Modules/ARUserManager.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/2_-_Calls_to_Action/ARSignUpActiveUserViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/2_-_Calls_to_Action/ARSignUpSplashViewController.m
Figured it won't need a changelog, but happy to add if you prefer. Might be worth auditing if this will still trigger the normal logged in via email analytics calls too.
> @alloy => Add ARAnalyticsSignInWebCredentials to note when logging in via web creds

- Artsy/Views/Utilities/ARSpinner.m
- docs/BETA_CHANGELOG.md
This appears to be a compiler bug, but also a case where we were
using an incorrect type (double) anyways.
Fixes #838.
> @jorystiefel => [Spinner] Fix a bug where the spinner would only rotate 8 times.

- Artsy/View_Controllers/Embedded/Generics/AREmbeddedModelsPreviewDelegate.m
The absence of any popover on http://cl.ly/2g0D1B1j2V3a in the artists page is shows the fix, as opposed to the behaviour seen in http://cl.ly/0U3R3n1Y002l & #863
> @alloy => Ensure the cell which we could be highlighting is visible on screen

- Artsy/Views/Artwork/ARArtworkActionsView.m
- docs/BETA_CHANGELOG.md
Show a spinner when transitioning back to the auction artwork until the new top bid information comes in. This prevents the user from seeing the old bid amount and a "Not for sale" message for a brief moment until the new data loads.
> @alloy => [Bidding] Show spinner to remove flash of old amount, "not for sale"

- Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
Adjust the float delta, this was giving us an `NSAssert` failure on iPad (but not iPhone).
> @alloy => [WKWebView] Fix for scroll deceleration assert fail on iPad

- Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m
- docs/BETA_CHANGELOG.md
Fixes issue of iPad bidding returning you to a Force web view instead of the native artwork view
> @alloy => [Bidding] Return to native artwork view on iPad after bid

- Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
- docs/BETA_CHANGELOG.md
> @orta => [WKWebView] Don’t use deceleration rate bug workaround on iOS 8.

- Artsy/View_Controllers/Util/ARNavigationController.m
- docs/BETA_CHANGELOG.md
Closes #850.
Disable the Search button and re-enable it once the view controller has transitioned to the search view, in attempt to prevent rapidly pressing the search button from trying to push the same VC twice.
> @alloy => [Crash] attempt to fix search crash

- Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.h
- Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
- Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
Fixes : https://github.com/artsy/eigen/issues/898
So problem is:
* Trial user opens page
* Before page has had chance to load, it is stopped so we can do a log in prompt for bidding
* The web view doesn't have a URL, thus reloading does nothing.
``` objc
- (void)userDidSignUp
{
[self.webView loadRequest:[self requestWithURL:self.webView.URL]];
}
```
> @alloy => [auctions+trial] Add support for reloading web views not done loading

- Artsy/Networking/ARRouter.m
- Artsy_Tests/Networking_Tests/ARRouterTests.m
- docs/BETA_CHANGELOG.md
I don’t know why there was a test that checked for the device name being included, I don’t see a need for it.
When including the device name, it could contain characters outside the allowed character set, which could lead to encoding issues on the backend. E.g.
```
Mozilla/5.0 Artsy-Mobile/2.3.0 Eigen/2015.10.15 Device: Eloy Durán’s iPod/2.3.0 (iPod touch; iOS 8.4.1; Scale/2.00)AppleWebKit/601.1.46 (KHTML, like Gecko)
```
Includes a unicode `’` and results in the following error on the `https://stagingapi.artsy.net/api/v1/me/bidder_position` endpoint:
_[Full error](https://gist.github.com/alloy/3785563548fa0d02302e)_
```
irb(main):005:0> puts bt.reject { |s| s.include?('gems') }
/srv/www/gravity/releases/20151015140557/app/api/v1/me_bidder_positions_endpoint.rb:63:in `block (3 levels) in …
```
> @orta => [Router] Fix error with disallowed chars in User-Agent.

- Artsy/App_Resources/Artsy-Info.plist
- Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m
- Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.h
- Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
- docs/BETA_CHANGELOG.md
Fixes #687 & #899.
Untested on iPhone as currently martsy won't load the auctions views. (See Slack.)
> @orta => [iPad] skip onboarding when signing-up when trying to bid.

- Artsy/App/ARAppActivityContinuationDelegate.m
- Artsy/Constants/ARDefaults.h
- Artsy/Constants/ARDefaults.m
- Artsy/Networking/API_Modules/ARUserManager.h
- Artsy/Networking/API_Modules/ARUserManager.m
- Artsy/Networking/API_Modules/ArtsyAPI+Private.h
- Artsy/Networking/ARRouter.m
- Artsy/Networking/ArtsyAPI.h
- Artsy/Networking/ArtsyAPI.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/2_-_Calls_to_Action/ARSignUpSplashViewController.m
- Artsy/View_Controllers/Util/ARTrialController.h
- Artsy/View_Controllers/Util/ARTrialController.m
- Artsy_Tests/Networking_Tests/API_Modules/ARUserManagerTests.m
- Artsy_Tests/Networking_Tests/API_Modules/ArtsyAPI+PrivateTests.m
- docs/BETA_CHANGELOG.md
I've renamed the key to make it more obvious what should be happening, ideally though we should be moving to our ArtsyAuthentication lib for this kind of stuff.
> @alloy => Use the keychain for checking the authentication token - fixes #939

- Artsy/App/ARAppBackgroundFetchDelegate.m
- Artsy/App/ARAppDelegate.m
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/Models/Feed_Timelines/ARFeedSubclasses.h
- Artsy/Models/Feed_Timelines/ARFeedSubclasses.m
- Artsy/Models/Feed_Timelines/ARFeedTimeline.h
- Artsy/Networking/ARRouter.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m
- Artsy/View_Controllers/Feed_VCs/ARSimpleShowFeedViewController.m
- docs/BETA_CHANGELOG.md
**This should be merged during the next sprint, it is not a trivial feature / bug fix**
So, there isn't much in my life I feel guilty about. However, every time I open the app, I feel a little pang of guilt. I made background fetch a long time ago, and haven't gone back to remedy my original implementation. IMO, it's pretty essential.
The original problem was that it used our router, and API clients to grab data which depending on the locked-ness of your iPhone could totally log you out. I've fixed this by giving the fetch-er it's own NSURLSession setup, and totally obviated any work that our internal networking stack does. Just to be paranoid, I've added extra precautions everywhere. From file serialisation, to keychain.
On the plus side, I did [some …
> @alloy => Bring back background fetch

- Artsy/View_Controllers/Feed_VCs/ARSimpleShowFeedViewController.m
- docs/BETA_CHANGELOG.md
Fixes #965 
When there was no size context for the ShowFeeds's header stackview's height, it would default to the one provided by `systemLayoutSizeFittingSize` which is a full screen. Defaulting to 0,0 makes it fit to the smallest possible value.
> Set the header's size to fit to be CGSizeZero

- .gitignore
- Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme
- Makefile
- config/generate_changelog_short.rb
Removes the side-effect of creating the changelog_short by capturing `puts` directly from ruby.
Removes the scheme actin that was opening hockey when it doesn't need it.
> Cleanup the changelog + Remove hockey from deployment

- Artsy/View_Controllers/Feed_VCs/ARSimpleShowFeedViewController.m
- CHANGELOG.md
- docs/BETA_CHANGELOG.md
Decreases the time before attempting another reconnect, if they're failing then they're probably taking less than a second to show, plus who waits for 3 seconds for anything nowadays?
> Don't wait three seconds between re-tries for failed networking

- Artsy/App/ARAppBackgroundFetchDelegate.m
- docs/BETA_CHANGELOG.md
So this is the crasher. Closes #968
Looking into ideas about what would happen if the app was first launched in the background for the odd state.
> @alloy => Add support for not raising when downloading the feed from the background

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARSwitchboard+Eigen.m
- Artsy/Categories/Apple/UIViewController+FullScreenLoading.h
- Artsy/Categories/Apple/UIViewController+ORStackView.swift
- Artsy/Models/API_Models/Auctions/Sale.h
- Artsy/Models/API_Models/Auctions/SaleArtwork.h
- Artsy/Networking/API_Modules/ArtsyAPI+Artworks.h
- Artsy/Networking/API_Modules/ArtsyAPI+Sales.h
- Artsy/Networking/API_Modules/ArtsyAPI+Sales.m
- Artsy/Networking/ARNetworkConstants.h
- Artsy/Networking/ARNetworkConstants.m
- Artsy/Networking/ARRouter.h
- Artsy/Networking/ARRouter.m
- Artsy/Resources/Artsy-Bridging-Header.h
- Artsy/View_Controllers/Auction/AuctionNetworkModel.swift
- Artsy/View_Controllers/Auction/AuctionViewController.swift
- Artsy/View_Controllers/Core/ARArtistViewController.m
- Artsy/View_Controllers/Fair/ARFairArtistViewController.m
- Artsy/View_Controllers/Fair/ARShowViewController.m
- Artsy/View_Controllers/Util/ARScrollNavigationChief.h
- Artsy/View_Controllers/Util/ARScrollNavigationChief.m
- Artsy/Views/Auction/AuctionBannerView.swift
- Artsy/Views/Auction/AuctionTitleView.swift
- Artsy/Views/Auction/SaleViewModel.swift
- Podfile
- Podfile.lock
This is work towards #974. The infrastructure is acceptable for now until we get https://github.com/artsy/mobile/issues/65 figured out, but I've tried to keep things as loose as possible so we don't get locked in or anything. 
The following view controllers:
- ARArtistViewController 
- ARFairArtistViewController 
- ARShowViewController
Had common code in them that I needed, so I abstracted it into a new UIViewController extension. Spacecommander went to town on those files, so the PR is smaller than it appears.
> Auction banner

- Artsy/Resources/Artsy-Bridging-Header.h
- Artsy/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
- Artsy/Views/Auction/AuctionBannerView.swift
In terms of trying to keep the seams smaller between swift/objc - we can remove the isPad check with a size class check. This makes life much easier if we ever decide to do real work surrounding the split screen stuff that we do support already.
> Use size classes instead of isPad now that we're post iOS7

- Artsy/View_Controllers/Contact/ARInquireForArtworkViewController.m
- Artsy_Tests/View_Controller_Tests/Contact/ARInquireForArtworkViewControllerTests.m
- CHANGELOG.yml
You're an admin, you go test a bug report. Ten minutes later you find yourself seeing this JSON: 
```
Printing description of JSON:
{
detail =     {
inquirer =         (
"cannot be an admin"
);
};
message = "Inquirer cannot be an admin.";
type = "param_error";
}
```
This changes the name section on an inquiry to let you know it will fail if you are using an artsy email address as a user.
> Show messages about failing inquiries if you're an admin

- Artsy/App/ARAppDelegate.m
- Artsy/Tooling/ARWebViewCacheHost.m
- CHANGELOG.yml
fixes #1048 
fixes #1047 
Adds the same support we added for iOS7 back in #198
> Support iOS again, and support gracefully deprecating the platform when we choose 

- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m
- CHANGELOG.yml
The previous code was presenting the top menu VC during routing, whereas it should’ve only returned it. This was leading to a blank web view being shown when tapping a “works for you” push notification.
Why the blank web view is being shown I’m not certain of, but as the initial cause for it being shown is faulty logic, I didn’t spend more time chasing that.
> [Push Notification] Fix blank view issue with ‘works for you’.

- Artsy/App/ARSwitchBoard.m
- CHANGELOG.yml
https://rink.hockeyapp.net/manage/apps/37029/app_versions/49/crash_reasons/102830998?type=overview
----
If you really do prefer a sheet on iPhone, we’ll have to add a device conditional, because a sheet in a popover on iPad has to point to a location and there really is none to point to:
> [iPad] Fix crash when presenting an alert regarding external URL.

- Artsy/Views/Artwork/Auctions/ARCountdownView.m
Because different platforms do `NSInteger` differently, leading to... problems.
Didn't add tests since this doesn't change behaviour (verified existing tests pass).
Fixes #1062.
> Use NSNumberFormatter instead of format strings

- Artsy_Tests/Stubs/ARUserManager+Stubs.m
This is a possible fix for #985. According to [other SDWebImage users](https://github.com/rs/SDWebImage/issues/507), there's a problem with deadlocking which is related to a race condition checking if a request is cancelled/finished. 
This solution cancels all downloads whenever we stub the user (which is where we've been deadlocking). Fairly straightforward – ran it a bunch of times locally and it was all good.
> Fixes deadlocks.

- Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
- Artsy/Networking/ARRouter.m
- CHANGELOG.yml
The API calls for filter come in as a dictionary, with the Artworks being inside `hits` rather than at the root of the array. 
This PR will mean that we need to deploy another build of our current beta 2.3.5.
> Get Gene pages working again

- CHANGELOG.yml
Added a section for upcoming called `details` that gives an overview for an upcoming releases aim. Separates out developer related notes from user facing ones too. Was getting tough to see what affected a user and what is behind the scenes.
> Update CHANGELOG format a bit

- Artsy/App/ARHockeyFeedbackDelegate.swift
- CHANGELOG.yml
I think if `PHImageManager` is left async it will send multiple results, which we took to imply sending multiple feedback managers. We only need the one, so I've made is synchronous, and done some device testing 0.5 seconds is working for me.
> Fix the snapshot feedback mechanism

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/App/ARAppDelegate.m
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/View_Controllers/Core/ARHeroUnitViewController.h
- Artsy/View_Controllers/Core/ARHeroUnitViewController.m
- Artsy/Views/Utilities/ARSiteHeroUnitView.h
- Artsy/Views/Utilities/ARSiteHeroUnitView.m
- Artsy_Tests/Analytics_Tests/ARAppAnalyticsSpec.m
- Artsy_Tests/Stubs/ARStubbedAnalyticsProvider.h
- Artsy_Tests/Stubs/ARStubbedAnalyticsProvider.m
- CHANGELOG.yml
- Dangerfile
As this is testing the app delegate's launch code, I'm a bit at odds on how to add a test covering us for this. Going to take a stab at making it possible for us to run analytics tests, but I don't think I can cover _this case_.
> Fixes missing analytics for the tab views

- Artsy/App/ARAnalyticsConstants.h
- Artsy/App/ARAnalyticsConstants.m
- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
Allow us to differentiate between push / taps WRT the bell.
> Add support for showing the bell tapped analytics events

- Artsy/View_Controllers/Fair/Views/ARSearchFieldButton.m
- Artsy_Tests/View_Controller_Tests/Fair/Views/ARSearchFieldButtonTests.m
- CHANGELOG.yml
ARSearchFieldButton accidentally used `self.delegate` before it existed, now it creates the gesture on `setDelegate` - :phone:
> Fix the ARSearchFieldButton tap delegate

- Artsy_Tests/View_Controller_Tests/Fair/Views/ARSearchFieldButtonTests.m
- Dangerfile
- Gemfile.lock
- Makefile
Contains a broken snapshot.
Danger should spot this and provide a message for us.
> Use danger to show error messages for snapshots #trivial

- Artsy.xcodeproj/project.pbxproj
- Artsy/View_Controllers/Auction/AuctionViewController.swift
- Artsy/View_Controllers/Embedded/Generics/AREmbeddedModelsViewController.h
- Artsy/View_Controllers/Embedded/Generics/AREmbeddedModelsViewController.m
- Artsy/Views/Auction/SaleViewModel.swift
- Artsy_Tests/View_Controller_Tests/Auction/SaleViewModelTests.swift
- Artsy_Tests/View_Controller_Tests/Embedded/AREmbeddedModelsViewControllerTests.m
- CHANGELOG.yml
- Podfile.lock
Related to #972.
@orta I had some questions about how to use the embedded model view controller. Specifically, what are you thoughts on an approach to display not _just_ artworks? We'll need two different cells, one for each masonry/list layout. Could we chat tomorrow sometime?
In the mean time, filtering by price works :tada: and I shored up the tests around the sale view model.
> Applies refine settings to filter artworks

- Artsy.xcodeproj/project.pbxproj
- Artsy/View_Controllers/Auction/AuctionInformationViewController.swift
- Artsy/Views/Styled_Subclasses/Buttons/ARNvagiationButton+Swift.swift
- Artsy_Tests/View_Tests/Buttons/NavigationButtonTests.swift
- CHANGELOG.yml
This abstracts the messiness of working with the `ARNavigationButton` stuff with Swift into one place.
Fixes #1169.
> Adds Swift abstraction for Navigation Buttons

- Artsy/Resources/Artsy-Bridging-Header.h
- Artsy/View_Controllers/Auction/AuctionViewController.swift
- Artsy/Views/Auction/SaleArtworkViewModel.swift
- Artsy_Tests/View_Controller_Tests/Auction/SaleArtworkViewModelTests.swift
- CHANGELOG.yml
... where you can then bid on the artwork 🎉
So the bridging head changers are a bit odd, eh? What's going on?
Well we have our switchboard, right? And it has methods on it that return various `UIViewController` subclasses. In order to call those methods, Swift needs to have access to the return types of the functions as well the types of any parameters. So even though I'm passing in a `nil` fair, Swift still needs `Fair.h` in the bridging header.
> Tapping an auction lot takes you to that lot's artwork page

- Podfile
- Podfile.lock
Thus: using shallow clones in CP. This it's safe to assume anything we wanted in 3.0.3 is in 3.0.7
> Fix the massive pods download by using Analytic's from a tag

- Artsy/App/ARSwitchBoard.h
- Artsy/App/ARSwitchBoard.m
- Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
- CHANGELOG.yml
We have a link that needs to escape the eigen sandboxing around routing, in this case - the link is a link that safari can handle and create an event in someone's calendar. In the future, well, it could be anything. 
So we want to provide a way to optionally skip this routing for _non_ artsy URLs. So, prerequisites are: not in this list `artsyHosts = [NSSet setWithObjects:@"art.sy", @"artsyapi.com", @"artsy.net", @"m.artsy.net", @"staging.artsy.net", @"m-staging.artsy.net", nil];`, and has a query string which includes the string `eigen_escape_sandbox`. 
/cc @broskoski
> Add support for breaking out of the sandbox when needed

- Artsy/Constants/ARDefaults.h
- Artsy/Constants/ARDefaults.m
- Artsy/Networking/ARNetworkConstants.h
- Artsy/Networking/ARNetworkConstants.m
- Artsy/Networking/ARRouter.m
- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- Artsy_Tests/Networking_Tests/API_Modules/ARUserManagerTests.m
- Artsy_Tests/Supporting_Files/ARTestHelper.m
- CHANGELOG.yml
Makes it easier for non-cocoa devs to move to test Eigen support without deploying to staging or production:
> Add support for custom web / api staging urls for eigen

- Artsy/Networking/ARNetworkConstants.h
- Artsy/Networking/ARNetworkConstants.m
- Artsy/Networking/ARRouter.m
- Artsy/View_Controllers/Embedded/Sale_Artworks/ARSaleArtworkItemMasonryModule.m
- Artsy_Tests/Networking_Tests/ARRouterTests.m
- CHANGELOG.yml
Passes the UUID for a trial account as a header so that analytics events can be hooked up between eigen and martsy/force. The ID is a header named `"X-Eigen-Trial-ID"`
> Add a header for the eigen trial user account to web requests

- Artsy/Models/API_Models/Partner_Metadata/Artwork.m
- Artsy/View_Controllers/WorksForYou/ARWorksForYouViewController.h
- Artsy/View_Controllers/WorksForYou/ARWorksForYouViewController.m
- CHANGELOG.yml
TODO (on top of what's in #1158)
Demo:
Scroll and load:
Click:
Will do this later today hopefully, and then separately do new snapshot tests, mark notification as read, etc
> [WorksForYou] V1 of the view controller

- Artsy/App/ARSwitchBoard.h
- Artsy/App/ARSwitchBoard.m
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
- CHANGELOG.yml
- Podfile.lock
For Live Auctions we need to be able to deal with routes like `https://live.artsy.net/auction` - both from external links on the website and from inside the app. So as JLRoutes has no concept around host based routing, I've added a _very simple_ domain router. So far this is the simplest thing we'll need. 
I still have to go and add the route to echo, so I've not added tests around the actual existing routing that should happen from the app. As that can do something different in my next PR.
fixes #1198
> Support routing a domain to a view controller - fixes #1198

- Artsy/App/ARFonts.h
Fixes #1071.
The module is called `Artsy_UIFonts` not `Artsy_OSSUIFonts`.
/cc @craigspaeth @kanaabe
> [Fonts] Fix OSS import statement.

- .gitignore
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController+DeveloperExtras.h
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController+DeveloperExtras.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
OK - THIS IS AMAZING. 
My compile & run cycle just went from (and I counted) 11 seconds to ~1 second. 
**Injection**: Dynamically re-compiles files you've saved, and ships those changes to your currently running app.
**How does this work?** In simple, it is an Xcode plugin that can compile your code into a bundle, this bundle is then added to your app. It will include newer versions of the classes you've injected via this bundle, then it is up to you to do something with this.
**What does this PR do?** So, the default behaviour of Injection is to allows re-compiled classes to know that they have been re-compiled. Given the `viewDidLoad` heavy view controllers we create I felt it would be better for our flow to work a little different from that.
Instead of letting the view controllers …
> Support code injection !m!

- CHANGELOG.yml
I had a think about this, our changelogs are sent to apple during beta review, I don't think it's a good idea to include this line.
> Removed the Dev reference to injection

- Artsy/App/ARAppDelegate.m
- CHANGELOG.yml
Related to #1242
We were no longer showing the on-boarding screen when launching the app.
> [Onboarding] Re-enable on launch, which was accidentally disabled.

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARAnalyticsPapertrail.h
- Artsy/App/ARAnalyticsPapertrail.m
- Artsy/App/ARAppDelegate+Analytics.m
- CHANGELOG.yml
Nothing fancy, just stores entities that have slugs. How/if we’re going to use this data in the future is not yet defined.
> [On-boarding] Collect screen data to improve future on-boarding.

- Dangerfile
Interesting that the last one didn't fail, the syntax changed.
> Danger syntax fixes

- Artsy/App_Resources/Artsy-Info.plist
There's a way to skip that question in iTunes connect, by doing this. So less is less.
> Add the plist option for 'does not contain crypto' #trivial

- Artsy/App_Resources/Artsy-Info.plist
- Artsy/Networking/Network_Models/ARWorksForYouNetworkModel.m
Fixes a typo that failed a build of the beta: https://circleci.com/gh/artsy/eigen/1834 
As we run tests in debug, this slipped past us.
> Fix a typo in the #ifdef for release builds #trivial

- Artsy/Networking/API_Modules/ARUserManager.m
- CHANGELOG.yml
Fixes https://github.com/artsy/eigen/issues/1123#issuecomment-198306933.
> [Analytics] Make ‘sign-up/connect with email/facebook/twitter’ -> ‘created account’ consistent.

- Artsy/View_Controllers/Search/ARSearchViewController.m
- CHANGELOG.yml
This makes it so when you're trying to use the search more than once per session, you can easily do another query as the text is highlighted for you. 
As this is probably more the use case than the opposite, of wanting to expand on the current query,  I've added it.
> [Search] Auto-selects the search query when you go back to a search view

- Dangerfile
See - https://github.com/artsy/eigen/pull/1370
Danger wasn't looking for a swift syntax WRT `fit` tests
> Add a check for `fit` in swift tests #trivial

- Artsy.xcodeproj/project.pbxproj
- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.h
- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/4-_Onboarding_New_User/ARCollectorStatusViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.h
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingHeaderView.h
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingHeaderView.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingNavigationItemsView.h
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingNavigationItemsView.m
- Artsy_Tests/View_Controller_Tests/Login_and_Onboarding/AROnboardingViewControllerTests.m
- CHANGELOG.yml
Previous PR for this work: #1397
Current state:
Introduced:
- new header view
- new sequence navigation view 
`ARPersonalizeViewController` will now be reused for all 3 questions in the sequence (though it'll probably embed a different classes for artist/category search and budget).
> [Onboarding] Basic Questionnaire Sequence

- Artsy.xcodeproj/project.pbxproj
- Artsy/View_Controllers/Feed_VCs/ARSimpleShowFeedViewController.m
- Artsy_Tests/Extensions/ARTopMenuViewController+Testing.h
- Artsy_Tests/Extensions/ARTopMenuViewController+Testing.m
- Artsy_Tests/Stubs/ArtsyOHHTTPAPI.m
- Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m
- Artsy_Tests/View_Controller_Tests/Fair/ARFairGuideViewControllerTests.m
- Artsy_Tests/View_Controller_Tests/Login_and_Onboarding/ARCreateAccountViewControllerTests.m
Make it so that you don't need to know all the requests an `ARTopMenuViewController` makes by default.  Should bring us back down to 0 unstudied networking requests.
> Always create an ARTopViewController with its networking stubs in tests #trivial

- Artsy/Models/API_Models/Partner_Metadata/Artwork.h
- Artsy/Models/API_Models/Partner_Metadata/Artwork.m
- Artsy/Views/Auction/SaleArtworkViewModel.swift
- Artsy/Views/Auction/SaleViewModel.swift
- CHANGELOG.yml
I've added a macro so all properties, method parameters, etc on `Artwork` are assumed to be non-null, then added nullability specifiers for things that _can_ be null (the `artist` property and methods that accept ObjC blocks). 
As a result, if an artwork _doesn't_ have an artist, its cell looks a little weird:
This happens rarely enough that this seems, to me, an acceptable solution. However, I'm open to suggestions :bow:
Fixes #1413.
> Fixes crash in auction view controller caused by missing nullability specifier

- Artsy/Networking/Network_Models/ARWorksForYouNetworkModel.h
- Artsy/Networking/Network_Models/ARWorksForYouNetworkModel.m
- Artsy/View_Controllers/WorksForYou/ARWorksForYouReloadingHostViewController.m
- Artsy/View_Controllers/WorksForYou/ARWorksForYouViewController.h
- Artsy/View_Controllers/WorksForYou/ARWorksForYouViewController.m
- Artsy_Tests/Networking_Tests/Networking_Models/ARWorksForYouNetworkModelTests.m
- Artsy_Tests/Stubs/ARStubbedWorksForYouNetworkModel.h
- Artsy_Tests/View_Controller_Tests/ARWorksForYouReloadingHostViewControllerTests.m
- Artsy_Tests/View_Controller_Tests/ARWorksForYouViewControllerTests.m
- CHANGELOG.yml
- Podfile.lock
If the network connection is lost, WorksForYouVC will reload if the user navigates elsewhere and returns with a solid connection.
Fixes #1425
> Fix for network failures in WorksForYou

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/App/ARSwitchBoard.m
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
- CHANGELOG.yml
A few notes:
- Since Prediction staging is currently on a _non_ `.artsy.net` domain, it gets treated as an external link. When it gets moved to a proper domain, I'll check that move does indeed work.
- Because of the way routes are loaded on startup, after changing the Adoption, you need to restart the app. Wasn't sure how best to document this, open to suggestions.
Fixes #1466.
> Requires AROption set for native live auctions

- Artsy/View_Controllers/ARSerifNavigationViewController.m
When generating the max size of the bounds for a single VC'd container.
> [SerifNav] Ensure that the padding for the title is taken into account

- Artsy/App/ARSwitchBoard.m
- Artsy/View_Controllers/Debug/Quicksilver/ARQuicksilverViewController.m
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
- CHANGELOG.yml
In favour of #1489.
I'd like to route https://live-staging.artsy.net/54c7e8fa7261692b5acd0600 to use an internal web browser. However, it gets routed as a profile. 
I've changed the switchboard to only route URLs with known Artsy hosts (so an unexpected Artsy subdomain will get routed to an internal web view instead of as a profile, which would remove the custom subdomain and replace it with either staging or production (m)artsy).
Paired with @orta.
> Cleanup surrounding non-native live support

- Artsy/App/ARAppDelegate+Analytics.m
It's looking like some of the shared logic seems to be failing on the artwork view's inquiry button occasionally, adding some more breadcrumbs till  I can devote [considerable time](https://artsy.slack.com/archives/gmv-ios/p1463403163000804) to it.
> Improve analytics when an inquiry fails

- Artsy/App/ARSwitchBoard.m
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
- CHANGELOG.yml
The results are that pretty:
But keep in mind this is an emergency stop-gap and a clutch for users who haven't upgraded to the native live version by the time we hold our first auction. @katarinabatina we can chat about how to make it less gauche.
Fixes #1515.
> Live auctions web views are presented in a modal view controller

- Artsy/Categories/Apple/Int+Metrification.swift
- Artsy/Models/API_Models/Live/LiveEvent.m
- Artsy/Views/Auction/SaleViewModel.swift
Auctions that were held in non-USD currencies were still showing the currency in USD, which ain't optimal. 
I've also added a developer option, giving someone the ability to log live events, mine currently looks like:
```
username:orta@artsymail.com
password:???
suppress_network_logs:yes
log_live_events:yes
```
> [Live] Localization Improvements

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/ARAppDelegate.m
- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/App/ARSwitchboard+Eigen.m
- Artsy/View_Controllers/App_Navigation/ARAppSearchViewController.m
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
Removes the AROption
Uses Echo to look for a flag that will disable React views. 
_minor note_ only one bad thing happens with this ( and I don't think it matters) we used to pass in a "full" artist object when searching, now it's only the ID, but given hat I think the react one ignores the model object completely - it's not really a problem.
> Move React Artists to be the default, and add the ability to stop loading React views

- Artsy/View_Controllers/Live_Auctions/LiveActionStateReconciler.swift
- Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
- Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionBiddingViewModel.swift
- Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
- CHANGELOG.yml
Previously we would say you were the top bidder if you had the top bid, now we check if you're being sold to. The difference is subtle, but important when reserves haven't been set yet.
> [Live] Derive Top Bidder status by using `sellingToBidder`

- Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
In https://github.com/artsy/eigen/pull/1661 I made some changes that used the paddle number checks against aa bidderID, which was OK then, but not OK now, because they're two discrete values that are definitely different. Now you correctly get the green button.
> [Live] Ensure we're consistently using bidderID internally

- Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionFancyLotCollectionViewLayout.swift
The repulsion constant is driven by the bid history delta. When we made the history larger when closed, we changed the maximum delta, and thus the maximum `repulsionConstant`. I decreased the scale down factor to accommodate the new history size and added clarifying documentation to match.
> Fixes problem with fancy lot layout #trivial

- Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift
- CHANGELOG.yml
This isn't comprehensive, but it's a good start. App shouldn't crash the moment you try close a live auction.
> Add checks for iOS 10 support - fixes #1741

- Artsy/Constants/ARDefaults.m
- Artsy/Networking/API_Modules/ArtsyAPI+HEAD.h
- Artsy/Networking/API_Modules/ArtsyAPI+HEAD.m
- Artsy/Networking/ARRouter.m
- Artsy/View_Controllers/ARMutableLinkViewController.m
- Artsy_Tests/View_Controller_Tests/Web_Browsing/ARInternalMobileWebViewControllerTests.m
- CHANGELOG.yml
A black screen would appear on VCs routed through vanity URLs because `viewWIllAppear:` wasn't getting called, which needs to be to [load the profile](https://github.com/artsy/eigen/blob/195633eb3eba35fdaeee709d25931fda7a565428/Artsy/View_Controllers/Fair/ARProfileViewController.m#L56). The result was a blank, black view. 
The fix was to add begin/end appearance transition methods to the appearing view controller. I've tested this with the `/paf-auction` vanity URL on staging and it worked, but the `/ash-test-url` to redirect to a testing live auction, didn't. Looking into it, @joeyAghion was right about us testing for URLs against the staging domain instead of the web domain, so I fixed that. But then we were getting false negatives because AFNetworking was handling redirects with the …
> Fixes problem with redirects on profile VCs

- CHANGELOG.yml
- Dangerfile
This should fail, due to the releases not having a date.
> Let Dangerfile lint our CHANGELOG

- Artsy/View_Controllers/Auction/AuctionBiddersNetworkModel.swift
- Artsy/View_Controllers/Auction/AuctionNetworkModel.swift
- Artsy/View_Controllers/Auction/AuctionSaleArtworksNetworkModel.swift
- Artsy/View_Controllers/Auction/AuctionSaleNetworkModel.swift
- CHANGELOG.yml
Fixes #1774, related to #1747. The problem is that calling `subscribe()` or `flatMap()` on an `Observable` doesn't strongly reference that observable. The code we had assumed it was, and didn't take responsibility for referencing the observables strongly, so they were deallocated before the network call completed. Since Interstellar lacks the clarity of a dispose bag or similar structure to explicitly handle "who owns this observable?", sometimes I feel like I'm just guessing 😞 
I take responsibility for this, I tested on device for the live interface but didn't test the existing non-live auction view controller even though I made changes to its network stack, too.
> Fixes problems with unretained observables

- circle.yml
- dependencyci.yml
Hrm, bit of a weird one this - basically every iOS app using dep CI will need to set this.
> Remove the check for colored

- circle.yml
Mysteriously about 2 weeks ago our Circle builds stopped working. I don't really know the cause, but the symptom was that Circle could not access our [private pod](http://artsy.github.io/blog/2014/06/20/artsys-first-closed-source-pod/).
We were using the `.netrc` to auth our HTTP requests for the git repo, which worked. Now we're using a CircleCI feature called user keys, which is the encouraged way in the docs
> Remove the github auth from CI

- Artsy/App/ARAppDelegate.m
- Artsy/App/ARAppNotificationsDelegate.m
- Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m
The notifications delegate was being created in `load`, one of the first methods to get called when the app is loaded into the runtime. However, because the ARAnalytics DSL swizzles `alloc` to listen for events, events from the notification delegate weren't being fired; the instance had already been created, so `alloc` had already been called. 
This PR fixes that by moving the creation of the notification delegate from `load` into `applicationDidBecomeActive:`. @alloy: Maxim and I wanted to check with you to see if this would have any unintended consequences in the rest of the app.
> Moves notification delegate creation to after analytics setup

- Artsy/App/ARAppDelegate.h
- Artsy/App/ARAppDelegate.m
- Artsy/Networking/API_Modules/ARUserManager.m
- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.h
- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
- No more dodging the onboarding #1837 (done by not allowing an xapp token to qualified as 'having an account')
- Removed the request for push notifications upon launch, because that'll be part of onboarding or artist follows.
> [Onboarding] Tidy up conditionals in App Delegate

- Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
- CHANGELOG.yml
This bug was fixed in iOS 10, so compiling for iOS 10 on my device would throw an exception. This PR fixes that.
> Removes iOS 9-specific workaround for iOS 10

- Artsy/Networking/ARRouter.m
Fix #1868 and #1826 
Have uploaded the new json file and images on our S3 instance (login details are the default artsy it ones in 1pass). 
Links:
- https://s3.amazonaws.com/eigen-production/json/eigen_categories.json
- example image: https://s3.amazonaws.com/eigen-production/images/minimalism.jpg
In Onboarding (these are a few - I did check all of them):
cc @katarinabatina
> [API] Update eigen popular categories url

- Artsy.xcodeproj/project.pbxproj
- Artsy/Categories/PanDirectionGestureRecognizer.swift
- Artsy/View_Controllers/Live_Auctions/LiveAuctionLotBidHistoryGestureController.swift
- Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift
- Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift
- Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotBidHistoryGestureControllerTests.swift
- CHANGELOG.yml
- Podfile
- Podfile.lock
Fixes #1866. Also adds some documenting comments.
The bug's cause was two interfering autolayout constraints, so I got rid of `topMetadataStackConstraint` and used only `alignMetadataToTopConstraint`. This PR is a work-in-progress because the view controller I modified is almost 400 lines of code, with a quarter of that devoted _just_ to a gesture recognizer. I want to move that into its own object.
> Fixes bug with opening lot info 📱

- Artsy/Models/API_Models/Auctions/SaleArtwork.h
- Artsy/Models/API_Models/Auctions/SaleArtwork.m
- Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
- Artsy/Views/Artwork/Auctions/ARArtworkAuctionPriceView.m
- CHANGELOG.yml
Gravity wants to add an explicit "unknown" reserve status, this PR accommodates that. 
Fixes #1835.
> Adds reserve_unknown status

- Artsy/Views/Utilities/ARTabContentView.m
Fixes #1916.
Here's what it now looks like, visually:
> Expands hit areas for toolbar

- Artsy/App/ARAnalyticsConstants.m
- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
Here're the analytics fixes for v3. Some notes:
- Duplicate events with old names were caused by some code left in from the old onboarding that would produce a sort of "catch all". So if we showed the user a view with a class named "ARPersonalizeViewController", we would mangle that into "personalize". @anipetrov Please double check that removing this behaviour didn't accidentally remove any page views we were relying on.
- Firing another page view event when the app goes from foreground -> background -> foreground again is difficult. I've left it out for now, because it really affects how the whole app should work, and the feature would ideally be built into the ARAnalytics library itself. Happy to chat about this, maybe it's something we can squeeze in for v3, but it definitely needs a …
> Analytics fixes for v3

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginViewController.m
Fix issue that @katarinabatina mentioned earlier today with keyboard coverup in iPad landscape.
> [Onboarding] Fix spacing for landscape ipad keyboard

- Artsy/View_Controllers/Util/ARBrowseViewController.m
- Artsy/Views/Utilities/ARTabContentView.m
This is not comprehensive, but covers a good chunk of our use cases. Essentially we would have multiple scrollviews with `scrollsToTop` enabled, which means it doesn't work at all. This covers _most_ cases, a few view controllers do not conform to the `ARMenuAwareViewController`protocol, and so we cannot turn those off. Which may mean it's going to occasionally show.
The real fix as noted in #1891 is to remove the bandage and use apples tab view controller instead of our custom one.
> Use the ARTopMenuViewController to turn on/off scrolls to top on views

- Artsy/View_Controllers/Util/ARNavigationController.h
- Artsy/View_Controllers/Util/ARNavigationController.m
This changes the status bar color to white at 98% opacity on the Home view and leaves in unchanged elsewhere in eigen.
> Status bar background color for Home #trivial

- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
Moves the 3.0.0 release from `upcoming` to `releases` and adds a `date` to it. Also creates skeleton for new patch release in `upcoming`.
> Updates changelog from 3.0.0 release #trivial

- Artsy/Views/Utilities/ARTabContentView.m
- CHANGELOG.yml
Fixes #1976. (Or, rather, attempts to.)
Disclaimer: I wasn’t able to find a reproduction for this crash yet. What I think is happening is that concurrent code influences the result of sending the `topViewController` message to the `oldViewController`, so that by the time line 178 was reached the actual object returned might not respond to `menuAwareScrollView`.
> [Tabs] Don’t send a message to the search VC it doesn’t accept.

- Artsy/View_Controllers/App_Navigation/ARAppSearchViewController.m
Is this part still necessary?
https://github.com/artsy/eigen/blob/master/Artsy/App/ARSwitchboard+Eigen.m#L140
Is there ever going to be a case where we want to be using the old version of this VC?
Fixes #1995
> Fix for searchVC routing to old geneVC #tiny

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizationGeneImageStateReconciler.h
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m
- CHANGELOG.yml
Fixes #1994.
Alas, even with nullability info Xcode did not flag that line as being a risk, not sure what’s up with that, so doing this based purely on the crash log.
> [Onboarding] Fix crash that occurs when de-selecting in a tableview.

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginButtonsView.m
- Artsy/View_Controllers/Util/ARTextFieldWithPlaceholder.h
- Artsy/View_Controllers/Util/ARTextFieldWithPlaceholder.m
Fix #2012.
Cut a lot of padding to make it fit by default on the screen with keyboard up.
Hoping to squeeze this one into 3.0.2! (cc @alloy)
> [Onboarding] Update create account screen with more contrasting changes

- Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
- CHANGELOG.yml
Problem: user sees "Register to Bid" instead of a "Bid" button.
Cause: we were asking for _all_ bidder models for all sales, instead of limiting to our current sale. The models appears to be ordered by oldest first, so after the first page we don't get the model we need to recognize that the user is registered for the sale.
Fix for https://github.com/artsy/auctions/issues/218.
> Fixes problem with users registered for too many sales

- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.h
- Artsy/View_Controllers/Login_and_Onboarding/ARPersonalizeWebViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m
Sorry everyone... this needs to go in for 3.0.2! 
In the clean up around Facebook's signup process, I removed methods we weren't using anymore / didn't do anything, but the email signup method still called it. 
Not sure if I should changelog this, as it hasn't officially gone out yet?
> [!] [Onboarding] Fix code using old delegate method, resulting in crash

- Artsy/View_Controllers/Live_Auctions/LiveAuctionLotListViewController.swift
- CHANGELOG.yml
Fix for https://github.com/artsy/auctions/issues/181.
Explanation: a lot's state is a mapping of its bidding status, which gets [updated](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/Live_Auctions/LiveActionStateReconciler.swift#L139) every time there's a new derived lot data (which happens on every related lot broadcast, which happens very very often). We weren't unsubscribing from old subscriptions, leading to hundreds of callbacks _per lot_ in a list of hundreds of lots. 
This issue is difficult to debug because it only occurs on sales with many lots, so I'll have to monitor an auction later to QA.
> Removes old subscriptions to improve lot list scrolling performance

- Artsy/App/ARSwitchBoard.m
- CHANGELOG.yml
Fixes #2023.
It seems like this was only enabled for iPad, I’m not entirely sure I understand why.
> [Artist] Use new view for artists in gallery context.

- Artsy/View_Controllers/Auction/AuctionInformationViewController.swift
- Artsy/Views/Auction/SaleViewModel.swift
- CHANGELOG.yml
Fix for https://github.com/artsy/auctions/issues/175. Basically we want to show the live start time instead of the auction open time (if it's a live auction).
> More accurate "auction begins" data in auction info VC.

- Artsy/Models/API_Models/LiveAuctionLot.h
- Artsy/View_Controllers/Live_Auctions/LiveAuctionBidViewModel.swift
- Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
- Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
- CHANGELOG.yml
Fix for https://github.com/artsy/auctions/issues/178. Mantle was choking on `null` JSON fields and primitive `UInt64` types. This uses `NSNumber` instead to avoid future problems.
> Fixes auctions with sale artworks that are missing high estimates.

- Artsy/Views/Artwork/ARArtworkActionsView.m
- CHANGELOG.yml
Fix for https://github.com/artsy/auctions/issues/185 . There just wasn't enough space on either side of the countdown timer, autolayout was clipping individual labels.
> Fixes auction countdown timer issue on iPad

- Artsy.xcodeproj/project.pbxproj
This lets Xcode handle all signing and removes provisioning profile settings because they are now deprecated.
> Updated project and target settings for new automatic code signing

- Artsy/Models/API_Models/LiveAuctionLot.h
When I added `nullable`, I got a compile warning about duplicate nullability specifiers, so it looks like the behaviour is the same. Is this something we want to standardize on?
> Fixes assign/strong mixup #trivial

- Artsy/View_Controllers/Auction/AuctionViewController.swift
- Artsy/Views/Pages/ScrollingStickyHeaderView.swift
- CHANGELOG.yml
Pretty simple fix, we were just disregarding the `animated` property.
Fix for https://github.com/artsy/auctions/issues/260.
> Fixes flash of text when pushing auction view controllers.

- Podfile
- Podfile.lock
We were referring to a pod named `Artsy+UIFonts` on a repo which no longer contains an `Artsy+UIFonts.podspec` file, so `pod install` was failing for open source contributors. I spent time over the weekend updating our fonts pods on the [Artsy Specs](https://github.com/artsy/specs) repo, so there shouldn't be any reason to refer to them directly with `git`.
Fixes #2079.
> Updates Podfile to use Artsy Specs repo.

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m
- CHANGELOG.yml
Fix #2095. 
Currently, the fix is that we do not accept Facebook accounts that don't have primary emails - we give the user a warning with what the issue is. 
This seemed simpler for now than having a separate screen that allows users to enter an email (like we used to), because in that case, I would say that users can create an email account instead. 
@orta  - sorry, more indentation grief!
> [Facebook] Fix crash when account does not have associated email

- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- CHANGELOG.yml
I haven't done any work on the ArtworkVC animations so I'm not sure what the ideal is supposed to be - is it supposed to slide up from the bottom? In any case, the current app store version has the VC slide in from right with a gray artwork placeholder before loading the image. For some reason in the iOS10/Xcode8-compiled version, the transition was adding an extra slide. 
Was the slide supposed to be there all along and got lost in the shuffle? If so, is it worth it to try and make it work again, or leave this as-is? 
With redundant animation:
With this PR, and also what the App Store version currently does:
Fixes #2117
> Fix for double sliding animation in artworkVC

- Podfile
- Podfile.lock
So previously we were pointing to a `test` branch that Orta had been working on for this PR: https://github.com/artsy/Aerodramus/pull/1 I've wrapped up that PR, merged, and cut a new release of that library. This just updates Eigen to use that library.
Related to https://github.com/artsy/auctions/issues/262 and https://github.com/artsy/Aerodramus/issues/2 .
> Updates Aerodramus

- Artsy Stickers/Info.plist
- Dangerfile
This is a work-in-progress because I want to verify it works. Once I've done that, I'll modify our `make` task to update it, and update the Info.plist file.
Fixes https://github.com/artsy/eigen/issues/2219
> Adds Danger rule for sticker extension version

- Artsy/App/ARAppDelegate+Emission.m
Ideally RN wouldn’t even generate a callstack in this case, will have to think/talk about that and maybe fix upstream, for now this logged error is less ambiguous.
> [Emission] Add a message to error that RN logs when rejecting a promise #trivial

- Artsy/App/ARAppDelegate.m
For https://github.com/artsy/collector-experience/issues/124
From the email thread by an Adjust employee:
> In case a customer wants to use the Segment module within Adjust, they must implement a Session Partner Parameter whose key is `anonymous_id`. 
So if I understood it correctly, this is the only required change on our side.
> [Adjust] Send `anonymous_id` to partner integrations (Segment). #trivial

- Podfile.lock
Just includes the fix to move the active bids module to the top of the home feed.
> [Pods] Update Emission to 1.2.2

- Artsy/App/ARAppActivityContinuationDelegate.m
- Artsy/App/ARAppStatus.h
- Artsy/App/ARAppStatus.m
- Artsy/Networking/API_Modules/ARUserManager.h
- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
- Artsy/View_Controllers/Util/ARSecureTextFieldWithPlaceholder.h
- Artsy/View_Controllers/Util/ARTextFieldWithPlaceholder.m
It seems that there are several semantic issue warnings.
In this PR, I eliminated those issues as much as possible.
I just left following warning which was introduced by https://github.com/artsy/eigen/pull/1049 since I'm not sure which is better just removing or updating to something `checkForiOS9Deprecation`.
```
eigen/Artsy/App/ARAppDelegate.m:440:10: Comparison of address of 'UIApplicationOpenURLOptionsAnnotationKey' not equal to a null pointer is always true
```
> Eliminate semantic issue

- Dangerfile
Popped the check into irb it was returning `Error Reading File: Artsy` and failing on all PRs. Spaces-in-file-paths strikes again!
> Fixes Danger sticker version check

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
Based on our release yesterday.
Also removes duplicate `releases` key.
> Bumps version numbers and seals 3.2.0 release in changelog

- Artsy/Models/API_Models/Auctions/Bidder.h
- Artsy/Models/API_Models/Auctions/Bidder.m
- Artsy/Models/API_Models/Auctions/SaleArtwork.m
- Artsy/View_Controllers/Live_Auctions/LiveAuctionStaticDataFetcher+Stubs.swift
- Artsy/Views/Auction/SaleAuctionStatus.swift
- Artsy_Tests/Model_Tests/SaleArtworkTests.m
- Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift
- CHANGELOG.yml
Force [already includes this check](https://github.com/artsy/force/blob/master/desktop/apps/auction/templates/registration_component.jade#L3) for calculating the `qualified_for_bidding` field. I still need to run through the app and remove uses of this field. /cc @sweir27
> Removes unnecessary field

- Artsy/Views/Auction/SaleViewModel.swift
- CHANGELOG.yml
Sales with no closing date could cause issues due to Swift implicitly unwrapping a nil optional.
Related to https://github.com/artsy/emission/issues/486
> Fixes crash due to IUO

- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/App/ARAppDelegate.m
- Artsy/Networking/API_Modules/ARUserManager.m
- CHANGELOG.yml
We were providing the anonymous ID after initializing the SDK.
For https://github.com/artsy/collector-experience/issues/124
Also see https://github.com/adjust/ios_sdk/pull/285
/cc @wrgoldstein
> [Adjust] Configure to include partner params with install event.

- Artsy/Models/API_Models/Auctions/SaleArtwork.m
- Artsy_Tests/Model_Tests/SaleArtworkTests.m
- CHANGELOG.yml
The definition is now based on gravity's sale data - fixes https://github.com/artsy/eigen/issues/2311
As all of the production examples from yesterday I could use are now "fixed" from a data perspective, I couldn't test this against a direct reproduction.
> [Auctions] Improve SaleArtworks state for auction closed

- Artsy/App_Resources/Artsy.Store.entitlements
- CHANGELOG.yml
We have different entitlements files for dev and store, updated the latter now as well.
> [Activity Continuation] Also support link.artsy.net in production builds.

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
A bit gutted I didn't manage to get this in for the beta!
Was chatting with @orta about internal martsy views the other day (wrt analytics), so I added a debug option to indicate them with a little red dot :).
> [Debug] Add flag to indicate martsy views

- Artsy/Networking/API_Modules/ArtsyAPI+RelatedModels.h
- Artsy/Networking/API_Modules/ArtsyAPI+RelatedModels.m
- Artsy/Networking/ARRouter.h
- Artsy/Networking/ARRouter.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
- CHANGELOG.yml
Fix #2324 
@alloy was hoping to get this in for release!
Very unglamorous code, I had originally wanted the `Artsy API popularArtists` to deal with it when it doesn't get any artists back, but I wasn't sure how to do it within that method and still return a request, so I just do it twice in the onboarding code :/. 
I've probably overlooked a better way of doing it, happy to amend!
> [Onboarding] Add fallback url with popular artists

- CHANGELOG.yml
- Podfile.lock
- Ensured rails without artworks cannot be rendered - sarah
- Fix for strange scrolling behavior in WFU - sarah
- Adds support for lot_label in auctions - ash
- Fixes a crash in opening sales with no end date - ash
- Spruced up artworks in auctio view - ash
- Add support for Universal Links to Sailthru links - alloy
- No longer shows bidding status labels for artworks in a closed sale - ash
- Allows users to place higher bids in advance in LAI - ash
- Add popular artists fallback url for onboarding - maxim
- Fixes display of artworks in non-expanding grids in artwork rails - ash
- Adds inline bid info to artist grid elements - ash
> [Emission] Update to 1.3.3

- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/Models/API_Models/Fair/Fair.h
- Artsy/Models/API_Models/Fair/Fair.m
- Artsy/Models/API_Models/Partner_Metadata/Artwork.h
- Artsy/Models/API_Models/Partner_Metadata/Artwork.m
- Artsy/Models/API_Models/Partner_Metadata/PartnerShow.h
- Artsy/Models/API_Models/Partner_Metadata/PartnerShow.m
- Artsy/View_Controllers/Artwork/ARArtworkInfoViewController.h
- Artsy/View_Controllers/Artwork/ARArtworkInfoViewController.m
- Artsy_Tests/View_Controller_Tests/Fair/ARFairSearchViewControllerTests.m
- CHANGELOG.yml
Fix #2261 , as per [schema doc](https://docs.google.com/spreadsheets/d/1P6qUe7yFPzly5JYicAa6eQ3BAy9s7Bx1_6k-Q5hB-Pw/edit#gid=0) from @anipetrov 
Ani - I've annotated in the sheet what's gone in. I'm missing gravity IDs for Artists and Genes (I need to see how to expose them from Emission). Refine view is another one. I've also noted all the martsy views, and hence those are not implemented here.
@ashfurrow thought it'd be nice to request your feedback :) let me know if you have Qs about the scope of the work!
@alloy I'm not sure if you think this should go into this release or hold off. I also need to work out a way to expose a `viewDidAppear` for refine from Emission (and preferably gravity ids also). I assume I can send something in `componentDidMount`?
> Analytics Screen IDs

- Artsy/Views/Artwork/ARAuctionBannerView.m
- CHANGELOG.yml
This removes the purple banner at the top of the artwork pages for artworks in sales that have closed. 
This is a fix for https://github.com/artsy/auctions/issues/459 .
> No longer show sale messaging banner for artwork pages for lots in closed sales.

- Artsy/View_Controllers/Util/ARNavigationController.m
Fix emission/[538](https://github.com/artsy/emission/issues/538)
cc @l2succes, #teameffort
What happens is that if there’s a notification, `ARTopMenuNavigationDatasource` ([here](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m#L134L145)) goes through all tabs and `viewDidLoad` on `ARNavigationController` gets executed, _after_ we have done our changing of the status bar (which is [here](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/Util/ARNavigationController.m#L325L335)).
Should be easy from here to change it to white background always btw, but didn't mess with that for now :).
> [Bug] Fix white text on white statusbar in home

- Artsy/App/ARAppDelegate+Analytics.m
- CHANGELOG.yml
Fix #2265 
I understood from @katarinabatina that the only remaining issue in there was the artwork double fire, so this should complete that ticket! :)
The issue was RAC related - multiple fires of the artwork being updated, so I've just changed to the ArtworkVC's viewDidAppear event, with grabbing details from its artwork view still.
> [Analytics] Fix double fire in artwork pages

- Artsy/View_Controllers/Auction/AuctionViewController.swift
- Artsy/View_Controllers/Live_Auctions/LiveAuctionSalesPerson.swift
- Artsy/Views/Auction/SaleViewModel.swift
- CHANGELOG.yml
This primarily includes a fix for https://github.com/artsy/auctions/issues/477 .
- Fixes sales with only one, two, or three lots.
- Fixes a problem preventing auction VCs from reloading their content when a sale goes live (`shouldShowLiveInterface`).
- Cleans up some indentation.
> Live Cleanup

- Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/2_-_Calls_to_Action/ARSignUpSplashViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
- Artsy/View_Controllers/Util/Sharing/ARSharingController.m
- Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
- CHANGELOG.yml
- Podfile
- Podfile.lock
~I was trawling for deprecated things to remove from Eigen and this seemed like an easy one. Next up is our use of popovers, but it won't be as easy or straightforward.~
Edit: I did popover controllers too 🙈 
- Removes UIAlertView and associated dependency
- Removes use of deprecated UIPopoverController API
> Removes remaining deprecated UIKit API uses

- Artsy/View_Controllers/ARSerifNavigationViewController.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- Artsy/View_Controllers/Auction/AuctionViewController.swift
- Artsy/View_Controllers/Auction/RefinementOptionsViewController.swift
- CHANGELOG.yml
This problem was introduced [here](https://github.com/artsy/eigen/pull/2368/files#diff-49c86a13feb606822a3e4f37eae08989L42) in #2368. I accidentally switched from status bar _hidden_ to status bar _style_. But, since this VC isn't shown full screen on an iPad, we can simply always say it prefers the status bar hidden.
Investigating the iPad status bar issues led me further down a rabbit hole until I figured out what was causing our problems with status bars having to be manually changed back in `viewDidAppear`. The problem was our top menu VC was overriding `childViewControllerForStatusBarHidden` and `childViewControllerForStatusBarStyle`, returning the _presented_ view controller in all cases. iOS is smart enough to decide (based on presentation contexts and trait collections) which VC …
> WIP: Fixes status bar problem on Refine view controller

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
- Podfile.lock
Includes only this update from 1.3.9: https://github.com/artsy/emission/pull/675 This fixes a critical bug for auctions, as noted in the changelog.
> Updates Emission to 1.3.10

- Artsy/Views/Artwork/ARArtworkRelatedArtworksView.m
- Artsy/Views/Collection_View_Cells/ARArtworkWithMetadataThumbnailCell.m
- CHANGELOG.yml
- Podfile.lock
This is a fix for https://github.com/artsy/auctions/issues/515 . This isn't the fix I wanted to submit, though; ideally we could reuse the `ARSaleArtworkItemMasonryModule` from the auction view controller. However, this module is tightly coupled to that particular view controller, and the `ARArtworkRelatedArtworksView` is tightly coupled to using only `ARArtworkMasonryModule`, which is a shame. 
The "related artworks" view is, like, begging to be replaced by existing React Native infrastructure, which would be a fun little project. So, I'm submitting this PR with the expectation of replacing the whole component soon. The upside is this fix is easy and fast, but the downside is that we _should_ display lot number, number of bids, etc, but won't be until we replace this component.
> Removes Contact for Price from auction works.

- circle.yml
We were trying to pre-launch a simulator for our tests to avoid Error 65, but recent changes to Circle's infrastructure mean this was unnecessary at best, and hurting our changes of getting the error at worst. Additionally, the UUID of the simulator we were trying to launch is out of date.
So I removed the workaround. See conversation on twitter: https://twitter.com/dantoml/status/888385665364365312
> Removes Error 65 workaround #trivial

- Gemfile
- Gemfile.lock
- Podfile.lock
No more changing the `Podfile.lock` WRT strings 🥇 - thanks @keith
Also re-orders the gems in Gemfile, removes commented out ones.
> [Dev] Adds psych to the gemfile

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
- Podfile.lock
- Fixes bad changelog merge from #2402.
- Updates bundle versions.
- Updates Emission to 1.3.11.
- Changes Podfile.lock one final time
> Prep for 3.2.4 release

- Artsy/View_Controllers/Auction/AuctionViewController.swift
- CHANGELOG.yml
This fixes the following bug:
- Open auctions view before live bidding opens.
- Tap an artwork, wait until live bidding opens.
- Tap "back" button.
App would show auctions view with timer at zero instead of the live interface.
> Presents Live interface when reappearing when sale has opened.

- Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
- Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionToolbarView.swift
- Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
- CHANGELOG.yml
Fixes https://github.com/artsy/auctions/issues/606 . What was happening was we were using the new events signal to update the # of bids UI, but the number of bids on the model wasn't being updated until _after_ the events were added (so we would typically number of bids from 1 event ago). This PR adds an observable for the number of bids specifically.
> Updates bid count UI after model has been updated

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
- CHANGELOG.yml
- Podfile.lock
This fixes [a crash](https://sentry.io/artsynet/eigen/issues/347208068) caused by a misunderstanding in how GraphQL errors are reported (they return a 200 status code, Eigen was relying on a non-200 to indicate failure). This needs to be applied to everywhere in Eigen we're calling metaphysics, and I will follow up with a PR to master that refactors that. In the mean time, this patch should be deployed as soon as possible.
> Fixes crash with new users without any favourites

- Artsy.xcodeproj/project.pbxproj
- Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
- Artsy/Networking/API_Modules/ArtsyAPI+Private.h
- Artsy/Networking/API_Modules/ArtsyAPI+Sales.m
- Artsy/Networking/ArtsyAPI.m
- Artsy_Tests/Networking_Tests/API_Modules/ArtsyAPI+GraphQLTests.m
- CHANGELOG.yml
This is a longer-term solution for https://github.com/artsy/eigen/pull/2419 which was a hot fix for 3.2.5. The problem is, new users have no favourites and Gravity errors out on Metaphysics. This was causing a crash for new users signing up. Now, the following error gets logged instead.
```
Failure fetching GraphQL query: (
{
message = "https://stagingapi.artsy.net/api/v1/collection/saved-artwork/artworks?offset=0&private=true&size=15&total_count=true&user_id=59b7fa3f8b3b813c631e7fd1 - {\"error\":\"Collection Not Found\"}";
}
)
```
> Consolidates GraphQL response error-handling

- Makefile
So I've had the following scenario happen a few times:
- Do work and `make pr` at work.
- Pull that branch at home, commit+push more work.
- Next day, try to pull that work.
Git doesn't know where to pull from because we didn't set our local branch to track the remote one when we initially pushed in `make pr`. I can't think of any downsides or inadvertent side-effects.
> Adds -u to `make pr` command #trivial

- README.md
- docs/deploy_to_app_store.md
- docs/deploy_to_beta.md
Our deploy documentation was pretty out of date – it predated Fastlane! So I've updated it, and also added a pre-release checklist as discussed in [Eigen's recent retrospective](https://github.com/artsy/post_mortems/issues/20).
This is just a first draft – if something isn't obvious, make a comment. We should be concise, but comprehensive so that any engineer at Artsy could submit by following these directions.
> Updates deploy documentation.

- Makefile
Eigen deploys were broken, see this link for more info: https://discuss.circleci.com/t/homebrew-must-be-run-under-ruby-2-3-runtimeerror/17232/8
I've tested and it works: https://circleci.com/gh/artsy/eigen/4512
> Updates Homebrew before installing dependencies

- Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionToolbarView.swift
- CHANGELOG.yml
While testing the beta to submit 3.2.6 to the App Store, I opened the Phillips sale we had on and noticed that the label for the number of bids in the LAI interface never updated, even as new bids came in.
The bug was that if we had a previous subscription to the new events signal, we would never replace it until we were removed from our superview. That's fine as long as we are removed from the superview before being set up again. But if you had your view set up twice, for whatever reason, the subscription would still be the first one pointing to the first label (which is now an orphaned view). The solution is to unsubscribe existing subscriptions and always create a new subscription.
I couldn't reproduce the build in the simulator, only on device. I suspect that something about the view …
> Fixes a problem with number of bids not updating 📱

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
This updates the changelog for a new (hypothetical, not planning on it) 3.2.7 patch release. It also adds a note about JSON null-handing in GraphQL requests that had been omitted.
> Version bump to 3.2.7

- docs/deploy_to_app_store.md
This bug has shipped twice, we should check for it before releasing.
> Adds note about checking for blank screen to deploy instructions.

- Artsy/Theming/ARTheme.m
Looks like there was a place the font changes were missed by us in #2449 , interestingly the places this code touches ( ArtworkVCs related pages, Fair Guide, and native old ArtistVC) seemed to not have snapshot tests covering them. Weird.
> Also apply the font changes to ARThemes

- docs/eigen_tips.md
Specifically, the docs around login using the `.eigen` file, as it's no longer used and not planned for un-obsolescence.
> Removes .eigen file docs #trivial

- Artsy/App/ARAppDelegate.m
- CHANGELOG.yml
Apple announced an API switcheroo with iOS 10, then forced it on iOS 11 - should fix #2460
> Moves to use the new iOS 10 open url syntax

- Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.h
- Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m
- Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuNavigationDataSourceSpec.m
- CHANGELOG.yml
Fixes: https://github.com/artsy/collector-experience/issues/794
Currently, every time the user taps on the messages tab, we create a new instance of `ARInboxComponentViewController` and present it. That causes the view loading indicator to show more than we'd like even though data has been loaded already.
In order for the view to be refreshed properly, we'll have to refresh data in emission when the tab is active using one of the react lifecycle (i.e. `componentWillMount`).
Before
After
> [Top Menu] cache messages VC after initial load

- Podfile.lock
Fixes https://github.com/artsy/collector-experience/issues/793
Full explanation is in ^ - but the lowdown is that events we were sending to Segment, would actively cause a hard deadlock in our app when going coming back from the home screen. Fixed with an update to the Segment lib, which adds protection against the type of data.
> [Dev] Fixes a crash bug when you exit the app #trivial

- Artsy/Models/API_Models/Social/User.m
Fixes https://github.com/artsy/collector-experience/issues/780
`price_range` isn't supported on the route we use for the min/max - this does now cause two API requests, but I think that's OK.
> Update the API routes used for setting the user's min/max price ranges

- Artsy/Models/API_Models/Auctions/SaleArtwork.h
- Artsy/Models/API_Models/Auctions/SaleArtwork.m
- Artsy/Models/API_Models/LiveAuctionLot.h
- Artsy/Models/API_Models/LiveAuctionLot.m
- Artsy/View_Controllers/Live_Auctions/LiveAuctionBidViewModel.swift
- Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
- Artsy_Tests/Model_Tests/SaleArtworkTests.m
- Artsy_Tests/Networking_Tests/LiveAuctionLotViewModelSpecs.swift
- Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
- CHANGELOG.yml
Okay so this PR adds support for point estimates (in lieu of estimate _ranges_). There are two important components:
- a generic lot model that adds support for the estimate field for display in the UI, and
- a live-specific lot model that needs the estimate field for capping the max bid to be placed by the user (display for estimates in live sales is already computed for us by metaphysics)
The second point is kind of interesting since we want to move away from Eigen calculating appropriate bid values altogether and only rely on Causality/Metaphysics. But in the mean time, I've replaced the unused `lowEstimateCents` with just `estimateCents`. 
~This PR is a WIP because it has no tests yet. In fact, I believe it will fail to compile on CI.~
Here's what it looks like:
Tracked in …
> Adds supports for point estimates

- Artsy/View_Controllers/Gene/GeneRefineSettings.swift
The refine settings from JSON is super safe about the data it gets, but it fails silently, now it fails more loudly.
> Adds some more logs for the Gene Refine settings

- Podfile.lock
- fastlane/Fastfile
Took a while because I needed to find a new flag for pilot
( /cc @KrauseFx have you seen this anywhere else? It kinda came out of nowhere, our last build was two weeks ago and deploys always get the latest fastlane ) (also this is Xcode 8 build, not the Xcode 9 stuff in the [auto_sign](https://github.com/artsy/eigen/tree/orta-auto_sign) branch )
@sarahscott you can ignore the dependency CI yellow - I just disabled it for this repo
> Updates to Emission b12

- Artsy/View_Controllers/Util/ARNavigationController.m
- Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
- Artsy_Tests/View_Controller_Tests/Web_Browsing/ARExternalWebBrowserViewControllerTests.m
Without making any sweeping structural changes, this fix makes sure the payment request modal (or any visible view controller that uses the scroll chief) doesn't change the back button visibility of its presenter.
Fixes https://github.com/artsy/collector-experience/issues/791
> Make sure modals cannot change back button visibility of presenters #trivial

- Artsy/App/ARAppNotificationsDelegate.m
- Artsy/Views/Notifications/ARNotificationView.m
- CHANGELOG.yml
This PR:
- Fixes crash when notification payload title is object
- Adds checks to see if our conversation view controller is presented with the same `conversationID` as the one in the notification payload. if yes, just fetch the latest data.
- Switches to the messaging tab before presenting conversation VC
> [Dev] push notification delegate fixes

- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
Not the _most_ elegant way to do this, but it ensures that the selected artist param from a deep link definitely doesn't get lost in the shuffle.
I think I want to spend some more time thinking about how to do this more elegantly (maybe with some work in Emission?) but given time constraints, this at least fixes the bug I found and works in all cases on my physical iPad.
> [home] force set homeVC with selected artist if using universal link

- Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m
- Artsy/Views/Artwork/ARArtworkView.m
On Contact Gallery page, status bar is black.
fixes https://github.com/artsy/collector-experience/issues/912
Originally tried to fix this by changing `presentViewController:` to a `pushViewController` which fixes the issue, but with this change cancel button doesn't work anymore and if we go with this approach we need to update cancel button in Emission to properly dismiss the view assuming it was pushed.
Better solution, thanks to @orta, was to embed `ARInquiryComponentViewController` in a `ARNAvigationController` and present that instead.
> Fix Black Status Bar Issue

- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
The blank bug was caused by `forceSetViewController` being called twice. This is a small fix to make sure it can't happen, but ideally in the long run we can revisit [this tab view](https://github.com/artsy/eigen/blob/master/Artsy/Views/Utilities/ARTabContentView.m#L147)'s responsibilities, because its relationship with ARTopMenuViewController and ARTopMenuNavigationDataSource is a bit confusing.
> [WFU] Do not call forceSetViewController more than once

- Gemfile.lock
It has a security vulnerability and it probably doesn't matter for our purposes but I'm tired of dismissing this warning:
> Updates Nokogiri

- Artsy/View_Controllers/Fair/ARShowViewController.m
- CHANGELOG.yml
We want to be able to show _Online Exclusive_ label for shows without `location` or `fair_location`.
https://artsyproduct.atlassian.net/browse/STI-35
Updated `ARShowViewController` to check if `location` and `show.fairLocation` are not available, show `Online Exclusive` label.
Noticed that in `PartnerShow` model we also have https://github.com/artsy/eigen/blob/master/Artsy/Models/API_Models/Partner_Metadata/PartnerShow.m#L209 and https://github.com/artsy/eigen/blob/master/Artsy/Models/API_Models/Partner_Metadata/PartnerShow.m#L175 I updated those but they are not used in this view controller so didn't commit those changes, let me know if those need to be updated too.
> [STI-35] Add support for online exclusive shows

- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
This should make sure `forceSetViewController` isn't being called so many times. I would really like some time to look at how our `ARTopMenuViewController` does routing, because this particular method is called so many times when it seems like it should only happen once, and it's not entirely clear why. For this sprint though, this fixes the blank screen issue and should go into the next release.
Fixes https://artsyproduct.atlassian.net/browse/IN-93
Related: https://artsyproduct.atlassian.net/browse/IN-40
> [dev] Fix for blank screen from push notifications on iOS 11 #trivial

- Artsy Stickers/Info.plist
- Artsy/App/ARAppDelegate.m
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
I [compared 4.0.2 to master](https://github.com/artsy/eigen/compare/4.0.2-0...master) and spotted that a bad rebase had removed some of the code for universal links. This brings that back, and prepares us for making a 4.0.3 build.
> Update the version, and add back the universal links changes

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- Artsy/View_Controllers/Util/ARBrowseViewController.m
- Artsy/View_Controllers/Util/ARRootViewController.h
- CHANGELOG.yml
- Dangerfile
We had some weird behavior in 11.3 that was making our entire screen push off the edge
Turns out that every view controller was now a root view controller. This is because 11.3 adds a new function the Apple's `UIViewController` that we check for with `respondsToSelector:@selector(isRootViewController)`.  Couldn't find docs for it though, so it might not be public. 
[It's not](https://github.com/marksands/iOSHeaders/blob/3a12eb5ea3c05a8cf9436fc1d9b8fa58552c9c8c/private/iTunesStoreUI/UIViewController-SUAdditions.h#L24) -  thanks @marksands
It's likely that the iTunes UI lib is now linked to our app in 11.3 whereas previously it wasn't
This meant that, when you would push a VC, it would fight to place it at the root instead of adding it as a subnav.
```sh
(lldb) po [viewController …
```
> Renames our check for whether a VC is a root view controller to not conflict with a new API used in 11.3

- Artsy.xcodeproj/project.pbxproj
- Artsy/Models/API_Models/Partner_Metadata/Artwork+AttributionClassStrings.h
- Artsy/Models/API_Models/Partner_Metadata/Artwork+AttributionClassStrings.m
- Artsy/Models/API_Models/Partner_Metadata/Artwork.h
- Artsy/Models/API_Models/Partner_Metadata/Artwork.m
- Artsy/Views/Artwork/ARArtworkDetailView.m
- Artsy_Tests/Model_Tests/ArtworkAttributionClassTests.m
- CHANGELOG.yml
https://artsyproduct.atlassian.net/browse/AC-61
This displays the new `attribution_class` field on Artwork, aka our concept of "classification" (unique vs. multiples vs. ephemera, etc)
If the field is present, a corresponding human-friendly short description is shown, else it is ignored.
In the example below the copy "This is a unique work" appears because this artwork's `attribution_class` == "unique"
> [AC-61] Add attribution class aka "classification" to artwork view

- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
- Podfile.lock
Updates the FB SDK, and ensures we remove the indeterminate spinner on some FB callbacks
> [FB] Updates the FB login auth flow, adds hiding the spinner for a potential edge cases

- Artsy/Constants/ARDefaults.m
We are now forcing SSL on staging to match production. 
Update default staging url to `https`.
> Update MP's staging URL to https

- Gemfile
- Gemfile.lock
Right now master is failing because the lockfile & manifest aren't the same, I want to be avoiding downloading the specs repo so we use CocoaPods-Check to decide if we do that. 
It only works with the installed Pods, but doesn't validate the manifest in the way CP will do at compile time. I sent over a PR adding that, https://github.com/square/cocoapods-check/pull/9 and migrated us.
> Use a stricter version of CP-check

- Artsy/View_Controllers/AuctionBuyNowView.swift
- CHANGELOG.yml
As per https://artsyproduct.atlassian.net/browse/PURCHASE-14
New layout (basically always 3 columns for iPad):
> [Buy] Fix iPad layout to be 3 columns

- Artsy/View_Controllers/Auction/AuctionViewController.swift
- Artsy/View_Controllers/Live_Auctions/Views/LotStandingsView.swift
- Artsy_Tests/View_Controller_Tests/Auction/Views/LotStandingsViewTests.swift
- CHANGELOG.yml
[PURCHASE-29](https://artsyproduct.atlassian.net/browse/PURCHASE-29)
For tomorrow's release. 
New shiny:
> [Buy] Show separator line only when there's lotstandings and no buy now segment

- Artsy/View_Controllers/ARVIR/AR/ARAugmentedVIRInteractionController.m
- CHANGELOG.yml
With this merged ARVIR does not update the wall positioning after an Artwork has been placed, [see slack](https://artsy.slack.com/archives/C9ZHUJXEZ/p1524062272000754) for full context.
> [ARVIR] After placing an artwork, don't update the positions of walls

- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- Artsy/View_Controllers/Util/ARNavigationController.m
- CHANGELOG.yml
Re: https://artsyproduct.atlassian.net/browse/EV-55
I decoupled the setting of the new toolbar state from when the artwork is still the top view controller for the navigation stack. This means that the changes in the layout don't affect the ArtworkVC and it becomes immune to the bug.
> EV-55 - Fixes the Artwork not being able to scroll correctly when moving into VIR

- Artsy.xcodeproj/project.pbxproj
- Artsy/Networking/API_Modules/ArtsyAPI+Artworks.h
- Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
- Artsy/Networking/ARRouter+GraphQL.h
- Artsy/Networking/ARRouter+GraphQL.m
- Artsy/Networking/ARRouter.h
- Artsy/Networking/ARRouter.m
- Artsy/Networking/record_artwork_view_mutation.graphql
- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
- CHANGELOG.yml
- Podfile.lock
Related to: https://artsyproduct.atlassian.net/browse/DISCOVER-23
> Upon viewing an artwork, sends recordArtworkView graphql mutation

- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
A friend reported that the app crashed while attaching a photo to their consignment submission. I found [the corresponding crash report](https://sentry.io/artsynet/eigen/issues/452245164/events/18647931286/) and took a very quick look, and it appears that as of iOS 11, the `NSPhotoLibraryAddUsageDescription` key is required to be included in an app's `Info.plist`, or else the following SIGABRT is raised:
```
abort | NSPhotoLibraryAddUsageDescription | This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.
```
This PR adds the key, which should fix the crashes.
> Fixes crash attaching photos to a consignment submission.

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
Fix [PURCHASE-103](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=41&projectKey=PURCHASE&modal=detail&selectedIssue=PURCHASE-103)
This is far from an elegant solution. Another option is amending the Emission View Controllers to have the `isRootNavViewController` property (which is currently considered `false`, which caused the bug).  That would mean an Emission release though, and I opted in favour for this, for the time being.
> Fix Emission VCs not being considered Root 

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
- Podfile.lock
So, this will be corresponding with [Emission 1052](https://github.com/artsy/emission/pull/1052).
The switchboard registration and `rootNavigationControllerHomeWithTab` are legit, I think.
The code written in `presentRootViewController` is just... I don't know, I did what _I_ thought made sense, but I'm not 100% convinced. 
Basically, there are a few things that are odd:
1) There is no final `else`. There are cases in which nothing is presented, because nothing is being force set, as some of the variables/flags don't apply. Why is this a present VC method then? -> So I added a final clause
2) Favourites was missing, and would end up as a Home VC
3) (from my understanding) it essentially overwrites the passed through View Controller in the case of home, because it gets the rootNavigationVC …
> [Auctions] Add support for showing auctions home tab on /auctions push notification

- fastlane/Fastfile
Moves to https://docs.fastlane.tools/actions/latest_testflight_build_number/ instead of doing it manually
#trivial
> Use the fastlane action for getting the build number from testflight

- docs/deploy_to_app_store.md
This does a few things:
- Moves testing changes specified in the changelog to the top since it seems like it's the most important and also most likely to spoil a beta.
- Adds detail on how to test certain things, for example where to open a mocktion on staging.
- Removes the inquiry flow test, which is covered by the new conversation push notification test, and replaces it with a smoke test of a populated conversation view.
- Adds steps for our new auctions push notification testing.
> Updates pre-deploy docs

- Artsy/App/ARSwitchboard+Eigen.m
- CHANGELOG.yml
This was actually already done! Eigen handles the `/admin` route already so this PR just removes the check when instantiating that view controller. I looked around and I don't see anywhere else that calls that function, so we're good.
**One note**: In Safari I had to use triple-slash to get the route recognized by JRRoutes (I think because the URL is missing a host name). So the URL to visit in Safari is `artsy:///admin`.
> Exposes admin menu to non-admin users via URL

- Artsy/View_Controllers/ARVIR/AR/ARVIRHorizontalPlaneInteractionController.m
Re-aligns the artwork to use a different screen point of reference in comparison to the floor. This fixes a weird UX issue. EV-209
> [ARVIR] Use a higher point in the screen for projecting the artwork vs the wall

- Artsy/Networking/API_Modules/ARKeychainable.m
- CHANGELOG.yml
When someone jumps between prod and beta builds, they can end up with an access token for the wrong environment. This makes that infeasible.
> Adds a custom prefix to keychain keys when in staging

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARAppDelegate+Emission.m
- Artsy_Tests/Supporting_Files/ARTestHelper.m
- Podfile
- Podfile.lock
⚠️ Do not merge! ⚠️ 
We're trying to get an Eigen release out the door, would rather not complicate things with an Emission update. Also I can't find where to add the `pod keys set` command for our deploys.
> Updates Emission to 1.5.5

- Artsy/App/ARAppDelegate.m
- CHANGELOG.yml
This allows you to sign up and then be able to get to the admin panel without restarting the app.
> [Admin] You can access the admin tools after finishing onboarding

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/View_Controllers/Artwork/ARZoomArtworkImageViewController.m
- Artsy/Views/Utilities/Image/ARZoomView.h
- Artsy/Views/Utilities/Image/ARZoomView.m
- CHANGELOG.yml
Previously the image would be cropped and you can't zoom in on an iPhone X after tapping for the full zoomed image, now you can zoom in to a full screen. 
As a bonus, I added a lab option for something @bhoggard wanted a few years ago (hah) which was letting the back button fade after some inactivity (3 seconds) - congrats on moving to android Barry :P
> Fixes the iPhone X support for a zoomed iamge

- Podfile
- Podfile.lock
The previous deploy of Eigen missed an updated tipsy-stripe pod which had been temporarily pinned to my fork. It is now fixed.
> update tipsi-stripe pod

- Artsy/View_Controllers/ARSerifNavigationViewController.m
This PR makes the hit area for the modal exit button 10 bigger.
> increase modal close hit area

- Artsy/View_Controllers/ARSerifNavigationViewController.m
Tracked in [purchase-220](https://artsyproduct.atlassian.net/browse/PURCHASE-220)
cc @sweir27 @yuki24 @zephraph 
This PR is an attempt to address the issue mentioned above- a tiny white box in the upper left corner of the screen which becomes visible when you scroll the Billing Address form (here covering the 'F' in 'Full Name':
This seems to address the issue but I'm not sure if it is the best way or what other implications might come along- I just shoehorned in a single check for presence of `nav.title` and `nav.length`.
View debugger shows it is an ARSerifLabel:
Updated debugger view hierarchy:
> Fix tiny white box on bidding form

- Artsy/App/ARAppNotificationsDelegate.m
- Artsy/Views/Utilities/Image/ARZoomView.h
- Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m
- CHANGELOG.yml
Because you're on the screen, and it's going to tell you that stuff anyway
> Suppresses push notifications for things like being outbidded when you're on the ARBidFlow components UIVC

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/ARSwitchBoard+Eigen.h
- Artsy/App/ARSwitchboard+Eigen.m
- Artsy/Views/Artwork/ARArtworkActionsView.h
- Artsy/Views/Artwork/ARArtworkActionsView.m
- Artsy/Views/Artwork/ARArtworkMetadataView.h
- Artsy/Views/Artwork/ARArtworkMetadataView.m
- Artsy/Views/Artwork/ARArtworkView.m
- Artsy_Tests/Supporting_Files/ARTestHelper.m
- Podfile.lock
Tracked in https://artsyproduct.atlassian.net/browse/PURCHASE-248
@ashfurrow helped me with the first two commits of this. It seems to be working now (see below- the banner should update after bidding and going from outbid to winning) but there is an error I've seen before [see below].
[resolved]
```
2018-07-17 14:36:32.614393+0200 Artsy[83465:8377853] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
Stack:(
0   Foundation                          0x000000010e626df7 _AssertAutolayoutOnAllowedThreadsOnly + 77
1   Foundation                          0x000000010e432540 -[NSISEngine withBehaviors:performModifications:] + 28
2   Foundation …
```
> Update banner after bid

- Artsy/Views/Artwork/ARArtworkActionsView.h
- Artsy/Views/Artwork/ARArtworkActionsView.m
- Artsy/Views/Artwork/ARArtworkMetadataView.h
- Artsy/Views/Artwork/ARArtworkMetadataView.m
- Artsy/Views/Artwork/ARArtworkView.m
- CHANGELOG.yml
This is for [Purchase-290](
https://artsyproduct.atlassian.net/browse/PURCHASE-290) but it needs more testing before merging. 
Here's the cause of the bug:
- `ARArtworkView` fetches API results when new bids are placed.
- We were relying on `ARArtworkView` to notify subviews when there is new bid status (from API fetch).
- We expected the model in the nested `ARArtworkActionsView` to be updated in-place based on the fetch **but** they weren't.
The solution is to pass down the new sale artwork model as a parameter to the `updateUI` function.
> Fixes bid status not updating

- Artsy/Views/Artwork/ARArtworkActionsView.m
- CHANGELOG.yml
This PR shows a spinner while the necessary API requests to display the artwork actions view (bid button, contact gallery button, countdown timer, etc) are fetched. 
The bug was incorrectly identified as a regression. We saw the beta behave as described in the ticket, and saw the App Store version working fine a few minutes later. During that time, I believe a staging blip corrected itself. I could no longer produce the lag on the beta _but_ sometimes API requests take time, so we should still show the spinner while they're in flight.
Fixes [Purchase-292](https://artsyproduct.atlassian.net/browse/PURCHASE-292).
> Shows spinner during API request load.

- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- CHANGELOG.yml
When testing things across multiple accounts, it's often helpful to know which account I'm logged in with from within the app. This PR adds the email to the build info at the top:
> Logged-in user email is displayed in admin menu #trivial

- Artsy/App/ARAppNotificationsDelegate.m
- Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m
- CHANGELOG.yml
I've got a more detailed description of the bug [here](
https://github.com/artsy/eigen/pull/2666/files#r204059063) but the gist is, since BidFlow is presented modally, we can't rely on a simple class check of the global top view controller. 
Testing push notifications is really tricky since our staging environment uses Apple's production servers and they'll only push to properly deployed builds of the app, so I've updated the tests and read the code until I'm confident it'll probably work. More eyes on this would be helpful to double-check. I'll definitely test on the next beta.
> Fixes outbid notification suppression.

- Artsy/App/ARAppNotificationsDelegate.m
- Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m
- CHANGELOG.yml
This PR updates the keys that Eigen uses to extract data from the outbid push notifications sent from Pulse. A PR on the pulse side has been submitted: https://github.com/artsy/pulse/pull/218
Together, they fix [PURCHASE-300](
https://artsyproduct.atlassian.net/browse/PURCHASE-300).
> Updates outbid notification payload parsing

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
We released version 4.2.1 to the store today, so this PR prepares the Info.plist files and changelog for the new 4.2.2 version. I've also created 4.2.2 in iTunesConnect, so we're prepared to release a beta when we go to do that next.
> Updates version and changelog

- Artsy/App/ARSwitchBoard+Eigen.h
- Artsy/App/ARSwitchBoard.m
- Artsy/App/ARSwitchboard+Eigen.m
- Artsy/View_Controllers/Live_Auctions/LiveAuctionLotSetViewController.swift
- Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
- CHANGELOG.yml
Took a look with @erikdstock on this – just an oversight from the BidFlow project. It fixes this crash: https://sentry.io/artsynet/eigen/issues/626942969/?query=is:unresolved# And addresses [PURCHASE-411](https://artsyproduct.atlassian.net/browse/PURCHASE-411#).
> Fixes bug where LAI registration would invoke BidFlow

- Artsy/Networking/create_order.graphql
Update `createOrder` mutation to match latest error type introduced in https://github.com/artsy/metaphysics/pull/1276
> [Coordinate Merge] Switch to latest error type

- Artsy/Networking/create_order.graphql
We want to have all stitched in mutations [prefixed with the domains](https://github.com/artsy/README/blob/master/best-practices/graphql-schema-design.md#schema-stitching) to handle the issue of what "if we need order in two contexts" in the future.
This got added with https://github.com/artsy/metaphysics/pull/1281 (check the `_schema.graphql`) but isn't yet shipped to prod.
> Updates the mutation name to use the prefix

- Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerBuyButtonTests.m
- CHANGELOG.yml
Fixes [PURCHASE-463](https://artsyproduct.atlassian.net/browse/PURCHASE-463), which was caused by sending an artwork slug instead of its proper ID. Something something string data types 😉
> Fixes a problem with order creation input #trivial

- Artsy Stickers/Info.plist
- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/App/ArtsyEcho.h
- Artsy/App/ArtsyEcho.m
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- Artsy/Views/Table_View_Cells/Feed_Items/Modern/ARModernPartnerShowTableViewCell.m
- Artsy_Tests/Supporting_Files/ARTestHelper.m
- CHANGELOG.yml
- Podfile
- Podfile.lock
Updates us the latest build of Emission.
The latest build of Emission includes a change to the `AREmission` host API  https://github.com/artsy/emission/pull/1184 to include an options dictionary. This PR takes all the options that we use (from Echo and from the Admin) and passes them into Emission so that people can make feature flags etc in React Native code.
> Updates to the latest emission

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/AROptions.h
- CHANGELOG.yml
This means when we turn on Buy Now via Echo the changes in Emission should also receive those settings, we chatted about we chatted about this [in slack](https://artsy.slack.com/archives/C02BAQ5K7/p1538602434000100)
> Consolidates the options for buy now into one flag from echo

- Artsy/Views/Utilities/Image/ARZoomView.m
- CHANGELOG.yml
I think iOS 12's safe area insets screw around with zoom settings in our zoom view. This makes the zooming unpredictable in that it could accidentally pop you out the moment you move anything. I've removed the pop.
> Remove the pop on zoom out feature of the ARZoomView

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/View_Controllers/Artwork/ARZoomArtworkImageViewController.m
- Artsy/Views/Utilities/Image/ARZoomView.m
- CHANGELOG.yml
Also includes #2703 
I've had this as a lab option for a while, had a chat with Stephen a few weeks back and he reminded me today that we agreed to make this default.
> Turns on "hide the backbutton after a delay" as default

- Artsy/App/ARAppDelegate.m
- CHANGELOG.yml
- Podfile.lock
OK, so I went through getting started docs and I'm alright with saying this is just how they send URLs to us occasionally. I verified that it doesn't break FB auth in the app.
> Handle links that come through the FB app in an unusual format

- Artsy/App/ARAppActivityContinuationDelegate.m
- Artsy/App_Resources/Artsy.entitlements
- Podfile.lock
This is the new recommendation from Adjust, so it seems like a good time to give it a shot. I've verified that links like https://kqwq.adj.st/?adjust_t=esa8xn would correctly open Eigen and seen in the logs that Adjust has reported the link.
> Migrates Adjust to use universal links instead of deep links

- Artsy/App/ARAppDelegate.m
- Artsy/Networking/API_Modules/ARUserManager.h
- Artsy/Networking/API_Modules/ARUserManager.m
- CHANGELOG.yml
Now that we store the email/password we can try save the creds at a later stage than just onboarding. This adds it on the third run.
> Re-enables the safari web keychain, and only shows it on the 3rd launch

- Artsy/Models/API_Models/Partner_Metadata/Artwork.m
- Artsy/Networking/artwork.graphql
- Artsy_Tests/Model_Tests/ArtworkAttributionClassTests.m
- Artsy_Tests/Model_Tests/ArtworkTests.m
- CHANGELOG.yml
This PR is to remedy [an ongoing incident](https://trello.com/c/UTDSwXwm/181-ios-app-not-showing-lots-in-auction-views).
[Recent changes](https://github.com/artsy/eigen/pull/2688) to the artwork modelling were deployed today, causing a long series of events that led users to see the auction view with few or zero lots. Only artworks with no attribution class were visible.
tl;dr
- We changed the JSON Mantle mapping for `attributionClass` to be `attributionClass.name`, since it's nested in Metaphysics.
- However, Gravity models don't return that nesting. When Mantle calls `valueForKeyPath` with `attribution_class.name` on Gravity models, it has an `NSString` for the `attribution_class` key path, but string is not key value coding compliant for the `name` key, so …
> Fixes problem with attribution classes from Gravity

- Artsy/Models/API_Models/Partner_Metadata/Artwork+AttributionClassStrings.m
- Artsy_Tests/Model_Tests/ArtworkAttributionClassTests.m
- CHANGELOG.yml
This fixes a bug mentioned here:
https://github.com/artsy/eigen/pull/2716#issuecomment-431046347 It prevents the artwork view from displaying the attribution class information for many (all?) artworks, whose `attribution_class` has a capital letter at the beginning.
> Makes attribution classes case-insensitive

- docs/deploy_to_app_store.md
This updates the deploy docs in a few important ways:
- Splits our pre-deploy QA into one of three groups:
- Tests that need to be run on staging.
- Tests that need to be run on production.
- Tests that currently don't work (with Jira links).
- I added a test that would have caught [Eigen's incident last week](https://trello.com/c/UTDSwXwm/181-ios-app-not-showing-lots-in-auction-views)
- I added notes for a recent problem with view-in-room as well.
- Adds note about our use of IDFA.
I also updated the Markdown headers so the page has an `H1`.
> Updates deploy docs

- Artsy/Networking/artwork.graphql
- CHANGELOG.yml
Adds width, height, and metric to Artwork GraphQL query. This PR is a WIP because it requires https://github.com/artsy/metaphysics/pull/1350 to be merged and deployed before it can work.
Fixes [DISCO-438](https://artsyproduct.atlassian.net/browse/DISCO-438).
> Fixes view-in-room #trivial

- Artsy/View_Controllers/ARSerifNavigationViewController.m
- CHANGELOG.yml
I couldn't find this ticketed in Jira, but it's been bugging me lately. In certain contexts (details below), presenting a modal view controller and then dismissing it leaves an ugly grey bar underneath the home screen indicator on iPhone X-style devices:
This bar persists until the app is restarted.
I took a look into this and found that the app's root view controller (`ARTopMenuViewController`) had a view with a background colour set to grey. Using [KVO](https://nshipster.com/key-value-observing/), I found where this was getting set:
https://github.com/artsy/eigen/blob/c956fee683f14c87c8bd7082d8455d3261b00064/Artsy/View_Controllers/ARSerifNavigationViewController.m#L245-L252
This is a fix we made for LAI so our split view looked correct on iPad. This had the unintended consequence of …
> Fixes grey bar left along iPhone X after dismissing modals

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/View_Controllers/Auction/AuctionNetworkModel.swift
- Artsy_Tests/View_Controller_Tests/Auction/AuctionNetworkModelTests.swift
- CHANGELOG.yml
I ran into an issue where a sale was 404'ing and crashing the app. Looks like a `FIXME` made it through review, so I cleaned it up. Also added a test.
This is the first PR since 4.3.2 got released, so I updated our changelog and version numbers too.
> Version bump and type fix

- Artsy/Models/API_Models/LiveAuctionLot.h
- Artsy/Models/API_Models/LiveAuctionLot.m
- Artsy/Networking/static_sale_data.graphql
- CHANGELOG.yml
As it's not used, and caused a problem. Position is used in MP/ Grab to order, and we don't do custom ordering inline in the app.
> Removes the position field from a LiveAuctionLot 

- docs/deploy_to_app_store.md
I've put these instructions [into Notion](https://www.notion.so/artsy/Pre-submission-QA-Checklist-785e3233fdcf423f95ee239ab3c22ec3), where our non-engineering colleagues can help improve it.
> Moves pre-flight checklist into Notion #trivial

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
Now that we've released 4.3.3.
I have also removed some extraneous spacing (so that now, _versions_ are divided by newlines but sections of the notes, like `dev` and `user_facing` aren't separated). I also added a `signed_of_by` field to the release to note who did the final QA and release to the App Store.
> Bumps everything to 4.3.4 #trivial

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARSwitchBoard.m
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
- CHANGELOG.yml
As part of [LD-28](https://artsyproduct.atlassian.net/browse/LD-28), we're adding a "Find Exhibitors and Artists" link button to the new Fair view that links to a fair-scoped search. This mirrors functionality that exists in Eigen today as part of `ARFairSearchViewController`. This PR aims to expose this screen via SwitchBoard.
> Add switchboard routing for ARFairSearchViewController

- Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
- Artsy/View_Controllers/ARVIR/Views/ARInformationView.h
- Artsy/View_Controllers/ARVIR/Views/ARInformationView.m
Fixes DISCO-552
Adds support for toggling the UI, to make it easier to take screenshots when using the AR mode.
> Adds the ability to hide the completed AR UI by tapping on the screen

- Artsy Stickers/Info.plist
- Artsy.xcodeproj/project.pbxproj
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/Models/API_Models/Application/SearchResult.h
- Artsy/Models/API_Models/Application/SearchResultable.h
- Artsy/Models/API_Models/Application/SearchSuggestion.h
- Artsy/Models/API_Models/Application/SearchSuggestion.m
- Artsy/Networking/API_Modules/ArtsyAPI+Search.m
- Artsy/Networking/ARNetworkConstants.m
- Artsy/Networking/ARRouter.m
- Artsy/View_Controllers/App_Navigation/ARAppSearchViewController.m
- Artsy/View_Controllers/Fair/ARFairSearchViewController.h
- Artsy/View_Controllers/Fair/ARFairSearchViewController.m
- Artsy/View_Controllers/Fair/ARFairViewController.m
- Artsy/View_Controllers/Search/ARSearchResultsDataSource.h
- Artsy/View_Controllers/Search/ARSearchResultsDataSource.m
- Artsy/View_Controllers/Search/ARSearchViewController.h
- Artsy/View_Controllers/Search/ARSearchViewController.m
- Artsy_Tests/View_Controller_Tests/App_Menu/ARAppSearchViewControllerSpec.m
- Artsy_Tests/View_Controller_Tests/App_Menu/ARSearchViewControllerSpec.m
- Artsy_Tests/View_Controller_Tests/Fair/ARFairSearchViewControllerTests.m
- CHANGELOG.yml
Fixes DISCO-550
Moves us to the new suggest API, and conservatively adds support for all the new suggestion types. Note that this code is not aiming for pure elegance, it was built to make it easy to remove the `SearchResult` class etc when Local Discovery is shipped and the SearchVC only has to handle one type of data (suggestions)
☎️
> Uses the 'new' search suggestion API for the main app search

- .circleci/config.yml
- CHANGELOG.yml
- Makefile
This PR skips running tests (and building for the purposes of running tests) on CI if the branch is `beta`. We ignore any test failures on this branch anyway, so the tests are just taking up time.
@javamonn I meant do pair on this but it kind of folded naturally into some release automation work I'm doing. I've assigned you to the PR, let me know if you'd like to pair on the review.
> Skips test builds and run on beta deploys #trivial

- Artsy/Views/Collection_View_Cells/ARArtworkWithMetadataThumbnailCell.m
- Artsy/Views/Utilities/ARArtworkThumbnailMetadataView.h
- Artsy/Views/Utilities/ARArtworkThumbnailMetadataView.m
- CHANGELOG.yml
Updates artwork grid item styling, companion PR to: https://github.com/artsy/emission/pull/1253, implements [LD-104](https://artsyproduct.atlassian.net/browse/LD-104).
Before:
After:
> Update artwork tile metadata styling

- Artsy/Views/Utilities/ARArtworkThumbnailMetadataView.h
- Artsy/Views/Utilities/ARArtworkThumbnailMetadataView.m
Fixes a compilation error causing a failing build introduced in: #2752 
Instead of adding a special-cased uncapitalized sans-serif font to `Artsy+UILabels`, we use `UILabel` directly to the same result.
> Fix build by using UILabel directly

- fastlane/Fastfile
'External' is in square quotes because these are all Artsy staff (but not strictly developers). After being merged, new betas of Eigen should go out to both our engineers and our Artsy colleagues (based on the new `pilot` parameters).
---
This PR replicates the following emission-nebula commits:
https://github.com/artsy/emission-nebula/commit/360d0bdf14e238f05483b0c977e08707b91c4266
https://github.com/artsy/emission-nebula/commit/8cd5e64444f5121b0ee36036a2348d2a6f5d150e
I [already made](https://github.com/artsy/eigen/commit/d304ce5b61180981baf985380e3c12d62d8d0cfe) another necessary change in https://github.com/artsy/emission-nebula/commit/3d281dd01ea40429c371f20ffdf4d9dc0f72ccad to `master` to unblock an earlier beta deploy (see [this tweet for …
> Distributes eigen betas to 'external' testers

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/ARSwitchboard+Eigen.m
- Artsy/View_Controllers/Fair/ARProfileViewController.m
- CHANGELOG.yml
The PR fixes [LD-199](https://artsyproduct.atlassian.net/browse/LD-199) by wrapping all not-already-wrapping view controllers in navigation controllers (providing them with a close button, so the user doesn't become trapped in a modal). I still need to test that this works with the following invocations routed from Emission (see the comment in `ARAppDelegate+Emission.m`):
This PR also fixes a problem where Eigen would route `/conditions-of-sale` to the new fair component (if enabled, so this bug only presents for our beta testers) with a `fairID` set to `conditions-of-sale`. I described the problem in more detail [in Slack](https://artsy.slack.com/archives/C02BAQ5K7/p1550266403153100).
> Fixes some fair routing issues

- Artsy.xcodeproj/project.pbxproj
I've been seeing [this error](https://twitter.com/ashfurrow/status/1068618230426730502) for months, and @kierangillen began seeing it on his machine, too:
The solution appears to be the following check box in the main target's build phases:
I found the solution in one of the many answer is [this StackOverflow post](https://stackoverflow.com/questions/27167020/ios-simulator-could-not-hardlink-copy-wrong-path-in-my-filesystem).
> Fixes hard link simulator installation failure #trivial

- Artsy/View_Controllers/Util/ARNavigationController.m
- Artsy_Tests/View_Controller_Tests/Util/ARNavigationControllerTests.m
- CHANGELOG.yml
Opening search while looking at a fair/show view was crashing because we were sending the `pushViewController:animated:` message to the `NavigatorIOS` that the fair/show components are using. This was due to our use of `self.ar_innermostTopViewController.navigationController`, which looks from the git history like a copy/paste thing and not a conscious decision. I've look for other uses of `ar_innermostTopViewController` that might cause trouble, but I think we're good 👍 
In the long run, we really need to get those components doing their routing through Eigen's switchboard instead of having their own navigation controller. I wouldn't be surprised if there are more edge case bugs like this one that we might run into.
Fixes [LD-242](https://artsyproduct.atlassian.net/browse/LD-242).
> Fixes crash with opening search on Fair/Show components

- Artsy/App/ARAppDelegate+Emission.m
- CHANGELOG.yml
This PR fixes a problem where the back button wasn't hiding in some Emission component controllers. Mostly this fix is in this commit: 
https://github.com/artsy/eigen/commit/5e4b265ee480abd7b9d36f9368e61e329112c13f However, this wasn't sufficient.
Our code relies on `viewDidLayoutSubviews`, which _should_ get called when the component controller lays out its subviews. Unfortunately, it's not working for some of our component controllers; it gets called while the view hierarchy is still just the spinner, and isn't called again after the full UI is laid out. This was unexpected. A quick look at the different components doesn't point to any obvious differences why the fair component works but the fair artists component doesn't.
We [already have a …
> Back button hiding bug fix

- Artsy/App/ArtsyEcho+LocalDisco.m
- Artsy/App/ArtsyEcho.m
2 things: 
1. because we were using new echo instances instead of sharing a singleton, it wasn't running the setup function. This means echo would always have failed (because it wouldn't have data) - so glad we were gonna test
2. this adds a message which is a CSV of user ID which we can allow into City Guides
#trivial - there's already a changelog for this
> Update the Echo settings to allow us passing in new people

- fastlane/Fastfile
Mentioned in Slack: https://artsy.slack.com/archives/C02BAQ5K7/p1552918520142600
We saw the `4.4.1-2019.3.15.11` build get pushed as `4.4.1-2019.3.15.5` in [this build](https://circleci.com/gh/artsy/eigen/6007). I took a look and we were pushing the tag based on [`latest_testflight_build_number`](https://docs.fastlane.tools/actions/latest_testflight_build_number/#latest_testflight_build_number), which is incorrect; it grabs the build number from the latest _already-uploaded_ TestFlight build.
We set the build number in the `Makefile`, so it's already set by the time that Fastlane gets run. So I've modified the `Fastfile` to read the value out of the Info.plist file for the git tag.
> Fixes deploy script incorrect tags #trivial

- Artsy/App/ARSwitchBoard.m
- Artsy_Tests/App_Tests/ARSwitchBoardTests.m
- CHANGELOG.yml
This is kind of a follow-up to https://github.com/artsy/Aerodramus/pull/9. I saw some logs that made me suspect that Echo might be getting updated a lot. In fact, if the JSON parsing for the updated Echo config fails (or you comment out that line), you'll see an infinite loop:
That screenshot shows an echo `update:` call invoking its callback, which calls `updateRoutes` on the switchboard, which checks for updates again, and which (if the parsing fails) will repeat forever. 
(The problem where `updateRoutes` is called on a background thread should be fixed by https://github.com/artsy/Aerodramus/pull/9 )
This PR introduces a guard against these repeated calls. I'm still verifying for sure this is the cause of the crash [here](https://sentry.io/organizations/artsynet/issues/942429014/?projec …
> Only updates echo once per switchboard call.

- Artsy/App/ArtsyEcho+LocalDisco.m
This will allow us to separate out the v1 and v1.1 users (ie: to only allow v1.1 to access LD). We don't _need_ to, but we might _want_ to, so why not ¯\_(ツ)_/¯
> Increments ARLocalDiscoCurrentVersionCompatibility #trivial

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
- CHANGELOG.yml
When iOS inserts an autocomplete email address, it adds a space at the end. Which isn't good, and other engineers have filed radars, but alas it breaks our current signup/signin flow (the "next" button gets disabled):
The solution is to trim whitespace characters. It's not clear how data flows through the UI flow, so I made the change in the top-level text field notification-handler.
> Fixes email autocomplete during login/signup

- fastlane/Deliverfile
- fastlane/Fastfile
This commit had a typo that renamed `username` to `apple_id` (`Deliverfile` uses one and `Appfile` uses another):
https://github.com/artsy/eigen/commit/d865463a49b7d3306a777865ab1294d780581c10#diff-915e65323d2a5bb17e964d92abce9497
#2820 tried to fix this but I was getting the same error as it got. I'll keep this as a draft until I verify it works.
> Fixes store promotion

- Artsy/Networking/API_Modules/ARUserManager.m
- Artsy/Networking/ArtsyAPI.m
- Artsy_Tests/Networking_Tests/API_Modules/ArtsyAPI+PrivateTests.m
- CHANGELOG.yml
This is a follow-up to https://github.com/artsy/emission/pull/1583 and related to [DISCO-978](https://artsyproduct.atlassian.net/browse/DISCO-978). This PR changes Eigen to clear the Relay cache whenever we make a write to our API; this mirrors the existing behaviour of clearing the (same) cache on Emission whenever we make a GraphQL mutation.
> Clears Relay cache when a PUT, POST, or DELETE is made to our API.

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
Closes https://artsyproduct.atlassian.net/browse/PURCHASE-1069 &
https://artsyproduct.atlassian.net/browse/PURCHASE-1070
Again, not adding a CHANGELOG entry right now. We should do so retroactively once 5.0.3 is released.
#trivial
> [Artwork] Put new RN view behind a lab option.

- README.md
We could consider adding a Peril check for point-people being in the Artsy GitHub org. Maybe you'd be interested, @mdole?
> Updates point people

- Podfile
- Podfile.lock
Follow-up from eb2761a3584d16b4b68350c31c2a43b2540d11a3 and https://github.com/artsy/emission/pull/1586.
This PR will unify Emission+Eigen to point to my fork of `react-native-navigator-ios`. The only functional difference between my fork and upstream is some types that Orta added [in this PR](https://github.com/michaelknoch/react-native-navigator-ios/pull/2).
> Points react-native-navigator-ios in Podspec to Ash's fork #trivial

- Artsy/Models/API_Models/Application/SearchSuggestion.m
- CHANGELOG.yml
Introduced [here](https://github.com/artsy/eigen/commit/fe99debe3d7ce9004fd3fc92fae61295c561addb#diff-0a09df735f7924aad646b7b805d6a29aR44). No tests on that code 😞 
The view itself... looks not great. But that's on the Force side, which is much easier to update.
I've already kicked off a beta for this commit, so CI will take a long time on this PR.
> [DISCO-1045] Fixes search result selection for features

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
- Podfile.lock
This PR updates version numbers and changelog for the new 5.0.4 release (which I've already created in AppStoreConnect).
> Updates version/etc after 5.0.3 release #trivial

- Artsy/Models/API_Models/Application/SearchSuggestion.m
This is a follow-up from #2830. The `else if` statement will never be reached because an earlier `if` catches it (with the `prefixless` array, which is likely why the static analyzer didn't catch this).
> Removes unused if statement #trivial

- CHANGELOG.yml
- Podfile
- Podfile.lock
This PR moves `tipsi-stripe` to my fork, which includes [this commit](https://github.com/ashfurrow/tipsi-stripe/commit/bfebb733fb44d3e1d0522a38a317993f9c686422) (copied from [this PR](https://github.com/tipsi/tipsi-stripe/pull/418) that was closed without resolution) which fixes [this bug](https://github.com/tipsi/tipsi-stripe/issues/408). The bug _appears_ related to our recent React Native upgrade (I ruled out the `tipsi-stripe` [upgrade from 7.4.0 -> 7.5.0](https://github.com/tipsi/tipsi-stripe/compare/7.4.0...7.5.0)).
The fix was to remove a callback for when the keyboard appears; the callback that was being executed was this:
```objc
- (void)keyboardWillShow:(NSNotification *)n {
if (!_jsRequestingFirstResponder && !_isFirstResponder) {
[_paymentCardTextField resignFirstResponder];
} …
```
> Fixes issue with tipsi-stripe

- Podfile.lock
Includes the change in this PR: https://github.com/artsy/Artsy-OSSUIFonts/pull/18 This catches a common problem that Artsy staff run into when setting up this repo – that PR discusses it in more detail, but let me know if I can clarify anything!
> Updates Artsy fonts pod #trivial

- Podfile
- Podfile.lock
Updates Emission to the latest version.
Also updates `RNSVG` per https://github.com/artsy/emission/pull/1634
> Updates Emission to version 1.12.0

- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/View_Controllers/Artwork/ARArtworkSetViewController.m
- CHANGELOG.yml
We saw that the analytics for swiping between view controllers weren't firing for artwork set view controllers _opened from an auction_. The others would work no problem, just not the ones presented from the Auction view controller. Super-weird. 
I dug through the ARAnalytics code, and then the ReactiveCocoa code its built on top of, but couldn't find any reason for `rac_signalForSelect:` not to fire for certain instances. I'm a bit worried we might be missing analytics events in other places, though with more and more of our codebase moving to React Native, it might be worth ripping out ARAnalytics+DSL altogether soon. This would also let us remove ReactiveCocoa and get a smaller app size.
> Moved artwork set analytics into artwork set view controller

- Artsy/View_Controllers/Util/ARNavigationController.m
- CHANGELOG.yml
<details><summary>Screenshot of misaligned back button</summary>
</details>
This would happen when the City Guides controller was in-memory (even if it wasn't in the view hierarchy). It was still getting the `viewWillAppear:` callback and setting state on the ARTopMenuViewController singleton. The fix was to only invoke the callback to update the state if the view has a window (ie: if it is in the on-screen view hierarchy).
/cc @dleve123 @yuki24
> Fixes a problem where the app's back button would become misaligned

- Artsy/App/ARAppDelegate+Emission.m
Per https://artsyproduct.atlassian.net/browse/PURCHASE-1182
For now, we want eigen to continue consuming metaphysics v1 while emission uses metaphysics v2. That will allow us to ship working betas with the current version of emission, and we can follow up with the eigen migration at a different pace.
> PURCHASE-1182: Append /v2 to the metaphysics config sent to emission from eigen

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
After 5.0.5 was released, we need to do two things:
- Add a new version (5.0.6 in this case) to Apple's AppStoreConnect dashboard, and
- Edit our changelog and Xcode projects to match that new version.
More details are [in the docs](https://github.com/artsy/eigen/blob/master/docs/deploy_to_app_store.md#prepare-for-the-next-release).
We will also need to pull the changes from the `5.0.5-develop` branch into `master`, which I'll take care of later today.
> Updates version number

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/Views/Artwork/ARArtworkActionsView.m
- Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
- CHANGELOG.yml
I noticed that we have a few lab options that we aren't using anymore, so I went through and pruned them down. Now the labs screen looks like this:
> Cleans up unused lab options

- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy/Views/Artwork/ARArtworkView.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
Our first iteration of the artwork view is just for non-commercial works. This PR updates our logic for whether or not to show the RN view or the legacy view to be the following:
- If the artwork is not "for sale" (different from "not for sale") _and_ the artwork is not "inquireable", we show the RN view as long as a user has the flag enabled.
> PURCHASE-1203 : Refines logic for showing RN artwork view for all non-commercial works

- Makefile
- docs/deploy_to_app_store.md
- docs/deploy_to_beta.md
Purchase recently did a QA session with a fresh version number, which triggers extra beta review from Apple, which delayed some of our testers.
To avoid this, we've added a new step to trigger a beta as soon as we change the version number. I used this as an opportunity to generally freshen up the deployment docs. It also updates the `Makefile` to no longer set git/date properties in `Info.plist` (because these are set for us during beta deploys). Let me know if I can clarify anything.
> Deployment doc updates

- Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
- CHANGELOG.yml
This is a longstanding bug with the LAI interface (longstanding as in, it's been there since we built the thing in 2016). Funny how taking a few years off of piece of code gives you a new perspective, eh? 
Unit testing this would be... impractical. But I've made sure to document what's going on. And I have a handy gif, which I guess is _almost_ as useful as a unit test?
> [PURCHASE-165] LAI view now updates the number of bids as they come in

- Podfile.lock
Self-assigning and merging-on-green because the changes in here have all already been reviewed.
> Updates Emission to 1.12.6

- Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
- CHANGELOG.yml
Introduced in #2867, it was caused by a mutex lock. The solution here is, instead of merging signals, we no longer filter non-bidding status updates from our signal. That is to say: we were only letting observers know about new bidding status updates when a subset of fields got updated, and now we send all updates from Causality through the signal.
> Fixes problem not being able to open LAI sales.

- Podfile.lock
This includes the last change that the Auctions team wanted to finish this week: https://github.com/artsy/emission/blob/master/CHANGELOG.md#1127
> Upgrade to Emission 1.12.8

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/Models/API_Models/Partner_Metadata/Artwork.h
- Artsy/Models/API_Models/Partner_Metadata/Artwork.m
- Artsy/Networking/artwork.graphql
- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
- CHANGELOG.yml
- Podfile.lock
This PR improves the user experience and tester experience of the new artwork view. It does a bunch of little things, so here's the summary:
- The artwork view, which appears on-screen while we do an MP call to determine which _actual_ artwork view to present, is now opaque white. It shows the spinner immediately instead of fading it in (the fade animation was taking longer than the MP request).
- There are new, more gradual lab options for testing the view. The lab options will now always appear in the same order, too (alphabetized). See the screenshot below.
- Applies consistent indentation to the `ARArtworkViewController` class and its tests (looks like we were mixing-and-matching 2 and 4 tab widths). For this reason, I recommend reviewing this PR with GitHub's "ignore whitespace" …
> [PURCHASE-1277] Improves UX and TX for new artwork view

- Podfile.lock
This includes the following changes:
* https://github.com/artsy/emission/pull/1743: Display an error message when polling fails on bidding
* https://github.com/artsy/emission/pull/1742: Fixes an issue where placing a bid hangs
> Upgrade to Emission 1.12.10

- Podfile.lock
This includes:
* https://github.com/artsy/emission/pull/1767: Cleans up old, duplicated docs
* https://github.com/artsy/emission/pull/1768: Fix copy on registration pending view
The whole diff: https://github.com/artsy/emission/compare/v1.12.12...v1.12.13
#trivial
> Upgrade to Emission 1.12.13

- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- Artsy/View_Controllers/Admin/ARAdminTableViewController.h
- Artsy/View_Controllers/Admin/ARAdminTableViewController.m
- CHANGELOG.yml
These were modifiable settings that are ignored while pointing to production. This leads to engineers trying to point the app (in production mode) to custom URLs, which it ignores in favour of a hard-coded constant:
https://github.com/artsy/eigen/blob/55c5b7f9e397b8778d65d53bdabbb3beb099dbd3/Artsy/Networking/ARRouter.m#L76-L84
This PR changes the admin menu to prevent users from trying to customize the URLs:
> [PLATFORM-1653] Prevents admins from customizing API URLs while pointing to production.

- Artsy/View_Controllers/Artwork/ARArtworkViewController.h
- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy/View_Controllers/Artwork/ARLegacyArtworkViewController.h
- CHANGELOG.yml
This PR replaces #2886. It:
- Removes landscape capability on `ARArtworkViewController` (was previously left in to support non-AR view-in-room).
- Cleans up an unused property left over from #2884. 
- Cleans up a bunch of compiler warnings.
The last one is kind of weird, so I've left a note in the commit message with more details.
> Disables landscape rotation, cleans up ARArtworkViewController

- Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
- Artsy_Tests/View_Controller_Tests/Web_Browsing/ARExternalWebBrowserViewControllerTests.m
- CHANGELOG.yml
Fixes [PURCHASE-1454](https://artsyproduct.atlassian.net/browse/PURCHASE-1454)
For some reason this navigation messes with the close button's position persistently. We already have a QA ticket for that bug on notion because it's affecting the auction views too, so I'm happy to tackle it separately. What do you think @alloy?
> PURCHASE-1454 Open web view target='_blank' links by pushing to navigation stack

- Artsy/App/ARAnalyticsVisualizer.m
- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- CHANGELOG.yml
A few things in this PR:
- Fixed a problem where we were showing users the new Artwork page for Auctions artworks /cc @sweir27 
- The UI for analytics debugging was being presented from a background thread, likely causing the delays and other UI bugs. I moved it to the main thread with `dispatch_async`.
- Presenting the detail view on iPad required some additional UIAlertController configuration. I added a link for further reading in a comment.
I also investigated the errant `"tap"` events being tracked:
One of the most used components in Emission, `GenericGrid`, fires this event _on layout_:
https://github.com/artsy/emission/blob/ce9ce5eaa143216fc9cd8a6fc41bee2eba3e2bf7/src/lib/Components/ArtworkGrids/GenericGrid.tsx#L42-L48
This seems like a bug to me, but I need to do more digging. …
> [PURCHASE-1414] Fixes Analytics

- Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme
A few years ago, Apple added a bunch of noise to our app's logs which led us ([and others](https://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-logs)) to disable them using the `OS_ACTIVITY_MODE="disable"` environment variable. However, as we ([and others](https://stackoverflow.com/questions/37886600/ios-10-doesnt-print-nslogs/43509270)) discovered, `NSLog` statements weren't printing anything to our console. (But Swift `print` statements _were_ still printed).
This is something @ds300 and I saw a few weeks ago, and that I ran into again yesterday. A noisy log is better than an incomplete log, so I'm disabling this env var (but leaving it there to be easily re-enabled if needed for debugging something). This was accomplished through the "Edit Scheme" UI:
Note: Apple …
> Enables full logging #trivial

- docs/updating_emission.md
- Updates the updating Emission docs with more thorough instructions for creating a new Eigen release with Emission
#trivial
> Updates doc with Eigen build instructions

- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
Follow up from: https://github.com/artsy/eigen/pull/2900
This flag is only a convenience; it complicates the logic around the phased rollout of the RN artwork view so let's remove it.
> [PURCHASE-1481] Removes ARReactNativeArtworkEnableAlways Echo flag #trivial

- Artsy/App/SwiftExtensions.swift
- Artsy/View_Controllers/Auction/AuctionViewController.swift
- CHANGELOG.yml
I was looking through Sentry and found this crash: https://sentry.io/organizations/artsynet/issues/739658774 I'd seen the crash before, but the solution just kind of clicked so I thought I'd get a fix in quickly. 
The problem is that the `viewWillAppear` callback assumes that the `saleViewModel` is already loaded _if_ the view is re-appearing. If the network is slow, this might not be the case, so I've added a guard to check that the `saleViewModel` is non-nil before trying to access any of its properties. (Note: this would normally be caught by the Swift compiler, but we're using an implicitly-unwrapped optional here. Ideally we'd avoid this and use a view controller containment to deal with the optionality of the view model, but that's a much larger refactor.)
> Fixes crash when AuctionViewController re-appears without a populated view model

- Artsy/Navigation_Transitions/ARAppSearchTransition.m
- Artsy/Navigation_Transitions/ARDefaultNavigationTransition.m
Previously, these were using default values from iOS, which worked _most_ of the time. By being explicit about what we want in terms of layout, we get a more reliable animation. I also had to change from animating with `frame` (which is a bad idea because [`frame` is complicated](https://ashfurrow.com/blog/you-probably-dont-understand-frames-and-bounds/)) to using `transform`.
Previously:
Now:
> [PURCHASE-1482] Adds explicit layout specification for default pop and search push animation

- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
@lilyfromseattle and I found this today – basically if an artwork is inquirable _and_ in an auction, we want to show the old view.
> Fixes show the new RN artwork view for sale artworks (that are inquirable) #trivial

- Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
https://artsyproduct.atlassian.net/browse/PURCHASE-1511
https://artsyproduct.atlassian.net/browse/PURCHASE-1512
I'm not sure about the ramifications of this change. While it fixes the problem and doesn't seem to break other webviews, I don't understand why new pages were originally being pushed onto the top level navigation stack rather than the one that the web view is currently in. Any ideas @ashfurrow ?
Also I noticed that this conditions-of-sale web view doesn't have a back button because it's a modal and it was opened from within a modal. So to go 'back' after visiting a sublink you have to dismiss the modal, going back to a different modal, and then tap back into the conditions of sale modal. We should really rethink these funky navigation flows as part of the mobile experience …
> PURCHASE-1511 PURCHASE-1512 Fix conditions-of-sale sublinks

- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingWebViewController.h
- CHANGELOG.yml
At one point, we supported customizing the navigation bar during onboarding to selectively show a back button, but that stopped working at some point (likely when we added support for the iPhone X notch). Now, when users tap the Terms of Service or Privacy Policy links, they are shown a web view that they can't back out of; the only solution is to force close the app and start the onboarding process again (a terrible UX).
This PR changes the behaviour of these links; users will now be shown the ToS or PP in Safari, rather than the app. This isn't a _great_ UX either, since it takes the user out of the app, but is _significantly_ less work than fixing a navigation bar that is _only_ used during onboarding for these specific links (which we don't expect will get tapped often, anyway). I'm …
> [ME-3] Fixes opening Terms/Privacy Policy links during onboarding

- fastlane/metadata/en-US/release_notes.txt
(Normally we replace the release notes from the previous version in this file, which [gets uploaded to AppStoreConnect when we promote a beta to an App Store submission](https://github.com/artsy/eigen/blob/0dfd9962311e3a691ff6d732e0ed02525d2ecdea/fastlane/Fastfile#L120-L160). The file was empty because during the last submission, the 5.0.6 hot fix, Circle CI had a partial outage so I had to promote the beta manually.)
> Updates release notes for 5.0.7 public release

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
- CHANGELOG.yml
I don't think there are any Emission changes merged in since we deployed last time, so it's just this native change to re-enable respecting the Echo flag.
Monday morning, we plan on doing the following:
- Release 5.0.7 ([instructions](https://github.com/artsy/eigen/blob/master/docs/deploy_to_app_store.md#release-to-app-store)).
- Create new iOS app version `6.0.0` in AppStoreConnect.
- `make deploy` on `master` after this PR is merged, to kick off a new beta for our QA session at noon.
> Prepares for next version

- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/View_Controllers/Util/ARNavigationController.m
- Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
- CHANGELOG.yml
This PR fixes a problem where duplicate view controllers were being pushed onto the stack, first introduced in #2909. The case where this bug happens is:
- Someone opens a profile link, and the profile 404's (ideally this wouldn't happen, but it does sometimes).
- The 404 page has a "go back to Artsy homepage" button, which links to `/`.
- The `ARRouter` routes from `/` to **the existing** `ARHomeComponentViewController`. 
- Normally, `ARTopMenuViewController` knows how to handle this case, but since #2909, it doesn't.
The fix was to check if the view controller we're routing _to_ already has a non-`nil` `navigationController` property, which indicates it's in an existing navigation stack. We dismiss ourselves from modal presentation (if applicable) before routing through the usual …
> [PURCHASE-1548] Duplicate view controller crash fix

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- Artsy/View_Controllers/Artwork/ARArtworkViewController.m
- Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
- CHANGELOG.yml
- Podfile.lock
- fastlane/metadata/en-US/release_notes.txt
Patches since we released 5.0.7. It reverts a change here: https://github.com/artsy/eigen/pull/2915
> 5.0.8 patch, re-disables Echo check for artwork view, Emission update

- Gemfile.lock
Replaces #2918 to get CI green. See: https://github.com/danger/swift/issues/281
> Bump rubyzip from 1.2.1 to 1.3.0

- Artsy/View_Controllers/AuctionBuyNowView.swift
- CHANGELOG.yml
This bug was introduced in #2884 and released on Monday in 5.0.7. It's a quick fix, so let's get it in for 5.0.8.
For context around the bug, the `as?` is a conditional cast in Swift. If the cast fails, then the `else` block gets executed (in this case, `return`). This was causing the UI to not respond. The bug was introduced because there were a bunch of similar changes to remove the swipe controller, and in this code, there are two sources of truth for which model got selected. I switched to the one that made more sense to me, but missed this change while testing the change.
> [PURCHASE-1542] Fixes problem selecting buy now artworks from auction view

- Artsy/Navigation_Transitions/ARAppSearchTransition.m
- Artsy/Navigation_Transitions/ARDefaultNavigationTransition.m
- CHANGELOG.yml
This reverts the change from #2904 because it introduced the problem for PURCHASE-1537. We re-opened ticket 1482 (the extra white padding above the artwork page) and moved it to Mobile Experience's backlog. It's a relatively minor bug compared to what this fixes.
We also tried to clean up code indentation and commenting, I'll comment on the import changes below.
> [PURCHASE-1537] Fix search transition animation

- Artsy/App/ARAppDelegate.m
Running eigen locally from master I was unable to interact with the app because the default value for `KillSwitchBuildMinimum` was the empty string, which triggered the kill switch. Here I updated the check for whether or not the `KillSwitchBuildMinimum` is set to fail in the case of the empty string.
Maybe it would make more sense to set the dev value of `KillSwitchBuildMinimum` to `"0.0.0"`?
#trivial
> Fix presence check for echoMinimumBuild

- Artsy/App/ARAppDelegate.m
https://artsyproduct.atlassian.net/browse/ME-11
I discovered that the push notification was being handled twice at launch. Both here, where this code is being deleted, and in `ARNotificationsDelegate` by way of `didReceiveRemoteNotification` being triggered (presumably by iOS?)
Both of these trigger the [`applicationDidReceiveRemoteNotification` method](https://github.com/artsy/eigen/blob/1708a28de50114ed7d6f90e5d668704be2edb1fc/Artsy/App/ARAppNotificationsDelegate.m#L187) which is very much not idempotent, and the second invocation was causing the strange behaviour we were seeing somehow.
So deleting this code seems to fix the issue for me. Indeed, I wonder how this ever worked or why this code was there in the first place if `didReceiveRemoteNotification` gets triggered when you tap …
> ME-11 Fix conversations push notification handling

- Artsy/View_Controllers/ARVIR/Views/ARInformationView.m
- CHANGELOG.yml
This came up during knowledge-share this morning. Here's the Sentry report (no Jira ticket): https://sentry.io/organizations/artsynet/issues/1150547566/events/6b17772e38404324965147e32d05e93b/?project=166784
I think what happens is that sometimes this method gets involved repeatedly, asynchronously. This can cause `self.index` to overflow the array bounds, which we _are_ checking for, but with `>` instead of `>=`. This should fix it.
> Fixes intermittent crash during Augmented Reality View-in-Room

- Artsy/App/ARAppDelegate+Emission.m
- Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
It's been a long time since we released the Buy Now Make Offer last year, and I don't think we use a feature flag for it at this point. There are only [two occurrences in the entire org](https://github.com/search?q=org%3Aartsy+enableBuyNowMakeOffer&type=Code), both of which are in Eigen, so this should be safe to remove.
#trivial
> Remove unused feature flag

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- CHANGELOG.yml
addresses https://artsyproduct.atlassian.net/browse/AUCT-697
This adds a new feature flag `AROptionsPriceTransparency` to Eigen so we can toggle the entire feature either globally or per admin basis. I've already [added a new flag that has the consistent name in Echo](https://echo-web-production.herokuapp.com/accounts/1/features/13), so in theory it should work fine. Though this is my first Eigen PR for the first time in a while, so let me know if there's anything wrong.
> Add a feature flag for Price Transparency

- Artsy/App/ARAppDelegate.m
- Fixes killswitch to use a minimum version instead of a maximum from echo
#trivial
> Killswitch to ascending

- Artsy/View_Controllers/ARVIR/AR/ARVIRHorizontalPlaneInteractionController.m
- CHANGELOG.yml
I've left a comment explaining the change and how the fix works. Here's the tl;dr
- We use ARKit's `rawFeaturePoints` (which is intended for debugging) to show the user that we're loading the ARKit scene (ie: that ARKit is mapping the world).
- In iOS 13, this "point cloud" started including points that were really close to the camera. [I asked around](https://twitter.com/ashfurrow/status/1189910896920989700) but no one else has been seeing this behaviour. Here's what it looked like:
<details><summary>screenshot of ARKit session start</summary>
</details>
- The docs say that this point cloud isn't stable between versions, so I think iOS is just adding extra points really early in the AR session (they go away after a few seconds, by which time we no longer want to show the point cloud …
> [ME-1] Fixes ARKit point cloud bug

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m
- Artsy/Views/Utilities/ARTabContentView.m
- CHANGELOG.yml
- Podfile.lock
This PR adds a lab option for selecting the new search component VC as a normal view controller (rather than a weird modal). See: https://github.com/artsy/emission/pull/1958
> [ME-83] Initial work for new Search UI

- Artsy/View_Controllers/ARMutableLinkViewController.m
- Artsy/View_Controllers/Fair/ARProfileViewController.m
- CHANGELOG.yml
- Updates Profile and Mutable view controllers to use the default white background unless a fair, in which case we use transparent.
> Updates viewcontrollers background colors

- Artsy/App/ARAppDelegate+Emission.m
- CHANGELOG.yml
Following up on https://github.com/artsy/eigen/pull/2934#issuecomment-547111199. This update Eigen to also look at the Echo flag for the new Price Transparecy as well as the lab feature flag.
> ⚠️ Do not merge: Add a new flag for Price Transparency to Echo

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
As discussed [in Slack](https://artsy.slack.com/archives/CN8S32FJR/p1574264726054600?thread_ts=1574264242.052500&cid=CN8S32FJR) and in today's FE iOS Practice meeting. I'll update AppStoreConnect too.
- The changelog was manually edited.
- The rest was done with `make update_bundle_version`.
> Bumps version to 6.1.0

- Artsy/View_Controllers/ARMutableLinkViewController.m
- Podfile.lock
- https://artsyproduct.atlassian.net/browse/MX-115
#trivial
> MX-115 - Fixes landscape partner page

- fastlane/metadata/en-US/description.txt
- fastlane/metadata/en-US/keywords.txt
- fastlane/metadata/en-US/subtitle.txt
These changes were intended to go live with the 6.0.0 release, but [as I described in Slack](https://artsy.slack.com/archives/CN8S32FJR/p1574799323016500), the new updates were overwritten by the _old_ versions here in the repo. 
Going forward, the metadata in the repo should be considered canonical.
> Updates App Store metadata

- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- CHANGELOG.yml
This PR adds an option to the admin menu (you can get there by shaking your device or hitting the backtick key ` on your keyboard while in the simulator) to show a collection:
This will unblock our Grow colleagues from QA'ing the in-progress collections work. I'll go into more detail in-person next week in our check-in, but tl;dr tickets in Mobile Experience/Purchase are generally considered "done" once they have been deployed and tested in an Eigen beta. 
- Grow will send PRs to Emission
- After merging, PR's get auto-deployed (thanks @ds300!)
- When ready to QA some tickets, we'll update the version of Emission that Eigen uses (ie: `bundle exec pod update Emission`)
- Then we'll cut a new beta (ie: `make deploy`)
> Adds admin option to show collection view controller

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/ARAppDelegate.m
- Artsy_Tests/Supporting_Files/ARTestHelper.m
- CHANGELOG.yml
- Podfile
- Podfile.lock
See: https://github.com/artsy/emission/pull/1995
I've already pushed a beta with these changes, so no rush to get this merged.
> [MX-54] Migrates to new Emission-based, native iOS ratings prompt

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
We released 6.1.0 of the app this morning, which means there is post-release follow-up to take care of. The steps are [outlined in the documentation](https://github.com/artsy/eigen/blob/master/docs/deploy_to_app_store.md#prepare-for-the-next-release) but the quick version is:
- Create a new version (6.2.0) in AppStoreConnect.
- Update changelog, manually.
- Run `make next` to update various `Info.plist` files' version numbers (build numbers are set automatically during beta deploys).
Let me know what I can clarify.
> Preparing for 6.2.0

- Artsy/View_Controllers/Util/ARNavigationController.m
https://artsyproduct.atlassian.net/browse/MX-127
Now that search is it's own page we had a problem in deciding _where_ tapping a search result takes you in our nav system.
This PR implements the decision to copy the twitter app by keeping all search-related activity in the search page. It accomplishes this by hiding the bottom toolbar nav when viewing search results.
Here's how that looks.
Where I've put this logic feels like the wrong place conceptually but also the simplest place practically. I'm curious if you're concerned about that @ashfurrow or maybe you have a suggestion for where else this could go?
> [MX-127] Hide tool bar when in search nav stack

- Artsy/App/ARAppDelegate+Emission.m
To disable react native default debug menu and present our own we are swizzling out the RCT_motionEnded method in Emission setup, with new logout flow this is occurring multiple times so needs to be wrapped in a dispatch_once block. Long term we should probably look into other ways of doing this but I can't see an obvious solution right now.
https://github.com/facebook/react-native/issues/4330
https://github.com/facebook/react-native/blob/master/React/CoreModules/RCTDevMenu.mm#L108
> Avoid swizzling debug method again on logout

- Artsy/View_Controllers/AREigenCollectionComponentViewController.m
Design requested that the status bar icons in Collections be black, not white. This PR implements that change.
[See comments in FX-1421 for context](https://artsyproduct.atlassian.net/browse/GROW-1421)
#trivial
> Changes status bar icon colors from white to black

- Artsy/View_Controllers/Util/ARNavigationController.m
Sam, Brittney and I were discussing the behaviour of hiding the bottom tab bar when tapping in a search. In the abstract, the idea made sense, but seeing it play out on-device felt weird. If a user is searching, they might want to tap from a search result back to their Home (or Conversations, or Favourites, etc) and then quickly back to their search result again (see the below GIF).
<details><summary>GIF of the original (now new again) behaviour</summary>
</details> 
This PR changes back the behaviour introduced #2969. I think it was worth trying out, and we learned from it 👍
> Moves back to old-style search nav bar behaviour #trivial

- Artsy/App/ARAnalyticsConstants.h
- Artsy/App/ARAnalyticsConstants.m
- Artsy/App/ARAppDelegate+Analytics.m
https://artsyproduct.atlassian.net/browse/MX-96
Removing a redundant Artist screen view event and removing redundant properties from the remaining Artist screen view event.
There will be one more PR to emission which removes another redundant artist screen view event!
> [MX-96] Remove redundant analytics for Artist screen views

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/View_Controllers/ARSerifNavigationViewController.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
The underlying issue is that React Native's `KeyboardAvoidingView` isn't yet taking into account the additional space added by the iOS 13 modal presentation style ([there is an open pull request](https://github.com/facebook/react-native/pull/27607)). We could adopt this approach, but I'd rather not duplicate logic that will be included in the view itself pretty soon.
Instead, I read more about the transition changes ([this blog post was really helpful](https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e)) and have opted out of the new transition style on iPhone only. Here's a before-and-after of the behaviour on iOS 13 devices in the different contexts that we present modal view controllers (not including uncommonly-seen views, like the Privacy …
> [MX-152] Opts out of new iOS 13 modal presentation style on iPhone

- Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift
- Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionToolbarView.swift
- CHANGELOG.yml
Same issue as https://github.com/artsy/eigen/pull/2996 causing toolbar to be hidden on iOS 13. 
**Before:**
**After:**
> Fix auction toolbar display on iOS 13

- Artsy.xcodeproj/project.pbxproj
- Artsy/Networking/API_Modules/ARUserManager.m
- Artsy/Networking/API_Modules/ArtsyAPI+DeviceTokens.h
- Artsy/Networking/API_Modules/ArtsyAPI+DeviceTokens.m
- Artsy/Networking/ARNetworkConstants.h
- Artsy/Networking/ARNetworkConstants.m
- Artsy/Networking/ARRouter.h
- Artsy/Networking/ARRouter.m
- CHANGELOG.yml
This won't work until artsy/gravity#12751 gets deployed, but it can be deployed first without disrupting the current behaviour. Worth noting that I haven't tested the happy path yet! Only the sad path.
https://artsyproduct.atlassian.net/browse/MX-159
> [MX-159] clear APN token on logout

- .gitignore
- Artsy.xcodeproj/project.pbxproj
- Artsy.xcodeproj/xcshareddata/xcschemes/Artsy Integration Tests.xcscheme
- Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme
- Artsy/App/ARAppDelegate+Emission.m
- Artsy/Networking/ARReactPackagerHost.h
- scripts/set_packager_host.sh
When running eigen linked with emission on a device you need to manually edit `Artsy/App/ARAppDelegate+Emission.m` to set the packager url to point to your local machine. This is a pain if, like me, you change wifi networks a lot.
This PR causes the packager URL to be set automatically when in dev mode.
During the build phase we write an obj-c file containing your macbook's hostname. This PR adds that file to the project index but not the git index, and git will ignore it going forward.
I think this is a robust way to do it. Definitely try it out before merging though!
#known
> Set react packager url automatically

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- CHANGELOG.yml
- Adds a lab option/feature flag for lot condition report in artwork details for biddable artwork
Emission PR here:
https://github.com/artsy/emission/pull/2050
> [AUCT-744] - Add Lot Condition Report lab option

- Artsy/Networking/API_Modules/ARUserManager.m
Tiny followup from #3007, moving the push notification token deletion into the `logout` method so it gets called after session expiration too. Perhaps in gravity we should clear all device tokens associated with a user when they reset their password?
#trivial
> Move token deletion into logout method

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
I went with 6.3.1 as a version number based on upcoming product work.
> Updates for next version of the app #trivial

- emission/src/lib/Scenes/Collection/Collection.tsx
- emission/src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
This PR just updates the styles on the filter button (and makes it show up a little later).
Gif
Screenshot
(Side note: the fact that these RN PRs now go to `eigen` makes me feel like a real mobile developer 😻)
> FX-1811: Updates styling on the filter button for collections

- emission/src/lib/Scenes/Collection/Collection.tsx
This PR re-introduces code that was lost during a rebase and merge of  https://github.com/artsy/eigen/pull/3029 and https://github.com/artsy/emission/pull/2096.
#trivial
> Fixes bug introduced via Eigen/Emission rebase

- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingNavigationItemsView.m
- CHANGELOG.yml
This PR does two things:
- Show the user the error from Gravity when new account creation fails.
- Increases minimum allowed new password length to 8.
The UX is not... ideal. Modifying the error-handling is difficult because of how the code is organized, and tightly coupled. Additionally, while the user _can_ swipe to go back, there is no affordance for this and no back button. So in the case of an error, I decided to take the user back to the first screen where they can take action, where we ask for email. They'll have to go through the process from there. 
When it comes to migrating code from Objective-C to React Native, I'd say that the login/signup flow would be a great candidate. Maybe even higher priority than our routing logic, since it's so user-facing and high-impact. Open to …
> [MX-205] Show password error details, increase minimum password length

- .circleci/config.yml
We were having a problem where the `Emission.js` was not being included in beta builds. That's because the `Emission.js` file was being built *after* `pod install` had run, which means that it wasn't copied over from `emission/Pod/Assets` to `Pods/Emission/Assets` which is where it needs to be at build time.
This PR fixes that by manually copying `Emission.js` to `Pods/Emission/Assets`.
> But why not just bundle the JS before running `pod install` so it gets copied over automatically? 
Because then we'd need to invalidate our `Pods` cache whenever `Emission.js` changes, which is _pretty much always_.
#trivial
> Fix missing Emission.js

- scripts/set_packager_host.sh
@anandaroop [ran into an issue](https://artsy.slack.com/archives/C02BAQ5K7/p1582576904013500) where his macbook's local hostname was not resolvable because he didn't have any sharing options enabled in his system settings. This meant the app couldn't connect to the react packager to load the JS bundle. 
To prevent people running into the same issue in the future, this PR makes the host string fall back to your local wifi IP, or `localhost` if you're not connected to wifi.
#trivial
> Intelligent fallbacks for packager hostname

- CHANGELOG.yml
- src/lib/relay/middlewares/__tests__/cacheMiddleware-tests.ts
- src/lib/relay/middlewares/cacheMiddleware.ts
This fixes an issue where marking an artwork as recently viewed would clear the entire client-side cache. We should re-evaluate this strategy altogether sometime, since we still do a lot of cache clearing that we don't need to be. 
I also added some types to `cacheMiddleware.ts`.
> [MX-184] Allows some mutations to bypass client-side cache clearing

- CHANGELOG.yml
- src/lib/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
https://artsyproduct.atlassian.net/browse/MX-230
Accidentally stumbled on this error while working on other things. No idea why it's only just started happening, but it seems to happen *sometimes* when you navigate *away* from an artwork page. Either by tapping a link or hitting the back button.
I could reliably get it to happen after tapping between an artist and their artworks madly for a few seconds, and after this change the same kind of mad tapping does not produce errors.
> [MX-230] Grid bugfix

- CHANGELOG.yml
- package.json
- src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomView.tsx
- src/lib/Scenes/Collection/Collection.tsx
- src/lib/utils/__tests__/markdown-kitchen-sink.md
- src/lib/utils/__tests__/renderMarkdown-tests.tsx
- src/lib/utils/renderMarkdown.tsx
- yarn.lock
https://artsyproduct.atlassian.net/browse/MX-169
```md
this art work is lovely
----
it's really so so nice
many a work wishes it were as nice as this work
----
> Yes this is a lovely work, thank you. *but* I wish it came in blue.
- Jackson Pollock
```
becomes
Would it make sense to prevent Partners from including this kind of content in artwork details markdown?
> [MX-169] Handle remaining markdown element types

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
I've created 6.3.2 in AppStoreConnect, and that leaves this PR as follow-up. We need to do this so betas work. This involves:
- Running `make next` to update versions.
- Moving Changelog entries around (usually pretty simple, but with the cherry-picking for the [6.3.1 release](https://github.com/artsy/eigen/releases/tag/6.3.1-2020.02.27.16) it was a little more involved).
> Prep for 6.3.2 release

- src/lib/Components/ArtworkFilterOptions/SortOptions.tsx
- src/lib/Components/FilterModal.tsx
Updates font styling based on feedback from the QA of https://artsyproduct.atlassian.net/browse/FX-1781.
- Can we use consistent casing? – Recently Updated and Added use Title Casing and Artwork year uses sentence casing. Can we use sentence casing?
- “Filter” should be 16px Unica Medium 
- “Clear all” should be 14 px Unica Regular
- “Sort” by and “Default” should be 16px Garamond
> Updates artwork filter fonts per QA feedback

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
- CHANGELOG.yml
Just an update to the UI, not the client-side validation:
> Updates UI for password requirements #trivial

- Makefile
I did three things here:
1. Added `bundle exec pod install` to the end because you're always going to want to do that, I think.
2. Cleared a few other caches: relay's query cache, jest transformer cache, and the emission bundle artefacts.
3. Moved the package manager cache clearing to a super-task called `flip_table_extreme` because those should only ever be needed in very very very rare situations, and clearing those caches can be quite expensive in terms of extra dev time spent waiting for things to install.
#trivial
> add to flip_table

- src/lib/Components/FilterModal.tsx
After last week's QA Jeffrey modified the font size on the filter header, which slightly deviates from the design spec, this PR makes that change.
> Alignment + size adjustment on Filter header

- CHANGELOG.yml
- src/lib/Components/ArtworkGrids/GenericGrid.tsx
- src/lib/Components/WorksForYou/Notification.tsx
- src/lib/Components/WorksForYou/__tests__/Notification-tests.tsx
- src/lib/Components/WorksForYou/__tests__/__snapshots__/Notification-tests.tsx.snap
- src/lib/Containers/WorksForYou.tsx
- src/lib/Containers/__tests__/WorksForYou-tests.tsx
- src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap
https://artsyproduct.atlassian.net/browse/MX-248
Thanks to @alloy for discovering this bug  🙌 
The problem was
1. the `GenericGrid` component initially renders with a height of 0, then measures it's own width before populating the grid with artworks.
2. in `WorksForYou` (Artists tab on home screen) `GenericGrid`s were being rendered in a `FlatList`
3. When you scroll far enough in a `FlatList` things that are off-screen will be unmounted and removed. When you scroll back they will be mounted and shown again.
4. When a component re-mounts with a different height `FlatList` rightly adjusts the top offset of succeeding items to match.
5. Scrolling far down in `WorksForYou` and then scrolling back up was a disco funky janky mess.
This has been a problem since the recent react-native upgrade …
> [MX-248] Fix works-for-you scrolling

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
- docs/deploy_to_app_store.md
I created the new version in AppStoreConnect, and moved the changelog around to account for what we released. Since `emission_version` is no longer a thing, I removed it from the new version and the docs. Self-merging as this will block other PRs (otherwise their changelog entries will be under the wrong version).
> Changelog update for 6.3.3 #trivial

- fastlane/Fastfile
Prettier changed a bunch of formatting in the `Fastfile` but I didn't notice in time to isolate the changes 😒 At least it's a good demonstration of what Prettier considers "good" Ruby style!
Anyway. I have noticed that we have this one release, `1.6.0-2015.1.5-submission`, that lingers near the top of [Eigen's releases](https://github.com/artsy/eigen/releases). 
I took a look and we were constantly re-tagging the _first_ ever releases through TestFlight, instead of the most recent one. Whoopsie. (I'm not entirely willing to take the blame on this, it could be that Apple's APIs reversed the order of their responses at some point.)
What's more, the commit that we're targeting as the submission to the App Store is technically the commit that ran on CI _to_ submit, and not the commit of the …
> Fixes App Store promotion script #trivial

- .circleci/config.yml
- .gitignore
~So it turns out that the reason this wasn't working is that xcode detects file changes by inspecting the 'last modified' timestamp of files. Circle's cache restoration does not preserve those timestamps so xcode thinks everything has changed since the last build and rebuilds everything.~
~[this blogpost](https://medium.com/@bitrise/60-faster-builds-force-xcode-to-use-caching-on-bitrise-af8979ca39a6) says you can fix this by just resetting the timestamps, so in this PR I made a script which saves the timestamps before saving the cache, then restores the timestamps after restoring the cache.~
as mentioned [on slack](https://artsy.slack.com/archives/CN8S32FJR/p1583512314109700?thread_ts=1583428005.089000&cid=CN8S32FJR) this was proving to be a serious rabbit hole with no clear evidence that …
> Stop caching derived_data on ci

- CHANGELOG.yml
- src/lib/Scenes/Fair/Components/FairBoothPreview/index.tsx
- src/lib/Scenes/Fair/Screens/FairDetail.tsx
- src/lib/data/constants.ts
This is the only other place where `GenericGrid` could cause glitchy scrolling... for now  👀 It would be good to find some other way of laying out images. I *think* it's possible to do without knowing width as long as we know the image aspect ratios.
> Use static width for GenericGrid on Fairs page

- CHANGELOG.yml
- data/schema.graphql
- src/__generated__/ArtworkDetails_artwork.graphql.ts
- src/__generated__/ArtworkFullQuery.graphql.ts
- src/lib/Scenes/Artwork/Artwork.tsx
- src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
- src/lib/Scenes/Artwork/Components/__tests__/ArtworkDetails-tests.tsx
- src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-928
This is basically the same change as https://github.com/artsy/reaction/pull/3223 but for our iOS app. This replaces the `isBiddable` flag with the new `canRequestLotCOnditionsReport` flag to toggle the request button.
> User does not see lot condition report request if it's disabled for a sale

- CHANGELOG.yml
- src/lib/Scenes/Home/Components/ForYou/Components/ArtworkRail.tsx
Noticed this while developing locally. Love the new short-circuiting operator!
> Fixes WSOD on home feed with artworks that have missing images #trivial

- Artsy/App/ARAppDelegate+Analytics.m
- CHANGELOG.yml
- src/lib/Containers/Artist.tsx
Okay so here's what happened. [This PR](https://github.com/artsy/emission/pull/2058) fixed a problem where we were duplicating tracking events of Artist screen views. Later, I saw a runtime error about a missing `@track` decorator, which I fixed [in this PR](https://github.com/artsy/emission/pull/2062). This fixed the runtime error, but not the underlying problem.
I added `@track`, but `@track` and `@screenTrack` are subtly different. `@screenTrack` includes a `dispatch` argument already, which gets shared down the whole component tree:
https://github.com/artsy/eigen/blob/da03b34416d5f5980cafe79350ac86dba3563471/src/lib/utils/track/index.ts#L142
Without this `dispatch`, tracking will technically fire but those events won't be dispatched anywhere. It seems that `react-tracking` will …
> [MX-255] Fixes problem where artist follows on Artist page weren't being tracked

- src/lib/Components/Consignments/Components/TextInput.tsx
- src/lib/Components/Consignments/Screens/Metadata.tsx
https://artsyproduct.atlassian.net/browse/MX-240
- Fix a bug where navigator push transitions were duplicated, by making sure `.focus` is called on a TextInput synchronously after mounting rather than during the transition animation (though not sure why the animation was being restarted as a result of that. The animation was handled by CA so I didn't feel it was worth digging into.)
- Fix another bug I found where the submit button on the Metadata step of the consignments flow was being hidden behind the keyboard.
Before:
After:
> [MX-240] Consignments ui fixes

- .circleci/config.yml
I noticed this was failing: https://circleci.com/gh/artsy/eigen/7398
Seems like Linux (which we use for that job) uses a different command name for generating md5 hashes. TIL!
> Fixes the update-metaphysics circle job #trivial

- src/lib/Components/Consignments/Components/__tests__/__snapshots__/TextInput-tests.tsx.snap
- src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Edition-tests.tsx.snap
- src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Metadata-tests.tsx.snap
- src/lib/Scenes/Search/RecentSearches.tsx
- src/lib/Scenes/Search/SearchResult.tsx
- src/lib/utils/track/schema.ts
The [tracking schema](https://github.com/artsy/eigen/blob/master/src/lib/utils/track/schema.ts) is kind of all over the place – some events `have spaces`, some `use_snake_case`, and some `UseCamelCase`. @mikehrom we've previously discussed having the Data team take ownership of this schema, which would let use use the schema y'all define with less back-and-forth. Maybe we can chat about this in Tuesday's Knowledge Share?
> [MX-202] Updates tracking for tapping recent search results #trivial

- src/lib/Components/ArtworkFilterOptions/SortOptions.tsx
- src/lib/Components/ArtworkFilterOptions/__tests__/SortOptions-tests.tsx
- src/lib/Components/FilterModal.tsx
- src/lib/Components/__tests__/FilterModal-tests.tsx
- src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
- src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx
- src/lib/utils/ArtworkFiltersStore.tsx
- src/lib/utils/__tests__/ArtworkFiltersStore-tests.tsx
This PR fixes https://artsyproduct.atlassian.net/browse/FX-1851 and makes a few minor refactors to the store (will explain inline)!
To summarize:
- Removed the `selectedSortOption` item from the global state object since this value can be derived from existing properties (the `selectedFilters` and `appliedFilters` arrays).
- Refactored the shape of the `FilterArray`s slightly.
- Fixed the bug described in the ticket!
#trivial
> Selected sort option

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
- Moved changelog entries down.
- Ran `make next`.
Went with 6.4.0 since we have some larger, user-facing changes to Home coming up.
> Prepares for 6.4.0 release #trivial

- patches/react-dom+16.8.3.patch
Fixes the 'cannot read property body of null' nondeterministic error that seems to be a bug in the react-dom/jsdom teardown sequence.
see facebook/react#15691
> Fix jest flake

- .circleci/config.yml
On our first beta build after the CI revamp, the build failed claiming that the project directory was not empty while trying to check out the code from github.
Not sure why this was only a problem on the beta branch, but the fix is straightforward enough: just delete the project directory before it tries to check it out :)
> Fix beta build

- CHANGELOG.yml
- src/lib/Components/ArtworkFilterOptions/__tests__/SortOptions-tests.tsx
- src/lib/Components/FilterModal.tsx
- src/lib/Components/__tests__/FilterModal-tests.tsx
- src/lib/utils/ArtworkFiltersStore.tsx
- src/lib/utils/__tests__/ArtworkFiltersStore-tests.tsx
Addresses https://artsyproduct.atlassian.net/browse/FX-1873
When a user clicks "Clear All", we want to re-set their current UI state in the filter modal to the default, but also allow them to:
- X out of the modal entirely, in which case if they re-open it's as if they'd never clicked "Clear all" at all
- Apply the changes, in which case everything is returned to the default upon re-opening the modal.
In order to do this, I added an additional piece of state (currently named `previouslyAppliedFilters`). The updated definition of our `ArtworkContextFilterState` is:
- `selectedFilters`: Options that are selected within the filter modal UI. Gets re-set to `[]` when the modal is closed.
- `appliedFilters`: Always represents the filters that are applied to the artwork grid. Only changes when …
> FX-1873: Allows user to "Clear All" and apply changes in collections filter

- .circleci/config.yml
Reverts artsy/eigen#3120
This PR seems to have caused a problem with linux builds not being able to restore caches properly, or simply running out of memory. I'm going to revert for now and send CircleCI a message about it.
Here's an example build failure: https://app.circleci.com/pipelines/github/artsy/eigen/487/workflows/81c4aeaa-002f-4af3-a08d-8758485e96f6/jobs/7699
Notice that the cache restorations appear to happen successfully but then the actual files aren't there.
> Revert "Update node orb to v2"

- Podfile.lock
After updating XCode to latest, booting Eigen led to a compiler error: 
Following the thread, i ran into this issue: https://stackoverflow.com/questions/60841771/stripe-ios-sdk-incompatible-block-pointer-types-sending
Which provided the solution: 
```sh
bundle exec pod update Stripe
```
Not sure what the implications of this lib update are, but it fixed the compiler issue on my side. 
#trivial
> Fix compiler error by bumping Stripe pod

- .gitattributes
I was reviewing #3134 and the "mark file as viewed" feature in GitHub PRs was tedious to use. I looked up [the docs](https://help.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github) and it looks like we had a slight syntax error. This should remove the generated files from the PR review pane, I think.
> Removes generated files from PR web diffs, hopefully #trivial

- CHANGELOG.yml
Updating whatsNew in the App Store [started failing](https://circleci.com/gh/artsy/eigen/7852) due to:
> Could not set changelog: An attribute value has invalid text. - Text for whatsNew contains invalid characters/formats.
Here is my attempt to fix it. Let's see how it goes...
#trivial
> Attempt to fix an issue where whatsNew in AppStore can not be updated

- CHANGELOG.yml
- src/__generated__/RegistrationFlowQuery.graphql.ts
- src/__generated__/Registration_me.graphql.ts
- src/__generated__/Registration_sale.graphql.ts
- src/lib/Components/Bidding/Screens/Registration.tsx
- src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
- src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
- src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap
addresses https://artsyproduct.atlassian.net/browse/AUCT-950
This adds a new text to explain what IDV is for users who are new to it. On larger screens, it looks totally fine. But on iPhone SE the button at the bottom was pushed down to outside of the viewport. So I replaced the container with a `<ScrollView>`. This blog post https://medium.com/@peterpme/taming-react-natives-scrollview-with-flex-144e6ff76c08 was heplful to get the components positions right.
> Non-IDV new bidder registering through typical registration form sees information about identity verification

- src/lib/Components/Artist/ArtistConsignButton.tsx
- src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
- src/lib/Components/Artist/__tests__/__snapshots__/ArtistConsignButton-tests.tsx.snap
Fixes https://artsyproduct.atlassian.net/browse/CSGN-125
We had a click action on the outer container, but this isn't web; the inner button will capture the event if touched.
#trivial
> [Bugfix/Consignments] Ensure inner button triggers action

- src/lib/Scenes/Collection/Screens/CollectionZeroState.tsx
- src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx
Updates the zero state layout when filtering collections artworks yields no results.
#trivial
> Updates Collections Artworks Zero State Layout

- CHANGELOG.yml
- src/lib/Components/FilterModal.tsx
- src/lib/Components/__tests__/FilterModal-tests.tsx
- src/lib/Scenes/Collection/Collection.tsx
- src/lib/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
- src/lib/Scenes/Collection/Helpers/FilterArtworksHelpers.ts
- src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
- src/lib/Scenes/Collection/Screens/CollectionZeroState.tsx
- src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx
Adds analytics tracking for:
- opening filter modal
- closing filter modal
- applying filters
- clearing filters
https://artsyproduct.atlassian.net/browse/FX-1856
> Adds tracking to collections artworks filters

- CHANGELOG.yml
- src/lib/Components/Bidding/Screens/Registration.tsx
- src/lib/Components/Bidding/Screens/RegistrationResult.tsx
- src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
- src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx
- src/lib/utils/renderMarkdown.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-951 and https://artsyproduct.atlassian.net/browse/AUCT-953.
> Non-IDV bidder sees copy in the "registration pending" modals about identity verification

- .circleci/config.yml
Going to self-merge this tiny change. `yarn relay` is really fast so this is kinda overkill.
> Always compile query map

- data/schema.graphql
- src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
- src/__generated__/ArtistConsignButtonTestsQuery.graphql.ts
- src/__generated__/ArtistConsignButton_artist.graphql.ts
- src/lib/Components/Artist/ArtistConsignButton.tsx
- src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-98
Depends on https://github.com/artsy/metaphysics/pull/2284 
Related https://github.com/artsy/reaction/pull/3364
Updates the Consign button with new `isTargetSupply` check. 
#trivial (changelog entry already has sufficient description)
> [Consignments] Update ArtistConsignButton with targetSupply check

- src/lib/Components/Artist/ArtistConsignButton.tsx
Address design feedback:
Non-target-supply artists missing padding around text: 
Larger Arrow: 
#trivial
> [ArtistConsignButton] Visual QA

- src/lib/Components/Artist/ArtistConsignButton.tsx
Padding didn't quite match the comps on the default button, had to expand it a bit: 
#trivial
> [ArtistConsignButton] Fix padding

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
A gallery partner wrote in to say that they couldn't log into the app with their email ending in `.gallery`. Turns out we only allow TLDs up to 5 characters - this PR loosens the regex to allow 7 characters.
> Allow 7 character TLDs instead of 5

- .circleci/config.yml
6am UTC is currently 2am in NY and 7am in London so it should be finished by the time I start working, and it shouldn't be started while y'all are still awake.
Paired on this with @brainbicycle during knowledge share 🎓
> Add cron job to deploy beta at 6am UTC

- Artsy/Constants/ARDefaults.h
- Artsy/Constants/ARDefaults.m
- Artsy/Networking/API_Modules/ARUserManager.h
- Artsy/Networking/API_Modules/ARUserManager.m
- Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
- CHANGELOG.yml
- Reenable sign in with apple
- Workaround for a bug that occurs when first auth fails
Apple only shares user email and name on first authentication so if initial authentication fails to create an artsy user for whatever reason (previously linked account, network error) we need to store the user name and email to enable sign up later. This does that by storing in keychain and deleting once a user is created successfully.
> [MX-214] - Fix sign up on initial sign up with apple failure

- Artsy/App/ARAppDelegate+Emission.m
- CHANGELOG.yml
- emission/Pod/Classes/Core/ARSwitchBoardModule.h
- emission/Pod/Classes/Core/ARSwitchBoardModule.m
- src/lib/Components/Bidding/Screens/RegistrationResult.tsx
Yuki was running into a problem where the `RCTRootView`'s `reactViewController` property was `nil`. This was because the code was being invoked from the Bid Flow interface, which uses its own navigation controller (that's my intuition, anyway).
The thing is, `fromViewController` isn't even used in the `presentNavigationViewController` and `presentModalViewController` blocks. Removing the parameter altogether would be a big refactor, so I opted instead to remove the `_Nonnull` specifier and the `NSParameterAssert` that was causing the crash. I also prefixed the parameter names in the blocks in `ARAppDelegate+Emission.m` to indicate that `_fromViewController` isn't used.
> Removes ARSwitchBoardModule requirement that fromViewController lookup succeeds

- .circleci/config.yml
Instead of waiting for another job to complete _in_ a job ([which was failing due to a timeout](https://circleci.com/gh/artsy/eigen/8268)), we can use the `requires` on workflows to just not start the MP update job until the beta is deployed.
> Moves to Circle CI jobs to queue MP update

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginButtonsView.m
- CHANGELOG.yml
https://artsyproduct.atlassian.net/browse/MX-304
Add missing constraint in onboarding causing containing view to collapse and make forgot password and "Go Back" untappable.
> [MX-304] - Add missing constraint in onboarding

- docs/thanks.md
[thanks.md](https://github.com/artsy/eigen/blob/master/docs/thanks.md) is a file where we thank anyone with > 100 commits in Eigen (or Emission) to thank them for the ongoing impact that their work has on the app. Brian, you crossed over this at some point in the last week, so let's get you properly thank'd 😄
> Adds Brian to thanks.md

- src/lib/Scenes/Collection/Collection.tsx
- src/lib/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/ArtistSeriesRail.tsx
Hi Ashley 👋 I've been following your PRs and wanted to say, really great work on the Collections UI! Emission currently uses a few patterns that we're trying to move away from, which have snuck into the Collections work, so I put this PR together to show what we're trying to do instead. All my feedback is open to discussion, too, so please let me know where I can clarify my thinking (or if I got something wrong).
What we're trying to do:
---
Move away from `renderItem()`, `renderSection()`, or `renderThing()` functions. We should put as much of the render logic in the `render()` function as possible. There are a few reasons, but the big one is that TypeScript is a lot less useful when breaking things into smaller, one-off functions. Take a look at the typings first, it's just `any`, which …
> Small Collections refactors

- Artsy Stickers/Info.plist
- Artsy/App_Resources/Artsy-Info.plist
- CHANGELOG.yml
- Ran `make next`
- Moved all unreleased changes from 6.4.2 to  6.4.3
- Add 6.4.2 to releases in changelog with only bug fix
> Preparing for development version 6.4.3 #trivial 

- Artsy.xcodeproj/project.pbxproj
- Artsy/Networking/API_Modules/ArtsyAPI+CurrentUserFunctions.h
- Artsy/Networking/API_Modules/ArtsyAPI+CurrentUserFunctions.m
- Artsy/View_Controllers/Auction/AuctionNetworkModel.swift
- Artsy/View_Controllers/Auction/AuctionUserNetworkModel.swift
- Artsy/View_Controllers/Live_Auctions/LiveAuctionLotSetViewController.swift
- Artsy/Views/Auction/AuctionTitleView.swift
- Artsy/Views/Auction/SaleViewModel.swift
- Artsy_Tests/View_Controller_Tests/Auction/AuctionInformationViewControllerTests.swift
- Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift
- Artsy_Tests/View_Controller_Tests/Auction/RefinementOptionsViewControllerTests.swift
- Artsy_Tests/View_Controller_Tests/Auction/SaleViewModelTests.swift
- Artsy_Tests/View_Controller_Tests/Auction/Views/LotStandingsViewTests.swift
- Artsy_Tests/View_Tests/Auctions/AuctionTitleViewTests.swift
- CHANGELOG.yml
fixes https://artsyproduct.atlassian.net/browse/AUCT-986
We have talked about this a couple times, but the current user object is locally stored in the phone and doesn't get updated unless the user explicitly logs out and back in. As a result of this, the identity verification status stays unchanged even after the user completes the verification. This PR adds another call to `/me` to get fresh data about the user to displays the latest information.
We may want to iterate on the `/me` call in general once we merge this PR, so we could use the up-to-date data everywhere else rather than throwing it away after the sale screen is gone. Let me know what you think.
> Fixes a bug where the "Register To Bid" button displays that IDV is required after begin verified

- src/lib/Components/Consignments/Screens/Overview.tsx
- src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
- src/lib/Components/Consignments/Screens/__tests__/Overview-tests.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-118
This PR updates the consignment submission flow to require at least one photo. In the animated gif below, I demonstrate a submission where everything _but_ a photo is included. The `Submit` button does not become enabled until my second visit into the `Photos` screen, when I select a photo to attach to the submission.
The language on the photo selection screen is updated to make it more clear that photos are required. (Though I made that change _after_ recording the above video 😅 ) 
I also refactored an existing test that covers the `Submit` button disabled state. I split it into several more intentional tests.
> [CSGN-118] Require images for consignment submissions

- src/lib/Scenes/Fair/Screens/FairDetail.tsx
Fairs have two ways they can be missing location. Either:
- `location.coords` is `undefined`, or
- `location` is `undefined`.
The current code crashes in the latter case. This PR should fix it. We've already fixed the issue on the data side, but let's avoid future crashes 👍
> [MX-307] Handles nullability of fair location #trivial

- src/__generated__/ViewingRoomHeaderTestsQuery.graphql.ts
- src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomQuery.graphql.ts
- src/__generated__/ViewingRoomStatementTestsQuery.graphql.ts
- src/__generated__/ViewingRoom_viewingRoom.graphql.ts
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomStatement.tsx
- src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomHeader-tests.tsx
- src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomStatement-tests.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
The purpose of this PR is to refactor `ViewingRoomHeader` to use a fragment container (instead of receiving its props directly from its parent) so that its test can be written with the `ReactTestRenderer` instead of `enzyme`.
> Refactor ViewingRoomHeader to use a fragment container (GALL-2784)

- CHANGELOG.yml
- emission/Pod/Classes/Core/AREmission.m
- index.ios.js
- src/ambient.d.ts
- src/lib/Components/StickyTabPage/StickyTabPage.tsx
- src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
- src/lib/tests/MockRelayRenderer.tsx
- src/lib/utils/AboveTheFoldQueryRenderer.tsx
- src/lib/utils/__tests__/volleyClient-tests.ts
- src/lib/utils/volleyClient.ts
- src/setupJest.ts
- typings/emission.d.ts
First step of https://artsyproduct.atlassian.net/browse/MX-261
This PR just add new metrics tags for the device and network. I also added a global `__TEST__` const so we don't need to use `process.env.NODE_ENV === 'test'` for gating behaviour at test time.
> [MX-261] Add device tags to volley metrics

- src/lib/Scenes/Collection/Collection.tsx
This PR fixes a small bug introduced after #3220 was merged causing the filter button to not appear after scrolling through the collections artwork grid. 
https://artsyproduct.atlassian.net/browse/FX-1909
The bug:
The fix:
> [Minor Bug Fix] Filter button not appearing on Collection Artworks 

- src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx
- src/lib/Components/FilterModal.tsx
- src/lib/Components/__tests__/FilterModal-tests.tsx
- src/lib/Scenes/Collection/Collection.tsx
- src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
This PR fixes the following bugs reported from QA-ing the v2 iOS Collections Filters:
- [Increasing the tappable area for the close and back icons](https://artsyproduct.atlassian.net/browse/FX-1910)
- [Decreasing the viewability config of the artworks grid so the filter button animates sooner](https://artsyproduct.atlassian.net/browse/FX-1911)
> Visual QA Launch Blocker Fixes for v2 Collections Filters

- src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx
- src/lib/Components/FilterModal.tsx
Collections Filters Visual QA Fixes
- Adds a border in the filter modals to indicate separation between list row items and the modal header
- Adds a top border to the apply button to indicate separation between Apply button and list row items 
- Removes "double" border between list row items
- [Increases the tappable area for the close and back icons with hitSlop property](https://artsyproduct.atlassian.net/browse/FX-1910)
#trivial
> Collections Filters Visual QA Fixes

- src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
This bug in the Infinite Scroll Artworks grid on Collections pages was reported:
- user filters artworks in the grid that have fewer than 10 works
- this causes the grid component to enter a state where it no longer fetches artworks from Relay 
(end of pagination reached)
- Attempting to fetch additional artworks after this point fails because the logic indicating if the  component should load more is set to false and the component returns without fetching additional artworks
- The proposed fix is to add an additional check before this return confirming that the artworks connection has no more artworks to fetch. 
https://artsyproduct.atlassian.net/browse/FX-1912
**The Fix:**
**The Bug:**
> Confirm there are no artworks left to render before ending loadMore Relay call

- src/lib/Components/GenericArtistSeriesRail.tsx
- src/lib/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/CollectionArtistSeriesRail.tsx
- src/lib/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/__tests__/CollectionArtistSeriesRail-tests.tsx
- src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
Visual QA Fixes from Artist Series:
- Renders a default image in the artwork grids on Artist Series rails when collections have only 1-2 artworks
- Centers collection header title text
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:** 
https://artsyproduct.atlassian.net/browse/FX-1929
https://artsyproduct.atlassian.net/browse/FX-1928
> Artist Series Rail QA Fixes + Center Collection Header Titles

- Artsy/App/ARAppDelegate+Analytics.m
- CHANGELOG.yml
We were seeing all users come back with "unspecified" possibly because we were overriding the property on the keyWindow, this check appears to work for the system setting.
Worked on in knowledge share with @pvinis @ds300 @mikehrom
> Update interface style check to fix dark mode tracking

- CHANGELOG.yml
- src/lib/Components/ToggleButton.tsx
Adds a generic toggle button for use in the Ways to Buy Collection filter.
Video shows what the new component looks like, but the button is not yet being used in the app.
https://artsyproduct.atlassian.net/browse/FX-1792
> Add Toggle button component

- CHANGELOG.yml
- src/lib/Scenes/Fair/Screens/FairDetail.tsx
Fix for one part of issue Sam reported in slack: 
https://artsy.slack.com/archives/CN8S32FJR/p1588353744112800
> Don't show loading spinner or load next page for inactive fairs

- src/__generated__/ViewingRoomArtworkRailTestsQuery.graphql.ts
- src/__generated__/ViewingRoomArtworkRail_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomArtworksTestsQuery.graphql.ts
- src/__generated__/ViewingRoomQuery.graphql.ts
- src/__generated__/ViewingRoomSubsectionsTestsQuery.graphql.ts
- src/__generated__/ViewingRoomSubsections_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomTestsQuery.graphql.ts
- src/__generated__/ViewingRoom_viewingRoom.graphql.ts
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
- src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomArtworkRail-tests.tsx
- src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomHeader-tests.tsx
- src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomSubsections-tests.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
- src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx
- src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx
This is a continuation of the work to write tests for the new viewing room components, which was started in #3221. That code was merged before its time so that we could merge the newly refactored `ViewingRoomHeader` functional component.
> Add more tests for viewing room components (GALL-2784)

- .circleci/config.yml
- src/lib/Scenes/Home/Home.tsx
While investigating a bug, I found Sentry was missing our source maps. Looks like fastlane is set up to log-but-not-fail when this happens ([example build](https://circleci.com/gh/artsy/eigen/9079)). I re-ran the build with ssh enabled and saw the following:
```sh
Distillers-Mac-6:~ distiller$ cd project/
Distillers-Mac-6:project distiller$ ls emission/Pod/Assets/
Emission.js	assets
```
Running the command locally to bundle showed the following contents:
```sh
~/code/eigen git:(master) ✗ ls emission/Pod/Assets
Emission.js     Emission.js.map assets
```
It took a little looking, but I found that the file extension here was mixed up. Hoping this fixes it 🤞
> Fixes path for JS source map #trivial

- package.json
- src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx
- src/lib/Components/FilterModal.tsx
- src/lib/Scenes/Collection/Collection.tsx
- src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
- src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
- yarn.lock
This PR addresses a bunch of visual QA items from our last session!
The biggest change is the introduction of [`react-native-modal`](https://github.com/react-native-community/react-native-modal).
Reasoning:
- It appears well-maintained.
- It extends react native's default `Modal` implementation and has a super simple API. Should RN decide to add these features into their implementation, it should be easy enough to go back.
- It makes things like "have a background that fades in + a modal sheet that slides up" _incredibly_ easy (it's built in!). If we want to add more facilities, especially as we built out more interactivity in the app, this feels like a good addition.
Cons:
- It's _one more dep_. I was stuck on getting the behavior mentioned ☝️to feel seamless and it definitely felt …
> Addresses various visual QA items from the collections work

- src/lib/Scenes/Consignments/Screens/Overview.tsx
- src/lib/Scenes/Consignments/index.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
- src/setupJest.ts
- typings/emission.d.ts
This stubs out our new app work following some existing Eigen conventions, including Relay expectations: 
```
v2
├── Components
└── Screens
├── ConsignmentsHome
│   ├── Components
│   └── index.tsx
└── ConsignmentsSubmission
└── Components
```
This maps pretty 1:1 to Reaction if one replaces "Screens" with "Routes". 
Also, not sure if `ConsignmentsSubmission` is the best name for the submission flow; this just sets down an example which we can modify. 
#trivial
> [Consignments] Stub v2 folder structure

- CHANGELOG.yml
- src/lib/Components/__tests__/FilterModal-tests.tsx
- src/lib/Scenes/Collection/Collection.tsx
Collections Artworks filters are ready to go out with the next app release. This PR removes the feature flag that had to be enabled in order to interact with the filters.
As we still have filters that in progress/not ready for release, new filter additions will use the `AROptionsFilterCollectionsArtworks` native module, so for now we will keep this flag active, and deprecate completely once the rest of the in-progress and/or upcoming filters don't need to be hidden.
https://artsyproduct.atlassian.net/browse/FX-1942
> Removes Collection Artworks Filters Feature Flag

- src/lib/Components/Countdown/Ticker.tsx
- src/lib/Components/Countdown/__tests__/Ticker-tests.tsx
Completes 🔒 [[AUCT-999]](https://artsyproduct.atlassian.net/browse/AUCT-999)
Paired with @brainbicycle 
This PR updates the react native countdown timer to count number of full days left in the timer using [`Duration.asDays()`](https://momentjs.com/docs/#/durations/days/) - `days()` only returns the number in the current month.
_possible followup: should we ever include the year in the 'timer ends May 6, blah blah blah am EDT' part below the timer? I don't think this is very important since the year would be implied by anything except a multi-year auction - eg if it is november but this sale ends in january, i don't need to know what year, but if it ends in december of the following year that would be relevant._
_by the way: while investigating this I saw a similar bug in the main auction …
> Show number of full days in emission Ticker, not just number of days in month

- .circleci/config.yml
I noticed that https://github.com/artsy/eigen/pull/3282 initially failed because CI expected us to run `yarn relay` before committing - thought it would be simple enough to just always run that step when we pull updated MP schema.
If folks think we should be pickier and only run it when strictly necessary, I'm not sure exactly how we'd do that but would be happy to pair on it!
[CI failure for reference](https://app.circleci.com/pipelines/github/artsy/eigen/1355/workflows/ceed897e-f0d4-443d-bb2a-ae85281a5f15/jobs/9432/steps)
#trivial
> Add yarn relay to MP update steps

- CHANGELOG.yml
- src/__generated__/CollectionsRailTestsQuery.graphql.ts
- src/__generated__/CollectionsRail_collectionsModule.graphql.ts
- src/__generated__/HomeQuery.graphql.ts
- src/__generated__/HomeRefetchQuery.graphql.ts
- src/__generated__/Home_homePage.graphql.ts
- src/lib/Scenes/Home/Components/CollectionsRail.tsx
- src/lib/Scenes/Home/Components/__tests__/CollectionsRail-tests.tsx
- src/lib/Scenes/Home/Home.tsx
This depends on this Metaphysics PR: https://github.com/artsy/metaphysics/pull/2361 ~We'll need to wait for that to merge and for the schema to get updated in Eigen first, but I have included the changes to the generated files in this PR (CI will fail).~
The `CollectionsRail` component is heavily based on the existing `SalesRail`, so I think it makes sense to create an abstraction for these cards. But we can follow-up with that. 
I'm _very_ excited to see such an important screen like collections finally get a well-earned entry point from the home screen of the app 🎉 /cc @ashleyjelks
> [MX-291] Adds collections to home page

- CHANGELOG.yml
- src/lib/Scenes/Home/Home.tsx
This fixes the loader on iPad. I also did some visual cleanup to match the new small tiles from #3271 and forthcoming changes in #3284. Instead of always flowing offscreen, I added an amount of randomness to the horizontal tile rail placeholders to match the content. Here's a side-by-side on both platforms:
| Skeleton | Content |
|---|---|
| ![Simulator Screen Shot - iPhone X - 2020-05-08 at 11 25 50](https://user-images.githubusercontent.com/498212/81421388-6a339300-911f-11ea-85fc-f4149afb4d09.png)  | ![Simulator Screen Shot - iPhone X - 2020-05-08 at 11 23 35](https://user-images.githubusercontent.com/498212/81421410-71f33780-911f-11ea-8770-125265d66ccd.png) |
| ![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-05-08 at 11 25 …
> [MX-308] Fixes Home tab's skeleton loader

- src/lib/Components/Home/ArtistRails/ArtistRail.tsx
- src/lib/Scenes/Home/Components/ArtworkRail.tsx
- src/lib/Scenes/Home/Components/CollectionsRail.tsx
- src/lib/Scenes/Home/Components/FairsRail.tsx
- src/lib/Scenes/Home/Components/SalesRail.tsx
I'm 99% sure we don't want to animate these offset changes, since it draws attention to the user interface when pulling-to-refresh.
But I've left this in its own commit/PR so we can revert it if I'm wrong 👍
> Scrolls rails back to starting position without animation #trivial

- src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
Addresses: [FX-1916](https://artsyproduct.atlassian.net/browse/FX-1916)
This PR adds the border that is missing above the CollectionZeroState #trivial 
**Regular Collection**
**Collection that is a department**
> [FX-1916] add border for collection zero state

- src/__generated__/ArtworkTileRailTestsQuery.graphql.ts
- src/__generated__/ArtworkTileRail_artworksConnection.graphql.ts
- src/__generated__/ViewingRoomArtworkRailTestsQuery.graphql.ts
- src/__generated__/ViewingRoomArtworkRail_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomQuery.graphql.ts
- src/__generated__/ViewingRoomTestsQuery.graphql.ts
- src/lib/Components/ArtworkTileRail.tsx
- src/lib/Components/__tests__/ArtworkTileRail-tests.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
- src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomArtworkRail-tests.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
This PR adds artist name and price to the rail in viewing rooms. The code is mostly copy/pasted from `SmallTileRail`, with a few tweaks to make it work with this flatlist.
@ashfurrow I'd love your perspective on the copy/paste-ness of this since I believe it was you who worked on implementing the home rail version. My thinking is that I would ideally like every place we use the same rail to rely on the same component so we don't get out of sync. However, I feel like that gets tricky when the Relay fragments are slightly different for each one, unless we're comfortable passing a bunch of stuff as props.
One thought I had was around making the `ArtworkCard` an all-purpose component that could be reused by both rails as a step in that direction.
What do you think? 
#trivial
> Update Viewing Rooms artwork rail

- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/ArtistList.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-185
This PR updates the static layout for the artist list on the new sell tab's landing page to:
* use react-native/eigen concepts like `FlatList` for virtualization and `TouchableHighlight` for user feedback
* extract components for displaying lists of data
* display data in the same shape as what will come from MP/relay.
My next step will be to connect the component to MP via relay, and with these changes I think that should be almost all "plumbing" work.
#trivial #skip_new_tests (I anticipate including tests & changelog entry when this component gets closer to shippable.)
> Refine static layout of sell tab's artist list

- CHANGELOG.yml
- src/lib/Scenes/Fair/Components/FairBoothHeader.tsx
This fixes a bug that was causing fair booths not to load when a partner profile was empty.
Reported in slack: https://artsy.slack.com/archives/CN8S32FJR/p1589375619280400
Co-authored with @ashfurrow
> Fix for fair booth display with null profile

- .circleci/config.yml
Reverts artsy/eigen#3285
I believe #3285 tried to fix an issue with the automated process we have for updating the schema file in the eigen repo after changes are made to MP. But the area of code changed in that PR actually deals with updates which go in the opposite direction, i.e. changes in the eigen query map being pushed to MP.
In addition, the change in #3285 was a no-op since `yarn relay` was added _after_ the step which actually pushes the query map changes.
The problem that #3285 was intended to address is that sometimes schema changes can affect the files in the `__generated__` folder, but we have a CI check which fails when the `__generated__` folder is out-of-date. So the CI script which pushes schema changes *from MP to eigen* was creating a pull request where the schema file …
> Revert "Add yarn relay to MP update steps"

- Artsy/App/ARSwitchBoard.m
- emission/Pod/Classes/ViewControllers/ARNewSubmissionFormComponentViewController.h
- emission/Pod/Classes/ViewControllers/ARNewSubmissionFormComponentViewController.m
- src/lib/AppRegistry.tsx
- src/lib/Scenes/Consignments/index.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
- src/lib/Scenes/MyCollection/NewSubmissionForm/NewSubmissionForm.tsx
- src/lib/Scenes/MyCollection/NewSubmissionForm/index.tsx
This PR wires up the existing consign flow to the new landing page. I think it's compatible with what you're working on @pepopowitz but lmk if things have diverged enough that we need to look at this again!
Update: turned out that it was not compatible but we figured it out - see the use of `useRef` and `SwitchBoard.presentModalViewController`. 👍 
> Wire up existing form to new landing

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARSwitchBoard.m
- Artsy/View_Controllers/AREigenViewingRoomComponentViewController.h
- Artsy/View_Controllers/AREigenViewingRoomComponentViewController.m
- CHANGELOG.yml
- emission/Pod/Classes/ViewControllers/ARViewingRoomComponentViewController.h
- emission/Pod/Classes/ViewControllers/ARViewingRoomComponentViewController.m
- src/__generated__/ViewingRoomHeaderTestsQuery.graphql.ts
- src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomQuery.graphql.ts
- src/__generated__/ViewingRoomTestsQuery.graphql.ts
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomHeader-tests.tsx
This PR adds the partner name and logo to the VR header and makes the header full bleed, AKA it extends into the "horns" that iPhone X and later have.
[Jira ticket](https://artsyproduct.atlassian.net/browse/GALL-2845)
> Viewing rooms header updates [GALL-2845]

- CHANGELOG.yml
- src/lib/Components/ArtworkTileRail/ArtworkTileRail-tests.tsx
- src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx
- src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
- src/lib/Components/ArtworkTileRail/__tests__/ArtworkTileRail-tests.tsx
- src/lib/Components/ArtworkTileRail/__tests__/ArtworkTileRailCard-tests.tsx
- src/lib/Components/ArtworkTileRail/index.ts
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
- src/lib/Scenes/Home/Components/SmallTileRail.tsx
I will be rendering an artwork rail on the sell tab landing page, and I want it to look like the other artwork rails in the app. The shape of my data is very different from what `ArtworkTileRail` uses, though, so this PR extracts an `ArtworkTileRailCard` that takes things like `artistNames` and `saleMessage` as props. This leaves it up to the parent component to decide how to get those bits of data.
I chose to do this at the card level instead of the rail level because there might be subtle differences between my upcoming rail and the other rails, specifically in the spacing between cards. Perhaps it's confirmation bias, but it also feels nice that the parent can decide if it's rendering a `FlatList`, an `AboveTheFoldFlatList`, or a `Join` to render this rail of cards.
The PR also …
> Extract ArtworkTileRailCard for reuse with other shapes of data

- CHANGELOG.yml
- src/__generated__/PartnerQuery.graphql.ts
- src/__generated__/PartnerRefetchQuery.graphql.ts
- src/__generated__/PartnerShowsInfiniteScrollGridQuery.graphql.ts
- src/__generated__/PartnerShowsTestsQuery.graphql.ts
- src/__generated__/PartnerShows_partner.graphql.ts
- src/lib/Scenes/Partner/Components/PartnerShows.tsx
- src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
This PR moves us from a static "test-viewing-room-id" slug to dynamic navigation.
For example, you can now open artsy:///viewing-room/david-zwirner-private-party-selected-works-by-nicolas-party in a simulator Safari and be taken to a VR. This PR also lays the groundwork for displaying VRs on the partner screen (which may or may not be used for a while since we're unclear how we're gating access to/from rooms). Still, should be handy for testing since you can go to a gallery page and tap through to a VR, assuming you have the feature flag.
@starsirius while working on this, I discovered that querying any partner for `vieiwngRooms` returns ALL viewing rooms in existence, regardless of whether or not they're associated with that particular partner. I'm wondering if you might have some …
> Make viewing rooms dynamic [GALL-2794]

- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-200
In the name of shipping smaller slices iteratively, this PR removes the "Recently sold on Artsy" section of the Sell Tab landing page.
We'll add it back in a future PR.
#trivial
> Remove recently sold section from Sell Tab landing page

- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-189
Adds a proper placeholder screen for the Sell Tab landing page.
Static content remains static, and only the dynamic pieces are grayed out. Here's what it looks like - note the very bottom, where the "Artists collectors are looking to buy" section fills in:
To give a better idea of what that artist list would look like if it were to, say, move up the page some day, here's how that artist section loads when you can see it completely:
There is a slight difference in heights that causes the section below it to jump a couple pixels...I was unable to figure out what was causing that difference. I don't personally think it's a big deal because no one really sees the bottom of the artist section when the full view is loading, but let me …
> [CSGN-189] Placeholder for Sell Tab landing page

- CHANGELOG.yml
- Podfile
- Podfile.lock
- package.json
- src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
- yarn.lock
Included in this PR:
- A new dependency, [react-native-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient). Styled components [doesn't support gradients](https://github.com/styled-components/styled-components/issues/1170) and doesn't plan to, so seemed like the best way to achieve one
- Artwork rail on viewing rooms now extends all the way to the edge of the screen
- Countdown clock now says "closes" and is properly vertically aligned
> Add react-native-linear-gradient + viewing rooms tweaks

- src/lib/Components/Artist/ArtistArtworks/index.tsx
- src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx
- src/lib/Containers/Gene.tsx
- src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
- src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
- src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx
This PR is in response to a bug that was introduced in https://github.com/artsy/eigen/pull/3249 which caused us to send _many_ concurrent requests for data on each refetch. I believe it's because the `! hasMoreWorksToFetch &&`  conditional meant that we would _always_ fetch for more if we could (instead we need to also verify that we're not in the middle of loading).
This component is pretty old and used to do its own management of loading + completed state. I updated this to fully embrace relay's `isLoading` and `hasMore` which both fixes the current bug and the one that the original PR was aiming to fix.
> Use relay's hasMore and isLoading for more robust pagination on infinite scroll grid

- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Completes https://artsyproduct.atlassian.net/browse/CSGN-203 
Using the new PaymentIcon from palette, the page now looks like this:
#trivial
> [CSGN-203] Replace icon for Receive Payment section of sell tab landing page

- CHANGELOG.yml
- src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
`OpaqueImageView` was logging a warning in one recently-added instance (`ArtworkTileRailCard`).  It was being supplied with dimensions props in a valid way, but the conditional logic for the warning wasn't nuanced enough to allow it.
I also fixed the prop type definitions and removed strictness migration issues.
> Fix OpaqueImageView

- CHANGELOG.yml
- src/__generated__/ViewingRoomArtworksQuery.graphql.ts
- src/__generated__/ViewingRoomArtworksRendererQuery.graphql.ts
- src/__generated__/ViewingRoomArtworksTestsQuery.graphql.ts
- src/__generated__/ViewingRoomArtworks_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomQuery.graphql.ts
- src/__generated__/ViewingRoomTestsQuery.graphql.ts
- src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
- src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx
Missed this in the spec till now! This PR grabs the artwork description if one exists and puts it below the artwork in the list view.
> Add artwork description to Viewing Room artworks view

- CHANGELOG.yml
- src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
- src/lib/Containers/Artist.tsx
- src/lib/Containers/__tests__/Artist-tests.tsx
- src/lib/Icons/SearchIcon.tsx
- src/lib/Scenes/Search/AutosuggestResults.tsx
- src/lib/Scenes/Search/CityGuideCTA.tsx
- src/lib/Scenes/Search/Input.tsx
- src/lib/Scenes/Search/RecentSearches.tsx
- src/lib/Scenes/Search/Search.tsx
- src/lib/Scenes/Search/SearchContext.tsx
- src/lib/Scenes/Search/SearchResult.tsx
- src/lib/Scenes/Search/SearchResultList.tsx
- src/lib/Scenes/Search/__tests__/CityGuideCTA-tests.tsx
- src/lib/Scenes/Search/__tests__/Search-tests.tsx
- src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx
https://artsyproduct.atlassian.net/browse/MX-326
spec: https://www.figma.com/file/2Im0qW2WpwQj2BowaFypxG/Explore?node-id=322%3A1143
1. Make sure the city guide call-to-action is visible when there are recent searches
2. Updated the 'Recent Searches' title copy to match the spec.
3. Updated the search page typography to match the spec (serif -> sans)
3. Fix an aspect ratio bug in OpaqueImageView which I introduced yesterday 😬 
4. Fix a crash that happened when artist pages have no tabs (data folks say this shouldn't happen but it does, see, e.g. Jillian Banks) – I used the empty state copy from the web.
5. Strictness migration cleanup
> [MX-326] Fix Explore unfocused states

- src/lib/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tsx
UI Bug Fix where the Iconic Collections rail wasn't doing a full bleed across the screen:
https://artsyproduct.atlassian.net/browse/FX-1975
#trivial
> enable full bleed on artist series rail

- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/__tests__/RecentlySold-tests.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-205
Artworks in our recently sold rail may or may not have a realized price. This PR protects against artworks that don't, by suppressing the "Sold for" message if there is no `realizedPrice` property.
> Don't show 'sold for' message if no realized price

- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/ArtistList.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-212
We incorrectly had permanent padding on the rails on the consignment landing page (Recently Sold & Artist List). This PR updates both rails so that they appear left-padded when the screen loads, but on swipe they bleed fully to the left and right edges.
It also updates the associated placeholders..which technically didn't _need_ to happen, but I think making similar changes there removes the likelihood of divergence between placeholders and what they represent.
> [CSGN-212] Make consignment landing page rails full-bleed on swipe

- src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
react-native throws a full-on Error when you pass a string as children to a component which is not  wrapped by a `Text` component.
We got some mysterious sentry reports about this happening on the Home tab in the latest release and after digging through the changes to all components on the home tab I'm 90% sure this is the culprit.
Trivial change so I'll self-merge, but it's good to be aware that this `blah && <Blah />` pattern is very unsafe in react-native when the thing on the left is a string or a number. It's necessary to use `blah ?? <Blah />` if you're not concerned about falsey values (`""` and `0`) or `blah ? <Blah /> : null` if you are.
> Fix no-text-outside-Text issue

- metro.config.js
#trivial config change so going to self-merge and monitor
> Use maxWorkers: 0 on CI to prevent OOMs during bundle on CI

- src/lib/Components/Artist/ArtistConsignButton.tsx
- src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-210.
When we built out the new sell tab, we forgot that tapping the "consign with Artsy" button on an artist page would direct the user to the new landing page. It wasn't so much a problem that we were sending them there...but they were sent to the landing page in the context of a modal without a mechanism for closing or going back. They were dead-ended, and the only way to escape was to restart the app.
This is what it looked like:
This PR updates the destination of that button to be the new sell tab (if the feature flag is enabled). 
This works really well when they tap an artist consign button while browsing within the home or search tabs of the app:
It is a little less great when they tap an artist consign button while browsing …
> Send users to the new sell tab when they tap on the artist consign CTA

- CHANGELOG.yml
- src/lib/Scenes/Home/Components/SalesRail.tsx
- src/lib/Scenes/Home/Components/__tests__/SalesRail-tests.tsx
Re: [MX-320](https://artsyproduct.atlassian.net/browse/MX-320)
> If 1 work, repeat the 1 work in all tiles. 
> If 2 works, repeat 2nd work.
> [MX-320] handles image fallbacks on SalesRail

- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/Footer.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/Header.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/__tests__/index-tests.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-227
We were sending inaccurate subjects for the consignment header/footer CTA buttons. This PR updates the subjects to be accurate.
#trivial
> Update analytics subject for consignment CTA buttons

- CHANGELOG.yml
- src/lib/Scenes/Home/Components/EmailConfirmationBanner.tsx
- src/lib/Scenes/Home/Components/__tests__/EmailConfirmationBanner-tests.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-1072
Just fixing a typo in the email confirmation sash and adding a CHANGELOG entry.
> Fix a typo in the email confirmation sash

- scripts/strictness-migration.js
There's a kind of race condition which can cause false positives with the strictness check:
1. you make a PR which doesn't increase the strictness issue count
2. someone else merges a PR which decreases the strictness issue count
3. you update your PR so CI runs again
4. CI fails because your branch has more strictness issues than master
So in this PR I make the script try to merge master in before running to get an accurate notion of how your PR affects strictness issue counts.
#trivial infra change so gonna self-merge.
> Prevent false positives in strictness migration check

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.h
- Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
- emission/Pod/Classes/Core/AREmission.h
- emission/Pod/Classes/Core/AREmission.m
- emission/Pod/Classes/Core/ARTopMenuModule.h
- emission/Pod/Classes/Core/ARTopMenuModule.m
- src/lib/NativeModules/TopMenu.tsx
In #3389, I demonstrated a proof of concept on how I'd go about identifying the currently selected tab name from a React component. This PR cleans up that implementation, and is limited to setting up the bridge.
A followup PR will take advantage of this new bridge function to modify user flow within the sell tab landing page.
> Add a bridge to identify the currently selected tab name

- Artsy/App/ARSwitchBoard.m
- emission/Pod/Classes/ViewControllers/ARSellTabLandingViewController.h
- emission/Pod/Classes/ViewControllers/ARSellTabLandingViewController.m
- src/lib/AppRegistry.tsx
- src/lib/Components/Artist/ArtistConsignButton.tsx
- src/lib/NativeModules/TopMenu.tsx
- src/lib/Scenes/Consignments/SellTabLanding.tsx
This work depends on #3400. The only commits in this diff that are related to this PR are the last two.
Addresses https://artsyproduct.atlassian.net/browse/CSGN-225
This PR uses your currently selected tab to determine where to send you when you tap the artist consign button. 
For users who are on the home or search tab (or anywhere that isn't sell), we'll continue to send them to the sell tab landing page:
If you're already in the sell tab, we push another landing page view onto your nav stack. This addresses the experience of tapping on something and not getting enough feedback about where you're going:
#trivial (but not really; it's just covered by another entry that's already in the changelog.)
> [CSGN-225] Choose the destination of artist consign taps based on your active tab

- Artsy/View_Controllers/ARSerifNavigationViewController.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
https://artsyproduct.atlassian.net/browse/MX-189
- Fixes pointy corner of modals in auctions flows
- Makes live auctions views presentation full screen on iPad + iOS 13
While we were working on the pointy corner Damon noticed that the LiveAuctions VC was not being presented correctly on iPad, this is due to the new card presentation style for modals in iOS 13. Fix is to add an exception for this view controller in our presentation code. There may be more layout issues associated with our native modals on iOS 13 that might be worth looking into. 
**Co-authored with @dzucconi** 
**Before**
**After**
> [MX-189] - Fix for auctions pointy modal corner and non-fullscreen display

- src/lib/Scenes/Consignments/Screens/Confirmation.tsx
- src/lib/Scenes/Consignments/Screens/__tests__/Confirmation-tests.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-172
This PR updates the content of the consignment submission confirmation, and makes some related small changes to the consignment submission failure.
Tapping "Done" will close the modal; tapping "Browse new works for sale" will close the modal and take you to the home tab.
> [CSGN-172] Update content of consignment submission confirmation

- .circleci/config.yml
We created the deploy block test here: https://releases.artsy.net/admin/deploy_blocks/83 This will block beta deploys for us in a way that is familiar to the rest of Artsy Engineering and will make creating a manual deploy easier (ie: no more asking "is it okay to make a beta?", you can just try to make it and if there is no block it will work).
> Adds deploy block check to beta builds

- Artsy/View_Controllers/ARSerifNavigationViewController.m
- src/lib/Components/Bidding/Components/BackButton.tsx
Fix for back button layout issue in auction registration components that came up in QA session
. I am not crazy about the fix just being updating magic constants but this is complicated a bit by the fact that the close button is added on the native side and the back button is added on the react side and the buttons need to be aligned. I think the better fix would be to have the react side create and manage both buttons but this is a bigger change. Not totally clear on why the `theme.space[3]` broke, possibly palette updates? 
**iPhone**
**iPhone**
**iPad**
> Fix auction registration back button layout issue

- CHANGELOG.yml
- src/lib/Scenes/Consignments/Screens/Confirmation.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/ArtistList.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-232
The horizontal scrollbar was appearing over the bottom artists on the sell tab artist list. This PR removes the horizontal scrollbar from that rail entirely. 
It now looks like this: 
Also included is a small change to some content on the "submission failed" view.
> [CSGN-232] Remove horizontal scrollbar from sell tab artist list & update "submission failed" content

- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
Addresses https://artsyproduct.atlassian.net/browse/CSGN-233
This PR adds the sales tab to the list of tabs that should scroll to top when the user is already on the tab and taps its icon.
> [CSGN-233] Scroll sales tab to top when already on sales tab and icon is tapped

- Artsy/App/ARSwitchBoard.m
- emission/Pod/Classes/ViewControllers/ARMyCollectionAddArtworkComponentViewController.h
- emission/Pod/Classes/ViewControllers/ARMyCollectionAddArtworkComponentViewController.m
- emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.h
- emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.m
- emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkListComponentViewController.h
- emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkListComponentViewController.m
- emission/Pod/Classes/ViewControllers/ARMyCollectionHomeComponentViewController.h
- emission/Pod/Classes/ViewControllers/ARMyCollectionHomeComponentViewController.m
- src/lib/AppRegistry.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/index.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/index.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionHome/index.tsx
- src/lib/Scenes/Consignments/v2/State/navigationState.ts
- src/lib/Scenes/Consignments/v2/State/store.tsx
This gets us to a place where we can start building out static views by sketching in the bones of our navigation flow. Things **will** change. 
The flow: 
- Created primitive view controllers and routes for each view: `add-artwork`, `artwork-details`, `artwork-list`, `home`. These routes are basically placeholder stubs and aren't dynamic at all (we're not yet ready to start that phase) 
- Started establishing nav patterns for moving between various sections. (See [flow diagram here](https://www.figma.com/file/yDSHlbJVzBxvSUROD2bfRI/Sell-tab?node-id=1308%3A0). 
- Right now i'm just pushing view controllers so that we can easily move between sections / dismiss while we build out designs. In the future this will change. 
- In the future we'll be needing to check various conditions before …
> [My Collection] Stub out skeleton nav flow 

- src/__generated__/ViewingRoomsListQuery.graphql.ts
- src/__generated__/ViewingRoomsListTestsQuery.graphql.ts
- src/__generated__/ViewingRoomsList_viewingRooms.graphql.ts
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
- src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomsList-tests.tsx
- src/lib/utils/track/schema.ts
Quick lil PR to set us up for navigating to VRs from the list. Included:
- Tapping a VR takes you to the VR
- Only show "scheduled" and "live" VRs on the viewing-rooms page
- Bugfix for VR page (crashed w/o pull quote)
- Basic test for VR list
[Jira ticket](https://artsyproduct.atlassian.net/browse/GALL-2936)
> Link listed VRs into navigation [GALL-2936]

- CHANGELOG.yml
- src/lib/Scenes/Consignments/v2/SellTabApp.tsx
- src/lib/utils/track/schema.ts
Addresses https://artsyproduct.atlassian.net/browse/CSGN-244, at least temporarily.
We know that the screenview only fires the first time the tab is visited. We're adding a ticket to work with MX to figure out how to get it to happen more frequently, so that we can prioritize that work accordingly.
> Track a screenview on the Sell Tab

- fastlane/Fastfile
So what we _were_ trying to do before is figure out which git tag was created by the beta which we were trying to submit to App Store Review. The thinking was that we could "target" this tag so that both the beta deploy tag _and_ the App Store Review promotion tag would point to the same commit.
This turns out to be difficult because most months and many days begin with 0, and different tools treat that leading zero differently. AppStoreConnect, for example, turns something like `6.4.8-2020.06.19.06` into `6.4.8-2020.6.19.6`. This makes it difficult to figure out what the beta deploy tag is.
I've tried for a while to get this to work but the constant CI failures cause a lot of noise. So this PR "fixes the glitch" by not trying to target the commits anymore. The commit of the submission …
> [MX-340] Fixes promotion script #trivial

- .circleci/config.yml
https://circleci.com/gh/artsy/eigen/12526
Build failed with new job to check for new developer agreements due to bundler not being on the machine, this changes to use macOS vm as other jobs do. Might be a bit heavy handed, open to suggestions. 
#trivial
> Update image for nightly job to use macOS #trivial

- CHANGELOG.yml
- src/lib/Components/ArtworkFilterOptions/ColorOptions.tsx
- src/lib/Components/ArtworkFilterOptions/GalleryOptions.tsx
- src/lib/Components/ArtworkFilterOptions/InstitutionOptions.tsx
- src/lib/Components/ArtworkFilterOptions/MediumOptions.tsx
- src/lib/Components/ArtworkFilterOptions/MultiSelectOption.tsx
- src/lib/Components/ArtworkFilterOptions/PriceRangeOptions.tsx
- src/lib/Components/ArtworkFilterOptions/SizeOptions.tsx
- src/lib/Components/ArtworkFilterOptions/SortOptions.tsx
- src/lib/Components/ArtworkFilterOptions/TimePeriodOptions.tsx
- src/lib/Components/ArtworkFilterOptions/WaysToBuyOptions.tsx
- src/lib/Components/FilterModal.tsx
- src/lib/Scenes/Collection/Helpers/FilterArtworksHelpers.ts
- src/lib/utils/ArtworkFiltersStore.tsx
Fixes for a few bugs found in QA for artwork filters.
- Ways to buy filters were not allowing second selection because the filter object was being modified rather than passing new value, causing filter context to think nothing changed
-  "All" options in some filters didn't match default param values
- Layout and copy issue fixes
> [MX-289] - Artwork filters QA 

- Artsy/App/ARSwitchBoard.m
- emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.h
- emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.m
- src/lib/AppRegistry.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/ArtworkMeta.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/AuctionResults.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/ConsignCTA.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/Field.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/Insights.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/MyCollectionArtworkDetail.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/MyCollectionArtworkList.tsx
- src/lib/Scenes/Consignments/v2/Screens/MyCollectionHome/MyCollectionHome.tsx
- src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-268
This PR adds some fake "real" data to drive the artwork detail page of My Collection. 
Some components are extracted where it seems easy to predict fragment container boundaries, but at this point that's a lot of guessing. In some cases I didn't bother to drive the components from "real" data because it seems unlikely we'll have real data for them soon. This gets us _closer_ to a place where we just need to hook up metaphysics, but not all the way there.
#trivial #skip_new_tests (but really this is work in progress that is hidden behind a lab flag)
> [CSGN-268] Drive collection artwork detail with data

- CHANGELOG.yml
- src/lib/Scenes/Favorites/Components/Artists/index.tsx
- src/lib/Scenes/Favorites/Components/Artworks/index.tsx
- src/lib/Scenes/Favorites/Components/Categories/index.tsx
- src/lib/Scenes/Favorites/Components/Fairs/index.tsx
- src/lib/Scenes/Favorites/Components/Shows/index.tsx
This was done by wrapping the `ZeroState` component in a scrollview, modifying the scroll view's content to stretch full screen, and adding the same refresh control.
> [MX-251] Adds pull-to-refresh control on empty states of Favourites view

- CHANGELOG.yml
- src/__generated__/PartnerQuery.graphql.ts
- src/__generated__/PartnerRefetchQuery.graphql.ts
- src/__generated__/PartnerShowRailItem_show.graphql.ts
- src/__generated__/PartnerShowsInfiniteScrollGridQuery.graphql.ts
- src/__generated__/PartnerShowsRailQuery.graphql.ts
- src/__generated__/PartnerShowsTestsQuery.graphql.ts
- src/lib/Scenes/Partner/Components/PartnerShowRailItem.tsx
- src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
- src/lib/Scenes/Sales/Components/ZeroState/index.tsx
Our colleagues have requested a few tweaks to the app. First, the empty state for the sales list should say "there are" instead of "there's no"; second, partner shows should show the cover image instead of using the first image of the show (if a cover image is specified). /cc @coolyoungdad
> Requested tweaks #trivial

- tsconfig.json
Enables typescript check to return errors when non-empty switch cases fallthrough: 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-8.html#case-clause-fall-throughs
#trivial
> Enable noFallThroughCasesInSwitch typescript check #trivial

- CHANGELOG.yml
- src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/lib/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tsx
- src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
- src/lib/Scenes/Collection/Collection.tsx
https://artsyproduct.atlassian.net/browse/MX-434
This hides the filter button on the artist artworks page until the artist artwork are visible, it is pretty close to the implementation in the collections component: https://github.com/artsy/eigen/blob/master/src/lib/Scenes/Collection/Collection.tsx#L59
- Adds a flatlist to contain the artist artworks and rails in section
- Adds callbacks for viewableItems changed and displays filter button when filtered artworks section is visible
> [MX-434] - Filter button visibility

- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- CHANGELOG.yml
- src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
- src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
- src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
- src/__generated__/ArtistSeriesHeaderTestsQuery.graphql.ts
- src/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
- src/__generated__/ArtistSeriesMetaFollowMutation.graphql.ts
- src/__generated__/ArtistSeriesMetaTestsQuery.graphql.ts
- src/__generated__/ArtistSeriesMeta_artistSeries.graphql.ts
- src/__generated__/ArtistSeriesQuery.graphql.ts
- src/__generated__/ArtistSeriesTestsQuery.graphql.ts
- src/__generated__/ArtistSeries_artistSeries.graphql.ts
- src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesHeader.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesArtworks-tests.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesHeader-tests.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesMeta-tests.tsx
This PR resolves: [FX-2010](https://artsyproduct.atlassian.net/browse/FX-2010) and [FX-2050](https://artsyproduct.atlassian.net/browse/FX-2050)
Implements an infinite scroll artwork grid on the Artist Series view.  In order to implement this feature I had to refactor the Artist Series "home page" to use a `Flatlist`.  This refactor involved breaking out the existing components into separate files (including test files). I also added a header image url to the Artist Series Header, which takes care of  [FX-2050](https://artsyproduct.atlassian.net/browse/FX-2050).
@ashleyjelks  and @nicoleyeo will QA the new changes in a beta.
> [FX-2010] Add artworks to Artist Series

- src/lib/Scenes/Feature/Feature.tsx
- src/lib/Scenes/Feature/components/FeatureFeaturedLink.tsx
This resolves design feedback given on [MX-140] https://artsyproduct.atlassian.net/browse/MX-410
- Give the link images a margin, rather than having them be full bleed
- Give images 3:4 aspect ratio
#trivial
[MX-140]: https://artsyproduct.atlassian.net/browse/MX-140
> Feature page QA fixes

- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
Here's the bug:
- Open the app. It shows the home tab.
- Without tapping into another tab, tap the home tab icon.
What happens is we see a blank screen, and the other tabs are unresponsive. 
The cause of the bug is that the `currentTab` property isn't initially set to anything, leading the comparison to check if the user has selected the  current tab to fail (comparison to `nil`). If the user selects another tab, then the bug doesn't appear (the `currentTab` property has been set).
I also fixed a stylistic Objective-C issue with a `==` versus `isEqual:`. `==` is a pointer comparison, but happens to succeed because Objective-C string literals are hoisted into static memory, so every Objective-C `@"home"` string literal _is_ the identical `NSString` …
> Fixes problem selecting home tab initially

- Artsy.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- package.json
- patches/react-native-image-crop-picker+0.32.2.patch
- yarn.lock
The type of this PR is: **dependency**
See: https://github.com/artsy/eigen/issues/3473
The Objective-C code had a bug specific to our app setup, so I had to patch it. I've [submitted a PR](https://github.com/ivpusic/react-native-image-crop-picker/pull/1354) to address it for others, too. Prettier mangled the Podfile, too 😭 
<details>
<summary>GIF proof of concept</summary>
</details>
> Adds react-native-image-crop-picker

- src/lib/Components/AnimatedBottomButton.tsx
- src/lib/Components/FilterModal.tsx
- src/lib/Scenes/Collection/__tests__/Collection-tests.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
- src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx
I extracted the animated part of `AnimatedArtworkFilterButton` into `AnimatedBottomButton`. This way we can reuse it easily. In the PR I also am adding it in the VR page, so we are consistent. :)
> generalize and use in vr #trivial

- src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
Tiny change, but in VR list, when there is no hero image, the app would crash. now its just showing an empty square, as it should. Normally we wouldn't allow no hero image on cms and we would not return it from MP, but for now since we are still building the verifications, ill just add this here.
- Go to VR list page.
- Your app didn't crash.
> dont crash if no image. just show an empty one. #trivial

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARAppDelegate.h
- Artsy/App/ARAppDelegate.m
- Artsy/App/ARAppNotificationsDelegate.m
- CHANGELOG.yml
- Podfile
- Podfile.lock
The type of this PR is: **dependency**
This PR resolves **[MX-467]**
This adds the Sailthru SDK. I looked through their headers to make sure we were using them correctly. Docs are fine but code talks. The new SDK key is in the usual place in 1P.
Fixes #3632. 
See [MX-469].
[MX-467]: https://artsyproduct.atlassian.net/browse/MX-467
[MX-469]: https://artsyproduct.atlassian.net/browse/MX-469
> [MX-467] Integrates Sailthru SDK

- Artsy/View_Controllers/Auction/AuctionViewController.swift
- CHANGELOG.yml
This PR resolves **[MX-475]**
This adds a Segment analytics event when the network calls necessary to render the current Auction view are completed. This is a good approximation of time-to-interactive.
Get @mikehrom to look at the event and give a 👍 on the naming: `sale_screen_load_complete` with a property of `load_time_ms`.
Then I'll assign it to an engineer to review the code
Original: 
Update: 
[MX-475]: https://artsyproduct.atlassian.net/browse/MX-475
> Starts tracking auction page load time

- Artsy/App/ARSailthruIntegration.m
Sailthru's SDK crashes in some circumstances. This PR guards against them.
Here is the stack trace of the crash, in case someone finds this through Google:
<details>
<summary>Crash stacktrace</summary>
```
2020-07-29 16:11:17.485 [fatal][tid:com.facebook.react.AREventsModuleQueue] Exception 'Attempt to insert non-property list object (
{
date = 1596053477;
name = "Screen view";
origin = session;
vars =         {
"context_screen_owner_type" = "<null>";
screen = Home;
};
}
) for key com.corepush.customevents' was thrown while invoking postEvent on target AREventsModule with params (
{
"context_screen" = Home;
"context_screen_owner_type" = "<null>";
}
)
callstack: (
0   CoreFoundation                      0x00000001150868db __exceptionPreprocess + 331
1 …
```
> Fixes Sailthru SDK crash #trivial

- src/__generated__/ViewingRoomArtworkQuery.graphql.ts
- src/__generated__/ViewingRoomArtwork_selectedArtwork.graphql.ts
- src/__generated__/ViewingRoomsHomeRailQuery.graphql.ts
- src/__generated__/ViewingRoomsHomeRail_regular.graphql.ts
- src/lib/Components/Countdown/Ticker.tsx
- src/lib/Components/Countdown/index.ts
- src/lib/Scenes/Home/Home.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
The type of this PR is: **Bugfix/Enhancement**
A few things in here again:
- Copy changes, using the new font and removing the Serif one from VR related things.
- If there are no featured VRs, we hide that section in the VR landing page.
- If there are no featured VRs, we show the regular VRs in home.
- Fixed tag color.
- Show description in artwork page, it was hiding in `additionalInformation`.
I'll add #trivial and #skip_new_tests for the new component. It's a funky component that shows the featured rail or if its empty then does a new query to get the regular VRs.
https://f.p0l.co/file/dropshare-public-pavlos/Screen-Recording-2020-07-30-at-20.13.00.mov
I'm guessing we will always/usually have featured VRs so it would be fine to do another request? I felt it was too much to fetch these …
> Qa fixes 3

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/App/ARSwitchBoard.m
- CHANGELOG.yml
- src/lib/AppRegistry.tsx
- src/lib/Scenes/MyBids/index.tsx
- src/lib/Scenes/MyProfile/MyProfile.tsx
- src/setupJest.ts
- typings/emission.d.ts
Addresses https://artsyproduct.atlassian.net/browse/AUCT-1158
This is the first basic implementation of the new My Bids screen. The data shown is all static as we are still working on the backend to expose the necessary GraphQL queries/fields, but you should be able to see what it looks like and it should allow us to iterate on the frontend without having to wait until the backend work is done.
The "Enable Bid Management" feature flag needs to be on to have the My Bids row show up on the My Profile screen:
And the actual UX:
> Add basic and static My Bids screen

- .gitignore
- Artsy/App/ARSwitchBoard.m
- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- src/__generated__/ArtistSeriesMoreSeriesTestsQuery.graphql.ts
- src/__generated__/ArtistSeriesMoreSeries_artist.graphql.ts
- src/__generated__/ArtistSeriesQuery.graphql.ts
- src/__generated__/ArtistSeriesTestsQuery.graphql.ts
- src/__generated__/ArtistSeries_artistSeries.graphql.ts
- src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesMoreSeries-tests.tsx
This PR resolves [**[FX-2015]**](https://artsyproduct.atlassian.net/browse/FX-2015)
- Adds `ArtistSeriesMoreSeries` component that shows additional artist series by the artist on the artist series view. This also involves updating the view controller to be able to navigate to a different artist series.
- Lightly refactors tests for `ArtistSeries` to remove duplicated tests and account for a new case
- Adds `.swiftpm` to `.gitignore`
**Edge cases**
- If there is no artist associated with the artist series, `ArtistSeriesMoreArtist` is not rendered.
- If there are no other artist series the child components of `ArtistSeriesMoreSeries` are not rendered.
**Followup work**
- [User does not see the current artist series when looking at a list of related artist …
> Add ArtistSeriesMoreSeries component

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginFieldsView.m
- CHANGELOG.yml
This PR resolves **[MX-356]**
Moves the show/hide button outside the password textfield on login and create password screens to avoid overlap with the clear button.
[MX-356]: https://artsyproduct.atlassian.net/browse/MX-356
> [MX-356] - Move show/hide button outside text field to avoid clear overlap #trivial

- src/lib/Scenes/Artwork/Components/AboutArtist.tsx
- src/lib/Scenes/Artwork/Components/AboutWork.tsx
- src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
- src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx
- src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
- src/lib/Scenes/Artwork/Components/OtherWorks/Header.tsx
- src/lib/Scenes/Artwork/Components/OtherWorks/__tests__/Header-tests.tsx
- src/lib/Scenes/Artwork/Components/PartnerCard.tsx
- src/lib/Scenes/Artwork/Components/__tests__/OtherWorks-tests.tsx
This PR resolves **[MX-427]**
Typography changes from Serif To Sans in Artwork Pages (**BNMO, Inquiry, Auctions, Permanent Collection, On Hold, Not for Sale, No Availability**)
[MX-427]: https://artsyproduct.atlassian.net/browse/MX-427
> [MX-427] Update type on Artwork Pages

- src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
- src/lib/Scenes/ArtworkAttributionClassFAQ/__tests__/ArtworkAttributionClassFAQ-tests.tsx
This PR resolves **[MX-437]**
Update typography on Artwork Classification from Serif to Sans
**Before**
**After**
#trivial
[MX-437]: https://artsyproduct.atlassian.net/browse/MX-437
> [MX-437] Update type on Artwork Classifications

- Artsy/App/ARAppDelegate.m
- Artsy/App/ARAppNotificationsDelegate.m
This PR resolves **[MX-492]**
Disables 'auto-integration' from sailthru SDK which swizzles notification related methods that we use to handle deep linking. 
- Send existing push notifications from staging and confirm deep links are followed 
- Send Sailthru notifications from console and confirm deep links are followed and pushes are generally handled correctly 
[MX-492]: https://artsyproduct.atlassian.net/browse/MX-492
> [MX-492] - Disable sailthru swizzling to fix existing notifications

- Artsy/View_Controllers/Fair/ARProfileViewController.m
- Artsy_Tests/View_Controller_Tests/Fair/ARProfileViewControllerTests.m
Enable the ipad app to go to partners natively, not in a webview.
I guess try to go to one, or maybe try to see if there is a case where this might be/look broken?
These are a bit slow on my network and device, but you see the diff.
https://f.p0l.co/file/dropshare-public-pavlos/RPReplay_Final1596450747.MP4
https://f.p0l.co/file/dropshare-public-pavlos/RPReplay_Final1596450608.MP4
> Partner view on ipad

- src/lib/Scenes/Collection/Components/FullFeaturedArtistList.tsx
This PR resolves a QA item https://www.notion.so/artsy/header-in-Featured-Artists-list-in-collections-view-is-misaligned-05e969249d8e45ffbba5b68bcdc99f23
Use the standard `PageWithSimpleHeader` component
before:
after:
> Use standard page template on featured artist list

- src/lib/Scenes/Artwork/Artwork.tsx
This PR resolves **[This](https://artsyproduct.atlassian.net/browse/MX-427?focusedCommentId=30419)**
Remove padding from the `ItemSeparatorComponent`
#trivial
> Adjust artwork separator horizontal margin

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/ARAppNotificationsDelegate.h
- Artsy/App/ARAppNotificationsDelegate.m
- CHANGELOG.yml
- emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
- emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
- src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
- src/setupJest.ts
- typings/emission.d.ts
This PR resolves **[MX-493]**
@MounirDhahri called out during knowledge share that this state was possible on this screen due to how we don't show system notification prompt in some cases. 
- Changes existing native method to access notifications permissions to return "notDetermined", "authorized" or "denied"
- Exposes a new native method to request notification permissions from react native
- Adjusts copy of banner and button for "notDetermined" state, prompts for permission on tap
Co-authored by @ds300 @MounirDhahri 
[MX-493]: https://artsyproduct.atlassian.net/browse/MX-493
> [MX-493] - Push notification authorization not determined state 

- .circleci/config.yml
Our deploy block check is currently failing due to an issue with horizon:
https://artsy.slack.com/archives/CP9P4KR35/p1596570219288400
Removing for now to deploy a beta.
Will want to revert once this is resolved.
> Remove horizon block check for now #trivial

- CHANGELOG.yml
- src/lib/Components/Artist/ArtistHeader.tsx
This PR resolves **[MX-451]**
Adds a flex priority to artist metadata flex container.  Adds a right margin to artist metadata.
[MX-451]: https://artsyproduct.atlassian.net/browse/MX-451
> [MX-451] - Prevent follow button going off screen #trivial

- CHANGELOG.yml
- src/lib/Components/ArtistListItem.tsx
This PR resolves **[MX-452]**
Moves follow button outside EntityHeader component adds a flex priority to EntityHeader. Fixes a few strictness migration comments. I wonder if this is something that can be fixed in palette EntityHeader component? FollowButton prop doesn't seem to respect flex bounds.
[MX-452]: https://artsyproduct.atlassian.net/browse/MX-452
> [MX-452] - Prevent follow button going off screen partner/artist page

- CHANGELOG.yml
- src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
- src/__generated__/ArtistArtworksQuery.graphql.ts
- src/__generated__/ArtistNotableWorksRailTestsQuery.graphql.ts
- src/__generated__/ArtistNotableWorksRail_artist.graphql.ts
- src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
- src/__generated__/ArtworkRefetchQuery.graphql.ts
- src/__generated__/Artwork_artworkBelowTheFold.graphql.ts
- src/__generated__/ArtworksInSeriesRailTestsQuery.graphql.ts
- src/__generated__/ArtworksInSeriesRail_artwork.graphql.ts
- src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
- src/lib/Components/Artist/ArtistArtworks/__tests__/ArtistNotableWorksRail-tests.tsx
- src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx
- src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
- src/lib/Components/ArtworkTileRail/__tests__/ArtworkTileRailCard-tests.tsx
- src/lib/Scenes/Artwork/Artwork.tsx
- src/lib/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
- src/lib/Scenes/Artwork/Components/__tests__/ArtworksInSeriesRail-tests.tsx
- src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
- src/lib/Scenes/Home/Components/SmallTileRail.tsx
This PR resolves **[FX-2019](https://artsyproduct.atlassian.net/browse/FX-2019)**
- Creates `ArtworksInSeriesRail` component that, for an artwork in an artist series, displays other artworks from the series on the artwork page
- Updates `ArtworkTileRailCard`:
- Displays artwork title, date and partner (if given) 
- Supports true aspect ratio images
- `ArtistNotableWorksRail` to use true aspect ratio images instead of square aspect ratio images
- Updates other artwork rails as needed to use new `ArtworkTileRailCard` props
* @williardx to test in beta
**`ArtworksInSeriesRail`**
**`ArtistNotableWorksRail`**
> Users can see related artworks from an artist series on the artwork page

- src/lib/Scenes/Partner/Components/PartnerHeader.tsx
- src/lib/Scenes/Partner/Components/__tests__/PartnerHeader-tests.tsx
The type of this PR is: **Design Upkeep**
This PR resolves **[MX-458]**
Follow-up from feedback on https://github.com/artsy/eigen/pull/3660:
- Reduces spacing in below partner name to 10px
- Updates 'Works for sale' copy to 'works' to align with other pages
[MX-458]: https://artsyproduct.atlassian.net/browse/MX-458
> [MX-458] - Update copy, spacing in partner header #trivial

- src/lib/Components/ReadMore.tsx
- src/lib/Components/__tests__/ReadMore-tests.tsx
This PR is related to **[GALL-3073]**
The "Read more" button was using the old style of text, we moved it to the new.
Before
After
[GALL-3073]: https://artsyproduct.atlassian.net/browse/GALL-3073
> make `Read more` text use the new type styles #trivial

- src/lib/Scenes/ArtistSeries/ArtistSeriesHeader.tsx
This PR resolves **[FX-2109]**
This is take 2 (after #3692 ) at setting the `borderRadius` for the Artist Series header image. Turns out that you need to set an overflow on the `OpaqueImageView` for the image to actually be constrained. 
Here is an exaggerated version, for demo purposes —
Without no `overflow` on the left -vs-  with `overflow: hidden` on the right.
Here's the actual, final, very subtle 2px radius!
#trivial
[FX-2109]: https://artsyproduct.atlassian.net/browse/FX-2109
> Fix Artist Series header image border radius

- CHANGELOG.yml
- src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
- src/__generated__/ArtworkRefetchQuery.graphql.ts
- src/__generated__/Artwork_artworkBelowTheFold.graphql.ts
- src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
- src/lib/Scenes/Artwork/Artwork.tsx
- src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
This PR resolves **[FX-2021](https://artsyproduct.atlassian.net/browse/FX-2021)**
- Adds ability for users to see artist series from the artist on the artwork page (if the artist series feature flag is enabled)
- @williardx to test in beta
> User can see artist's artist series on the artwork page

- src/lib/Components/Home/ArtistRails/ArtistRail.tsx
- src/lib/Scenes/City/CityPicker.tsx
- src/lib/Scenes/City/Components/SavedEventSection/index.tsx
- src/lib/Scenes/MyProfile/MyProfile.tsx
- src/lib/Scenes/Search/CityGuideCTA.tsx
- src/lib/Scenes/Search/RecentSearches.tsx
- src/lib/Scenes/Search/__tests__/CityGuideCTA-tests.tsx
- src/lib/Scenes/Search/__tests__/Search-tests.tsx
- src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
This PR resolves **[MX-483]**
Most of our section titles are currently using title case, but Brand has suggested we move to sentence case as its more approachable/welcoming! 
Slack thread for reference: https://artsy.slack.com/archives/CV68RJVV3/p1594923419020700
**_Home tab screenshots will be available once [this PR](https://github.com/artsy/metaphysics/pull/2610) is merged_**
___
**_My profile tab_**
___
**_Search Tab_**
#trivial
[MX-483]: https://artsyproduct.atlassian.net/browse/MX-483
> [MX-483] Update subtitles to sentence case

- CHANGELOG.yml
- src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
- src/__generated__/ArtistArtworksQuery.graphql.ts
- src/__generated__/ArtistSeriesFullArtistSeriesListQuery.graphql.ts
- src/__generated__/ArtistSeriesFullArtistSeriesListTestsQuery.graphql.ts
- src/__generated__/ArtistSeriesFullArtistSeriesList_artist.graphql.ts
- src/__generated__/ArtistSeriesMoreSeriesTestsQuery.graphql.ts
- src/__generated__/ArtistSeriesMoreSeries_artist.graphql.ts
- src/__generated__/ArtistSeriesQuery.graphql.ts
- src/__generated__/ArtistSeriesTestsQuery.graphql.ts
- src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
- src/__generated__/ArtworkRefetchQuery.graphql.ts
- src/lib/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesFullArtistSeriesList-tests.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesListItem-tests.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesMoreSeries-tests.tsx
This PR resolves **[FX-2123]**
Updates artwork count that are displayed in the context of Artist Series, such that they have a fallback value when the for-sale artworks count is zero. 
(This fallback is derived in Metaphysics; nothing special being done here other than querying a new `artworksCountMessage` field in the MP schema.)
Mostly a no-op, but existing test fixtures are updated to reflect the new upstream field being utilized in MP queries
|Artist Series - more series|Artist - top series|Artist - all series|Artwork - more series|
|<img height="300" src="https://user-images.githubusercontent.com/140521/90178323-bc68fd80-dd79-11ea-952e-c5a22b648f18.png" title="series - more rail" />|<img height="300" …
> [FX-2123] Update artworks counts for Artist Series 

- src/lib/Components/Inbox/Conversations/Composer.tsx
- src/lib/Components/Inbox/Conversations/__tests__/Composer-tests.tsx
This PR resolves [PURCHASE-2051]
Re-styled reply box on inbox to look more like web. Currently looks like this:
This PR makes it look like this:
[PURCHASE-2051]: https://artsyproduct.atlassian.net/browse/PURCHASE-2051
> [PURCHASE-2051] Restyle reply box

- src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
- src/lib/Scenes/Artwork/Components/__tests__/CommercialPartnerInformation-tests.tsx
The type of this PR is: Enhancement (?)
This PR resolves [MX-504]
Replace "Sold by" with "From" in CommercialPartnerInfo
#trivial
[MX-504]: https://artsyproduct.atlassian.net/browse/MX-504
> fix: change "sold by" to "from" in comm partner info

- CHANGELOG.yml
- src/lib/Scenes/Search/Search.tsx
- src/lib/Scenes/Search/__tests__/Search-tests.tsx
This PR resolves [MX-425]
Conforms the iPad view to the iPhone, minus City Guide.
I also refactored the code slightly to make it (to my mind) more readable, but others may disagree - I'm open to change it back, obvs!
[MX-425]: https://artsyproduct.atlassian.net/browse/MX-425
> fix: conform ipad empty search screen to iphone

- src/lib/Scenes/Search/AutosuggestResults.tsx
This PR resolves [MX-497]
Sets the font of the _We couldn't find anything for "zzzz"_ message to `Sans` instead of `Serif`
#trivial
[MX-497]: https://artsyproduct.atlassian.net/browse/MX-497
> fix: empty search message font should be sans

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- Artsy/App/ARSwitchBoard+Eigen.m
- CHANGELOG.yml
- src/__generated__/SaleQueryRendererQuery.graphql.ts
- src/__generated__/Sale_sale.graphql.ts
- src/lib/AppRegistry.tsx
- src/lib/Scenes/Sale/Sale.tsx
- src/lib/Scenes/Sale/index.tsx
This PR resolves [MX-512]
Adds a new page for auctions (called "sales", technically) behind a lab option. The new component actually performs the MP query to grab some sale data – I included the `name` as a proof-of-concept for others to build upon. I opted to use the new `relay-hooks` approach – not sure I love it yet. But best to get with the times!
[MX-512]: https://artsyproduct.atlassian.net/browse/MX-512
> [MX-512] Adds new sale page

- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- CHANGELOG.yml
This fixes an edge case introduced by #3714 that prevented deep links from being handled correctly.
Basically the problem is that after #3714 it took a little longer for the `ARTopMenuViewController` singleton to reach a state where it is ready to properly handle pushing VCs.
`ARTopMenuViewController` is going to be disappearing very soon so I put a band-aid on the issue here, by adding `pushViewController` method calls to a queue until `ARTopMenuViewController` finishes loading, and then processing them.
- Not sure it's worth testing this since it's going to be deleted so soon and this whole class lacks test coverage anyhow.
> Push deep link VCs after main nav VC loads

- patches/react-native+0.62.1.patch
This fixes City Guide having weird touch behaviour by using a much more robust method of deduplicating touches in nested `RCTRootContentView`s.
Basically we now allow touchables to have more than one `RCTTouchHandler` in their responder chain, and we just make sure that only their closest ancestor actually handles their touches fully.
> improve touch deduplication approach

- src/__generated__/MyBidsQuery.graphql.ts
- src/__generated__/MyProfileQuery.graphql.ts
- src/__generated__/MyProfileRefetchQuery.graphql.ts
- src/__generated__/MyProfile_me.graphql.ts
- src/__generated__/SaleCard_sale.graphql.ts
- src/lib/Scenes/MyBids/Components/ActiveLot.tsx
- src/lib/Scenes/MyBids/Components/SaleCard.tsx
- src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx
- src/lib/Scenes/MyBids/__tests__/index-tests.tsx
- src/lib/Scenes/MyBids/helpers/lotStanding.ts
- src/lib/Scenes/MyBids/index.tsx
- src/lib/Scenes/MyProfile/MyProfile.tsx
_One question about testing: We don't have a high-level test for the MyProfile screen where I could check for active bid count. Is this okay to skip for now in order to QA in tomorrow's session?_
This PR adds the active lot count to the user profile page. It needs tests and is blocked by (includes commits from) #3787. Once that is merged I will rebase and add tests here.
It also fixes a few visual bugs:
- missing/broken sale end time on sale card
- Reserve not met message should not should for live lots with UnknownReserve status
One point of note - I created a `lotStandingIsClosed` helper since I was reusing this logic, and imported it into the MyProfile screen from the `MyBids` screen helpers directory. I don't know if that is okay.
> add active lot standing count to profile page

- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/Categories/AFNetworking/AFHTTPRequestOperation+JSON.m
- Artsy/Models/API_Models/Partner_Metadata/Artwork.m
- Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
- Artsy/Networking/API_Modules/ArtsyAPI+ErrorHandlers.m
- Artsy/Networking/API_Modules/ArtsyAPI+ListCollection.h
- Artsy/Networking/API_Modules/ArtsyAPI+Notifications.h
- Artsy/Networking/API_Modules/ArtsyAPI+Sailthru.m
- Artsy/Networking/ARRouter.m
- Artsy/Networking/Network_Models/ARFavoritesNetworkModel.m
- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
- Artsy/View_Controllers/Util/Logging/ARHTTPRequestOperationLogger.m
- Artsy_Tests/Networking_Tests/AFHTTPRequestOperationJSONTests.m
- Artsy_Tests/Stubs/OHHTTPStubs+Artsy.m
- Artsy_Tests/Supporting_Files/Artsy_Tests-Prefix.pch
- CHANGELOG.yml
- Podfile
- Podfile.lock
The type of this PR is: **Upkeep**
This PR resolves [MX-286]
This PR removes the `AFNetworking/UIKit` dependency (by specifying all the other `AFNetworking/*` subspecs explicitly). This removes the code in AFNetworking that referenced `UIWebView`, without having to go through an arduous AFNetworking upgrade. We weren't using the `UIWebView` code anyway – I'm grateful to the AFNetworking maintainers that they were so forward-thinking in dividing up the dependency into thoughtful subspecs. I also had to update all our `#import` statements.
I got the idea here: https://github.com/AFNetworking/AFNetworking/issues/4428#issuecomment-527956472 Really great workaround, especially considering how (longterm) we want to move away from AFNetworking and towards all network requests being done from …
> Removes AFNetworking/UIKit subspec

- Artsy/App_Resources/Artsy-Info.plist
- Artsy/Networking/ARAuthProviders.m
- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- CHANGELOG.yml
- Podfile
- Podfile.lock
This PR resolves [MX-462]
- Updates Facebook sdk to version that supports disabling access to idfa
- Adds plist value to disable access
- Removes access to idfa in admin menu
[MX-462]: https://artsyproduct.atlassian.net/browse/MX-462
> [MX-462] - Disable idfa access by Facebook sdk

- Artsy.xcodeproj/project.pbxproj
- Artsy/App/ARAppDelegate+Analytics.m
- Artsy/App/ARSegmentProvider.h
- Artsy/App/ARSegmentProvider.m
- CHANGELOG.yml
This PR resolves [MX-463]
This disables tracking IDFA in Segment in preparation for new iOS 14 changes around its collection: 
https://developer.apple.com/app-store/user-privacy-and-data-use/
Since we use ARAnalytics pod with the default segment provider this creates a custom subclass of the default Segment analytics provider with the only change being disabling this tracking on initialization.
**Note:** Segment is releasing an update sometime soon that removes this tracking code entirely and replaces it with a block based approach, we may want to update to that version when the time comes: https://github.com/segmentio/analytics-ios/pull/892
[MX-463]: https://artsyproduct.atlassian.net/browse/MX-463
> [MX-463] - Disable idfa collection in segment

- .circleci/config.yml
I noticed when merging a few PRs in a row that `pod install` was being ran every build, despite having manifest-style caching like our other dependencies. This isn't a huge deal but it takes a minute or two for CocoaPods just to download the podspecs to do dependency resolution. We already have [`cocoapods-check`](https://github.com/square/cocoapods-check) in our `Gemfile`, which compares `Podfile.lock` to `Pods/Manifest.lock` and returns the resulting exit code. This should shave some time off our builds. 
I tried to think of a reason this wouldn't work, but I think it should be safe. Open to feedback here.
> Avoids installing CocoaPods on CI if cache is available #trivial

- Makefile
These flags were initially added in #1465 but we don't use them anymore. They were causing build failures on CI, so let's remove them 👍
> chore: remove swift build flags

- Artsy_Tests/View_Controller_Tests/Web_Browsing/ARExternalWebBrowserViewControllerTests.m
- Artsy_Tests/View_Controller_Tests/Web_Browsing/ARInternalMobileWebViewControllerTests.m
- CHANGELOG.yml
This PR resolves [MX-286]
Migrate to `WKWebView ` because Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
There were only 2 references for UIWebView in the project after [this commit](https://github.com/artsy/eigen/commit/f3c8ad009a75072b57141e0013bb95d5d0c033aa) and [this PR](https://github.com/artsy/eigen/pull/3806)
_The remaining instances are part of react-native code and they are not used anywhere_
____
**Before**
**After**
[MX-286]: https://artsyproduct.atlassian.net/browse/MX-286
> chore: [MX-286] migrate away from UIWebView

- Artsy/App/ARAppDelegate+Emission.m
- Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift
- Artsy_Tests/View_Controller_Tests/Auction/SaleArtworkViewModelTests.swift
- Artsy_Tests/View_Controller_Tests/SaleOnHoldOverlayViewTests.swift
- Artsy_Tests/View_Tests/Auctions/AuctionTitleViewTests.swift
- docs/developing_a_feature.md
The type of this PR is: **Cleanup**
- Update some places feature flag docs are out of date
- Fixes some warnings in tests
- Remove unnecessary OR of newly added feature flag
The logical or part came up in this PR: https://github.com/artsy/eigen/pull/3808#discussion_r481372160 
My best guess is the initial price transparency feature flag had a key that didn't match the string for the echo flag so this line was necessary: https://github.com/artsy/eigen/pull/2934/files#diff-fa3274520df88be962c7afc891c3b5edR27. Also we call out in docs that we have had problems with OR'ing these flags so probably do not want to do this. 
https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md#why-do-we-need-to-remove-the-lab-flag-when-adding-echo-flag Unfortunately simply removing the OR is …
> Feature flag doc updates cleanup remove unnecessary OR #trivial

- fastlane/Fastfile
This PR resolves [MX-]
Use `app_store_build_number` to get the version number out of `Actions.lane_context[SharedValues::LATEST_VERSION]`
cc: @ashfurrow 
ref: https://github.com/fastlane/fastlane/pull/17148
> Fix Fastfile for new fastlane for beta

- fastlane/Fastfile
This is part of ongoing work to get our deploys working again. We ran into [this issue](https://github.com/fastlane/fastlane/issues/17140) but the fix [here](https://github.com/fastlane/fastlane/pull/17148) didn't work. @joshdholtz was kind enough to open #3821 but we still saw errors based on version number mismatches.
Stepping back, the code that was now failing was a check to make sure beta deploys failed early. This was important a few years ago when beta deploys took 45 minutes. Now they take a lot less (we have sophisticated CI caching) and it was only the check that was causing our current problem. So I just removed the check. The new build is [running here](https://app.circleci.com/pipelines/github/artsy/eigen/4977/workflows/b55c5a31-114e-4838-89c1 …
> Fixes deploys by removing Fastfile check #trivial

- Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginFieldsView.m
The type of this PR is: **Feature**  #trivial
This PR resolves [MX-440]
Marking the email field as `username` since that's the field apple autofills, and marking the keyboard as `email` still, so we keep the current behaviour.
[MX-440]: https://artsyproduct.atlassian.net/browse/MX-440
> Enable autofill on email field on login

- Makefile
- README.md
- docs/getting_started.md
The type of this PR is: Enhancement/Documentation
While setting up eigen locally, I noticed a few improvements we can do in the makefile and documentation:
* Fixing `$TMPDIR` when clearing cache in `make flip_table`.
* Cleaning up Makefile.
* Fixing broken links in documentation.
> Clean up Makefile; fix broken links in documentation

- CHANGELOG.yml
- src/__generated__/ConversationQuery.graphql.ts
- src/__generated__/FileDownload_attachment.graphql.ts
- src/__generated__/Message_message.graphql.ts
- src/__generated__/MessagesQuery.graphql.ts
- src/__generated__/SendConversationMessageMutation.graphql.ts
- src/lib/Components/Inbox/Conversations/Message.tsx
- src/lib/Components/Inbox/Conversations/Preview/Attachment/FileDownload.tsx
- src/lib/Components/Inbox/Conversations/Preview/Attachment/PDFPreview.tsx
- src/lib/Components/Inbox/Conversations/Preview/Attachment/__tests__/FileDownload-tests.tsx
- src/lib/Components/Inbox/Conversations/Preview/Attachment/__tests__/PDFPreview-tests.tsx
This PR resolves [PURCHASE-2052]
**Problem:**
Only PDF and Image attachments are displayed in conversation. This hasn't been reported by any collectors since this has been launched a couple of years ago. I noticed it while doing QA.
**Solution:**
Add `FileDownload` component for other content types. It downloads the file in Safari. Since nobody has noticed this problem before a lightweight solution should be enough for now.
While at it also did some 🐍 -> 🐫 case updates.
cc: @jo-rs 
Before:
---
After:
</details>
[PURCHASE-2052]: https://artsyproduct.atlassian.net/browse/PURCHASE-2052
> [PURCHASE-2052] Add Download option for non-preview-able attachments

- src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/lib/Containers/Gene.tsx
This PR resolves [MX-506]
Fix the strange transition that happens when switching between the `Works` and `About` Tabs.
[MX-506]: https://artsyproduct.atlassian.net/browse/MX-506
> [MX-506] Fix gene tabs strange transition

- docs/overview.md
- docs/preferred_practices.md
Co-authored-by: Mounir Dhahri <mounir.dhahri@ensi-uma.tn>
- Renames map_to_app to preferred_practices 
- Adds section in preferred_practices on relay containers
> docs: Rename map_to_app, add relay container docs #trivial

- src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
- src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomSubsections-tests.tsx
This PR resolves https://www.notion.so/artsy/UI-Viewing-room-page-padding-is-gone-46a54ca7a0ca4e56bf7ea6ffa705589b
I fixed the margins for VR subsections. #trivial
I noticed that the issue actually is a bit deeper, so I created https://artsyproduct.atlassian.net/browse/MX-534 to investigate and fix.
Before
After
> fix for vr subsections margin

- src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
This PR resolves https://www.notion.so/artsy/UI-ArtistSeries-work-added-inconsistent-padding-at-top-of-ArtistArtworks-tab-content-2cbf56880f764330a11e75705c12e37c
> fix ArtworkArtists padding

- CHANGELOG.yml
- src/__generated__/MyBidsQuery.graphql.ts
- src/__generated__/MyBids_me.graphql.ts
- src/__generated__/MyProfileQuery.graphql.ts
- src/__generated__/MyProfileRefetchQuery.graphql.ts
- src/__generated__/MyProfile_me.graphql.ts
- src/lib/Scenes/MyBids/Components/ClosedLot.tsx
- src/lib/Scenes/MyBids/__fixtures__/MyBidsQuery.ts
- src/lib/Scenes/MyBids/__tests__/index-tests.tsx
- src/lib/Scenes/MyBids/helpers/lotStanding.ts
- src/lib/Scenes/MyBids/index.tsx
- src/lib/Scenes/MyProfile/MyProfile.tsx
This PR updates our My Bids screen to group lots by whether their _associated sale_ is closed or pre-closed, not by whether each individual lot is closed. This is to keep lots in a Live Auction Integration sale from disappearing into the 'closed' view while the sale is ongoing.
> group lots by whether sale is closed, not per-lot

- CHANGELOG.yml
- src/lib/Scenes/Home/Components/SalesRail.tsx
This resolves https://www.notion.so/artsy/Seeing-register-by-in-time-field-on-Auction-cards-9e2e742a85e5457db62607a1655507cd
Fix issue with register by at Auctions rail on Home screen
> Fix issue with register by field on auctions rail

- CHANGELOG.yml
- src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/__tests__/index-tests.tsx
- src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
- src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
This PR resolves [CSGN-287]
This fixes an issue where tapping 'consign with artsy' on the artwork page would open the sell tab landing page in an undismissable modal without actually switching tab.
Now it just switches to the sell tab, unless it's already in the sell tab, in which case it pushes a new version of the landing page on the nav stack. This mirrors the behaviour of the consignments CTA on the artist page.
[CSGN-287]: https://artsyproduct.atlassian.net/browse/CSGN-287
> Fix artwork page consignment link

- CHANGELOG.yml
- src/__generated__/MyCollectionArtworkListPaginationQuery.graphql.ts
- src/__generated__/MyCollectionArtworkList_me.graphql.ts
- src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListHeader.tsx
This PR resolves [CSGN-375](https://artsyproduct.atlassian.net/browse/CSGN-375)
Adds a pagination container to the My Collection artworks list component.
> [My Collection] Add pagination container to My Collection Artworks List 

- CHANGELOG.yml
- src/lib/Scenes/Consignments/Screens/Metadata.tsx
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/MediumPicker.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
- src/lib/utils/__tests__/artworkMediumCategories-tests.ts
- src/lib/utils/artworkMediumCategories.ts
The type of this PR is: **Enhancement/Documentation**
Refactors duplicated artwork categories to a single utility file for use throughout the app. The raw values come from Gravity so any changes upstream can be maintained here. 
Unchanged files that still render mediums as expected:
> Move artwork categories to a common util file

- src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
- src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/lib/Components/HeaderTabGridPlaceholder.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesFullArtistSeriesList-tests.tsx
- src/lib/utils/placeholders.tsx
[FX-2264]
[FX-2253]
[FX-2266]
A couple of visual QA items from the artist series launch (we have tickets to track other issues that were brought up!).
In summary:
- Adds a skeleton loading view
- Makes the header on the "Full artist list" not sticky
- Changes case of "show more" button to be sentence case
- Updates spacing between Artist Series list and Notable Works rail on artist page
[FX-2264]: https://artsyproduct.atlassian.net/browse/FX-2264
[FX-2253]: https://artsyproduct.atlassian.net/browse/FX-2253
[FX-2266]: https://artsyproduct.atlassian.net/browse/FX-2266
#trivial
> FX-2264/FX-2253/FX-2266: Small QA items for artist series

- src/lib/Scenes/Consignments/Screens/Overview.tsx
- src/lib/Scenes/MyCollection/Boot.tsx
- src/lib/Scenes/MyCollection/Components/Navigator.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
- src/lib/Scenes/MyCollection/Screens/ConsignmentsHome/ConsignmentsHome.tsx
- src/lib/Scenes/MyCollection/Screens/ConsignmentsHome/ConsignmentsSubmissionForm.tsx
- src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
This PR resolves https://artsyproduct.atlassian.net/browse/CSGN-372
This cleans up our navigation between MyCollections screens and Consignments home / submission, etc, now that we have a good NavigatorIOS abstraction in place to push to these views. 
cc @artsy/csgn-devs 
#minor 
> [MyCollection] Clean up navigation between MyCollection and consignments

- CHANGELOG.yml
- src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
- src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
- src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
- src/__generated__/ArtistSeriesQuery.graphql.ts
- src/__generated__/ArtistSeriesTestsQuery.graphql.ts
- src/__generated__/ArtistSeries_artistSeries.graphql.ts
- src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/lib/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
- src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/lib/Components/FilterModal.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
- src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesArtworks-tests.tsx
- src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
This PR resolves [FX-2265]
This PR adds the ability to filter the artworks on the artist series view. On the way, I had to make a couple of adjustments to existing components.
Full list of changes is:
- Converts the top-level `ArtistSeries` view to be a `FlatList`. This is both because my understanding is that FlatLists are slightly more performant (especially given the artist series view has components far below-the-fold), and because FlatLists provide helpers for understanding the placement of components on the screen-- this made it possible for us to conditionally render the Filter button.
- Caveat: It's possible you can achieve something similar with a `ScrollView`, but I didn't see anything obvious in my research.
- Using the existing filter …
> FX-2265: User can filter artworks within an artist series

- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
This PR resolves [CSGN-385](https://artsyproduct.atlassian.net/browse/CSGN-385)
Replaces the static integer values for Liquidity with a string representation (Low, Medium, High, Very High).
*After*
*Before*
#trivial 
> [My Collection] Use product defined ranges to display liquidity values as text

- CHANGELOG.yml
- src/__generated__/ArtistSeriesFullArtistSeriesListQuery.graphql.ts
- src/__generated__/ArtistSeriesFullArtistSeriesListTestsQuery.graphql.ts
- src/__generated__/ArtistSeriesFullArtistSeriesList_artist.graphql.ts
- src/lib/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
This PR resolves [FX-2281]
This is a one-liner change to bump the size of the `artistSeriesConnection` query from the default (20) to a max of 50.
Depends on https://github.com/artsy/gravity/pull/13481, which implements the backend change allowing this max.
(^39 Kaws series in this list)
[FX-2281]: https://artsyproduct.atlassian.net/browse/FX-2281
> feat: show up to 50 artist series in the full list of series by an artist

- src/lib/tests/renderWithWrappers.tsx
When writing a relay test today I found myself hopelessly lost as to why the test renderer wasn't rendering the `<QueryRenderer>`. It turns out I forgot to add `jest.unmock('react-relay')` at the top of my test.
This updates our `renderWithWrappers` function to check for this condition, and to alert the user of the possibility.
> Make mocked relay error more obvious

- Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
- CHANGELOG.yml
- src/__generated__/Fair2HeaderTestsQuery.graphql.ts
- src/__generated__/Fair2Header_fair.graphql.ts
- src/__generated__/Fair2MoreInfoQuery.graphql.ts
- src/__generated__/Fair2MoreInfoTestsQuery.graphql.ts
- src/__generated__/Fair2MoreInfo_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/lib/AppRegistry.tsx
- src/lib/Scenes/Fair2/Components/Fair2Header.tsx
- src/lib/Scenes/Fair2/Components/Fair2MoreInfo.tsx
- src/lib/Scenes/Fair2/Fair2MoreInfo.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Header-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2MoreInfo-tests.tsx
- src/lib/navigation/routes.tsx
This PR resolves [FX-2209]
- Adds `Fair2MoreInfo` view that gives additional information about a fair. The implementation follows our implementation in Force when possible: https://github.com/artsy/force/pull/6119.
- Migrates routing/navigation logic to new routing logic per https://github.com/artsy/eigen/pull/3771.
[FX-2209]: https://artsyproduct.atlassian.net/browse/FX-2209
[FX-2209]: https://artsyproduct.atlassian.net/browse/FX-2209
> feat: Adds view showing more info about fairs

- src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/lib/Components/ArtworkGrids/__tests__/InfiniteScrollArtworksGrid-tests.tsx
- src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx
- src/lib/Containers/Gene.tsx
- src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
- src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
- src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
- src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx
#trivial
This PR resolves [FX-2246]
The [`isLoading` function](https://relay.dev/docs/en/pagination-container#isloading) provided by Relay pagination containers does not trigger a render. It "is convenient for avoiding duplicate load calls" rather than transitioning the state of the UI. This PR just switches it to a simple state flag and removes what, I assume, is some code that was not actually rendering. [It *looks* like this broke in this commit.](https://github.com/artsy/eigen/commit/1090fc6251514ba157220c86fdcc0f1827eed5b2)
I did not include a spec for this because of the simplicity, but let me know if you believe it should have one and I'll add it.
-----
[FX-2246]: https://artsyproduct.atlassian.net/browse/FX-2246
> [FX-2246] Utilizes state to track loading

- src/lib/Scenes/MyProfile/Components/MyProfileMenuItem.tsx
While testing some stuff on `MyProfile` tab I noticed that we broke the `MyProfileMenuItem`
**Before**
**After**
#trivial
> fix: fix MyProfileMenuItem

- fastlane/Fastfile
Worked on in knowledge share, our submission tags are incorrectly being tagged with an old date taken from the plist.
See an example here: https://github.com/artsy/eigen/releases/tag/6.6.4-2019.05.24.09-submission
This instead uses the latest test flight build version and addresses the issue of truncating build version called out in the comment by appending leading zeros to any truncated values.
Co-authored-by: @ds300
Co-authored-by: @MounirDhahri 
Co-authored-by: @pvinis
> Fix date for submission tags #trivial

- Artsy/View_Controllers/Web_Browsing/ARInternalWebView.m
- CHANGELOG.yml
- src/lib/navigation/routes.tsx
This PR resolves [MX-549]
These routes were actually loading correctly but there was a layout issue with the internal web view component, not really clear how it broke.
- Aligns internal web view native component to parent vc
- Adds dedicated routes for identity verification FAQ and auction FAQ to avoid profile api call in VanityURLEntity
- The back button is covering the Auction FAQ header in the webview, seems like this is an existing bug in older builds
[MX-549]: https://artsyproduct.atlassian.net/browse/MX-549
> [MX-549] - align internal webview to parent vc, add dedicated routes for faqs

- src/lib/Components/Buttons/BottomAlignedButtonWrapper.tsx
- src/lib/Scenes/Consignments/Components/BottomAlignedButton.tsx
This PR resolves [MX-553]
The Bottom buttons in modals are obscured by the keyboard.
**Before:**
___
**After**
___
[MX-553]: https://artsyproduct.atlassian.net/browse/MX-553
> [MX-553] fix: Bottom buttons in modals are obscured by keyboard

- CHANGELOG.yml
- src/__generated__/Fair2ArtworksInfiniteScrollGridQuery.graphql.ts
- src/__generated__/Fair2ArtworksTestsQuery.graphql.ts
- src/__generated__/Fair2Artworks_fair.graphql.ts
- src/__generated__/Fair2ExhibitorRailTestsQuery.graphql.ts
- src/__generated__/Fair2ExhibitorRail_show.graphql.ts
- src/__generated__/Fair2ExhibitorsQuery.graphql.ts
- src/__generated__/Fair2ExhibitorsTestsQuery.graphql.ts
- src/__generated__/Fair2Exhibitors_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/Fair2_fair.graphql.ts
- src/lib/Scenes/Fair2/Components/Fair2Artworks.tsx
- src/lib/Scenes/Fair2/Components/Fair2Collections.tsx
- src/lib/Scenes/Fair2/Components/Fair2Editorial.tsx
- src/lib/Scenes/Fair2/Components/Fair2ExhibitorRail.tsx
- src/lib/Scenes/Fair2/Components/Fair2Exhibitors.tsx
- src/lib/Scenes/Fair2/Components/SimpleTabs.tsx
- src/lib/Scenes/Fair2/Fair2.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Artworks-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2ExhibitorRail-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Exhibitors-tests.tsx
This PR resolves [FX-2213], [FX-2214], [FX-2215]
This PR adds the bottom-of-the-page content to the new fair page, which includes the Exhibitors and Artworks shelves/grid.
Some notes:
- To get the sticky header effect, I used the built-in `stickyHeaderIndices` prop on `FlatList`. It seems to work fine, the only weird thing is that when you click into the "Artworks" tab, the screen jumps. I'm pretty sure this is due to how we lazily-load that artworks grid (as the same does not occur when switching to the "Exhibitors" tab).
- The rest is pretty standard and builds off the logic we have on web.
- In order to validate that the basic layout works as-intended, I also included the animated Filter Button in this PR. Will follow up with the actual filtering …
> FX-2213, FX-2214, FX-2215: Adds the Artworks and Exhibitors content to fair page

- src/lib/Scenes/Collection/Components/FullFeaturedArtistList.tsx
For some reason I notice this error out in the simulator (inconsistently). Not sure why, but adding a safe access operator can't hurt. 
#trivial
> Make access safer

- CHANGELOG.yml
- src/lib/Components/FilterModal.tsx
This PR resolves [MX-547]
While working on the auctions filters I had to fix the title issue
[MX-547]: https://artsyproduct.atlassian.net/browse/MX-547
> [MX-547] fix: center filters modal title

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/Networking/API_Modules/ArtsyAPI+Search.h
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- Artsy/View_Controllers/Util/Errors/ARNetworkErrorManager.m
- Podfile
- Podfile.lock
The type of this PR is: **upkeep** ✨ 
Xcode was showing various warnings, about unused unimplemented functions, and a type warning, that I cleaned up. I also fixed the annoying warnings after running `pod install`.
Before:
After:
I added a note explaining the issue to the Podfile.
> Fix various build-time warnings #trivial

- CHANGELOG.yml
- docs/pull_request_template.md
The type of this PR is: **DX**
We added the changelog after the change in https://github.com/artsy/peril-settings/pull/167.
> tooling: Adding a new checkbox in the pr template for changelog #trivial

- CHANGELOG.yml
- src/__generated__/Fair2ArtworksInfiniteScrollGridQuery.graphql.ts
- src/__generated__/Fair2ArtworksTestsQuery.graphql.ts
- src/__generated__/Fair2Artworks_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/Fair2_fair.graphql.ts
- src/lib/Components/ArtworkFilterOptions/ArtistsIFollowOptions.tsx
- src/lib/Components/FilterModal.tsx
- src/lib/Scenes/Collection/Helpers/FilterArtworksHelpers.ts
- src/lib/Scenes/Collection/Helpers/__tests__/FilterArtworksHelpers-tests.tsx
- src/lib/Scenes/Fair2/Components/Fair2Artworks.tsx
- src/lib/Scenes/Fair2/Components/SimpleTabs.tsx
- src/lib/Scenes/Fair2/Fair2.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Artworks-tests.tsx
- src/lib/utils/ArtworkFiltersStore.tsx
This PR resolves [FX-2216]
This PR adds the ability filter a fair by "Artists I Follow". For the most part, I was able to follow existing patterns but refactored slightly to make it easier to include the new aggregation/filter.
Adding the default filters at this point is trivial boilerplate (the filter button was included in a separate PR).
[FX-2216]: https://artsyproduct.atlassian.net/browse/FX-2216
> FX-2216: Allows filtering on new fair page by defaults + Artists I Follow

- data/schema.graphql
- src/__generated__/MyCollectionArtworkDetailQuery.graphql.ts
- src/__generated__/MyCollectionArtworkDetail_sharedProps.graphql.ts
- src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts
- src/__generated__/MyCollectionArtworkListItem_artwork.graphql.ts
- src/__generated__/MyCollectionArtworkListPaginationQuery.graphql.ts
- src/__generated__/MyCollectionArtworkListQuery.graphql.ts
- src/__generated__/MyCollectionArtworkListTestsQuery.graphql.ts
- src/__generated__/MyCollectionArtworkMetaTestsQuery.graphql.ts
- src/__generated__/MyCollectionArtworkMeta_artwork.graphql.ts
- src/__generated__/MyCollectionArtworkModelCreateArtworkMutation.graphql.ts
- src/__generated__/MyCollectionArtworkModelUpdateArtworkMutation.graphql.ts
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AdditionalDetails.tsx
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/__tests__/AdditionalDetails-tests.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkMeta.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/__tests__/MyCollectionArtworkMeta-tests.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
- src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
- src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
This PR resolves [CSGN-379]
When an artwork in My Collection has edition data, we should show it by default in the form.
Artwork with edition data:
Artwork without edition data:
#trivial 
[CSGN-379]: https://artsyproduct.atlassian.net/browse/CSGN-379
> feat(My Collection): show edition data in form by default

- CHANGELOG.yml
- src/__generated__/Fair2HeaderTestsQuery.graphql.ts
- src/__generated__/Fair2Header_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/Fair2Timing_fair.graphql.ts
- src/lib/Components/Bidding/Context/TimeOffsetProvider.tsx
- src/lib/Components/EventTiming.tsx
- src/lib/Components/WithCurrentTime.tsx
- src/lib/Components/__tests__/EventTiming-tests.tsx
- src/lib/Scenes/Fair2/Components/Fair2Header.tsx
- src/lib/Scenes/Fair2/Components/Fair2Timing.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Header-tests.tsx
This ports over the logic from https://github.com/artsy/force/pull/6348 , which implements the updated timing display for a fair (as well as in a show view, when we tackle that).
I updated the sample fair in the [admin menu](https://github.com/artsy/eigen/blob/a9ee792704bde817a36936e727d8535ea13e3af0/Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m#L128) to represent the various states in order to QA (although, since the logic matches web, it should be the same!).
> @sweir27 => feat(fair2) Add updated timing info

- CHANGELOG.yml
This was failing to parse in our `Fastfile` with the following error:
```
Psych::SyntaxError: (<unknown>): found character that cannot start any token while scanning for the next token at line 19 column 7
```
This caused the beta deploy to fail.
/cc @sepans 
> Fixes Changelog parse error #trivial

- CHANGELOG.yml
- src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
- src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx
- src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
We lacked UTMs on artwork and VR share links - this PR fixes that by adding `utm_content=[artwork|viewing-room]-share`
[Slack discussion](https://artsy.slack.com/archives/C9ZJYFDNF/p1601661871287500)
<details><summary>Screenshots!</summary>
</details>
> chore: add utms to share links

- src/lib/NativeModules/SwitchBoard.tsx
- src/lib/Scenes/City/Components/FairEventSection/Components/FairEventSectionCard.tsx
- src/lib/Scenes/City/Components/TabFairItemRow/index.tsx
- src/lib/Scenes/Home/Components/FairsRail.tsx
- src/lib/Scenes/Home/Components/__tests__/FairsRail-tests.tsx
- src/lib/Scenes/Map/Components/ShowCard.tsx
- src/lib/Scenes/Search/SearchResult.tsx
- src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx
- src/lib/navigation/__tests__/routes-tests.tsx
- src/lib/navigation/routes.tsx
- src/setupJest.ts
This is part of a series of PRs that will update fairs routing to support the new fair view.
Fairs routing is inherently confusing because:
- Externally (i.e. search results, from web), fairs are linked to via a URL that looks like `/:profileSlug`. This means that for any fair view, we need to be able to support this top-level URL.
- Internally within eigen, we currently use a combination of that top-level URL and routes that are scoped like `/fair/:fairID`.
What this PR does:
- Gets rid of `SwitchBoard.presentFairViewController` in favor of our new `navigate` helper. (I'm guessing/assuming this is desired from a general ecosystem perspective!)
- Adds a new route to our routes file: `/fair/:fairID`, which will route to the main Fair screen. …
> Use navigate where possible for fairs routing #trivial

- CHANGELOG.yml
- src/lib/Scenes/Sales/Components/SaleListItem.tsx
This PR resolves [CX-537] (woop! first CX issue!)
The text was displayed incorrectly. Now it should be good.
I basically added two more `replace`s. One is for removing the newline, and the other is for making the months capitalized, since `capitalize` doesn't do it (I guess it cares only about "sentences", and we don't have a full-stop, so it skips the month).
I tried adding tests but it got a bit tricky because I would need to have them at the top level, in the QueryRenderer, and that feels a bit meh? I might add some there..
[CX-537]: https://artsyproduct.atlassian.net/browse/CX-537
> fix(formatting): Fix register text in auction

- CHANGELOG.yml
- src/lib/Scenes/Fair/Components/FairBoothHeader.tsx
- tslint.json
This PR resolves [MX-535]
Turns out the error was not from a gallery not being there, it was from a wrong if check.
We were checking on `!partnerFollowed` with `partnerFollowed: boolean | null | undefined`, which means that the above check would get be truthy for `null` (correctly), `undefined` (correctly), and `false` (incorrectly). Basically if the gallery was not followed, then we would not procceed, which would block us from following.
I changed the check from `!partnerFollowed` to `partnerFollowed == null` so it only becomes truthy in the `null` and `undefined` cases. I feel this is a nice way to check but if anyone can think of a better way, I'm open to suggestions.
As an extra thing, I thought I'll add …
> fix: Gallery follow button doesnt follow

- Artsy/App/AROptions.h
- Artsy/App/AROptions.m
- CHANGELOG.yml
- src/__generated__/Show2Query.graphql.ts
- src/__generated__/Show2TestsQuery.graphql.ts
- src/__generated__/Show2_show.graphql.ts
- src/lib/AppRegistry.tsx
- src/lib/Scenes/Show2/Show2.tsx
- src/lib/Scenes/Show2/__tests__/Show2-tests.tsx
- src/lib/navigation/__tests__/routes-tests.tsx
- src/lib/navigation/routes.tsx
- src/lib/store/NativeModel.ts
- src/setupJest.ts
This PR resolves [FX-2220]
(Collab with @sweir27)
This roughs in the routing and basic component setup for a new Show view. (No real design or data fetching work as of yet.)
It's a beaut!
[FX-2220]: https://artsyproduct.atlassian.net/browse/FX-2220
> feat: add new Show2 view, behind a lab option

- src/__generated__/Fair2MoreInfoQuery.graphql.ts
- src/__generated__/Fair2MoreInfoTestsQuery.graphql.ts
- src/__generated__/Fair2MoreInfo_fair.graphql.ts
- src/lib/Scenes/Fair/Screens/FairBMWArtActivation.tsx
- src/lib/Scenes/Fair2/Fair2MoreInfo.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2MoreInfo-tests.tsx
This PR resolves [FX-2231]
Adds a link to BMW art activations if the fair is sponsored.
[FX-2231]: https://artsyproduct.atlassian.net/browse/FX-2231
> feat: Display BMW art activations link on Fair2MoreInfo

- Artsy/App/ARAppDelegate+Emission.m
- Artsy/App/ArtsyEcho.h
- Artsy/App/ArtsyEcho.m
- emission/Pod/Classes/EigenCommunications/ARNotificationsManager.h
- emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m
- src/__generated__/VanityURLEntityQuery.graphql.ts
- src/__generated__/VanityURLEntity_fairOrPartner.graphql.ts
- src/lib/Scenes/VanityURL/VanityURLEntity.tsx
- src/lib/Scenes/VanityURL/__tests__/VanityURLEntity-tests.tsx
- src/lib/navigation/__tests__/routes-tests.tsx
- src/lib/navigation/__tests__/util-tests.ts
- src/lib/navigation/navigate.ts
- src/lib/navigation/routes.tsx
- src/lib/navigation/util.ts
- src/lib/store/NativeModel.ts
- src/setupJest.ts
This PR resolves [FX-2328]
This PR allows us to continue to show the _old_ fair view for certain fairs (configured via `LegacyFairSlugs` and `LegacyProfileSlugs`). This is necessary so that, when we launch the new view of fairs, any currently-running (or otherwise specified) fairs can continue to use the old view for a period of time.
Some notes:
- We need to route to the new or old view based on whether the `fairID` param is in that configured list. I couldn't find a "nice" way to do that in our new router, but I tried to make it as clean as possible. Will comment inline.
- Aside from the router, we have to include this logic in our `VanityURLEntity` renderer so we can correctly route from search results (and externally, based on `:profileSlug` …
> FX-2328: (feat) Adds legacyFairSlugs and legacyProfileSlugs for tailored fair routing #trivial

- src/__generated__/Fair2EditorialTestsQuery.graphql.ts
- src/__generated__/Fair2Editorial_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/VanityURLEntityQuery.graphql.ts
- src/lib/Scenes/Fair2/Components/Fair2Editorial.tsx
- src/lib/Scenes/Fair2/Components/Fair2ExhibitorRail.tsx
- src/lib/Scenes/Fair2/Components/Fair2Header.tsx
- src/lib/Scenes/Fair2/Components/SimpleTabs.tsx
- src/lib/Scenes/Fair2/Fair2.tsx
This PR resolves [FX-2310], [FX-2322]
This PR addresses some general spacing issues on the Fair view. The main change is to fix the way we handle spacing around our tab component. It's slightly tricky because:
- We want there to be a `safeAreaInsets.top` amount of padding on top of the tabs when they are stuck, so that we don't overlap with the top of the phone.
- zIndexes have questionable support in `FlatList`s 😅.
There's more description in-code. Many thanks to @pvinis for tackling this tricky one with me!
[FX-2310]: https://artsyproduct.atlassian.net/browse/FX-2310
[FX-2322]: https://artsyproduct.atlassian.net/browse/FX-2322
> fix: Fixes sticky tab spacing and a few other QA items for Fairs #trivial

- src/lib/Components/Bidding/Screens/RegistrationResult.tsx
- src/lib/Components/HoursCollapsible.tsx
- src/lib/Components/Markdown.tsx
- src/lib/Components/ReadMore.tsx
- src/lib/Components/__tests__/Markdown-tests.tsx
- src/lib/Scenes/Collection/Components/CollectionHubsRails/FeaturedCollections/FeaturedCollectionsRail.tsx
- src/lib/Scenes/Fair2/Components/Fair2Header.tsx
- src/lib/Scenes/Fair2/Fair2MoreInfo.tsx
- src/lib/Scenes/Feature/components/FeatureMarkdown.tsx
- src/lib/utils/__tests__/renderMarkdown-tests.tsx
- src/lib/utils/renderMarkdown.tsx
The type of this PR is: ** Feature**
I noticed while working on Fairs that we don't yet have great support for our new text styles within the existing `Markdown` component.
This PR takes a stab (using my best guess and existing tokens/variants) at providing support for this.
Within the ReadMore component:
Within the Markdown component:
> Adds support for new text styles within Markdown #trivial

- src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
- src/__generated__/ArtworkRefetchQuery.graphql.ts
- src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
- src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
- src/__generated__/InquiryModal_artwork.graphql.ts
- src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
- src/lib/__fixtures__/ArtworkFixture.ts
#3985 reverted this PR although there were no apparent issues. Re-trying without the merge commit to see if this passes CI on `master`
This PR resolves [PURCHASE-2096](https://artsyproduct.atlassian.net/browse/PURCHASE-2096)
Adds modal navigation questions to serve as entry points for the shipping, condition, and price inquiry flows.
> Add inquiry questions to inquiry modal flow

- src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
This PR resolves https://artsy.slack.com/archives/CN8S32FJR/p1601474431112100
We are keeping the `Modal` until we can work on https://artsyproduct.atlassian.net/browse/CX-681.
In order to make the dismissal on profile work, we need to pass it on to the Modal. When we `setIsSaving` to `false`, that will hide the modal. When the modal is hidden, it will then run the onDismiss to pop one screen back.
Before (doesnt pop to profile):
https://f.p0l.co/file/dropshare-public-pavlos/Screen-Recording-2020-10-08-at-15.45.05.mov
After (pops to profile):
https://f.p0l.co/file/dropshare-public-pavlos/Screen-Recording-2020-10-08-at-15.43.52.mov
Follow-up: bring #3950 up to speed with this PR.
> Using onDismiss of Modal to pop, once its hidden

- src/__generated__/MyCollectionArtworkModelUpdateArtworkMutation.graphql.ts
- src/lib/Scenes/MyCollection/Boot.tsx
- src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/AddEditModal.tsx
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/__tests__/AddEditModal-tests.tsx
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Form/artworkSchema.tsx
- src/lib/Scenes/MyCollection/Screens/AddArtwork/__tests__/AddEditArtwork-tests.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
- src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
- src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
This PR roughs in some patterns around global loading and error handling while performing different mutation operations on MyCollection. 
The flow:
- The navigation model listens for various artwork actions (add / edit / delete) and toggles `isLoading` to true
- Views can then tap into the `isLoading` state and display a loading indicator, etc
Note that I tried to take advantage of the `LoadingModal` component in Eigen but ran into a hard blocker -- since most of our operations take place modally, from within the FancyModal component, we can't display the `LoadingModal` because of a hard iOS limitation around displaying only **one** modal at a time.  (cc @pvinis and @MounirDhahri)
In place of this limitation I'm just displaying "loading" text in the …
> Feature: [MyCollection] Add global loading / error handing

- src/lib/Scenes/Fair2/Components/Fair2Exhibitors.tsx
- src/lib/Scenes/Fair2/Fair2MoreInfo.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Exhibitors-tests.tsx
- src/lib/utils/track/schema.ts
Fixes some analytics naming mistakes in our `Fair2` feature.
> Fix: Update incorrect analytics fields #trivial

- src/__generated__/Fair2CollectionsTestsQuery.graphql.ts
- src/__generated__/Fair2Collections_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/VanityURLEntityQuery.graphql.ts
- src/lib/Scenes/Fair2/Components/Fair2Collections.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Collections-tests.tsx
- src/lib/Scenes/Search/SearchResult.tsx
- src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx
This PR fixes two issues:
1. Clicking into "Photo London Fair" search result led to an "Unable to load" screen. This is actually a bug in the current app version, due to some mismatch between the `slug` returned from the search result and the `href`. I believe that `href` [should be the correct field](https://github.com/artsy/metaphysics/blob/3f16e6c5a9c0f2e40bb91ab00cddad5ff307b1eb/src/schema/v2/SearchableItem/SearchableItemPresenter.ts#L50-L51).
2. Collections return `null` for their `internalID` field. I [created a ticket](https://artsyproduct.atlassian.net/browse/FX-2343) to address the underlying issue (either in MP or KAWS), but this will fix the current problem within eigen.
> fix: Fixes a few issues from fair QA #trivial

- src/__generated__/RegistrationCreateBidderMutation.graphql.ts
- src/lib/Components/Bidding/Screens/Registration.tsx
This PR resolves [CX-546]
(I paired with @MounirDhahri on this.)
Return the user's `registrationStatus` for the `createBidder` mutation, so that the Relay state is immediately updated.
[CX-546]: https://artsyproduct.atlassian.net/browse/CX-546
> fix: Update bidder registration status upon registration

- CHANGELOG.yml
- src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
- src/__generated__/ArtworkRefetchQuery.graphql.ts
- src/__generated__/CollapsibleArtworkDetailsTestsQuery.graphql.ts
- src/__generated__/CollapsibleArtworkDetails_artwork.graphql.ts
- src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
- src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
- src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
- src/lib/Scenes/Artwork/Components/ArtworkDetailsRow.tsx
- src/lib/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tsx
- src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
- src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CollapsibleArtworkDetails-tests.tsx
- src/lib/__fixtures__/ArtworkFixture.ts
This PR resolves [PURCHASE-2154].
Following up on https://github.com/artsy/eigen/pull/3883, this adds the full artwork details in the inquiry modal. I also take this opportunity to improve the expand/collapse animation. More details inline.
[PURCHASE-2154]: https://artsyproduct.atlassian.net/browse/PURCHASE-2154
> feat: full artwork details in inquiry modal; improve UI (PURCHASE-2154)

- src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
- src/__generated__/ArtworkRefetchQuery.graphql.ts
- src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
- src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
- src/__generated__/InquiryModal_artwork.graphql.ts
- src/lib/Scenes/Artwork/Artwork.tsx
- src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
- src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
- src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
- src/lib/__fixtures__/ArtworkFixture.ts
- src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
- src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
- src/lib/utils/ArtworkInquiry/__tests__/ArtworkInquiryStore-tests.tsx
This PR resolves [PURCHASE-2096]
This PR adds a context provider around the Artwork app to enable passing and persisting state between views in the inquiry modal.
This is an initial pass, so we can safely assume the shape of the global data state will evolve.
[PURCHASE-2096]: https://artsyproduct.atlassian.net/browse/PURCHASE-2096
> PURCHASE Add Artwork context provider for passing/persisting modal state

- CHANGELOG.yml
- src/__generated__/Fair2ArtworksInfiniteScrollGridQuery.graphql.ts
- src/__generated__/Fair2ArtworksTestsQuery.graphql.ts
- src/__generated__/Fair2Artworks_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/VanityURLEntityQuery.graphql.ts
- src/lib/Scenes/Fair2/Components/Fair2Artworks.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Artworks-tests.tsx
- src/lib/data/constants.ts
- src/lib/tests/renderWithWrappers.tsx
This PR resolves [FX-2346]
The artwork grid on the Fairs2 screen shows artworks in batches of 20. 
This updates the batch size to 30, per the design spec. The new batch size is effect for show more pagination, as well as for refetching in response to filter changes.
[FX-2346]: https://artsyproduct.atlassian.net/browse/FX-2346
> fix: change Fairs2 artwork grid batch size from 20 to 30

- src/__generated__/Fair2HeaderTestsQuery.graphql.ts
- src/__generated__/Fair2Header_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/VanityURLEntityQuery.graphql.ts
- src/lib/Scenes/Fair2/Components/Fair2Header.tsx
- src/lib/Scenes/Fair2/Fair2MoreInfo.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Header-tests.tsx
This PR resolves [FX-2351]
Adds checks for fair sponsored content or fair coordinates and renders the "More Info" link if the fair has either.
Previously this fair did not show a "More Info" link and now it does:
[FX-2351]: https://artsyproduct.atlassian.net/browse/FX-2351
> fix: Show More Info link when there is sponsored content or a location map

- src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistAuctionResults-tests.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistMarket-tests.tsx
- src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
This PR resolves 
- https://artsyproduct.atlassian.net/browse/CX-701
- https://artsyproduct.atlassian.net/browse/CX-700
This fixes an issue where on artwork delete, the form is still populated. This is because we "load" the form on edit button click, but then don't reset the form on delete (which happens from the edit screen). When a user goes to add a new work, the form appears populated with the work that was just deleted. This fixes that. 
Also makes it so that the entire auctions section is clickable, taking the user to `/artist/id/auction-results`, and removes the "optional" text around photo addition (since we require 1 photo before a work can be submitted).
> Fix: [My Collection] reset form on delete; auction list click

- src/__generated__/Fair2HeaderTestsQuery.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/lib/Scenes/Fair2/Fair2.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Header-tests.tsx
Pulling this out of a [PR](https://github.com/artsy/eigen/pull/4016) that's toward [FX-2347] — this was a good opportunity to update a bunch of tests to the [new mocking pattern](https://github.com/artsy/eigen/pull/3960) involving `MockPayloadGenerator`
(Only covers `Fair2` and `Fair2-Header`, as those are the components I was touching in [the other PR](https://github.com/artsy/eigen/pull/4016) — updating other specs would be worthwhile too, maybe #FF)
Once this is merged I'll open that PR for review.
[FX-2347]: https://artsyproduct.atlassian.net/browse/FX-2347
> refactor: update some Fair2 tests to new mocking pattern

- src/__generated__/Fair2ExhibitorsTestsQuery.graphql.ts
- src/__generated__/Fair2Exhibitors_fair.graphql.ts
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/VanityURLEntityQuery.graphql.ts
- src/lib/Scenes/Fair2/Components/Fair2Exhibitors.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Exhibitors-tests.tsx
- src/lib/data/constants.ts
This PR resolves [FX-2346].
Updates pagination to show 30 exhibitors at a time instead of 20. Also updates exhibitors test to use new testing pattern.
[FX-2346]: https://artsyproduct.atlassian.net/browse/FX-2346
> fix: Update paging for exhibitors to 30 shows at a time

- CHANGELOG.yml
- src/__generated__/Show2InstallShots_show.graphql.ts
- src/__generated__/Show2Query.graphql.ts
- src/__generated__/Show2TestsQuery.graphql.ts
- src/__generated__/Show2_show.graphql.ts
- src/lib/Scenes/Show2/Components/Show2InstallShots.tsx
- src/lib/Scenes/Show2/Show2.tsx
- src/lib/Scenes/Show2/__tests__/Show2-tests.tsx
This PR resolves [FX-2222]
Built off https://github.com/artsy/eigen/pull/4010 so once that's merged those SHAs go away here... Will convert to ready once it's merged. cc @sweir27 
There should likely be another issue about what happens if these images are tapped, which isn't clear from the spec.
[FX-2222]: https://artsyproduct.atlassian.net/browse/FX-2222
> feat(show2): implements show2 installation shot carousel

- CHANGELOG.yml
- src/__generated__/Fair2Query.graphql.ts
- src/__generated__/Fair2TestsQuery.graphql.ts
- src/__generated__/Fair2_fair.graphql.ts
- src/__generated__/VanityURLEntityQuery.graphql.ts
- src/lib/Scenes/Fair2/Components/Fair2Header.tsx
- src/lib/Scenes/Fair2/Fair2.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2Header-tests.tsx
This PR resolves [FX-2347]
To be consistent with the current Fair view this PR updates the Fair2 view to be pared down for inactive fairs:
Also updates handling for missing images (which maybe shouldn't happen, but I was able to navigate to this one from City Guide, e.g.)
[FX-2347]: https://artsyproduct.atlassian.net/browse/FX-2347
> feat: add inactive fair state to Fair2

- src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkList/__tests__/MyCollectionArtworkListItem-tests.tsx
- src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
This PR resolves [CX-703]
Use local path to display photo in users collection list while photo is processing. 
- Adds an additional lastPhotoUploaded field to the session state
- When rendering artwork list view use this as a backup if imageURL is not present
Note: I  initially tried to use relay's optimisticResponse for this but ultimately decided against it because it requires recreating an entire fake artwork model object and we only really need the local path to the last uploaded photo. If there is a better way please let me know.
Co-authored with @bhoggard
Co-authored with @damassi 
[CX-703]: https://artsyproduct.atlassian.net/browse/CX-703
> fix: fallback to local photo when processing

- CHANGELOG.yml
- src/lib/Scenes/VanityURL/VanityURLEntity.tsx
- src/lib/Scenes/VanityURL/__tests__/VanityURLEntity-tests.tsx
- src/lib/utils/renderWithPlaceholder.tsx
When #3867 was merged while I was away, it broke the `VanityURLEntity` fallback handling which depended on the old `principalField` behaviour. Here I added a special `renderFallback` option to our `renderWithPlaceholder` utility so that when metaphysics errors out we can show something other than the `LoadFailureView`, in this case we show our `VanityURLPossibleRedirect` fallback component.
> fix: vanity url fallback handling

- CHANGELOG.yml
- src/__generated__/Show2Info_show.graphql.ts
- src/__generated__/Show2MoreInfoQuery.graphql.ts
- src/__generated__/Show2MoreInfoTestsQuery.graphql.ts
- src/__generated__/Show2MoreInfo_show.graphql.ts
- src/__generated__/Show2Query.graphql.ts
- src/__generated__/Show2TestsQuery.graphql.ts
- src/__generated__/Show2_show.graphql.ts
- src/lib/AppRegistry.tsx
- src/lib/Scenes/Show2/Components/Show2Info.tsx
- src/lib/Scenes/Show2/Screens/Show2MoreInfo.tsx
- src/lib/Scenes/Show2/Show2.tsx
- src/lib/Scenes/Show2/__tests__/Show2MoreInfo-tests.tsx
- src/lib/Scenes/Show2/index.ts
- src/lib/navigation/routes.tsx
This PR resolves [FX-2223]
Implements a "more information" screen with basic info (about/press release). I'd like us to handle the following as separate tickets as there's some complexity to each sub-task:
* Extract PartnerCard from the artwork and utilize it here
* Display open hours
* Display location with map
[FX-2223]: https://artsyproduct.atlassian.net/browse/FX-2223
> feat(show2): sets up more information route with basic information

- Artsy/App/ARScreenPresenterModule.m
- Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h
- CHANGELOG.yml
#3771 introduced a regression for deep link handling when the app is closed. The app would open to the home screen. See slack context: https://artsy.slack.com/archives/C9EK04NV6/p1602799492003700
The problem was that the `ARScreenPresenterModule` was asking the `ARTopMenuViewController` to present a screen before it had fully initialized. This PR makes it wait until everybody's ready.
Note that this code is extremely temporary and will be refactored away in my next android PR.
> fix: deep link handling

- package.json
- src/lib/Scenes/Fair2/Components/Fair2FollowedArtistsRail.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2FollowedArtistsRail-tests.tsx
- yarn.lock
This PR resolves [FX-2337]
Updates Cohesion and adds tracking for tapping on `View all` button on `Fair2FollowedArtistsRail`.
[FX-2337]: https://artsyproduct.atlassian.net/browse/FX-2337
> chore: Add tracking for View All button on artworks by artists you follow rail #trivial

- src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
After the last PR #3950 we merged, I found out there is a way to have named items in arrays in ts, so I used that and removed a couple of `any`s introduced in that last PR.
> fix(types): removed some `any`s

- src/lib/Scenes/Sale/Components/SaleArtworkListItem.tsx
This PR resolves Sam's comment here: https://artsyproduct.atlassian.net/browse/CX-519
- Center the text items within the saleArtworks
> fix: center text items withing the sale artwrorks items

- CHANGELOG.yml
- src/__generated__/Fair2AllFollowedArtistsQuery.graphql.ts
- src/__generated__/Fair2AllFollowedArtistsTestsQuery.graphql.ts
- src/__generated__/Fair2AllFollowedArtists_fairForFilters.graphql.ts
- src/lib/Scenes/Fair2/Components/Fair2Artworks.tsx
- src/lib/Scenes/Fair2/Fair2AllFollowedArtists.tsx
- src/lib/Scenes/Fair2/__tests__/Fair2AllFollowedArtists-tests.tsx
This PR resolves [FX-2358]
cc/ @sweir27 
When navigating from the new fair screen to the "Works by Artists I Follow" artwork grid, we set an initial filter. This initial filter causes the filter options (backed by aggregations) to also be scoped to the initial filter. A user can disable the initial filter, but the aggregations will not update to reflect the complete set of available filters for the unscoped artworks.
This commit prefetches the artwork aggregations and passes them into the artwork grid component.
_Note fewer mediums available to filter by._
[FX-2358]: https://artsyproduct.atlassian.net/browse/FX-2358
> fix: provide complete filter options for Works by Artists I Follow grid

- Artsy/App/AROptions.m
This PR resolves [FX-2304]
Removes the Fair2 lab option in favor of using Echo. The Echo feature flag already exists.
[FX-2304]: https://artsyproduct.atlassian.net/browse/FX-2304
> chore: remove Fair2 lab option in favor of using Echo

- CHANGELOG.yml
- src/__generated__/Show2ArtworksInfiniteScrollGridQuery.graphql.ts
- src/__generated__/Show2ArtworksTestsQuery.graphql.ts
- src/__generated__/Show2Artworks_show.graphql.ts
- src/__generated__/Show2_show.graphql.ts
- src/lib/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
- src/lib/Components/FilterModal/FilterModal.tsx
- src/lib/Scenes/Show2/Components/Show2Artworks.tsx
- src/lib/Scenes/Show2/Show2.tsx
- src/lib/Scenes/Show2/__tests__/Show2Artworks-tests.tsx
- src/lib/data/constants.ts
This adds the artwork filter onto the show view. I checked out the fair view for inspiration, but of course there are some differences (for instance, since shows aren't large we don't need the artist filter, and since shows are at a single partner, we don't need the gallery or institution filter, etc.)
> @dzucconi => feat(show2): implement artwork grid + filter

- CHANGELOG.yml
- src/lib/Scenes/Home/Components/SalesRail.tsx
- src/lib/Scenes/Sale/helpers.ts
- src/lib/Scenes/Sales/Components/SaleListItem.tsx
This PR resolves [CX-731]
Fixes capitalization in home rail, by reusing the logic we have for the auctions screen.
[CX-731]: https://artsyproduct.atlassian.net/browse/CX-731
> fix(home): auctions rail capitalization

- src/lib/Scenes/Sale/Sale.tsx
This PR resolves [CX-719]
- Filter button overlaps artwork grid content when scrolled to the bottom
[CX-719]: https://artsyproduct.atlassian.net/browse/CX-719
> fix: filter button overlaps artwork grid content

- src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
- src/lib/Scenes/Sale/__tests__/RegisterToBidButton-tests.tsx
This PR resolves [CX-732]
- Make "You're approved to bid" copy  in Medium weight text instead of regular weight text
**Before**
**After**
[CX-732]: https://artsyproduct.atlassian.net/browse/CX-732
> fix: adjust typography on you're approved to bid

- CHANGELOG.yml
- HACKS.md
- patches/react-native-image-crop-picker+0.32.2.patch
This PR resolves [CX-711]
We do some swizzling in the AppDelegate that causes  `[[UIApplication sharedApplication] delegate] window]` to return nil. react-native-image-crop-picker uses this method to find the viewController to present the picker onto so we had a patch that grabbed the last window in the hierarchy to workaround this issue. In the My Collection flow this was returning the wrong window, specifically a UIInputWindow that manages presentation of the keyboard. This PR updates our existing patch for react-native-image-crop-picker to look for our custom window subclass instead which should return the correct window, and falls back to the last window if it can't find the subclass.
[CX-711]: https://artsyproduct.atlassian.net/browse/CX-711
> fix: select correct window in react-image-crop-picker when input window is present

- Podfile
- Podfile.lock
I think this is all that's required to update us to the latest FB SDK but lmk if I am missing something! Seems trivial enough that I'm going to mark this PR as squash on green. 👍 
https://artsyproduct.atlassian.net/browse/GRO-29
> chore: update FB SDK

- Makefile
Deploys on Circle CI started failing a few days ago:
```
brew install getsentry/tools/sentry-cli
v12.16.2 is already installed.
Now using node v12.16.2 (npm v6.14.4)
default -> v12.16.2 *
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
==> Tapping getsentry/tools
Cloning into '/usr/local/Homebrew/Library/Taps/getsentry/homebrew-tools'...
remote: Enumerating objects: 20, done.        
remote: Counting objects: 100% (20/20), done.        
remote: Compressing objects: 100% (15/15), done.        
remote: Total 516 (delta 4), reused 0 (delta 0), pack-reused 496        
Receiving objects: 100% (516/516), 58.49 KiB | 4.87 MiB/s, done.
Resolving deltas: 100% (183/183), done.
Tapped 1 formula (28 files, …
```
> chore: fix Sentry CLI installation on beta deploys #trivial

- src/__generated__/AutosuggestResultsQuery.graphql.ts
- src/lib/Components/AboveTheFoldFlatList.tsx
- src/lib/Scenes/Search/AutosuggestResults.tsx
- src/lib/Scenes/Search/__tests__/AutosuggestResults-tests.tsx
This PR resolves [CX-734]
Fix the issue with the search box not showing more results.
**PS**: It's also been broken in production for a while.
[CX-734]: https://artsyproduct.atlassian.net/browse/CX-734
> fix: infinite scroll not working

- src/lib/Scenes/Sale/Components/SaleArtworksRail.tsx
- src/lib/Scenes/Sale/__tests__/SaleArtworksRail-tests.tsx
This PR resolves [CX-716]
- Fix: If there are no lots by artists that the user follows, hide this section
- I also added a regression test to avoid this in the future
_When the user **has lots** from artists he's following_
_When the user **has no lots** from artists he's following_ 
[CX-716]: https://artsyproduct.atlassian.net/browse/CX-716
> fix: hide lots artists if the user has no follows

- src/lib/Scenes/Sale/Components/SaleLotsList.tsx
- src/lib/Scenes/Sale/__tests__/SaleLotsList-tests.tsx
(cherry picked from commit 53c1e7d94432ba0b8ddaa812f76c3fac24007644)
This PR resolves [CX-721]
When sorting by a different method, we should also change the subtitle above the grid to reflect that method, i.e.
[CX-721]: https://artsyproduct.atlassian.net/browse/CX-721
> fix: show the right filtering subtitle

- CHANGELOG.yml
- src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/lib/Scenes/Fair2/Components/Fair2Artworks.tsx
- src/lib/Scenes/Fair2/Components/SimpleTabs.tsx
- src/lib/Scenes/Fair2/Fair2.tsx
This PR resolves [CX-556]
- Fixes the scroll jump that happened when you switch tab.
This happened because the `InfiniteScrollArtworkGrid` component needs to know how wide it is to layout its masonry grid manually. By default it needs to wait until it has mounted to have an `onLayout` callback invoked. This causes a single frame to be rendered where the content has no height. To fix that we allow manually specifying a width so that the content can be laid out before first paint. We could also have worked around this issue in this one case by adding a `min-height: screenHeight` style, but I went for the general-purpose solution since we are likely to need it again one day.
- Hides the back button while the user scrolls down. Otherwise the back button obscures one of the sticky tabs.
- Make …
> fix(fair2): sticky tabs interactions + UI

- src/lib/Scenes/Show2/Components/Show2Artworks.tsx
- src/lib/Scenes/Show2/Show2.tsx
- Moves component out of container to avoid refresh when changing iews
- Restores zero state for filter
> fix: avoid needless show artwork grid refresh as views change

- src/lib/Components/FilterModal/FilterModal.tsx
- src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
- src/lib/utils/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
This PR resolves [CX-718]
- If you filter for an artist, the top-level filter modal shows the artist-slug instead of the artist name
___
**Before the changes**
**After the changes**
[CX-718]: https://artsyproduct.atlassian.net/browse/CX-718
> fix: add artist names to filtermodal

- src/lib/Scenes/Sale/Components/SaleLotsList.tsx
- src/lib/Scenes/Sale/Sale.tsx
- src/lib/Scenes/Sale/__tests__/SaleLotsList-tests.tsx
This PR resolves [CX-733]
Instead of staying in the same scroll position on the page, we should instantly move users to the top of the list after applying any filtering/sorting
[CX-733]: https://artsyproduct.atlassian.net/browse/CX-733
> fix: scroll to top after applying filters

- src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
- src/lib/Scenes/MyProfile/MyProfile.tsx
- src/lib/Scenes/MyProfile/__tests__/MyProfile-tests.tsx
This PR resolves [CX-756]
Updates copy in My Collection pages from "Artwork Insights" to "My Collection"
[CX-756]: https://artsyproduct.atlassian.net/browse/CX-756
> chore: update copy in my collection #trivial

- src/lib/Components/FilterModal/FilterModal.tsx
The type of this PR is: BUG
This PR resolves [CX-720]
[CX-720]: https://artsyproduct.atlassian.net/browse/CX-720
> bug: Disable sale artworks clear-all-filters button if 0 filters selected

- src/palette/svgs/sf/StarCircleFill.tsx
This PR resolves [PURCH-2169]
Fixes a small SVG bug where won lots under the My Bids closed tabs showed the artwork through the icon.
Before:
After:
> [Purchase-2169] SVG bugfix on closed/won auction star icons

- CHANGELOG.yml
- src/lib/Scenes/Sale/Components/SaleHeader.tsx
- src/lib/Scenes/Sale/__tests__/SaleHeader-tests.tsx
This PR resolves [CX-523]
- Add auction closed banner
[CX-523]: https://artsyproduct.atlassian.net/browse/CX-523
> feat: add auction closed banner

- CHANGELOG.yml
- src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
This PR resolves [CX-769]
Updates check to be string comparison rather than existence. 
[CX-769]: https://artsyproduct.atlassian.net/browse/CX-769
> fix: fix title for add artwork modal #trivial

- CHANGELOG.yml
- src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
This PR resolves [CX-785]
I couldn't reproduce the exact behavior described in the ticket but I am assuming this is the bug, when starting to edit an artwork in your collection and dismissing the modal and then adding an artwork, the details of the edited artwork appear in the form. Fixed by resetting the form in the cancelAddOrEditArtwork action when editing. 
Found another bug while fixing this one that is visible in gif above, the text is updating to the "Add" artwork copy when dismissing the edit modal. Bug filed here: https://artsyproduct.atlassian.net/browse/CX-790
[CX-785]: https://artsyproduct.atlassian.net/browse/CX-785
> fix: reset form when leaving edit modal

- src/lib/Components/States/ZeroState.tsx
- src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
This PR resolves [CX-767]
Moves the zero state component to the centre of the screen. Also reduces the font size.
[CX-767]: https://artsyproduct.atlassian.net/browse/CX-767
> fix(my collection): artwork list empty state alignment #trivial

- CHANGELOG.yml
- src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
This PR resolves [CX-768]
Adds props to scrollview to prevent keyboard intercepting initial tap. Thanks @ds300 for the pointer this would have taken me a while to figure out 🙌 
[CX-768]: https://artsyproduct.atlassian.net/browse/CX-768
> fix: prevent keyboard touch intercept #trivial

- CHANGELOG.yml
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/ArtistSearchResult.tsx
This PR resolves [CX-780]
This PR fixes a bug where long artist names would push the 'remove' button off the screen.
✨ **bonus** :sparkles:
- the artist name was in the wrong font (using RN's `Text` component rather than the palette `Text`)
- the remove button had the wrong text size
[CX-780]: https://artsyproduct.atlassian.net/browse/CX-780
> fix(my collection add/edit artwork): truncate artist name

- CHANGELOG.yml
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AddPhotos.tsx
- src/palette/svgs/XCircleIcon.tsx
This PR resolves [CX-779]
Some layout re-jigging to get the photos to lay themselves out in a grid. Also, I edited the close button SVG to use a white circle background instead of a square, in order to provide the appearance of a 2px white border.
Note that I can't actually get photos to save, so I've illustrated the layout by adding a background color to the photo components in this image:
[CX-779]: https://artsyproduct.atlassian.net/browse/CX-779
> fix(my collection): photo list layout in add artwork

- src/lib/Scenes/Sale/Components/SaleHeader.tsx
- src/lib/Scenes/Sale/__tests__/SaleHeader-tests.tsx
The auction screen now shows "auction is closed" always. It should instead show "auction is closed" only if an auction `endAt` already passed.
> fix(SaleHeader): auction closed bug

- src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/Dimensions.tsx
- src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AdditionalDetails.tsx
This PR resolves [CX-786]
This specifies keyboard types for the Add Artwork form:
- Dimensions (height/width/depth): numeric with decimal
- Edition (number/size): numeric
- Price paid: numeric with decimal
- Date: numeric with punctuation
The Date field is not ideal - I wonder whether we should change the label to "Year" and then have a straight numeric keyboard @joanna20 ? Or just leave it as "Date" but use a numeric keyboard?
[CX-786]: https://artsyproduct.atlassian.net/browse/CX-786
> fix(my collection): set correct keyboard types #trivial

- CHANGELOG.yml
- src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
- src/palette/elements/Button/Button.tsx
This PR resolves [CX-772]
Disables the save button in the _Edit Artwork_ form until the user makes changes. Additionally improves the styling of the delete button. (Does that new variant name look alright to you @ds300 ?)
[CX-772]: https://artsyproduct.atlassian.net/browse/CX-772
> fix(my collection): button improvements in add artwork form

- src/__generated__/Show2MoreInfoQuery.graphql.ts
- src/__generated__/Show2MoreInfoTestsQuery.graphql.ts
- src/__generated__/Show2MoreInfo_show.graphql.ts
- src/lib/Scenes/Show2/Components/Show2Hours.tsx
- src/lib/Scenes/Show2/Components/Show2Location.tsx
- src/lib/Scenes/Show2/Screens/Show2MoreInfo.tsx
- src/lib/Scenes/Show2/__tests__/Show2MoreInfo-tests.tsx
This PR resolves [FX-2408]
I think this pattern of rendering is very brittle because of the implicit linking between the parent context and the rendered children which may have conditionals that drift. I don't really have any good answers for this. I could imagine some kind of interface where a component contains its own guard for rendering. For now this just syncs them up.
[FX-2408]: https://artsyproduct.atlassian.net/browse/FX-2408
> fix(fx-2408): improves guards for rendering hours and locations #trivial

- src/lib/utils/AboveTheFoldQueryRenderer.tsx
While trying to figure out some caching issues in the new sale screen I realized we are missing the `cacheConfig` as a prop.
> fix: add missing prop to above the fold query renderer

- src/lib/Components/ArtworkFilterOptions/SortOptions.tsx
- src/lib/Scenes/Sale/__tests__/SaleLotsList-tests.tsx
This PR resolves [CX-793]
- Fix Reverted sale artworks sorting options.
[CX-793]: https://artsyproduct.atlassian.net/browse/CX-793
> fix: reverted sale artworks sorting options

- src/lib/Scenes/Show2/Components/Show2Header.tsx
This PR resolves [FX-2404]
This simply causes the timer to update once per second. We don't need to do any fancy syncing with the server for millisecond offsets or anything since this isn't an auction.
The ticket says to use the same component in viewing rooms. However:
* That component isn't entirely shared. [Part of it lives in viewing rooms and is specific to viewing rooms status.](https://github.com/artsy/eigen/blob/b9caccdd3a487a199095413e5bd9984de7dfe6ea/src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx#L50-L75)
* We already use this hook on fairs
So rather than use viewing rooms' component: we should settle on a detailed spec for how to format time, update the hook to match that spec, then refactor the viewing rooms header to use the …
> fix(show2): updates remaining time once per second #trivial

- src/lib/Components/Bidding/Screens/BillingAddress.tsx
This PR resolves [CX-801]
Switch the keyboard for Phone # to the numeric keyboard on Billing Address.
[CX-801]: https://artsyproduct.atlassian.net/browse/CX-801
> fix: add keyboard type for phone number on billing address

- src/lib/Components/ArtworkFilterOptions/MediumOptions.tsx
- src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx
This PR resolves [CX-796]
- Add extra padding on single option filters screens
**Before** 
____
**After**
[CX-796]: https://artsyproduct.atlassian.net/browse/CX-796
> fix: extra padding on single option filters screens
