artsy/eigen

src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
This PR resolves [CX-990]
Properly format number of results
[CX-990]: https://artsyproduct.atlassian.net/browse/CX-990
=> fix: properly format large numbers

fastlane/metadata/en-US/release_notes.txt
**Description:**
Set release notes for 6.7.7
=> update release notes for 6.7.7

package.json, src/lib/AndroidApp.tsx, src/lib/Components/CreditCardDetails.tsx, src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
- Fixed the UI problem with the card number in profile
Before
After
- add a yarn script for opening a URL in the app.
To be used like `yarn open-url artsy:///search --android`. Taken from davids notion page, and turned into a script.
- remove a fragment that I saw that was not really needed.
- add relay env provider for android, so viewing rooms work, because of relay hooks.
=> fixes(small): 4 small things, packaged nicely into one PR

package.json, src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkHeader_artwork.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx, yarn.lock
Small PR to use cohesion for tracking on share events.
=> enhancement(analytics): use cohesion

package.json, src/__generated__/ArtistBelowTheFoldQuery.graphql.ts, src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts, src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts, src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts, src/__generated__/ArtistInsightsTestsQuery.graphql.ts, src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx, src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx, src/lib/Components/FilterModal/FilterModal.tsx, src/lib/Scenes/AuctionResult/AuctionResult.tsx, yarn.lock
This PR resolves [CX-833]
- Analytics tracking bugs
[CX-833]: https://artsyproduct.atlassian.net/browse/CX-833
=> feat: fix screen tracking on auction results

CHANGELOG.yml, src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx, src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx, src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsightsAuctionResults-tests.tsx, src/lib/Components/ArtworkFilterOptions/ArtistIDsSaleArtworksOptionsScreen.tsx, src/lib/Components/ArtworkFilterOptions/MultiSelectCheckOption.tsx, src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
This PR resolves [CX-971]
- Scroll to the top after applying a filter on auction results
https://user-images.githubusercontent.com/11945712/107645936-aaf5a500-6c79-11eb-9a0f-3679249bda17.mov
- Fix padding issue on medium/size filters options screens
**On Medium Filter**
_Before_
_After_
**On Size Filter**
_Before_
_After_
[CX-971]: https://artsyproduct.atlassian.net/browse/CX-971
=> feat: scroll to the top after applying a filter on auction results

src/lib/AndroidApp.tsx, src/lib/Components/FilterModal/FilterModal.tsx, src/lib/Components/OpaqueImageView/OpaqueImageView.tsx, src/lib/NativeModules/GraphQLQueryCache.ts, src/lib/NativeModules/LegacyNativeModules.tsx, src/lib/Scenes/Search/Search.tsx, src/lib/Scenes/VanityURL/VanityURLPossibleRedirect.tsx, src/lib/navigation/BackButton.tsx, src/lib/navigation/__tests__/navigate-tests.tsx, src/lib/navigation/navigate.ts, src/lib/store/GlobalStore.tsx, src/lib/utils/__tests__/hardware-tests.ts, src/lib/utils/hardware.ts
Quickly addressing many tiny issues that we found during the screen audit (most of the things marked `[super-quick]` on https://www.notion.so/artsy/First-Android-Screen-Audit-Findings-3e3c302cdfd047308b9ba76b77802b3d )
=> chore: small android fixes

src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
This PR resolves [CX-1065]
**Make the following copy updates:**
- "Market Signals by Medium -> change to "Market Signals"
- (In Info modal next to Market Signals) -> change last paragraph to 
"In this data set, please note that the sale price includes the hammer price and buyer’s premium, as well as any other additional fees (e.g., Artist’s Resale Rights). The data set only includes works valued over $1,000."
- "Yearly lots sold" -> change to "Average yearly lots sold"
[CX-1065]: https://artsyproduct.atlassian.net/browse/CX-1065
=> chore: auction results copy updates #trivial

CHANGELOG.yml, package.json, src/lib/Components/AuctionResult/AuctionResultMidEstimate.tsx, src/lib/Scenes/Fair/Components/SimpleTabs.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx, src/palette/elements/Box/Box.tsx, src/palette/elements/Box/__tests__/Box-tests.tsx, src/palette/elements/Cards/CardTag.tsx, src/palette/helpers/styled-system/position.ts, src/palette/helpers/styled-system/space.ts, src/palette/helpers/styled-system/transforms.ts, src/palette/helpers/types.ts, src/palette/svgs/Icon.tsx, yarn.lock
Quick addition to your custom type handling. Now `top`, `bottom`, `left`, `right` are handled the same way, and we also support percentages too, like `top="10%"`.
=> enhancement(palette): position (left, top, bottom, right) is the same as space (ml, mx, etc) now, and we added %

src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
This PR resolves Joanna's comment here
_https://artsyproduct.atlassian.net/browse/CX-1065?focusedCommentId=34981_
=> chore: remove heritage from auction results info modal #trivial

CHANGELOG.yml, src/lib/NativeModules/presentEmailComposer.ts, src/lib/Scenes/MyProfile/MyProfile.tsx
This PR resolves [CX-1062]
Open default mail client in Android when the user taps on _Send Feedback_.
[CX-1062]: https://artsyproduct.atlassian.net/browse/CX-1062
=> fix(android): send email

src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
This PR resolves [CX-1065]
Updates market signals copy, fixes info button padding.
[CX-1065]: https://artsyproduct.atlassian.net/browse/CX-1065
=> chore: update market signals copy

Podfile.lock, package.json, src/lib/ErrorReporting.ts, yarn.lock
This PR is related to [CX-867]
This PR just updated to latest sentry and enables the release health tracking. After this is merged I will release a beta to test it out.
Also, a call to `setRelease` is removed because it is not deprecated. The `release` key in the `init` config should be enough to set it.
[CX-867]: https://artsyproduct.atlassian.net/browse/CX-867
=> enhancement(sentry): enable release health tracking

scripts/setup-distribute-linux
trivial fix, gonna self-merge and push a beta
=> fix(ci): make aws install idempotent

docs/getting_started.md
This PR updates the Android setup instructions with a few necessary ENV vars. See [this slack convo](https://artsy.slack.com/archives/C02BAQ5K7/p1614730384038900) for more info.
=> docs: Add ENV vars for Android setup

src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
This PR resolves [CX-907]
Fixes a remaining bug with saving pricePaid, we missed passing pricePaidCurrency to the edit mutation. 
[CX-907]: https://artsyproduct.atlassian.net/browse/CX-907
=> fix: save pricePaid currency on edit #trivial

renovate.json
I just saw @ashfurrow's name here still. Better not bug him with that anymore :D.
=> volunteer to help with the upgrades

CHANGELOG.yml, src/lib/Components/FancyModal/FancyModal.tsx, src/lib/utils/useScreenDimensions.tsx
This PR resolves [CX-1202]
- Fix **FancyModal** height on android
[CX-1202]: https://artsyproduct.atlassian.net/browse/CX-1202
=> fix: android keyboard height on android

docs/developing_a_feature.md
The type of this PR is: Documentation
This PR adds information about accessing the admin menu and overriding feature flags to the [Developing a Feature](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md) doc.
=> docs: share learnings from adding a feature flag

fastlane/metadata/en-US/release_notes.txt
=> chore: update release notes

CHANGELOG.yml, src/lib/AndroidApp.tsx, src/lib/Components/SearchInput.tsx
- Fix buggy search input animation
- This serves as an example on how we might solve some of the issues here https://artsyproduct.atlassian.net/browse/CX-1096
**Before**
https://user-images.githubusercontent.com/11945712/111333117-a7877c00-8672-11eb-8d12-7dfb71d71e01.mov
___
**After**
https://user-images.githubusercontent.com/11945712/111333108-a5bdb880-8672-11eb-922f-dd9055e6b66a.mov
=> fix: search input layout animation

CHANGELOG.yml, src/lib/Scenes/MyAccount/MyAccountEditPassword.tsx, src/lib/Scenes/MyAccount/__tests__/MyAccountEditPassword-tests.tsx
This PR resolves [CX-1074]
- Fix change password screen title
[CX-1074]: https://artsyproduct.atlassian.net/browse/CX-1074
=> fix: change password screen title

Podfile.lock
- This is happening after running `bundle exec pod install --repo-update`
(I tested the **buy now** and **make offer** flows and both seem to be working well)
=> chore: update react-native-webview pod

src/lib/Scenes/Onboarding/Onboarding.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount.tsx, src/lib/Scenes/Onboarding/OnboardingForgotPassword.tsx, src/lib/Scenes/Onboarding/OnboardingLogin.tsx, src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
This PR resolves [CX-1079]
https://user-images.githubusercontent.com/11945712/112041774-0fdcce80-8b47-11eb-8bed-b4cc68ed6979.mov
[CX-1079]: https://artsyproduct.atlassian.net/browse/CX-1079
=> feat: Add onboarding navigation infra

src/lib/store/config/EchoModel.tsx, src/lib/store/config/__tests__/EchoModel-tests.tsx
- Use `killedVersions` instead of `excludedVersions`
=> fix: use killedVersions instead of excludedVersions

fastlane/metadata/en-US/release_notes.txt
=> chore: release notes for 6.8.2

CHANGELOG.yml, src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx, src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx, src/lib/Components/StickyTabPage/StickyTabPage.tsx, src/lib/Scenes/Fair/Fair.tsx, src/lib/navigation/BackButton.tsx, src/lib/navigation/NavStack.tsx, src/lib/utils/__tests__/hideBackButtonOnScroll-tests.tsx, src/lib/utils/hideBackButtonOnScroll.tsx
This PR resolves [CX-984]
It's not terribly responsive with the obvious implementation approach, but it's OK and might be fine in production mode.
https://user-images.githubusercontent.com/1242537/112849597-22a05780-90a1-11eb-9e02-9f7a4dbd847b.mp4
[CX-984]: https://artsyproduct.atlassian.net/browse/CX-984
=> feat: make back button hide-able on Android

yarn.lock
Updates sentry to latest version to hopefully fix our android beta job here:
https://app.circleci.com/pipelines/github/artsy/eigen/10559/workflows/fd6b2f9b-62fc-4585-ab80-2ad6c95d0151/jobs/30310
=> fix: update sentry #trivial

src/lib/Components/Artist/ArtistInsights/__tests__/MarketStats-tests.tsx
=> fix market stats typo #trivial

CHANGELOG.yml, src/lib/Scenes/VanityURL/__tests__/VanityURLPossibleRedirect-tests.tsx, src/lib/navigation/__tests__/routes-tests.tsx, src/lib/store/config/__tests__/features-tests.ts, src/lib/store/config/features.ts
Added the echo flag in artsy/echo#81
=> chore: Switch on react native web views behind echo flag

CHANGELOG.yml, app.json
=> chore: prepare for 6.8.3 #trivial

src/lib/navigation/BackButton.tsx
bugfix follow up to #4567 closes [CX-1272]
pretty trivial so will self-merge
[CX-1272]: https://artsyproduct.atlassian.net/browse/CX-1272
=> fix: disable pointer events on hidden back button

src/lib/store/config/features.ts, src/lib/utils/AdminMenu.tsx
Changed the `onTrue` and `onFalse` to `onChange` after @brainbicycle's suggestion, and made the way this is called use some better typescript 😅. I was missing the dot last time I tried to do that.
=> enhancement(typescript): better usage of typescript

src/lib/Components/Input/Input.tsx, src/lib/Components/Input/InputTitle.tsx, src/lib/NativeModules/ArtsyNativeModule.tsx, src/lib/Scenes/Onboarding/Onboarding.tsx, src/lib/Scenes/Onboarding/OnboardingLogin.tsx, src/lib/Scenes/Onboarding/OnboardingWelcome.tsx, src/lib/Scenes/Onboarding/__tests__/OnboardingLogin-tests.tsx, src/palette/elements/Button/Button.tsx
This PR resolves [CX-1083]
- Add login screen
- The bottom navigation bar and status bar will be worked on separately
https://user-images.githubusercontent.com/11945712/113322225-b7f75200-9314-11eb-989f-8cda1746e0d9.mov
[CX-1083]: https://artsyproduct.atlassian.net/browse/CX-1083
=> feat: add login screen

src/__generated__/ConversationSnippet_conversation.graphql.ts, src/__generated__/ConversationsQuery.graphql.ts, src/__generated__/ConversationsTestsQuery.graphql.ts, src/__generated__/InboxOldQuery.graphql.ts, src/__generated__/InboxOldRefetchQuery.graphql.ts, src/__generated__/InboxQuery.graphql.ts, src/__generated__/InboxRefetchQuery.graphql.ts, src/__generated__/InboxTestsQuery.graphql.ts, src/lib/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
=> fix: removes message count from conversation snippet

src/__generated__/ConversationRefetchQuery.graphql.ts, src/lib/Scenes/Inbox/Components/Conversations/Messages.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/Messages-tests.tsx, src/lib/Scenes/Inbox/Screens/Conversation.tsx
Existing pull to refresh in conversation should refresh cta state in addition to messages
I couldn't figure out how to test this but am open to suggestions
=> Pull to refresh refreshes CTA

CHANGELOG.yml, Podfile.lock, src/lib/Components/ArtworkFilterOptions/ColorOptions.tsx, src/lib/Components/ArtworkFilterOptions/ColorsSwatch.tsx, src/lib/Components/ArtworkFilterOptions/MultiSelectOption.tsx, src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx, src/lib/Components/ArtworkFilterOptions/YearOptions.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/AggregationOptionCommonValidation.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/TimePeriodMultiOptions-tests.tsx, src/lib/Components/FilterModal/FilterModal.tsx, src/lib/Components/FilterModal/__tests__/FilterModal-tests.tsx, src/lib/Components/TouchableRow.tsx
This PR resolves [FX-2739]
https://user-images.githubusercontent.com/112297/113778132-084a2780-96fa-11eb-9166-f74f81dbf415.mov
[FX-2739]: https://artsyproduct.atlassian.net/browse/FX-2739
=> feat(fx-2739): updates filter menu component styling

src/lib/Scenes/Inbox/Screens/Conversation.tsx
This PR resolves [PURCHASE-2528]
[PURCHASE-2528]: https://artsyproduct.atlassian.net/browse/PURCHASE-2528
[PURCHASE-2528]: https://artsyproduct.atlassian.net/browse/PURCHASE-2528
=> chore: updates icon in inq chk conversation header

CHANGELOG.yml, package.json, src/lib/Scenes/BottomTabs/BottomTabType.ts, src/lib/Scenes/BottomTabs/BottomTabsButton.tsx, src/lib/Scenes/BottomTabs/bottomTabsConfig.tsx, yarn.lock
This PR resolves [CX-862]
[CX-862]: https://artsyproduct.atlassian.net/browse/CX-862
=> fix: add contextScreenOwnerType to tab bar tap tracking

CHANGELOG.yml, src/lib/Scenes/SaleFAQ/SaleFAQ.tsx
This PR resolves [CX-1274]
|---|---|
|![image](https://user-images.githubusercontent.com/4691889/114199160-5b1f1b80-9954-11eb-9a55-f2e0627b4c36.png)|![image](https://user-images.githubusercontent.com/4691889/114199191-5f4b3900-9954-11eb-9156-4aca6d590e5f.png)|
[CX-1274]: https://artsyproduct.atlassian.net/browse/CX-1274
=> enhancement: use artsy web view

CHANGELOG.yml, src/lib/Components/FilterModal/FilterModal.tsx, src/lib/Components/FilterModal/__tests__/FilterModal-tests.tsx
This PR resolves [CX-1258]
[CX-1258]: https://artsyproduct.atlassian.net/browse/CX-1258
=> enhancement: Set action type for tracking filter params change

fastlane/metadata/en-US/release_notes.txt
The type of this PR is: chore
Updates release notes for v6.8.3
Collaboration with @olerichter00 
=> chore: update release notes for 6.8.3

docs/debugging.md
The type of this PR is: Documentation
`brew cask install react-native-debugger` will throw `Error: Unkown command: cask`. 
This PR changes the command to `brew install --cask  react-native-debugger`
see https://formulae.brew.sh/cask/react-native-debugger#default
=> chore: Update brew install command in debugging docs

CHANGELOG.yml, app.json
Collaboration with @olerichter00 and @jo-rs.
Prep work for our next iOS version (6.8.4). Thanks all for [the very comprehensive docs](https://github.com/artsy/eigen/blob/master/docs/deploy_to_app_store.md)!
The changelog modifications were based on this comparison - https://github.com/artsy/eigen/compare/ios-6.8.3-2021.04.12.19...master. If it looks like we put any changelog items in the wrong place (6.8.3 vs 6.8.4), let me know!
=> chore: prep for 6.8.4

CHANGELOG.yml, src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts, src/lib/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tsx, src/lib/Components/ArtworkFilter/Filters/AttributionClassOptions.tsx, src/lib/Components/ArtworkFilter/Filters/ColorsOptions.tsx, src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx, src/lib/Components/ArtworkFilter/Filters/TimePeriodMultiOptions.tsx, src/lib/Components/ArtworkFilter/Filters/WaysToBuyOptions.tsx, src/lib/Components/ArtworkFilter/Filters/__tests__/AdditionalGeneIDsOptions-tests.tsx, src/lib/Components/ArtworkFilter/Filters/__tests__/TimePeriodMultiOptions-tests.tsx, src/lib/Components/ArtworkFilter/Filters/__tests__/useMultiSelect-tests.tsx, src/lib/Components/ArtworkFilter/Filters/useMultiSelect.ts, src/lib/Components/FancyModal/FancyModalHeader.tsx
This PR resolves [FX-2762]
https://user-images.githubusercontent.com/112297/114749266-c3894680-9d20-11eb-8c4f-a9749a495999.mov
[FX-2762]: https://artsyproduct.atlassian.net/browse/FX-2762
=> feat(fx-2762): replace all option with clear all

package.json, yarn.lock
This is a follow-up to a previous comment you left here https://github.com/artsy/eigen/pull/4566
=> chore: pin cohesion #trivial

CHANGELOG.yml, Podfile.lock, src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx, src/lib/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tsx, src/lib/Components/ArtworkFilter/Filters/AttributionClassOptions.tsx, src/lib/Components/ArtworkFilter/Filters/ColorsOptions.tsx, src/lib/Components/ArtworkFilter/Filters/TimePeriodOptions.tsx, src/lib/Components/ArtworkFilter/Filters/WaysToBuyOptions.tsx, src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx, src/lib/Components/Bidding/Screens/__tests__/CreditCardForm-tests.tsx, src/lib/Components/FancyModal/FancyModalHeader.tsx
This PR resolves [FX-2866]
[FX-2866]: https://artsyproduct.atlassian.net/browse/FX-2866
=> fix(fx-2866): consistent filter header typography and spacing

Podfile.lock
Just a tiny PR to stop the podfile changes from being there all the time.
=> podfile update

docs/getting_started.md
- Update getting started docs for android to follow the official documentation
- Add run on device docs for android
=> chore: Update getting started docs

src/__generated__/ComposerTestsQuery.graphql.ts, src/__generated__/ConversationCTATestsQuery.graphql.ts, src/__generated__/ConversationCTA_conversation.graphql.ts, src/__generated__/ConversationQuery.graphql.ts, src/__generated__/ConversationRefetchQuery.graphql.ts, src/__generated__/ConversationTestsQuery.graphql.ts, src/__generated__/OpenInquiryModalButtonQuery.graphql.ts, src/__generated__/OpenInquiryModalButtonTestsQuery.graphql.ts, src/lib/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx, src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/Composer-tests.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/ConversationCTA-tests.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/OpenInquiryModalButton-tests.tsx
This PR resolves [PURCHASE-2545]
**Issue:**
When an artwork is sold we should no longer see the Make Offer button. The display of the Make Offer button in a conversation is not being updated after the artwork availability is changed to sold. This is because of `isOfferableFromInquiry` which determines whether we should show the make offer button is out of date and comes from a snapshot version of the artwork in impulse.
**Fix:** 
This PR refactors the ConversationCTA button to remove `isOfferableFromInquiry` from the nested conversation query. Instead we now wrap `OpenInquiryModalButton` in a `QueryRenderer` that fetches the actual artwork from gravity to ensure we have fresh and accurate data.
[PURCHASE-2545]: …
=> fix: query artwork to get fresh isOfferableFromInquiry value

fastlane/metadata/en-US/release_notes.txt
=> chore: set release notes for 6.8.4

CHANGELOG.yml, app.json, docs/deploy_to_app_store.md
=> chore: prepare for 6.9.0

CHANGELOG.yml, src/lib/Scenes/Onboarding/ForgotPassword.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx, src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
This PR resolves [CX-1013]
Update the onboarding screens copy.
@joanna20 and @bhoggard it seems to me like the welcome screen text is a bit long now ("collect art by the world's leading artists"), is that fine?
**PS:** The copy for the follow artists will be part of the Follow Artists PR
[CX-1013]: https://artsyproduct.atlassian.net/browse/CX-1013
=> chore(CX-1013): update copy on onboarding

docs/pull_request_template.md
This PR adds an item about Android (and iOS) testing to the PR Checklist in the Eigen PR template to make sure everyone tests new features or changes on Android and iOS.
=> chore: Add iOS and Android test item to checklist in PR template

CHANGELOG.yml, src/lib/Components/StickyTabPage/StickyTabPage.tsx, src/lib/Scenes/Artist/Artist.tsx, src/lib/navigation/__tests__/routes-tests.tsx, src/lib/navigation/routes.tsx
This PR resolves [CX-1254]
[CX-1254]: https://artsyproduct.atlassian.net/browse/CX-1254
=> feat: Route artist auction results route to artist insights

CHANGELOG.yml, android/app/src/main/AndroidManifest.xml, src/lib/utils/useDeepLinks.ts
Co-authored-by: Ole <ole.richter91@gmail.com>
- Support staging for deep links on android
https://user-images.githubusercontent.com/11945712/117426647-68fc9800-af24-11eb-99bb-aee2fb8fbbf5.mov
=> feat: Support staging deep links on android

src/lib/AndroidApp.tsx, src/lib/AppRegistry.tsx, src/lib/utils/track/ConsoleTrackingProvider.ts, src/lib/utils/track/SegmentTrackingProvider.ios.ts, src/lib/utils/track/SegmentTrackingProvider.ts, src/lib/utils/track/providers.tsx, src/setupJest.ts, tsconfig.json
The type of this PR is: **followup**
=> followup(analytics): review suggestions

Gemfile, Gemfile.lock, scripts/test-ios
This PR resolves [CX-1410]
Pairing with @brainbicycle we saw that the thing blocking json to an old version was `second_curtain`, a gem that now is not actually doing anything for us. It was uploading native test results to S3. We removed it and updated json.
[CX-1410]: https://artsyproduct.atlassian.net/browse/CX-1410
=> update(gem): update json

src/lib/AppRegistry.tsx
Think this may have been some test code that got through as part of https://github.com/artsy/eigen/pull/4702
but please let me know if that's not right! 🙏
=> fix: don't show personalize on iOS

CHANGELOG.yml, src/__generated__/ComposerTestsQuery.graphql.ts, src/__generated__/ConversationCTATestsQuery.graphql.ts, src/__generated__/ConversationCTA_conversation.graphql.ts, src/__generated__/ConversationQuery.graphql.ts, src/__generated__/ConversationRefetchQuery.graphql.ts, src/__generated__/ConversationTestsQuery.graphql.ts, src/__generated__/MessagesQuery.graphql.ts, src/__generated__/MessagesTestsQuery.graphql.ts, src/__generated__/OrderUpdateTestsQuery.graphql.ts, src/__generated__/OrderUpdate_event.graphql.ts, src/lib/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx, src/lib/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx, src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/Composer-tests.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/ConversationCTA-tests.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/Messages-tests.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/OrderUpdate-tests.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx
This PR resolves [PURCHASE-2578]
[screen capture](https://artsy.slack.com/files/U8623D8RJ/F021DAW68LV/p2_eigen.webm) 🔒 
</details>
[PURCHASE-2578]: https://artsyproduct.atlassian.net/browse/PURCHASE-2578
=> feat: CTA and modal for collector confirming IC provisional offer

fastlane/Fastfile, fastlane/metadata/en-US/release_notes.txt
- Update release notes
- Fix build version issue in promote beta lane
=> chore: 6.9.0 submission #trivial

src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
#trivial
This PR resolves [CX-1219]
- Cut down welcome screen animation speed by half
@ jonathanburkett check this out and let me know what you think of it 
**Before**
https://user-images.githubusercontent.com/11945712/117951111-210ab600-b314-11eb-8d65-a782c64a7eef.mov
**After**
https://user-images.githubusercontent.com/11945712/117951122-236d1000-b314-11eb-9a0e-b79b563aaeb8.mov
[CX-1219]: https://artsyproduct.atlassian.net/browse/CX-1219
=> chore: cut down welcome screen animation speed by half

CHANGELOG.yml, app.json
- updates our app version number
- updates our CHANGELOG for the upcoming release
=> chore: prep for 6.9.1 development #trivial

src/lib/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tsx, src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
This PR resolves [PURCHASE-2668]
This PR addresses minor visual QA issues in the Make Offer modal:
- Fixes title copy.
- Fixes spacing issue.
- Ensure that the collapsable artwork details component is scrollable.
[PURCHASE-2668]: https://artsyproduct.atlassian.net/browse/PURCHASE-2668
=> fix: minor visual qa for make offer modal

CHANGELOG.yml, src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx, src/lib/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
This PR resolves [[PURCHASE-2663]]
Copy additions to the inbox/inquiry make offer flow as requested by legal. Arvind confirmed that it was ok that the inbox message is below the timestamp.
- [X ] I have tested my changes on **iOS** and **Android**.
- [ X] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
[PURCHASE-2663]: https://artsyproduct.atlassian.net/browse/PURCHASE-2663
=> Inquiry checkout copy additions from legal

docs/README.md
Fix a broken link to the notification doc
=> fix: change a broken link to the notification doc

Artsy/App/ARAppDelegate+Emission.m, Podfile.lock, docs/analytics_and_tracking.md, src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx, src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsights-tests.tsx, src/lib/Scenes/AuctionResult/AuctionResult.tsx, src/lib/Scenes/MyBids/MyBids.tsx, src/lib/Scenes/MyCollection/MyCollection.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/lib/Scenes/MyProfile/MyProfile.tsx, src/lib/utils/track/SegmentTrackingProvider.ts, src/lib/utils/track/helpers.ts, src/lib/utils/track/providers.tsx
This PR resolves [CX-1449], [CX-1458] and one with no jira ticket, about profile screen tracking missing.
We found that Profile didn't send a screen tracking event. Now it does.
profile
before, track:screen (highlighted)
after, screen:screen (highlighted)
extra
[CX-1449]: https://artsyproduct.atlassian.net/browse/CX-1449
[CX-1458]: https://artsyproduct.atlassian.net/browse/CX-1458
=> analytics(screens): add tracking in profile and fix track event not being a `screen` event.

docs/pull_request_template.md
=> enhancement(documentation): you get a feature flag, and you get a feature flag, and you get a feature flag

CHANGELOG.yml, src/lib/Scenes/Sales/Components/SaleList.tsx, src/lib/Scenes/Sales/Components/SaleListItem.tsx, src/lib/Scenes/Sales/Components/__tests__/SaleListItem-tests.tsx
The type of this PR is: fix
This PR resolves [CX-852]
This PR fixes spaces between items in SaleList
How it looks:
Before my fix(Android Pixel C): 
After my fix(Android Pixel C): 
Before my fix(iOS iPad Pro 9.7-inch):
After my fix(iOS iPad Pro 9.7-inch):
It looks unchanged on Android and iOs phones.
[CX-852]: https://artsyproduct.atlassian.net/browse/CX-852
=> fix(CX-852): fix spaces between items in SaleList for tablets

.vscode/tasks.json
I don't use these but I see they are there. vscode seems to want to update them, so here's a PR of the autoupdate vscode did on them.
=> vscode autoupdate of tasks

CHANGELOG.yml
Looks like we accidentally brought a few old changes back into the changelog. This removes them, going to self-merge to avoid anyone else accidentally merging the old changes. Looking forward to the new changelog process making this less manual!
=> fix: fix changelog #trivial

CHANGELOG.yml, src/lib/store/config/features.ts
This enables Inquiry Checkout. The corresponding Echo PR is [here](https://github.com/artsy/echo/pull/85).
https://artsyproduct.atlassian.net/browse/PURCHASE-2684
=> feat: enable Inquiry Checkout (PURCHASE-2684)

fastlane/metadata/en-US/release_notes.txt
Updates release notes for release 6.9.1
=> chore: update release notes #trivial

Artsy/App/ArtsyEcho.h, Artsy/App/ArtsyEcho.m, src/lib/store/config/EchoModel.tsx
The type of this PR is: **Cleanup**
In order to remove aerodramus completely, I started by removing some code that was not used anywhere in the app. It was an easy quick step. The rest is now used in a few places. Once the old admin menu is migrated, we could probably do another step of cleanup.
=> cleanup(old echo): removed some methods and code that were not used

CHANGELOG.yml, app.json
Prepping for the next release!
- Update version number
- Update changelog
=> chore: Prepare for development, 6.9.2

src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts, src/__generated__/CollectionArtworksTestsQuery.graphql.ts, src/__generated__/CollectionArtworks_collection.graphql.ts, src/__generated__/CollectionQuery.graphql.ts, src/__generated__/CollectionTestsQuery.graphql.ts, src/__generated__/Collection_collection.graphql.ts, src/__generated__/FilterModalTestsQuery.graphql.ts, src/lib/Scenes/Collection/Collection.tsx, src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
This PR resolves [FX-2899]
Pass input argument for artworksConnection
[FX-2899]: https://artsyproduct.atlassian.net/browse/FX-2899
=> feat: pass argument for artworksConnection

src/lib/Components/LocationMap/index.tsx, src/lib/Scenes/Partner/Components/PartnerMap.tsx, src/lib/Scenes/Partner/Screens/PartnerLocations.tsx
This PR resolves [CX-1484]
This crash was happening in both ios and android. A hook was being used inside a function that was on an `onPress`, which totally broke the rules of hooks and it crashed.
I moved the hook to the components that used it, and made the previous function that was called to return the arguments the hook expects.
[CX-1484]: https://artsyproduct.atlassian.net/browse/CX-1484
=> fix(actionsheet): gallery locations actionsheet crash fix

src/lib/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
**Type of PR**: Bug Fix
**Jira Ticket**: https://artsyproduct.atlassian.net/browse/PURCHASE-2690
**Description of Issue**
When a partner's name was greater than a certain length, the time since last message would overflow. 
This has been resolved by wrapping the gallery name in a `Flex` component and setting the `flex-shrink` property to `1`.  See below screenshots. 
**Original Issue**
**iPhone 8:** 
**iPhone 12:** 
**Android Pixel 2:**
- [ x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ x] I have tested my changes on **iOS** and **Android**.
- [ x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ x] I have added a …
=> Mc jones/fix time overflow in inquiries inbox

CHANGELOG.yml, src/lib/Components/CircleWithBorder/CircleWithBorder.tsx
This PR resolves [CX-1488]
This PR fixes a broken slider
https://user-images.githubusercontent.com/73339470/119122124-dd602c80-ba36-11eb-85f6-871eff57cd57.mov
[CX-1488]: https://artsyproduct.atlassian.net/browse/CX-1488
=> fix(CX-1488): broken slider

.gitignore, CHANGELOG.yml, src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts, src/lib/Components/ArtworkFilter/Filters/PriceRangeOptionsNew.tsx, src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx, src/lib/Components/ArtworkFilter/Filters/SizeOptionsNew.tsx, src/lib/Components/ArtworkFilter/Filters/SizeOptionsOld.tsx, src/lib/Components/ArtworkFilter/Filters/__tests__/SizeOptionsNew-tests.tsx, src/lib/Components/ArtworkFilter/Filters/__tests__/helpers-tests.tsx, src/lib/Components/ArtworkFilter/Filters/helpers.ts
This PR resolves [FX-2634]
🇺🇸 
https://user-images.githubusercontent.com/112297/119041769-06c08000-b985-11eb-9699-555b4c72b8fe.mov
🌎 
https://user-images.githubusercontent.com/112297/119041847-1c35aa00-b985-11eb-9c2e-584b6ed4f501.mov
[FX-2634]: https://artsyproduct.atlassian.net/browse/FX-2634
=> feat(fx-2634): Custom size filter

CHANGELOG.yml, src/lib/utils/AdminMenu.tsx
Adds a menu item to the admin menu to clear the relay cache.
=> feat: add admin menu item to clear relay cache

docs/developing_a_feature.md
This came up in https://github.com/artsy/eigen/pull/4753#discussion_r633201657, so I made a quick addition in docs to have this for the future.
=> docs(flags): removing a feature flag

fastlane/metadata/en-US/release_notes.txt
=> new release!

HACKS.md
The type of this PR is: **cleanup**
After the RFC https://github.com/artsy/README/issues/390, I wanted to clean up this file a bit, so it's a better example.
Now all entries have a name, a time to remove, and the context of the hack, in that order.
=> cleanup(hacks): just some reodering of lines to follow the template

CHANGELOG.yml, src/lib/utils/AdminMenu.tsx
This PR resolves [CX-1287]
https://user-images.githubusercontent.com/73339470/119345035-0edc3080-bca1-11eb-8d9c-6463c5f5a6dd.mov
[CX-1287]: https://artsyproduct.atlassian.net/browse/CX-1287
=> enhancement(CX-1287): improve admin menu

src/lib/Scenes/Onboarding/ForgotPassword.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx, src/lib/Scenes/Onboarding/OnboardingLogin.tsx
I noticed that, in smaller devices at least, there was this funky layout for the bottom button and the checkbox. They were way too far left.
I fix that here.
I'm not sure that that `flex-end` was supposed to do but it was breaking these screens. Maybe it was old? Anyway, now it's not there anymore and now screens seem alright.
=> fix(layout): button and checkbox were not layed out right

src/lib/Scenes/Home/Components/SalesRail.tsx, src/lib/utils/track/schema.ts
This PR resolves [CX-1500]
We didn't have a screen tracking event for the Auctions screen, now we do.
The diff is disgusting 😬, but basically I added the line `<ProvideScreenTrackingWithCohesionSchema info={screen({owner_type: OwnerType.auctions })}>` and the closing tag, and it pushed everything around. Also I `lint-fix`ed the imports.
[CX-1500]: https://artsyproduct.atlassian.net/browse/CX-1500
=> analytics(add screen): add screen event for `auctions`

CHANGELOG.yml, android/app/src/main/AndroidManifest.xml, src/lib/utils/useDeepLinks.ts
This PR resolves [CX-1454]
- Enable app links on android. This allows us to open the artsy app without asking for which app to handle the deep link.
- The issue with deep links was that we were handling the deep links in the wrong activity (MainActivity instead of the SplashActivity)
- The app links were broken because they were configured in the wrong way as well
- We were missing some deep links so I added them as well
**When the app is closed**
https://user-images.githubusercontent.com/11945712/119411208-4fac6780-bcea-11eb-821e-3e2a4e2a2afb.mov
**When the app is open**
https://user-images.githubusercontent.com/11945712/119411121-32779900-bcea-11eb-964b-629baec763a9.mov
[CX-1454]: …
=> fix: app links on android

CHANGELOG.yml
This PR is meant to trigger the android build again
=> chore: trigger android build #trivial

src/lib/Components/Input/Input.tsx
On https://github.com/artsy/eigen/pull/4831 I tried to fix a bug, and in fixing it I caused a bigger bug, where the cancel button does nothing! Fast refresh must have made it work when I was making the previous PR.
Anyway, this PR reverts the main change. So the old bug is still there but it's waaaaay less important than the cancel button not working.
=> fix(search input): cancel button was not cancelling 

.gitignore, Artsy.xcodeproj/project.pbxproj, Artsy/App/ARTArtsyNativeModule.h, Artsy/App/ARTArtsyNativeModule.m, Artsy/App_Resources/Artsy-Info.plist, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Podfile.lock, android/app/build.gradle, android/app/src/main/java/net/artsy/app/ArtsyNativeModule.java, fastlane/Fastfile, src/lib/NativeModules/ArtsyNativeModule.tsx, src/lib/NativeModules/LegacyNativeModules.tsx, src/lib/Scenes/About/About.tsx, src/lib/store/__tests__/GlobalStoreModel-tests.ts, src/lib/store/config/EchoModel.tsx, src/lib/utils/AdminMenu.tsx, src/setupJest.ts
This PR is part of whatever result came after [CX-871].
Old Admin menu had version and build number and commit hash. I added the same in the new Admin menu.
To add it, I added an ArtsyNativeModule on ios, to keep, same as we have for android. kind of a general place to put things and expose them to TS. For android I added an extra constant to be exported, that reads the git hash.
I skipped the email because it's easy enough to see it in profile. I also renamed some fields to make more sense. I also removed the old swift playground we had on the ios app.
old admin
new admin ios
new admin android
[CX-871]: https://artsyproduct.atlassian.net/browse/CX-871
=> enhancement(admin menu): show version, build number, commit short hash

CHANGELOG.yml, src/lib/Scenes/Onboarding/ForgotPassword.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx, src/lib/Scenes/Onboarding/OnboardingLogin.tsx
This PR resolves [CX-1504]
This PR fixes not floating back button
https://user-images.githubusercontent.com/73339470/119488978-d3566a80-bd63-11eb-86c9-33d81d309c2f.mov
[CX-1504]: https://artsyproduct.atlassian.net/browse/CX-1504
=> fix(CX-1504): onboarding back button is flying off

android/app/src/main/AndroidManifest.xml, src/lib/utils/useDeepLinks.ts
This PR resolves deep link issue when the app is in the background
=> fix: deep link issue when the app is in the background

CHANGELOG.yml, src/lib/NativeModules/LegacyNativeModules.tsx
Co-authored-by: Ole <ole.richter91@gmail.com>
- Fix iOS app blank screen
=> fix: iOS app blank screen

renovate.json
=> no need to bother david :)

src/lib/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tsx
=> fix(filters): uses correct copy for title

CHANGELOG.yml, package.json, src/lib/utils/renderMarkdown.tsx, yarn.lock
This PR resolves[CX-1540]
HTML Entities are escaped when we render them with `renderMarkdown`. This leads to problems e.g. with copyright symbols (see screenshots). 
This PR introduces [html-entities][https://www.npmjs.com/package/html-entities] to decode html entities in markdown.
About HTML Entities in JSX https://shripadk.github.io/react/docs/jsx-gotchas.html
| Before | After (iOS) | After (Android) |
|---|---|---|
[CX-1540]: https://artsyproduct.atlassian.net/browse/CX-1540
[CX-1540]: https://artsyproduct.atlassian.net/browse/CX-1540
=> fix: Decode html entities in markdown

CHANGELOG.yml, src/lib/store/config/features.ts
This PR resolves [FX-2960]
Added the saved search feature flag
[FX-2960]: https://artsyproduct.atlassian.net/browse/FX-2960
=> Feat(fx-2960) saved search feature flag

CHANGELOG.yml, app.json
- Updates changelog and version number for development on 6.9.4
=> chore: Prepare for development, 6.9.4

HACKS.md, android/build.gradle, package.json, patches/@segment+analytics-react-native-appboy+1.4.8.patch, src/lib/utils/track/SegmentTrackingProvider.ts, yarn.lock
This PR resolves [GRO-262]
This is a small PR that only contains the braze integration for android. The ios part is a bit more tricky because it still uses the native analytics code.
We will test this first on android, and if the integration here works, we will move on with ios too.
[GRO-262]: https://artsyproduct.atlassian.net/browse/GRO-262
=> feature(analytics): adding braze on android

Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingNavigationItemsView.m
The type of this PR is: FIX
This PR resolves [CX-853](https://artsyproduct.atlassian.net/browse/CX-853)
=> fix: Change error text when signing in with Apple

CHANGELOG.yml, src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
The type of this PR is: FIX
This PR resolves [CX-960](https://artsyproduct.atlassian.net/browse/CX-960)
=> fix: Vertically aligned 'Follow/Following' artist button text

CHANGELOG.yml, src/__generated__/OrderDetailsPaymentTestsQuery.graphql.ts, src/__generated__/OrderDetailsPayment_order.graphql.ts, src/__generated__/OrderDetailsQuery.graphql.ts, src/__generated__/OrderDetailsTestsQuery.graphql.ts, src/__generated__/OrderDetails_order.graphql.ts, src/lib/Scenes/OrderHistory/OrderDetails/OrderDetails.tsx, src/lib/Scenes/OrderHistory/OrderDetails/OrderDetailsPayment.tsx, src/lib/Scenes/OrderHistory/__tests__/OrderDetailsPayment-tests.tsx
This PR resolves [PX-4073]
Payment method section, margins in the section list will be fixed by @alexj105.
[PX-4073]: https://artsyproduct.atlassian.net/browse/PX-4073
=> feat(PX-4073): order details payment section

Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m, CHANGELOG.yml
The type of this PR is: Fix
This PR resolves [CX-1565](https://artsyproduct.atlassian.net/browse/CX-1565)
Changed the error message when a user tries to Sign up with Apple or Facebook, while his email is already registered in the system 
from "User already exists with this email. Please log in with your email and password" 
to "There is already an account with this email address, so you can’t log in with Apple. Please login with your email instead."
I can't add a screenshot of the change right now, cause when I Sign up with Apple I see an infinite loading wheel
=> fix: Specified a more specific error for logging in with Apple or Facebook

CHANGELOG.yml, src/__generated__/OrderDetailsQuery.graphql.ts, src/__generated__/OrderDetailsTestsQuery.graphql.ts, src/__generated__/OrderDetails_order.graphql.ts, src/__generated__/SummarySectionTestsQuery.graphql.ts, src/__generated__/SummarySection_section.graphql.ts, src/lib/Scenes/OrderHistory/OrderDetails/ArtworkInfoSection.tsx, src/lib/Scenes/OrderHistory/OrderDetails/OrderDetails.tsx, src/lib/Scenes/OrderHistory/OrderDetails/ShipsToSection.tsx, src/lib/Scenes/OrderHistory/OrderDetails/SummarySection.tsx, src/lib/Scenes/OrderHistory/__tests__/OrderDetails-tests.tsx, src/lib/Scenes/OrderHistory/__tests__/SummarySection-tests.tsx
This PR resolves [PX-4071]
Added Order Summary section to Order Details page and covered by tests.
[PX-4071]: https://artsyproduct.atlassian.net/browse/PX-4071
=> feat: User can see Order Summary section PX-4071

CHANGELOG.yml
=> chore: remove duplicate changelog entries #trivial

src/lib/Scenes/Home/Components/ArticlesRail.tsx
This is a follow up PR for https://github.com/artsy/eigen/pull/4901. As discussed in  [CX-1550] this PR aligns the home articles rail to the new design specs and renames the section to "Market News".
Note: I didn't add a changelog because https://github.com/artsy/eigen/pull/4901 already added a changelog about the articles rail.
[CX-1550]: https://artsyproduct.atlassian.net/browse/CX-1550
=> fix: Rename home articles section to market news

CHANGELOG.yml, src/lib/Components/ArtsyReactWebView.tsx
This PR resolves [CX-1567] by reverting https://github.com/artsy/eigen/pull/4870
| Article | Sale FAQ |
|---|---|
|![Screenshot_1623070009](https://user-images.githubusercontent.com/4691889/121019216-84ff8d80-c79f-11eb-8be0-40fe9c1c8d67.png) |![Screenshot_1623070062](https://user-images.githubusercontent.com/4691889/121019230-87fa7e00-c79f-11eb-9cbf-8ab64d1858f3.png) |
[CX-1567]: https://artsyproduct.atlassian.net/browse/CX-1567
=> fix: Remove artsy react web view top padding

src/lib/AndroidApp.tsx, src/palette/svgs/DecreaseIcon.tsx, src/palette/svgs/IncreaseIcon.tsx
tiny fix but you can see the change if you zoom in.
before:
after:
If you cant see it, the difference is on the down arrow. before, it was not pointy like the up arrow. it was a bit smushed, because the rotation was at the wrong point.
I re-exported from figma and now its nice and pointy like the up arrow.
=> fix(icons): small fix in decrease and increase icons

CHANGELOG.yml, docs/getting_started.md
=> chore: Update open simulator command in docs

CHANGELOG.yml, app.json
- Updates changelog
- Updates version number
=> chore: Preparing for development version 6.9.5

CHANGELOG.yml, Podfile.lock, src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
This PR resolves [FX-2981]
https://user-images.githubusercontent.com/18648835/121653144-a6f95880-ca9c-11eb-997b-9eb2989b5fbd.mp4
[FX-2981]: https://artsyproduct.atlassian.net/browse/FX-2981
=> Enhancement(fx 2981)/saved search user is prompted to enable push notifications

Podfile.lock, src/__generated__/OrderDetailsQuery.graphql.ts, src/__generated__/OrderDetailsTestsQuery.graphql.ts, src/__generated__/OrderDetails_order.graphql.ts, src/__generated__/ShipsToSectionTestsQuery.graphql.ts, src/__generated__/ShipsToSection_address.graphql.ts, src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsHeader.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/ShipsToSection.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/SoldBySection.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/SummarySection.tsx, src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetailsHeader-tests.tsx
The type of this PR is: Fixes
https://artsyproduct.atlassian.net/browse/PX-4212
This PR resolves [PX-4212]
skip shipsTo if shipping type is pickup. Small UIX fixes
[PX-4212]: https://artsyproduct.atlassian.net/browse/PX-4212
=> fix:order details qa fixes

CHANGELOG.yml, src/__generated__/OrderDetailsHeaderTestsQuery.graphql.ts, src/__generated__/OrderDetailsHeader_info.graphql.ts, src/__generated__/OrderDetailsQuery.graphql.ts, src/__generated__/OrderDetailsTestsQuery.graphql.ts, src/__generated__/OrderDetails_order.graphql.ts, src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsHeader.tsx, src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetailsHeader-tests.tsx
This PR resolves [PX-4211]
User can see the way of delivery (fulfillment)
[PX-4211]: https://artsyproduct.atlassian.net/browse/PX-4211
=> fix: User can see the way of delivery (PX-4211)

CHANGELOG.yml, Podfile.lock, src/__generated__/ArtworkTileRailTestsQuery.graphql.ts, src/__generated__/ArtworkTileRail_artworksConnection.graphql.ts, src/__generated__/LotsByArtistsYouFollowQuery.graphql.ts, src/__generated__/LotsByArtistsYouFollow_me.graphql.ts, src/__generated__/LotsByFollowedArtistsQuery.graphql.ts, src/__generated__/SalesQuery.graphql.ts, src/__generated__/SalesQueryRendererQuery.graphql.ts, src/__generated__/ViewingRoomArtworkRailTestsQuery.graphql.ts, src/__generated__/ViewingRoomQuery.graphql.ts, src/__generated__/ViewingRoomTestsQuery.graphql.ts, src/lib/AppRegistry.tsx, src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx, src/lib/Scenes/Home/Components/SaleArtworksHomeRail.tsx, src/lib/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx, src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx, src/lib/Scenes/Sales/index.tsx, src/lib/navigation/routes.tsx
This PR resolves [GRO-298]
https://user-images.githubusercontent.com/112297/121072026-af9d1680-c79e-11eb-821f-e890774900b9.mov
[GRO-298]: https://artsyproduct.atlassian.net/browse/GRO-298
=> feat(GRO-298): adds "lots by artists you follow" landing screen

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/net/artsy/app/MainApplication.java, android/app/src/main/res/values/braze.xml, package.json, patches/react-native-appboy-sdk+1.29.1.patch, yarn.lock
Trying to make Braze work.
Here we used https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup and https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.
I have no idea if this works or how to test it 😬.
cc @jonallured
=> Some more braze setup testing

CHANGELOG.yml, src/__generated__/OrderHistoryQuery.graphql.ts, src/lib/Scenes/OrderHistory/OrderHistory.tsx, src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
This PR resolves [PX-4253]
[PX-4253]: https://artsyproduct.atlassian.net/browse/PX-4253
=> fix: Order History: "Unable to load" page is opened (exception occurs) when artwork is deleted/unpublished from order (PX-4253)

src/lib/Scenes/Home/Components/ArticlesRail.tsx
This PR resolves [CX-1600]
[CX-1600]: https://artsyproduct.atlassian.net/browse/CX-1600
=> fix: adjust market news rail spacing

src/lib/store/config/features.ts
We're not actually ready to release this feature just yet!
=> fix: Unrelease order history feature for now

src/__generated__/OrderDetailsQuery.graphql.ts, src/lib/Scenes/OrderHistory/OrderDetails/Components/ArtworkInfoSection.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
While pairing with Mounir, we adjust the screen we should to let the user know what is happening
=> Unable to load fixed on OrderDetails

CHANGELOG.yml, src/__generated__/ArtistBelowTheFoldQuery.graphql.ts, src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts, src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts, src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts, src/__generated__/ArtistInsightsTestsQuery.graphql.ts, src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx, src/lib/Components/ArtworkFilter/ArtworkFilter.tsx, src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts, src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx, src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx, src/lib/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx, src/lib/Components/ArtworkFilter/Filters/__tests__/AuctionHouseOptions-tests.tsx, src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
This PR resolves [CX-848]
Adds an "auction house" filter for auction results on the artist insights tab.
| | | | 
|---|---|---|
| ![Simulator Screen Shot - iPhone 8 - 2021-06-22 at 13 02 27](https://user-images.githubusercontent.com/4691889/122914082-8feb1e00-d35a-11eb-9633-f2ac9bb96da8.png) | ![Simulator Screen Shot - iPhone 8 - 2021-06-22 at 13 02 31](https://user-images.githubusercontent.com/4691889/122914097-92e60e80-d35a-11eb-831b-b8de160af16d.png) | ![Simulator Screen Shot - iPhone 8 - 2021-06-22 at 13 02 36](https://user-images.githubusercontent.com/4691889/122914109-96799580-d35a-11eb-911e-98eb66c47495.png) |
[CX-848]: https://artsyproduct.atlassian.net/browse/CX-848
=> feat: User on app can filter auction results by auction house

app.json, docs/deploy_to_play_store.md, fastlane/metadata/android/en-US/changelogs/default.txt, fastlane/metadata/en-US/release_notes.txt
Co-authored-by: George Kartalis <g.kartalis7@gmail.com>
=> docs: update release notes

src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx, src/lib/Components/PopoverMessage/PopoverMessage.tsx, src/lib/Components/PopoverMessage/__tests__/PopoverMessage-tests.tsx
This PR resolves [FX-2972]
**Before**
**After**
[FX-2972]: https://artsyproduct.atlassian.net/browse/FX-2972
=> feat: Message on mutation fail

scripts/changelog/generatePlatformChangelog-tests.ts
This PR resolves https://artsy.slack.com/archives/C02BAQ5K7/p1624534609409000
=> fix: broken tests due to app version #trivial

CHANGELOG.yml, src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
This PR resolves [FX-3038]
User is not prompted to enable push notifications before they can disable a saved search.
https://user-images.githubusercontent.com/3513494/123249204-66b0c600-d4f1-11eb-9e84-561bed94aa58.mp4
- Remove "Enable push notification" guard for disabling saved search - dzmitry tratsiak
[FX-3038]: https://artsyproduct.atlassian.net/browse/FX-3038
=> fix: ask notification permissions only for create saved search

Podfile.lock
This PR Updates the pods and locks them to whatever output we get from `bundle exec pod install`
=> chore: update Podfile.lock #trivial

Artsy/App/ARAppNotificationsDelegate.m, Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m, CHANGELOG.yml, emission/Pod/Classes/Core/AREmission.h, emission/Pod/Classes/Core/AREmission.m, emission/Pod/Classes/EigenCommunications/ARNotificationsManager.h, emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m, src/lib/Scenes/Artist/Artist.tsx, src/lib/store/NativeModel.ts
This PR resolves [FX-3042]
Allow component props to be passed from push notification payload.
We’re planning to use a `searchCriteriaID` attribute, sent in the payload defined in Gravity, to trigger some saved search behavior on the artist screen.
There’s some additional context in this thread: https://artsy.slack.com/archives/C9SATFLUU/p1624539467277200
The original POC was built in [this PR](https://github.com/artsy/eigen/pull/5000). This attempts a couple improvements following that POC:
- We won’t send the entire notification payload through - most of which we don’t need
- We can be very selective and explicit with the keys in the payload passed down as props
-
-
-
- Allow custom attributes from push notifications to be passed through to React …
=> feat: allow component props to be passed from push notification payload

CHANGELOG.yml
- Update changelog, the version number was already updated previously
-
-
-
- dev prep
=> chore: prepare for development, 6.9.6

CHANGELOG.yml, app.json
- Updates version number to match App Store connect
-
-
-
- 6.10.0 dev prep
=> chore: Prepare for development, 6.10.0 #trivial

CHANGELOG.yml, src/lib/Components/ArtsyReactWebView.tsx, src/lib/Components/FancyModal/FancyModalHeader.tsx, src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx, src/lib/navigation/__tests__/routes-tests.tsx, src/lib/navigation/routes.tsx
This PR resolves [CX-1590]
Share button added to article pages. 
https://user-images.githubusercontent.com/27921300/122058130-9d008e00-cdeb-11eb-9436-ccee1665726e.mov
[CX-1590]: https://artsyproduct.atlassian.net/browse/CX-1590
=> feat (CX-1590): implement share button for articles

src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
=> chore: update saved search tests

src/lib/Components/ArtworkFilter/SavedSearch/__tests__/convertersToFilterParams-tests.ts
Update convert to filter params tests
=> chore: update convert to filter params tests

CHANGELOG.yml, src/lib/Components/StickyHeaderPage.tsx, src/lib/Components/StickyTabPage/StickyTabPage.tsx, src/lib/Scenes/ArtistSeries/ArtistSeries.tsx, src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx, src/lib/Scenes/ArtistSeries/ArtistSeriesFilterHeaders.tsx, src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesArtworks-tests.tsx, src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesFilterHeader-tests.tsx, src/lib/utils/useAutoCollapsingMeasuredView.tsx
[Initial implementation](https://github.com/artsy/eigen/pull/4705)
https://user-images.githubusercontent.com/3513494/121366762-684f8b00-c942-11eb-9ade-d47ebf5ba1c0.mp4
=> feat: artist series sticky filter

docs/getting_started.md
First time setting up eigen I experienced the same error that [was reported here](https://artsy.slack.com/archives/CP9P4KR35/p1617129794216400) and to resolve I had to [do this](https://artsy.slack.com/archives/CP9P4KR35/p1619171694068200?thread_ts=1617129794.216400&cid=CP9P4KR35). I didn't search slack initially and found the same [advice here](https://github.com/facebook/react-native/issues/29203#issuecomment-814889611).
This adds a note to getting started about configuring Xcode properly after installing to avoid running into `Flipper-Glog error` during `pod install`.
=> docs: update getting started

CHANGELOG.yml, src/lib/Scenes/Consignments/Screens/ConsignmentsArtist.tsx
This PR resolves [CX-1658]
https://user-images.githubusercontent.com/73339470/124129869-dfca9300-da86-11eb-9b02-bdc7aae0739e.mov
-
-
-
-
[CX-1658]: https://artsyproduct.atlassian.net/browse/CX-1658
=> fix(CX-1658): empty search in artist field for consignment submissions

CHANGELOG.yml, package.json, src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx, src/lib/Scenes/Home/Components/AuctionResultsRail.tsx, yarn.lock
This PR resolves [CX-1617]
Add analytics for AuctionResultsForYou and AuctionResultsRail components
- Add analytics for auction results for artists you flow
[CX-1617]: https://artsyproduct.atlassian.net/browse/CX-1617
=> add analytics for auction results for artists you flow

CHANGELOG.yml, src/__generated__/ConsignmentsArtistQuery.graphql.ts, src/lib/Scenes/Consignments/Components/SearchResults.tsx, src/lib/Scenes/Consignments/Screens/ConsignmentsArtist.tsx, src/lib/Scenes/Consignments/Screens/__tests__/ConsignmentsArtist-tests.tsx, src/lib/Scenes/Consignments/index.tsx
This PR resolves [CX-630]
- Removes artists that are not marked as target supply from the search autosuggest.
- Increases the number of results for the search query (because we have to filter out a lot of the results).
- Does not add tracking - I'm waiting for some input and will implement it in another PR to get this change out as soon as possible.
| Target Supply | No Target Supply |
|---|---|
| ![Simulator Screen Shot - iPhone 8 - 2021-06-30 at 13 51 22](https://user-images.githubusercontent.com/4691889/123955842-60679180-d9aa-11eb-9e50-8bdf925bbba4.png) | ![Simulator Screen Shot - iPhone 8 - 2021-06-30 at 13 51 16](https://user-images.githubusercontent.com/4691889/123955825-5b0a4700-d9aa-11eb-9f37-d208e3fd186b.png) |
- Click on "Submit a work"
- …
=> feat: Prevent users from submit consignments for non target supply artists

CHANGELOG.yml, src/lib/store/config/features.ts
This PR marks the Order History feature as ready for release! 🚀
-
-
-
-
=> feat: Mark Order History feature as ready for release

src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
This PR resolves [FX-3055]
Updated saved search text prompt (both for disabled/enabled) according to ticket.
|enable|disable|
|---|---|
|![Simulator Screen Shot - iPhone 8 - 2021-07-02 at 10 15 39](https://user-images.githubusercontent.com/21178754/124245193-0c7eb900-db20-11eb-8adb-1ac6a45ff888.png)|![Simulator Screen Shot - iPhone 8 - 2021-07-02 at 10 16 19](https://user-images.githubusercontent.com/21178754/124245203-0e487c80-db20-11eb-8d02-8f6fc6506930.png)|
|enable|disable|
|---|---|
|![Screenshot_1625214784](https://user-images.githubusercontent.com/21178754/124246200-fd4c3b00-db20-11eb-860c-e2e4b184958f.png)|![Screenshot_1625214793](https://user-images.githubusercontent.com/21178754/124246205-fe7d6800-db20-11eb-968f-8df45c2f0a46.png)| …
=> chore: update saved search text prompt within banner

src/lib/store/config/features.ts
This PR resolves [FX-3039]
Even when switching to true from echo Android will not show the banner since we don't have yet notifications implemented in android.
**iOS**
- Show banner flag is enabled remotely by echo
**Android**
- Show banner if feature flag is enabled locally via admin menu
Once [PR #99 from echo](https://github.com/artsy/echo/pull/99) is merged need to re run tests</del>
#nochangelog
[FX-3039]: https://artsyproduct.atlassian.net/browse/FX-3039
=> feat: display saved search logic behind platform specific flag

docs/preferred_practices.md
Adds a table of contents to the preferred practices doc.
-
-
-
-
=> chore: Add preferred practices TOC

CHANGELOG.yml, src/lib/Components/Lists/AuctionResultListItem.tsx, src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx, src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
Addresses: [CX-1669]
We tried to display the artist name for an auction result on the artist insights page which doesn't exist. This PR fixes the issue by introducing a `showArtistName` flag.
|![Simulator Screen Shot - iPhone 8 - 2021-07-05 at 11 27 15](https://user-images.githubusercontent.com/4691889/124451177-6af8a100-dd85-11eb-902c-981902645bf8.png)|![Simulator Screen Shot - iPhone 8 - 2021-07-05 at 11 27 36](https://user-images.githubusercontent.com/4691889/124451184-6cc26480-dd85-11eb-94e2-b7df4e6337f3.png)|![Simulator Screen Shot - iPhone 8 - 2021-07-05 at 11 32 46](https://user-images.githubusercontent.com/4691889/124451265-81066180-dd85-11eb-8cac-c978392f7c74.png)|
|---|---|---|
-
-
-
-
[CX-1669]: …
=> fix: hide auction results artist name on artist insights screen

docs/pull_request_template.md
Co-authored-by: Pavlos Vinieratos <pvinis@gmail.com>
- The Changelog section was really long and annoying so we changed it to be inside a collapsible component to make it less jarring
-
-
-
- Put PR changelog changes inside a collapsible section
=> chore: update PR template

.circleci/config.yml
Co-authored-by: Pavlos Vinieratos <pvinis@gmail.com>
This PR resolves [CX-1214]
-
-
-
- Add update changelog to CI, mounir, pavlos
</details>
[CX-1214]: https://artsyproduct.atlassian.net/browse/CX-1214
#run_new_changelog_check
=> feat: add update changelog script to CI

.circleci/config.yml, Artsy/App/ARAppDelegate.h, Artsy/App/ARAppDelegate.m, Artsy/App/ARAppNotificationsDelegate.m, Artsy/App_Resources/Artsy-Info.plist
This PR resolves [CX-1678]
- Adds option at sdk startup to explicitly state our custom endpoint, the plist integration seems to not have worked
- Adds push notification registration and handling methods
-
-
-
- Fix iOS braze integration
</details>
[CX-1678]: https://artsyproduct.atlassian.net/browse/CX-1678
=> fix: fix iOS braze integration

CHANGELOG.yml, src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx, src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
This PR resolves [CX-1617]
```
Rail header tap
{
"context_screen": "Home",
"context_screen_owner_type": "home",
"action": "tappedAuctionResultGroup",
"context_module": "auctionResultsRail",
"destination_screen_owner_type": "auctionResultsForArtistsYouFollow",
"type": "header"
}
Rail thumbnail tap
{
"context_screen": "Home",
"context_screen_owner_type": "home",
"action": "tappedAuctionResultGroup",
"context_module": "auctionResultsRail",
"destination_screen_owner_type": "auctionResult",
"destination_screen_owner_id": "315289",
"horizontal_slide_position": 1,
"type": "thumbnail"
}
Screen thumbnail tap
{
"action": "tappedAuctionResultGroup",
"context_module": "auctionResultsForArtistsYouFollow",
"context_screen_owner_type": …
```
=> fix: Adjust auction results for you tracking

CHANGELOG.yml, src/lib/Scenes/Home/Home.tsx, src/lib/store/config/features.ts
- Make home auction results available for release
- Give the flag a better name
-
-
-
- Make home auction results by followed artists available for release 
- Rename the flag
</details>
=> chore: make home auction results available for release

CHANGELOG.yml, src/lib/Components/LoadFailureView.tsx
This PR resolves [CX-1668]
- Add Tracking to "unable to load" screen
https://user-images.githubusercontent.com/11945712/124904995-dccf2580-dfe5-11eb-85ac-30e303660757.mov
-
-
-
- Add tracking to unable to load screen
</details>
[CX-1668]: https://artsyproduct.atlassian.net/browse/CX-1668
=> feat: add tracking to unable to load screen

src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx, src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
This PR resolves [FX-3073]
- copy changes on iOS notifications saved search flow
- copy changes on Profile > PushNotifications screen
|PushAuthorizationStatus.Denied|PushAuthorizationStatus.NotDetermined|
|---|---|
|![IMG_4488](https://user-images.githubusercontent.com/21178754/124906762-b6aa8500-dfe7-11eb-9a95-e2317a494e18.PNG)|![IMG_4478](https://user-images.githubusercontent.com/21178754/124902505-47cb2d00-dfe3-11eb-800c-c6053680cd6c.PNG)|
|![IMG_4487](https://user-images.githubusercontent.com/21178754/124906960-e48fc980-dfe7-11eb-8d77-24611fa12795.PNG)|![IMG_4486](https://user-images.githubusercontent.com/21178754/124906966-e5c0f680-dfe7-11eb-9678-f29dd32a05b6.PNG)|
- copy changes on iOS …
=> chore: update copy on iOS notifications saved search flow and profile 

src/lib/Components/Home/ArtistRails/ArtistRail.tsx, src/lib/Scenes/Home/Components/FairsRail.tsx, src/lib/Scenes/Home/Components/__tests__/FairsRail-tests.tsx, src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
The type of this PR is: **Update**
This PR resolves [CX-1347]
Artsy is moving away from Sentence Case across Titles and CTAs throughout the UI. I'm starting this change by updating all titles in the App Home Feed.
_Home screen_
-
-
-
-
</details>
[CX-1347]: https://artsyproduct.atlassian.net/browse/CX-1347
=> Update home feed titles to title case

Artsy/App_Resources/Artsy-Info.plist
This PR resolves [CX-1709]
Firebase [swizzles](https://nshipster.com/method-swizzling/) some push notification handling methods to make setup easier, It seems our own method swizzling is not playing nicely with this and causing a crash on opening a push notification. This disables this behavior with a value in the plist.
Note this means when integrate messaging we will have to take a couple extra steps: 
https://firebase.google.com/docs/cloud-messaging/ios/client#token-swizzle-disabled
-
- Fix crash in push notification opens - Brian
-
-
</details>
[CX-1709]: https://artsyproduct.atlassian.net/browse/CX-1709
=> fix: push crash, disable method swizzling for firebase

fastlane/metadata/en-US/release_notes.txt
=> update release notes

src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
This PR resolves [CX-938]
before
after
-
- Fix spacing on Viewing Room Artworks - pavlos
-
-
</details>
[CX-938]: https://artsyproduct.atlassian.net/browse/CX-938
=> fix(styling): Viewing Room Artwork spacing

src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
=> fix: Add auction results for you section header space

__tests__/dangerRules/validateChangelogYMLFile-tests.ts, dangerfile.ts, docs/pull_request_template.md, scripts/changelog/generatePlatformChangelog-tests.ts, scripts/changelog/parsePRDescription-tests.ts, scripts/changelog/parsePRDescription.js
The type of this PR is: **AWESOMENESS**
Thanks @ds300 and @MounirDhahri for doing this work 💜!
I'm just removing the opt-in here, so we are officially using this from now on. ✂️🎀
-
-
-
- Rejoice! No more fighting with CHANGELOG conflicts! - david, mounir
</details>
=> WE DONT NEED THIS ANYMORE!! IM SO EXCITEDDDDDD!!!!!!! WOOP WOOOOOP

docs/getting_started.md
we don't really need this.
-
-
-
-
#nochangelog
</details>
=> fix(docs): we dont need this

src/__generated__/SavedAddressesQuery.graphql.ts, src/__generated__/SavedAddressesRefetchQuery.graphql.ts, src/__generated__/SavedAddressesTestsQuery.graphql.ts, src/__generated__/SavedAddresses_me.graphql.ts, src/lib/Scenes/SavedAddresses/SavedAddresses.tsx, src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
This PR resolves [PURCHASE-2763]
- Implement design of card - the way the address is presented.
- Fetch and list existing saved addresses.
|Android|iOS|
|---|---|
|![Screenshot_1626183396](https://user-images.githubusercontent.com/21178754/125462882-a7bb4d01-ca38-463a-93ce-896a7ef12a05.png)|![Simulator Screen Shot - iPhone 8 - 2021-07-13 at 15 33 45](https://user-images.githubusercontent.com/21178754/125462885-8a1ec793-670f-48fb-b131-e4a8d02e1ed7.png)|
@artsy/purchase-devs
- Implemented SavedAddresses List Item
-
-
-
</details>
[PURCHASE-2763]: https://artsyproduct.atlassian.net/browse/PURCHASE-2763
=> feat: add saved address list item and fetch saved addresses

src/__generated__/SavedAddressesQuery.graphql.ts, src/__generated__/SavedAddressesRefetchQuery.graphql.ts, src/__generated__/SavedAddressesTestsQuery.graphql.ts, src/__generated__/SavedAddresses_me.graphql.ts, src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
This PR resolves [PURCHASE-2762]
1. Default flag/label on applicable address
1. Outline of address which is default is black versus grey where it isn't. 
1. In order added after default on top (new first)
|iOS|Android|
|---|---|
|![Simulator Screen Shot - iPhone 8 - 2021-07-14 at 10 06 28](https://user-images.githubusercontent.com/21178754/125586959-71a9ce0a-ad0a-40fd-97ae-f45f21855c84.png)|![Screenshot_1626249996](https://user-images.githubusercontent.com/21178754/125586957-8b024222-857b-459e-8765-e045f4e9c1ad.png)|
|iOS|Android|
|---|---|
|![Simulator Screen Shot - iPhone 8 - 2021-07-14 at 14 07 22](https://user-images.githubusercontent.com/21178754/125619373-40946eac-b5a1-4b76-9fae-6e3ecacab2a9.png)|![Screenshot_1626264420](https://user-images.githubu …
=> feat: default view of an address when multiple are saved

CHANGELOG.yml, app.json
- Prepare for 6.10.1
#nochangelog
=> chore: Prepare for 6.10.1

src/__generated__/SavedAddressesDeleteUserAddressMutation.graphql.ts, src/__generated__/deleteSavedAddressDeleteUserAddressMutation.graphql.ts, src/lib/Scenes/SavedAddresses/SavedAddresses.tsx, src/lib/Scenes/SavedAddresses/mutations/deleteSavedAddress.ts
This PR resolves [PURCHASE-2787]
- Allow an address to be deleted when a user selects the delete text link on the card by adding a deleteAddress mutation
https://user-images.githubusercontent.com/21178754/125631970-70c8fe18-44f1-4223-9a1f-91f913da82e7.mp4
- Enables users to delete saved addresses
-
-
-
</details>
[PURCHASE-2787]: https://artsyproduct.atlassian.net/browse/PURCHASE-2787
=> feat: add delete address functionality

Podfile, Podfile.lock
I noticed that running pod install will cause sometimes to have a bunch of duplicate tokens in .netrc. After this change, if a pod install run is successful, there should be no tokens in the .netrc. It will only be added temporarily to download, and then it should go away, until next time.
https://user-images.githubusercontent.com/100233/126200303-e679ba25-e955-4165-a75d-99cb93ec5568.mov
-
-
-
- Fix .netrc during pod install for duplicate mapbox tokens - pavlos
</details>
=> fix(scripts): better handling of .netrc

Artsy/App_Resources/Artsy-Info.plist
- enables verbose logging in order to troubleshoot integration, this should be disabled before releasing to App Store
-
-
-
- Enable verbose logging for braze sdk - Brian
</details>
=> chore: enable braze verbose logging #trivial

Artsy/App/ARAppDelegate.m
🤦 🙈 
-
-
-
- Use the right key for braze - Brian
</details>
=> fix: copy paste error braze prod api

src/__generated__/FairArticlesQuery.graphql.ts, src/__generated__/FairArticles_fair.graphql.ts, src/__generated__/FairEditorialTestsQuery.graphql.ts, src/__generated__/FairEditorial_fair.graphql.ts, src/__generated__/FairQuery.graphql.ts, src/__generated__/FairTestsQuery.graphql.ts, src/__generated__/Fair_fair.graphql.ts, src/__generated__/VanityURLEntityQuery.graphql.ts, src/lib/Scenes/Fair/Components/FairEditorial.tsx, src/lib/Scenes/Fair/Fair.tsx, src/lib/Scenes/Fair/FairArticles.tsx
This PR resolves [[CX-1564](https://artsyproduct.atlassian.net/browse/CX-1564)]
Adding inEditorialFeed: true to articlesConnection for all Fair and Other Queries. Please only merge this PR after the one from  [metaphysics#3291](https://github.com/artsy/metaphysics/pull/3291).   
( cc @pvinis )
- Adding inEditorialFeed: true to articlesConnection for all Fair and Other Queries. - christian
</details>
=> [CX-1564] Adding inEditorialFeed: true to articlesConnection for all Fair and Other Queries

Podfile.lock
In #5145 I totally added a not updated lockfile. I don't know how CI didn't complain til now, but here's the updated lockfile.
#nochangelog
-
-
-
-
</details>
=> fix(podfile.lock): revert an oopsie

src/__generated__/SavedAddressesQuery.graphql.ts, src/__generated__/SavedAddressesRefetchQuery.graphql.ts, src/__generated__/SavedAddressesTestsQuery.graphql.ts, src/__generated__/SavedAddresses_me.graphql.ts, src/lib/Scenes/SavedAddresses/SavedAddresses.tsx, src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx, src/lib/navigation/navigate.ts
This PR resolves [PURCHASE-2788]
"goBack" listener was added. Also, add this listener for both platforms. 
If I understand correctly `LegacyNativeModules.ARScreenPresenterModule.goBack(unsafe__getSelectedTab())` doesn't provide us refetch logic
-
-
-
-
</details>
[PURCHASE-2788]: https://artsyproduct.atlassian.net/browse/PURCHASE-2788
=> feat: auto refresh for goBack event in view page [PURCHASE-2788]

.secrets.baseline, package.json, yarn.lock
This PR resolves [CX-1628]
Adds a [detect-secrets](https://github.com/Yelp/detect-secrets) from Yelp as a pre-commit hook as descriped [here](https://github.com/lirantal/detect-secrets) using this [detect-secrests npm package](https://www.npmjs.com/package/detect-secrets).
Adding a `ARTSY_API_CLIENT_SECRET` to `Home.tsx`, results in:
```
✖ detect-secrets-launcher:
ERROR: Potential secrets about to be committed to git repo!
Secret Type: Secret Keyword
Location:    /Users/ole/artsy/eigen/src/lib/Scenes/Home/Home.tsx:66
Possible mitigations:
- For information about putting your secrets in a safer place, please ask in
#security
- Mark false positives with an inline `pragma: allowlist secret`
comment
If a secret has already been committed, visit …
```
=> chore: Add detect-secrets pre-commit hook

Artsy/App/ARAppDelegate.h, Artsy/App/ARAppDelegate.m, Artsy/App/ARAppNotificationsDelegate.h, Artsy/App/ARAppNotificationsDelegate.m, emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m
This PR resolves [CX-1678]
- Moves braze push handling to BEFORE our own push handling to fix a deeplink issue
- Adds UserNotification center delegate methods
- Adds some logging to debug in TestFlight - to be removed
-
- 
-
- Braze integration follow-ups - Brian
</details>
[CX-1678]: https://artsyproduct.atlassian.net/browse/CX-1678
=> fix: braze once more

src/lib/Scenes/Home/Components/SalesRail.tsx, src/lib/Scenes/Sales/index.tsx
This PR resolves [CX-1715]
There was a screen tracking provider wrapping the auctions home rail causing a screen event to be fired every time home was rendered. This moves that provider to the Sales component instead.
-
-
-
- Fix tracking for auctions screens - Brian
</details>
[CX-1715]: https://artsyproduct.atlassian.net/browse/CX-1715
=> fix: move auctions tracking to screen component

package.json
-
-
-
- Create storybook config file when starting Android - ole
</details>
=> fix: Set storybook env when starting android

src/lib/relay/middlewares/__tests__/errorMiddleware-tests.ts, src/lib/relay/middlewares/errorMiddleware.ts
This PR resolves [CX-1722]
This PR is a fix for Sentry errors where it shows the error title as **[unknowns]**. Now with this fix, we can see the error message as the title. 
For eg, for [this](https://sentry.io/organizations/artsynet/issues/2339408559/?query=is%3Aunresolved) sentry issue. We will get **ESOCKETTIMEDOUT** as the title instead of **[unknown]**
-
-
-
- Showing the error message as the title instead of [unknown].
</details>
[CX-1722]: https://artsyproduct.atlassian.net/browse/CX-1722
=> fix(CX-1722): [unknown] sentry errors

src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx, src/lib/Components/ArtworkFilter/Filters/KeywordFilter.tsx, src/lib/Components/Input/Input.tsx
This PR resolves [CX-1742]
https://user-images.githubusercontent.com/4691889/127331410-a48b838a-526e-4e32-b596-19add1b2a2f0.mp4
- Show loading spinner on artist auction result keyword filter input - ole
-
-
-
</details>
[CX-1742]: https://artsyproduct.atlassian.net/browse/CX-1742
=> feature: Add loading indicator to keyword filter input

src/lib/Scenes/Home/Components/SaleArtworksHomeRail.tsx, src/lib/Scenes/Home/Components/__tests__/SaleArtworksHomeRail-tests.tsx
This PR resolves [CX-1602]
- change auction lots for you ending soon title to title case - ole
-
-
-
</details>
[CX-1602]: https://artsyproduct.atlassian.net/browse/CX-1602
=> fix: change auction lots for you ending soon title to title case

src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx, src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx, src/lib/Scenes/SaleFAQ/SaleFAQ.tsx, src/lib/Scenes/VanityURL/__tests__/VanityURLPossibleRedirect-tests.tsx, src/lib/Scenes/ViewingRoom/ViewingRoom.tsx, src/lib/navigation/__tests__/routes-tests.tsx, src/lib/navigation/routes.tsx, src/lib/store/config/EnvironmentModel.tsx
This PR resolves [CX-1612]
This PR changes the production artsy web URL form `https://artsy.net` to `https://www.artsy.net` to avoid unnecessary redirects and fix the `Auction FAQs` screen which fails to load due to the redirect. 
- fix auction FAQs not loading - ole
- Add www to artsy web url (https://artsy.net -> https://www.artsy.net) / fix Auction FAQs screen - ole
-
-
-
</details>
[CX-1612]: https://artsyproduct.atlassian.net/browse/CX-1612
=> fix: Add www to web url

src/lib/Components/Artist/ArtistHeader.tsx, src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx, src/lib/Components/ArtworkFilter/Filters/KeywordFilter.tsx
This PR resolves [CX-1742]
-
-
-
-
</details>
[CX-1742]: https://artsyproduct.atlassian.net/browse/CX-1742
=> fix: Adjust keyword filter loading indicator timing

src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx, src/lib/Scenes/SavedAddresses/__tests__/SavedAddressesForm-tests.tsx
This PR resolves [PURCHASE-2812]
Added 'Delete Address' text link in Saved address edit form. 
-
- 
-
- Delete address text link is added in the edit form. It will delete the address and navigate the user back to the list of Saved address screen. 
</details>
[PURCHASE-2812]: https://artsyproduct.atlassian.net/browse/PURCHASE-2812
=> feat: Delete address through edit form

src/lib/store/config/features.ts
The type of this PR is: Chore
This PR resolves [CX-1744]
Depends on https://github.com/artsy/echo/pull/110/
-
-
-
-
</details>
[CX-1744]: https://artsyproduct.atlassian.net/browse/CX-1744
=> Release auction results keyword filter and add echo

Artsy/App/ARAppDelegate+Emission.m, Artsy/App/ARAppDelegate.m, Artsy/Networking/API_Modules/ARUserManager.h, Artsy/Networking/API_Modules/ARUserManager.m, Artsy/Networking/ARRouter.m, Artsy_Tests/Networking_Tests/API_Modules/ARUserManagerTests.m, src/lib/AppRegistry.tsx
Fixes a bug where user who logged in and uninstalled would not be able to create an account the next time they open the application. Seems as though in certain scenarios this can happen even without the uninstall event.
- Clears out access token when setting up Emission if there is no authenticated user
- Deletes all cookies on logout, not just those associated with artsy domains
- Overrides default behavior of passing cookies automatically on native side
- Puts the useWebViewCookies behind a logged in check to avoid cookie refresh when logging in
-
- Fix a bug where in certain scenarios previously logged in users cannot create accounts - brian
-
-
</details>
=> fix: persisting auth cookie

.secrets.baseline, package.json, src/lib/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx, src/lib/store/AuthModel.ts, src/lib/store/__tests__/AuthModel-tests.ts
This PR resolves [CX-1419]
| ![Simulator Screen Shot - iPhone 8 - 2021-07-30 at 13 21 07](https://user-images.githubusercontent.com/4691889/127645952-1d4ea4dd-ca75-42a9-90ea-a81ac52aae00.png) |
||
- Add separate marketing email checkbox to new signup flow - ole
-
-
-
</details>
[CX-1419]: https://artsyproduct.atlassian.net/browse/CX-1419
=> feature: Add signup marketing email checkbox

.gitignore
I noticed that a few of these `.gitkeep` files were in our repo, and they were not needed. One is needed, in `Emission`, but we did not have it in our gitignore, so basically it was accidentally kept.
Now we have the files cleaned up, and we actually make sure to keep them.
-
-
-
- Use `.gitkeep` files correctly - pavlos
</details>
=> tooling(git): fix up `.gitkeep`

src/lib/Scenes/SaleFAQ/SaleFAQ.tsx
The top padding looks different in the Simulator, so I removed the increased top padding that was introduced in https://github.com/artsy/eigen/pull/5109.
-
-
-
-
</details>
=> fix: Decrease auctionFAQs top padding

Artsy/App_Resources/Artsy-Info.plist, src/lib/AppRegistry.tsx, src/lib/Components/ArtsyReactWebView.tsx
I broke the rules of hooks by having cookies generation conditioned on isLoggedIn: https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level
Moved the check to inside the function.
Also disable braze verbose logging.
-
-
-
- Fix login crash - brian
</details>
=> fix: login crash

src/lib/tests/__tests__/MockRelayRenderer-tests.tsx, src/palette/elements/Spinner/Spinner.tsx
- Fix the missing spinner on buttons - ole, brian, pavlos
-
-
-
</details>
=> fix(button spinner): cherry-pick some work from ole's button PR

src/lib/Scenes/SavedAddresses/SavedAddressNotification.tsx, src/lib/Scenes/SavedAddresses/SavedAddresses.tsx, src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx, src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx, src/lib/navigation/navigate.ts
The type of this PR is: **FEAT**
This PR resolves [PURCH-2789]
This PR resolves [PURCH-2761]
Adds notifications when users create, edit, or delete a saved address. This PR does not include adding the swipe left to dismiss the notification functionality.  Many thanks to @xtina-starr for the pairing!
- Adds a Notification when users add, edit, or delete a Saved Address
-
-
-
</details>
=> feat: show notifs when saved addresses added, updated, or deleted

src/lib/AndroidApp.tsx, src/lib/store/GlobalStore.tsx, src/lib/store/GlobalStoreModel.ts, src/lib/store/PendingPushNotificationModel.ts, src/lib/store/__tests__/migration-tests.ts, src/lib/store/migration.ts, src/lib/utils/PushNotification.ts, src/lib/utils/__tests__/PushNotification-tests.ts, src/setupJest.ts
This PR resolves [CX-1768]
Handles the display and proper routing of users based on custom data in push notification payload.
- if user is logged in, tapped push notification is handled immediately
- If user is not logged in, tapped push notification is temporarily saved and handled if user logs in within 90 seconds else it is discarded.
https://user-images.githubusercontent.com/18648835/127865744-c113a3f8-a340-481a-9fa5-befdcbdf6b65.mov
-
-
-Handles the display and proper routing of users based on custom data in push notification payload.
-
</details>
[CX-1768]: https://artsyproduct.atlassian.net/browse/CX-1768
=> Feat (CX-1768): handle data in notification

app.json
This PR resolves https://artsy.slack.com/archives/C02BAQ5K7/p1628232050094800
-
-
-
- Fix broken build, mounir
</details>
=> Prepare for 6.10.3

src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx, src/lib/Components/Home/CardRailCard.tsx, src/lib/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx, src/lib/Scenes/Search/Search.tsx
`object-form attrs({})` keys are now deprectaed in `styled-components`. This PR switches to the new `attr(props => ({}))` syntax which will remove the warning (see screenshot).
-
-
-
- Remove deprecated object-form attrs({}) keys in styled-components - ole
</details>
=> fix: Remove deprecated object-form attrs({}) keys

src/lib/AndroidApp.tsx, src/lib/store/PendingPushNotificationModel.ts, src/lib/store/__tests__/migration-tests.ts, src/lib/store/migration.ts, src/lib/utils/PushNotification.ts, src/lib/utils/__tests__/PushNotification-tests.ts, src/lib/utils/useInitialNotification.ts, src/setupJest.ts
This PR resolves [CX-1768]
Fixes general concerns raised regarding handling of push notifications in [this PR](https://github.com/artsy/eigen/pull/5208)
- create channels on app start
- stop unsetting url when passing push notif props (as eigen rerouting logic is not based on url prop, thus making the url unsetting confusing to devs)
- unify android & ios pending notification objects
-
-
-
- Update general android push notification handling logic - kizito
</details>
[CX-1768]: https://artsyproduct.atlassian.net/browse/CX-1768
=> feat(cx-1768): fix concerns raised in handling of push notifications

.secrets.baseline, src/lib/Components/Bidding/Components/BidInfoRow.tsx, src/lib/Components/Bidding/Components/BiddingThemeProvider.tsx, src/lib/Components/Bidding/Components/PaymentInfo.tsx, src/lib/Components/Bidding/Components/__tests__/Checkbox-tests.tsx, src/lib/Components/Bidding/Components/__tests__/Input-tests.tsx, src/lib/Components/Bidding/Components/__tests__/PaymentInfo-tests.tsx, src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx, src/lib/Components/Bidding/Components/__tests__/Title-tests.tsx, src/lib/Components/Bidding/Context/__tests__/TimeOffsetProvider-tests.tsx, src/lib/Components/Bidding/Elements/Grid.tsx, src/lib/Components/Bidding/Elements/Theme.tsx, src/lib/Components/Bidding/Screens/BidResult.tsx, src/lib/Components/Bidding/Screens/BillingAddress.tsx, src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx, src/lib/Components/Bidding/Screens/CreditCardForm.tsx, src/lib/Components/Bidding/Screens/Registration.tsx, src/lib/Components/Bidding/Screens/RegistrationResult.tsx, src/lib/Components/Bidding/Screens/__tests__/BidResult-tests.tsx, src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx, src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx, src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx, src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx, src/lib/Components/Input/InputTitle.tsx, src/lib/Components/Select.tsx, src/palette/Theme.tsx
This reverts commit b80f2d01f8b255b2a7af67afad26a86cd80d549b.The type of this PR is: **TYPE**
Before
After
-
-
-
-
</details>
#nochangelog
=> sigh(theme providers): bring back bidding provider until we are ready to replace this :(

src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
The type of this PR is: enhancement 
This PR resolves [FX-3163]
Reorder artwork filters within a series to remain consistent with desired order. 
- Reorder artwork filters on series screen - rquartararo
-
-
-
</details>
[FX-3163]: https://artsyproduct.atlassian.net/browse/FX-3163
=> feat: reorder artwork filters on artist series screen

docs/pull_request_template.md
Just a tiny fix.
-
-
-
-
</details>
#nochangelog
=> docs: MX -> CX

src/__generated__/PartnerArtworkInfiniteScrollGridQuery.graphql.ts, src/__generated__/PartnerArtworkTestsQuery.graphql.ts, src/__generated__/PartnerArtwork_partner.graphql.ts, src/__generated__/PartnerQuery.graphql.ts, src/__generated__/PartnerRefetchQuery.graphql.ts, src/__generated__/VanityURLEntityQuery.graphql.ts, src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx, src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
This PR resolves [FX-3160]
Gallery show filter is aligned in the following order
- Sort By
- Artists 
- Rarity
- Medium
- Price 
- Size
- Ways to Buy
- Material
- Artist Nationality & Ethnicity
- Time Period
- Color 
Before
After
- Reorder artwork filters on gallery screen - rajsam003
-
-
-
</details>
[FX-3160]: https://artsyproduct.atlassian.net/browse/FX-3160
=> chore: align artworks filters on gallery screen

.secrets.baseline, src/__generated__/MyProfileQuery.graphql.ts, src/lib/Scenes/MyProfile/MyProfile.tsx, src/lib/relay/middlewares/metaphysicsMiddleware.ts, src/lib/store/GlobalStoreModel.ts, src/lib/utils/AdminMenu.tsx, src/setupJest.ts
We had few reports from users being **unable to log out and login** to the app and consistently getting the **Unable to Load** screen.
I guess we, unfortunately, have few hundred of users at least affected by this: https://sentry.io/organizations/artsynet/issues/2541915792/?project=166784&query=is%3Aunresolved
The only way the error described above could occur and the user does not get logged out is if **the user has no access token on the native side** for some reason. By tracking back how this could be possible, I found out that during the **signOut**, which normally happens when the user access token is invalid or does not exist we do the following:
1. we clear the native state using a native module (**this seem to have worked properly since we have …
=> fix: Unable to logout and login + Unable to load failures

src/lib/Components/LoadFailureView.tsx, src/lib/relay/middlewares/errorMiddleware.ts
This PR resolves [CX-1703]
This PR contains 2 parts that you can navigate by commit:
1. **Leverage Datadog/Statd to track graphql request failures**
i. Include tracking as part of the relay errorMiddleware
ii. Include the **operation kind** (mutation/query), **query name** (HomeQuery...) and the **handler** (default, @optionalField or @principalField). The handler is needed here to know exactly how much the @optionalField is helping us.
2. **Remove old way of tracking those failures**
_The board looks like this on Datadog_** 
Link: https://app.datadoghq.com/dashboard/ib7-8gr-u6x/eigen-graphql-requests-with-errors
-
-
-
- improve tracking for "unable to load" - mounir
</details>
[CX-1703]: …
=> enhancement: improve tracking for "unable to load"

Artsy/Views/Styled_Subclasses/Buttons/ARNavigationButton.m, emission/Pod/Classes/EigenCommunications/ARPHPhotoPickerModule.m
This PR resolves [CX-1794]
- Moves photo picker configuration to main thread
- Fixes some warnings in the photo picker module and navigation button
Not totally clear if this was causing crash but was causing photo picker not to show up on my device on iOS 15 simulator but wasn't crashing.
@pvinis if you could try running on device and seeing if this fixes I would appreciate 🙏 
-
- Fix photo picker presentation on iOS 15 - Brian
-
-
</details>
[CX-1794]: https://artsyproduct.atlassian.net/browse/CX-1794
=> fix: iOS 15 photo picker thread

fastlane/Fastfile
Updates our external tester group name in fastlane that was updated in App Store connect so our builds get distributed to everyone. 
-
-
-
- Fix external tester group name for beta distribution - brian
</details>
=> fix: update external tester group name

src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchAlertsListPlaceholder.tsx, src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx, src/lib/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
After a little QA session, it was decided to show loading placeholder during the refetch operation on saved search list screen. You can find more context [here](https://artsy.slack.com/archives/C9SATFLUU/p1628785754409200?thread_ts=1628779499.394600&cid=C9SATFLUU)
https://user-images.githubusercontent.com/3513494/129240015-53fdca21-1009-4c5a-843d-925435430192.mp4
https://user-images.githubusercontent.com/3513494/129241151-ca9f6462-a10c-4f49-97e5-3ad3e4b7c31c.mp4
- 
-
-
- Show loading placeholder on the saved search list screen
</details>
=> feat: show loading placeholder

src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
Small fixes for Saved Search Button M2
- 
-
-
- Pass empty filters to saved search when empty criteria
</details>
=> fix: pass empty filters to saved search button

src/__generated__/EditSavedSearchAlertQuery.graphql.ts, src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
After a little QA session, a bug was found by @mdole. More context [here](https://artsy.slack.com/archives/C9SATFLUU/p1628784176405800?thread_ts=1628779499.394600&cid=C9SATFLUU)
> I created a saved search with two different mediums (Sculpture, Drawing). When I later navigated to the "edit" screen for that saved search, I only saw one of two mediums from my original filter in the edit screen (Drawing). I tried again to replicate, and this time I didn't see any of the mediums in the edit screen. They're definitely saved to the database; I double-checked in Gravity
https://user-images.githubusercontent.com/3513494/129245736-dc2e2766-487e-4461-9aff-c16ff5a51137.mp4
#nochangelog
=> fix: get correct aggregations for saved search

Podfile.lock, src/lib/Scenes/Home/Home.tsx
This PR resolves [CX-1716]
- Fix analytics events triggering multiple times
-
-
-
- Fix analytics events triggering multiple times
</details>
[CX-1716]: https://artsyproduct.atlassian.net/browse/CX-1716
=> fix(CX-1716): Analytics events triggering multiple times

src/__generated__/GeneArtworksPaginationQuery.graphql.ts, src/__generated__/GeneArtworksTestsQuery.graphql.ts, src/__generated__/GeneArtworks_gene.graphql.ts, src/__generated__/GeneQuery.graphql.ts, src/__generated__/GeneTestsQuery.graphql.ts, src/__generated__/TagArtworksPaginationQuery.graphql.ts, src/__generated__/TagArtworksTestsQuery.graphql.ts, src/__generated__/TagArtworks_tag.graphql.ts, src/__generated__/TagQuery.graphql.ts, src/__generated__/TagTestsQuery.graphql.ts, src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx, src/lib/Components/Gene/GeneArtworks.tsx, src/lib/Components/Tag/TagArtworks.tsx
This PR resolves [FX-3166]
Gene and Tag filter is aligned in the following order
- Artists
- Rarity
- Medium
- Price 
- Size
- Ways to Buy
- Material
- Artist Nationality & Ethnicity
- Artwork Location
- Time Period
- Color
- Galleries & Institutions
Before:
After: 
- Reorder artwork filters on Gene and Tag screen - rajsam003
-
-
-
</details>
[FX-3166]: https://artsyproduct.atlassian.net/browse/FX-3166
=> chore: Tag and Gene filter Alignment

src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx, src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx, src/lib/Scenes/Onboarding/OnboardingWelcome.tsx, src/lib/Scenes/Onboarding/__tests__/OnboardingWelcome-tests.tsx, src/lib/store/AuthModel.ts, src/lib/store/__tests__/AuthModel-tests.ts, src/lib/store/config/features.ts
This PR resolves [CX-1755]
This PR does two things:
-  Improving the UX by returning user-friendly error messages when the signup fails. The logic is inspired by what we do on the web and that can be found in artsy-passport here https://github.com/artsy/artsy-passport/blob/5f464a55c859d9a6e5f6bccaa92fd3661c88d21d/lib/app/lifecycle.js
- Adding the feature flag to the onboarding welcome screen in order to navigate to the user flow
**Android**
https://user-images.githubusercontent.com/11945712/129567739-4c7ddd41-05d3-4df0-9152-ede226089c49.mov
**iOS**
https://user-images.githubusercontent.com/11945712/129567768-ec5f0ea2-6f8d-49eb-b931-c5fb1900f3ae.mov
- Return friendly user-friendly error messages on failed …
=> feat: show relevant error messages on the onboarding

src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx, src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
Close the keyboard while scrolling the form
https://user-images.githubusercontent.com/3513494/129573939-ecd6ce92-5f3d-40c4-ad90-287fd673b35c.mp4
-
-
-
- Close keyboard during scroll saved search form
</details>
=> chore: close keyboard during scroll

scripts/changelog/commitChangelog.js
- fix typo to call function 😢
-
-
-
- Fix typo to call `createAndMergePullRequest()`
</details>
=> fix: typo to call function

src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
This PR resolves [CX-1698]
- Track link tap and Auction Results Screen
-
-
-
- Track link tap and AuctionResultsForYou Screen - kizito
</details>
[CX-1698]: https://artsyproduct.atlassian.net/browse/CX-1698
=> Enhancement: Track Link Tap in Auction Results For You

app.json
This PR prepares for version **7.0.0**
=> chore: preparing for development, version 7.0.0

scripts/changelog/generatePlatformChangelog-tests.ts, scripts/changelog/generatePlatformChangelog.js
The goal from this PR is to make sure that the changelog update PR gets only created when something changes in the changelog. The issue with the current implementation is the fact that we are saving the changelog update date every time we run the script and therefore the generated changelog file is going to be always different since the date is never the same and therefore unnecessary commits. By removing the changelog date for beta builds, we avoid that. 
-
-
-
- Do not save the changelog update date - mounir
</details>
=> chore: Remove changelog update date

CHANGELOG/android-changelog.md, CHANGELOG/ios-changelog.md
This is an automatic PR to update the changelog ✍️
=> Update Changelog ✍️

src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
This PR adds a test to make sure that the delete mutation is called with the correct input after the user presses delete address button.
Also updated the test file to use `@testing-library/react-native`
-
-
-
- add tests for delete address - gkartalis
</details>
=> spec: update tests to use RNTL and add test for delete address

.circleci/config.yml, scripts/setup-distribute-macos
The `build-test-app-ios` job on circle ci stopped working [see this failed job for the error](https://app.circleci.com/pipelines/github/artsy/eigen/16026/workflows/ce34d9d6-3870-43d7-bb8d-8e5e01d7d4e8/jobs/44934) and from a small research that I did found [this problem](https://discuss.circleci.com/t/brew-link-step-failing-on-python-dependency/33925/2) on circle ci that has to do with brew and python dependencies auto update.
They suggest that the recommended way of solving this is by [Disable Homebrew Automatic Updater](https://support.circleci.com/hc/en-us/articles/360037683553-Disable-Homebrew-Automatic-Updater?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo4MjgyMDksInVzZXJfaWQiOjQwMDY1Njg5NTEzMywidGlja2V0X2lkIjo2N …
=> fix: remove brew update distribute-macos script

src/lib/Scenes/SavedAddresses/SavedAddresses.tsx, src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
This PR resolves [PURCHASE-2789]
- Show notifications when users add, update, or delete saved addresses
-
-
-
</details>
[PURCHASE-2789]: https://artsyproduct.atlassian.net/browse/PURCHASE-2789
=> feat: add saved addresses notifs using toast hook 

src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
This PR resolves [FX-3218]
* As a user
* When I navigate to the create saved search alert screen
* I see push notification copy at the top of the create alert screen
* "You will be able to access all your Saved Alerts in your Profile."
* And I see copy at the bottom of the create alert screen 
* “Receive alerts as Push Notifications directly to your device.“
* [Figma](https://www.figma.com/file/zbEFZqjKgKquZwtU8U44j9/Saved-Search-M2?node-id=2383%3A5548)
- Update copies for create saved search alert screen - dzmitry tratsiak
-
-
-
</details>
[FX-3218]: https://artsyproduct.atlassian.net/browse/FX-3218
=> fix(FX-3218): update copies saved search

src/__generated__/HomeAboveTheFoldQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/Home_homePageAbove.graphql.ts, src/lib/Scenes/Home/Home.tsx
We should not set `maxRails` in the home screens above-the-fold query in case we want to include more than 2 artwork modules in the above-the-fold query. Using the `INCLUDE` variable makes sure we don't fetch more artwork modules than specified. Setting the value to -1 will unset the restriction.
- Don't restrict number of artwork modules  in the home screen above-the-fold query - ole
-
-
-
</details>
=> fix: Dont restrict number of artwork rails in home screen above-the-fold query

src/lib/Scenes/MyProfile/MyProfile.tsx
This PR resolves [FX-3217]
The **Saved Alerts** section in the Profile tab should live underneath the **My Collection** tab
1. My Collection
2. Saved Alerts
3. Saves and follows
4. etc
-
-
-
- Place "saved alerts" above "my collection" - dzmitry tratsiak
</details>
[FX-3217]: https://artsyproduct.atlassian.net/browse/FX-3217
=> fix: place saved alerts under my collection

src/lib/Scenes/SavedSearchAlert/Components/Form.tsx, src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchAlertsListPlaceholder.tsx
Small improvements for Saved Search M2
#nochangelog
=> fix: saved search m2

src/lib/Components/PopoverMessage/PopoverMessage.tsx, src/lib/Components/PopoverMessage/__tests__/PopoverMessage-tests.tsx
This PR resolves [FX-3188]
https://user-images.githubusercontent.com/3513494/130801522-ff0e8f2e-baaa-4545-9952-93a464e09191.mp4
https://user-images.githubusercontent.com/3513494/130802317-39b3edf2-6d33-4a23-b72b-fece0ca13d9b.mp4
-  Update Popover Message to V3 design system - dzmitry tratsiak
-
-
-
</details>
[FX-3188]: https://artsyproduct.atlassian.net/browse/FX-3188
=> feat(FX-3188): update popover message to v3 design system

Podfile.lock, src/lib/Scenes/Search2/Search2.tsx, src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
This PR resolves [FX-3228]
Behind improved search feature flag:
- By default show results from our existing global search API (backed from ES)
- Render one pill "Artists" above results to switch to the new Algolia backed index
https://user-images.githubusercontent.com/21178754/131339608-b5be6e01-2afe-41c5-b97f-bb179bde79cd.mp4
- Improved search by default queries ES - gkartalis
- Adds Artists pill that switches to algolia search - gkartalis
-
-
-
</details>
=> feat(FX-3228): global combined search results by default

src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
This PR resolves [[CX-1853](https://artsyproduct.atlassian.net/browse/CX-1853)]
Scrollview is added in Make offer Modal. The cancel button and the text below can be displayed if there are multiple editions for an artwork. 
- Add ScrollView component in make offer modal- rajsam003
-
-
-
</details>
=> fix: Scrollview in make offer modal

fastlane/metadata/android/en-US/full_description.txt
Google play rejected us due to irrelevant info in our description, this removes said info :)
-
-
-
- Remove extra info from Android description - brian
</details>
=> chore: remove extra info from description #trivial

CHANGELOG.legacy.yml, src/lib/Components/ArtsyReactWebView.tsx, src/lib/Components/FancyModal/FancyModalHeader.tsx, src/lib/navigation/routes.tsx
Feature
This PR resolves[PURCHASE-840]
navigation back in BMNO flow
https://user-images.githubusercontent.com/37010996/131338269-1c38e688-ed7f-4173-8585-1ab83789a3b5.mov
https://user-images.githubusercontent.com/37010996/131338287-e2542a4c-46f4-4fc3-a0fd-6981697c2ec4.mov
=> feat:navigate back in BNMO [PURCHASE-840]

src/lib/AppProviders.tsx
Set Palette V3 toggle title correctly.
-
-
-
-
</details>
=> fix: Set Palette V3 toggle title correctly

src/lib/Scenes/Search2/Search2.tsx, src/palette/elements/Pill/Pill.stories.tsx, src/palette/elements/Pill/Pill.tsx, src/storybook/storyLoader.js
This PR resolves [FX-3239]
-
-
-
- Enhanced Pill component with variants and active props and added to storybook - gkartalis
</details>
[FX-3239]: https://artsyproduct.atlassian.net/browse/FX-3239
=> feat(FX-3239): Pill component enhancement and stories

.gitignore, Gemfile.lock, fastlane/Fastfile, fastlane/Pluginfile, scripts/setup-distribute-linux
This PR resolves [CX-1809]
Uploads android betas to firebase app distribution as well as google play alpha track. Firebase app distribution will be the typical place for devs to get betas for testing and google play will contain release candidates. The only difference between the two builds should be defaulting to staging in dev betas and defaulting to production in release candidates. This way we can test in betas and confidently promote the corresponding release candidate to the play store.
Implementation:
- Adds firebase app distribution fastlane plugin
- Builds the app twice with the beta flag set to true and false
- Uploads to google play and firebase app distribution
- Reverts earlier promotion change to just promote from google play rather than …
=> chore: firebase app distribution

src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
This PR resolves [PURCHASE-2899]
refetch data after deleting address on Android platform
-
- 
-
- refetch addresses after deleting - alexj105
</details>
https://user-images.githubusercontent.com/37010996/131480782-77ede842-9bd7-4ac4-9fd7-bf76dba3cf42.mov
=> fix:refetch data after deleting [PURCHASE-2899]

src/lib/Components/PopoverMessage/PopoverMessage.stories.tsx, src/storybook/storyLoader.js
https://user-images.githubusercontent.com/3513494/131339277-c9aab2f5-ed41-4f86-86dc-20c1e62c6152.mp4
-
-
-
- Add `PopoverMessage` component to Storybook - dimatretyak
</details>
=> feat: add popover message to storybook

src/lib/utils/AdminMenu.tsx
This PR resolves [CX-1852]
Enable storybook admin menu link for Android.
-
-
-
- Enable storybook admin menu link for Android - ole
</details>
[CX-1852]: https://artsyproduct.atlassian.net/browse/CX-1852
=> fix: Enable storybook admin menu link for Android

src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx, src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
This PR resolves [FX-3220]
When a user select artists
And after that select some other filter (for example, ways to buy)
All previously selected artists should be displayed
And previously selected artists should not be reset
https://user-images.githubusercontent.com/3513494/131350247-e86a50dc-2a99-49d3-b22a-efe423a77145.mp4
https://user-images.githubusercontent.com/3513494/131352093-2b7e08fd-62ce-4be5-975d-1433f31ece7b.mp4
- Previously selected artists are not reset - dimatretyak
-
-
-
</details>
[FX-3220]: https://artsyproduct.atlassian.net/browse/FX-3220
=> fix(FX-3220): Previously selected artists are not reset

src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
This PR resolves [FX-3147](https://artsyproduct.atlassian.net/browse/FX-3147)
As an admin with the saved search M2 feature flag enabled, If I apply filters on an an artist artworks grid, I see the count of filters applied next to the "sort & filter" button
https://user-images.githubusercontent.com/56556580/131666672-90000ac7-5509-4d2e-9837-af3fd2826dc8.mov
- Total count of applied filters near "Sort & Filter" label
</details>
=> feat(FX-3147): total number of applied filters

package.json, src/lib/Scenes/Inbox/Screens/Conversation.tsx, yarn.lock
We are seeing some issues with linking in CI due to a change in react-native-net-info, updating the library to fix. 
https://stackoverflow.com/questions/69021225/resource-linking-fails-on-lstar
- Update react-native-netinfo / fix linking issue - Brian
-
-
-
</details>
=> fix: update react-native netinfo to fix linking issue

docs/getting_started.md
Minor docs updates @starsirius and I came across when getting up and running with Eigen again. 
- Minor doc updates - brian
-
-
-
</details>
=> chore: update getting started #trivial

src/palette/PaletteFlag.tsx
This PR resolves [CX-1760]
Enables Palette V3 for all users by setting `allowV3` to `true`.
- Enable Palette V3 for all users - ole
-
-
-
</details>
[CX-1760]: https://artsyproduct.atlassian.net/browse/CX-1760
=> feat: Enable Palette V3 for all users

src/palette/elements/Dialog/Dialog.tsx
- Increase button offset in Dialog component - dimatretyak
-
-
-
</details>
=> fix: increase button offset in Dialog component

app.json
Updates version number to prepare for dev work. 
- Prep for dev work version 7.0.1 - Brian
-
-
-
</details>
=> chore: prepare for development, 7.0.1 #trivial

.circleci/config.yml
Trying an upgraded machine size for android builds to see if we can resolve our memory issues. 
https://app.circleci.com/pipelines/github/artsy/eigen/16570/workflows/97b2e6cc-32b1-4eab-870c-ba716229aaa0/jobs/46632 
- Use a larger resource class for circle android builds - brian
-
-
-
</details>
=> fix: circle android memory

src/__generated__/OrderHistoryPaginationQuery.graphql.ts, src/__generated__/OrderHistoryQuery.graphql.ts, src/__generated__/OrderHistoryRow_order.graphql.ts, src/__generated__/OrderHistoryTestsQuery.graphql.ts, src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx, src/lib/utils/__tests__/getTrackingUrl-tests.ts, src/lib/utils/getTrackingUrl.ts
This PR resolves [PX-4402]
This PR updates link for the Track Package button to support ARTA shipping tracking
- Update URL for Track Package button - kiryl-zubarau
</details>
[PX-4402]: https://artsyproduct.atlassian.net/browse/PX-4402
=> feat: use trackingUrl and trackingNumber to generate tracking url [PX-4402]

src/__generated__/OrderDetailsQuery.graphql.ts, src/__generated__/OrderDetailsTestsQuery.graphql.ts, src/__generated__/SummarySectionTestsQuery.graphql.ts, src/__generated__/SummarySection_section.graphql.ts, src/lib/Scenes/OrderHistory/OrderDetails/Components/SummarySection.tsx, src/lib/Scenes/OrderHistory/__tests__/SummarySection-tests.tsx
This PR resolves [PX-4452]
This PR updates the shipping label on the order details page to show selected shipping quote provided by ARTA.
- Update shipping label - kirill-zubarau
</details>
Arta shipping
Usual shipping
=> feat: update shipping label [PX-4452]

fastlane/Fastfile
- specifies test group in firebase app distribution to make sure builds are distributed correctly
- skip apk upload for google play, if both apk and aab are present upload will fail without this flag
- Firebase app distribution tweaks - Brian
-
-
-
</details>
=> fix: specify group in fastfile, skip apk upload #trivial

src/lib/Scenes/Search2/Search2.tsx
_Note: This updates a screen currently behind a feature flag_
Use the `href` attribute in Algolia objects to navigate to search results.
- update new improved search screen (behind feature flag) to use `href` to navigate to results - dblandin
-
-
</details>
=> feat: use href attribute in Algolia to navigate to result screen

src/palette/elements/Button/Button.tsx
This PR resolves [FX-3287]
- 
-
- Display full text in the button on android - dimatretyak
-
</details>
[FX-3287]: https://artsyproduct.atlassian.net/browse/FX-3287
=> fix(FX-3287): Display full text in button on android

src/lib/Components/ArtworkFilter/useArtworkFilters.ts, src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
[FX-3253]
**Before**
**After**
- Fixed filters options lists on Gallery page - anastasiapyzhik
-
-
-
</details>
[FX-3253]: https://artsyproduct.atlassian.net/browse/FX-3253
=> fix(FX-3253): Set aggregations on mount only on partner page

src/lib/Scenes/Search2/Search2.tsx
This PR resolves [FX-3267]
https://user-images.githubusercontent.com/3513494/132383975-f6401c90-3967-4da8-b153-65bcb14b4a9d.mp4
https://user-images.githubusercontent.com/3513494/132384004-7d7c6316-e84b-420a-894f-6bad4acc7bc9.mp4
- Support infinitely scrolling search results from Algolia - dimatretyak
-
-
-
</details>
[FX-3267]: https://artsyproduct.atlassian.net/browse/FX-3267
=> feat(FX-3267): Support infinitely scrolling search results from Algolia

Podfile.lock, src/lib/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx, src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx, src/lib/Scenes/Onboarding/OnboardingWelcome.tsx, src/lib/store/AuthModel.ts, src/lib/store/__tests__/AuthModel-tests.ts, src/palette/elements/Text/index.tsx
Addresses [CX-1903]
- Palette v3 issues with onboarding
- Onboarding copy
- Add missing copy that we agreed on here 
https://www.notion.so/artsy/Onboarding-Socail-auth-error-messages-9aeb58a81f8042a185d55effc27cb461
- Fix Following UI Issues:
**Before**
**After**
- Palette v3 onboarding issues - mounir
- Onboarding copy error message - mounir
-
-
-
</details>
[CX-1903]: https://artsyproduct.atlassian.net/browse/CX-1903
=> fix: onboarding fixes

src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
This PR resolves [CX-1904]
Makes "View more details" button on the viewing room screen bigger.
| Before | After | 
|---|---|
| ![simulator_screenshot_D680F9B2-2422-4BAD-AB84-4EEA095D4E27](https://user-images.githubusercontent.com/4691889/132697834-bc6bcddb-864e-451b-8432-bdc69201bfc3.png)| ![simulator_screenshot_5782E14E-4E8B-4CF5-B181-E54C43ED3071](https://user-images.githubusercontent.com/4691889/132697702-f774d0a4-6dd4-4e3d-8124-542a2cc99586.png) |
- Increase size of "View more details" button on viewing room screen - ole
-
-
-
</details>
[CX-1904]: https://artsyproduct.atlassian.net/browse/CX-1904
=> fix: Make viewing room more details button bigger

src/__generated__/EditSavedSearchAlertQuery.graphql.ts, src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
This PR resolves [FX-3293]
https://user-images.githubusercontent.com/3513494/132831436-12292b2c-65cb-4f23-91fe-c5dd54c4fe1b.mp4
- Show the colors filter on edit saved search page - dimatretyak
-
-
-
</details>
[FX-3293]: https://artsyproduct.atlassian.net/browse/FX-3293
=> fix(FX-3293): request color aggregation

src/lib/Scenes/Home/Home.tsx
Adjusts home screen placeholder size to the new spacing between modules that was introduced in https://github.com/artsy/eigen/pull/5417.
| | |
|---|---|
|![Simulator Screen Shot - iPhone 12 mini - 2021-09-10 at 11 44 29](https://user-images.githubusercontent.com/4691889/132835025-5a32b5b9-23c7-425d-8b61-0ba1b9eb263a.png)|![Simulator Screen Shot - iPhone 12 mini - 2021-09-10 at 11 44 30](https://user-images.githubusercontent.com/4691889/132835039-84c47400-fafd-470a-b666-d369d445a258.png) |
- Adjust home screen placeholder sizes - ole
-
-
-
</details>
=> fix: Adjust home screen placeholder size

src/palette/elements/Checkbox/Checkbox.tsx, src/palette/elements/Checkbox/CheckboxV2.stories.tsx
This PR addresses [CX-1910]
Centers the checkbox text to align the component with the [web version](https://palette.artsy.net/elements/checkbox/#gatsby-focus-wrapper) and to fix issues with font scaling (the checkbox wasn't aligned anymore if the font was too small or too large.
| | | |
|---|---|---|
|![Simulator Screen Shot - iPhone 8 - 2021-09-10 at 15 12 12](https://user-images.githubusercontent.com/4691889/132858782-b5dfb258-a8c4-4145-a1d8-91d43870dff8.png) | ![Simulator Screen Shot - iPhone 8 - 2021-09-10 at 15 12 23](https://user-images.githubusercontent.com/4691889/132858797-0d92d4a2-3d2e-4e64-b42d-af02356f81d7.png) | ![Simulator Screen Shot - iPhone 8 - 2021-09-10 at 15 12 34](https://user-images.githubusercontent.com/4691889/132858813-419dc293-b3 …
=> fix: Center checkbox V3 text

src/__generated__/OrderDetailsHeaderTestsQuery.graphql.ts, src/__generated__/OrderDetailsHeader_info.graphql.ts, src/__generated__/OrderDetailsQuery.graphql.ts, src/__generated__/OrderDetailsTestsQuery.graphql.ts, src/__generated__/OrderDetails_order.graphql.ts, src/__generated__/OrderHistoryPaginationQuery.graphql.ts, src/__generated__/OrderHistoryQuery.graphql.ts, src/__generated__/OrderHistoryRowTestsQuery.graphql.ts, src/__generated__/OrderHistoryRow_order.graphql.ts, src/__generated__/OrderHistoryTestsQuery.graphql.ts, src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsHeader.tsx, src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetailsHeader-tests.tsx, src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx, src/lib/Scenes/OrderHistory/__tests__/OrderHistoryRow-tests.tsx, src/lib/utils/__tests__/getOrderStatus-tests.ts, src/lib/utils/getOrderStatus.ts
This PR resolves [PX-4401]
- New shipment statuses in orders - Serge0n
-
-
-
</details>
**VIDEO:clapper: :**
https://user-images.githubusercontent.com/55637696/132683020-6331f49f-594c-4213-8f28-d48f0a42555a.mov
https://user-images.githubusercontent.com/55637696/132715630-f23c106b-9587-4cfb-9f04-2c6f35635944.mov
[PX-4401]: https://artsyproduct.atlassian.net/browse/PX-4401
=> feat: Collector can see new status about their shipment in the app [PX-4401]

src/lib/Scenes/Inbox/Screens/ConversationDetails.tsx
This PR resolves [CX-1901]
- Center text in the Inquiries FAQ button - mrsltun
-
-
-
</details>
[CX-1901]: https://artsyproduct.atlassian.net/browse/CX-1901
=> fix: Center text in Inquiries FAQ button in Conversation Info screen

src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx, src/palette/elements/Checkbox/Checkbox.tsx, src/palette/elements/Checkbox/CheckboxV2.tsx
Stops onboarding checkbox text from overflowing (V2 & V3).
| V2 | V3 |
|---|---|
|![Simulator Screen Shot - iPhone 8 - 2021-09-13 at 18 17 13](https://user-images.githubusercontent.com/4691889/133120209-102e1b1d-8e7e-4bc2-8b18-771c37c1747c.png)|![Simulator Screen Shot - iPhone 8 - 2021-09-13 at 18 17 09](https://user-images.githubusercontent.com/4691889/133120217-657aff02-4bca-4aa6-b4de-de3258cacfcc.png)|
- Fix onboarding checkbox text from overflowing - ole
-
-
-
</details>
=> fix: Stop onboarding checkboxes fromm overflowing

.circleci/config.yml, fastlane/Fastfile
Some more attempts to reduce gradle build memory usage. 
-
-
-
- More fastlane tweaks to try to resolve memory issues - brian
</details>
=> fix: remove unused resourceClass in circle, pass flags to android beta builds #trivial

src/lib/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx
This PR resolves [CX-1789]
Adds pull-to-refresh feature to Auction Results by Artists you Follow screen
- Add pull-to-refresh feature - mrsltun
-
-
- Add identifiers to error messages the file - mrsltun
</details>
[CX-1789]: https://artsyproduct.atlassian.net/browse/CX-1789
=> fix: add pull to refresh to Auction Results for artists you follow

android/app/src/main/AndroidManifest.xml, src/lib/navigation/__tests__/routes-tests.tsx, src/lib/navigation/routes.tsx
This PR resolves [CX-1932] and [FX-3279]
- New-style partner pages were [launched a while ago ](https://github.com/artsy/force/pull/7682)
- The url structure for these changed as well (to have more conventional URLs rather than relying on Force's old vanity profile url pattern)
- The routing logic in Eigen was not updated accordingly
This PR adds the missing routing logic and 
- handles all the currently supported partner URLs as inferred from [Force's own redirection logic](https://github.com/artsy/force/blob/master/src/desktop/apps/partner_redirect/partnerRedirectionMiddleware.ts)
- sends em all to the native Partner screen (there are no separate entry points / query renderers for partner artworks or partner artists, so the Partner screen will have to …
=> fix: routing for new-style partner urls

src/__generated__/HomeAboveTheFoldQuery.graphql.ts, src/__generated__/HomeBelowTheFoldQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/Home_homePageAbove.graphql.ts, src/__generated__/Home_homePageBelow.graphql.ts, src/lib/Scenes/Home/Home.tsx
This PR resolves [CX-1812]
- Home feed reordering - rajsam003
-
-
-
</details>
[CX-1812]: https://artsyproduct.atlassian.net/browse/CX-1812
=> feat: Home feed reordering

src/__generated__/Search2RefetchQuery.graphql.ts, src/__generated__/Search2_system.graphql.ts, src/lib/Scenes/Search2/Search2.tsx, src/lib/Scenes/Search2/__tests__/Search2-tests.tsx, src/lib/Scenes/Search2/components/SearchPlaceholder.tsx, src/lib/Scenes/Search2/containers/RefetchWhenApiKeyExpired.tsx, src/lib/Scenes/Search2/types.ts, src/lib/utils/__tests__/getRandomInt-tests.ts, src/lib/utils/getRandomInt.ts
This PR resolves [FX-3266]
https://user-images.githubusercontent.com/3513494/133488934-98c189e0-0ebf-4b00-bc9b-d2770a5bdbf5.mp4
-
-
-
- Gracefully respond when Algolia API key expires - dimatretyak
</details>
[FX-3266]: https://artsyproduct.atlassian.net/browse/FX-3266
=> feat(FX-3266): Gracefully respond when Algolia API key expires

src/lib/Scenes/Search2/Search2.tsx, src/lib/Scenes/Search2/SearchResults.tsx
[FX-3295]
**Before**
**After**
- Added no results state for Algolia queries
-
-
-
</details>
[FX-3295]: https://artsyproduct.atlassian.net/browse/FX-3295
=> feat(FX-3295): Added no results state when Algolia query comes back empty

src/__generated__/SearchArtworksContainerQuery.graphql.ts, src/__generated__/SearchArtworksGridQuery.graphql.ts, src/__generated__/SearchArtworksGrid_viewer.graphql.ts, src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx, src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx, src/lib/Components/ArtworkFilter/useArtworkFilters.ts, src/lib/Components/ArtworkGrids/FilterHeader2.tsx, src/lib/Scenes/Search2/Search2.tsx, src/lib/Scenes/Search2/SearchArtworksContainer.tsx, src/lib/Scenes/Search2/SearchArtworksGrid.tsx, src/lib/Scenes/Search2/containers/SearchArtworksContainer.tsx
This PR resolves [FX-3292]
⚠️ Note: This work is behind a feature flag
- add sort & filter on searchable artwork grid
- add skeleton component on artwork grid
|---|---|
|https://user-images.githubusercontent.com/21178754/133605704-85bbecb0-7de7-4d33-aa55-d097eda9a333.mp4|https://user-images.githubusercontent.com/21178754/133605861-218952c7-28e2-4a09-94f9-e716f8152fa0.mp4|
- add filters to searchable artwork grid - gkartalis
-
-
-
</details>
[FX-3292]: https://artsyproduct.atlassian.net/browse/FX-3292
=> feat(FX-3292): add filters to searchable artwork grid

src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx, src/lib/Scenes/Artist/__tests__/SearchCriteria-tests.tsx
=> fix: failed saved search tests

src/lib/utils/useAlgoliaClient.ts
This PR resolves [FX-3314]
PR includes a check that doesn't send a request to Algolia until the `indexName` is selected for which the search results should be displayed
https://user-images.githubusercontent.com/3513494/133645831-d3a6b4ec-5cd9-447d-9651-380fbfd5367c.mp4
https://user-images.githubusercontent.com/3513494/133645906-3229c503-8998-4c3c-8b85-7a30097d688b.mp4
-
-
-
- Don't send an empty request until `index_name` is selected - dimatretyak
</details>
[FX-3314]: https://artsyproduct.atlassian.net/browse/FX-3314
=> fix(FX-3314): Don't send an empty request until `index_name` is selected

app.json
Updates version number of the app to prep for the next release!
-
- 
-
- 7.0.2 dev prep! - Brian
</details>
=> chore: Prepare for development, 7.0.2 #trivial

src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
This PR resolves [FX-3304]
- adds some tests for improved search screen
-
-
-
- add tests for improved search screen - gkartalis
</details>
[FX-3304]: https://artsyproduct.atlassian.net/browse/FX-3304
=> spec: add more tests for improved search

src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx, src/lib/store/AuthModel.ts
This PR resolves [CX-1944]
Fix Copy issues on new onboarding
- Fix Copy issues on new onboarding - mounir
-
-
-
</details>
[CX-1944]: https://artsyproduct.atlassian.net/browse/CX-1944
=> fix: fix copy issues on new onboarding

src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
This PR resolves [CX-1950]
- Fix Cropped C in OnboardingWelcome screen on **iOS**
-
- Fix cropped C on onboarding welcome screen - mounir
-
-
</details>
[CX-1950]: https://artsyproduct.atlassian.net/browse/CX-1950
=> fix: Cropped C in OnboardingWelcome screen

src/lib/Scenes/Onboarding/ForgotPassword.tsx
This PR resolves [CX-1951]
- Fix font size on forgot password screen
- Fix font size on forgot password screen - mounir
-
-
-
</details>
[CX-1951]: https://artsyproduct.atlassian.net/browse/CX-1951
=> fix: font size on forgot password screen

src/__generated__/HomeAboveTheFoldQuery.graphql.ts, src/__generated__/HomeBelowTheFoldQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/Home_homePageAbove.graphql.ts, src/__generated__/Home_homePageBelow.graphql.ts, src/lib/Scenes/Home/Home.tsx
Reverts artsy/eigen#5447 until we decide how to release the upcoming home screen changes.
=> Revert "feat: Home feed reordering"

src/__generated__/HomeAboveTheFoldQuery.graphql.ts, src/__generated__/HomeBelowTheFoldQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/Home_homePageAbove.graphql.ts, src/__generated__/Home_homePageBelow.graphql.ts, src/lib/Scenes/Home/Home.tsx
This PR resolves [CX-1812]
Note: Reverts artsy/eigen#5447
- Home feed reordering - rajsam003
-
-
-
</details>
[CX-1812]: https://artsyproduct.atlassian.net/browse/CX-1812
=> feat: Home feed reordering (v2)

src/lib/Scenes/Search2/Search2.tsx
This PR resolves [FX-3317]
⚠️ **NOTE:**  This work is currently behind a feature flag
Change the threshold for we start querying when user types in search from >= 2 to >= 1
Started a slack thread for the **multi index** search that doesn't return results from gravity for now [here](https://artsy.slack.com/archives/C9SATFLUU/p1632131786288300)
- change improved search shouldStartQuering threshold - gkartalis
-
-
-
</details>
[FX-3317]: https://artsyproduct.atlassian.net/browse/FX-3317
=> feat: change improved search shouldStartQuering threshold

src/lib/Components/Bidding/Screens/BillingAddress.tsx, src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx
- fix: Uppercase input labels on billing address screen
- remove import
This PR resolves [CX-1911]
Uppercase input labels on billing address screen.
| Palette V2 | Palette V3 |
|---|---|
| ![Simulator Screen Shot - iPhone 8 - 2021-09-20 at 12 44 15](https://user-images.githubusercontent.com/4691889/133990483-470da070-990c-4237-9022-0ce135130109.png) | ![Simulator Screen Shot - iPhone 8 - 2021-09-20 at 12 44 35](https://user-images.githubusercontent.com/4691889/133990501-043bf58c-41e2-4ed2-90fa-23a22d9678dc.png)|
-
-
-
-
</details>
[CX-1911]: https://artsyproduct.atlassian.net/browse/CX-1911
=> fix: Uppercase input labels on billing address screen

Podfile.lock, android/build.gradle, emission/Pod/Classes/Core/AREventsModule.m, package.json, src/lib/NativeModules/Events.tsx, yarn.lock
This PR resolves [CX-1898]
- Implement in app review in ts
- Implement in-app review in ts - brian, mounir
-
- 
- set android min sdk version to 21 - brian, mounir
</details>
[CX-1898]: https://artsyproduct.atlassian.net/browse/CX-1898
=> feat: implement in app review in ts

src/lib/Scenes/Search2/Search2.tsx
Co-authored-by: Mounir Dhahri <soussouheros@gmail.com>
Addressing the point of @MounirDhahri that was commented [here](https://github.com/artsy/eigen/pull/5467#issuecomment-922734085)
Changing from debounce to throttle to provide a better user experience.
-
-
-
- change debounce to throttle when searching - gkartalis
</details>
=> chore: change debounce to throttle when searching

src/__generated__/OrderDetailsQuery.graphql.ts, src/__generated__/OrderDetailsTestsQuery.graphql.ts, src/__generated__/OrderDetails_order.graphql.ts, src/__generated__/ShipsToSectionTestsQuery.graphql.ts, src/__generated__/ShipsToSection_address.graphql.ts, src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/ShipsToSection.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/SoldBySection.tsx, src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetails-tests.tsx, src/lib/Scenes/OrderHistory/OrderDetails/__tests__/ShipsToSection-tests.tsx
This PR resolves [PX-4561]
This PR allows `ShipsToSection` to work with ARTA orders
- Order Details: ShipsToSection supports ARTA orders - Serge0n
-
-
-
</details>
**VIDEO:clapper: :**
https://user-images.githubusercontent.com/55637696/133578579-29ebfb28-21bb-438f-88d6-0b35ca1d2dea.mov
[PX-4561]: https://artsyproduct.atlassian.net/browse/PX-4561
=> fix: Order History: Order Details: "null" is displayed in "Ships to" section for ARTA orders [PX-4561]

android/app/build.gradle, android/app/src/main/java/net/artsy/app/MainApplication.java
Adds android adjust integration following docs here: https://segment.com/docs/connections/destinations/catalog/adjust/#android
-
-
- Adjust integration - brian, jon
-
</details>
https://artsyproduct.atlassian.net/browse/GRO-500
=> chore: add adjust android specific config - GRO-500

src/lib/Components/Input/InputTitle.tsx, src/lib/Components/TextArea.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/ArtistAutosuggest.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/Dimensions.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx, src/palette/elements/Select/Select.tsx
This PR resolves [CX-1942]
- Updates input titles to be capitalized and Text size XS on main form and additional details form
- Updates medium picker to be a radio button
</details>
</details>
- Noticed while I was working on this that the radio button text is not centered is this a known bug?
-
- Update titles + medium select in my collection forms - Brian
-
-
</details>
[CX-1942]: https://artsyproduct.atlassian.net/browse/CX-1942
=> chore: my collection design tweaks

src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx, src/lib/Scenes/OrderHistory/OrderDetails/Components/TrackOrderSection.tsx, src/palette/Theme.tsx, src/palette/elements/Button/Button.tsx, src/palette/elements/Text/Text.stories.tsx, src/palette/elements/Text/Text.tsx, src/palette/elements/Text/index.tsx
After @MounirDhahri saw that eigen and force use different names for the same prop, based on the discussion here https://artsy.slack.com/archives/C9XJKPY9W/p1632234545035900, I have renamed the prop from `size` to `variant`.
-
-
-
- rename `size` to `variant` in text v3 - pavlos
</details>
=> rename(text props): rename `size` to `variant` for text v3

src/lib/Components/Input/InputTitle.tsx, src/lib/Components/TextArea.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/ArtistAutosuggest.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/Dimensions.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx, src/palette/elements/Select/Select.tsx
#nochangelog
-
-
-
-
</details>
=> fix(naming): fix prop name

src/lib/Scenes/Favorites/Favorites.tsx
This PR resolves [CX-1885]
- Most of this work has been done as part of https://github.com/artsy/eigen/pull/5456
- Update to Follows Experience - kizito
-
-
-
</details>
[CX-1885]: https://artsyproduct.atlassian.net/browse/CX-1885
=> Feat(CX-1885): Update Follows Experience

src/lib/Scenes/Search2/SearchResults.tsx
This PR resolves [FX-3333]
|---|---|
| ![Android](https://user-images.githubusercontent.com/3513494/134529245-0f794cd7-5c38-4014-855a-ed792f1d6802.png) | ![iOS](https://user-images.githubusercontent.com/3513494/134528066-1f7e6ccf-5ac6-419b-9e9a-7b2b508f4e73.png) |
- Render Algolia result titles in one line - dimatretyak
-
-
-
</details>
[FX-3333]: https://artsyproduct.atlassian.net/browse/FX-3333
=> fix: render Algolia result titles in one line

src/lib/Scenes/Favorites/Favorites.tsx
Think one Text component with old props slipped through after we updated to use `variant`
-
-
-
- Fix palette type error - Brian
</details>
=> fix: fix palette type error #trivial

src/lib/Scenes/Onboarding/Onboarding.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/__tests__/Onboarding-tests.tsx, src/lib/store/config/features.ts
This PR resolves [this comment](https://github.com/artsy/eigen/pull/5494#pullrequestreview-761221925) and [this comment](https://github.com/artsy/eigen/pull/5494#issuecomment-925279714)  on #5494 
Hide network unavailable modal behind feature flag
**Note:** Please only merge after https://github.com/artsy/echo/pull/129
-
-
-
- Hide network unavailable modal behind feature flag - mounir
</details>
=> chore: hide network unavailable modal behind feature flag

package.json, src/lib/store/AuthModel.ts, yarn.lock
This PR resolves [CX-1663]
- Fix created_account missing analytics event
-
-
-
- Fix missing created_account analytics missing event - CX
</details>
[CX-1663]: https://artsyproduct.atlassian.net/browse/CX-1663
=> fix(CX-1663): created_account missing analytics event

src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
This PR resolves [PX-4402]
This PR fixes text splitting for action buttons on the order history page
- fixes text splitting for action buttons - kirill-zubarau
</details>
Before
Now
[PX-4402]: https://artsyproduct.atlassian.net/browse/PX-4402
=> fix(PX-4402): use small buttons

src/lib/Scenes/Search2/components/SearchPills.tsx
This PR resolves [FX-3336]
https://user-images.githubusercontent.com/3513494/134706614-52a67ba4-dc7b-477b-8835-36e8a2fa07cd.mp4
https://user-images.githubusercontent.com/3513494/134707580-b1bfadcd-c8e3-4ebd-933b-ea0c719fad0c.mp4
- Allow clicking on pills when the search input is focused - dimatretyak
-
-
-
</details>
[FX-3336]: https://artsyproduct.atlassian.net/browse/FX-3336
=> fix(FX-3336): Allow clicking on pills when the search input is focused

src/lib/Scenes/Search2/SearchResults.tsx, src/lib/Scenes/Search2/components/AlgoliaSearchPlaceholder.tsx
This PR resolves [FX-3332]
* When I as a user
* first open the app
* go to improved search
* and type in a search term 
* and then select any of algolia pills (every pill except artwork)
* I want to be able to see a skeleton component of the list items instead of the empty screen
https://user-images.githubusercontent.com/3513494/134557131-6222c830-80e7-4507-b21d-139153697415.mp4
Uploading Android.mp4…
- Render placeholder to Algolia results when loading – dimatretyak
-
-
-
</details>
[FX-3332]: https://artsyproduct.atlassian.net/browse/FX-3332
=> feat(FX-3332): add placeholder to Algolia results when loading

src/lib/Components/States/ZeroState.tsx, src/lib/Scenes/MyCollection/MyCollection.tsx
This PR resolves [CX-1976]
- This PR fixes the broken padding My Collection. 
**Before**
**After**
https://user-images.githubusercontent.com/11945712/134897850-167b1807-fcd0-4020-b3fa-8ef55974f56a.mov
- Fix padding on zero state - mounir
-
-
-
</details>
[CX-1976]: https://artsyproduct.atlassian.net/browse/CX-1976
=> fix(CX-1976): Fix broken padding in my collection

fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/android/en-US/title.txt
We agreed to update the tagline to mitigate some confusion customers were having over  not being able to sell personal works. Slack thread: https://artsy.slack.com/archives/CDU4AH60Z/p1630509806001600
-
-
- Update tagline Sell -> Resell - Brian
-
</details>
=> chore: update sell tagline #trivial

src/lib/Components/StickyTabPage/SitckyTabPageContext.tsx, src/lib/Components/StickyTabPage/StickyTabPage.tsx, src/lib/Components/StickyTabPage/StickyTabPageTabBar.tsx, src/lib/Scenes/MyCollection/MyCollection.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkInsights-tests.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/__tests__/MyCollectionArtwork-tests.tsx, src/lib/Scenes/MyCollection/__tests__/MyCollection-tests.tsx, src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx, src/palette/elements/Tabs/NavigationalTabs.tsx, src/palette/elements/Tabs/Tab.tsx, src/palette/elements/Tabs/Tabs.stories.tsx, src/palette/elements/Tabs/index.tsx
This PR resolves [CX-1983]
This PR resolves [CX-1982]
This PR resolves [CX-1981]
-
- My Collection Copy Updates - mounir
- Remove submit button from my collection - mounir
-
- Support superscript in StickyTabPage - mounir
</details>
[CX-1983]: https://artsyproduct.atlassian.net/browse/CX-1983
[CX-1982]: https://artsyproduct.atlassian.net/browse/CX-1982
[CX-1981]: https://artsyproduct.atlassian.net/browse/CX-1981
=> fix: My collection bug fixes

src/lib/Scenes/MyCollection/MyCollection.tsx, src/lib/Scenes/MyProfile/__tests__/MyProfile-tests.tsx, src/lib/store/config/features.ts
This PR resolves [CX-1980]
- Add and enable AREnableMyCollectionIOS feature flag
**Note:**
Please merge this https://github.com/artsy/echo/pull/131 before 
-
- Enable My collection feature flag
-
-
</details>
[CX-1980]: https://artsyproduct.atlassian.net/browse/CX-1980
=> chore: add and enable AREnableMyCollectionIOS feature flag

src/lib/Scenes/MyProfile/__tests__/MyProfile-tests.tsx, src/lib/Scenes/Search2/SearchResults.tsx
This PR resolves the broken tests due to https://github.com/artsy/eigen/pull/5527
- I broke the tests with my previous PR #5527 and I was impatient and merged the PR before it passed all the tests. (of course this didn't go well). 
#nochangelog
-
-
-
-
</details>
=> fix: broken tests on master

src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
This PR resolves https://artsy.slack.com/archives/C01B2P6LJUU/p1632758937021000?thread_ts=1632746772.008900&cid=C01B2P6LJUU
- Remove superscript from my collection
-
- Remove superscript from my collection - mounir
-
-
</details>
=> chore: remove superscript from my collection

src/lib/Scenes/Search2/SearchResults.tsx
Additional fix for #5531
#nochangelog
=> chore: update check for render empty message

src/lib/Components/ArtsyReactWebView.tsx
This PR resolves [CX-1978]
This was a bug in a previous PR that unintentionally passed an empty function to onRightButtonPress instead of `undefined`. This checks for presence of either of right button actions and if neither are present returns undefined.
- Hide right arrow where not needed in webviews - Brian
-
-
-
</details>
[CX-1978]: https://artsyproduct.atlassian.net/browse/CX-1978
=> fix: hide right arrow in webviews where not needed 

src/lib/Scenes/Home/Components/AuctionResultsRail.tsx, src/lib/Scenes/Home/Components/__tests__/AuctionResultsRail-tests.tsx, src/lib/Scenes/Home/Home.tsx
This PR resolves the error on pull to refresh in homepage, [more details 🔒](https://artsy.slack.com/archives/C02BAQ5K7/p1632309630214300)
This PR fixes the error that shows up when refreshing the homepage
-
-
-
- Fix error on pull to refresh in homepage - mrsltun
</details>
=> fix: pull to refresh error in homepage

src/lib/Scenes/Search2/Search2.tsx
This PR resolves [FX-3382]
By changing when it should start querying for results as mentioned [here](https://artsyproduct.atlassian.net/browse/FX-3317?focusedCommentId=41769) the problem goes away. 
| Android  | iOS |
|---|---|
|https://user-images.githubusercontent.com/21178754/135063917-6da75415-b412-4b98-8ef2-f8c280ea5a61.mov|https://user-images.githubusercontent.com/21178754/135063512-e3a4fa7a-5070-4a11-96ff-c654e427fc23.mov|
- adjust shouldStartQuerying improved search to 2 chars - gkartalis
-
-
-
</details>
[FX-3382]: https://artsyproduct.atlassian.net/browse/FX-3382
=> chore(FX-3382): adjust when shouldStartQuerying to 2 chars

fastlane/metadata/android/en-US/changelogs/default.txt, fastlane/metadata/en-US/release_notes.txt
Co-authored-by: Joel Rosenblatt <7117670+jo-rs@users.noreply.github.com>
This PR prepares for submission of 7.0.2
#nochangelog
-
-
-
-
</details>
=> chore: prepare 7.0.2 for submission

src/lib/Scenes/Artwork/Components/__tests__/ContextCard-tests.tsx, src/lib/Scenes/Artwork/Components/__tests__/PartnerCard-tests.tsx, src/lib/Scenes/Onboarding/OnboardingWelcome.tsx, src/palette/elements/Button/Button.stories.tsx, src/palette/elements/Button/Button.tsx, src/palette/elements/Text/Text.stories.tsx
It was a forgotten prop that was not renamed. I also added some extra stories since I was using them to test.
Before
After
- Fixed a button text layout - pavlos
-
-
-
</details>
=> fix(small buttons): fix a text layout problem on small buttons

app.json
Prepare for 7.0.3
#nochangelog
=> chore: Preparing for development, version 7.0.3.

src/lib/Scenes/Search/Search.tsx
A previous rebase broke the functionality of the Search.tsx screen where the AutosuggestResult component doesn't display the result type. This pr fixes this
Note: This is the **existing** Search screen in the app NOT the improved search that is hidden behind a feature flag
|---|---|
|![Simulator Screen Shot - iPhone 8 - 2021-09-30 at 09 18 52](https://user-images.githubusercontent.com/21178754/135406101-f3e7dab0-119f-4ce2-8bd4-8cbb264bc926.png)|![simulator_screenshot_4F095B62-3FD8-47C2-9927-DDB12225A6B6](https://user-images.githubusercontent.com/21178754/135406145-48d962ea-6753-49a6-a5bc-0705f61c09de.png)|
- bugfix show result type on search results - gkartalis
-
-
- …
=> fix: showResultType on autosuggestResults that broke after rebase

src/lib/Scenes/Search2/Search2.tsx, src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
This PR resolves [FX-3414]
Changes for PR #5567
https://user-images.githubusercontent.com/3513494/135617326-2395b824-635e-426b-9d67-4c6cdcdae0d9.mp4
https://user-images.githubusercontent.com/3513494/135618948-735ff4e2-1147-4525-b415-f9d864b21b82.mp4
- Update behaviour for search button – dimatretyak
-
-
-
</details>
[FX-3414]: https://artsyproduct.atlassian.net/browse/FX-3414
=> fix(FX-3414): update behaviour for search button

src/lib/Scenes/Search2/Search2.tsx
This PR resolves [FX-3408]
* Type `abc` into search bar
* Tap `Artist` pill
* Click on search bar again (the keyboard **should be** displayed)
* Select some artist
* Tap `Artworks` pill
* All pills have disappeared
https://user-images.githubusercontent.com/3513494/135660965-bca78824-956d-4971-a842-a03fc67ff37b.mp4
https://user-images.githubusercontent.com/3513494/135661004-edeb65d4-0321-4856-b2da-b5c8897ff0ec.mp4
-
-
- Fix search pills disappearing - dimatretyak
-
</details>
[FX-3408]: https://artsyproduct.atlassian.net/browse/FX-3408
=> fix(FX-3408): set collapsable to false for parent container

src/lib/Scenes/Search2/Search2.tsx, src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
This PR resolves [FX-3414]
-
-
-
- Update tests for search pills - anastasiapyzhik
</details>
[FX-3414]: https://artsyproduct.atlassian.net/browse/FX-3414
=> chore(FX-3414): Update tests for pills

src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
This PR resolves [CX-894]
Fixes large images going offscreen while preserving aspect ratio
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;
<p align="center"><b>iPhone (iOS)</b></p>
<p align="center"><b><i>image landscape           |            image portrait</i></b></p>
<p align="center">
&nbsp; &nbsp; &nbsp; &nbsp;
</p>
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;
<p align="center"><b>Tablet in portrait mode</b></p>
<p align="center"><b><i>image portrait           |            image landscape</i></b></p>
<p align="center">
&nbsp; &nbsp; &nbsp; &nbsp;
</p>
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; …
=> Enhancement(CX-894): Fix Image view goes off screen / too tall in My Collection Artworks

src/lib/store/__tests__/GlobalStoreModel-tests.ts, src/lib/store/__tests__/migration-tests.ts
I had the random thought, "when we install the app first time, do we have the latest migration version directly, or do we start from 1 and on do migrations". I guessed that we start from latest, but wanted to make sure.
And that's what we do. We set the version to the latest migration version, on first install.
On my way to quickly investigate this, I found a couple of places where the tests names could be improved, so I did.
-
-
-
- better test names - pavlos
</details>
=> refactor(test names): small rework of test names

src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
Addresses [CX-2024]
Adjust Viewing Rooms screen header by using `PageWithSimpleHeader` (the header border overlaps the back button when font scaling is active). 
| --- | --- |
| ![Simulator Screen Shot - iPhone 8 - 2021-10-05 at 12 07 33](https://user-images.githubusercontent.com/4691889/136003502-8fa4a78e-b142-4695-8341-4c672b63b1fd.png) | ![Simulator Screen Shot - iPhone 8 - 2021-10-05 at 12 02 18](https://user-images.githubusercontent.com/4691889/136003515-5922ca80-cbde-40ee-b721-52230be3a698.png) |
- Fix Viewing Rooms screen header height - ole
-
-
-
</details>
[CX-2024]: https://artsyproduct.atlassian.net/browse/CX-2024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> fix: Adjust Viewing Rooms screen header

src/lib/Components/PhoneInput/PhoneInput.tsx, src/lib/Scenes/Consignments/Components/Toggle.tsx, src/palette/elements/Input/Input.stories.tsx, src/palette/elements/Input/Input.tsx
This PR resolves https://artsy.slack.com/archives/C01B2P6LJUU/p1633433974209000
I made the Input inner text use less `absolute` positioning, and made sure the PhoneInput is also doing the same.
I confirmed in the storybook and also in the screens, with small and big and regular ios font sizes.
-
- Input text's baseline is centered better, when ios font size changes - pavlos
-
-
</details>
=> fix(input): fix baseline

Podfile.lock, package.json, yarn.lock
This PR resolves the following on Sentry: 
- Update Sentry to the latest to support better error grouping
-
-
-
- Update Sentry to 3.1.1 - mounir
</details>
=> chore: update sentry to latest

.github/dependabot.yml
This PR resolves [PLATFORM-3580]
This enables security alerts for Github-native dependabot and puts it in line with the 🔒 [security alert playbook](https://www.notion.so/artsy/Security-alerts-and-updates-for-repositories-dependabot-114369231d854ce89b104ea0da5d0c65).
Step 1 (already complete): Enable "Dependabot security updates" under the repo's Security & analysis settings.
Step 2 (this PR): Commit a minimal `.github/dependabot.yml` specifying open-pull-requests-limit: 0 (a hack to enable only security updates, which can't otherwise be configured). Point person has been made the assignee with associated team as reviewers.
> NOTE: I did not see any private dependencies in this project. If I overlooked, please let me know. 🙇
> NOTE2: swift …
=> feat: dependabot configuration for security updates

src/lib/AndroidApp.tsx, src/lib/AppRegistry.tsx, src/lib/Scenes/Home/Home.tsx, src/lib/store/config/features.ts
The type of this PR is:Feature
This PR resolves [CX-1973]
This PR includes the A/B testing feature for `New works for you` rails Vs `New works by Artist you follow` rails. 
-
-
-
- A/B testing for New works for you vs New works by followed Artist - sam
</details>
[CX-1973]: https://artsyproduct.atlassian.net/browse/CX-1973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: implement A/B testing with New works rails

android/app/build.gradle, android/build.gradle
This PR resolves [CX-2126]
- Update Android SDK to 30
-
-
-
- Update android target SDK to 30 - mounir
</details>
[CX-2126]: https://artsyproduct.atlassian.net/browse/CX-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Update Android Target SDK to 30

src/lib/Components/ArtworkFilter/Filters/AuctionHouseOptions.tests.tsx, src/lib/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx, src/lib/Components/ArtworkFilter/Filters/CategoriesOptions.tests.tsx, src/lib/Components/ArtworkFilter/Filters/CategoriesOptions.tsx, src/lib/Components/ArtworkFilter/Filters/SizesOptions.tests.tsx, src/lib/Components/ArtworkFilter/Filters/SizesOptions.tsx
This PR resolves [CX-1937]
This PR changes the `MultiSelectOptions` in some filters that were using a deprecated version to match the Figma specs for filters with multi-select features.
Since I had to update the tests, I changed to use RTL and not the deprecated function anymore.
https://user-images.githubusercontent.com/15792853/139417371-8afb64c7-2064-4bfc-a39d-1730432df366.mov
- change filters to use the correct MultiOptions component - araujobarret
-
-
-
</details>
[CX-1937]: https://artsyproduct.atlassian.net/browse/CX-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(CX-1937): Change multi select filters to the right component

src/lib/Scenes/Search2/Search2.tests.tsx, src/lib/Scenes/Search2/Search2.tsx, src/lib/store/config/features.ts, src/lib/utils/useAlgoliaIndices.ts
This PR resolves [FX-3503]
Currently if search pill doesn't contain results we show _no results_ state [like this](https://github.com/artsy/eigen/pull/5654)
This PR implements checking all algolia indices when typing term and only displaying those having results
https://user-images.githubusercontent.com/44819355/139078732-61840bfe-9be0-4a3d-a204-3a315d5aabbb.mp4
https://user-images.githubusercontent.com/44819355/139080135-ebbc60c5-6688-4d18-a91d-4c3b5ad36238.mp4
To see this change you should have both `AREnableImprovedSearch` and `AREnableImprovedSearchPills` feature flags enabled
- hide search pills with no results - anastasiapyzhik
</details>
[FX-3503]: …
=> feat(FX-3503): Hide search pills with no results

src/__generated__/SearchArtworksGridTestsQuery.graphql.ts, src/lib/Scenes/Search2/Search2.tests.tsx, src/lib/Scenes/Search2/Search2.tsx, src/lib/Scenes/Search2/SearchArtworksGrid.tests.tsx, src/lib/Scenes/Search2/SearchArtworksGrid.tsx
This PR resolves [FX-3512]
The `openFilterModal` and `closeFilterModal` events are not standard, we should re-use those we see on the artist screen
https://user-images.githubusercontent.com/44819355/139644270-c8372799-dd4f-4826-8174-dc758d4030c8.mp4
We fire a `closeFilterModal` event after selecting filters, we should not
https://user-images.githubusercontent.com/44819355/139644562-86e070e8-9645-4e42-98db-5f30ffab248c.mp4
selected result from search screen event on the artist tab and on the auction tab both fire with a `selected_object_tab` property and they should not
https://user-images.githubusercontent.com/44819355/139644839-f78f6d32-5e37-44e2-8a5e-ede9f0152b3f.mp4
- Fix search results analytics tracking …
=> fix(FX-3512): Search results analytics tracking issues

src/lib/Scenes/Search2/SearchArtworksGrid.tests.tsx
-
-
-
- Fix Failing Test - kizito
</details>
=> Bugfix: fix failing test

src/palette/elements/Input/Input.tsx
This PR removes the margin-right of the limit value of the Input component. 
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/140346832-777958fb-afb4-4089-b859-4b1fc8e1fb44.png)|![image](https://user-images.githubusercontent.com/17421923/140346004-97ea50d0-54a4-404d-9e22-7d82b9d99d18.png)|
- Removed margin right from the limit of Input components
-
-
-
</details>
=> fix: Remove margin right from limit of Input components

src/lib/Scenes/Search2/SearchArtworksGrid.tsx
FX-3523
FX-3523
ⓘ 'User-facing' changes will be published as release notes. 
-
-
-
</details>
=> fix(FX-3523): Rename modal title

src/lib/Scenes/Search2/components/SearchPlaceholder.tsx
This PR resolves [FX-3538]
This pr aligns the skeleton shown when users press the first time the search button in the bottom navigation bar. It was slightly off.
slack thread where this was decided [here](https://artsy.slack.com/archives/C9SATFLUU/p1636022197491400)
|---|---|
|![simulator_screenshot_CB50B4A3-B837-4251-AD25-47D6192FAA24](https://user-images.githubusercontent.com/21178754/140381061-b2edbf46-1333-45c1-aa93-0443ed2ddab4.png)|![Simulator Screen Shot - iPhone 8 - 2021-11-04 at 17 36 37](https://user-images.githubusercontent.com/21178754/140380954-c8d95d70-1939-49f0-b217-90391aeac24c.png)| 
- skeleton of search alignment - gkartalis
-
-
-
</details>
[FX-3538]: …
=> fix: search2 skeleton alignment

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
This PR resolves [NX-3003](https://artsyproduct.atlassian.net/browse/NX-3003)
Adds padding to iOS only to fix icon and text overlap on inquiry screen.
- 
- Fixes First inquiry checkboxes displaying incorrectly on iOS
-
-
</details>
=> fix: fixes overlapping icon and text on inquiry msg

src/__generated__/AuctionResultQuery.graphql.ts, src/lib/Scenes/AuctionResult/AuctionResult.tsx
This PR resolves [CX-2148]
- Hide description from auction results
- Hide description from auction results
-
-
-
</details>
[CX-2148]: https://artsyproduct.atlassian.net/browse/CX-2148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(CX-2148): hide description from auction results

android/app/build.gradle
This PR resolves [CX-2153]
This PR resolves [CX-2154]
A crash was occurring on pages showing maps on Android.
The issue was using an old telemetry dependency that reads phone state without permission: 
https://github.com/react-native-mapbox-gl/maps/issues/1286
Fix is to update the telemetry dependency in our own build.gradle
-
-
- Fix a crash on pages showing maps - Brian
-
</details>
[CX-2153]: https://artsyproduct.atlassian.net/browse/CX-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2154]: https://artsyproduct.atlassian.net/browse/CX-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update telemetry dep to fix mapbox rn crash

src/lib/store/config/features.ts
- Switch on AREnableMyCollectionAndroid
- Switch on AREnableMyCollectionOrderImport
- Add echoflag key for AREnableSplitIOABTesting
-
-
-
- Switch on order import and my collection flag for android - kizito
</details>
=> Feat: Switch on order import and my collection flag for android

src/lib/Scenes/Home/Components/ArtworkRail.tsx, src/lib/Scenes/Home/Home.tests.tsx, src/lib/Scenes/Home/Home.tsx, src/lib/store/config/features.ts
- Enable new works for you rail
**Note:** this is required to test the A/B test experiment
- Enable new works for you rail - mounir
-
-
- 
</details>
=> chore: enable new works for you rail

docs/getting_started.md
This PR updates the documentation
-
-
-
-
</details>
=> docs: Update getting_started.md

src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx, src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx
Co-authored by: Kizito, Brian, Sam
Sorry something went wrong with Github co-authors
This PR resolves the following bug
https://user-images.githubusercontent.com/11945712/141338752-93023c04-cdef-4106-b9c8-51e9d9a0f044.MP4
- Fix issue with editing user profile image - brian, kizito, mounir, sam
-
-
-
</details>
=> fix: issue with image profile upload

src/lib/Scenes/Consignments/Screens/ConfirmContactInfo.tsx
Phone inputs with titles layout was broken. We have a title in consignments flow. Opting for quick fix to use flex on the component because this is a launch blocker, but we probably want to fix the PhoneInput component so you don't have to.
</details>
</details>
-
- Fix broken phone input layout in consignments flow - Brian
-
-
</details>
=> fix: add flex to fix phone input layout #trivial

src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx, src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
This PR resolves [FX-3577]
* Remove the below line of copy from the create alert screen: "Receive alerts as Push Notifications directly to your device."
* Hide the line of copy when `AREnableSavedSearchToggles` feature flag is enabled
|AREnableSavedSearchToggles is disabled|AREnableSavedSearchToggles is enabled|
|---|---|
|![Simulator Screen Shot - iPhone 8 - 2021-11-11 at 21 29 44](https://user-images.githubusercontent.com/3513494/141351134-2157f5e8-85a7-4e55-9ac5-249e0a9f3105.png)|![Simulator Screen Shot - iPhone 8 - 2021-11-11 at 21 26 21](https://user-images.githubusercontent.com/3513494/141351156-583ad14a-9dd0-4b70-8bf5-412dfe1eeb04.png)|
https://user-images.githubusercontent.com/3513494/141444880-8656d4da-7a91-4df7-a03a-40645de8fe7b.mp4 …
=> feat(FX-3577): Remove push notifs copy from create alert screen

src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tests.tsx, src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx, src/lib/store/AuthModel.ts, src/lib/tests/flushPromiseQueue.ts
There was an old PR that tried to fix this. I took it and made it work for login too.
-
-
-
-
</details>
=> fix(push notifs): asking for permission with new onboarding

src/lib/store/AuthModel.ts
Tested the latest push prompt code in TestFlight and all looks good except for some existing users that had not been prompted I was not getting prompted to enable push, checked and onboarding was undefined for them. Added a check for this case.
-
- one last push fix - Brian
-
-
</details>
=> fix: prompt for push for users with no onboarding state #trivial

src/lib/Scenes/BottomTabs/BottomTabsButton.tsx
When a user was using a screen reader when they were on top of the bottomNavigation buttons they heared: "description for element unavailable"
Changed that to be `${tab name} bottom tab`
- added accessibility labels to bottom navigation bar - gkartalis
-
-
-
</details>
=> feat: adding a11y labels to bottomTabs

src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/BuyNowButton_artwork.graphql.ts, src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts, src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts, src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx, src/lib/utils/track/schema.ts
This PR is a follow-up for [CX-2076]
just adding some types that were missing, and adding the slug that the type caught missing.
-
-
-
- types for analytics - pavlos
</details>
[CX-2076]: https://artsyproduct.atlassian.net/browse/CX-2076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(analytics): add types and missing slug

src/lib/Scenes/Consignments/Submission/consignmentSetupToSubmission.ts
This PR resolves [SWA-43]
-
-
-
- change editionNumber in consignmentSetupToMutationInput to editionSizeFormatted(also change type from int to string)
</details>
[SWA-43]: https://artsyproduct.atlassian.net/browse/SWA-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SWA-43] Migrate the edition size field in Convection to a string

app.json
-
-
-
- version 7.1.2
</details>
=> Prep for v7.1.2

HACKS.md, patches/@sentry+react-native+3.1.1.patch, src/lib/ErrorReporting.ts
This PR resolves https://artsy.slack.com/archives/C0HP61PUJ/p1637249538105400
- Disable outOfMemoryTracking issues on iOS
**Note:** Although we did not have any memory issues over the past few months, I think we should keep this flag turned on just in case. For now, this is just returning falsy events and non-actionable alerts  (see https://sentry.io/organizations/artsynet/alerts/53/ )
-
-
-
- Disable out of memory tracking issues on iOS - mounir
</details>
=> fix: disable outOfMemoryTracking issues on iOS

src/lib/Scenes/Home/Home.tests.tsx
=> fix: failed test

fastlane/Fastfile
Adds the widget to our code signing syncing in fastlane, also had to create a new identifier in dev portal.
This file is due for some cleanup 😬 
-
-
-
- Fix widget code signing for betas
</details>
=> fix: sync widget code signing in beta builds

.github/workflows/beta-android.yml, .github/workflows/beta-ios-manual.yml, .github/workflows/beta-ios.yml, .github/workflows/promote-android.yml, .github/workflows/promote-ios.yml, .github/workflows/trigger-ci-after-ready-to-review.yml
=> feature(CI/DX): Allow manual trigger of an ios beta build on github

app.json
This PR prepares for 7.1.3
-
-
-
- Prepare for 7.1.3 - mounir
</details>
=> chore: Prepares for 7.1.3

src/lib/store/config/features.ts
This PR resolves [FX-36213]
- marks AREnableSavedSearchToggles feature flag as ready for release
Wait for https://github.com/artsy/echo/pull/177 to get deployed before merging
-
-
-
- marked AREnableSavedSearchToggles ready for release - gkartalis
</details>
=> other: marked AREnableSavedSearchToggles ready for release

src/lib/store/config/features.ts
This PR resolves [CX-2187]
🔴   Make sure https://github.com/artsy/echo/pull/173 is deployed before merging this PR.
Enable comparable works for auction results.
- Enable comparable works section for auction results - ole
-
-
-
</details>
[CX-2187]: https://artsyproduct.atlassian.net/browse/CX-2187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Enable comparable works for auction results

src/lib/Components/HeaderArtworksFilter/HeaderArtworksFilter.tsx, src/lib/Scenes/Show/Show.tsx
This PR resolves [CX-2194]
Reduce the size of fairs and shows header to `50px`.
| Before | After | 
| --- | --- | 
| ![Simulator Screen Shot - iPhone 8 - 2021-12-01 at 10 07 07](https://user-images.githubusercontent.com/4691889/144211409-727680e0-1366-4f2d-8097-177536d6b22a.png) | ![Simulator Screen Shot - iPhone 8 - 2021-12-01 at 10 36 10](https://user-images.githubusercontent.com/4691889/144211417-8d8a16bc-3dd5-4763-8c25-c18d75b9e3ef.png) |
| ![Simulator Screen Shot - iPhone 8 - 2021-12-01 at 10 07 35](https://user-images.githubusercontent.com/4691889/144211422-31bbe59b-ac28-42bc-a4ee-7edf56474db7.png) | ![Simulator Screen Shot - iPhone 8 - 2021-12-01 at 10 43 39](https://user-images.githubusercontent.com/4691889/144211451-5e762ad9-5c94-465c-a0f0-134cc6 …
=> fix: Reduce size of fairs and shows header

src/lib/Components/ArtsyReactWebView.tests.tsx, src/lib/Components/ArtsyReactWebView.tsx, src/lib/store/config/features.ts
Oftentimes I am not sure if a view is a webview or a native one. I thought I'll add a small indicator, so that it's always obvious what it is. It's just a floating red text that says "webview".
-
-
-
- webview indicator - pavlos
</details>
=> feature(DX): showing an indicator for webviews

src/lib/Scenes/Search/SearchArtworksGrid.tests.tsx
=> fix: failed tests

src/lib/Scenes/Partner/Components/PartnerShows.tests.tsx
When trying to run old tests locally, they failed. I refactor it to use RNTL and now everything is ok
#nochangelog
=> fix: tests for PartnerShows

src/__generated__/ArtistCard_artist.graphql.ts, src/__generated__/ArtistRailFollowMutation.graphql.ts, src/__generated__/ArtistRailNewSuggestionQuery.graphql.ts, src/__generated__/ArtistRail_rail.graphql.ts, src/__generated__/HomeAboveTheFoldQuery.graphql.ts, src/__generated__/HomeBelowTheFoldQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/Home_homePageAbove.graphql.ts, src/__generated__/Home_meAbove.graphql.ts, src/__generated__/RecommendedArtistsRailFollowMutation.graphql.ts, src/__generated__/RecommendedArtistsRailQuery.graphql.ts, src/__generated__/RecommendedArtistsRail_me.graphql.ts, src/lib/Components/Home/ArtistRails/ArtistCard.tsx, src/lib/Components/Home/ArtistRails/ArtistRail.tsx, src/lib/Components/Home/ArtistRails/RecommendedArtistsRail.tests.tsx, src/lib/Components/Home/ArtistRails/RecommendedArtistsRail.tsx, src/lib/Scenes/Home/Home.tsx, src/lib/store/config/features.ts, src/lib/utils/experiments.ts
This PR resolves [CX-2121]
- Implements new artist rail design (for "Popular Artists" and "Recommended Artists")
- Adds new "Recommended Artists" home rail (behind feature flag).
- Adds an A/B test to test the old artist recommendations against the new one (behind feature flag).
| Popular Artists | Artist Recommendations |
| --- | --- |
| ![Simulator Screen Shot - iPhone 8 - 2021-12-01 at 13 03 34](https://user-images.githubusercontent.com/4691889/144231363-ab46907f-0168-46b6-a779-cedb86a4ed1d.png) | ![Simulator Screen Shot - iPhone 8 - 2021-12-01 at 12 59 59](https://user-images.githubusercontent.com/4691889/144231386-51a7f4de-b7eb-463b-99c7-b9bc7f47c5ea.png) |
**Artist Card Tap:**
```
{
"context_screen": "Home",
"context_screen_owner_type": "home", …
```
=> feat: Add new artist recommendations home rail

docs/navigation.md, src/palette/icons.stories.tsx, src/storybook/storyLoader.js
Documentation 
`Add Icons to Storybook `
Add Icons to Storybook 
-
</details>
=> docs: Add Icons to Storybook

.circleci/config.yml
`consider-job` flag is deprecated. We can use `block-workflow` instead ([link to documentation](https://circleci.com/developer/orbs/orb/eddiewebb/queue))
-
-
-
- Remove legacy `consider-job` flag in CircleCI config - dimatretyak
</details>
=> fix: remove legacy flag in CircleCI config

src/lib/Components/ArtworkFilter/ArtworkFilterNavigator.tsx, src/lib/Components/FancyModal/FancyModal.tsx, src/lib/Components/FancyModal/FancyModalCard.tsx, src/lib/Components/FancyModal/FancyModalContext.tsx
* These changes add the ability to specify the type of animation appearance for `FancyModal` - either from the bottom or on the right
* More context you can find in [Slack thread](https://artsy.slack.com/archives/C02BAQ5K7/p1638978523028600)
https://user-images.githubusercontent.com/3513494/145249837-df003c19-dc21-48a8-acb0-474fbc473f04.mp4
https://user-images.githubusercontent.com/3513494/145249912-6221d25f-57e5-4722-85d1-0e3fdc9d9970.mp4
- Add new animation for FancyModal - dimatretyak
-
-
-
</details>
=> feat: add new animation for FancyModal

.circleci/config.yml, .github/workflows/beta-android.yml, .github/workflows/beta-ios-manual.yml, .github/workflows/beta-ios.yml, .github/workflows/promote-android.yml, .github/workflows/promote-ios.yml, Artsy/View_Controllers/Admin/Networking/ARAdminNetworkModel.h, Artsy/View_Controllers/Admin/Networking/ARAdminNetworkModel.m, HACKS.md, README.md, docs/deploy_a_hotfix.md, docs/deploy_to_app_store.md, docs/deploy_to_play_store.md, docs/getting_started.md, docs/preferred_practices.md, docs/pull_request_template.md, docs/release_candidate_code_freeze.md, fastlane/Fastfile, scripts/changelog/commitChangelog.js, scripts/generate-cities-objc.js, scripts/strictness-migration.js, src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tsx, src/lib/relay/middlewares/metaphysicsMiddleware.ts
This PR is a follow-up from https://github.com/artsy/README/issues/427 and https://github.com/artsy/README/issues/386
- Remove master mentions in the project where it's possible
- Some archived/deprecated repos that we don't own still use master as default branch, we decided to leave those until we agree on best practice
-
-
-
- Remove artsy internal master branch references - mounir
</details>
=> chore: remove master references in eigen

scripts/build-for-tests-android
This PR resolves failing build on Android
The test build on Android has been failing due to missing the `bundleReleaseJsAndAssets`. This is a step that have separated from the main build because it's the one that consumes the most resources.
The build has been failing because at some point we removed the step of creating the assets folder.
-
-
- Fix test build failing - mounir
-
</details>
=> fix: add missing assets directory

.circleci/config.yml
While trying to understand why the build is failing here https://app.circleci.com/pipelines/github/artsy/eigen/20809/workflows/72f79527-9caa-4da6-9ff3-81826f74890c/jobs/60455/steps, I noticed that we have no build artifacts for android. These would help us get a better understanding of what's failing hopefully.
-
-
-
- Store build artifacts on Android - mounir
</details>
=> chore: store build artifacts on android

.circleci/config.yml
Use a large instance for ci - see if it works 🤷‍♂️
**Update:** it works like a charm!
-
-
-
- use large instance for ci - mounir
</details>
=> chore: use large instance

.circleci/config.yml, package.json, yarn.lock
This PR is a follow-up from https://github.com/artsy/eigen/pull/5887
- Upgrade update repo to 0.5.0
-
-
-
- Upgrade update repo to 0.5.0 - mounir
</details>
=> chore: upgrade update repo to 0.5.0

src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx, src/palette/elements/Checkbox/Checkbox.tsx
This PR resolves [CX-2221]
- Bidding flow terms and conditions text invisible  
- fix bidding flow terms and conditions text invisible - mounir
-
-
-
</details>
[CX-2221]: https://artsyproduct.atlassian.net/browse/CX-2221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: bidding flow terms and conditions text invisible  

fastlane/metadata/android/en-US/changelogs/default.txt, fastlane/metadata/en-US/release_notes.txt
Update release notes for 7.1.3
#nochangelog 
-
-
-
-
</details>
=> chore: update release notes for 7.1.3

app.json
This PR prepares 7.1.4 for development
#nochangelog
=> chore: Prepare 7.1.4 for development

index.ios.js, src/lib/ErrorReporting.ts, src/lib/utils/AdminMenu.tsx, src/lib/utils/useScreenReaderTracking.ts
This started as an investigation to solve `RangeError: Maximum call stack exceeded` with @olerichter00 and @MounirDhahri. We failed, but at least I fixed the following on the way.
- moved `setupSentry` in `index.ios.js` so it doesnt get called again
- removed a deprecated `enableOutOfMemoryTracking` from sentry init
- added an `Open RN Dev Menu` menu item in the admin menu, so we can open the RN dev menu on a device!
- reworked the `useScreenReaderTracking` to not use state
https://user-images.githubusercontent.com/100233/146233912-19aa5f4d-4380-42f3-9348-a6ba8642a1e1.mov
-
-
-
- moved `setupSentry` in `index.ios.js` so it doesnt get called again - pavlos
- removed a deprecated …
=> fix(DX): some small but nice things

src/lib/Components/Artist/ArtistConsignButton.tests.tsx, src/lib/Components/Countdown/Ticker.tests.tsx, src/lib/utils/renderWithLoadProgress.tests.tsx, src/lib/utils/renderWithPlaceholder.tests.tsx
Just some updates on tests here and there
-
-
-
- updated tests and removed some ts-expect-error - gkartalis
</details>
=> test: updated tests and removed ts-expect-error

src/lib/utils/useScreenReaderTracking.tests.ts, src/lib/utils/useScreenReaderTracking.ts
refactor screenreaderTracking hook to not use state and update tests
proof that this can work 🤷  https://codesandbox.io/s/react-ts-unit-test-example-forked-76e3k?file=/src/hooks/useStepper/useStepper.test.tsx
<details><summary>How it looks</summary>
</details>
- 
-
-
- refactor screenreaderTracking hook to not use state - gkartalis, pvinis
</details>
=> refactor: screenreaderTracking hook to not use state

scripts/biweekly-flag-check.sh
Fixes the flag check, had mislabeled the fastlane action, cleans up the script a little.  
-  
-
-
- Fix the feature flag biweekly check - Brian
</details>
=> fix: fix the flag check

src/lib/ErrorReporting.ts, src/lib/relay/middlewares/errorMiddleware.ts, src/lib/store/config/features.ts, src/lib/utils/AdminMenu.tsx
- The exceptions that we receive in Sentry are either named `<unknown>` or `RRNLRequestError`. This makes it harder to understand them unless we open their particular page. The goal from this PR is to take advantage of the `formatGraphQLErrors()` API in `react-relay-network-modern` to make our dashboard easier to understand.
-
-
-
- send better formatted errors to sentry - mounir
</details>
=> chore: send better formatted errors to sentry

src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/ArtworkTombstone_artwork.graphql.ts, src/__generated__/FollowArtistLinkMutation.graphql.ts, src/__generated__/FollowArtistLinkTestsErrorQuery.graphql.ts, src/__generated__/FollowArtistLinkTestsQuery.graphql.ts, src/__generated__/FollowArtistLink_artist.graphql.ts, src/lib/Components/Artist/ArtistHeader.tsx, src/lib/Components/ArtistListItem.tsx, src/lib/Components/Gene/Header.tsx, src/lib/Components/Home/ArtistRails/ArtistCard.tsx, src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx, src/lib/Scenes/Artwork/Components/ContextCard.tsx, src/lib/Scenes/Artwork/Components/FollowArtistLink.tests.tsx, src/lib/Scenes/Artwork/Components/FollowArtistLink.tsx, src/lib/Scenes/Artwork/Components/PartnerCard.tsx, src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalizationArtistListItem.tsx, src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx, src/lib/utils/Wrap.tsx, src/palette/elements/Button/Button.stories.tsx, src/palette/elements/Button/Button.tsx, src/palette/elements/Button/FollowButton.tsx, src/palette/elements/Button/index.tsx, src/storybook/storyLoader.js
This PR resolves [CX-2195]
Follow Buttons need an update to unify across all surfaces and better present states and share visual feedback for accessibility best practices. 
Within Eigen, we want to show the default button with text only, and the `following` state with updated text and a check on the left (as well as darker border of Black60). 
- Unify look for follow and following buttons
</details>
[CX-2195]: https://artsyproduct.atlassian.net/browse/CX-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://user-images.githubusercontent.com/554507/146221542-c0abd7b8-582f-4bc1-86c6-fe3fc2ecea2b.mp4 …
=> feat: unify follow buttons

src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
This PR resolves [CX-2071]
Removed unnecessary lineHeight prop with value 50 in MarketStats.tsx, paragraph "Sale price over estimate", "Market Signals" info popup.
- Decreased line spacing in paragraph "Sale price over estimate" in "Market Signals" info popup .
- 
-
-
</details>
[CX-2071]: https://artsyproduct.atlassian.net/browse/CX-2071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove unnecessary lineHeight prop in MarketStats.tsx

src/palette/elements/Select/Select.tsx
This PR resolves [CX-2246]
Changes the border color of the  `Select` component from `black10`  to `black30`.
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2021-12-29 at 10 39 33](https://user-images.githubusercontent.com/4691889/147648978-b136a34e-74c9-4b1b-b295-048605f9803a.png) | ![Simulator Screen Shot - iPhone 12 mini - 2021-12-29 at 10 41 42](https://user-images.githubusercontent.com/4691889/147648981-b0c12cb6-df00-4b7b-aed5-8031b851c8b0.png) |
- Adjust Select border color - ole
-
-
-
</details>
[CX-2246]: https://artsyproduct.atlassian.net/browse/CX-2246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Adjust Select border color

src/lib/Scenes/Home/Home.tsx
This PR resolves [CX-2244]
To match the current home layout with the bigger boxes in the second row.
_before_
_after_
- Update home placeholder's order
-
-
- Update home placeholder's order
</details>
[CX-2244]: https://artsyproduct.atlassian.net/browse/CX-2244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove artwork rails placeholder repetition

src/palette/elements/Select/Select.stories.tsx, src/palette/elements/Select/Select.tsx
This PR resolves [CX-2231]
This PR is the continuation of [closed PR ](https://github.com/artsy/eigen/pull/5928)
-Tooltip for select components on storybooks - sam
-
-
-
</details>
[CX-2231]: https://artsyproduct.atlassian.net/browse/CX-2231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Adding tooltip for Select components 

src/lib/AppRegistry.tsx, src/lib/Containers/Inbox/Inbox.tsx, src/lib/Scenes/BottomTabs/BottomTabs.tsx, src/lib/Scenes/Home/Home.tsx, src/lib/Scenes/Search/Search.tsx
This PR resolves [CX-1781]
Add prefetching to bottom navigation links.
-  Add prefetching to bottom navigation links - ole
-
-
-
</details>
[CX-1781]: https://artsyproduct.atlassian.net/browse/CX-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add prefetching to bottom navigation links

src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx, src/lib/Scenes/AuctionResult/ComparableWorks.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
Adjust auction results list item separators in order to make them normal again. The space between the items is not necessary anymore because it has been added to the item component in https://github.com/artsy/eigen/pull/5929
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2021-12-30 at 17 24 16](https://user-images.githubusercontent.com/4691889/147770028-471cb5c0-b643-4bca-a476-fc6ace332671.png) | ![Simulator Screen Shot - iPhone 12 mini - 2021-12-30 at 17 24 08](https://user-images.githubusercontent.com/4691889/147770032-16026032-bfdc-4a3e-a7ab-046e41d1280c.png) |
-
-
-
-
</details>
=> fix: Adjust auction results list item separators

src/lib/Scenes/MyCollection/Components/MyCollectionImageView.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
This PR resolves [CX-2199]
This PR removes the image validation for My Collection artworks and updates the fallback image to the new design.
| List View | Detail View |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2021-12-30 at 11 07 58](https://user-images.githubusercontent.com/4691889/147742631-0cbb8e3d-94e2-420c-8548-808580096d8c.png) | ![Simulator Screen Shot - iPhone 12 mini - 2021-12-30 at 11 15 31](https://user-images.githubusercontent.com/4691889/147742637-bdb070a5-6d7e-43bb-96f3-e33636881d12.png) |
- Allow "My Collection" artwork upload without images - ole
-
-
-
</details>
[CX-2199]: https://artsyproduct.atlassian.net/browse/CX-2199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
=> feat: Allow My Collection artworks without image

src/lib/Scenes/Sale/SaleActiveBidItem.tests.tsx
Fixes the failing SaleActiveItemBid.tests
-
-
-
- Fix SaleActiveBidItem.test - kizito
</details>
=> fix sale active bid item failing test

src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
This PR resolves [CX-1060]
Changed description textStyle from PaletteText to Sans
- changed description textStyle from PaletteText to Sans
-
-
-
https://user-images.githubusercontent.com/36167539/147093590-d47dd909-3184-47d8-a85f-12d95131cbc0.mp4
</details>
[CX-1060]: https://artsyproduct.atlassian.net/browse/CX-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-1060): change description textStyle

src/__generated__/AboutArtist_artwork.graphql.ts, src/__generated__/AboutWork_artwork.graphql.ts, src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts, src/__generated__/ArtworkHistory_artwork.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/Artwork_artworkAboveTheFold.graphql.ts, src/__generated__/Artwork_artworkBelowTheFold.graphql.ts, src/lib/Scenes/Artwork/Artwork.tests.tsx, src/lib/Scenes/Artwork/Artwork.tsx, src/lib/Scenes/Artwork/Components/AboutArtist.tsx, src/lib/Scenes/Artwork/Components/AboutWork.tests.tsx, src/lib/Scenes/Artwork/Components/AboutWork.tsx, src/lib/Scenes/Artwork/Components/ArtworkHistory.tests.tsx, src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx, src/lib/Scenes/Artwork/Components/CommercialInformation.tsx, src/lib/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
This PR refactors the artwork screen components (class component -> functional component).
Included components:
- [Artwork](http://www.google.com/search?q=src%2Flib%2FScenes%2FArtwork%2FArtwork.tsx&oq=src%2Flib%2FScenes%2FArtwork%2FArtwork.tsx&aqs=chrome.0.69i59j69i58.265j0j7&sourceid=chrome&ie=UTF-8)
- [AboutArtist](https://github.com/artsy/eigen/pull/5963/files#diff-965f51ed64081f5c91ee8412a7d39b312eeda42cf20c39c782846ce8dbdca0e9R11)
- [AboutWork](https://github.com/artsy/eigen/pull/5963/files#diff-c4350dd53d2574b98171d2cc567cda7dbee35de4a1cc2403655ba9426796933aR29)
- [AboutArtistHistory](https://github.com/artsy/eigen/pull/5963/files#diff-0b3cd4b942e8e851fbaeda8f7dd339e076f975ca5111db128b4cd40611b8e669R10)
- …
=> chore: Refactor artwork screen components

src/lib/Components/Modals/LoadingModal.tsx
This PR resolves [CX-2252]
- Make Spinner visible on android
- Use Palette `Spinner` instead of react-native `ActivityIndicator`
- Make sure that the status bar is also dimmed
- Fix: Use Palette Spinner for My Collection Add Artwork Saving Modal - mounir
- 
- Fix: Make My Collection Add Artwork Saving Spinner visible - mounir
-
</details>
[CX-2252]: https://artsyproduct.atlassian.net/browse/CX-2252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: saving spinner not visible on android in my collection

package.json, src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx, yarn.lock
This PR resolves [CX-2255]
- Rename Add an Artist to Select an Artwork
- Add tracking to artist research taps
**Before**
https://user-images.githubusercontent.com/11945712/148094085-ee9e9a27-48ab-4065-bed5-cd053861b02a.mov
**After**
https://user-images.githubusercontent.com/11945712/148094094-a8170a71-00e5-4579-96b7-5fdd74278c72.mov
- Rename Add an Artist to Select an Artwork - mounir
- Add tracking to artist research taps - mounir
-
-
-
</details>
[CX-2255]: https://artsyproduct.atlassian.net/browse/CX-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: rename select artist to select artwork

fastlane/metadata/android/en-US/changelogs/default.txt, fastlane/metadata/en-US/release_notes.txt
This PR updates the release notes for the next release **7.1.4**
#nochangelog
=> chore: update release notes for 7.1.4

src/lib/Components/ArtsyReactWebView.tsx, src/lib/Components/ArtsyReactWebViewPolicy.tsx, src/lib/Scenes/Onboarding/Onboarding.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingSocialPick.tests.tsx, src/lib/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx, src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx
This PR resolves [CX-2248]
Added the right navigation to Onboarding, Terms of Use, Privacy Policy and Conditions of Sale pages, Android. Fixes the bug introduced in CX-2204.
-
-
- Onboarding screens, Terms of Use, Privacy Policy  and Conditions of Sale pages are opened in a WebView on Android -Daria
- Added three webview components and used them in the Onboarding StackNavigator.Navigator
- Implemented navigation conditionally. For iOS - navigate function from lib/navigation/navigate. For Android - react-navigation
</details>
[CX-2248]: https://artsyproduct.atlassian.net/browse/CX-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2248): broken onboarding webview links on android

src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
This PR resolves [CX-2253]
Fixes bug where previously selected my collection artwork form details is not cleared if a user goes back and clicks Skip.
https://user-images.githubusercontent.com/18648835/148369006-f9933e12-2d57-4399-a566-08b79c7b14a6.mp4
- fix skip bug in my collection artwork forms - kizito
-
-
-
</details>
[CX-2253]: https://artsyproduct.atlassian.net/browse/CX-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: (CX-2253) fix skip bug in my collection artwork forms

app.json
This PR prepares 7.1.5 for development
-
-
-
- prepare 7.1.5 for development - mounir
</details>
=> chore: prepare 7.1.5 for development

src/lib/Scenes/MyCollection/MyCollection.tsx
This PR resolves [CX-2258]
Adjust My Collection import banner copy.
- Adjust My Collection import banner copy - ole
-
-
-
</details>
[CX-2258]: https://artsyproduct.atlassian.net/browse/CX-2258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Adjust My Collection import banner copy

src/lib/Scenes/Search/Search.tsx, src/lib/Scenes/Search/SearchModel.tsx, src/lib/Scenes/Search/SearchResults.tsx, src/lib/Scenes/Search/components/SearchPills.tests.tsx, src/lib/Scenes/Search/components/SearchPills.tsx, src/lib/Scenes/Search/components/SearchResult.tests.tsx, src/lib/Scenes/Search/components/SearchResult.tsx, src/lib/Scenes/Search/constants.ts, src/lib/Scenes/Search/types.ts
-
-
-
- Use key instead of name for search pills - dimatretyak
</details>
=> refactor: Use key instead of name for search pills

src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingSocialPick.tests.tsx
The type of this PR is: **tests**
A quick PR because I saw this in the tests.
#nochangelog
-
-
-
-
</details>
=> tests: re-enable all tests in OnboardingSocialPick.tests.tsx

src/lib/Scenes/Home/Home.tsx
Adjust home screen artist placeholder size.
| | |
|---|---|
|![Simulator Screen Shot - iPhone 12 mini - 2022-01-10 at 11 15 21](https://user-images.githubusercontent.com/4691889/148749549-0e972108-853e-4973-a7d8-e474c1fe9a53.png)|![Simulator Screen Shot - iPhone 12 mini - 2022-01-10 at 11 14 15](https://user-images.githubusercontent.com/4691889/148749648-c6b1f1b7-6205-411e-bf6c-df55e31aa6e1.png)|
- Fix home screen placeholder size - ole
-
-
-
</details>
=> fix: Adjust home screen artist placeholder size

src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/FavoriteArtworksPaginationQuery.graphql.ts, src/__generated__/FavoriteArtworksQuery.graphql.ts, src/__generated__/FeatureQuery.graphql.ts, src/__generated__/GenericGrid_artworks.graphql.ts, src/__generated__/HomeAboveTheFoldQuery.graphql.ts, src/__generated__/HomeBelowTheFoldQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/MyProfileQuery.graphql.ts, src/__generated__/MyProfileRefetchQuery.graphql.ts, src/__generated__/NewWorksForYouRailQuery.graphql.ts, src/__generated__/ShowArtworksPreviewTestsQuery.graphql.ts, src/__generated__/SmallTileRail_artworks.graphql.ts, src/__generated__/WorksForYouPaginationQuery.graphql.ts, src/__generated__/WorksForYouQuery.graphql.ts, src/lib/Components/ArtworkGrids/GenericGrid.tsx, src/lib/Scenes/Artwork/Artwork.tsx, src/lib/Scenes/Home/Components/SmallTileRail.tsx, src/lib/utils/relayHelpers.ts
Currently, the dimensions we set for the artwork image placeholder don't match the artwork dimensions. This PR improves how we calculate the dimension for the placeholder by looking for the artwork image record in the Relay store. This works in most places because we usually either already fetched the width and height or the image ratio of the artwork image.
How to access the Relay store directly is influenced by [this blog post](https://yashmahalwal.medium.com/a-deep-dive-into-the-relay-store-9388affd2c2b). 
I've added [these two](https://github.com/artsy/eigen/pull/5967/files#diff-9d0f2f55f3139b0bb2b677f9902e6e0d7c27196c113ff634fdaed962f57117d6R1) helper functions to find records in the Relay store.
**Before:** …
=> feat: Preload artwork placeholder image size

.secrets.baseline, src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx, src/lib/Components/ArtworkGrids/ArtworksFilterHeader.tsx, src/lib/Scenes/MyCollection/MyCollection.tests.tsx, src/lib/Scenes/MyCollection/MyCollection.tsx, src/setupJest.ts
This PR resolves [CX-2263]
Avoid My Collection price filter crash.
- fix: Avoid My Collection price filter crash - ole
-
-
-
</details>
[CX-2263]: https://artsyproduct.atlassian.net/browse/CX-2263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Avoid My Collection price filter crash

src/lib/utils/queryPrefetching.ts
Adjust query prefetching fetch policy to not bypass the cache.
-
-
-
-
</details>
=> fix: Adjust query prefetching fetch policy to not bypass the cache

src/lib/Components/Home/ArtistRails/ArtistRail.tsx, src/lib/Components/Home/ArtistRails/RecommendedArtistsRail.tsx, src/lib/Scenes/Artist/Artist.tsx
Prefetch artist recommendations.
- Prefetch artist recommendations - ole
-
-
-
</details>
=> feat: Prefetch artist recommendations

src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
=> Revert "fix: (CX-2253) fix skip bug in my collection artwork forms"

src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
This PR resolves [CX-2091]
- Fixes broken sharing to Instagram stories on android
- Replace sharing small images (because these images are blurry) with viewshot image
<p>
</p>
- Fix sharing to Instagram Stories - kizito
-
-
-
</details>
[CX-2091]: https://artsyproduct.atlassian.net/browse/CX-2091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix(cx-2091): fix broken sharing to instagram stories

src/lib/utils/AdminMenu.tsx
Clear Relay cache on reloads in Admin menu.
-
-
-
- Clear Relay cache on reload in Admin menu - ole
</details>
=> feat: Clear Relay cache on reload in Admin menu

src/palette/elements/Button/Button.stories.tsx, src/palette/elements/Button/CTAButton.tsx, src/palette/elements/Button/index.tsx
Adds CTAButton in Palette
-
-
-
-
</details>
=> feat: CTAButton in Palette

scripts/update-metaphysics.js
Change update-metaphysics target branch from master to main 
-
-
-
- change update-metaphysics target branch to main - gkartalis
</details>
=> fix: change master to main

src/lib/utils/useImageSearch.tsx
Supports both href and artworkHref coming from backend
-
-
-
- image search additions - gkartalis
</details>
=> feat: use both artworkHref/href

app.json
The type of this PR is: chore
-
-
-
-
</details>
=> chore: bump version

src/lib/Scenes/Home/Home.tsx, src/lib/store/config/features.ts
This PR resolves [CX-2270]
Remove AREnableNewWorksForYou feature flag.
-
-
-
- Remove AREnableNewWorksForYou feature flag - ole
</details>
[CX-2270]: https://artsyproduct.atlassian.net/browse/CX-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove AREnableNewWorksForYou feature flag

src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx, src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx, src/lib/Components/ArtworkFilter/SavedSearch/constants.ts, src/lib/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts, src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts, src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.ts, src/lib/Components/ArtworkFilter/SavedSearch/types.ts, src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tests.tsx, src/lib/Scenes/SavedSearchAlert/Components/Form.tsx, src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts, src/lib/Scenes/SavedSearchAlert/SavedSearchStore.tsx, src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV2.tsx, src/lib/Scenes/SavedSearchAlert/helpers.tests.ts, src/lib/Scenes/SavedSearchAlert/helpers.ts, src/lib/Scenes/SavedSearchAlert/pillExtractors.tests.ts, src/lib/Scenes/SavedSearchAlert/pillExtractors.ts, src/lib/Scenes/SavedSearchAlert/screens/CreateSavedSearchAlertScreen.tsx
This PR resolves [FX-3669]
-
-
-
- Refactor saved search alert logic - dimatretyak
</details>
[FX-3669]: https://artsyproduct.atlassian.net/browse/FX-3669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(FX-3669): saved search alert logic

src/lib/Scenes/Onboarding/OnboardingLogin.tsx
We are revalidating the form after setting the login error, since this isn't a form error it clears out the error. Remove the revalidation.
https://user-images.githubusercontent.com/49686530/149790955-4b084c2c-cc13-4478-9c0d-073056befac2.mp4
- Fix hidden login errors - brian 
-
-
-
</details>
=> fix: fix hidden login errors #trivial

app.json, fastlane/metadata/android/en-US/changelogs/default.txt, fastlane/metadata/en-US/release_notes.txt
This PR  prepares 7.1.7 for submission
#nochangelog
=> chore: prepare 7.1.7 for submission

src/__generated__/MyCollectionPaginationQuery.graphql.ts, src/__generated__/MyCollectionQuery.graphql.ts, src/__generated__/MyCollectionTestsQuery.graphql.ts, src/__generated__/MyCollection_me.graphql.ts, src/lib/Scenes/MyCollection/MyCollection.tsx, src/lib/store/config/features.ts
The type of this PR is: **chore** 
This PR resolves [CX-2269]
🔴  Blocked by https://github.com/artsy/metaphysics/pull/3668
Remove AREnableMyCollectionOrderImport feature flag.
-
-
-
- Remove AREnableMyCollectionOrderImport feature flag - ole
</details>
[CX-2269]: https://artsyproduct.atlassian.net/browse/CX-2269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove AREnableMyCollectionOrderImport feature flag

Artsy.xcodeproj/project.pbxproj, BrazePushServiceExtension/Info.plist, BrazePushServiceExtension/NotificationService.swift
This PR resolves [GRO-741]
- Adds a notification service extension target 
- Adds braze content
Following docs here: 
https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/rich/
- 
-  Support Braze rich push notifications - brian
-
-
</details>
[GRO-741]: https://artsyproduct.atlassian.net/browse/GRO-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: support braze rich push notifications

src/__generated__/ArtworkModuleRail_rail.graphql.ts, src/__generated__/ArtworkRailCard_artwork.graphql.ts, src/__generated__/HomeAboveTheFoldQuery.graphql.ts, src/__generated__/HomeBelowTheFoldQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/Home_homePageAbove.graphql.ts, src/__generated__/Home_homePageBelow.graphql.ts, src/__generated__/LargeArtworkRail_artworks.graphql.ts, src/__generated__/SmallArtworkRail_artworks.graphql.ts, src/lib/Components/ArtworkRail/ArtworkRail.tsx, src/lib/Components/ArtworkRail/ArtworkRailCard.tsx, src/lib/Components/ArtworkRail/LargeArtworkRail.tsx, src/lib/Components/ArtworkRail/SmallArtworkRail.tsx, src/lib/Components/OpaqueImageView/OpaqueImageView.tsx, src/lib/Scenes/Home/Components/ArtworkModuleRail.tsx, src/lib/Scenes/Home/Home.tests.tsx, src/lib/Scenes/Home/Home.tsx, src/lib/Scenes/Home/homeAnalytics.tests.ts, src/lib/Scenes/Home/homeAnalytics.ts
This PR resolves [CX-1818]
This PR introduces the new Palette V3 artwork rails (`SmallArtworkRail`, `LargeArtworkRail`) and updates the home feed artwork modules.
I'll update other existing artwork rails in follow-up PRs to reduce the size of this PR.
| --- | --- |
| ![simulator_screenshot_82650AFC-911A-4205-85FC-A634486223B3](https://user-images.githubusercontent.com/4691889/149953143-f7c45d52-c77b-480c-96a8-042312a8ead2.png) | ![simulator_screenshot_13E1425A-FCBF-41BB-A22B-FDF19F5E33A1](https://user-images.githubusercontent.com/4691889/149952956-ae9d0c24-6ee8-4c6a-ba96-98019c308d62.png) |
- Palette V3 artwork rails on the home screen - ole
-
-
-
</details>
[CX-1818]: …
=> feat: Palette V3 artwork rail

docs/add_a_visual_clue.md, src/lib/Scenes/BottomTabs/BottomTabs.tsx, src/lib/Scenes/BottomTabs/BottomTabsButton.tsx, src/lib/store/GlobalStore.tsx, src/lib/store/GlobalStoreModel.ts, src/lib/store/VisualClueModel.ts, src/lib/store/config/visualClues.ts, src/lib/store/migration.ts, src/palette/elements/VisualClue/VisualClue.stories.tsx, src/palette/elements/VisualClue/VisualClueDot.tsx, src/palette/elements/VisualClue/VisualClueText.tsx, src/palette/elements/VisualClue/index.tsx, src/storybook/storyLoader.js
This PR resolves [CX-2019]
This PR introduces the ability to add visual clues to the app. 
Visual clues can be added as a pulsating dot and a "new" text (see screenshots). 
```
!!showVisualClue("NewVisualClue") && <VisualClueDot />
!!showVisualClue("NewVisualClue") && <VisualClueText style={{ top: 14, right: -24 }} />
```
Whenever the user has seen the new feature `setVisualClueAsSeen("ClueName")` can be called to add the clue to the list of clues the user has seen (saved in GlobalStorage). 
**Screenshots:**
| | |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-01-10 at 15 21 27](https://user-images.githubusercontent.com/4691889/148781924-a6eaecb0-4bd3-41fa-9093-13de4b197ab3.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-01-10 at …
=> feat: Introduce visual clue

src/lib/store/config/features.ts
This PR resolves [CX-2273]
- Add collector profile feature flag
-
-
-
- Add collector profile feature flag - mounir
</details>
[CX-2273]: https://artsyproduct.atlassian.net/browse/CX-2273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add collector profile feature flag

src/__generated__/ViewingRoomArtworkRailTestsQuery.graphql.ts, src/__generated__/ViewingRoomArtworkRail_viewingRoom.graphql.ts, src/__generated__/ViewingRoomQuery.graphql.ts, src/__generated__/ViewingRoomTestsQuery.graphql.ts, src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tests.tsx, src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
This PR resolves [CX-1818]
Convert viewing rooms artwork rail to V3.
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-01-19 at 11 14 30](https://user-images.githubusercontent.com/4691889/150111563-a90739b6-acbd-46e4-bff3-eb713f464e7b.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-01-19 at 11 15 23](https://user-images.githubusercontent.com/4691889/150111590-93909193-39f6-46f3-9599-9ae106d81f17.png) |
- Convert viewing rooms artwork rail to V3 - ole
-
-
-
</details>
[CX-1818]: https://artsyproduct.atlassian.net/browse/CX-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Convert viewing rooms artwork rail to V3

src/lib/Components/PopoverMessage/PopoverMessage.stories.tsx, src/lib/utils/Wrap.tsx, src/palette/elements/Button/Button.stories.tsx, src/palette/elements/Input/Input.stories.tsx, src/palette/elements/Text/Text.stories.tsx, src/storybook/helpers.tsx
This PR resolves [MOPLAT-120]
The issue was with `Wrap`. It was returning `children` as a string, not `{children}` for the actual children.
@patrinoua check if its running locally for you too please 🙌.
#nochangelog
-
-
-
-
</details>
[MOPLAT-120]: https://artsyproduct.atlassian.net/browse/MOPLAT-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bring button stories back

src/__generated__/ArtistAboutTestsQuery.graphql.ts, src/__generated__/ArtistBelowTheFoldQuery.graphql.ts, src/__generated__/ArtistNotableWorksRailTestsQuery.graphql.ts, src/__generated__/ArtistNotableWorksRail_artist.graphql.ts, src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx, src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx, src/lib/Components/ArtworkRail/ArtworkRail.tsx, src/lib/Components/ArtworkRail/ArtworkRailCard.tsx
This PR resolves [CX-1818]
Convert artist notable works rail to V3.
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-01-19 at 11 43 17](https://user-images.githubusercontent.com/4691889/150114865-795d36d7-156b-40ec-b1bd-a197f7b55aea.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-01-19 at 11 41 06](https://user-images.githubusercontent.com/4691889/150114872-25ed8875-9df6-424f-8452-fe7290edb520.png) |
- Convert artist notable works rail to V3 - ole
-
-
-
</details>
[CX-1818]: https://artsyproduct.atlassian.net/browse/CX-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Convert artist notable works rail to V3

app.json
This PR prepares 7.2.0 for Dev
#nochangelog
=> chore: prepares 7.2.0 for development

src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx, src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx, src/lib/Scenes/Search/UserPreferencesModel.tsx
This PR addresses the comments in #5957 
This PR resolves [CX-1947]
This PR adds a new model to save user preferences and adds the currency and the dimension unit for the artwork form to it.
When this feature is implemented in Force, the user preferences needs to be stored in Gravity to reflect on both Force and Eigen
- Add UserPreferences for Currency and Dimension Unit - mrsltun 
-
-
-
</details>
[CX-1947]: https://artsyproduct.atlassian.net/browse/CX-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(CX-1947): Save user preferences follow-up

src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
Small changes for create alert flow and "Save Alert" button
-
-
-
- small change for create alert flow - dimatretyak
</details>
=> fix: small change for create alert flow (save alert button)

src/lib/Scenes/SavedAddresses/SavedAddresses.tests.tsx, src/lib/Scenes/SavedAddresses/SavedAddressesForm.tests.tsx
I just did this:
```
$ replace "26th" "24th"
```
And ran the tests which went green so I think this is fine.
https://artsyproduct.atlassian.net/browse/GRO-744
/cc @artsy/grow-devs @jpoczik
=> feat: Update Artsy Address GRO-744

src/lib/Components/PhoneInput/PhoneInput.tsx
add heights that improve how error message appears
-
-
-
-
</details>
=> fix: fix how error message appears

src/lib/Components/AnimatableHeader/AnimatableHeader.tsx
The type of this PR is: **Fixes**
This PR resolves [FX-3705]
⚠️ Changes are available under the feature flag –`Enable improved search pills`
It was not possible to align 100% the same everywhere, but I tried to center everything vertically as much as possible for iOS and Android
[Demo link](https://www.figma.com/file/Vtib71WLYAb5XhnErVpRjB/Header-for-Sort-%26-Filter?node-id=0%3A1)
* “Clear All” button should be underlined
* Header title and "Clear All" button should be aligned equally vertically [[issue](https://www.notion.so/artsy/Improved-Alerts-QA-77859f2050bb44258c47215ba44dfebd?p=355445d620f14593a5cc5e8936621ab6)]
* [Issue #1](https://www.notion.so/artsy/Improved-Alerts-QA-77859f2050bb44258c47215ba44dfebd?p=355445d620f14593a5cc5e8936621ab6)
* [Issue …
=> fix(FX-3705): Add small changes to the header for the "Sort & Filter" screen

src/lib/Scenes/MyCollection/MyCollection.tsx, src/lib/store/config/features.ts
This PR resolves [CX-2266]
-
-
-
- Removed released feature flag ARMyCollectionLocalSortAndFilter. Followed by code cleanup. - Daria
</details>
[CX-2266]: https://artsyproduct.atlassian.net/browse/CX-2266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(CX-2266): clean up feature flag ARMyCollectionLocalSortAndFilter

src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
Avoid error when onSuccess is not passed to the my collection artwork form.
-
-
-
- Avoid error when onSuccess is not passed to the my collection artwork form - ole
</details>
=> fix: Avoid error when onSuccess is not passed to the my collection artwork form

src/__generated__/MyCollectionAndSavedWorksQuery.graphql.ts, src/__generated__/MyCollectionAndSavedWorksTestsQuery.graphql.ts, src/__generated__/MyCollectionAndSavedWorks_me.graphql.ts, src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tests.tsx, src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
This PR resolves [CX-2183]
This PR updates the `otherRelevantPosition` to `otherRelevantPositions` as a follow up to artsy/metaphysics#3682
-
-
-
- update otherRelevantPosition to otherRelevantPositions - mrsltun
</details>
[CX-2183]: https://artsyproduct.atlassian.net/browse/CX-2183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore[CX-2183]: collector profile new info update

src/lib/Components/SectionTitle.tsx, src/lib/Scenes/Home/SectionTitle.tests.tsx
This PR addresses [CX-1818]
Update section title right button text from `>` to `View All >` according to the design.
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-01-26 at 12 06 35](https://user-images.githubusercontent.com/4691889/151152498-b037f2d0-0aab-4c39-a89c-58a8c6b2fc76.png) |  ![Simulator Screen Shot - iPhone 12 mini - 2022-01-26 at 12 03 07](https://user-images.githubusercontent.com/4691889/151152408-525b38a2-f981-4193-8d7b-71986a0e35b6.png) |
- Update section title right button text - ole
-
-
-
</details>
[CX-1818]: https://artsyproduct.atlassian.net/browse/CX-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Update section title right button text

src/lib/Components/ArtworkRail/ArtworkRailCard.tsx, src/lib/Components/ArtworkRail/SmallArtworkRail.tsx, src/lib/Scenes/Home/Home.tsx
The home screen placeholder needs to be adjusted after updating the artwork rails.
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-01-25 at 18 11 24](https://user-images.githubusercontent.com/4691889/151025230-69751535-a467-4ccb-b642-e2d4e76de6b5.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-01-25 at 18 05 53](https://user-images.githubusercontent.com/4691889/151025161-9a0c623a-1674-45b1-9a14-99d2179e9405.png) |
- Fix home screen placeholder - ole
-
-
-
</details>
=> fix: Adjust home screen placeholder

src/lib/Components/ArtworkRail/ArtworkRail.tsx
Adjust ArtworkRail onPress type.
-
-
-
-
</details>
=> fix: Adjust ArtworkRail onPress type

src/lib/Scenes/MyCollection/MyCollection.tsx, src/lib/store/config/features.ts
This PR resolves [FX-3706]
Marks AREnableImprovedAlertsFlow ready for release
-
-
-
- mark AREnableImprovedAlertsFlow readyForRelease - gkartalis
</details>
[FX-3706]: https://artsyproduct.atlassian.net/browse/FX-3706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-3706): mark AREnableImprovedAlertsFlow to readyForRelease

src/__generated__/CreateSavedSearchContentContainerV2Query.graphql.ts, src/__generated__/CreateSavedSearchContentContainerV2RefetchQuery.graphql.ts, src/__generated__/CreateSavedSearchContentContainerV2_me.graphql.ts, src/__generated__/getSavedSearchIdByCriteriaQuery.graphql.ts, src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tsx, src/lib/Scenes/SavedSearchAlert/Components/Form.tsx, src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx, src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts, src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV2.tsx, src/lib/Scenes/SavedSearchAlert/helpers.ts, src/lib/Scenes/SavedSearchAlert/queries/getSavedSearchIdByCriteria.ts
This PR resolves [FX-3707]
* If the user clicks on the "Cancel" button, then
* the warning message should close
* the duplicate alert will not be replaced
* the new alert will not be created (for create flow), new changes should not be applied to the old alert (for update flow)
* If the user clicks on the "Replace" button, then
* the warning message should close
* the duplicate alert should be replaced with a new alert.
* Warning message
* Title: Duplicate Alert
* Message: You already have a Saved Alert with these filters. Do you want to replace it?
* Buttons
* Cancel
* Replace
https://user-images.githubusercontent.com/3513494/151366055-0a5c0800-225e-44f0-8dc4-e3b1f97b6829.mp4
https://user-images.githubusercontent.com/3513494/151366086-eb6fdda8-8a42-49d4 …
=> feat(FX-3707): show a warning message for a duplicate alert

.env.example, .secrets.baseline, Artsy/Networking/ARRouter.m, src/lib/store/AuthModel.ts, src/setupJest.ts
As part of updating the app to support 2fa we needed to create new client ids for eigen on the backend. @joeyAghion also suggested we distinguish dev and prod clients. This pr updates our env vars an code to distinguish the two.
- Remove the old client keys from env after this is merged
-
-
-
- Distinguish dev and prod clients in app and env - brian
</details>
=> chore: distinguish dev and prod clients

src/palette/elements/Input/Input.stories.tsx
The type of this PR adds phoneInput to palette 
-
-
-
</details>
=> phoneInput on stories

src/lib/Scenes/MyCollection/MyCollection.tsx, src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
This PR adjusts the My Collection placeholder and removes the initial spinner.
| | |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-01-31 at 16 47 43](https://user-images.githubusercontent.com/4691889/151826280-5ed7ab8e-bbcf-4c5e-b286-224464196dea.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-01-31 at 16 48 58](https://user-images.githubusercontent.com/4691889/151826294-80234176-d1b1-4bdc-b6e5-b17263852719.png) |
- Adjust My Collection placeholder - ole
-
-
-
</details>
=> fix: Adjust My Collection placeholder

src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
Follow up for https://github.com/artsy/eigen/pull/6132
Render retry screen if My Collection query fails.
-
-
-
-
</details>
=> fix: Render retry screen if My Collection query fails

src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts, src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts, src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts, src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts, src/__generated__/MyCollectionArtworkQuery.graphql.ts, src/__generated__/MyCollectionArtwork_sharedProps.graphql.ts, src/__generated__/myCollectionAddArtworkMutation.graphql.ts, src/__generated__/myCollectionEditArtworkMutation.graphql.ts, src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx, src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
This PR resolves [CX-2291]
Added missing variable (artworkLocation) to myCollectionAddArtworkMutation and all corresponding query fragments to be able to change and save artworkLocation value.
**Before:**
https://user-images.githubusercontent.com/36167539/151817885-c5177255-2f16-47f8-bd0d-b434acb7c817.MP4
**After:**
https://user-images.githubusercontent.com/36167539/151818271-4dbdcc8b-6051-4a47-8eb7-bd7f45338375.mp4
- now artworkLocation field of artwork in My Collection can be changed and saved -daria
-
-
-
</details>
[CX-2291]: https://artsyproduct.atlassian.net/browse/CX-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2291): Can't save location when editing artwork in My Collection

src/__generated__/ContactInformationQuery.graphql.ts, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
Use the new hook **useLazyLoadQuery** for getting the user info
-
-
-
-
</details>
=> Contact information/use lazy load query

src/__generated__/ContactInformationQuery.graphql.ts, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
=> fetch data

src/__generated__/MyCollectionAndSavedWorksQuery.graphql.ts, src/__generated__/MyCollectionAndSavedWorksTestsQuery.graphql.ts, src/__generated__/MyProfileEditFormModal_me.graphql.ts, src/__generated__/updateMyUserProfileMutation.graphql.ts, src/lib/Components/DetailedLocationAutocomplete.tests.tsx, src/lib/Components/DetailedLocationAutocomplete.tsx, src/lib/Scenes/MyAccount/updateMyUserProfile.ts, src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx, src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx
This PR resolves [CX-2179]
This PR adds `profession`, `location` and `otherRelevantPosition` to the "My Profile" form.
| | |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-01-28 at 12 46 41](https://user-images.githubusercontent.com/4691889/151541917-5d3702c7-d5d5-41f7-b47a-7e9cac746375.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-01-28 at 12 46 51](https://user-images.githubusercontent.com/4691889/151541927-3981c40c-050e-41b7-8f90-8c9021fe8b28.png) |
- Add profession, location and otherRelevantPositions to profile form (behind feature flag). - ole
-
-
-
</details>
[CX-2179]: https://artsyproduct.atlassian.net/browse/CX-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> feat: Add profession, location and otherRelevantPosition to profile form

src/lib/utils/placeholders.tsx
This PR adds [layout animation](https://reactnative.dev/docs/layoutanimation) for placeholders to make the transitions smoother.
**With Layout Animation:**
https://user-images.githubusercontent.com/4691889/151797261-bdf7c6f4-f191-4d64-ab71-f1a6f6fa3c44.mp4
**Without Layout Animation:** 
Uploading Simulator Screen Recording - iPhone 12 mini - 2022-01-31 at 13.28.53.mp4…
- Add placeholder layout animation - ole
-
-
-
</details>
=> feat: Add placeholder layout animation

src/lib/Containers/Inbox.tsx, src/lib/utils/renderWithLoadProgress.tsx
The type of this PR is: **Improvement**
This PR adds a placeholder skeleton to the Inbox screen and deprecates `renderWithLoadProgress`.
| | |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-02-02 at 13 26 38](https://user-images.githubusercontent.com/4691889/152153435-9b022d91-b7ee-4540-8a2a-b53d26f7395f.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-02-02 at 13 25 45](https://user-images.githubusercontent.com/4691889/152153345-8c42cf2f-9cae-497a-a252-37f9f6c0812d.png)  |
- Add placeholder skeleton to Inbox screen - ole
-
-
-
</details>
=> fix: Add placeholder skeleton to inbox screen

.circleci/config.yml, .yarnrc, Artsy_Tests/Supporting_Files/ARTestHelper.m, scripts/source-for-bash-env
- updating the version of ios that the tests run. they are not broken, but now they are a bit more up-to-date than before.
- also, i added the tiny yarnrc line, to make sure that when we run `yarn add x`, the version will be installed like `"x": "1.2.3"` rather than `"x": "^1.2.3"`. we are trying to move to exact versions pinned.
-
-
-
-
</details>
=> ci(tests): update ios version for tests

fastlane/Fastfile
I changed a '+' to a '-'. 
I'll fix this manually for the outgoing builds 🙄 
-
-
-
- Fix sentry release name on iOS - Brian
</details>
=> fix: match iOS sentry release name in fastfile #trivial

src/__generated__/MyCollectionAndSavedWorksQuery.graphql.ts, src/__generated__/MyCollectionAndSavedWorksRefetchQuery.graphql.ts, src/__generated__/MyCollectionAndSavedWorksTestsQuery.graphql.ts, src/__generated__/MyCollectionAndSavedWorks_me.graphql.ts, src/__generated__/MyProfileEditFormModalTestsQuery.graphql.ts, src/__generated__/MyProfileEditFormModal_me.graphql.ts, src/__generated__/verifyEmailMutation.graphql.ts, src/lib/Scenes/Home/Components/EmailConfirmationBanner.tsx, src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx, src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx, src/lib/Scenes/MyProfile/__tests__/MyProfileEditFormModal.tests.tsx, src/lib/tests/renderWithWrappers.tsx, src/lib/utils/verifyEmail.ts
This PR resolves [CX-2180] [CX-2230]
- This PR adds profile verifications to my collection profile in addition to the email verification
- **Ps:** Id verification will be handled in a different ticket
https://user-images.githubusercontent.com/11945712/152404092-c5d8d86d-fab5-420f-9a6e-a87c66848e4e.mov
- Add Email Verification - mounir
- Add ID Vertification UI - mounir
-
-
-
</details>
[CX-2180]: https://artsyproduct.atlassian.net/browse/CX-2180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2230]: https://artsyproduct.atlassian.net/browse/CX-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add profile verifications

src/lib/store/config/features.ts, src/lib/tests/MockRelayRenderer.tests.tsx, src/lib/utils/placeholders.tsx
🔴 Depends on https://github.com/artsy/echo/pull/198
This PR 
- deactivates the placeholder layout animation for Android devices (because it causes issues), 
- adds an Echo feature flag, 
- reactors the placeholder animation hook,
- and sets the layout duration to 100ms.
-
-
-
-
</details>
=> fix: Deactivate placeholder layout animation for android

app.json, fastlane/metadata/android/en-US/changelogs/default.txt, fastlane/metadata/en-US/release_notes.txt
Prepare for next release, updates version number and release notes.
-
-
-
- Prep for next release - Brian
</details>
=> chore: 7.2.1 dev prep #trivial

src/lib/store/config/features.ts
This PR resolves [CX-2304]
Created ARShowConsignmentsInMyCollection feature flag
-
-
-
- created ARShowConsignmentsInMyCollection feature flag -daria
</details>
[CX-2304]: https://artsyproduct.atlassian.net/browse/CX-2304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(CX-2304): Create ARShowConsignmentsInMyCollection feature flag

src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
Android not affected in any way
|Android|
|---|
|![photo_2022-02-04 13 16 36](https://user-images.githubusercontent.com/21178754/152567251-b95586b3-5fe5-4305-9369-149bc80e4d01.jpeg)|
iOS
|8|11 Pro Max|13 Pro|13 mini|
|![iPhone 8](https://user-images.githubusercontent.com/21178754/152566633-cd3345be-b8f9-46a1-9b10-3c50c0f95b87.png)|![simulator_screenshot_521BC5BD-3DEC-4069-9020-3B5F049B97E6](https://user-images.githubusercontent.com/21178754/152567594-7c8134dd-770e-4a84-979c-631aee582bf2.png)|![simulator_screenshot_F980E1A2-899E-4D93-A9CD-10798BAADAF9](https://user-images.githubusercontent.com/21178754/152567096-52eda000-df1e-4897-aaee-a1940e5817a5.png)|![simulator_screenshot_5267AADA-50F0-4083-A09E-713810944305](https://user-images. …
=> chore: create alert button padding bottom on iOS devices

src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx, src/lib/Scenes/Artwork/Artwork.tests.tsx, src/lib/Scenes/Artwork/Artwork.tsx, src/lib/store/config/features.ts
Jira: [CX-2331]
Removes old AROptionsArtistSeries feature flag. The feature is already released for more than a month and the feature flag is not needed anymore.
-
-
-
Removes old AROptionsArtistSeries feature flag - Nikita
</details>
[CX-2331]: https://artsyproduct.atlassian.net/browse/CX-2331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CX-2331]: Remove AROptionsArtistSeries feature flag

src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx, src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx, src/lib/Scenes/MyProfile/utils.ts
This PR resolves [CX-2321]
This PR fixes an issue where it was possible to add many new lines to the bio which then makes the My Collection page unusable (see screenshot).
- Prevent new lines in My Profile bio - ole
-
-
-
</details>
[CX-2321]: https://artsyproduct.atlassian.net/browse/CX-2321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Prevent new lines in My Profile bio

src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tests.tsx, src/lib/Components/ArtworkFilter/FilterModal.tests.tsx, src/lib/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tests.tsx, src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx, src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tests.tsx, src/lib/Components/Gene/GeneArtworks.tests.tsx, src/lib/Components/Tag/TagArtworks.tests.tsx, src/lib/Scenes/MyCollection/MyCollection.tests.tsx, src/lib/Scenes/Sale/Sale.tests.tsx, src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tests.tsx, src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx, src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
After flipping the AREnabledImprovedAlertsFlow some tests started failing. This pr fixes those tests.
Update those tests to cover all new functionality
-
-
-
- fix failing tests due to release of AREnabledImprovedAlertsFlow - gkartalis
</details>
=> chore: fix failing tests due to ff release

src/lib/Scenes/MyCollection/MyCollection.tsx, src/lib/Scenes/MyCollection/MyCollectionArtworks.tsx
This PR resolves [CX-2332]
Add no results for filter message to My Collection.
-Add "no results for filter" message to My Collection - ole
-
-
-
</details>
[CX-2332]: https://artsyproduct.atlassian.net/browse/CX-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add no results for filter message to My Collection

app.json, fastlane/metadata/android/en-US/changelogs/default.txt, fastlane/metadata/en-US/release_notes.txt, src/lib/AppProviders.tsx, src/lib/AppRegistry.tsx, src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tests.tsx, src/lib/Components/ArtworkFilter/FilterModal.tests.tsx, src/lib/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tests.tsx, src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx, src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tests.tsx, src/lib/Components/Gene/GeneArtworks.tests.tsx, src/lib/Components/Tag/TagArtworks.tests.tsx, src/lib/Scenes/Artwork/Artwork.tests.tsx, src/lib/Scenes/Artwork/Artwork.tsx, src/lib/Scenes/MyCollection/MyCollection.tests.tsx, src/lib/Scenes/Sale/Sale.tests.tsx, src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tests.tsx, src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx, src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx, src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
This PR is a hotfix containing a fix for analytics events broken on iOS. 
PS: I followed the docs here https://github.com/artsy/eigen/blob/main/docs/deploy_a_hotfix.md
#nochangelog
=> fix: prepare for 7.2.1

src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx, src/palette/elements/Collapse/CollapseView.tsx, src/palette/elements/Collapse/index.tsx, src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
[SWA-205]
A replacement of Collapse component, using a View instead of Spring.
This resolves the bug of Collapse component not appearing on Android and sometimes on iOS due to height calculation issues.
To quickly test the behaviour you can go to ArtworkDetails component and
1) comment out line 55 (disabled under CTAButton)
```
<CTAButton
// disabled={!isValid}
onPress={() => handleArtworkDetailsSubmit(values)}
testID="Submission_ArtworkDetails_Button"
>
Save & Continue
</CTAButton>
```
2) replace handleArtworkDetailsSubmit (line 17) with 
```
const handleArtworkDetailsSubmit = async (values: ArtworkDetailsFormModel) => {
handlePress()
// try {
//   const id = await createOrUpdateSubmission(values, submissionId)
//   if (id) {
// …
```
=> feat [SWA-205] CollapsibleView component

src/lib/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
Use existing normalizeText function for keyword filtering.
-
-
-
-
</details>
=> fix: Use existing normalizeText function for keyword filtering

app.json
This PR set the app version to 7.2.2
#nochangelog
=> chore: set app version to 7.2.2

src/__generated__/MyCollectionArtworkQuery.graphql.ts, src/__generated__/NewMyCollectionArtworkHeaderTestQuery.graphql.ts, src/__generated__/NewMyCollectionArtworkHeader_artwork.graphql.ts, src/lib/AppRegistry.tsx, src/lib/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tests.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tsx, src/lib/tests/renderWithWrappers.tsx
This PR resolves [CX-2334]
This PR adds my collection artwork details page header
**Note:**
- I also kept the same logic we have for the image carousel and the analytics
https://user-images.githubusercontent.com/11945712/153213782-9d5bd4ca-b481-472b-bf1a-e7010bcdbd6b.mov
- Add my collection artwork details page header - mounir
-
-
-
</details>
[CX-2334]: https://artsyproduct.atlassian.net/browse/CX-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: my collection artwork details page header

src/__generated__/myCollectionAddArtworkMutation.graphql.ts, src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
This PR removes the unnecessary exports added by PR https://github.com/artsy/eigen/pull/6158
-
-
-
- Remove unnecessary exports added in MyProfileEditForm.tsx -Sam
</details>
=> chore: Remove unnecessary exports

src/lib/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
Remove selectTextOnFocus from My Collection search bar. Automatically selecting the text is not necessary and in combination with hiding the header on focus it creates weird UI effects.
-
-
-
-
</details>
=> fix: Remove selectTextOnFocus from My Collection search bar

src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
Follow-up on [CX-2238]
This PR resolves the right padding issue on the profile verifications
-
-
-
-
</details>
[CX-2238]: https://artsyproduct.atlassian.net/browse/CX-2238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add padding to profile verifications

docs/adding_a_new_route.md, src/lib/navigation/routes.tests.tsx, src/lib/navigation/routes.tsx
This PR adds `addRoute` as an abstraction on top of the `RouteMatcher` class to make it "easier to digest".
**Bonus:** I also updated the docs around adding a new route to explain why we need to make sure the routes we are adding are the same as in Force.
-
-
-
- Add abstraction on top of RouteMatcher - chriss, mounir
</details>
=> chore: abstract route matcher

docs/testing.md, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx
[SWA-223] adds tests to ContactInformation.tsx
also introduces testing.md an initial effort to put docs about testing together.
[SWA-223]: https://artsyproduct.atlassian.net/browse/SWA-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
-
-
-
</details>
=> Feat(SWA 223): Test ContactInformation

EXAMPLES.md, src/lib/store/ToastModel.ts
This is the result of a lot of discussions about new devs in eigen getting lost and not knowing what to copy, what to look at, how we do things. We have been doing different things and we still do things in multiple ways sometimes, so that file can serve as the "Latest and greatest way to do X in eigen".
-
-
-
- adding EXAMPLES.md - pavlos
</details>
=> docs(examples): adding our initial EXAMPLES.md

docs/preferred_practices.md
=> Update broken link

src/lib/Scenes/Show/Screens/ShowMoreInfo.tsx
This PR resolves [CX-2345]
Changed textStyle from "new" to "sans"
Before: 
https://user-images.githubusercontent.com/36167539/154079050-906fb9a1-ce07-4cc3-85b5-1517e7c5a52e.mp4
After:
https://user-images.githubusercontent.com/36167539/154079119-3b6552e5-0ac0-4b23-8981-319b66080465.mp4
- Fixed line height for "Read more" section on Gallery Info screen -daria
-
-
-
</details>
[CX-2345]: https://artsyproduct.atlassian.net/browse/CX-2345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2345): ReadMore line height changes after expansion

index.ios.js
=> test PR for circle

docs/preferred_practices.md
This PR implements the results of [this](https://artsy.slack.com/archives/C02BAQ5K7/p1643294097102400) vote.
-
-
-
</details>
=> docs: update folder capitalisation preferred practices

src/lib/store/migration.tests.ts
This PR resolves [CX-1990]
Add migration test for view options.
-
-
-
-
</details>
[CX-1990]: https://artsyproduct.atlassian.net/browse/CX-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Add migration test for view options

src/lib/utils/useDeepLinks.ts
This PR resolves [MOPLAT-141]
Watches the `isLoggedIn` state in the deeplink setup hook. Previously if you started a session unauthenticated and tried opening a deeplink the handleDeepLink call would still have the stale value of `false` for `isLoggedIn` so we would not try to navigate to the page. 
https://user-images.githubusercontent.com/49686530/154350434-d1237a4e-cbcd-406f-9234-52e64053fb13.mp4
</details>
https://user-images.githubusercontent.com/49686530/154350441-65fcf681-90a6-48b1-8700-d614b0be8286.mp4
</details>
-
-
- Fix deeplinks from sessions started unauthenticated - brian
-
</details>
[MOPLAT-141]: …
=> fix: android deeplinks, watch login state in deeplink setup

src/lib/Components/StickyHeaderPage.tsx, src/lib/Components/StickyTabPage/StickyTabPage.tsx, src/lib/Scenes/Onboarding/OnboardingLoginWithOTP.tests.tsx, src/lib/Scenes/Onboarding/OnboardingLoginWithOTP.tsx, src/lib/utils/hideBackButtonOnScroll.tsx
#nochangelog
-
-
-
-
</details>
=> fix(typo): some name fixes and prettier formatting

fastlane/Fastfile, fastlane/metadata/en-US/release_notes.txt, src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx, src/lib/utils/useDeepLinks.ts
- Prepare for 7.2.2 submission
- I created beta by following the beta freeze docs, the last beta we tested was last Friday "ios-7.2.2-2022.02.11.15" 
#nochangelog
=> Prepare for 7.2.2 submission

app.json
Co-authored-by: Nikita Skalkin <nikskalkin@gmail.com>
This PR prepares 7.3.0 for development
#nochangelog
=> chore: prepare 7.3.0 for developmemt

src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx, src/lib/store/config/features.ts
This PR resolves [FX-3749]
This pr removes `AREnableSortFilterForArtworksPill` feature flag that was [released](https://github.com/artsy/echo/pull/183) on `December 3rd of 2021` 
-
-
-
- remove AREnableSortFilterForArtworksPill feature flag - gkartalis
</details>
[FX-3749]: https://artsyproduct.atlassian.net/browse/FX-3749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove AREnableSortFilterForArtworksPill feature flag

src/lib/store/config/features.ts, src/lib/utils/AdminMenu.tsx
This PR:
- hides stable released feature flags from the admin menu
- removes the alphabetical sorting from the feature flags list which was making it hard to find newly added feature flags 
-
-
-
- Hide stable released feature flags from admin menu - mounir
</details>
=> chore: hide stable released feature flags from admin menu

src/lib/AppRegistry.tsx, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx, src/lib/navigation/BackButton.tsx, src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
[SWA-243] keep back button only on the first screen of submission flow
[SWA-207]
❗️ Please note: 
It seems to me like my prettier has added some unnecessary spaces in lines 22-25.
Maybe you can try locally to see if this happens, if you add an extra prop (eg hasBackButton) in line 22 of **CollapsibleMenuItem** ? 
Thank you in advance 🙏
-
-
-
</details>
[SWA-243]: https://artsyproduct.atlassian.net/browse/SWA-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SWA-207]: https://artsyproduct.atlassian.net/browse/SWA-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> feat (SWA-243) stop back button from floating

.circleci/config.yml, .github/workflows/release-ios-app.yml, docs/deploy_to_app_store.md, fastlane/Fastfile, scripts/check-if-app-has-been-approved-for-release.sh, scripts/release-ios-app, scripts/release-ios-app-branch
**[FUTURE FRIDAY]**
This PR does the following:
- Adds a script to release the ios app from CI. 
- We actually used this to release **7.2.2** 🎉
- Adds a cron-job that checks if the app has been approved at the store every 4 hours during work days and sends a slack notification to the team
- It would be nice to iterate on this to make it faster and to stop it from notifying the #practice-mobile if it already notified it, but yeah first good, then great then perfect 🤷‍♂️
- Update the docs to reflect the new changes
-
-
-
- add release ios app script - mounir, nikita
- add cron-job to check if the app has been approved at the store - mounir
</details>
=> feat: add release-ios-app and check-pending-release scripts

src/lib/AppProviders.tsx
Because we mix Relay query renderers with Relay hooks, it can happen that components using `useFragment` suspend without being wrapped in a `Suspense` component. This PR adds a root `Suspense` component to avoid them from throwing an error. 
**Example:**
```
<MyQueryRenderer>
...
<NestedComponentUsingRelayHooks />
...
</MyQueryRenderer>
```
-
-
-
- Add root Suspense component - ole
</details>
=> fix: Add root Suspense component

src/lib/Components/ArtsyReactWebView.tsx, src/lib/Components/LoadFailureView.tsx
This PR adds some more margin to the FailureView error message and removes an export that confuses auto import.
-
-
-
-
</details>
=> chore: Small improvements

src/lib/Scenes/Onboarding/OnboardingSocialLink.tsx, src/lib/store/AuthModel.ts
This PR resolves [CX-2373]
- Updates copy according to design spec. 
[See the Figma file here](https://www.figma.com/file/UsBYz11REIlXJwHCrgUkaz/Onboarding?node-id=2402%3A46865). Please Note that we are using designs in Suggested Flow (Frame 3)
- Update copy on link accounts flow - kizito
-
-
-
</details>
[CX-2373]: https://artsyproduct.atlassian.net/browse/CX-2373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2373): Update copy on link accounts flow

src/lib/Scenes/MyProfile/MyProfileEditForm.tsx, src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
This PR resolves [CX-2379]
Adjust collector profile icon alignment and size.
| small | big |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-02-22 at 13 08 28](https://user-images.githubusercontent.com/4691889/155120740-4611529f-84d1-4065-b785-c25e74608793.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-02-22 at 13 08 37](https://user-images.githubusercontent.com/4691889/155120751-8744ea2b-2d94-412b-ae13-c0aa8e12e9d1.png) |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-02-22 at 13 08 54](https://user-images.githubusercontent.com/4691889/155120756-68c59b67-fe51-45b4-9e7f-8712f01be40e.png) | ![Simulator Screen Shot - iPhone 12 mini - 2022-02-22 at 13 08 45](https://user-images.githubusercontent.com/4691889/155120761-833ca8d1-4aac- …
=> fix: Adjust collector profile verification icon alignment

.secrets.baseline, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tsx, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
This PR resolves [[SWA-247](https://artsyproduct.atlassian.net/browse/SWA-247)]
This PR changes the logic of preserving photos in GlobalStore in the photo upload step of the new submission flow. Previously, the photos were preserved in the GlobalStore after user clicks Save & Continue button, so that user would see uploaded photos when they leave and come back to the form. With the change, photos are saved to the GlobalStore as soon as they are uploaded on backend. 
https://user-images.githubusercontent.com/42584148/155095719-0f00eafa-13b8-4a03-8db6-12ae38d0b8b9.mp4
The change is applicable only to devs since the feature is behind a flag. 
</details>
=> [enhancement]: Preserve photos on GS as soon as upload on backend

src/lib/Components/DetailedLocationAutocomplete.tsx, src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
This PR resolves [CX-2375]
- Improve next behavior on collector profile edit
https://user-images.githubusercontent.com/11945712/155152513-ade720b5-8e8c-4085-98f1-b612eac8e07d.mov
-
-
-
-
</details>
[CX-2375]: https://artsyproduct.atlassian.net/browse/CX-2375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: improve next behaviour on collector profile edit

.secrets.baseline, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/PhotoRow.tsx, src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
This PR resolves [[SWA-246](https://artsyproduct.atlassian.net/browse/SWA-246)]
This PR fixes a bug in the photo upload step of the new submission flow. The bug is that when user uploads photos of which total size exceeds 30MB, we are supposed to display an error message to the user. The fix:
- displays the error message on the photo that causes the limit to be exceeded 
- stops the upload of other further photos, if any 
- disables the continue and add photos buttons, when limit exceed
- and clears the error message, when a photo is deleted and the total size is no longer above the limit
https://user-images.githubusercontent.com/42584148/155089173-cb2bc4e7-0254-475d-b80e-6b0f3e8108e4.mp4
The changes apply to …
=> [fix]: 30mb err msg in Submission photo upload step

docs/preferred_practices.md
This PR updates all sections in preferred_practices.md related to Relay according to the https://github.com/artsy/eigen/issues/6080.
-
-
-
-
</details>
=> docs: Update preferred practices relay sections

README.md
Adds a link to preferred practices in README
-
-
-
- 
</details>
=> docs: add link to preferred practices

src/app/Scenes/MyProfile/MyProfileEditForm.tsx
This PR resolves [CX-2374]
- Fix keyboard issues on my collection edit profile screen
**Before**
https://user-images.githubusercontent.com/11945712/155292732-c5d17ceb-4199-4332-a1bf-c8bfa16165c2.mov
**After**
https://user-images.githubusercontent.com/11945712/155292671-e67204a0-de95-4d69-a88b-610f57d84e3c.mov
- Fix keyboard issues on my profile edit screen - mounir
-
-
-
</details>
[CX-2374]: https://artsyproduct.atlassian.net/browse/CX-2374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: keyboard issues on my collection edit profile screen

src/app/Scenes/Home/Home.tsx, src/app/store/config/features.ts
This PR resolves [CX-2364]
- remove shows for you rail ff
-
-
-
- remove shows for you rail ff - mounir
</details>
[CX-2364]: https://artsyproduct.atlassian.net/browse/CX-2364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove shows for you rail ff

src/app/Scenes/Home/Home.tsx, src/app/store/config/features.ts
This PR resolves [CX-2365]
- Remove enable trove ff
-
-
-
- remove enable trove ff - mounir
</details>
[CX-2365]: https://artsyproduct.atlassian.net/browse/CX-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove enable trove ff

src/app/Scenes/MyProfile/MyProfileEditForm.tsx, src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx, src/app/Scenes/MyProfile/utils.tests.ts, src/app/Scenes/MyProfile/utils.ts
This PR resolves [CX-2377]
- Fix bio line breaks issues on the collector profile
- I updated the helper we have to also support other types of line breaks + concatenating the lines together and showing them properly with `. ` as a separator (this is not set in stone of course and I am happy to update this logic)
- Fix line break issues on the collector profile - mounir
-
-
-
</details>
[CX-2377]: https://artsyproduct.atlassian.net/browse/CX-2377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: bio line breaks issues on the collector profile

src/app/store/config/features.ts
This PR resolves [CX-2360]
- Add ARShowDemandIndexHints and ARShowwRequestPriceEstimateBanner feature flags
-
-
-
- add ARShowDemandIndexHints and ARShowwRequestPriceEstimateBanner feature flags - mounir
</details>
[CX-2360]: https://artsyproduct.atlassian.net/browse/CX-2360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add ARShowDemandIndexHints and ARShowwRequestPriceEstimateBanner feature flags

src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx, src/app/store/AuthModel.ts, src/app/utils/PushNotification.ts
- This PR refactors some thunks inside the AuthModel
- I tested the login flows again using all authentication methods and everything is working fine for me
-
-
-
- refactor some thinks inside the auth model - mounir
</details>
=> chore: refactor some thunks inside the AuthModel

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx, src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx, src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx, src/app/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx, src/app/Scenes/Artwork/Components/CommercialInformation.tsx, src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx, src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx, src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tests.tsx, src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tsx, src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx, src/app/utils/ArtworkInquiry/ArtworkInquiryStore.tests.tsx, src/app/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
This PR resolves [NX-3082]
We're changing the copies around `Buy now`, `Make offer` and `Contact for Price` but only the copies, we are not touching in any `saleMessage` coming from Gravity or other services, nor the language elsewhere, example we still call `Buy now` everything related to it, only the copy has changed to `Purchase`.
Price on Request
Purchase and Make an Offer
Make an Offer
- change copies Buy Now, Make Offer and Contact For Price - araujobarret
-
-
-
</details>
[NX-3082]: https://artsyproduct.atlassian.net/browse/NX-3082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(NX-3082): Change artwork and CTAs copies

src/app/Scenes/MyProfile/MyProfileEditForm.tsx
This PR resolves [CX-2378]
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/155701723-4312a89c-de7b-42b9-a0b7-894f3db9d93b.png)|![image](https://user-images.githubusercontent.com/17421923/155701654-4b878da0-7143-4ff1-aecf-019b5ecfe540.png)|
- Change copy of fields and placeholder on Collector Profile - Sam
-
-
-
</details>
[CX-2378]: https://artsyproduct.atlassian.net/browse/CX-2378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Update copy on Collector profile

src/app/Scenes/MyProfile/MyProfileEditForm.tsx, src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx, src/palette/svgs/Icon.tsx
Follow up for https://github.com/artsy/eigen/pull/6286
Font scaling does not apply to icons. This PR changes that.
| small font | large font |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 mini - 2022-02-25 at 12 22 46](https://user-images.githubusercontent.com/4691889/155698877-67d47841-55b6-4c92-9baa-fba65ab6e527.png) |  ![Simulator Screen Shot - iPhone 12 mini - 2022-02-25 at 12 22 56](https://user-images.githubusercontent.com/4691889/155698881-b1fb728d-eb6c-4e99-8afa-dbac04c0faef.png)
|
- Scale all icons based on font scale - ole
-
-
-
</details>
=> feature: Scale all icons based on font scale

src/app/Scenes/Artwork/Components/ArtworkHeader.tsx, src/app/store/config/features.ts
This PR resolves [CX-2366]
Remove AREnableCustomSharesheet feature flag.
- 
-
-
- Remove AREnableCustomSharesheet feature flag - ole
</details>
[CX-2366]: https://artsyproduct.atlassian.net/browse/CX-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove AREnableCustomSharesheet feature flag

src/app/Components/OpaqueImageView/createGeminiUrl.tsx, src/app/store/config/features.ts
This PR resolves [CX-2363]
Remove AREnableWebPImages feature flag.
-
-
-
- Remove AREnableWebPImages feature flag - ole
</details>
[CX-2363]: https://artsyproduct.atlassian.net/browse/CX-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove AREnableWebPImages feature flag

README.md
=> Update README.md : Fix typo

Artsy/App_Resources/Artsy-Info.plist
This PR resolves google login issues caused by an invalid URL scheme. I noticed this is broken after we updated our **GoogleService-info.plist**
-
- set the right url scheme on google login - mounir
-
-
</details>
=> fix: invalid url scheme on google login

docs/preferred_practices.md, src/app/Scenes/MyProfile/MyProfileEditForm.tsx
This PR updates the phrasing and removes some old parts of the documentation. 
preferred_practices.md is there to give us a broad overview of the history and how we prefere to do things.
@olerichter00 could you maybe contribute on the **relay hooks** part?
@gkartalis could you contribute on the **testing** part? 
We don't need to fix everything under this PR, but this could be a start to make sure we keep our current practices up to date.
-
-
-
</details>
=> Docs: Update preferred_practices.md

README.md
#nochangelog
-
-
-
-
</details>
=> docs(point people): adding a link to our full list

src/app/Components/PhoneInput/PhoneInput.tests.tsx, src/app/Components/PhoneInput/PhoneInput.tsx, src/palette/elements/Input/Input.tests.tsx, src/palette/elements/Input/Input.tsx
The type of this PR is: **bug**
[SWA-228]: use consistent error message format
**To reviewers :** For some reason there is a lot of white space diffs that you can turn off by selecting "Hide whitespace" 
-
-
-
</details>
[SWA-228]: https://artsyproduct.atlassian.net/browse/SWA-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bug(SWA-228): use consistent error message format

src/app/store/config/features.ts
This PR sets the collector profile and linking social accounts feature flags to be ready for release.
**Please make sure to merge this pull request instead of squashing it!**
**The CI needs to be restarted after https://github.com/artsy/echo/pull/209 gets merged**
-
-
-
- set the collector profile and linking social accounts flags to be ready for release - mounir
</details>
=> chore: prepare ready feature flags for the release

src/app/Components/PhoneInput/PhoneInput.tsx
The type of this PR is: **bug**
[SWA-248] erase the area code of US phone numbers
**bug**
https://user-images.githubusercontent.com/36475005/155716606-16a3b6a8-b36e-44b9-b24e-5462986e52d9.mov
**resolution**
https://user-images.githubusercontent.com/36475005/155716631-08c215e2-0523-4c32-8a38-40dfee61bd7c.mov
-
-
-
</details>
[SWA-248]: https://artsyproduct.atlassian.net/browse/SWA-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bug[SWA-248] remove the country code bug

.secrets.baseline, src/app/Scenes/Consignments/Screens/ConfirmContactInfo.tsx, src/app/Scenes/Consignments/Screens/Confirmation.tests.tsx, src/app/Scenes/Consignments/Screens/Confirmation.tsx, src/app/Scenes/Consignments/Screens/Overview.tsx, src/app/Scenes/MyCollection/MyCollection.tests.tsx, src/setupJest.ts
=> Revert "fix: fix old consignments nav"

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tsx, src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
This PR fixes a few UI problems that I found after manual testing:
1. Removed additional paddings for each flow step
2. Added scroll view for the last step
3. Updated collapsing animation 
<details><summary>Removed additional paddings for each flow step</summary>
Before
Now
</details>
<details><summary>Added scroll view for the last step</summary>
Before
https://user-images.githubusercontent.com/79979820/155985523-79d63196-20ce-42f4-8a5d-bdccd32d4660.mov
Now
https://user-images.githubusercontent.com/79979820/155983148-6f053b1f-b987-4283-9c19-8e8f38a62204.mov
</details>
<details><summary>Updated collapsing animation</summary>
Before
https://user-images.githubusercontent.com/79979820/155985366-716a9302-88ff-42dd-a93a-ce10ef9ae8a4.mov
Now …
=> fix(SWA): submission flow updates

.secrets.baseline, src/app/Scenes/Consignments/Screens/ConfirmContactInfo.tsx, src/app/Scenes/Consignments/Screens/Confirmation.tests.tsx, src/app/Scenes/Consignments/Screens/Confirmation.tsx, src/app/Scenes/Consignments/Screens/Overview.tsx, src/app/Scenes/MyCollection/MyCollection.tests.tsx, src/setupJest.ts
Co-authored-by: brainbicycle <brian.beckerle@artsymail.com>
The type of this PR is: **Bugfix for a bugfix**
This PR fixes:
- fix issue with back navigation on swa flow
**Use Squash instead of merge**
- fix issue with back navigation on swa flow
-
-
- 
</details>
=> fix: fix issue with back navigation on swa flow

src/app/Scenes/Consignments/ConsignmentsHome/ConsignmentsHome.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tsx, src/app/Scenes/Consignments/Utils/TrackingEvent.ts, src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
~~**WIP because waiting for the response from the data team**~~
This PR resolves [SWA-90]
This PR adds new analytics events for the submission flow.
-
-
-
- Add analytics tracking for the submission flow
</details>
[SWA-90]: https://artsyproduct.atlassian.net/browse/SWA-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(SWA-90): event tracking for submission flow

docs/best_practices.md
#nochangelog
-
-
-
-
</details>
=> docs: tiny change

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx, src/palette/elements/Button/Button.stories.tsx, src/palette/elements/Button/LinkButton.tsx, src/palette/elements/Button/index.tsx, src/palette/elements/Select/Select.tsx, src/palette/elements/Text/LinkText.tsx, src/palette/elements/Text/Text.stories.tsx, src/palette/elements/Text/Text.tsx
before
after
This PR resolves [swa-252] : underline "what is this?" text
-
-
-
</details>
=> feat[swa 252]underline "what is this?" text

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
This PR resolves [SWA-276] : updates error message for an invalid email address which was not completely human-readable
-
-
-
</details>
[SWA-276]: https://artsyproduct.atlassian.net/browse/SWA-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat [SWA-276] update user email error

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
This PR resolves [SWA-254]
This PR adds HEIC to the list of supported file in the UI only. 
Changes applicable to devs only. 
</details>
[SWA-254]: https://artsyproduct.atlassian.net/browse/SWA-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Enhancement]: add HEIC to supported files list

.circleci/config.yml
We we were point to the check flags job in the workflow instead of the new check release status workflow. 
Think this was a copy paste issue none of us caught in review. 🙈 
-
-
-
- Fix release status check job - brian
</details>
=> fix: fix release status check job #trivial

docs/README.md
This PR resolves : easily navigate through our docs
-
-
-
</details>
=> docs: Update eigen docs README.md

src/app/Icons/HighDemandIcon.tsx, src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
This PR resolves [CX-2359]
Adds trending icon to My Collection artwork detail screen if the demand index is higher or equal to 9.
- Add trending icon to My Collection artwork detail screen - ole
-
-
-
</details>
[CX-2359]: https://artsyproduct.atlassian.net/browse/CX-2359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add trending icon to My Collection artwork detail screen

src/app/Scenes/AuctionResult/ComparableWorks.tsx
Renames ComparableWorks variables.
-
-
-
-
</details>
=> chore: Rename ComparableWorks variables

src/app/AppRegistry.tsx, src/app/navigation/routes.tests.tsx, src/app/navigation/routes.tsx
The type of this PR is: chore
This PR resolves [CX-2367]
-
-
-
- Remove AROptionsNewSalePage feature flag - Sam
</details>
[CX-2367]: https://artsyproduct.atlassian.net/browse/CX-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove AROptionsNewSalePage feature flag

src/app/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
https://artsyproduct.atlassian.net/browse/FX-3355 but for eigen
-
-
-
-
</details>
=> feat: remove cohesion helper

fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/android/en-US/title.txt, fastlane/metadata/en-US/description.txt
- Updates title of Android app to be under character count limit
- Updates number of partners from 3000+ -> 4000+
- Updates anywhere in app description we are using `sell` to `resell`
-
-
-
- Update app description and title - brian
</details>
=> chore: update app description and title, sell -> resell, update partner count

src/app/Components/ArtsyKeyboardAvoidingView.stories.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx, src/storybook/storyLoader.js
The type of this PR is: **bug**
This PR resolves [SWA-274]
Keyboard covers half of phone number field
as well as a small fix for "what's this?" text colour 
-
-
-
</details>
[SWA-274]: https://artsyproduct.atlassian.net/browse/SWA-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Patrinoua/swa 274/keyboard covers input field

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
This PR resolves [CX-2417]
Before
https://user-images.githubusercontent.com/17421923/157456422-76177ff6-3f62-4655-a8fb-3c6559762698.mov
After
https://user-images.githubusercontent.com/17421923/157456452-f1fdf5f4-9564-47a1-bec1-895483e262dd.mov
- Sticky button at the bottom of My collection add/edit artwork form page - sam
-
-
-
</details>
[CX-2417]: https://artsyproduct.atlassian.net/browse/CX-2417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Stick Save/Complete button on My collection artwork form

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/validation.ts, src/palette/elements/Input/PhoneInput/PhoneInput.tests.tsx, src/palette/elements/Input/PhoneInput/PhoneInput.tsx
The type of this PR is: **BugFix**
This PR resolves [SWA-289]
This PR resolves [SWA-292]
This PR resolves [SWA-293]
This PR improves the validation of the contact information in the new app submission flow. Specifically: 
- improves phone number validation (SWA-289) 
- validates email address after input value changed (SWA-292) 
- fixes the display of an error message when submitting (SWA-293)
https://user-images.githubusercontent.com/42584148/157086480-a28ac42b-6ef3-40b8-af48-b6a66de51d13.mp4
Changes applicable to devs only. 
</details>
[SWA-289]: https://artsyproduct.atlassian.net/browse/SWA-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SWA-292]: …
=> fix: swa289/92/93 - Contact Information step validations

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
This PR resolves [SWA-294]
https://user-images.githubusercontent.com/36475005/157635446-c62c4cf1-9c38-4bf3-be44-101aeb83639d.mov
-
-
-
</details>
[SWA-294]: https://artsyproduct.atlassian.net/browse/SWA-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix[SWA-294]:reposition onPress

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
This PR is the follow up of https://github.com/artsy/eigen/pull/6391
The button should stay behind the keyboard as per the discussion [here](https://artsyproduct.atlassian.net/browse/CX-2417?focusedCommentId=46885). 
Before
https://user-images.githubusercontent.com/17421923/157662263-32751a3b-350c-4540-a625-5d1ca412d424.mov
After
https://user-images.githubusercontent.com/17421923/157662234-e8aef3a0-c7fa-481b-ab04-3f8625514bf1.mov
- Button should stay behind the keyboard on MyCollection Add/Edit artwork form - Sam
-
-
- 
</details>
=> fix: Button behind keyboard

src/app/Scenes/Home/Components/ShowsRail.tsx, src/app/Scenes/Home/Home.tsx
Because we never show more than 2 shows per gallery we need to overfetch, filter out, and then limit the number of shows.
Follow up for https://github.com/artsy/gravity/pull/15059
- Limit gallery appearances in Shows For You rail - ole
-
-
-
</details>
=> fix: Limit shows per gallery for Shows for You rail

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/Mutations/createConsignSubmissionMutation.ts
This PR resolves [SWA-234]
The PR adds source field to identify the source of the submission.
-
-
-
- Added source field on submission create
</details>
[SWA-234]: https://artsyproduct.atlassian.net/browse/SWA-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(SWA-234): add submission source for the app.

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx
This PR resolves [SWA-300]
Since new submission flow is ready to be released but the submission <> myCollection integration is not, this PR wraps the mentions to my collection in the Artwork submitted screen with the relevant feature flag. 
Feature flag disabled
---
Feature flag enabled
The change will be (for the first time) visible to all users. 
</details>
[SWA-300]: https://artsyproduct.atlassian.net/browse/SWA-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: wrap my collection mentions with feature flag in submitted screen

.secrets.baseline, src/app/Scenes/Onboarding/ForgotPassword.tsx, src/app/Scenes/Onboarding/Onboarding.tsx, src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx, src/app/Scenes/Onboarding/OnboardingLogin.tsx, src/app/Scenes/Onboarding/OnboardingLoginWithOTP.tsx
This PR resolves [CX-2138]
Removed <ArtsyKeyboardAvoidingView/> that wrapped NavigationContainer of all Onboarding screens (file Onboarding.tsx).  Instead placed it inside the <View/> wrapper for each component of Onboarding flow. To the mentioned View added paddingButtom: 10 (used 10 because we use paddingBottom: 20 on OnboardingWelcome screen for the text and 10 looks ok for the button. I couldn't find the design for these screens in figma, looks like they've been updated recently)
After fixes. On the left - Android, on the right - iOS
https://user-images.githubusercontent.com/36167539/157866769-42f35947-f5b2-4def-8752-85c1b5b8f997.mov
- small design improvements for the onboarding screens -daria
-
-
- …
=> fix(CX-2138): login and signup screen, bottom buttons dont obey SafeArea

src/app/Components/MenuItem.tsx, src/app/Scenes/MyAccount/MyAccount.tests.tsx, src/app/Scenes/MyAccount/MyAccount.tsx, src/app/utils/LinkedAccounts/apple.ts, src/app/utils/LinkedAccounts/facebook.ts, src/app/utils/LinkedAccounts/google.ts
- Fixes weird Account linking issues.
https://user-images.githubusercontent.com/18648835/158218345-e8c8d922-49e2-4d28-b8cd-48e88e7727a0.mp4
- 
-
-
-
- Fix for account linking behaviour bug - kizito
</details>
=> chore(Account Linking): fix for launch blocking account linking behaviour

package.json
The type of this PR is: **UX**
Thanks to @pepopowitz for showing me this exists.
Now when we run `yarn start` we will get names on the left, instead of 0 and 1, so we know where each output line is coming from.
#nochangelog
-
-
-
-
</details>
=> feat(ux): adding names to `yarn start` output

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/MediumPicker.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
This PR resolves [CX-2437]
Make medium required in artwork form.
| --- | --- |
|![Simulator Screen Shot - iPhone 12 mini - 2022-03-15 at 12 07 37](https://user-images.githubusercontent.com/4691889/158364998-e0b0d3dd-f52c-4666-b2d0-5076ad19a395.png)| ![Simulator Screen Shot - iPhone 12 mini - 2022-03-15 at 12 04 26](https://user-images.githubusercontent.com/4691889/158365008-a9a39866-bb00-439f-aedd-2bd7ae6c725e.png)|
-
-
-
-
</details>
[CX-2437]: https://artsyproduct.atlassian.net/browse/CX-2437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Make medium required in artwork form

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
removed redundant failing test
-
-
-
- removed redundant failing test -daria
</details>
=> chore: removed redundant failing test

scripts/check-flags/check-flags.tests.ts, src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx, src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx, src/app/store/config/features.ts
This PR resolves [NX-3093]
-
-
-
- Removes old NewFirstInquiry feature flag - Mitchell
</details>
[NX-3093]: https://artsyproduct.atlassian.net/browse/NX-3093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore: Remove NewFirstInquiry feature flag

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx, src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
This PR resolves [CX-2354]
use isSold instead of inProgress for My Collection artworks.
-
-
-
-
</details>
[CX-2354]: https://artsyproduct.atlassian.net/browse/CX-2354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: use isSold instead of inProgress for My Collection artworks

package.json, src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx, yarn.lock
This PR resolves [CX-2415]
This PR adds a link to skip the `Select and Artwork` page below the search artworks textbox.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/157700122-e0803d41-c174-45f7-90c9-98855bab1695.png)|![image](https://user-images.githubusercontent.com/17421923/157700031-b4694673-fd8a-4f31-87b4-372b4b154d83.png)|
- Added a link to skip the `Select and Artwork` page below the search artworks textbox - sam
-
-
-
</details>
[CX-2415]: https://artsyproduct.atlassian.net/browse/CX-2415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add skip ahead link

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx, src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx, src/app/store/config/features.ts
This PR resolves [CX-2442]
Put price estimate range behind feature flag.
-
-
-
- Put price estimate range behind feature flag - ole
</details>
[CX-2442]: https://artsyproduct.atlassian.net/browse/CX-2442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Put price estimate range behind feature flag

scripts/setup-env-for-artsy, scripts/setup-env-for-oss
This PR removes "rimraf storybook" from setup env
-
-
-
- remove "rimraf storybook" from setup env
</details>
=> fix: remove rimraf storybook

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
This PR resolves [CX-2448]
|Before  | After |
|---|---|
https://user-images.githubusercontent.com/36167539/159036053-e65306ca-8767-439e-81d4-3f7a9d788c83.mp4 | https://user-images.githubusercontent.com/36167539/159036116-0622fe92-5b63-4c45-9984-10bd48d7ee5b.mp4
This PR fixes the link that allows to skip the Select and Artwork page.
- Fixed unclickable link on the select artwork page in my collection -daria
-
-
-
</details>
[CX-2448]: https://artsyproduct.atlassian.net/browse/CX-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2448): fix skip ahead link

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate.tsx
This PR resolves [CX-2443]
Update price estimate CTA copy and adjusts the margin.
| --- | --- |
|![simulator_screenshot_CC534BE7-B4C7-4AD5-8F4B-504F49EC064A](https://user-images.githubusercontent.com/4691889/159296793-04f5df0c-e8e8-42d5-b4c6-dcf7e8df02e2.png) |  ![simulator_screenshot_CBB888C2-84D4-4955-BE88-EB4C036072F4](https://user-images.githubusercontent.com/4691889/159296711-7ac8679e-3ec0-4a63-b97b-f9fc3d494aeb.png)|
-
-
-
-
</details>
[CX-2443]: https://artsyproduct.atlassian.net/browse/CX-2443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Update price estimate CTA copy

src/app/Components/ArtworkGrids/ArtworkGridItem.tsx, src/app/Scenes/Artwork/Components/CommercialInformation.tsx, src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx, src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tests.tsx, src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tsx
This PR resolves [NX-3091]
Change "Price on Request" to "Price on request" on the artwork page and in the search results. Only CTA texts should use title case.
-
-
-
-
</details>
[NX-3091]: https://artsyproduct.atlassian.net/browse/NX-3091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(NX-3091): Make Price on Request sentence case

src/app/utils/AdminMenu.tsx
#nochangelog
-
-
-
-
</details>
=> remove the admin menu storybook link until its back working

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx
After upgrading React Native the issues show up as an error instead of a warning (see https://github.com/artsy/eigen/pull/6461).
This PR removes the `FlatList` component inside of `LocationInput` and fixes a few small issues:
- "Please try searching again with a different spelling." message shows up now.
- `powered_by_google` always stays below the suggestion list.
**Before:**
https://user-images.githubusercontent.com/4691889/159454183-78b889f6-64ad-45e2-9bee-1106d9330bc3.mp4
**After:**
https://user-images.githubusercontent.com/4691889/159453716-3ef1b189-2181-4bf4-a9e8-e2051ec5056f.mp4
-
-
-
- Fix submission location input nested scroll view issue - ole
</details>
=> fix: submission location input nested scroll view issues

app.json
-
-
- Increase app version to 7.3.3
</details>
=> chore: Increase app version to 7.3.3

.secrets.baseline, src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx, src/app/Scenes/MyCollection/mutations/myCollectionCreateArtwork.ts, src/app/Scenes/MyCollection/mutations/myCollectionUpdateArtwork.ts, src/app/Scenes/MyCollection/utils/randomMyCollectionArtwork.ts, src/app/utils/artworkRarityClassifications.ts
This PR resolves [CX-953]
This PR
- sets import source when creating My Collection artworks to `MY_Collection`
- renames `myCollectionAddArtworkMutation` to `myCollectionCreateArtworkMutation` 
- renames `myCollectionEditArtworkMutation` to `myCollectionUpdateArtworkMutation` 
to align with conventions and the name of the mutations: `myCollectionCreateArtwork` & `myCollectionUpdateArtwork`.
- Set import source when creating My Collection artworks - ole
-
-
-
</details>
[CX-953]: https://artsyproduct.atlassian.net/browse/CX-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Set import source when creating My Collection artworks + refactoring

package.json, src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx, src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx, src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx, src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx, src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx, yarn.lock
This PR resolves [CX-2457]
Added correct events to the SWA banner on MC Artwork page
-
-
-
- Added correct events to the SWA banner on MC Artwork page -daria
</details>
[CX-2457]: https://artsyproduct.atlassian.net/browse/CX-2457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2457): added correct events to the SWA banner on MC Artwork page

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/State/SubmissionModel.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/calculatePhotoSize.tests.ts, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/calculatePhotoSize.ts, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/validation.ts, src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx, src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts, src/app/store/migration.tests.ts, src/app/store/migration.ts, src/palette/elements/PhotoRow/PhotoRow.tsx
This PR resolves [CX-2418]
Initialize images when submitting My Collection artworks with the following approach:
1. Save the image URLs of the MC artwork in `initialPhotos` inside the `ArtworkSubmissionModel`,
2. Add the photos later in `UploadPhotosForm` using the URLs from `initialPhotos`.
https://user-images.githubusercontent.com/4691889/159454748-0838e3df-14d7-4e84-a13b-f2bf059c6635.mp4
- Initialize images when submitting My Collection artworks - ole
-
-
-
</details>
[CX-2418]: https://artsyproduct.atlassian.net/browse/CX-2418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Initialize images when submitting My Collection artworks

README.md
=> docs: link to rfc

patches/react-native+0.66.4.patch
patch React Native `find-node.sh` using the latest version before it was removed in https://github.com/facebook/react-native/pull/33146.
-
-
-
-
</details>
=> chore: patch React Native find-node.sh

src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
This PR resolves [CX-2460]
- Fixes Show Only Submitted Artwork Filter not showing any artwork when selected
https://user-images.githubusercontent.com/18648835/159950527-cfcb1f91-34f8-43b4-9398-10cae7c2c71b.mp4
- Fix Show Only Submitted Artwork Filter Bug - kizito
-
-
-
</details>
[CX-2460]: https://artsyproduct.atlassian.net/browse/CX-2460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2460): Fix Show Only Submitted Artwork Filter Bug

src/app/Scenes/MyCollection/MyCollection.tsx, src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
This PR resolves [2433]
- When an artwork is added to MyCollection, the artist does not show in the MyCollection Filters. This is because the filters were initialized with previous artworks and are not updated. This PR fixes that.
https://user-images.githubusercontent.com/18648835/159748677-b1b703ed-ad5a-4d3b-91e3-903f481ed6cb.mp4
- Fix Newly added MyCollection Artwork's artist not showing in Filters - kizito
-
-
-
</details>
=> fix(CX-2433): Fix Newly added MyCollection Artwork's artist not showing in Filters

src/palette/elements/Text/Text.tsx
I dont know how we missed that, but since #6350 we had been missing underlines. the `style` was much higher that it needed to be in that array, now its fixed.
Notice the
- terms of service
- privacy policy
- sign up
<table>
<tr>
<td>before
<td>after
<tr>
<td>
<td>
</table>
-
-
-
-
</details>
=> fix: text underlines

.secrets.baseline, src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
This PR resolves [CX-2435]
- Fix artwork dimensions not updated after mutation inside my collection artwork v3
**Before**
https://user-images.githubusercontent.com/11945712/160362346-0736e93e-be3b-42d9-ad54-e8439d542f06.mov
**After**
https://user-images.githubusercontent.com/11945712/160362392-d8f3af2a-8412-4a54-8e74-7b2ae6824abf.mov
- artwork dimensions not updated after editing them - mounir
-
-
-
</details>
[CX-2435]: https://artsyproduct.atlassian.net/browse/CX-2435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: artwork dimensions not updated after mutation

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx, src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx, src/app/store/config/features.ts
- Hide comparable works behind feature flag
-
-
-
- Hide comparable works behind feature flag - mounir
</details>
=> chore: hide comparable works behind feature flag

src/app/utils/experiments/UnleashProvider.tsx
@gkartalis found out that release versions only could connect to prod unleash. now fixed. thank you!
-
-
-
-
</details>
=> fix: unleash working right on beta and release

src/app/Scenes/Home/Home.tests.tsx, src/app/Scenes/Home/Home.tsx, src/app/utils/experiments.ts
This PR resolves [CX-2447]
Remove old recommendations ("New Works for You" & "Artist Recommendations") from the home feed.
-
-
-
- Remove old recommendations from home feed - ole
</details>
[CX-2447]: https://artsyproduct.atlassian.net/browse/CX-2447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove old recommendations from home feed

package.json, yarn.lock
Bumps @testing-library/react-native version
👀 see what's changed [here](https://github.com/callstack/react-native-testing-library/releases/tag/v9.1.0)
-
-
-
- bump @testing-library/react-native version - gkartalis
</details>
=> chore(deps): bump rntl version to 9.1.0

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggest.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggestResults.tsx
This PR resolves [SWA-324]
This PR fixes 2 things on the artist auto-suggest input in submission:
- the error message that does not disappear
- the virtualised list error 
https://user-images.githubusercontent.com/42584148/160437269-c72c5acf-9941-4b69-ba75-b76f43df2fec.mp4
The changes apply to all users. 
-
-
-
</details>
[SWA-324]: https://artsyproduct.atlassian.net/browse/SWA-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: erase bug and virtualised list err

package.json, src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tests.tsx, src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx, src/app/Scenes/Home/Home.tsx, src/app/store/config/features.ts, yarn.lock
This PR resolves [CX-2372]
Adds Artwork recommendations home screen rail with enabled Echo feature flag.
| | |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-03-29 at 10 07 42](https://user-images.githubusercontent.com/4691889/160565466-f2907f94-bc72-4d64-b117-0cf051c5190d.png) | ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-03-29 at 10 07 46](https://user-images.githubusercontent.com/4691889/160565476-2e1d9216-89d9-4ce8-bbb5-7bdba5f951ab.png) |
- New Artwork recommendations home screen rail - ole
-
-
-
</details>
[CX-2372]: https://artsyproduct.atlassian.net/browse/CX-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Artwork recommendations home screen rail

src/app/Scenes/Home/Home.tsx
This PR resolves [CX-2470]
Move Artist Recommendations home screen rail below Market News.
- Move Artist Recommendations home screen rail below Market News - ole
-
-
-
</details>
[CX-2470]: https://artsyproduct.atlassian.net/browse/CX-2470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Move Artist Recommendations home screen rail below Market News

src/app/utils/LocalImageStore.tests.ts
Fixing broken tests from the previous PR :( 
#nochangelog
=> fix broken tests

docs/overview.md
Just fixing a link in the docs!
=> docs: Fix link [ci skip]

src/app/Scenes/Search/Search.tsx, src/app/Scenes/Search/SearchResults.tsx, src/app/Scenes/Search/components/AlgoliaSearchResults.tsx, src/app/Scenes/Search/constants.ts
A small refractor to improve the readability of the code for `Search` component
-
-
-
- Split search results from Search component - dimatretyak
</details>
=> refactor: Search results container

src/app/Scenes/Home/Home.tsx, src/app/store/config/features.ts
This PR removes the following unused/old feature flags that are not used anymore because the features have been released a long time ago:
- ARDisableReactNativeBidFlow (not used)
- AREnableNewPartnerView (not used)
- AREnableViewingRooms (released long ago)
- ARHomeAuctionResultsByFollowedArtists (released long ago
- AREnableArtistRecommendations (not used)
-
-
-
- Remove unused feature flags - ole
</details>
=> chore: Remove unused feature flags

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
This PR resolves [CX-2478]
Adjust My Collection artwork high demand logic.
- Adjust My Collection artwork high demand logic - ole
-
-
-
</details>
[CX-2478]: https://artsyproduct.atlassian.net/browse/CX-2478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Adjust My Collection artwork high demand logic

src/app/utils/AdminMenu.tsx, src/app/utils/experiments/UnleashProvider.tsx, src/app/utils/experiments/hooks.ts
Add Unleash display in admin menu 
-
-
-
- add unleash environment display on admin menu - gkartalis
</details>
=> feat: Add unleash env display on admin menu

src/app/store/config/features.ts
This PR resolves [CX-2477]
Hide Estimate Range section on MC artwork screen.
-
-
-
-
</details>
[CX-2477]: https://artsyproduct.atlassian.net/browse/CX-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Hide Estimate Range section on MC artwork screen

app.json
**Description:**
This PR prepares for the 7.3.4 dev.
Note: 7.3.3 is still in review
@brainbicycle I would appreciate if you create a new version in ASC once the version in review is approved 🙇‍♂️
#nochangelog
=> chore: prepare for 7.3.4

Podfile.lock, package.json, yarn.lock
After https://github.com/artsy/eigen/pull/6546 noticed that I was getting podfile diffs with RNSplit.
Removing the split npm package makes the diffs go away 
-
-
-
-
</details>
=> chore: remove split.io package remains 

src/app/Scenes/Inbox/Components/Conversations/MakeOfferModal.tests.tsx, src/app/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
This PR resolves [NX-3052]
- Remove text “Make sure the artwork below matches the intended work...”
- Remove text “Making an offer doesn’t guarantee you the work...”
- Change the title to “Select edition set”
|Before|After|
|---|---|
|<img alt="Screenshot 2022-03-31 at 11 45 30" src="https://user-images.githubusercontent.com/265560/161030767-269db9ef-469d-4aca-9046-6fe4451ad834.png">|<img alt="Screenshot 2022-03-31 at 11 56 11" src="https://user-images.githubusercontent.com/265560/161031152-799b6a2c-e3ed-4b77-af8b-d6f64468d624.png">|
- Modify the UI of the edition selection modal on Make Offer on Inquiry - LeandroL
-
-
-
</details>
[NX-3052]: …
=> feat(NX-3052): Modify the UI of the edition selection modal

docs/pull_request_template.md
After some chat with the moplat team, and seeing a lot of past PRs, I'm trying to simplify this template.
I saw a lot of PRs with either all of them checked, or none checked. The idea here is to maybe have a "true representation". What does this PR have? Does it have a feature flag or not? Does it have tests or not? etc. We dont expect all PRs to have migrations for example, but we expect that if a PR has a flag, the checkbox would be checked. Filling this in should be quick and easy and clear. (Maybe in the future we will have some script doing this for us. Not yet though.)
I have simplified the checkboxes, and removed some. Maybe we can remove more?
I have not changed the changelog part of this template, until we work on the changelog scripts, but I think we can …
=> docs: suggestion for update PR template

src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
This PR resolves [FX-3836]
The feature is behind an unleash feature flag named [eigen-enabled-price-histogram](https://unleash.artsy.net/projects/default/features2/eigen-enable-price-histogram).
No extra implementation was needed, the histogram functionality was already in place, we just added it to the artist series price filter. 
It is under the existing price histogram feature flag.
https://user-images.githubusercontent.com/1684673/162018828-0765e080-acf0-4cf1-af60-8e7da15ee245.mp4
- adds histogram on Artist Series price filter screen - rumyantseva 
-
-
-
</details>
[FX-3836]: https://artsyproduct.atlassian.net/browse/FX-3836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-3836): add histogram on Artist Series price filter screen

src/app/Components/ArtworkFilter/useArtworkFilters.ts, src/app/Scenes/Sale/Components/SaleLotsList.tsx, src/app/Scenes/Sale/Sale.tsx
The type of this PR is: **Bugfix/Enhancement**
Similar PR: #6534 
At the moment, refetch logic doesn't work correctly and for this reason the user cannot get up-to-date info about auction on Sale screen using Pull-to-refresh pattern. This PR includes fixes and improvements for it. 
* getting up-to-date info about auction ([above query](https://github.com/artsy/eigen/blob/1ab3429053e97c0ca20d72bdfa2536baf74f19a2/src/app/Scenes/Sale/Sale.tsx#L384-L387))
* getting up-to-date info about sale artworks ([below query](https://github.com/artsy/eigen/blob/1ab3429053e97c0ca20d72bdfa2536baf74f19a2/src/app/Scenes/Sale/Sale.tsx#L388-L405)), taking into account the selected and applied filters
-
-
-
- Update refetch logic for Sale screen - dimatretyak …
=> fix: update refetch logic for Sale screen

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/162482690-95d222cc-656f-4cad-91bf-eea65fbe4319.png"></td>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/162482722-98e48095-ea3e-41e1-b38a-13bfa40b3702.png"></td>
</tr>
</table>
- fix RequestPriceEstimate Button padding issue on iphone minis - kizito
-
-
-
</details>
=> fix(RequestPriceEstimate Button): padding issue on iphone minis

src/app/Components/LoadFailureView.tsx, src/app/store/config/features.ts
Adds a dev toggle to show error messages within the failure view outside of the dev environment.
-
-
-
- Adds a dev toggle to show error messages within the failure view outside of the dev environment. - ole
</details>
=> feat: Add dev toggle to show error message in failure view

src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tests.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/createOrUpdateSubmission.ts, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/testUtils.ts, src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/validation.ts, src/app/store/migration.tests.ts, src/app/store/migration.ts, src/app/utils/googleMaps.ts
https://user-images.githubusercontent.com/36475005/162452374-aebd680e-4cc0-4c39-b2c7-8cdf9ac64d6f.mov
This PR resolves [SWA-291]
-
-
-
-
</details>
[SWA-291]: https://artsyproduct.atlassian.net/browse/SWA-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat[SWA-291]: zip code field

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
This PR resolves [CX-2481]
Adjust demand rank text.
```
0 - 3.9 -> Less Active Demand
4 - 6.9 -> Moderate demand
7 - 8.9 -> Active Demand
9 and higher -> High demand
```
- Adjust demand rank text - ole
-
-
-
</details>
[CX-2481]: https://artsyproduct.atlassian.net/browse/CX-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Adjust demand rank text

src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx, src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx, src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx, src/app/store/config/features.ts
- Rename my collection demand index ff
Blocked by https://github.com/artsy/echo/pull/234
-
-
-
- rename my collection demand index ff - mounir
</details>
=> chore: rename my collection demand index ff

docs/pull_request_template.md
Some more small changes to the formatting:
=> Update pull_request_template.md v2

src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tests.tsx, src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx, src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tests.tsx, src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
This PR is a follow up on #6376 to add tests for the High Demand logic
-
-
-
- add tests to high demand icon logic - mrsltun
</details>
=> fix: Add tests for High Demand logic

src/app/Components/FancyModal/FancyModal.tsx, src/app/Scenes/Sale/Components/SaleHeader.tsx, src/app/store/config/features.ts
- Add share auction button
https://user-images.githubusercontent.com/11945712/162436369-7de74270-0444-41e0-b1ea-61e2931dfc04.mov
- Add share button to the sale screen - mounir
-
-
-
</details>
=> feat: add share auction button

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx, src/palette/elements/Input/Input.stories.tsx, src/palette/elements/Input/Input.tests.tsx, src/palette/elements/Input/Input.tsx
This PR resolves [FX-3888]
🍐 paired with @rumyantseva on this
- fixed flakiness of input button on priceRangeFilter screen
- add fixedRightPlaceholder on palette input component
- added some stories for 👆
- added some tests for 👆
|Screenshots|||
|---|---|---|
|![inputstories](https://user-images.githubusercontent.com/21178754/163363483-e1086484-6aa6-4d48-bb64-4462f1769e96.jpg)|![simulator_screenshot_3186A674-8871-4214-B3E6-B3354B7E47CC](https://user-images.githubusercontent.com/21178754/163363650-14dda704-f06a-47ad-b4cd-8614514d0937.png)|![simulator_screenshot_EE1C9494-4E60-4E69-AB98-94C378661ADB](https://user-images.githubusercontent.com/21178754/163363699-62fe2491-815b-40c5-bbd3-bd97cb1cc6d2.png)|
- fixed input flakiness and add fixed right …
=> feat(FX-3888): Price filter design refinements

src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tsx
This PR resolves [FX-3887]
- use `description` and `descriptionColor` props of palette Input instead of <Text>
- change color of description from `black100` to `black60`
- use `fixedRightPlaceholder` palette Input prop instead of `placeholder`
|Android|iOS|
|---|---|
|![Screenshot_1649949770](https://user-images.githubusercontent.com/21178754/163422031-edf57137-0381-435b-b9c0-288af799f7c5.png)|![Untitled](https://user-images.githubusercontent.com/21178754/163421533-dfa43fde-4a93-44d0-b6d9-b958568787fa.jpg)|
- size filter input refinements - gkartalis
-
-
-
</details> …
=> chore(FX-3887): size filter design refinements

src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
This PR resolves [FX-3896]
* Navigate to artist screen
* Tap on Create Alert button in Artworks tab.
* Tap on Create Alert at bottom left side of Sort & Filter screen.
* Tap on Name text field
* Minimize the keyboard by clicking down arrow key in keyboard.
* To save the alert, we need to tap "Save Alert" button twice
https://user-images.githubusercontent.com/3513494/163444830-5d909e78-a288-46ad-b9fd-3c745ebf8689.mp4
https://user-images.githubusercontent.com/3513494/163444938-73883bb1-4672-4e92-9482-b8aac2d4f7ff.mp4
-
-
-
- Fix problem when need to click "Save Alert" button twice - dimatretyak
</details>
[feature …
=> fix(FX-3896): problem when need to click "Save Alert" button twice

src/app/Scenes/ViewingRoom/ViewingRoom.tsx
This PR resolves [FX-3816]
* Open the Artsy app
* Scroll down until the Viewing Rooms tab
* Choose any room
* Tap on the share icon upper right corner
* Choose WhatsApp to share
* Choose the contact to share
It displays the room title and link of the room.
It displays the room title but the link of the room is not.
https://user-images.githubusercontent.com/3513494/163456259-efd4d374-d5d3-495a-b0e1-56ee8187ec55.mp4
-
-
-
- Share link for Viewing Rooms - dimatretyak
</details>
[FX-3816]: …
=> fix(FX-3816): Share link for Viewing Rooms

.circleci/config.yml
This reverts commit 8b8f2b1c1d106b7cafaba7a6e1099cedd116030d.
Unfortunately we can't remove these as is, the bundled js is created as a side effect of these jobs. That probably shouldn't be the case we can separate out that step from these jobs and remove the tests. Reverting until we do so we can get betas working again. 
- 
-
-
- Revert removing test js step from betas, to get bundled js working again - Brian
</details>
=> fix: revert "chore: disable build-test-js on beta builds (#6598)" #trivial

src/palette/elements/Input/Input.stories.tsx
- removed some non-essential styles
- Added withScreenDimensions decorator that fixes the previous error that this story was having and as a result storybook was crashing with error:
|iOS|Android|
|---|---|
|![simulator_screenshot_71FD807E-ECD5-4936-AD9A-3F93F5B00F5E](https://user-images.githubusercontent.com/21178754/164031767-3760057e-f032-4742-b285-f3f92f0cc0a3.png)|![Screenshot_1650380123](https://user-images.githubusercontent.com/21178754/164033287-1a3ce37b-1f4a-42fd-a77e-e1fd0484b571.png)|
-
-
-
- fix broken phone input story - gkartalis
</details>
[docs]: …
=> fix: add decorator to phone input story

src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts, src/app/store/config/features.ts
This PR resolves [CX-2521]
Remove AREnableShowOnlySubmittedMyCollectionArtworkFilter feature flag.
-
-
-
-
</details>
[CX-2521]: https://artsyproduct.atlassian.net/browse/CX-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove AREnableShowOnlySubmittedMyCollectionArtworkFilter feature flag

src/app/Scenes/Sale/Components/SaleActiveBids.tsx
This PR resolves [FX-3892]
1. Go to Artsy app and log in
2. Scroll to Auctions section and choose any auction which is 'Timed auction'
3. Click on Sort and Filter
4. Choose Price/Estimate Range
5. Choose different price ranges from the list and click Show Results. After any change of the price range, the application will get stuck.
https://user-images.githubusercontent.com/3513494/163838034-bf5ad132-7895-4213-91b5-6a855888bc0a.mp4
https://user-images.githubusercontent.com/3513494/163838058-e17336e4-811f-4b9f-8673-54c728ab221b.mp4
https://user-images.githubusercontent.com/3513494/163838821-cda74e99-3776-466d-9e78-95e6a64099f6.mp4
-
-
-
- Fix app freezes on Sale page when filters are changed - dimatretyak
</details> …
=> fix(FX-3892): App freezes on Sale page when filters are changed

src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx, src/app/Components/Bidding/Screens/Registration.tests.tsx, src/app/Components/Modal.tests.tsx, src/app/Components/Modal.tsx, src/app/Scenes/Artwork/Components/RequestConditionReport.tsx, src/app/utils/renderMarkdown.tsx
This PR resolves [FX-3902]
1. Launch the app
2. Swipe Auctions carousel
3. Tap any auction
4. Tap any lot
5. Scroll down and tap Request condition report
6. Under `For questions contact` tap  on the provided  email
Contact email is hyperlinked
Contact email is not hyperlinked
https://user-images.githubusercontent.com/3513494/164019646-ab850486-6b06-4840-921b-b945693c4489.mp4
https://user-images.githubusercontent.com/3513494/164019623-a2cce107-08a5-4bc7-91c3-fe987ac2189e.mp4
- Fix contact email is not hyperlinked  in Request condition report modal - dimatretyak
-
-
-
</details> …
=> fix(FX-3902): Contact email is not hyperlinked  in Request condition report modal

src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
This PR resolves [CX-2501]
Fixes sort by price (low or high) on MyCollection local filter
- Fix sort by price my collection filter - kizito
-
-
-
</details>
[CX-2501]: https://artsyproduct.atlassian.net/browse/CX-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(cx-2501): Fix sort by price my collection filter

src/app/Scenes/MyCollection/MyCollection.tsx, src/app/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tsx, src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts, src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkSubmitted.tsx, src/app/store/config/features.ts
This PR resolves [CX-2523]
Remove ARShowConsignmentsInMyCollection feature flag.
-
-
-
-
</details>
[CX-2523]: https://artsyproduct.atlassian.net/browse/CX-2523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove ARShowConsignmentsInMyCollection feature flag

src/app/store/config/features.ts
This PR resolves [SWA-343]
This PR removes the feature flag (AREnableAccordionNavigationOnSubmitArtwork) used in the development and release process of the new submission flow. 
-
-
-
Changes affect the devs only. 
</details>
[SWA-343]: https://artsyproduct.atlassian.net/browse/SWA-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(SWA-343): Remove ff AREnableAccordionNavigationOnSubmitArtwork

src/app/Components/Bidding/Components/Timer.tests.tsx, src/app/Components/Bidding/Components/Timer.tsx, src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx, src/app/Scenes/Artwork/Components/CommercialInformation.tsx, src/app/store/config/features.ts
Follow-up for [BX-210](https://artsyproduct.atlassian.net/browse/BID-210)
Updating the feature flag to "Enable" instead of "Disable" to better match current conventions for feature flagging.
Blocked by: https://github.com/artsy/echo/pull/243
-
-
-
-
</details>
=> chore: Change cascading end time feature flag from disable to enable

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
This PR resolves [CX-2496]
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/164409802-498b8e37-cb45-4325-b02e-d538e063d5a8.png"></td>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/164409785-24f6e69a-868b-4e34-b282-4800cd5b4acc.png"></td>
</tr>
</table>
- Fix Materials and Medium interchanged - kizito
-
-
-
</details>
[CX-2496]: https://artsyproduct.atlassian.net/browse/CX-2496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> fix(CX-2496): Materials and Medium interchanged

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
This PR resolves [FX-3888]
- Adjusted the margins after a discussion with design
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 13 - 2022-04-21 at 17 55 09](https://user-images.githubusercontent.com/21178754/164503403-4f01dedf-30dc-45cb-b00a-e3f19ad2e947.png)|![Simulator Screen Shot - iPhone 13 - 2022-04-21 at 17 56 13](https://user-images.githubusercontent.com/21178754/164503388-69f508ec-74a1-4a2a-818a-35ae7f0bd34c.png)|
|![Simulator Screen Shot - iPhone 13 - 2022-04-21 at 17 54 37](https://user-images.githubusercontent.com/21178754/164503399-1da3d233-a903-4db2-bba9-6368b467e3bf.png)|![Simulator Screen Shot - iPhone 13 - 2022-04-21 at 17 54 15](https://user-images.githubusercontent.com/21178754/164503397-990de143-88d2-4d89-a993-dbede1a8179f.png)| …
=> fix: adjust margins in price filter

src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
This PR resolves [BX-201](https://artsyproduct.atlassian.net/browse/BID-353)
Add negative left and right padding to casacding end time banner to it's full bleed.
(I forgot to push this up in my last PR)
Before:
After:
-
-
-
-
</details>
=> Fix (BX-201): Fix padding on cascading end times banner on lot page

Podfile.lock, src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx, src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx, src/app/store/config/features.ts
This PR resolves [CX-2506]
- Create my collection Insights feature flag and add an empty Insights Tab.
- add insights tab inside my collection - mounir
-
-
- Add collection insights feature flag - mounir
</details>
[CX-2506]: https://artsyproduct.atlassian.net/browse/CX-2506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add my collection insights feature flag

src/app/Scenes/MyProfile/MyProfileEditForm.tsx, src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx, src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx, src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx, src/app/store/config/features.ts
This PR resolves [CX-2524]
Clean up feature flag AREnableCollectorProfile
-
-
-
- clean up feature flag AREnableCollectorProfile -daria
</details>
[CX-2524]: https://artsyproduct.atlassian.net/browse/CX-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(CX-2524): clean up feature flag AREnableCollectorProfile

src/palette/elements/Button/CTAButton.tsx
This PR resolves [SWA-325]
This PR removes maxWidth limitation from CTAButton, since this button is a block element and having maxWidth limits it from being centralised. 
The changes would be reflected on both platforms for users going through sell with artsy flow. 
-
-
-
</details>
[SWA-325]: https://artsyproduct.atlassian.net/browse/SWA-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(SWA-325): remove maxwidth from cta button

package.json
Having only eloy there feels strange at this point. Pointing this to docs/thanks.md feels a bit nicer?
#nochangelog
-
-
-
-
</details>
=> docs: update author to point to thanks.md

src/app/Scenes/MyProfile/MyProfileHeader.tsx, src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
This PR resolves [CX-2542]
This PR fixes an issue where the profile header was not correctly updated when the icon was changed. I moved the header component in it's own file and added a `useFragment` hook to the component instead of just passing the data via props.
- Fix "Complete Profile" message update issue - ole
-
-
-
</details>
[CX-2542]: https://artsyproduct.atlassian.net/browse/CX-2542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Let Profile header update on Relay data change

src/app/Scenes/MyCollection/MyCollectionArtworks.tsx, src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
This PR resolves [CX-2499]
The rarity filter did not work - always showed zero results. TH problem was in different attribution class string value formatting and in the missing prop in MyCollectionFilterPropsFragment
https://user-images.githubusercontent.com/36167539/165472170-841387e2-b008-4432-8f6d-9fcc4b7ee1c9.mp4
- Fixed rarity filter in MyCollection
-
-
-
</details>
[CX-2499]: https://artsyproduct.atlassian.net/browse/CX-2499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2499): fixed rarity filter in MyCollection

src/app/Scenes/Sale/SaleHeader.tests.tsx
Fixes failing sale header test. Not sure if this is expected behavior but now that the flag is enabled by default it seems this is not rendering the auction closed message.
-
-
-
- Fix failing sale header test - Brian
</details>
=> fix: inject feature flag in sale header test

app.json
Set app version to 7.3.6 to prepare for app dev
-
-
-
- set app version to 7.3.6 - mounir
</details>
=> chore: set app version to 7.3.6

src/app/utils/AdminMenu.tsx
Update the check in admin screen to allow customizing environment in beta.
-
-
-
- Allow customizing env in beta - Brian
</details>
=> feat: allow customizing environment in beta #trivial

scripts/install
conform with new package name.
This PR resolves [a package name change from brew]
-
-
-
-
</details>
=> fix(package install): package name update

fastlane/metadata/en-US/keywords.txt
Update App Store keywords. 
- update keywords - Brian
-
-
-
</details>
=> chore: update keywords #trivial

docs/deploy_to_play_store.md
The type of this PR is: Documentation
-
-
-
-
</details>
=> docs: Deploy to playstore

docs/best_practices.md
=> docs: Update best_practices.md

android/app/src/main/java/net/artsy/app/MainApplication.java, android/app/src/main/res/values/braze.xml
Adds back manual token registration and updates key values because tokens were not being registered in beta, hopefully this will fix it. Forgive squash on green 🙏 want to test in beta.
-
-
-
-
</details>
=> fix: add back manual token registration and new keys #trivial

src/app/Scenes/MyProfile/MyProfileHeader.tsx, src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
collector profile message typo introduced in https://artsyproduct.atlassian.net/browse/CX-2473
- fix collector profile message typo - ole
-
-
-
</details>
=> fix: collector profile message typo

.secrets.baseline, src/app/Components/FancyModal/FancyModalHeader.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx, src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx, src/app/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx, src/app/Scenes/Search/AutosuggestResults.tsx, src/app/store/config/features.ts
This PR resolves [CX-2414]
Introduces My Collection artwork upload with custom artists behind a feature flag. A custom artist name can be specified if the user skips the artist selection.
https://user-images.githubusercontent.com/4691889/166892632-e6ee9f76-1e5a-4844-aad3-deac36d2f77c.mp4
- My Collection artwork upload with custom artists - ole
-
-
-
</details>
[CX-2414]: https://artsyproduct.atlassian.net/browse/CX-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2528): My Collection artwork upload with custom artist

src/app/Scenes/Home/Home.tsx
Remove unused `followedArtistsArtworkModule` from the home screen query. The fragment probably wasn't removed after an A/B test.
-
-
-
-
</details>
=> fix: Remove unused followedArtistsArtworkModule from home screen query

src/app/Components/SectionTitle.tsx
This PR resolves [CX-2554]
Changed the alignment of the "View all" link of the <SectionTitle/> component from 'center' to 'top'.
As discussed today with Dasha and Jonathan
// I thought it will be a touch more complicated 🗿 
|---|---|
| ![Simulator Screen Shot - iPhone 12 mini - 2022-05-06 at 14 24 35](https://user-images.githubusercontent.com/36167539/167133590-1d54e64f-c8d4-4254-b76f-72e8ad944234.png) |  ![Simulator Screen Shot - iPhone 12 mini - 2022-05-06 at 14 24 15](https://user-images.githubusercontent.com/36167539/167133527-1a1cdee0-76f0-4c42-a3bf-53de224d8560.png)
|
- Changed the alignment of the "View all" link of the <SectionTitle/> component from 'center' to 'top' -daria
-
-
-
</details> …
=> fix(CX-2554): Fix alignment of the "View all" link of the <SectionTitle/> component

EXAMPLES.md, src/app/Scenes/Onboarding/OnboardingSocialPick.tsx, src/app/Scenes/Onboarding/OnboardingWelcome.tsx, src/palette/organisms/screenStructure/Screen.stories.tsx, src/palette/organisms/screenStructure/Screen.tsx
This PR resolves the blockers from https://www.notion.so/artsy/2022-05-06-Mobile-App-QA-version-7-3-6-iOS-build-2022-5-6-6-Android-build-431-c53039f25bf349358a57639b58bda0a2
Both issues fixed. Basically with no safe area, there is no spacer. I added a component that will add a spacer if there is no safe area, and null if there is safe area. That way things look right on all devices.
-
-
-
-
</details>
=> fix: Screen layout bugs

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
This PR resolves [FX-3812]
In some smaller screen phone resolutions the price on the artwork rail was truncated. This pr fixes this issue.
More info on the [jira ticket](https://artsyproduct.atlassian.net/browse/FX-3812) 
|Before||
|---|---|
|![Screenshot_1652099409](https://user-images.githubusercontent.com/21178754/167411206-0bf67974-e1ed-44c6-b60e-e7ce0c85605f.png)|![Screenshot_1652099405](https://user-images.githubusercontent.com/21178754/167411211-58f0c801-0196-46a5-99a7-5b4d66a5df65.png)|
|After||
|![Screenshot_1652099416](https://user-images.githubusercontent.com/21178754/167411201-a2da1c34-7695-4e1d-a9c3-3d8b091a17d0.png)|![Screenshot_1652099424](https://user-images.githubusercontent.com/21178754/167411180-5c93abaf-4c59-43c3-a90b-e60e1211766e.png)|
|Before|||
|---|---|---| …
=> fix: artworkrail truncated price

src/app/Components/Toast/Toast.tests.tsx, src/app/Components/Toast/ToastComponent.tsx, src/app/Components/Toast/types.ts, src/app/Scenes/Inbox/Components/Conversations/Messages.tsx, src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateScreen.tsx
This PR resolves [CX-2556]
- This PR standardizes the duration used by Toasts, providing `enum ToastDuration { Short = 2500, Long = 5000 }`
- Toast duration after Submission of Request Price Estimate changed to Long duration
- Standardize Toast Duration and Make RequestPriceEstimate Toast duration long - kizito
-
-
-
</details>
[CX-2556]: https://artsyproduct.atlassian.net/browse/CX-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Enhancement(CX-2556): Standardize Toast Duration and Make RequestPriceEstimate Toast duration long
