src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
src/app/Scenes/Artwork/Components/BelowTheFoldPlaceholder.tsx
src/app/Scenes/Artwork/helpers.ts

This PR resolves [FX-3953]
Reduce the size of Artwork Screen in preparation for the [FX-3953](https://artsyproduct.atlassian.net/browse/FX-3953)
- Moved helper functions to helpers.ts file 
- Moved placeholder components to their own files 
-
-
-
- small refactor on Artwork Screen - gkartalis
</details>
[FX-3953]: https://artsyproduct.atlassian.net/browse/FX-3953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: small refactor on artwork scene

---

src/app/Components/NotFoundFailureView.tsx
src/app/Components/RetryErrorBoundary.tsx
src/app/utils/renderWithPlaceholder.tsx

This PR resolves [CX-2516]
This PR adds the "Not found" screen as a fallback to all screens that use `AboveTheFoldQueryRenderer`. So also the Artwork screen will show the "Not found" screen if the status code of the response error is `404`.
| dev | prod |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-10 at 15 13 48](https://user-images.githubusercontent.com/4691889/167662413-af9b344f-0a54-4451-9025-ca23da82dbb2.png)| ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-10 at 15 14 28](https://user-images.githubusercontent.com/4691889/167662370-b72967d5-3707-4fe5-8b08-cc9563f48454.png)|
- Show Not Found screen for missing artworks -ole
-
-
-
</details>
Need help with something? Have a look on our [docs], or get in touch …

fix: Show Not Found screen for missing artworks

---

app.json
fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/release_notes.txt

prep for next release

---

docs/best_practices.md

This PR resolves N/A
Making sure this is mentioned in a `.md` doc somewhere!
- ~[ ] I tested my changes on **iOS** / **Android**.~
- ~[ ] I added screenshots or videos to illustrate my changes.~
- ~[ ] I added Tests and Stories for my changes.~
- ~[ ] I added an [app state migration].~
- ~[ ] I hid my changes behind a [feature flag].~
#nochangelog
</details>

docs: Note flushPromiseQueue helper [ci skip]

---

Podfile.lock
package.json
src/app/utils/resizeImage.ts
yarn.lock

This PR adds the ability to resize/scale image 
-
-
-
- Add image resizer - dimatretyak
</details>

feat: resize image helper 

---

src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tsx
src/app/Components/LocationAutocomplete/LocationAutocomplete.tests.tsx
src/app/Components/LocationAutocomplete/LocationAutocomplete.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
src/app/Scenes/MyProfile/MyProfileEditForm.tsx
src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tests.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tests.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tsx

This PR resolves [MOPLAT-261]
-
-
-
-
</details>
[MOPLAT-261]: https://artsyproduct.atlassian.net/browse/MOPLAT-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(MOPLAT-261): Sentence case on placeholder

---

src/app/Scenes/Fair/Fair.tsx

* Mobile images should be 600 pixels in the smallest dimension
* Recommended average image size is 100 kB
* Use a quality setting of 85% or higher for JPEG images
* Uploaded images must be JPEG, PNG, WebP, GIF, BMP or TIFF format
```javascript
// Before resize
{
"width": 900,
"height": 900,
"size": 5083 // ~ 5kb
}
// After resize
{
"width": 600,
"height": 600,
"size": 3003 // ~ 3kb
}
```
```javascript
// Before resize
{
"width": 1600,
"height": 1200,
"size": 281044 // ~281kb
}
// After resize
{
"width": 800,
"height": 600,
"size": 72232 // ~72kb
}
```
```javascript
// Before resize
{
"width": 1080,
"height": 2160,
"size": 1184278 // ~1mb
}
// After resize
{
"width": 600,
"height": 1200,
"size": 70170 // ~70kb
}
```
```javascript
// Before resize
{
"width": 1440, …
```

feat: resize image for TinEye search

---

src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx

This PR resolves [CX-2558]
Change subtitle copy for the recent auction results section of Insights tab
|before|after|
|---|---|
| ![1](https://user-images.githubusercontent.com/36167539/168558092-42336095-5744-4db2-be9c-375a26ffdc1d.png) | ![2](https://user-images.githubusercontent.com/36167539/168558140-72f69187-fb62-4009-a619-13f285f2cc0e.png)|
-  Change copy -daria
-
-
-
</details>
[CX-2558]: https://artsyproduct.atlassian.net/browse/CX-2558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2558): Change subtitle copy

---

src/app/AppRegistry.tsx
src/app/Scenes/Fair/Fair.tsx
src/app/Scenes/ReverseSearchImageResults/ReverseSearchImageResultItem.tsx
src/app/Scenes/ReverseSearchImageResults/ReverseSearchImageResults.tsx
src/app/navigation/routes.tsx

Added a screen that displays TinEye search results. Don't pay attention to the design, as this screen is more intended for debug/development purposes and most likely this screen will be removed in the future
https://user-images.githubusercontent.com/3513494/168392211-3f2878dc-10dc-4d5e-ad3e-a988b4979b4c.mp4
-
-
-
- display TinEye search results - dimatretyak
</details>

chore: display TinEye search results

---

src/app/Components/LoadFailureView.tsx
src/app/Scenes/MyCollection/MyCollection.tsx

This PR resolves [CX-2582]
Align My Collection failure view.
| --- | --- |
|![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-16 at 11 28 10](https://user-images.githubusercontent.com/4691889/168562343-922dc31c-273b-40c4-bb1f-d60c5d413a04.png) | ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-16 at 11 27 35](https://user-images.githubusercontent.com/4691889/168562314-bc05f41d-691f-45e0-9e7d-dc5ed6d6874d.png)|
-  Align My Collection failure view - ole
-
-
-
</details>
[CX-2582]: …

fix: Align My Collection failure view

---

docs/pull_request_template.md

Noticed that the links in the pr template didn't work due to [relative links](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links) not working in pr templates.
> Note: the changes will be reflected on the template after merging this PR
https://www.loom.com/share/38b3469ff6ce4f3ba08ba7d0cc3273d7
-
-
-
-
</details>

docs: fix pull request template broken links [ci_skip]

---

src/app/Scenes/Sale/Components/SaleHeader.tsx

This PR resolves [CX-2562]
Fix share button positioning
|before|after|
|--|--|
|![Simulator Screen Shot - iPhone 12 mini - 2022-05-16 at 21 00 02](https://user-images.githubusercontent.com/36167539/168664787-65da0166-6fb6-4e7b-965c-c7c50d87ec76.png) |![Simulator Screen Shot - iPhone 12 mini - 2022-05-16 at 21 00 19](https://user-images.githubusercontent.com/36167539/168664848-476b03e0-68a9-495f-9891-ce710f77ccfa.png)|
- UI improvements (share button positioning) -daria
-
-
-
</details>
[CX-2562]: …

fix(CX-2562): fix share icon positioning

---

src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
src/app/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts
src/app/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.ts
src/app/Components/ArtworkFilter/SavedSearch/types.ts
src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
src/app/Scenes/SavedSearchAlert/pillExtractors.ts
src/app/Scenes/SavedSearchAlert/screens/CreateSavedSearchAlertScreen.tsx
src/app/Scenes/SavedSearchAlert/useSavedSearchPills.ts

Prepare changes for [FX-3954]
* Add `entry` field for `SavedSearchStore`
* Get artist pill from `entry`
* Add `extractArtistPills` helper
* Add `extractPillsFromCriteria` helper
- Create Alert button opens up modal pre-filled with relevant filters on artwork page - dimatretyak
-
-
- Small refactor for `SavedSearchStore` (stage №1) - dimatretyak
</details>
[FX-3954]: https://artsyproduct.atlassian.net/browse/FX-3954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: prepare SavedSearchStore for FX-3954

---

.circleci/config.yml

Adjust check-if-app-has-been-approved-for-release CircleCI command.
-
-
-
-
</details>

fix: Adjust check-if-app-has-been-approved-for-release CircleCI command

---

src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx

This PR resolves [CX-2572]
Adde market signal info modal.
I went for the modal that was used by SWA team as it fits the design better than others.
https://user-images.githubusercontent.com/36167539/169016323-f100ae64-8f34-4466-8e83-385bfe0158bf.mp4
- add new info modal -daria
-
-
-
</details>
[CX-2572]: https://artsyproduct.atlassian.net/browse/CX-2572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2572): add market signal info modal

---

src/app/Components/ArtworkGrids/LotCloseInfo.tsx
src/app/Components/Bidding/Components/Timer.tsx
src/app/Components/Countdown/Ticker.tests.tsx
src/app/Components/Countdown/Ticker.tsx
src/app/utils/saleTime.ts

This PR resolves [BID-369]
- Prefixes the timer on Lots with "Extended: " when popcorn has been activated
-
-
-
-
</details>
[BID-369]: https://artsyproduct.atlassian.net/browse/BID-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(BID-369): Prefix Extended to Bid label when popcorn has been activated

---

src/app/Scenes/MyCollection/MyCollection.tsx

This PR resolves [CX-2589]
Add the third tab to the MyC placeholder when MyC Insights FF is enabled
https://user-images.githubusercontent.com/36167539/169099325-692bd0f0-baa0-4d3f-b603-f91ec0286d90.mp4
- MyCollection placeholder improvements (related to my collection insights) -daria
-
-
-
</details>
[CX-2589]: https://artsyproduct.atlassian.net/browse/CX-2589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2589): add the third tab to the MyC placeholder

---

src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
src/app/Scenes/Sale/Components/SaleHeader.tsx
src/app/Scenes/Sale/Sale.tsx

This PR resolves [BID-379]
- Enhances the cascading banner to feature popcorn message
<table>
<tr>
<td>Image</td>
</tr>
<tr>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/169298266-47123001-a82a-481f-8659-6ece9181d314.png" width=40%""></td>
</tr>
</table>
-
-
-
-
</details>
[BID-379]: https://artsyproduct.atlassian.net/browse/BID-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(BID-379): Enhance Cascading banner to feature popcorn message

---

src/app/Scenes/Home/Components/SalesRail.tests.tsx
src/app/Scenes/Home/Components/SalesRail.tsx
src/app/Scenes/Sales/Components/SaleListItem.tests.tsx
src/app/Scenes/Sales/Components/SaleListItem.tsx
src/app/store/config/features.ts

This PR resolves [BID-213]
- This PR changes the subtitle on SalesRails and SaleListItem to use `formattedStartDateTime` when the proper feature flag is switched on
<p align="center"><img src="https://user-images.githubusercontent.com/18648835/169280317-f7b73010-8da8-4a58-85ba-06bfb1129505.png" width="45%" /></p>
- Sale Listings on Eigen show correct subtitle - kizito
-
-
-
</details>
[BID-213]: https://artsyproduct.atlassian.net/browse/BID-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …

feat(BID-213): Sale Listings on Eigen show correct subtitle

---

src/app/Components/LoadFailureView.tsx

Center Unable to Load screen
-
-
-
-
</details>

fix: Center Unable to Load screen again

---

src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx

This PR resolves [CX-2565]
|before|after|
|--|--|
|![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-20 at 14 00 21](https://user-images.githubusercontent.com/36167539/169523901-1851a85f-979d-40b9-9f28-8786e783b46e.png)|![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-20 at 13 59 56](https://user-images.githubusercontent.com/36167539/169523835-b0651d0f-dedb-46d6-a719-c41197962c10.png)| 
-
-
-
-
</details>
[CX-2565]: https://artsyproduct.atlassian.net/browse/CX-2565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …

fix(CX-2565): my collection insights empty state - ui fix

---

src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
src/app/store/config/features.ts

This PR resolves [CX-2594]
- Add my collection insights phases steps
Sorry for adding you all as reviewers, that's because we will be going step by step with the release, therefore I wanted you all to know about the feature flags we're going with and adjust your PRs according to that
**Note:** don't forgot to enable the feature flag after this PR gets merged
-
-
-
- add my collection insights phase 1 different steps - mounir
</details>
[CX-2594]: https://artsyproduct.atlassian.net/browse/CX-2594?atlOrigin=eyJ …

feat(CX-2594): add my collection insights phases steps

---

src/app/AndroidApp.tsx
src/app/AppRegistry.tsx
src/app/relay/usePurgeCacheOnAppUpdate.ts

- Context: https://artsy.slack.com/archives/C01B2P6LJUU/p1653042937308069
- Clears the Relay cache when a user moves from one version to another, thus keeping cache fresh across versions.
- 
-
-
-
- Clear relay cache when app is updated - kizito
</details>

chore: Clear relay cache when app is updated

---

src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx

This PR fixes a regression when the artwork inside a conversation is offerableFromInquiry the CTA is white when should be black.
- fix cta color inside a conversation - araujobarret
-
-
-
</details>

fix: make offer button color fix

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts

[Slack Thread](https://artsy.slack.com/archives/C01B2P6LJUU/p1652404071482149)
Description
This change prevents the My Collection queries and screens from failing if artworks don't have artists. Since we do not validate the presence of artists, this case is to be expected.
**Screens showing My Collection artworks without artists:**
| | |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-20 at 10 24 28](https://user-images.githubusercontent.com/4691889/169487502-1fd8ac4e-3968-498b-a83e-757d5eda2682.png) | ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-20 at 10 14 20](https://user-images.githubusercontent.com/4691889/169487515-40902238-9180-4553-9e78-052c25ad3cff.png) |
- Allow My Collection artworks without artists - …

fix: Allow My Collection artworks without artist

---

src/app/Scenes/Artist/Artist.tests.tsx

Small updates for Artist screen
-
-
-
- updates tests for Artists screen - dimatretyak
</details>

chore: updates tests for Artist screen

---

src/app/Scenes/Search/Search.tests.tsx
src/app/Scenes/Search/types.ts

https://user-images.githubusercontent.com/3513494/169848033-e9385f45-7b6d-42c5-b777-b51c671c56c2.mp4
https://user-images.githubusercontent.com/3513494/169848087-65d7983f-3552-42d8-8708-94bddb54ce79.mp4
-
-
-
-
</details>

chore: update Algolia index key for collection pill

---

src/app/Scenes/SavedSearchAlert/Components/Form.tsx
src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx

Related PR #6542
https://user-images.githubusercontent.com/3513494/169814305-befe22e4-1f68-4490-9b60-6140fd227556.mp4
https://user-images.githubusercontent.com/3513494/169814363-e7b5c0d5-0cca-4c25-8044-f3387ce3b397.mp4
-
-
-
- use new user email preferences for saved search alert flows - dimatretyak
</details>

chore(FX-3984): use new user email preferences for saved search alert flows

---

.github/workflows/beta-ios-manual.yml

This indent error got introduced recently and caused error reports every time someone pushes a branch.
-
-
-
-
</details>

fix: yaml indent error

---

HACKS.md
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tests.tsx
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtworkList.tsx
src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx

This PR resolves [CX-2440]
This is the second attempt to refactor the My Collection search bar to make it work on iOS and Android. 
Rework 1: https://github.com/artsy/eigen/pull/6676
-
-
-
-
</details>
[CX-2440]: https://artsyproduct.atlassian.net/browse/CX-2440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: My Collection Search Bar Rework 2

---

src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx

Refetch My Collection insights when adding or removing an artwork.
-
-
-
-
</details>

fix: Refetch My Collection insights when adding or removing an artwork

---

src/app/Scenes/Artwork/Artwork.tsx

Due to the fact that info about partner was requested in `artworkBelowTheFold`, the partner section appeared with "bounce" effect. This PR fixes this
https://user-images.githubusercontent.com/3513494/170005173-a151c95a-1c8b-41ee-a1e0-10fbc082dee7.mp4
https://user-images.githubusercontent.com/3513494/170005223-4cd1af4c-d27a-4ec1-9bff-a7ed49a11f9f.mp4
-
-
-
-
</details>

fix: bounce effect for partner on artwork page

---

src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkActions.tsx

Small refactor:
- updated some tests
- replaced deprecated sans component with palette Text
- uncommented and fixed commented out test
-
-
-
- refactor artwork action screen - gkartalis
</details>

refactor: ArtworkActions butttons

---

src/app/navigation/navigate.ts
src/app/store/config/features.ts
src/app/utils/track/SegmentTrackingProvider.ts
src/app/utils/visualizer.ts

Adds a little dev tool similar to the analytics visualizer for navigation calls. 
https://user-images.githubusercontent.com/49686530/170491883-d608312f-2c99-46f8-8d01-3b1ee5a8390b.mov
Shortcomings:
- Doesn't work for tab switches or native code but still useful I think
-
-
-
-
</details>

feat: add nav visualizer, make visualizer shared util

---

src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tsx

| Before  | After |
| ![Simulator Screen Shot - iPhone 8 - 2022-05-26 at 20 51 21](https://user-images.githubusercontent.com/3513494/170547159-b176f9b6-9e52-4017-90c9-f7cecd4dd682.png) | ![Simulator Screen Shot - iPhone 8 - 2022-05-26 at 20 51 40](https://user-images.githubusercontent.com/3513494/170547185-67c964c2-1462-4db7-8d1b-5dffc3978b35.png) |
-
-
-
- hide "Contact Gallery" button when auction is in closed state - dimatretyak
</details>

fix: hide "Contact Gallery" button when auction is in closed state

---

src/app/store/config/features.ts

This PR resolves [FX-3985]
Echo PR: artsy/echo#264
Mark `AREnableCreateArtworkAlert` readyForRelease
-
-
-
- mark AREnableCreateArtworkAlert as ready for release - dimatretyak
</details>
[FX-3985]: https://artsyproduct.atlassian.net/browse/FX-3985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-3985): mark AREnableCreateArtworkAlert as ready for release

---

src/app/Scenes/MyAccount/MyAccountEditEmail.tsx

This PR resolves [PLATFORM-4107]
This PR adds an alert message after a user updates their email instructing them to verify their email address. It supports the backend changes being made as part of this [ticket](https://artsyproduct.atlassian.net/browse/PLATFORM-4178).
NOTE: I saw double notifications in other areas, so assuming this is unrelated to my changes. 
- Alert user they need to confirm their email address after updating - Matt
</details>
[PLATFORM-4107]: …

refactor(PLATFORM-4107): notify user to verify email after update

---

app.json

Bump to 7.3.9
-
-
-
-
</details>

prepare for next version 7.3.9

---

src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
src/app/store/config/features.ts

Make My Collection Insights feature flags naming consistent to not confuse variable names in the code base too much (rename `show...` to `enable...`).
-
-
-
-
</details>

chore: Make My Collection Insights feature flags naming consistent

---

src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx

Unbold My Collection list artist name.
-
-
-
-
</details>

fix: Unbold My Collection list artist name

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx

This PR resolves [FX-3993]
There’s a slight delay between choosing an option with the slider and the “Show results” / “Clear” options flipping to an enabled state (see attached video)
-
-
-
-
</details>
[FX-3993]: https://artsyproduct.atlassian.net/browse/FX-3993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-3993): decrease debounce value to 200ms

---

src/app/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
src/app/Scenes/MyAccount/MyAccountEditEmail.tests.tsx
src/app/Scenes/MyAccount/MyAccountEditEmail.tsx
src/app/Scenes/MyAccount/updateMyUserProfile.ts

This PR adds tests to my account edit email screen as follow up from https://github.com/artsy/eigen/pull/6822
-
-
-
- add tests to my account edit email - mounir
</details>

chore: add tests to my account edit email flow

---

src/app/Scenes/MyCollection/MyCollectionArtworks.tsx

This PR resolves [CX-2601]
This PR updates the button copy inside my collection tab
| After  | Before |
|   ![Simulator Screen Shot - iPhone 13 - 2022-06-01 at 12 41 29](https://user-images.githubusercontent.com/11945712/171386876-1e4990cd-6000-43aa-a780-c030ce886ddf.png)  |   ![Simulator Screen Shot - iPhone 13 - 2022-06-01 at 12 41 44](https://user-images.githubusercontent.com/11945712/171386895-fc87f1e4-fd64-4448-bb3a-562fbe967f8b.png) |
- Update copy on my collection tab add artwork - mounir
-
-
-
</details> …

chore: update my collection empty state button

---

src/app/store/config/features.tests.ts
src/app/store/config/features.ts

We had issues with missing echo flag keys, so we are removing the option to have feature flags that are not controlled by an echo flag key.
This does not change how unleash is handled.
I have added the missing echo flag keys.
-
-
-
-
</details>

feat: stricter feature flag types

---

src/app/Components/States/ZeroState.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx

This PR resolves [CX-2609]
This PR fixes the vertical alignment inside my collection empty screen
| ![Simulator Screen Shot - iPhone 13 - 2022-06-01 at 13 32 44](https://user-images.githubusercontent.com/11945712/171394832-2edace33-2ee6-437e-bc8f-a4fa4e3dfc1b.png) |  ![Simulator Screen Shot - iPhone 13 - 2022-06-01 at 13 32 31](https://user-images.githubusercontent.com/11945712/171394852-833897ce-9359-4bb1-b7d8-15377ff5072d.png) |
-
-
-
-
</details>
[CX-2609]: …

fix: vertical alignment inside my collection empty screen

---

.gitignore
Artsy.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

based on https://stackoverflow.com/a/50368149 and the fact that its in the shared part of the xcode project, we can safely include this in our repo.
-
-
-
-
</details>

build: remove xcode shared files from gitignore

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx

Follow up on #6851
Update the visual clue name for the Insights tab 
-
-
-
- update insights tab visual clue name - mrsltun
</details>

fix: Update Insights tab visual clue name

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

A small fix for the logic to show the messages for artworks with/without Insights
https://user-images.githubusercontent.com/20655703/171453411-efeabeb7-2fc1-401c-aae3-1b9649006fbd.mp4
-
-
-
- update insights messages logic - mrsltun
</details>

fix: update showing insights message logic

---

src/app/Scenes/MyCollection/Screens/Insights/MyCollectionMessages.tsx

fix: update collection typo 😅 

---

src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx

Adds missing collection insights visual clue to profile screen tab (`new`). The dot and the `new` will disappear as soon as the user taps on the tab.
-
-
-
-
</details>

fix: Add collection insights visual clue to profile screen tab

---

src/palette/elements/VisualClue/VisualClueDot.tsx

Remove animation from visual clue dot.
-
-
-
-
</details>

fix: Remove animation from visual clue dot

---

src/app/Components/SectionTitle.tsx

Remove View All from section titles.
| --- | --- |
|![Simulator Screen Shot - iPhone 12 Pro Max - 2022-06-02 at 10 34 53](https://user-images.githubusercontent.com/4691889/171590579-c9551e9f-fc1e-4c01-87ca-56f63b85f298.png) | ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-06-02 at 10 35 00](https://user-images.githubusercontent.com/4691889/171590587-6654af2c-5c11-417b-a34c-7a8ec5f461ec.png)|
- Remove View All from section titles - ole
-
-
-
</details>

feat: Remove View All from section titles

---

src/app/Components/SectionTitle.tsx
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx

Change My Collection Insight Auction Results title.
| --- | --- |
|![simulator_screenshot_2C966663-DB7E-4570-9880-3534C1A9839A](https://user-images.githubusercontent.com/4691889/171592404-35da507e-336d-43f8-ae21-eb5b8b71eddf.png) | ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-06-02 at 10 43 39](https://user-images.githubusercontent.com/4691889/171592381-0271819c-7d32-4355-be09-c5e22732f7a1.png)|
- Change My Collection Insight Auction Results title - ole
-
-
-
</details>

feat: Change My Collection Insight Auction Results title

---

src/app/Components/AuctionResultsList.tsx
src/app/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx

Add year to auction result list section titles.
- Add year to auction result list section titles - ole
-
-
-
</details>

feat: Add year to auction result list section titles

---

src/app/Components/AuctionResultsList.tsx
src/app/Components/Lists/AuctionResultListItem.tsx
src/app/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tests.tsx
src/app/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx
src/app/Scenes/Home/Home.tsx
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx

New auction results screen design and copy.
[Slack Thread](https://artsy.slack.com/archives/C01B2P6LJUU/p1654164332741549)
| Home Screen | Auction Results for artists You Follow | 
| --- | --- |
|![simulator_screenshot_646915D3-B160-4A69-875E-4275752F93BF](https://user-images.githubusercontent.com/4691889/171614011-78da90b2-2b7e-479a-93e9-e960cde3f48c.png)| ![simulator_screenshot_3011D76B-8676-4B29-82CE-CD2666D01761](https://user-images.githubusercontent.com/4691889/171614027-cbeca43f-adae-4dc0-8b33-ea68ebb7d05b.png)|
| --- | --- |
|- | Auction Results for artists You Collect | 
| ![simulator_screenshot_80B9677B-A0C0-4B5C-9AF0-4D81BDC86342](https://user-images.githubusercontent.com/4691889/171614042-aa4455fb-c790-4b46-8a75-5343333ce655.png)|![simulator_screenshot_551356A6-D74B-4A0F-9EC3-FF …

feat: New auction results screen design

---

src/app/Scenes/Artwork/Components/CommercialEditionSetInformation.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx
src/app/Scenes/Artwork/Components/CommercialPartnerInformation.tests.tsx
src/app/Scenes/Artwork/Components/CommercialPartnerInformation.tsx

This PR resolves [FX-3990]
When feature flag is enabled use new styles from [Figma specs](https://www.figma.com/file/xsnfIWE7H67ZndGoEPVtN0/Alerts-2022?node-id=2103%3A30223)
* Text size increased to `lg` for price, "For Sale", "Not For Sale"
* Text size decreased to `xs` for shipping info
| Before  | After |
| ![before-1](https://user-images.githubusercontent.com/3513494/171442176-4c3d3f72-e8b0-4938-8641-1c11566695f9.png) | ![after-1](https://user-images.githubusercontent.com/3513494/171442217-19fe5b52-f595-4141-9dcc-8184f9639aca.png) |
| ![before-2](https://user-images.githubusercontent.com/3513494/171442254-dfc8948c-d280-47d5-bb66-1c66e9af442a.png) | ![after-2](https://user-images.githubusercontent.com/3513494/171442305-55e3514f-00e1-48aa-939f-6e509b338d …

chore(FX-3990): update text styles on Artwork page

---

.secrets.baseline
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/store/config/features.ts

This PR sets `readyForRelease` to TRUE for `AREnableMyCollectionInsights` and `AREnableMyCollectionInsightsPhase1Part1` feature flags and adds the echo flags to them
-
-
-
- set my collection insights flags to ready for release - mrsltun+dariakoko
</details>
Co-authored-by: Daria Kozlova <daria.kozlova@artsymail.com>

feat: Set My Collection Insights feature flags to readyForRelease

---

src/app/AppRegistry.tsx
src/app/Scenes/AuctionBuyersPremium/AuctionBuyersPremium.tests.tsx
src/app/Scenes/AuctionBuyersPremium/AuctionBuyersPremium.tsx
src/app/navigation/routes.tsx

This PR resolves [FX-3959]
* Added a separate page inside Eigen. When user clicks the "Buyer's premium" link, this page will open
* This page will display the same content as on Force (see attached video below)
https://user-images.githubusercontent.com/3513494/171679282-ff187318-f3fb-4800-8322-ed2f419c52eb.mp4
https://user-images.githubusercontent.com/3513494/171678851-22ca4a49-c217-44db-a2b1-fd19ced2acd5.mp4
https://user-images.githubusercontent.com/3513494/171678405-52f799cd-547d-484f-8af1-dace226831f7.mp4
-  AuctionBuyersPremium scene - dimatretyak
-
-
-
</details> …

feat: add AuctionBuyersPremium scene

---

src/app/Components/ArtsyReactWebView.tests.tsx
src/app/Components/ArtsyReactWebView.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tsx
src/app/utils/useWebViewEvent.ts
src/app/utils/useWebViewEvents.tests.ts

This PR resolves [NX-3139]
This PR implements some custom hook to register callbacks for webview events and tries to run callbacks given certain data received from Force throughout the `onMessage` prop of `react-native-webview`.
Now we have an Offer modal that pops when we finish the Offer flow in Force given the right information received from it.
https://user-images.githubusercontent.com/15792853/171411954-9710a393-72af-4663-8c4f-b9c93ada134d.mov
- enable webview communication and add offer completion modal - araujobarret
-
-
-
</details> …

feat(NX-3139): enable webview messages to trigger callbacks

---

src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx

This PR resolves [CX-2440]
Increases the My Collection search bar hit slop for the view option buttons and the search input.
-
-
-
-
</details>
[CX-2440]: https://artsyproduct.atlassian.net/browse/CX-2440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Increase My Collection search bar hit slop

---

.github/dependabot.yml

This PR assigns mobile-platform instead of collector experience to review dependabot PRs
-
-
-
- update reviewers on dependabot PRs
</details>

chore: update reviewers on dependabot PRs

---

src/app/store/config/features.ts

This PR enabled Google Auth. We added the feature flag to echo and forgot to set it to `readyForRelease` inside eigen :( 
-
-
-
- enable google auth - mounir
</details>

chore: enable google auth feature flag

---

app.json

Bumps version to 7.4.0
-
-
-
-
</details>

chore: bump version 7.4.0

---

src/app/Scenes/MyCollection/Screens/Artwork/ArtworkSubmissionStatusFAQ.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionSellingWithartsyFAQ.tsx

This PR resolves [CX-2561]
Added missing details to FAQ screens inside My Collection
- navigation to articles
- changed copy and email address
- linking to open email client when pressing on the email address
**NOTE: _I couldn't test the mailing on a real device - some issue with XCode and iPhone versions, the update takes alooooot of time_**
- add missing details to FAQ screens inside My Collection
-
-
-
</details>
[CX-2561]: https://artsyproduct.atlassian.net/browse/CX-2561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

fix(CX-2561): add missing details to FAQ screens inside My Collection

---

.gitignore

Fixes .gitiginore file.
-
-
-
-
</details>

chore: Fix .gitiginore file

---

docs/generate_a_release_build_for_local_testing.md
docs/getting_started.md

Updated the docs for opening xcode in the correct file now that the structure changed with the new app shell.
-
-
-
- updated getting started docs ios - gkartalis
</details>

docs: updated getting started ios [ci skip]

---

Brewfile
Brewfile.lock.json
scripts/install

- after the latest app shell changes, I noticed that the `init-metaflags` script is breaking because of the missing `jq` dependency in my macbook - this PR adds it to Brewfile ot make sure everyone gets it once they run the initial install script.
-
-
-
- fix: add jq to Brewfile - mounir
</details>

fix: add JQ to Brewfile

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/ArtworkRail/LargeArtworkRail.tsx
src/app/Components/ArtworkRail/SmallArtworkRail.tsx
src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtworkList.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkArticles.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkPurchaseDetails.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkComparableWorks.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsOverview.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx

In most cases, Relay's `useFragment` actually works without passing the type of the fragment. This PR removes all the passed types to clean up the code 🧹 
-
-
-
- Remove unnecessary passed types from useFragment - ole
</details>

chore: Remove unnecessary passed types from useFragment

---

ios/Artsy.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
src/storybook/index.js

- Get Storybook working again
-
-
-
- get storybook to work again - mounir
</details>

fix: get storybook working again

---

ios/Artsy.xcodeproj/project.pbxproj

These frameworks are only supported on later versions of iOS, since we support down to 12 we need to mark them as optional to avoid a crash on startup. 
-
- Fix embedded frameworks issue on lower version of iOS - brian
-
- 
</details>

fix: mark iOS 13+ frameworks optional

---

docs/README.md

add fetching_data.md link to readme 
-
-
-
-
</details>

docs:Update README.md

---

src/app/utils/AdminMenuWrapper.tsx

This PR disabled showing the admin menu after 5 touches on **iOS**. 
_More context can be found in [Slack](https://artsy.slack.com/archives/C02NAJ2CGLW/p1655297964264719)_
-
- Disable turning on admin menu after 5 taps on iOS - mounir
-
- 
</details>

chore: disable turning on admin menu after 5 taps on iOS

---

src/app/Components/ArtworkGrids/LotCloseInfo.tsx
src/app/Components/Bidding/Components/Timer.tsx
src/app/Components/Countdown/Ticker.tests.tsx
src/app/Components/Countdown/Ticker.tsx
src/app/Scenes/Sale/SaleHeader.tests.tsx
src/app/utils/saleTime.ts
src/app/utils/useTimer.tsx

This PR resolves [BID-406]
Update the timers to show time according to design specs
<table>
<tr>
<td>Day</td>
<td>Mins</td>
</tr>
<tr>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/174106925-49ece2ea-526b-4605-8c22-26d6a818e046.png"></td>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/174106905-8398108f-22f8-49e2-b2f9-a134318ed0e1.png"></td>
</tr>
</table>
- update lot timer to meet current specifications - kizito
-
-
-
</details>
[BID-406]: …

chore(BID-406): update lot timer to current specifications

---

src/app/Scenes/MyCollection/MyCollection.tsx

Add return to load all My Collection artworks logic.
-
-
-
-
</details>

fix: Add missing return when loading all My Collection artworks

---

src/app/store/config/features.ts

Marks `AREnableNewOpaqueImageView` ready for release and introducing it to echo with https://github.com/artsy/echo/pull/277 defaulting to false for now
-
-
-
- marks AREnableNewOpaqueImageView as ready for release - gkartalis
</details>

chore: mark AREnableNewOpaqueImageView as readyForRelease

---

src/app/store/config/features.ts

- Move my collection insights step 2 to echo
- [ x I hid my changes behind a [feature flag].
-
-
-
- move my collection insights ff step 2 to echo - mounir
</details>

chore: move my collection insights step 2 to echo

---

src/app/Scenes/Onboarding/OnboardingLogin.tests.tsx
src/app/Scenes/Onboarding/OnboardingLogin.tsx

- Fix login button covered by keyboard on Android
-
-
- Fix login keyboard button - mounir
-
</details>

fix: login button covered by keyboard

---

src/app/NativeModules/ARScreenPresenterModule.tsx

With new app shell deep linking from a killed state was not working due to the main nav stack not having time to instantiate. This checks if the stack is instantiated and if not waits using requestAnimationFrame. This is a bit of a hacky solution, will try to come up with something better in the coming days but it fixes the immediate issue. 
https://user-images.githubusercontent.com/49686530/174888424-7fe4e4b4-fad5-4cba-b853-fa8b821032d8.mov
</details>
- Fix deeplinks not working from killed state - Brian
-
-
-
</details> …

fix: deeplinks from killed state not working

---

src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx

Hides the next button in the onboarding webview that was resulting in a crash when tapped.
Co-authored by @MounirDhahri 
- Fix next button showing in onboarding web views - Brian, Mounir
-
-
-
</details>

fix: don't render next button in webview

---

app.json

set app version to 8.0.0 
#nochangelog

chore: set app version to 8.0.0 🎉

---

EXAMPLES.md

Noticed that we encourage people to use `test-id` to query components, while `@testing-library/react-native` has different suggestions on querying components. Updated our docs to reflect to the best practices of the community 😊
I will also update the example links during the refineathon :) 
read more info here 👇
[How should I query?](https://callstack.github.io/react-native-testing-library/docs/how-should-i-query/)
-
-
-
- updated how to test docs - gkartalis
</details>

docs: update test section examples [ci skip]

---

src/app/store/config/features.ts

Enable AREnableMyCollectionSearchBar feature flag.
-
-
-
-
</details>

chore: Enable AREnableMyCollectionSearchBar feature flag

---

src/app/store/config/features.ts

Echo PR: artsy/echo#284
Remove unused `AREnableImprovedAlertsFlow` feature flag
-
-
-
-
</details>

chore: remove unused `AREnableImprovedAlertsFlow` feature flag

---

package.json
src/app/Components/AnimatableHeader/AnimatableHeader.tests.tsx
src/app/Components/ArtworkFilter/FilterModal.tests.tsx
src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tests.tsx
src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tests.tsx
src/app/Components/ArtworkFilter/components/ArtworkFilterBackHeader.tests.tsx
src/app/Components/Bidding/Screens/Registration.tests.tsx
src/app/Components/SearchInput.tests.tsx
src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
src/app/Scenes/Fair/Fair.tests.tsx
src/app/Scenes/MyCollection/MyCollection.tests.tsx
src/app/Scenes/SavedSearchAlert/Components/SavedSearchAlertSwitch.tests.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/app/Scenes/Search/AutosuggestResults.tests.tsx
src/app/Scenes/Search/Search.tests.tsx
src/app/Scenes/Search/SearchArtworksContainer.tests.tsx
src/app/Scenes/Search/components/AutosuggestSearchResult.tests.tsx
src/app/Scenes/Search/components/SearchInput.tests.tsx
src/app/Scenes/Show/Show.tests.tsx
src/palette/elements/Input/Input.tests.tsx
yarn.lock

Upgrade `@testing-library/react-native` from 9.1.0 to v10.0.0
Addressed breaking changes like:
- `A11yLabel` -> `LabelText`
- RenderAPI type is not exported anymore due to a bug (reported it [here](https://github.com/callstack/react-native-testing-library/issues/999)) and added a workaround for this till this is addressed.
The changelog can be found [here](https://github.com/callstack/react-native-testing-library/releases/tag/v10.0.0)
-
-
-
-
</details>

chore(deps): update dep @testing-library/react-native from 9.1.0 to v10.0.0

---

package.json
src/app/Components/Bidding/Screens/Registration.tests.tsx
src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/MyCollection/MyCollection.tests.tsx
src/app/Scenes/Search/Search.tests.tsx
yarn.lock

Upgrade rntl and one reference I missed due to another pr getting merged.
Fixes issue from https://github.com/callstack/react-native-testing-library/issues/999
Also fixes breaking tests in main right now
-
-
-
- chore(deps): update dep @testing-library/react-native from 10.0.0 to v10.1.0 - gkartalis
</details>

chore(deps): update dep @testing-library/react-native from 10.0.0 to v10.1.0

---

src/app/Scenes/MyCollection/Components/MyCollectionArtworkList.tsx

This PR resolves [CX-2621](https://artsyproduct.atlassian.net/browse/CX-2621)
Quick fix that adds extra padding to My Collection artwork list on Android devices.
-
-
-
-
</details>

fix: Add extra padding to My Collection artwork list

---

src/app/Scenes/AuctionResult/AuctionResult.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx
src/app/Scenes/Sale/Components/SaleArtworkListItem.tsx
src/app/utils/resizeImage.ts

Set correct dimensions on My Collection artwork list view image.
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-27 at 13 42 08](https://user-images.githubusercontent.com/4691889/175935252-57dae513-e57a-4f34-a119-54263d44ede5.png)| ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-27 at 13 53 17](https://user-images.githubusercontent.com/4691889/175935262-1110ba59-6441-4151-bb75-6371bf1c2a0a.png)|
-
-
-
-
</details>

fix: Set correct dimensions on My Collection artwork list view image.

---

.circleci/config.yml
.secrets.baseline
.tool-versions
Brewfile
requirements.txt
scripts/doctor.js
scripts/install

Context: https://artsy.slack.com/archives/C02BAQ5K7/p1656407038938159
In short, we were using our own brew version of detect-secrets because the docker image we use had an older version. We don't need that anymore.
We now use the fresh python version of detect-secrets, and in another PR we will replace the docker image, so we don't have issues in the future.
-
-
-
-
</details>

fix: secrets detection

---

.circleci/config.yml
.tool-versions

Context: https://artsy.slack.com/archives/CP9P4KR35/p1656415016701649
Before (circle complaining):
https://app.circleci.com/pipelines/github/artsy/eigen/29350/workflows/1855d5ea-ba86-4a39-8f2a-e9c52045437a/jobs/87661/parallel-runs/0/steps/0-101
After (ci happy using a test PR): https://app.circleci.com/pipelines/github/artsy/eigen/29372/workflows/1a73eceb-f616-4dfc-b2bc-434e25d2b798/jobs/87742/parallel-runs/0/steps/0-101 
After (ci happy with our own docker images): https://app.circleci.com/pipelines/github/artsy/eigen/29382/workflows/fb48fa2b-2d38-4539-828f-03cbb8ff4c4c/jobs/87774/parallel-runs/0/steps/0-101
-
-
-
-
</details>
[app state …

build: detect secrets versions and docker image

---

src/app/Components/Bidding/Components/Timer.tests.tsx
src/app/Components/Bidding/Components/Timer.tsx

This PR resolves [BID-410]
Correct a typo on the lot screen.
-
-
-
-
</details>
[BID-410]: https://artsyproduct.atlassian.net/browse/BID-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(BID-410):correct spelling of accommodate below bid button

---

src/app/Components/Bidding/Components/Timer.tsx
src/app/Components/Bidding/Screens/BidResult.tests.tsx
src/app/Scenes/Artwork/Components/AuctionPrice.tests.tsx
src/app/Scenes/Artwork/Components/AuctionPrice.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/BidButton.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tests.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomView.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tests.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tests.tsx
src/app/Scenes/Artwork/Components/PartnerCard.tests.tsx
src/app/Scenes/Collection/Components/FullFeaturedArtistList.tests.tsx
src/palette/elements/Avatar/Avatar.tsx

[Notion card](https://www.notion.so/artsy/remove-enzyme-from-eigen-b4efdc0fe1cd4f0682d3b4df9c73f628)
* BidResult
* AuctionPrice
* BidButton
* CommercialButtons
* ImageCarouselFullScreen
* ImageZoomView
* ImageCarouselContext
* ImageWithLoadingState
* PartnerCard
* FullFeaturedArtistList
-
-
-
-
</details>

refactor: replace enzyme on RNTL

---

src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx

This PR resolves [FX-3990]
Related changes for PR #6821
Colored dots have been removed to match [the updated design](https://www.figma.com/file/xsnfIWE7H67ZndGoEPVtN0/Alerts-2022?node-id=2103%3A30223)
| Before  | After |
| ![before-1](https://user-images.githubusercontent.com/3513494/175343134-80ff5e40-080b-493d-8c29-2f3f2e191442.png) | ![after-1](https://user-images.githubusercontent.com/3513494/175343160-ea890080-c164-4efd-864f-9b82166db007.png) |
| ![before-2](https://user-images.githubusercontent.com/3513494/175343192-9585addc-eb06-4a2f-ae17-58a9e066a296.png) | ![after-2](https://user-images.githubusercontent.com/3513494/175343236-d6888f36-539e-4b97-a3c6-54b8f083ee48.png) |
| ![before-3](https://user-images.githubusercontent.com/3513494/175343267-ec793 …

chore(FX-3990): Remove color dots for availability label on artwork page

---

ios/Podfile.lock
package.json
src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/utils/index.tests.tsx
yarn.lock

Took the initiative and removed some unused eigen deps. Let me know your thoughts.
-
-
-
- remove some unused deps - gkartalis
</details>

chore(deps): remove unused deps

---

ios/Podfile.lock

On pr https://github.com/artsy/eigen/pull/7010 I removed by mistake the pods of this package (@react-native-community/cameraroll) this pr reverts this change and replaces the pods
-
-
-
- bring cameraroll pod back - gkartalis
</details>

fix: restore cameraroll to podfile

---

src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
src/app/Scenes/Artist/SearchCriteria.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx
src/app/Scenes/Artwork/Components/FollowArtistLink.tests.tsx
src/app/Scenes/Artwork/Components/PartnerCard.tests.tsx
src/app/Scenes/Artwork/Components/RequestConditionReport.tests.tsx
src/app/Scenes/Home/Components/EmailConfirmationBanner.tests.tsx
src/app/Scenes/MyProfile/LoggedInUserInfo.tests.tsx
src/app/Scenes/Search/AutosuggestResults.tests.tsx
src/app/Scenes/Search/SearchArtworksContainer.tests.tsx
src/app/tests/rejectMostRecentRelayOperation.ts

chore: add `rejectMostRecentRelayOperation`

---

package.json

Just a small cleanup.
-
-
-
-
</details>

build: no need for resolutions

---

dangerfile.ts

docs: tiny cleanup after enzyme

---

src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tsx

This PR resolves [CX-2641]
| New Profile Design | New Placeholder |
| -- | -- |
| <img alt="new design" src="https://user-images.githubusercontent.com/20655703/176948592-db7723ca-b15d-461c-b9e0-1f0a1a0af761.png" width="340px" /> | <img alt="new placeholder" src="https://user-images.githubusercontent.com/20655703/176948599-c1d89608-2fa7-4473-8ec8-2919116bcd5e.png" width="340px" />
- update my collection profile header design - mrsltun
-
-
-
</details>
[CX-2641]: …

feat [CX-2641]: Update collector profile header design

---

docs/pull_request_template.md

Trying to make our Recent Changes QA compilation of test cases a bit easier.
-
-
-
-
</details>

docs: adding a place to add QA test cases

---

src/app/Scenes/Artwork/Components/ArtworkExtraLinks/AuctionFaqSection.tsx

After the removal of Sans and Serif we missed some styling changes updates like this
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-07-06 at 16 01 15](https://user-images.githubusercontent.com/21178754/177583684-0254fcc5-516f-4d5f-a68c-d42d8c54598b.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-07-06 at 16 01 02](https://user-images.githubusercontent.com/21178754/177583665-25d16f06-f63a-4622-b4c2-5fb16a585494.png)|
-
-
-
-
</details>
Need …

fix: minor ui fixes after sans/serif removal

---

android/app/src/main/AndroidManifest.xml

This PR resolves [MOPLAT-189]
The problem is relevant for SDK 30 and higher. You can find more context [here](https://artsyproduct.atlassian.net/browse/MOPLAT-189?focusedCommentId=49616)
https://user-images.githubusercontent.com/3513494/178467386-ac670f53-6370-4e50-89cf-d36fd4dd68f1.mp4
**Pixel 4a (SDK 30)**
https://user-images.githubusercontent.com/3513494/178467562-0b4743cf-1b56-4621-838b-6aadfaa15057.mp4
**Pixel 2 (SDK 30)**
https://user-images.githubusercontent.com/3513494/178467630-75c864ec-ca80-4c98-9e45-731b25a3ffdc.mp4 …

feat(MOPLAT-189): support mailto links for SDK 30 and above

---

src/app/Scenes/MyProfile/MyProfileHeader.tsx

This PR adds adjusts the spaces to match the new design of the collector profile after finding out the difference between the design and the app in the visual audit
| -- | -- |
| ![Before](https://user-images.githubusercontent.com/20655703/178500545-77e598e4-2343-438d-b9f8-cfd671c40857.png) | ![After](https://user-images.githubusercontent.com/20655703/178500565-23b61edd-b425-44ab-b17b-bb949e1aaf6e.png) |
-
-
-
-
</details> …

Fix: Update name and profile picture spacing in the new collector profile header

---

src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx

This PR resolves [NX-3201]
The modal title has already been changed when opening the checkout flow from a conversation. The one opened from the artwork page remained unchanged.
- Changed checkout modal title from Buy Now to Purchase - LeandroL
-
-
-
</details> …

fix(NX-3201): changed modal title from Buy Now to Purchase

---

src/app/Components/Artist/ArtistConsignButton.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx

Tiny fix on text styling, consign with artsy text
|Before|After|
|---|---|
|![simulator_screenshot_8564B04F-6013-41FA-B49A-BC02B234B154](https://user-images.githubusercontent.com/21178754/179007230-59139e3a-11c9-4c85-aaf3-cb7063afaab5.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-07-14 at 16 48 38](https://user-images.githubusercontent.com/21178754/179011079-340f3745-e733-4e95-8c4e-ade7f08885e3.png)|
- fixed consign with artsy text style - gkartalis
-
-
- …

fix: small adjustment on text style after migrating to text from serif

---

src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tsx

This PR resolves [NX-3191](https://artsyproduct.atlassian.net/browse/)
The "go to inbox" and "close" buttons had the same functionality which is not the behaviour we want. 
I've separated the functionality to `onGoToInbox` and `onClose`.
When you close the modal `onClose` it's supposed to stay on the artwork page.
https://user-images.githubusercontent.com/17580625/179351420-f6742b4f-8971-4b4c-8ea0-c82133cb42ee.mp4
-
-
-
-
</details>
Need help with something? Have a look at our [docs], or …

fix(NX-3191): separate functionality for close and go to inbox button

---

src/app/Scenes/MyCollection/Screens/Insights/AverageAuctionPriceRail.tsx

This PR resolves [CX-2666]
Return an empty tag when the data is not available
| ![simulator_screenshot_7DA2999C-92F1-480A-B8EE-7F46959AF6F6](https://user-images.githubusercontent.com/36167539/179258313-1642b075-1369-48b2-8268-6cc4c999b7ce.png) | ![simulator_screenshot_26727FF9-ED89-4AD8-A9D1-02BDE99D818F](https://user-images.githubusercontent.com/36167539/179258276-ebbdb51b-6df2-4d38-bea2-2c941220ceb7.png) |
- Don't show section title in MyCollection …

fix (CX-2666): Don't show section title in MyCollection Insights when the data is not available

---

.gitignore

tiny PR to make our gitignore slightly simpler
-
-
-
-
</details>

chore: move this at the same place

---

src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
src/app/Scenes/Sale/Sale.tsx

This PR resolves [FX-4085]
Inside the auction screen when the auction is a popcorn (cascading) auction, the banner doesn’t seem to have spacing horizontally
| ![Simulator Screen Shot - iPhone 8 - 2022-07-20 at 13 34 54](https://user-images.githubusercontent.com/3513494/179962769-4e49daa6-3e6b-4b70-969e-56ecd60cadd5.png) | ![Simulator Screen Shot - iPhone 8 - 2022-07-20 at 13 36 34](https://user-images.githubusercontent.com/3513494/179962731-e5e7f912-8906-454f-b649-1310fe9cb8c0.png) |
| ![before](https://user-images.githubusercontent.com/3513494/179964460-a56be216-3546-4799-bd48-0ab3cf3e0c84.png) | ![after](https://user-images.githubusercontent.com/3513494/179964497-605b2732-db81-4cb7-91d5-b4b0755f18ab.png) |
| Test Case | Feature | …

fix(FX-4085): horizontal offset for popcorn auction banner

---

src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx

This PR fixes the signup flow issue where if the user tries to update the email for a second time it doesn't allow them to proceed to the password screen
-
-
-
-
</details>

fix: allow updating email on the sign up flow

---

docs/fetching_data.md

- Updated the description to have some screenshots.
- < secrets > was not visible, fixed that
- added a troubleshooting section for the case of getting "unauthorised" when making a request.
-
-
-
-
</details>

docs: update fetching_data.md

---

app.json

-
-
-
- Update app.json from 8.0.2 to 8.0.3 - mrsltun
</details>

chore: Update app.json (8.0.2 -> 8.0.3)

---

patches/@types+relay-test-utils+6.0.5.patch
src/app/Scenes/OrderHistory/OrderDetails/ArtworkInfoSection.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/OrderDetails.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/OrderDetailsPayment.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/ShipsToSection.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/SoldBySection.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/TrackOrderSection.tests.tsx
src/app/Scenes/OrderHistory/OrderHistory.tests.tsx
src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
src/app/Scenes/OrderHistory/SummarySection.tests.tsx
src/steps-for-new-tests.md

Fixing all the OrderHistory test files!
-
-
-
-
</details>

refactor(tests): OrderHistory

---

src/app/Components/ReadMore.tsx
src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
src/app/utils/renderMarkdown.tsx
src/palette/elements/Text/LinkText.tsx

This PR resolves [NX-3243]
After some refactoring of Sans element deprecation text variants were not correctly overwritten by children leading to wrong variants in some Texts inside other Texts. This PR fixes the AboutArtist component plus the LinkText variant from renderMarkdown util.
special thanks for the pairing on it to @gkartalis @pvinis @lean8086 
- fix link sizes from md texts - araujobarret
-
-
-
</details> …

fix(NX-3243): adjust font size elements from md text

---

.secrets.baseline
src/app/Scenes/MyAccount/MyAccount.tests.tsx
src/app/Scenes/MyAccount/MyAccountEditEmail.tests.tsx
src/app/Scenes/MyBids/ActiveLotStanding.tests.tsx
src/app/Scenes/MyProfile/LoggedInUserInfo.tests.tsx
src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
src/app/Scenes/SaleInfo/SaleInfo.tests.tsx
src/app/Scenes/SavedAddresses/SavedAddresses.tests.tsx
src/app/Scenes/SavedAddresses/SavedAddressesForm.tests.tsx
src/steps-for-new-tests.md

refactor(tests): MyProfile, MyAccount, SavedAddresses, SaleInfo tests

---

src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tests.tsx
src/app/Scenes/MyCollection/MyCollection.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateScreen.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/AverageSalePriceSelectArtist.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/TrackOrderSection.tests.tsx
src/app/Scenes/Tag/Tag.tests.tsx
src/app/tests/resolveMostRecentRelayOperation.ts
src/setupJest.ts

- Tag, MyCollection, setupjest
-
-
-
-
</details>

refactor: fix some relay tests 1

---

ios/ArtsyTests/ArtsyWidget/ArtworkTests.swift

Fixes Widget broken tests
-
-
-
-
</details>

fix: widget test missing prop

---

src/app/store/config/features.ts

Make `AREnableArtworksConnectionForAuction` feature flag as ready for release
-
-
-
-
</details>

chore: make `AREnableArtworksConnectionForAuction` as ready for release

---

src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx

In the old onboarding we were getting the error:
```
VirtualizedLists should never be nested in ScrollView with same orientation....
```
This pr fixes this issue.
|Before|After|
|---|---|
|https://user-images.githubusercontent.com/21178754/181026731-546984cd-2192-483b-9f69-30e09abb4181.mp4|https://user-images.githubusercontent.com/21178754/181027071-ccabef9c-3da5-4422-8921-3caef80f4c42.mp4|
- 
-
-
- fix virtualizedlist error on onboarding personalization screen - gkartalis
</details>

fix: virtualized list should never be nested inside scrollview

---

src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingAnimation.tsx

This PR resolves [GRO-1107]
|Android|iOS|
|---|---|
|https://user-images.githubusercontent.com/21178754/180997699-9f19e95b-13c3-4bea-98c4-38de483a5559.mov|https://user-images.githubusercontent.com/21178754/180994563-9d4e5c00-5621-4b30-9a02-5459c6ababd8.mp4|
- add entering buttons/description animation to start onboarding screen - gkartalis
-
-
-
</details> …

feat(GRO-1107): add button section description and animation

---

src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/utils/marketPriceInsightHelpers.tsx

Currently, we have some My Collection artworks where category and medium are interchanged.
Until we fix all of these artworks, this change will add logic to check which one is the category that we need to send to Vortex in order to fetch price insights.
-
-
-
-
</details>
[docs]: …

fix: Send only valid vortex mediums when fetching price insights

---

src/app/Scenes/Home/Components/SalesRail.tests.tsx
src/app/Scenes/Home/Components/SalesRail.tsx

This PR resolves [FX-4106]
Currently we are using `saleArtworksConnection` for "Auctions" rail on the home page. We want to replace this with `artworksConnection` to simplify development and support in the future (as we did it for [FX-4089](https://artsyproduct.atlassian.net/browse/FX-4089)).
- use `artworksConnection` for "Auctions" rail on home page - dimatretyak
-
-
-
</details> …

feat(FX-4106): use `artworksConnection` for auctions rail on home page

---

src/app/Components/StickyTabPage/StickTabPageRefreshControl.tsx

This PR fixes the crashing caused by the RefreshControl component
-
-
- fix crashing on profile tab - mrsltun, pavlos
-
</details>

fix: RefreshControl crash on android

---

src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx

Adjust Artwork screen placeholder spacing.
- Adjust Artwork screen placeholder spacing - ole
-
-
-
</details>

fix: Adjust Artwork screen placeholder spacing

---

src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx

This PR fixes the "Unable to Load" screen when opening the My Collection artwork screen from the grid view by passing the correct medium and category.
-
-
-
-
</details>

fix: Pass correct medium and category when clicking on My Collection artwork grid item

---

src/app/Components/ArtistListItem.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/ArtistListItem.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollowArtists.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tests.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingOrderedSet.tests.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingOrderedSet.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingSearchResults.tsx
src/shared/hooks/useDebouncedValue.ts

This PR resolves [GRO-1113]
- adds follow artists screen
- dynamic to easily support the galleries follows afterwards
- added some dumb tests (will add more on the galleries pr)
- collector can search screen
- title goes away when collector starts typing
- button disabled when no followed artists
> Missing the header and progress bar right now, will be added after it is finished in another ticket. Also todo: add animation when reanimated2 is merged to hide header dynamically
cc @artsy/grow-devs 
https://user-images.githubusercontent.com/21178754/181746069-3bd6e482-f261-4759-974e-72d288471034.mp4
|           |         | …

feat(GRO-1113): User sees app path for `Follow artists I’m interested in`

---

src/app/Components/FullScreenLoadingImage.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/SavingArtworkModal.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPostFollowLoadingScreen.tsx

The first 2 screenshots are to make sure nothing broke in `SavingArtworkModal` flow
|normal phones |smaller phones|
|---|---|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-08-01 at 13 13 23](https://user-images.githubusercontent.com/21178754/182136697-cfb152d3-3cbe-4750-9fcf-a161b45a4ce7.png)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-01 at 13 13 08](https://user-images.githubusercontent.com/21178754/182136728-58192140-25b8-4198-9c08-b1f230e7aed5.png)|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-08-01 at 13 13 20](https://user-images.githubusercontent.com/21178754/182136721-ba49e830-d2d0-478a-b9b1-74e5603cd819.png)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-01 at 13 13 …

feat: add onboarding loadingscreen

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx

This PR resolves [CX-2642]
Add a border to the promotional card to align with the design.
[Slack thread for context](https://artsy.slack.com/archives/C01B2P6LJUU/p1659356403574019)
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-01 at 16 22 06](https://user-images.githubusercontent.com/4691889/182169119-4607d86f-30bd-4fd6-8a41-c48d770b8e3e.png) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-01 at 16 20 35](https://user-images.githubusercontent.com/4691889/182169131-c2768afd-0c27-4176-811f-464b2ed3d02a.png)|
|           |         |             |                     | …

fix: Add border to promotional card

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tsx

- Move career highlights card padding out of the component to avoid the space left to the card getting white when the user presses the card.
- Open upload flow on card press (instead of just the button)
| After | Before |
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-01 at 14 20 30](https://user-images.githubusercontent.com/4691889/182146954-b11192bf-ca89-44ff-89ca-84f96edff24a.png) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-01 at 14 23 24](https://user-images.githubusercontent.com/4691889/182146965-7df32cde-586a-4a03-82bb-da6c68eb8261.png) |
|           |         |             | …

fix: Move career highlights card padding out of the component

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx

Follow-Up PR for https://github.com/artsy/eigen/pull/7136
Remove additional padding from the promo card.
-
-
-
-
</details>

fix: Remove additional padding from promo card

---

src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tests.tsx
src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tsx
src/app/Scenes/Sale/Sale.tsx

This PR resolves [FX-4107]
-
-
-
-
</details>
[FX-4107]: https://artsyproduct.atlassian.net/browse/FX-4107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4107): Replace `saleArtworksConnection` with `artworksConnection` for "Artworks Available to Buy Now" rail on the sale page

---

src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx

This PR resolves  [TX-522] 
Companion PR to https://github.com/artsy/force/pull/10650 - Minor copy update from 'pending' to 'processing'
[TX-522]: https://artsyproduct.atlassian.net/browse/TX-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update copy per spec

---

src/app/Components/ArtworkGrids/GenericGrid.tsx
src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx

This PR resolves [CX-2631]
This PR fixes a few artwork grid issues on tablets:
- Unifies the number of columns for tablets to **3** ([Slack thread with more context](https://artsy.slack.com/archives/C01B2P6LJUU/p1659436532361989).
- Adds correct right margin to the "Saved Works" artwork grid
| Saved Works | My Collection |
| --- | --- |
|![Simulator Screen Shot - iPad Air (4th generation) - 2022-08-02 at 12 32 50](https://user-images.githubusercontent.com/4691889/182382434-0ee9f10e-25fa-4597-b962-be86ea7f0775.png) | ![Simulator Screen Shot - iPad Air (4th generation) - 2022-08-02 at 11 52 35](https://user-images.githubusercontent.com/4691889/182382466-10fe96be-d0e2-45e4-9a7d-cbe80cfd3887.png)|
| …

fix: Artwork grid tablet layout

---

docs/best_practices.md
src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tests.tsx
src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tests.tsx
src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
src/app/Scenes/Search/Search.tests.tsx

docs: test docs + start using `screen.` from rntl

---

src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx

This PR hides the Career Highlights rail behind a feature flag `AREnableMyCollectionInsightsPhase1Part3`
- hide career highlights rail behind feature flag - mrsltun
-
-
-
</details>

Fix: Hide Career Highlights rail behind a feature flag

---

src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingOrderedSet.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingSearchResults.tsx

This PR resolves [GRO-1180]
|normal|small|
|---|---|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-08-02 at 14 56 22](https://user-images.githubusercontent.com/21178754/182382040-bb5143ad-a8a2-471f-ab9e-9762bbf1bac1.png)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-02 at 14 56 15](https://user-images.githubusercontent.com/21178754/182382051-5003ff79-8a49-42e8-adcd-919b559abafb.png)|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-08-02 at 14 56 30](https://user-images.githubusercontent.com/21178754/182382215-b2f8f315-df91-4f27-af6e-7624ffe3bc0b.png)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-02 at 14 56 10](https://user-images.githubusercontent.com/21178754/182382212-89a83cfe-2ff9-4273-af63-d6e3391b7617.png)|
|![Simulator Screen Shot - iPhone 13 Pro …

feat(GRO-1180): Add nav bar and progress bar to follows onboarding screen

---

src/app/Components/ArtworkGrids/GenericGrid.tsx

GenericGrid Theme import.
-
-
-
-
</details>

fix: GenericGrid Theme import

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx

Require `category` instead of `medium` in artwork form.
- Require category instead of medium in artwork form - ole
-
-
-
</details>

fix: Require category instead of medium in artwork form

---

src/app/Scenes/Onboarding/OnboardingPersonalization2/Components/GeneHeader.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Hooks/useNextOnboardingScreen.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingGene.tests.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingGene.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPostFollowLoadingScreen.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTemplate.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionThree.tsx

This PR resolves [GRO-1182]
|flow1|flow2|
|---|---|
|https://user-images.githubusercontent.com/21178754/182853723-24ce5538-62c7-4493-8f8a-05faf0a99901.mp4|https://user-images.githubusercontent.com/21178754/182853751-2a98a51c-f44a-4764-9920-7827d7ff7f37.mp4|
- onboarding ui fixes and navigation logic - gkartalis
-
-
-
</details>
[GRO-1182]: https://artsyproduct.atlassian.net/browse/GRO-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(GRO-1182): minor fixes and screen navigation logic

---

src/app/Scenes/Onboarding/OnboardingPersonalization2/Components/GeneHeader.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Hooks/useNextOnboardingScreen.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Hooks/useUpdateUserProfile.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingGene.tests.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingGene.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPostFollowLoadingScreen.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionOne.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTemplate.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionThree.tsx

This PR resolves [GRO-1188]
This PR resolves [GRO-1189]
https://user-images.githubusercontent.com/21178754/182857122-ce7486af-6f65-4ecc-9aa9-54a3ee6f1d9b.mov
- persist onboarding data - gkartalis
-
-
-
</details>
[GRO-1188]: https://artsyproduct.atlassian.net/browse/GRO-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1189]: https://artsyproduct.atlassian.net/browse/GRO-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

feat(GRO-1188, GRO-1189): persist onboarding data

---

fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/release_notes.txt

release: Update release_notes.txt

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx

This PR removes auto-correct functionality from the artist and artwork search in the My Collection upload flow. This is to prevent auto-correction to correct artist or artwork names that are not in the dictionary of the device.
-
-
-
-
</details>

fix: Remove auto-correct from artwork form search inputs

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/utils/marketPriceInsightHelpers.tsx

Improve MyCollectionArtwork screen props type safety.
[Slack Thread for context](https://artsy.slack.com/archives/C03RXBY2A1M/p1659692768603799)
-
-
-
- Improve MyCollectionArtwork screen props type safety - ole
</details>

chore: Improve MyCollectionArtwork screen props type safety

---

src/app/Scenes/Onboarding/OnboardingPersonalization2/Components/AnimatedFadingPill.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTemplate.tsx

This PR resolves [GRO-1183]
https://user-images.githubusercontent.com/21178754/183107576-31334d42-8137-40b6-a643-e097981f1a1d.mp4
- animated removal of unselected answers onboarding - gkartalis
-
-
-
</details>
[GRO-1183]: https://artsyproduct.atlassian.net/browse/GRO-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(GRO-1183): animated removal of unselected answers

---

docs/pull_request_template.md

We updated the PR template to include test descriptions as well as a section that we can directly provide to Applause for testing.
Coauthored by @brainbicycle 
@artsy/engineering for your reference
-
-
-
-
</details>

Docs: update pr template

---

src/app/store/config/features.ts

Add AREnableMyCollectionInsightsMedianPrice feature flag.
This PR resolves [CX-2688]
-
-
-
-
-
-
</details>
[CX-2688]: https://artsyproduct.atlassian.net/browse/CX-2688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add AREnableMyCollectionInsightsMedianPrice feature flag

---

.secrets.baseline
src/app/AppRegistry.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
src/app/Scenes/MyCollection/Screens/Insights/SelectArtist.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx
src/app/navigation/routes.ts

This PR changes the copy in the My Collection insights from "Average Price" to "Median Price" (see screenshot) and renames the corresponding components and routes.
This PR doesn't change the data that is fetched. This will happen in a follow-up PR.
| | |
| --- | --- |
| ![Simulator Screen Shot - iPad Air (4th generation) - 2022-08-09 at 12 11 00](https://user-images.githubusercontent.com/4691889/183623585-8cee7a09-2ed4-4ea5-9451-75180d731e57.png) | ![Simulator Screen Shot - iPad Air (4th generation) - 2022-08-09 at 12 11 05](https://user-images.githubusercontent.com/4691889/183623598-7b666cfc-134c-4a6d-9889-8a4862248cd8.png) |
This PR resolves [CX-2688]
-
-
- My Collection Insights Average Auction Price -> Median Auction Price - ole
-
-
- …

fix: change My Collection Insights Average Price copy to Median Price 

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
src/app/Scenes/Search/AutosuggestResults.tsx
src/app/Scenes/Search/SearchResults.tsx
src/app/Scenes/Search/components/placeholders/AutosuggestResultsPlaceholder.tsx

This PR adjusts the My Collection artist search result horizontal padding according to the design (remove extra horizontal padding).
[Figma Design](https://www.figma.com/file/l3plkt7gMSg4p1Or0E8SLC/My-Collection-2022?node-id=5776%3A84599)
I've decided to refactor the search component and add extra padding whenever we need it in the component that uses the component.
| --- | --- |
| ![Simulator Screen Shot - iPad Air (4th generation) - 2022-08-05 at 14 52 07](https://user-images.githubusercontent.com/4691889/183082828-0f89b24e-5c4f-468f-a443-9db096da62fb.png) | ![Simulator Screen Shot - iPad Air (4th generation) - 2022-08-05 at 14 57 55](https://user-images.githubusercontent.com/4691889/183082840-947b7fe3-b613-46b5-a373-68e945cfe960.png) |
| Test Case | Feature | …

fix: Adjust My Collection artist search result horizontal padding

---

src/app/Scenes/MyCollection/Screens/Insights/AverageAuctionPriceRail.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx

This PR resolves [CX-2724]
- The title is changed from "Average..." to "Median..."
-
- update the copy of a section in MyCollection Insights - daria
-
-
-
</details>
[CX-2724]: https://artsyproduct.atlassian.net/browse/CX-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2724): Update copy for sale price in the last 3 years

---

src/app/Scenes/Collection/Collection.tsx

https://user-images.githubusercontent.com/3513494/183700441-682a4a7b-c280-42fe-bdc0-d4f24ac84834.mp4
https://user-images.githubusercontent.com/3513494/183700470-05da6676-aeac-486c-9f49-d600821ff78a.mp4
-
-
-
-
-
- dynamically find sticky section on collection screen - dimatretyak
</details>

chore: dynamically find sticky section on collection screen

---

package.json

Add comment about react-native-vision-camera
-
-
-
-
-
- update dependencies comments - dimatretyak 
</details>

chore: update dependencies comments

---

package.json
scripts/add-submission-tags.js
scripts/changelog/commitChangelog.js
scripts/helpers/exec.js
yarn.lock

This PR adds the `-submission` tag to the android and iOS tags.
The way this script works is as follows:
```bash
node scripts/add-submission-tags.js  
```
-
-
-
- add add-manual-submission-tag to releases - mounir
</details>

feat: add add-manual-submission tag to releases

---

scripts/add-submission-tags.js

- Checkout to main after adding submission tags.
cc @patrinoua @MrSltun 
#nochangelog

fix: checkout to main after adding submission tags

---

src/app/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/WaysToBuyOptions.tests.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingAnimation.tsx
src/app/utils/placeholders.tests.tsx
tsconfig.json

This PR resolves [GRO-1106]
Part 2 of https://github.com/artsy/eigen/pull/7098.
waiting for reanimated work to be merged before proceeding in merging this.
|Android|iOS|
|---|---|
|https://user-images.githubusercontent.com/21178754/180977332-75a7a3f5-ef0a-4f11-8a0d-48bc8d0ad4ed.mov|https://user-images.githubusercontent.com/21178754/180978288-c429798b-f631-4763-b11a-4e964e0fb403.mp4|
cc @artsy/grow-devs 
- add onboarding animation - gkartalis
-
-
-
</details> …

feat: add onboarding animation (not connected yet)

---

src/app/Scenes/Onboarding/OnboardingPersonalization2/Hooks/useOnboardingContext.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionOne.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTemplate.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionThree.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTwo.tsx
src/app/Scenes/Onboarding/OnboardingPersonalization2/config.tests.ts
src/app/Scenes/Onboarding/OnboardingPersonalization2/config.ts
src/app/utils/WorkflowEngine/WorkflowEngine.tsx

This PR resolves [GRO-1184]
This PR expands on the current workflow engine functionality to allow users to move backward through the onboarding experience. 
A follow up PR is needed to re-enable the fade away button animation.
https://user-images.githubusercontent.com/14044896/183742408-0450241f-8100-4794-bb94-0bc9d7bbf1fa.mov
| Backward Navigation |  Onboarding  |  Staging   |    User can navigation backward, edit answers, process forward and complete onboarding |                         |
- Add backward navigation to new onboarding workflow
-
-
-
</details>
Need help with …

feat(GRO-1184): implement onboarding backward navigation 

---

.github/workflows/hello.yml
.github/workflows/labels-from-comments.yml

ci: adding labels from comments

---

src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx

fetch median instead of average for My Collection Insights.
This PR resolves [CX-2688]
-
-
-
-
-
-
</details>
[CX-2688]: https://artsyproduct.atlassian.net/browse/CX-2688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Fetch median instead of average for My Collection Insights

---

src/app/AppRegistry.tsx

Add top padding to career highlights full modal carousel
#nochangelog

fix(CX2750): add top padding to career highlights full modal carousel

---

src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
src/app/store/config/features.ts

This PR hides median price screen under different ff.
cc @dariakoko 
#nochangelog

chore: hide median price screen under different ff

---

src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts

Update My Collection artwork filter to use category instead.
-
-
-
-
-
-
</details>

fix: Update My Collection artwork filter to use category instead

---

src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx

Display category in My Collection price insight updates.
-
-
-
-
-
-
</details>

fix: Display category in My Collection price insight updates

---

src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/store/config/features.ts

Add delete all artworks in my collection [dev only]
https://user-images.githubusercontent.com/11945712/184339052-bd3d38f1-84b7-494c-817a-bc4a08eed412.mov
-
-
-
-
-
- add delete all artworks in my collection [dev only] - mounir
</details>

feat: add delete all artworks in my collection [dev only]

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx

fix(CX-2752): Refresh career highlights after adding an artist

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tsx

Changed onPress actions. When pressing on the card - ig view opens. When pressing on the button - the "add new work" screen opens
Also fixed the grammar issue mentioned by Sarah [here](https://artsy.slack.com/archives/C01B2P6LJUU/p1660228563673259?thread_ts=1660228465.211109&cid=C01B2P6LJUU)
https://user-images.githubusercontent.com/36167539/184253213-260a3ab3-fe58-4272-a5fc-7310148ad061.mp4
This PR resolves [CX-2749, ]
- When pressing the button we should navigate to the add artwork screen
- When pressing on the card we should open the big card view
-
- fix promo card's UX | Career Highlights - daria
-
-
-
</details> …

fix(CX-2749): fix small promo card and grammar

---

src/app/store/config/features.ts

Enable part 3 of insights
#nochangelog

chore: enable part 3 of insights

---

src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx

Deactivate autoCorrect from MyC artwork search bar.
Follow-up for https://github.com/artsy/eigen/pull/7166
-
-
- Deactivate autoCorrect from MyC artwork search bar - ole
-
-
-
</details>

fix: Deactivate autoCorrect from MyC artwork search bar

---

src/app/Scenes/Onboarding/Onboarding.tsx
src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
src/app/Scenes/Onboarding/OnboardingV2/Hooks/useOnboardingTracking.ts
src/app/Scenes/Onboarding/OnboardingV2/OnboardingOrderedSet.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingSearchResults.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingWelcome.tsx
src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingGene.tests.tsx
src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingWelcome.tests.tsx
src/app/Scenes/Onboarding/OnboardingV2/__tests__/useOnboardingTracking.tests.ts

This PR resolves [GRO-1227]
Calling `useOnboardingTracking` from outside the onboarding `NavigationStack` crashed the app via internal use of `useNavigation`. Refactored to supply that data via prop instead. 
- App loads and runs w/o crashing
-
-
-
-
-
</details>
[GRO-1227]: https://artsyproduct.atlassian.net/browse/GRO-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug(GRO-1227): fix tracking hook

---

src/palette/elements/ProgressBar/ProgressBar.tsx

Fixes progress bar that was broken (due to wrong import)
This PR resolves [GRO-1218]
-
-
- fix progress bar not working - gkartalis
-
-
-
</details>
[GRO-1218]: https://artsyproduct.atlassian.net/browse/GRO-1218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GRO-1218): progress bar doesn't reflect progress

---

.tool-versions

changing tool-versions file to have `java zulu-11.58.15` version
-
-
-
-
-
- update tool-versions file with latest zulu11 java - gkartalis
</details>

chore: update tool-versions to java latest rec from rn docs

---

ios/Artsy.xcodeproj/project.pbxproj
ios/Podfile
ios/Podfile.lock
src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
src/palette/atoms/BackButton/BackButton.tsx
src/palette/organisms/screenStructure/Screen.tsx

Managed to make the iOS app run without rosetta on a M1 macbook.
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
slack thread for more context [here](https://artsy.slack.com/archives/CP9P4KR35/p1660825098095549)
-
-
-
-
-
-
</details>

feat: make iOS app run natively without rosetta on M1 macs

---

src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
src/palette/atoms/BackButton/BackButton.tsx
src/palette/organisms/screenStructure/Screen.tsx

Disabled the gesture navigation in onboarding. Before we were able to go back with a gesture and it was messing with the onboardingContext when we went back this way
Before video:
https://user-images.githubusercontent.com/21178754/185619271-7b608dee-6ed8-4c1d-be24-5b4969334bd0.mp4
Didn't record an after video 🎉 
This PR resolves [GRO-1240]
-
-
- disable new onboarding gesture navigation - gkartalis
-
-
-
</details>
[GRO-1240]: https://artsyproduct.atlassian.net/browse/GRO-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

fix(GRO-1240): disable gesture navigation onboarding

---

src/app/store/config/features.ts

This PR resolves [GRO-1232]
⚠️ Merge after https://github.com/artsy/echo/pull/298 is merged in echo ⚠️ 
-
-
-
-
-
- mark onboarding as ready for release - gkartalis
</details>
[GRO-1232]: https://artsyproduct.atlassian.net/browse/GRO-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(GRO-1232): mark onboarding as readyforrelease and connect with echo

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/ReverseImage/ReverseImage.tsx
src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx

https://user-images.githubusercontent.com/3513494/184325412-00ed6cf4-3cc0-4ac5-8f8c-27ccefc01c2e.mp4
https://user-images.githubusercontent.com/3513494/184329068-7db32091-903c-4378-b5d2-712cd5b1829c.mp4
-
-
-
-
-
- set white color for the status bar icons on artwork page when navigated from reverse image - dimatretyak
</details>

fix: set white color for the status bar icons on artwork page when navigated from reverse image

---

src/app/Scenes/Favorites/FavoriteArtworks.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsPromotionalCard.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
src/app/store/config/features.ts

chore: get main up to date

---

app.json

Preparing for development, version 8.1.0

---

src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx

Remove artist insights modal height restriction.
This PR resolves [CX-2764]
| --- | --- |
|![Simulator Screen Shot - iPhone 13 Pro - 2022-08-22 at 12 09 30](https://user-images.githubusercontent.com/4691889/185896870-e2775f5b-4ff9-4f22-8221-bd40240d2b8b.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-08-22 at 12 05 59](https://user-images.githubusercontent.com/4691889/185896810-4ea365de-3ec9-48c6-87ea-c340ce115704.png)|
-
-
- Remove artist insights modal height restriction - ole
-
-
-
</details>
[docs]: …

fix fix: Remove artist insights modal height restriction

---

src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx
src/shared/utils/normalizeText.ts

Normalize query in My Collection select artist modal to be able to search without Umlaute.
| --- | --- |
|![Simulator Screen Shot - iPhone 13 Pro - 2022-08-23 at 12 33 23](https://user-images.githubusercontent.com/4691889/186137047-0c318357-9a95-4271-adc9-1759e5d14045.png) |![Simulator Screen Shot - iPhone 13 Pro - 2022-08-23 at 12 31 33](https://user-images.githubusercontent.com/4691889/186137054-67ad9543-2ec1-48b6-86ee-f75de9f1aefc.png) |
-
-
- Normalize query in My Collection select artist modal. - ole
-
-
-
</details> …

fix: Normalize query in My Collection select artist modal

---

src/palette/elements/LineGraph/LineGraphChart.tsx

This PR resolves [CX-2815]
-
-
- fix space between chart duration and chart too big
-
-
-
</details>
[CX-2815]: https://artsyproduct.atlassian.net/browse/CX-2815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2815): fix space between chart duration and chart too big

---

src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx

This PR resolves [CX-2812]
-
-
-
-
-
-
</details>
[CX-2812]: https://artsyproduct.atlassian.net/browse/CX-2812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cx-2812): unable to scroll to medium pills

---

src/palette/elements/LineGraph/LineGraphChart.tsx

This PR resolves [CX-2812] [CX-2817]
**After**
https://user-images.githubusercontent.com/11945712/186171975-08b08323-f0c2-4c3a-b93f-7630dde1719e.mov
**Before**
https://user-images.githubusercontent.com/11945712/186171949-95d37fa0-98fb-40c2-9ed9-c9156decadd4.mov
-
-
- Improve the performance of the sale graph chart - mounir
-
-
-
</details>
[CX-2812]: https://artsyproduct.atlassian.net/browse/CX-2812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2817]: …

chore: improve performance of interactions in the graph

---

src/palette/elements/LineGraph/LineGraphCategoryPicker.tsx
src/palette/elements/Pill/Pill.tsx

This PR resolves [CX-2814]
Increase medium pills hit stop inside the line chart graph
-
-
- Increase hitslop for medium pills inside the line chart graph - mounir
-
-
-
</details>
[CX-2814]: https://artsyproduct.atlassian.net/browse/CX-2814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: increase medium pills hitslop

---

src/palette/elements/LineGraph/LineGraph.tsx
src/palette/elements/LineGraph/LineGraphChart.tsx
src/palette/elements/LineGraph/LineGraphHeader.tsx

This PR resolves [CX-2812]
When the content is too tall, the screen goes down. this won't happen after this fix since the text has fixed height now
**Before**
https://user-images.githubusercontent.com/11945712/186169349-3e55f7d1-d244-493c-8c16-9532a7aae509.mov
**After** Even if the text is long, the graph will keep position
-
-
- fix graph content pushed down when the text is too long - mounir
-
-
-
</details>
[CX-2812]: https://artsyproduct.atlassian.net/browse/CX-2812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …

fix: graph content pushed down when the text is too long

---

src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx

This PR resolves [CX-2811]
This PR improves the copy when no auction results or little are available. Return **Median Unavailable (Limited Data)** instead of **0 Auction Results**
-
-
-
-
</details>
[CX-2811]: https://artsyproduct.atlassian.net/browse/CX-2811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: improve copy when no auction results or little are available

---

ios/Artsy.xcodeproj/project.pbxproj
ios/Podfile.lock
package.json
yarn.lock

bump `react-native-vision-camera` to [2.14.1](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.14.1)
-
-
-
-
-
-
</details>

feat: bump `react-native-vision-camera` to `2.14.1`

---

src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
src/app/store/config/features.ts

Display some debug info to try to understand [the cause of this error](https://artsy.slack.com/archives/C03RKQGMHUJ/p1661174765611519?thread_ts=1661174741.411159&cid=C03RKQGMHUJ) 
-
-
-
-
-
-
</details>

chore: display debug info for reverse image screen

---

src/palette/elements/LineGraph/LineGraphHeader.tsx

Remove dot when there is not medium available
- only show medium dot when there is a medium available - mounir
-
-
-
</details>

fix: only show medium dot when there is a medium available

---

src/app/Scenes/MyProfile/MyProfileHeader.tsx
src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
src/app/store/config/features.ts
src/app/store/config/visualClues.ts

Remove complete profile message
This PR resolves [[CX-2810]](https://artsyproduct.atlassian.net/browse/CX-2810)
-
-
- Remove complete profile message banner - mounir
-
-
-
</details>
[CX-2810]: https://artsyproduct.atlassian.net/browse/CX-2810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove complete profile message

---

src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx

This PR resolves [CX-2826](https://artsyproduct.atlassian.net/browse/CX-2826)
- Remove section title description in select artist modal in sale graph screen
-
-
- remove section title description (With insights currently available) in select artist modal - mounir
-
-
-
</details>

chore: remove section title description in select artist modal

---

src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx

https://user-images.githubusercontent.com/11945712/186399643-8b3a13c8-bcf6-4be4-83c7-20177528c29b.mov
This PR resolves [CX-2758](https://artsyproduct.atlassian.net/browse/CX-2758)
-
-
- improve last 3 median touch behaviour price section on insights screen - mounir
-
-
-
</details>

chore: improve last 3 median price section on insights screen

---

src/app/Scenes/MyAccount/updateMyUserProfile.ts
src/app/Scenes/MyProfile/MyProfileEditForm.tsx

This PR resolves [CX-2766]
This PR fixes an issue where the user is unable to save new updated fields into their profile as well as improve the error returned from the update profile mutation.
https://user-images.githubusercontent.com/11945712/186459798-3aa92275-73c0-458d-8495-4f27f407f018.mov
- Fix can not update profile - mounir
-
-
-
</details>
[CX-2655]: https://artsyproduct.atlassian.net/browse/CX-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

fix: can't save update profile fields

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkComparableWorks.tsx

This PR resolves [CX-2655]
This PR makes the comparable works menu not clickable
-
-
- make comparable works menu on my collection artwork screen not clickable - mounir
-
-
-
</details>
[CX-2655]: https://artsyproduct.atlassian.net/browse/CX-2655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: make comparable works menu not clickable

---

src/app/Scenes/Onboarding/OnboardingV2/OnboardingPostFollowLoadingScreen.tsx

change the NAVIGATE_TO_NEXT_SCREEN_DELAY on post follow screen
https://user-images.githubusercontent.com/21178754/186434686-26d2916d-7e5c-42fb-ace1-06c4559e68d8.mp4
This PR resolves [GRO-1246]
-
-
- adjust NAVIGATE_TO_NEXT_SCREEN_DELAY time on postfollow screen onboarding - gkartalis
-
-
-
</details>
[GRO-1246]: https://artsyproduct.atlassian.net/browse/GRO-1246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(GRO-1246): change NAVIGATE_TO_NEXT_SCREEN_DELAY on postfollow screen

---

src/app/Scenes/Onboarding/OnboardingV2/OnboardingFollows.tsx
src/palette/organisms/screenStructure/Screen.tsx

Removes back button from follow artist/gallery onboarding flow.
This PR resolves [GRO-1247]
-
-
- removed back button from follow artist/gallery onboarding flow - gkartalis
-
-
-
</details>
[GRO-1247]: https://artsyproduct.atlassian.net/browse/GRO-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove back button from follow artists/galleries onboarding page

---

src/app/Components/ArticleCard.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/Home/ArtistRails/ArtistCard.tsx
src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
src/app/store/config/features.ts
src/palette/elements/Cards/MediumCard.tsx

Rename opaqueImageView component feature flag to be released only in latest app version (8.1.0 +)
- make sure that the new image component (on staging it has a purple watermark NewImg) renders normally and no weird behavior is encountered. This covers many surfaces so exploratory testing might be suitable for this. Most of the artwork grids use the new image.
- go to admin menu and enable the feature flag Enable New Image Component.
-
-
-
- **[NEEDS EXTERNAL QA]** rename opaqueImageView component ff - gkartalis
</details> …

build: rename opaqueImageView component ff

---

src/app/Scenes/Onboarding/OnboardingV2/OnboardingGene.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingPostFollowLoadingScreen.tsx

This PR extends visible time of the thank-you screen, and adds the end loader to all onboarding routes (per a discussion w/ @jpoczik).
-
-
-
-
-
-
</details>

chore: copy & redirect interval changes 

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx

This PR resolves [[CX-2796](https://artsyproduct.atlassian.net/browse/CX-2796)]
https://user-images.githubusercontent.com/11945712/186904852-e2e026aa-4e10-4a41-84e8-580e39eb9e4d.mov
- navigate to artist page on artist name press - mounir
-
-
-
</details>

feat: navigate to artist page when user presses on artist name

---

.circleci/config.yml

This PR resolves [PLATFORM-4375](https://artsyproduct.atlassian.net/browse/PLATFORM-4375)
- CI runs successfully. detect-secrets job uses`ci` tag
- N/A
- [ N/A ] I tested my changes on **iOS** / **Android**.
- [ N/A ] I added screenshots or videos to illustrate my changes.
- [ N/A ] I added Tests and Stories for my changes.
- [ N/A ] I added an [app state migration].
- [ N/A ] I hid my changes behind a [feature flag].
- [ N/A ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.
- [ N/A ] I would like **at least one** of the reviewers to run this PR on the simulator or device.
-
-
-
-
</details>
[app state …

chore: switch to detect-secrets dedicated CI tag

---

.secrets.baseline
src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx

This PR resolves [CX-2722]
- allow editing and deleting submitted artworks inside my collection
**Edit**
https://user-images.githubusercontent.com/11945712/186909195-8d6d5b55-e106-4083-a35e-e1028c18a67e.mov
**Delete**
https://user-images.githubusercontent.com/11945712/186909179-9ec0e41d-c21b-4aa2-baf6-d0847c6d6d69.mov
-
-
-  allow editing and deleting submitted artworks inside my collection - mounir
-
-
-
</details>
[CX-2722]: https://artsyproduct.atlassian.net/browse/CX-2722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

feat: allow editing and deleting submitted artworks inside my collection

---

src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx

Decrease MyC search bar vertical spacing when focused. This is a follow up for [this change](https://github.com/artsy/eigen/pull/7279/files#diff-90633c917a6ee2f6beebb9bacc945c6c51cf8e41b60cb42e7da052a483ac7c4eL150) which only decreased the spacing for the non-focused search bar.
-
-
-
-
-
-
</details>

fix: Decrease MyC search bar vertical spacing when focused

---

src/app/Scenes/Onboarding/OnboardingV2/OnboardingFollows.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingGene.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingPostFollowLoadingScreen.tsx
src/shared/hooks/useBackHandler.tests.ts
src/shared/hooks/useBackHandler.ts

This PR resolves [GRO-1274]
Fixes launch blocking bug from Sprintly Release QA session (notion card [here](https://www.notion.so/artsy/OnboardingV2-Android-OS-back-button-can-navigate-back-from-final-screens-e20b363eaef64f8b83573569e4ce50e0))
-
-
-
-
- prevent users to go back on Follow / Gene / Thank you onboarding screens - gkartalis
-
</details>
[GRO-1274]: https://artsyproduct.atlassian.net/browse/GRO-1274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GRO-1274): Prevent users from using the hardware android button onboarding

---

src/app/Scenes/ReverseImage/Screens/Camera/Components/CameraButtons.tsx
src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
src/app/Scenes/ReverseImage/types.ts

This PR resolves [FX-4189]
Add the ability to select an image on the user's device from the library for image search
https://user-images.githubusercontent.com/3513494/186924100-89a32f85-efc2-4259-8d77-696ee657437e.mp4
https://user-images.githubusercontent.com/3513494/186925291-e118513a-1df1-45ec-80d6-6624d6b49203.MP4
- The user can select an image on the device from the library
-
- Add the ability to select an image from the library for reverse image search - dimatretyak
-
-
-
</details>
[FX-4189]: …

feat(FX-4189): Add the ability to select an image from the library for reverse image search

---

ios/Podfile.lock
package.json
yarn.lock

not a chore, but an update.
-
-
-
-
-
-
</details>

chore: upgrade view-shot

---

src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingSocialPick.tests.tsx
src/app/Scenes/Onboarding/OnboardingSocialLink.tests.tsx
src/app/Scenes/Onboarding/OnboardingSocialLink.tsx
src/app/Scenes/Onboarding/OnboardingSocialPick.tsx

Hides Sign In with Apple on unsupported iOS versions.
- Sign In with Apple should be hidden on iOS devices running iOS 12 and below
- Sign In with Apple should not be hidden on all other iOS versions
-
-
- Hide Sign In with Apple on iOS < 13 - Brian 
-
-
</details>

fix: hide apple sign in on iOS <13

---

src/app/Scenes/Onboarding/OnboardingV2/OnboardingWelcome.tsx

|iphone8|iphone 13 pro| Android with notch|Android without notch|
|![Simulator Screen Shot - iPhone 8 - 2022-08-29 at 19 12 46](https://user-images.githubusercontent.com/21178754/187263209-3a5925ea-738c-4712-a251-d66f0ea12c49.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-08-29 at 19 12 59](https://user-images.githubusercontent.com/21178754/187263136-30abf7b6-7935-4817-90db-8c97614b72a6.png)|![Screenshot_1661794826](https://user-images.githubusercontent.com/21178754/187264188-5c8c9cd1-1d93-4cb1-b51d-899056dda746.png)|![Screenshot_1661794826](https://user-images.githubusercontent.com/21178754/187264188-5c8c9cd1-1d93-4cb1-b51d-899056dda746.png)|
This PR resolves [GRO-1274]
-
-
- fix android with notch cutting onboarding …

fix: android cut off welcome screen when having notches

---

ios/Artsy/App_Resources/Info.plist

This pr solves the issue that we had in iOS devices when switching the device theme to dark mode, the status bar was disappearing, but with this fix, it is fixed.
-
-
-
-  dark satatusbar for eigen ios by default - practice-mobile
-
-
</details>

feat: dark satatusbar for eigen ios by default

---

package.json
yarn.lock

-------
-
-
-
-
-
-
</details>

chore: tiny upgrade of dep

---

src/app/utils/renderMarkdown.tests.tsx

fix: typescript?

---

src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx

Fix Broken build on main after releasing the new onboarding.
- We are no longer returning the old onboarding but instead the new onboarding
-
-
#nochangelog 

fix: broken main build after onboarding release

---

src/app/Components/Artist/ArtistInsights/MarketStats.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
src/app/utils/marketPriceInsightHelpers.tsx

Adjust MyC insights sell-through rate formatting.
| --- | --- |
| <img width="288" alt="Screenshot 2022-09-01 at 16 28 06" src="https://user-images.githubusercontent.com/4691889/187939216-b4d6f33a-9fc1-456f-87b6-a48bc0fd7b05.png">|<img width="322" alt="Screenshot 2022-09-01 at 16 33 02" src="https://user-images.githubusercontent.com/4691889/187940412-5b88a9dd-f721-4daa-95cf-d21e6d8cac85.png"> |
-
-
-
-
-
-
</details>

fix: Adjust MyC insights sell-through rate formatting

---

package.json
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
src/app/Scenes/MyCollection/Screens/Insights/providers/MedianSalePriceChartDataContext.tsx
src/palette/elements/LineGraph/ScatterPointsContainers.tsx
src/setupJest.ts
yarn.lock

Adds Career Highlight to Median Sales Graph
https://user-images.githubusercontent.com/18648835/187254796-05db4be6-3eb2-4f39-82fa-3d6df045904c.mp4
This PR resolves [CX-2646]
-
-
- Added career highlights to Median sales graph - kizito
-
-
-
</details>
[CX-2646]: https://artsyproduct.atlassian.net/browse/CX-2646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2646): add career highlights to graph

---

src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
src/palette/elements/LineGraph/LineGraphHeader.tsx

- PR updates the copy when we have no data for the selected timeframe.
<p>
</p>
This PR resolves [CX-2828]
-
-
- Update empty graph copy - kizito
-
-
-
</details>
[CX-2828]: https://artsyproduct.atlassian.net/browse/CX-2828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2828): change empty graph copy

---

src/app/AppRegistry.tsx
src/app/navigation/ModalStack.tsx

https://user-images.githubusercontent.com/3513494/187684142-c43cc15f-2946-4b98-bbb5-4d7e5eb25b6e.mov
https://user-images.githubusercontent.com/3513494/187684190-f83a3373-b191-41e5-9cd9-56ae308f4465.mov
-
-
-
-
-
-
</details>

feat: support fullscreen mode for modal screens

---

src/app/Components/Gene/Biography.tests.tsx
src/app/Components/Tag/About.tests.tsx
src/app/Components/WorksForYou/Notification.tests.tsx
src/app/Scenes/Artwork/Components/AboutArtist.tests.tsx

Fixes some relay tests
-
-
-
-
-
-
</details>

test: fix some relay tests

---

.secrets.baseline
src/app/Scenes/AuctionResult/AuctionResult.tests.tsx
src/app/Scenes/Fair/FairExhibitors.tests.tsx
src/app/tests/resolveMostRecentRelayOperation.ts

test: more relaytest fixes

---

src/palette/elements/LineGraph/LineGraphChart.tsx

- fixes label space on android
This PR resolves [CX-2900]
-
-
- 
-
- Adjust label space in chart on android - kizito
-
</details>
[CX-2900]: https://artsyproduct.atlassian.net/browse/CX-2900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2900): fix label space in chart

---

src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx

- center the text overlay on the graph
- 
<p>
</p>
This PR resolves [CX-2898]
-
-
- center graph no data text - kizito
-
-
-
</details>
[CX-2898]: https://artsyproduct.atlassian.net/browse/CX-2898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2898): center graph no data text

---

src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx

make the camera always active when the `DTShowDebugReverseImageView` dev toggle is enabled to check if this is the cause of [this error](https://artsy.slack.com/archives/C03RKQGMHUJ/p1661174765611519?thread_ts=1661174741.411159&cid=C03RKQGMHUJ)
-
-
-
-
-
- make camera always active when the `DTShowDebugReverseImageView` dev toggle is enabled - dimatretyak
</details>

chore: make camera always active when dev toggle is enabled

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx

- This PR fixes some UI issues related to career highlights
- Groups National Pavillion under Biennial Inclusion
This PR resolves [CX-2895]
This PR resolves [CX-2896]
-
-
- Fix Career Highlight UI issues - kizito
-
-
-
</details>
[CX-2895]: https://artsyproduct.atlassian.net/browse/CX-2895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2896]: https://artsyproduct.atlassian.net/browse/CX-2896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

fix: Fix Career Highlight UI issues

---

src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
src/app/utils/marketPriceInsightHelpers.tsx
src/palette/elements/LineGraph/LineGraph.tsx
src/palette/elements/LineGraph/LineGraphChart.tsx

- This PR changes the color of the highlight icon
<p>
</p>
This PR resolves [CX-2894]
-
-
- Change Highlight Icon Color - kizito
-
-
-
</details>
[CX-2894]: https://artsyproduct.atlassian.net/browse/CX-2894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2894): Change Highlight Icon Color

---

src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx

This PR adjusts the following:
- Makes the first category in MedianAuctionRails highlighted when the artist is pressed
- Adjusts the space between items
This PR resolves [CX-2867]
This PR resolves [CX-2866]
-
-
- fixed tappable area and spacing in MedianAuctionRailsItem - kizito
-
-
-
</details>
[CX-2867]: https://artsyproduct.atlassian.net/browse/CX-2867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2866]: …

fix(CX-2867): fix tappable area and spacing in MedianAuctionRailsItem

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
src/palette/elements/Radio/RadioButton.tsx

Make unit change experience better at MyC add works flow
**Before**
https://user-images.githubusercontent.com/11945712/189301424-16530567-14c5-49aa-8a6e-4780b37d1000.mov
**After**
https://user-images.githubusercontent.com/11945712/189301446-89a2f92b-7065-4432-9468-af3364216af0.mov
This PR resolves [CX-2892]
- Make tappable area better at changing units inside add works flow at MyC - mounir
-
-
-
</details>
[CX-2892]: https://artsyproduct.atlassian.net/browse/CX-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

fix(CX-2892): make unit change experience better at add works flow

---

src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx

-
-
-
-
-
- additional checks for reverse image photos picker flow - dimatretyak
</details>

chore: additional checks for reverse image photos picker flow

---

src/app/App.tsx
src/app/NativeModules/ArtsyNativeModule.tsx
src/app/Scenes/Onboarding/OnboardingWelcome.tsx
src/app/Scenes/ReverseImage/ReverseImage.tsx

| ![before](https://user-images.githubusercontent.com/3513494/189325085-95e29eb5-600d-4ab1-b685-8228b5bc7586.png) | ![after](https://user-images.githubusercontent.com/3513494/189325123-93a91fff-2037-48d6-84f3-a1423f63ac6a.png) |
https://user-images.githubusercontent.com/3513494/189325466-b9ba14a0-ec94-47d0-88ea-0a3d4ff610ac.mp4
-
-
-
-
-
- set dark navigation bar color for reverse image screens - dimatretyak
</details>

feat: set dark navigation bar color for reverse image screens

---

src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
src/app/store/config/features.ts

- Feature flags for Median Auction Screen and Chart 
This PR resolves [CX-2920]
-
-
-
-
-
- Feature flags for Median Auction Screen and Chart - kizito
</details>
[CX-2920]: https://artsyproduct.atlassian.net/browse/CX-2920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(2920): Feature flags for Median Auction Screen and Chart

---

package.json
src/app/Scenes/MyCollection/Screens/Insights/Components/MedianSalePriceChartTracking.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
yarn.lock

- Add tracking to the MedianAuctionScreen and other median auction chart interactions
- 
This PR resolves [CX-2919]
-
-
-
-
-
- Track Median Auction Screen and Chart Interactions - kizito
</details>
[CX-2919]: https://artsyproduct.atlassian.net/browse/CX-2919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2919): Track Median Auction Screen and Chart Interactions

---

src/app/Scenes/ReverseImage/ReverseImage.tsx

https://user-images.githubusercontent.com/3513494/189354456-ef3ea25c-5840-42c0-8703-c3591d6acec9.mp4
https://user-images.githubusercontent.com/3513494/189355347-3ea4f920-d34c-42c4-9e5d-1459c1233471.mp4
https://user-images.githubusercontent.com/3513494/189361978-695b4980-2ce2-4224-9a2e-50b9bead41ca.mp4
https://user-images.githubusercontent.com/3513494/189355485-bf237cf0-d3f7-4f0f-b201-e67e46b0fcef.mp4
https://user-images.githubusercontent.com/3513494/189355553-3e82cf9a-03f0-4786-a97e-294b2c0a32a7.mp4
https://user-images.githubusercontent.com/3513494/189363359-49374b6f-e918-4468-81bf-ae951a3d27f9.mp4
-
-
- set white color for status bar icons when reverse image screen is focused - dimatretyak
-
-
-
</details> …

feat: set white color for status bar icons when reverse image screen is focused

---

src/app/Scenes/ReverseImage/ReverseImage.tsx

-
-
-
-
-
- update navigation color on focus for reverse image screen - dimatretyak
</details>

chore: update navigation color on focus for reverse image screen

---

src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx

This PR adds a loading state to the function handling the sending of an inquiry to prevent it from firing multiple times when clicked repeatedly.
_**NOTE**: This whole file is a bit antiquated/of a mess. I'm creating a separate ticket to refactor/clean to keep the scope small._
This PR resolves [NX-3280]
On an artwork, tap the "Contact Gallery" button, write in a message, and rapidly press "Send."
Before: multiple `InquiryRequests`, and subsequently `Conversations`, were created.
After: only one should be created.
-Only one `InquiryRequest` should be created, despite repeated taps to the "send" button.
-Prevent the creation of multiple identical inquiries by adding a loading state - joel
</details>
Need help with …

fix(NX-3280): Adds loading state to fix multiple inquiry sends

---

src/app/Scenes/ReverseImage/ReverseImage.tsx
src/app/Scenes/ReverseImage/ReverseImageContext.tsx
src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageArtworksRail.tsx
src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageMultipleResults.tsx
src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
src/app/Scenes/ReverseImage/types.ts

Small changes that add context to the reverse image screen to be able to access this data at any time
-
-
-
-
-
- add context for reverse image screen - dimatretyak
</details>

feat: add context for reverse image screen

---

src/app/Components/Toast/ToastComponent.tsx
src/app/Components/Toast/toastHook.tsx
src/app/tests/renderWithWrappers.tsx

##before:
##after:
-
-
-
-
-
-
</details>

fix: middle toast layout

---

LICENSE

chore: update license date

---

.circleci/config.yml
fastlane/Fastfile
fastlane/Pluginfile

We should downgrade sentry fastlane plugin on CI to 1.12.2. We currently use 1.13.0. And it seems to be problematic. See this issue: https://github.com/getsentry/sentry-fastlane-plugin/issues/161
If issue still persists, we should consider removing or moving the sentry step in ship_beta_android_play_store lane to the last until we can determine what the problem really is.
-
-
-
-
-
-  Fix Firebase non-incrementing build version issue - kizito
</details>

fix(Firebase AppDistribution): Fix Firebase non-incrementing build version issue

---

fastlane/Fastfile

one of possibly many attempts to fix android beta issues.
-
-
-
-
-
- don't upload changelogs when updating android betas - Brian
</details>

fix: don't upload changelogs in supply #trivial

---

fastlane/Fastfile

stops retaining old android versions for now to fix the android beta issues, note this means the specific release script won't work until we fix this. 
-
-
-
-
-
-
</details>

fix: don't retain old android versions for now #trivial

---

src/app/Components/ArtworkFilter/Filters/KeywordFilter.tsx

https://user-images.githubusercontent.com/3513494/190169882-3c452516-202e-47f8-81af-df7523bc49ab.mp4
https://user-images.githubusercontent.com/3513494/190169301-8f3d400b-204c-4792-a216-9265f6f989a8.mp4
This PR resolves [FX-4221]
-
-
-
-
-
-
</details>
[FX-4221]: https://artsyproduct.atlassian.net/browse/FX-4221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4221): "Show results" does not work after applying filters in Insights

---

ios/Artsy/View_Controllers/Auction/AuctionInformationViewController.swift

This PR resolves [MOPLAT-420]
This spotlight indexing code is interfering with scroll performance in the live auctions info modal.
After upgrading this modal to a full screen modal recently it started interfering even more and caused the app to hang completely. Not 100% on the why, maybe we need to do this work on a background thread but since this is a fairly niche feature let's just remove it for now. 
-
-
-
- Fix freeze in live auctions info modal - Brian
-
-
</details>
[MOPLAT-420]: …

fix: remove spotlight indexing code interfering with scrolling

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx

This PR resolves an issue where the estimate text is cropped on android
#nochanges #nochangelog

fix: cropped text for recently sold artworks

---

src/app/navigation/NavStack.tsx

See more context here: https://artsy.slack.com/archives/C02BAQ5K7/p1663316451086229
https://user-images.githubusercontent.com/3513494/190615758-990a29a7-8d00-4c5f-aaeb-04518d1b8ed5.mp4
https://user-images.githubusercontent.com/3513494/190615796-858d445c-76b5-4c13-94e8-eeb943d45dee.mp4
https://user-images.githubusercontent.com/3513494/190617238-5f8fa707-e7dd-4446-8be8-f6b269a5c86b.mp4
-
-
-
-
-
- lock orientation to "portrait" - dimatretyak
</details>

fix: lock orientation to "portrait"

---

.secrets.baseline
src/app/Scenes/MyCollection/MyCollection.tests.tsx
src/app/Scenes/MyCollection/MyCollection.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx

This PR updates the tracking events to use cohesion interfaces instead of events 
This is a follow-up to the work on artsy/cohesion#354
-
-
-
-
-
-
</details>

fix: Update deprecated tracking events

---

src/app/Components/Artist/ArtistInsights/ArtistInsights.tests.tsx
src/app/Scenes/Artist/Artist.tests.tsx
src/app/Scenes/Artist/SearchCriteria.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/Message.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/Preview/ArtworkPreview.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/Preview/Attachment/ImagePreview.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/Preview/Attachment/PDFPreview.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/Preview/ShowPreview.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tests.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
src/app/Scenes/Tag/TagHeader.tests.tsx

fixes some relay tests, 50 to go
-
-
-
-
-
-
</details>

test(refactor): relay test refactor fixes

---

app.json

This PR sets the app version to 8.1.2
#nochangelog

chore: sets app version to 8.1.2

---

src/app/Scenes/MyCollection/MyCollection.tsx

Change add artwork button copy.
This PR resolves [CX-2792]
-
-
- Change add artwork button copy - ole
-
-
-
</details>
[CX-2792]: https://artsyproduct.atlassian.net/browse/CX-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Change add artwork button copy

---

src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx

This is a sibling PR to https://github.com/artsy/force/pull/10983 and updates Eigen in the same way for the same reasons.
https://artsyproduct.atlassian.net/browse/GRO-1297
/cc @artsy/grow-devs @shaq31415926 @isakelaris

feat: Increase max number of works per artist for new for you GRO-1297

---

src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx

when you take a picture and quickly go back (while it is being processed), it returns to the camera and then proceeds to the processing results
* [Card with issue](https://www.notion.so/artsy/when-I-take-a-picture-and-quickly-go-back-while-it-s-processing-it-goes-back-to-the-camera-and-th-f24af9c6b3ef4a6294e8ae55b2d0030f)
* [Slack message](https://artsy.slack.com/archives/C0420DYTHLK/p1663263984361749)
https://user-images.githubusercontent.com/3513494/191318847-04afb546-5b7f-4ce3-a71d-3240334bc0bf.mp4
https://user-images.githubusercontent.com/3513494/191318172-690ccd25-128b-4bda-b28f-18e6452a4fa6.mp4
-
-
-
-
-
- ignore search results when component was unmounted - dimatretyak
</details> …

chore: ignore search results when component was unmounted

---

src/app/Scenes/ReverseImage/ReverseImage.tsx

When navigating back after a successful match. The camera doesn't seem to reactivate
https://user-images.githubusercontent.com/3513494/191290770-025b14dd-11f8-4465-bbc8-9f8ad10eb5bf.mp4
* [Issue 1](https://www.notion.so/artsy/camera-not-opening-when-taking-a-second-photo-on-android-a752e046100c4da6b69b610d8d012170)
* [Issue 2](https://www.notion.so/artsy/Sometimes-on-Android-when-I-couldn-t-find-an-artwork-the-camera-screen-gets-white-and-I-have-to-clo-d26cb1723d1944b4a212261cfdf991f5)
* [Issue 3](https://www.notion.so/artsy/the-screen-turns-black-after-going-back-after-taking-a-pic-edited-a82d44e59beb407bb00d145aaac0f47a)
* [Issue 4](https://www.notion.so/artsy/it-wasn-t-the-easiest-to-scan-then-do-something-else-on-my-phone-and-then-get-back-to-scanning-7fc66c4197564a20a3b3a648ef638080) …

fix: camera doesn't seem to reactivate when taking a photo on some android devices

---

src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
src/app/store/config/features.ts

* Remove debug dev toggle (#7260)
* Use Sentry for errors
-
-
-
-
-
- remove debug dev toggle, use sentry for errors on reverse image screens - dimatretyak
</details>

refactor: remove debug dev toggle, use sentry for errors on reverse image screens

---

src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx

This PR resolves [DO-461]
-
-
-
-
-
-
</details>
[DO-461]: https://artsyproduct.atlassian.net/browse/DO-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DO-461): add bonhams to filter list

---

src/app/Components/Home/ArtistRails/ArtistRail.tsx
src/app/Scenes/ReverseImage/ReverseImage.tsx
src/app/Scenes/ReverseImage/ReverseImageContext.tsx
src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
src/app/utils/nextTick.ts

Related PR: artsy/eigen#7374
* [Issue 1](https://www.notion.so/artsy/camera-not-opening-when-taking-a-second-photo-on-android-a752e046100c4da6b69b610d8d012170)
* [Issue 2](https://www.notion.so/artsy/Sometimes-on-Android-when-I-couldn-t-find-an-artwork-the-camera-screen-gets-white-and-I-have-to-clo-d26cb1723d1944b4a212261cfdf991f5)
* [Issue 3](https://www.notion.so/artsy/the-screen-turns-black-after-going-back-after-taking-a-pic-edited-a82d44e59beb407bb00d145aaac0f47a)
* [Issue 4](https://www.notion.so/artsy/it-wasn-t-the-easiest-to-scan-then-do-something-else-on-my-phone-and-then-get-back-to-scanning-7fc66c4197564a20a3b3a648ef638080)
-
-
-
-
-
- camera doesn't seem to reactivate when taking a photo on some android devices …

fix: camera doesn't seem to reactivate when taking a photo on some android devices (attempt 2)

---

src/app/Scenes/ReverseImage/Components/HeaderBackButton.tsx
src/app/Scenes/ReverseImage/Screens/ArtworkNotFound/ReverseImageArtworkNotFoundScreen.tsx
src/app/Scenes/ReverseImage/Screens/Camera/Components/CameraGrantPermissions.tsx
src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageMultipleResults.tsx
src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx

Touchable area for the back button on the camera screen is too small, was kinda hard to press it some times
This PR resolves [Notion card](https://www.notion.so/artsy/touchable-area-for-the-back-button-on-the-camera-screen-is-too-small-was-kinda-hard-to-press-it-som-d28c2b352ff44e60a7bb84d36387755a)
-
-
-
-
-
-
</details>

chore: increase touchable area for the back button

---

src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

fix: SWA android crash

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx

Hide Get Price Estimate CTA when artwork is submitted.
This PR resolves [CX-2935]
-
-
- Hide Get Price Estimate CTA when artwork is submitted - ole
-
-
-
</details>
[CX-2935]: https://artsyproduct.atlassian.net/browse/CX-2935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Hide Get Price Estimate CTA when artwork is submitted

---

src/app/Scenes/SellWithArtsy/Components/Header.tsx
src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
src/app/Scenes/SellWithArtsy/Components/WhySellWithArtsy.tsx
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

Adjust SWA copy spacing and font size.
[Slack Thread for context](https://artsy.slack.com/archives/C01B2P6LJUU/p1664268146882799)
-
-
-
-
-
-
</details>

fix: Adjust SWA copy spacing and font size

---

src/app/Scenes/SellWithArtsy/Components/Header.tsx

Adjust SWA header subtitle copy.
-
-
-
-
-
-
</details>

fix: Adjust SWA header subtitle copy

---

src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
src/app/Scenes/SellWithArtsy/Components/SellWithArtsyCustomRecentlySold.tsx
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

Adjust SWA spacing.
-
-
-
-
-
-
</details>

fix: Adjust SWA spacing

---

src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

This PR solves a margin that shows up above the tabbar inside the SWA landing page on Android
|--|--|--|
| iOS (no change) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-27 at 18 12 12](https://user-images.githubusercontent.com/20655703/192580670-18a6b1a7-fcf9-466d-95ff-7bc133233e58.png) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-27 at 18 12 45](https://user-images.githubusercontent.com/20655703/192580696-4e00e738-3e7b-4f65-9f8c-c021b4403204.png) |
| Android | ![image](https://user-images.githubusercontent.com/20655703/192580589-eb7e75ee-f0d1-4b40-a53a-0e510f53f764.png) | ![image](https://user-images.githubusercontent.com/20655703/192580608-59573aa1-17c0-46b0-9b9f-899e761d4bfd.png) |
-
-
-
- …

fix: SWA landing page margin issue in Android

---

patches/react-native-reanimated+2.9.1.patch
src/app/AppRegistry.tsx
src/app/Components/Artist/ArtistHeaderFloatingButtons.tsx
src/app/Components/HeaderButton.tsx
src/app/Components/SearchImageHeaderButton/SearchImageHeaderButton.tsx
src/app/Scenes/Fair/Fair.tsx

When navigating to a partner show page and scrolling further down, the ➕ button of the reverse image search overlaps the sort and filter sticky button
https://user-images.githubusercontent.com/3513494/192252942-29a6ca70-7e20-480f-938c-548e97de56e4.mp4
https://user-images.githubusercontent.com/3513494/192253008-17a49622-4b71-4639-8b31-e26d5cb6b45c.mp4
https://user-images.githubusercontent.com/3513494/192250332-ac82b681-0c6c-46a7-9e87-4d15fe4a6623.mp4
https://user-images.githubusercontent.com/3513494/192250928-ea97d5bb-3049-47d1-a33c-3939508e7b23.mp4
-
-
- hide header buttons on Fair screen - dimatretyak
-
-
-
</details> …

feat: hide header buttons on Fair screen

---

src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

Decrease the SWA screen spacing below header.
-
-
-
-
-
-
</details>

fix: Decrease the SWA screen spacing below header

---

src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx

By default Relay's `useLazyLoadQuery` uses `store-or-network` as a fetch policy. This PR changes the fetch policy to `store-and-network` on MyC screens to make sure the data is reloaded every time the user opens one of the screens.
[Relay Docs](https://relay.dev/docs/api-reference/use-lazy-load-query/)
This PR resolves [CX-2969]
-
-
-
-
-
-
</details>
[CX-2969]: https://artsyproduct.atlassian.net/browse/CX-2969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Change fetch policy to store-and-network on MyC screens

---

src/app/AppRegistry.tsx
src/app/Scenes/Activity/Activity.tests.tsx
src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/Activity/ActivityList.tsx
src/app/Scenes/Activity/ActivityTabSubheader.tsx
src/app/Scenes/Activity/types.ts

https://user-images.githubusercontent.com/3513494/193029358-73d34ca2-49b0-45e3-9396-59eeab68418f.mp4
https://user-images.githubusercontent.com/3513494/193030466-7db96a63-bb7d-4052-8a4c-604973b67572.mp4
This PR resolves [FX-4304]
-
-
- add tabs for activity screen - dimatretyak
-
-
-
</details>
[FX-4304]: https://artsyproduct.atlassian.net/browse/FX-4304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4304): add activity panel tabs

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx

This PR resolves [CX-2842]
This PR changes the onSuccess behaviour when editing a My Collection artwork to go back to artwork details screen instead of My Collection screen
-
-
-
-
-
- update MyC edit artwork onSuccess behaviour - mrsltun
</details>
Uploading CX-2842.mp4…
[CX-2842]: https://artsyproduct.atlassian.net/browse/CX-2842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2842): Update onSuccess behavior when editing a MyC artwork

---

package.json
yarn.lock

build(deps): bump @testing-library/react-native from 10.1.1 to 11.2.0
-
-
-
-
-
- bump @testing-library/react-native from 10.1.1 to 11.2.0 - gkartalis
</details>

build(deps): bump @testing-library/react-native from 10.1.1 to 11.2.0

---

fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/release_notes.txt
src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
src/app/Scenes/SellWithArtsy/Components/Header.tsx
src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
src/app/Scenes/SellWithArtsy/Components/SellWithArtsyCustomRecentlySold.tsx
src/app/Scenes/SellWithArtsy/Components/WhySellWithArtsy.tsx
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

release candidate
-
-
-
-
-
-
</details>

build(release): 8.1.2 release

---

app.json

Prepare for 8.1.3
-
-
-
-
-
-
</details>

chore: prepare for 8.1.3

---

package.json
src/app/Components/MenuItem.tsx
src/app/Components/SectionTitle.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
src/app/Scenes/Artwork/Components/AboutArtist.tsx
src/app/Scenes/Artwork/Components/AboutWork.tsx
src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
src/app/Scenes/Artwork/Components/ArtworkHistory.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/app/Scenes/Artwork/Components/AuctionPrice.tsx
src/app/Scenes/Artwork/Components/ContextCard.tsx
src/app/Scenes/Artwork/Components/PartnerCard.tsx
src/app/Scenes/MyBids/MyBids.tsx
src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
src/app/Scenes/Onboarding/OnboardingV2/OnboardingWelcome.tsx
src/app/Scenes/Onboarding/OnboardingWelcome.tsx
src/app/utils/AdminMenu.tsx
src/palette/Theme.tsx
src/palette/atoms/colors.stories.tsx
src/palette/elements/Message/Message.tsx
yarn.lock

@olerichter00 make any extra changes you need!
-
-
-
-
-
-
</details>

feat: upgrade palette-tokens

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx

This PR resolves [CX-2837]
| --- | --- |
| ![before](https://user-images.githubusercontent.com/36167539/193585527-c8172086-b44e-455f-b443-ea64b1cfd16f.png) | ![after](https://user-images.githubusercontent.com/36167539/193585551-e874668c-0985-4fe1-b00c-7fa3eca4f0fe.png) |
-
-
-
-
- Fix broken padding on full screen career highlights modal on Android -daria
-
</details>
[CX-2837]: https://artsyproduct.atlassian.net/browse/CX-2837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

fix(CX-2837): Padding is broken on full screen career highlights modal on Android

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx

This PR resolves [CX-2789, CX-2791]
https://user-images.githubusercontent.com/36167539/193616792-2085f257-d8e7-4adf-ab8f-0d52c05a32e4.mp4
-
-
- Submit to Sell - UI and Copy Update; Hide Learn More CTA (Submit Art from your collection) if not P1 artist -daria
-
-
-
</details>

fix(CX-2789, CX-2791) : change submit for sale section, show section only if P1 artist

---

docs/getting_started.md

based on [this thread](https://artsy.slack.com/archives/C02BAQ5K7/p1663795125573209), xcode 14 is the new hotness

Update getting_started.md with correct xcode version

---

src/app/Components/SearchInput.tsx

Align search input cancel button correctly when error message is shown.
| --- | --- |
|![simulator_screenshot_4EE7954B-AD09-47BB-B9C4-2209C099DD17](https://user-images.githubusercontent.com/4691889/193364049-e69ff4a9-fcde-4d84-aad2-b81c7867bbed.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-10-01 at 00 17 40](https://user-images.githubusercontent.com/4691889/193364002-25a4f0ef-dc4a-4797-8b48-49c348cc37f6.png)|
This PR resolves [CX-2949]
-
-
-
-
-
-
</details>
[CX-2949]: …

fix: Align search input cancel button correctly

---

.secrets.baseline
src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/ArtworkRail/SmallArtworkRail.tsx

This PR adds a font-scaling factor to the artwork rail text height to avoid the text being cut off.
| --- | --- |
|![Simulator Screen Shot - iPhone 13 Pro - 2022-10-05 at 15 02 58](https://user-images.githubusercontent.com/4691889/194066977-5ec098ac-9f4e-4801-a7a3-1eb6868ec851.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-10-05 at 14 57 02](https://user-images.githubusercontent.com/4691889/194067004-317d9436-22e4-4cf4-9280-977b907b6d4d.png)|
| --- | --- |
|![Simulator Screen Shot - iPhone 13 Pro - 2022-10-05 at 14 50 22](https://user-images.githubusercontent.com/4691889/194067005-b7f570ec-da14-4e9f-aff4-913dd4ae4104.png) |![Simulator Screen Shot - iPhone 13 Pro - 2022-10-05 at 15 02 34](https://user-images.githubusercontent.com/4691889/194067020-2adedefb-e5d9-4fb …

fix: Adjust artwork rail height when font scaling is enabled

---

src/app/Components/OpaqueImageView/createGeminiUrl.tsx

Enables web on iOS now that `SDWebImage` version supports it 
-
-
-
- enable webp images on iOS - gkartalis
-
-
</details>

feat: enable webp on iOS

---

.secrets.baseline
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx

This PR resolves [CX-2990]
Adjust copy and spacing
-
-
- Submit to Sell - UI and Copy Update -daria
-
-
-
</details>
[CX-2990]: https://artsyproduct.atlassian.net/browse/CX-2990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2990): Submit to Sell - UI and Copy Update

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkArticles.tsx

Hiding the scroll bar on MyC featured articles rail to adjust to the look of all the other rails in the app.
-
-
- Hide scroll bar on MyC featured articles rail - ole
-
-
-
</details>

fix: Hide scroll bar on MyC featured articles rail

---

src/app/utils/AdminMenu.tsx
src/palette/elements/CollapseMenu/CollapseMenu.tsx
src/palette/elements/CollapseMenu/index.tsx

This PR makes small adjustments to the admin settings screen to make finding feature flags easier. 
https://user-images.githubusercontent.com/11945712/194364683-6cc65ba9-9664-44b8-9634-317e9bba0aeb.mov
-
-
-
- Improve presentation of admin settings screen - mounir
</details>

chore: improve admin settings screen

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx

The CTA "Request a price estimate" appears for every artwork by P1 artist, the demand rank condition is removed
This PR resolves [CX-2891]
-
-
- The CTA "Request a price estimate" appears for every artwork by P1 artist, the demand rank condition is removed -daria
-
-
-
</details>
[CX-2891]: https://artsyproduct.atlassian.net/browse/CX-2891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2891): change the condition to make the cta appear only P1

---

src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
src/app/Scenes/MyCollection/Screens/Insights/providers/MedianSalePriceChartDataContext.tsx

The BottomSheet randomly shows up on android when you select an artist to view their MedianSalePriceChart. This appears to be a longstanding react native BottomSheet issue on android. 
This PR changes our display logic and loads the BottomSheet only when a highlight has been selected instead of loading it before hand and making it visible when highlight has been selected.
Other approaches may include:
1. changing `android:windowSoftInputMode="adjustResize"` for MainActivity (which hosts the RN screens) in AndroidManifest to `android:windowSoftInputMode="adjustPan"` . But this approach might have unintended effect on how we handle KeyboardAvoiding view on android.
2. Set a timeout that forceCloses BottomSheet when we select a new artist - There will be a very jarring flicker and we cannot …

fix(CX-2965): Fix BottomSheet randomly showing up on ArtistSelect

---

docs/pull_request_template.md

This PR only moves "This PR resolves []" to be above the description
-
-
-
-
-
-
</details>

fix: 👼 PR template update

---

src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
src/app/utils/useStatusBarStyle.ts

This PR resolves an issue affecting the status bar and making it break on Android
https://user-images.githubusercontent.com/11945712/195144490-66695c47-f1dd-4708-b8f1-126da3caf33b.mov
-
-
- fix status bar issue on android - mounir
-
-
-
</details>

fix: status bar issue on android

---

src/app/Scenes/SavedSearchAlert/Components/Form.tsx

This PR resolves [FX-4370]
Removes Layout animation that was causing app to freeze
|Before|After|
|---|---|
|https://user-images.githubusercontent.com/21178754/195302770-b26bfcf1-c625-4e2a-92f0-d24709899a1f.mp4|https://user-images.githubusercontent.com/21178754/195302531-5f53db42-82ec-4a4c-a448-77747df54bc8.MP4|
-
-
- remove layout animation that was causing a bug - gkartalis
-
-
-
</details>
[FX-4370]: https://artsyproduct.atlassian.net/browse/FX-4370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

fix: remove layout animation that was causing a bug

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
src/app/navigation/routes.ts

This PR resolves [CX-2781]
Rename request-for-price-estimate to price-estimate.
-
-
-
-
-
-
</details>
[CX-2781]: https://artsyproduct.atlassian.net/browse/CX-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Rename request-for-price-estimate to price-estimate

---

scripts/setup-env-for-artsy

Noticed that if we mark a feature flag as ready for release in [features.ts](https://github.com/artsy/eigen/blob/main/src/app/store/config/features.ts) we have to run manually `./scripts/update-echo`.
I added it to `yarn setup:artsy` since I thought it was already included there 🤯
-
-
-
- add update echo script in setup:artsy - gkartalis
</details>

build(scripts): add update echo script in setup:artsy

---

src/app/Components/FullScreenLoadingImage.tsx
src/app/Scenes/Artwork/Components/InstagramStoryViewShot.tsx
src/app/Scenes/MyCollection/Components/ScreenMargin.tsx
src/app/Scenes/MyCollection/Screens/Insights/ActivateMoreMarketInsightsBanner.tsx
src/palette/Theme.tsx
src/palette/atoms/Spacer/Spacer.tsx
src/palette/elements/BorderBox/BorderBox.tsx
src/palette/elements/Box/Box.tsx
src/palette/elements/EntityHeader/EntityHeader.tsx
src/palette/elements/LineGraph/Axes.tsx

After some typescript revelations, we now have better types for color and space stuff. These will be part of @artsy/palette-mobile too, but for now adding them to eigen too.
The main difference is the editor autosuggest 🙌.
-
-
-
-
-
-
</details>

feat: add some types for autocomplete support

---

src/app/Scenes/Activity/ActivityEmptyView.tsx

This PR resolves [FX-4380]
Related Force PR: artsy/force#11170
| ![before](https://user-images.githubusercontent.com/3513494/196234227-0d981d8b-dcfc-4493-aadf-dd5c4c67cf9e.png) | ![after](https://user-images.githubusercontent.com/3513494/196234259-cd1af7c8-d3da-4d8b-8863-ee3c2d2353b7.png) |
-
-
-
-
-
- Change copy of Alert's tab empty state - dimatretyak
</details>
[FX-4380]: https://artsyproduct.atlassian.net/browse/FX-4380?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

feat(FX-4380): Change copy of Alert's tab empty state

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateScreen.tsx

This PR resolves [CX-2808]
Removed toast that confirms that the request for a price estimate is sent
When the request is sent, show an icon and text instead of a blue button
Kept two toasts that notify about: 1. error when no user; 2. error when the request for a price estimate failed
https://user-images.githubusercontent.com/36167539/196202132-7a36510d-bd6b-4df9-8a8a-13d3ef0b3e26.mp4
-
-
- Adjusted the request for a price estimate section in MyCollection Artwork to match the implementation in Force -daria
-
-
-
</details>
[docs]: …

feat(CX-2808): request a Price Estimate / App - UX/UI Update 3/3 (Request Sent update) [app]

---

docs/pull_request_template.md

feat: updating pull_request_template.md in mobile practice

---

src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx
src/app/store/config/features.ts

This PR resolves [CX-3014] 
Clean up AREnableMyCollectionInsightsMedianPrice.
-
-
-
-
</details>
[CX-3014]: https://artsyproduct.atlassian.net/browse/CX-3014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Clean up AREnableMyCollectionInsightsMedianPrice

---

src/app/Scenes/Sale/Components/RegisterToBidButton.tsx

Resolves the following:
- Approved to bid - checkmark not aligned ticket [here](https://www.notion.so/artsy/UNRELATED-Auctions-After-registering-to-bid-You-re-approved-to-bid-and-the-checkmark-are-not--58f4e3db26ea4c83b4c6a07c8797b6d0)
|Before|After|
|---|---|
|**Auctions approved to bid before**|**Auctions approved to bid after**|
|![Screenshot_2022-10-13-17-34-19-42_d3de0bcf20ed82f6ee9aa09aef394b51](https://user-images.githubusercontent.com/21178754/196625980-20a27645-2707-4d7c-a646-cc1bc40e2164.jpg)|![Simulator Screen Shot - iPhone 13 mini - 2022-10-19 at 09 20 43](https://user-images.githubusercontent.com/21178754/196625695-6e643a54-1e2e-4a1a-bcc8-2e81278ad1b9.png)|
- Approved to bid - checkmark not aligned - gkartalis …

fix: Approved to bid - checkmark not aligned

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx

This PR resolves [CX-2806]
Adjust request price estimate section design.
| | |
| --- | --- |
|![Simulator Screen Shot - iPhone 13 Pro - 2022-10-19 at 08 52 05](https://user-images.githubusercontent.com/4691889/196618345-69301ec3-df19-4ec5-8f81-f9522b149629.png) |![Simulator Screen Shot - iPhone 13 Pro - 2022-10-19 at 08 52 48](https://user-images.githubusercontent.com/4691889/196618357-9cf204d4-50a0-4eb1-8eb9-c6e372619719.png) |
-
-
- Adjust request price estimate section design - ole
-
-
-
</details> …

fix: Adjust request price estimate section design

---

src/app/AppRegistry.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateScreen.tsx
src/app/navigation/routes.ts

This PR resolves [CX-2807] 
| What | iOS | Android |
| Confirmation screen | ![ios-confirmation](https://user-images.githubusercontent.com/36167539/196706855-d36704cc-1321-4649-969f-5a56d3ab1d5f.png) | ![android-confirmation](https://user-images.githubusercontent.com/36167539/196706751-48c59b26-dd62-4fa9-83aa-61a0119f7f96.png) |
| Contact Information screen **before** | ![simulator_screenshot_5F30D2D9-C1EB-4900-AC72-3C3B63648F67](https://user-images.githubusercontent.com/36167539/196707408-2e320e77-3133-4826-9fca-7039b3a623aa.png) | ![android-contact-befor](https://user-images.githubusercontent.com/36167539/196707325-1863c430-a178-4059-a28c-63870e826c49.png) |
| Contact Information screen **after** | ![ios-contact](https://user-images.githubusercontent.com/36167539/1967 …

feat(CX-2807): add confirmation screen and correct cotact form

---

src/app/store/config/features.ts

This PR resolves [CX-3043]
- Add new request price estimate feature flag
-
-
-
- add new request price estimate feature flag - mounir
</details>
[CX-3043]: https://artsyproduct.atlassian.net/browse/CX-3043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add new request price estimate feature flag

---

src/app/Scenes/Artwork/Components/ArtworkHistory.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkHistory.tsx

This PR resolves [FX-4277]
Related PR: artsy/eigen#7483
| ![before](https://user-images.githubusercontent.com/3513494/196409852-a540dc89-8292-4325-9f3d-2d89e934f378.png) | ![after](https://user-images.githubusercontent.com/3513494/196409877-03c2d94a-f7db-4294-abb4-a454683083d1.png) | 
* update the styling of the ArtworkHistory component to match the [designs](https://www.figma.com/file/9DMfKOi5RuuBD2f49eB9nV/Artwork-page?node-id=2759%3A41361)
* change copy from “Exhibition History” to “Exhibition history”
-
- change Provenance / Exhibition History / Bibliography text styling - dimatretyak
-
-
-
</details>
[app …

feat(FX-4277): change Provenance / Exhibition History / Bibliography text styling

---

src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx

https://user-images.githubusercontent.com/3513494/196940564-b4714fe8-bc78-49e3-a11d-8fda5590064a.mp4
https://user-images.githubusercontent.com/3513494/196943084-e6a84668-1e52-4730-a416-a7ac761e61bc.mp4
-
-
-
- update artwork loading placeholder - dimatretyak
</details>

chore: update artwork loading placeholder

---

src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/PartnerCard.tests.tsx
src/app/Scenes/Artwork/Components/PartnerCard.tsx
src/app/Scenes/Artwork/Components/Questions.tests.tsx
src/app/Scenes/Artwork/Components/Questions.tsx

This PR resolves [FX-4308]
- Change copy of title from `At gallery` → `Gallery`
- update the styles of the title to match [figma specs](https://www.figma.com/file/9DMfKOi5RuuBD2f49eB9nV/Artwork-page?node-id=2759%3A41361)
- remove follow partner button
- move [Questions about this piece?](https://www.figma.com/file/9DMfKOi5RuuBD2f49eB9nV/Artwork-page?node-id=2759%3A41361) / [contact gallery button](https://www.figma.com/file/9DMfKOi5RuuBD2f49eB9nV/Artwork-page?node-id=2759%3A41361)
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 13 - 2022-10-18 at 14 43 56](https://user-images.githubusercontent.com/21178754/196433864-dfc8e0b3-6b3a-4c25-819e-2c9e17a6dfe6.png)|![Simulator Screen Shot - iPhone 13 - 2022-10-18 at 14 43 30](https://user-images.githubusercontent.com/21178754/196433873- …

feat(FX-4308): Artwork page, update PartnerCard styling

---

ios/Artsy/App_Resources/Artsy.Store.entitlements
ios/Artsy/App_Resources/Artsy.entitlements

- enable time sensitive notifs (iOS)
This PR resolves [FX-4343]
-
-
-
-
-
-
</details>
[FX-4343]: https://artsyproduct.atlassian.net/browse/FX-4343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: enable time sensitive notifs

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
src/app/utils/marketPriceInsightHelpers.tsx

This PR resolves [CX-3063] 
This PR removes an extra % that shows up in the Artist Market stats inside the artist Insights
|Screen|Before|After|
|--|--|--|
| My Collection Artwork (iOS) | ![Screenshot 2022-10-20 at 4 48 33 PM](https://user-images.githubusercontent.com/20655703/196983565-a173487f-3ba0-4e75-9789-37a700f69f4c.png) | ![image](https://user-images.githubusercontent.com/20655703/196980984-f7757854-ae6c-4cc4-9cc9-bee48b540091.png) |
| My Collection Artwork (Android) | ![Screenshot 2022-10-20 at 4 49 56 PM](https://user-images.githubusercontent.com/20655703/196983312-08eb4683-2ccd-4971-92cd-7f7594bf84ce.png) | ![image](https://user-images.githubusercontent.com/20655703/196981273-4973862f-f69d-4e96-a0f2-f4ac8be35365.png) |
| Artist Insights (iOS) | ![Screenshot 2022-10-20 at 4 49 …

fix(CX-3063): Remove extra `%` in the Artist Market Stats

---

docs/getting_started.md

Minor documentation update —
Now that we don't keep Relay generated artifacts checked in to the repo (ever since https://github.com/artsy/eigen/pull/6254) it seems necessary to run a manual `yarn relay` before being able to boot up the app.
- Update setup docs with `yarn relay`
</details>

docs: update setup docs with `yarn relay`

---

src/app/Scenes/Onboarding/OnboardingV2/Components/MarketingCollectionHeader.tsx

Makes CollectionHeader container slightly bigger
|Before|After|
|---|---|
|**smaller devices**|**smaller devices**|
|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-21 at 12 29 58](https://user-images.githubusercontent.com/21178754/197175953-7627e2c2-ea01-4a1b-8e1c-6a9cd0e233bd.png)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-21 at 12 29 04](https://user-images.githubusercontent.com/21178754/197175962-de6fcc6d-ca50-4edf-b4b3-f06ad207b3de.png)|
|**bigger devices**|**bigger devices**|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-10-21 at 12 30 01](https://user-images.githubusercontent.com/21178754/197175936-864a0c9c-67f7-48c1-8dcf-3fe2717cf376.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-10-21 at 12 29 …

fix: make CollectionHeader container slightly bigger

---

src/app/Components/SectionTitle.tsx
src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
src/app/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx

This PR resolves [FX-4282] 
Changing the titles of otherWorks, artistSeries grid, artist series rail in artwork screen to have `variant="md"`.
|OtherWorks|ArtistSeries Rail|ArtistSeriesMoreSeries|Other Works|Related Works|
|---|---|---|---|---|
|![Simulator Screen Shot - iPhone 14 Pro - 2022-10-24 at 13 28 27](https://user-images.githubusercontent.com/21178754/197516104-445de377-4f28-4fb4-a5db-f129b342606b.png)|![Simulator Screen Shot - iPhone 14 Pro - 2022-10-24 at 13 33 49](https://user-images.githubusercontent.com/21178754/197516668-30d18cc1-4a6e-472f-b55c-a44a8045fb8a.png)|![Simulator Screen Shot - iPhone 14 Pro - 2022-10-24 at 13 30 08](https://user-images.githubusercontent.com/21178754/197516126-0d8ed58d-caf6-4fda-93d0-bbe1ed90776e.png)|![Simulator Screen Shot - iPhone 14 Pro - …

refactor(FX-4282): change artwork section titles to have variant md

---

ios/Artsy/App_Resources/Info.plist

Updates our camera usage permission string to account for new use cases.
-
- Update camera usage description - Brian
-
-
</details>

fix: update camera usage description #trivial

---

src/app/Scenes/Onboarding/OnboardingV2/Components/MarketingCollectionHeader.tsx

Use spacer over fixed height in onboarding screens
|iOS|Android|
|---|---|
|![Simulator Screen Shot - iPhone 14 Pro - 2022-10-28 at 10 42 36](https://user-images.githubusercontent.com/21178754/198548821-2d8059c0-ffd6-4819-ac88-bef25500537f.png)|![Screenshot_1666948106](https://user-images.githubusercontent.com/21178754/198550149-6e8f44c0-28e3-460b-8c03-52056a635e20.png)|
|![Simulator Screen Shot - iPhone 14 Pro - 2022-10-28 at 10 43 25](https://user-images.githubusercontent.com/21178754/198548827-acb9a28b-4f01-4851-9165-41bd2dc847e8.png)|![Screenshot_1666948215](https://user-images.githubusercontent.com/21178754/198550454-a5590422-1863-417b-ba49-1eb7b19423f5.png)|
|![Simulator Screen Shot - iPhone 14 Pro - 2022-10-28 at 10 45 …

refactor: replace fixed heights with paddings

---

app.json

chore: bump version 8.2.1

---

src/app/Components/StickyTabPage/StickyTabPage.tsx
src/app/Scenes/Activity/Activity.tests.tsx
src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/Home/Components/ActivityIndicator.tests.tsx
src/app/Scenes/Home/Components/ActivityIndicator.tsx
src/app/Scenes/Home/Home.tests.tsx

This PR resolves [FX-4413] 
https://user-images.githubusercontent.com/3513494/198265150-3e7fd476-dbb1-416f-b47f-dfca4c64efcc.mp4
https://user-images.githubusercontent.com/3513494/198265261-8c0530a8-e9cc-4089-8861-39e496381a63.mp4
https://user-images.githubusercontent.com/3513494/198270249-dd1d3ba4-3b96-45ca-95ee-69fa99f85cab.mp4
-
-
-
- Activity Panel tracking - dimatretyak
</details>
[FX-4413]: https://artsyproduct.atlassian.net/browse/FX-4413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …

feat(FX-4413): Activity Panel tracking

---

src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
src/app/store/config/features.ts

This PR resolves [CX-3016] 
Remove AREnableMedianPriceChartCareerHighlights feature flag.
-
-
-
-
</details>
[CX-3016]: https://artsyproduct.atlassian.net/browse/CX-3016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Remove AREnableMedianPriceChartCareerHighlights feature flag

---

src/app/store/config/features.ts

- Preparing AREnableNewRequestPriceEstimateLogic for release
- AREnableNewRequestPriceEstimateLogic feature flag
-
-
-
</details>

AREnableNewRequestPriceEstimateLogic feature flag

---

src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
src/app/store/config/features.ts

This PR resolves [CX-3017] 
Remove My Collection phase feature flags.
-
-
-
-
</details>
[CX-3017]: https://artsyproduct.atlassian.net/browse/CX-3017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove My Collection phase feature flags

---

src/app/Scenes/Activity/ActivityItem.tests.tsx
src/app/Scenes/Activity/ActivityItem.tsx

| <img width="507" alt="before" src="https://user-images.githubusercontent.com/3513494/199225498-8ee9dfec-d079-4dac-8756-629caf62183f.png"> | <img width="507" alt="after" src="https://user-images.githubusercontent.com/3513494/199225419-27eba2cb-c9a6-4d1f-b499-205bb5338095.png"> | 
-
-
-
-
</details>

chore: remove artworks count

---

src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/Activity/ActivityList.tsx

* Pass correct `key` prop
* Use `store-and-network` fetch policy
* Use `StickTabPageRefreshControl`
-
-
-
-
</details>

chore: improvements for activity screen

---

src/app/Scenes/Activity/Activity.tsx
src/app/Scenes/Activity/ActivityList.tsx
src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
src/app/Scenes/Activity/types.ts
src/app/Scenes/Activity/utils/getNotificationTypes.ts

-
-
-
- small improvements for "mark all as read" button - dimatretyak
</details>

chore: small improvements for "mark all as read" button

---

src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
src/app/Scenes/Artwork/Components/ArtworkDetailsRow.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/app/Scenes/Artwork/Components/RequestConditionReport.tsx

This PR resolves [FX-4392] 
|Request condition report button|Lot on top of Artwork page|
|---|---|
|![Simulator Screen Shot - iPhone 14 Pro - 2022-10-31 at 15 54 43](https://user-images.githubusercontent.com/21178754/199038911-4c875f1f-41f8-436a-8327-97e4031ce2af.png)|![Simulator Screen Shot - iPhone 14 Pro - 2022-10-31 at 15 52 23](https://user-images.githubusercontent.com/21178754/199038913-12021848-a51c-4fc1-aaab-5131841540be.png)|
-  auction artwork screen minor style changes - gkartalis
-
-
-
</details> …

refactor(FX-4392): auction artwork screen

---

src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx

This PR resolves [FX-4374]
Recently we introduced new types of notifications:
- [One](https://artsyproduct.atlassian.net/browse/FX-4252)
- [Two](https://artsyproduct.atlassian.net/browse/FX-4255)
These notifications utilise a newly introduced user preference `receive_partner_show_notification` to either send or not push notifications. Since there is no way to opt out from such notifications, `receive_partner_show_notification` is set to false for all users by default, meaning that basically no one receives new notification at the moment.
This PR adds a switch to toggle  `receive_partner_show_notification`.
- New setting to toggle "New Shows for You"
-
-
-
</details> …

feat(FX-4374): new preference to allow opting out of partner show notifications

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx

This PR resolves [CX-2973] 
Move all required fields to top in artwork form.
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-11-02 at 15 53 26](https://user-images.githubusercontent.com/4691889/199522566-cdb906ab-3d2f-4ac7-92b4-85ba44fb8e0c.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-11-02 at 15 50 51](https://user-images.githubusercontent.com/4691889/199522393-37c456ca-c800-490a-a41e-7e6ca5ae8c9a.png) |
- Move all required fields to top in artwork form - ole
-
-
-
</details>
[docs]: …

feat: Move all required fields to top in artwork form

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
src/app/Scenes/Search/AutosuggestResults.tsx

This PR resolves [CX-3104] 
Change Artist Select screen copy.
-
-
-
-
</details>
[CX-3104]: https://artsyproduct.atlassian.net/browse/CX-3104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Change Artist Select screen copy

---

src/app/Scenes/Activity/ActivityEmptyView.tsx
src/app/Scenes/Home/Components/ActivityIndicator.tsx
src/palette/helpers/text.ts

- change "Set alerts for artworks you're hunting for." -> "Set alerts for artworks you're seeking”
- the quote marks around "Create Alert." in the body text should be curly quotes, with the period inside the quote marks.
- artworks you're hunting for → …artworks you’re hunting for curly apostrophe
- activity icon 24x24 px
|Empty message|Activity icon|
|---|---|
|![Simulator Screen Shot - iPhone 14 Pro - 2022-11-03 at 16 53 19](https://user-images.githubusercontent.com/21178754/199771104-90259d41-7910-455e-8066-1bdd0e4806ad.png)|![Simulator Screen Shot - iPhone 14 Pro - 2022-11-03 at 16 57 52](https://user-images.githubusercontent.com/21178754/199771004-b60a0415-ea96-4a47-b02e-5977c51b3c1f.png)|
- activity icon and copy …

fix(FX-4426): activity icon and copy changes

---

src/app/Scenes/Activity/ActivityTabPlaceholder.tsx

-
-
-
- update image size for activity item placeholder - dimatretyak
</details>

chore: update image size for activity item placeholder

---

src/app/store/config/features.ts

Echo PR: artsy/echo#336
-
-
-
- mark `AREnableActivity` as ready for release - dimatretyak
</details>

chore: mark `AREnableActivity` as ready for release

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx

Do not link to personal artist screen.
-
-
-
-
</details>

fix: Do not link to personal artist screen

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx

This PR resolves [CX-3103] 
Adjust My Collection form artwork select loading screen.
-
-
-
-
</details>
[CX-3103]: https://artsyproduct.atlassian.net/browse/CX-3103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: My Collection artist select loading screen

---

src/app/Components/OpaqueImageView/createGeminiUrl.tsx

Webp images are not supported on iOS 12 and below, so users on these versions are seeing images fail to load. This just adds an OS check and doesn't use webp images on these versions. 
</details>
</details>
-
- Fix broken images on iOS 12 - Brian 
-
-
</details>

fix: don't use webp on unsupported os versions

---

ios/Podfile.lock
package.json
patches/react-native+0.66.5.patch
yarn.lock

This PR resolves [MOPLAT-490] 
- In summary: An update to RN (v0.71) caused lower versions to fetch 0.71 instead of their specified versions. Unfortunately our version still uses the gradle dynamic versioning pattern (i.e using `+` instead of specifying a specific version) so we ended up fetching v0.71. A patch for 0.66.* was released. This PR updates the version to that patch.
-
-
-
- Fix android unable to build issue - kizito
</details>
[MOPLAT-490]: …

fix(MOPLAT-490): Fix android unable to build issue

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx

This PR resolves [CX-3048] 
Update price estimate form copy.
- Update price estimate form copy - ole
-
-
-
</details>
[CX-3048]: https://artsyproduct.atlassian.net/browse/CX-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update price estimate form copy

---

package.json

This PR makes the `yarn ios` command work again. This is useful if you hate opening xCode as much as I do. 
-
-
-
- fix: make yarn ios work again - mounir
</details>

fix: make yarn ios work again

---

docs/troubleshooting.md

This updates the troubleshooting doc with the step that helped me finally install Eigen:
```
bundle exec pod repo update 
```

docs(troubleshooting.md): Add pod repo update item 

---

package.json
src/app/Scenes/Artwork/Artwork.tests.tsx
yarn.lock

bump @testing-library/jest-native from 5.0.0 to 5.1.2
-
-
-
- bump jest native dep - gkartalis
</details>

build(deps): bump @testing-library/jest-native from 5.0.0 to 5.1.2

---

src/palette/elements/Avatar/Avatar.tsx

Center Avatar initials.
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-11-09 at 14 19 54](https://user-images.githubusercontent.com/4691889/200842572-67afad98-0414-43d0-8dfd-29679f61c692.png)| ![Simulator Screen Shot - iPhone 13 Pro - 2022-11-09 at 14 19 47](https://user-images.githubusercontent.com/4691889/200842579-f20fb0c4-ceae-4826-8630-c7ca6d520cbd.png)|
-
-
-
-
</details>

fix: Center Avatar initials

---

docs/getting_started.md

This PR adds `yarn ios` to the **How to run on iOS step**
#nochangelog

chore: add steps to run ios from terminal

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx

Adjust "Privacy Policy" font size on RPE form.
[Slack Thread for context](https://artsy.slack.com/archives/C01B2P6LJUU/p1668075372661309)
-
-
-
-
</details>

fix: Adjust Privacy Policy font size on RPE form

---

fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/release_notes.txt

chore: Release Notes 8.2.1

---

src/app/Components/Bidding/Screens/ConfirmBid/index.tsx

This PR resolves [TX-877] 
Fixes a bug where pulling down the conditions of sale modal on the bidding modal causes the app to crash. This removes the modal navigation. 
https://user-images.githubusercontent.com/50849237/201092067-9eb61e16-e3f6-45bb-a76c-dccfd576f59e.mp4
-
-
-
-
</details>
[TX-877]: https://artsyproduct.atlassian.net/browse/TX-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TX-877): remove modal navigation for bidding conditions of sale

---

src/app/AppRegistry.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/app/navigation/routes.ts

This PR resolves [CX-2799] 
Adjust the Settings screen according to the new design.
- Adjust the Settings screen - ole
-
-
-
</details>
[CX-2799]: https://artsyproduct.atlassian.net/browse/CX-2799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Adjust settings screen

---

src/app/store/config/features.ts

This PR resolves [CX-3145] 
- Prepare ARReorderSWAArtworkSubmissionFlow for release
-
-
-
- Prepare ARReorderSWAArtworkSubmissionFlow for release - kizito
</details>
[CX-3145]: https://artsyproduct.atlassian.net/browse/CX-3145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ARReorderSWAArtworkSubmissionFlow

---

android/app/src/main/AndroidManifest.xml
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/Home/Home.tsx
src/app/navigation/routes.ts

This PR resolves [MOPLAT-514] 
Fixes broken deeplinking for new-for-you.
Before this fix we were rendering a webview for the new-for-you page when visiting a link either from push or email of this format https://artsy.net/new-for-you.
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-11-15 at 14 07 14](https://user-images.githubusercontent.com/21178754/201933082-95a84521-7abc-44a0-9831-0a992bbc4062.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-11-15 at 14 07 38](https://user-images.githubusercontent.com/21178754/201933109-2c4e52cd-5584-48e1-9641-72677ab929e6.png)|
- fix broken deeplinking for new-for-you - gkartalis
-
-
-
</details>
[app …

fix(MOPLAT-514): deeplinking for new-for-you

---

src/app/Components/ArticleCard.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/app/Components/Home/ArtistRails/ArtistCard.tsx
src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
src/app/store/config/features.ts
src/palette/elements/Cards/MediumCard.tsx

This PR resolves [MOPLAT-485] 
Note that the label is only visible in the dev env via [this](https://github.com/artsy/eigen/blob/main/src/app/store/config/features.ts#L293) dev toggle.
How to QA:
1. create a file on your desktop called `whatever.apns`, inside the file add a simple notification payload like:
```json
{
"Simulator Target Bundle": "net.artsy.artsy",
"url": "/works-for-you",
"aps": {
"alert": "New Phony auctions push title",
"badge": 1,
"sound": "default"
}
}
```
2. drag and drop this file to your ios simulator, this triggers a notification that redirects you to this grid
3. grid should be fixed 👌
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 13 Pro - 2022-11-15 at 13 57 09](https://user-images.githubusercontent.com/21178754/201925377-2cb3e7d8-b417-48d8-ade6-c2a1d6 …

fix(MOPLAT-485): Layout issues when navigating to works-for-you from notification

---

src/app/Scenes/MyProfile/MyProfileHeader.tsx
src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx

This PR resolves [CX-2805] 
Redesign Profile UI
| **After** | **Before** |
| --- | ---|
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-11-15 at 12 27 21](https://user-images.githubusercontent.com/11945712/201908838-b1d9310b-2428-475f-90d1-9cb582da94b5.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-11-15 at 12 29 10](https://user-images.githubusercontent.com/11945712/201908872-d755eaff-57be-4cbf-a352-9e17f8f09ce1.png) |
- Update profile UI - mounir
-
-
-
</details>
[CX-2805]: …

chore(CX-2805): redesign profile ui

---

.secrets.baseline
src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkConsignments.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkConsignments.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx

This PR resolves [FX-4428] 
| Disabled FF | Enabled FF |
| <img width="506" alt="before" src="https://user-images.githubusercontent.com/3513494/201394833-6fe7eca5-384e-40d7-8d15-5bc7c7c47f9e.png"> | <img width="506" alt="after" src="https://user-images.githubusercontent.com/3513494/201394856-c248420e-bd3e-4973-b660-309370069aa6.png"> | 
- add "Consign with Artsy" section - dimatretyak
-
-
-
</details>
[FX-4428]: https://artsyproduct.atlassian.net/browse/FX-4428?atlOrigin=eyJp …

feat(FX-4428): add "Consign with Artsy" section

---

src/app/Components/PageWithSimpleHeader.tsx
src/app/navigation/BackButton.tsx

This PR adds a minimum height to the simple header to avoid the back button not aligning with the bottom border when font scaling is enabled (smallest)
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-11-14 at 11 54 56](https://user-images.githubusercontent.com/4691889/201642678-02409cc6-9a69-44e5-948f-eef116af139f.png)|![Simulator Screen Shot - iPhone 13 Pro - 2022-11-14 at 11 53 23](https://user-images.githubusercontent.com/4691889/201642688-4f4cd6b1-ddb2-4d24-88ed-659479d30d9d.png) |
-
-
-
-
</details> …

fix: Add min height to simple header for font scaling

---

android/app/src/main/AndroidManifest.xml

This PR resolves [CX-2078] 
Do not deep link privacy and terms of conditions links.
https://user-images.githubusercontent.com/11945712/202232116-21bc1255-cdca-4d6f-9d19-2c298c068b3c.mov
-
-
- Fix privacy policy and terms and policy deep links - mounir
-
</details>
[CX-2078]: https://artsyproduct.atlassian.net/browse/CX-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2078): do not deep link privacy and terms of conditions links

---

ios/Artsy.xcodeproj/project.pbxproj
ios/Podfile.lock
package.json
yarn.lock

This PR resolves [CX-2486] 
Show network status during the Onboarding. This was broken because of an old version of react native device info.
**On Android**
https://user-images.githubusercontent.com/11945712/202221172-0f913ebc-0d79-4e38-9892-457ec4ee9056.mov
**On iOS**
https://user-images.githubusercontent.com/11945712/202221240-614117ea-5846-4a51-839a-88d5112bcc8e.MP4
- Fix Network status modal during the Onboarding - mounir
-
-
-
</details>
[CX-2486]: …

fix(CX-2486): show network status during the Onboarding

---

src/app/Scenes/Partner/Partner.tsx
src/app/navigation/routes.tests.ts
src/app/navigation/routes.ts

This PR resolves [MOPLAT-486] 
|Before|
https://user-images.githubusercontent.com/17421923/202220148-e8d0e2a8-face-487d-bc2b-f0f705a887eb.mov
|After|
https://user-images.githubusercontent.com/17421923/202220185-875ac125-ceea-468f-892f-0addb83ffabf.mov
-
-
-
-
</details>
[MOPLAT-486]: https://artsyproduct.atlassian.net/browse/MOPLAT-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: deeplink fix for partner shows and works

---

src/app/Scenes/Favorites/FavoriteArtworks.tsx

This PR resolves [FX-4442] 
| <img width="516" alt="before" src="https://user-images.githubusercontent.com/3513494/202438357-7a3a2af2-f776-4700-90d4-7ad6e1ad365e.png"> | <img width="506" alt="after" src="https://user-images.githubusercontent.com/3513494/202480541-9da76eb8-1e6d-4613-9873-68b380d1c1f2.png"> | 
- change copies for "Saved" tab - dimatretyak
-
-
-
</details>
[FX-4442]: https://artsyproduct.atlassian.net/browse/FX-4442?atlOrigin=eyJpIjoiNWRkNTljN …

chore(FX-4442): change copies for "Saved" tab

---

src/app/Scenes/MyAccount/MyAccountEditPassword.tsx

This PR resolves [MOPLAT-358] 
Before
https://user-images.githubusercontent.com/17421923/202467769-ddb3bd5c-f709-4850-b64b-fed72eae2c0e.mov
After
https://user-images.githubusercontent.com/17421923/202467855-ac6b2daa-6f0e-4593-8dd1-8c499cddd849.mov
- password change fix - sam
-
-
-
</details>
[MOPLAT-358]: https://artsyproduct.atlassian.net/browse/MOPLAT-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change password

---

.circleci/config.yml
CHANGELOG/android-changelog.md
CHANGELOG/ios-changelog.md
scripts/setup-env-for-ci

- Fix broken iOS build on 8.3.0
#nochanges

fix: broken iOS build on 8.3.0

---

src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarouselContainer.tsx
src/app/Scenes/MyProfile/MyProfileHeader.tsx
src/app/store/config/features.ts

This PR fixes the homefeed onboarding issues on small phones
Slack thread: https://artsy.slack.com/archives/C01B2P6LJUU/p1668782999404209
#nochanges

fix: spacing on small iPhones

---

.secrets.baseline
src/app/Components/Modals/LoadingModal.tsx
src/app/Scenes/MyCollection/Screens/Insights/SelectArtist.tests.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingSocialPick.tests.tsx
src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
src/app/store/AuthModel.tests.ts
src/app/store/AuthModel.ts
src/app/store/migration.tests.ts
src/setupJest.ts

This PR resolves [CX-3142] 
- Show loading spinner on social login
- Increase hit stop for login / sign up button
- Fix logout issue on Android 
https://user-images.githubusercontent.com/11945712/201960175-539df0c5-aea4-4da7-9467-9308e64e9790.mov
- Show loading spinner on social login - mounir
- Increase hit stop for login / sign up button - mounir
-
- Fix logout issue on Android - mounir     
-
</details>
[CX-3142]: https://artsyproduct.atlassian.net/browse/CX-3142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

chore(CX-3142): show loading spinner while social login

---

src/app/store/config/features.ts

Set artists not in artsy ff as ready to be released
#nochanges

chore: set artists not in artsy ff as ready to be released

---

src/app/Containers/BidFlow.tsx

This PR resolves: [Notion Card](https://www.notion.so/artsy/Headers-look-broken-on-register-to-bid-modal-bfd68b027bf544d69162b5a52ca64985)
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-11-18 at 20 03 36](https://user-images.githubusercontent.com/3513494/202761985-6b6db1d5-742f-4019-a787-6ba53fb4c888.png) | ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-11-18 at 20 03 32](https://user-images.githubusercontent.com/3513494/202762013-9f525fec-760c-4828-8014-02f06de66ec8.png) | 
| ![before-2](https://user-images.githubusercontent.com/3513494/202762860-528b86a7-4231-457c-87ee-71c815cc7823.png) | ![after-2](https://user-images.githubusercontent.com/3513494/2027628 …

fix: broken register to bid headers

---

src/app/Scenes/Partner/Components/PartnerOverview.tests.tsx
src/app/Scenes/Partner/Components/PartnerOverview.tsx

This PR resolves [MOPLAT-449] 
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/202704376-fbb08ce8-3427-46a1-aa05-a1c9d3cc5462.png)|![image](https://user-images.githubusercontent.com/17421923/202704314-8c58c14b-546a-476b-89e2-53e526cadfda.png)|
-
-
-
- partner overview query change
</details>
[MOPLAT-449]: https://artsyproduct.atlassian.net/browse/MOPLAT-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change partner overview query

---

src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/store/config/features.ts
src/app/utils/experiments/hooks.ts

This PR resolves [CX-3135] 
"New Works for You" home screen rail size A/B test.
- Unleash A/B test [https://unleash.artsy.net/projects/default/features/eigen-new-works-for-you-rail-size](https://unleash.artsy.net/projects/default/features/eigen-new-works-for-you-rail-size/variants)
- Feature flag to enforce the large rail (`AREnforceLargeNewWorksRail`)
| **Small** | **Large** | 
| --- | --- |
|![Simulator Screen Shot - iPhone 13 Pro - 2022-11-16 at 17 52 51](https://user-images.githubusercontent.com/4691889/202243423-7c262c8c-9c49-4d17-8a52-b038cab13b9e.png) |![Simulator Screen Shot - iPhone 13 Pro - 2022-11-16 at 17 52 36](https://user-images.githubusercontent.com/4691889/202243454-17869359-bc6e-414e-97c7-342fb5b6ee46.png) |
-
-
-
- …

feat: Large New Works Rail AB test

---

src/app/Containers/Inbox.tests.tsx
src/app/Containers/Inbox.tsx
src/app/Scenes/MyBids/MyBids.tsx

This PR resolves [NX-3318] 
Conditionally display "Bids" or "Inquiries" on the Inbox
Many thanks to @gkartalis for co-authoring this over 4 zoom sessions and helping write tests for Inbox which is a tricky component to test. 🎉 
Thanks also to @lukewlms for opening an issue regarding the mock of react-native-scrollable-tab-view that was necessary for the resolution of [this issue](https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/1116).
https://user-images.githubusercontent.com/36475005/200625104-8266e5b3-0ed4-4d8b-8d20-d404259fc05a.mov
-
-
-
-
</details> …

feat(NX-3318): Conditionally display "Bids" or "Inquiries" on the Inbox.

---

fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/release_notes.txt

Update release notes for 8.3.0.
**Slack thread**: https://artsy.slack.com/archives/C02BAQ5K7/p1669126160123949
#nochanges

chore: update release notes for 8.3.0

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx

| <img width="505" alt="before" src="https://user-images.githubusercontent.com/3513494/203335040-95fd6643-9bad-4512-bfb1-f2219e998cae.png"> | <img width="505" alt="after" src="https://user-images.githubusercontent.com/3513494/203335088-f7b63d7a-672a-409e-955e-cb105c3ab711.png"> | 
- update section title for recently selected price ranges - dimatretyak
-
-
-
</details>

chore: update section title for recently selected price ranges

---

src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
src/app/Components/ArtworkGrids/GenericGrid.tests.tsx
src/app/Components/ArtworkGrids/GenericGrid.tsx
src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
src/app/Components/ArtworkGrids/LotCloseInfo.tsx
src/app/Scenes/Artwork/Components/AboutArtist.tests.tsx
src/app/store/config/features.ts
src/app/tests/renderWithWrappers.tsx

This PR resolves [CX-3138] 
Add save icon PLPs
https://user-images.githubusercontent.com/11945712/203356374-2be2d443-03c8-4a0a-962f-d14ce815d715.mov
- Add save icon to artworks - Mounir, Ole
-
-
-
</details>

feat: Add save icon PLPs

---

app.json

- Set app version to 8.4.0
#nochanges

chore: set app version to 8.4.0

---

src/app/Scenes/MyCollection/MyCollection.tsx

This PR updates the My Collection header placeholder to match the new design
| Profile Header | New Placeholder | 
| -- | -- | 
| ![image](https://user-images.githubusercontent.com/20655703/203615082-bb80d657-9c43-43d7-bf7f-c93618fe3989.png) | <img width="463" alt="image" src="https://user-images.githubusercontent.com/20655703/203615099-c9832b19-a240-4647-8e51-d48fb038a886.png">|
- update my collection header placeholder - mrsltun
-
-
-
</details>

fix: update my collection header placeholder

---

src/app/Components/ArtworkImagesComposition.tsx
src/app/Components/GenericArtistSeriesRail.tsx
src/app/Components/Home/CardRailCard.tsx
src/app/Components/ThreeUpImageLayout.tsx
src/app/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/CollectionArtistSeriesRail.tests.tsx
src/app/Scenes/Home/Components/CollectionsRail.tsx
src/app/Scenes/Home/Components/FairsRail.tsx
src/app/Scenes/Home/Components/SalesRail.tsx

Add reusable component that displays artwork images compositions
-
-
-
- add reusable component that displays artwork images compositions - dimatretyak
</details>

refactor: add reusable component that displays artwork images compositions

---

src/app/Scenes/Search/Search.tests.tsx
src/app/Scenes/Search/TrendingArtists.tsx
src/app/Scenes/Search/components/TrendingArtistCard.tsx
src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
src/app/store/config/features.ts

https://user-images.githubusercontent.com/3513494/203833142-038b7542-645a-4f17-9f6b-027df4bc3fc1.mp4
-  use large card on tablets, small card on phones for trending artist rails - dimatretyak
-
-
-
</details>

chore: use large card on tablets, small card on phones for trending artist rails

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx

https://user-images.githubusercontent.com/3513494/203592099-82a9127b-7b39-460d-8618-8497e4860ef6.mp4
https://user-images.githubusercontent.com/3513494/203592150-8ba6adb4-043d-4321-99b4-0a5e96821cbc.mp4
-
-
-
- scroll to the top ScrollView on Android when "clear" button is tapped - dimatretyak
</details>

fix: scroll to the top ScrollView on Android when "clear" button is tapped

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx

This PR resolves [FX-4471] 
https://user-images.githubusercontent.com/3513494/203933089-c0a42eba-d942-4eb2-ac73-13ae31fc39fd.mp4
-
-
-
- add analytics for the recent price ranges - dimatretyak
</details>
[FX-4471]: https://artsyproduct.atlassian.net/browse/FX-4471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-4471): Add analytics for the recent price ranges

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx

This PR resolves [CX-2975] 
Replace "Delete Artwork" CTA with "Delete Artwork" red link
Android / iOS:
- replace CTA with red link | Edit MyC Artwork -daria
-
-
-
</details>
[CX-2975]: https://artsyproduct.atlassian.net/browse/CX-2975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2975): MyC Edit Artwork Page - Replace the "Delete Artwork" CTA with a Red link CTA [app]

---

src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx

This PR resolves [CX-3170] 
- Disable empty names onboarding creating account
https://user-images.githubusercontent.com/11945712/203979089-db1f9271-d5fd-4b4d-b00d-7a0898474d8c.mov
- disable empty names onboarding creating account - mounir
-
-
-
</details>
[CX-3170]: https://artsyproduct.atlassian.net/browse/CX-3170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: disable empty names onboarding creating account

---

src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionSellingWithartsyFAQ.tsx

This PR resolves [CX-3162] 
Change email address from sell@artsymail.com to sell@artsy.net
- Change email address from sell@artsymail.com to sell@artsy.net -daria
-
-
-
</details>
[CX-3162]: https://artsyproduct.atlassian.net/browse/CX-3162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3162): change email address from sell@artsymail.com to sell@artsy.net

---

src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
src/app/store/AuthModel.ts

This PR resolves [MOPLAT-501] 
https://user-images.githubusercontent.com/17421923/203335397-7553b03e-4ccf-494b-b962-5b489603f7b6.mov
-
-
-
-
</details>
[MOPLAT-501]: https://artsyproduct.atlassian.net/browse/MOPLAT-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: SignUp continue with the link

---

src/app/Scenes/Search/TrendingArtists.tsx

https://user-images.githubusercontent.com/3513494/204303256-e4e345b3-96ef-43a6-b7dd-39699ca711c6.mp4
https://user-images.githubusercontent.com/3513494/204303331-9eba2e6b-4d62-493d-9793-9e605482b2f7.mp4
- add the missed bottom offset for the trending artists rail - dimatretyak
-
-
-
</details>

chore: add the missed bottom offset for the trending artists rail

---

EXAMPLES.md
docs/best_practices.md
docs/testing.md
src/app/tests/extractText.ts
src/app/tests/setupTestWrapper.tsx
src/app/tests/waitUntil.ts

More information about how our tests work, wrappers and preferred patterns.
co-author: @pvinis

docs: testing docs 🎉

---

docs/troubleshooting.md

docs: clear cache on troubleshooting

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx

This feature was removed in artsy/eigen#6473. Now there is more content on the page (recent price ranges were added recently) and there was a chance that everything could not fit (especially on small screens). For this reason, I decided to restore the ability to scroll the screen
https://user-images.githubusercontent.com/3513494/204551211-b2621e19-9a64-468c-8ecc-4c69d1f197b9.mp4
https://user-images.githubusercontent.com/3513494/204551331-006a2f61-bbf9-4546-8675-2129f472562b.mp4
- Restore ability to scroll price filter screen - dimatretyak
-
-
-
</details> …

chore: restore ability to scroll price filter screen

---

src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
src/app/Components/ArtworkFilter/RecentPriceRanges.tests.tsx
src/app/Components/ArtworkFilter/RecentPriceRanges.tsx
src/app/store/config/features.ts

-
-
-
- remove `ARRecentPriceRanges` feature flag - dimatretyak
</details>

chore: remove `ARRecentPriceRanges` feature flag

---

ios/Podfile.lock
package.json
patches/react-native-image-crop-picker+0.38.1.patch
src/setupJest.ts
yarn.lock

This PR resolves [MOPLAT-225] 
blindly trying out the latest version to see if it helps. @brainbicycle will test it.
-
-
-
-
</details>
[MOPLAT-225]: https://artsyproduct.atlassian.net/browse/MOPLAT-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: android crash on image picker

---

docs/generate_a_release_build_for_local_testing.md

Adding the signing step.
-
-
-
-
</details>

docs: more docs on generating a local release build

---

src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsPayment.tsx
src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
src/app/Scenes/OrderHistory/OrderDetails/OrderDetails.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/OrderDetailsPayment.tests.tsx
src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx

This PR resolves [TX-925] 
This PR updates order details screen: added payment information for wire transfers, updated payment method section.
-
-
-
-
</details>
[TX-925]: https://artsyproduct.atlassian.net/browse/TX-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update order details: add payment info and payment method

---

src/app/Scenes/Artwork/Artwork.tests.tsx

test: skip a flaky test until its fixed

---

.circleci/config.yml
ios/Artsy.xcodeproj/project.pbxproj
ios/ArtsyTests/Supporting_Files/ARTestHelper.m
ios/Podfile.lock
package.json
scripts/source-for-bash-env
src/app/App.tsx
src/app/utils/DynamicIslandStagingIndicator.tsx
yarn.lock

I found a fun way to upgrade to the latest device-info version.
I added a little outline around the dynamic island, so that it shows purple when we are on staging. basically reflecting the tabbar line.
-
-
-
-
</details>

feat: staging indicator (and major dep update)

---

src/app/Components/Bidding/Components/ArtworkAuctionProgressBar.tsx
src/app/Components/Bidding/Components/Timer.tsx
src/app/Components/Countdown/Ticker.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkHeader.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
src/app/Scenes/Artwork/Components/ArtworkLotTimer.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx

This PR resolves [FX-4419] 
Moves timer label and progress bar to the top of the artwork page.
Feature is behind a feature flag
|Screenshots|||
|---|---|---|
|![Simulator Screen Shot - iPhone 14 - 2022-12-01 at 16 54 41](https://user-images.githubusercontent.com/21178754/205099548-254cb6c7-91c7-4f00-89ce-d3a688f8ea25.png)|![Simulator Screen Shot - iPhone 14 - 2022-12-01 at 16 54 08](https://user-images.githubusercontent.com/21178754/205099622-310a9723-a958-4f8d-8de3-e1ae91a85949.png)|![Simulator Screen Shot - iPhone 14 - 2022-12-01 at 16 57 23](https://user-images.githubusercontent.com/21178754/205099787-345d481d-36cd-48cb-bd7a-7ef1c1e60dcd.png)|
- Auctions progressbar/timer move to header (behind a ff) - gkartalis
-
-
-
</details>
Need help …

feat(FX-4419): Auctions progressbar/timer move to header

---

ios/Podfile.lock

after #7769, I had a bad sync with podfile.lock. this is the fix.
i upgraded to 1.11, pod install, then later went back to 1.7 and forgot to pod install.
-
-
-
-
</details>

fix: small podfile.lock fix

---

src/app/Scenes/Artwork/Artwork.tests.tsx

fix flaky artwork tests
-
-
-
- fix flaky artwork tests - gkartalis
</details>

test: fix flaky artwork tests

---

src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
src/app/navigation/NavStack.tsx

Fixes for PR: artsy/eigen#7760
| ![before](https://user-images.githubusercontent.com/3513494/205691555-84eafc0c-ec1b-4dc6-abda-390bf56598ad.png) | ![after](https://user-images.githubusercontent.com/3513494/205691344-2d9f7601-8874-4523-8f90-d4d4bc7309c5.png) | 
-
-
-
- remove bottom offset for modal screens -dimatretyak
</details>

refactor: remove bottom offset for modal screens

---

src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx

This PR resolves [TX-925] 
This PR adds copy buttons for the payment information. Also added a subject for the email.
https://user-images.githubusercontent.com/79979820/205277374-00952bbf-36f1-4180-8373-a2256d405653.mp4
-
-
-
-
</details>
[TX-925]: https://artsyproduct.atlassian.net/browse/TX-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add copy buttons for payment info

---

src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx

fix: import

---

src/app/Components/Bidding/Screens/BidResult.tsx
src/app/Components/Bidding/Screens/Registration.tsx
src/app/Components/Bidding/Screens/RegistrationResult.tsx
src/app/Components/Bidding/Screens/SelectMaxBid.tsx
src/app/utils/AdminMenu.tsx

after #7758, the dismissModal func needs to be called like a func 🤷 
-
-
-
-
</details>

fix: bad function call

---

src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Artwork.tsx

- change order for consignments section - dimatretyak
-
-
- 
</details>

chore: change order for consignments section

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
src/app/Scenes/Artwork/Components/CommercialInformation.tsx
src/app/Websockets/auctions/AuctionSocketContext.tsx

-
-
-
- improvements for artwork - dimatretyak
</details>

refactor: small improvements for artwork

---

src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx

https://user-images.githubusercontent.com/3513494/206181112-e91caff5-62f3-4af5-956c-bcd02b89a5d2.mp4
https://user-images.githubusercontent.com/3513494/206181239-d709750e-d356-4343-a898-a3abe0e4aa4d.mp4
-
-
-
- return correct data for optimistic response for save button - dimatretyak
</details>

chore: return correct data for optimistic response for save button

---

src/app/Scenes/Home/Home.tsx

Adjust home screen placeholder for large rail.
-
-
-
-
</details>

fix: Adjust home screen placeholder for large rail

---

src/app/Scenes/MyProfile/MyProfileEditForm.tsx
src/app/utils/googleMaps.ts

This PR resolves [TX-926] 
This PR fix user's timezone by saving coordinates to the user's location.
-
-
-
- Save coordinates after the user's location changed.
</details>
[TX-926]: https://artsyproduct.atlassian.net/browse/TX-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: save user's coordinates

---

src/app/Scenes/Artwork/Components/RequestConditionReport.tests.tsx
src/app/Scenes/Artwork/Components/RequestConditionReport.tsx

Notion card where it was reported [here](https://www.notion.so/artsy/Request-Condition-Report-button-looks-cramped-c694d4cfb2d2463daffc6188be787144)
change copy Request condition report -> request 
|---|---|
|![Simulator Screen Shot - iPhone 14 - 2022-12-08 at 10 42 50](https://user-images.githubusercontent.com/21178754/206414634-3744d9b0-3f29-4519-8e1b-011f18226697.png)|![Simulator Screen Shot - iPhone 14 - 2022-12-08 at 10 43 14](https://user-images.githubusercontent.com/21178754/206414624-0b578779-8175-4f3d-8b02-d2579a2eb3f3.png)|
- request condition report copy change - gkartalis
-
-
-
</details> …

fix: request condition report copy change

---

src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx

Artwork title will be in italic on the artwork page according to the designs.
[Notion card](https://www.notion.so/artsy/Artwork-name-should-be-in-italic-font-as-we-have-on-artsy-net-15e1bb410b4348f396489de4d63595da) where this was reported.
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 14 - 2022-12-02 at 16 59 03](https://user-images.githubusercontent.com/21178754/206420803-fd5b28f9-0247-4740-87de-e4fca0d6b93c.png)|![Simulator Screen Shot - iPhone 14 - 2022-12-08 at 11 11 55](https://user-images.githubusercontent.com/21178754/206420738-0d87e70b-171b-43b3-b820-b1df027b8127.png)|
- artwork title should be italic - gkartalis
-
-
-
</details> …

fix: artwork title should be italic

---

src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
src/palette/elements/Button/Button.tsx

* the design of the buttons is consistent (the same state when pressed)
https://user-images.githubusercontent.com/3513494/206191899-c9a32365-1ac8-4fba-b9c8-fb1edcba437a.mp4
https://user-images.githubusercontent.com/3513494/206191984-f43a9c1c-5cd5-4ebe-84ba-8a2bf9a283f4.mp4
https://user-images.githubusercontent.com/3513494/206192047-6ac5c9f7-45fb-4d15-9829-733c63bb3093.mp4
https://user-images.githubusercontent.com/3513494/206192100-55624a79-bc42-4df6-aa78-2e88ae263bb1.mp4
https://user-images.githubusercontent.com/3513494/206192190-dda28faa-5529-4eb0-9fe7-29816d983501.mp4
https://user-images.githubusercontent.com/3513494/206192247-53e138df-d567-4163-a6bf-eb7cef5a6edf.mp4
-
-
-
- artwork header buttons improvements - …

chore: artwork header buttons improvements

---

src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx

make use of trim: true on lot labels
[notion card ](https://www.notion.so/artsy/the-bidding-closed-label-is-displayed-on-the-next-line-if-the-lot-label-is-too-long-542a96a4597d454c9fcbdceb3bc969fa)
|Before|After|
|---|---|
|<img width="588" alt="Screenshot 2022-12-08 at 16 18 51" src="https://user-images.githubusercontent.com/21178754/206484264-a5f3faca-6c08-4695-9ccf-41c892d945f2.png">|![Simulator Screen Shot - iPhone 14 - 2022-12-08 at 16 17 29](https://user-images.githubusercontent.com/21178754/206484285-da48e5c9-a150-4c26-ac3c-238c477a0fe7.png)|
-  lot label trim - gkartalis
-
-
-
</details> …

fix: lot label trim

---

src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx

[Notion card](https://www.notion.so/artsy/Displays-Watch-lot-instead-of-Save-for-bidding-closed-artwork-6dc19d675b064dd0ac30b888f4b7a598)
|Before|After|
|---|---|
|<img width="715" alt="Screenshot 2022-12-08 at 17 01 37" src="https://user-images.githubusercontent.com/21178754/206497516-a26578fb-9442-4955-8d6f-37c5aa8384dd.png">|![Simulator Screen Shot - iPhone 14 - 2022-12-08 at 16 36 47](https://user-images.githubusercontent.com/21178754/206497522-016971e9-5bc1-4996-9a3c-47fba4c465cd.png)|
- display save button for bidding closed lots - gkartalis
-
-
-
</details> …

fix: display save button for bidding closed lots

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
src/app/navigation/NavStack.tsx

-
-
-
- another approach to hiding the bottom tabs - dimatretyak
</details>

refactor: another approach for hiding the bottom tabs

---

src/app/Scenes/Artwork/Artwork.tests.tsx

flaky artwork test fix
-
-
-
- flaky artwork test - gkartalis
</details>

fix: flaky artwork test

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx

This PR resolves [CX-3196] 
Add artwork rail save icon tracking.
-
-
-
-
</details>
[CX-3196]: https://artsyproduct.atlassian.net/browse/CX-3196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add artwork rail save icon tracking

---

src/app/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
src/app/Scenes/Artwork/Artwork.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkDetails.tsx

small refactor on artwork tests
-
-
-
- refactor artwork tests - gkartalis
</details>

refactor: artwork tests

---

src/app/Components/Toast/ToastComponent.tsx
src/app/store/GlobalStoreModel.ts
src/app/store/persistence.tests.ts
src/app/store/persistence.ts
src/app/utils/DevMenu.tsx

quick fix after the #7787. the env could not be swapped from stag to prod. the reason was that when we reset the state after logout, we do a complete reset and we just keep some stuff. when the env state was moved to devicePrefs from artsyPrefs, it was not being kept in that reset func.
two other quick changes, one is just the view on devmenu from
to
and finally adding rounded corners on the toast.
both things were things I touched while debugging this.
-
-
-
-
</details>

fix: environment swap

---

src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreenAndroid.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomViewAndroid.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
src/app/Scenes/MyProfile/DevicePrefsModel.ts
src/app/utils/DevMenuWrapper.tsx

This PR resolves [CX-3186] 
https://user-images.githubusercontent.com/11945712/206481214-8c59036b-88b8-4ea1-9023-186d730cece1.mov
-
-
- Fix deep zoom android issues - mounir
-
</details>
[CX-3186]: https://artsyproduct.atlassian.net/browse/CX-3186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Deep zoom issues

---

src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
src/app/Scenes/BottomTabs/BottomTabsModel.ts

This PR resolves [FX-4472]
Add unread notifications count on the app icon (iOS only).
https://user-images.githubusercontent.com/3934579/206218578-59bbdccd-0ea0-4d10-9a64-211d3fadefd5.mp4
-
- Counter on the app icon now incorporates number of unread activity panel notifications too 
-
-
</details>
[FX-4472]: https://artsyproduct.atlassian.net/browse/FX-4472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4472): iOS: unread notifications count on the app icon

---

src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx

Now that we are hiding the bottom tab bar on the artwork screen, thought it would be a good idea to add the staging indicator for us to know quickly that we are on the staging env.
-
-
-
- add staging indicator on artwork page header - gkartalis
</details>

feat: add staging indicator on artwork page header #ff

---

src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx

| ![before-1](https://user-images.githubusercontent.com/3513494/206736738-34d983a7-5bd3-4255-9a40-ad0c2bba28da.png) | ![after-1](https://user-images.githubusercontent.com/3513494/206736802-0e44778f-1fb0-43f6-b115-255ae95713eb.png) | 
| ![before-2](https://user-images.githubusercontent.com/3513494/206736852-b74ea729-f104-4d6b-8016-8902331127cb.png) | ![after-2](https://user-images.githubusercontent.com/3513494/206736886-5e5d70d4-ddd7-440d-bcde-c69ec50905f3.png) |
https://user-images.githubusercontent.com/3513494/206737595-6b6598d3-0207-46ba-8fb2-91fa5bc056ba.mp4
- Improvements for header actions on artwork screen - dimatretyak
-
-
-
</details> …

chore: improvements for header actions on artwork screen

---

src/app/Components/OpaqueImageView/createGeminiUrl.tsx

Webp images failing to load on iOS due to bad check. They are only supported on 14 and above.
-
-
-
-
</details>

fix: off by one for webp check #trivial

---

src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx

| ![before](https://user-images.githubusercontent.com/3513494/206810208-0de68f74-59a4-4673-ab72-54e9d719154f.png) | ![after](https://user-images.githubusercontent.com/3513494/206810226-026d2522-f376-48fa-8e0c-c80f32e0e236.png) | 
#nochangelog

chore: small improvements for redesigned artwork loading placeholder

---

src/app/store/AuthModel.ts

There were two spaces if the provider was an email, like `Your  account is blabla`. Also, the sentence was kinda intense, so I split it in two.
-
-
-
-
</details>

fix: better-spaced text

---

src/app/NativeModules/ARScreenPresenterModule.tsx

apparently this was like that since at least a year.
before
https://user-images.githubusercontent.com/100233/206853723-3cdbaf67-2143-4d60-861e-e94ee59d4ad0.mov
after
https://user-images.githubusercontent.com/100233/206853688-493f97c2-5d4e-4c44-ae61-015e3de55a49.mov
-
-
-
-
</details>

fix: statusbar color fix after modal dismissal

---

src/app/store/config/features.ts

Change showInAdminMenu to showInDevMenu for AREnableConsignmentInquiryFlow
-
-
-
- Change showInAdminMenu to showInDevMenu for AREnableConsignmentInquiryFlow - kizito
</details>

Change showInAdminMenu to showInDevMenu for AREnableConsignmentInquiryFlow

---

src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx

https://user-images.githubusercontent.com/3513494/207060050-3ad23236-06ae-43d8-b5f7-68099ad4611e.mp4
https://user-images.githubusercontent.com/3513494/207060133-1deaddf9-ae14-4f3a-8bfb-74659d8159d6.mp4
-
-
-
- Small improvement for saved search alert flow - dimatretyak
</details>

chore: small improvement for saved search alert flow

---

src/app/Scenes/Search/Search.tests.tsx
src/app/Scenes/Search/Search.tsx

clean up enableImprovedSearchPills flag
-
-
-
-  clean up enableImprovedSearchPills flag - gkartalis
</details>

chore: clean up enableImprovedSearchPills flag

---

src/app/Components/PartnerEntityHeader.tests.tsx
src/app/tests/setupTestWrapper.tsx

-
-
-
- setupTestWrapper improvements - gkartalis
</details>

test: setupTestWrapper improvements

---

CHANGELOG/android-changelog.md
CHANGELOG/ios-changelog.md

Co-authored-by: George Kartalis <g.kartalis7@gmail.com>
#nochangelog

chore: update changelog for 8.4.0

---

src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
src/app/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
src/app/Components/ArtworkFilter/types.ts

[THIS CAN BE REVIEWED]
This PR resolves [CX-3222] 
- Allow filtering for upcoming lots
https://user-images.githubusercontent.com/11945712/207573835-0bd3feb5-8066-4a51-8e64-df238e2f1d24.mov
cc @egdbear 
Blocked by https://github.com/artsy/metaphysics/pull/4580
-
-
-
-
</details>
[CX-3222]: https://artsyproduct.atlassian.net/browse/CX-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add show only upcoming auction results filter

---

fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/release_notes.txt

Update release notes for 8.4.0.
**Slack thread**: https://artsy.slack.com/archives/C02BAQ5K7/p1670950474493449
#nochanges

chore: update release notes for 8.4.0

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx

This PR resolves [CX-2564] 
This PR adds bottom padding to the My Collection Artist Select screen to be able to see the last results.
-
-
-
-
</details>
[CX-2564]: https://artsyproduct.atlassian.net/browse/CX-2564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: My Collection form artist screen bottom spacing

---

src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
src/app/Components/Artist/ArtistHeader.tests.tsx
src/app/Scenes/Search/SearchArtworksGrid.tests.tsx
src/app/Scenes/Search/TrendingArtists.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tests.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tests.tsx

refactor some tests to use setupTestWrapper
-
-
-
-
</details>

test: refactor some tests to use setupTestWrapper

---

app.json

- Set app version to 8.5.0
#nochanges

chore: set app version to 8.5.0

---

dangerfile.ts

pause danger rule for webp
-
-
-
- pause danger rule for webp - gkartalis
</details>

chore: pause danger rule for webp

---

src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
src/app/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
src/app/Components/ArtworkFilter/types.ts

Revert "feat: add show only upcoming auction results filter"

---

src/app/Components/HeaderArtworksFilter/HeaderArtworksFilter.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tests.tsx
src/app/Scenes/Show/Components/ShowContextCard.tsx
src/app/Scenes/Show/Show.tests.tsx

small test refactor
#nochangelog
</details>

refactor(test): tests to use setupTestWrapperTL

---

src/app/Components/AuctionResult/AuctionResultMidEstimate.tests.tsx
src/app/Components/AuctionResult/AuctionResultMidEstimate.tsx
src/app/Components/Lists/AuctionResultListItem.tests.tsx
src/app/Components/Lists/AuctionResultListItem.tsx

fix: revert mid estimate strings

---

data/schema.graphql
src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/app/Components/Lists/AuctionResultListItem.tsx

Show different content for upcoming auction results
#nochanges 

fix: address QA comments on auction results 

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx

This PR resolves [CX-3285] 
Add includePersonalArtists param to collection artist query (https://github.com/artsy/metaphysics/pull/4656).
-
-
-
-
</details>
[CX-3285]: https://artsyproduct.atlassian.net/browse/CX-3285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add includePersonalArtists param to collection artist query

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx

Remove the unnecessary divider below MyC Why Sell With Artsy section.
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-12-29 at 14 55 41](https://user-images.githubusercontent.com/4691889/209963623-06576e3c-f7e1-4457-8f51-233c14920a71.png)| ![Simulator Screen Shot - iPhone 14 Pro - 2022-12-29 at 14 56 48](https://user-images.githubusercontent.com/4691889/209963664-a650b26b-53f1-4615-b4fd-8f8b4e67d8d0.png)|
- Remove the unnecessary divider below MyC Why Sell With Artsy section - ole
-
-
-
</details>
[docs]: …

fix: Remove unnecessary divider below MyC Why Sell With Artsy section

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tests.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/validation.ts

This PR resolves [CX-3273] 
- Removes the phone number validation in the SWA form
- Remove Phone validation in SWA form - kizito
-
-
-
</details>
[CX-3273]: https://artsyproduct.atlassian.net/browse/CX-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3273): Remove Phone validation in SWA form

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx

Mark depth as optional in SWA flow.
-
-
-
-
</details>

fix: Mark depth as optional in SWA flow

---

src/app/Scenes/Home/Home.tsx

This PR resolves [CX-3295] 
This PR updates the Upcoming Auction Results rail title on the home screen
| -- | -- |
| ![image](https://user-images.githubusercontent.com/20655703/210097637-23787a2a-0817-42b9-b4ca-693aad9e73dc.png) | ![image](https://user-images.githubusercontent.com/20655703/210097639-6b847adc-b558-414e-9674-0662fc0c18a4.png) |
- Update upcoming results auction rail title on home screen - mrsltun
-
-
-
</details>
[CX-3295]: …

fix(CX-3295): Update upcoming auction results rail title

---

src/app/Scenes/Onboarding/Onboarding.tsx
src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
src/app/store/config/features.ts

This PR resolves [CX-3030] 
Clean up ARShowNetworkUnavailableModal.
-
-
-
-
</details>
[CX-3030]: https://artsyproduct.atlassian.net/browse/CX-3030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Clean up ARShowNetworkUnavailableModal

---

src/app/Scenes/Home/Home.tsx

Revert "fix(CX-3295): Update upcoming auction results rail title"

---

src/app/store/config/features.ts

This PR resolves [CX-3032] 
Clean up AREnableTrove feature flag.
-
-
-
-
</details>
[CX-3032]: https://artsyproduct.atlassian.net/browse/CX-3032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Clean up AREnableTrove feature flag

---

src/app/store/config/features.ts

This PR resolves [CX-3031] 
Clean up AREnableShowsRail.
-
-
-
-
</details>
[CX-3031]: https://artsyproduct.atlassian.net/browse/CX-3031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Clean up AREnableShowsRail

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
src/app/Scenes/Search/AutosuggestResults.tsx

This PR resolves [CX-3211] 
Skip artwork step if artist has no artworks.
- Skip artwork step if artist has no artworks - ole
-
-
-
</details>
[CX-3211]: https://artsyproduct.atlassian.net/browse/CX-3211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Skip artwork step if artist has no artworks

---

src/app/store/config/features.ts

This PR resolves [CX-3026] 
Clean up AREnablePlaceholderLayoutAnimation.
-
-
-
-
</details>
[CX-3026]: https://artsyproduct.atlassian.net/browse/CX-3026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Clean up AREnablePlaceholderLayoutAnimation

---

src/app/Scenes/SellWithArtsy/Components/WhySellWithArtsy.tsx
src/app/navigation/routes.ts

fix broken specialist link in SWA screen
- fix broken SWA specialist link - gkartalis
-
-
-
</details>

fix: meet the specialists link on swa screen

---

src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
src/app/store/config/features.ts

This PR resolves [CX-3024] 
Clean up ARShowMyCollectionDemandIndexHints.
-
-
-
-
</details>
[CX-3024]: https://artsyproduct.atlassian.net/browse/CX-3024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Clean up ARShowMyCollectionDemandIndexHints

---

app.json

chore: Update app version to 8.6.0 in app.json

---

src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tests.tsx
src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx

This PR resolves [CX-3298] 
This PR resolves [CX-3297]
This PR resolves [CX-3302]
- Fixes focus behaviour in ConsignmentInquiry form
- Spaces adjustments
- Fixes the abandon form confirmation showing up when form has not been interacted with
https://user-images.githubusercontent.com/18648835/210527337-999ab7fe-cd49-4e47-bd27-8c77ead230a3.mov
- App ConsignmentInquiry Improvements - kizito
-
-
-
</details>
[CX-3298]: https://artsyproduct.atlassian.net/browse/CX-3298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

fix(CX-3298, CX-3297, CX-3302): App ConsignmentInquiry Improvements

---

package.json
yarn.lock

update sentry-cli in order to fix the failing fastlane [job](https://app.circleci.com/pipelines/github/artsy/eigen/36181/workflows/f992c008-7df3-4fec-bf94-0a6c52fea391/jobs/109228)
-
-
-
-  update sentry-cli - gkartalis
</details>

chore: update sentry-cli

---

src/app/Scenes/Home/Home.tsx
src/app/store/config/features.ts

This PR resolves [CX-3023] 
Clean up AREnableHomeScreenArtworkRecommendations.
-
-
-
-
</details>
[CX-3023]: https://artsyproduct.atlassian.net/browse/CX-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Clean up AREnableHomeScreenArtworkRecommendations

---

fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/release_notes.txt

chore: Update release notes for 8.5.0

---

src/app/Scenes/MyProfile/MyProfileEditForm.tsx
src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx

This PR resolves [CX-2964] 
This PR adds Complete your profile banner on top of Edit Profile screen if the user has empty fields in their profile
|--|--|
| <img width="367" alt="image" src="https://user-images.githubusercontent.com/20655703/211033493-51d657d8-61bb-403b-81e5-6e72526ce3c5.png"> | ![image](https://user-images.githubusercontent.com/20655703/211033630-dd92d0a5-b416-4865-b918-1ba29fbf27c3.png) |
- Add complete your profile banner in Edit Profile screen - mrsltun
-
-
-
</details> …

feat(CX-2964): Add complete your profile banner to Edit Profile screen

---

src/app/Scenes/SellWithArtsy/Components/Header.tsx
src/app/store/config/features.ts

This PR resolves [CX-3324] 
-  Rename Consignment Inquiry Feature Flag
-
-
-
- Rename Consignment Inquiry Feature Flag - kizito
</details>
[CX-3324]: https://artsyproduct.atlassian.net/browse/CX-3324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3324): Rename Consignment Inquiry Feature Flag

---

.circleci/config.yml

This PR adds fastlane match deploy key ssh 
#nochanges

chore: add fastlane match ssh fingerprint

---

android/app/build.gradle

Attempt to fix signing on Android
#nochangelog

fix: signinig on android

---

src/app/Components/ArticleCard.tests.tsx
src/app/Components/ArticleCard.tsx
src/app/Scenes/Articles/Articles.tests.tsx
src/app/Scenes/Articles/Articles.tsx
src/app/Scenes/Home/Home.tsx

This PR resolves [FX-4542] 
* Change "Market News" title on home page to "Artsy Editorial"
* Use `byline` field instead of `author.name`
| <img alt="app-before" src="https://user-images.githubusercontent.com/3513494/212082445-d4790a84-1012-447e-8942-00fc148dc0ff.png"> | ![app-after](https://user-images.githubusercontent.com/3513494/212082036-0b0fc984-6095-4009-af5e-2e74ce05f2be.png) |
-
-
-
-
</details>
[FX-4542]: …

chore(FX-4542): Change "Market News" title on home page to "Artsy Editorial"

---

src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tests.tsx
src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
src/app/store/config/features.ts

This PR resolves [CX-3028] 
Remove ARAllowLinkSocialAccountsOnSignUp feature flag.
-
-
-
-
</details>
[CX-3028]: https://artsyproduct.atlassian.net/browse/CX-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove old feature flags

---

src/app/utils/experiments/reporter.ts

feat: enable payload sending

---

scripts/update-env-for-artsy

I made the mistake of updating the env keys by mistake in s3 instead of pulling them. Luckily I have everything up to date, so both env vars are equal. This could occur to other devs as well, therefore I think it would be nice to prompt devs for confirmation here. 
-
-
-
- prompt for confirmation before updating env vars in s3 - mounir
</details>

chore: prompt for confirmation before updating keys in s3

---

src/app/utils/experiments/reporter.ts

context https://artsy.slack.com/archives/CP9P4KR35/p1673449241511309
-
-
-
-
</details>

feat: variants as strings

---

package.json
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/Search/Search.tsx
src/app/utils/experiments/reporter.ts
yarn.lock

Update tracking event to support new payload.
New payload based on the conversation [here](https://artsy.slack.com/archives/CP9P4KR35/p1673449241511309)
-
-
-
- Update tracking event - mounir
</details>

chore: update tracking event

---

.secrets.baseline
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/Home/Home.tsx
src/app/Scenes/NewWorksForYou/NewWorksForYou.tests.tsx
src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
src/app/utils/experiments/reporter.ts

This PR resolves [CX-3347] 
- Show works using new recs model for the new works for you
https://user-images.githubusercontent.com/11945712/213172864-14bc754a-7c92-485b-b9f2-c2054184c8a4.mov
- show works using new recs model for the new works for you - mounir
-
-
-
</details>
[CX-3347]: https://artsyproduct.atlassian.net/browse/CX-3347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show works using new recs model for the new works for you

---

src/app/AppRegistry.tsx
src/app/Scenes/SellWithArtsy/Components/Header.tsx
src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
src/app/navigation/NavStack.tsx

This PR resolves [CX-3342] 
- Prevent gesture back on contact a specialist screen.
_Can't make a video of this because I can't show screen touches on my device, it's working though when tested on my iPhone._
-
- Prevent swiping back gesture - mounir
-
- Support screen options inside react module - mounir
</details>
[CX-3342]: https://artsyproduct.atlassian.net/browse/CX-3342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: prevent gesture back on contact a specialist screen

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
src/palette/elements/Input/INTERNALSelectAndInputCombinationBase.tsx
src/palette/elements/Input/MoneyInput/MoneyInput.tests.tsx
src/palette/elements/Input/MoneyInput/MoneyInput.tsx
src/palette/elements/Input/MoneyInput/index.ts
src/palette/elements/Input/PhoneInput/PhoneInput.tsx
src/palette/elements/Input/index.tsx

This PR resolves [CX-2974] 
- This PR adds a MoneyInput component modelled after the existing PhoneInput component to Palette
- Provides a base for easily creating and updating Select+Input combination components
- Update the MyCollection Artwork form to use the MoneyInput component
https://user-images.githubusercontent.com/18648835/213443062-eaffa7ae-6efb-4146-8025-0e7a780d200e.mov
https://user-images.githubusercontent.com/18648835/213442514-f333ff2a-97a7-4c43-be2a-170c16272ac9.mov
-
-
-
-
</details> …

feat(CX-2974): Money Input

---

.secrets.baseline
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/createOrUpdateSubmission.ts

- Fixes the Input issues we are having with mycollection artwork submission and sell with artsy submissions. The inputs for these flows are passed an artist param when the Input type does not have a member field named artist.
https://user-images.githubusercontent.com/18648835/214136855-e6e05950-c174-4534-8e27-d931b26300cd.mov
https://user-images.githubusercontent.com/18648835/214136897-3a7354e2-4b4a-4db4-a72c-7a38a2607c0b.mov
- fix SWA and MyCollection Submission bug - kizito
-
-
-
</details>
[docs]: …

Fix(SWA/MyCollection): Error Submitting artwork and submissions

---

src/app/store/config/EnvironmentModel.tsx

fix default local metaphysics url on dev menu
-
-
-
- fix default local metaphysics url on dev menu - gkartalis
</details>

chore: fix default local metaphysics url on dev menu

---

src/app/Scenes/Search/Search.tsx

Removes smudge unleash sample experiment from search since we already have another one running [here](https://github.com/artsy/eigen/blob/f38649dc4135d87b2f55d2ba5d9d122c5a02c2f7/src/app/Scenes/Home/Home.tsx#L396). 
We can keep the closed pr as a reference to the experiment.
- 
-
-
- remove smudge unleash experiment from search - gkartalis
</details>

refactor(cleanup): remove smudge unleash experiment from search

---

src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
src/app/Scenes/BottomTabs/BottomTabs.tsx
src/app/Scenes/BottomTabs/BottomTabsModel.ts
src/app/store/persistence.tests.ts

* rename `unreadConversation` to `conversations`
* rename `unreadActivityPanelNotifications` to `notifications`
* rename `unreadActivityPanelNotificationsCountChanged` to `setUnreadNotificationsCount`
* rename `unreadConversationCountChanged` to `setUnreadConversationsCount`
-
-
-
- small improvements for `BottomTabsModel` - dimatretyak
</details>

refactor: small improvements for `BottomTabsModel`

---

app.json

Set app version to **8.7.0**
cc @brainbicycle
#nochangelog

chore: increase app version

---

src/app/AppRegistry.tsx
src/app/Scenes/MyCollection/Screens/Artwork/ArtworkSubmissionStatusFAQ.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
src/app/routes.ts

This PR resolves [CX-2888] 
https://user-images.githubusercontent.com/36167539/214792877-eeeecec6-6f54-4707-808e-9ba883f64f05.mp4
-
-
-
-
</details>
[CX-2888]: https://artsyproduct.atlassian.net/browse/CX-2888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2888): adjust submission status modal

---

.betterer.results
.betterer.ts

feat: palette extraction prep

---

src/app/Scenes/Home/Home.tsx

This PR resolves [CX-3194] 
Bring back  **Works from galleries you follow** rail.
- Add works from galleries you follow rail - mounir
-
-
-
</details>
[CX-3194]: https://artsyproduct.atlassian.net/browse/CX-3194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3194): add works from galleries you follow rail

---

.eslintrc.js
package.json
yarn.lock

As I was working on one task that I had noticed the following:
I deleted a helper function and the import was not needed anymore but the linter didn't catch it and I was alerted by the CI.
Because this is not ideal I added the `unused-imports` eslint plugin and added an eslint rule for preventing unused importss
-
-
-
- add unused imports eslint rule - gkartalis
</details>

feat: add unused imports eslint error rule

---

package.json

Adds a new deploy beta script to package.json.
**Use:**
```
yarn deploy-beta
```

toolchain(scripts): Add `yarn deploy-beta` script to package.json

---

src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tests.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselVimeoVideo.tsx

Removes an unnecessary key that's being passed in the URL. #superminor

fix(video): Remove unnecessary extra key

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
yarn.lock

|                                                                                  Before                                                                                  |                                                                                   After                                                                                  |
|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-01-30 at 17 46 …

fix: missing image dimensions

---

scripts/doctor.js
scripts/setup-env-for-artsy
scripts/setup-env-for-ci
scripts/update-env-for-artsy

This PR resolves [MOPLAT-576] 
Little pr to move our .env file to the same place as the rest so we can have stricter policies. 
-
-
-
-
</details>
[MOPLAT-576]: https://artsyproduct.atlassian.net/browse/MOPLAT-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: move s3 files

---

.betterer.results
src/app/Scenes/Home/Home.tsx

This PR solves [CX-3386]
- Update copy on home screen rails
- Use Chicago formatting for other titles
cc @dariakoko 
-
-
-
-
</details>
[CX-3386]: https://artsyproduct.atlassian.net/browse/CX-3386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(CX-3386): update copy on home screen rails

---

src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
src/app/store/config/visualClues.ts
src/palette/elements/ToolTip/ToolTip.stories.tsx
src/palette/elements/ToolTip/ToolTip.tests.tsx
src/palette/elements/ToolTip/ToolTip.tsx
src/palette/elements/ToolTip/ToolTipFlyout.tsx
src/palette/elements/ToolTip/index.ts
src/storybook/storybook.requires.js

This PR resolves [CX-3090] 
This PR adds a ToolTip Component to palette and displays a tooltip over MedianAuction price item.
https://user-images.githubusercontent.com/18648835/215440104-3f01bf6b-660d-4d18-9b66-e80e4fd9a476.mov
[tooltip-android.webm](https://user-images.githubusercontent.com/18648835/215440213-bd78e756-3bbf-46be-8461-84a4b989464f.webm)
- ToolTip Component - kizito
-
-
-
</details>
[CX-3090]: https://artsyproduct.atlassian.net/browse/CX-3090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …

Feat(CX-3090): Tooltip

---

.betterer.results
.betterer.ts
.husky/pre-commit
.lintstagedrc.mjs

Backing out of Betterer changes. See [this convo](https://artsy.slack.com/archives/C02NAJ2CGLW/p1675190552099359) for more info. 
Reverts artsy/eigen#8074

Revert "fix(betterer): Remove betterer from precommit and move into lint-staged"

---

package.json
yarn.lock

sentry cli version bump
-
-
-
-  sentry cli bump - gkartalis
</details>

build(deps): sentry cli bump

---

src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizNavigation.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsLoader.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizLikedArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsEmptyTabs.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabsHeader.tsx

This PR resolves [GRO-1533] 
Tabs content are the part of these tickets
- https://artsyproduct.atlassian.net/browse/GRO-1537
- https://artsyproduct.atlassian.net/browse/GRO-1538
-
-
-
-
</details>
[GRO-1533]: https://artsyproduct.atlassian.net/browse/GRO-1533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Empty fallback results tabs

---

scripts/changelog/commitChangelog.js

While trying to cherry pick few commits on Eigen for a hotfix release, I noticed that our commits history is messed up because of the changelog updater. This PR removes the merge on green label and therefore keeps the PR open and up to date with whatever is the latest state. If we merge the PR by mistake, it will still be created again.
-
-
-
- Do not merge the changelog updater PRs - mounir
</details>

chore: do not change changelog PRs

---

yarn.lock

- After running yarn on main, I got a different yarn.lock file
#nochangelog

chore: run yarn on main

---

docs/pull_request_template.md

We saw that after shortening these, we all started not filling it in, and also skipping/forgetting steps.
This way the list can be fully filled, so we all remember, and we all know that we either did the thing, or the thing is not required.
-
-
-
- PR checklist changes
</details>

chore: Update the PR checklist to be more mandatory

---

src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtist.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtists.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizLikedArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx

This PR resolves [GRO-1272] 
-
-
-
-
</details>
[GRO-1272]: https://artsyproduct.atlassian.net/browse/GRO-1272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Artists result screen tab

---

.eslintrc.js
package.json
src/setupJest.ts
yarn.lock

I noticed we get this camera errors on tests, so i just added an empty mock for now. Also, while debugging, imports were removed, and we don't like that. The rule will mark the unused imports but it will not "fix" them.
-
-
-
- mocks and eslint rules
</details>

tests: camera mock for tests, and less annoying eslint rule

---

src/app/AppRegistry.tsx
src/app/Scenes/Home/Home.tsx
src/app/Scenes/Search/Search2.tests.tsx
src/app/Scenes/Search/Search2.tsx
src/app/Scenes/Search/components/CityGuideCTA.tsx
src/app/Scenes/Search/useRefetchWhenQueryChanged.tsx
src/app/Scenes/Search/useSearchQuery.tsx
src/app/routes.ts
src/app/utils/queryPrefetching.ts

This PR resolves [FX-4564] 
Preloaded query payload of "new search" with `AREnableESOnlySearch` enabled:
example of calls of the refetching func as typing banksy:
- optimize search query calls behind a ff - gkartalis
-
-
-
</details>
[FX-4564]: https://artsyproduct.atlassian.net/browse/FX-4564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: optimize search query calls

---

.secrets.baseline
package.json
src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tests.tsx
src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tests.tsx
src/app/Components/ReadMore.tests.tsx
src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tests.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
src/app/utils/renderMarkdown.tests.tsx
src/palette/elements/LineGraph/LineGraphBands.tests.tsx
src/palette/elements/LineGraph/LineGraphCategoryPicker.tests.tsx
src/palette/elements/PhotoRow/PhotoRow.tests.tsx
yarn.lock

build(deps): update dep @testing-library/react-native from 11.5.0 to 11.5.1
-
-
-
- update dep @testing-library/react-native from 11.5.0 to 11.5.1 - gkartalis
</details>

build(deps): update dep @testing-library/react-native from 11.5.0 to 11.5.1

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/SavingArtworkModal.tsx
src/app/Scenes/SellWithArtsy/Components/Header.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx

This PR comes as a follow-up to the QA session:
|                                                                                    iOS                                                                                   |                                                             Android                                                             |
|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------------------------------------:|
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-02-06 at 10 47 00](https://user-images.githubusercontent.com/11945712/216939851-fa419d83-5c3a-42a …

fix: broken spacings in save artwrork modal and SWA flow

---

src/app/Scenes/Activity/ActivityItem.tsx
src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
src/app/Scenes/Activity/utils/shouldDisplayNotificationTypeLabel.ts

This PR resolves [FX-4607]
Add "Artsy Editorial" prefix in activity panel
|---|---|
| ![before](https://user-images.githubusercontent.com/3934579/217574661-506b225e-53ae-4c6f-9534-02369c31a5d3.png) | ![after](https://user-images.githubusercontent.com/3934579/217574741-b1a86bdd-c668-43af-b065-b6d49b7f9d32.png) |
- Added "Artsy Editorial" prefix to editorial activity panel notifications
-
-
-
</details>
[FX-4607]: https://artsyproduct.atlassian.net/browse/FX-4607?atlOrigin=eyJpIjoiNWRkNTljNzY …

feat(FX-4607): Add "Artsy Editorial" prefix in activity panel

---

src/app/Scenes/Search/SearchResults.tsx
src/app/Scenes/Search/components/ElasticSearchResults.tsx

https://user-images.githubusercontent.com/3513494/217620693-286c4fd2-dfc0-430b-b80c-0135aa66685e.mp4
https://user-images.githubusercontent.com/3513494/217620731-a702d0e3-b30a-4c03-924f-0403d082a94d.mp4
#nochangelog
</details>

fix: don't save the previous scroll offset for lists with search results

---

src/app/Scenes/Search/SearchResults.tsx
src/app/Scenes/Search/components/ElasticSearchResult.tsx
src/app/Scenes/Search/components/ElasticSearchResults.tsx
src/app/Scenes/Search/constants.ts
src/app/Scenes/Search/types.ts

This PR resolves [FX-4564] 
Adds ES search results analytics + moving around some stuff 🚚
- add analytics on es search results - gkartalis
-
-
-
</details>
[FX-4564]: https://artsyproduct.atlassian.net/browse/FX-4564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add analytics on es search results + bonus refactor

---

src/app/Scenes/Sales/Sales.tests.tsx
src/app/Scenes/Sales/Sales.tsx

On android when opening the app and trying to navigate to the `Sale` page we were always getting an error on the first try, and on the second try we were accessing the page correctly.
The reason for that was that the relay and suspense weren't configured correctly for this screen, this pr fixes that.
|Before|After|
|---|---|
|https://www.loom.com/share/9330260275f34efdbddd6bd565ca7104|https://www.loom.com/share/c96813f55e6a4b748ac7960e38749246|
- 
-
- fix auction navigation android issue - gkartalis
-
</details>
[docs]: …

fix: auction navigation android issue

---

package.json
yarn.lock

bump @testing-library/react-native from 11.5.1 to 11.5.2
Just fixes the crash that was caused when wrapping `fireEvent` with `act`. 
changelog [here](https://github.com/callstack/react-native-testing-library/releases/tag/v11.5.2)
-
-
-
- bump @testing-library/react-native from 11.5.1 to 11.5.2 - gkartalis
</details>

build(deps): bump @testing-library/react-native from 11.5.1 to 11.5.2

---

app.json
src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx

chore: prepare for 8.7.1

---

app.json

chore: prepare for 8.8.0

---

src/app/Providers.tsx
src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
src/app/Scenes/BottomTabs/BottomTabs.tsx
src/app/Scenes/BottomTabs/BottomTabsButton.tsx
src/app/Scenes/BottomTabs/BottomTabsModel.ts
src/app/utils/tests/renderWithWrappers.tsx
src/setupJest.ts

-
-
-
- refactor bottom tabs tests - dimatretyak
</details>

[FF] refactor: bottom tabs tests

---

ios/Podfile.lock
package.json
yarn.lock

This PR bumps `react-native-in-app-review` app version to the latest version
-
-
-
- bump react-native-in-app-review version to 4.2.1 - mounir
</details>

chore: bump react-native-in-app-review version

---

src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/Home/Home.tsx
src/app/store/config/features.ts

This PR resolves [CX-3406] 
Change all artwork rails on the home feed to use large images.
- Change all artwork rails on the home feed to use large images - ole
-
-
-
</details>
[CX-3406]: https://artsyproduct.atlassian.net/browse/CX-3406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Use only large artwork rails on home screen

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tsx

This PR resolves [CX-3419] 
Display New Field Notes in MyCollection Artwork
https://user-images.githubusercontent.com/18648835/219026276-36fd5ec6-e027-4e25-94d8-b937bca85421.mov
- Display New Field Notes in MyCollection Artwork - kizito
-
-
-
</details>
[CX-3419]: https://artsyproduct.atlassian.net/browse/CX-3419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3419): Display New Field Notes in MyCollection Artwork

---

src/app/Scenes/Search/AutosuggestResults.tsx
src/app/Scenes/Search/SearchContext.ts
src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
src/app/Scenes/Search/components/ElasticSearchResults.tests.tsx
src/app/Scenes/Search/components/ElasticSearchResults.tsx

This PR resolves [FX-4628] 
Makes sure that onScrollDragBegin the keyboard is dismissed and the input is blurred
https://www.loom.com/share/ad512fab10bf48509716820c4550a99e
https://user-images.githubusercontent.com/21178754/219061809-1eb35159-8bb9-417e-9cf2-72718f537fe8.MP4
- search results onScrollDragBegin dismiss keyboard and blur input - gkartalis
-
-
-
</details>

fix: onScrollDragBegin dismiss keyboard and blur input

---

package.json
src/app/Providers.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx
src/palette/Button/Button.tsx
yarn.lock

using the old palette-eigen button for now, so `block` works.
-
-
-
-
</details>

fix: old button until palette button is ready

---

src/app/Scenes/Partner/Components/PartnerHeader.tests.tsx
src/app/utils/formatLargeNumber.tests.ts
src/app/utils/formatLargeNumber.ts
src/app/utils/formatLargeNumberOfItems.tests.ts

This PR resolves [DO-648] 
-
-
-
-
</details>
[DO-648]: https://artsyproduct.atlassian.net/browse/DO-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use capital K for price values

---

src/app/Components/ArtworkRail/LargeArtworkRail.tsx

This PR resolves [CX-3406] 
Show save icon by default on large artwork rails ([Jira comment for context](https://artsyproduct.atlassian.net/browse/CX-3406?focusedCommentId=55075)).
- Show save icon by default on large artwork rails - ole
-
-
-
</details>
[CX-3406]: https://artsyproduct.atlassian.net/browse/CX-3406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Show save icon by default on large artwork rails

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx

Hide save icon in My Collection form artwork grid.
-
-
-
-
</details>

fix: Hide save icon in My Collection form artwork grid

---

src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx

Adjust My Collection photo upload spacing so the delete photo button (x) is still visible on the right column.
@lordkiz the layout issue might come from https://github.com/artsy/eigen/pull/7977. Could you please have a look to make sure this change doesn't break your fix 🙏 
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-16 at 15 28 38](https://user-images.githubusercontent.com/4691889/219392482-5d70ba39-6c02-4516-b476-68dbd6918fd7.png) |![Simulator Screen Shot - iPhone 14 Pro - 2023-02-16 at 15 28 04](https://user-images.githubusercontent.com/4691889/219392503-c077b527-5530-45b3-b58e-89e6a2ea3b6f.png) |
- Adjust My Collection photo upload spacing - ole
-
-
-
</details> …

fix: Adjust My Collection photo upload spacing

---

src/app/Scenes/MyProfile/MyProfileHeader.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx

Update profile image locally correctly.
-
-
-
-
</details>

fix: Update profile image locally correctly

---

src/app/Components/Bidding/Screens/SelectMaxBid.tsx

See more about the problem here: https://artsy.slack.com/archives/CCS8TMQ0K/p1676554860006719
https://user-images.githubusercontent.com/3513494/219456002-8881af7b-5943-41a1-af42-2d179e8af4cc.mp4
https://user-images.githubusercontent.com/3513494/219456063-2be59239-60ba-4734-a34f-37aa5986bc62.mp4
-
-
-
- error for select max bid query - gkartalis, dimatretyak
</details>

fix: error for select max bid query

---

.gitignore
docs/README.md
docs/developing_local_palette.md
package.json
scripts/yalc-link-local-palette
scripts/yalc-unlink-local-palette

Related
- https://github.com/artsy/palette-mobile/pull/64
This adds a few scripts for developing features using a locally-running version of palette-mobile, allowing us to skip the long feedback cycles around publishing canaries, installing, stopping and rebooting the simulator and more. 
**Scripts**:
- `yarn link-local-palette`
- `yarn unlink-local-palette` 
The docs herein provide some overview as well as setup instructions. 
-
-
-
- Add yarn link/unlink-local-palette scripts for working with palette-mobile 
</details>
[docs]: …

feat(toolchain): Streamline DX around working with local palette-mobile

---

src/app/Scenes/Search/Search2.tsx

| ![before](https://user-images.githubusercontent.com/3513494/219743951-81f4f81b-6353-4828-9cdf-57ef7be36c85.png) | ![after](https://user-images.githubusercontent.com/3513494/219744154-224509ab-12ee-46ef-b953-a07c91c0beb6.png) | 
| `Search` | `Search2` |
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-02-17 at 21 08 48](https://user-images.githubusercontent.com/3513494/219744562-1d4894e4-ece0-41b7-bc41-feb6558ee26b.png) | ![after](https://user-images.githubusercontent.com/3513494/219744387-e30689e4-d556-4e8a-9eeb-cf80503de736.png) | 
-
-
-
-
</details> …

chore: update offsets for search pills

---

.secrets.baseline
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/Home/Home.tsx
src/app/Scenes/NewWorksForYou/NewWorksForYou.tests.tsx
src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx

This PR resolves [CX-3418] 
We need to ensure that the "New works for you" (`/works-for-you`) screen loads the correct recommendations version when opened from an email campaign.
We use the `version` URL param if specified or default to no specified version to match the recommendations in the email
- Use email campaign new works for you version - ole
-
-
-
</details>
[CX-3418]: https://artsyproduct.atlassian.net/browse/CX-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

feat: Use email campaign new works for you version

---

src/app/Scenes/Home/Home.tsx

This PR resolves [CX-3407] 
Home screen reordering.
-
-
-
-
</details>
[CX-3407]: https://artsyproduct.atlassian.net/browse/CX-3407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Home screen reordering

---

src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
src/palette/Button/Button.tsx

Bug that came out of Mobile QA, save button not easily pressable.
|Before|After|
|---|---|
|![IMG_8685](https://user-images.githubusercontent.com/21178754/220086603-46702e4a-67ee-4147-84d5-ebc573120bed.PNG)|![IMG_8684](https://user-images.githubusercontent.com/21178754/220086622-d79a01a1-f6f7-4da2-b34a-533993b9e5e2.PNG)|
|More screenshots|||
|---|---|---|
|![IMG_1C12F1291251-2](https://user-images.githubusercontent.com/21178754/220114879-d5adebad-5a66-40f3-8a47-70e0276798f3.jpeg)|![IMG_1C12F1291251-1](https://user-images.githubusercontent.com/21178754/220114891-add281ad-38e4-49b7-990c-ab3ce3b0f97a.jpeg)|![IMG_25A02E0D4E1B-1](https://user-images.githubusercontent.com/21178754/220115175-595c0422-5594-4346-b63f-213ebf2129e4.jpeg)| …

fix: increase save button hitslop

---

src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx

Adjusted placeholder to match new save button, and changing also color to the bell icon according to the background
|Screenshots|||
|---|---|---|
|![IMG_1C12F1291251-1](https://user-images.githubusercontent.com/21178754/220116947-019a60a9-fab7-4d5a-9b9d-79d55d1818d3.jpeg)|![IMG_25A02E0D4E1B-1](https://user-images.githubusercontent.com/21178754/220116940-afa00083-0a21-488b-9fa5-490acf910ef2.jpeg)|![IMG_1C12F1291251-2](https://user-images.githubusercontent.com/21178754/220116944-1fb71b80-2936-4192-a16e-037f252d6be5.jpeg)|
-  fixes icon color / placeholder issues on artworkscreenheader - gkartalis
-
-
-
</details> …

fix: fixes icon color / placeholder issues on artworkscreenheader

---

src/app/Components/Bidding/Screens/PhoneNumberForm.tests.tsx
src/palette/elements/Input/INTERNALSelectAndInputCombinationBase.tsx

- Addresses Incident - 167
- 
https://user-images.githubusercontent.com/18648835/220151911-a3b6b163-043e-469e-a7f5-64ed892895e2.mov
- Fix Phone Input Bug - Inc-167 - kizito
-
-
-
</details>

Fix Phone Input Bug - Inc-167

---

src/palette/elements/Input/INTERNALSelectAndInputCombinationBase.tsx

This PR resolves padding issue on the input component on Android
-
-
- Fix money input spacing issues - mounir
-
</details>

fix: padding issue on input android

---

src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx

This PR resolves [APPL-305] 
| <video src="https://user-images.githubusercontent.com/3513494/220340452-42afa672-d9bf-40ed-bf1c-cf3e04adeaa2.mp4" /> | <video src="https://user-images.githubusercontent.com/3513494/220340500-da2987e8-a514-4001-af6d-3a98edd4fd0a.mp4" /> | 
- edit alert flow - dimatretyak
-
-
-
</details>
[APPL-305]: https://artsyproduct.atlassian.net/browse/APPL-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …

fix(APPL-305): edit alert flow

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Components/ArtworkRail/LargeArtworkRail.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tests.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomView.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tests.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tests.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tests.tsx
src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx

This PR resolves issues with images on the carousel
As the pixel ratio is at least 2x on most of the devices we target, I increased the images quality to cover for the low quality as follow in notion docs [here](https://www.notion.so/artsy/Handling-Images-On-The-Web-In-Force-5c6832bf4b3e431cb4830061ce057399). This doesn't fix the issue everywhere though and I would suggest MoPlat follows up on support the pixel ratio when querying from Gemini. 
|                                                                                  Before                                                                                  |                                                                                   After                                                                                  | …

fix: fix carousel image

---

app.json

chore: update version number #trivial

---

package.json
yarn.lock

[build(deps): update dep @testing-library/jest-native from 5.4.1 to 5.4.2](https://github.com/artsy/eigen/commit/c4de5dcaf6e527aa29b61afb421b43f86b9a3d10)
-
-
-
-
</details>

build(deps): update dep @testing-library/jest-native from 5.4.1 to 5.4.2

---

src/app/Scenes/MyAccount/MyAccount.tsx

Resolves https://github.com/artsy/eigen/issues/6470
-
-
-
- simplify myaccount linked accounts - gkartalis
</details>

fix: simplify myaccount linked acounts

---

src/app/Scenes/Search/ElasticSearchPills.tsx

This PR resolves [FX-4624] 
Added explicitly the entities that we want to get back counts from for the ESSearchPills.
https://user-images.githubusercontent.com/21178754/220634166-782c7cc0-b6b2-4985-918e-7fba3d328f05.mp4
- explicit entities for es search pills counts - gkartalis
-
-
-
</details>
[FX-4624]: https://artsyproduct.atlassian.net/browse/FX-4624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: specify which entities to get aggregations from on essearchpills

---

src/app/Scenes/Home/Home.tsx
src/app/store/config/features.ts

Remove AREnableMyCollectionHFOnboarding feature flag.
-
-
-
- Remove AREnableMyCollectionHFOnboarding feature flag - ole
</details>

chore: Remove AREnableMyCollectionHFOnboarding feature flag

---

src/app/Scenes/Home/Home.tsx

This PR resolves https://artsyproduct.atlassian.net/browse/CX-3407?focusedCommentId=55265
-
-
-
-
</details>

feat: Change home scren order again

---

src/app/Scenes/Partner/Components/PartnerArtistsList.tsx
src/app/Scenes/Partner/Components/PartnerOverview.tests.tsx
src/app/Scenes/Partner/Components/PartnerOverview.tsx
src/app/Scenes/Partner/Partner.tsx
src/app/utils/useClientQuery.ts

This PR resolves [APPL-313] 
[slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1677075697155079) for context
https://user-images.githubusercontent.com/21178754/220868133-25e114e4-16fa-4e05-9b84-97e65342c34b.mp4
-
-
-
-
</details>
[APPL-313]: https://artsyproduct.atlassian.net/browse/APPL-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: fix partner artist list

---

src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabsHeader.tsx

This PR resolves [GRO-1273] 
Users can see the results and save them via email so that they can access them later
https://user-images.githubusercontent.com/17421923/218818258-659ace61-e158-4599-9858-f616fc25e7ff.mov
-
-
-
-
</details>
[GRO-1273]: https://artsyproduct.atlassian.net/browse/GRO-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: request result email

---

src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx

This PR resolves [GRO-1271] 
-
-
-
-
</details>
[GRO-1271]: https://artsyproduct.atlassian.net/browse/GRO-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: explore artworks tab

---

src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/store/config/features.ts

Change browse all artworks copy to adjust to new design.
https://artsyproduct.atlassian.net/browse/CX-3408?focusedCommentId=55284
-
-
-
-
</details>

fix: Change browse all artworks copy

---

.vscode/launch.json

Enables vscode debugger for eigen
-
-
-
- enable vscode rn debugger - gkartalis
</details>

feat: enable vscode rn debugger

---

src/app/Scenes/Favorites/FavoriteArtworks.tsx

Aligns Saved artworks Grid on my profile saves tab
| Before | After|
|----|----|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-24 at 16 43 15](https://user-images.githubusercontent.com/21178754/221222442-2ce0b856-3227-4cc6-8397-de7f42a47b32.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-24 at 16 43 02](https://user-images.githubusercontent.com/21178754/221222418-3a931dfc-3bf3-4629-9f04-d0f28028dbd2.png)|
-  align favoriteArtworks grid on my profile - gkartalis
-
-
-
</details>
[docs]: …

fix: align favoriteArtworks grid on my profile

---

src/app/App.tsx
src/app/Scenes/Onboarding/Onboarding.tsx
src/app/utils/DevMenuWrapper.tsx

Allow devs to switch environment during onboarding
**iOS**
https://user-images.githubusercontent.com/11945712/220356423-51b7d6b6-495c-4dc9-9b3a-64d3f6f49fbd.mov
**Android**
https://user-images.githubusercontent.com/11945712/220356438-ada5866b-15bb-46a3-ba77-3207d679b72c.mov
-
-
-
- allow devs to switch environment during onboarding - mounir
</details>

chore: allow devs to switch environment during onboarding

---

src/app/store/config/features.ts

This PR resolves [FX-4643] 
mark AREnableESOnlySearch as readyForRelease
-
-
-
- mark AREnableESOnlySearch as readyForRelease - gkartalis
</details>
[FX-4643]: https://artsyproduct.atlassian.net/browse/FX-4643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: mark AREnableESOnlySearch as readyForRelease

---

src/app/Scenes/Home/Home.tsx
src/app/Scenes/Sales/UpcomingAuctions.tsx

This PR resolves [CX-3461] 
Adjust Upcoming Auctions rail and screen title.
-
-
-
-
</details>
[CX-3461]: https://artsyproduct.atlassian.net/browse/CX-3461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Adjust Upcoming Auctions rail and screen title

---

src/app/Components/AboveTheFoldFlatList.tsx
src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/Home/ArtistRails/ArtistRail.tsx
src/app/Components/Home/ArtistRails/RecommendedArtistsRail.tsx
src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tests.tsx
src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
src/app/Scenes/Articles/ArticlesList.tsx
src/app/Scenes/Home/Components/ArticlesRail.tsx
src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
src/app/Scenes/Home/Components/AuctionResultsRail.tsx
src/app/Scenes/Home/Components/CollectionsRail.tsx
src/app/Scenes/Home/Components/ContentCards.tsx
src/app/Scenes/Home/Components/FairsRail.tsx
src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
src/app/Scenes/Home/Components/OldCollectionsRail.tsx
src/app/Scenes/Home/Components/SalesRail.tsx
src/app/Scenes/Home/Components/ShowsRail.tsx
src/app/Scenes/Home/Home.tsx
src/app/Scenes/Home/homeAnalytics.ts
src/app/Scenes/Home/homeModules.ts
src/app/Scenes/Sales/UpcomingAuctions.tsx
src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
src/app/store/config/features.ts

This PR resolves [CX-3385] 
This PR adds tracking to the home screen rails.
Bonus: while adding tracking, I noticed few issues related to performance, then more issues then more issues, along the way I decided to fix everything I can fix.
- FPS went from 24 to 47 in boot
- FPS went from 32 to 48 after 3 seconds from boot
- Removed 2 unnecessary rerenders
- Clean up logic a bit
Before changes
https://user-images.githubusercontent.com/11945712/221570249-9ec8d682-6ba9-42fb-9bde-2a4f3c18d704.mov
After changes
https://user-images.githubusercontent.com/11945712/221570185-5ad95c3c-8fbb-40ee-95a1-880f4fbc1b49.mov
Before changes (throttle)
https://user-images.githubusercontent.com/11945712/221570293-690e88d8-2fd3-401e-b8c2-181ad993bfee.mov
After changes (throttling is way shorter and almost not …

feat: add tracking to home screen rails and improve performance

---

src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizNavigation.tsx
src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingWelcome.tsx

This PR resolves [GRO-1268] 
https://user-images.githubusercontent.com/17421923/220156503-1f7aabc7-14f5-40c6-b89f-5e349779ff08.mov
-
-
-
-
</details>
[GRO-1268]: https://artsyproduct.atlassian.net/browse/GRO-1268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: return to last interacted artwork

---

ios/Podfile.lock
package.json
yarn.lock

update react-native-fast-image from 8.5.11 to 8.6.3
-
-
-
- update react-native-fast-image from 8.5.11 to 8.6.3 - gkartalis
</details>

build(deps): update react-native-fast-image from 8.5.11 to 8.6.3

---

src/app/AppRegistry.tsx
src/app/Components/OpaqueImageView/OpaqueImageView.tsx
src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizNavigation.tsx
src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtworks.tsx
src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx

This PR adds home tabs to the art quiz results screen.
For more context : https://artsy.slack.com/archives/C01ADJNCS5D/p1676550493504989
-
-
-
-
</details>

feat: adding home tabs in results screen

---

src/app/AppRegistry.tsx
src/app/Components/FancySwiper/FancySwiper.tsx
src/app/Components/FancySwiper/FancySwiperCard.tsx

Add tinder like swiper component.
https://user-images.githubusercontent.com/11945712/221902926-43d2f79e-5544-4c1c-a460-87314ab4a55e.mov
- Add swiper component - mounir, sam
-
-
-
</details>

feat: add swiper component

---

src/app/Scenes/Home/homeModules.ts
src/app/Scenes/Sales/UpcomingAuctions.tsx

This PR resolves [CX-3461] 
Adjust Upcoming Auctions rail copy.
Follow up for https://github.com/artsy/eigen/pull/8280. The changes got lost in merge conflicts 🧹 
-
-
-
-
</details>
[CX-3461]: https://artsyproduct.atlassian.net/browse/CX-3461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Adjust Upcoming Auctions rail copy

---

app.json

prepare for new release 8.9.0
-
-
-
-
</details>

chore: prepare for new release 8.9.0

---

src/app/Scenes/Onboarding/OnboardingWelcome.tsx

artwork label signup color, came out of the mobile QA on Friday
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 13 - 2023-03-06 at 10 39 41](https://user-images.githubusercontent.com/21178754/223073652-cf448655-e584-43f0-b2ac-519464a5f016.png)|![Simulator Screen Shot - iPhone 13 - 2023-03-06 at 10 44 11](https://user-images.githubusercontent.com/21178754/223074348-05d3d442-a002-4e7c-8cba-8c9b6c690bb8.png)|
- artwork label signup color - gkartalis
-
-
-
</details>

fix: artwork label signup color

---

src/app/Scenes/Articles/ArticlesList.tsx

Remove bottom padding on articles screen.
-
-
-
-
</details>

fix: Remove bottom padding on articles screen

---

src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx

Remove artwork grid loading indicator overlay by moving it into the scroll view
[Slack Thread with context](https://artsy.slack.com/archives/C01B2P6LJUU/p1678179301028889)
-
-
-
-
</details>

fix: Remove artwork grid loading indicator overlay

---

src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx

Adds a default image size to artwork screen images in order to show the image if it doesn't has a height or width.
Artwork to reproduce the bug: https://www.artsy.net/artwork/andy-warhol-mao-f-and-s-ii-dot-97-3
[Slack Thread](https://artsy.slack.com/archives/C9SATFLUU/p1678097802934269)
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-03-07 at 11 43 17](https://user-images.githubusercontent.com/4691889/223403219-c59c5b83-c176-4034-adbf-98725fc4cf61.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-03-07 at 11 43 03](https://user-images.githubusercontent.com/4691889/223403238-29d0ed94-1904-4e0f-8be6-a8d43c9d2a77.png)|
-
-
-
-
</details> …

fix: Add default image size to artwork screen images

---

src/app/Components/ArtworkRail/ArtworkRailCard.tsx
src/app/Scenes/SellWithArtsy/Components/Header.tsx
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

This PR resolves [APPL-331] & [APPL-332] 
https://user-images.githubusercontent.com/11945712/223442231-6e64b4f3-2001-4361-9ad8-718e179fbff5.mov
https://user-images.githubusercontent.com/11945712/223442242-33d26814-6e9f-4af4-94c4-927cd86fab48.mov
#nochanges 
[APPL-331]: https://artsyproduct.atlassian.net/browse/APPL-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPL-332]: https://artsyproduct.atlassian.net/browse/APPL-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

feat: fix swa buttons

---

package.json
yarn.lock

bump @testing-library/react-native from 11.5.2 to 11.5.3
-
-
-
- bump @testing-library/react-native from 11.5.2 to 11.5.3 - gkartalis
</details>

build(deps): bump @testing-library/react-native from 11.5.2 to 11.5.3

---

package.json
yarn.lock

Removes unused zustand dependency. 
- 
-
-
- Removes zustand dependency - Brian
</details>

chore: remove unused zustand dependency

---

src/app/Components/ArtsyWebView.tsx

This PR resolves [APPL-330] 
I was unable to reproduce the bug locally but I think it is related to this part of the code - we can't show the confirmation modal unless we dismiss the active modal.
- Fix modal dismissal after making an offer
-
-
-
</details>
[APPL-330]: https://artsyproduct.atlassian.net/browse/APPL-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dimiss modal after make offer

---

ios/Podfile.lock
package.json
yarn.lock

This PR resolves [MOPLAT-583] 
Removes unused @react-native-community/geolocation dependency. 
-
-
-
- Remove unused geolocation dependency - brian
</details>
[MOPLAT-583]: https://artsyproduct.atlassian.net/browse/MOPLAT-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove unused rn-geolocation dependency

---

package.json
yarn.lock

updates remove markdown dep to latest. 
-
-
-
- updates remove markdown dependency to latest - Brian 
</details>

chore: update remove-markdown to latest

---

package.json
yarn.lock

Updates supercluster dep to latest version.
-
-
-
- update supercluster (map pins) dependency to latest - Brian 
</details>

chore: update supercluster to latest

---

src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx

This PR resolves [CX-3430] 
show only past auction results inside insights auction results
- show only past auction results inside insights - mounir
-
-
-
</details>
[CX-3430]: https://artsyproduct.atlassian.net/browse/CX-3430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: show only past auction results inside insights

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
src/palette/elements/PhotoRow/PhotoRow.tsx

This PR resolves [CX-3346] 
Prevent simultaniously adding and deleting images in SWA form to prevent race condition.
- Prevent simultaneously adding and deleting images in SWA form to prevent race condition - ole
-
-
-
</details>
[CX-3346]: https://artsyproduct.atlassian.net/browse/CX-3346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Prevent simultaneously adding and deleting images in SWA form to prevent race condition

---

src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
src/app/Scenes/Home/Home.tsx

This PR resolves [CX-3493] 
Sort Emerging Picks rail by decayed_merch.
-
-
-
-
</details>
[CX-3493]: https://artsyproduct.atlassian.net/browse/CX-3493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Sort Emerging Picks rail by decayed_merch

---

src/app/Scenes/Home/Home.tsx
src/app/Scenes/Home/useHomeModules.ts

Don't hide Auction Lots for You Ending Soon home screen rail.
[Slack Thread with Context](https://artsy.slack.com/archives/C01B2P6LJUU/p1678721528082989)
-
-
-
-
</details>

fix: Don't hide Auction Lots for You Ending Soon home screen rail

---

src/app/Scenes/Home/Components/AuctionResultsRail.tsx

Upcoming auction results view all URL.
-
-
-
-
</details>

fix: Upcoming auction results view all URL

---

src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx

This PR resolves [CX-3467] 
This PR removes the space before the Edition number in My Collection artwork details screen
| - | Android | iOS |
| -- | -- | -- |
| Before | <img width="367" alt="image" src="https://user-images.githubusercontent.com/20655703/225294079-936e259e-17e5-4363-90df-30aadc62dbed.png"> | <img width="394" alt="image" src="https://user-images.githubusercontent.com/20655703/225294250-2452073a-483a-4b7c-bbaf-6088c18bd67a.png"> |
| After | <img width="368" alt="image" src="https://user-images.githubusercontent.com/20655703/225294187-afb48244-286d-453f-ac94-c32ac9de54d7.png"> | <img width="393" alt="image" src="https://user-images.githubusercontent.com/20655703/225294261-5b6ad6e6-d1e3-4a53-8862-4ff3d7e0750a.png"> |
- Update …

fix(CX-3467): Update Edition Number spacing in My Collection artwork details

---

src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx

This PR resolves [CX-3266] 
This PR updates the url used in the AddPhotos component in My Collection Form to be the same as the one used in [My Collection artwork details screen](https://github.com/artsy/eigen/blob/main/src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx#L40), hence benefitting from the already loaded image on the device
https://user-images.githubusercontent.com/20655703/225285744-ebde1eed-e823-448b-bd24-9acec0302871.mp4
- Update image URL inside AddPhotos component in My Collection artwork form - mrsltun
-
-
-
</details> …

fix(CX-3266): Update AddPhotos image URLs

---

src/app/Scenes/Home/Components/MarketingCollectionRail.tsx

Addresses [CX-3493-comment](https://artsyproduct.atlassian.net/browse/CX-3493?focusedCommentId=55737)
Increase number of artworks in Marketing Collections rail to 20.
- Increase number of artworks in Marketing Collections rail to 20 - ole
-
-
-
</details>

fix: Increase number of artworks in Marketing Collections rail to 20

---

docs/README.md
docs/add_an_experiment.md
docs/best_practices.md
docs/deploy_to_app_store.md
docs/deploy_to_play_store.md
docs/developing_a_feature.md
docs/getting_started.md
docs/images.md
docs/release_candidate_code_freeze.md
docs/storybook.md
docs/testing.md
docs/troubleshooting.md

This PR updates the broken links in the docs, as well as some styling and adding 🔐 icon on Artsy team links
-
-
-
- update broken links and styling in docs - mrsltun
</details>

fix: Update broken links and styling in the docs

---

src/app/system/relay/middlewares/errorMiddleware.ts

Adds version / OS to Volley tags so we will be able to differentiate in [datadog dashboards](https://app.datadoghq.com/dashboard/yyp-59r-ehf/cx-main-queries-dashboard?tile_focus=2264222510213684&from_ts=1666750635684&to_ts=1676395575684&live=true) between version / OS.
-
-
-
- add version / OS to volley tags - gkartalis
</details>

feat: add version / OS to volley tags

---

package.json

This PR updates the `sync-schema:localhost` in package.json since it wasn't working properly 😕
Plus prettify the newly synced schema
-
-
-
- update sync-schema:localhost script - mrsltun
</details>

fix: update sync-schema:localhost script

---

src/app/store/config/features.ts

Prepare SWA Landing Page for release
-
-
-
- Prepare SWA Landing Page for release - kizito
</details>

Prepare SWA Landing Page for release

---

src/app/Scenes/SellWithArtsy/utils/useSWALandingPageData.tsx

update useSWAlandingpagedata url
-
-
-
- update useSWAlandingpagedata url - kizito
</details>

update useSWAlandingpagedata url

---

data/schema.graphql
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx

This PR resolves [CX-3524] 
This PR is a follow-up on artsy/metaphysics#4888
This PR updates the logic of the request price estimate banner to use the new field `isPriceEstimateRequestable` from metaphysics
-
-
-
- Refactor request price estimate banner logic - mrsltun
</details>
[CX-3524]: https://artsyproduct.atlassian.net/browse/CX-3524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3524): Refactor Request Price Estimate banner logic

---

src/app/Scenes/SellWithArtsy/Components/FAQSWA.tsx
src/app/Scenes/SellWithArtsy/Components/Header.tsx
src/app/Scenes/SellWithArtsy/Components/SpeakToTheTeam.tsx
src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx

- Small update to SWA copy
- Remove 20px space from header
[swa-lp-final-copy.webm](https://user-images.githubusercontent.com/18648835/225895397-6296a164-5d33-4187-bfbf-162e32272abb.webm)
- Update SWA LP copy - kizito
-
-
-
</details>

Update SWA LP copy

---

src/app/Scenes/SellWithArtsy/Components/Testimonials.tsx

- New design entails centering the testimonials instead of previous left align
- Center Testimonials - kizito
-
-
-
</details>

Center Testimonials

---

package.json
src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
src/app/Scenes/Search/components/SearchResult.tests.tsx
src/app/Scenes/Search/components/SearchResult.tsx
src/app/utils/tests/extractText.tests.tsx
src/app/utils/useGlobalState.tests.tsx
src/palette/elements/Avatar/Avatar.tests.tsx
yarn.lock

Major testing library version bump
[migration guide](https://callstack.github.io/react-native-testing-library/docs/migration-v12)
[changelog](https://github.com/callstack/react-native-testing-library/releases/tag/v12.0.0)
-
-
-
- bump @testing-library/react-native from 11.5.3 to 12.0.0
</details>

build(deps): bump @testing-library/react-native from 11.5.3 to 12.0.0

---

src/app/Components/ArtworkRail/ArtworkRail.tsx
src/app/Components/BrowseMoreRailCard.tsx
src/app/Scenes/Home/Components/AuctionResultsRail.tsx
src/app/Scenes/Home/Components/SalesRail.tsx
src/app/Scenes/Home/homeAnalytics.ts
src/app/store/config/features.ts

This PR resolves [CX-3517] 
Add browse more card to auction rails.
| | |
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-03-17 at 09 32 41](https://user-images.githubusercontent.com/4691889/225853771-3b133ccc-45a1-4190-bad1-828995984fa6.png) |![Simulator Screen Shot - iPhone 14 Pro - 2023-03-17 at 09 26 34](https://user-images.githubusercontent.com/4691889/225853798-400bc46d-e258-4410-8bde-35c3174a7d4b.png) |
- Add browse more card to auction rails - ole
- Add browse more card to auction result rails - ole
-
-
-
</details> …

feat: Add browse more card to auction rails

---

src/app/AppRegistry.tsx
src/app/Scenes/AuctionResult/AuctionResult.tsx

| Before                                                                                                                                                                | After                                                                                                                                                                 |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="389" alt="Screenshot 2023-03-20 at 10 30 39" …

fix: auction result screen header

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotos.tsx
src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx

This PR resolves [CX-3542] 
Fix photos validation issue on SWA form
https://user-images.githubusercontent.com/11945712/226355914-a79ea905-607d-4ede-8e8c-c4fed907d72e.mov
- unable to submit after deleting a photo on sell flow - mounir
-
-
-
</details>
[CX-3542]: https://artsyproduct.atlassian.net/browse/CX-3542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3542): photos validation issue on swa form

---

src/app/Scenes/AuctionResult/AuctionResult.tests.tsx
src/app/Scenes/AuctionResult/AuctionResult.tsx

This PR resolves [CX-3403] 
Address comments in [[CX-3403]
](https://artsyproduct.atlassian.net/jira/software/c/projects/CX/boards/77?modal=detail&selectedIssue=CX-3403)
#nochanges 
[CX-3403]: https://artsyproduct.atlassian.net/browse/CX-3403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3403]: https://artsyproduct.atlassian.net/browse/CX-3403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3403): address UI bugs

---

src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx

This PR resolves [CX-3416] 
Hide upcoming auction results filter if no results are available
https://user-images.githubusercontent.com/11945712/226416044-cf63e066-975d-430b-927f-b8666e1ceedb.mov
- Hide upcoming auction results if none are available - mounir
-
-
-
</details>
[CX-3416]: https://artsyproduct.atlassian.net/browse/CX-3416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3416): hide upcoming auction results filters if none are available

---

src/app/Scenes/Artist/Artist.tsx
src/app/Scenes/ArtistArticles/ArtistArticles.tsx
src/app/Scenes/Artwork/Artwork.tsx
src/app/Scenes/Sale/Sale.tsx
src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx

Replacing instances of the old relay env `defaultEnvironment -> getRelayEnvironment()`
The reason for this is that the prev one was creating weird UI updating issues like [this](https://github.com/artsy/eigen/pull/8391) and [this](https://github.com/artsy/eigen/pull/8219)
-
-
-
-  replace old default env with getRelayEnv - gkartalis
</details>

refactor: replace old default env with getRelayEnv()

---

package.json
src/app/App.tsx
yarn.lock

Adds relay-dev-tools in flipper so we can debug what's going on with the relay store 🤩
-
-
-
- add relay dev tools on flipper - gkartalis
</details>

feat: add relay dev tools on flipper

---

yarn.lock

Run yarn in main
cc @gkartalis 
#nochangelog

chore: run yarn in main

---

src/app/Components/Lists/AuctionResultListItem.tests.tsx
src/app/Components/Lists/AuctionResultListItem.tsx
src/app/Scenes/AuctionResult/AuctionResult.tsx

This PR resolves [CX-3487] 
Do not show estimate if an auction is past
https://user-images.githubusercontent.com/11945712/226566745-fe4fdc7a-e0fe-4b00-b112-fa0391052170.mov
- Do not show estimate if an auction is in the past - mounir
-
-
-
</details>
[CX-3487]: https://artsyproduct.atlassian.net/browse/CX-3487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(CX-3487): do not show estimate if an auction is in the past

---

src/app/Scenes/Articles/Articles.tests.tsx
src/app/Scenes/Articles/ArticlesList.tsx

This PR refactors the Articles test to use the new `setupTestWrapper` method
-
-
-
- refactor Articles.tests.tsx to use setupTestWrapper - mrsltun
</details>

refactor(practice): Update articles test

---

src/app/Scenes/Home/Components/AuctionResultsRail.tests.tsx
src/app/Scenes/Home/Components/AuctionResultsRail.tsx

This PR addresses the comment [here](https://artsyproduct.atlassian.net/browse/CX-3517?focusedCommentId=55889)
Adjust copy on auction results rails to match the copy updates
#nochangelog 

fix: adjust copy on auction rails

---

package.json
yarn.lock

This PR updates redux-flipper to latest version
-
-
- update redux-flipper plugin to latest - mounir
-
</details>

chore: update redux-flipper to latest version

---

src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollection.tsx

This PR resolves [GRO-1594] 
This PR is to fix a bug where the descriptions for trending collections at the end of the art quiz flow rendered html tags along with text. In order to fix this we will need two versions of collections descs for both web (which supports HTML) and eigen (which does not). 
This thread provides more context: https://artsy.slack.com/archives/C02BAQ5K7/p1679429352422569
In formatting the markdown there is a line break that sneaks in w/ this solution, but might not be a big deal? Can try to make the text limit even shorter if possible to hide this. 
-
-
-
-
</details>
[feature …

fix(quiz): remove html from trending collections desc

---

fastlane/metadata/android/en-US/changelogs/default.txt
fastlane/metadata/en-US/release_notes.txt

Release notes for 8.10
#nochangelog

chore: release notes 8.10.0

---

app.json

prepare for new app version
#noChangelog

chore: prepare for new app version

---

src/app/Scenes/Home/useHomeModules.ts

This PR resolves [CX-3544]
Reposition works from galleries you follow
- reposition works from galleries you follow - mounir
-
-
-
</details>
[CX-3544]: https://artsyproduct.atlassian.net/browse/CX-3544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: reposition works from galleries you follow

---

src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
src/app/Scenes/Home/useHomeModules.ts

This PR resolves [CX-3567] 
Rename upcoming auction lots components
https://user-images.githubusercontent.com/11945712/228200906-56db6327-44f4-43a0-8327-a58c2403afed.mov
#nochanges
[CX-3567]: https://artsyproduct.atlassian.net/browse/CX-3567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: rename upcoming auction lots components

---

src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx

This PR resolves [CX-3541] 
- Use version C for new works for you rail
- Roll version C for all new works for you context - mounir
-
-
-
</details>
[CX-3541]: https://artsyproduct.atlassian.net/browse/CX-3541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: use version C for new works for you rail

---

src/app/Components/Home/ArtistRails/ArtistCard.tsx

This PR resolves [CX-3488] 
Update artist rail card
https://user-images.githubusercontent.com/11945712/228184647-77487768-343a-4b66-9a45-b9f395d437d8.mov
- Update homefeed rail card component - mounir
-
-
-
</details>
[CX-3488]: https://artsyproduct.atlassian.net/browse/CX-3488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update artist rail card

---

scripts/flip-table

Removes generated files on flip table script (context on the why [here](https://artsy.slack.com/archives/C02NAJ2CGLW/p1674514816335159))
-
-
-
- Removes generated files on flip table script  - gkartalis
</details>

feat: update flip table script to remove __generated__ files

---

data/schema.graphql
src/app/Components/Lists/AuctionResultListItem.tests.tsx
src/app/Components/Lists/AuctionResultListItem.tsx

This PR resolves [CX-3580] 
Navigate to lot page for upcoming auction results
- navigate to lot page for upcoming auction results - mounir
-
-
-
</details>
[CX-3580]: https://artsyproduct.atlassian.net/browse/CX-3580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: navigate to lot page for upcoming auction results

---

src/app/Components/Home/ArtistRails/ArtistCard.tsx
src/app/Components/Home/ArtistRails/ArtistRail.tsx

#nochanges
This PR removes x button and adjust font size on the artist Card
#nochanges

chore: remove x button

---

package.json
yarn.lock

https://github.com/artsy/eigen/pull/8426 needs resolution in package json to work 😅
#nochangelog

fix: step 2 needs resolution to work properly 😅

---

Gemfile
Gemfile.lock

Removes the psych gem. Devs are having setup issues installing this gem, the comment suggests it is to keep the Podfile.lock consistent, might be nice to revisit because we still have problems with that but being able to build more important for now :) 
-
-
-
- Remove psych gem to resolve build issues - Brian 
</details>

fix: remove psych, causing setup issues

---

src/app/utils/DynamicIslandStagingIndicator.tsx

I added this Dynamic Island dev indicator, but I just noticed that if the simulator (or the device) is named anything different than `iPhone 14 Pro`, then it will not show up. I used the device id, which I should have from the start. I also print out the device id if its not found, so it can be added possibly.
-
-
-
- dev indicator on dynamic island is properly detecting devices
</details>

feat: better device detection

---

src/app/Scenes/SellWithArtsy/index.tests.tsx

- Fix failing SWA LP tests related to old designs
-
-
-
-
</details>

fix Failing SWA tests

---

src/app/store/config/features.ts
src/app/utils/placeholders.tsx
src/app/utils/useSkeletonAnimation.tsx

Add skeleton animation to loading placeholders
https://user-images.githubusercontent.com/11945712/229451670-e6754e46-c3be-4d4f-80da-818f6bcb0a85.mov
- add skeleton animation to loading placeholders - mounir, ole
-
-
-
</details>

feat: add skeleton animation to loading placeholders

---

src/app/Components/Home/ArtistRails/ArtistCard.tsx

Adjust artist notable works image width to fit within container
https://user-images.githubusercontent.com/11945712/229589163-3578cd2e-195a-4ffe-99c0-3edc6e7552d6.mov
-
-
-
-
</details>

chore: adjust artist notable works image width

---

src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx

Rounds sort and filter button to match button designs
|Before|After|
|---|---|
|![Simulator Screen Shot - iPhone 13 - 2023-04-04 at 11 46 38](https://user-images.githubusercontent.com/21178754/229754646-12fa00ba-0f80-48fe-a2fc-1fc3c778a822.png)|![Simulator Screen Shot - iPhone 13 - 2023-04-04 at 11 46 19](https://user-images.githubusercontent.com/21178754/229754674-0a6956c5-548a-4739-b8c7-50d330381aeb.png)|
- round auction sort filter button - gkartalis
-
-
-
</details>

fix: round auction sort filter button

---

src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
src/app/Scenes/MyProfile/MyProfileSettings.tsx

This PR resolves [CX-3570] 
| --- | --- |
| ![simulator_screenshot_9DC79E32-646C-48C6-85EB-8C3EE3891471](https://user-images.githubusercontent.com/36167539/228868044-70996192-a7bb-4b40-b0fb-b80505390b9a.png) | ![simulator_screenshot_32777AEC-E49D-495D-9EF2-1D3081DFA3FC](https://user-images.githubusercontent.com/36167539/228867858-b0742586-edee-4318-90aa-f0db9b5b224c.png)
- adjust settings menu to the new requirements -daria
-
-
-
</details>
[CX-3570]: …

fix(CX-3570): adjust settings menu to the new requirements

---

src/app/utils/DevMenu.tsx
src/palette/elements/CollapseMenu/CollapseMenu.tsx

This PR makes the following changes
- Move items that are not used to the dev tools
- Add animation to the collapse menu to make it clear that it can be dismissed
https://user-images.githubusercontent.com/11945712/229542169-1d3d3c98-04ee-4a29-8ee9-caf2eb36dd62.mov
-
-
-
-
</details>

chore: Improve Dev Menu

---

src/app/Scenes/Home/Home.tsx

- fix position y tracking on artwork rails typo 🤦‍♂️
#nochanges

fix: position y tracking on artwork rails typo

---

src/app/Components/Lists/AuctionResultListItem.tsx
src/app/Scenes/AuctionResult/AuctionResult.tsx

This PR fixes https://artsyproduct.atlassian.net/browse/CX-3594
https://user-images.githubusercontent.com/11945712/230026087-1d80f84e-2552-4bd0-85ec-283af6281ac1.mov
- Show placeholder image when auction results image fails to load - mounir
-
-
-
</details>

fix: Show placeholder image when auction results image fails to load

---

src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
src/app/Components/Bidding/Screens/Registration.tsx

Copy change. Companion PR to https://github.com/artsy/force/pull/12179.
[Hackathon card](https://www.notion.so/artsy/All-Bids-Are-Binding-check-box-when-registering-to-an-auction-placing-a-bid-6e430c678ca4466c97a21f3bb8e3c654?pvs=4)
| --- | ---  |
| ![Screenshot 2023-04-03 at 12 04 18](https://user-images.githubusercontent.com/5361806/229481623-8c4ee5bb-55f1-4261-a31f-70b5873217f4.png) | ![Screenshot 2023-04-03 at 12 05 56](https://user-images.githubusercontent.com/5361806/229481628-41aba5a9-6822-4653-b694-5022e95c7680.png) |
| --- | ---  |
| ![Screenshot 2023-04-03 at 12 06 51](https://user-images.githubusercontent.com/5361806/229481634-2fc76b1b-c80c-4368-a0f7-f12241bb3b5e.png) | ![Screenshot 2023-04-03 at 12 06 …

feat: update pre-bid checkbox copy

---

app.json

chore: Update app version to 8.12.0

---

package.json
yarn.lock

bump @artsy/palette-mobile from 11.0.6 to 11.0.7
- 
-
-
- bump @artsy/palette-mobile from 11.0.6 to 11.0.7 - gkartalis
</details>

build(deps): bump @artsy/palette-mobile from 11.0.6 to 11.0.7

---

src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkSubmitted.tsx

This PR resolves [CX-3525] 
- Update copy to follow new designs
[CX-3525]: https://artsyproduct.atlassian.net/browse/CX-3525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update copy to follow new designs

---

src/app/Components/PrefetchFlatList.tsx
src/app/Scenes/Home/Home.tsx

Fix home viewAreaCoveragePercentThreshold fields and type.
-
-
-
-
</details>

chore: Fix home viewAreaCoveragePercentThreshold fields and type

---

src/app/Components/PrefetchFlatList.tsx

Use default config for PrefetchFlatlist to avoid bugs like https://github.com/artsy/eigen/pull/8372#discussion_r1160022051
-
-
-
-
</details>

chore: Use default config for PrefetchFlatlist

---

scripts/deploy-beta-android
scripts/deploy-beta-ios

We often cancel each other builds by mistake when we trigger new builds. This command will help us avoid that by pointing out that there is a build in progress already.
___
**When no build is available, it behaves the same way as the normal command (triggered the build on main here to avoid having the same commit head)**
https://user-images.githubusercontent.com/11945712/230423445-3a93338e-2ed5-480e-9c15-4aafd1d0b71d.mov
___
**When a build is running, cancel**
https://user-images.githubusercontent.com/11945712/230423504-a4316ce2-b924-46d3-920b-dcdc6b976680.mov
___
**When a build is running, overwrite**
https://user-images.githubusercontent.com/11945712/230423580-3b184dfa-babe-4b83-8640-b312905f4d7a.mov
-
-
-
- prompt to overwrite current …

chore: prompt to overwrite current running beta build

---

src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx

This PR resolves [TX-1114] 
- Update wire transfer bank details 
-
-
-
</details>
[TX-1114]: https://artsyproduct.atlassian.net/browse/TX-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(TX-1114): update wire transfer details

---

src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx

Follow up on https://github.com/artsy/eigen/pull/8474, this fixes a typo in the wire instructions.
- 
-
-
-
</details>

fix: wire copy typo

---

ios/Podfile.lock
package.json
src/app/App.tsx
src/app/store/AuthModel.ts
src/app/utils/useIdentifyUser.ts
src/app/utils/useSiftConfig.ts
src/setupJest.ts
yarn.lock

This PR resolves [PRO-87]
Uses [Sift's RN wrapper](https://github.com/SiftScience/sift-react-native) to send "device information and app life cycle events" to Sift ([docs](https://sift.com/developers/docs/curl/javascript-api/overview)).
Noting that I've already updated the .env.shared that lives in S3, as well as CircleCI env, with the new variables.
This is unfortunately pretty much black-box; I can see what payloads show up in our Sift sandbox but there doesn't appear to be any other way to get at what's triggered when etc.
Event payloads look like:
```json
{
"data": [
{
"user_id": "5744b8888b3b8145d7005304",
"installation_id": "81F4B083-DC04-4047-8304-2969997400A0",
"time": 1678895687765,
"ios_app_state": {
"network_addresses": [
"fe80::aede:48ff:fe00:1122",
"172.16.100.10", …
```

feat: integrate Sift SDK (PRO-87)

---

android/app/src/main/AndroidManifest.xml
src/app/AppRegistry.tsx
src/app/Scenes/PriceDatabase/PriceDatabase.tests.tsx
src/app/Scenes/PriceDatabase/PriceDatabase.tsx
src/app/routes.ts

This PR resolves [CX-3601] 
Add Price Database route.
-
-
-
-
</details>
[CX-3601]: https://artsyproduct.atlassian.net/browse/CX-3601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add Price Database route

---

src/app/Components/ArtsyWebView.tsx
src/app/Scenes/VanityURL/VanityURLEntity.tsx

This PR resolves [CX-3599] 
- DeepLinking to arbitrary vanity url in Eigen is broken. So, urls like https://artsy.net/find-the-art-you-want  when opened in the App can't load. This is because in ArtsyWebView there is an attempt to redirect VanityUrls to use a native screen, so we end up with an infinite loop with a new Webview screen added to the stack with each loop.
https://user-images.githubusercontent.com/18648835/231439688-7ec17442-d15e-4879-823b-a04ea728e23f.MP4
- Fix broken vanityURLs in Webview - kizito
-
-
-
</details>
[docs]: …

Fix(CX-3599): Fix broken vanityURLs in Webview

---

package.json
src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
yarn.lock

Upgrade Cohesion to 4.124.0 and add data to `is_p1_artist` to avoid type errors.
-
-
-
-
</details>

chore: Upgrade Cohesion to 4.124.0

---

src/app/Scenes/MyCollection/MyCollection.tests.tsx
src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
src/app/Scenes/SellWithArtsy/Components/Footer.tsx

This PR resolves [CX-3605]
This PR resolves [CX-3608] 
Update copy changes
<p align="center">
&nbsp; &nbsp; &nbsp; &nbsp;
</p>
-  Update Copy Changes - kizito
-
-
-
</details>
[CX-3605]: https://artsyproduct.atlassian.net/browse/CX-3605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3608]: https://artsyproduct.atlassian.net/browse/CX-3608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: Update Copy Changes

---

src/app/Scenes/MyAccount/MyAccount.tsx

- change title on the Account Settings screen -daria
-
-
-
</details>

chore: change title

---

src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx

Add keyboardShouldPersistTaps to price database scroll view to make buttons work again in scroll view.
https://stackoverflow.com/questions/36822391/react-native-touchableopacity-onpress-problems-inside-a-scrollview
-
-
-
-
</details>

fix: Add keyboardShouldPersistTaps to price database scroll view

---

package.json
yarn.lock

bumps palette with the reanimated fix
#nochangelog

build(deps): bumps palette version with reanimated fixes
