artsy/eigen

Artsy_WatchKit_Extension/Watch_Models/WatchArtwork.m
First of thank you so much for sharing your app so we can all learn from your architecture and implementation.
This super small PR just makes the font usage in WatchArtwork OSS friendly.
=> PR to make watch artwork OSS friendly :)

Artsy/Constants/ARAppConstants.m
=> @orta => Default (non-test) should run async

Artsy/Views/Artwork/Auctions/ARArtworkAuctionPriceView.m, Artsy/Views/Artwork/Auctions/ARAuctionBidderStateLabel.m, Podfile, Podfile.lock, docs/BETA_CHANGELOG.md
=> @jorystiefel => [Artwork] Ensure dollar amounts always format with dollar sign.

Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, Artsy_Tests/Supporting_Files/ARTestHelper.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuNavigationDataSourceSpec.m, Makefile, circle.yml, docs/BETA_CHANGELOG.md
=> @jorystiefel => Fix app notification badge not being cleared

Artsy/App/ARAppDelegate.m, docs/BETA_CHANGELOG.md
Fixes #772.
Gonna kick-off a beta build from this branch. Once this PR is merged I’ll start the App Store build.
=> @orta => [Push Notifications] Always register after initial on-boarding.

Artsy/App/ARAppNotificationsDelegate.m, Artsy/Constants/ARAppConstants.h, Artsy/Constants/ARAppConstants.m, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, docs/BETA_CHANGELOG.md
This guy is merging all them PRs.
=> @alloy => Add push notification token pastboard support to admin view

Makefile, docs/BETA_CHANGELOG.md
As suggested by CircleCI support.
/cc @orta @ashfurrow
=> [CircleCI] Add build action to test task to ensure simulator runs.

Artsy/View_Controllers/Fair/ARProfileViewController.m, docs/BETA_CHANGELOG.md
=> @alloy => Remove ?foo=bar parameter

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARAppActivityContinuationDelegate.h, Artsy/App/ARAppActivityContinuationDelegate.m, Artsy/App/ARSwitchBoard.m, Artsy/Artsy.entitlements, Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, docs/BETA_CHANGELOG.md
=> @jorystiefel => Support Web-to-Native Handoff and Universal Links 📱

Artsy/Views/Styled_Subclasses/Buttons/ARNavigationButton.m
@alloy as noted in your feedback, cleaned up some of the constraints.
=> @alloy => [iOS 9 Tests] Constraints cleanup

Artsy.xcodeproj/project.pbxproj, Artsy/Categories/Apple/UIViewController+ARUserActivity.h, Artsy/Categories/Apple/UIViewController+ARUserActivity.m, Artsy/Categories/Apple/UIViewController+WithLoadedData.h, Artsy/Categories/Apple/UIViewController+WithLoadedData.m, Artsy/View_Controllers/Artwork/ARArtworkViewController.m, Artsy/View_Controllers/Core/ARArtistViewController.m, Artsy/View_Controllers/Fair/ARFairViewController.m, Artsy/View_Controllers/Fair/ARShowViewController.m, Artsy/Views/Collection_Views/ARGeneViewController.h, Artsy/Views/Collection_Views/ARGeneViewController.m, Artsy_Tests/View_Controller_Tests/Fair/ARFairViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Gene/ARGeneViewControllerTests.m, docs/BETA_CHANGELOG.md
=> @orta => [Handoff] Make Native to desktop web work.

Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.h, Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m, Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m, Artsy/View_Controllers/Web_Browsing/ARTopMenuInternalMobileWebViewController.m, Artsy_Tests/View_Controller_Tests/Web_Browsing/ARInternalMobileWebViewControllerTests.m, docs/BETA_CHANGELOG.md
* makes topVC background black
* doesn't have an extra top margin
* Improves logging around allowing/cancelling requests
Ran out of time.
Includes #819 - cause 'ya know.
=> @alloy => webkit polish

Artsy/View_Controllers/Util/Logging/ARLogger.m, docs/BETA_CHANGELOG.md
There was some double negation going on, I opted to keep it simple.
Fixes #824
=> @orta => Disable network logging in release

Artsy/App/ARAppDelegate+Analytics.m, Artsy/Networking/API_Modules/ArtsyAPI+SiteFunctions.h, Artsy/Networking/API_Modules/ArtsyAPI+SiteFunctions.m, Artsy/View_Controllers/Contact/ARInquireForArtworkViewController.m, docs/BETA_CHANGELOG.md
@orta please review and make sure this looks good.
=> @orta => [Inquiries] Add response data to inquiry failure analytics

Artsy/App/ARAppDelegate.m, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m, Artsy/View_Controllers/Favorites/ARFavoritesViewController.m, docs/BETA_CHANGELOG.md
We want to be saying no to actions that require a user account when in demo mode. Caught a few.
=> @jory => Add checks for Demo

Artsy/View_Controllers/App_Navigation/ARAppSearchViewController.m, docs/BETA_CHANGELOG.md
Doesn't entirely fix https://github.com/artsy/eigen/issues/744 but it definitely makes it presentable by my standards.
=> @alloy => [Search] Quick fix to make app search look nicer in iOS9

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARApplicationShortcutItemDelegate.h, Artsy/App/ARApplicationShortcutItemDelegate.m, Artsy/App_Resources/Artsy-Info.plist, Podfile, Podfile.lock
This merges into your PR, not master.
=> @jory => Static Search button

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARSwitchBoard.m, Artsy/App_Resources/Artsy-Info.plist, Artsy/Constants/ARAppConstants.h, Artsy/Constants/ARAppConstants.m, Artsy/Models/API_Models/Partner_Metadata/Artwork.h, Artsy/Models/API_Models/Partner_Metadata/Artwork.m, Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.h, Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m, Artsy/View_Controllers/Login_and_Onboarding/ARPersonalizeWebViewController.m, Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.h, Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m, Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m, Artsy/Views/Artwork/ARArtworkActionsView.m, Artsy_Tests/View_Controller_Tests/Web_Browsing/ARAuctionWebViewControllerTests.m, Artsy_Tests/View_Tests/ARArtworkActionsViewTests.m, docs/BETA_CHANGELOG.md
=> @jorystiefel => [Auction] Pop bid VC after bidding and update views with new price.

Artsy/View_Controllers/Search/ARSearchViewController.m, docs/BETA_CHANGELOG.md
=> @jorystiefel => [Search] Do not allow rotation on iPhone.

Artsy/App/ARAppActivityContinuationDelegate.m, Artsy/App/ARAppDelegate.h, Artsy/App/ARAppDelegate.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/2_-_Calls_to_Action/ARSignUpSplashViewController.m, docs/BETA_CHANGELOG.md
=> @jorystiefel => [Handoff] Bypass on-boarding.

Artsy/App/ARAppDelegate.h, Artsy/App/ARAppDelegate.m
=> @orta => [AppDelegate] Get rid of warning.

Artsy/Views/Collection_View_Cells/ARArtworkWithMetadataThumbnailCell.m, docs/BETA_CHANGELOG.md
=> @orta => [Embedded Models] Fix layout bug on iPad.

Artsy/Categories/Categories.h
=> add if __include to Categories.h file to remove font file not found err

Artsy/Networking/Network_Models/ARArtistFavoritesNetworkModel.m
=> @alloy => Improve the artist data for demo mode

Artsy/App/ARSwitchBoard.m, Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m, Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m, Artsy_Tests/View_Controller_Tests/Web_Browsing/ARAuctionWebViewControllerTests.m, docs/BETA_CHANGELOG.md
=> @orta => Auction related fixes.

Gemfile, Gemfile.lock
Updates to a new release based on [our discussion](https://github.com/ashfurrow/second_curtain/issues/31).
=> @orta Updated second_curtain

Artsy/App/ARSpotlight.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
When I looked through our crashes 
https://rink.hockeyapp.net/manage/apps/37029/app_versions/44/crash_reasons/54275149?type=crashes
I kept seeing the same thing, this always happens after onboarding, not sure the exact cause of it, but this should deal with the key issue of "it crashes."
=> @alloy => Use root url if we cannot generate a public artsy url

Artsy/App/ARAppDelegate+Analytics.m
Hopefully this is the right one and it fixes #931.
=> [Analytics] Fix `nil` slipping into data.

Artsy.xcodeproj/project.pbxproj, Artsy/App_Resources/Artsy.Store.entitlements, Artsy/App_Resources/Artsy.entitlements
=> [Project] Remove staging domain from associated domains in Store build.

Artsy/View_Controllers/Feed_VCs/ARSimpleShowFeedViewController.m, Podfile.lock, docs/BETA_CHANGELOG.md
=> [Show Feed] Don’t scroll the hero units view.

Artsy/App/ARAppDelegate+Analytics.m
=> Fixes switched up analytics calls for signing up with twitter/facebook - fixes #951

Artsy/Networking/API_Modules/ARUserManager.m, Artsy/View_Controllers/Util/ARValueTransformer.h, Artsy/View_Controllers/Util/ARValueTransformer.m, Podfile, Podfile.lock
Waiting for this to be merged to perform the last cleanup https://github.com/orta/ARAnalytics/pull/232
=> Segment cleanup

Podfile, README.md
Re: https://github.com/artsy/mobile/issues/60
=> Use ARTSY_STAFF_MEMBER in the Podfile

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARAppDelegate+Analytics.m, Artsy/App/ARAppDelegate.m, Artsy/App/ARAppStatus.h, Artsy/App/ARAppStatus.m, Artsy/App_Resources/Artsy-Info.plist, Artsy/View_Controllers/Core/ARFeedLinkUnitViewController.m, Artsy_Tests/View_Controller_Tests/Util/ARFileUtilsTests.m, Makefile, circle.yml, config/generate_changelog_short.rb, docs/deploy_to_beta.md, docs/getting_started.md, fastlane/AppFile, fastlane/PilotFile
Introduces an AppStatus model, that lets you know whether we're in beta or not inside the app. 
Adds a deploy command that just pushes your current branch to the beta. Fixes CI.
=> Migrate to using deploying test flight betas via Fastlane

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARAppDelegate+Analytics.m, Artsy/App/ARAppDelegate.m, Artsy/App/ARAppStatus.h, Artsy/App/ARAppStatus.m, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Core/ARFeedLinkUnitViewController.m, docs/BETA_CHANGELOG.md
This flag signals whether the build is a beta or dev build vs an app store build and is required in the beta build once https://github.com/artsy/gravity/pull/9529 is merged.
=> Include production flag in push notification registration.

Artsy/Tooling/ARWebViewCacheHost.m, Artsy_Tests/App_Tests/ARWebViewCacheHostSpec.m, docs/BETA_CHANGELOG.md
Adds support for auto-playing the videos we use in the BG for super-posts in martsy/force.
=> Support auto-playing html5 videos - fixes #980

Artsy/App_Resources/Artsy-Info.plist
This will have to be merged into master too.
See: https://developers.facebook.com/docs/ios/ios9
=> Support latest facebook SDK

Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> Support latest Facebook SDK on master

CHANGELOG.yml, Gemfile, Gemfile.lock
Puts us on the latest stable release.
=> Update Danger to latest release

Artsy/Networking/ARNetworkConstants.h, Artsy/Networking/ARNetworkConstants.m, Artsy/Networking/ARRouter.m, CHANGELOG.yml
Updates signing profiles: When I added myself as an individual developer it required updating the certs
Still hooked up good.
I verified that the Gene artworks is the same as the app store build.
=> Use newer API routes for genes

Podfile
Finally, I got something done today!
=> [Pods] ¡Silencio!

Podfile.lock
Looks like it was accidentally left uncommited from https://github.com/artsy/eigen/pull/1046/
=> Updates Podfile.lock

Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/App/ARSwitchboard+Eigen.m, CHANGELOG.yml
=> Use AROptions to make native auctionview an option 

Artsy/App/ARHockeyFeedbackDelegate.swift
Adds some default text, and lets the analytics data be optional and show as text so we can click in the website and look.
=> Improve how we get feedback

Podfile, Podfile.lock
Based on https://github.com/vadymmarkov/MARKRangeSlider/pull/22 getting merged + pushed.
=> Moved pod back to trunk.

CHANGELOG.yml, Gemfile, Gemfile.lock, circle.yml
This uses the new `--base` option which lets you specify a specific commitish to base against.
=> Use the latest Danger / pilot

Dangerfile, Makefile
I also added the ability to declare a PR trivial, and worth skipping the CHANGELOG requirement for Danger.
=> Add the developer extra file to git's ignore index  #trivial

Artsy_Tests/Supporting_Files/ARTestHelper.m
I can't guarantee this will help, so if this fails with those errors, we can def not merge. Will run theses tests 3-4 times, if it's always green I'll merge.
=> Attempt to cache fonts before loading the testing environment #trivial

Artsy/App/ARAnalyticsConstants.h, Artsy/App/ARAppDelegate+Analytics.m, Artsy/Networking/API_Modules/ARUserManager.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m, CHANGELOG.yml, Dangerfile
=> Analytics re-fresh on sign-up / screen info

Artsy/View_Controllers/App_Navigation/ARTopMenuViewController+DeveloperExtras.m
From https://github.com/artsy/eigen/commit/038dca3dd5b29ca1c4483df41625111438a2e937
=> Removes erroneously checked-in extras.

Artsy/View_Controllers/Core/ARHeroUnitViewController.m, CHANGELOG.yml
Added comments to the HeoUnitVC as this is not a common pattern
=> Don't crash on hero units with a '/' url

Artsy.xcodeproj/project.pbxproj, Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, Artsy/View_Controllers/WorksForYou/ARWorksForYouViewController.h, Artsy/View_Controllers/WorksForYou/ARWorksForYouViewController.m, CHANGELOG.yml
The sane version of [this PR](https://github.com/artsy/eigen/pull/1174)
A switch between native and web VC of "works for you"
=> Mc nativeworksforyouvc switch

Dangerfile
Ideally we should see a warning here soon.
=> Make danger look for un-stubbed network requests in the build log #trivial

Gemfile, Gemfile.lock
Moves us to the latest stable version of Danger.
=> Danger -> 0.5.1 #trivial

Makefile
=> Changed upstream => origin in Makefile

Artsy/App/ARAppDelegate+Analytics.m
This was meant to go in the last PR, but it got merged before I was able to push :)
=> [Onboarding] only keep papertrail for trial users.

Artsy/Networking/ARRouter.m, Artsy/Views/Utilities/ARArtworkThumbnailMetadataView.m
I'm making this a tiny PR because the layout stuff is going to take a bit longer.
=> [WorksForYou] Updated ARRouter request to get For Sale works only

Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m, Artsy_Tests/Networking_Tests/Networking_Models/ARArtworkFavoritesNetworkModelTests.m, Artsy_Tests/Networking_Tests/Networking_Models/ARFairFavoritesNetworkModelTests.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m, Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerBuyButtonTests.m, Artsy_Tests/View_Controller_Tests/Embedded/AREmbeddedModelPreviewViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Fair/ARFairViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Gene/ARGeneViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Login_and_Onboarding/ARCreateAccountViewControllerTests.m
We should hear from Danger less now.
=> Remove all the unstubbed networking requests from the test suite

Artsy/App/ARAppDelegate+Analytics.m, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, CHANGELOG.yml
Also makes all tabs have accessibility labels.
=> [Analytics] Include tab labels and rename ‘bell’ to ‘notifications’.

Artsy/Navigation_Transitions/ARViewInRoomTransition.m, Artsy/View_Controllers/Core/ARViewInRoomViewController.m, CHANGELOG.yml
This is someone's favorite feature.
=> Added dude in vertical view, closes #1294.

Artsy/App/ARAnalyticsConstants.h, Artsy/App/ARAnalyticsConstants.m, Artsy/App/ARAppDelegate+Analytics.m, Artsy/Models/API_Models/Live/SaleStatusType.swift, Artsy/Views/Auction/SaleViewModel.swift
=> Analytics for Auctions

Artsy/App/ARSwitchboard+Eigen.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, CHANGELOG.yml
We also support a way to disable, can be removed in future builds.
=> Make the Auctions page native by default

Artsy/App/ARAppDelegate.m, CHANGELOG.yml
Analytics sessions should be closer to as expected
=> [Analytics] Make app backgrounding trigger the end of a session

Artsy/Networking/API_Modules/ArtsyAPI+Sales.m
Wanted to fix [this](https://github.com/artsy/eigen/pull/1283#issuecomment-198152637) before I forgot about it.
=> Cleans up callback invocation

Artsy/View_Controllers/WorksForYou/ARWorksForYouReloadingHostViewController.m, CHANGELOG.yml
=> [WorksForYou] Disable rotation on iPhone.

Artsy/Views/Collection_View_Cells/ARSaleArtworkMasonryCollectionViewCell.m, CHANGELOG.yml
=> Fixes collection view bottom margin issues on lot listings

Artsy/App/ARAnalyticsConstants.h, Artsy/App/ARAnalyticsConstants.m, Artsy/App/ARAppDelegate+Analytics.m, Artsy/Resources/Artsy-Bridging-Header.h, Artsy/View_Controllers/Auction/AuctionInformationViewController.swift, Artsy/View_Controllers/Auction/AuctionRefineViewController+Private.swift, CHANGELOG.yml
=> [Analytics] Auctions fixes

fastlane/metadata/de-DE/description.txt, fastlane/metadata/de-DE/keywords.txt, fastlane/metadata/de-DE/name.txt, fastlane/metadata/en-US/description.txt, fastlane/metadata/en-US/keywords.txt, fastlane/metadata/en-US/name.txt, fastlane/metadata/es-ES/description.txt, fastlane/metadata/es-ES/keywords.txt, fastlane/metadata/es-ES/name.txt, fastlane/metadata/fr-FR/description.txt, fastlane/metadata/fr-FR/keywords.txt, fastlane/metadata/fr-FR/name.txt, fastlane/metadata/it/description.txt, fastlane/metadata/it/keywords.txt, fastlane/metadata/it/name.txt, fastlane/metadata/ja/description.txt, fastlane/metadata/ja/keywords.txt, fastlane/metadata/ja/name.txt, fastlane/metadata/ru/description.txt, fastlane/metadata/ru/keywords.txt, fastlane/metadata/ru/name.txt, fastlane/metadata/zh-Hans/description.txt, fastlane/metadata/zh-Hans/keywords.txt, fastlane/metadata/zh-Hans/name.txt
Updated name, keywords, and description all to be English as defined in #1272.
=> [AppStore Metadata] Update copy

Artsy.xcodeproj/project.pbxproj, Artsy/Constants/ARDefaults.h, Artsy/Constants/ARDefaults.m, Artsy/Networking/API_Modules/ArtsyAPI+Private.h, Artsy/Networking/API_Modules/ArtsyAPI+Sales.h, Artsy/Networking/API_Modules/ArtsyAPI+Sales.m, Artsy/Networking/ARNetworkConstants.h, Artsy/Networking/ARNetworkConstants.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/Networking/ArtsyAPI.m, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Artsy/View_Controllers/Live_Auctions/LiveAuctionSalesPerson.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionStateManager.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionStaticDataFetcher.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift, Artsy_Tests/Networking_Tests/Live_Auctions/LiveAuctionStateFetcherSpec.swift, Artsy_Tests/Networking_Tests/Live_Auctions/LiveAuctionStaticDataFetcherSpec.swift, CHANGELOG.yml
Basic fetching, no parsing yet. Continued from #1391.
=> Metaphysics fetching

Artsy/View_Controllers/App_Navigation/ARTopMenuViewController+SwiftDeveloperExtras.swift
Otherwise you're going to see a random auction every time you start eigen....
=> Remove swiftDeveloperExtras code

Gemfile, Gemfile.lock
Should fix [CI build failures](https://circleci.com/gh/artsy/eigen/2222).
=> Updates to CocoaPods master branch #trivial

.gitignore, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController+SwiftDeveloperExtras.swift, CHANGELOG.yml, Dangerfile
=> Added swiftDeveloperExtras to Dangerfile 

CHANGELOG.yml, Podfile, Podfile.lock
A work-in-progress; we need to switch from `Signal` to `Observable`. Then I need to add unsubscribing where necessary.
=> Updates Interstellar to v2

Podfile
I was 👀  on your Podfile and noticed a typo.
=> Podfile typo

Podfile, Podfile.lock
First time using #trivial, please let me know if I'm doing it right.
=> Updates Quick and Nimble for Swift test suite #trivial

Artsy/Constants/ARDefaults.m, Artsy/Networking/ARNetworkConstants.h, Artsy/Networking/ARNetworkConstants.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/Resources/Artsy-Bridging-Header.h, Artsy/View_Controllers/Live_Auctions/LiveAuctionSalesPerson.swift, CHANGELOG.yml
Should work out-of-the box and @orta and I can customize to point to localhost.
=> Makes sockets depend on staging flag

Artsy/Categories/Apple/Int+Metrification.swift, Artsy/Models/API_Models/Auctions/SaleArtwork.m, Artsy/View_Controllers/Auction/AuctionViewController.swift, Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift, Artsy/View_Controllers/Auction/RefinementOptionsViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionBidButton.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionBidViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift, Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionEventViewModel.swift, Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift, Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionBiddingViewModel.swift, Artsy/Views/Artwork/Auctions/ARArtworkAuctionPriceView.m, Artsy/Views/Artwork/Auctions/ARAuctionBidderStateLabel.m, Artsy/Views/Auction/SaleViewModel.swift, Artsy_Tests/Stubs/SaleArtwork+Extensions.m, Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift, Artsy_Tests/View_Controller_Tests/Auction/RefinementOptionsViewControllerTests.swift, Artsy_Tests/View_Controller_Tests/Auction/SaleArtworkViewModelTests.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionBidButtonTests.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionBidHistoryViewControllerTests.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionBidViewControllerTests.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionBiddingViewModelTests.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift, Artsy_Tests/View_Tests/ARArtworkActionsViewTests.m, CHANGELOG.yml
=> Uses server-defined currency string throughout app.

Artsy/App/ARHockeyFeedbackDelegate.swift, docs/using_the_beta.md, docs/welcome_to_eigen_beta.md
Adds a doc page specifically around using the beta
=> [Beta] Improve docs around the beta

Artsy/View_Controllers/App_Navigation/ARAppSearchViewController.m
Fix #1541 (and [this issue](https://github.com/artsy/emission/issues/91) on Emission).
=> [ArtistView] Add routing to Emission's Artist VC from search

Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift, CHANGELOG.yml
=> [Live] Move the idle timer to the liveauctionVC instead of on a lot

CHANGELOG.yml, Podfile, Podfile.lock
As described on the tin.
This branch has been sent off for a beta.
=> [Pods] Update Emission and React Native.

Gemfile, Gemfile.lock
This PR has lots of possible places for breakage, best to test on a real project too. https://github.com/danger/danger/pull/218
=> Update Danger to latest build #trivial

Artsy/Networking/Live_Auctions/LiveAuctionSocketCommunicator.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionStateManager.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionStateManagerSpec.swift, CHANGELOG.yml
Provides functionality for #1102.
=> Allows user to set max bid

Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift, CHANGELOG.yml
=> Hides CTA when appropriate.

Artsy/View_Controllers/Live_Auctions/LiveAuctionStaticDataFetcher.swift
The iOS version of https://github.com/artsy/metaphysics/pull/297 #trivial
=> [Live] Convert logged in users to be participants instead of bidders

Artsy/View_Controllers/Auction/AuctionInformationViewController.swift
=> [Auctions] Add an alert when a user doesn't have an email set up 

Artsy/App/ARAppDelegate+Emission.m, Artsy/View_Controllers/Util/ARMenuAwareViewController.h, Artsy/View_Controllers/Util/ARNavigationController.m, Artsy/View_Controllers/Util/ARScrollNavigationChief.m, CHANGELOG.yml
Fixes https://github.com/artsy/emission/issues/132
=> [ARMenuAwareViewController] Indicate what scrollview should report to the chief.

Artsy/App/ARAppDelegate+Analytics.m, Artsy/App/ARAppDelegate+Emission.m, CHANGELOG.yml, Podfile.lock, circle.yml
Fixes #1469 
This first needs Emission to be updated, which I’m doing once https://github.com/artsy/emission/issues/148 is in.
=> [Emission] Add artist analytics integration.

Artsy/View_Controllers/Live_Auctions/LiveAuctionBidButton.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionBidButtonTests.swift, CHANGELOG.yml, Dangerfile, Gemfile.lock
Continued from https://github.com/artsy/eigen/pull/1609
=> Removes delay from test

Artsy.xcodeproj/project.pbxproj, Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift
Converts the view that was being done manually into something that can be used in many places if needed. Already covered by tests in LiveAuctionVCTests - so no changes means everything is OK.
=> [Infra] Refactor the blurred overlay view #trivial 

Artsy/View_Controllers/Live_Auctions/LiveAuctionBidButton.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift
=> Changes copy on bid button while bidding is underway

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARSwitchBoard.m, Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift, Artsy/View_Controllers/SerifModalWebNavigationController.swift, Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.h, Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, CHANGELOG.yml
=> User can cancel registration

Artsy/Networking/ARNetworkConstants.h, Artsy/Networking/ARNetworkConstants.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Live_Auctions/LiveAuctionSalesPerson.swift
This keeps one staging socket, this makes it possible to change your socket for devs.
=> [Live] Support two production sockets

Artsy/Networking/ARRouter.m
=> [Live] Ensure that we grab all sale artworks instead of capping at 25

Gemfile.lock
https://github.com/danger/danger/pull/268 introduces changes to Danger that I want to be certain of in a production environment. So we're going to be that. 👍
=> [Danger] Update Danger to master

Artsy/Models/API_Models/Live/LiveSale.m, Artsy/Networking/Live_Auctions/LiveAuctionSocketCommunicator.swift, Artsy/View_Controllers/Live_Auctions/LiveActionStateReconciler.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionLotSetViewController.swift, Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift, Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionBiddingViewModel.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
iPad horizontal scrolling & bid button state.
=> Some fixes

Makefile
=> [Infra] Make our build number x.y.z.ø instead of x.y.z using hours

Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/App/ARSwitchBoard.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, CHANGELOG.yml
Switches our lab setting to disable, this could be valuable for web developers to test on eigen if they need it, will probably be removed a few versions down the line.
=> [Infra/Live] Convert Live Auctions to be native by default

Artsy/App/ARSwitchBoard.m, CHANGELOG.yml
Previous beta deploy failed because of things I forgot to change, fixed now.
=> Updates for 2.6.1.

CHANGELOG.yml
=> Fixes Changelog typo #trivial

Podfile.lock
https://github.com/artsy/eigen-artefacts/commit/3298304f90f1fe76f80a158e1b490131ad4b92f7
Need to get Danger to include a link for this
=> [Pods] Update emission

Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift, CHANGELOG.yml
Only remove the observer for the disconnect overlay when we're… removing the live view controller
=> [Live] Improve disconnect overlay reliability

Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
With this + the vanity PR, should be good to go.
=> Version Bump to 2.6.2

Artsy/App/ARSwitchBoard.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m
Reverts #1748, since #1750 fixes the problem properly.
=> Revert stop-gap fix

Artsy/Models/API_Models/Artwork_Metadata/Image.h, Artsy/Models/API_Models/Artwork_Metadata/Image.m, Artsy_Tests/Model_Tests/ARImageTests.m, CHANGELOG.yml
=> [Image] Fallback to higher, or lower, available image version.

Artsy/View_Controllers/Live_Auctions/LiveAuctionLotListViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionLotSetViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionPlaceMaxBidViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionSalesPerson.swift, Artsy/View_Controllers/Live_Auctions/LotListCollectionViewCell.swift, Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift, Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionToolbarView.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift, CHANGELOG.yml
=> Fixes for deleted lots and ordering

Makefile
should be less confusing for new to CP readers re: #1809 
#trivial
=> Make 'make oss' update the cocoapods repos,

README.md
Replacing https://github.com/artsy/mobile/blob/master/what_is_artsy.md.
=> @orta => Update what is artsy link to the meta repo.

fastlane/Fastfile
=> Fix fastlane spelling

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m
=> [Onboarding] No results view

Artsy/Models/API_Models/Artwork_Metadata/Gene.h, Artsy/Models/API_Models/Artwork_Metadata/Gene.m, Artsy/Models/API_Models/Partner_Metadata/Artist.h, Artsy/Models/API_Models/Partner_Metadata/Artist.m, Artsy/Networking/API_Modules/ArtsyAPI+RelatedModels.h, Artsy/Networking/API_Modules/ArtsyAPI+RelatedModels.m, Artsy/Networking/ARNetworkConstants.h, Artsy/Networking/ARNetworkConstants.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingFollowableTableViewCell.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.h, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m, CHANGELOG.yml
Completes 4/4 of #1454 
Migrated to use of `/me/suggested/artists` as per #1449
Need to add the high level genes to the S3 file, but will do that separately.
This is probably best tried out locally. I can add a gif shortly.
=> [Onboarding] API Updates

Artsy/App/ARUserActivity.m, Artsy/Models/API_Models/Partner_Metadata/Location.h
Going to try and get this working on Xcode 8, wanted it up for early review.
=> [Maps] support for putting shows on the map in iOS 10

.gitignore, Artsy/App_Resources/Artsy-Info.plist, Dangerfile, Makefile, README.md, fastlane/Fastfile, fastlane/Gemfile
* Fastlane - bail early so we know to make a version on iTunes
* Danger - fail if you've bumped the CHANGELOG version but not the app version
* Deployment - Use bundler to ensure that our environment is set up as we want
=> Danger/Fastlane/Deploy Improvements to deployment

Artsy/Networking/API_Modules/ArtsyAPI+Search.h, Artsy/Networking/API_Modules/ArtsyAPI+Search.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
...When you've already followed them.
Unfortunately Gravity hasn't added it for genes yet, so I'll see if I can do that later on, but eigen's code is already prepped for it!
=> [Onboarding] Exclude certain artists and genes from search

Artsy/Models/API_Models/Artwork_Metadata/Gene.m
Fix #1839 and addresses the actual comment Eloy made earlier about using appropriate size and scale for the thumbnails.
=> [Onboarding] Propery category images loaded 

Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m, Artsy_Tests/View_Controller_Tests/Contact/ARInquireForArtworkViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Fair/ARFairGuideContainerViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Fair/ARShowViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Web_Browsing/ARAuctionWebViewControllerTests.m
- disabled tests around 'logged out state' since we don't do that anymore
- there are some failing tests that weren't easy to figure out why (lots of ones that seemed unstubbed?) -> commented those out for now.
=> [Onboarding] Tests etc

Artsy/App/ARAppDelegate+Emission.m, Artsy/App/ARAppDelegate.h, Artsy/App/ARAppDelegate.m, Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.h, Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/2_-_Calls_to_Action/ARSignUpSplashViewController.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuNavigationDataSourceSpec.m
Not comprehensive, but covers all our cases that I can think of, running out of time. Will comment inline
=> [Home v3] Covnert to use the emission homeVC

Artsy/App/ARHockeyFeedbackDelegate.swift
=> [Hockey] Fallback if there’s no current user yet. #trivial

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
=> [Onoarding] Add inline suggestions/replacements for popular artists and categories

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingFollowableTableViewCell.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingHeaderView.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingSearchField.m
Fix #1865 and #1880 and #1864 
So I actually don't know why the icon isn't showing up on device - it does in the simulator (as can be seen below) and is persisted through the search. 
I'll dig into that further, but for now, here's:
cc @katarinabatina 
Also polished up all the margins seeing as I was on a screenhero with Katarina:
😍
=> [Onboarding] Search behaviour improvements

Artsy/App/ARAppDelegate+Emission.m, Artsy/App/ARAppNotificationsDelegate.m, Artsy/Constants/ARDefaults.h, Artsy/Constants/ARDefaults.m
=> [Push Notifications] Weekly limit and only on artist pages

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginViewController.m
=> [Onboarding] Fix keyboard convering signup fields in iPad landscape

Artsy_Tests/View_Controller_Tests/Login_and_Onboarding/ARCreateAccountViewControllerTests.m
Noted in #1902, will dive deeper after deadline.
=> [Tests] Disable Create Account test

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingSearchField.m
Not sure why this would work on simulator but not device. Think this fixes #1860.
=> [Onboarding] Fix capitalisation on search button asset

Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Artsy/View_Controllers/Artwork/ARZoomArtworkImageViewController.m, Artsy/View_Controllers/Core/ARViewInRoomViewController.m, Artsy/View_Controllers/Feed_VCs/ARSimpleShowFeedViewController.m, Artsy/View_Controllers/Util/ARMenuAwareViewController.h, Artsy/View_Controllers/Util/ARNavigationController.h, Artsy/View_Controllers/Util/ARNavigationController.m
Fixes #1885 
There may be some snapshot test failures for the badge color and those should be addressed when v3 is merged.
=> Removed search button from ARNavigationController and fixed color of notifications badge #tiny

Artsy/App/ARAppDelegate+Emission.m, Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
works with https://github.com/artsy/emission/pull/338
=> [Admin] Support running Emission from a local packager

Artsy/View_Controllers/Debug/Quicksilver/ARQuicksilverViewController.m
You can throw a URL in Quicksilver and it will go there and add it into history.
=> [Quicksilver] Fixes adding a URL to the history #trivial

Artsy/Tooling/ARWebViewCacheHost.m, CHANGELOG.yml
As [discussed in Slack](https://artsy.slack.com/archives/help/p1476275183000667).
=> [WebView] Fixes video embedded in articles not playing inline on iOS 10.

Artsy/App/ARAppDelegate+Emission.m
This relies on [this pr](https://github.com/artsy/emission/pull/343) and ensuring eigen points to the correct version of the Emission pod.
=> [WIP 🚨] Support for new search bar

Artsy/App/ARAppDelegate+Emission.m
=> [Emission] Hook-up gene status API module.

Artsy.xcodeproj/project.pbxproj, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizationGeneImageStateReconciler.h, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizationGeneImageStateReconciler.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m, Artsy_Tests/View_Controller_Tests/Login_and_Onboarding/AROnboardingPersonalizationGeneImageStateReconcilerTests.m, CHANGELOG.yml
=> Fixes blank gene images

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m, CHANGELOG.yml
=> "No Results" flashing

Artsy/App/ARAppDelegate.m
=> [Loading] Do not show the rate Artsy popover if you do not have an account

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
=> [Onboarding] Add default placeholders for when no search results 

Artsy/App/ARAppDelegate.m, Artsy/App/ARSwitchBoard.m
For https://github.com/artsy/eigen/issues/1468 and https://github.com/artsy/emission/pull/367
=> Artist Auction  Results

Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/App/ARSwitchBoard.m, Artsy/App/ARSwitchboard+Eigen.h, Artsy/App/ARSwitchboard+Eigen.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, CHANGELOG.yml
This switches the default to on, and uses echo to support turning it off.
=> [blocked] Update Gene to use the new ARGeneComponentVC

Podfile, Podfile.lock
https://github.com/facebook/react-native/issues/8607#issuecomment-249530803
Fixes #1961
=> [React] Apply blank scroll view fix to 0.34.1

Artsy/App_Resources/Artsy-Info.plist
Currently doing a deploy of this version. Will merge into master if we go through with replacing the release by this.
=> Bump bundle version.

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m
My first merge into master in _months_!!
Fix #1971  #1968
=> [Fix] Onboarding crashes

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m
=> [Fix] for nil crash in Gene Image State Reconciler

Artsy/App_Resources/Artsy-Info.plist, Artsy/View_Controllers/App_Navigation/ARAppSearchViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m, CHANGELOG.yml
=> Fix for onboarding tableview crasher

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARSwitchBoard.h, Artsy/App/ARSwitchBoard.m, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Artsy/View_Controllers/Admin/AREchoContentsViewController.h, Artsy/View_Controllers/Admin/AREchoContentsViewController.m, CHANGELOG.yml
Looks like this:
Related to https://github.com/artsy/auctions/issues/262.
=> Adds admin ability to view echo configuration.

Artsy.xcodeproj/project.pbxproj, Artsy/App_Resources/Artsy-Info.plist, Artsy/App_Resources/Artsy.Store.entitlements, Artsy/App_Resources/Artsy.entitlements
Tried to be as vague as possible without being meaningless.
=> Adds APNS entitlements and privacy Info.plist specifiers

Artsy/Views/Artwork/ARArtworkActionsView.m, CHANGELOG.yml
Fixes #2115. /cc @sweir27 
Problem caused as a result of an oversight when initially implementing this logic. The file to manage all this is quite large, I think a factoring the logic to decide which button(s) to show into its own class might be a good idea the next time any substantial work needs to be done here. Happy to take that on.
=> Fixes live auction / contact buttons problem.

Artsy/App/ARAppDelegate.m, CHANGELOG.yml, Podfile.lock
=> [Adjust] Report user’s anonymous ID as a callback parameter.

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, Artsy/View_Controllers/Auction/AuctionInformationViewController.swift, CHANGELOG.yml
As reported in Slack last night: https://artsy.slack.com/archives/auctions-dev/p1485298570003846
=> Fixes auction contact email address

Artsy/Models/API_Models/Application/SearchResult.h, Artsy/Models/API_Models/Application/SearchResult.m, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Search/ARSearchResultsDataSource.m, Artsy_Tests/Stubs/OHHTTPStubs+Artsy.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARAppSearchViewControllerSpec.m, CHANGELOG.yml
Fix for [CE/131](https://github.com/artsy/collector-experience/issues/131).
=> [Fairs] Add parsing so fairs can be displayed as search results

LICENSE, README.md
I noticed that our copyright line was inconsistent across projects and
often still listed 2016. So, I worked with Yayoi to figure out what the
right language was and am now copy/pasting to achieve consistency.
=> Update License section

Artsy/Models/API_Models/Partner_Metadata/Partner.h, Artsy/Models/API_Models/Partner_Metadata/Partner.m, Artsy/View_Controllers/Fair/ARShowViewController.m, Artsy_Tests/View_Controller_Tests/Fair/ARShowViewControllerTests.m, CHANGELOG.yml
=> @alloy => [Show] changes follow button text

Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, CHANGELOG.yml, Podfile.lock
After merging this we can rebase and merge #1960.
=> Update to emission 1.2.1

Podfile.lock
Apples this PR: https://github.com/artsy/Aerodramus/pull/5
=> Updates Aerodramus to 0.3.0

Artsy/Networking/ARRouter.m, Artsy_Tests/Networking_Tests/ARRouterTests.m, CHANGELOG.yml
I've tested it on staging and production and it appears to work. Would like input from @alloy and @orta, if there's no rush.
Fixes https://github.com/artsy/eigen/issues/2213
=> Changes metaphysics call to use POST instead of GET

Artsy/Views/Auction/LotStandingsLotView.swift, CHANGELOG.yml
Fixes https://github.com/artsy/eigen/issues/2230
=> Fixes my-bids view with long artist/artwork names

Artsy/View_Controllers/App_Navigation/ARAppSearchViewController.m
=> [Search] Open fair VC.

Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionToolbarView.swift
Small improvement, I'll see if others come to mind.
=> Switched from strings to enums

Podfile.lock
3.1.1 just is a fix for this - https://github.com/artsy/Artsy-OSSUIFonts/issues/11
=> [Pods] Update fonts again for OSS consumers #trivial

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m, CHANGELOG.yml
=> [Onboarding] Fix issue when searching for artists to scroll to top

Podfile.lock
A hopeful fix for https://github.com/artsy/auctions/issues/410
=> Updated Starscream.

Artsy/Networking/ARRouter.m
Necessary in live since https://github.com/artsy/eigen/pull/2275 was merged.
=> Adds qualified_for_bidding to GraphQL query #trivial

Artsy/App/ARAppDelegate+Emission.m, Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.h, Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m, CHANGELOG.yml, Podfile, Podfile.lock
=> [WFU] Supports new RN WFU container

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARAppDelegate.m, Artsy/App/ARSpotlight.m, Artsy/App/ARSwitchBoard.h, Artsy/App/ARSwitchBoard.m, Artsy/App_Resources/Artsy.entitlements, Artsy/Constants/ARDefaults.h, Artsy/Constants/ARDefaults.m, Artsy/Networking/ARNetworkConstants.h, Artsy/Networking/ARNetworkConstants.m, Artsy/Networking/ARRouter+Private.h, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Artsy/View_Controllers/Core/ARFeedLinkUnitViewController.m, Artsy/View_Controllers/Fair/ARFairSearchViewController.m, Artsy/View_Controllers/Util/Sharing/ARURLItemProvider.m, Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, Artsy_Tests/Networking_Tests/API_Modules/ARUserManagerTests.m, Artsy_Tests/Networking_Tests/ARRouterTests.m, Artsy_Tests/Util_Tests/Sharing_Tests/ARURLItemProviderTests.m, Artsy_Tests/View_Controller_Tests/Fair/ARFairSearchViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Web_Browsing/ARInternalMobileWebViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Web_Browsing/ARInternalShareValidatorTests.m, CHANGELOG.yml
=> Remove references to martsy

Artsy/App/ARAnalyticsConstants.h, Artsy/App/ARAnalyticsConstants.m, Artsy/App/ARAppDelegate+Analytics.m
Analytics for new deeplink url
=> [Analytics] Added event for deeplinks #trivial

Artsy/View_Controllers/Live_Auctions/LiveAuctionBidViewModel.swift, CHANGELOG.yml
/cc @devangt 
See https://github.com/artsy/auctions/issues/453
=> Allows users to place higher bids in advance in LAI

Artsy/App/ARAppDelegate+Analytics.m, Artsy/View_Controllers/Gene/GeneRefineSettings.swift
Seems like this commit never got pushed last night >_< sorry!
=> [Analytics] Add placement for refine page view and tag incomplete analytics

CHANGELOG.yml, Podfile.lock
- Fixes loading state UI for artwork rail - luc
=> [Emission] Update to 1.3.4

Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
=> [WFU] Fixes selected artist not showing when view is already presented

Artsy/Models/API_Models/Auctions/Sale.h, Artsy/Models/API_Models/Auctions/Sale.m, Artsy/View_Controllers/Artwork/ARArtworkViewController.m, Artsy_Tests/Model_Tests/SaleTests.m, Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m, CHANGELOG.yml
This adds a timer to the artwork view controller that refreshes the UI when the live sale opens. This is a work in progress because there's still required:
=> Timer update for artwork page 📱

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> Updates changelog after 3.2.1 release

Artsy/View_Controllers/Auction/AuctionInformationViewController.swift
Pointed out on Twitter: https://twitter.com/r0unak/status/867478836342018048
=> Fixes value of pi #trivial

Artsy/App/SwiftExtensions.swift, Artsy/Networking/Live_Auctions/LiveAuctionSocketCommunicator.swift, Artsy/Views/Auction/LotStandingsLotView.swift, Podfile, Podfile.lock
Changes are backwards-compable with Xcode 8.
=> Adds Xcode 9 Compatibility

CHANGELOG.yml, Podfile.lock
To 1.3.9. See PR here: https://github.com/artsy/emission/pull/612
=> Updates Emission #trivial

Artsy/View_Controllers/Auction/AuctionSaleArtworksNetworkModel.swift, Artsy_Tests/View_Controller_Tests/Auction/AuctionSaleArtworksNetworkModelTests.swift, CHANGELOG.yml
Fix for https://github.com/artsy/auctions/issues/497
=> Filters out lots with unpublished artworks

Artsy/View_Controllers/ARSerifNavigationViewController.m, CHANGELOG.yml
Still not sure why this is necessary, going to look into it more. In the mean time, this works.
=> Fixes an issue with the status bar appearence returning from LAI modals.

Artsy/App_Resources/Artsy-Info.plist, Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m
This can't be merged yet ofc, because it relies on an Emission update, but when that's good to go so should this be! :)
=> [MSG] Use new RN inquiry modal from artwork VC

CHANGELOG.yml
Just a changelog update really.
=> Merge 3.2.3 into master.

circle.yml
As requested here: https://twitter.com/dantoml/status/885562493816516611
=> Copies logs to circle artefacts directory

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
=> [Onboarding] Change password restriction to 6 chars

Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/Resources/Artsy-Bridging-Header.h, Artsy/View_Controllers/Live_Auctions/LiveAuctionBidHistoryViewController.swift, Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionEventViewModel.swift, CHANGELOG.yml
This will only work on iPhone 7s, and it is behind and admin flag.
Our tests only run on an iOS 9 device, so I can't do a 'does this call happen' kind of test, but even then I can't verify it's called without something like OCMock. So, no tests.
=> [Auctions] Adds haptic feedback for any live auctions

Artsy/App/ARSwitchBoard.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, CHANGELOG.yml
My first pass at Eigen.  Closes https://github.com/artsy/eigen/issues/2113
=> Fea dont intercept tel urls

Artsy/Networking/ARNetworkConstants.h, Artsy/Networking/ARNetworkConstants.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Live_Auctions/LiveAuctionSalesPerson.swift, CHANGELOG.yml
No longer needed, as causality doesn't distinguish the two anymore.
=> Removes bifurcation of bidders/observers for causality websocket connections

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARSwitchBoard.m, Artsy/Constants/ARAppConstants.h, Artsy/Constants/ARAppConstants.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Web_Browsing/ARPaymentRequestViewController.h, Artsy/View_Controllers/Web_Browsing/ARPaymentRequestWebViewController.h, Artsy/View_Controllers/Web_Browsing/ARPaymentRequestWebViewController.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, Artsy_Tests/Networking_Tests/ARRouterTests.m, Artsy_Tests/View_Controller_Tests/Web_Browsing/ARPaymentRequestWebViewControllerTests.m, CHANGELOG.yml
~~This is awaiting the final version of https://github.com/artsy/lewitt-web-public/pull/69 before it can be completed/merged.~~
This works!
=> [Payment Request] Adds dedicated webview VC that detects payments.

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
This updates the changelog and bundle version numbers for a forthcoming 3.2.6 release.
=> Updates based on 3.2.5 release.

Artsy/App/ARSwitchBoard.m
Eigen’s side of https://github.com/artsy/emission/pull/790
=> Properly present modal emission views #trivial

README.md
This is an outcome of the meeting we had earlier today. Open to feedback.
Relates to https://github.com/artsy/eigen/issues/2444
=> Adds notes about branching

Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m, Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
Aaaand we're back in business!
Fix [#CE695](https://github.com/artsy/collector-experience/issues/695)
=> [Onboarding] Fix bug where next button was stuck behind keyboard

Artsy/App/ARSwitchBoard.m, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Artsy/View_Controllers/App_Navigation/ARContentViewControllers.h, Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Artsy/View_Controllers/Util/ARNavigationController.h, Artsy/View_Controllers/Util/ARNavigationController.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuNavigationDataSourceSpec.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m, CHANGELOG.yml, Podfile.lock
Adds the ability to have routes to some of our new Emission  VCs.
=> Update Emission and include routing

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, CHANGELOG.yml
Currently you need to be showing red dots for martsy views in order to turn off analytics popovers 😄
=> [Dev] Fix small bug where you can't turn off analytics popovers

Artsy/Models/API_Models/LiveAuctionLot.h, Artsy/View_Controllers/Live_Auctions/LiveAuctionPlaceMaxBidViewController.swift, Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift, Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionLotCollectionViewDataSource.swift, Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionLotCollectionViewLayoutType.swift, Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift, CHANGELOG.yml
Almost entirely type changes, didn't feel the need to test. Let me know what you think. 
Addresses https://github.com/artsy/auctions/issues/699 .
=> Modifies types to handle missing image URLs.

Artsy/App/ARAppDelegate+Analytics.m, Artsy/App/ARAppDelegate+Emission.m, Artsy/App/ARAppStatus.h, Artsy/App/ARAppStatus.m, CHANGELOG.yml
Forgot to push this work earlier! 🙈
=> Dont enable sentry in dev mode

Artsy/App_Resources/Launch Screen.xib, CHANGELOG.yml
=> [Polish] Fix for launch screen being truncated

Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift, Artsy/View_Controllers/Live_Auctions/Views/SaleOnHoldOverlayView.swift
Tracked in artsy/auctions#700
Paired with @ashfurrow on this
This 🚧PR improves support for custom sale on hold messages.
=> WIP update sale old hold banner

CHANGELOG.yml
=> [Dev] Update the CHANGELOG

Artsy/App/ARAppDelegate+Emission.m, Artsy/App/ARSwitchBoard+Eigen.h, Artsy/App/ARSwitchboard+Eigen.m, Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, Podfile.lock
=> Updates Emission

Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/View_Controllers/Live_Auctions/LiveAuctionBidHistoryViewController.swift, CHANGELOG.yml
=> [Auctions] Make haptic feedback for lot events the default in live auctions

Artsy/View_Controllers/Util/ARNavigationController.m
Pairs with https://github.com/artsy/emission/pull/892
=> Allow Emission components to declare whether they want black/white status bars - #trivial

Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, CHANGELOG.yml, Podfile, Podfile.lock
If a new user signs up for Artsy, they will be directed to the For You of tab instead of Artists. All other users will land on Artists.
=> [home] Onboarding users land on For You tab of Home

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARAppNotificationsDelegate.m, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Artsy/View_Controllers/Search/ARSearchViewController.m, Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m, CHANGELOG.yml, Podfile, Podfile.lock
Updates the design as per https://github.com/artsy/collector-experience/issues/661, but doesn’t yet implement the granularity of the notification count.
=> Updates tab bar notifications badge

Artsy/App/ARSpotlight.m, Artsy_Tests/App_Tests/ARUserActivityAndSpotlightTests.m, CHANGELOG.yml
See https://github.com/artsy/collector-experience/issues/810
Closes https://github.com/artsy/collector-experience/issues/879
=> [Spotlight] Disable for now.

Artsy/App/ARAnalyticsConstants.h, Artsy/App/ARAnalyticsConstants.m, Artsy/App/ARAppDelegate+Analytics.m, CHANGELOG.yml
Fixes https://github.com/artsy/eigen/issues/2450
Fixes https://github.com/artsy/collector-experience/issues/826
@anipetrov I left the auction and onboarding events as were for now. Maybe we can see how we want to do those to match the new schema after 4.0 :).
=> [Analytics] Cleanup

Podfile.lock
=> Update Emission to 1.4 beta 13

Artsy/Networking/artworks_in_sale.graphql, CHANGELOG.yml
Fixes the currency symbol issue described in https://github.com/artsy/eigen/issues/2514 .
=> Fixes display issue for currency in related artworks view.

Artsy/App/ARSpotlight.m, Artsy/Models/API_Models/Auctions/SaleArtwork.m, Artsy_Tests/App_Tests/ARUserActivityAndSpotlightTests.m, CHANGELOG.yml, Podfile.lock
This fixes the decimal part of https://github.com/artsy/collector-experience/issues/786. It’s a crude fix, but figuring out this iOS bug is proving more than 5 minutes work.
=> Remove unneeded decimals from prices

Artsy/App/ARAppDelegate.m, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Fixes https://github.com/artsy/collector-experience/issues/906
Going to self-merge so I can start cutting a build.
=> [Launch] Lock to portrait mode on iPhone.

Artsy/Tooling/ARWebViewCacheHost.m
Adds ability to use safari dev tools. Paired with @orta! Thanks.
=> Adds ability to use safari dev tools #trivial

Podfile, Podfile.lock
=> [Pods] Update Emission to 1.4.0

Artsy/View_Controllers/ARVIR/ARAugmentedVIRViewController.m
Makes the spinners hide after finishing, instead of just stopping.
=> [ARVIR] Remove the spinners instead of making them stop

Podfile.lock
Adds some changes [related to iOS 11](https://github.com/adjust/ios_sdk/blob/master/CHANGELOG.md#version-4115-21st-september-2017)
=> Updates adjust for iOS11 #trivial

Artsy/View_Controllers/Core/ARViewInRoomViewController.m, CHANGELOG.yml
=> Fix the old VIR animations, and remove the status bar

CHANGELOG.yml, Podfile.lock
=> Version bump for Emission

Artsy Stickers/Info.plist, Artsy/App/ARAppDelegate+Emission.m, Artsy/App_Resources/Artsy-Info.plist, Artsy_Tests/Supporting_Files/ARTestHelper.m, CHANGELOG.yml, Podfile, Podfile.lock
=> Release 4.0.2

docs/push_notifications.md
=> [docs] Update link to APNS cert

Artsy/App/SwiftExtensions.swift, Artsy/Networking/Live_Auctions/LiveAuctionSocketCommunicator.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionLotSetViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionStateManager.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift, Artsy/Views/Auction/AuctionBannerView.swift, CHANGELOG.yml, Podfile.lock
While I'm clever enough to write these functions, I am not clever enough to debug them. Especially as Swift changes under our feet. So I "fixed the glitch" and just did things manually.
=> Removes apply functions

Artsy/App/SwiftExtensions.swift, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController+SwiftDeveloperExtras.swift, Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift, Artsy/Views/Auction/AuctionTitleView.swift
Got this to compile on Xcode 9.2:
Continued from #2567.
=> Adds support for Xcode 9 < 9.2

Artsy/Models/API_Models/Partner_Metadata/Artwork+AttributionClassStrings.m, CHANGELOG.yml
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=SELL&modal=detail&selectedIssue=SELL-240&sprint=49
=> minor change to display string on AttributionClassification

Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRViewController.m, Artsy_Tests/View_Controller_Tests/Auction/RefinementOptionsViewControllerTests.swift
Fixes https://artsyproduct.atlassian.net/browse/EV-53
=> Always show the opening message in ARVIR

Artsy/App/ARAppDelegate+Analytics.m
Makes the actions camelCase in line with the rest.
#trivial
=> Update event IDs for Analytics

Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRViewController.m, CHANGELOG.yml
Fixes https://artsyproduct.atlassian.net/browse/EV-56
=> EV-56 - Ensure we have a black BG for the ARVIR

Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRSetupViewController.m, CHANGELOG.yml
Also includes #2581 
Looks like we were showing a status bar, and aligning to a non-existent margin on the bottom.
#trivial
=> non-iPhone X ARVIR bug fixes

Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRViewController.m, CHANGELOG.yml
- [EV-59](https://artsyproduct.atlassian.net/browse/EV-59) [EV-60](https://artsyproduct.atlassian.net/browse/EV-60), and [EV-58](https://artsyproduct.atlassian.net/browse/EV-58)
Updates to the in-app copy from https://www.notion.so/artsy/AR-View-in-Room-Updates-ce5de35851b84f67a9e8376b0eabd9c3
#trivial
=> Update the copy for ARVIR

Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRViewController.m
Fixes - https://artsyproduct.atlassian.net/browse/EV-52
=> EV-52 - Add shadows to the action buttons on ARVIR

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, Makefile
=> Preparing for the next release, version 4.1.1

fastlane/Fastfile
=> [Fastlane] Remove slack message for now as it fails

Artsy/View_Controllers/ARVIR/AR/ARAugmentedVIRInteractionController.m, Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRViewController.m, Artsy/View_Controllers/ARVIR/Views/ARAugmentedVIRModalView.m
Handles:
* https://artsyproduct.atlassian.net/browse/EV-88
* https://artsyproduct.atlassian.net/browse/EV-89
* https://artsyproduct.atlassian.net/browse/EV-87
* https://artsyproduct.atlassian.net/browse/EV-90
=> ARVIR bug fixes

CHANGELOG.yml, Podfile.lock
I’ve verified that this actually pulls in the Emission code. A beta is being built at this moment.
=> Update emission to v1.4.8

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
The release just contains #2607 
Deploy: https://circleci.com/gh/artsy/eigen/5205
=> [Beta] Prepare for 4.1.2

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> Deploys merge commits for 4.1.2

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, CHANGELOG.yml
Let's you re-trigger the request to get notifications on an app at any point. So you can log into staging and re-trigger.
=> Adds an admin button that lets you request notifications

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Also includes the CHANGELOG entry for #2621
=> Updates the CHANGELOG for the next version

CHANGELOG.yml, Podfile.lock
Blocked on this Metaphysics PR: https://github.com/artsy/metaphysics/pull/1070
=> Updates Emission to 1.5.3.

Artsy/App/ARAppDelegate+Analytics.m, Artsy/App/ARAppDelegate+Emission.m, Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/App/ARSwitchBoard+Eigen.h, Artsy/App/ARSwitchBoard.m, Artsy/App/ARSwitchboard+Eigen.m, Artsy/Models/API_Models/Auctions/SaleArtwork.m, Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m, Artsy/Views/Artwork/ARArtworkActionsView.h, Artsy/Views/Artwork/ARArtworkActionsView.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, Artsy_Tests/View_Tests/ARArtworkActionsViewTests.m, CHANGELOG.yml
This fell through the cracks when updating to Emission 1.5, oops! So #2609 never made it into master.
=> Merge from emission-1.5 develop branch.

docs/deploy_to_app_store.md
Fixed two typos and adds a link to a Jira ticket around something that's not working.
=> Fixes some typos, adds Jira ticket to docs

Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
Brings it in line with how having it work on a push instead of the current design for modals
#trivial
=> Switches the back and beta positions on the floor based ARVIR

Artsy/View_Controllers/ARVIR/AR/ARVIRHorizontalPlaneInteractionController.m, Artsy/View_Controllers/ARVIR/Nodes/ARSCNWallNode.m
=> ARVIR - Animates the line into position

Artsy/View_Controllers/ARVIR/AR/ARVIRHorizontalPlaneInteractionController.m, Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m, Artsy/View_Controllers/ARVIR/Views/ARInformationView.h, Artsy/View_Controllers/ARVIR/Views/ARInformationView.m, CHANGELOG.yml
Closes https://artsyproduct.atlassian.net/browse/EV-148
This should thus far have the design up to spec.
=> [ARVIR2] Reset AR world 📱

Artsy/View_Controllers/ARVIR/AR/ARVIRHorizontalPlaneInteractionController.m, Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
This makes it be in line with the user interface changes, so that they don't all happen at once.
#trivial
=> [ARVIR] Delays the transition from showing feature points to the line

Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
=> [ARVIR] Updates the wording on the view in room final message

Dangerfile
Peril handles this now as of https://github.com/artsy/peril-settings/issues/16
=> Remove the changelog check in danger

Artsy/App/ARSwitchBoard+Eigen.h, Artsy/App/ARSwitchboard+Eigen.m, Artsy/Resources/Artsy-Bridging-Header.h, Artsy/View_Controllers/Auction/AuctionViewController.swift, Podfile.lock
#trivial
✅ Needs https://github.com/artsy/eigen/pull/2645 to be merged first. This updates Eigen to use the new registration flow from emission if selected in the debug menu.
=> PURHASE-198 new registration flow

Podfile.lock
=> Update emission to 1.5.6

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, Artsy/Networking/API_Modules/ARUserManager.m, CHANGELOG.yml
Otherwise you’re left with data from previous session, which is confusing.
=> [UserManager] Clear Relay response cache when clearing user data.

Podfile.lock
#trivial
@orta - Would you be able to help me drop a new beta release for this?
=> Update emission to 1.5.7

Podfile.lock
This updates Emission to 1.5.8.
=> update Emission pod

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m, CHANGELOG.yml, Podfile.lock
Emission release 1.5.9 ft. new registration results for new bid flow
=> Emission release 1.5.9

CHANGELOG.yml, Podfile.lock
This PR updates to the latest Emission release in anticipation of a beta deploy.
=> update emission to 1.5.10 #trivial

Artsy/App/ARAppNotificationsDelegate.m, Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m
in https://github.com/artsy/pulse/pull/215
#trivial
=> Updates the check in supressing notification views to match new format

Podfile.lock
This beta went out earlier today.
#trivial
=> update emission to 1.5.11

Podfile.lock
Self-assigning to get a beta out asap.
=> Updates Emission to 1.5.13 #trivial

Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m, CHANGELOG.yml
Fixes [PURCHASE-424](https://artsyproduct.atlassian.net/browse/PURCHASE-424). After this is merged, we can deploy a beta. /cc @briansw
=> Updates error messaging for Buy Now mutation failures

Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m, Artsy_Tests/Networking_Tests/API_Modules/ArtsyAPI+ArtworksTests.m, Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerBuyButtonTests.m, CHANGELOG.yml
Follow-up from #2685. Also adds a changelog entry for that PR.
=> Fixes mutation reference to include ecommerce prefix

Artsy/Models/API_Models/LiveAuctionLot.m, Artsy/Networking/static_sale_data.graphql, Artsy/View_Controllers/live_auctions_static.json, CHANGELOG.yml
The MVVM model, Mantle's keypathing and our approach to GraphQL's flexibility really paid off well for this PR
=> Adds support for showing multiple artists in live lots

Artsy.xcodeproj/project.pbxproj, Artsy.xcodeproj/xcshareddata/xcschemes/Artsy Integration Tests.xcscheme, Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme, Artsy/Categories/Apple/NSAttributedString+Additions.swift, Artsy/Categories/Apple/UILabel+Styling.swift, Artsy/Categories/Apple/UITableViewController+Animations.swift, Artsy/Categories/PanDirectionGestureRecognizer.swift, Artsy/View_Controllers/Auction/AuctionViewController.swift, Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift, Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionBidButton.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionBidHistoryViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionLoadingView.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionLotListViewController.swift, Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift, Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionEventViewModel.swift, Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift, Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionToolbarView.swift, Artsy/View_Controllers/SerifModalWebNavigationController.swift, Artsy/Views/AuctionCircularButtons.swift
The migrator failed, bit of a shame, however it was small enough that I could do it manually.
Not made it into the release, which is pretty chill.
#trivial  #known
=> Migrates us to Swift 4.2

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Migrates the CHANGELOG and versions etc
=> Prepare for 4.3.1

Artsy/App/ARAppDelegate+Analytics.m, Artsy/Models/API_Models/Partner_Metadata/Artwork.h, Artsy/Models/API_Models/Partner_Metadata/Artwork.m, Artsy/Networking/artwork.graphql, Artsy/View_Controllers/Artwork/ARArtworkViewController.m, Artsy_Tests/Model_Tests/ArtworkTests.m, CHANGELOG.yml
WIP because it's in the next release - and I don't want to do all the changelog faffing until we're certain that the release is going out.
For [DISCO-219](https://artsyproduct.atlassian.net/browse/DISCO-219) with the aim to replicate https://github.com/artsy/force/pull/2971
Will comment inline
=> Adds Buy Now analytics

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> Updates Emission and prepares for the next version

Artsy/App/ARAppNotificationsDelegate.m
This updates based on our conversation in Slack: https://artsy.slack.com/archives/C9YNS4X32/p1543612342033600
Maybe with the visual refresh work coming, we can look through for more copy changes like that we'd like to make.
| Before  | After  |
|---|---|
| <img width="559" alt="after" src="https://user-images.githubusercontent.com/498212/49315572-2f561600-f4bc-11e8-84f5-06b9694f12aa.png">  | <img width="559" alt="after2" src="https://user-images.githubusercontent.com/498212/49315583-354bf700-f4bc-11e8-8a98-0f0525707855.png">  |
=> Changes copy for prompt asking user to open Settings to enable push notifications #trivial

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Artsy/View_Controllers/Admin/ARAdminTableViewController.h, Artsy/View_Controllers/Admin/ARAdminTableViewController.m, CHANGELOG.yml
Adds an admin panel button for grabbing your tracking uuid
=> Adds a new admin menu option for copying your tracking UUID

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
So that #2743  and #2742 can get a changelog entry
=> Migrate to a new build version

CHANGELOG.yml, Podfile.lock
Deploys https://github.com/artsy/emission/pull/1244 into Eigen
=> Adds a CHANGELOG entry, and updates emission

CHANGELOG.yml, Podfile.lock
For https://github.com/artsy/emission/pull/1247
=> Updates Emission for 1.7.6

Artsy/View_Controllers/Debug/Quicksilver/ARQuicksilverViewController.m
The search changes broke the Quicksilver admin tool, mostly used by me, but y'know - I like it for browsing quickly via the keyboard
#trivial
=> Fixes Quicksilver

Podfile.lock
=> Update Adjust to the latest version

Artsy/Networking/API_Modules/ARUserManager.m, CHANGELOG.yml, Dangerfile.swift, Package.resolved
Also checks for 401s from auth to inform the user about failed credentials.
=> Improve the auth checking code for passsword-resets

.circleci/config.yml, Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml, README.md
Sets us up for the next release, and updates Circle CI to use Xcode 10.1
=> Prepare for next release + Xcode 10.1

Artsy/Models/API_Models/Application/SearchSuggestion.h, Artsy/Models/API_Models/Application/SearchSuggestion.m, CHANGELOG.yml
I believe this should fix https://artsyproduct.atlassian.net/browse/DISCO-257
=> Improves the search for fairs where their profileID is different

Artsy.xcodeproj/project.pbxproj, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Artsy/View_Controllers/Fair/ARFairComponentViewController+Eigen.h, Artsy/View_Controllers/Fair/ARFairComponentViewController+Eigen.m, Artsy/View_Controllers/Fair/ARFairSearchViewController.m, Artsy/View_Controllers/Fair/ARFairViewController.m, Artsy/View_Controllers/Search/ARSearchViewController+Private.h, Artsy/View_Controllers/Search/ARSearchViewController.m, Artsy/View_Controllers/Search/UIViewController+Search.h, Artsy/View_Controllers/Search/UIViewController+Search.m, Artsy/View_Controllers/Util/ARNavigationController.m, Artsy_Tests/View_Controller_Tests/Fair/ARFairSearchViewControllerTests.m, Artsy_Tests/View_Controller_Tests/Fair/ARFairViewControllerTests.m, CHANGELOG.yml
This PR fixes LD-207. It's a WIP because of the TODOs left in the code.
=> Fix for fair component search 📱

CHANGELOG.yml, Podfile.lock
Follow-up to https://github.com/artsy/metaphysics/pull/1517.
=> Updates Emission to 1.8.3 #trivial

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
=> Adds a clear relay cache button

Artsy/Networking/API_Modules/ArtsyAPI+Notifications.h, Artsy/Networking/API_Modules/ArtsyAPI+Notifications.m, Artsy/Networking/ARNetworkConstants.h, Artsy/Networking/ARNetworkConstants.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m
@joeyAghion  spotted some logs from this API, but it doesn't look like it's being used anywhere in the app. So I removed it while waiting on CI for something else.
=> Removes some unused networking code

fastlane/Fastfile
This PR reproduces as fix I made in emission automated deploys a few weeks ago: https://github.com/artsy/emission-nebula/commit/185e789e1cbcfddeb4b1188c85e9361bb1ba29a2
=> Fixes beta deploys #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> Preparing for the next release, version 4.4.0

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginFieldsView.m, CHANGELOG.yml
Fixes #2787. Thank you to @igor-makarov for pointing out how we can improve our app!
=> Adds text content types to signup/login flow text fields #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml, Podfile.lock
I've already verified that tests pass locally and I've kicked off a beta build.
=> Updates Emission to 1.8.11 #trivial

Artsy/Networking/ARRouter.m, CHANGELOG.yml
=> Uses POSTs for auth requests

Artsy/App/ARSwitchBoard.m
- Adds CityListSection route and CityFairList route
=> Adds new routes

Package.resolved
=> Update danger swift

Artsy/App/ARAppStatus.h, Artsy/App/ARAppStatus.m, Artsy/App/ArtsyEcho+LocalDisco.m
This will allow testing LD-391 
#trivial
=> Reduces the echo check for Local Disco to be admin only and not beta/dev also

Podfile, Podfile.lock
=> Update Emission and the react native mapbox lib

Artsy/App/ARAppDelegate+Analytics.m, Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Gemfile.lock
- Adds analytics to main nav buttons
=> Adds main nav analytics

Artsy/App/ARSwitchBoard.m, Artsy_Tests/App_Tests/ARSwitchboard+EchoSpec.m, Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m, CHANGELOG.yml
Our current betas don't update echo, which is a bit strange. This fixes that.
=> Hooks up Echo to make API calls

Artsy/App_Resources/Artsy-Info.plist
Sibling PR to https://github.com/artsy/emission/pull/1501
#trivial
=> Adds lslauchqueries for sending people to google maps because their n ative API urls work better than their web ones

fastlane/metadata/en-US/description.txt, fastlane/metadata/en-US/release_notes.txt
=> Updates the app store description + release notes

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> Readies repo for 5.0

Artsy/App/ARSwitchBoard.m, Artsy/App/ArtsyEcho+BNMO.m, Artsy/App/ArtsyEcho+LocalDisco.m, Artsy/View_Controllers/Admin/AREchoContentsViewController.m, Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, Artsy_Tests/App_Tests/ArtsyEchoTests.m, Artsy_Tests/View_Tests/ARArtworkActionsViewTests.m, CHANGELOG.yml, Podfile.lock
There's an API change (moving from an array to a dictionary) so lots of little changes throughout. I've tested the app locally and can't find any issues, and I've looked at every callsite of `messages`. 
Fixes LD-511
=> Updates to Aerodramus 1.0 #trivial

Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
- Fixes switch indexes for LD tracking
#trivial
=> Fixes switch indexes #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Since 5.0.0 was just released. Merge on green.
=> Version bump to 5.0.1 #trivial

Artsy/App/ARAppDelegate+Analytics.m, CHANGELOG.yml
Fixes [LD-537](https://artsyproduct.atlassian.net/browse/LD-537).
=> Adds offerable analytics to artwork view #trivial

docs/deploy_to_app_store.md, fastlane/Fastfile
CI is failing on the promote to App Store release - https://circleci.com/gh/artsy/eigen/6067
=> Fix fastlane promote

fastlane/metadata/en-US/release_notes.txt
=> Updates release notes for 5.0.2 #trivial

CHANGELOG.yml, Gemfile.lock, Podfile, Podfile.lock
This works for a lot of screens, but there are a few queries which fail on staging. Shouldn't be a blocker for merging and making a beta IMO.
=> Update to RN 0.59

fastlane/metadata/en-US/release_notes.txt
Updates release notes for 5.0.3.
=> Updates release notes for 5.0.3 #trivial

Podfile, Podfile.lock
This includes this PR: https://github.com/artsy/emission/pull/1590 As well as, apparently, an upgrade to tipis-stripe.
=> Emission update to 1.11.1

Podfile, Podfile.lock
Already deployed this in a beta. See: https://github.com/artsy/emission/pull/1592
=> Updates Emission to 1.11.2

Podfile.lock
Includes some updates to the fledgling artwork view in Emission.
=> Updates Emission to version 1.11.4 #trivial

Artsy/View_Controllers/Artwork/ARArtworkViewController.m, Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m, CHANGELOG.yml
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-1154
cc @sweir27 
#trivial
=> [Artwork] Load below the fold content of legacy VC

Artsy/App/ARAppDelegate+Analytics.m, Artsy/View_Controllers/Artwork/ARArtworkSetViewController.m, CHANGELOG.yml
Discussed in Slack: https://artsy.slack.com/archives/C02BAQ5K7/p1560357205139000
I've created the new `5.0.5-develop` branch from the last beta's tag. I've kicked off a deploy with this commit too.
=> Adds analytics tracking for artwork set view controller swipes

Podfile.lock
=> Updates Emission to 1.12.1

Artsy/App/ARSwitchBoard.m
Adds a link to the consignments flow information page.
=> PURCHASE-1171: If an artist is consignable, a user can click to consign their work through Artsy

Artsy/View_Controllers/Artwork/ARArtworkViewController.m
My bad!
Thought I had tested this in the simulator after adding this piece of logic but clearly I had not. 😞Works now!
#trivial
=> Correctly reference isInquireable.boolValue for artwork view switching logic

Podfile.lock
Includes a bunch of small updates to the Artwork view
=> Updates Emission to 1.12.5

docs/using_dev_emission.md
Getting the docs updated ahead of Friday's bug bash.
=> Updates development docs

Artsy/Models/API_Models/Application/FeaturedLink.m, Artsy_Tests/View_Tests/ARBrowseFeaturedLinksCollectionViewControllerTests.m, CHANGELOG.yml
=> DISCO-935 Trim whitespace on Featured link urls

Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionCurrentLotView.swift, CHANGELOG.yml
Subscribe to currentBidSignal for bidding price updates
=> PURCHASE-1131 Subscribe to currentBidSignal to update current lot

Artsy/View_Controllers/Util/ARNavigationController.m, CHANGELOG.yml
Documented here: https://www.notion.so/artsy/Crash-when-opening-app-from-Search-shortcut-on-iOS-home-screen-281bd2d9622f4c4b870463f80be6497a
=> Dont push search view if it already exists

Artsy/App/ARSwitchBoard.m
Removed the link to the consignments flow that doesn't present modally because we are going to use the existing route.
=> Removed unnecessary route

Podfile.lock
Standard Emission bump to get more Artwork view features out.
=> Updates Emission to 1.12.9

Podfile.lock
Small updates to the artwork view
=> Updates Emission to 1.12.11

Artsy/App/ARSwitchBoard.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy_Tests/App_Tests/ARSwitchBoardTests.m, Artsy_Tests/Networking_Tests/ARRouterTests.m, CHANGELOG.yml
- Adds routing for `/inquiry` and `/orders`
=> [PURCHASE-1344] Adds routing for inquiry and orders

Podfile.lock
- Updates Eigen to use Emission `1.12.12`
=> @1.12.12 - Updates version of Emission

Artsy/View_Controllers/Artwork/ARArtworkViewController.m, Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m, CHANGELOG.yml
This adds new flags. Note that they are **enabled** on Echo, so if you need to see the old view, you will have to disable them.
=> [PURCHASE-1366] Adds echo flag support for enabling various types of RN Artwork view.

Artsy/View_Controllers/Gene/GeneRefineSettings.swift, Artsy_Tests/Model_Tests/Data/gene_refine_example_full.json, Artsy_Tests/Model_Tests/Data/gene_refine_example_medium_price.json, CHANGELOG.yml, Podfile, Podfile.lock
Fixes https://artsyproduct.atlassian.net/browse/PLATFORM-1683
This needs to be verified on staging, but its data is currently out of whack.
=> [Gene] Fix refine settings after MP v2 switch

Podfile.lock
=> Emission update

Podfile, Podfile.lock
=> [Pods] Update Emission to v1.17.0

Podfile.lock
=> Update Emission to 1.17.1

Podfile.lock
=> Updates Emission to 1.17.2

Podfile.lock
Gonna self-merge. Already started a deploy.
=> Updates Emission to 1.17.3

Dangerfile.swift, Package.resolved
Obviates #2923. See: https://github.com/danger/swift/issues/281#issuecomment-538299682
=> Update danger swift #trivial

Artsy/App/ARAppDelegate.m, CHANGELOG.yml
- Adds killswitch based on Eigen version
- https://artsyproduct.atlassian.net/browse/ME-43
=> ME-43 - Adds killSwitch

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, Artsy/View_Controllers/Artwork/ARArtworkViewController.m, CHANGELOG.yml
Using `make update_bundle_version`.
=> Prepares for 6.0.0 betas

Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, CHANGELOG.yml
- Fixes circle icon size on messages ( https://artsyproduct.atlassian.net/browse/ME-33 )
=> ME-33 - Fixes circle height

Podfile.lock
=> Updates emission to 1.17.8

Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
It does seem like I merged this too early without looking at build results. This PR should fix the failure and also give Yuki one more chance to confirm successful builds before merging.
#trivial
=> Fix test failure in ARAppDelegateEmissionSpec

Podfile.lock
=> Update Emission to 1.18.10

CHANGELOG.yml, Podfile.lock
=> Update emission to 1.18.17

Podfile.lock
[ME-78] Includes this fix: https://github.com/artsy/extraction/pull/12
See also: https://github.com/artsy/emission/pull/1950
[ME-78]: https://artsyproduct.atlassian.net/browse/ME-78
=> Updates Extraction #trivial

CHANGELOG.yml, Podfile.lock
:shipit:
#trivial #skip_new_tests
=> Update emission to 1.18.23

fastlane/metadata/en-US/release_notes.txt
=> Updates release notes for 6.0.0 release #trivial

Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/View_Controllers/Fair/ARProfileViewController.m, CHANGELOG.yml
We mobbed on this in knowledge share.
=> Add option to show new partner page

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Updates to the changelog are manual, but the rest are done via `make update_bundle_version`.
=> Prepares for 6.0.1 betas

Artsy/App/ARSwitchBoard.m, Podfile.lock
- Adds routing for the new Partner page's locations view
=> Adds partner locations routing

CHANGELOG.yml, Podfile.lock
=> Update emission to 1.18.39

Artsy/App/ARAppDelegate+Emission.m, CHANGELOG.yml
Companion PR for artsy/emission#1981
=> implement show/hide api for back button

Artsy/View_Controllers/Fair/ARProfileViewController.m, CHANGELOG.yml
This is a trivial change so I'm going to self-merge. We want to get this out today in a beta, so I'm isolating this change in its own PR separate from #2964. 
/cc @kierangillen.
=> Puts new Partner page behind echo flag #trivial

README.md
I put a call out last week for anyone interested in being added as a point-person here but got no response. That's okay! If anyone _would_ like to be added, just say so 👍 /cc @kierangillen
=> Updates point people

README.md
=> Update broken Emission doc link

Podfile, Podfile.lock
=> Upgrade to Emission 1.20.0

Podfile, Podfile.lock
=> Upgrade to Emission 1.20.1

Artsy/App/ARSwitchBoard.h, Artsy/App/ARSwitchBoard.m, Artsy/Networking/API_Modules/ARUserManager.m, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h, Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m, Podfile, Podfile.lock
=> Adds log out button to app

Artsy.xcodeproj/project.pbxproj, Artsy/View_Controllers/AREigenCollectionComponentViewController.h, Artsy/View_Controllers/AREigenCollectionComponentViewController.m, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Podfile.lock
The full-bleed of the collection header was not rendering as expected. This PR updates the protocol used on the Collection view controller to enable the collection header to bleed to the top of the viewport.
#trivial
=> Enables full bleed on collection view controller

Podfile, Podfile.lock
Upgrade emission to 1.21.5
#trivial
=> Upgrade emission to 1.21.5

Artsy/View_Controllers/AREigenCollectionComponentViewController.m
Follow up to #2982 to remove unneeded function call to change status bar icon colors.
=> Removes unnecessary function call

Podfile, Podfile.lock
Update emission to v 1.21.6
#trivial
=> update emission to v 1.21.6

.circleci/config.yml, Artsy.xcodeproj/project.pbxproj, CHANGELOG.yml
See: https://github.com/artsy/emission/pull/2026
=> Xcode 11 update

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Podfile, Podfile.lock
Changes the default collection slug + upgrades to Emission v 1.21.8
#trivial
=> Change default collection + upgrade emission

Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, Artsy/Views/Utilities/ARTabContentView.m, CHANGELOG.yml
I've already added the new flag in Echo's dashboard.
=> [MX-149] Enables new Search for all users

Artsy/App/ARSwitchBoard.m
Submitting this PR as [a part of this spike](https://artsyproduct.atlassian.net/browse/FX-1600) for testing iOS Collections.
#trivial
=> Enables url schemes for Collections routes

Podfile, Podfile.lock
Upgrades Emission to 1.21.11
#trivial
=> upgrade emission to 1.21.11

Artsy/Networking/API_Modules/ARUserManager.m, CHANGELOG.yml
https://artsyproduct.atlassian.net/browse/MX-151
This covers both admin logout and user logout. Do you think it's worth adding a test for this @ashfurrow ? I couldn't figure out how to run the tests for `ARUserManager` locally.
=> [MX-151] clear search history on log out

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Podfile, Podfile.lock
Upgrade Emission to 1.21.24
#trivial
=> Upgrade Emission to 1.21.24

Podfile, Podfile.lock
Upgrades Emission to 1.21.27
#trivial
=> Upgrades Emission to 1.21.27

Artsy/App/ARAppDelegate.m, CHANGELOG.yml
https://artsyproduct.atlassian.net/browse/MX-164
=> [MX-164] Disable dark mode

Podfile, Podfile.lock
Upgrades emission to 1.21.28
#trivial
=> Upgrades emission to 1.21.28

Podfile, Podfile.lock
Upgrades Emission to 1.21.29
#trivial
=> Upgrades Emission to 1.21.29

Podfile, Podfile.lock
Upgrades Emission to 1.21.31
#trivial
=> Upgrades Emission to 1.21.31

Artsy/Networking/API_Modules/ARUserManager.h, Artsy/Networking/API_Modules/ARUserManager.m, Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, CHANGELOG.yml
This PR is stacked on #3003 and should be merged into master after that. (remember to change the target branch)
https://artsyproduct.atlassian.net/browse/MX-157
=> [HOLD] [MX-157] use non-exiting logout for session expired

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
See notes here: https://github.com/artsy/eigen/blob/master/docs/deploy_to_app_store.md#prepare-for-the-next-release
=> Prepares for version 6.3.0 #trivial

Artsy/App/ARSwitchBoard.m, CHANGELOG.yml
We mobbed on this in Knowledge Share. It's a WIP since 6.2.1 is still in Apple Review.
https://artsyproduct.atlassian.net/browse/FX-1760
=> Fixes full-bleed collections display

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Podfile, Podfile.lock
- Upgrades Emission to 1.21.35
- Updates default collection to "Old Masters"
=> Upgrades Emission to 1.21.35

Podfile, Podfile.lock
Upgrades Emission to 1.21.39
#trivial
=> Upgrades Emission to 1.21.39

Artsy/App/AROptions.h, Artsy/App/AROptions.m, CHANGELOG.yml
Adds a lab feature for collections artworks.
https://artsyproduct.atlassian.net/browse/FX-1796
=> Adds a lab feature for collections artworks

CHANGELOG.yml, Podfile, Podfile.lock
=> Upgrades Emission to 1.21.40

Podfile, Podfile.lock
Upgrades emission to 1.21.41
#trivial
=> Upgrades emission to 1.21.41

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, Podfile, Podfile.lock
Upgrade Emission to 1.21.44
#trivial
=> Upgrade Emission to 1.21.44

fastlane/metadata/en-US/release_notes.txt
I conferred with the FX team last week on how to handle Collections support.
=> Updates release notes for 6.3.0 #trivial

Podfile.lock, emission/storybook/storyLoader.js
These are autogenerated file changes that others will see as soon as pulling from master, so I'm going to self-assign this one to get them on master quickly. /cc @ds300
=> Quick cleanups after Emission merge #trivial

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, src/lib/Components/ArtworkFilterOptions/SortOptions.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/SortOptions-tests.tsx, src/lib/Components/FilterModal.tsx, src/lib/Components/__tests__/FilterModal-tests.tsx, src/lib/Scenes/Collection/Collection.tsx
Enables selecting sort options in artwork filter nav stack.
https://artsyproduct.atlassian.net/browse/FX-1782
#trivial
=> Sort options filter

Makefile
Adds make command to clear caches and build files for troubleshooting.
=> Add flip table make command (┛ಠ_ಠ)┛彡┻━┻

src/lib/Components/Home/ArtistRails/ArtistCard.tsx, src/lib/Components/Home/ArtistRails/__tests__/__snapshots__/ArtistCard-tests.tsx.snap
https://artsyproduct.atlassian.net/browse/MX-196
#trivial
=> [MX-196] Fix artist card styles

docs/README.md
I noticed that there is no longer a `eigen_tips.md` file. Happy to rename if one exists, I just happened to be here today and thought someone might appreciate a small PR like this ¯\_(ツ)_/¯
=> Remove dev tips from the docs since it no longer exists

renovate.json
Thanks for your long service @zephraph 💪 
#trivial
=> Set ds300 as assignee for renovate updates

CHANGELOG.yml, src/__generated__/FairsRail_fairs_module.graphql.ts, src/__generated__/ForYouRefetchQuery.graphql.ts, src/__generated__/QueryRenderersForYouQuery.graphql.ts, src/lib/Scenes/Home/Components/ForYou/Components/FairsRail.tsx, src/lib/Scenes/Home/Components/ForYou/Components/__tests__/FairsRail-tests.tsx, src/lib/Scenes/Home/Components/ForYou/Components/__tests__/__snapshots__/FairsRail-tests.tsx.snap
This change brings in the hero image as the first image in the card:
Also includes a changelog entry for #3041.
=> Fair card updates

src/__generated__/FairsRail_fairs_module.graphql.ts, src/__generated__/ForYouRefetchQuery.graphql.ts, src/__generated__/QueryRenderersForYouQuery.graphql.ts, src/lib/Scenes/Home/Components/ForYou/Components/ArtworkRail.tsx, src/lib/Scenes/Home/Components/ForYou/Components/FairsRail.tsx, src/lib/Scenes/Home/Components/ForYou/Components/__tests__/FairsRail-tests.tsx, src/lib/Scenes/Home/Components/ForYou/Components/__tests__/__snapshots__/FairsRail-tests.tsx.snap
Here's what we've got
/cc @samchieng
=> [MX-260] Updates home feed designs #trivial

src/lib/Components/FilterModal.tsx, src/lib/Components/__tests__/FilterModal-tests.tsx
Updates UI on Filter Modal Apply Button
https://artsyproduct.atlassian.net/browse/FX-1853
#trivial
=> Updates UI on Filter Modal Apply Button

.circleci/config.yml
Forgot to update this in both places earlier 🙈 it caused a build fail on master for the update-metaphysics step: https://circleci.com/gh/artsy/eigen/7354
=> Fix node_modules caching for metaphysics update script too

src/lib/utils/__tests__/ArtworkFiltersStore-tests.tsx
Adds test coverage for artworks filters reducer
=> Adds test coverage for artworks filters reducer

Makefile, fastlane/Fastfile
I noticed that the promotion fastlane script was failing here: https://circleci.com/gh/artsy/eigen/7366 Seems like I forgot to rename some variables 🙈 
I also took the time to remove some unnecessary work from our `Makefile`, and update one of its tasks to make it obvious that it's not to be called from development machines (by prefixing it with an underscore).
=> Fixes app promotion issue

fastlane/Fastfile
Followup from #3096 based on this failure: https://circleci.com/gh/artsy/eigen/7473
=> Fixes promotion script again #trivial

src/lib/Components/ArtworkFilterOptions/SortOptions.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/SortOptions-tests.tsx, src/lib/Components/FilterModal.tsx, src/lib/Components/__tests__/FilterModal-tests.tsx, src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx, src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx, src/lib/utils/ArtworkFiltersStore.tsx, src/lib/utils/__tests__/ArtworkFiltersStore-tests.tsx
Reverts artsy/eigen#3107
this introduced a test failure due to sneaky logical merge conflicts. Going to rebase on master and PR again.
=> Revert "Selected sort option"

src/lib/Components/ArtworkFilterOptions/SortOptions.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/SortOptions-tests.tsx, src/lib/Components/FilterModal.tsx, src/lib/Components/__tests__/FilterModal-tests.tsx, src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx, src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx, src/lib/utils/ArtworkFiltersStore.tsx, src/lib/utils/__tests__/ArtworkFiltersStore-tests.tsx
Retrying #3107 , which was undone by #3113 
There was a small logical conflict in files that were updated by both ashley and sarah which never got resolved.
@sweir27 @ashleyjelks  I added just one small fixup commit. Please check that it makes sense and then let's try again 🙏
=> Selected sort option 2

.circleci/config.yml, Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy/App/ARSwitchBoard.m, CHANGELOG.yml, emission/Pod/Classes/ViewControllers/ARViewingRoomComponentViewController.h, emission/Pod/Classes/ViewControllers/ARViewingRoomComponentViewController.m, src/lib/AppRegistry.tsx, src/lib/Scenes/Partner/Components/PartnerShows.tsx, src/lib/Scenes/ViewingRoom/ViewingRoom.tsx, src/lib/Scenes/ViewingRoom/index.tsx
This is just an empty shell behind a lab option (so users don't see it until we're ready). #skip_new_tests
=> Galleries viewing rooms shell

.circleci/config.yml
Going to self merge since this is trivial, there should really be a button for it 🙈
=> Clear linux CI caches

.circleci/config.yml, fastlane/Fastfile, fastlane/metadata/copyright.txt
Several fixes, mobbed on in Knowledge Share.
=> Fix promotion script #trivial

CHANGELOG.yml, src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/CommercialInformation_artwork.graphql.ts, src/lib/Scenes/Artwork/Components/CommercialInformation.tsx, src/lib/utils/track/schema.ts
follow-up to https://artsyproduct.atlassian.net/browse/AUCT-892 after discussion on event schema
=> Update lotViewed event schema - paired with @dleve123

.circleci/config.yml, Gemfile.lock
See: https://github.com/orta/cocoapods-keys/pull/202
=> Upgrades CocoaPods-Keys

Artsy/App/ARAppDelegate+Analytics.m
Adds a user property to the session.
=> Adds tracking for iOS Dark Mode #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Updates version numbers and changelog.
=> Prepares for 6.4.1 development #trivial

CHANGELOG.yml, data/schema.graphql, src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/Artwork_me.graphql.ts, src/__generated__/BidButtonTestsQuery.graphql.ts, src/__generated__/BidButton_artwork.graphql.ts, src/__generated__/BidButton_me.graphql.ts, src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts, src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts, src/__generated__/CommercialButtons_me.graphql.ts, src/__generated__/CommercialInformation_me.graphql.ts, src/lib/Scenes/Artwork/Artwork.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/BidButton-tests.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx, src/lib/Scenes/Artwork/Components/CommercialInformation.tsx, src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx, src/lib/__fixtures__/ArtworkBidAction.ts, src/lib/utils/track/schema.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-964
=> [AUCT-964] User who needs IDV sees a button to register which sends user to typical sale registration form and does not see max bid dropdown

CHANGELOG.yml, src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts, src/__generated__/CollectionArtworks_collection.graphql.ts, src/__generated__/CollectionQuery.graphql.ts, src/__generated__/CollectionTestsQuery.graphql.ts, src/__generated__/FilterModalTestsQuery.graphql.ts, src/lib/Components/ArtworkFilterOptions/MediumOptions.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/MediumOptions-tests.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/SortOptions-tests.tsx, src/lib/Components/FilterModal.tsx, src/lib/Components/__tests__/FilterModal-tests.tsx, src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx, src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx, src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap, src/lib/utils/ArtworkFiltersStore.tsx
This PR enables filtering by artwork medium in Collections.
https://artsyproduct.atlassian.net/browse/FX-1476
=> Adds Collections Medium Artwork Filter

CHANGELOG.yml, src/__generated__/HomeQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/Home_homePage.graphql.ts, src/lib/Scenes/Home/Home.tsx
Here's what it looks like:
We don't have a tonne of control over the ordering, so I called that out in a comment.
=> [MX-193] Home re-ordering and skeleton loader

package.json, scripts/update-metaphysics.js, yarn.lock
Tested this over here: https://github.com/artsy/metaphysics-ci-test/pull/15
=> Use @artsy/update-repo to update metaphysics

src/lib/Components/FilterModal.tsx, src/lib/Scenes/Collection/Collection.tsx, src/lib/Scenes/Collection/Helpers/FilterArtworksHelpers.ts, src/lib/Scenes/Collection/Helpers/__tests__/FilterArtworksHelpers-tests.tsx, src/lib/Scenes/Collection/Screens/CollectionZeroState.tsx, src/lib/utils/track/schema.ts
Adds changes to tracking based on QA by @abhitip.
- Updates missing action types
- De-deduplicates previously selected, but currently applied filters.
- Adds additional unit tests
https://artsyproduct.atlassian.net/browse/FX-1896
#trivial
=> Makes corrections to collections filters analytics tracking

CHANGELOG.yml
=> Update changelog #trivial

src/lib/Components/SectionTitle.tsx, src/lib/Scenes/Home/Home.tsx
https://artsyproduct.atlassian.net/browse/MX-283
- Makes header sticky in home
- Bumps font size of rail subtitles
=> [MX-283] - Home design tweaks

Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m, CHANGELOG.yml
I agree that flagging it off is better than reverting the whole PR 👍
=> Defers Sign In with Apple until next release

fastlane/Fastfile, src/lib/Components/Home/ArtistRails/ArtistRail.tsx, src/lib/Scenes/Home/Components/ArtworkRail.tsx, src/lib/Scenes/Home/Components/FairsRail.tsx, src/lib/Scenes/Home/Components/SalesRail.tsx, src/lib/Scenes/Home/Components/__tests__/FairsRail-tests.tsx
https://artsyproduct.atlassian.net/browse/MX-276
Updates copy based on Sam's feedback for home rails.
Corresponding Metaphysics PR here:
https://github.com/artsy/metaphysics/pull/2311
=> [MX-276] - Update eigen side copy for home rails

docs/deploy_to_beta.md
To reflect our new ✨ nightly betas ✨ (among a few other updated details).
=> Updates beta docs

CHANGELOG.yml, src/lib/Components/Bidding/Screens/Registration.tsx, src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/BidButton-tests.tsx, src/lib/utils/auction/bidderNeedsIdentityVerification.ts, src/lib/utils/auction/index.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-985
This PR allows manually approved users to bid even when they are not verified.
=> Allow manually approved users to bid even when they are not verified

Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
Another silly one, need to check values are non-nil before storing in keychain otherwise 💥
=> Add null check before attempting to store in keychain #trivial

src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts, src/__generated__/CollectionArtworksTestsQuery.graphql.ts, src/__generated__/CollectionArtworks_collection.graphql.ts, src/__generated__/CollectionQuery.graphql.ts, src/__generated__/CollectionTestsQuery.graphql.ts, src/__generated__/FilterModalTestsQuery.graphql.ts, src/lib/Components/ArtworkFilterOptions/PriceRangeOptions.tsx, src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/PriceRangeOptions-tests.tsx, src/lib/Components/FilterModal.tsx, src/lib/Components/__tests__/FilterModal-tests.tsx, src/lib/Scenes/Collection/Helpers/FilterArtworksHelpers.ts, src/lib/Scenes/Collection/Helpers/__tests__/FilterArtworksHelpers-tests.tsx, src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx, src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx, src/lib/utils/ArtworkFiltersStore.tsx
Pretty straightforward now that this is the third filter we've built! Adds the ability to filter by price range from a collection view.
Addresses: https://artsyproduct.atlassian.net/browse/FX-1635
=> Adds Price Range filter to collection view

dangerfile.ts
Follow up to #3233. /cc @ds300
=> Removes comments from Dangerfile #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> Prepares for 6.4.4 release.

src/lib/Components/GenericArtistSeriesRail.tsx
A ref needs to be attached to the GenericArtistSeriesRail component to support the use of Switchboard's `presentNavigationViewController` method. This PR moves that ref to a View wrapping the entire component.
=> Removes incorrectly placed ref

CHANGELOG.yml, src/__generated__/CollectionHubsRails_linkedCollections.graphql.ts, src/__generated__/CollectionQuery.graphql.ts, src/__generated__/CollectionTestsQuery.graphql.ts, src/__generated__/OtherCollectionsRail_collectionGroup.graphql.ts, src/lib/Scenes/Collection/Components/CollectionHubsRails/OtherCollections/OtherCollectionsRail.tsx, src/lib/Scenes/Collection/Components/CollectionHubsRails/OtherCollections/__tests__/OtherCollectionsRail-tests.tsx, src/lib/Scenes/Collection/Components/CollectionHubsRails/index.tsx, src/lib/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
Okay let's try this again
-----
Re: [FX-1799](https://artsyproduct.atlassian.net/browse/FX-1799)
=> [FX-1799] Implements small other collections category rail

CHANGELOG.yml, src/__generated__/ArtistCard_artist.graphql.ts, src/__generated__/ArtistRailFollowMutation.graphql.ts, src/__generated__/HomeQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/lib/Components/Home/ArtistRails/ArtistCard.tsx
Probably best to review this one with GitHub's "ignore whitespace" option enabled 👍
=> [MX-245] Adds suggested artist basis to home rails

src/lib/Scenes/Consignments/index.tsx, src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
This builds out a static layout for the v2 page. Next up will wire in dynamic data.
#trivial
=> [Consignments] Build out static v2 landing

fastlane/metadata/en-US/release_notes.txt, src/__generated__/HomeQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/__generated__/Home_homePage.graphql.ts, src/lib/Scenes/Home/Components/FairsRail.tsx, src/lib/Scenes/Home/Components/SmallTileRail.tsx, src/lib/Scenes/Home/Home.tsx
Mobbed on the changelog update and home module updates with MX, so I'm going to self-assign. The beta is already underway.
=> Finishing touches for 6.4.4 release #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> Updates for 6.4.5 development

docs/map_to_the_app.md
This came up in a recent retro. I've tried to elevate the abstraction level a bit: less "this is how to code a specific thing" and more "these are our goals." I also included some historical notes on changes we've made since the map was originally written.
=> Updates the app map

src/__generated__/CollectionsRailTestsQuery.graphql.ts, src/__generated__/CollectionsRail_collectionsModule.graphql.ts, src/__generated__/HomeQuery.graphql.ts, src/__generated__/HomeRefetchQuery.graphql.ts, src/lib/Scenes/Home/Components/CollectionsRail.tsx
We fall back to the empty string if the count is missing for whatever reason so that all the cards have the same height.
=> Adds total # to collections on Home #trivial

Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m, CHANGELOG.yml
Addresses https://artsyproduct.atlassian.net/browse/CSGN-202
What it looks like:
=> [CSGN-202] Move the sell tab to 4th in the nav

CHANGELOG.yml, src/lib/Scenes/Home/Home.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-174
The title says it all.
=> [CSGN-174] Hide consign sash when sell tab feature flag is enabled

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
- Update version number
- Update changelog for hotfix and upcoming work
=> Preparing for development version 6.4.6 #trivial

Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
Jira ticket https://artsyproduct.atlassian.net/browse/AUCT-1040 🔒 
#trivial
=> change flash_message to flashMessage #trivial

src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/ArtistList.tsx, src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/Footer.tsx, src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/Header.tsx, src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/HowItWorks.tsx, src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
Addresses: [CSGN-201](https://artsyproduct.atlassian.net/browse/CSGN-201)
This PR makes the following copy changes:
- Change both button CTAs to: Submit a work
- Change recently sold works header from “with Artsy” to: “on Artsy”
- Change receive payment description copy to: We'll help you ship the work, and ensure you receive payment quickly.
- Change artists header from “Artists collectors are looking to buy” to “Artists in-demand on Artsy”
=> [CSGN-201] make copy changes to consignment app

fastlane/metadata/en-US/release_notes.txt, src/lib/utils/router.ts
Quick fix for an issue we found during QA.
=> Fix show href creation

src/lib/Scenes/Home/Components/__tests__/EmailConfirmationBanner-tests.tsx
Just to follow up on https://github.com/artsy/eigen/pull/3351 I tried to replace enzyme usages with `react-test-renderer`. This was mostly straight forward except I cuoldn't figure out how I could get the tests pass without `done` and `setTimeout`. Perhaps I'm missing something, so it would be great if you could review and guide me to the right direction.
#trivial
=> Replace enzyme usages with react-test-renderer

package.json, tsconfig.json, yarn.lock
Palette PR: https://github.com/artsy/palette/pull/705
Opening this for now to see CI pass and ask what the appropriate Q/A process for something like this would be. In general I'm not super concerned since the breaking changes were mostly about pulling values out of the theme directly which isn't done in this codebase. The only real change here I'm making is removing `"keyofStringsOnly": true` from the tsconfig, which is required for type-check to pass (I'm not positive why this was enabled in the first place).
#trivial
=> [WIP] Upgrades to styled-system v5

CHANGELOG.yml, data/schema.graphql, src/__generated__/createConsignmentSubmissionMutation.graphql.ts, src/lib/Scenes/Consignments/Submission/createConsignmentSubmission.ts
Depends on https://github.com/artsy/metaphysics/pull/2450 
Addresses https://artsyproduct.atlassian.net/browse/CSGN-177
Related: https://github.com/artsy/convection/pull/682
This fixes an issue where the `userAgent` wasn't being passed along during a consignment submission.
=> [Consignments] Pass userAgent over when creating submission

Artsy/App/AROptions.h, Artsy/App/AROptions.m, src/lib/Scenes/Home/Home.tsx, src/lib/Scenes/Home/__tests__/Home-tests.tsx, src/setupJest.ts, typings/emission.d.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-1067
#trivial
=> Remove the feature flag for email confirmation sash in Eigen

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Updates version number and changelog.
=> Prep for 6.4.8.

Artsy/App/ARSwitchBoard.m, emission/Pod/Classes/ViewControllers/ARMyCollectionAddArtworkComponentViewController.h, emission/Pod/Classes/ViewControllers/ARMyCollectionAddArtworkComponentViewController.m, emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.h, emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.m, emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkListComponentViewController.h, emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkListComponentViewController.m, emission/Pod/Classes/ViewControllers/ARMyCollectionHomeComponentViewController.h, emission/Pod/Classes/ViewControllers/ARMyCollectionHomeComponentViewController.m, src/lib/AppRegistry.tsx, src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/index.tsx, src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/index.tsx, src/lib/Scenes/Consignments/v2/Screens/MyCollectionHome/index.tsx, src/lib/Scenes/Consignments/v2/State/navigationState.ts, src/lib/Scenes/Consignments/v2/State/store.tsx
=> Revert "Revert "[My Collection] Stub out skeleton nav flow ""

package.json, yarn.lock
Addresses `Adopted` status of [this RFC](https://github.com/artsy/eigen/issues/3452). 
#trivial
=> [Lib] Add formik and yupp

CHANGELOG.yml, src/__generated__/ArtistAboveTheFoldQuery.graphql.ts, src/__generated__/ArtistArtworksQuery.graphql.ts, src/__generated__/ArtistArtworks_artist.graphql.ts, src/__generated__/ArtistNotableWorksRailTestsQuery.graphql.ts, src/__generated__/ArtistNotableWorksRail_artist.graphql.ts, src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx, src/lib/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tsx, src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx, src/lib/Components/Artist/ArtistArtworks/__tests__/ArtistNotableWorksRail-tests.tsx, src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx, src/lib/Scenes/Collection/Collection.tsx
https://artsyproduct.atlassian.net/browse/FX-1964
=> Add Notable Works rail to Artist pages

src/lib/Scenes/Consignments/v2/Form/useFormikSync.ts, src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx, src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Screens/MyCollectionAddArtworkTitleAndYear.tsx
Missed a small cleanup opportunity to compose things.
#trivial
=> [MyCollection] Combine hooks

src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx, src/lib/Scenes/Consignments/v2/State/artworkModel.tsx, src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
This adds some more form checking behavior, in this case an action sheet that will present if the add  artwork form is dirty: 
#trivial
=> [MyCollection] Add dirty form checking action sheet

src/__generated__/MyAccountQuery.graphql.ts, src/__generated__/MyAccount_me.graphql.ts, src/lib/Scenes/MyAccount/MyAccount.tsx
For users who've signed up with FB and Apple hide "Change password" menu option
https://artsyproduct.atlassian.net/browse/MX-363
#trivial
=> [MX-363] hide change password for users signed up using facebook and apple

Artsy/App/main.m, src/lib/Scenes/Consignments/v2/Form/artworkSchema.tsx, src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx, src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/MyCollectionArtworkDetail.tsx, src/lib/Scenes/Consignments/v2/State/artworkModel.tsx, src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
This adds the rough static view for ArtworkDetail.
#trivial 
=> [MyCollection] Add static ArtworkDetail view 

Artsy/App/ARSwitchBoard.m, src/__generated__/MyAccountEditPhoneMutation.graphql.ts, src/__generated__/MyAccountEditPhoneQuery.graphql.ts, src/__generated__/MyAccountEditPhone_me.graphql.ts, src/lib/AppRegistry.tsx, src/lib/Scenes/MyAccount/MyAccount.tsx, src/lib/Scenes/MyAccount/MyAccountEditPhone.tsx, src/lib/Scenes/MyAccount/__tests__/MyAccountEditPhone-tests.tsx
Allow users to edit their phone number
https://artsyproduct.atlassian.net/browse/MX-362
=> added change phone number screen

src/lib/Scenes/Collection/Components/CollectionHubsRails/FeaturedCollections/FeaturedCollectionsRail.tsx
https://artsyproduct.atlassian.net/browse/FX-1970
=> Use above the fold Flatlist on Collection Department Rails

src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
Implement the new Personal Data Request Page
**Ticket/Issue Link:** https://artsyproduct.atlassian.net/browse/MX-395
#trivial
=> update Personal Data Request Page

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
`make next` and changelog dance. Also prettier 😭
=> Prepares for 6.4.9 development

fastlane/Gemfile
Attempt to fix: https://circleci.com/gh/artsy/eigen/13039
See issue in the gem's repo for discussion: https://github.com/postmodern/digest-crc/issues/19
#trivial
=> Add rake to gem file #trivial

src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
=> [MX-395] Privacy Request visual tweaks

CHANGELOG.yml, src/__generated__/HomeRefetchQuery.graphql.ts, src/lib/Scenes/Home/Components/HomeHero.tsx, src/lib/Scenes/Home/Home.tsx
https://artsyproduct.atlassian.net/browse/MX-401 - add 60% breakpoint for title on iPad
https://artsyproduct.atlassian.net/browse/MX-403 - fix spacing above and below hero unit
✨ bonus ✨ 
- fix refetch query so it gets the right version of the hero background image
=> [MX-401][MX-403] Home Promo QA fixes

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
=> Removes collection entry point from Admin view

Artsy/App/ARAppActivityContinuationDelegate.m, Artsy/App/ARAppDelegate+Analytics.h, Artsy/App/ARAppDelegate+Analytics.m, Artsy/App/ARAppDelegate.m, Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m, CHANGELOG.yml
https://artsyproduct.atlassian.net/browse/MX-171
Adds referrerLink to analytics for opened universal links. 
#trivial
=>  [MX-171] - Add referrer to deeplink analytics #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
- Ran make next
- Create 6.5.0 release in changelog (sentry errors were after 6.4.9 submission)
- Add 6.4.9 to releases in changelog
=> Preparing for development version 6.5.0 #trivial

CHANGELOG.yml, package.json, patches/@artsy+palette+11.7.0.patch, src/__generated__/ArtistSeriesFollowMutation.graphql.ts, src/__generated__/ArtistSeriesTestsQuery.graphql.ts, src/__generated__/ArtistSeries_artistSeries.graphql.ts, src/lib/Scenes/ArtistSeries/ArtistSeries.tsx, src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx, yarn.lock
https://artsyproduct.atlassian.net/browse/FX-2086
=> Adds Entity Header to Artist Series

src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
See [MX-395].
[MX-395]: https://artsyproduct.atlassian.net/browse/MX-395
=> Minor tweak to Priacy Request typography #trivial

src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
It was there to remind me to fix this. It was fixed, but I forgot to remove the comment.
#trivial
=> Forgot to remove a comment

CHANGELOG.yml, src/lib/Scenes/MyProfile/MyProfilePayment.tsx
Adds a placeholder screen to the payment menu. Follow up from #3484
=> Add payment placeholder

docs/developing_a_feature.md
The type of this PR is: **Documentation** <sub>(that wasnt in the PR template, who would have expected Documentation to come up so quickly 😅)</sub>
Adding some Notion links to docs on how to QA a new feature.
=> Adding some links for QAing a new feature #trivial

docs/pull_request_template.md
let's make it more.. english :D
=> simpler text #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
The type of this PR is: **Release**
Release upkeep.
=> Prepare for next release #trivial

CHANGELOG.yml, src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx, src/lib/Components/FilterModal.tsx, src/lib/Scenes/Collection/Collection.tsx
This PR resolves: n/a
In Knowledge Share today, we made the filter pill button animate into and out of view. We refactored this view into its own, new `AnimatedArtworkFilterButton` component.
/cc @ashleyjelks 
Test in the betas, maybe adjusting the spring animation parameters.
<details>
<summary>Animation on Collection page</summary>
</details> 
<details>
<summary>Animation on Artist Artworks page</summary>
</details>
=> Adds animation to filter button appearing / disappearing.

.circleci/config.yml
This PR temporarily removes deploy blocks, similar to https://github.com/artsy/force/pull/5989.
=> Temporarily removes Horizon deploy blocks.

.circleci/config.yml
=> Revert "Temporarily removes Horizon deploy blocks."

Artsy/App/ARAnalyticsConstants.h, Artsy/App/ARAnalyticsConstants.m, Artsy/App/ARAppActivityContinuationDelegate.m, Artsy/App/ARAppDelegate+Analytics.m, Artsy/App/ARAppDelegate.m, Artsy/Networking/API_Modules/ARUserManager.m, CHANGELOG.yml, Podfile, Podfile.lock
The type of this PR is: **dependency**
This removes the Adjust SDK; we haven't used their service for a while but forgot to remove it here.
=> Removes Adjust SDK #trivial

Artsy/App/AROptions.h, Artsy/App/AROptions.m, CHANGELOG.yml, src/lib/Scenes/Home/Home.tsx, src/setupJest.ts, typings/emission.d.ts
This PR resolves **[MX-476]**
This shows the home promo space for all users.
Test on staging, and in our next QA session.
[MX-476]: https://artsyproduct.atlassian.net/browse/MX-476
=> [MX-476] Ungates Home Promo space.

src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Form/artworkSchema.tsx, src/lib/Scenes/Consignments/v2/Screens/AddArtwork/MyCollectionAddArtwork.tsx, src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Screens/MyCollectionAddArtworkAddPhotos.tsx, src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Screens/MyCollectionAddArtworkTitleAndYear.tsx
This PR does some final pre-backend cleanup for the Add Artwork screen:
- Matches comps
- Adds validation 
#trivial
=> [MyCollection] Cleanup AddArtwork screen 

Artsy.xcodeproj/project.pbxproj, Artsy/App/ARAppDelegate+Analytics.m, Artsy/App/ARSailthruIntegration.h, Artsy/App/ARSailthruIntegration.m, Artsy/Networking/API_Modules/ARUserManager.m, CHANGELOG.yml
The type of this PR is: **Integration**
This PR resolves **[MX-469]**
This integrates Sailthru into the app's existing analytics use. 
I had to kind of shoe-horn things in, so we can take a look in the Sailthru dashboard to see if I got everything right after the next beta.
[MX-469]: https://artsyproduct.atlassian.net/browse/MX-469
=> [MX-469] Sends data to Sailthru

package.json, src/__generated__/PartnerQuery.graphql.ts, src/__generated__/PartnerRefetchQuery.graphql.ts, src/__generated__/PartnerShowsInfiniteScrollGridQuery.graphql.ts, src/__generated__/PartnerShowsTestsQuery.graphql.ts, src/__generated__/PartnerShows_partner.graphql.ts, src/__generated__/ViewingRoomArtworkQuery.graphql.ts, src/__generated__/ViewingRoomArtwork_viewingRoomInfo.graphql.ts, src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx, src/lib/Scenes/Home/Home.tsx, src/lib/Scenes/Partner/Components/PartnerShows.tsx, src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx, src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx, src/lib/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx, src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx, src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx, src/lib/Scenes/ViewingRoom/ViewingRoom.tsx, src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx, src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx, src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx, src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx, src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx, src/lib/utils/track/schema.ts, tslint.json
The type of this PR is: **Bugfix/Enhancement**
#trivial
- Adding a few new analytics events and fixing some existing ones. Didn't use cohesion here as the needed changes were not there already, and I need to fix this quickly for the launch. We will make them nice next week.
For context, here is the doc: https://docs.google.com/spreadsheets/u/1/d/1o1J8xs7R3wLY7MXAK28J2XKmYe4NSiKT0aNdwMkryZA/edit#gid=0.
- Removed some testing buttons we added a while ago.
- Added a `shouldTrack` prop in the ArtworkRail so we can disable it for the VR page and do our own tracking. It's a bit messy since some events use the old names, some the new names, and some cohesion. Once we move these to cohesion we could remove this prop too, or at least fix up the other props that are used. For the FeaturedRail for …
=> Qa fixes 2

src/lib/Scenes/Partner/Components/PartnerHeader.tsx
The type of this PR is: **Design Upkeep**
This PR resolves **[MX-458]**
[MX-458]: https://artsyproduct.atlassian.net/browse/MX-458
=> [MX-458] - Add spacing beneath header on gallery page #trivial

src/__generated__/ViewingRoomsListQuery.graphql.ts, src/__generated__/ViewingRoomsList_query.graphql.ts, src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx, src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx, src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomsList-tests.tsx
Quick change to make only live VRs appear in the lists.
No closed, no scheduled.
#trivial
=> Final qa vrs

src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
This PR resolves: https://www.notion.so/artsy/Push-notification-toggles-have-some-stickiness-when-turned-on-off-d5dc34d7513b4576a1c126cdf1fc7214
Fix issue with push notification not being responsive
#trivial
=> fixed issue with push notification stickiness

src/lib/Components/FancyModal/FancyModalContext.tsx
trivial fix for minor fancy modal layout issue, self-merging
#trivial
=> Fix initial jump on tab load

src/lib/Components/FancyModal/FancyModalContext.tsx
follow-up to #3669 which accidentally introduced a different minor visual glitch, #trivial self-merging 🙏
=> Fix black background flash on intial tab load

CHANGELOG.yml, src/__generated__/ViewingRoomQuery.graphql.ts, src/__generated__/ViewingRoomSubsectionsTestsQuery.graphql.ts, src/__generated__/ViewingRoomSubsections_viewingRoom.graphql.ts, src/__generated__/ViewingRoomTestsQuery.graphql.ts, src/lib/Components/ReadMore.tsx, src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx, src/lib/Scenes/Artwork/Components/AboutArtist.tsx, src/lib/Scenes/Artwork/Components/AboutWork.tsx, src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx, src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx, src/lib/Scenes/Collection/Screens/CollectionHeader.tsx, src/lib/Scenes/Partner/Components/PartnerOverview.tsx, src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx, src/lib/Scenes/ViewingRoom/ViewingRoom.tsx, src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
The type of this PR is: **Bugfix/Enhancement**
- Small copy changes for non-live VRs
- Add support for new `Text` in `ReadMore`, and use it in VR
- Fix wrong aspect ratio of subsection image
=> Small ios things for vrs

src/lib/Components/FancyModal/FancyModalContext.tsx
Follow up to #3670 which introduced another different minor layout issue. #trivial gonna self-merge #didaproperqathistime
=> Fix fancy modal cleanup logic

.circleci/config.yml
Reverts artsy/eigen#3679
We should be good to use the horizon block again https://artsy.slack.com/archives/CP9P4KR35/p1596571131291800?thread_ts=1596570219.288400&cid=CP9P4KR35
=> Revert "Remove horizon block check for now #trivial"

dangerfile.ts, docs/map_to_the_app.md
This adds new Danger rules to make sure we don't introduce new unit tests with Enzyme or `renderRelayTree`.
=> Adds Danger rules for unit testing best practices

CHANGELOG.yml, src/lib/Scenes/Home/Components/HomeHero.tsx
This PR resolves **[MX-405]**
[MX-405]: https://artsyproduct.atlassian.net/browse/MX-405
=> Use consistent max-width on HomeHero iPad

Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m, src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx, src/lib/Scenes/ArtistSeries/ArtistSeriesHeader.tsx, src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
The type of this PR is: **Bugfix** (← I'm guessing, since I don't see a better fit for a Q/A ticket like this)
This PR resolves **https://artsyproduct.atlassian.net/browse/FX-2109**
This is a grab bag of visual Q/A fixes for the Artist Series view
n/a, style changes only
#trivial
=> [FX-2109] Artist Series QA

CHANGELOG.yml, src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx, src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx, src/lib/Components/Inbox/Conversations/Conversations.tsx, src/lib/Components/Inbox/Conversations/Messages.tsx, src/lib/Containers/Gene.tsx, src/lib/Containers/WorksForYou.tsx, src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx, src/lib/Scenes/City/CityBMWList.tsx, src/lib/Scenes/City/CityFairList.tsx, src/lib/Scenes/City/CitySavedList.tsx, src/lib/Scenes/City/CitySectionList.tsx, src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx, src/lib/Scenes/Fair/Screens/FairArtists.tsx, src/lib/Scenes/Fair/Screens/FairDetail.tsx, src/lib/Scenes/Favorites/FavoriteArtists.tsx, src/lib/Scenes/Favorites/FavoriteArtworks.tsx, src/lib/Scenes/Favorites/FavoriteCategories.tsx, src/lib/Scenes/Favorites/FavoriteShows.tsx, src/lib/Scenes/MyProfile/MyProfilePayment.tsx, src/lib/Scenes/Partner/Components/PartnerArtwork.tsx, src/lib/Scenes/Partner/Components/PartnerOverview.tsx, src/lib/Scenes/Partner/Components/PartnerShows.tsx, src/lib/Scenes/Partner/Components/PartnerShowsRail.tsx, src/lib/Scenes/Partner/Screens/PartnerLocations.tsx, src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx, src/lib/Scenes/Search/AutosuggestResults.tsx
The type of this PR is: **DX enhancement**
See this blog post PR: https://github.com/artsy/artsy.github.io/pull/622
I've smoke tested everything in the app in the simulator, but we'll need to be thorough about testing these views in the beta as well.
=> Cleans up uses of createPaginationContainer

CHANGELOG.yml, src/__generated__/PartnerOverviewInfiniteScrollQuery.graphql.ts, src/__generated__/PartnerOverviewTestsQuery.graphql.ts, src/__generated__/PartnerOverview_partner.graphql.ts, src/__generated__/PartnerQuery.graphql.ts, src/__generated__/PartnerRefetchQuery.graphql.ts, src/lib/Scenes/Partner/Components/PartnerOverview.tsx, src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
This PR resolves [MX-481]
Hide artists with 0 published works on the gallery page
**Before** 
**After**
[MX-481]: https://artsyproduct.atlassian.net/browse/MX-481
=> [MX-481] Hide artists with no published works

src/lib/Scenes/Home/Components/FairsRail.tsx
This PR resolves [MX-483]
Update `Featured Fairs` to use sentence case
#trivial 
[MX-483]: https://artsyproduct.atlassian.net/browse/MX-483
=> [MX-483] Use sentence case for feature fairs

src/lib/Components/Gene/About.tsx, src/lib/Components/Gene/Biography.tsx
This PR resolves [MX-426]
Please check this for more details: https://artsyproduct.atlassian.net/browse/MX-426?focusedCommentId=30817
Updated type on about screen on gene to match the rest of the gene screen
[MX-426]: https://artsyproduct.atlassian.net/browse/MX-426
#trivial
=> updated type on about screen on gene

src/lib/Scenes/Consignments/v2/SellTabApp.tsx, src/lib/Scenes/Favorites/FavoriteArtists.tsx, src/lib/Scenes/Favorites/FavoriteArtworks.tsx, src/lib/Scenes/Favorites/FavoriteCategories.tsx, src/lib/Scenes/Favorites/FavoriteShows.tsx, src/lib/Scenes/ViewingRoom/ViewingRoom.tsx, src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
The type of this PR is: **bugfixes**
Bugs listed here: https://www.notion.so/artsy/78dc5b152c5c4015bb7777be61b92a32?v=4fcbc6ab83d9406b8404aa63a51cfa42
Mobbed on these in MX Knowledge Share this morning.
- I haven't, but all the changes are pretty minor.
=> Fixes UI bugs found in QA #trivial

CHANGELOG.yml, src/__generated__/PartnerOverviewInfiniteScrollQuery.graphql.ts, src/__generated__/PartnerOverviewTestsQuery.graphql.ts, src/__generated__/PartnerOverview_partner.graphql.ts, src/__generated__/PartnerQuery.graphql.ts, src/__generated__/PartnerRefetchQuery.graphql.ts, src/__generated__/PartnerShowsInfiniteScrollGridQuery.graphql.ts, src/__generated__/PartnerShowsRailQuery.graphql.ts, src/__generated__/PartnerShowsRail_partner.graphql.ts, src/__generated__/PartnerShowsTestsQuery.graphql.ts, src/__generated__/PartnerShows_partner.graphql.ts, src/lib/Scenes/Partner/Components/PartnerOverview.tsx, src/lib/Scenes/Partner/Components/PartnerShows.tsx, src/lib/Scenes/Partner/Components/PartnerShowsRail.tsx, src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx, src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
This PR resolves [MX-507] & [MX-508]
This Fixes a couple of problems reported on slack today. One is quite serious (partner shows not appearing in the app) while the other is superficial (counting the number of artists represented by the gallery incorrectly).
We've decided to re-do the beta->qa->submission process to release these changes asap rather than as part of the next release cycle in 2 weeks. @ashfurrow do you mind taking point on that?
[MX-507]: https://artsyproduct.atlassian.net/browse/MX-507
[MX-508]: https://artsyproduct.atlassian.net/browse/MX-508
=> Fix partner rendering

README.md, docs/thanks.md
The type of this PR is: **documentation**
I was reading the README and noticed some outdated sections, which I updated. I also updated `thanks.md` to reflect Pavlos' contributions 🎉
=> Updates some docs #rivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
The type of this PR is: **version bump**
Preparing for 6.6.2 development, following [the instructions in our docs folder](https://github.com/artsy/eigen/blob/master/docs/deploy_to_app_store.md#prepare-for-the-next-release).
=> Prepares for 6.6.2 development.

src/__generated__/MyCollectionArtworkDetailQuery.graphql.ts, src/__generated__/MyCollectionArtworkListItem_artwork.graphql.ts, src/__generated__/MyCollectionArtworkListQuery.graphql.ts, src/lib/AppRegistry.tsx, src/lib/Scenes/Consignments/v2/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx, src/lib/Scenes/Consignments/v2/Screens/ArtworkList/MyCollectionArtworkList.tsx, src/lib/Scenes/Consignments/v2/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
The type of this PR is: Enhancement 
This PR wires up basic My Collection graphql calls (list view, detail view). Still quite a bit of mock data in place, but this is a good building block.
#trivial
=> [MyCollection] Wire up basic MP queries

README.md
Removes references to cocoapods-keys in README and adds aws-cli prerequisite which we use to get ENV variables.
=> Update readme for react-native-config setup #trivial

tsconfig.json
This brings `yarn tsc` down to about 3-5 seconds on my machine 🎉
=> Enable TS incremental mode

CHANGELOG.yml, patches/react-native+0.62.1.patch, src/lib/AppRegistry.tsx, src/lib/Containers/RegistrationFlow.tsx
This fixes two things that were broken by #3714 
- Touch handling in old Consignments + Inquiry + BidFlow/RegistrationFlow views was accidentally disabled.
- Bottom safe area was not being given to old Consignments + Inquiry + BidFlow. I had given it to RegistrationFlow but not the others.
also I had forgotten to add a changelog entry for #3714 😬
=> Fix modally-presented RN views

Artsy/App/ARAppDelegate+Emission.m, Artsy/App/AROptions.h, Artsy/App/AROptions.m, Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m, CHANGELOG.yml, src/lib/Scenes/Artwork/Components/CommercialInformation.tsx, src/lib/store/NativeModel.ts, src/setupJest.ts
[PURCHASE-2087]
Creates Lab Option to develop new inquiry UI features while supporting the current implementation. See documentation in eigen for creating a new lab option.
First time adding a lab option in Eigen, so I'm not sure if I added everything I needed to add, also unsure if I may have added lines that were unnecessary.
[PURCHASE-2087]: https://artsyproduct.atlassian.net/browse/PURCHASE-2087
=> Create Lab Option to develop new inquiry UI features

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
The type of this PR is: **prep**
This updates the changelog and version number (`make next`).
=> Prepares for 6.6.3 development

CHANGELOG.yml, src/lib/AppRegistry.tsx
This is some groundwork for #3771 
I want to update how the top-level app modules are registered so that we can use the module names as a type in the upcoming route definitions.
Doing this now to avoid conflicts down the line.
=> Typeable app module definitions

src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
The type of this PR is: **TEMP**
This PR comments out current TBD sections so that we can get a better idea of what is in place work-wise on (specifically) the detail page of My Collections. 
#trivial
=> [MyCollection] Comment out TBD sections

HACKS.md, package.json, yarn.lock
This PR resolves [MX-438]
We had 4 resolutions. 3 were some `@types/*` thing, and we had them in the devdeps anyway, so I removed them.
The last one is cheerio and I looked around and documented it in `HACKS.md`.
Lastly I also added a little comment in resolutions so we remember to write things down next time.
[MX-438]: https://artsyproduct.atlassian.net/browse/MX-438
=> Resolutions

CHANGELOG.yml, fastlane/Fastfile
This PR resolves [MX-502]
I just set `add_id_info_uses_idfa` to `false`.
In the ticket there was a link to the line with `export_compliance_available_on_french_store`, I'm not sure if that was by mistake or if we need to toggle that too.
Also, I'll try to make a build locally and run fastlane to upload the build to see if it worked of if there was any complaint. I guess we can also check it after merging with the nightly?
[MX-502]: https://artsyproduct.atlassian.net/browse/MX-502
=> IDFA toggle

src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx, src/lib/utils/__tests__/getUrgencytag-tests.ts, src/lib/utils/getUrgencyTag.ts
This PR resolves QA comments on [MX-482] and [MX-332]
Fix QA Comments By Sam
[MX-482]: https://artsyproduct.atlassian.net/browse/MX-482
[MX-332]: https://artsyproduct.atlassian.net/browse/MX-332
=> Fix auction tiles layout

docs/thanks.md
The `thanks.md` doc is where we thank contributors with over a hundred commits in Eigen for their work on the app. Thank you to @damassi and @mdole 🎉 
This PR will also be used to test https://github.com/artsy/peril-settings/pull/161
=> Adds contributors to the thanks doc

src/palette/platform/primitives.ts
This PR resolves [MX-]
These are not used anywhere for eigen, and removing them helps with the autoimport of `Text`.
#trivial
=> tiny palette cleanup, removing names for primitives

src/__generated__/MyCollectionArtworkListItem_artwork.graphql.ts, src/__generated__/MyCollectionArtworkListQuery.graphql.ts, src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx, src/lib/Scenes/MyCollection/utils/formatArtworkMedium.ts
This PR resolves [CSGN-373](https://artsyproduct.atlassian.net/browse/CSGN-373)
Before:
After:
#trivial
Updates the My Collection view to reflect latest design specifications.
=> [Consignments] Updates layout on My Collection Insights view

src/__generated__/SaleHeaderTestsQuery.graphql.ts, src/__generated__/SaleHeader_sale.graphql.ts, src/__generated__/Sale_sale.graphql.ts, src/lib/Scenes/Sale/Components/SaleHeader.tsx, src/lib/Scenes/Sale/Sale.tsx, src/lib/Scenes/Sale/__tests__/SaleHeader-tests.tsx
=> refactor: sale header

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml, fastlane/metadata/en-US/release_notes.txt
The type of this PR is: **Release**
- Updates changelog
- Updates version numbers
- Updates release notes with last release notes
**Question:** Do we have a preference on where to initially commit release notes changes? Should they be committed on tag of released version and then cherry-picked here?
=> Preparing for development, version 6.6.4

Artsy.xcodeproj/project.pbxproj
The type of this PR is: **Cleanup**
#trivial 
This PR resolves [MX-]
I saw this file was just hanging around in Xcode, being red in the navigator. I didn't see it imported in any file, so I just removed it from the project.
=> remove Constants.h ref

Artsy/Networking/API_Modules/ARUserManager.h, Artsy/Networking/API_Modules/ARUserManager.m, Artsy/Networking/ARRouter.h, Artsy/Networking/ARRouter.m, Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m, Artsy_Tests/Networking_Tests/API_Modules/ARUserManagerTests.m, Artsy_Tests/Stubs/ARUserManager+Stubs.m, CHANGELOG.yml
This PR resolves [MX-543]
See slack thread for context: https://artsy.slack.com/archives/CN8S32FJR/p1599838945258600
[MX-543]: https://artsyproduct.atlassian.net/browse/MX-543
=> [MX-543] - Send id token from apple sign in

src/lib/Scenes/Sale/Components/SaleArtworksRail.tsx, src/lib/Scenes/Sale/Sale.tsx
This PR resolves [MX-539]
#trivial 
Added navigation. No analytics event was there in the native part of that tile in the old style of the list.
[MX-539]: https://artsyproduct.atlassian.net/browse/MX-539
=> Handle auction lot artwork onPress

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
The type of this PR is: **Prep**
This updates the changelog and version number (`make next`).
=> Preparing for development, version 6.6.5.

Makefile
This updates our `make flip_table` command to explictly update echo as well.
=> Update flip_table to include echo update

CHANGELOG.yml, src/__generated__/Fair2EditorialTestsQuery.graphql.ts, src/__generated__/Fair2Editorial_fair.graphql.ts, src/__generated__/Fair2Query.graphql.ts, src/__generated__/Fair2TestsQuery.graphql.ts, src/__generated__/Fair2_fair.graphql.ts, src/lib/Scenes/Fair2/Components/Fair2Editorial.tsx, src/lib/Scenes/Fair2/Fair2.tsx, src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx, src/lib/Scenes/Fair2/__tests__/Fair2Editorial-tests.tsx
This PR resolves [FX-2210]
User can see up to 5 articles associated with the fair
[FX-2210]: https://artsyproduct.atlassian.net/browse/FX-2210
=> [FX-2210] Implements fair editorial display

src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
This PR removes unnecessary refs from the artist article and artist auction Switchboard links on My Collection components. They were throwing a `function components cannot be given refs` warning.
#trivial 
=> [My Collection]  Removes unnecessary refs from my collection Switchboard links

src/__generated__/Fair2Query.graphql.ts, src/__generated__/Fair2TestsQuery.graphql.ts, src/__generated__/Fair2_fair.graphql.ts, src/lib/Scenes/Fair2/Fair2.tsx
Just picking up from a comment in https://github.com/artsy/eigen/pull/3914 — we do need to conditionally insert or not if we're using the separator. Also just removed the slightly awkward switch statement — I dunno if I'm breaking any laws here 👮 .
=> Refactors conditional section display #trivial

src/__generated__/MyCollectionArtworkModelCreateArtworkMutation.graphql.ts, src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AdditionalDetails.tsx, src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx, src/lib/Scenes/MyCollection/utils/__tests__/cleanArtworkPayload-tests.ts, src/lib/Scenes/MyCollection/utils/cleanArtworkPayload.ts
This fixes an issue where we were sending falsy values to MP, leading to failures in create / edit, and also automates a lot of the manual update [documented here](https://github.com/artsy/eigen/pull/3896#discussion_r493188885).
#trivial
=> [MyCollection] Fix invalid payload

CHANGELOG.yml, src/__generated__/MyAccountTestsQuery.graphql.ts, src/lib/Scenes/MyAccount/MyAccount.tsx, src/lib/Scenes/MyAccount/__tests__/MyAccount-tests.tsx, src/lib/Scenes/MyProfile/Components/MyProfileMenuItem.tsx
This PR resolves [MX-538]
We will add ellipsis at the middle of a long email.
I tried adding tests for it but I couldnt find a way to test the truncated string 😬.
[MX-538]: https://artsyproduct.atlassian.net/browse/MX-538
=> fix(profile): long email truncate 🙄

Artsy/App/ARAppDelegate+Echo.m, Artsy/App/ARAppDelegate.h, Artsy/App/ARScreenPresenterModule.h, Artsy/App/ARScreenPresenterModule.m
The type of this PR is: **Followup**
This is PR follow up from #3771. Self-assigning because it's #trivial and because I didn't want to block the (extensive) PR from getting merged. /cc @ds300 
=> Code cleanup from #3771.

CHANGELOG.yml, src/__generated__/Fair2CollectionsTestsQuery.graphql.ts, src/__generated__/Fair2Collections_fair.graphql.ts, src/__generated__/Fair2Query.graphql.ts, src/__generated__/Fair2TestsQuery.graphql.ts, src/__generated__/Fair2_fair.graphql.ts, src/lib/Scenes/Fair2/Components/Fair2Collections.tsx, src/lib/Scenes/Fair2/Fair2.tsx, src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx, src/lib/Scenes/Fair2/__tests__/Fair2Collections-tests.tsx, src/palette/elements/Cards/SmallCard.tsx, src/palette/elements/Touchable/TouchableWithScale.tsx, src/palette/elements/Touchable/index.tsx
This PR resolves [FX-221]
[FX-221]: https://artsyproduct.atlassian.net/browse/FX-221
=> [FX-2211] Fair collections rail

Podfile.lock
The type of this PR is: **upkeep**
The marketing team is having trouble tracking opens from pushes from ST and ST has asked that we update to the latest version of their SDK.
=> Updates SailThru SDK #trivial

src/__generated__/SaleArtworkListItem_artwork.graphql.ts, src/__generated__/SaleArtworkListQuery.graphql.ts, src/__generated__/SaleLotsListTestsQuery.graphql.ts, src/__generated__/SaleQueryRendererQuery.graphql.ts, src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx, src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx, src/lib/Components/ArtworkGrids/__tests__/ArtworkGridItem-tests.tsx, src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx, src/lib/Scenes/Sale/Components/SaleArtworkListItem.tsx, src/lib/Scenes/Sale/Components/SaleLotsList.tsx, src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx
This PR resolves layout issues reported by sam here [MX-515](https://artsyproduct.atlassian.net/browse/MX-515), here [MX-517](https://artsyproduct.atlassian.net/browse/MX-517) and here [MX-519](https://artsyproduct.atlassian.net/browse/MX-519)
**Hide Patner Name**
**Remove Upper case from lot label**
**Dynamically adjust aspect ratio**
#trivial
=> fix: various auctions UI fixes

Podfile, Podfile.lock
The type of this PR is: UPKEEP
This PR resolves [MX-]
=> chore: update podfile #trivial

HACKS.md, Podfile, Podfile.lock
The type of this PR is: **upkeep**
This resolves a hack introduced in #3938.
=> chore: update TOCropViewController to resolve hack #trivial

CHANGELOG.yml, src/__generated__/ArtworkTileRailCard_artwork.graphql.ts, src/__generated__/Fair2FollowedArtists_fair.graphql.ts, src/__generated__/Fair2Query.graphql.ts, src/__generated__/Fair2TestsQuery.graphql.ts, src/__generated__/Fair2_fair.graphql.ts, src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx, src/lib/Scenes/Fair2/Components/Fair2FollowedArtists.tsx, src/lib/Scenes/Fair2/Fair2.tsx, src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
This PR resolves [FX-2212]
[FX-2212]: https://artsyproduct.atlassian.net/browse/FX-2212
=> feat: followed artist artworks rail

CHANGELOG.yml, src/__generated__/ViewingRoomQuery.graphql.ts, src/__generated__/ViewingRoomTestsQuery.graphql.ts, src/__generated__/ViewingRoom_viewingRoom.graphql.ts, src/lib/Scenes/ViewingRoom/ViewingRoom.tsx, src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx
This PR resolves [GALL-3221](https://artsyproduct.atlassian.net/browse/GALL-3221)
This PR adds a share button to viewing rooms. See screenshots for examples!
<details>
<summary>Screenshot: iPhone 8</summary>
</details>
<details>
<summary>Screenshot: iPhone 11 pro</summary>
</details>
<details>
<summary>Screenshot: iPad Pro 3</summary>
</details>
<details>
<summary>Screenshot: share menu</summary>
</details>
<details>
<summary>Screenshot: tracking (cc @louislecluse)</summary>
</details>
=> feat: share button in viewing rooms [GALL-3221]

src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
Note: This PR relies on artsy/metaphysics#2742 and the update to the schema that it adds.
The purpose of this PR is to begin supporting the uploading of My Collection artwork images. I worked down the stack to support this behavior so it is now possible. For the UX in the app I did the dumbest thing possible: block sending the mutation until all the photos have been uploaded and don't start uploading until the "Create" button is pressed.
This is almost certainly NOT what we'll end up shipping to end users, but it's a start! And it moves us from zero support for images to one that is naive but possible. I hope to demonstrate how this works today and then get feedback and improve things.
https://artsyproduct.atlassian.net/browse/CSGN-356
=> CSGN-356: Upload photos to S3 and pass off urls to MP

docs/pull_request_template.md
I know this is a silly title but hey :D, we have fun!
=> perf(DX): Improve developer speed by not needed to change the PR template

src/__generated__/MyCollectionArtworkModelCreateArtworkMutation.graphql.ts, src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx, src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx, src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx, tslint.json
This fixes an issue where MyCollections would crash after creating a new item and clicking it in the list view. Why it would only crash on a device is a bit of a mystery, but it should have crashed everywhere! 
#trivial
=> Bugfix: [MyCollection] Fixes crash when navigating to newly-created work

src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
Fixes a My Collection crash when navigating to "All Auctions" or "All Articles" or a specific article. On device, it triggers a race condition in the store. Not sure if its related to new `navigate` function interfacing with global store in some way, or something else. Adding a `setImmediate` fixes the problem. 
#trivial
=> Bugfix: Fix crash on navigate to articles / auctions

src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts, src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts, src/__generated__/InquiryModal_artwork.graphql.ts, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/__fixtures__/ArtworkFixture.ts
This PR resolves [PURCHASE-2096](https://artsyproduct.atlassian.net/browse/PURCHASE-2096)
Adds modal navigation questions to serve as entry points for the shipping, condition, and price inquiry flows.
=> [PURCHASE] Add inquiry questions to inquiry modal flow

src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts, src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts, src/__generated__/InquiryModal_artwork.graphql.ts, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/__fixtures__/ArtworkFixture.ts
=> Revert "[PURCHASE] Add inquiry questions to inquiry modal flow"

src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts, src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts, src/__generated__/InquiryModal_artwork.graphql.ts, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/__fixtures__/ArtworkFixture.ts
=> Revert "Add inquiry questions to inquiry modal flow"

package.json
I just saw it and thought I'll update it.
=> fix: updated the repo's description

src/lib/Components/Inbox/Conversations/Message.tsx, src/lib/Components/Inbox/Conversations/Messages.tsx
This PR resolves [PURCHASE-2156][PURCHASE-2157]
This PR fixes issues in layout when paginating a conversation. Bugs discovered after Purchase QA.
1-Fixes issue of messages sometimes disappearing on pagination.
2-Fixes flat-list top-margin/wrong layout.
3-Fixes issue of keyboard blocking last message if its a long message.
4-Fixes crash caused by image attachments resizing on pagination.
There's one QA bug which wasn't reproducible which for one person caused the whole screen to flicker. There will be QA conducted to make sure it's not happening any more.
[PURCHASE-2156]: https://artsyproduct.atlassian.net/browse/PURCHASE-2156
[PURCHASE-2157]: https://artsyproduct.atlassian.net/browse/PURCHASE-2157
=> fix: conversation pagination layout fixes #trivial

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Preparing for 6.6.6 development work.
=> Prepare for 6.6.6 release

CHANGELOG.yml, src/__generated__/Show2Header_show.graphql.ts, src/__generated__/Show2Query.graphql.ts, src/__generated__/Show2TestsQuery.graphql.ts, src/__generated__/Show2_show.graphql.ts, src/lib/Components/Countdown/Ticker.tsx, src/lib/Scenes/Show2/Components/Show2Header.tsx, src/lib/Scenes/Show2/Show2.tsx, src/lib/Scenes/Show2/__tests__/Show2-tests.tsx, src/lib/utils/__tests__/useEventTiming-tests.tsx, src/lib/utils/useEventTiming.tsx
This PR resolves [FX-2221]
[FX-2221]: https://artsyproduct.atlassian.net/browse/FX-2221
=> feat(show2): implements show2 header

src/lib/Components/EventTiming.tsx
The type of this PR is: Refactor
Refactors existing `EventTiming` component to utilize `useEventTiming` hook
=> refactor(eventtiming): refactors to use useeventtiming hook

src/__generated__/Fair2CollectionsTestsQuery.graphql.ts, src/__generated__/Fair2EditorialTestsQuery.graphql.ts, src/__generated__/Fair2ExhibitorRailTestsQuery.graphql.ts, src/__generated__/Fair2MoreInfoTestsQuery.graphql.ts, src/lib/Scenes/Fair2/__tests__/Fair2Collections-tests.tsx, src/lib/Scenes/Fair2/__tests__/Fair2Editorial-tests.tsx, src/lib/Scenes/Fair2/__tests__/Fair2ExhibitorRail-tests.tsx, src/lib/Scenes/Fair2/__tests__/Fair2MoreInfo-tests.tsx
The type of this PR is: *Enhancement**?
Updates the remaining Fair2 tests to use the new automatically generated mock payload pattern.
=> chore: Update remaining Fair2 tests to use new testing pattern

docs/deploy_to_app_store.md
While pairing with @brainbicycle on submitting a hotfix to Apple, I picked up on a couple things we did that weren't documented. This PR adds them to the docs.
=> Add more details to deploy_to_app_store.md

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Updates plist and changelog for new release.
=> Prepares for 6.6.7 development

src/lib/Scenes/Fair2/Components/Fair2Editorial.tsx
This PR resolves [FX-2376]
Trivial text changes
[FX-2376]: https://artsyproduct.atlassian.net/browse/FX-2376
[FX-2376]: https://artsyproduct.atlassian.net/browse/FX-2376
=> fix: update label for fair editorial sections

CHANGELOG.yml, src/__generated__/Show2ContextCardTestsQuery.graphql.ts, src/__generated__/Show2ContextCard_show.graphql.ts, src/__generated__/Show2Query.graphql.ts, src/__generated__/Show2_show.graphql.ts, src/lib/Components/SectionTitle.tsx, src/lib/Scenes/Show2/Components/Show2ContextCard.tsx, src/lib/Scenes/Show2/Show2.tsx, src/lib/Scenes/Show2/__tests__/Show2-tests.tsx, src/lib/Scenes/Show2/__tests__/Show2ContextCard-tests.tsx, src/palette/elements/Cards/SmallCard.tsx
This PR resolves [FX-2227]
(These screenshots cheat a bit by hiding everything except the `Show2Header` and the `Show2ContextCard`. This was in lieu of setting up the whole scrollable sections `FlatList` stuff, which could be a separate PR)
|Mobile Partner Show|Mobile Fair Booth|
|---|---|
|<img width="300" src="https://user-images.githubusercontent.com/140521/96207241-bd183e80-0f38-11eb-90a5-2f6413178933.png">|<img width="300" alt="mf2" src="https://user-images.githubusercontent.com/140521/96207711-dc639b80-0f39-11eb-8dbd-c74a2a9c1aff.png">|
There's no specific spec for tablet sizes. But this is how it looks by default 🤷 
|Tablet Partner Show|Tablet Fair Booth|
|---|---|
|<img width ="400" src="https://user-images.githubusercontent.com/140521/96207244-b …
=> feat(show2): add a context card

src/lib/Components/AnimatedBottomButton.tsx, src/lib/Components/FilterModal/FilterModal.tsx, src/lib/Components/FilterModal/__tests__/FilterModal-tests.tsx, src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomViewWorksButton-tests.tsx
This PR resolves [CX-730]
- Update copy from “Filter” to “Sort & Filter”
- Add hover state by lightening background color opacity from 100% to 80%
- Please use **Merge Pull Request** instead of **Squash Pull Request** since issues raised in this PR are separate.
___
[CX-730]: https://artsyproduct.atlassian.net/browse/CX-730
=> fix: update copy on filter button

src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts, src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts, src/__generated__/InquiryModalTestsQuery.graphql.ts, src/__generated__/InquiryModal_artwork.graphql.ts, src/lib/Scenes/Artwork/Artwork.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/helpers.ts, src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx, src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
This PR follows up on some of the first inquiry work to make some minor updates.
There's only a few things here:
1. Moves the state provider down to be closer to it's usage in the tree
2.
=> enhancement: follow up on first inquiry functionality

CHANGELOG.yml, src/__generated__/SaleQueryRendererQuery.graphql.ts, src/__generated__/SaleTestsQuery.graphql.ts, src/lib/Scenes/Sale/Components/SaleHeader.tsx, src/lib/Scenes/Sale/Sale.tsx, src/lib/Scenes/Sale/__tests__/Sale-tests.tsx, src/lib/Scenes/Sale/helpers/__tests__/auctionTime-tests.ts, src/lib/Scenes/Sale/helpers/saleTime.ts, src/lib/utils/usePrevious.ts
This PR resolves [CX-725], [CX-728]
This includes two fixes:
- when a closed auction is accessed, it doesn't try to go live anymore.
- when a closed auction is accessed, the register button is not displayed.
[CX-725]: https://artsyproduct.atlassian.net/browse/CX-725
[CX-728]: https://artsyproduct.atlassian.net/browse/CX-728
=> fix(auctions): Closed auctions fixes

CHANGELOG.yml, src/__generated__/RegisterToBidButtonTestsQuery.graphql.ts, src/__generated__/RegisterToBidButton_me.graphql.ts, src/__generated__/SaleActiveBidItemTestsQuery.graphql.ts, src/__generated__/SaleActiveBidItem_lotStanding.graphql.ts, src/__generated__/SaleActiveBidsTestsQuery.graphql.ts, src/__generated__/SaleActiveBids_me.graphql.ts, src/__generated__/SaleQueryRendererQuery.graphql.ts, src/__generated__/SaleTestsQuery.graphql.ts, src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx, src/lib/Scenes/Sale/Components/SaleActiveBidItem.tsx, src/lib/Scenes/Sale/Components/SaleActiveBids.tsx, src/lib/Scenes/Sale/Components/SaleArtworksRail.tsx, src/lib/Scenes/Sale/Sale.tsx, src/lib/Scenes/Sale/__tests__/RegisterToBidButton-tests.tsx, src/lib/Scenes/Sale/__tests__/Sale-tests.tsx, src/lib/Scenes/Sale/__tests__/SaleActiveBidItem-tests.tsx, src/lib/Scenes/Sale/__tests__/SaleActiveBids-tests.tsx
This PR resolves [CX-559]
- Add your active bids to new auction sale page
- I had to create a new component for the `SaleActiveBids` since the existing one expects very different inputs.
[CX-559]: https://artsyproduct.atlassian.net/browse/CX-559
=> feat: add active bids to new auctions

CHANGELOG.yml, src/__generated__/DetailTestsQuery.graphql.ts, src/__generated__/Detail_show.graphql.ts, src/__generated__/Fair2MoreInfoQuery.graphql.ts, src/__generated__/Fair2MoreInfoTestsQuery.graphql.ts, src/__generated__/FairDetailShowsQuery.graphql.ts, src/__generated__/FairDetail_fair.graphql.ts, src/__generated__/FairQuery.graphql.ts, src/__generated__/HoursCollapsible_location.graphql.ts, src/__generated__/LocationMap_location.graphql.ts, src/__generated__/Show2LocationTestsQuery.graphql.ts, src/__generated__/Show2Location_show.graphql.ts, src/__generated__/Show2MoreInfoTestsQuery.graphql.ts, src/__generated__/Show2MoreInfo_show.graphql.ts, src/__generated__/ShowQuery.graphql.ts, src/__generated__/ShowTestsQuery.graphql.ts, src/__generated__/VanityURLEntityQuery.graphql.ts, src/__generated__/indexTestsQuery.graphql.ts, src/lib/Components/HoursCollapsible.tsx, src/lib/Components/LocationMap/index.tsx, src/lib/Scenes/Fair/Screens/FairDetail.tsx, src/lib/Scenes/Fair2/Fair2MoreInfo.tsx, src/lib/Scenes/Show/Screens/Detail.tsx, src/lib/Scenes/Show2/Components/Show2Location.tsx, src/lib/Scenes/Show2/Screens/Show2MoreInfo.tsx, src/lib/Scenes/Show2/__tests__/Show2Location-tests.tsx
This PR resolves [FX-2367]
* Refactors some component fragment spaghetti
* Adds location map
[FX-2367]: https://artsyproduct.atlassian.net/browse/FX-2367
=> feat(fx-2367) adds show2 location map

CHANGELOG.yml, src/__generated__/Show2HoursTestsQuery.graphql.ts, src/__generated__/Show2Hours_show.graphql.ts, src/__generated__/Show2LocationHours_location.graphql.ts, src/__generated__/Show2MoreInfoQuery.graphql.ts, src/__generated__/Show2MoreInfoTestsQuery.graphql.ts, src/__generated__/Show2MoreInfo_show.graphql.ts, src/lib/Scenes/Show2/Components/Show2Hours.tsx, src/lib/Scenes/Show2/Components/Show2LocationHours.tsx, src/lib/Scenes/Show2/Screens/Show2MoreInfo.tsx, src/lib/Scenes/Show2/__tests__/Show2Hours-tests.tsx
This PR resolves [FX-2366]
[FX-2366]: https://artsyproduct.atlassian.net/browse/FX-2366
=> feat(fx-2366): displays show2 location or fair location hours

CHANGELOG.yml, src/__generated__/PartnerEntityHeaderTestsQuery.graphql.ts, src/__generated__/PartnerEntityHeader_partner.graphql.ts, src/__generated__/Show2MoreInfoQuery.graphql.ts, src/__generated__/Show2MoreInfoTestsQuery.graphql.ts, src/__generated__/Show2MoreInfo_show.graphql.ts, src/lib/Components/PartnerEntityHeader.tsx, src/lib/Components/__tests__/PartnerEntityHeader-tests.tsx, src/lib/Scenes/Show2/Screens/Show2MoreInfo.tsx, src/lib/Scenes/Show2/__tests__/Show2MoreInfo-tests.tsx, src/lib/utils/__tests__/limitWithCount-tests.tsx, src/lib/utils/limitWithCount.tsx
This PR resolves [FX-2368]
[FX-2368]: https://artsyproduct.atlassian.net/browse/FX-2368
=> feat(fx-2368): display partner entity header on show2 more info

src/__generated__/SaleArtworksRailTestsQuery.graphql.ts, src/__generated__/SaleArtworksRail_me.graphql.ts, src/__generated__/SaleQueryRendererQuery.graphql.ts, src/lib/Scenes/Sale/Components/SaleArtworksRail.tsx, src/lib/Scenes/Sale/Sale.tsx, src/lib/Scenes/Sale/__tests__/SaleArtworksRail-tests.tsx
This PR resolves [CX-515]
Add sale ID in auctions lots rail.
**PS:** Adding a screenshot here didn't feel useful
[CX-515]: https://artsyproduct.atlassian.net/browse/CX-515
=> fix: add sale ID in auctions lots rail

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Updates changelog and version numbers.
=> Prepares for 6.7.0 development

CHANGELOG.yml, src/__generated__/Show2Query.graphql.ts, src/__generated__/Show2TestsQuery.graphql.ts, src/__generated__/Show2ViewingRoomTestsQuery.graphql.ts, src/__generated__/Show2ViewingRoom_show.graphql.ts, src/__generated__/Show2_show.graphql.ts, src/lib/Scenes/Show2/Components/Show2ViewingRoom.tsx, src/lib/Scenes/Show2/Show2.tsx, src/lib/Scenes/Show2/__tests__/Show2ViewingRoom-tests.tsx, src/palette/elements/Box/Box.tsx, src/palette/elements/Cards/MediumCard.tsx
This PR resolves [FX-2224]
[FX-2224]: https://artsyproduct.atlassian.net/browse/FX-2224
=> feat(fx-2224) show2 viewing room

src/lib/Components/ArtworkFilterOptions/SortOptions.tsx, src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx, src/lib/utils/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
This PR resolves [CX-760]
For sort by, remove the "default" option – we should show that we're already sorting by lot number ascending
[CX-760]: https://artsyproduct.atlassian.net/browse/CX-760
=> fix(SortOptions): auctions sort default options remove

Podfile.lock, package.json, src/__generated__/Show2ContextCardTestsQuery.graphql.ts, src/__generated__/Show2ContextCard_show.graphql.ts, src/__generated__/Show2Query.graphql.ts, src/__generated__/Show2TestsQuery.graphql.ts, src/__generated__/Show2ViewingRoomTestsQuery.graphql.ts, src/__generated__/Show2ViewingRoom_show.graphql.ts, src/lib/Scenes/Show2/Components/Show2Artworks.tsx, src/lib/Scenes/Show2/Components/Show2ContextCard.tsx, src/lib/Scenes/Show2/Components/Show2ViewingRoom.tsx, src/lib/Scenes/Show2/__tests__/Show2ContextCard-tests.tsx, src/lib/Scenes/Show2/__tests__/Show2ViewingRoom-tests.tsx, yarn.lock
This PR resolves [FX-2364]
I'm a bit unclear about how screen (page-view) tracking works in Eigen, so any tips in that direction? Can be a separate ticket/PR however if there's something to pick up there.
[FX-2364]: https://artsyproduct.atlassian.net/browse/FX-2364
=> feat(fx-2364) show2 tap tracking

CHANGELOG.yml, src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts, src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts, src/__generated__/InquiryModalTestsQuery.graphql.ts, src/__generated__/InquiryModal_artwork.graphql.ts, src/__generated__/SubmitInquiryRequestMutation.graphql.ts, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx, src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts, src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx, src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts, src/lib/utils/ArtworkInquiry/__tests__/ArtworkInquiryStore-tests.tsx
This PR resolves [PURCHASE-2098]
This PR addresses the following:
- Wiring up state for the checkbox inquiry questions.
- Creates a `SubmitInquiryMutation` and hooks that up to the send link.
**POST request body:**
**Response**
[PURCHASE-2098]: https://artsyproduct.atlassian.net/browse/PURCHASE-2098
=> feat: submit inquiry request

src/__generated__/Show2InstallShots_show.graphql.ts, src/__generated__/Show2Query.graphql.ts, src/__generated__/Show2TestsQuery.graphql.ts, src/__generated__/Show2_show.graphql.ts, src/lib/Scenes/Show2/Components/Show2InstallShots.tsx, src/lib/Scenes/Show2/Show2.tsx
This PR resolves [FX-2407]
[FX-2407]: https://artsyproduct.atlassian.net/browse/FX-2407
=> fix(fx-2407): adjusts show2 install shots query #trivial

src/lib/Scenes/SaleInfo/SaleInfo.tsx, src/lib/Scenes/SaleInfo/__tests__/SaleInfo-tests.tsx
This PR resolves [CX-767]
- [ x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.
[CX-767]: https://artsyproduct.atlassian.net/browse/CX-767
=> fix(auction): hide register to bid button on closed auctions #trivial

src/lib/Components/Buttons/CaretButton.tsx, src/lib/Components/Buttons/__tests__/CaretButton-tests.tsx, src/lib/Scenes/Sale/Components/SaleHeader.tsx
This PR resolves [CX-795]
- Add feedback to more info about this auction
___
**before**
**after**
[CX-795]: https://artsyproduct.atlassian.net/browse/CX-795
=> fix: add feedback to more info about this auction

src/lib/Scenes/SaleFAQ/SaleFAQ.tsx, src/lib/Scenes/SaleFAQ/__tests__/SaleFAQ-tests.tsx, src/lib/Scenes/SaleInfo/SaleInfo.tsx
This PR resolves [CX-799]
Fix sale info bugs
- Add 30px padding bottom
- Adjust hover time when scrolling paragraphs (I adjusted the panresponder)
- Add Auctions FAQ padding
[CX-799]: https://artsyproduct.atlassian.net/browse/CX-799
=> fix: fix sale info bugs

Artsy/App/AROptions.m
This PR resolves [FX-2432]
[FX-2432]: https://artsyproduct.atlassian.net/browse/FX-2432
=> chore: remove show2 lab option in favor of using Echo

Artsy/App/AROptions.m, Artsy/App/ARScreenPresenterModule.m
Co-authored-by: Brian Beckerle <brian.beckerle@artsymail.com>
- Migrate AROptionsNewSalePage to echo
- Tested this locally after echo production deployment and it's working fine.
=> chore: migrate AROptionsNewSalePage to echo

src/__generated__/SaleInfoQueryRendererQuery.graphql.ts, src/__generated__/SaleInfoTestsQuery.graphql.ts, src/__generated__/SaleInfo_sale.graphql.ts, src/lib/Scenes/SaleInfo/SaleInfo.tsx, src/lib/Scenes/SaleInfo/__tests__/SaleInfo-tests.tsx
paired with @pepopowitz 
This PR resolves [CX-745]
Adds display of buyers premium to the **About this auction** page.
---
[CX-745]: https://artsyproduct.atlassian.net/browse/CX-745
=> fix: Add buyers premium to sale info page

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
The type of this PR is: **test**
This PR resolves [PURCHASE-2219] 
This PR adds a test for the inquiry questions checkbox and serves as an example testing this functionality.
[PURCHASE-2219]: https://artsyproduct.atlassian.net/browse/PURCHASE-2219
=> test: checkbox functionality

Artsy/App/ArtsyEcho.m, Artsy/View_Controllers/Admin/AREchoContentsViewController.m, CHANGELOG.yml
This check was assuming that the `_OSS_` var will always be there when it shouldn't. This caused the app to basically never check for echo updates 😱. Now it checks as usual. 
Also in the admin menu, the "echo configuration" screen now sorts things alphabetically so we can find things more easily.
=> fix(echo): Echo config sort and only skip update if `_OSS_=true`

src/__generated__/RegisterToBidButtonTestsQuery.graphql.ts, src/__generated__/RegisterToBidButton_sale.graphql.ts, src/__generated__/SaleAboveTheFoldQuery.graphql.ts, src/__generated__/SaleInfoQueryRendererQuery.graphql.ts, src/__generated__/SaleInfoTestsQuery.graphql.ts, src/__generated__/SaleInfo_sale.graphql.ts, src/__generated__/SaleRefetchQuery.graphql.ts, src/__generated__/Sale_sale.graphql.ts, src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx, src/lib/Scenes/Sale/Sale.tsx, src/lib/Scenes/Sale/__tests__/helpers-tests.ts, src/lib/Scenes/Sale/helpers.ts, src/lib/Scenes/SaleInfo/SaleInfo.tsx
Fix missing register to bid button on sale screen when the `registrationEndAt` is available.
**Before**
**After**
=> fix: sale status on sale screen

src/__generated__/Show2MoreInfoQuery.graphql.ts, src/__generated__/Show2MoreInfoTestsQuery.graphql.ts, src/__generated__/Show2MoreInfo_show.graphql.ts, src/lib/Components/FilterModal/FilterModal.tsx, src/lib/Scenes/Show2/Screens/Show2MoreInfo.tsx, src/lib/Scenes/Show2/Show2.tsx, src/lib/utils/track/schema.ts
Addresses feedback [from spreadsheet.](https://docs.google.com/spreadsheets/d/1_VDAmRJz2K87FXDq7oh_tQSgwBv4syuZjaaR3sfetcI/edit#gid=596196548)
=> fix(show2): adds missing analytics tracking

src/lib/Components/FilterModal/FilterModal.tsx
This PR resolves [CX-808]
- Add tracking event for filtering
[CX-808]: https://artsyproduct.atlassian.net/browse/CX-808
=> chore: add filter params changed tracking event

CHANGELOG.yml, src/lib/Components/Buttons/CaretButton.tsx, src/lib/Components/Buttons/__tests__/CaretButton-tests.tsx
This PR resolves [CX-819]
- Add feedback to more info about this auction button
[CX-819]: https://artsyproduct.atlassian.net/browse/CX-819
=> fix: add feedback to more info about this auction button

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Updates changelog and version numbers.
=> Preparing for development, version 6.7.1

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
- Update changelog
- Update version number
=> Preparing for development, version 6.7.2

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx, src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts, src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx, src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts, src/lib/utils/ArtworkInquiry/__tests__/ArtworkInquiryStore-tests.tsx
This PR resolves [PURCHASE-2209]
This PR enables the user to submit a custom message through the first inquiry flow.
[PURCHASE-2209]: https://artsyproduct.atlassian.net/browse/PURCHASE-2209
=> feat: first inquiry custom message

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
This PR resolves [PURCHASE-2235]
Fixes an issue where the form wouldn't reset after submitting.
[PURCHASE-2235]: https://artsyproduct.atlassian.net/browse/PURCHASE-2235
=> fix: Form now resets on successful mutation

Artsy/App/ARSegmentProvider.m, CHANGELOG.yml
This PR resolves [CX-466]
Override segment provider method to prevent sending unnecessary properties.
[CX-466]: https://artsyproduct.atlassian.net/browse/CX-466
=> chore: don't pass email to segment #trivial

Artsy/App/ARAppNotificationsDelegate.m, CHANGELOG.yml
#4150 added logic to avoid unnecessary token updates, which are very expensive for gravity. Somehow the objective-c compiler missed a bug in the code, which only manifested when trying to ship a beta.
=> fix: device token checking

src/lib/utils/track/schema.ts
This PR resolves [FX-2510]
[FX-2510]: https://artsyproduct.atlassian.net/browse/FX-2510
=> fix(analytics): updates fair/show screen schema naming

CHANGELOG.yml, src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
This PR resolves [CX-695]
[CX-695]: https://artsyproduct.atlassian.net/browse/CX-695
=> fix: add spinner to artist artworks infinite scroll

CHANGELOG.yml, src/__generated__/ArtistShows2PastShowsQuery.graphql.ts, src/__generated__/ArtistShows2Query.graphql.ts, src/__generated__/ArtistShows2TestsQuery.graphql.ts, src/__generated__/ArtistShows2_artist.graphql.ts, src/lib/AppRegistry.tsx, src/lib/Components/Artist/ArtistShows/ArtistShow.tsx, src/lib/Components/Artist/ArtistShows/SmallList.tsx, src/lib/Scenes/ArtistShows/ArtistShows2.tsx, src/lib/Scenes/ArtistShows/__tests__/ArtistShows2-tests.tsx, src/lib/navigation/routes.tsx
This PR resolves [CX-770]
- Create past shows view
[CX-770]: https://artsyproduct.atlassian.net/browse/CX-770
=> feat: create past shows view

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
The type of this PR is: **Preparation for new Release**
Preparing for development, version **6.7.3**
=> Preparing for development, version 6.7.3

CHANGELOG.yml, data/schema.graphql, src/__generated__/ActiveLot_lotStanding.graphql.ts, src/__generated__/ClosedLot_lotStanding.graphql.ts, src/__generated__/MyBids2TestsQuery.graphql.ts, src/__generated__/MyBidsQuery.graphql.ts, src/lib/Scenes/MyBids/Components/ActiveLot.tsx, src/lib/Scenes/MyBids/Components/ClosedLot.tsx, src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx, src/lib/Scenes/MyBids/__tests__/ClosedLot-tests.tsx
This PR resolves [PURCHASE-2171] and depends on https://github.com/artsy/metaphysics/pull/2805.
Following https://github.com/artsy/metaphysics/pull/2805, this migrates `floorSellingPrice` and `onlineAskingPrice` to Metaphysics `Money` type (instead of the deprecated Causality money type).
Migration steps:
[PURCHASE-2171]: https://artsyproduct.atlassian.net/browse/PURCHASE-2171
=> fix: use MP money fields for My Bids floor selling price and online asking price (PURCHASE-2171)

Podfile.lock, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
This PR resolves [CX-850]
@ds300 and I changed the upload code to process the images one at a time, instead of doing it in parallel.
[CX-850]: https://artsyproduct.atlassian.net/browse/CX-850
=> fix(MyCollection): upload images synchronously, not async

Podfile.lock, src/lib/Scenes/MyBids/Components/ActiveLot.tsx, src/lib/Scenes/MyBids/Components/Lot.tsx, src/lib/Scenes/MyBids/Components/SaleCard.tsx, src/lib/Scenes/MyBids/MyBids.tsx, src/lib/Scenes/MyBids/helpers/screenDimensions.ts
This PR resolves [PURCHASE-2170](https://artsyproduct.atlassian.net/browse/PURCHASE-2170)
The text in the My Bids view on smaller screen iOS devices needed some UI layout tweaks to prevent text from being cramped. This PR introduces those fixes.
**On iPhone SE First Generation (small size)**
**On iPhone 12 (standard size)**
[PURCHASE-2170]: https://artsyproduct.atlassian.net/browse/PURCHASE-2170
=> [PURCH-2170] Fix My Bids text layout bugs on small screen devices

src/__generated__/InboxQuery.graphql.ts, src/__generated__/InboxRefetchQuery.graphql.ts, src/__generated__/InboxTestsQuery.graphql.ts, src/lib/Containers/__tests__/Inbox-tests.tsx
This PR resolves https://artsy.slack.com/archives/C02BAQ5K7/p1606923119080500
When merging #4154, we missed running relay compiler for a few files that caused the master CI build to fail. 
=> Bugfix: Resolve broken master build

src/lib/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
This PR resolves [PURCHASE-2252](https://artsyproduct.atlassian.net/browse/PURCHASE-2252)
Adjusts the padding and dropshadow on the inquiry message notification as a QA followup.
*After*
*Before*
=> [PURCH-2252] Fix drop shadow and padding on inquiry msg notification

src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx, src/lib/utils/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
This PR resolves [FX-2397]
[FX-2397]: https://artsyproduct.atlassian.net/browse/FX-2397
=> fix(fx-2397): changes artists filter label

src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
This PR resolves [PURCHASE-2249]
This vertically centers the chevron to the left of the 'Add your location' copy.
[PURCHASE-2249]: https://artsyproduct.atlassian.net/browse/PURCHASE-2249
=> [PURCHASE-2249] First inquiry visual qa

src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
I just realised that My Collection crashes if no images are uploaded for an artwork. This fixes that.
=> fix(my collection): crash when no images #trivial

CHANGELOG.yml, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
[PURCHASE-2276]
[PURCHASE-2276]: https://artsyproduct.atlassian.net/browse/PURCHASE-2276
=> In the inquiry modal change 'Add Message' to 'Add message'

CHANGELOG.yml, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Co-authored-by: Ashley Jelks <ashley.jelks@artsymail.com>
This PR resolves **[PURCHASE-2251](https://artsyproduct.atlassian.net/browse/PURCHASE-2251)** 
- Scroll to add message input on input focus
- Bonus (please feel free to revert): Grow inbox message input to a maximum of 200 pixels
[PURCHASE-2251]: https://artsyproduct.atlassian.net/browse/PURCHASE-2251
=> fix: scroll to add message input on input focus

Artsy/App/AROptions.m, CHANGELOG.yml
[PURCHASE-2240]
This PR removes the feature flag for the new inquiry flow, so that we can use an echo flag instead (added [here](https://github.com/artsy/echo/pull/57))
May need to hold off on merging until the echo PR is merged
[PURCHASE-2240]: https://artsyproduct.atlassian.net/browse/PURCHASE-2240
=> chore: Remove first inquiry flag

src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
This PR resolves [CX-813]
Updated copy based on spec in ticket. I confirmed with @samchieng that the ranges are still 0-9.9, and we are using purple.
Please double-check my copy changes with those in the ticket.
[CX-813]: https://artsyproduct.atlassian.net/browse/CX-813
=> chore: Update demand index copy

CHANGELOG.yml, src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/Dimensions.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
The type of this PR is: **Content updates?**
This PR resolves [CX-771]
This PR includes several minor copy changes for My Collection: 
1. Remove last sync date from auction results help: 
2. Update message when cancelling adding a work:
3. Change "Metric" field label to "Units":
4. Change add/edit modals to use Title Case: 
5. Change "Year" field label to "Year created": 
[CX-771]: https://artsyproduct.atlassian.net/browse/CX-771
=> chore(my collection): final copy changes

Podfile.lock, src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts, src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts, src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts, src/__generated__/MyCollectionArtworkQuery.graphql.ts, src/__generated__/MyCollectionArtwork_sharedProps.graphql.ts, src/__generated__/myCollectionAddArtworkMutation.graphql.ts, src/__generated__/myCollectionEditArtworkMutation.graphql.ts, src/lib/Components/TextArea.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/Scenes/Consignments/Screens/Provenance.tsx, src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx, src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx, src/lib/Scenes/MyCollection/State/__tests__/MyCollectionArtworkModel-tests.tsx
This PR resolves [CX-602]
I paired with @pepopowitz on this.
- Created a generalized `TextArea` based on the one in `InquiryModal`
- Added an input for Provenance to My Collection artwork additional details
[CX-602]: https://artsyproduct.atlassian.net/browse/CX-602
=> chore: Add provenance field to My Collection artworks

src/lib/Scenes/Consignments/Screens/Provenance.tsx
Small copy fix spotted by @admbtlr.
=> chore: small copy fix: s/had/owned #minor

src/lib/Scenes/Fair2/Fair2.tsx
This PR resolves [FX-2415]
[FX-2415]: https://artsyproduct.atlassian.net/browse/FX-2415
=> fix(fx-2415): adds footer whitespace

CHANGELOG.yml, src/__generated__/InboxQuery.graphql.ts, src/__generated__/InboxRefetchQuery.graphql.ts, src/__generated__/InboxTestsQuery.graphql.ts, src/__generated__/MyBidsPaginatedQuery.graphql.ts, src/__generated__/MyBidsQuery.graphql.ts, src/__generated__/MyBids_me.graphql.ts, src/lib/Containers/Inbox/Inbox.tsx, src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx, src/lib/Scenes/MyBids/MyBids.tsx, src/lib/Scenes/MyBids/__tests__/MyBids-tests.tsx, src/lib/Scenes/MyBids/__tests__/MyBids2-tests.tsx
[PURCHASE-2173]
This story was initially. a spike, but I had a pretty good idea of how to implement it so after consulting with @zephraph I just went ahead and did it.
We may want to move the refresh container beneath the upper tabs in the future, but will wait until design looks it over.
This PR was branched from my PR fixing the conversations refresh, as they both made changes to the. same function in `Inbox` and I wanted to avoid a tricky merge. This PR also includes a small update to remove some unused code I forgot to remove from that PR. 
[PURCHASE-2173]: https://artsyproduct.atlassian.net/browse/PURCHASE-2173
=> Build Mechanism for refreshing My Bids view

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
=> chore(release): for 6.7.4 development work.

HACKS.md
=> doc(HACKS): follow-up from #4185

src/__generated__/Show2ArtworksTestsQuery.graphql.ts, src/__generated__/Show2Artworks_show.graphql.ts, src/__generated__/Show2Query.graphql.ts, src/__generated__/Show2TestsQuery.graphql.ts, src/lib/Components/ArtworkFilterOptions/SortOptions.tsx, src/lib/Components/ArtworkFilterOptions/__tests__/SortOptions-tests.tsx, src/lib/Scenes/Sale/Components/SaleLotsList.tsx, src/lib/Scenes/Show2/Components/Show2Artworks.tsx, src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx, src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts, src/lib/utils/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx, src/lib/utils/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
Will open this in draft. If you think this the right approach to take, I'll add some specs here.
I kind of stumbled through this — there may be (I hope) an easier/more straightforward way to do this.
--------
This PR resolves [FX-2517]
[FX-2517]: https://artsyproduct.atlassian.net/browse/FX-2517
=> fix(fx-2517): set default sort to "gallery curated"

CHANGELOG.yml, src/__generated__/MyProfileQuery.graphql.ts, src/__generated__/MyProfileRefetchQuery.graphql.ts, src/__generated__/MyProfileTestsQuery.graphql.ts, src/__generated__/MyProfile_me.graphql.ts, src/lib/Scenes/MyProfile/MyProfile.tsx
This PR fixes a bug where an unused query may cause a user's profile to not load.
=> fix: remove unused auctionsLotStandingConnection from profile

src/__generated__/Fair2EmptyStateTestsQuery.graphql.ts, src/__generated__/Fair2EmptyState_fair.graphql.ts, src/__generated__/Fair2Query.graphql.ts, src/__generated__/Fair2TestsQuery.graphql.ts, src/__generated__/Fair2_fair.graphql.ts, src/__generated__/VanityURLEntityQuery.graphql.ts, src/lib/Scenes/Fair2/Components/Fair2EmptyState.tsx, src/lib/Scenes/Fair2/Fair2.tsx, src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx, src/lib/Scenes/Fair2/__tests__/Fair2EmptyState-tests.tsx, src/lib/tests/setupTestWrapper.tsx
This PR resolves [FX-2498]
Also ported over the test wrapper setup from Force.
[FX-2498]: https://artsyproduct.atlassian.net/browse/FX-2498
=> fix(fx-2498): renders more accurate empty state

Artsy/App/AROptions.m, CHANGELOG.yml
This PR removes the feature flag for the my bids tab, so that we can use an echo flag instead (added here)[https://github.com/artsy/echo/pull/63]
May need to hold off on merging until the echo PR is merged
=> chore: Remove my bids flag

src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts, src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts, src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts, src/__generated__/MyCollectionArtworkQuery.graphql.ts, src/__generated__/MyCollectionArtwork_sharedProps.graphql.ts, src/__generated__/myCollectionAddArtworkMutation.graphql.ts, src/__generated__/myCollectionEditArtworkMutation.graphql.ts, src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAddPhotos.tsx
Fixes a bug introduced in a previous PR that caused images not to show in the Add Photos screen:
=> fix(my collection): show images in add photos

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Prep for development version 6.7.5
=> chore: Preparing for development, version 6.7.5

CHANGELOG.yml, src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
This makes the header on the screen sticky.
=> fix(my collection): additional details edit screen layout

src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts, src/__generated__/ArtworkDetails_artwork.graphql.ts, src/__generated__/ArtworkMediumQuery.graphql.ts, src/__generated__/ArtworkMedium_artwork.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/lib/AppRegistry.tsx, src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx, src/lib/Scenes/Artwork/Components/ArtworkDetailsRow.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CollapsibleArtworkDetails-tests.tsx, src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx, src/lib/Scenes/ArtworkAttributionClassFAQ/__tests__/ArtworkAttributionClassFAQ-tests.tsx, src/lib/Scenes/ArtworkMedium/ArtworkMedium.tsx, src/lib/Scenes/ArtworkMedium/__tests__/ArtworkMedium-tests.tsx, src/lib/Scenes/ArtworkMedium/index.ts, src/lib/navigation/routes.tsx, src/lib/utils/__tests__/flattenChildren-tests.tsx, src/lib/utils/flattenChildren.ts, src/palette/elements/Join/Join.tsx
This PR resolves [FX-2467]
[FX-2467]: https://artsyproduct.atlassian.net/browse/FX-2467
=> feat(fx-2467): adds artwork medium screen

src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts, src/__generated__/ArtworkRefetchQuery.graphql.ts, src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts, src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts, src/__generated__/InquiryButtonsTestsQuery.graphql.ts, src/__generated__/InquiryButtons_artwork.graphql.ts, src/__generated__/InquiryModalTestsQuery.graphql.ts, src/__generated__/InquiryModal_artwork.graphql.ts, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx, src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx, src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
Co-authored-by: Christina Thompson <c.thompsonms@gmail.com>
This PR introduces missing tracking requested by the data team for first inquiry events https://artsy.slack.com/archives/C9YNS4X32/p1608669619193000
=> chore: adds first inquiry analytics to messaging events

src/lib/AppRegistry.tsx, src/lib/utils/useAppState.tsx, tslint.json
The type of this PR is: **Bugfix + DX enhancement**
This PR has two things 😬.
- While working on the Instagram share feature, I noticed that this is not called when the app goes foreground or background, which is the point of this code. Adding these two as deps fixes the issue.
- A bunch of people felt the `strict-boolean-expressions` is more annoying than helping. I added this to avoid bugs like one when I added this rule, but mostly it produces warnings with no "best practices" on how to avoid/rewrite them. We can just remove it again for now, until we find a better way to apply this rule.
=> fix(deps): useEffect bug

CHANGELOG.yml, Podfile, Podfile.lock, package.json, yarn.lock
This PR updates the `Podfile` and `package.json` dependencies to no longer point to personal forks, but rather to forks under the Artsy GitHub organization (which I created this morning). 
Many of the forks we are currently pointing to belong to developers who no longer work at Artsy, which poses quite a risk for the business. If the developer (perhaps inadvertently) deletes the fork, or force-pushes to it, or even deletes their GitHub account, we will be left in a very tricky spot. This problem isn't theoretical – it's happened before, so let's keep it from happening again.
=> chore: update dependencies to point to Artsy forks

src/lib/utils/track/schema.ts
This PR resolves [FX-2577]
Minor screen name fix.
[FX-2577]: https://artsyproduct.atlassian.net/browse/FX-2577
=> fix(fx-2577): updates screen name

CHANGELOG.yml, src/__generated__/SaleAboveTheFoldQuery.graphql.ts, src/__generated__/SaleActiveBidItemTestsQuery.graphql.ts, src/__generated__/SaleActiveBidItem_lotStanding.graphql.ts, src/__generated__/SaleActiveBidsRefetchQuery.graphql.ts, src/__generated__/SaleActiveBidsTestsQuery.graphql.ts, src/__generated__/SaleRefetchQuery.graphql.ts, src/lib/Scenes/Sale/Components/SaleActiveBidItem.tsx, src/lib/Scenes/Sale/__tests__/SaleActiveBidItem-tests.tsx
Co-authored-by: Anna Carey <anna.carey@artsymail.com>
This PR resolves [CX-929]
- Active bids are not clickable on the auction screen
[CX-929]: https://artsyproduct.atlassian.net/browse/CX-929
=> fix(SaleActiveBidItem): make auction lots clickable

fastlane/metadata/en-US/release_notes.txt
Update release notes for 6.7.5
=> chore: update release notes for 6.7.5

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
**Description**
Prep for development version 6.7.6
=> chore: preparing for development, version 6.7.6

src/__generated__/Fair2ArticlesQuery.graphql.ts, src/__generated__/Fair2Articles_fair.graphql.ts, src/__generated__/Fair2EditorialTestsQuery.graphql.ts, src/__generated__/Fair2Editorial_fair.graphql.ts, src/__generated__/Fair2Query.graphql.ts, src/__generated__/Fair2TestsQuery.graphql.ts, src/__generated__/VanityURLEntityQuery.graphql.ts, src/lib/AppRegistry.tsx, src/lib/Scenes/Fair2/Components/Fair2Editorial.tsx, src/lib/Scenes/Fair2/Components/Fair2EditorialShare.tsx, src/lib/Scenes/Fair2/Fair2Articles.tsx, src/lib/Scenes/Fair2/__tests__/Fair2Articles-tests.tsx, src/lib/Scenes/Fair2/__tests__/Fair2Editorial-tests.tsx, src/lib/navigation/routes.tsx, src/lib/navigation/util.ts
This PR resolves [FX-2509]
[FX-2509]: https://artsyproduct.atlassian.net/browse/FX-2509
=> feat(fair): implents fair articles landing screen

fastlane/metadata/en-US/release_notes.txt
Updates release notes in preparation for 6.7.6 release
=> chore: update release notes for 6.7.6

Artsy Stickers/Info.plist, Artsy/App_Resources/Artsy-Info.plist, CHANGELOG.yml
Preps for the next release (6.7.7).
=> Preparing for development, version 6.7.7

CHANGELOG.yml, Podfile.lock, src/lib/AppRegistry.tsx, src/lib/Containers/Inbox/Inbox.tsx, src/lib/Containers/Inbox/InboxOld.tsx, src/lib/Containers/Inbox/index.tsx, src/lib/Containers/__tests__/Inbox-tests.tsx, src/lib/Containers/__tests__/InboxWrapper-tests.tsx, src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx, src/lib/Scenes/Inbox/Components/Conversations/__tests__/Conversations-tests.tsx, src/lib/Scenes/MyBids/MyBids.tsx, src/lib/Scenes/MyBids/__tests__/MyBids-tests.tsx
Co-authored-by: Lily Pace <lilyfpace@gmail.com>
This PR adapts @lilyfromseattle's fix (#4276) to refresh the inbox when revisiting to account for some breaking changes introduced in the analytics pr. there are some type errors, but the crux of the fix is that the `Inbox.tsx` component no longer needs to use a `componentRef` to trigger internal component methods. There is still one lingering question which i've marked with a todo.
I've tested it manually and it seems to work, but there are some lingering type errors and since i'll be out next week someone else may want to pick this up (unassign me and take it away) or may have a better fix - no hard feelings if so. I didn't add tests, but on the bright side testing should be easier this way.
I've …
=> feat: Refresh inbox on visit

package.json, yarn.lock
- Somehow this got merged and I wanted to delete it now before we forget about it.
=> fix: remove react-native-navigator-ios from package.json

package.json, src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx, src/lib/Components/ArtworkGrids/GenericGrid.tsx, src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx, src/lib/Components/ArtworkGrids/SaleArtworkGridItem.tsx, src/lib/Components/ArtworkGrids/__tests__/ArtworkGridItem-tests.tsx, yarn.lock
This PR resolves [FX-2550]
[FX-2550]: https://artsyproduct.atlassian.net/browse/FX-2550
=> feat(fx-2550): adds position and sort to tap analytics

CHANGELOG.yml, src/__generated__/AuctionResultQuery.graphql.ts, src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx, src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx, src/lib/Components/Buttons/InfoButton.tsx, src/lib/Components/FilterModal/FilterModal.tsx, src/lib/Scenes/AuctionResult/AuctionResult.tsx, src/lib/utils/track/schema.ts
This PR resolves [CX-833]
- Add tracking events to auction results
**Tab change and Info bubbles events**
https://user-images.githubusercontent.com/11945712/106043406-a4462a00-60de-11eb-97f2-c9b5ff1e6c5a.mov
**AuctionResult tap and screen events**
https://user-images.githubusercontent.com/11945712/106043425-af00bf00-60de-11eb-8016-21340a6b48fe.mov
**Filter events**
https://user-images.githubusercontent.com/11945712/106043291-752fb880-60de-11eb-8540-0c517ecded00.mov
[CX-833]: https://artsyproduct.atlassian.net/browse/CX-833
=> feat: add tracking to auction results

Artsy/App/AROptions.h, Artsy/App/AROptions.m, CHANGELOG.yml
This PR resolves [CX-985]
- Remove artist insights lab feature flag
- Use echo flag instead
[CX-985]: https://artsyproduct.atlassian.net/browse/CX-985
=> chore: remove artist insights lab feature flag

src/__generated__/MarketStatsQuery.graphql.ts, src/__generated__/MarketStats_priceInsightsConnection.graphql.ts, src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
- Add market price insights picker
=> [WiP] feat: add market price insights picker
