artsy/eigen

- android/app/src/main/AndroidManifest.xml
- src/app/AppRegistry.tsx
- src/app/Scenes/ArtQuiz/ArtQuiz.tsx
- src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsEmptyTabs.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollection.tsx
- src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
- src/app/Scenes/BottomTabs/BottomTabsButton.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/Home/HomeContainer.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/Hooks/useNextOnboardingScreen.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingArtTasteQuiz.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuiz.tsx
- src/app/routes.ts
- src/app/store/AuthModel.ts
- src/app/store/migration.tests.ts
- src/app/store/migration.ts
- src/app/utils/DevMenu.tsx
- src/palette/organisms/screenStructure/Screen.stories.tsx
- src/palette/organisms/screenStructure/Screen.tsx
This PR fixes the navigation issue on Art Quiz
Steps involved : 
1.  Adding `artQuizState` with `none|open|close` states in AuthModel, which separates it from `onboardingState` and has its own. 
2. Once the user clicks on `Art Taste Quiz` pill option, on the Question 3 screen of OnboaringQuiz,  it will close the onboarding with `onDone()` prop from `useOnboardingContext()`. 
3. `onDone()` completes the Onboarding flow and opens the Art Quiz.  
4. Removing `ArtQuizNavigation` that has its own stack navigation and appending it with the global navigation which makes it easier to navigate to different artists and artwork on the results screen.
5. Adding `useEffect()` in Home.tsx where it navigates to the Art Quiz landing screen. 
6. Pressing on BottomTabs can also close the Art quiz
7. Art …
> fix: Art quiz navigations

- src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
Addresses [CX-3479]
Hide collections in collection rail on home screen if the collection is empty to avoid:
- hide collections in collection rail on home screen if the collection is empty
-
-
-
</details>
[CX-3479]: https://artsyproduct.atlassian.net/browse/CX-3479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Hide collections in collection rail on home screen if the collection is empty

- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
This PR resolves [CX-3466] 
This PR adds the edition number in My Collection artwork details if the artwork is part of a limited edition
| Edition | iOS | Android |
| -- | -- | -- |
| Unique (before) | <img width="394" alt="image" src="https://user-images.githubusercontent.com/20655703/223118764-d493eda7-cf3f-4d02-ab70-f3bf9bb1b565.png"> | <img width="416" alt="image" src="https://user-images.githubusercontent.com/20655703/223134613-926b17f8-f84f-4d27-b5f6-9d18799e914d.png"> |
| Unique (after) | <img width="394" alt="image" src="https://user-images.githubusercontent.com/20655703/223119110-f7091d4a-eca9-4614-bba2-40519629ba80.png"> | <img width="416" alt="image" src="https://user-images.githubusercontent.com/20655703/223134847-7f23d226-57ec-4d94-b4b9-be6e42f926ec.png"> |
| Limited (before) …
> feat(CX-3466): Add edition number to My Collection artworks

- src/app/Components/LoadFailureView.tsx
Displays the Unable to load error message by default ALWAYS on Staging environment.
Benefits:
- we will be able to immediately see whats the exact error when testing Betas
- Applause unable to load errors that are not reproducible will include the message in the already included video / screenshot that they submit
-
-
-
- display unable to load error message always on staging - gkartalis
</details>
> feat: display unable to load error message always on staging

- src/app/Scenes/Home/Home.tsx
This PR resolves [CX-3385] 
- I figured out I added the tracking event without triggering it 😅
https://user-images.githubusercontent.com/11945712/223434681-e3a1c3f4-27c3-4cc4-bd8a-0b8c7b3753c5.mov
- add track rail viewed event to home rails - mounir
-
-
-
</details>
[CX-3385]: https://artsyproduct.atlassian.net/browse/CX-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add track rail viewed

- src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
- src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkActions.tsx
- src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
- src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
This PR resolves [FX-4682] 
After the redesign of the Artwork Page we noticed a significant drop on artwork saves, so we decided to move it where it was placed before (under the artwork image -> ArtworkActions component)
This pr includes the following:
|---|---|
|![Simulator Screen Shot - iPhone 13 - 2023-03-15 at 16 19 01](https://user-images.githubusercontent.com/21178754/225368362-21bb89b9-af1a-4a6b-942b-8e141dd58a5c.png)|![Simulator Screen Shot - iPhone 13 - 2023-03-15 at 16 38 48](https://user-images.githubusercontent.com/21178754/225368445-fb1a6179-2f5e-4d72-b4cf-87c0a6c550e1.png)|
|![IMG_C2A093B6FDA1-1](https://user-images.githubusercontent.com/21178754/225369113-da6adb0c-d3f3-4c5c-a954-1f0fea7a2c98.jpeg)|![Simulator Screen Shot - iPhone 13 - 2023-03-15 at 16 51 …
> refactor(FX-4682): Move save artwork button to artwork actions

- src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
show only past auction results on my collection insights rails preview
-
-
-
-
</details>
> fix: show only past auction results on my collection insights

- src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
- src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
This PR resolves [CX-3416] 
**Before**
**After**
https://user-images.githubusercontent.com/11945712/226614546-7c7ac58e-7b51-4d9e-8109-ede144a4a7dd.mov
#nochangelog
[CX-3416]: https://artsyproduct.atlassian.net/browse/CX-3416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove duplicate filter for upcoming auctio nresults

- src/app/Components/PopoverMessage/PopoverMessage.tsx
- src/palette/elements/BorderBox/BorderBox.tsx
- src/palette/elements/Input/Input.tsx
Loading storybook with `yarn start-storybook` failed because `themeGet("space.1")` returns `10` instead of `10px`. Not sure if there is a better way to fix this 🤔 
-
-
-
-
</details>
> chore: Make Storybook work again

- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkDetailsRow.tsx
- src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
- src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
- src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/utils/mutations/useSaveArtwork.ts
- src/app/utils/refreshHelpers.tsx
This PR resolves [CX-3586] 
Update home screen on artist follow and artwork save to refresh the state on the rails showing the follow/save state.
I will try to find out if we can update artwork and artists directly in the store in the next step ([Docs](https://relay.dev/docs/guided-tour/updating-data/local-data-updates/)).
- Update home screen on artist follow and artwork save - ole
-
-
- Add saveArtwork mutation helper that replaces all save artwork mutations - ole
</details>
[CX-3586]: …
> fix: Update home screen on artist follow and artwork save

- src/app/Components/Home/ArtistRails/ArtistRail.tsx
Removes the internal artist rail state in order to update the content correctly. This logic was needed for the Dismiss button which isn't in use anymore.
This change fixes a bug where the following state isn't updated after following/unfollowing an artist on the artist screen.
- Fix trending artist home screen rail follow status updates - ole
-
-
-
</details>
> fix: Remove internal artist rail state to update content correctly

- src/app/Scenes/AuctionResult/AuctionResult.tsx
This PR updates the condition to show which sign (`-` OR `+`) for the performance in the auction result screen
| - | iOS | Android |
| -- | -- | -- |
| Before | ![image](https://user-images.githubusercontent.com/20655703/229824272-e0ae054f-f673-4f95-b0e5-3fe76d81d250.png) | <img width="418" alt="image" src="https://user-images.githubusercontent.com/20655703/229824228-51b595cb-ec95-4805-80f8-0fec66b14873.png"> |
| After | ![image](https://user-images.githubusercontent.com/20655703/229824321-294f2ebb-c799-4324-86b8-ba452dd93ea7.png) | <img width="418" alt="image" src="https://user-images.githubusercontent.com/20655703/229824394-a41f14df-65df-4144-a155-97c58b0aa07b.png"> |
- Update sign condition for the performance in the …
> fix: Update the performance sign condition in auction result screen

- src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
- src/app/Scenes/AuctionResults/AuctionResultsUpcoming.tsx
- src/app/Scenes/Home/Home.tsx
This PR resolves [CX-3533] 
Sort upcoming auction results by date asc
https://user-images.githubusercontent.com/11945712/230016209-65e95f93-487b-410f-9312-9d60492a5d8a.mov
- Revert sorting date on upcoming auction results - mounir
-
-
-
</details>
[CX-3533]: https://artsyproduct.atlassian.net/browse/CX-3533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: sort upcoming auction results by date asc

- src/app/Scenes/Inbox/Components/Conversations/Composer.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
- src/app/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
This PR resolves [NX-3507]
Fixes the background color of the offer CTA inside a conversation. Also, minor fixes where other areas were using the non-existing color `copper`, changed all to `orange150`.
Before
https://user-images.githubusercontent.com/15792853/231761750-a4f0c1d6-f109-4c89-b1c3-9e1fd5202d30.mov
After
- fix: use the orange150 color for the offer CTA inside a conversation - araujobarret
-
-
-
</details>
[NX-3507]: https://artsyproduct.atlassian.net/browse/NX-3507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
> fix(NX-3507): use the right backgroundColor for counterOffer banner

- src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
This PR resolves [FX-4728] 
Slack thread: [link](https://artsy.slack.com/archives/C03N12SR0RK/p1680797397951269)
Sometimes the incorrect auction countdown time is displayed for artworks on home feed. This is due to the fact that we use the “wrong” endAt [value](https://github.com/artsy/eigen/blob/77d0dbd98b1f3f212ff57d9064edfda4c006bdb4/src/app/Components/ArtworkRail/ArtworkRailCard.tsx#L84) when popcorn bidding is enabled for the auction.
| <video src="https://user-images.githubusercontent.com/3513494/231813938-4ee9ded3-b4f1-40cb-944c-07b13a00e881.mp4" />  | <video src="https://user-images.githubusercontent.com/3513494/231814008-4277024c-acb9-48e5-a632-d468cf4cface.mp4" />  | 
- ix …
> fix(FX-4728): inconsistency in auction countdown on home feed

- package.json
- yarn.lock
Related: 
- https://github.com/artsy/palette-mobile/pull/88
Noticed that the button was triggering a crash when _not_ in debugging mode, and it (seemed) to point at the button. Updating here. 
> lib(palette): bump to latest

- src/app/Scenes/Article/ArticleScreen.tsx
- src/app/Scenes/Article/Components/ArticleBody.tsx
- src/app/Scenes/Article/Components/ArticleByline.tsx
- src/app/Scenes/Article/Components/ArticleHero.tsx
- src/app/Scenes/Article/Components/ArticleNewsSource.tsx
- src/app/Scenes/Article/Components/ArticleSection.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionEmbed.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionCaption.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageSet.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionSocialEmbed.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionText.tsx
This adds the relay article data layer and lays out all of the component stubs. 
> feat(article): Add relay data layer and Article component stubs 

- eslint-rules/no-uselazyloadquery-inside-suspense.js
description identifiers error fix,
after merging the custom rule I merged a change via github suggestions in the description which breaks the rule with:
```bash
$ eslint --cache --cache-location '.cache/eslint/' --ext .ts,.tsx --fix /Users/georgekartalis/Artsy/eigen/src/app/Components/LocationAutocomplete.tsx
Oops! Something went wrong! :(
ESLint: 8.32.0
/Users/georgekartalis/Artsy/eigen/node_modules/eslint-plugin-artsy/no-uselazyloadquery-inside-suspense.js:18
recommended: "error",
^^^^^^^^^^^
SyntaxError: Unexpected identifier
at compileFunction (<anonymous>)
at Object.compileFunction (node:vm:360:18)
at wrapSafe (node:internal/modules/cjs/loader:1084:15)
at Module._compile (node:internal/modules/cjs/loader:1119:27)
at Object.Module._extensions..js …
```
> fix: description identifiers

- src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
- src/app/Components/ArtworkLists/components/ArtworkInfo.tests.tsx
- src/app/Components/ArtworkLists/components/ArtworkInfo.tsx
- src/app/Components/ArtworkLists/components/ArtworkListsBottomSheetSectionTitle.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
This PR resolves [FX-4754] 
https://user-images.githubusercontent.com/3513494/234289011-c5ea4034-2491-44d4-b151-f166686a7994.mp4
https://user-images.githubusercontent.com/3513494/234289151-6753b70e-8641-46c5-8a75-d2a7ce054197.mp4
-
-
-
- display artwork data in artwork lists bottom sheet - dimatretyak
</details>
[FX-4754]: https://artsyproduct.atlassian.net/browse/FX-4754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FX-4754): display artwork data in artwork lists bottom sheet

- ios/Artsy/Networking/ARRouter.m
This PR resolves [MOPLAT-660] 
Have a very strong suspicion this is the root of our issues with registered bidders seeing registration closed. Getting `304 Not Changed` responses from the service without this setting which will result in the cached values used, if the cache is bad the button will be in a bad state. Will try to reproduce the bug with this in mind tomorrow. In the meantime I don't think there is harm in merging this. 
-
-  fix registered bidders sometimes seeing registration closed - Brian 
-
-
</details>
[docs]: …
> fix: don't let the bidders call get cached

- src/app/Components/ShareSheet/ShareSheet.tsx
Turns out that Sentry.captureMessage("message") records the event as a crash and we don't want that in this case
-
-
-
- remove sentry tracking from sharesheet - gkartalis
</details>
> fix: remove sentry tracking from sharesheet

- ios/Artsy/App/ARAppNotificationsDelegate.m
- src/app/Scenes/Home/HomeContainer.tsx
- src/app/store/AuthModel.ts
This PR resolves [MOPLAT-737] 
Adds a check to make sure we only request push permissions once per login session to not spam Android users with the settings dialog when they deny push permissions. 
**Follow-ups:**
Digging into this code revealed it is fairly buggy, probably at least partially my fault but having the logic split across native side and typescript side makes it hard to follow. Going to create a ticket to bring this all over to typescript, write some tests and hopefully fix some of these bugs:
- We are not refreshing tokens when the users push status is authorized
- Login is not the relevant event for our push logic, we should be checking it any time the app is launched
- Not a bug necessarily but now that Android has a similar push permissions model we should make the logic …
> fix: only request push notifications once per login session

- src/app/Components/ArtsyWebView.tsx
Our Android modals are full screen so need the safeArea insets, iOS is not so doesn't.
We should probably do the same thing on both platforms eventually. Quick fix for now. 
Before:
After:
-
-
- Fix header buttons showing behind status bar - Brian 
-
</details>
> fix: add safe area insets on Android

- src/app/Components/ArtsyWebView.tsx
- src/app/Scenes/Home/HomeContainer.tsx
- src/app/store/AuthModel.ts
- src/app/store/__tests__/migration.tests.ts
- src/app/store/migration.ts
- src/app/utils/PushNotification.ts
Good spot @damassi this can't be in session state if we want it to persist and prevent showing dialog if user kills the app.
-
-
- Fix the push settings dialog showing up for real - Brian 
- 
</details>
> fix: move flag out of session state so it stays between sessions

- src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
@egdbear this PR makes the auction results query optional to avoid breaking my collection tab because of timeouts there
In the long term we would like to support lazy loading with the sticky tabs and only triggering this query when we land on the insights tab
#nochangelog
> chore: make my c auction results query optional

- .eslintrc.js
When we were using eslint we had the `jsxSafeConditionalsRule` custom rule for preventing of doing stuff that can crash the app like:
```tsx
const whatever = "test"
// ....random code in between......
whatever && <Text>{whatever}</Text>
```
and encouraged something like that (adding doublequotes):
```tsx
const whatever = "test"
// ....random code in between......
!!whatever && <Text>{whatever}</Text>
```
This PR enables the use of `react/jsx-no-leaked-render` rule which pretty much does the same! 
You can read more about this rule [here](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-leaked-render.md)
https://user-images.githubusercontent.com/21178754/236007635-5d8f4b4b-ac12-4c25-b1f8-a0c4869f035b.mov
#nochangelog
> feat: enable react/jsx-no-leaked-render eslint rule

- .eslintrc.js
This needs to be updated to support ternaries, lest the autofixer removes them. 
> fix(eslint): Support ternaries in jsx rule

- src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Components/ArtworkLists/components/ArtworkInfo.tests.tsx
- src/app/Components/ArtworkLists/components/ArtworkInfo.tsx
- src/app/Components/ArtworkLists/types.ts
- src/app/Components/ArtworkLists/useArtworkListsToast.ts
- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkLists.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
This PR resolves [FX-4759] 
https://user-images.githubusercontent.com/3513494/235751219-d6da597e-4779-4e17-82a1-8e108387df21.mp4
https://user-images.githubusercontent.com/3513494/235751377-6a6eedb5-b71d-468a-b8c1-26d74c1c248b.mp4
https://user-images.githubusercontent.com/3513494/235751648-a4c74046-223f-4881-91b6-0a25652a7db6.mp4
https://user-images.githubusercontent.com/3513494/235751677-573d3e49-d0a6-4306-819a-3b536a0cdb2b.mp4
-
-
-
- Display toast with actions summary for artwork lists flow - dimatretyak
</details>
[docs]: …
> feat(FX-4759): Display toast with actions summary for artwork lists flow

- src/app/AppRegistry.tsx
- src/app/Components/ArtworkLists/components/AutomountedBottomSheetModal.tsx
- src/app/Components/BottomSheet/DefaultBottomSheetBackdrop.tsx
- src/app/Components/MenuItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tests.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tests.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
- src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
- src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
- src/app/Scenes/MyCollection/State/MyCollectionTabsStore.tsx
- src/app/Scenes/MyProfile/MyProfileHeader.tsx
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
- src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
This PR resolves [CX-3636] 
This PR adds "Add to my collection" bottom sheet inside my collection. It also lays the foundation of the future work around the bottom sheet modal.
**For easier review, I recommend hiding spaces like below ⬇️ .**  
___
**Screen Recording**
https://user-images.githubusercontent.com/11945712/236489872-677c8da9-23a5-4d92-a7b0-0f9f16610a0f.mov
- Create Add to my collection bottom sheet - mounir
-
-
-
</details>
[CX-3636]: https://artsyproduct.atlassian.net/browse/CX-3636?atlOrigin=eyJ …
> feat(CX-3636): create add to my collection bottom sheet

- src/app/Components/ArtworkLists/useArtworkListsToast.ts
- src/app/Components/Toast/ToastComponent.tsx
- src/app/Components/Toast/types.ts
This PR resolves [FX-4762] 
* Add the ability to pass the CTA for the Toast component
* The whole toast should remain clickable, **not** just CTA
| ![before-1](https://user-images.githubusercontent.com/3513494/236295036-84be3ba7-b336-4fda-b72a-d061457ca1e4.png) | ![after-1-xs](https://user-images.githubusercontent.com/3513494/236299883-cf5fe96d-0606-441c-a6db-1720321072c5.png) | 
| ![before-2](https://user-images.githubusercontent.com/3513494/236295107-a0dcfdc0-f37f-40a8-aabe-b090f3149cfe.png) | ![after-2-xs](https://user-images.githubusercontent.com/3513494/236299777-02c31e9f-4114-4620-bc83-8b0bcdb4c965.png) |
- Support CTA in Toast - dimatretyak
-
-
-
</details> …
> feat(FX-4762): Support CTA in Toast

- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Scenes/Home/Home.tests.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/utils/mutations/useSaveArtwork.ts
- src/app/utils/refreshHelpers.tsx
This PR resolves [CX-3586] 
Related PR: https://github.com/artsy/eigen/pull/8442
The problem in the [CX-3586](https://artsyproduct.atlassian.net/browse/CX-3586) task was that we used different relay env on the Home screen and `useMutation` (this hook uses env, which is passed [here](https://github.com/artsy/eigen/blob/8676b5afc7fee7e0d681fd14bfb5c978290ff116/src/app/Providers.tsx#L78)).
We have already faced such a problem [here](https://github.com/artsy/eigen/pull/8219) and [here](https://github.com/artsy/eigen/pull/8391) + some [related PR](https://github.com/artsy/eigen/pull/8393) from George
| <video src="https://user-images.githubusercontent.com/3513494/236521664-a3a2a846-71da-43bf-9df6-bf64a4caf2da.mp4" />  | <video …
> fix: use the same relay env between Home screen and `useMutation`

- src/app/Components/ArtworkLists/useArtworkListsToast.ts
This PR resolves [FX-4762], [FX-4759] 
| ![before](https://github.com/artsy/eigen/assets/3513494/977378ab-ac8f-4099-8611-b00dbedf0ef2) | ![after](https://github.com/artsy/eigen/assets/3513494/7e815910-af12-418d-8213-024c27eb4304) | 
-
-
-
- display CTA when artwork saved to saved artworks (default artwork list) - dimatretyak
</details>
[FX-4759]: https://artsyproduct.atlassian.net/browse/FX-4759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
> chore(FX-4762, FX-4759): display CTA when artwork saved to saved artworks (default artwork list)

- docs/troubleshooting.md
Per this [slack convo](https://artsy.slack.com/archives/C02NAJ2CGLW/p1683830323891879?thread_ts=1683829089.992739&cid=C02NAJ2CGLW), this updates our Troubleshooting doc with an entry on hot-reloading, and ensuring a proper developer experience in Eigen. 
> docs(troubleshooting): Add docs on fixing hot reloading

- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
The Artwork lists loading indicator took up all the space and for this reason the footer component was not displayed. This PR fixes it
| ![before](https://github.com/artsy/eigen/assets/3513494/114ca93e-8856-4ec7-b9f7-9099de11717c) | ![after](https://github.com/artsy/eigen/assets/3513494/df6284fd-561d-4b0f-b253-8f6be83b4aab) | 
| ![before](https://github.com/artsy/eigen/assets/3513494/74759fef-e2ea-4ca7-bacf-c7c45d08874e) | ![after](https://github.com/artsy/eigen/assets/3513494/25d91987-370b-4c10-9646-21f81bbb853f) |
https://github.com/artsy/eigen/assets/3513494/9d9a0310-3eaf-4778-b934-020264f87020
-
-
-
- fix artwork lists loading indicator - dimatetyak
</details>
Need …
> fix: artwork lists loading indicator

- src/app/Components/MenuItem.tsx
- src/app/Components/PartnerEntityHeader.tsx
- src/app/Scenes/Artwork/Components/PartnerCard.tsx
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
This PR resolves 3 things:
- Menu item component broken in account settings
- Weird bottom padding inside my collection
- Main build failures due to entity-header component removed unused href property
#nochanges
> fix: UI blocking bugs

- src/app/Scenes/ArtworkList/ArtworkListEmptyState.tests.tsx
- src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
Small updates for empty artwork lists state
-
-
-
-
</details>
> refactor: update empty state for artwork lists

- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
This PR resolves [MOPLAT-619] 
Hides the long press feature on android.
Turns out the disabled prop on ContextMenu is working only on iOS so I did an early return if it is android return only the children, otherwise wrap with the ContextMenu
#nochangelog
[MOPLAT-619]: https://artsyproduct.atlassian.net/browse/MOPLAT-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: hide context menu on android

- src/app/Components/ArtistListItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
- src/app/Scenes/MyCollection/MyCollection.tsx
- src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
This PR addresses the following QA bugs reported by Pierluca:
- Show the artist preview modal instead of navigating to the user press
- Adds underlay color to artwork rows for better UX
https://github.com/artsy/eigen/assets/11945712/989e016c-f167-4ef3-aa69-0b086c96ebaa
#nochanges
> chore: make artist list item clickable

- src/app/Scenes/ArtworkList/ArtworkList.tests.tsx
- src/app/Scenes/ArtworkList/ArtworkList.tsx
- src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
- src/app/Scenes/ArtworkList/ArtworkListHeader.tsx
don't display contextual menu button for "Saved Artworks" list (our default artwork list)
| <video src="https://github.com/artsy/eigen/assets/3513494/3486db6b-5808-4d32-9403-08c97ab53c09" />  | <video src="https://github.com/artsy/eigen/assets/3513494/920b7047-cc8f-4b76-8ba2-ed265435a9ad" />  | 
-
-
-
- don't display contextual menu button for "Saved Artworks" list - dimatretyak
</details>
> feat: don't display contextual menu button for "Saved Artworks" list

- src/app/Components/NotFoundFailureView.tsx
- src/app/Components/RetryErrorBoundary.tests.tsx
- src/app/Components/RetryErrorBoundary.tsx
- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Partner/Partner.tsx
- src/app/Scenes/Sale/Sale.tsx
As we were working on sticky tab stuff we realized that some of the error boundary screens weren't working properly and due to the changes we did (fullBleed: true) it broke a bit the design of this page.
This PR fixes that and readjusts the screens to be always correcly aligned utilizing the `<Screen />` palette component.
As a **bonus** I also removed all the references of the `RetryErrorBoundaryLegacy` which was used in some places (and it was **overriding** the new error boundary that we already have in place in the providers of the app.
Nothing changes behavior wise since they both used under the hood the same view 🤷‍♂️.
⚠️ I didn't touch the Override that we do in **MyCollection** since it is due to using specific error messages related with the errors in this …
> refactor: error boundary screens

- ios/Podfile.lock
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkLists.tsx
Notion Card: https://www.notion.so/artsy/Selecting-unselecting-lists-in-the-sheet-can-feel-a-bit-sluggish-Takes-a-second-or-two-to-settle-b63ab6d694dc4f8e94ccefda22386b84
-
-
-
- improve artwork lists performance - dimatretyak
</details>
> feat: improve artwork lists performance (attempt 1)

- src/app/Components/ArtworkLists/components/AutomountedBottomSheetModal.tsx
This PR resolves [FX-4796] 
Notion card: https://www.notion.so/artsy/Cannot-tap-on-dimmed-negative-space-to-dismiss-modal-241df02014654b1aa9d5ecde107994c6
| <video src="https://github.com/artsy/eigen/assets/3513494/ec511221-c0d8-4aac-8479-c7e1cb02b120" /> | <video src="https://github.com/artsy/eigen/assets/3513494/313869a8-b267-44a6-a506-554853def411" /> | 
-
-
-
- add ability to close bottom sheet for artwork lists when backdrop is clicked - dimatretyak
</details>
[docs]: …
> feat(FX-4796): add ability to close bottom sheet for artwork lists when backdrop is clicked

- .circleci/config.yml
- fastlane/Fastfile
- scripts/hermes-ios-bundle-sourcemap.sh
This PR resolves [MOPLAT-771] 
- MOPLAT-771 -> get rid of bundle-js job which bundles ios for`build-test-js` (which is **NOT** needed) and might speed things up when running CI checks
- Bonus: Attempt to fix ios hermes sourcemaps
-
-
-
-
</details>
[MOPLAT-771]: https://artsyproduct.atlassian.net/browse/MOPLAT-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(WIP): remove bundle-js job and move bundling to fastlane #doNotMerge

- docs/README.md
- docs/setting_up_eigen_after_long_time.md
Updating the docs for setting up eigen after a long time, happy to hear peoples thoughts on it
#nochangelog
> docs: add section about setting up after long time [skip ci]

- src/app/Scenes/ArtworkList/ArtworkList.tsx
Notion card: https://www.notion.so/artsy/When-an-artwork-list-is-open-and-an-artwork-is-removed-from-the-list-the-update-is-not-reflected-imm-fa6851d0c519441a90e6519f95dde7e0
| <video src="https://github.com/artsy/eigen/assets/3513494/80d31a76-d87c-47a3-858a-5c37e45cf774" /> | <video src="https://github.com/artsy/eigen/assets/3513494/03f06587-9a76-47e6-bea8-e1ed5674ed27" /> | 
-
-
-
- use `network-only` fetch policy mode for artwork list screen - dimatretyak
</details> …
> chore: use `network-only` fetch policy mode for artwork list screen

- package.json
- src/app/Scenes/Activity/Activity.tsx
- src/app/Scenes/Favorites/Favorites.tsx
- src/app/Scenes/Gene/Gene.tsx
- src/app/Scenes/Partner/Partner.tsx
- src/app/Scenes/Tag/Tag.tsx
- yarn.lock
Related: 
- https://github.com/artsy/palette-mobile/pull/107
Bumps palette with the latest, which centers content. Also fixes some missing back actions when we rolled in the animated headers. 
> fix(tabs): ensure back actions are present

- src/setupJest.tsx
Adds setupJest mock for `FadeIn` as a follow up to https://github.com/artsy/palette-mobile/pull/111 for tests to not break
#nochangelog
> test: add fadeIn duration easing mock function

- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx
This PR updates the spacing in the about tab inside the My Collection artwork details screen
|--|---|---|
| with insights tab | ![image](https://github.com/artsy/eigen/assets/20655703/2ce8868c-d6dd-4608-816b-41ad90b176cb) | ![image](https://github.com/artsy/eigen/assets/20655703/8bd664e9-471f-437f-9851-199266c2f3c3) | 
| without insights tab | ![image](https://github.com/artsy/eigen/assets/20655703/86917738-033d-440b-9012-c95f17ce4333) | ![image](https://github.com/artsy/eigen/assets/20655703/681c74e1-cead-4082-92b1-bf0dcca4a544) |
- update about tab spacing insight MyC artwork screen - mrsltun
-
-
-
</details>
[app state …
> fix: My Collection artwork about tab spacing

- src/app/utils/mutations/useLegacySaveArtwork.ts
- src/app/utils/mutations/useSaveArtwork.ts
-
-
-
- ignore/dispose prev save artwork to artwork list mutation - dimatretyak
</details>
> feat: ignore/dispose prev save artwork to artwork list mutation

- src/app/utils/mutations/useSaveArtwork.ts
-
-
-
- add comment about flag for `useSaveArtwork` mutation - dimatretyak
</details>
> chore: add comment about flag for `useSaveArtwork` mutation

- src/app/Scenes/ArtworkList/views/EditArtworkListView/useEditArtworkList.ts
This PR resolves [FX-4814]
Fixes launch blocking bug when renaming an artwork list displays a wrong validation message.
After the fix:
https://github.com/artsy/eigen/assets/3934579/b32a2636-a068-487d-8433-814f8be3d573
-
-
-
-
</details>
[FX-4814]: https://artsyproduct.atlassian.net/browse/FX-4814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FX-4814): fix broken validation message when renaming an artwork list

- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/useCreateNewArtworkList.ts
This PR resolves [FX-4814]
Fixes launch blocking bug when renaming an artwork list displays a wrong validation message.
Same [as here](https://github.com/artsy/eigen/pull/8866).
-
-
-
-
</details>
[FX-4814]: https://artsyproduct.atlassian.net/browse/FX-4814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FX-4814): fixes wrong create collection validation message

- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
This PR resolves [CX-3782] 
This PR hides the indicator after navigating to insights tab. We were showing the wrong indicator and not removing it 😄
- hide profile visual clue indicator after navigating to insights tab - mounir
-
-
-
</details>
[CX-3782]: https://artsyproduct.atlassian.net/browse/CX-3782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CX-3782): hide profile visual clue indicator after navigating to insights tab

- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/useCreateNewArtworkList.ts
- src/app/Scenes/ArtworkList/views/EditArtworkListView/useEditArtworkList.ts
Fixes a regression introduced in [#8868][] for which we would default to a generic error message, even if a successful mutation response came back from Metaphysics.
[#8868]: https://github.com/artsy/eigen/pull/8868
- update handling of create/edit mutation error - gkartalis dblandin nickskalkin
-
-
-
</details>
> fix(artwork lists): update handling of create/edit mutation error

- src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
- src/app/store/config/features.ts
⚠️ this is a PR to reduce the future work to us and @artsy/fx-devs (not clear exactly on what the status is for the lists right now so opened it to have it ready in case we want to remove this release)
Disable `AREnableArtworkLists` from `8.14.0` in order to not to have to refresh the feature flag.
Refreshing the feature flag means that if this release goes live like this we will need to open two follow-up PRs:
- eigen to introduce a new ff for the feature
- echo to introduce a new ff for the feature to toggle remotely
#nochangelog
> feat: remove lists from release for 8.14.0

- src/app/store/config/features.ts
This PR resolves [MOPLAT-819]
Deprecates `AREnableArtworkContextMenu` and refreshes it to `AREnableLongPressArtworkCards`.
Reason: 
Before the `8.14.0` release where the `AREnableArtworkContextMenu` was marked as `readyForRelease: true` got some launch blocking design feedback so we are refreshing the feature flag to prevent leaking the feature to `8.14.0` version.
Related echo PR: TODO: add echo PR
Mark `AREnableLongPressArtworkCards` as ready for release and enable it on echo when feedback is addressed (ticketed [here](https://artsyproduct.atlassian.net/browse/MOPLAT-823))
#nochangelog
[MOPLAT-819]: https://artsyproduct.atlassian.net/browse/MOPLAT-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: refresh ff AREnableLongPressArtworkCards

- src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
This PR updates the  Add button behavior in my collection to behave differently depending on where it was opened. The new behavior is as follows:
- If the screen was opened from the artists view -> Open **Add artist you collect** flow
- If the screen was opened from the artworks view -> Open **Add artwork to your collection** flow
- If the screen was opened from the default my collection view -> Open the **Default bottom sheet drawer** flow
https://github.com/artsy/eigen/assets/11945712/a0af02d3-f1d7-443e-a5f2-ee1a6eb15ebf
- update add button behavior in my collection - mounir
-
-
-
</details> …
> feat(CX-3805): update add button behavior in my collection

- src/app/Scenes/MyCollection/Components/MyCollectionZeroState.tsx
- src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx
MyCollection empty states were not properly aligned on android, this PR fixes that.
|Before|After|
|---|---|
|<img width="387" alt="Screenshot 2023-06-26 at 10 13 02" src="https://github.com/artsy/eigen/assets/21178754/9f0d50fc-fb25-4809-b6fe-7cc87d80937f">|<img width="385" alt="Screenshot 2023-06-26 at 10 28 04" src="https://github.com/artsy/eigen/assets/21178754/99e99ecb-a4cc-4daa-a745-73564d89ddda">|
|<img width="385" alt="Screenshot 2023-06-26 at 10 13 11" src="https://github.com/artsy/eigen/assets/21178754/6af43dde-cd48-4682-9161-e3cbe0916d0d">|<img width="379" alt="Screenshot 2023-06-26 at 10 28 11" src="https://github.com/artsy/eigen/assets/21178754/191200f6-562a-4f1c-a3da-23d1eab302cf">|
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 14 Pro - …
> fix: my collection empty states paddings

- src/app/Components/ArtsyWebView.tsx
This PR removes extra padding for modals on Android
This reverts the work on #8602 after the addition of the safe area view for the webview in #8897 
|---|---|---|
| Android | ![image](https://github.com/artsy/eigen/assets/20655703/50ffe8e7-d82d-4048-a7c4-c627686fa47c) | ![image](https://github.com/artsy/eigen/assets/20655703/25ac8a4a-1991-45fa-81cd-01eff7872844) |
| iOS | ![image](https://github.com/artsy/eigen/assets/20655703/1af0fc5d-e4f7-4660-96ec-54048eace1de) | ![image](https://github.com/artsy/eigen/assets/20655703/3121a485-df84-46a5-9178-177ebb85113a) |
- Remove additional top padding in modals for Android in ArtsyWebview - mrsltun
-
-
-
</details>
Need help with something? Have a look at our …
> fix: Remove additional padding in modals in Android

- src/app/Scenes/Activity/ActivityEmptyView.tsx
Update copy for Activity Panel empty states (both All and Alerts tabs) based on feedback from Content Design team.
Jira: [FX-4678](https://artsyproduct.atlassian.net/browse/FX-4678)
| ![Simulator Screenshot - iPhone 14 Pro - 2023-06-27 at 12 25 01](https://github.com/artsy/eigen/assets/123595/e4d7ade6-801c-486a-866e-b0a643a0dea3) | ![Simulator Screenshot - iPhone 14 Pro - 2023-06-27 at 12 22 36](https://github.com/artsy/eigen/assets/123595/f6411cc1-d4ec-4698-93fd-c00522479b67) |
| ![Simulator Screenshot - iPhone 14 Pro - 2023-06-27 at 12 25 06](https://github.com/artsy/eigen/assets/123595/0d4b5da8-5159-4226-9bc3-fe91516dc6d9) | ![Simulator Screenshot - iPhone 14 Pro - 2023-06-27 at 12 22 44](https://github.com/artsy/eigen/assets/123595/9652d630-de94-4 …
> feat: update activity panel empty state copy

- src/app/Scenes/MyCollection/MyCollection.tsx
This PR fixes the issue that shows the Artist Collected Onboarding modal when the feature flag is turned off
|--|---|---|
| Android | <video src="https://github.com/artsy/eigen/assets/20655703/22464a62-1278-4cdd-9a03-03659d1a8127" /> | <video src="https://github.com/artsy/eigen/assets/20655703/6546463c-e186-4209-b3b8-b17580ef440e" /> |
| iOS | <video src="https://github.com/artsy/eigen/assets/20655703/92292e07-39ce-4572-8623-ac9e98435c81" /> | <video src="https://github.com/artsy/eigen/assets/20655703/de531799-b9b8-43c6-8fa4-00dce7a47d1f" /> |
- Disable Collected Artist onboarding modal if the feature flag is off - mrsltun
-
-
-
</details> …
> fix: Fix showing the Collected Artists onboarding modal when the FF is turned off

- src/app/Components/OpaqueImageView/OpaqueImageView.tsx
- src/app/Components/OpaqueImageView2/OpaqueImageView2.tsx
Marks OpaqueImageView and OpaqueImageView2 as deprecated.
|OpaqueImageView|OpaqueImageView2|
|---|---|
|<img width="725" alt="Screenshot 2023-06-29 at 15 47 59" src="https://github.com/artsy/eigen/assets/21178754/e697e7de-9592-4184-bc50-7724105d607f">|<img width="784" alt="Screenshot 2023-06-29 at 15 47 54" src="https://github.com/artsy/eigen/assets/21178754/044c8194-e39d-4c0a-869d-0724328ac00a">|
-
-
-
- mark opaqueImageView as deprecated - gkartalis
</details>
> chore: mark opaqueImageView as deprecated

- src/app/Scenes/MyProfile/MyProfileEditForm.tsx
- src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx
- src/app/Scenes/MyProfile/useHandleVerification.tsx
- src/app/utils/verifyID.ts
This PR resolves [PRO-159] 
Companion to https://github.com/artsy/gravity/pull/16451. We want to store the ID of the user who initiated an IDV request.
I didn't test this one personally since it's a small change and I haven't run Eigen in a while, so figured I'd get some help rather than fighting with sims for a day. @gkartalis thanks for volunteering to help with that! LMK if you either a) have changed your mind and want me to do it, or b) want to do it together 🙂 
- add initiator ID to self-initiated IDV requests
</details>
[PRO-159]: https://artsyproduct.atlassian.net/browse/PRO-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(PRO-159): add initiator ID to self-initiated IDV requests

- src/app/Scenes/Home/Components/ShowsRail.tsx
This PR resolves [CX-3740] 
Prevent Shows for You rail to reload when scrolling.
-
-
-
-
</details>
[CX-3740]: https://artsyproduct.atlassian.net/browse/CX-3740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Prevent Shows for You rail to reload when scrolling

- src/app/Scenes/Home/Home.tsx
No data changes only fixes the error from below which was caused because we never spread the fragment `Home_heroUnits`. 
Small renaming in the query to remove the alias, I don't know why I see a lot of aliasing to match UI from GraphQL, I strongly believe we should use what comes from MP, if the naming is bad there we should go on MP and change instead of aliasing. Alias in Relay should be used to avoid conflicting fields from different fragments/queries, for example 2 fragments relying on `date` but each one using a different format `param`.
-
-
-
- spread Home_heroUnits fragment in Home - araujobarret
</details> …
> fix(home): missing Home_heroUnits spread fragment

- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Scenes/Artwork/Components/ArtworkActions.tsx
- src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
- src/app/Scenes/Artwork/utils/isOpenOrUpcomingSale.ts
This PR resolves [ONYX-113] 
Do not dispatch new artwork lists behavior when tapping 'Watch lot' on artwork screen
https://github.com/artsy/eigen/assets/3934579/6d4a6468-90e1-4138-bede-07997007b81f
- Do not display artwork lists bottom sheet component when tapping 'Watch lot' on artwork screen
-
-
-
</details>
[ONYX-113]: https://artsyproduct.atlassian.net/browse/ONYX-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-113): Do not dispatch new artwork lists behavior when tapping 'Watch lot' on artwork screen

- src/app/Components/Artist/ArtistInsights/ArtistInsights.tsx
Solves https://www.notion.so/Android-Artist-Auction-Results-content-is-hidden-behind-the-tabs-25c838b4c3174afc8c127f5edebd0005 launch blocking bug
Android
|Before|After|
|---|---|
|<img width="361" alt="Screenshot 2023-07-10 at 13 13 13" src="https://github.com/artsy/eigen/assets/21178754/549d238b-e12d-45f7-b97e-e09909aa4dea">|<img width="362" alt="Screenshot 2023-07-10 at 13 50 27" src="https://github.com/artsy/eigen/assets/21178754/a0a44347-63ea-4cb2-b4c3-3f3c202d6aa5">|
|<img width="363" alt="Screenshot 2023-07-10 at 13 16 04" src="https://github.com/artsy/eigen/assets/21178754/d5bab0ed-6c4f-4137-b74d-eb5a2f584b5d">|<img width="362" alt="Screenshot 2023-07-10 at 13 50 37" src="https://github.com/artsy/eigen/assets/21178754/c89119a0-1025-40f7-a9b1-cdba34e41470">
| …
> fix: artist page insights hidden behind sticky tab

- .lintstagedrc.mjs
- package.json
- yarn.lock
This PR resolves [Detect secret issues from eigen painpoints doc](https://www.notion.so/artsy/Detect-secrets-f491a33d263841f782842e39e5340b56?pvs=4)
We wanted to make eigen's detect secrets to behave more like force. The `.lintstagedrc.mjs` file wasn't working as expected, moving the contents of it to `package.json` looks like it solves the issue! 
- Bonus update ✨: updated lint-staged dep
- go to main or any other branch
- run `yarn lint:all; yarn prettier-project`
- try to commit 
- you get this error:
- go to this branch
- run `yarn lint:all; yarn prettier-project`
- try to commit 
- you get this error:
⚠️ It is normal for yarn lint to fail since we have some issues in eigen **but** you see on the second screenshot that the detect secrets hook was executed succesfully! …
> fix: detect-secrets flow

- docs/getting_started.md
Update `getting_started.md` to make slightly more sense for first-timers. In particular, make sure to build with Xcode first, and only then use `yarn ios` or flipper.
No changelog or simulation needed.
#nochangelog
</details>
> doc: update getting_started doc slightly for first-timers

- src/app/Components/Artist/ArtistInsights/ArtistInsights.tests.tsx
- src/app/Components/Artist/ArtistInsights/ArtistInsights.tsx
- src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
- src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
I noticed the Artist's screen with a super low FPS, especially after opening ArtistInsight tab. Investigating further I've found the following error message:
Because of the lists inside the ScrollView, this message was shown, and this practice is not so performant, for example in my Android device that's almost impossible to tap and interact with the elements there.
Down below I'm sharing some tests that I made(plus FPS):
Current performance:
https://github.com/artsy/eigen/assets/15792853/425c67d9-64c0-4fde-9210-202fdbbb105b
Without rendering the elements inside the ScrollView:
https://github.com/artsy/eigen/assets/15792853/f47ff09e-86c2-43dd-942e-6797f8ddb8e1
After the changes:
https://github.com/artsy/eigen/assets/15792853/0a7a8d81-c783-4acd-98bd-03fc0c693d61 …
> perf(artist): replace ScrollView with FlatList in ArtistInsights screen

- HACKS.md
- patches/sift-react-native+0.1.8.patch
- src/app/store/config/features.ts
- src/app/system/navigation/ModalStack.tsx
Followup to https://github.com/artsy/eigen/pull/8370.
Sift's React Native package doesn't correctly upload events without manual calls. This means we've had a few Sift events on Android (on app open + user login), but not as many as we'd like. The [recommendation](https://github.com/SiftScience/sift-react-native/pull/23#issuecomment-1630984250) from the folks who worked on it is to add these calls on navigate.
- Adds additional Sift event calls on Android - mdole
</details>
> feat: send additional Sift events on Android

- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
- src/app/Components/ArtworkGrids/GenericGrid.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
This PR resolves [FX-4805] 
Counterpart to https://github.com/artsy/force/pull/12543
Adds a richer confirmation experience when creating an alert — a preview of currently matching artworks, plus CTAs to view all, or manage alerts:
Props to @gkartalis and @mzikherman for pairing 🙏🏽 
<details>
<summary>TODO</summary>
- As on web, this is only wired up for the creation flow, not the editing flow
- Confirmed working from grid long-press and rail long-press
- Still some work to do here, in order to:
- have a sensible zero state when there are no matches
- have a sensible "one state" when there is only one match, redundantly displaying the work or grid you started from
- align copy and design with web for zero-state and one-state
</details>
> **Note**
>
> **Please feel free to test out these …
> feat(alerts): add confirmation modal with matching artworks

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
This PR moves the submit button inside My Collection artwork from to be above the keyboard when the keyboard is visible
|---|---|---|
| Android | <img width="435" alt="image" src="https://github.com/artsy/eigen/assets/20655703/c5d9f1e8-84f6-45e2-82a1-cd3924a79ce8"> | <img width="436" alt="image" src="https://github.com/artsy/eigen/assets/20655703/022a50e9-124c-4670-b595-5c3436409a47"> |
| iOS | <img width="438" alt="image" src="https://github.com/artsy/eigen/assets/20655703/e23d2236-7511-4312-8abd-16ce18363657"> | <img width="438" alt="image" src="https://github.com/artsy/eigen/assets/20655703/c67324a9-70d7-4eb7-9d7d-654a72b037c1"> |
- Move submit button inside KeyboardAwareScrollView inside MyC …
> fix: Move submit button inside KeyboardAwareScrollView in MyC form

- src/app/Components/Gene/GeneArtworks.tsx
- src/app/Components/TabsFlatlist.tsx
- src/app/Scenes/MyCollection/MyCollection.tsx
- src/app/Scenes/Partner/Components/PartnerArtwork.tsx
- src/app/Scenes/Tag/TagArtworks.tsx
This PR resolves [PHIRE-100] 
There was a report that after migrating to collapsible-tabs from stickyTabs the infinite scrolling stopped working on Android.
The issue was that we use [infiniteScrollArtworkGrid ](https://github.com/artsy/eigen/blob/main/src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx) in these surfaces that uses a different implementation (scrollview) for iOS and ([ParentAwareScrollView](https://github.com/artsy/eigen/blob/main/src/app/Components/ParentAwareScrollView.tsx#L39)) on Android.
Wrapping it to another scrollview broke the functionality, this PR fixes this behavior on the following ArtworkGrids:
- GeneArtworks
- TagArtworks
- MyCollectionArtworks (didn't add a video for that as I don't have a lot of mycollection artworks to test out the …
> fix: problematic android infinite scroll grids

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
This PR resolves [ONYX-150] 
This PR updates the logic in the artists preview bottom sheet to use myCollectionConnection to fetch artworks count within my collection
https://github.com/artsy/eigen/assets/11945712/1b43440d-9b53-4350-9f44-298b5146cc12
- use myCollectionConnection to fetch artworks count within my collection - mounir
-
-
-
</details>
[ONYX-150]: https://artsyproduct.atlassian.net/browse/ONYX-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-150): use myCollectionConnection to fetch artworks count within my collection

- src/app/utils/tests/rejectMostRecentRelayOperation.ts
- src/app/utils/tests/renderWithLayout.tsx
- src/app/utils/tests/resolveMostRecentRelayOperation.ts
Deprecating some legacy test helpers to prevent people from using them:
- resolveMostRecentRelayOperation
- rejectMostRecentRelayOperation
- renderWithLayout
-
-
-
- deprecate legacy test utils in eigen - gkartalis
</details>
> chore: deprecate legacy test utils in eigen

- src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
This PR fixes some font size inconsistencies on the accept terms of bid screen. We found it during the Mobile QA meeting (card [here](https://www.notion.so/artsy/Text-link-for-agreeing-to-terms-of-auctions-bigger-than-it-is-supposed-to-be-when-bidding-8b5fb9c3dccd4e8e91a727a8a97e5dc0?pvs=4))
|Before|After|
|---|---|
|![before1](https://github.com/artsy/eigen/assets/21178754/db89c91d-a6c0-4ca5-978f-4fbc3e426075)|![after1](https://github.com/artsy/eigen/assets/21178754/b56dd7df-fc31-43f6-adfe-dfa2dc581441)| 
|![before2](https://github.com/artsy/eigen/assets/21178754/c33b9fc3-6f07-41fe-a32b-b535a1606388)|![after2](https://github.com/artsy/eigen/assets/21178754/7a196b0e-53b0-4c77-b36e-8c9a24f0d786)| 
- fixed text style …
> fix: text style incosistency on accepting bid terms

- src/app/Scenes/Home/Home.tsx
Quick little PR to reverse the behavior of the app from including unpublished hero units to excluding them even for admins. My thought was that they would want to see them so that they could do QA but web is sufficient for this. More chatter here:
https://artsy.slack.com/archives/C054P6V8HQQ/p1689948709667389
https://artsyproduct.atlassian.net/browse/DIA-75
/cc @artsy/diamond-devs
> chore: Only show published heroes even for admins DIA-75

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
This PR resolves [ONYX-167] 
Navigate to my collection after deleting artwork
https://github.com/artsy/eigen/assets/11945712/408ffdce-0a64-48d8-9a6b-5504b8aa2143
#nochanges
#8133 Need help with something? Have a look at our [docs], or get in touch with us.
[ONYX-167]: https://artsyproduct.atlassian.net/browse/ONYX-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-167): navigate to my collection after deleting artwork

- src/app/Scenes/Home/Components/ShowsRail.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/utils/queryPrefetching.ts
The "Shows for You" rail uses its own query renderer to avoid increasing the loading time for the entire home screen. This is because the rail accesses the device's location before fetching data.
This leads to the situation where the rail only starts fetching the data when the user's scroll position is close to the rail. As a result, the user sees a loading state for a few seconds before the data is loaded.
To avoid this loading state, I added a function to pre-fetch all the data needed for the rail (device location and GraphQL data).
I'm happy to hear any ideas on how to solve the issue in a better way. 🙏
**Without preloading 😢 :**
https://github.com/artsy/eigen/assets/4691889/30706633-c6e1-42fe-86aa-264217c844fe
**With preloading 🥳:** …
> fix: Preload Shows for You rail

- src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tsx
This PR resolves [ONYX-190] 
https://github.com/artsy/eigen/assets/11945712/06e501d3-6647-4053-bf01-f4f13c075cb7
#nochangelog
[ONYX-190]: https://artsyproduct.atlassian.net/browse/ONYX-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-190): dismiss keyboard after leaving add personal artist route

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
This PR resolves: [ONYX-181]
This PR fixes an issue where the copy is not matching the displayed text for my collection artist. The logic should be: if an artist is private, do not tick the box.
#nochangelog
[ONYX-181]: https://artsyproduct.atlassian.net/browse/ONYX-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: reverse artist is checked value

- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/methods/uploadArtwork.ts
- src/app/Scenes/MyCollection/mutations/createArtist.ts
This PR resolves [ONYX-188] 
**The Problem:**
When a user creates a new personal artist in the "Create Artwork" flow (creating both the artwork and the artist), the details of the artist (birthday, deathday and nationality) do not get saved correctly. This is because the `createArtworkMutation` only accepts a display name for a new personal artist ([Schema](https://github.com/artsy/eigen/blob/main/data/schema.graphql#L12578)).
**The Solution:**
I have decided to use the `createArtistMutation` instead of adding the missing parameters to the `createArtworkMutation` in Metaphysics to decouple the creation of artworks and artists. 
This way, we won't have to maintain two mutations when making adjustments to the artist form and both endpoints are independent of each other. 
I'm happy to hear …
> fix: Save artist details correctly when creating an artwork

- src/app/Scenes/Home/Home.tsx
Fixes the `Encountered two children with the same key,` warning that we were getting in the home screen.
The reason that this was happening was that inside useHomeModules we had two elements with matching title [here](https://github.com/artsy/eigen/blob/b85b154859bbdee6c6330b6955667a31b8e07dd0/src/app/Scenes/Home/useHomeModules.ts#L88) and [here](https://github.com/artsy/eigen/blob/b85b154859bbdee6c6330b6955667a31b8e07dd0/src/app/Scenes/Home/useHomeModules.ts#L35).
This PR fixes this issue by replacing the title with the key in the keyExtractor in the flatlist.
-
-
-
- warning about same key in the home flatlist - gkartalis
</details>
[app state …
> fix: Encountered two children with the same key home warning

- ios/Podfile.lock
- package.json
- yarn.lock
Bumps `react native screens` dependency to latest.
This might actually also resolve one issue that we have here in playstore [crash reports](https://play.google.com/console/u/0/developers/6449739225222972501/app/4975007939329818983/vitals/crashes/fffaa0613407aa21b7eec0f9822d2516/details?versionCode=1674645382).
Found it on a react native issue, it is not clear that it resolves the issue but the guideline is to have the `react-native-screens` dep always up to date
-
-
-
- bump react-native-screens from 3.20.0 to 3.23.0 - gkartalis
</details> …
> build(deps): bump react-native-screens from 3.20.0 to 3.23.0

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
This PR resolves [ONYX-213] 
When setting and unsetting the privacy toggle on the collected artist preview modal, the privacy setting doesn't get updated for the artist in the Collected artists list view. 
In order to show the updated state we need to reload MyCollection when the user changes the privacy setting
https://www.notion.so/artsy/Privacy-lock-is-not-displayed-Displayed-only-after-I-change-the-privacy-setting-and-open-the-artist-41a9cf33885640eeaf11d7492ef421b5?pvs=4
- reload MyCollection when setting and unsetting the privacy toggle -daria
-
-
-
</details> …
> fix(ONYX-213): reload MyCollection when setting and unsetting the privacy toggle

- src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
The toggle allowing a user to select between Grid and List views within the My Collection surface is currently placed within the Sort/Filter panel.
Using the toggle doesn't interact with the filter state however, instead utilizing a global user preference which alters the displayed artworks (not visible in the same screen) right away. This can be confusing because every other control in the panel affects the enabled/disabled state of the "Show results" primary action button.
For now, we're going to remove this feature until we can find a better placement for it.
| ![Simulator Screenshot - iPhone 14 Pro - 2023-08-04 at 17 09 44](https://github.com/artsy/eigen/assets/123595/37539a74-f167-44d3-b11f-3db43e517b7b) | ![Simulator Screenshot - iPhone 14 Pro …
> chore(My Collection): remove grid/list view option for artworks

- src/app/Scenes/Inbox/Components/Conversations/Conversations.tsx
Fixes the layout of inbox empty state.
Before:
After:
- fix inbox empty state - brian 
-
-
-
</details>
> fix: inbox empty state

- package.json
related PR -> https://github.com/artsy/eigen/pull/9111
Removes cleanBuildCache from clean-android script due to failures since it is not needed.
-
-
-
- remove cleanBuildCache from clean-android script - gkartalis
</details>
> chore: remove cleanBuildCache from clean-android script

- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Disable horizontal scroll between Profile tabs as it conflicts with the horizontal scroll of the Artists rail within the My Collection tab.
This PR resolves [ONYX-233](https://artsyproduct.atlassian.net/browse/ONYX-233)
cc/ @MounirDhahri @olerichter00 
| <video src="https://github.com/artsy/eigen/assets/123595/9c05ac6a-c4ec-4903-b7a0-0707099e107b" /> | <video src="https://github.com/artsy/eigen/assets/123595/9d3caa92-ce0f-42a7-b797-880a7ea5d567" /> | 
- fix: disable scroll between Profile screen tabs to avoid conflict with My Collection artists rail - devon
-
-
-
</details> …
> fix: disable tab scroll on Profile screen

- .circleci/config.yml
This PR resolves [PHIRE-82](https://artsyproduct.atlassian.net/browse/PHIRE-82) 
This switches the CI `check-code` job to read _danger github token_ from CircleCI contexts. By my understanding, that is the only job that requires this var.
~- [ ] I have tested my changes on **iOS** and **Android**.~
~- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.~
~- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.~
~- [ ] I have added **tests**, or my changes don't require any.~
~- [ ] I added an **[app state migration]**, or my changes do not require one.~
~- [ ] I have added a **changelog entry** below, or my changes do not require one.~
~- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.~
❗ …
> chore: check-code ci job uses danger-github-oss context

- src/app/Scenes/Partner/Components/PartnerShows.tsx
This PR resolves [APPL-499] 
**Android** wasn't respecting the paddingTop of the flatlist. This PR fixes that, changes  padding with margin and solves the issue.
**iOS** is unaffected by the change
|Before|After|
|---|---|
|![Screenshot_1691569380](https://github.com/artsy/eigen/assets/21178754/17f09f48-9fe0-441f-bd59-a9181334399a)|![Screenshot_1691569371](https://github.com/artsy/eigen/assets/21178754/21702ad4-6599-4138-b6cf-044fa6878286)|
-
-
- Partner shows rail padding - gkartalis
-
</details> …
> fix: Partner shows rail padding

- src/app/AppRegistry.tsx
- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
Refactors the Galleries For You screen to use the `<Screen />` component and to use the animated headers for consistency.
Also uses the ListEmptyComponent for the empty state.
Margin that we wanted to get rid of:
|Placeholder|Screen video|empty state|
|---|---|---|
|<img width="363" alt="Screenshot 2023-08-09 at 09 55 46" src="https://github.com/artsy/eigen/assets/21178754/0cf0fb12-02ee-4166-b470-4eb45255788b">|<video src="https://github.com/artsy/eigen/assets/21178754/d4476e9a-8be9-48cd-bddd-f67d77decc6a" width="300" />|<img width="362" alt="Screenshot 2023-08-09 at 09 55 08" src="https://github.com/artsy/eigen/assets/21178754/39ed6cda-924c-4903-8be7-781e95506e6c">|
|Placeholder|Screen video|empty state|
|---|---|---|
|![Simulator Screenshot - iPhone 14 - 2023-08-09 …
> refactor: use screen component to get rid of extra margins on iOS

- scripts/test-ios
Follow up from https://github.com/artsy/eigen/pull/9133
Fix broken tests due to missing flipper, adding a flag as we did [here](https://github.com/artsy/eigen/pull/9133/files#diff-ba93086cec5cca28644b617308de2b9ecf41ad09a97efeeb320bc63b1b3f05ffR8) to avoid from happening again
#nochangelog
> fix: pass GCC_PREPROCESSOR_DEFINITIONS flag to skip flipper on test ios job

- src/app/Components/LoadFailureView.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionZeroState.tsx
This PR resolves [ONYX-225] 
Show showAddToMyCollectionBottomSheet (modal with Add Artist and Add Artwork buttons) on the MyC empty state instead of navigating to Add Artist screen
Slack thread: https://artsy.slack.com/archives/C05EQL4R5N0/p1691572134461639
- show modal with Add Artist and Add Artwork buttons on the MyC empty state -daria
-
-
-
</details>
[ONYX-225]: https://artsyproduct.atlassian.net/browse/ONYX-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-225): show showAddToMyCollectionBottomSheet on the MyC empty state

- src/app/Scenes/Home/Components/ShowsRail.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/utils/queryPrefetching.ts
Reverts artsy/eigen#9064
---
To prevent exceeding the API limit for IP-based geo lookup, we should disable the prefetching for now.
> Revert "fix: Preload Shows for You rail"

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
- src/app/Scenes/MyCollection/MyCollection.tsx
- src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
- src/app/store/config/visualClues.ts
This PR resolves [ONYX-60] 
This PR adds two onboarding tooltips for the new Collected Artists feature.
Since the tooltips will be released at least two weeks after the feature is launched, I intend to exclude users, who have already seen the full-screen Collected Artists onboarding, from seeing the tooltips. These users are likely to have already seen and used the new feature.
I welcome feedback on whether to display the tooltips to all users or modify the method of determining whether users have already used the feature ([Slack Discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1691516616111269)).
**Screenshots:**
https://github.com/artsy/eigen/assets/4691889/5c17bde1-3e30-46d6-850d-63ecdee31159
- Collected Artists tooltip onboarding …
> feat(ONYX-60): Collected Artists tooltip onboarding

- scripts/changelog/generateChangelog.ts
This PR updates the generate changelog script:
- Updates stripping the comments from the PR body to keep `` 
- Updates the check on nochangelog in the pr body to accept NoChangelog & noChangelog
-
-
-
- update generate changelog script - mrsltun
</details>
> fix: Update generate Changelog script

- src/app/Scenes/BottomTabs/BottomTabsModel.ts
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
- src/app/system/navigation/navigate.ts
- src/app/utils/hooks/useIsFocusedInTab.ts
This PR resolves [this issue](https://artsy.slack.com/archives/C05EQL4R5N0/p1692019426486269) 
When the user moves from Home to My Collection and back to Home quickly, the first time modal (Share artists you collect) shows up, and after clicking the button the app becomes unresponsive, until the user kills the app.
Suggested approach: only show the modal if the user did move to a different screen.
- [] I have tested my changes on **iOS** and **Android**.
- do not show onboarding modal unless tab is active - mounir
-
-
-
</details>
[docs]: …
> fix: do not show onboarding modal unless tab is active

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
This PR resolves [ONYX-262] 
This PR hides **Add to artworks list** prompt during the onboarding.
**Bonus:** alphabetically order some props (sorry for the big diff)
https://github.com/artsy/eigen/assets/11945712/001db72a-7048-4594-ab49-6f3353b5f05c
- do not show artwork lists prompt during onboarding - mounir
-
-
-
</details>
[ONYX-262]: https://artsyproduct.atlassian.net/browse/ONYX-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: do not show artwork lists prompt during the onboarding

- src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
- src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
- src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
- src/app/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts
- src/app/Components/ArtworkFilter/SavedSearch/types.ts
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
- src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
- src/app/Scenes/SavedSearchAlert/helpers.ts
- src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tests.tsx
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
- src/app/store/config/features.ts
- This PR resolves [ONYX-228] 
- Related Force PR: https://github.com/artsy/force/pull/12751
This PR updates the Saved Search form (edit & create) to use Metaphysic's generated display name as a placeholder.
https://github.com/artsy/eigen/assets/4691889/0aa9be37-0ba8-402a-bfb5-9b2196783bd7
- Use generated displayName in Saved Search form - ole
-
-
-
</details>
[ONYX-228]: https://artsyproduct.atlassian.net/browse/ONYX-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
> feat: Use generated displayName in Saved Search form

- android/app/build.gradle
- android/build.gradle
- package.json
- yarn.lock
This PR resolves [PHIRE-208] 
Gets rid of `jsc-android` since we use hermes and this is already bundled with react-native nowadays if we decide to go back to it (that I don't think that will happen)
-
-
- remove jsc-android engine - gkartalis
-
</details>
[PHIRE-208]: https://artsyproduct.atlassian.net/browse/PHIRE-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build(deps): get rid of jsc-android

- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
This PR fixes the `CreateSavedSearchAlert` tests. The tests failed upon enabling [this](flag.https://github.com/artsy/echo/pull/519) feature 
-
-
-
-
</details>
> chore: Fix CreateSavedSearchAlert tests after enabling feature flag

- src/app/Scenes/Favorites/FavoriteArtists.tsx
- src/app/Scenes/Favorites/FavoriteCategories.tsx
- src/app/Scenes/Favorites/FavoriteShows.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionZeroStateArtworks.tsx
- src/app/Scenes/MyCollection/MyCollection.tsx
This PR resolves [ONYX-301] 
| Artist collected rail Before | Artist collected rail After | Artist collected rail Before | Artist collected rail After |
| ![12](https://github.com/artsy/eigen/assets/36167539/e3dd9447-9cd6-4326-a9f9-666e59c0490a) | ![10](https://github.com/artsy/eigen/assets/36167539/c287430b-007c-40ff-91ba-e1a5f2387a23) | ![13](https://github.com/artsy/eigen/assets/36167539/6d2187c7-efde-4af5-8655-c3e3a12278a3) | ![11](https://github.com/artsy/eigen/assets/36167539/0aae15e6-e342-4b11-8e99-85113dee7dc9) |
| My Collection Empty State Before | My Collection Empty State After | 
| --- | --- |
| ![10](https://github.com/artsy/eigen/assets/36167539/7297891f-29ca-4637-80f6-44749d6a844f) | ![14](https://github.com/artsy/eigen/assets/36167539/d8f22ded-ceeb …
> fix(ONYX-301): padding is wrong on the follows page, collected artists rail and myc empty state

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
This CI makes the alert name input span across multiple lines in Android. This is required to make sure that text doesn't cut because of the input height. Ideally, we would ellipsize the text but this is not yet supported in RN on Android. Another solution that I tried to work on is to make to use the placeholders array that we are also using inside the search tab, but this turned out to be not possible because it assumes we know the possible placeholder strings (which is obviously not the case here)
- make alert name multiline on android - mounir
-
-
-
</details> …
> fix: make alert name multiline on android

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-295] 
**[This is already reviewable]**
**[Erin still needs to update the copy before merging this PR]**
This PR adds support to creating an alert at the end of the list of artworks in Artist page.
| Tracking event                                                                                                                                    | Create alert Message                                                                                                                              |
|---------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------- …
> feat: add create alert at end of artworks list

- package.json
- src/app/Scenes/Home/Components/HeroUnitsRail.tsx
- src/app/system/devTools/DevMenu/DevMenu.tsx
- yarn.lock
This PR resolves [ONYX-358]
Co-authored-by: @gkartalis 
Addresses [the overfetching of image data in the `HeroUnitsRail`](https://artsy.slack.com/archives/C05EEBNEF71/p1694628881863159?thread_ts=1694436720.499889&cid=C05EEBNEF71).
Prior to the change in https://github.com/artsy/palette-mobile/pull/149 the palette-mobile `Image` component was rendering images that were too low-res
In order to avoid that we added `performResize=false` to the `<Image />` tag here
That had the opposite and unintended effect of pulling down un-sized images that were multiple megabytes in size — 12mb instead of what should have been a couple hundred kb.
Fixed now — we only found one actual usage of the new `Image` component, so that's the only one updated here.
- …
> fix(images): use new default resize behavior to avoid overfetching

- src/app/Components/Artist/Articles/Articles.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAboutShows.tsx
- src/app/Components/Artist/ArtistAbout/ArtistCareerHighlights.tsx
- src/app/Components/Artist/Biography.tsx
- src/app/Components/Artist/RelatedArtistsRail.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
This PR resolves [DIA-165] 
This PR fixes the broken padding inside the artist screen about tab.
| Before                                                                                             | After                                                                                               |
|----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|
| <Video src="https://github.com/artsy/eigen/assets/11945712/28868a5d-7f87-43bb-91c1-410c6ddf7a63"/> | <Video src="https://github.com/artsy/eigen/assets/11945712/c6bf8e17-5e8e-493b-8ead-757067825f12" /> |
- fix broken horizontal padding in about …
> fix(DIA-165): broken horizontal padding on artist page

- src/app/Components/FancySwiper/FancySwiper.tsx
- src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
This PR resolves [DIA-168] 
This PR resolves a race condition that resolved in a crash if you move through the art quiz fast. The solution here is to decouple the swiper from the handler in order to avoid relying on a state value for the active index that might be outdated. I also moved the API logic to happen before the state logic. 
**Note:** I believe the logic can be improved even further here buy having the `activeIndex` getting incremented only after a successful mutation and creating a queue of mutations. It's alright though as it is right now and it should be good enough in its current state.
**Before** 
https://github.com/artsy/eigen/assets/11945712/35e360e5-cb68-4f64-a4c5-879141059c30
**After**
https://github.com/artsy/eigen/assets/11945712/6178ad9b-eb6b-4f32-83af-3316a4368b58 …
> fix(DIA-168): onboarding quiz crash

- src/app/Scenes/Fair/Fair.tsx
This PR resolves [PHIRE-229] 
Seems like this crash was coming from the zIndex (more info on this [rn issue](https://github.com/facebook/react-native/issues/27610)).
Got rid of the cellItemRenderer that we had to avoid overlapping the sticky section with the status bar that was **obsolete**. Avoiding the status bar is being handled by a safeareaview so no need to do zIndex hacks to bypass that.
[Sentry issue stream](https://artsynet.sentry.io/issues/4375898883/?project=5867225&query=release%3Aandroid-8.20.0-1674645426&referrer=release-issue-stream)
⚠️ Wasn't able to successfully reproduce the error though
Suggested plan: 
Release the fix and mark it as resolved in sentry and wait to see if it surfaces again on the next release.
https://github.com/artsy/eigen/assets/21178754/53fe7549-5589-4 …
> refactor: ArrayIndexOutOfBoundsException - remove obsolete cellItemRenderer

- src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-342] 
Remove ARReorderSWAArtworkSubmissionFlow ff.
-
-
-
-
</details>
[ONYX-342]: https://artsyproduct.atlassian.net/browse/ONYX-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Remove ARReorderSWAArtworkSubmissionFlow ff

- src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
- src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
- src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
- src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
- src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
This PR resolves [ONYX-394]
Follow-up to https://github.com/artsy/metaphysics/pull/5296
Counterpart of https://github.com/artsy/force/pull/12905 and very similar!
We have conditional logic to determine whether an artwork is eligible to have an alert created from it. This logic has multiplied throughout client code paths in Force and Eigen.
This addresses that tech debt by relying on the new `isEligibleToCreateAlert` flag computed in Metaphysics, instead of computing this eligibility locally.
Mostly that means diffs along the lines of…
```diff
- const hasArtists = artwork.artists?.length > 0
- if (hasArtists) {
+ if (artwork.isEligibleToCreateAlert) {
// render an alert cta
}   
```
-
-
-
- Refactor artwork alerts to use eligibility flag from …
> refactor(alerts): use eligibility flag from MP instead of computing locally

- package.json
- scripts/doctor.js
- yarn.lock
Inspired by @MounirDhahri suggestion in platform practice. 
- Uses yarn instead of outdated check-dependencies which was broken
- Adds a workaround for a bug in cocoapods-check and brings it back: https://github.com/square/cocoapods-check/issues/18
- Checks Android studio and Xcode installations and versions
- Checks ruby version and bundler version as well as existence
**Notes:** 
- We are still on Xcode 14.3 officially but looking to get to 15 soon so that version number is a bit ahead
- Android studio I am not sure we officially document which version is needed but maybe we should? 
-
-
-
- Update doctor script with more checks, fix broken checks - brian 
</details> …
> fix: update doctor script

- src/app/Scenes/Home/Home.tsx
This PR addresses the logic of the Home screen refetch indicator. Previously, the `isRefetching` state was never set to `true` in the `Home` component. By removing the `useMemo` hook, `isRefetching` is now updated correctly and functions as intended.
I believe this change does not impact performance, which was likely the initial reason for using `useMemo`. Within the `useMemo`, there were only two function declarations and no computationally heavy code (code within the function is not executed when the function is declared).
**Before:**
https://github.com/artsy/eigen/assets/4691889/8a5fbf24-9943-48a6-b195-534ae699c10d
**Now:**
https://github.com/artsy/eigen/assets/4691889/067314d6-2678-42b6-83e6-126700dba888
- fix Home screen refetch indicator …
> fix: Home screen refetch indicator logic

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
This PR prevents the Popover from being rendered on Android due to it blocking interaction in Artwork screen on first open when the user has no saved artworks
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/60877861-cf89-415f-a1c6-6e6212ad3a2b" />  | <video src="https://github.com/artsy/eigen/assets/20655703/19dc984c-fbcd-479d-9f67-6806f3973288" />  |	
-
-
- Prevent Popover from rendering on Android - mrsltun
-
</details>
> fix: Prevent Popover from rendering on Android

- src/app/Scenes/Home/Components/ActivityRailItem.tsx
If user has viewing room published notification - home screen crashes. It happens because viewing room notifications always have an empty `artworksConnection`, but the code assumes that artworks always exist.
-  fix latest activity rail when user has viewing room published event - @nickskalkin 
-
-
- 
</details>
> fix: fix latest activity rail when user has viewing room published event

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
Fix a weird behavior once you enter a screen with an ArtworkGridItem at the bottom and try to show the Popover even when the respective element anchoring it is not on the screen yet. On Android that was breaking and becoming unresponsive.
Added back to Android since got back to work with the fix(a04e87ab9fdaa3980f5e43dc95dca532d37fc31c)
iOS
https://github.com/artsy/eigen/assets/15792853/e0832062-3062-4376-b695-888c6197a9aa
Android
https://github.com/artsy/eigen/assets/15792853/52f71a3f-cde2-4ff7-842c-024ecc782fa3
- fix the first progressive onboarding alert on the Artwork screen - araujobarret
-
-
-
</details> …
> fix(ProgressiveOnboarding): adjust the logic to display the first Popover of saved Artwork

- src/app/system/errorReporting/hooks.ts
- src/app/system/errorReporting/sentrySetup.ts
- src/app/system/relay/middlewares/errorMiddleware.ts
- src/app/system/relay/middlewares/principalFieldErrorHandlerMiddleware.ts
While checking Sentry I noticed few issues:
-> Fixed that 
___
-> Now we will be reporting under this format: `Query/Mutation failed: Query Name / Mutation Name`
___
**(very) Soon  we can enable this for all screen**
-
-
-
-
</details>
> chore: Sentry error reporting improvements

- src/app/AppRegistry.tsx
- src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Scenes/ArtworkList/ArtworkList.tsx
- src/app/Scenes/ArtworkList/ArtworkListArtworksGridHeader.tsx
- src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
- src/app/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
- src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
- src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
- src/app/utils/masonryHelpers/index.ts
- src/app/utils/masonryHelpers/index.tsx
This PR resolves [PHIRE-218] 
> [!IMPORTANT]
> Nothing changed UI wise! 
Replacing the following surfaces with the new MasonryFlashList. 
Created also a reusable component for FullScreen Masonry grids (there is another one for the tabs).
Refactored surfaces:
> [!NOTE]
> There was also a **bonus** refactor on the `LotsByArtistsYouFollow.tsx` surface that refactored the queryRenderer to use relay hooks instead ⭐️
- refactor full screen artworkgrid surfaces to use new masonry - gkartalis
-
-
-
</details> …
> refactor(PHIRE-218): use MasonryFlashList of full screen grids

- src/app/AppRegistry.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/ActivityItemArtworksGrid.tsx
- src/app/Scenes/Activity/ActivityItemScreen.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
- src/app/Scenes/MyCollection/Screens/Insights/ArtistItem.tsx
- src/app/routes.ts
This PR resolves [ONYX-356]
- [Figma prototype](https://www.figma.com/proto/VjFsvmJ7e5geXuRGDeKRCg/Onyx---Design-Strategy-WIP?page-id=841%3A3070&type=design&node-id=1187-4428&viewport=99%2C-1064%2C0.31&t=2zHDojRSyxBIT0wv-1&scaling=scale-down&starting-point-node-id=851%3A859)
I've added a new screen for individual activity panel notifications. You can navigate to it by clicking on an activity panel item from activity panel or latest activities rail.
https://github.com/artsy/eigen/assets/3934579/cee75832-aa92-4045-8a67-71e2ade1b4da
- behind feature flag: new screen for individual activity panel notifications - @nickskalkin 
-
-
-
</details> …
> feat(onyx-356): single activity panel notification screen

- src/app/Scenes/Article/Components/ArticleHero.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
The image quality in certain images in articles is still not great because we aren't fetching high quality image urls. We left out specifying a version parameter when fetching the url from metaphysics and this appears to be defaulting to the medium.jpg image url which is quite small. This then is the basis for the resized image from gemini so the resultant image is quite blurry. 
This fetching was just copied from force so 👀 appreciated: https://github.com/artsy/force/blob/3a1e19354d48ebad8d47439ad0925891b1c02e0b/src/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx#L66
- Also updated the articleHero image but can't find an article with one of those, needs to be tested
- Can we document the right way to fetch images? …
> fix(articles): fetch the larger image urls, remove default param

- src/app/Components/MenuItem.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-368] [ONYX-371] 
- Add "Add Filters" to Create Alert modal - mounir
-
-
-
</details>
[ONYX-368]: https://artsyproduct.atlassian.net/browse/ONYX-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-371]: https://artsyproduct.atlassian.net/browse/ONYX-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-369]: …
> feat: add  "Add filters" to create alert screen

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
This PR adds some extra padding to the create alert artist footer. It also removes the X button that is no longer part of the designs.
#nochangelog
> fix: add extra padding to create alert artist footer

- ios/Podfile.lock
- package.json
- src/app/Components/ArtsyWebView.tests.tsx
- src/app/Components/ArtsyWebView.tsx
- src/setupJest.tsx
- yarn.lock
This PR resolves [EMI-1396] 
This PR upgrades `react-native-webview`, and adds a handler for the back button in WebViews
|---|---|---|
| Android | <video src="https://github.com/artsy/eigen/assets/20655703/80b079d1-b997-4bf9-8444-c8314645fb41" /> | <video src="https://github.com/artsy/eigen/assets/20655703/64cb0c21-9b50-4f8f-903e-1903b947f49c" /> |
| iOS | <video src="https://github.com/artsy/eigen/assets/20655703/f2cd62f4-b009-493e-a4db-ca5ba0a9c23b" /> | <video src="https://github.com/artsy/eigen/assets/20655703/94e11a12-4661-45e4-95e3-ed9accea892b" />	 |
- Add back handler for web views on Android - mrsltun
-
-
-
</details>
[app state …
> fix(EMI-1396): Fix Android hardware back button in WebViews

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
This PR comes as a follow-up on a discussion with Barney to shorten the cope for the create alert. This is in order to avoid an issue where the text comes across 3 lines if the screen is too small. 
#nochangelog 
> chore: update copy on create alert artist artworks footer

- src/app/Components/OpaqueImageView/OpaqueImageView.tsx
- src/app/Components/OpaqueImageView2/OpaqueImageView2.tsx
This PR resolves [PHIRE-311] 
Continuation of an effort to reduce the `400` requests from geminy due to falsy height and width that we started with @anandaroop.
Early exit to prevent making requests to Gemini with falsy widths and heights.
The component is smart enough to actually do the request when it should (when it has the dimensions)
Also fixes some rules of hooks issues.
|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/3e59bba6-6c44-4ac2-8cdd-1a0e1124359c" height="500" />|<video src="https://github.com/artsy/eigen/assets/21178754/b055e0fd-7d6b-4b42-bb46-27a15beac701" height="500" />|
-
-
-
- prevent image requests with falsy height / width - gkartalis
</details>
Need help with something? Have a look at …
> refactor: prevent image requests with falsy height / width

- src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
- src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
- src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
This PR resolves [ONYX-397]
Counterpart of https://github.com/artsy/force/pull/12973
Copied from the Force PR^
> When saving an alert, we use the alert's criteria to display potentially matching inventory.
> 
> If the alert is being saved from an _artwork_, we don't want to redundantly show that very artwork again as part of that inventory — a problem that is especially apparent when the alert criteria only match a handful of works.
> 
> This change therefore allows the current artwork to be passed in the `excludeArtworkIDs` param that is already supported by the `artworksConnection` field.
|If setting an alert from this work…|Before|After|
|---|---|---|
|<img width="790" alt="orign" src="https://github.com/artsy/eigen/assets/140521/35e92e44-2a09-4750-9a4e-75099bc2c601">|<img width="790" …
> fix(alerts): don't include current artwork in suggested inventory

- src/app/Components/Artist/ArtistHeader.tsx
[future-friday]
This PR brings a small fix to the artist-featured representation rail where it gets cropped when you scroll it.
https://github.com/artsy/eigen/assets/11945712/cc83091e-5d69-48e7-b793-07d9e10509e9
___
https://github.com/artsy/eigen/assets/11945712/dfc51bb5-d697-4e61-bebe-ffdea5d303eb
#nochangelog
> fix: featured representation horizontal padding

- src/app/Components/ArtsyWebView.tests.tsx
- src/app/Components/ArtsyWebView.tsx
This PR resolves [EMI-1395]
When users tap on external links (such as help center articles) in the checkout flow, and then return to the checkout flow by tapping the back button, they are navigated to the previous step of the checkout flow. This is a poor user experience.
This PR addresses that by ensuring that the WebView's backward navigation event (`goBack`) isn't called for taps on external links.
- Opening help center links during checkout won't return users to the previous step
</details>
[EMI-1395]: https://artsyproduct.atlassian.net/browse/EMI-1395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: prevent backward navigation when clicking a link in a webview (EMI-1395)

- .circleci/config.yml
Try prebooting simulators using macOS orb to see if that speeds up tests.
Going to merge this as is, one possible optimization to follow-up on, we probably only want to do the test prep in the case where native code changed. 
-
-
-
- Preboot iOS simulators when running tests - Brian 
</details>
> build(ci): preboot simulators

- package.json
- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Scenes/Activity/ActivityItem.tests.tsx
- src/app/Scenes/Activity/utils/navigateToActivityItem.ts
- src/app/Scenes/Artist/Artist.tsx
- src/app/Scenes/Search/components/AutosuggestSearchResult.tests.tsx
- src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
- src/app/routes.ts
- yarn.lock
This PR sets the foundation for the work on [ONYX-421] [ONYX-422] [ONYX-423]  
This PR adds support of URLs query params injection to navigate to the artworks grid.
https://github.com/artsy/eigen/assets/11945712/015ede74-9e3b-4f1f-9b26-201219422b23
**Remaining work:**
https://github.com/artsy/eigen/assets/11945712/942a31b7-017b-4b71-b04d-7f4f2a762c67
Blocked. by: https://github.com/artsy/palette-mobile/pull/159
- support navigating to artist artworks grid using URL query injections - mounir
-
-
-
</details> …
> feat: support navigating to artist artworks grid - mounir

- jest.config.js
- package.json
- src/setupJest.tsx
- yarn.lock
> chore(cleanup test deps): remove unused test utils

- package.json
- yarn.lock
Bumps sentry-cli from 2.12.0 to 2.21.2
#nochangelog
> build(deps): bump sentry-cli from 2.12.0 to 2.21.2

- src/app/Components/SectionTitle.tsx
- src/app/Scenes/Home/Components/ActivityRail.tsx
This PR resolves [ONYX-446] 
Remove Latest Activity rail header font boldness.
-
-
-
-
</details>
[ONYX-446]: https://artsyproduct.atlassian.net/browse/ONYX-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Remove Latest Activity rail header font boldness

- src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
- src/app/routes.ts
chore: scroll back to artworks grid on artworks press.
https://github.com/artsy/eigen/assets/11945712/d03a02d2-a72b-4779-b55b-a68013e813cd
#nochangelog
> feat: scroll back to artworks grid

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
- src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tsx
This PR improves the Alert Color filter responsiveness by adding a local state for selected colors and delaying the store update which rerenders the whole screen.
#nochangelog
-
-
-
-
</details>
> fix: Improve Alert Color filter responsiveness

- src/app/Scenes/Home/Components/ActivityRail.tsx
- src/app/Scenes/Home/Home.tsx
This PR resolves [ONYX-465] 
We have decided to filter out all notifications without associated artworks for now to avoid showing items without images in the rail until we fix the backend to support an artworks connection or find other ways to display images.
**Notification Types to include:**
`[ARTWORK_ALERT, ARTWORK_PUBLISHED]`
**Follow-Up:**
- Remove the filtering once Metaphysics exposes an `artworkConnection` for all notification types
- Consider a default image for edge cases where notifications don't have artworks with images associated (e.g. Editorial notifications)
- Filter out notifications without images in Latest Activity rail - ole
-
-
-
</details>
[app …
> fix: Filter out notifications without images in Latest Activity rail

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
This PR resolves [ONYX-463] 
Save recent price ranges only after saving alert
https://github.com/artsy/eigen/assets/11945712/caa6e6a2-ac79-49ae-9795-4b39153a266d
- save recent price ranges only after saving alert - mounir
-
-
-
</details>
[ONYX-463]: https://artsyproduct.atlassian.net/browse/ONYX-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-463): save recent price ranges only after saving alert

- src/app/system/navigation/navigate.ts
- src/app/utils/useDeepLinks.ts
This PR resolves [PHIRE-343] 
Fixes marketing link tracking - tested on iOS ✅
Fixes double tracking on normal deep links for logged out users - tested on iOS ✅
More info on decisions can be found [here](https://artsy.slack.com/archives/C03NF9TKR/p1697645671461019)
and for the bonus bug fix ar
> [!WARNING]
> Would like for at least 1 person to test with any `click.artsy.net` link from an email with an android device if possible since yarn open-url doesn't work with android 
|Before|After|
|---|---|
|logged in||
|<video src="https://github.com/artsy/eigen/assets/21178754/f800d006-3cc0-4b7e-9fe8-125a1ef3eca4" width="200" />  |<video src="https://github.com/artsy/eigen/assets/21178754/82113844-2044-4a14-b735-ec2029cc7ad9" width="200" /> |
|logged out|| 
|<video …
> fix: marketing link tracking

- src/app/Scenes/Home/Components/ActivityRail.tsx
- src/app/Scenes/Home/Home.tsx
The `notificationsConnection` cache key [depends on the number of items fetched](https://github.com/artsy/gravity/blob/a7fc24ce4e6def061a2571741012d3ed20a326e6/app/api/v1/me_notifications_endpoint.rb#L27). This can lead to inconsistencies between the activity screen (fetches initially 10 items) and the Activity rail (fetches 6 items).
As a quick fix, this PR aligns increases the number of items being fetched for the Activity rail to match the number of items fetched for the screen.
**Follow-Up:**
We should look into ways to change the way the activity feed is cached to avoid the issue.
**Screenshots:**
| Screen (10 items) | Fetching 6 items 🔴  | Fetching 10 items 🟢  |
|![screen](https://github.com/artsy/eigen/assets/4691889/8930f46b-7b06-4a99-bdc8-0a43e158a260) |![no …
> fix: Fix Latest Activity rail caching issue

- fastlane/utility_fastlane.rb
Replaces the red X with a ⚠️ for slack codepush message:
`Native code has changed, new testflight needed! Deploy new betas from main to keep testing.`
-
-
-
- replace error emoji with warning for codepush - gkartalis
</details>
> chore: replace error emoji with warning for codepush

- ios/Podfile.lock
For some reason renovate bot doesn't really care about podfile changes and after merging some dep updates I run pod-install basically and commiting the diff
#nochangelog
> chore: podfile.lock changes

- ios/ArtsyTests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
Gives all the snapshot tests a tolerance for live auction view controller. If they continue to fail we can remove. 
-
-
-
- fix flaky test part 2 - Brian 
</details>
> fix(flaky test): give all the live auction snapshots a tolerance

- src/app/Scenes/Onboarding/OnboardingLogin.tests.tsx
- src/app/Scenes/Onboarding/OnboardingLogin.tsx
This PR resolves [DIA-198] 
Related to #9531, prevents submitting the form without being correctly filled via the keyboard submit button.
Also, disable the button until the form is valid.
Bonus: refactored the deprecated use of our test suite within the tests
Before
https://github.com/artsy/eigen/assets/15792853/d01cf52d-676c-4585-88d4-46993f14a92e
After
https://github.com/artsy/eigen/assets/15792853/b2b19bc5-c5cb-456b-9a6b-a20beb43d733
- fix: disable the cta on the login screen until the form is in a valid state, prevent submitting when its blank - araujobarret
-
-
-
</details> …
> fix(DIA-198): add better disabled control on login via email screen

- scripts/setup/setup-env-for-artsy
- scripts/setup/setup-env-for-ci
- scripts/setup/update-env-for-artsy
- scripts/utils/doctor.js
For the reasons described in https://github.com/artsy/README/pull/530, I think it's simpler and more extensible to name our shared config file the same way in S3 as it's ultimately named locally. This PR attempts to update the few scripts with the new location.
I've already copied the file to its new location, and can follow up to remove the old version a little while after this is merged:
```
aws s3 cp s3://artsy-citadel/eigen/.env.eigen s3://artsy-citadel/eigen/.env.shared
```
#nochangelog
</details>
> chore: simplify S3 paths for shared configuration

- src/app/AppRegistry.tsx
- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
This PR resolves [ONYX-502] 
This PR makes the Alert form's "Save" (and "Delete) CTAs sticky and removes the bottom navigation for the "Create Alert" flow and the "Edit Alert" screen ([Slack Discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1699547193794289)).
| --- | --- |
|![Simulator Screenshot - iPhone 15 Plus - 2023-11-09 at 17 15 16](https://github.com/artsy/eigen/assets/4691889/b003208f-f64a-4819-9dc1-2bd58b12c070) | ![Simulator Screenshot - iPhone 15 Plus - 2023-11-09 at 17 10 13](https://github.com/artsy/eigen/assets/4691889/dc32dc6e-6f8d-4864-9d58-6524b403407e)|
| --- | --- |
|![Simulator Screenshot - iPhone 15 Plus - 2023-11-09 at 17 14 54](https://github.com/artsy/eigen/assets/4691889/72f974f0-e4f1-4c9a-bd8f-5b9b91e0f581) |![Simulator Screenshot - …
> fix: Make Alert form Save CTA sticky

- ios/Podfile.lock
- package.json
- yarn.lock
Reverts artsy/eigen#9548 due to breaking Sentry - Caught during Mobile QA meeting notion card [here](https://www.notion.so/artsy/No-sentry-error-stacktrace-ios-android-after-the-sentry-bump-19265331360a4fd9b5e9f14a8d05bc3c?pvs=4)
#nochanglog
> build(REVERT deps): bumps sentry to latest

- src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
This PR resolves [DIA-310] 
Fixes the logic of when or not to display the empty state. It's very similar to Force's implementation.
Before
After
- fix: show correctly the empty state on Artists' about tab - araujobarret
-
-
-
</details>
[DIA-310]: https://artsyproduct.atlassian.net/browse/DIA-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(DIA-310): empty state logic on Artist about tab

- package.json
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
- yarn.lock
This PR resolves [ONYX-536] 
This PR brings in some design adjustments to the suggested filters. These adjustments come after the last KS meeting.
**User has no suggested artworks**
https://github.com/artsy/eigen/assets/11945712/21df2232-0bac-4dc9-b68f-36c770a3062c
**User has suggested artworks**
https://github.com/artsy/eigen/assets/11945712/18c76ead-27fd-42d0-a869-f7e97d9584db
#nochangelog
[ONYX-536]: https://artsyproduct.atlassian.net/browse/ONYX-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-536): make design adjustment to suggested filters

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
This PR fixes padding issues on the create alert flow 
_The red background is only for the screenshot_
#nochagelog
> fix: broken padding in create alert screen

- ios/Podfile.lock
- src/app/routes.ts
Follow-up fix for https://github.com/artsy/eigen/pull/9590 that adjusts the route to "/settings/alerts/:savedSearchAlertId/**edit**"
-
-
-
-
</details>
> fix: Alert edit route

- src/app/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
[ONYX-550]
This PR fixes the broken padding below the **Add Alerts** section on **Create Alert** Modal and the placeholders.
**Before**
https://github.com/artsy/eigen/assets/11945712/3190c262-4098-482f-88bb-fac0bb0c8524
**After**
https://github.com/artsy/eigen/assets/11945712/381ab54e-f626-444f-b3f8-a3952cc1bcdf
- fix broken padding on create alert screen - mounir
- fix broken skeleton on edit alert screen - mounir
-
-
-
</details>
[ONYX-550]: https://artsyproduct.atlassian.net/browse/ONYX-550?atlOrigin=eyJpI …
> chore: UI improvements to saved searches

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
- src/app/Components/Artist/ArtistArtworks/hooks/useCreateSavedSearchModalFilters.ts
- src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
- src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tsx
- src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tsx
- src/app/Components/ArtworkFilter/Filters/helpers.ts
- src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterSize.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
- src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
- src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
- src/app/Scenes/SavedSearchAlert/helpers.ts
- src/app/Scenes/SavedSearchAlert/pillExtractors.ts
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
- src/app/Scenes/SavedSearchAlert/useSavedSearchPills.ts
This PR resolves [ONYX-379] 
This PR adds the size filters to saved searches fitlers
https://github.com/artsy/eigen/assets/11945712/4f2b9696-9c42-4283-af39-936358ebdf36
https://github.com/artsy/eigen/assets/11945712/d450c148-bf14-4470-b287-3865106a4625
https://github.com/artsy/eigen/assets/11945712/9bcbd934-c4a5-48f1-ab39-b9e3adedb41e
https://github.com/artsy/eigen/assets/11945712/2b6614f3-fc3a-4dc5-acb8-da4304b3f29d
**Challenges faced with custom sizes here:**
- The height and width are stored only in inches
- The metric selected while injecting the size filter might be different from your favourite unit
- Opportunity to unite both (**Did that on save!**)
- The name preview does not support a unit
**Follow-up suggestions:**
Continuing to support both inches and cm in all size screens …
> feat(ONYX-379): add saved searches size filter

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
This PR resolves [ONYX-586] 
Allow creating and saving alerts with disabled notifications.
| | |
| --- | --- |
| ![Simulator Screenshot - iPhone 15 Plus - 2023-12-07 at 15 03 11](https://github.com/artsy/eigen/assets/4691889/0e2c11a0-d021-4c8a-afc2-a7edec2ad0d7)| ![Simulator Screenshot - iPhone 15 Plus - 2023-12-07 at 15 03 31](https://github.com/artsy/eigen/assets/4691889/b5de93df-e231-4a45-ae13-815eb2d86d67)|
- Allow creating and saving alerts with disabled notifications. - ole
-
-
-
</details>
[ONYX-586]: …
> feat: Allow creating and saving alerts with disabled notifications

- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
This PR resolves [ONYX-451] 
This PR removes `experiment_viewed` tracking event from the home screen.
**PS:** I left `maybeReportExperimentVariant` intentionally since we might (_will_) need to use this for future experiments.
-
-
-
- remove experiment viewed event from the home screen - mounir
</details>
[ONYX-451]: https://artsyproduct.atlassian.net/browse/ONYX-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: remove experiment viewed event from the home screen

- docs/add_progressive_onboarding.md
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
- src/app/Components/ProgressiveOnboarding/useSetActivePopover.tests.tsx
- src/app/Components/ProgressiveOnboarding/useSetActivePopover.ts
- src/app/store/ProgressiveOnboardingModel.ts
This PR resolves [DIA-343] 
We had a few bugs with the tool when multiple popovers(given the flexibility of the feature) were attempted to be shown at the same time, by default the element does not allow it, and it's hard to control.
This PR introduces another variable in the model's `sessionState` to control if a Popover from the ProgressiveOnboarding has already occurred to block another from being shown.
- fix: ProgressiveOnboarding control active popover - araujobarret
-
-
-
</details>
[DIA-343]: …
> fix(DIA-343): controls when more than one Popover tries to appear

- src/app/NativeModules/ARScreenPresenterModule.tsx
- src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
- src/app/Scenes/Inbox/Components/Conversations/InquiryPurchaseButton.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/InquiryPurchaseButton.tsx
- src/app/system/navigation/navigate.tests.tsx
- src/app/system/navigation/navigate.ts
This PR updates the `navigate` function to include `replaceActiveScreen` to update current screen in the stack
**Example with `replaceActiveScreen`**
https://github.com/artsy/eigen/assets/11945712/b68553df-7ba7-4db0-b8ff-3f828e13fa13
-
-
-
- Support replaceActiveScreen in navigation - mounir + sultan
</details>
> feat: support replace routes on navigation

- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Scenes/Artist/Artist.tsx
- src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
- src/app/Scenes/Search/SearchArtworksContainer.tests.tsx
- src/setupJest.tsx
This PR comes to fix the broken tests in the artist screen. After some investigation, I realized that this was broken due to returning the same interface twice which led to overwriting the previously returned mocked values of `Me`
-
-
-
-
</details>
> fix: broken artist screen tests

- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tests.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
- src/app/store/config/features.ts
This PR resolves [EMI-1593] 
> [!Note]
> This change is hidden behind the feature flag `AREnablePartnerOffer`
This PR updates the content of the Progressive Onboarding tooltip for saves to match the new content for Partner Offer
|---|---|---|
| Android | <img width="455" alt="image" src="https://github.com/artsy/eigen/assets/20655703/f0f2367b-3f5a-48dc-a7d6-5b03fe3b4500"> | <img width="457" alt="image" src="https://github.com/artsy/eigen/assets/20655703/c6b71ac3-ee51-441a-bd4b-e5b233c00cde"> |
| iOS | ![image](https://github.com/artsy/eigen/assets/20655703/ae681748-1ecb-44f0-91c2-a28d7ac31e24) | ![image](https://github.com/artsy/eigen/assets/20655703/55fadecd-339f-4e16-8b8c-8334d5ddfb0e) |
- update progressive onboarding …
> feat(EMI-1593): Update save tooltip content for Partner Offer

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/helpers.ts
- src/app/Scenes/SavedSearchAlert/pillExtractors.ts
- src/app/store/config/features.ts
This PR resolves [ONYX-566] 
Enables the fetching and display of suggested Artist Series criteria, and puts it behind a new `AREnableArtistSeriesSuggestions` flag
(This is the replacement for https://github.com/artsy/eigen/pull/9631)
With the feature enabled…
- Enables suggested Artist Series criteria in the Alerts flow, behind feature flag - roop
-
-
-
</details>
[ONYX-566]: https://artsyproduct.atlassian.net/browse/ONYX-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …
> feat(alerts): enable artist series suggestions

- app.json
- src/app/Components/constants.ts
- src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
- src/app/Scenes/Fair/Components/FairExhibitors.tsx
This PR resolves [PHIRE-531] 
Fixes the `ArrayIndexOutOfBoundsException` crash from [sentry](https://artsynet.sentry.io/issues/4733947512/events/42f7964bc17443e19690323a211f4ba5/) on the fair page.
The issue was located inside the renderItem functions ~ returning null instead of an element inside there caused the `ArrayIndexOutOfBoundsException` crash, filtering the data before passing them on the flatlist fixed the issue.
Beta that was failing: all of them ~ beta that it is fixed: `codepush-canary-android-8.30.0-2023.12.21.14`
Steps to reproduce:
- Open the artsy app on prod environment (fair exhibitors are empty on staging)
- scroll to the bottom of the homepage
- press any of the two first fairs on the last home rail 
- start scrolling up and down 
Previous behavior: 
App was crashing …
> fix(fairs): Scrolling on fair exhibitors crashes the app

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
Refactors the autosuggest results on adding an artwork in my collection to use MasonryFlashList.
No changes are expected ui wise.
- 
-
-
- Replace artwork autosuggest results with Masonry - gkartalis
</details>
> refactor(masonry): Replace artwork autosuggest results with Masonry

- src/app/AppRegistry.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tests.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouHeader.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/Search/UserPrefsModel.tsx
- src/app/store/__tests__/migration.tests.ts
- src/app/store/config/features.ts
- src/app/store/migration.ts
Reverts artsy/eigen#9670
- Move the view mode toggle button to the top of the screen
- Add bottom padding to the scroll view (and it's not broken this time 😄)
- Wrap the screen with a suspense (this was why it was sometimes broken)
https://github.com/artsy/eigen/assets/11945712/083d882b-2cec-40bd-bc1e-c6269d3a37fa
https://github.com/artsy/eigen/assets/11945712/f0e8fd42-99b3-4ad3-8bd4-244d0603945d
> feat: Add new works for you screen + fixes

- src/app/Scenes/Partner/Partner.tsx
I noticed when loading a partner screen in Android the text `Gagosian Gal` flash up for 2-3 seconds until the actual gallery name populated. That would annoy me greatly if I was a gallery. As a user it was merely confusing. This just 
changes the placeholder text to not refer to a specific gallery.
#no-changelog
> chore: change skeleton text for partners so as to not refer to a specific gallery

- src/app/Scenes/SavedSearchAlert/helpers.tests.ts
- src/app/Scenes/SavedSearchAlert/helpers.ts
- src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
- src/app/Scenes/SavedSearchAlert/pillExtractors.ts
This PR resolves [ONYX-634] 
This implements @olerichter00 's suggestion for a workaround for better parsing of artist series titles from slugs.
Works as follows…
```ts
inferSeriesName("yayoi-kusama-pumpkins", ["Yayoi Kusama"])
// => "Pumpkins"
```
This is not the ideal solution, but a short-term expedient solution. Better long-term would be to make this work [as Force does](https://github.com/artsy/eigen/pull/9691#pullrequestreview-1803800447).
- 
-
-
- improve logic for inferring artists series titles in alert criteria pills
</details> …
> fix: extract artist series title for alert criteria pills

- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouHeader.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
This PR resolves some UI issues on small iPhones
**_I suggest to hide white spaces when reviewing this_**
- Fix screen analytics logic
___
- Fix top padding
**Before**
**After**
https://github.com/artsy/eigen/assets/11945712/3467c35c-cde2-47e1-b4b8-a676dddfa91c
https://github.com/artsy/eigen/assets/11945712/922af31b-2b34-4d49-89a7-eaf7b54e3a32
#nochangelog
> fix: address UI issues on small devices

- src/app/Components/ReadMore.tsx
- src/app/utils/renderMarkdown.tsx
Solves the [sentry issue](https://artsynet.sentry.io/issues/4774030999/events/fa2ed8bf06f54fd399ad6749d7eb7625/) where `if (node.target.startsWith("mailto:")) {` wasn't defensive
#nochangelog
> fix: more defensive markdown links mailto #trivial

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPill.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
This PR resolves [ONYX-648] 
This PR fixes an issue affecting the edit alert screen. When the user taps on a suggested filter, it should be possible for them to save an alert.
**Before: Broken behaviour**
https://github.com/artsy/eigen/assets/11945712/02ee7361-5896-49af-9754-859f38bb7523
**After: Expected behaviour**
https://github.com/artsy/eigen/assets/11945712/ea6a4b35-c15d-445c-9ab1-dce137d41f28
- allow saving alerts after tapping on a suggested filter - mounir
-
-
-
</details>
[ONYX-648]: …
> fix(ONYX-648): allow saving alerts after tapping on a suggested filter

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
Removes the save icon from the icons of the autosuggest - [Mobile QA ticket](https://www.notion.so/artsy/MyCollection-autosuggest-artworks-grid-shows-save-artwork-button-we-dont-want-that-3f8aae74f5224541b0bf3b730214a87b?pvs=4)
-
-
-
- hideSaveIcon from artwork autosuggest myc - gkartalis
</details>
> fix: hideSaveIcon from artwork autosuggest myc

- docs/troubleshooting.md
This PR adds a section to our `Troubleshooting.md` docs to help devs solve the different checksum in `Podfile.lock`. 
I had the same issue locally on a new device - not anymore though after running the commands I documented
-
-
-
- add podfile.lock troubleshooting tips - mounir
</details>
> chore: add solution to different podfile.lock

- HACKS.md
- ios/Podfile.lock
- patches/react-native+0.72.7.patch
This PR comes as a fix to broken `pod update boost` command. This is coming from issues related `JFrog`. I did the workaround suggested by the community while we're waiting for this to get solved in RN.
-
-
-
- Patch boost.podspec - mounir
</details>
> fix: broken pod-install command

- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
This PR resolves [ONYX-653] 
This PR solves the following issue with the new works for you screen: When the user scrolls down, and starts seeing new artwork images, the image flashes and a wrong ones shows up initially. 
The fix, since this screen has no pagination logic and it only shows a small list of artworks, we can avoid this by using RN default `Flatlist` here.
- NWFY: fix wrong artwork image flashing onScoll - mounir
-
-
-
</details>
[ONYX-653]: …
> fix: wrong artwork image flashing onScoll

- docs/add_an_experiment.md
- src/app/utils/experiments/hooks.ts
- src/app/utils/experiments/reporter.ts
This PR resolves [ONYX-652] 
This PR removes throttling from `ExperimentViewed` events. This comes as a request from Data.
**Bonus:**
To avoid injecting values that are already available in the hook context, I am not exporting the tracking helper within the same hook as we do in Force
-
-
-
-
</details>
[ONYX-652]: https://artsyproduct.atlassian.net/browse/ONYX-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: do not throttle experiment_viewed events

- src/app/Components/Toast/ToastComponent.tsx
This PR resolves [ONYX-655] 
This PR fixes the toast placement on screens that hide the bottom tab.
**Logic:**
When toast positioning is set to `bottom` we always show it far from the bottom by `TAB_BAR_HEIGHT`. This is not accurate in some screens that have no tab bar. We fix that by returning `0` in case there is no bottom tab. In screens like the `Artwork` screen, we can also inject a custom value using `useArtworkListsContext` and dipatching a `SET_TOAST_BOTTOM_PADDING` action
Related PR: https://github.com/artsy/eigen/pull/9720
https://github.com/artsy/eigen/assets/11945712/88c4b758-c5ec-4240-91d5-902f52a2d421
- adjust toast placement on screens without tab bar - mounir
-
-
-
</details> …
> chore: adjust toast placement on screens without tab bar

- src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
- src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
This PR resolves [ONYX-690] 
This PR adds the A/B testing logic to the new screens that support the feed view.
- add A/B testing logic to NWFGYF and RecentlyViewed - mounir
-
-
-
</details>
[ONYX-690]: https://artsyproduct.atlassian.net/browse/ONYX-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add A/B testing logic to NWFGYF and RecentlyViewed

- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
- src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
Swap icons on the NWFY and similar screens
[Slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1706283868890749) with discussion and before/after
- swap view mode icons on the NWFY and similar screens - daria
-
-
-
</details>
> fix: swap view mode icons on the NWFY and similar screens

- src/app/Scenes/Partner/Components/PartnerLocationSection.tests.tsx
- src/app/Scenes/Partner/Components/PartnerLocationSection.tsx
It was reported that when a gallery has 1 city and multiple locations we don't do the pluralization of the word `location` correctly. This PR addresses that.
Bug was reported in slack [here](https://artsy.slack.com/archives/C03N12SR0RK/p1706691425884869)
|Before|After|
|---|---|
|![IMG_8807](https://github.com/artsy/eigen/assets/21178754/c6688904-1e29-45b1-9375-338ec312cb93)|![Simulator Screenshot - iPhone 14 Pro - 2024-01-31 at 10 18 39](https://github.com/artsy/eigen/assets/21178754/007b5563-5771-439a-a910-ad761180e313)|
|![IMG_8806](https://github.com/artsy/eigen/assets/21178754/8ef6804c-fb03-49d8-a5c9-eb1a875e0a40)|![Simulator Screenshot - iPhone 14 Pro - 2024-01-31 at 10 18 11](https://github.com/artsy/eigen/assets/21178754/2a92ddbf-9326-4223-a0c2-8382a6859af3)| …
> fix: gallery locations copy + tests

- src/app/Scenes/Activity/Activity.tsx
- src/app/Scenes/Activity/NewActivityScreen.tsx
This PR resolves [ONYX-701] 
Looks like when creating the new Activity components, we forgot about the menu icon. Bringing it back
Also, in this R I'm removing the `AREnableSingleActivityPanelScreen` ff from the activity screen -- we should not have used it for the Menu icon, my bad
- add menu icon to the new activity screen (behind a ff) - daria
-
-
-
</details>
[ONYX-701]: https://artsyproduct.atlassian.net/browse/ONYX-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
> fix(ONYX-701): add menu icon to the new activity screen

- src/app/Scenes/Activity/utils/isArtworksBasedNotification.tests.ts
- src/app/Scenes/Activity/utils/isArtworksBasedNotification.ts
This PR resolves [Onyx-724]
Do not show partner offers with unpublished artwork.
[Slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1707233138078489)
#nochangelog
-
-
-
-
</details>
> fix(onyx-724): hide partner show notifications with unpublished artwork

- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/helpers.ts
This PR resolves [ONYX-379] 
**Before**
https://github.com/artsy/eigen/assets/11945712/e0ebe4ef-9778-4c75-b4cf-e742946b907b
**After**
https://github.com/artsy/eigen/assets/11945712/bea17f84-6f3d-40cb-aad9-e4ba784671a8
- fix size options height conversion - mounir
-
-
-
</details>
[ONYX-379]: https://artsyproduct.atlassian.net/browse/ONYX-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: size options height conversion

- src/app/system/relay/middlewares/helpers.ts
- src/app/system/relay/middlewares/principalFieldErrorHandlerMiddleware.ts
This PR resolves [PHIRE-592] 
This pr removes tracking network request errors on Sentry and keeps using volley (sends request failures to datadog). 
We **should** create [boards](https://app.datadoghq.com/dashboard/ib7-8gr-u6x/eigen-graphql-requests-with-errors?refresh_mode=sliding&view=spans&from_ts=1706702432300&to_ts=1707307232300&live=true) similar to these with important areas that we want to track when it comes to request errors in the mobile app.
This way the sentry dashboard will be clean with non-important and non-actionable request failures like 404s or 401s.
I believe that we won't have any issues with either wrong variables or schema changes since TS is our friend and will prevent us from having those issues, but even if these issues happen we can leverage the datadog …
> refactor: stop tracking request errors in sentry

- src/app/Scenes/BottomTabs/BottomTabsModel.ts
Removes fetch notifications info failed message from sentry since it doesn't group it along with the exception. We still keep the captureException though.
[event in sentry](https://artsynet.sentry.io/issues/4450613635/events/d034549605e24675bfafea924f2180d4/) - that we are removing - as you can see it is not that helpful
-
-
-
- remove fetch notifications info failed message - gkartalis
</details>
> fix: remove fetchnotif message sentry

- src/app/Scenes/Activity/Activity.tests.tsx
- src/app/Scenes/Activity/ActivityList.tsx
- src/app/Scenes/Activity/utils/__tests__/shouldDisplayNotification.tests.ts
- src/app/Scenes/Activity/utils/shouldDisplayNotification.ts
- src/app/Scenes/Home/Components/ActivityRail.tests.tsx
- src/app/Scenes/Home/Components/ActivityRail.tsx
This PR resolves [ONYX-756]
Hides notifications which do not have published viewing rooms / article within them.
#nochangelog
[ONYX-756]: https://artsyproduct.atlassian.net/browse/ONYX-756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(onyx-756): hide unpublished viewing room / editorial notifications from activity panel

- src/app/Scenes/Activity/Activity.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/ActivityList.tsx
This PR resolves [ONYX-738] 
This PR makes some updates to the activity screen in order to improve it's performance. These updates include:
- Using memo for activity item components
- Setting a header height to avoid the layout calculation and jumps
- Lazy load images thanks to using `LazyFlatlist` component from `palette-mobile`.
- Setting Flex height and width in image containers to avoid layout calculation 
**I recommend to hide white spaces when reviewing this**
https://github.com/artsy/eigen/assets/11945712/18e0574f-20ab-4249-a0fc-b00923d6818b
- Improve Activity screen performance - mounir
-
-
-
</details> …
> feat: Improve Activity screen performance

- src/app/Scenes/Home/Components/ActivityRail.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
- src/app/Scenes/Home/Home.tsx
This PR resolves [ONYX-660] 
This PR removes the activity type filter for the home screen's Activity rail and adds logic to get a preview image for all notification types. The missing preview images were the reason why we introduced the filter initially.
The logic to get a preview image could also be implemented in Metaphysics or Gravity, but I thought it might be more complex because we need data from additional associations, such as 'article'.
In case an image cannot be loaded (because of some missing data or if we introduce a new notification type, we display a gray box, which should be ok since it's an edge case.
- Display images for all Activity types in the home screens Latest Activity rail - ole
- Remove activity type filter from …
> feat: Display all notifications in Activity rail and add preview image

- src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/ArtworkPublishedNotification.tests.tsx
Removing the "Edit Follows" button from notification screen. I've accidentally added it again because I haven't seen [this](https://www.notion.so/artsy/Should-we-remove-Edit-Alert-CTA-as-well-as-Edit-Follows-CTA-cc-117ce6c3fbfa40ac896e8ffb48e8f4c9?pvs=4) card from the QA session.
- [Context](https://www.notion.so/artsy/Should-we-remove-Edit-Alert-CTA-as-well-as-Edit-Follows-CTA-cc-117ce6c3fbfa40ac896e8ffb48e8f4c9?pvs=4)
-
-
-
-
</details>
> fix: Remove "Edit Follows" button from notification screen

- src/app/Scenes/Activity/hooks/useMarkAllNotificationsAsRead.ts
- src/app/Scenes/Activity/hooks/useMarkNotificationsAsSeen.ts
- src/app/Scenes/Activity/mutations/useMarkNotificationAsRead.ts
This PR resolves [ONYX-750] 
Correctly update unreadNotificationsCount when reading notification.
- Correctly update unreadNotificationsCount when opening a notification/activity - ole
-
-
-
</details>
[ONYX-750]: https://artsyproduct.atlassian.net/browse/ONYX-750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Correctly update unreadNotificationsCount when reading notification

- src/app/Scenes/Activity/ActivityEmptyView.tsx
This PR resolves [ONYX-778] 
Match Alerts filters empty states to the design
[Figma](https://www.figma.com/file/PO3rjpDV29YOFR8kLI4InJ/Activity-Panel-%26-Alerts-Management?node-id=2766%3A4986&mode=dev)
| All | Alerts | Follows |
| ![image](https://github.com/artsy/eigen/assets/36167539/c1e9494a-4b01-4ea5-820e-d10827a593c2) | ![image](https://github.com/artsy/eigen/assets/36167539/894042cf-aaa7-4b59-b3a3-fd73a2a37403) | ![image](https://github.com/artsy/eigen/assets/36167539/32cf3a2f-cc7a-4de5-9cb1-8837b2dc9b61) |
- match Alerts filters empty states to the design  (behind a ff) - daria
-
-
-
</details> …
> feat(ONYX-778): match Alerts filters empty states to the design

- package.json
- src/app/Scenes/Activity/NewActivityScreen.tsx
- yarn.lock
Resolves https://www.notion.so/artsy/All-grey-lines-are-the-same-light-grey-Currently-in-the-build-the-top-line-is-darker-should-be-ch-1f007c0745654e1ca995194a294db279?pvs=4
- https://github.com/artsy/palette-mobile/pull/192
Make Activity header divider lighter.
- Make Activity screen header divider lighter - ole
-
-
-
</details>
> fix: Make Activity screen header divider lighter

- ios/Podfile.lock
- package.json
- yarn.lock
Use the same RN-blurhash version as in palette. 
I did this instead of upgrading palette to 2.0.0 because the latter breaks the android build. See: https://app.circleci.com/pipelines/github/artsy/eigen/51084/workflows/4cbd18bd-534f-4eec-84d7-487b41e467be/jobs/175225
#nochangelog
> chore: use rn-blurshash 1.1.11

- src/app/Scenes/Activity/components/NewActivityHeader.tsx
This PR resolves [ONYX-757] 
Use totalCount for offer notifications because the workaround is not needed in production.
-
-
-
- Use totalCount for offer notifications - ole
</details>
[ONYX-757]: https://artsyproduct.atlassian.net/browse/ONYX-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Use totalCount for offer notifications

- src/app/Components/SwitchMenu.tsx
- src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchAlertSwitch.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchAlertSwitch.tsx
This PR is a follow-up on artsy/palette-mobile#197
This PR updates the use of the Switch toggle across the app from React Native to Palette Mobile's Switch component.
|---|---|---|
| Push - before | <img width="454" alt="image" src="https://github.com/artsy/eigen/assets/20655703/05d14c64-a38a-4db4-9834-8ed7a3879bec"> | ![image](https://github.com/artsy/eigen/assets/20655703/89c225dc-ebaf-4f32-8683-f10c96a47baf) |
| Push - after | <img width="453" alt="image" src="https://github.com/artsy/eigen/assets/20655703/def45f8c-aeb5-47db-945d-605bdf793c1d"> | ![image](https://github.com/artsy/eigen/assets/20655703/5a7c2153-0924-416d-b89d-1adc03ad366f) |
| Create Alert - before | <img width="454" alt="image" …
> fix: Use palette mobile's switch component

- src/app/Components/ArtworkLists/components/CreateOrEditArtworkListForm.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
- src/app/store/config/features.ts
This PR resolves [EMI-1715] 
>[!NOTE]
> This feature is hidden behind the newly created `AREnableArtworkListOfferability` feature flag
This PR adds a new switch to share artwork lists with partners for the Partner Offer feature.
|---|---|
| <img width="452" alt="image" src="https://github.com/artsy/eigen/assets/20655703/0d42e997-baeb-4d25-aa95-4bfa9978039b"> | ![image](https://github.com/artsy/eigen/assets/20655703/e1406b11-53e4-4a3d-822c-f45428278241) |
- Add Share List toggle for Create New List (behind `AREnableArtworkListOfferability` FF) - mrsltun
-
-
-
cc @artsy/emerald-devs 
</details> …
> feat(EMI-1715): Add share list toggle in create new list

- src/app/Components/ArtsyWebView.tsx
- src/app/Scenes/Activity/ActivityList.tsx
- src/app/routes.ts
This PR resolves [ONYX-822] 
The ArtsyWebView uses SafeAreaView. SafeAreaView adds paddings to the top and bottom of the page to make sure the active area of the screen can be assessed. We do not need this padding if we are not presenting the screen modally. When we do not the screen modally we can use a react-native View instead of SafeAreaView
| Before iOS | After iOS | Before Android | After Android |
| ![image](https://github.com/artsy/eigen/assets/36167539/a4dc33e5-74cc-4bf2-b677-08301140edf7) | ![image](https://github.com/artsy/eigen/assets/36167539/3ca4f7eb-0964-41c5-b356-e8e9522615df) | ![Screenshot_1709343815](https://github.com/artsy/eigen/assets/36167539/58ba30f0-4c7d-4499-9c8a-dffc5eb2095d) | …
> fix(ONYX-822): fix broken ArtsyWebView paddings

- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
This PR resolves [ONYX-825] 
Add missing Activity item divider when Activity Panel redesign feature flag is disabled.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-03-06 at 16 39 48](https://github.com/artsy/eigen/assets/4691889/08ded6a4-5a25-4292-ae6f-93b449916950) |![Simulator Screenshot - iPhone 15 Pro - 2024-03-06 at 16 39 10](https://github.com/artsy/eigen/assets/4691889/2ff666e3-cf6f-4bd8-b166-70b690d935a5) |
|![Simulator Screenshot - iPhone 15 Pro - 2024-03-06 at 16 39 28](https://github.com/artsy/eigen/assets/4691889/3e74abe4-32e4-414e-80b5-026f6ab1e1ef) | ![Simulator Screenshot - iPhone 15 Pro - 2024-03-06 at 16 39 20](https://github.com/artsy/eigen/assets/4691889/d93599b2-14d0-47e3-8010-cc80c5535d19)| …
> fix: Missing Activity item divider

- src/app/system/devTools/DevMenu/DevMenu.tsx
Adds revert sort ability on ff dev menu:
-
-
-
- Adds revert sort ability on ff dev menu - gkartalis
</details>
> feat: add revert sort ability on ff dev menu

- src/app/Scenes/Activity/ActivityItem.tests.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
- src/app/Scenes/Activity/utils/getNotificationTypeLabel.ts
- src/app/Scenes/Activity/utils/shouldDisplayNotificationTypeLabel.ts
- src/app/Scenes/Home/Components/ActivityRail.tests.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
Resolve [ONYX-825](https://artsyproduct.atlassian.net/browse/ONYX-825)
- [Slack Discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1709544179604239)
This PR adjusts the "Latest Activity" rail items to match new design:
* Alert & Follow notifications: Artist name should be dropped to second line 
* Offer notifications: remove ‘Saved work by’ so just the name displays
* 240px width for each activity
* Text readjustments
[Figma Design](https://www.figma.com/file/PO3rjpDV29YOFR8kLI4InJ/Activity-Panel-%26-Alerts-Management?type=design&node-id=1001-21829&mode=design&t=wyetZPbufCxQsXZ7-0)
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-03-11 at 09 52 34](https://github.com/artsy/eigen/assets/4691889/270f4d7e-88d8-4bbb-b0d0-8332172c8575) |![Simulator …
> fix(ONYX-825): "Latest Activity" rail item design fixes

- src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingPartnerListItem.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx
[Ticket](https://www.notion.so/artsy/Follow-button-loading-state-broken-in-onboarding-d71c5f4f193f404798a0265de1a2cb35) from mobile QA session.
|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/022c07d1-b64e-434d-a39c-846d1206f443" width="350" />|<video src="https://github.com/artsy/eigen/assets/21178754/eafc8984-a16d-462f-b86f-827bec48ea12" width="350" />|
-
-
-
- onboarding follow galleries follow btn state - gkartalis
</details>
> fix: onboarding follow galleries follow btn state

- src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
This PR resolves [ONYX-736]
Previously - when there is only 1 matching artwork - no artworks were displayed at all. This PR solves this issue:
#nochangelog
</details>
[ONYX-736]: https://artsyproduct.atlassian.net/browse/ONYX-736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: display alert artworks grid when there is only 1 artwork

- src/app/Scenes/SavedSearchAlert/AlertArtworks.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tests.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworksPills.tsx
This PR resolves [ONYX-736]
In before video, when I add/remove pills and go back to the previous screen - neither artworks grid or pills are updated. This PR makes the View Artworks screen to forcefully refetch data to reflect changes.
|---|---|
| <video src="https://github.com/artsy/eigen/assets/3934579/859f1c6e-5743-4cfc-88e9-f2faba95349f" /> | <video src="https://github.com/artsy/eigen/assets/3934579/6b325211-53fb-420b-b246-e297e4e9634f" /> |
#nochangelog
[ONYX-736]: …
> fix(onyx-736): refetch pills and artworks when navigating to alerts View Artworks screen

- src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
This PR resolves [EMI-1759] 
This PR fixes an issue with the "Continue to Purchase" button in the Partner Offer screen from the Activity Panel
The issue was the Continue to Purchase button would go on to create an order to the artwork without applying the offer on the price, hence breaking the flow of the Partner Offer feature
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/9a16d991-a83a-4017-9e09-caa993ddcd67" /> | <video src="https://github.com/artsy/eigen/assets/20655703/a4648701-2acc-413a-910e-c015d56526ae" /> |
- Fix the "Continue to Purchase" button in the Partner Offer Activity screen - mrsltun
-
-
-
</details>
[app …
> fix: Update Activity panel Partner Offer purchase button

- docs/getting_started.md
This line reads like a step but this should happen automatically so there is nothing to be done for contributor. 
#nochangelog
> docs: remove confusing line from getting started #trivial

- HACKS.md
- ios/Artsy.xcodeproj/project.pbxproj
- ios/Podfile
- ios/Podfile.lock
- patches/react-native-fast-image+8.6.3.patch
This PR resolves [PHIRE-753] 
Updates SDWebImage to the latest which adds a privacy manifest to comply with apple requirements. 
Since we get this from react-native-fast-image and there is not a release that supports latest yet a patch had to be added.
Once this issue is resolved we can remove and update to the latest version.
https://github.com/DylanVann/react-native-fast-image/issues/1031
Images appear to work fine after the update:
-
-
- 
- update SDWebImage to the latest, patch react-native-fast-image - Brian 
</details>
[docs]: …
> chore: upgrade sdwebimage

- src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
- src/app/Scenes/Search/components/AutosuggestSearchResult.tests.tsx
- src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
- src/app/Scenes/Search/components/ResultWithHighlight.tsx
> [!IMPORTANT]  
> As a reminder, **any** time we present a list of artists from which a user will select, we should also display disambiguating info: nationality, birth date, death date.
This PR resolves [ONYX-231] 
This addresses a long-standing issue in MyC: we do not consistently display disambiguating info about artists, which increases the risk of misattributed artworks and duplicative artist data entering the platform.
If you're thinking there's already disambiguating info in the **Before** screenshots below — that's true, but only because people have abused one of the other name fields, presumably in response to ambiguous displays somewhere in the product:
The better we are about displaying the disambiguating info, the less the chance of that happening.
|Before|After (iOS)|After …
> feat(my collection): present disambiguating info when selecting an artist

- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
This PR resolves [APPL-857]
Steps to reproduce: Go to Alerts screen, tap on an alert, delete it -> you can still see the alert in the list.
Why this happened: I've added state for keeping `alertsConnection` to deal with some slide-to-delete things. When `alertsConnection` changes - state becomes stale. I'm not sure if what I'm doing is a good approach, I'm open to suggestions.
Fixed behaviour demo:
<video src="https://github.com/artsy/eigen/assets/3934579/15f909aa-2fa4-4ad1-b0eb-c684f77fd393" width="400px;" />
-
-
-
- bugfix: fix stale alerts staying on alerts screen after deletion - @nickskalkin 
</details> …
> fix: fix stale alerts staying on alerts screen after deletion

- src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
- src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
- src/app/Components/Bidding/Screens/Registration.tests.tsx
- src/app/Components/Bidding/Screens/Registration.tsx
This PR updates the copy and link of the disclaimer displayed on the "confirm bid" step. It also updates the link on the "register to bid" step that was previously missed.
|-------|-------|
| ![before_ios](https://github.com/artsy/eigen/assets/44589599/8af30865-a1e1-41bf-88ea-50c0c7d78140) | ![after_ios](https://github.com/artsy/eigen/assets/44589599/a9778b33-db8d-429f-b62d-83b9d18e5454) |
| ![before_ios_checkbox](https://github.com/artsy/eigen/assets/44589599/83a630b0-cd21-4db6-9fc6-01da1fa76349) | ![after_ios_checkbox](https://github.com/artsy/eigen/assets/44589599/4a7d6673-2d22-4b89-83ae-5e07a21a5b27) |
| ![before_android](https://github.com/artsy/eigen/assets/44589599/fce5bb0e-b3cf-4bd7-9c40-628745d3aa06) | …
> feat: navigate users to terms and conditions when bidding (DIA-546)

- .circleci/config.yml
- ios/Podfile.lock
- patches/react-native-image-crop-picker+0.38.1.patch
our patch for finding the root window in the photo stopped working reliably, this updates the window finding to a more robust method. 
It is still not totally clear why / under what conditions this doesn't work, it might be an iOS update or another dep update that broke it. 
- There are issues in the upstream repo about windows not being found? Maybe we could contribute this back if this is the root of the problem?
-
- Fix photo picker crash - Brian + George 
-
-
</details>
> fix: photo picker crash

- src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
- src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/components/ArtworkListOfferSettingsHeader.tsx
- src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
This PR resolves [EMI-1787] 
This PR swaps the positions of the "Create New List" button and the "Offer Settings" button
as well as capitalizing the S in "Offer Settings" across the app
|---|---|---|
| Feature Flag Enabled | <img width="466" alt="image" src="https://github.com/artsy/eigen/assets/20655703/272a1878-520f-4969-801f-6f4286b7eef7"> | ![image](https://github.com/artsy/eigen/assets/20655703/b9423722-b2b4-4b1a-a76f-7110c8bcda00) |
| Feature Flag Disabled | <img width="466" alt="image" src="https://github.com/artsy/eigen/assets/20655703/b6c8887a-2b2a-4f32-a475-a8515b15f501"> | ![image](https://github.com/artsy/eigen/assets/20655703/720e07ef-a6b7-483c-82cd-d0de5cb5fdc3) |
- Update buttons positions in Saves header + …
> fix(EMI-1787): Swap positions of Create New List and Offer Settings buttons

- ios/Podfile.lock
- src/app/Components/Artist/ArtistAbout/ArtistAboutShows.tsx
- src/app/Components/ShowItem.tests.tsx
- src/app/Components/ShowItem.tsx
- src/app/Scenes/Activity/ActivityItemScreen.tsx
- src/app/Scenes/Activity/components/AlertNotification.tsx
- src/app/Scenes/Activity/components/PartnerShowOpenedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/PartnerShowOpenedNotification.tests.tsx
This PR resolves [ONYX-722] 
This PR implements the Partner Show Opened notification screen (+ a small adjustment to the partner notification title in the Activity rail on the home screen).
**Note:** We have updated the design because the original design was not suitable for notifications with more than one show.
| Rail | Screen |
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-04-08 at 11 06 56](https://github.com/artsy/eigen/assets/4691889/7942819c-f92e-4617-ae5c-ec07e5ca481a) |![Simulator Screenshot - iPhone 15 Pro - 2024-04-10 at 11 51 22](https://github.com/artsy/eigen/assets/4691889/8851c509-5711-4c28-9898-629c3c90e092) |
- Partner Show Opened notification screen - ole
- Partner Show Opened notification title fix in "Latest …
> feat: Partner Show Opened notification screen

- src/app/store/config/features.ts
This PR marks the `AREnableNewTermsAndConditions` feature flag as ready for release so that it can be turned on in the next release.
#nochangelog
> feat: make AREnableNewTermsAndConditions releasable

- ios/Podfile.lock
fix boost on podfile.lock.
Was getting a diff even after running `cd ios && bundle exec pod update boost && cd ..` so I went ahead and opened a pr for it.
#nochangelog
> chore: fix boost on podfile.lock

- src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tests.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
This PR updates the disclaimer that is displayed when a user enters their full name during sign-up.
|-------|------|
| ![Simulator Screenshot - iPhone 15 Pro - 2024-04-12 at 08 30 17](https://github.com/artsy/eigen/assets/44589599/ee7877e4-5a8f-4e10-8902-1dbcf97df040) | ![Simulator Screenshot - iPhone 15 Pro - 2024-04-12 at 08 30 39](https://github.com/artsy/eigen/assets/44589599/b11653bf-f806-4aa0-afc4-dcbe5d1c5934) |
| ![Screenshot_1712925362](https://github.com/artsy/eigen/assets/44589599/a0a68913-5614-4138-8554-d7d07b80e6f4) | ![Screenshot_1712925353](https://github.com/artsy/eigen/assets/44589599/d80bf6f0-fb4e-4828-b979-25a3a504cb55) |
- Displays a new disclaimer to agree to terms and conditions when signing up (behind a feature flag)
> feat: update terms of service checkbox (DIA-552)

- src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
- src/app/store/AuthModel.ts
This PR resolves [PHIRE-784] 
Removes the warning popup - "no artsy account found" when user cancels the sign in / sign up flow (see videos below)
|Before|After|
|---|---|
|<video width="400" src="https://github.com/artsy/eigen/assets/21178754/da10080c-2558-4c5c-83de-93fedac8a332" />|<video width="400" src="https://github.com/artsy/eigen/assets/21178754/2fd07839-d271-4bcc-8730-8563ad0ef41f" />|
- google signup / singin on cancel improvement - gkartalis
-
-
-
</details>
[PHIRE-784]: …
> fix: google signup / singin on cancel improvement

- src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
This PR resolves [APPL-883]
Recently we've added nationality / birth year info label to artist search results. The gap between search results became too small when there is such label.
| Before adding disambiguating info | Before this change | After |
|---|---|---|
| <img src="https://github.com/artsy/eigen/assets/3934579/78130ce8-bde6-484f-acb3-5793e7afee9b" /> | <img src="https://github.com/artsy/eigen/assets/3934579/72694ab1-8bd8-4344-a64e-85952bc2fc40" /> | <img src="https://github.com/artsy/eigen/assets/3934579/8c4cf43a-856b-4c99-8beb-f045959eef44" /> |
#nochangelog …
> fix(appl-883): fixes Search results displayed too closely as though overlapping on search page

- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingOfferSettings.tests.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingOfferSettings.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSignalInterest.tsx
This PR resolves [APPL-871] 
This PR fixes the issue in Android where the screen gets frozen after navigating to the Saves tab
It also fixes the issue where two back-to-back onboarding popovers that weren't working well
https://github.com/artsy/eigen/assets/20655703/ee212051-150a-4194-8355-00f9e953ec61
|---|---|---|
| back to back popovers | <video src="https://github.com/artsy/eigen/assets/20655703/25d6b53f-d7a7-43aa-95be-74efbbe6342b" /> | <video src="https://github.com/artsy/eigen/assets/20655703/cd2b60f4-b50f-4301-9b51-1aa0cdc013a2" /> |	
- Fix frozen saves tab + fix back-to-back popovers issue - mrsltun
-
-
-
</details> …
> fix: make the screen responsive again

- src/app/Components/Cards/SmallCard.tsx
- src/app/Scenes/Show/ShowContextCard.tests.tsx
This PR resolves [APPL-875] 
Updates small grid to use fast image since currently the image from palette mobile doesn't allow only passing an aspect ratio + doesn't respect flex styles. 
The red boxes in before images are a dev only thing, rendering as gray boxes in prod.
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
- [] I have tested my changes on **iOS** and **Android**.
- Fix image display in viewing rooms list, gallery details, show details
-
-
-
</details>
[docs]: …
> fix: images in view in room, gallery, show not rendering

- package.json
- yarn.lock
bumps @artsy/palette-mobile from 13.1.29 to 13.1.30
#nochangelog
> build(deps): bumps @artsy/palette-mobile from 13.1.29 to 13.1.30

- src/app/Scenes/AuctionResult/AuctionResult.tsx
This PR resolves [APPL-896] 
Fixes auction results title going out of screen. (ignore the red color, it was added to display what changed)
|Before|After|
|---|---|
|<img width="364" alt="Screenshot 2024-04-19 at 14 39 48" src="https://github.com/artsy/eigen/assets/21178754/ced6331e-a8bf-4607-b0aa-369fc254b894">|<img width="366" alt="Screenshot 2024-04-19 at 14 39 20" src="https://github.com/artsy/eigen/assets/21178754/c54a7558-422a-4954-ac86-90f63c1581c9">|
-
-
- auction results title out of screen - gkartalis
-
</details>
[docs]: …
> fix: auction results title out of screen

- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtworkPrice.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkPrice.tsx
- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
- src/app/Scenes/Artwork/Components/ExpiresInTimer.tsx
- src/app/Scenes/Artwork/utils/formattedTimeLeft.ts
- src/app/Scenes/Artwork/utils/formattedTimeLeftForPartnerOffer.ts
This PR resolves [EMI-1766] 
> [!NOTE]
> This work is hidden behind `AREnablePartnerOfferV1Improvements` feature flag
This PR adds the partner offer details in the artwork screen
It also removes the `Exclude shipping and taxes` label from the artwork screen
And refactors a few tests 
|---|---|---|
| Android | <img width="469" alt="image" src="https://github.com/artsy/eigen/assets/20655703/598cf3f5-438e-45fe-9ec3-1afaa746d721"> | <img width="469" alt="image" src="https://github.com/artsy/eigen/assets/20655703/11c63587-ec7c-4fda-84c2-c4077a8c45b3"> |
| iOS | ![image](https://github.com/artsy/eigen/assets/20655703/f667408e-a5d1-436f-a0a8-19cc1997a4f7) | ![image](https://github.com/artsy/eigen/assets/20655703/08d4dd9e-a2ef-4bee-bfbf-f7623d5963c0) | …
> feat(EMI-1766): Show partner offer details on Artwork screeen

- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtworkPartnerOfferNote.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkPartnerOfferNote.tsx
This PR resolves [EMI-1781] 
> [!NOTE]
> This work is hidden behind `AREnablePartnerOfferOnArtworkScreen` feature flag
This PR adds the partner offer note, if available, to the artwork screen
|---|---|---|
| with icon | ![image](https://github.com/artsy/eigen/assets/20655703/4088f836-a952-4d95-be04-547a9d2be819) | <img width="542" alt="image" src="https://github.com/artsy/eigen/assets/20655703/4903ff59-7f0e-41fe-b6f6-33e118b04840"> |
| without icon | ![image](https://github.com/artsy/eigen/assets/20655703/7948a826-172d-4cae-934c-638519856353) | <img width="542" alt="image" src="https://github.com/artsy/eigen/assets/20655703/0e2800ee-1a2a-4f51-834a-305183970eed"> |
- Add parter offer note to artwork screen (behind FF …
> feat(EMI-1781): Add Partner Offer note in the artwork screen

- ios/Podfile.lock
- src/app/Scenes/Activity/components/NotificationArtworkList.tsx
- src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
- src/app/Scenes/Artwork/Components/ArtworkPartnerOfferNote.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkPartnerOfferNote.tsx
- src/app/Scenes/Artwork/Components/ArtworkPrice.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkPrice.tsx
- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
- src/app/Scenes/Artwork/Components/ExpiresInTimer.tsx
- src/app/Scenes/Artwork/hooks/useCreateOrder.ts
- src/app/Scenes/PartnerOffer/PartnerOfferContainer.tsx
- src/app/Scenes/PartnerOffer/mutations/usePartnerOfferCheckoutMutation.tsx
This PR resolves [EMI-1753] 
This PR changes the behavior of the purchase button when a partner offer is available. It was a little tricky because the button is also used in our partner offer notification panel.
I started out by following the patterns we used in artsy/force#13647 and its followup PRs, but ran into some typing issues due to the re-use of the button and the need to add our own checkout link (gravity attaches one to the notification which is separate from the object we are querying here). Ended up piggybacking off of work in #10085 and #10117 to make sure we didn't duplicate each other's work.
In the process I also converted some order creation mutations to the `useMutation => Promise` style for more consistent response handling, which also means that the creation action …
> feat: [EMI-1753] artwork screen partner offer button behavior

- ios/Podfile.lock
Fixes podfile.lock changes.
In order to stop getting the diff locally you need to run the following commands:
```bash
cd ios && bundle exec pod update boost && bundle exec pod update DoubleConversion && bundle exec pod update glog && cd ..
```
#nochangelog
> fix: podfile.lock diff

- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
This PR resolves [ONYX-892]
Recently we migrated alerts from using stitched gravity schema to a new un-stitched one. During this migration I made a mistake an started sending alert ID instead of search criteria ID as part of `toggleSavedSearch` (which tracks created alerts) payload. This resulted to a broken statistics in Looker.
-
-
-
- fixes bug in alerts tracking - @nickskalkin 
</details>
[ONYX-892]: https://artsyproduct.atlassian.net/browse/ONYX-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
> fix(onyx-892): fixes bug in alerts tracking

- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
This PR resolves [EMI-1844](https://artsyproduct.atlassian.net/browse/EMI-1844)
Purchase button was not properly displayed on artwork screen in some cases when the artwork had a partner offer. This PR updates the logic and expands the test cases to cover (hopefully) all major scenarios.
- Show Purchase button properly on artwork screen when there is a partner offer - starsirius
-
-
-
</details>
[EMI-1844]: https://artsyproduct.atlassian.net/browse/EMI-1844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> feat: show Purchase button properly on artwork screen when there is a partner offer

- src/app/Scenes/Artwork/Components/AboutArtist.tests.tsx
- src/app/Scenes/Artwork/Components/AboutArtist.tsx
Support for private artworks: This fixes things so we only display the partner bio section if isUnlisted is true and displayPartnerBio isn't false. Also updated the tests to use latest relay patterns. 
cc @artsy/amber-devs
> fix(artwork): only show partner bio if enabled

- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
This PR is a follow-up on #10144
This PR includes a missing state when the artwork is only inquiriable with a partner offer to show the Purchase button
It also refactors the tests for the ArtworkCommercialButtons component
<details>
<summary>Details</summary>
| | State |
|---|---|
| `isAcquireable` + `isOfferable`  | <img src="https://github.com/artsy/eigen/assets/20655703/fa086921-be8f-4ed1-9d7f-62b5f5c5f9dc" width="320" /> |
| `isAcquireable`  | <img src="https://github.com/artsy/eigen/assets/20655703/074bfcab-d456-4e08-bcdc-26a6d92a9a9b" width="320" /> |
| `isOfferable` + `isInquireable `  | <img src="https://github.com/artsy/eigen/assets/20655703/5b696d7d-d8aa-4012-80b3-f837f71fd0d7" width="320" /> |
| `isOfferable`  | <img …
> fix: follow up on Purchase button on artwork screen with partner offer

- src/app/Scenes/Artwork/Components/AboutArtist.tests.tsx
- src/app/Scenes/Artwork/Components/AboutArtist.tsx
Related:
- https://github.com/artsy/force/pull/13809
Only show artsy bio, and make sure to still show rest of artist section if bio is disabled.
cc @artsy/amber-devs
> fix(private-artworks): Defer to artsy bio

- src/app/Scenes/Articles/News/ArticlesCards.tsx
This PR resolves [DIA-609] 
This PR removes the thumbnail from the news element in the Home screen.
- feat: remove thumbnails from news section in home screen - araujobarret
-
-
-
</details>
[DIA-609]: https://artsyproduct.atlassian.net/browse/DIA-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-609): remove news thumbnail

- src/app/Components/WorksForYouArtworks.tests.tsx
- src/app/Components/WorksForYouArtworks.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/RecommendedAuctionLots/RecommendedAuctionLots.tsx
This PR resolves [ONYX-932] 
Some cached data persists when navigating between “New Works for You” and “Auction Lots for You” This change avoid displaying wrong cached data when rendering artworks for you by changing the Relay cache policy.
- Avoid displaying wrong cached data etween “New Works for You” and “Auction Lots for You” - ole
-
-
-
</details>
[ONYX-932]: https://artsyproduct.atlassian.net/browse/ONYX-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Avoid displaying wrong cached data when rendering artworks for you

- ios/Artsy/Views/Notifications/ARNotificationView.m
This PR resolves [PHIRE-848] 
Fixes text being cut off in certain in app notifications due to a bad width calculation for the text field.
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
-
- fix in app notification text cut off - Brian 
-
-
</details>
[PHIRE-848]: https://artsyproduct.atlassian.net/browse/PHIRE-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: in app notification text cut off

- src/app/Components/ArtworkLists/components/CreateOrEditArtworkListForm.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
This PR resolves [EMI-1785] 
This PR updates the input field inside the Create/Edit Artwork List bottom sheet to show `* Required`
It also adds tests for the character limit 
|---|---|
| ![image](https://github.com/artsy/eigen/assets/20655703/b1c642a0-ca95-4839-af80-663e07627154) | ![image](https://github.com/artsy/eigen/assets/20655703/f8eb9fda-bdf5-40b6-8d58-5c15bca11b5d) |
- update create/edit artwork list input field to show `required` - mrsltun
-
-
-
</details>
[EMI-1785]: …
> fix(EMI-1785): Update create/edit artwork list name input design

- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
As part of the private artworks project, we want to ensure that collectors know which artworks are private. The collector facing terminology that we are using is exclusive access and we want to update this across artsy wherever a private artwork is being viewed.
We want to update this for the artwork panel which is used across the website. An example being on the saved artworks page, or the recently viewed Rail.
#nochangelog
[AMBER-551]: https://artsyproduct.atlassian.net/browse/AMBER-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(AMBER-551): Update Artwork information panel (Mobile)

- src/app/Components/Expandable.tsx
- src/app/Scenes/Artwork/Artwork.tests.tsx
- src/app/Scenes/Artwork/Components/AboutArtist.tests.tsx
- src/app/Scenes/Artwork/Components/AboutArtist.tsx
- src/app/Scenes/Artwork/Components/PrivateArtwork/PrivateArtworkExclusiveAccess.tsx
- src/app/Scenes/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
- src/app/Scenes/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkMetadata.tests.tsx
This PR resolves [AMBER-592](https://artsyproduct.atlassian.net/browse/AMBER-592) 
Description
We want to add tracking to 5 behaviours found on [this spreadsheet](https://docs.google.com/spreadsheets/d/1zaFOn-bDKzYiK07sYoOYUwd7c4R5aAGzRA5oNmgZ5qs/edit#gid=0). If any of the methods do not already exist, then a separate PR will need to be made to Cohesion and to tag Louis so he can give feedback.
Some of the events were already being tracked (discussion [here](https://artsy.slack.com/archives/C05F8TNKGAV/p1714421942657479)) so I left those as is
This PR also includes some test fixes because those tests were not running due to an incorrect filepath
- Bugfix for displaying artist bio on private artwork screen - Lily
- Adds tracking events for user …
> chore(tracking): Add Private Artwork Tracking (mobile)

- src/app/Scenes/Artwork/Artwork.tests.tsx
- src/app/Scenes/Artwork/Components/PrivateArtwork/PrivateArtworkExclusiveAccess.tsx
This PR resolves Fix for failing test when merged into main
Patch fix for failing test that was caused when [this PR ](https://github.com/artsy/eigen/pull/10178)was merged into main branch. Apologies all, I thought the PR being green was all good!
-
-
-
- Patch fix for failing test on main 
</details>
> Fix: Adds test-id to properly test tracking event fire

- src/app/Scenes/Inbox/Components/Conversations/Preview/ArtworkPreview.tsx
This PR resolves [AMBER-659](https://artsyproduct.atlassian.net/browse/AMBER-659)
and thank you to @brainbicycle for the [slack pair advice](https://artsy.slack.com/archives/C02BAQ5K7/p1714588769205339)
Artwork preview Images were no longer being displayed in conversation show page, for all conversations regardless of artworks listed level
When running in dev mode this error is evident and a red box is displayed
```
[OpaqueImageView2] Either an aspect ratio or specific dimensions or flex should be specified."
```
On production: the image is empty like so:
---
Bug Example:
https://github.com/artsy/eigen/assets/12748344/ac6a4b56-15fe-42bb-a877-428735be60ec
---
Fix Example:
https://github.com/artsy/eigen/assets/12748344/209b72f6-cd44-4fbc-955d-65efcd958619 …
> fix(conversations): Images no longer rendering on conversations

- src/app/Scenes/SellWithArtsy/Components/Footer.tsx
- src/app/Scenes/SellWithArtsy/Components/Header.tsx
- src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
- src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
- src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
- src/app/Scenes/SellWithArtsy/Components/StickySWAHeader.tsx
- src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
- src/app/Scenes/SellWithArtsy/index.tests.tsx
This PR resolves [ONYX-869] 
Reorganize Sell screen.
| | |
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-04-29 at 16 31 36](https://github.com/artsy/eigen/assets/4691889/35cdb9d6-d2e0-4d49-8059-0f8061f887e8) | ![Simulator Screenshot - iPhone 15 Pro - 2024-04-29 at 16 34 23](https://github.com/artsy/eigen/assets/4691889/d8f70b46-fcb7-4a95-b894-2b90c269801e)|
- Reorganize Sell screen - ole
-
-
-
</details>
[ONYX-869]: https://artsyproduct.atlassian.net/browse/ONYX-869?atlOrigin=eyJpIjoiNWRkNTljNz …
> feat: Reorganize sell screen

- ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedWallBasedVIRViewController.swift
This PR resolves [PHIRE-783] 
I couldn't reproduce view in room not working altogether but did see that we don't handle the unhappy path at all and fail silently when either a user is pointing a non-vertical surface or the cursor is initializing. This might lead people to think it isn't working. 
This adds a little error message to explain what is going on when an artwork cannot be placed:
-
- Add user facing errors to view in room - brian 
-
-
</details>
[PHIRE-783]: …
> fix: add error messages to view in room

- docs/adding_a_new_route.md
- src/app/store/GlobalStore.tsx
- src/app/system/navigation/ModalStack.tsx
- src/app/system/navigation/navigate.ts
- src/app/system/navigation/useReloadedDevNavigationState.tests.tsx
- src/app/system/navigation/useReloadedDevNavigationState.ts
- src/setupJest.tsx
**[Future-Friday]**
This PR fixes the broken dev reload inside Eigen. 
**Context:** When we first updated our navigation infra, we had a few attempts to fix this and it worked if the app didn't crash but it never worked if the app crashed. This made the DX unfortunately painful when you are building feature and make mistakes that require an app refresh.
> Note: The same hook needs to be used in nested independent navigation containers + it can also be used in Energy in case we have issues with that there.
```mermaid
graph TB
A[Start] ==> B{DEV?};
B -->|Yes| C{Same Session};
C --> |Yes | D{Cached Nav State};
D --> |Yes | E[Restore State];
%% D -.-> B;
B ---->|No| F[Go to Home];
C ---->|No| F[Go to Home];
D ---->|No| F[Go to Home];
```
**Before** …
> chore: fix broken dev reload

- src/app/Components/Expandable.tsx
- src/app/Scenes/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
- src/app/Scenes/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkMetadata.tests.tsx
This PR resolves  bug reported by Louis on data team
Toggling the metadata component was firing a pagview event and not a toggled accordion event type
This code changes the event structure from
this:
```
{"context_module": "aboutTheWork", "context_owner_type": "artwork", "expand": true, "subject": "Condition"}
```
to this:
```
{"actionType": "toggledAccordion", "context_module": "aboutTheWork", "context_owner_type": "artwork", "expand": true, "subject": "Condition"}
```
-
-
-
- Adjust tracking event action type to be of ToggledAccordion
</details> …
> fix(tracking): Private artwork metadata toggle event is firing as a page view event

- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
Same as https://github.com/artsy/force/pull/13849 - Force/Eigen hardcode submission status labels and help messages.  We've moved this logic to `myCollectionConnection...consignmentSubmission` MP field (https://github.com/artsy/metaphysics/pull/5702) and in this PR we are replacing old "hardcoded" data with the new one taken from MP. Nothing should change visually, so I am not attaching screenshots.
#nochangelog
[ONYX-915]: https://artsyproduct.atlassian.net/browse/ONYX-915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> feat(onyx-915): use new consignmentSubmission MP fields when rendering submission state section

- .secrets.baseline
- scripts/detect-secrets/secrets-generate-baseline
This adds to the `.secrets.baseline` the plugins released in new version and also updates `secrets-generate-baseline` script to include an exclusion that is in the baseline but not in that script.
- add plugins to `.secrets.baseline`
- add an exclusion to `secrets-generate-baseline` script
> chore: regenerate .secrets.baseline

- ios/Artsy/App/main.m
- src/app/Scenes/MyAccount/updateMyUserProfile.ts
- src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
- src/app/Scenes/MyProfile/MyProfileHeader.tsx
The glitch of not showing the header on the profile screen was gone once I:
- removed the `@refetechable` annotation from the fragment(I don't know why someone would do it, this annotation should be only used with useRefetachableFragment hook, not with useFragment)
- force the query to run on the network
There are some extra things to be removed but it's a bit out of the scope of this fix, I'm handling it on behalf of Diamond but just to clarify it wasn't introduced by us.
Highly appreciate it if someone could test and merge this PR(tomorrow I will be roaming around some trains and then go for holidays)
https://github.com/artsy/eigen/assets/15792853/ae747c5e-e460-4977-a456-022846d9d425
https://github.com/artsy/eigen/assets/15792853/b333177e-11d6-4021-803c-c9fc1e6bf9c1 …
> fix: broken profile header when navigating fast

- src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
[ ](https://www.notion.so/artsy/Adding-a-P1-artwork-tooltip-not-showing-up-5fcae97fdde24d65a2bb25e25eb9c056?pvs=4)
We want to display "MyC Interested in selling" tooltip only for P1 artists. `artwork.artist?.targetSupply?.priority` is not a boolean and this PR adjusts the check
- Fix display "MyC Interested in selling" tooltip only for P1 artists - ole
-
-
-
</details>
> fix: display MyC Interested in selling tooltip only for P1 artists

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/acceptableCategoriesForSubmission.ts
This PR resolves [ONYX-955] 
This PR updates the artwork details screen to match the Figma designs. There are mainly two changes here: 
- Make the year input small
- Remove the rarity picker (including removing it from the validation schema for now + updating the list of accepted mediums)
- [The checkbox color in the design **doesn't** match the palette component, so I am using the palette component design now until I discuss this with Barney later if this change is intentional]
- [New SWA Flow] update artwork details screen to match new designs - mounir
-
-
-
</details> …
> chore(ONYX-955): update artwork details screen to match new designs

- src/app/Scenes/SellWithArtsy/Components/StickySWAHeader.tsx
- src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
**[Bug bash]**
This PR resolves [ONYX-950] 
This PR fixes the broken start selling button padding on Android
-
-
-
-
</details>
[ONYX-950]: https://artsyproduct.atlassian.net/browse/ONYX-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: broken start selling button padding on android

- fastlane/Fastfile
- fastlane/sentry_fastlane.rb
This PR resolves [PHIRE-915] 
Silences sentry errors when shipping builds to codepush, we do this every merge to main for both Android and iOS so in the event of a failure we get 2x messages to the practice-mobile channel. Will also fail in nightly betas if for example cli is out of date so we should still catch it. 
https://artsy.slack.com/archives/C02BAQ5K7/p1715942419895869
-
-
-
- silence sentry errors for codepush deploys - brian 
</details>
[PHIRE-915]: …
> chore: silence sentry noise for codepush deploys #trivial

- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
- src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
- src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
This PR resolves [ONYX-978] 
This PR adds support to initializing a submission from my collection. 
**Note:** While working on this I noticed a lot of code related to this in the global store that we can get rid of as soon as we release the feature and have a more clean global store. We can as well use it for the save & exit 🤷 
https://github.com/artsy/eigen/assets/11945712/de949e3d-b0c8-47dc-9ea8-23a34a4dd32d
- initialize submission from my collection artwork in new submission flow - mounir
-
-
-
</details> …
> feat: initialize submission from my collection artwork

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
This PR fixes broken validation on the artwork details screen
**Before**
https://github.com/artsy/eigen/assets/11945712/ae9ec3ba-c011-4b6a-a18d-d1c68dd0d484
**After**
https://github.com/artsy/eigen/assets/11945712/c62b8b00-8788-4b7e-979d-c3a36a7f289f
#nochangelog
#nochanges
> fix: broken medium validation

- src/app/AppRegistry.tsx
- src/app/Scenes/MyCollection/State/MyCollectionModel.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkFormEdit.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialNavigationState.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialSubmissionValues.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
- src/app/Scenes/SellWithArtsy/Components/Header.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
- src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
- src/app/Scenes/SellWithArtsy/utils/submissionModelState.tsx
- src/app/routes.ts
- src/app/store/__tests__/migration.tests.ts
- src/app/store/config/features.ts
- src/app/store/migration.ts
- src/app/utils/hooks/withSuspense.tsx
This PR resolves [ONYX-986] 
This PR makes the **Save & Exit** button in the new submission flow functional.
- The **Save & Exit** Button simply closes the modal or navigates you to the next screen
Expected behaviour:
- When the user taps on **Save & Exit**, we should save their progress, and allow them to continue from where they left when they tap on **Continue Previous Submission**
- Data to inject for the submission
- ~~Currently, I am saving the entire formik state and injecting it as it is, **However**, we can soon move toward saving only the submission id and querying for the data on screen mount. I didn't do that initially because we are going to get rid of this logic once we back up submissions with my collection artworks and have cross platform save and exit experience.~~
- …
> feat(ONYX-986): support save and exit in new submission flow

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
This PR resolves [ONYX-996] 
This PR hides the keyboard after each step on the new submission flow
#nochangelog
[ONYX-996]: https://artsyproduct.atlassian.net/browse/ONYX-996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: hide keyboard after each step on new submission flow

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
This PR resolves [ONYX-1009] 
This PR shows **Exit** if the user has the save and exit feature flag disabled
https://github.com/artsy/eigen/assets/11945712/539ede38-35bf-449e-a83f-f2d314b2e11e
#nochangelog
[ONYX-1009]: https://artsyproduct.atlassian.net/browse/ONYX-1009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: show exit if save and exit ff is disabled

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
This PR resolves [ONYX-1001] [ONYX-1006] 
This PR makes the following changes
- remove required from the year input
- fix validation after continue and save
**Before**
https://github.com/artsy/eigen/assets/11945712/b61dfabf-df32-4340-9805-b7968acc775f
**After**
https://github.com/artsy/eigen/assets/11945712/42e0a3cd-e814-4705-81f9-dadff850e6c4
#nochangelog
[ONYX-1001]: https://artsyproduct.atlassian.net/browse/ONYX-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> fix: artwork details year issues

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
This PR resolves [ONYX-1010] 
This PR fixes the text alignment on the artist rejected screen
#nochangelog
[ONYX-1010]: https://artsyproduct.atlassian.net/browse/ONYX-1010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: eligibility alignment on artist rejected screen

- src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tests.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
This PR resolves [PHIRE-949] 
> [!IMPORTANT]  
> This is affecting users in production on Android only - iOS works as expected.
Android users (tested in Android 12) that are eligible for seeing the new popover on MyCollection are not be able to access or interact with anything in the app (Application Not Responding) when they press the profile icon.
This is due to a bug with the popover - it needs to wrap the whole component.
-
-
- android anrs due to popover in myc screen - gkartalis
-
</details> …
> fix: android anrs due to popover

- src/app/Components/LocationAutocomplete.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
This makes the location input dropdown visible when the keyboard is up in the My Collection artwork form.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-05-29 at 11 41 06](https://github.com/artsy/eigen/assets/4691889/85200c8c-3ec6-42ca-8afe-652589dfd208)|![Simulator Screenshot - iPhone 15 Pro - 2024-05-29 at 11 41 28](https://github.com/artsy/eigen/assets/4691889/2eec11b0-4efe-48bb-98f4-cb56a713d8de)|
- Make location input dropdown visible when keyboard is up in MyC artwork - ole
-
-
-
</details>
[docs]: …
> fix: Make location input dropdown visible when keyboard is up in MyC artwork form

- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/Components/NewWorksFromGalleriesYouFollow.tsx
- src/app/Scenes/RecentlyViewed/Components/RecentlyViewedArtworks.tsx
This PR resolves [APPL-933] 
Fixes a crash that was happening on masonry surfaces that we were changing the `numColumns` dynamically. This occurred only when the artworks array was empty.
|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/f9d921dd-542a-432b-8715-0a3c193771fe" width="400" />|<video src="https://github.com/artsy/eigen/assets/21178754/bd4928bc-8e75-4695-b031-2635c3261c2f" width="400" />|
|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/710fde47-a9ed-4763-880e-2210ef9a05c3" width="400" />|<video src="https://github.com/artsy/eigen/assets/21178754/a3b39d89-c756-4213-9c0e-d8b9d6e6694e" width="400" />|
- crash on masonry dynamic columns empty state - gkartalis
-
- …
> fix: crash on masonry dynamic columns empty state

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
This PR resolves [ONYX-1026] 
When we go back from a modal where we used a keyboard to the previous screen, it takes time for the keyboard to close. We need to make sure the keyboard is closed before navigating back.
In this PR we added a keyboard listener that allows us to know when the keyboard is closed. After the keyboard is closed, we navigate back to the previous screen.
- 
-
- navigate to the previous screen only after the keyboard is closed -daria
-
</details>
[ONYX-1026]: …
> fix(ONYX-1026): navigate to the previous screen only after the keyboard is closed

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
This PR resolves [ONYX-1034]
- Change title from "Purchase history" to "Where did you purchase the artwork?"
- Remove "The document history of an artwork's ownership and authenticity. Please add ..." text.
<details>
#nochangelog
</details>
[ONYX-1034]: https://artsyproduct.atlassian.net/browse/ONYX-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-1034): update purchase history step

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkProgressBar.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
This PR resolves [ONYX-1031]
Demo:
* In the recording progress bar is thin because I removed `height={4}`, but I brought it back as per design
https://github.com/artsy/eigen/assets/3934579/be010dce-41fb-40e5-87ad-a11950259d48
<details>
#nochangelog
</details>
[ONYX-1031]: https://artsyproduct.atlassian.net/browse/ONYX-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-1031): move sell progress bar to the top

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
- src/app/Scenes/SellWithArtsy/Components/StickySWAHeader.tsx
This PR resolves [ONYX-1026] 
Turned out the fix in this PR was breaking the flow ([that's why](https://github.com/artsy/eigen/pull/10321#pullrequestreview-2093435900)). We paired with Ole and decided to proceed with the solution which seems to work fine. We added a timeout to let the keyboard have more time to close and made the function asynchronous
Also, we found out that the issue is present on iOS as well, it's just not so obvious
- wait for the keyboard to close before navigating back on the Sell flow -daria
-
-
-
</details>
[docs]: …
> fix(ONYX-1026): start selling sticky button hoisted up (attempt 2)

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
- src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tests.tsx
- src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
- src/app/utils/refreshHelpers.tsx
With this fix, the Sell screen refetches the current draft submission when clicking "Save & Exit" in the submission form.
https://github.com/artsy/eigen/assets/4691889/437ee2c7-7fb2-4dcf-aac5-68beb65e74ce
https://github.com/artsy/eigen/assets/4691889/763da21c-e30f-4ff0-9ce5-f658027c933e
- Refresh Sell screen when updating the current draft submission (behind ff) - ole
-
-
-
</details>
> fix: Refresh Sell screen when updating the current draft submission

- src/app/Components/Select/Components/SelectModal.tsx
- src/app/Components/Select/Select.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialSubmissionValues.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
- Remove year input component
#nochangelog
> chore: make year component optional

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
Resolves https://www.notion.so/artsy/morning-build-artwork-is-not-in-my-collection-after-completing-the-flow-908968ea497349169b25862543e73efc?pvs=4
This sets the final step in the submission form correctly. 
I have accidentally set it to the last entry in `ARTWORK_FORM_STEPS`, which is not the final step before the submission gets submitted.
With this fix, an artwork in My Collection gets created after submitting the submission (because the state change from "DRAFT" to "SUBMITTED" happens and the "Add Phone Number" step now displays `Submit Artwork` instead of `Continue`.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-06-05 at 19 35 59](https://github.com/artsy/eigen/assets/4691889/da82195e-a580-4357-96af-b2e7c9c238c4) |![Simulator Screenshot - iPhone 15 …
> fix: Set final step in submission form correctly

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
```
After adding a non-p1 artist to mycollection, the flow loads but then goes back to the rejection screen
Link: https://www.notion.so/artsy/After-adding-a-non-p1-artist-to-mycollection-the-flow-loads-but-then-goes-back-to-the-rejection-scr-1db618b7dc05445c80635c4f2f982fca?pvs=4
```
https://github.com/artsy/eigen/assets/11945712/57d4c669-a3da-46b8-8c3c-ddd94bc87d10
#nochangelog
> fix: replace active route after starting my collection

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkProgressBar.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
- yarn.lock
This PR makes the following changes
- Make the progress bar round
- Add 10 pixels bottom padding to the progress bar
Related PR: https://github.com/artsy/palette-mobile/pull/235
#nochangelog
> chore: progress bar fixes

- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialSubmissionValues.ts
- src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosPhotoItem.tsx
This PR makes the following fixes:
- Make the full image clickable, no need for feedback here because it's not the main way to add an image and it could make deleting a photo experience worse
- Add hitslop to delete icon
- Fix delete artwork image after you tap on continue and save. This was broken because the id was missing ⭐ 
- Make the photos upload in parallel
- Show processing images instead of hiding them (with gray background - in production this is not going to be happening much)
Example:
Uploading Screen Recording 2024-06-06 at 09.44.16.mov…
_The images do not show up immediately because of processing, this is why I was waiting on the video before tapping on delete 😢_ 
https://github.com/artsy/eigen/assets/11945712/a64b8704-4824-440c-b2e8-96223bdc97a9 …
> chore: upload photos fixes

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhoneNumber.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddTitle.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
This PR fixes the issue where the keyboard gets visible after one opens the submission flow after pressing on continue your submission.
**Rationale:**
Because we inject a **partial** `initialState` in the `NavigationContainer` on mount. React-navigation has no reliable way to rebuilt the full `initialState` other than going through all the routes again. This means that if for example, the active step is `AddPhotos`, we will go through `StartFlow`, `SelectArtist` and `AddTitle`. And because `SelectArtist` and `AddTitle` both have inputs with autofocus, the keyboard then shows up there. I am fixing that by making sure that the input is only focused if the screen is active
**Before**
https://github.com/artsy/eigen/assets/11945712/9153de8f-60e4-4705-a400-776cc0278abc …
> fix: do not show keyboard on open after continue submission

- src/app/Scenes/Artwork/Components/ArtworkEditionSetInformation.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkEditionSetItem.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkEditionSetItem.tsx
- src/app/Scenes/Artwork/Components/ArtworkEditionSets.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkEditionSets.tsx
This PR resolves [EMI-1900] 
This PR fixes the issue with selecting already sold edition sets and navigating to the checkout flow
|---|---|---|
| Android | <video src="https://github.com/artsy/eigen/assets/20655703/a0de929b-103b-452a-99ad-76273fbd5151" /> | <video src="https://github.com/artsy/eigen/assets/20655703/e618fc74-d42a-478e-90a0-22e544ff6605" /> |
| iOS | <video src="https://github.com/artsy/eigen/assets/20655703/234a5dae-90ac-46a9-a81f-3adf6627cb1f" /> | <video src="https://github.com/artsy/eigen/assets/20655703/dfc893a3-0a17-4c92-8bbb-8aba8720cd3d" /> |
|---|---|---|
| Android | <video src="https://github.com/artsy/eigen/assets/20655703/7063aa53-5b6a-481b-a6f7-922e61aff6e3" /> | <video …
> fix(EMI-1900): Fix issue with sold edition sets being able to go to Purchase flow

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddTitle.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
This PR is an attempt to improve the performance of validation in the submit artwork flow.
**We have tested this on the QA session yesterday**
The idea behind this is the following:
- Formik validates values on change. This validation is done in the wrapper component `SubmitArtworkForm`. Given the massive children tree, it might take a few seconds for changes to see the validation taking effect. Hence the performance issues on the bottom navigation component. Since the bottom navigation component, is the **only** component that needs that validation, I am updating the logic to only validate the values there.
**Before**
https://github.com/artsy/eigen/assets/11945712/194e598e-da9b-4884-ac85-d04c1904f33e
**After**
https://github.com/artsy/eigen/assets/11945712/9aee3d8e-cf8a-4c75-bc6c-1e2ad297 …
> chore: improve validation performance

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
- src/app/store/config/features.ts
_Drafting some description in a big_ 
https://github.com/artsy/eigen/assets/11945712/63bc768c-f412-4efa-a149-9db48a5d5d4a
#nochangelog
> feat: dismiss modal before opening new submission flow

- src/app/Scenes/Artwork/Components/ArtworkDimensionsClassificationAndAuthenticity/ArtworkDimensionsClassificationAndAuthenticity.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkDimensionsClassificationAndAuthenticity/ArtworkDimensionsClassificationAndAuthenticity.tsx
This PR resolves [AMBER-715] 
As discussed with Peter, we want to explicitely indicate to the user when the frame is not included, not just by omission.
__Before:__
__After:__
-
- Adds 'Frame not included' to artwork details - lfp
-
-
</details>
[AMBER-715]: https://artsyproduct.atlassian.net/browse/AMBER-715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(AMBER-715): Add 'Frame not included' to artwork details

- .secrets.baseline
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Form/useArtworkForm.ts
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
- src/app/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
This PR resolves [ONYX-1047] 
This PR fixes an issue with submit artwork flow where the artist details remain saved. This is because we are using a global artwork form. I am fixing the issue here by making sure that the values are not injected if you are within the submit artwork flow. I believe this was needed for the old flow, but the way things are now, we don't need that anymore. In the short/mid term, we should not handle these values using the global store and instead sending them as props because there is no value in persisting them + making sure they are reset each time we leave the screen.
https://github.com/artsy/eigen/assets/11945712/2cb4e0f0-cf31-41a3-8d7b-cd4bf982d7dc
-
-
-
-
</details>
Need help with something? Have a look at our …
> fix: prefilled artist in my collection flow

- src/app/Scenes/BottomTabs/BottomTabsButton.tsx
This PR resolves [ONYX-1065] 
- Fix bottom tab icons height on tablets
#nochangelog
[ONYX-1065]: https://artsyproduct.atlassian.net/browse/ONYX-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: adjust bottom tab icons height on tablets

- src/app/AppRegistry.tsx
- src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx
This PR resolves [ONYX-1063] 
This PR fixes an issue with the contact information screen where the user can not leave the screen after they edit it. 
**Bonus:** I noticed that the bottom tabs are visible and hid them as well
https://github.com/artsy/eigen/assets/11945712/7b485c87-54ed-44a0-b3be-ecd4ecc5bc24
#nochangelog
[ONYX-1063]: https://artsyproduct.atlassian.net/browse/ONYX-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: leave without sending contact information

- src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx
This PR resolves [APPL-826] 
On android when we press the `skip` twice on onboarding it results into making the app unresponsive and then it crashes.
Debouncing the skip works as expected.
|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/5fc9c508-e7de-40a8-a1e5-ce4834628378" width="300" />|<video src="https://github.com/artsy/eigen/assets/21178754/8c57b7a2-0314-4b40-a0a9-c8655d2e8268" width="300" />|
-
-
- crash on android when pressing onboarding skip twice fast - gkartalis
-
</details>
[docs]: …
> fix: crash on android when pressing skip twice fast

- src/app/utils/hooks/useSelectedTab.ts
This PR comes as a follow-up on https://github.com/artsy/eigen/pull/10415
https://github.com/artsy/eigen/assets/11945712/a9f1ba91-b7d2-4060-9108-dd64fddff93a
-
-
-
-
</details>
> fix: useSelectedTab broken behaviour

- src/app/store/__tests__/GlobalStoreModel.tests.ts
> chore: add test for user agent fragility 

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tests.tsx
https://github.com/artsy/gravity/pull/17866
This PR resolves [AMBER-769] 
It now comes straight from Gravity, we don't need it set on the clients anymore
-
-
-
- Remove "Bidding closed" logic from the Artwork Grid implementation and fetch it from Gravity instead
</details>
cc @artsy/amber-devs 
[AMBER-769]: https://artsyproduct.atlassian.net/browse/AMBER-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(AMBER-769): Remove "Bidding closed" logic from the artwork grid

- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/Home/useHomeModules.ts
This PR resolves [ONYX-1050]
Solves this extra empty space issue:
|---|---|
| <img src="https://github.com/artsy/eigen/assets/3934579/90a65bad-ae25-477b-adcb-429d5bacacce" /> | <img src="https://github.com/artsy/eigen/assets/3934579/3c58e2c3-3426-4c26-b606-7d21ac120291" /> |
If `artworksForUser` collection is empty - `isEmpty` condition in `useHomeModules` doesn't result in `true` and "empty" <></> component is rendered in home screen together with extra separator. This PR should fix it. 
The price of this fix is an extra request to metaphysics (or does relay cache the result and doesn't make a request when rendering the component?). I see that this approach is used for other modules on home page, but I am wondering - is it justified to make +1 request for each module …
> fix(onyx-1050): fix logic for checking if new works for you rail is empty

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFromMyCollectionArtworks.tsx
This PR address design comments on the submit artwork from my collection
_Tomorrow is release day, I will merge this to make sure it makes it - glad to address comments separately_
#nochangelog
> chore: fix submit artwork from my collection comments

- src/app/AppRegistry.tsx
- src/app/Components/Bidding/Components/BidInfoRow.tsx
- src/app/Components/Bidding/Screens/BillingAddress.tsx
- src/app/Components/Bidding/Screens/Registration.tests.tsx
- src/app/Components/Bidding/Screens/Registration.tsx
- src/app/Components/Containers/RegistrationFlow.tsx
[Future Friday]
- Users were able to quit the flow directly without warning - now they will be warned about it
If you swipe down, the modal will close and you will use your progress
- we probably don't want that to happen accidentally, I made the modal sheet not dismissible by swiping down, it will only be dismissed by click the X button
If you press on Conditions of sale, we used top open it in a WebView where you could easily get lost
- now, we don't distract you from registering and open that externally so you are right where you left - just like we do in the SWA flow
- Use the new credit card input component
- The font sizes were a mess, custom line heights, custom font sizes etc.. I updated them to look more or less like what we do in other …
> chore: register to bid ux/ui improvemnts

- src/app/Scenes/Artwork/Components/ArtworkDimensionsClassificationAndAuthenticity/ArtworkDimensionsClassificationAndAuthenticity.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkDimensionsClassificationAndAuthenticity/ArtworkDimensionsClassificationAndAuthenticity.tsx
Uses forces logic including unlisted to prevent "Frame not included" from showing up on auction lots when this value is not explicitly set.
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
- Fix 'Frame not included' bug in auction lots - brian
-
-
-
</details>
> fix: 'Frame not included' string showing on all lots

- src/app/store/config/features.ts
This PR resolves [DIA-713]
This PR adds `AREnableCollectorProfilePrompts` which will be used to build prompts to the user that will encourage them to update their profile or add artists to their collection after they perform commercial actions.
- Added feature flag AREnableCollectorProfilePrompts
</details>
[DIA-713]: https://artsyproduct.atlassian.net/browse/DIA-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add AREnableCollectorProfilePrompts

- src/app/Components/LocationAutocomplete.tsx
- src/app/Scenes/MyProfile/Components/UserProfileFields.tsx
- src/app/Scenes/MyProfile/MyProfileEditForm.tsx
- src/app/Scenes/MyProfile/MyProfileEditModal.tsx
- src/app/Scenes/MyProfile/useUpdateUserProfileFields.tsx
This PR resolves [DIA-695]
This PR adds a new `MyEditProfileModal` component that we can use to prompt collector's to complete their profile. It uses the same profile fields as the `MyEditProfileScreen` component, so it includes some refactoring work to extract those fields.
| ![ios](https://github.com/artsy/eigen/assets/44589599/6882dffa-606d-4a89-bdc5-f19cbdf73918) | ![android](https://github.com/artsy/eigen/assets/44589599/0f3debae-1113-41d5-8b64-86213268fa33) |
- The user profile address can be erased with one tap.
- A new `MyProfileEditModal` component is available.
</details>
[DIA-695]: https://artsyproduct.atlassian.net/browse/DIA-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
> feat: add a profile update modal (DIA-695)

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhoneNumber.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddTitle.tsx
This PR comes as a follow-up on https://github.com/artsy/eigen/pull/10466. 
- We need to navigate to complete your submission step on draft submissions instead of the shipping location
- When an artwork is submitted through my collection, we need to create a submission at the title step since it's not going to be there (because we skipped the creation that is supposed to happen at the artist step)
- fix submit artwork from my collection - mounir
-
-
-
</details>
> fix: submit artwork from my collection

- src/app/Scenes/Activity/ActivityList.tsx
- src/app/Scenes/Activity/utils/__tests__/shouldDisplayNotification.tests.ts
- src/app/Scenes/Activity/utils/shouldDisplayNotification.ts
- src/app/Scenes/Home/Components/ActivityRail.tsx
* Related Force PR: The type of this PR is: https://github.com/artsy/force/pull/14205
This PR solves https://artsy.slack.com/archives/C05EQL4R5N0/p1721034091096429
We should filter out `null` notifications in the Activity panel. This PR fixes the types of `shouldDisplayNotification` and adds a check that filters out `null` notifications to avoid the following error:
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR solves https://artsy.slack.com/archives/C05EQL4R5N0/p1721034091096429
We should filter out `null` notifications in the Activity panel. This PR fixes the types of `shouldDisplayNotification` and adds a check that filters out `null` …
> fix: Filter out null notifications in Activity panel

- src/app/Scenes/CompleteMyProfile/AvatarStep.tsx
- src/app/Scenes/CompleteMyProfile/ChangesSummary.tsx
- src/app/Scenes/CompleteMyProfile/CompleteMyProfileProvider.tsx
- src/app/Scenes/CompleteMyProfile/Footer.tsx
- src/app/Scenes/CompleteMyProfile/IdentityVerificationStep.tsx
- src/app/Scenes/CompleteMyProfile/LocationStep.tsx
- src/app/Scenes/CompleteMyProfile/ProfessionStep.tsx
- src/app/Scenes/CompleteMyProfile/__tests__/AvatarStep.tests.tsx
- src/app/Scenes/CompleteMyProfile/__tests__/Footer.tests.tsx
- src/app/Scenes/CompleteMyProfile/__tests__/IdentityVerificationStep.tests.tsx
- src/app/Scenes/CompleteMyProfile/__tests__/LocationStep.tests.tsx
- src/app/Scenes/CompleteMyProfile/__tests__/ProfessionStep.tests.tsx
- src/app/Scenes/CompleteMyProfile/hooks/__tests__/useCompleteProfile.tests.tsx
- src/app/Scenes/CompleteMyProfile/hooks/useCompleteMyProfileSteps.ts
- src/app/Scenes/CompleteMyProfile/hooks/useCompleteProfile.ts
- src/app/Scenes/CompleteMyProfile/hooks/useUpdateMyProfile.tsx
- src/app/Scenes/MyProfile/MyProfileHeader.tsx
This PR relates to [DIA-561] 
This PR mainly fixes a bug when saving from the middle of the flow, the current screen didn't save its field correctly so I removed more logic from `useCompleteProfile` to work directly with the newly created `store` from `easy-peasy` since its performance is enough to have a smooth flow within the UI.
Other relevant changes:
- updates the store directly when adding an avatar to the user to simulate an optimistic response in the fragments that listened to(optimisticResponse was too much since we have 3 spreads in the mutation and the return when using it requires to return all properties used by the fragments)
- UI corrections, spacing, missing border
- Android keyboard layout issue fixed when using `autoFocus` with the input
<details> …
> fix(DIA-561): Complete My Profile broken save in middle of the flow and UI adjustments

- src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Components/ArtworkLists/components/ArtworkInfo.tests.tsx
- src/app/Components/ArtworkLists/types.ts
- src/app/Components/ArtworkLists/useArtworkListsToast.ts
- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
This PR resolves https://artsyproduct.atlassian.net/browse/EMI-1976 
My first PR in Eigen so please excuse my mistakes here. Figuring out this Eigen flow!
Ideally we would have the auction saves(watches) go into a different list type but that is not done this way now. We are relying on checking if the artwork is in the auction for handling those saves in several places. So for now just reading this attribute from artwork and basing the sub-copy on that parameter.
Before:
After:
- Removed misleading sub-note after auction artwork save - oxaudo
-
-
- 
</details> …
> chore: Remove sub-copy from Artwork Saved tooltip for auction lots

- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
- src/app/utils/ArtworkInquiry/ArtworkInquiryStore.tests.tsx
- src/app/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
- src/app/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
This PR fixes a bug I introduced in #10491 by not setting the `inquiryType` state variable that defines what label should be used for the "Contact Gallery" button. I stopped using it because we never used any of the other 2 options, but I forgot that the inquiry modal's header also uses that state variable to display "Contact Gallery" as the title.
| Screenshot |
| ------------|
| ![Screenshot_1721403894](https://github.com/user-attachments/assets/1d63ad18-bda2-483e-891b-7486c91b565d) |
- Fixes a bug introduced mid-release that made the inquiry modal title disappear.
</details> …
> fix: missing inquiry modal title

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCondition.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFrameInformation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkCondition.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkFrameInformation.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkFromMyCollection.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkFormEdit.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/fetchArtworkInformation.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialSubmissionValues.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialSubmissionValuesFromArtwork.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
This PR resolves [ONYX-1118] 
This PR adds **Artwork Condition** screen to the submission flow
| Test case | Screenshot/video |
| Condition Definitions | <img width="379" alt="Screenshot 2024-07-23 at 12 20 58" src="https://github.com/user-attachments/assets/0553c31e-50cd-40a0-bd01-8109485f7c48"> |
| Save & Exit | <Video src="https://github.com/user-attachments/assets/60c7ea85-a605-4fff-a562-ff3e1eb05c9c" /> |
| Trigger the mutation | <Video src="https://github.com/user-attachments/assets/e9c5b2d0-1626-4fa8-a7d1-81be934972f3" /> | 
- add artwork condition screen to SWA flow - mounir
-
-
-
</details> …
> feat: add submit artwork condition screen

- android/app/src/main/AndroidManifest.xml
- data/schema.graphql
- docs/add_a_new_screen.md
- docs/adding_a_new_route.md
- docs/adding_new_components.md
- src/app/AppRegistry.tsx
- src/app/Scenes/HomeView/HomeView.tsx
- src/app/routes.ts
This is the counterpart to https://github.com/artsy/metaphysics/pull/5848 — see that description for more details.
Stubs in a new `HomeView` screen at the `home-view` route, so that we can safely iterate on the proposed new schema without touching or being constrained by existing home feed logic.
As of now this just renders some placeholders. A next step would be to actually render some content based on the response coming from `homeView.sectionsConnection`
(I'm having trouble bring this up in an Android sim, hoping someone else can confirm — would require access to the new MP schema either locally or in staging)
-
-
-
- A new sandbox screen at `home-view` route for iterating on the new dynamic home view schema - Roop
</details>
Need help with …
> feat: consume prototype schema for new home view sections

- src/app/Scenes/MyCollection/Screens/Artwork/ArtworkSubmissionStatusFAQ.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
- src/app/Scenes/MyCollection/mutations/myCollectionUpdateArtwork.ts
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCondition.tsx
This PR resolves [ONYX-1127] 
The changes are hidden behind `AREnableSubmitArtworkTier2Information` ff
Add submission statuses to the MyCollection artwork screen
[Figma](https://www.figma.com/design/E6rVm1tiSI4PW3EzibKKZw/Submission-%26-Pre-Consignment-Management?node-id=3128-39743&m=dev)
| Rejected | Submitted | Listed | Approved | 
| ![image](https://github.com/user-attachments/assets/692d23f3-73cb-449d-934b-964a5794eacb) | ![image](https://github.com/user-attachments/assets/6619e7f7-889c-4e81-9c8b-f3b4497f3db6) | ![image](https://github.com/user-attachments/assets/0494b4a7-a149-4a14-8e9b-8c1583804c88) | ![image](https://github.com/user-attachments/assets/0bef7ce9-dc8f-4f93-80de-ea5bdba6ff8b) |
- add submission …
> feat: add submission statuses to the MyC artwork screen

- src/app/Scenes/CompleteMyProfile/CompleteMyProfile.tsx
- src/app/Scenes/CompleteMyProfile/CompleteMyProfileProvider.tsx
- src/app/Scenes/CompleteMyProfile/__tests__/AvatarStep.tests.tsx
- src/app/Scenes/CompleteMyProfile/__tests__/IdentityVerificationStep.tests.tsx
- src/app/Scenes/CompleteMyProfile/hooks/__tests__/useCompleteMyProfileSteps.tests.tsx
- src/app/Scenes/CompleteMyProfile/hooks/__tests__/useCompleteProfile.tests.tsx
- src/app/Scenes/CompleteMyProfile/hooks/useCompleteMyProfileSteps.ts
- src/app/Scenes/CompleteMyProfile/hooks/useCompleteProfile.ts
- src/app/Scenes/CompleteMyProfile/hooks/useUpdateMyProfile.tsx
- src/app/Scenes/MyProfile/MyProfile.tsx
- src/app/Scenes/MyProfile/MyProfileEditForm.tsx
- src/app/Scenes/MyProfile/MyProfileHeader.tsx
- src/app/Scenes/MyProfile/hooks/useEditProfile.ts
- src/app/utils/mutations/useUpdateMyProfile.tsx
This PR resolves [DIA-763] 
This PR changes the Complete My Profile query into a fragment resulting in a more solid flow between the Edit form when changing the data.
This work also removes the localStorage approach with the avatar and the context around MyProfile in favor of the relay store manipulation
LazyLoad to Fragment change: 178d57b47987f8e1bbfc6800f3268aa6d2294de7
Avatar removed from local storage and manipulated directly on Relay store: c35f4bb78c01090c139d4473e33774474a6b36bd
Tests refactor: 6ed96c1a5414d551a9720295fbc6151997d1329f
https://github.com/user-attachments/assets/96f7585d-bff7-4b39-bf18-a0cef0b393bc
- feat: complete my profile query changed to fragment - araujobarret
-
-
-
</details> …
> feat(DIA-763): Move complete my profile lazyLoadQuery to fragment

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCondition.tsx
This PR sets the artwork submission state as `RESUBMITTED` after the final step.
- set artwork as resubmitted after last step - mounir
-
-
-
</details>
> chore: set artwork state as resubmitted after condition step

- src/app/Components/FancyModal/FancyModalHeader.tsx
- src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/CompleteProfilePrompt.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryQuestionOption.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/constants.ts
- src/app/Scenes/Artwork/Components/PartnerCard.tests.tsx
- src/app/Scenes/Artwork/Components/PartnerCard.tsx
- src/app/Scenes/Artwork/Components/Questions.tests.tsx
- src/app/Scenes/Artwork/Components/Questions.tsx
- src/app/Scenes/Artwork/Components/ShortContactGallery.tsx
- src/app/Scenes/MyProfile/MyProfileEditModal.tsx
- src/app/Scenes/MyProfile/useUpdateUserProfileFields.tsx
- src/app/utils/ArtworkInquiry/ArtworkInquiryStore.tests.tsx
- src/app/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
- src/app/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
- src/app/utils/collectorPromptHelpers.ts
- src/app/utils/tests/collectorPromptHelpers.tests.ts
This PR resolves [DIA-695]
This PR updates the inquiry modal to prompt users to complete their profile after an inquiry is sent, if their profile is incomplete and they have not been prompted in 30 days.
I have observed a few issues with the Android implementation, which can be merged without impacting users since this is behind a feature flag:
1. The modal flickers during autocompletion
2. The submit button doesn't respond after selecting a new location
3. The title of the location field is rendered behind its outline
4. The modal overlay doesn't disappear after closing the modal
| ![ios](https://github.com/user-attachments/assets/57114eaf-7c4e-454c-960c-4aee1c0ae53e) | ![android](https://github.com/user-attachments/assets/82347092-ad24-47a7-8f77-b24059 …
> feat(DIA-695): show profile prompt after sending an inquiry

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Components/Gene/GeneArtworks.tsx
- src/app/Scenes/Fair/Components/FairArtworks.tsx
- src/app/Scenes/Partner/Components/PartnerArtwork.tsx
- src/app/Scenes/Tag/TagArtworks.tsx
Moved all the renderItem from `Tabs.Masonry` to a `useCallback` in order to take advantage of slightly improved performance.
Read more [here](https://www.mukesh-jangid.com/post/optimize-flatlist-with-the-power-of-usememo-and-usecallback)
-
-
-
- boost tabs.masonry performance by wrapping renderitem in usecallback - gkartalis
</details>
> refactor(perf): boost performance by wrapping renderitem usecallback

- src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx
- src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
This PR resolves [DIA-764]
Use `goBack` instead of `popToRoot` when submitting artists from `MyCollectionAddCollectedArtists` screen.
This fixes the bug when linking the flow to Complete My Profile where we need to navigate back after the submission instead of going back to the root.
I've checked the existing flow and nothing breaks, tagged onyx folks because you have more context of something that might be off with this change or not 👍 
https://github.com/user-attachments/assets/54ab85f3-6556-4627-a1c1-01b51932c012
-
-
-
-
</details>
[docs]: …
> feat(DIA-764): navigate back instead of popping the navigation stack from add artist to my collection

- src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
This PR resolves [EMI-1958] 
>[!NOTE]
> This change is hidden behind `AREnablePartnerOfferSignals` feature flag
This PR adds a new "Limited-Time Offer" signal for artwork rail card and artwork grid item with partner offer
|---|---|---|
| Recently viewed rail | <img width="487" alt="image" src="https://github.com/user-attachments/assets/c2e74880-6246-4ef4-b2d5-a8cb54733f49"> | ![image](https://github.com/user-attachments/assets/e0d125a7-28db-4a6f-9a81-6a9de658a3fd) |
| Recently viewed grid | <img width="487" alt="image" src="https://github.com/user-attachments/assets/74d9e44a-c01c-4a4a-ada7-9f55974142af"> | ![image](https://github.com/user-attachments/assets/35df8fb0-8091-4d7e-9616-026340d870ec) |
| Saves list grid | <img width="487" alt="image" …
> feat(EMI-1958): Display limited time offer badge on artworks with Partner Offers

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhoneNumber.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAdditionalDocuments.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/useSubmissionContext.ts
- src/app/utils/showDocumentsAndPhotosActionSheet.ts
Resolve [Notion ticket](https://www.notion.so/artsy/Navigation-fails-after-navigating-from-phone-number-step-edit-submission-in-state-SUBMITTED-f6379608f1d940c79d157c057574846c?pvs=4) (Navigation fails after navigating from phone number step (edit submission in state SUBMITTED)
Adjust Additional documents screen 
<image width="250" src="https://github.com/user-attachments/assets/acce21f8-15d4-4e1d-a68e-b3f296a6993b" />
- adjust navigation and additional documents screen on the submission flow -daria
-
-
-
</details> …
> fix: edit submission, adjust additional documents screen

- src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
This PR resolves [EMI-2020] 
> [!NOTE]
> These changes are hidden behind the `AREnablePartnerOfferSignals` feature flag
This PR stops the second Limited-Time Offer badge in the Activity Panel from rendering
|---|---|---|
| Android | <img width="487" alt="image" src="https://github.com/user-attachments/assets/9450116f-370f-41b5-ae1a-40317a83862b"> | <img width="487" alt="image" src="https://github.com/user-attachments/assets/482ec3cc-93c0-43f0-bf7c-c46c3cdabd2b"> |
| iOS | ![image](https://github.com/user-attachments/assets/8c324a58-a36c-42d1-b4fe-f91a14fb8379) | ![image](https://github.com/user-attachments/assets/4e3647d9-ee5f-4916-9b9c-b5bc19457532) |
- Hide second Limited-Time Offer badge in Activity Panel (hidden behind …
> fix(EMI-2020): Stop limited-time offer badge from displaying twice in Activity Panel

- src/app/Scenes/Fair/FairOverview.tests.tsx
- src/app/Scenes/Fair/FairOverview.tsx
This PR also resolves [PHIRE-1083] 
The component was rendered doubled the empty state for the example below, on top of that the `isActive` logic is no longer used, so removing it made sense to fix the bug and clean up the component as we display in Force. From the example below we can see the fair had elements to be shown but `isActive` logic was blocking it.
- fix: double empty state and isActive logic on FairOverview tab - araujobarret
-
-
-
</details>
[PHIRE-1083]: …
> fix(FairOverview): remove double empty state rendered and isActive logic(deprecated)

- src/app/Components/ArtsyWebView.tests.tsx
- src/app/Components/ArtsyWebView.tsx
This PR resolves [PHIRE-1081] 
A while back we fixed a bug in our android webviews by changing the way we pass user agent: 
https://github.com/artsy/eigen/pull/9354 
This was due to a bug in the react-native-webview dependency:
https://github.com/react-native-webview/react-native-webview/issues/2949
This unfortunately also changed the format of our user agent to append our custom user agent to the browser user agent:
e.g: `Mozilla/5.0 (Linux; Android 14; Pixel 7 Pro Build/AP2A.240705.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 Mozilla/5.0 (Linux; Android 14; Pixel 7 Pro Build/AP2A.240705.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 Artsy-Mobile/8.44.0 …
> fix: user agents in webviews

- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tsx
- src/app/Scenes/SellWithArtsy/Hooks/useSubmitArtworkTracking.ts
This PR resolves [Notion card](https://www.notion.so/artsy/App-Missing-tracking-when-clicking-on-Add-Additional-Information-76c98f940c94485da4199cfab3e49c09?pvs=4): add Add Additional Information tracking
- add Add Additional Information tracking -daria
-
-
-
</details>
> fix: add Add Additional Information tracking

- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkBottomNavigation.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
- src/app/Scenes/SellWithArtsy/Components/Header.tsx
- src/app/Scenes/SellWithArtsy/utils/submissionModelState.tsx
Resolves https://www.notion.so/artsy/App-the-user-can-go-back-to-the-title-step-of-a-non-draft-submission-We-should-not-allow-the-user--06df9d217c3d45f7ab985276ed8a3b53?pvs=4
- Related Force PR: https://github.com/artsy/force/pull/14323
With this change, we link to the Title step instead of the Artist step when editing a submission and remove the "Back" button on the Title step. This approach prevents/discourages users from updating the artist of an already existing submission.
- Do not allow updating the artist from an already created submission in the Sell flow (behind ff) - ole
-
-
-
</details> …
> fix: Do not allow editing a submissions artist

- src/app/Scenes/Collection/Collection.tsx
- src/app/Scenes/Collection/CollectionOverview.tsx
- src/app/Scenes/Collection/Screens/CollectionHeader.tests.tsx
- src/app/Scenes/Collection/Screens/CollectionHeader.tsx
- src/app/store/config/features.ts
Makes collection ready for release.
After checking in with Jordan Huelskamp we decided to remove the header image from the collection header to avoid duplication (change hidden behind a FF) and to move description back to the header.
Now artworks is the default tab.
- make collections release ready - gkartalis
-
-
-
</details>
> refactor: make collections release ready

- src/app/Scenes/MyCollection/Components/SubmissionStatus.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
Addresses [Notion card](https://www.notion.so/artsy/App-draft-submissions-displayed-incorrectly-submission-staus-is-mission-on-the-artwork-grid-the--970bdad2662d4895bb9a5acc8d5295b5?pvs=4): [App] draft submissions displayed incorrectly - submission status is mission on the artwork grid, the action label take the user to the wrong screen 
- fix draft submissions displayed incorrectly -daria
-
-
-
</details>
> fix: draft submissions displayed incorrectly

- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtworkPrice.tsx
This PR resolves [EMI-2019] 
Follow up for #10607 
- Check that partner offer is active before rendering - leamotta
-
-
-
</details>
[EMI-2019]: https://artsyproduct.atlassian.net/browse/EMI-2019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(EMI-2019): check that partner offer is active before rendering

- src/app/AppRegistry.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
This PR updates the navigation from the empty state of the Alerts screen in the new collector profile
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/d44a3e81-f32f-4cd7-b723-4b9430b91d25" /> | <video src="https://github.com/user-attachments/assets/f4f892d3-e430-4529-919b-f808b29956df" /> |
| iOS | <video src="https://github.com/user-attachments/assets/c7d80ba8-74b1-4ca6-84b3-85c5b28b776c" /> | <video src="https://github.com/user-attachments/assets/cc664cab-f659-4f5f-bb48-35f7ed521621" /> |	
- 
-
-
- fix navigation to home in Alerts empty state - mrsltun
</details> …
> fix: fix Alerts nested navigation issue

- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/Sections/FeaturedCollectionHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
This PR resolves [ONYX-1190]
Adds Curators' Picks: Emerging section to the new home view. Blocked by https://github.com/artsy/metaphysics/pull/5916.
See a discussion why we came up with some of implementation decisions [in Slack](https://artsy.slack.com/archives/C05EQL4R5N0/p1723746300946949).
#nochangelog
</details>
[ONYX-1190]: https://artsyproduct.atlassian.net/browse/ONYX-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-1190): add Curators' Picks: Emerging home view section

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Components/Gene/GeneArtworks.tsx
- src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
- src/app/Scenes/Fair/Components/FairArtworks.tsx
- src/app/Scenes/Partner/Components/PartnerArtwork.tsx
- src/app/Scenes/Tag/TagArtworks.tsx
- src/app/utils/masonryHelpers/AnimatedMasonryListFooter.tsx
- src/app/utils/masonryHelpers/index.tsx
This PR resolves [PHIRE-1124] 
During the mobile QA we noticed that when doing infinite scroll in any `Tabs.Masonry` surface the spinner was never displayed for the `first` refetch. 
This PR fixes that. Note that in order to do it we had to introduce a boolean state variable on the artworkGrids that use the legacy relay containers.
In surfaces where we use the hooks (i.e. Fairs), it is **not needed** since the `isLoadingNext` is working as expected.
Unified also the page size for all surfaces and the spinner and **bonus** fix was that with the new `AnimatedMasonryListFooterComponent` the content is no longer jumpy after the next page is rendered ⭐ .
Tested on all surfaces on both Android and iOS - Attaching before and after videos for `CollectionArtworks` and `ArtistArtworks` …
> fix: generalize and animate AnimatedMasonryListFooterComponent

- src/app/Scenes/CompleteMyProfile/hooks/__tests__/useCompleteMyProfileSteps.tests.tsx
- src/app/Scenes/CompleteMyProfile/hooks/useCompleteMyProfileSteps.ts
Fixes the bug when updating the user avatar during "Complete My Profile" would keep the avatar step in the flow showing that the user has no image uploaded.
We have a updater to the store that changes `me.icon.url` and the hook was using `me.collectorProfile.icon` data, this PR switches to use `me.fields` instead and keep it simple.
https://github.com/user-attachments/assets/52b50265-d601-4496-8689-fa04637a7024
- fix: complete my profile avatar step asking for an image given the collector has one - araujobarret
-
-
-
</details>
[docs]: …
> fix: use me properties instead of collectorProfile

- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
This PR is a follow-up on https://github.com/artsy/eigen/pull/10625
This PR fixes the issue related to the progress bar transition between the additional documents and condition screens. The root cause for the issue resides inside react-navigation header prop which keeps on rendering. 
https://github.com/user-attachments/assets/7dfe1c42-4ac4-46df-b727-eb9c9d8d74c2
- fix SWA transition animation between AdditionalDocuments and Condition - mounir
-
-
-
</details>
> fix: SWA transition animation between AdditionalDocuments and Condition

- .secrets.baseline
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
This PR resolves [ONYX-1209]
This PR fixes the missing edit button on my collection artwork screen. I also added a bunch of tests to avoid the same regression in the future
| <img src="https://github.com/user-attachments/assets/8b24fad1-c1e0-43f5-8150-158181ad5161" /> | <img src="https://github.com/user-attachments/assets/32b2f106-0243-43d5-abad-7734e2ac11bb" /> |
- show edit artwork button - mounir
-
-
-
</details>
[ONYX-1209]: …
> fix: show edit artwork button

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkShippingLocation.tests.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/createOrUpdateSubmission.ts
This PR fixes an issue with the shipping location getting overwritten after the user finalizes the submission. The reason behind that is that we were setting the value to `null` instead of `undefined`.
**Bonus:** While inspecting the sent payload in Reactron, we noticed that the attribution class and edition related fields were also overwritten so we fixed that as well.
- fix broken submission values on state resubmitted - daria, mounir
-
-
-
</details>
> fix: broken submission values on state resubmitted

- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
This PR is a follow up on #10635 
This PR updates the edit button logic to show only in non-submitted artworks in My Collection
|---|---|---|
| Before - With Submission | ![image](https://github.com/user-attachments/assets/89be36bf-6d7a-465c-a538-d23912a3982f) | ![image](https://github.com/user-attachments/assets/6734d166-f8ff-44cc-9b5f-6f2361d9c621) |
| Before - Regular | ![image](https://github.com/user-attachments/assets/31047dea-8763-4c1a-84e0-c0c3ca705344) | ![image](https://github.com/user-attachments/assets/4531420d-5a81-4b47-997b-79d7af987a7a) |
| After - With Submission | ![image](https://github.com/user-attachments/assets/46b572fb-72a0-4745-af09-1a86d32252de) | ![image](https://github.com/user-attachments/assets/a986f41a-69c9-4aa3-bd14-0e2 …
> fix: show Edit button on My Collection artworks

- src/app/Scenes/SavedArtworks/SavedArtworks.tsx
This PR resolves [DIA-797]
There are some minor differences in how the navigation headers for the saves, follows, and alerts screens work that are more obvious now that those surfaces can be accessed easily from the redesigned profile screen.
This PR addresses the minor difference that the saves screen header has a "profile" breadcrumb next to the back nav button and the other two screens don't.
| Before | | After | |
|-|-|-|-|
| ![IOS BEFORE ONE](https://github.com/user-attachments/assets/ff938ad0-be50-41e7-ba4f-622590fa1f01) | ![IOS BEFORE TWO](https://github.com/user-attachments/assets/6d8b1916-fab1-44a0-8731-79e601308fe7) | ![IOS AFTER ONE](https://github.com/user-attachments/assets/e1d94c8a-00a2-4dff-a847-a584fcc2d199) | ![IOS AFTER …
> feat(DIA-797): remove breadcrumb label from saved artworks screen

- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/Sections/SalesRailHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/SalesRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/SalesRailItem.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
This PR resolves [ONYX-1230]
Add Auctions home view section:
#nochangelog
</details>
[ONYX-1230]: https://artsyproduct.atlassian.net/browse/ONYX-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-1230): add Auctions home view section

- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
- src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
- src/app/Components/LocationAutocomplete.tests.tsx
- src/app/Scenes/Activity/Activity.tests.tsx
- src/app/Scenes/Activity/ActivityItem.tests.tsx
- src/app/Scenes/Activity/components/__tests__/AlertNotification.tests.tsx
- src/app/utils/tests/flushPromiseQueue.ts
This PR deprecates flushPromiseQueue and shows some examples how to proper handle these cases within some test scenarios.
#noChangelog
-
-
-
-
</details>
> test(flushPromiseQueue): deprecate flushPromiseQueue and give some examples

- src/app/Scenes/Activity/ActivityItem.tests.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
Fix when navigating to the notification item of type _CollectorProfileUpdatePromptNotificationItem_, it should not navigate on this case, we open a prompt instead.
-
-
-
-
</details>
> fix(ActivityItem): avoid navigating on CollectorProfileUpdatePromptNotificationItem

- src/app/Scenes/Artwork/hooks/__tests__/useSendInquiry.tests.tsx
- src/app/Scenes/Artwork/hooks/useSendInquiry.ts
This PR changes the order of prompts. Previously we showed a profile prompt before the collector prompt, but this PR swaps that so that the collector prompt is shown first.
- Show collection prompt before profile prompt
</details>
> fix: show collection prompt before profile prompt

- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Search/SearchArtworksContainer.tests.tsx
This PR fixes tests after they broke due to enabling [this](https://github.com/artsy/echo/pull/668) feature flag
#nochangelog
> fix: broken search artworks container test

- data/schema.graphql
- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
This PR resolves [ONYX-1244] 
This PR adds a galleries near you rail to the home view.
https://github.com/user-attachments/assets/0592933d-acd8-473a-b1c7-839ca49a6c66
- add galleries near you rail - mounir
-
-
-
</details>
[ONYX-1244]: https://artsyproduct.atlassian.net/browse/ONYX-1244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add galleries near you rail

- scripts/update-metaphysics.js
Our query map updates in metaphysics were failing because they did not adhere to conventional commit format 🙃 
This just updates the message to conform. 
https://github.com/artsy/metaphysics/pull/5827
-
-
-
- update query map pr to use conventional commits - brian 
</details>
> chore: update commit message to use conventional commits

- src/app/Components/ArtworkLists/useArtworkListsToast.ts
- src/app/routes.ts
This PR resolves [APPL-1069] 
This PR fixes the issue with the View Saves button showing an empty screen after saving an artwork
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/1e34fd46-ea43-49de-b54f-72fa76a848e2" /> | <video src="https://github.com/user-attachments/assets/cbebb581-2493-449a-8347-489fa38da470" /> |
| iOS | <video src="https://github.com/user-attachments/assets/cd1ddbde-626c-486d-b629-7d998510b1af" /> | <video src="https://github.com/user-attachments/assets/14d28979-94c9-4971-bf48-3c81c28f4105" /> |	
- fix the issue with View Saves link navigating the user to an empty screen - sultan, brian, carlos
-
-
-
</details>
Need help with something? Have a look at our [docs], or get …
> fix: Update view saves button issue

- src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkRail/LargeArtworkRail.tsx
- src/app/Components/ArtworkRail/SmallArtworkRail.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tsx
- src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
- src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
- src/app/Scenes/Fair/FairExhibitorRail.tests.tsx
- src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
- src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
- src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
- src/app/Scenes/Home/homeAnalytics.ts
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
- src/app/utils/getArtworkSignalTrackingFields.ts
This PR resolves [EMI-2044] 
This PR adds tracking for Artworks with auction signals
-
-
-
- add tracking for artwork auction signals - mrsltun
</details>
[EMI-2044]: https://artsyproduct.atlassian.net/browse/EMI-2044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(EMI-2044): Add tracking to Auction Signals

- src/app/Components/constants.ts
- src/app/Scenes/ArtistSeries/ArtistSeries.tests.tsx
- src/app/Scenes/ArtistSeries/ArtistSeries.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tests.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesHeader.tests.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesHeader.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMeta.tests.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
- src/app/Scenes/Fair/Fair.tsx
This PR resolves [PHIRE-1111] 
Refactors the ArtistSeries screen.
- Moves description and more series from this artist section on an about tab
- Updates Artist component and follow artist button to use the updated design
- adds pagination to the Artwork Tab
|Before|After|
|---|---|
|<video width="400" src="https://github.com/user-attachments/assets/fcaec53b-8c5e-46f1-bba9-0b24beb8e5f4" />|<video width="400" src="https://github.com/user-attachments/assets/2067ab91-2350-41e8-9b69-e1ab48f3170d" />|
- refactor artist series artworks to use performant masonry grid - gkartalis
-
-
-
</details>
[feature …
> refactor(masonry): Migrate ArtistSeries Artworks to use MasonryTabs

- src/app/Scenes/Home/Components/ArticlesRail.tsx
- src/app/Scenes/HomeView/Sections/ActivityRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/ArticlesCardsHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/ArticlesCardsHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/ArticlesRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/ArtistsRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/ArtworksRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/AuctionResultsRailHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/AuctionResultsRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/FairsRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/FeaturedCollectionHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/MarketingCollectionsRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/SalesRailHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/SalesRailHomeViewSection.tsx
- src/app/Scenes/HomeView/Sections/ViewingRoomsRailHomeViewSection.tsx
This PR resolves [ONYX-1259]
Follow-up for https://github.com/artsy/metaphysics/pull/5963. Adds navigation links (from MP) to new home view sections.
#nochangelog
</details>
[ONYX-1259]: https://artsyproduct.atlassian.net/browse/ONYX-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-1259): home view sections use use behaviors.viewAll.href field for navigation

- src/app/Scenes/HomeView/Sections/ArtworksRailHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/ArtworksRailHomeViewSection.tsx
This PR resolves [ONYX-1255] 
This PR adds legacy tracking events to artworks' rail sections.
https://github.com/user-attachments/assets/732d4a8b-4131-460c-89a8-d19cb7799e74
-
-
-
-
</details>
[ONYX-1255]: https://artsyproduct.atlassian.net/browse/ONYX-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add ArtworksRailHomeViewSection tracking

- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
There's a spec that's been failing on CI ever since we [toggled the `AREnableSubmitArtworkTier2Information` flag](https://github.com/artsy/echo/pull/685/files) as part of the [SWA Tier 2 release](https://www.notion.so/artsy/SWA-Tier-2-Launch-f353c144ff2e473b8ecb859f1d3ca804) earlier today.
-
-
-
- Update a MyC spec that fails after an Echo change - Roop
</details>
> fix: broken MyC spec after SWA release

- src/app/AppRegistry.tsx
- src/app/Scenes/Home/HomeContainer.tests.tsx
- src/app/Scenes/Home/HomeContainer.tsx
- src/app/Scenes/HomeView/Components/AlphaVersionIndicator.tsx
- src/app/Scenes/HomeView/Components/HomeHeader.tsx
- src/app/Scenes/HomeView/HomeView.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-1267]
Implements the following logic to determine when to serve the new home view:
- A regular user on an app store build sees the legacy home screen by default
- A user on a simulator/beta/TestFlight build sees the new home screen by default
- A user can toggle a feature flag (`ARPreferLegacyHomeScreen`) to revert to the legacy home screen for dev/testing/QA
Or, in truth table form:
||isBetaOrDev=false| isBetaOrDev =true|
|---|---|---|
| ARPreferLegacyHomeScreen=false|Old screen|**New screen**|
| ARPreferLegacyHomeScreen=true|Old screen|Old screen|
In addition the new info button presents some helpful links for reporting issues related to the new home screen, or reverting back to the old one.
https://github.com/user-attachments/assets/670e828e-c9b7-4c54-a162-5b278ab …
> feat(art advisor): enable Milestone 1

- src/app/Scenes/Home/homeAnalytics.ts
- src/app/Scenes/HomeView/Sections/ActivityRailHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/ActivityRailHomeViewSection.tsx
This PR resolves [ONYX-1257] 
This PR adds legacy tracking to activity' rail sections.
https://github.com/user-attachments/assets/0d4e9fab-3e47-4278-b81f-ccea041e6e93
-
-
-
- add ActivityRailHomeViewSection tracking - mounir
</details>
[ONYX-1257]: https://artsyproduct.atlassian.net/browse/ONYX-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add ActivityRailHomeViewSection tracking

- src/app/Scenes/HomeView/Sections/ViewingRoomsRailHomeViewSection.tests.tsx
- src/app/Scenes/HomeView/Sections/ViewingRoomsRailHomeViewSection.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
This PR resolves [ONYX-1263] 
This PR adds tracking to the home view viewing rooms rail section.
https://github.com/user-attachments/assets/a4c3b269-28f0-4848-a935-10c388313f75
-
-
-
- add ViewingRoomsRailHomeViewSection tracking - mounir
</details>
[ONYX-1263]: https://artsyproduct.atlassian.net/browse/ONYX-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add ViewingRoomsRailHomeViewSection tracking

- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tests.tsx
- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenContent.tsx
This PR adjusts the screen section check to match the new types coming from MP.
**Bonus:**
I noticed that I wasn't getting the error message I was supposed to get when a section is not handled properly. That was because I was importing `Text` from `react-native-svg` instead of `palette`. I fixed that and added better styling and some tests.
-
-
-
-
</details>
> fix: home view artworks screen

- src/app/Scenes/Activity/Activity.tests.tsx
Fixes a flaky test given a pending Relay operation.
#nochangelog
-
-
-
-
</details>
> test(Activity): fix flaky test

- src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/ArtworkSocialSignal.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
- src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tsx
- src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
- src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
- src/app/store/config/features.ts
This PR resolves [EMI-2027] 
> [!NOTE]
> This work is hidden behind `AREnableCuratorsPicksAndInterestSignals` feature flag
This PR adds the new Increased Interest and Curator's Pick signals on artwork rail cards, grid items, and artwork details page
|---|---|---|
| Artwork screen - increased interest | <img width="468" alt="image" src="https://github.com/user-attachments/assets/ca040f09-bffd-4af9-924c-5de0513f2898"> | ![image](https://github.com/user-attachments/assets/dc7fbb22-2d47-4af4-8b2f-e4318681a286) |
| Artwork screen - curator's pick | <img width="466" alt="image" src="https://github.com/user-attachments/assets/1ba5c450-f8da-435b-91c8-1ac61d8ae569"> | ![image](https://github.com/user-attachments/assets/926562ee-dad2-416f-8c27-244224ac2120) |
| Artwork rail - …
> feat(EMI-2027): Add Curators' Pick and Increased Interest signals

- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
Restructure submission status tests
Follow up on https://github.com/artsy/eigen/pull/10733
-
-
-
- restructure submission status tests -daria
</details>
> chore: restructure submission status tests

- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionGeneric.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
This PR resolves [ONYX-1287]
This PR is an attempt to fix the broken spacings between home view sections. Here I am attempting a fix using the first approach suggested below in the thread👇.
<details><summary>Full Context from Slack Pasted Below</summary>
<p>
I noticed an extra margin between some rails in the home view - this is mainly because we define an ItemSeparatorComponent on the HomeView level. This is fine in the case where all sections are defined, however in our case, some sections might be missing and that will lead  to additional spaces representing missing section. 
If we want reliable margins, I see two possible approaches:
- Move the spacings one level below to the individual sections level. 
- Pros: easy to implement
- Cons: we need to make sure all new sections include …
> fix(ONYX-1287): broken spacing between home view sections

- src/app/utils/collectorPromptHelpers.tests.ts
Fixes flaky date usage in the tests.
#nochangelog
-
-
-
-
</details>
> test(collectorPrompt): fix flaky date tests

- src/app/Scenes/HomeView/HomeView.tsx
This PR resolves [ONYX-1278]
#nochangelog
</details>
[ONYX-1278]: https://artsyproduct.atlassian.net/browse/ONYX-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-1278): restore prompt for app store review for new home view

- src/app/Scenes/HomeView/HomeView.tsx
This PR resolves [ONYX-1279]
Prefetch tabs just like how "old" home screen does it: https://github.com/artsy/eigen/blob/f179a02295479892cac6f0f379ae246711c5188d/src/app/Scenes/Home/Home.tsx#L145-L150
#nochangelog
</details>
[ONYX-1279]: https://artsyproduct.atlassian.net/browse/ONYX-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-1279): prefetch tabs from new home view screen

- src/app/App.tsx
- src/app/Components/ArticleCard.tsx
- src/app/Components/Cards/MediumCard.tsx
- src/app/Components/FiveUpImageLayout.tsx
- src/app/Components/Home/ArtistRails/ArtistCard.tsx
- src/app/Components/Lists/AuctionResultListItem.tsx
- src/app/Components/ThreeUpImageLayout.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
- src/app/Scenes/Home/Components/HeroUnitsRail.tsx
- src/app/Scenes/Home/Components/ShowsRail.tsx
- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollectionsItem.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
This PR resolves [ONYX-1155] 
This PR adds the loading skeletons to the home view sections.
Here is exactly what I did:
- For each section, convert the section into a query renderer
- then, implement the placeholder
- then remove the query from the homeview level
After making my changes, I noticed that the homeview screen performance dropped, so I switched to `Flashlist` for out of the box performance improvements. 
https://github.com/user-attachments/assets/17aa19b3-ccf2-4f9a-9684-0bbc6e4d0b31
- Add loading skeletons to home view sections - mounir
-
-
-
</details> …
> feat: Implement Loading Skeletons for all home view sections

- src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
This PR resolves [ONYX-1277]
One more PR to achieve [parity](https://www.notion.so/artsy/Home-View-Features-Migration-Milestone-2-fa79161107e948078d2f32b4b9a282aa) between new and old home screens. [This condition](https://github.com/artsy/eigen/blob/main/src/app/Components/ContextMenu/ContextMenuArtwork.tsx#L60) (`contextModule == "newWorksForYouRail"`) enables the feature only for newWorksForYouRail. `contextModule` was missing before.
During refinement session we've discussed opportunity to enable context menu for all home screen rails, I've created a ticket to not forget to do it: [jira](https://artsyproduct.atlassian.net/browse/ONYX-1295).
#nochangelog
</details> …
> feat(onyx-1277): enable context menu for new works for you rail on new home screen

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/createOrUpdateSubmission.ts
This PR resolves https://artsy.slack.com/archives/C05EQL4R5N0/p1726128004361939
This fixes the "Condition is not in list" Sell flow "Save & Exit" bug and improves the error handling. Instead of failing when the artwork cannot be updated, we now catch the error and show a warning toast. This should be okay because creating/updating the submission does not fail in this case. Only updating the related My Collection artwork.
- fix: Sell flow Save and Exit button error handling when submitting a MyC artwork - ole
-
-
-
</details>
[docs]: …
> fix: Sell flow "Save and Exit" button error handling

- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionGeneric.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
Since switching sectionsConnection to be backed by an interface rather than a union, we can query for those standard attributes without the named inline spread.
-
-
-
- chore: remove last named inline spread from top-level home view query
</details>
> chore: remove last named inline spread from top-level home view query

- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
- src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
- src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
- src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
This PR resolves [ONYX-1290] 
This PR simplifies the code of the "Previously Sold on Artsy" rail on the `Sell` screen, which is a preparation for the Artwork Rail redesign. 
While these changes will lead to some design modifications, I believe this is acceptable since we will redesign and unify all artwork rails across the app in the upcoming weeks.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro Max (17 2) - 2024-09-18 at 11 02 49](https://github.com/user-attachments/assets/7787d160-6abd-4ea3-902c-7287885ba13a) | ![Simulator Screenshot - iPhone 15 Pro Max (17 2) - 2024-09-18 at 11 02 18](https://github.com/user-attachments/assets/1d56f968-547d-42c8-94d9-ec5541a9280e)|
-
-
-
- Simplify "Previously Sold on Artsy" …
> chore: Simplify Previously Sold on Artsy artworks rail

- src/app/Scenes/HomeView/HomeView.tsx
This PR resolves [ONYX-1282]
Errors in the new home screen offer a retry option. Before errors were bubbling up beyond the home screen, bottom tabs were not available.
Instead of using `withSuspense` I use `Suspense` component, because `ErrorBoundary` should be located higher than `Suspense` in the component tree. I've noticed that at some point we [had](https://github.com/artsy/eigen/blob/f6cf59181d3253e9d9bdfe742e5eb0f15a96ee13/src/app/utils/hooks/withSuspense.tsx#L20) `ErrorBoundary` integrated in `withSuspense`, but for some reason it is not there anymore.
#nochangelog
</details> …
> feat(onyx-1282): error boundary around new home view screen

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
- src/app/Components/ArtworkRail/LegacyArtworkRailCardImage.tsx
- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
- src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
- src/app/Components/ContextMenu/ContextMenuArtworkPreviewCardImage.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
- src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-1290] 
* Previous Refactoring PR: https://github.com/artsy/eigen/pull/10801
This PR:
* cleans up the artwork rail component and its sub-components,
* creates the feature flag `ARenableArtworkRailRedesignImageAspectRatio`, 
* creates a new artwork rail image component that can be used for the new aspect ratio (`LegacyArtworkRailCardImage` vs `ArtworkRailCardImage`).
-
-
-
-
</details>
[ONYX-1290]: https://artsyproduct.atlassian.net/browse/ONYX-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
> chore: Clean up artwork rail and extact sub components

- src/app/Components/ArtworkGrids/ArtworkAuctionTimer.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkAuctionTimer.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/app/Scenes/Sale/Components/SaleLotsList.tsx
This PR resolves [EMI-2053] 
This PR hides the Register By signal on the auction screen
it also fixes an issue with the data where some auctions have `undefined` as a price in rails
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/fe781426-8a7a-4377-989f-e10d214a77a0) | ![image](https://github.com/user-attachments/assets/4c006941-9ceb-4cf3-b822-f8512439ae21) |
| iOS | ![image](https://github.com/user-attachments/assets/8b257463-9d71-4419-b9fc-fd350662ad89) | ![image](https://github.com/user-attachments/assets/962de22e-3c71-4b7a-ae4b-7be54428c2eb) |
|---|---|
| ![image](https://github.com/user-attachments/assets/de3fef3a-3f1f-49c3-a53c-a9e03a4638a1) | ![image](https://github.com/user-attachments/assets/bae8c848-cd9c-4b37-b …
> fix(EMI-2053): Hide register by signal on auction screen

- android/app/src/main/java/net/artsy/app/MainApplication.kt
- src/app/NativeModules/LegacyNativeModules.tsx
- src/app/system/devTools/DevMenu/Components/DevTools.tsx
- src/app/utils/PushNotification.ts
Fixes a couple problems with our Android push set up:
- firebase manual registration happening early in app lifecycle causes onRegister not to be called on js side, believe this is unnecessary because we register in js
- braze registerToken call is failing in sdk, this warrants another look but currently causing saveToken not to be called
- android acts a little differently than iOS, calling requestPermissions does not result in onRegister being called again if already called, to workaround calling saveToken directly to make sure it is saved in that env
-
-
- fixes for push registration - brian 
-
</details> …
> fix: android push registration 

- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
This PR resolves [EMI-1897] 
This PR updates the requirement for the Contact Gallery modal form to allow users to send messages without the need to have any of the checkboxes selected but it still requires a message to be able to send to a gallery
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/fc89ed9d-3763-4d18-adab-e09b2972d2d7" /> | <video src="https://github.com/user-attachments/assets/1549ece5-5687-4398-a385-5febdcc11a12" /> |
| iOS | <video src="https://github.com/user-attachments/assets/7a131e01-b9e0-4ecc-87c0-ef7cd9b163ff" /> | <video src="https://github.com/user-attachments/assets/4b494ef7-e467-49b9-a58b-fb1b619d5252" /> |
- update Contact Gallery requirement to send with only a …
> fix(EMI-1897): Update Contact Gallery requirement to send messages

- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
- src/app/Components/PrefetchFlashList.tsx
- src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
This PR resolves [ONYX-1322] 
This PR comes as a fix for some issues after the past refactoring PRs to the artwork rails. 
__ Issue __
https://github.com/user-attachments/assets/0630c785-2ba2-474d-bfb0-b3c5a24ed6a2
__ After __
https://github.com/user-attachments/assets/727a6f7e-9e2f-42c2-823a-253b21dfab4f
**Rationale**
For some reason, `Flatlist` was struggling to calculate the width of the container in initial render and it led in some instances to the `RailCard` not covering the entire allowed area. Here I am setting the width and using `Flashlist` instead of `Flatlist` to take advantage of the performance improvements as well. 
- fix layout shifts for artwork rails
-
-
- use Flashlist for artwork rails - mounir
</details>
Need help with …
> fix: layout shifts for artwork rails

- src/app/Scenes/HomeView/HomeView.tests.tsx
- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
- chore(analytics): add tappedArticleGroup for Home View > ArticlesCards
- chore(analytics): add tappedArtworkGroup for Home View > FeaturedCollection
- chore(analytics): add screen analytics event for new Home View screen
This PR resolves [ONYX-1317](https://artsyproduct.atlassian.net/browse/ONYX-1317), [ONYX-1319](https://artsyproduct.atlassian.net/browse/ONYX-1319), and [ONYX-1323](https://artsyproduct.atlassian.net/browse/ONYX-1323).
-
-
-
- chore(analytics): add tappedArticleGroup for Home View > ArticlesCards
- chore(analytics): add tappedArtworkGroup for Home View > FeaturedCollection
- chore(analytics): add screen analytics event for new Home View screen
</details> …
> chore(analytics): implement missing analytics in new home view sections

- src/app/Scenes/HomeView/HomeView.tests.tsx
- src/app/Scenes/HomeView/HomeView.tsx
In this PR, I added support of `cacheable` to Eigen. It is however not possible to use that at the home view query because it is using `Me`. In this PR, I am fixing that by moving that `Me` query to be a standalone query. 
This has actually led to more performance gains! **167ms less** **or 37% faster**
| <img width="578" alt="Screenshot 2024-09-25 at 15 43 02" src="https://github.com/user-attachments/assets/2cb39c88-b64d-4c41-b97b-6c35ff6cfe6e"> | <img width="681" alt="Screenshot 2024-09-25 at 15 54 27" src="https://github.com/user-attachments/assets/01e9dd59-b457-4da9-8347-36d12e30c0be"> |
-
-
-
- improve home view query performance - mounir
</details>
Need help with something? Have …
> chore: improve home view query performance

- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
- src/app/utils/Sentinel.tsx
To ensure relevant UI is on screen before triggering analytics events, use `useFocusEffect`.
-
-
-
- chore(analytics): use ProvideScreenTrackingWithCohesionSchema for screen event
</details>
> chore(analytics): use useFocusEffect for screen event

- src/app/Scenes/HomeView/HomeView.tsx
[ONYX-1327]
This PR updates the `Homeview` to use `Flatlist` instead of `FlashList`
-
-
-
- use Flatlist in new home view - mounir
</details>
[ONYX-1327]: https://artsyproduct.atlassian.net/browse/ONYX-1327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: use Flatlist for new homeview

- src/app/AppRegistry.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/Home/HomeContainer.tests.tsx
- src/app/Scenes/Home/HomeContainer.tsx
This PR resolves [ONYX-1330] 
This PR exposes the new homeview to artsy people.
**For easier review, I suggest you hide white spaces**
-
-
-
- render new Homeview for artsy people - mounir
</details>
[ONYX-1330]: https://artsyproduct.atlassian.net/browse/ONYX-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: render new Homeview for artsy people

- src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsHeader.tsx
- src/app/Scenes/OrderHistory/OrderDetails/Components/TrackOrderSection.tsx
- src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
- src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
- src/app/utils/getOrderStatus.tests.ts
- src/app/utils/getOrderStatus.ts
This PR resolves [EMI-2112]
This PR adds a `payment failed` state to the order history along with a CTA to fix the failed payment. The work to expose that new payment failed state is still in progress, so there are no user-facing changes yet.
The `getOrderStatus()` method now returns a `string | null` rather than the string `'unknown'`. Unhandled (null) values are not rendered in the app - this should never happen.
<details><summary>📱Order history (failed payment state simulated)</summary>
<p>
</p>
</details> 
<details><summary>📱After clicking CTA</summary>
<p>
</p>
</details> 
- Enhancements to the order history screen when an order has a failed payment
-
-
-
</details> …
> feat(EMI-2112): failed payment order history

- src/app/AppRegistry.tsx
- src/app/Components/LoadFailureView.tsx
- src/app/Components/RetryErrorBoundary.tsx
- src/app/Providers.tsx
- src/app/Scenes/Artist/Artist.tsx
- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/MyCollection/MyCollection.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
- src/app/Scenes/Sale/Sale.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkFormEdit.tsx
- src/app/utils/AboveTheFoldQueryRenderer.tsx
- src/app/utils/renderWithPlaceholder.tsx
- src/app/utils/useDeepLinks.ts
This PR resolves [PHIRE-1196] 
- Updates a few error screens that were either dead ends (no nav) or not showing error messages.
- Stop tracking a few screens that are showing errors correctly
- Add an error message for devs in any error screen still being tracked
| Screen | Before | After |
|--------|--------|--------|
| SubmitArtworkEditForm | ![submit-artwork-edit-before](https://github.com/user-attachments/assets/6490f689-c874-4663-ab5c-500434973586)|![SubmitArtworkEditAfter](https://github.com/user-attachments/assets/8c8c011b-f7ca-4edc-b211-89ddd914f381)|
| Artist | ![artist-before](https://github.com/user-attachments/assets/fd20723c-d45c-48f2-be43-193d9a26c47d)| ![ArtistErrorAfter](https://github.com/user-attachments/assets/fd7f656b-fd36-40d5-979a-62d1f4847dfa)|
| Artwork …
> fix: fix some unable to loads

- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenPlaceholder.tsx
This PR resolves [https://www.notion.so/artsy/Would-be-nice-if-artwork-rails-used-skeleton-loaders-rather-than-spinners-when-viewing-all-10ecab0764a080509f0cc5ebf7701c03?pvs=4] 
This PR fixes the loading skeleton on the artworks section screen.
https://github.com/user-attachments/assets/0b0bd471-c588-4a9a-807f-9b38784b14a4
https://github.com/user-attachments/assets/ca96603d-3546-4661-a09e-aabf5e4f15df
#nochangelog
> fix: artworks screen loading skeleton

- src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
- src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
- src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
Addresses [Notion card](https://www.notion.so/artsy/Artwork-cards-don-t-have-heart-icon-10ecab0764a0807cb35fd5f10a699578?pvs=4)
Addressed in this PR: [chore(ONYX-1290): Remove artwork the rail size option & use large artwork rails everywhere](https://github.com/artsy/eigen/pull/10758)
In the `<LargeArtworkRail />` component `showSaveIcon` value defaults to `true`. On the `<ArtworkRail />` it defaults to `false`. If we want to show `showSaveIcon` on the `<ArtworkRail />` component we need to add it to the properties
https://github.com/artsy/eigen/pull/10758/files#diff-39b21dfbe8319ae394ce4112df93df27b7c99da48018d654b7540c4c7d89e669L23
- fix: add save icons back - daria
-
-
-
</details> …
> fix: add save icons back

- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
- src/app/routes.ts
- src/app/system/navigation/routes.tests.ts
This PR resolves [PBRW-59] 
This PR fixes a crash on iOS when navigating to saves through "Manage Saves" in the Activity Panel Partner Offer screen
It also updates the link registration to prevent crashes on iOS when navigating to the app using a deeplink with `/artwork-lists`
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/c90d54ab-0468-4252-834c-f89e5ebff74a" /> | <video src="https://github.com/user-attachments/assets/19d186a5-b4fc-4737-ba1f-ab8d69ca32c7" /> |
| iOS | <video src="https://github.com/user-attachments/assets/2c332f05-5c2a-4c31-8b50-faaaa865b882" /> | <video src="https://github.com/user-attachments/assets/933ef05b-8901-4a03-bd8c-63f4c545de61" /> |	
- fix crash on iOS when …
> fix(PBRW-59): Crash on iOS when navigating to saves from Activity Panel partner offer

- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
- src/app/Components/ArtworkRail/LegacyArtworkRailCardImage.tsx
- src/app/Components/ContextMenu/ContextMenuArtworkPreviewCardImage.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
This PR resolves [ONYX-1285] 
Implement a new Artwork Rail Card design (image only)
The artwork card within a rail should have 
- a consistent height of 215px
- a minimum width of 140px
- a maximum width of 340px
- If the image is thinner than the minimum width, a grey Black05 background is added. This should have a 10px padding at the top and bottom. 
- If the image is wider than the maximum width, a grey Black05 background is added. This should have a 10px padding on the left and right
| wide artwork | tall artwork | updated image skeleton New Home | updated image skeleton Old Home | outdated image skeleton Old Home |
| --- | --- | --- | --- | --- |
| ![Simulator Screenshot - iPhone 15 Plus - 2024-09-27 at 15 28 53](https://github.com/user-attachments/assets/0234cbb8-c49a-4741-85d1-4a890 …
> feat(ONYX-1285): change of the image size dimensions of an artwork rail card

- src/app/Components/ArticleCard.tests.tsx
- src/app/Components/ArticleCard.tsx
This PR resolves https://www.notion.so/artsy/Artsy-Editorial-rail-seems-to-be-the-only-one-whose-items-don-t-show-the-touchable-highlight-effect--10ecab0764a080d18fceee049b852ea7
Fixes a minor inconsistency that was present in both old and new home screens — the article rail was the only one whose card didn't have a touchable opacity highlight:
| <video src="https://github.com/user-attachments/assets/98f22760-815a-4b0e-afa9-879ec0003f4d" /> | <video src="https://github.com/user-attachments/assets/85b59b77-6a56-48ad-a9d5-ebee8734527f" /> | 
- Ensure consistent touchable highlight for articles rail — Roop
-
-
-
</details>
[app …
> fix(HomeView): ensure consistent highlight opacity for articles rail

- src/app/Components/ArtsyWebView.tests.tsx
- src/app/store/AuthModel.ts
- src/app/store/GlobalStore.tsx
- src/app/store/__tests__/AuthModel.tests.ts
- src/setupJest.tsx
This PR resolves [DIA-896] by adding a new `verifyUser` method to the `AuthModel` that can be used to check whether an email address belongs to an existing user or not.
It is a companion to artsy/gravity#18193
- Added more device information to user agent - iskounen
</details>
[DIA-896]: https://artsyproduct.atlassian.net/browse/DIA-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-896): add an auth model method to identify email addresses

- docs/generate_a_release_build_for_local_testing.md
Wanted to test something on device locally and ran into a few hiccups. This updates the docs a bit.
> docs(release-build): Update with screen cap and missing step

- src/app/Scenes/HomeView/Components/HomeHeader.tsx
- src/app/Scenes/HomeView/HomeView.tsx
This PR resolves [ONYX-1347]
We noticed that the safe area wasn't in use on the new home view Screen component, thus allowing for content to appear behind the status bar:
---
This PR toggles the safe area on, and adjusts the placeholder accordingly:
| <video src="https://github.com/user-attachments/assets/15b32ebf-def0-46d2-a097-c4f18b808d20" /> | <video src="https://github.com/user-attachments/assets/76eba366-ffd1-4566-9107-93bd531fae05" /> | 
- Respect safe area top inset on new home view — Roop
-
-
-
</details> …
> fix(home view): status bar safe area

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
- src/app/Scenes/Onboarding/Auth2/AuthContext.tsx
- src/app/Scenes/Onboarding/Auth2/AuthScenes.tsx
- src/app/Scenes/Onboarding/Auth2/__tests__/AuthApp.test.tsx
- src/app/Scenes/Onboarding/Auth2/__tests__/AuthContext.test.tsx
- src/app/Scenes/Onboarding/Auth2/__tests__/AuthScenes.test.tsx
- src/app/Scenes/Onboarding/Auth2/components/AuthModal.tsx
- src/app/Scenes/Onboarding/Auth2/components/AuthScreen.tsx
- src/app/Scenes/Onboarding/Auth2/components/__tests__/AuthScreen.test.tsx
- src/app/Scenes/Onboarding/Auth2/hooks/__tests__/useAuthNavigation.test.tsx
- src/app/Scenes/Onboarding/Auth2/hooks/useInputAutofocus.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/LoginOTPStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/WelcomeStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/ForgotPasswordStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginOTPStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginPasswordStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginWelcomeStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpNameStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpPasswordStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/utils/waitForSubmit.tsx
This cleans things up a bit more:
- Avoid the use of `useFormik` hooks [per the docs](https://formik.org/docs/api/useFormik#use-cases-for-useformik), and instead rely on standard `<Formik>`, which has performance benefits 
- On submit, collapse the keyboard, wait, then show keyboard again when the next screen appears. This is pretty standard native UX for mult-step login flows, and the only way we can get around the UI jank involving the keyboard QuickType bar (suggestions), which **jumps** the modal, vs animating, as the quick type bar appears / disappears instantly. 
Also stubbed out test files for a future PR. 
@iskounen - this one is pretty uncontroversial so gonna merge to get a beta out before monday but happy to follow up on any comments 👍 
cc @artsy/diamond-devs
> refactor(auth2): More smoothing out of auth screens 

- src/app/Components/Swipeable/Swipeable.tests.tsx
- src/app/Components/Swipeable/Swipeable.tsx
This PR resolves [EMI-2095] 
> [!NOTE]
> This PR is related to artsy/palette-mobile#263, we decided for the time being to move the work to Eigen.
> More info in the [Slack thread](https://artsy.slack.com/archives/C02JHHHKP5K/p1727790098522529?thread_ts=1727779387.115219&cid=C02JHHHKP5K) 🔒
This PR adds a swipeable component to Eigen
|---|---|
| <video src="https://github.com/user-attachments/assets/73a223ff-5586-4969-b837-b8a7211e48a9" /> | <video src="https://github.com/user-attachments/assets/a941add6-d28a-4434-ab8b-cf34994a7560" /> |
-
-
-
- Add swipeable component to Eigen - mrsltun
</details> …
> feat(EMI-2095): Add Swipeable component

- src/app/utils/PushNotification.ts
This PR resolves [PHIRE-1203] 
This avoids tracking push calls 2x. In some scenarios both our onInitialNotification and push notification configuration call both call handlePushNotification resulting in 2x analytics calls and probably other bugginess. This is a bandaid fix to debounce the analytics call. 
This revealed a couple problems:
- our navigation ready check is unreliable at least on Android, I believe it is because main nav is ready but not individual tabs, this is another motivation to refactor our nav code, the 2x push calls unintentionally makes push nav more reliable but it is flaky still
- our push integration is double handling push sometimes which should be fixed but I avoided because it made push nav less reliable …
> fix: debounce push analytics call to avoid double tracking 

- src/app/Scenes/Onboarding/Auth2/components/AuthModal.tsx
Quick follow-ups to https://github.com/artsy/eigen/pull/10896
> fix(auth2): PR follow-ups

- src/app/Scenes/Onboarding/Auth2/components/PasswordInput.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx
This PR resolves [DIA-898]
In order to prevent any drift between the implementation of the password input field between the sign-up and login flows, I created a shared component.
-
-
-
-
</details>
[DIA-898]: https://artsyproduct.atlassian.net/browse/DIA-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-898): use shared password field for sign-up and login [WIP]

- ios/Podfile.lock
- package.json
- src/setupJest.tsx
- yarn.lock
bump react-native-screens from 3.29.0 to 3.34.0
-
-
-
-  bump react-native-screens from 3.29.0 to 3.34.0 - gkartalis
</details>
> build(deps): bump react-native-screens from 3.29.0 to 3.34.0

- src/app/routes.ts
- src/app/system/relay/helpers/cacheHeaderMiddlewareHelpers.ts
- src/app/system/relay/middlewares/cacheHeaderMiddleware.ts
This PR makes a few adjustments to follow up on `@cacheable` [PR](https://github.com/artsy/eigen/pull/10842#issuecomment-2373992261). The goal here is to make it clear to developers when `@cacheable` is not going to take effect
| Use case | Screenshot |
| Dev added `@cacheable` to a query where `force` is set to `true` | ![Simulator Screenshot - iPhone 16 Pro - 2024-09-26 at 09 49 25](https://github.com/user-attachments/assets/cc587abd-70af-44d4-9686-e23a2b52001d) |
| Dev added `@cacheable` to a query where `nocache` is present in the URL  | ![Simulator Screenshot - iPhone 16 Pro - 2024-09-26 at 09 48 05](https://github.com/user-attachments/assets/556bd991-63f6-47a5-9a7b-943028922f5c) |
| Dev added `@cacheable` to a query where a specialized argument is present | …
> chore: better DX around for @cacheable

- scripts/utils/flip-table
- src/app/Components/Modals/LoadingModal.tsx
- src/app/store/GlobalStore.tsx
- src/app/store/config/features.ts
- src/app/system/navigation/ModalStack.tsx
- src/app/system/navigation/useReloadedDevNavigationState.tests.tsx
- src/app/system/navigation/useReloadedDevNavigationState.ts
This PR comes as a follow-up to https://github.com/artsy/eigen/pull/10189 and based on feedback [here](https://artsy.slack.com/archives/C07ANEV7RNV/p1728234779230509) (For Open source contributors; the spinner is quiet annoying and it's bad UX)
- Clarify that the spinner doesn't show up on release builds
- Add toggle to disable navigation state rehydration
- Flip table was missing an important command - `setup:artsy` - I added it.
___ **This is what you will see now instead of just a spinner - what do you think about it?** ___
**Second Thoughts**
Since the state is already hydrated on app start, maybe we can start saving the navigation state inside global store as well and have it ready for us 🤷. I can look at that at a future time 👀  …
> chore: improvements to ModalStack rehydration logic

- src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tests.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
- chore(analytics): update default view all behavior for auction results section
Discovered that we had the wrong value specified during a recent QA pass on the new Home View ([notes](https://www.notion.so/artsy/Eigen-Home-View-Analytics-Sync-112cab0764a0805391ecda25bf26fa33?pvs=4#112cab0764a080f1b136e01f7c79d6a0) 🔒 ).
#nochangelog
- chore(analytics): update default view all behavior for auction results section
</details>
> chore(analytics): update default view all behavior for auction results section

- src/app/Components/Swipeable/Swipeable.tsx
This PR resolves [EMI-2127] 
* Follow-Up PR for https://github.com/artsy/eigen/pull/10879
This PR adds swipe-to-interact functionality (swiping until the end without tapping on the action button) to the `Swipeable` component. We might fine-tune the interaction later after testing it on a real device.
https://github.com/user-attachments/assets/b51da737-0184-4f25-a1f4-865886c020b5
-
-
-
- Add swipe-to-interact functionality to `Swipeable` component (not used yet) - ole
</details>
[EMI-2127]: …
> feat: Add swipe-to-interact functionality to `Swipeable` component

- src/app/Scenes/HomeView/Sections/HomeViewSectionDiscoverMarketingCollections.tests.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionDiscoverMarketingCollections.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
- src/app/store/config/features.ts
This PR fixes the CI MP integration broken given a type that doesn't exist anymore for the element Discover Something New. Also protects the element from being displayed with ff.
- fix: Discover something new graphql type
-
-
-
</details>
> fix(DiscoverSomethingNew): fix graphql type

- ios/Podfile.lock
This PR updates some hashes in our Podfile.lock file that resulted from running:
```
cd ios && bundle exec pod update glog DoubleConversion --no-repo-update
```
- update glug and DoubleConversion pods - iskounen
> chore: update glog and DoubleConversion pods

- src/app/Components/SectionTitle.tsx
This PR resolves https://www.notion.so/artsy/Art-Advisor-Home-View-Feedback-abc1123548504ae58051405627fb6c9f?p=11acab0764a0800885a6eabc58c38e1b&pm=s
A sharp-eyed tester noticed that letters with descenders (g,j,p,q,y) were getting slightly clipped in the standard `SectionTitle` component.
Demonstrated here with those letters inserted and a background added  to show the clipping:
<details>
<summary>Details about the root cause…</summary>
- SectionTitle [takes](https://github.com/artsy/eigen/blob/7cd48256055229da0b538b1c330586014290ded0/src/app/Components/SectionTitle.tsx#L23) a `titleVariant` prop
- That prop [defaults](https://github.com/artsy/eigen/blob/7cd48256055229da0b538b1c330586014290ded0/src/app/Components/SectionTitle.tsx#L31) to `sm-display`
- That is …
> fix: allow visual overflow for title component

- src/app/Scenes/Home/Components/ShowsRail.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
This PR resolves [https://www.notion.so/artsy/Too-much-padding-below-Shows-for-You-section-iOS-production-11acab0764a080879716cabc4dec6e7b?pvs=4]
When working on this, I noticed that the bug reported is not really a bug, it's actually working as defined because I assume at least one show has a title that spans over 3 lines. I did however notice an issue when there are no shows available, the padding breaks.
**Before**
https://github.com/user-attachments/assets/a231ed79-5749-4994-a1bd-b82cb8272b02
**After**
https://github.com/user-attachments/assets/2fb3358e-c261-4ab9-aeb5-da7571bf842b
- fix shows for you rail broken padding when no shows are available on home - mounir
-
-
-
</details>
Need help with something? Have a look at our [docs], or get …
> fix: shows for you rail broken padding

- scripts/deploys/deploy-beta-android
- scripts/deploys/deploy-beta-ios
This PR comes as a follow-up to https://artsy.slack.com/archives/C02BAQ5K7/p1728649506233649?thread_ts=1728649134.119499&cid=C02BAQ5K7. 
In the thread above, I ran the deploy scripts and wasn't asked to confirm to override the ongoing build. After running the same request locally, I noticed that I was getting the build status as `success` while it was `running`. I assume there is something wrong with cache and I am trying to fix that by explicitly skipping the cache.
-
-
-
- skip cache when checking build status - mounir
</details>
[docs]: …
> chore: skip cache when checking build status

- src/app/utils/useHideSplashScreen.ts
This PR is an attempt to improve our homeview elements rendering logic. 
The idea from this PR is the following, we don't want to show an empty home view then suddenly have multiple sections show up at the same time. We can't avoid that because the home view query is still active. So what can we do about it?
We can wait for the prefetching query to finish. That's good, but! what if it takes forever or never finishes god forbid! 
How about we wait for a bit, enough for the query to finish (_usually_), then hide the splash screen. For how long should we wait, the average [query duration in datadog ](https://app.datadoghq.com/dashboard/z95-ftb-4qe/home-view-health?fromUser=true&refresh_mode=sliding&tpl_var_env%5B0%5D=%2A&from_ts=1728057263324&to_ts=1728662063324&live=true)
**Note: I know …
> fix: keep splash screen visible for 500ms

- index-common.js
- src/app/system/errorReporting/setupSentry.ts
This PR resolves [PHIRE-1263] 
- gets rid of bootstrap env
- updates sentry tracing init to use non-deprecated method
I started this ticket intending to lower our sample rate but then realized because we are initializing sentry 2x once without debug flag we are probably sending many more events due to this. 
I think we should try getting rid of the bootstrap environment, it only initializes a little earlier than our main sentry env and it causes duplicate event reporting in sentry, confusion on where to look for events and probably other issues due to having 2 initialized instances. I think if we want sentry initialized early we should do it on native side once if necessary. 
-
-
-
- remove sentry bootstrap env - brian 
</details>
Need help …
> chore: remove sentry bootstrap environment

- src/app/Scenes/Onboarding/Auth2/components/AuthModal.tsx
- src/app/Scenes/Onboarding/Auth2/hooks/useOnboardingAuth2Tracking.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
- src/app/store/AuthModel.ts
This PR resolves [DIA-815]
-
-
-
- Add AuthImpression and ResetYourPassword events to new auth flow - iskounen
</details>
[DIA-815]: https://artsyproduct.atlassian.net/browse/DIA-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(DIA-815): add AuthImpression and ResetYourPassword events (and more!)

- src/app/Scenes/CollectionsByCategory/Body.tsx
- src/app/Scenes/CollectionsByCategory/CollectionRail.tsx
- src/app/Scenes/CollectionsByCategory/__tests__/Body.tests.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
- replaces useClientQuery with useLazyLoadQuery
- adds FlashList for performance optimization of the collection list of rails
- adds missing UI elements such as Dividers
- fix the navigation bug from the collection rail, now navigates when tapping on artworks or in the title
- few Chriss' requests about relay variable naming and use of plural
https://github.com/user-attachments/assets/d52cda90-0bde-4d66-8a0d-43411df72d49
- refactor:  address bugs, layout issues, and relay fetching bugs of collections by category work
-
-
-
</details>
[docs]: …
> feat(ExploreBy): address bugs, layout issues and relay fetching bugs

- src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
- src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
- src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx
- src/app/Scenes/Collection/Screens/CollectionArtworks.tests.tsx
- src/app/store/config/features.ts
This is a second PR to resolve EMI-2139
This is second pr to clean up tasks to remove feature flags for signals works.
-
-
-
- remove AREnableCuratorsPicksAndInterestSignals feature flag - oxaudo
</details>
> chore: remove AREnableCuratorsPicksAndInterestSignals feature flag

- src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
This PR resolves [ONYX-1375] 
After the latest redesign and refactoring the UI of the SellWithArtsyRecentlySold Rail does not look correct.
Let’s adjust it to make the data on the artwork card assessable 
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5c9551ec-8df1-4bba-a541-9492d8ba3047) | ![image](https://github.com/user-attachments/assets/551d8040-db8c-4c99-8728-90ddf7483077) |
- fix SellWithArtsyRecentlySold Rail layout - daria
-
-
-
</details>
[ONYX-1375]: …
> fix(ONYX-1375): fix SellWithArtsyRecentlySold Rail layout

- src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
This PR resolves this QA launch-blocking bug:
https://www.notion.so/artsy/Border-around-artwork-rail-images-12acab0764a080e298c1d1ca455895c9
| <img width="100%" src="https://github.com/user-attachments/assets/f77ca03b-e492-4daa-8815-1ec7c24c8ff3" /> | <img width="100%" src="https://github.com/user-attachments/assets/cfc1ce82-191f-440c-b38a-01c003bfec8f" /> | 
QA uncovered an issue where some images appear to have hairline rules visible on their borders. 
(See ⬆️ in the **Before** column the sides of the first image and the top/bottom of the second image.)
The hairline itself, if you really zoom in there, turns out to be the blurhash showing through because it is not completely covered by the final image! Notice the gradient from the pale green down …
> fix(artwork rail): change image resize mode to "cover"

- e2e/flows/onboarding/signup.yml
- src/app/Scenes/Onboarding/Auth2/hooks/useCountryCode.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpNameStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpNameStep.tests.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
This PR resolves [DIA-927] 
This PR updates the auth2 sign-up flow to conditionally display a checkbox that users can check to enroll in email subscriptions depending on whether it is required or not.
| Required | Not Required |
|----------|--------------|
| ![Screenshot_1729885615](https://github.com/user-attachments/assets/4bcc4ce3-0350-4d7a-8ade-aae2c935af7f) | ![Screenshot_1729885602](https://github.com/user-attachments/assets/a38c9244-37b7-4f4a-b59a-465c624a5e54) |
- 
-
-
- conditionally display email enrollment checkbox during sign-up (auth2) - iskounen
</details> …
> feat(DIA-927): conditionally display email enrollment checkbox during sign-up

- src/app/Scenes/Home/HomeContainer.tsx
- src/app/Scenes/Onboarding/OnboardingWelcome.tsx
- src/app/utils/useAndroidAppStyling.ts
This PR resolves [PHIRE-1287] 
Fixes a regression that was introduced in https://github.com/artsy/eigen/pull/10953. The issue was reported by @dblandin in slack (see [thread](https://artsy.slack.com/archives/C02BAQ5K7/p1729773548707709))
|After||
|---|---|
|Device has|Light Theme|
|![Screenshot_20241029-145018](https://github.com/user-attachments/assets/4c89e896-e674-4644-b177-14cff4811dbf)|![Screenshot_20241029-130921](https://github.com/user-attachments/assets/969cd621-bcb8-48bd-9595-eb728cd2af8e)|
|![Screenshot_20241029-130941](https://github.com/user-attachments/assets/6bd45b71-8928-496d-9591-6d61c659cb47)|![Screenshot_20241029-131001](https://github.com/user-attachments/assets/7954b68e-af14-401b-b504-abb4d67d9b05)|
|Device has|Dark Theme| …
> fix: StatusBar fixes

- src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
This PR addresses the artwork title and artist name truncation not happening properly on android. - Surfaced during our mobile QA Session https://www.notion.so/artsy/Android-Artwork-title-not-center-aligned-cuts-off-on-Artwork-Rails-12acab0764a08052b672dac3c0c0d79a?pvs=4
Context:
Seems like our palette-mobile text doesn't handle properly the `ellipsizeMode` properly although the prop is being passed correctly, I am thinking that it might have to do with styled components.
In the meantime found this workaround, using RNText (the original react native text) as a wrapper / parent for the problematic surfaces the palette-mobile texts seem to inherit correctly both `numOfLines` and `ellipsizeMode`. 
See screenshots below:
|Before|After|
|---|---|
|<img width="410" …
> fix: truncated text+no ellipsizeMode on Android rail card meta

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFromMyCollectionArtworks.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkFromMyCollection.tests.tsx
This PR resolves [ONYX-1381] 
This PR fixes a launch-blocking bug. The artwork ID is not present on the Image step in the SWA flow when choosing an artwork from My Collection. However, the ID is necessary to upload assets/images to the submission.
The ID is not present in this step because, after choosing the artwork, the form values get initialized, but no submission is created (-> no ID).
This PR is a quick fix, and I will follow up with some simplifications. It should be able to create a submission from a My Collection artwork by just passing the artwork ID to the `createSubmission` mutation, which we should do in this case. This way, the form values do not have to be initialized manually.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Plus - 2024-10-31 at 11 07 …
> fix: Missing artwork ID in SWA My Collection flow

- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFromMyCollectionArtworks.tsx
This PR resolves [ONYX-1381](https://artsyproduct.atlassian.net/browse/ONYX-1381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Related to https://github.com/artsy/eigen/pull/11045
**Description**
This PR fixes a launch-blocking bug. The artwork ID is not present on the Image step in the SWA flow when submitting an artwork from My Collection for sale. However, the ID is necessary to upload assets/images to the submission.
The ID is not present in this step because, after choosing the artwork, the form values get initialized, but no submission is created (-> no ID).
This PR is a quick fix, and I will follow up with some simplifications. It should be able to create a submission from a My Collection artwork by just passing the artwork ID to the …
> fix: Missing artwork ID in My Collection Submit for Sale flow

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Scenes/Activity/components/NotificationArtworkList.tsx
- src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
Follows up on https://github.com/artsy/eigen/pull/10988
This is an attempt to refactor and decouple the Activity screen code to avoid bugs like the one fixed in https://github.com/artsy/eigen/pull/10988. I noticed that the artwork list component, which is used for many activity types, contains some type-specific elements and optimizations and tried to move them out of the component.
| Before | After (iOS) | After (Android) |
|![Simulator Screenshot - iPhone 15 Plus - 2024-11-04 at 12 33 48](https://github.com/user-attachments/assets/020f592d-5f23-4416-a28f-2eb206ad573b) | ![Simulator Screenshot - iPhone 15 Plus - 2024-11-04 at 12 34 25](https://github.com/user-attachments/assets/88a9e18d-b189-484a-b510-1a85de9536e4)|![Screenshot_20241104_130202](https://github.com/user- …
> chore: Activity screen refactoring & code decoupling

- src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
- src/app/store/AuthModel.ts
- src/app/store/__tests__/AuthModel.tests.ts
This PR resolves [DIA-899] 
- Adds a new method for Google Sign-In that the auth2 flow uses to authenticate in one-shot (sign-up and login together)
- Displays a loading screen while Google Sign-In is doing its thing
https://github.com/user-attachments/assets/cb9a6b60-fda5-469b-9274-4e1160a5554b 
-
-
-
- Implement one-shot Google Sign-In for auth2 - iskounen
- Display a loading screen during Google Sign-in for auth2 - iskounen
</details>
[DIA-899]: https://artsyproduct.atlassian.net/browse/DIA-899?atlOrigin=e …
> feat(DIA-899): One-Shot Google Sign-In

- src/app/store/__tests__/AuthModel.tests.ts
I forgot to remove a `fit` from #11036 so this PR does that and removes some mocks that were causing other tests in the suite to fail.
> fix: remove focus from a test in the AuthModel test suite

- src/app/Scenes/HomeView/HomeViewContext.ts
- src/app/Scenes/HomeView/__tests__/HomeView.tests.tsx
- src/app/Scenes/HomeView/useHomeViewExperimentTracking.ts
This PR resolves [ONYX-1371] 
Follow-up to #11048 which ensures that each experiment's `experiment_viewed` event is fired only once per session.
Recording here of Metaphysics + Eigen to demonstrate:
1. Initial home view request returns one experiment (`onyx_experiment_home_view_test`)
2. That experiment gets tracked
3. During the same session _another_ experiment is enabled (`onyx_experiment_home_view_test_2`)
4. That experiment also gets tracked, without re-firing the event for the first one.
<video src="https://github.com/user-attachments/assets/ee640155-9dd6-4f17-a8f1-d6201fbc88c9" />
-
-
-
- Ensure experiment_viewed fired only once per home view experiment
</details> …
> feat(home view, analytics): fire experiment event only once per session

- src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
- src/app/store/AuthModel.ts
- src/app/store/__tests__/AuthModel.tests.ts
- src/app/utils/auth/authHelpers.ts
- src/app/utils/auth/socialSignInHelpers.ts
This PR resolves [DIA-903] 
This PR adds one-shot Facebook Login to Eigen.
| https://github.com/user-attachments/assets/465b4696-4c10-43a4-b6a3-d03d7755604d | https://github.com/user-attachments/assets/bcc3f997-3670-4e49-a6e3-a137949e700f |
-
-
-
- Implemented one-shot facebook login for auth2 - iskounen
</details>
[DIA-903]: https://artsyproduct.atlassian.net/browse/DIA-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-903): One-Shot Facebook Login

- src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionArticles.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCards.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionFeaturedCollection.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionSales.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionViewingRooms.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/Section.tests.tsx
- src/app/Scenes/HomeView/__tests__/HomeView.tests.tsx
This PR resolves [ONYX-1249] 
This addresses some gaps in test coverage in the new home view frontend code:
- I used Jest's code coverage capabilities to assess which implementations were most lacking in coverage.
- I aimed to get red of all the 🔴 red that I could, but left 🟡 yellow alone: i.e. improvement not perfection
```sh
yarn jest src/app/Scenes/HomeView --coverage --collectCoverageFrom="src/app/Scenes/HomeView/**/*"
```
Consider this also a plea to prioritize test coverage as you add to the home view.
Here's another example of leveraging Jest to help you ensure that you've added a suitable amount of coverage when working on an implementation:
```sh
yarn jest --watch \
src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCards.tests.tsx \
--coverage --collectCoverageFrom …
```
> test(home view): improve coverage 

- src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
- src/app/store/config/features.ts
This PR enables the AREnableSignupLoginFusion feature flag, which will display the new auth flow to users. It also has an accompanying Echo flag: artsy/echo#687
- Display a redesigned sign up and login flow to users - iskounen
-
-
- 
</details>
> chore: enable AREnableSignupLoginFusion

- src/app/utils/useDeepLinks.ts
This PR resolves https://www.notion.so/artsy/Deeplink-opened-analytics-event-called-twice-13bcab0764a080b78390cf08dbc51759?pvs=4
This PR fixes an issue where deep links calls are getting triggered twice. This was happening because I forgot to check if the navigation is ready before handling the deep link.
| <Video src="https://github.com/user-attachments/assets/40da0526-0e1e-4e35-a41f-497976f2e6ec" /> | <Video src="https://github.com/user-attachments/assets/cc2c8f4c-a9d0-4710-bfb5-550958b839c7" /> | 
-
-
-
- fix deep link analytics event triggered twice - mounir
</details> …
> fix: deep link analytics event triggered twice

- src/app/Scenes/Sales/Sales.tests.tsx
Sales test is testing an expensive component, nothing stands out as a problem from the tests. Ideally, we would want to test only the element with the fragment but we're testing something like:
```jsx
<ProvideScreenTrackingWithCohesionSchema
info={screen({ context_screen_owner_type: OwnerType.auctions })}
>
<Suspense
fallback={
<PageWithSimpleHeader title="Auctions">
<Flex flex={1} justifyContent="center" alignItems="center">
<Spinner testID="SalePlaceholder" />
</Flex>
</PageWithSimpleHeader>
}
>
<Sales />
</Suspense>
</ProvideScreenTrackingWithCohesionSchema>
```
The timeout increased in the first test should do the job, but ideally we want to revisit this component structure and then refactor the test to test something lighter.
#noChangelog …
> test(Sales): increase test's timeout

- docs/best_practices.md
- src/app/Components/AnimatableHeader/AnimatableHeaderProvider.tsx
- src/app/Components/Disappearable.tsx
- src/app/Components/Swipeable/Swipeable.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingWelcome.tsx
- src/app/Scenes/Onboarding/OnboardingWelcome.tsx
- src/app/Scenes/Playground/Animation/L2-Shared-Values/App1.tsx
- src/app/Scenes/Playground/Animation/L2-Shared-Values/App2.tsx
- src/app/Scenes/Playground/Animation/L2-Shared-Values/App3.tsx
- src/app/Scenes/Playground/Animation/L2-Shared-Values/App4.tsx
- src/app/Scenes/Playground/Animation/L2-Shared-Values/App5.tsx
- src/app/Scenes/Playground/Animation/L5-Exercice/index.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
- src/app/utils/animations/useSkeletonAnimation.tsx
This PR resolves [PHIRE-1347] 
related palette PR https://github.com/artsy/palette-mobile/pull/284
After upgrading reanimated we noticed a bunch of new warnings coming up. 
They pointed to a missuse of useSharedValue, as seen [here](https://docs.swmansion.com/react-native-reanimated/docs/core/useSharedValue/#react-compiler-support) we need to avoid accessing the .value directly and also mutating values directly .value = "whatever".
Instead we should use the getters and setters as pointed in the PR below.
Nothing changes in the functionality of the animations.
-
-
-
- proper usage for useSharedValue - gkartalis
</details> …
> refactor: proper usage for useSharedValue

- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountEmail.tests.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tests.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountPassword.tests.tsx
- src/app/Scenes/Search/components/SearchInput.tests.tsx
Palette mobile inputs have been updated to be uncontrolled for performance benefits: https://github.com/artsy/palette-mobile/pull/281
This is a good change but caused some tests to fail: https://app.circleci.com/pipelines/github/artsy/eigen/61963/workflows/a45351d9-8ce7-457f-aa97-194eec848590/jobs/214287/parallel-runs/6?filterBy=FAILED, these tests are generally of the form "type something" then "check if the value exists in the input", since value is not set in input in uncontrolled inputs these fail. Talked with George and we think these tests are really just basic funcionality of inputs themselves and are already tested in palette-mobile so just getting rid of them. We did verify in both onboarding and search that the new inputs work and show text. …
> chore(tests): delete tests that fail for uncontrolled input

- src/app/Components/ArtworkRail/ArtworkRail.tsx
this issue found on Sprintly Mobile QA https://www.notion.so/artsy/Android-Weird-issue-with-wide-artwork-on-rails-could-be-from-the-artwork-130cab0764a080009cc6f1cb704f9cda?pvs=4
[slack thread for context](https://artsy.slack.com/archives/C02BAQ5K7/p1732102644251849)
This PR reverts using Flashlist to using Flatlist for two reasons:
- The first one is to solve the issue of when scrolling too fast on Android that some images were resized 
- The second one (discovered while testing) is that I guess due to not having pagination Flatlist is drawing the list elements on the screen way faster than Flashlist did. 
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/73939d0a-dea1-4c6b-8970-be670ee92484" width="300" />|<video …
> refactor: replace prefetchFlashList with PrefetchFlatList on rails

- src/app/Components/HeaderArtworksFilter/HeaderArtworksFilter.tsx
- src/app/Components/HeaderArtworksFilter/HeaderArtworksFilterWithTotalArtworks.tsx
- src/app/Scenes/Show/Components/ShowArtworks.tsx
- src/app/Scenes/Show/Show.tsx
This PR resolves [https://www.notion.so/artsy/Exhibition-Show-screen-scrolling-is-broken-13bcab0764a0809cb406ec574324170d?pvs=4] 
This PR fixes two issues related to the show artworks screen:
1. When scrolling the list of artworks, the artworks are sticky (I fixed that by fixing the sticky header indice on the Flatlist)
2. The list of artworks is not showing up - I fixed that by setting the same aggregations as in Web - I asked [here](https://artsy.slack.com/archives/CP9P4KR35/p1731938659234709) for a better understanding
| <Video src="https://github.com/user-attachments/assets/c33bff54-47fa-4dd7-9d04-9ad1f2da6bd9" > | <Video src="https://github.com/user-attachments/assets/95745642-703e-4980-ba2e-43ba30976a22" > |  …
> fix: scroll on show artworks screen

- src/app/Components/GlobalSearchInput/GlobalSearchInput.tests.tsx
- src/app/Components/GlobalSearchInput/GlobalSearchInput.tsx
- src/app/Scenes/Search/Search.tests.tsx
- src/app/Scenes/Search/Search.tsx
https://www.notion.so/artsy/Input-placeholder-copy-144cab0764a0806aae2dd64bef9b6f48?pvs=4
This PR updates the placeholder copy on the search modal input 
https://github.com/user-attachments/assets/468dfcae-f442-499f-b743-bd7addeace33
#nochangelog
> chore: update placeholder copy on search modal

- src/app/Scenes/Map/GlobalMap.tsx
This PR resolves [https://www.notion.so/artsy/City-guide-drop-down-misaligned-not-sure-if-new-13bcab0764a080838854d7f873a0b78e?pvs=4] 
This PR fixes the broken padding on the city guide after the latest navigation changes.
| ![IMG_3D3FA04DBC6D-1](https://github.com/user-attachments/assets/1c664d59-47cb-4ec7-851e-66bc47818e4f) | <img width="744" alt="Screenshot 2024-11-19 at 19 08 41" src="https://github.com/user-attachments/assets/f52012ad-308c-4915-9e1f-0aaaaa1456d7"> | 
- city picker padding on city guide - mounir
-
-
-
</details> …
> fix: city picker padding on city guide

- src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
- src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
This PR partially resolves [DIA-629] 
While deprecating the `AREnableNewTermsAndConditions` feature flag I was prevented from committing my changes because of a large number of ESLint errors in the `ConfirmBid` component and its tests.
This PR addresses those errors so that I can make changes to these files and commit them without having to use `--no-verify` and potentially miss a real error.
-
-
-
- Removed ESLint errors from ConfirmBid component and tests
</details>
[DIA-629]: …
> chore(DIA-629): address eslint errors in ConfirmBid component and tests

- src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx
This PR resolves
https://www.notion.so/artsy/Sliding-from-the-left-doesn-t-navigate-me-back-to-the-home-screen-after-opening-the-search-iOS-144cab0764a080e8956be0dfb69642cc?pvs=4
This PR hides the search modal on back button press
___
**Using Back Button**
https://github.com/user-attachments/assets/615c5b14-fcd3-439b-9ade-9e5a2e5a67b5
___
**Using the back gesture**
https://github.com/user-attachments/assets/013f4b98-14f7-41da-b28d-40998834da35
#nochangelog
> chore: hide search modal on back button press

- src/app/Scenes/Search/SearchArtworksGrid.tsx
https://www.notion.so/artsy/Shall-we-close-the-virtual-keyboard-when-the-user-scrolls-through-the-results-Especially-when-searc-144cab0764a08094965cc81ccdd72c6b?pvs=4
This PR updates the keyboard behaviour on the artworks grid to dismiss on scroll.
https://github.com/user-attachments/assets/67e76964-32cf-4a45-8419-2e6effc86ba4
#nochangelog
> chore: hide keyboard after scroll on artwork list

- src/app/Scenes/Search/SearchModel.tests.tsx
- src/app/Scenes/Search/SearchModel.tsx
https://www.notion.so/artsy/Recent-Searches-still-capped-at-5-max-rendered-result-event-though-more-seem-to-be-persisted-availab-144cab0764a080f29629f220c45f5a29?pvs=4
This PR increases the number of recent searches allowed in the new search modal
#nochangelog
> chore: increase max returned recent searches

- src/app/Components/GlobalSearchInput/GlobalSearchInputOverlayEmptyState.tsx
https://www.notion.so/artsy/Clicking-on-the-empty-area-below-the-Recent-Searches-results-or-the-Find-art-you-love-title-only-144cab0764a0806f86aec1b483fef148?pvs=4
This PR makes the text on the new search modal non selectable
#nochangelog
> chore: make text non selectable on search modal

- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
- src/app/Components/ArtworkRail/ArtworkRailUtils.tsx
- src/app/Components/ArtworkRail/ArtworkSaleMessage.tsx
- src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
- src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tsx
- src/app/store/config/features.ts
Resolves [Need an alternative for dark mode (if we’re continuing with Curator’s picks in current format)](https://www.notion.so/artsy/Need-an-alternative-for-dark-mode-if-we-re-continuing-with-Curator-s-picks-in-current-format-13ecab0764a0804eb63cf9241e9ea903?pvs=4)
It's not clear when the dark background is going to be removed from the Curator's Picks rail, so implementing dark mode support for new Save and Follow CTAs
| Before | After | Android |
| --- | --- | --- | 
| ![image](https://github.com/user-attachments/assets/cfa19396-1d89-4291-8010-03aec59ba2d5) | ![image](https://github.com/user-attachments/assets/488272b7-eaa2-4c98-b58a-fcbc9067ca4d) | ![Screenshot_1732101888](https://github.com/user-attachments/assets/98cf8429-3289-4299-bf86-0d33f038bd1f) | …
> chore: support dark mode for new Save and Follow CTAs

- src/app/Components/GlobalSearchInput/GlobalSearchInput.tests.tsx
- src/app/Components/GlobalSearchInput/GlobalSearchInput.tsx
- src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx
- src/app/Components/GlobalSearchInput/utils/useDismissSearchOverlayOnTabBarPress.ts
- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/Scenes/HomeView/Components/HomeHeader.tsx
- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/Search/Search.tsx
This PR allows us to dismiss the search overlay on tab bar press. While working on this, I noticed that the overlay was closing twice on both tabs. This is because we had the same new for the portal - so I separated the naming of the portals.
https://github.com/user-attachments/assets/074996b8-c42b-4756-821c-0df1bf3c822a
#nochangelog
> chore: search overlay on tab press

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
Visit any screen with visible tab on the home view
Go to Search
Go back to Home
Expected result:
- Find yourself in the screen you were at
Actual result:
- Navigate back to home view
| <Video src="https://github.com/user-attachments/assets/474708bd-9585-43b5-b5b7-76d8e11413ee" /> | <Video src="https://github.com/user-attachments/assets/371e2bb8-e37f-42bf-8314-a2e4d7af2542" /> | 
#nochangelog
> fix: navigate back to tab behaviour

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
Addresses notion bug: https://www.notion.so/artsy/variant-b-variant-c-The-meta-data-is-not-visible-on-the-grids-on-the-artist-page-but-show-up-when-13ecab0764a0805891ffdb96af05ac79?pvs=4
Follow up on https://github.com/artsy/eigen/pull/11134. The fix in this PR was **breaking** alignment of the save CTA:
Because we use different flexDirection value for different experiments, the layout was breaking. When displaying the data in a column, we need to use flexGrow and when in the row - flex.
```
flexGrow={positionCTAs === "column" ? 1 : undefined}
flex={positionCTAs === "row" ? 1 : undefined}
```
**Fix:**
| Fixed missing metadata data on the grids on artwork screen | Fixed Save CTA alignment |
| --- | --- |
| ![IMAGE 2024-11-21 …
> fix: fix icons and metadata alignment on ArtworkGridItem

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/Navigation/Utils/useBottomTabsBadges.tests.ts
- src/app/Navigation/Utils/useBottomTabsBadges.ts
- src/app/Scenes/BottomTabs/bottomTabsConfig.tsx
This PR comes as a follow-up on https://github.com/artsy/eigen/pull/10977
**Motivation:**
Currently, we have our own buttons to render the bottom tab bars. The button is listening to state changes, visual clues changes, watches for unread conversation and notifications count, and has plenty of logic that makes it a lot more expensive than it should be. This led in the past to delays when tapping it and it's quite easy to mess up things inside it and affect performance.
In this PR, I am suggesting that we align with react-navigation bottom tabs API and take advantage out of the box of all the performance improvements it comes with. There isn't something that I can think of that we can not do with the new API that we could have had before, I could however think of so many improvements this …
> feat: simplify bottom tabs logic

- package.json
While looking at the perf docs I saw this consequential little flag: https://reactnative.dev/docs/0.75/build-speed
```
When building your android app locally, by default you build all the 4 [Application Binary Interfaces (ABIs)](https://developer.android.com/ndk/guides/abis) : armeabi-v7a, arm64-v8a, x86 & x86_64.
However, you probably don't need to build all of them if you're building locally and testing your emulator or on a physical device.
This should reduce your native build time by a ~75% factor.
```
This was a very unscientific test of two clean builds so maybe others can try and see how it goes but it seems significant 👀 🙏 :
```
With the flag:
BUILD SUCCESSFUL in 39s
Without the flag:
BUILD SUCCESSFUL in 2m 28s
With the flag: 
BUILD SUCCESSFUL in 40s
Without …
```
> chore(speed): use recommended arch flag for local android builds

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
This PR brings back the staging indicator to the bottom tabs
-
-
-
- bring back staging indicator on bottom tabs - mounir
</details>
> fix: bring back staging indicator on bottom tabs

- src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
This PR removes `@cacheable` from the `HomeViewSectionTasks` query. The latter sets `force` to `true` and therefore by definition should not be cacheable.
| <img src="https://github.com/user-attachments/assets/37bd626e-32e5-43af-a273-59f5e47367f1" /> | <img src="https://github.com/user-attachments/assets/6e84b71d-a640-4abb-a742-e699d0078feb" /> | 
#nochangelog
> fix: remove @cacheable from HomeViewSectionTasks

- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/__tests__/HomeView.tests.tsx
- src/app/utils/hooks/useIsDeepLink.tests.ts
- src/app/utils/hooks/useIsDeepLink.ts
- src/app/utils/useHideSplashScreen.ts
This PR resolves [ONYX-1392] 
Co-authored-by: @brainbicycle 
Co-authored-by: @MounirDhahri 
Co-authored-by: @olerichter00 
The goal here is to avoid prefetching when following a deep link, in order to avoid an unnecessary [stampede](https://artsy.slack.com/archives/CA8SANW3W/p1731532192977049?thread_ts=1731531969.773739&cid=CA8SANW3W) that results in API latency.
We observe that prefetching happens in a few ways:
1. A lighter home view prefetch is initiated from the splash screen
- can be avoided by checking if we are following a deep link
2. A heavier prefetch for a subset of home view sections’ content
- can also be avoided by declining to render the home view _at all_ when launching via deep link
2. Content for other tabs is initiated from the home view
- can be avoided thanks to the …
> fix: avoid prefetching when following deeplinks

- src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/ForgotPasswordStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/ForgotPasswordStep.tests.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginPasswordStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginPasswordStep.tests.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpPasswordStep.test.tsx
- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpPasswordStep.tests.tsx
This PR resolves [DIA-942] 
This PR adds tests for the remaining user flows in the new auth flow after #11183.
-
-
-
- Added more tests for Auth2
</details>
[DIA-942]: https://artsyproduct.atlassian.net/browse/DIA-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(DIA-942): add tests for auth2

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
This PR resolves https://artsyproduct.atlassian.net/browse/PBRW-175
This PR fixes the broken bottom navigation on tablets
#nochangelog
> fix: broken bottom tabs on tablets

- src/app/Scenes/Onboarding/OnboardingWebView.tsx
This PR resolves
https://artsyproduct.atlassian.net/browse/PBRW-178
This PR fixes the back button on the terms and conditions on the new onboarding
https://github.com/user-attachments/assets/ab234b6b-7740-4504-a243-accf5e75aff8
#nochangelog
> fix: broken back button on terms

- src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx
- src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
- src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tsx
This PR resolves https://www.notion.so/artsy/Android-back-button-doesn-t-navigate-back-across-the-app-146cab0764a080a1be5adf144fb06dfb?pvs=4
This PR fixes the android back navigation issue that was reported during the QA session. 
Two issues were present:
- `gestureEnabled` wasn't set to `true`
- the search modal was overriding the default back handler 
https://github.com/user-attachments/assets/eef4601d-6b43-494e-ab69-9d81b6bc5ff3
-
-
-
-
</details>
> fix: back navigation on android

- src/app/AppRegistry.tsx
- src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
- src/app/Scenes/Sale/Components/SaleHeader.tsx
- src/app/Scenes/Sale/Sale.tsx
This PR resolves https://www.notion.so/artsy/Sort-and-filter-on-Auction-page-goes-below-tabs-146cab0764a08043b5c2d28656bcd197?pvs=4
This PR fixes the issue with the sort and filter button. In order to avoid such regressions happening again, I changed the logic slightly to make sure that the screen is always rendered with palette **Screen** component. This would save us the effort of getting the paddings/margins on point
https://github.com/user-attachments/assets/8362445d-82f3-466e-911b-0484c5504ff0
#nochangelog
> fix: sort and filter button on auction screen

- src/app/AppRegistry.tsx
- src/app/Components/ArtsyWebView.tsx
- src/app/routes.ts
- src/app/system/navigation/navigate.ts
- src/app/system/navigation/routes.tests.ts
This PR fixes an issue with tapping on `my-profile` on a webview.
**What was the root cause of the issue?**
When we need to switch from a modal to a screen nested in a tab where the modal is not present, `react-navigation` gets confused. We avoid that by baby sitting it: first dismiss the modal then navigate to the tab, then to the screen. In our case, none of that was happening because I forgot to note MyProfile tab/screen as a "Tab screen".
https://github.com/user-attachments/assets/0ad11c53-ba0b-40ee-91be-ba711af9860b
#nochangelog
> fix: broken my-profile tap after purchase

- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
- src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
This PR resolves [ONYX-1383] 
Use flatList instead of FlashList on artwork rails
Follow-up on https://github.com/artsy/eigen/pull/11142: The max and min width for the artwork rail card were missing. Adding these constraints resolved the issue where the metadata was stretched to its full width. More details: https://artsy.slack.com/archives/C02BAQ5K7/p1732116471982649
Summary after the bug investigation: https://artsy.slack.com/archives/C02BAQ5K7/p1732102644251849
Screenshots confirming that the layout of the artwork rail card is not broken when using FlatList
| Android FF is off | Android FF is on | iOS FF is off | iOS FF is on |
| ![Screenshot_1732712502](https://github.com/user-attachments/assets/342528fc-d015-40e3-b3d0-24817103b32f) | …
> fix(ONYX-1383): some artwork rail images get mangled after horizontal scrolling

- src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
- src/app/Scenes/Search/SearchArtworksGrid.tests.tsx
This PR fixes an outstanding issue we have with the filter modal which still rely on the old `FancyModal` 😮.
`FancyModal` is actually no longer needed and IMO, **should** be deprecated because there is nothing we can't do anymore with the native Modal component and we don't need the cards stack and the **extremely** complicated custom cards layering logic.
#nochangelog
> fix: sort & filter modal performance issues

- src/app/App.tsx
- src/app/Scenes/Search/Search.tsx
- src/app/system/errorReporting/setupSentry.ts
- src/setupJest.tsx
Some follow-ups now that our navigation is not quite as weird! 
- removes custom nav instrumentation that is no longer necessary
- wrap app if debugging sentry 
- try out sentry profiling on the search screen
-
-
-
- update sentry perf monitoring - brian 
</details>
> chore(performance): sentry performance updates

- src/app/Components/Toast/ToastComponent.tsx
- src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
This PR fixes the issue with the Artsy Guarantee toast that shows up in Conversation screen
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/b55d3f96-3eaa-4dc1-b739-4a6249fb7207" /> | <video src="https://github.com/user-attachments/assets/726ce0d4-ebdc-404b-b409-812c23a96ebd" /> |
| iOS | <video src="https://github.com/user-attachments/assets/076b618c-2a9c-4cd5-8d19-48f4b0cb51ee" /> | <video src="https://github.com/user-attachments/assets/6f1f2120-9cc2-45ba-a757-28d0ca457b48" /> |
- fix Artsy Guarantee toast position
-
-
-
</details> …
> fix: Update Artsy Guarantee position in Conversation

- src/app/utils/useDeepLinks.ts
This PR reverts the changes on artsy/eigen#11110 since we believe it introduced a bug when opening notifications on iOS from a killed state
The bug is not allowing the deeplinking to work after tapping the notification
This is an attempt to fix the [bugs reported](https://www.notion.so/artsy/Braze-push-Does-not-navigate-the-user-from-killed-state-14ccab0764a0801a80b2c19af333ea32?pvs=4) 🔒 in the release candidate branch
<details><summary>Changelog</summary>
- fix broken deeplinking with iOS push notification from killed state
</details>
> fix: Revert: "fix: deep link analytics event triggered twice"

- src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
After closing the filter modal on the Artist Series screen, it automatically opens again after a few milliseconds.
Not toggling the state that handles the visibility of the filter modal and instead setting it to `false` or `true` directly fixed the issue.
| --- | --- |
|https://github.com/user-attachments/assets/78023f38-a898-46f0-abdd-92f10cbe32f0 |https://github.com/user-attachments/assets/906630d1-7f69-427e-978a-dfa2187df3c3 |
**Screenshots**
| | |
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2024-11-29 at 09 26 04](https://github.com/user-attachments/assets/133bce27-e1dc-47ca-b40c-2cb0499e8a22) | ![Simulator Screenshot - iPhone 16 - 2024-11-29 at 09 35 44](https://github.com/user-attachments/assets/825f85d6-74f7-485e-b4db-215f7e3453d8)| …
> fix: Allow closing the filter modal on the Artist Series screen

- src/app/utils/useDeepLinks.ts
Brings back the #11110 fix of double tracking
#nochangelog
> fix(REVERT): bring back double deeplink tracking

- src/app/Components/Artist/useFollowArtist.ts
This PR resolves [ONYX-1422] 
Do not switch tabs when navigating to follows from the follow confirmation toast. Not switching tabs to make sure the back button leads us back to the home view and not the the profile main page
Resolves [Notion Card](https://www.notion.so/artsy/When-clicking-on-View-Follows-on-the-toast-after-following-an-artist-from-the-New-Works-for-You--13ecab0764a08071b69ce302a91f9250?pvs=4)
https://github.com/user-attachments/assets/9a41eedd-08ad-4956-b891-3bd6f2f5cafe
- do not switch tabs when navigating to follows from the follow confirmation toast
-
-
-
</details>
[feature …
> fix(ONYX-1422): do not switch tabs when navigating to follows

- app.json
Prep for 8.58.0
Seems like the auto generated bump didn't work this time around, not sure if it is related with AppStore not approving the app yet.
#nochangelog
> chore: prep for 8.58.0

- src/app/Scenes/Collection/Components/CollectionArtworksFilter.tsx
- src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
- src/app/Scenes/Fair/Components/FairArtworks.tsx
- src/app/Scenes/Show/Components/ShowArtworks.tsx
- src/app/Scenes/Show/Show.tsx
Related fix: https://github.com/artsy/eigen/pull/11223
Filter panel toggle logic on Fair and Collection screens.
After closing the filter modal on the Artist Series screen, it automatically opens again after a few milliseconds.
Not toggling the state that handles the visibility of the filter modal and instead setting it to `false` or `true` directly fixed the issue.
- fix: Allow closing the artwork filter modal on the Fiar, Show and Collection screen - ole
-
-
-
</details>
> fix: Filter panel toggle logic on Fair, Show and Collection screens

- src/app/Navigation/Navigation.tsx
- src/app/store/GlobalStoreModel.ts
- src/app/system/navigation/ModalStack.tsx
This PR resolves [PHIRE-1382] 
Fixes deeplinks from killed state not reliably opening screens on iOS 17.
We have a check on the native side if the app is done bootstrapping and we delay requests until that is true. This check was previously just if the app was `hydrated` but really we also care if our navigation is ready. This just delays setting that to true until our nav is ready. 
<p>
https://github.com/user-attachments/assets/7ef9ccf8-02eb-46d3-9b93-eeaf3aec826f
</p>
</details> 
<p>
https://github.com/user-attachments/assets/2dd17061-c371-4a19-b4e4-25abca774b3b
</p>
</details> 
- This bug is another example of consequences of have 2 different ways of handling pushes across iOS and Android, if we just consolidated on …
> fix(deeplinks): fix deeplinks from killed state on iOS 17

- src/app/Components/Swipeable/Swipeable.tsx
- src/app/Components/Tasks/Task.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionTasks.tests.tsx
This PR resolves [EMI-2096] 
This PR implements the grouping of multiple tasks on the home view
It also adds the animation to the tasks when expanding
|---|---|
| <video src="https://github.com/user-attachments/assets/8d9c0e85-6b73-4a61-956e-6dd869cd0bb2" /> | <video src="https://github.com/user-attachments/assets/dee17feb-6f9c-41a0-bb39-c02e9de92927" /> |
- implement task grouping in the Home View - MrSltun
-
-
-
</details>
[EMI-2096]: …
> feat: Implement Home view tasks section list

- HACKS.md
- ios/Podfile.lock
- package.json
- patches/react-native-fast-image+8.6.3.patch
- yarn.lock
This PR resolves [PHIRE-1389] 
Fixes this [iOS sentry crash](https://artsynet.sentry.io/issues/4479226101/events/d98fd95bd4c74271a184596c901fac26/).
By looking for this issue found connections with two of our deps:
1. react-native-linear-gradient 
1. react-native-fast-image
The `react-native-linear-gradient` has already fixed the issue and released a version so bumping in order to fix the issue from there.
For `react-native-fast-image` we need to [patch it](https://github.com/muntius/react-native-fast-image/commit/fc2b8acd97f07989e312f5cbd61d2e541fda3611#diff-24ce0837ec34bb03c94a76bc62258a10d1c729e2e6b2f3ac706eab55f76dc0ecR87) temporarily until they release this with a new version.
Related issues:
https://github.com/react-native-linear-gradient/react-native-linear-gradient/issues/618 …
> fix: NSInternalInconsistencyException sentry crash iOS 17

- .secrets.baseline
- data/schema.graphql
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts
This PR resolves [PBRW-228] or [ONYX-1431] 
We cannot edit artworks that have submission in progress, but we came up with a compromise:
- display Edit button always
- when no submission or submission is compete navigate to the edit flow
- when submission is in progress display edit button greyed out and show popover on click
iOS
https://github.com/user-attachments/assets/03607a1c-abfe-469a-b5dd-f283ffdd658d
Android 
- adjust Edit button behavior on My Collection Artwork screen
-
-
-
</details>
[PBRW-228]: …
> chore(PBRW-228): my collection submitted swa works unable to be deleted

- src/app/Scenes/Inbox/Screens/Conversation.tsx
This PR resolves [https://artsy.slack.com/archives/C02BAQ5K7/p1733774877736639?thread_ts=1733472979.842869&cid=C02BAQ5K7] 
This PR fixes the header padding issues on the conversation screen.
#nochangelog
> fix: conversation screen padding

- src/app/Scenes/Map/GlobalMap.tsx
This PR resolves [PHIRE-1400] 
Fixes deprecation warnings for `onDidFinishRenderingMapFully` and `onRegionIsChanging` and replacing them with the new properties.
Also attempts to fix https://artsyproduct.atlassian.net/browse/PHIRE-1400 type error by making the code more defensive
-
- city guide warnings
-
-
</details>
[PHIRE-1400]: https://artsyproduct.atlassian.net/browse/PHIRE-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: city guide warnings

- ios/Artsy/App_Resources/Info.plist
- src/app/Components/ShareSheet/ShareSheet.tsx
This PR resolves [PBRW-227] 
Fixes sharing with telegram doesn't work.
In the share sheet we do support instagram stories. whatsapp, copy link and more options.
The more options opens the native share sheet from both android / iOS but most of the rest of messaging apps do not support sharing base64 files.
Removing that made telegram work.
The only difference now is that we share the link like so:
```
Femme dans l'atelier by Pablo Picasso on Artsy
https://staging.artsy.net/artwork/pablo-picasso-femme-dans-latelier-2?utm_content=artwork-share
```
Note that the image is still visible in the message from the metadata of the link so we should be okay with this solution.
- fix telegram sharing
-
-
-
</details> …
> fix: telegram sharing

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/Navigation/Utils/useBottomTabsBadges.tests.ts
- src/app/Navigation/Utils/useBottomTabsBadges.ts
This PR comes as follow up to https://github.com/artsy/eigen/pull/11175
The implementation I had before was injecting the bottom tabs inside the main tabs navigator - which didn't work. Here I am adjusting my approach to follow Brian's comment [here](https://artsy.slack.com/archives/C05EQL4R5N0/p1733775779925169?thread_ts=1733755732.268809&cid=C05EQL4R5N0).
https://github.com/user-attachments/assets/fcd419f8-46eb-49d8-9f8c-5999360e0160
- fix missing tabs notifications
-
-
-
</details>
> fix: missing tabs notifications

- src/app/Scenes/Artwork/Components/AboutArtist.tsx
This PR resolves [PBRW-127] and [PBRW-249] 
On web/mWeb when we display an artist's bio within the context of an artwork page, [we prefer the canonical version of the bio](https://github.com/artsy/force/pull/7748).
But it looks like we never made the equivalent change in the app, so this addresses that.
| Before | After (iOS) | After (Android) | Web (for comparison) |
|--------|--------|--------|--------|
| ![before](https://github.com/user-attachments/assets/822b55f2-ae02-46d5-8e31-05674240259d) | ![after](https://github.com/user-attachments/assets/b26e091b-576a-4116-a2ba-012828dc2c4d) | ![android](https://github.com/user-attachments/assets/869ca220-3f52-4511-90fa-e0a49a1c1100) | ![web](https://github.com/user-attachments/assets/1a8bf85e-0c99-4105-9e14-27a47e6296cd) | …
> fix: prefer canonical artist bio on artwork screen

- src/app/Components/NotFoundFailureView.tsx
- src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
This PR fixes this issue raised by @gkartalis.
The problem here is that when an error happens, the outer error boundary intercepts it. But since that error boundary is situated **above** the navigation (it's defined in Providers), it is not with the navigation container context **and** it gets a null value for the `internal_navigationRef`.
The solution here is to wrap every screen with an error boundary. 
https://github.com/user-attachments/assets/a654ba6a-5909-4bd5-8fc0-ef1912fa8e06
-
-
-
- wrap individual screens with error boundary - mounir
</details> …
> chore: wrap individual screens with error boundary

- src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
This PR adds the back button to auction results screen.
#nochangelog
> fix: add back button to auction results screen

- .husky/pre-commit
Our pre-commit hook runs on merge commits currently and this has annoyed me a couple times now because it will run against all modified files in the merge so will likely fail. So what happens is:
```
$ git merge origin/main
$ # fix conflicts and git add
$ git commit
$ # hook fails, commit is lost, conflict fixes are lost, back to square one
```
instead:
```
$ git commit
Merge in progress; skipping pre-commit hook.
``` 
-
-
-
- don't run pre-commit hook on merge commits - brian 
</details>
[docs]: …
> chore(tools): skip pre-commit hook during merge

- src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
- src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
- src/app/utils/getOrderStatus.ts
This PR resolves [https://artsyproduct.atlassian.net/browse/EMI-2203]
The change here introduces 'Counteroffer Received' which we decide based on 'buyerAction' that is received from MP. For now I bundled the counteroffer states for incomplete orders as those are requiring the same action from the collector. 
Ideally we should move this additional 'buyerState' calculation to the server or MP and not repeat the calculation here and in Force but we decided to not do this refactor for now before we discuss more cohesive overhaul of Order/Offer states.
I noticed we are not relying on this 'buyerAction' when displaying the state in Inbox. Instead we repeat the calculation inline and derive the 'kind' variable there. Believe that should be refactored to use 'buyerState' as well. But that is a …
> feat: Change state of orders with new offer from partner to Counteroffer Received

- src/app/store/GlobalStore.tsx
This PR resolves [this suggestion](https://github.com/artsy/metaphysics/pull/6297#pullrequestreview-2494966720)
Adds context for how the user-agent string is used in Metaphysics.
-
-
-
- Add a note re: user-agent string
</details>
> docs(home view): add note about user agent string

- src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
- src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
- src/app/Components/Artist/ArtistInsights/MarketStats.tsx
- src/app/Components/Bidding/Screens/BillingAddress.tsx
- src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx
- src/app/Components/Buttons/InfoButton.tests.tsx
- src/app/Components/Buttons/InfoButton.tsx
- src/app/Scenes/AuctionResult/AuctionResult.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
Modernize Info Button Bottom Sheets.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2024-12-13 at 15 15 49](https://github.com/user-attachments/assets/e88c4f5b-5050-4b97-9a32-8709d13d8874) |![Simulator Screenshot - iPhone 16 - 2024-12-13 at 15 15 38](https://github.com/user-attachments/assets/364b412c-5c38-4fa8-a810-f21d4a489517) |
- Modernize Info Button Bottom Sheets - ole
-
-
-
</details>
> feat: Modernize Info Button Bottom Sheets

- src/app/Navigation/Navigation.tsx
Invalidate the timeout for our little failed deeplink tracking that didn't get carried over to new nav.
-
-
-
- fix broken deeplink tracking - brian
</details>
> fix: invalidate deeplink timeout in new nav #trivial

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/store/config/features.ts
- src/app/utils/queryPrefetching.ts
This PR resolves [ONYX-1391] 
This adds prefetching capability to artwork grids. The solution uses the already existing [ElementInView](https://github.com/artsy/eigen/blob/main/src/app/utils/ElementInView.tsx) component.
The feature can be toggled with an [Echo feature flag](https://github.com/artsy/echo/pull/747). Just in case something goes wrong...
In the next iteration, I'll try to find a more universal solution similar to Force's [RouterLink](https://github.com/artsy/force/blob/main/src/System/Components/RouterLink.tsx#L37) component that has prefetching capability.
---
This PR uses the already implemented solution ElementInView](https://github.com/artsy/eigen/blob/main/src/app/utils/ElementInView.tsx), an alternative would have been to use the package …
> feat: Add prefetching capability to artwork grids

- src/app/Scenes/Onboarding/Onboarding.tsx
This PR fixes an applause bug in which the Forgot Password flow was not accessible when a social account was being linked to an existing Artsy account with the same email address.
The solution was to reintroduce the `ForgotPassword` screen that the `OnboardingSocialLink` screen was expecting to be present. This allows users to request a forgotten password email. However, it raises two (non-blocking) issues:
1. The Forgot Password step navigates users back to the start of the login flow instead of back to the `OnboardingSocialLink` screen. Users will need to attempt to connect their social account once more.
2. The auth flow now has two separate "Forgot Password?" forms, which could be confusing for future developers. I left some comments to mitigate this. …
> fix(APPLAUSE-6694868): forgot password link does not work in link account

- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
- src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosPhotoItem.tsx
This PR resolves [ONYX-1433] 
As discussed [here](https://artsy.slack.com/archives/C05EQL4R5N0/p1734432658233589) adding "Processing..." state to the images that do not yet have a path. Making the Continue CTA enabled in this scenario
https://github.com/user-attachments/assets/6fb04d02-471d-41a1-9e05-15b00508426a
- add processing state to the images that do not have image path, enable Continue CTA
-
-
-
</details>
[ONYX-1433]: https://artsyproduct.atlassian.net/browse/ONYX-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
> chore(ONYX-1433): add processing state to the images that do not have image path, enable Continue CTA

- src/app/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
This PR fixes the following bug: Tapping 'Explore Artist' fails to trigger navigation on Edit Alert page.
Link: https://platform.applause.com/company/13083/products/27879/community-issues/6696714
https://github.com/user-attachments/assets/f9512123-794e-4783-bed6-47c1cf91765d
#nochangelog
> fix: explore artists link on home tab

- src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tsx
- src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
This PR fixes an issue with the custom artist creation screen.
https://platform.applause.com/company/13083/products/27879/community-issues/6695253
https://github.com/user-attachments/assets/d18fa325-3225-42a9-a430-23d913aadcb7
#nochangelog
> fix: safe area insets on add custom artist

- src/app/Components/ArtsyWebView.tsx
- src/app/Navigation/routes.tsx
This PR allows us to hide the bottom tabs on the live auction webview.
For the sake of testing, I changed the iOS simulator to show a webview as well in order to test this. My android setup was broken but the logic here is the same.
https://github.com/user-attachments/assets/04cbd563-6ce9-4589-a934-042e34146610
#nochangelog
> fix: hide bottom tabs on live auction webview

- src/app/Components/Artist/ArtistShows/ArtistShow.tsx
- src/app/Components/ImageWithFallback/ImageWithFallback.tests.tsx
- src/app/Components/ImageWithFallback/ImageWithFallback.tsx
- src/app/Components/Lists/SavedItemRow.tsx
- src/app/Components/ShowCard.tsx
- src/app/Components/ThreeUpImageLayout.tsx
- src/app/Scenes/City/Components/TabFairItemRow/index.tsx
- src/app/Scenes/Feature/components/FeatureFeaturedLink.tsx
- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
- src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
- src/app/Scenes/Inbox/Components/Conversations/ItemShow.tsx
- src/app/Scenes/MyBids/Components/Lot.tsx
- src/app/Scenes/Partner/Components/PartnerShowRailItem.tsx
- src/app/Scenes/Search/components/SearchResultImage.tsx
- src/app/Scenes/Search/components/TrendingArtistCard.tsx
Fixes error causing auctions not to render as well as a few other images I missed in migration. 
This restores some behavior we had with the old opaqueImageView, that is if a null or undefined url is passed render a gray box as a fallback. It looks like this:
<details><summary>Screenshot</summary>
</details> 
- fix images not rendering when url is null - brian 
-
-
-
</details>
> fix: restore image fallbacks

- src/app/Components/ImageWithFallback/ImageWithFallback.tests.tsx
- src/app/Components/ImageWithFallback/ImageWithFallback.tsx
- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
GalleriesForYou was passing aspectRatio rather than height and we weren't handling in the fallback image, since it is only place just calculating height there and requiring width and height in the props to avoid in future. 
- galleries for you fix fallback height - brian, george
-
-
-
</details>
> fix: galleries for you fallback height

- .circleci/config.yml
- fastlane/utility_fastlane.rb
- scripts/deploys/notify-if-new-license-agreement
This PR resolves [PHIRE-1420] 
This broke when we started using 2fa, unfortunately it looks like this still does not support token based auth but I was unaware you can use a fastlane session in CI and it should last around 30 days, a little annoying but should be fairly easy to refresh.
-
-
-
- bring back license agreement reminder - brian 
</details>
[PHIRE-1420]: https://artsyproduct.atlassian.net/browse/PHIRE-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(tools): use session auth and reintroduce license check

- HACKS.md
- patches/react-native-reanimated+3.16.3.patch
- src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
This PR resolves [EMI-2217] 
This PR adds animation to each task on the homeview tasks list
>[!important]
> This PR adds a patch to react-native-reanimated to support adding a zIndex to the flatlist elements
After multiple approaches not to go with Reanimated (mainly due to it not supporting `CellRendererComponent` prop), there was no option but to use reanimated and patch the package to support `CellRendererComponent`, which allowed us to use the `itemLayoutAnimation` and animate the items in the flatlist
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/df1b040e-b6da-4a43-a676-ffa60c92f0e6" /> | <video src="https://github.com/user-attachments/assets/c9f1757a-0b63-4e83-80ae-21c575cd0c5c" /> |
| iOS | <video …
> feat(EMI-2217): Animate tasks on tap or clear 

- src/app/Scenes/HomeView/Components/HeroUnit.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
This PR resolves [ONYX-1442] 
Adjust the image on the HomeViewSectionCards component on iPad
**Before**
**After**
https://github.com/user-attachments/assets/8ad50416-0392-4466-8dc8-6735b33826f0
- adjust HomeViewSectionCard component for bigger screens
-
-
-
</details>
[ONYX-1442]: https://artsyproduct.atlassian.net/browse/ONYX-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-1442): adjust HomeViewSectionCard component for bigger screens

- .vscode/settings.json
This PR adds a VS Code configuration to disable [Biome](https://biomejs.dev/) to silence the errors that it is throwing after we added it to the Artsy Omakase.
- Disabled Biome
> chore: disable biome

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/system/navigation/navigate.ts
This PR comes as a fix to some data issues noticed by @daytavares in this dashboard
This happened because when migrating the navigation to the new infra, I didn't migrate the tabs tracking. For some reason, it's using a different tracking way.
-
-
-
- fix tracking tab screens tracking - mounir
</details>
> fix: tab views tracking

- src/app/Components/Select/Components/SelectModal.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkCondition.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkPurchaseHistory.tests.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkShippingLocation.tests.tsx
This PR resolves [This notion card](https://www.notion.so/artsy/Android-Keyboard-aware-view-doesn-t-work-properly-on-modals-170cab0764a08048b6ffd281c95d00b9?pvs=4)
Makes Modals full screen by replacing `<FancyModal />` with `<Modal />` from `react-native`.
This solves the issue in android that we had with the keyboard avoiding view pushing the content outside of the screen that @MrSltun found during Sprintly Mobile QA Changes.  
|Before|After|
|---|---|
|![androidcg](https://github.com/user-attachments/assets/728adf31-aa49-4cc7-b968-86161f551484)|![AndroidcontactGalleryAfter](https://github.com/user-attachments/assets/84c9bd53-86e6-45c8-90c1-0ec90ffb809f)|
|![androidCountry](https://github.com/user-attachments/assets/0e9baf14-552a-4453-89e5-722ff569e5b5)|![AndroidcountryAfter](https://gith …
> fix: modal issues on android

- src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx
- src/app/Scenes/HomeView/Components/HomeHeader.tsx
- src/app/Scenes/Search/RecentSearches.tsx
- src/app/Scenes/Search/Search.tsx
- src/app/Scenes/Search/SearchModel.tests.tsx
- src/app/Scenes/Search/SearchModel.tsx
- src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
- src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-1367] 
Clean AREnableNewSearchModal ff related code.
-
-
-
-
</details>
[ONYX-1367]: https://artsyproduct.atlassian.net/browse/ONYX-1367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Clean AREnableNewSearchModal ff related code

- ios/Artsy/App/ARAppDelegate.mm
- ios/Artsy/App/ARAppNotificationsDelegate.h
- ios/Artsy/App/ARAppNotificationsDelegate.m
- ios/ArtsyTests/App_Tests/ARAppNotificationsDelegateTests.m
This PR resolves [EMI-2237] 
This PR updates the native iOS in-app notification view to the default notification style when the app is in the foreground
|---|---|
| <video src="https://github.com/user-attachments/assets/ec30e635-10d0-4fc0-b829-cc6c875ce748" /> | <video src="https://github.com/user-attachments/assets/e2e34107-3e1b-49cc-873c-9b90f037b260" /> | 
-
- Update the iOS notification style when the app is in the foreground
-
-
</details>
[EMI-2237]: …
> feat(EMI-2237): Update iOS in-app push notification style

- .circleci/config.yml
WIP - trying to figure out whats wrong with build-test-js job and specifically with `scripts/ci/generate-manifest.js .manifests/app_build '^\./manifests/native_code' '^dist/'` generation.
As a first step I am adding it on the initial generation of manifests to see how it will behave
#nochangelog
> build(ci): build-test-js fix

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/HomeView/Components/ActivityRailItem.tsx
- src/app/system/navigation/RouterLink.tests.tsx
- src/app/system/navigation/RouterLink.tsx
Resolves https://github.com/artsy/eigen/pull/11293#discussion_r1912804571
Rename routerProps to navigationProps in RouterLink.
-
-
-
-
</details>
> chore: Rename routerProps to navigationProps in RouterLink

- src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
Resolves https://github.com/artsy/eigen/pull/11293/files#r1913175557 
Avoid calling navigate twice from the Artwork rail.
-
-
-
-
</details>
> fix: Avoid calling navigate twice from Artwork rail

- src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
- src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
- src/app/Components/Bidding/Screens/SelectMaxBid.tests.tsx
This PR comes from investigating https://artsyproduct.atlassian.net/browse/EMI-2224. The issue described there is not exactly the same but in a process discovered the bug where user is required to reenter the credit card after their bid has been outbid right away
Following the pattern currently present in Force and reading the bidding info from sale on sale_artwork. Seems like there authenticatedUser is automatically applied to the data returns properly.
| Popover | Message |
| --- | --- |
| ![bidding_old](https://github.com/user-attachments/assets/918e4707-1800-425c-aaeb-bda6ec5499b8)  |  ![bidding](https://github.com/user-attachments/assets/283643ee-a912-48b9-aa18-8a04c5428434) |
- [ x ] I have tested my changes on **iOS** and **Android**.
- [ x ] I hid my changes behind a **[feature …
> chore: use bidder stored on sale for determining if credit card info or creating bidder info is required.

- src/app/Components/FancySwiper/FancySwiper.tsx
- src/app/Components/FancySwiper/FancySwiperCard.tsx
- src/app/Components/FancySwiper/FancySwiperIcons.tsx
- src/app/Components/FancySwiper/__tests__/FancySwiper.tests.tsx
- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
This PR updates the FancySwiper component to make right swiping optional since Infinite Discovery will only allow users to swipe in one direction. (I also added the option to make left swiping optional for the sake of symmetry.)
https://github.com/user-attachments/assets/b809647b-7e5b-4090-820e-86a63c691c08
-
-
-
- Allowed users of the FancySwiper to prevent right swipes
</details>
> feat(DIA-1015): allow FancySwipe to prevent left and/or right swiping

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
Resolves https://www.notion.so/artsy/Occasionally-the-long-press-results-in-a-navigation-to-the-artwork-AND-the-modal-menu-176cab0764a080bd9f63c64253e8c8da?pvs=4
This PR prevents `onPress` from being triggered on the artwork rail and grid when the long-press context menu opens. 
Occasionally, when opening the long-press context menu with a brief press, navigation to the artwork screen occurred simultaneously with the context menu opening. 
The issue and the fix are described in https://github.com/mpiannucci/react-native-context-menu-view/issues/60.
**Before:**
https://github.com/user-attachments/assets/8b3c824d-036b-41eb-b927-a9b2fcb51916
**After:**
https://github.com/user-attachments/assets/3b600124-16c0-463b-af55-ffc455e2a841
- Prevent …
> fix: Prevent `onPress` from being called when opening long-press context menu opens

- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ShowCard.tsx
- src/app/Navigation/routes.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollection.tsx
- src/app/Scenes/Artist/Artist.tsx
- src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
- src/app/Scenes/CollectionsByCategory/CollectionRail.tsx
- src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
- src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
- src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
- src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx
- src/app/Scenes/HomeView/Components/ArtistRails/ArtistRail.tsx
- src/app/Scenes/HomeView/Components/ArtistRails/RecommendedArtistsRail.tsx
- src/app/Scenes/HomeView/Components/ArtworkModuleRail.tsx
- src/app/Scenes/HomeView/Components/ArtworkRecommendationsRail.tsx
- src/app/Scenes/HomeView/Components/NewWorksForYouRail.tsx
- src/app/Scenes/HomeView/Components/RecommendedAuctionLotsRail.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
- src/app/Scenes/Sale/Components/BuyNowArtworksRail.tsx
- src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tsx
- src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
- src/app/Scenes/Show/Show.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
- src/app/system/navigation/RouterLink.tests.tsx
- src/app/system/navigation/RouterLink.tsx
- src/app/utils/loggers.ts
- src/app/utils/queryPrefetching.ts
This PR resolves [ONYX-1461] 
This PR replaces `Touchable` with `Routerlink` for prefetching on artwork and artist rails, as well as some additional rails on the home screen. It also makes some changes to the RouterLink component and to `routes.ts`. All updates are explained in the comments.
- Replace Touchable with Routerlink for prefetching on artwork and artist rails, as well as some additional rails on the home screen - ole
-
-
-
</details>
[ONYX-1461]: …
> feat: Replace Touchable with Routerlink for prefetching on artwork and artist rails

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
Avoid double prefetching on artwork grid
-
-
-
-
</details>
> fix: Avoid double prefetching on artwork grid

- src/app/Components/FancySwiper/__tests__/FancySwiper.tests.tsx
- src/app/Components/FancySwiper/__tests__/utils.ts
- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
- src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscovery.tests.tsx
This PR updates Infinite Discovery to use the `discoverArtwork` query (with refetch) to create an infinite scroll.
https://github.com/user-attachments/assets/442ac246-456d-4777-8a75-f58b3d015fa1
Some outstanding issues to be followed-up on:
1. I am showing a spinner when the next batch starts to load, but ideally the refetch won't trigger a redraw.
2. I am not persisting the artworks that a user has seen, so users will see the same artworks across multiple sessions.
-
-
-
- Infinite Discovery updated to refetch batches of 5 artworks
</details> …
> feat(DIA-1062): refetch infinite discovery

- src/app/system/relay/middlewares/rateLimitMiddleware.ts
- src/app/utils/queryPrefetching.ts
In https://github.com/artsy/eigen/pull/11293, I have increased the rate limit for prefetching, but I am now seeing error messages because it is not aligned with the rate limit middleware limit.
This PR increases the limit of the middleware slightly and decreases the prefetching limit to avoid this situation. 
This fix is for the next release and I don't want to adjust the rate limiting middleware (https://github.com/artsy/eigen/pull/3408) too much without extensive testing and understanding why the limit is so small.
-
-
-
-
</details>
[docs]: …
> fix: Align rate limit middleware and prefetching rate limiter

- ios/Artsy/App/ARAppNotificationsDelegate.m
Fixes an issue where when the app was in foreground and received a notification with an image, when the user tapped on it we weren't getting properly redirected to the correct page in the app.
Fixes these two issues:
- [Braze-Notification-opens-Deeplink-if-the-user-is-on-the-Foreground](https://www.notion.so/artsy/Braze-Notification-opens-Deeplink-if-the-user-is-on-the-App-17bcab0764a0805989c5c87648218a89?pvs=4)
- [Users-don-t-receive-push-notifications-when-the-app-is-in-the-foreground](https://www.notion.so/artsy/Users-don-t-receive-push-notifications-when-the-app-is-in-the-foreground-17bcab0764a080feafc0da3c5d167dbf?pvs=4)
-
- foreground notifications linking (/w images)
-
-
</details> …
> fix(iOS): foreground notifications linking (/w images)

- ios/Artsy.xcodeproj/project.pbxproj
- ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+LargeView.swift
- ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+MediumView.swift
- ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+SmallView.swift
- ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+Widget.swift
- ios/ArtsyWidget/FullBleed/FullBleed+View.swift
- ios/ArtsyWidget/FullBleed/FullBleed+Widget.swift
- ios/ArtsyWidget/LatestArticles/LatestArticles+LargeView.swift
- ios/ArtsyWidget/LatestArticles/LatestArticles+MediumView.swift
- ios/ArtsyWidget/LatestArticles/LatestArticles+SmallView.swift
- ios/ArtsyWidget/LatestArticles/LatestArticles+Widget.swift
This PR fixes a number of rough edges with our iOS widget.
<details><summary>screenshots</summary>
</details> 
This configuration turns off an annoying thing where Apple is attempting to limit the developer to a "safe" content area. I guess I see what they are going for here but for us it's all wrong. We want our widget area to extend all the way to the edge and this configuration restores that layout.
This configuration is used by iOS to decide how to render the widget in various scenarios where a background does not make sense. Think the Lock Screen - those widgets should not have a background. In our case we don't support the Lock Screen and further we do not want our background to ever be removed. Setting this to false ensures we always render correctly.
This view modifier is only …
> fix: Modernize iOS widget config

- src/app/Components/Buttons/InfoButton.tsx
This PR resolves [PBRW-359] 
This PR fixes the broken presentation after pressing on the tooltip icon the saves tab. I don't have a concrete explanation about why this is breaking. However my assumption is that the bottomsheet modal doesn't like when different heights are being specified because it breaks it's built in height calculation
https://github.com/user-attachments/assets/8e8a3697-f5c1-497a-bddf-62cf47be81a0
- fix broken saved and follows button tooltip animation - mounir
-
-
-
</details>
[PBRW-359]: …
> fix(PBRW-359): broken presentation on tooltip icon

- src/app/Components/Buttons/InfoButton.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
This PR resolves [PBRW-338] 
This PR fixes an issue happening at the create alert modal info button.
The problem here is that the bottom sheet modal component from rn-bottom-sheet couldn't be shown on top of the modal from react-native on Android. In iOS it's not an issue because we are anyway using a custom implementation of the modal (`FullScreenOverlay`). Here, I am updating the implementation on Android to use the modal from RN in case we are using the info button inside a modal.
https://github.com/user-attachments/assets/dd958aa9-9b13-49b0-b89c-f896d67f682e
- fix info button inside modals - mounir
-
-
-
</details> …
> fix(PBRW-338): broken info button inside modals

- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
- src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscovery.tests.tsx
- src/app/store/GlobalStoreModel.ts
- src/app/store/InfiniteDiscoveryModel.ts
- src/app/store/__tests__/migration.tests.ts
- src/app/store/migration.ts
This PR persists a list of artworks that have been received by Infinite Discovery so that those same artworks don't appear in Infinite Discovery again.
-
-
-
- Persist a list of artworks that have been displayed in Infinite Discovery
</details>
> feat(DIA-1062): persist discovered artwork IDs sent to infinite discovery endpoint

- src/app/Scenes/Artwork/Components/ShippingAndTaxes.tests.tsx
- src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx
#hackathon related PR.
This adds a 'pickup available line' to shipping section of artwork screen and also adds a minor adjustment in spacing in preparation of change that will be done in MP.
Current view without MP changes:
PickupAvailable:
Pickup not available:
- pickup available added on artwork screen
-
-
-
</details>
> chore: add pickup available line to shipping infor on artwork

- src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/useSubmissionContext.ts
This PR resolves [PBRW-344] 
This PR adds a listener to the hardware back button (Android) to ensure proper navigation to the previous step in the Sell flow.
Without this fix, the bottom navigation of the flow did not update correctly.
| --- | --- |
|![Screenshot_1737968072](https://github.com/user-attachments/assets/091e3e9f-ab92-411b-83d4-67b837f79c4d) |![Screenshot_1737968033](https://github.com/user-attachments/assets/f42d9eeb-ccfc-42a3-9ec6-14b51914b78f) |
-
-
-
-
</details> …
> fix: Sell flow navigation on hardware back button press for Android

- ios/Podfile.lock
- src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
>[!IMPORTANT]
> This change is part of [Migrating push to Pulse](https://www.notion.so/artsy/Consolidate-push-notification-responsibilities-in-Pulse-17ecab0764a080a3864ee0bc64268dcf?pvs=4) hackathon project
This PR is a prerequisite to artsy/gravity#18498 🔒 and artsy/gravity#18503 🔒 to clean up gravity and move all push notification login to Pulse
This PR removes `New Viewing Rooms for You` and `New Shows for You` notification permissions since they haven't been used for quite some time
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/86a2e4ae-6d13-478a-9e99-1b05da9c2a75) | ![image](https://github.com/user-attachments/assets/d5806416-7ebe-4e43-83bd-149a58a362d9) |
| iOS | …
> fix(hack-15): Remove unused notification permissions

- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
- src/app/Components/ContextMenu/__tests__/ContextMenuArtwork.tests.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-1474] 
This implements the Artwork card long-press context menu for Android using a bottom sheet.
* Feature Flag: `AREnableArtworkCardContextMenuAndroid`
**Android**
|![Screenshot_1737974340](https://github.com/user-attachments/assets/ac13a78f-7f02-432c-84ba-90d2e4f7132f) | ![Screenshot_1737974335](https://github.com/user-attachments/assets/d91c0a8e-d32f-4f26-ba2a-f4e7cbe62d72) |
| --- | --- |
| | |
**iOS**
| ![Simulator Screenshot - iPhone SE (3rd generation) - 2025-01-27 at 11 30 04](https://github.com/user-attachments/assets/191e44cf-bf2f-485d-a1fc-49439d33753e) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2025-01-27 at 11 24 37](https://github.com/user-attachments/assets/3e8c83c1-b912-47fa-b965-beeb3581b7f3) |
| --- | --- |
| | | …
> feat: Long-press artwork context menu for Android

- src/app/Scenes/MyBids/MyBids.tests.tsx
- src/app/Scenes/MyBids/MyBids.tsx
- src/app/utils/useAppState.tsx
This PR resolves [EMI-2187] 
This PR implements a `useInterval` in the Bids screen to update it every 10 seconds
- Refresh MyBids screen every 10 secs
-
-
-
</details>
[EMI-2187]: https://artsyproduct.atlassian.net/browse/EMI-2187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(EMI-2187): Refresh Bids screen every 10 secs

- src/app/Components/FancySwiper/FancySwiper.tsx
- src/app/Components/FancySwiper/FancySwiperCard.tsx
- src/app/Components/FancySwiper/__tests__/FancySwiper.tests.tsx
- src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
- src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscovery.tests.tsx
- src/app/store/InfiniteDiscoveryModel.ts
This PR refactors FancySwiper to receive an array of React components instead of JSX. I wanted to make this change because I will want to reuse the `useSaveArtwork` hook to allow users to save artworks, and I can't use that hook for each artwork card unless it is inside of a component.
https://github.com/user-attachments/assets/fa9e22e2-9e82-4093-ab13-df9c45168246
https://github.com/user-attachments/assets/5d4b37f1-0dd5-43fb-80f8-b0fa5408ae58
-
-
-
- Refactored FancySwiper to receive an array of components instead of JSX
</details>
[docs]: …
> refactor(DIA-1019): pass a component to FancySwiperCard instead of JSX

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
- src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/Onboarding/Onboarding.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuiz.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingWelcome.tsx
- src/app/store/AuthModel.ts
- src/app/store/GlobalStoreModel.ts
- src/app/store/OnboardingModel.ts
- src/app/store/__tests__/AuthModel.tests.ts
- src/app/store/__tests__/migration.tests.ts
- src/app/store/migration.ts
We noticed with @brainbicycle while pairing to fix some other unrelated navigation issues that when calling `GlobalStore.actions.auth.setState({ onboardingState: "complete" })` on some parts of the codebase we managed to reproduce reliably the `Proxy handler is null` error (stacktrace [here](https://artsynet.sentry.io/issues/6207698490/events/fb6fc7b4ccc9480fbd44c0b07d3fdf62/)).
What we noticed in more detail was that the `auth` property in `GlobalStore` was replaced with the error resulting in the store not having access to the rest of the variables there that are needed for auth.
This is an attempt to decouple the onboardingStates from the auth in order to not affect the auth variables with anything onboarding related since these are used for navigating users after …
> refactor(GlobalStore): move onboardingState to onboardingModel

- src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
- src/app/store/AuthModel.ts
- src/app/store/OnboardingModel.ts
This PR fixes an issue with the onboarding always showing up when the user signs in
This is a follow-up PR after #11458 
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/0b687eef-7ae4-4672-a1c4-a6a5692fb7eb" /> | <video src="https://github.com/user-attachments/assets/80685d0c-0516-4794-8c9b-904184b8ff2c" /> |
| iOS | <video src="https://github.com/user-attachments/assets/9ff16246-a638-46fc-a645-5958b56368f3" /> | <video src="https://github.com/user-attachments/assets/c4a266e7-cea4-438e-a16d-5788a4a692d1" /> |
- hide onboarding when users sign in
-
-
-
</details> …
> fix: Hides onboarding flow after sign in

- src/app/store/GlobalStoreModel.ts
- src/app/system/devTools/DevMenu/Components/DevTools.tsx
As users browse artworks in Infinite Discovery, we compile a list of artworks that the user has received from the backend, and we store this on the device, and send it with each request for more batches of artworks so that we don't see the same artwork twice.
However, it is possible that a user sees all of the artworks that are available, which results in a blank Infinite Discovery screen. That happens a lot during development while working on the card swiping action and animation, and it is frustrating to have to reinstall the app to get an empty list of discovered artworks.
This PR adds a tool to the dev menu to clear that list of discovered artworks so we can keep working in the same app install.
-
-
-
- Added a dev tool to allow users to …
> feat: add a dev tool to forget about disovered artworks

- src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx
- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
This PR resolves [PBRW-400] 
This PR fixes two bugs:
1. When opening an artwork from the artwork rail, the long-press context menu would also open after navigating back.
2. After opening and closing a bottom sheet, the back button might stop working because the back button handler from the bottom sheet does not properly bubble up the event.
I resolved the first issues by setting `delayLongPress` to prevent `onLongPress` from being triggered when opening the artwork. And the second one by fixing a condition from the bottom sheets back button handler.
-
-
-
-
</details> …
> fix: Android long-press back button fix

- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
This PR resolves [PBRW-410] 
Fixes a potential by optional chaining for safer access to notificationPreferences.
Previously some users were getting this error:
-
-
-
- optional chaining for safer access to notificationPreferences
</details>
[PBRW-410]: https://artsyproduct.atlassian.net/browse/PBRW-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: optional chaining for safer access to notificationPreferences

- src/app/Components/ArtsyWebView.tsx
- src/app/store/NativeModel.ts
- src/app/utils/PushNotification.ts
This PR resolves [PBRW-397] 
This PR fixes the issue where push notifications don't navigate the users when a webview modal is present
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/a875bad3-7708-4767-b6ae-1dbbb1b18796" /> | <video src="https://github.com/user-attachments/assets/df5bc43f-ef2f-4229-9cd5-aae53b230125" /> |
| iOS | <video src="https://github.com/user-attachments/assets/f3eee367-b4f4-4a4d-adcb-51243c3c64a0" /> | <video src="https://github.com/user-attachments/assets/d14367d8-de83-4495-8462-adb235238bf3" /> |
- navigate the user on foreground push when a webview modal is visible
-
-
-
</details>
[app …
> fix(PBRW-397): Dismiss modal on foreground Push Notification tap

- LICENSE
- package.json
- src/app/Components/ArtsyWebView.tsx
This PR resolves [PBRW-412] 
This is a workaround for the purchase button disappearing after tapping the artsy logo in the purchase flow.
This is happening because this logo redirects to https://www.artsy.net which maps to the Home module, so under the modal navigation happens and this breaks the display of the artwork page. This just prevents navigation in this case.
This is not a great solution I think it would be better to **remove the artsy logo** or make tapping a no-op when visiting the checkout pages from Eigen in **force**.
<p>
https://github.com/user-attachments/assets/61573616-df21-43c9-a357-7aab6fb341a3
</p>
</details> 
<p>
https://github.com/user-attachments/assets/697410e6-1502-4b65-af77-78625d9cb3d0
</p> …
> fix: purchase button disappears

- src/app/system/navigation/RouterLink.tsx
This replaces the Touchable component used in RouterLink. I noticed that on some surfaces, the `Touchable` from palette mobile does not highlight on touch. Palette mobile uses `TouchableHighlight`, which does not seem to work correctly.
In this PR, I simply replace it with `TouchableOpacity`, which seems to work as expected.
This is a "quick" fix, and I'll start a conversation about making the change in palette-mobile.
- Replace Touchable component in RouterLink - ole
-
-
-
</details>
> fix: Replace Touchable component in RouterLink

- src/app/Scenes/Activity/ActivityList.tsx
- src/app/Scenes/Activity/utils/__tests__/shouldDisplayNotification.tests.ts
- src/app/Scenes/Activity/utils/shouldDisplayNotification.ts
- src/app/Scenes/HomeView/Components/ActivityRail.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
This PR resolves [PBRW-392] 
I’ve looked into the code, and it could be related to [this line](https://github.com/artsy/eigen/blob/f78303a22940f20d1a97cd9343537311617e90ad/src/app/Scenes/HomeView/Components/ActivityRailItem.tsx#L45), which prevents rendering activity items with the type name CollectorProfileUpdatePromptNotificationItem man shrugging Activities by this type get filtered out in the rail item component instead of the rail. This could be the reason why the rail is still rendering.
- Correctly filter CollectorProfileUpdatePromptNotificationItem in Activity rail. - ole
-
-
-
</details> …
> fix: Correctly filter CollectorProfileUpdatePromptNotificationItem in Activity rail

- src/app/Components/FancySwiper/FancySwiper.tsx
- src/app/Components/FancySwiper/FancySwiperCard.tsx
This PR adds a fade-in effect for the second card in a FancySwiper so that it becomes more visible and larger as the top card is swiped away.
|----|-------|
| https://github.com/user-attachments/assets/a1279a9f-ed54-40f4-ba87-689b5bf6d712 | [android_webm.webm](https://github.com/user-attachments/assets/db7e3261-673c-4944-bf00-b47326f55a91) |
-
-
- Added a fade-in effect for the second card in a FancySwiper
-
</details>
> feat(DIA-1107): fade the second card in as the top card is swiped

- src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
- src/app/Components/BottomSheet/AutoHeightBottomSheet.tsx
- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
- src/app/Components/ContextMenu/__tests__/ContextMenuArtwork.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
Close Info bottom sheet on tapping Close button.
| --- | --- |
|https://github.com/user-attachments/assets/98cef454-4e4a-4220-96e7-46fabed6f19e|https://github.com/user-attachments/assets/87477406-f228-46cd-a870-c723bdadb32f |
- fix: Correctly close Info bottom sheet on tapping Close button - ole
-
-
-
</details>
> fix: Close Info bottom sheet on tapping Close button

- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Fixes the index being wrong because using a derived value instead of the state artworks.
iOS demo
https://github.com/user-attachments/assets/2ea38299-9f72-45c3-a609-990d1ac5cb03
- fix: infinite discovery swiping more than 5 cards bug
-
-
-
</details>
> fix(InfiniteDiscovery): adjust the bottomSheet to use the state artworks

- src/app/Components/ArticleCard.tsx
- src/app/Navigation/routes.tsx
- src/app/Scenes/Article/ArticleScreen.tsx
- src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
- src/app/Scenes/HomeView/Components/ActivityRailItem.tsx
- src/app/Scenes/HomeView/Components/NewWorksForYouRail.tsx
Resolves [ONYX-1496](https://artsyproduct.atlassian.net/browse/ONYX-1496)
**Home view prefetching part III:**
Implements prefetching for the home view's Article rail and the Activity indicator.
- Implements prefetching for the home view's Article rail and the Activity indicator - ole
-
-
-
</details>
[ONYX-1496]: https://artsyproduct.atlassian.net/browse/ONYX-1496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Home view prefetching part III

- src/app/Components/ArtistListItem.tsx
- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
This PR makes some changes to the artwork card in Infinite Discovery to more closely match the design specs.
- Make the artist avatar smaller
- Exclude artist nationality, birthdate, etc.
- Add horizontal margins to header and footer
- Make the save artwork button larger
- Make the artwork card a consistent height
It adds a new `includeTombstone` field to make the nationality, birthdate, and deathdate optional in the ArtistListItem component.
|-------|-------|
| ![Simulator Screenshot - iPhone 16 Plus - 2025-02-07 at 12 59 10](https://github.com/user-attachments/assets/208c5336-5cf1-4d51-9f4b-0c1f2d04401d) | ![Simulator Screenshot - iPhone 16 Plus - 2025-02-07 at 13 00 17](https://github.com/user-attachments/assets/54ddfc91-efc9-4312-ae61-4182b058b896) | …
> fix(DIA-1068): make the artwork card match the design specs more closely

- src/app/Components/FancySwiper/FancySwiper.tsx
- src/app/Components/FancySwiper/__tests__/FancySwiper.tests.tsx
- src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
This PR fixes a bug in Infinite Discovery where, after the first 3 swipes, the 4th card would be on top for an instant before being replaced by another card. When trying to swipe this new card that appeared, users would not be able to swipe it, so the Infinite Discovery would come to a halt. It looked like this:
https://github.com/user-attachments/assets/01942f3d-653c-43ad-97e8-e5614d8be60e
I was struggling to debug this, so I decided to pass each card's artwork ID to FancySwiper so that I could print out the ID of each artwork card in the stack as I was swiping. Lo and behold, the bug stopped happening.
The only real change that I made was to use the artwork IDs for each artwork card's `key` field, so that seems to have fixed the buggy behavior. (@araujobarret and @MounirDhahri, I am …
> fix(DIA-1068): prevent artwork cards from freezing

- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
Resolves https://artsy.slack.com/archives/C02BC3HEJ/p1739175371909169 
This PR disables the iOS Artwork context menu in the test environment because enabling the Echo flag caused many unrelated tests to fail.
-
-
-
-
</details>
> chore: Disable Artwork context menu in test environment

- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingLongPressContextMenu.tsx
Resolves https://artsy.slack.com/archives/C05EQL4R5N0/p1739185851472429
Do not show the Artwork Long Press quick tip on the first app launch.
- Do not show Long Press quick tip on first app launch (min second session) - ole
-
-
-
</details>
> feat: Do not show Long Press quick tip on first app launch

- src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
This PR resolves [PBRW-487] 
This PR fixes the issue with double navigation to the artwork screen that can be found in Similar Artworks screen, Alert Confirmation screen and Alert Artworks screen
I believe this issue comes from the `RouterLink` component wrapping the Artwork component which helps with the artwork navigation, as well as adding a separate `onPress` prop to the generic artwork grid, causing the two navigation calls to run
In this PR, I just removed the onPress that calls for a `navigate` to fix the issue, but I'm open to any other suggestions
|---|---|---|
| Similar Artworks | <video src="https://github.com/user-attachments/assets/48cc5a5e-167f-4796-a9dd-767d8d75aaae" /> | <video src="https://github.com/user-attachments/assets/2c720bf7-243e-4fad-9858-8931 …
> fix(PBRW-487): Fix double artwork navigation issues

- src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionNavigationPills.tests.tsx
This PR resolves [ONYX-1464] 
Consumes the [new](https://github.com/artsy/metaphysics/pull/6423) `icon` field of the `NavigationPill` MP type in order to render icons in the Quick Links section of the home view.
Unsupported or missing icons are simply not rendered.
| <img height=400 alt=iOS src="https://github.com/user-attachments/assets/960dc1d9-90dd-4268-ace5-b921f8f6bf64" /> |<img height=400 alt=iOS src="https://github.com/user-attachments/assets/56e6f9f3-4975-4d7b-bff7-1739448a09de" /> |
- Display icons with home view navigation pills
-
-
-
</details> …
> feat(home view): add icons to navigation pills

- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
- src/app/Scenes/InfiniteDiscovery/mutations/useCreateUserSeenArtwork.ts
We now have a backend to track seen artworks for the Infinite Discovery project. Currently, `discoverArtworks` does not take BE seen artworks into account (though there is an argument in the query that allows this, and merging [this PR](https://github.com/artsy/metaphysics/pull/6454) will make it possible to enable via a feature flag).
In this PR, I add functionality to store seen artworks on the BE only. After it’s merged, whenever we feel that our BE is ready for internal tracking, we can simply enable the feature flag on the Metaphysics side.
-
-
-
- infinite disco - persist seen artworks - @nickskalkin 
</details> …
> feat: infinite disco — send seen artworks to BE

- src/app/Scenes/HomeView/HomeView.tsx
This PR resolves [PBRW-518] 
This PR fixes the issue with the Android status bar being invisible after login
|---|---|
| <video src="https://github.com/user-attachments/assets/eed6905c-e2db-451f-97fc-42ee929fdc19" /> | <video src="https://github.com/user-attachments/assets/bd5c22c1-44d4-4688-81f8-24ee6d039060" /> |
-
-
- Bring back Android status bar
-
</details>
[PBRW-518]: https://artsyproduct.atlassian.net/browse/PBRW-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
> fix(PBRW-518): Bring back Android status bar

- src/app/Scenes/MyBids/ActiveLotStanding.tests.tsx
- src/app/Scenes/MyBids/ClosedLotStanding.tests.tsx
- src/app/Scenes/MyBids/Components/ActiveLotStanding.tsx
- src/app/Scenes/MyBids/Components/BiddingStatuses.tsx
- src/app/Scenes/MyBids/Components/ClosedLotStanding.tsx
- src/app/Scenes/MyBids/Components/LotStatusListItem.tsx
- src/app/Scenes/Sale/Components/SaleActiveBidItem.tsx
- src/app/Scenes/Sale/Components/SaleActiveBids.tsx
- src/app/Scenes/Sale/SaleActiveBidItem.tests.tsx
Solves  [[EMI-2234](https://artsyproduct.atlassian.net/browse/EMI-2234)] 
We do not have a good way currently to get the timely status of bids in the auction that is in live bidding state. So instead of displaying wrong outbid/winning info the decision is to display Bidding live now note instead on Auction page. Also hide bidding info in this case in myBids screen.
Auction page:
|Android|iOs|
|---|---|
|<img width="293" alt="Screenshot 2025-02-27 at 1 21 10 PM" src="https://github.com/user-attachments/assets/e9098e28-d653-40b0-91cb-4d6eed1e4e10" />|<img width="399" alt="Screenshot 2025-02-27 at 1 17 57 PM" src="https://github.com/user-attachments/assets/c5a101e6-0a07-4829-a29b-0cd0c2c42125" />|
myBids page:
|Android|iOs|
|---|---|
|<img width="294" alt="Screenshot 2025-02-27 at 1 55 …
> feat: hide Bidding info for live auction in progress as it's not reliable.

- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
- src/app/store/GlobalStoreModel.ts
- src/app/store/InfiniteDiscoveryModel.ts
- src/app/store/__tests__/migration.tests.ts
- src/app/store/migration.ts
- src/app/system/devTools/DevMenu/Components/DevTools.tsx
Stop using local storage for `discoveredArtworkIds`—backend will do it instead.
#nochangelog
</details>
> refactor: infinite discovery - rely on backed to exclude seen artworks (remove discoveredArtworkIds)

- src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tsx
This PR resolves [PBRW-510] 
Video of the behavior after the fix:
<video src="https://github.com/user-attachments/assets/65b5944e-2467-4084-beb9-64c06a9fc8e2" width="500" />
- fix unresponsive artwork screen after make offer 
-
-
-
</details>
[PBRW-510]: https://artsyproduct.atlassian.net/browse/PBRW-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(PBRW-510): Fix issue with the app freezing after Make Offer flow

- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
This PR resolves [DIA-1165] 
Adds additional copy to the save widget for infinite discovery.
- When I encounter an unsaved artwork, I can see the word “Save” next to the heart icon
- While I’m saving that artwork, the font color of “Save” becomes grey
- When I’ve saved that artwork, I can see the word “Saved” next to the heart icon
- When I encounter a saved artwork, I can see the word “Saved” next to the heart icon
- While I’m un-saving that artwork, the font color of “Saved” becomes grey
- When I’ve un-saved that artwork, I can see the word “Save” next to the heart icon
https://github.com/user-attachments/assets/4cb7974e-5647-4b0b-bb0e-c52d0c4c066d
-
-
-
- Adds additional copy to the save widget for infinite discovery.
</details>
Need help …
> feat(DIA-1165): Add an optional “Save” copy to the save widget in Eigen.

- ios/Artsy/App/ARAppNotificationsDelegate.m
This reverts commit e22305e0bec299ebd5de9bdd1102696f6a4bafea.
Reverts #11416
-
-
-
-
</details>
> chore: revert foreground notifications linking

- ios/Artsy/App/ARAppNotificationsDelegate.m
This PR reverts https://github.com/artsy/eigen/pull/11402
We are reverting a series of prs in response to an incident, see here: https://artsy.slack.com/archives/C0KEQD4B0/p1740779996158429
-
-
-
- revert direct opens tracking - mounir
</details>
> chore: revert direct opens tracking

- src/app/Scenes/HomeView/Sections/Section.tsx
- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
- src/app/Scenes/InfiniteDiscovery/Components/Swiper/AnimatedView.tsx
- src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx
- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
✍️ Currently updating description
In this PR, I am suggesting two performance optimisations for the infinite discovery. They are the following:
- Only render the previous artwork the was swiped, older artworks will be rendered as null to free up memory. They will be rendered as soon as they become last in the `swipedCards` array
- We had a `cards` array that has an array of jsx `InfiniteDiscoveryArtworkCard` components. I believe as you swipe, the latter gets big and the state isn't optimised for such big arrays in React. I updated that to be simply an array of artworks and updated the logic of the swiper to render `InfiniteDiscoveryArtworkCard` within `ImageView`. Meaning that we don't need to keep in memory a component that is not rendered or that was rendered 50 …
> chore: optimize performance of infinite discovery

- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
This PR resolves [DIA-1166]
This PR adds an animation for when a user double taps on an artwork.
https://github.com/user-attachments/assets/7e807bbc-8218-4cfe-956b-692734d04db2
- infinite discovery save artworks on double tap - mounir
-
-
-
</details>
[DIA-1166]: https://artsyproduct.atlassian.net/browse/DIA-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Infinite-discovery): save artworks on double tap

- src/app/Components/Artist/ArtistShows/ArtistShow.tsx
- src/app/Navigation/routes.tsx
- src/app/Scenes/ArtistShows/ArtistShows.tests.tsx
- src/app/Scenes/ArtistShows/ArtistShows.tsx
- src/app/Scenes/Partner/Components/PartnerLocationSection.tsx
- src/app/Scenes/Partner/Components/PartnerShowRailItem.tsx
- src/app/Scenes/Partner/Components/PartnerShows.tsx
- src/app/Scenes/Partner/Components/PartnerShowsRail.tsx
- src/app/Scenes/Partner/Screens/PartnerLocations.tsx
This PR resolves [ONYX-1595] 
Prefetch all links on Partner screen.
- Prefetch all links on Partner screen - ole
-
-
-
</details>
[ONYX-1595]: https://artsyproduct.atlassian.net/browse/ONYX-1595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Prefetch all links on Partner screen

- src/app/Scenes/Search/CuratedCollectionItem.tsx
- src/app/Scenes/Search/CuratedCollections.tests.tsx
- src/app/Scenes/Search/TrendingArtists.tsx
- src/app/Scenes/Search/components/TrendingArtistCard.tsx
This PR resolves [ONYX-1591] 
Prefetch Search screen rail links.
- Prefetch Search screen rail links - ole
-
-
-
</details>
[ONYX-1591]: https://artsyproduct.atlassian.net/browse/ONYX-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Prefetch Search screen rail links

- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
This PR changes how we increment and decrement the number of artworks that are saved during an Infinite Discovery session. We used to increment and decrement this number after the artwork was saved in the backend and some artwork list context management was completed. This created a noticeable (2-3 seconds) delay between when a user taps the save button and when that count gets incremented. The effect of this is that users would receive the wrong number of saved artworks in the toast that users see when they close Infinite Discovery.
As a bonus, this PR also updates the gradient on the Infinite Discovery so that the copy is easier for users to read against the background images.
- Optimistically count saved artworks in an Infinite Discovery …
> fix(InfiniteDiscovery): optimistic save counter

- src/app/Components/ArtistListItem.tests.tsx
- src/app/Components/ArtistListItem.tsx
- src/app/Navigation/routes.tsx
- src/app/Scenes/ArtistSeries/ArtistSeries.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
- src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
- src/app/Scenes/Artwork/Components/ArtworkMakerTitle.tsx
- src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
- src/app/Scenes/Artwork/Components/ContextCard.tsx
- src/app/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx
- src/app/Scenes/Artwork/Components/PartnerCard.tsx
- src/app/Scenes/Artwork/Components/ShortContactGallery.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
- src/app/Scenes/MyCollection/Components/SelectArtistToShareListItem.tsx
- src/app/Scenes/Partner/Partner.tsx
- src/app/system/navigation/navigate.ts
This PR resolves [ONYX-1582] 
Prefetch links on Artwork screen.
- Prefetch all links on Artwork screen - ole
- Prefetch items in Artist lists and refactor Artist List code - ole
- 
-
- 
</details>
[ONYX-1582]: https://artsyproduct.atlassian.net/browse/ONYX-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Prefetch links on Artwork screen

- src/app/Scenes/Articles/News/ArticlesCards.tsx
- src/app/system/navigation/RouterLink.tsx
This PR resolves [ONYX-1517] 
* Related Palette-Mobile PR: https://github.com/artsy/palette-mobile/pull/315
After the fix from https://github.com/artsy/palette-mobile/pull/315, we can now use Palette's [Touchable](https://github.com/artsy/palette-mobile/blob/a5acc4fef5d2892de608b0b45d522ca0a975222c/src/elements/Touchable/Touchable.tsx#L63) component for `RouterLink`'s.
- Use Palette's Touchable component for all RouterLink's - ole
-
-
- Use Palette's Touchable component for all RouterLink's (there shouldn't be a visible difference) - ole
</details> …
> fix: Use Palettes Touchable component for RouterLinks

- src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingQuestionTemplate.tests.tsx
This PR resolves [DIA-1116] 
This PR removes the original LegacyScreen.header that was being used for the Art Quiz and replaces it with a new header that uses a close icon instead of text. We may want to consider removing LegacyScreen altogether in a future PR. 
Before:
After:
-
-
-
- removed the original LegacyScreen.header that was being used for the Art Quiz and replaces it with a new header that uses a close icon instead of text.
</details>
[DIA-1116]: …
> fix(DIA-1116): Refactored Onboarding Art Quiz header 

- src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselCloseButton.tsx
- src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreenAndroid.tsx
- src/app/Scenes/InfiniteDiscovery/Components/__tests__/InfiniteDiscoveryAboutTheWorkTab.tests.tsx
This PR resolves [PBRW-346]
Great example of a (not) p4 bug! Users couldn't exit out of full screen (which for an art app is pretty rough). 
This bug is also an illustration of the principle: for what i'm trying to do, do I surely, absolutely, need this line of code? Eg, if I'm rendering a modal with a back button (simple UX), do i need to check a variety of conditions before I display the only means to exit, or is that a failure point? Its just a close button + an image. Just show the close button. For exits, just trigger close and don't worry about it. Close is close. If it seems like it should be simple, it can be simple. 
Also fixes unrelated flicker issue on the close button as the image is loading. 
Android: 
https://github.com/user-attachments/assets/8dd0d287-8eb6-4cd5-9dcc-7984b368 …
> fix(full-screen-image): Fixes fullscreen close button issues

- src/app/Components/AnimatedBottomButton.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
- src/app/Scenes/ViewingRoom/ViewingRoom.tsx
- src/app/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
- src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tests.tsx
- src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
This PR resolves [ONYX-1596] 
Prefetch links on Viewing Room screen.
- Prefetch links on Viewing Room screen - ole
-
-
-
</details>
[ONYX-1596]: https://artsyproduct.atlassian.net/browse/ONYX-1596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Prefetch links on Viewing Room screen

- src/app/Components/Artist/Articles/Article.tsx
- src/app/Components/Artist/Articles/Articles.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAboutEmpty.tsx
- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
- src/app/Components/Artist/ArtistInsights/ArtistsInsightsEmpty.tsx
- src/app/Components/Artist/ArtistShows/ArtistShow.tsx
- src/app/Components/Artist/RelatedArtistsRailCell.tsx
- src/app/Components/LatestAuctionResultsRail.tsx
- src/app/Components/Lists/AuctionResultListItem.tests.tsx
- src/app/Components/Lists/AuctionResultListItem.tsx
- src/app/Navigation/routes.tsx
- src/app/Scenes/ArtistArticles/ArtistArticles.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesListItem.tests.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tests.tsx
- src/app/Scenes/AuctionResult/AuctionResult.tsx
- src/app/Scenes/AuctionResult/ComparableWorks.tsx
- src/app/Scenes/Gene/Gene.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkComparableWorks.tsx
- src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
This PR resolves [ONYX-1583] 
Prefetch links on Artist screen.
- Prefetch all links on Artist screen - ole
-
-
-
</details>
[ONYX-1583]: https://artsyproduct.atlassian.net/browse/ONYX-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Prefetch links on Artist screen

- src/app/system/navigation/RouterLink.tsx
- src/app/utils/queryPrefetching.ts
This PR resolves [ONYX-1621] 
Currently links don't get prefetched again when the prefetched query has been garbage collected by Relay. This PR removes this behavior.
- Re-prefetch queries when they have been garbage collected - ole
-
-
-
</details>
[ONYX-1621]: https://artsyproduct.atlassian.net/browse/ONYX-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Re-prefetch queries when they have been garbage collected

- src/app/Navigation/routes.tsx
- src/app/Scenes/Fair/Components/FairCollections.tsx
- src/app/Scenes/Fair/Components/FairEditorial.tsx
- src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
- src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
- src/app/Scenes/Fair/FairAllFollowedArtists.tsx
- src/app/Scenes/Fair/FairArticles.tsx
- src/app/Scenes/Fair/FairMoreInfo.tsx
- src/app/Scenes/Fair/FairOverview.tsx
This PR resolves [ONYX-1597] 
Prefetch links on Fair screen.
- Prefetch links on Fair screen - ole
-
-
-
</details>
[ONYX-1597]: https://artsyproduct.atlassian.net/browse/ONYX-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Prefetch links on Fair screen

- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
This PR resolves [ONYX-1587] 
This fixes the artwork card context menu for artwork rails with a dark background. I've decided to simply give the bottom sheet a white background to keep it consistent with other bottom sheets.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-03-18 at 15 41 23](https://github.com/user-attachments/assets/e18d6f43-18f4-4fcc-b70c-b3d428a52883) |![Simulator Screenshot - iPhone 16 - 2025-03-18 at 15 37 27](https://github.com/user-attachments/assets/11fcc926-246f-4625-b472-d0feaa347624) |
- Fix the artwork card context menu for artwork rails with a dark background on home screen -ole
-
-
-
</details>
[app state …
> fix: Artwork card context menu with dark background.

- ios/Artsy/App/ARAppNotificationsDelegate.m
This reverts commit 411f921ffb6059a3256bc22d62b10e40d9550c7b.
This PR reverts the foreground notifications linking revert
Context: [Slack](https://artsy.slack.com/archives/C08HWB3FR1N/p1742312970877799) 🔐
Previous PR: #11639
-
- foreground notifications linking
-
-
</details>
> chore: Revert "revert foreground notifications linking"

- src/app/Scenes/Favorites/Components/FollowedArtists.tests.tsx
- src/app/Scenes/Favorites/Components/FollowedArtists.tsx
- src/app/Scenes/Favorites/Components/FollowedGalleries.tests.tsx
- src/app/Scenes/Favorites/Components/FollowedGalleries.tsx
- src/app/Scenes/Favorites/Components/FollowedShows.tests.tsx
- src/app/Scenes/Favorites/Components/FollowedShows.tsx
- src/app/Scenes/Favorites/Favorites.tsx
- src/app/Scenes/Favorites/FollowsTab.tsx
This PR resolves [ONYX-1602] 
This PR adds the follows tab to the favorites bottom tab.
| <video src="https://github.com/user-attachments/assets/0ec47112-d87e-4c24-b068-d05d2de2d4e8" /> | <video src="https://github.com/user-attachments/assets/84d08b89-613b-4f9b-a908-a1c50d5505c3" /> |
- add follows to favorites tab - mounir
-
-
-
</details>
[ONYX-1602]: https://artsyproduct.atlassian.net/browse/ONYX-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
> feat: add follows to favorites tab

- src/app/system/flags/Components/WrappedFlagProvider.tsx
This reverts commit 0b5dbd9e119877484e740bb6e5eb984327776902.
The commit reverted here is causing Android builds to get stuck on the splash screen. Reverting this to fix those builds while we investigate further.
Related Slack thread [here](https://artsy.slack.com/archives/C02BAQ5K7/p1742559672312569).
-
-
-
- revert "feat: render remaining providers after Unleash is initialized (or errored)"
</details>
> chore(Unleash): revert "feat: render remaining providers after Unleash is initialized (or errored)"

- src/app/Components/Containers/Inbox.tsx
- src/app/Navigation/routes.tsx
- src/app/Scenes/ArtworkList/ArtworkList.tsx
- src/app/Scenes/ArtworkLists/ArtworkLists.tsx
- src/app/Scenes/Collection/Collection.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
- src/app/Scenes/MyProfile/MyProfileHeader.tsx
- src/app/Scenes/Sales/Sales.tsx
- src/app/Scenes/Search/SearchArtworksContainer.tsx
- src/app/Scenes/Shows/ShowsForYou.tsx
- src/app/utils/queryPrefetching.ts
This PR resolves [ONYX-1630] 
This PR replaces Relay's `cacheConfig: force: true` with `fetchPolicy: "store-and-network"` for screens using `useLazyloadQuery`. It also adds a few more queries to routes.tsx for prefetching.
Relay's "store-and-network" fetch policy does not seem to be supported by `QueryRenderer`. During testing, the component did not run a new query when the screen opened, and the query was already cached. I will further investigate and probably migrate the remaining screens that use `QueryRenderer` to `useLazyLoadQuery`.
-
-
-
- Migrate Relay `{ cacheConfig: force true }` to "store-and-network" fetchPolicy (for prefetching) - ole
</details>
[app …
> chore: Migrate Relay `{ cacheConfig: force true }` to `store-and-network` fetchPolicy

- src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx
Was playing around with this trying to debug the missing avatar image on some artist card headers when I noticed that the swipe back was a bit abrasive due to `linear` easing. Added some natural easing to polish it out a bit. 
Re avatar image: if you swipe forward enough they 'plop' in, leading to layout shift. The only fix i could come up with was commenting out this line [here](https://github.com/artsy/palette-mobile/blob/main/src/elements/EntityHeader/EntityHeader.tsx#L96), and then to smooth out the animation to swap to use Moti). Not sure whats up tho, or why after a certain point the image data isn't accessible to the underlying card, but only after card 5 or so. I suspect it has to do with some of the null relay fragment warnings, which we should solve. 
Android …
> chore(infinite-discovery): Add some polish on swipe back

- src/app/Scenes/ArtworkLists/ArtworkLists.tsx
- src/app/Scenes/Favorites/Components/SavesHeader.tsx
- src/app/Scenes/Favorites/Favorites.tsx
- src/app/Scenes/Favorites/SavesTab.tsx
This PR resolves [ONYX-1601] 
This pull request includes changes to the `ArtworkLists` and `Favorites` scenes to add a new `SavesHeader` component. 
**_NOTE:_** We could have fetched the lists of saves directly on the Saves tab, but it would mean updating the `key` value  in `useCreateNewArtworkList` and `useDeleteArtworkList` to ensure the create/edit/delete action work as expected. That would be a bigger change and is not necessary imo
| --- | --- |
| <video src="https://github.com/user-attachments/assets/f3457fa8-08ea-44eb-8f65-e9ebaf07e757" /> | <video src="https://github.com/user-attachments/assets/a7e89eb6-6e58-4cb9-8342-d9c1cb970e25" /> |
- add saves view to the Favorites tab
-
-
-
</details> …
> feat(ONYX-1601): add saves view

- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryMoreWorksTab.tsx
This PR resolves [DIA-1233]
The "other works" tab in the Discover Daily bottom sheet does not allow users to scroll down to view more artworks on Android. However, it works fine on iOS.
We wrapped the contents of that tab in a BottomSheetScrollView, which worked for Android but not iOS.
This PR adds some conditional logic to select the correct wrapper for that tab so that it can be scrolled on both platforms:
https://github.com/user-attachments/assets/f7b0953b-b71b-496e-9005-ea7553c56749
-
-
- Fixed an issue where other works couldn't be scrolled in Discover Daily on Android
-
</details>
[feature …
> fix(DIA-1233): other works tab doesn't scroll on android

- src/app/Scenes/MyCollection/MyCollection.tsx
This PR attempts to resolve an Applause bug report where the tester was seeing the following error message when they accessed the profile tab:
> Error: Cannot read property 'userInterestsConnection' of null
I cannot reproduce this locally, but Sentry shows that this error happens a handful of times a day on production (search for "Unable to load in tab" and find ones that show "Unable to load in tab: profile" in the message). The stack trace of that points to something in MyCollection:
> TypeError: Cannot read property 'userInterestsConnection' of null
at MyCollection (address at ...)
I'm adding a null access operator to the line that accesses `userInterestesConnection` in that file to see if it stops the errors.
-
-
-
- 
</details>
Need help …
> fix(DIA-1162): cannot read property 'userInterestsConnection' of null

- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/BrowseMoreRailCard.tsx
- src/app/Scenes/HomeView/Components/ArtworkModuleRail.tsx
- src/app/Scenes/HomeView/Components/ArtworkRecommendationsRail.tsx
- src/app/Scenes/HomeView/Components/RecommendedAuctionLotsRail.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
- src/app/system/navigation/RouterLink.tsx
- src/app/system/navigation/__tests__/RouterLink.tests.tsx
`RouterLink` wasn't passing the `onPress` callback correctly to its touchable child component (with `hasTouchableChild` prop) when prefetching was disabled (e.g., no `to` prop provided).
This PR fixes the issue and adjusts the "Browse More" rail card that was affected by the issue.
- Fix "Browse More" rail card navigation - ole
-
-
-
</details>
> fix: "Browse More" card navigation

- src/app/Scenes/ArtworkLists/ArtworkLists.tsx
- src/app/Scenes/Favorites/Favorites.tsx
This PR fixes an issue with DX on favorites tab. This is happening because we didn't have suspense wrapping the favorites screen query.
**Before**
https://github.com/user-attachments/assets/23b6974b-9204-4230-9f5a-26954eae291d
**After**
https://github.com/user-attachments/assets/2c0f7ee3-5ba0-4f2e-a3f5-b43fe6747143
-
-
-
- missing suspense on favorites tab - mounir
</details>
> fix: add missing suspense to Favorites

- src/app/utils/useHideSplashScreen.ts
Related PR: https://github.com/artsy/eigen/pull/10951
The currently added delay of 500 ms that the splash screen keeps visible after the home screen has rendered does not seem to be enough anymore to hide the initial loading skeleton and layout shifts (explained in https://github.com/artsy/eigen/pull/10951). This PR updates the timeout to 1200 milliseconds. 
I assume that the initial home screen query has gotten slower since we're also fetching experiments (https://github.com/artsy/eigen/issues/11048).
- Increase Splash screen duration to hide Home screen loading skeletons - ole
-
-
-
</details> …
> fix: Increase Splash screen duration

- src/app/Components/Containers/Inbox.tsx
- src/app/Scenes/Collection/Components/FullFeaturedArtistList.tsx
Resolves https://github.com/artsy/eigen/pull/11744#discussion_r2010228837 
Add local error boundaries to Inbox and collection artists screens.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-03-26 at 10 47 28](https://github.com/user-attachments/assets/89820d04-b85a-4fc5-95b2-9c3287b08d96) | ![Simulator Screenshot - iPhone 16 - 2025-03-26 at 10 32 23](https://github.com/user-attachments/assets/0f9adb1f-4787-4d64-9001-766edcb3e8b5)|
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-03-26 at 10 47 09](https://github.com/user-attachments/assets/0eb48ff8-98bf-42f3-b613-0c44bc933121) |![Simulator Screenshot - iPhone 16 - 2025-03-26 at 10 46 28](https://github.com/user-attachments/assets/d55073ca-b3db-4913-8433-1bec4dc17fbd) | …
> fix: Add local error boundaries to Inbox and collection artists screens

- src/app/Navigation/routes.tsx
Tap on Follows is broken: https://artsy.slack.com/archives/C07PRTJSD6G/p1743106282007899
-
-
-
-
</details>
> fix: redirect to Follows doesn't work

- src/app/Components/ArtistListItem.tsx
We observed that the artist avatar that appears at the top of an artwork card in Discover Daily was slow to load after the first few swipes.
~This PR attempts to fix that by disabling prefetching on the RouterLink that wraps the contents of the ArtistListItem component that makes up the top of an artwork card.~
~I am still not sure why prefetching causes this to happen. I suspect that it has something to do with the bottom sheet also querying for the contents of an ArtistListItem, because the avatar loads correctly when the bottom sheet is commented-out.~
This PR fixes that by requesting the same cover artwork image size that the ArtworkScreenQuery requests. We noticed that prefetching caused a new request for this cover artwork that should have already been in the Relay store. It was, …
> fix(DIA-1239): artist avatar is slow to load in discover daily

- src/app/Components/ArtworkLists/components/ArtworkLists.tsx
This PR resolves [PBRW-612] 
Resolves [Notion card](https://www.notion.so/artsy/Saved-lists-the-list-of-saves-on-the-bottom-sheet-modal-can-be-refreshed-on-pull-let-s-remove-it-1c4cab0764a0803f8d88f644e0685de1?pvs=4) 
[Saved lists] the list of saves on the bottom sheet modal can be refreshed on pull - let’s remove it?
| --- | --- |
| <video src="https://github.com/user-attachments/assets/a9d5dcdb-7aaa-47e1-a1ba-857d0f9f4964" /> | <video src="https://github.com/user-attachments/assets/7e2b8c4f-7808-4052-bb2d-da6a15d6fe6d" /> |
- remove pull to refresh from the saved lists modal
-
-
-
</details> …
> chore: remove pull to refresh from the saved lists modal

- src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCardsChips.tests.tsx
This PR addresses an issue raised by the Data team. When users tap on a chip in the Discover Something New home view section, a `tappedCardGroup` event should be fired, but it hasn't been, so it looks like no users are engaging with it.
|-------|-------|
| https://github.com/user-attachments/assets/2d5483ac-3dd2-4407-ad23-d7e1c25a722b | https://github.com/user-attachments/assets/97f1ee8c-6215-475f-9d64-1e572797aca5 |
-
-
-
-
</details>
> fix: missing tappedCardGroup event on home screen

- src/app/system/navigation/RouterLink.tsx
- src/app/utils/Sentinel.tests.tsx
- src/app/utils/Sentinel.tsx
This PR adds a `threshold` prop to `Sentinel` to be able to prefetch links as soon as they enter the viewport (vs. when they have fully entered the viewport).
| --- | --- |
|https://github.com/user-attachments/assets/af91a3e0-5eb0-43fc-a137-528299732137 | https://github.com/user-attachments/assets/7f0540df-d414-40d0-9f7f-c19718e5b5bd|
| --- | --- |
|https://github.com/user-attachments/assets/82728aee-1fc2-40ed-b293-4b3989b17170 | https://github.com/user-attachments/assets/4564e8a1-f2be-4455-9b8c-b9531f989cab|
- Prefetch links earlier (when they enter the viewport instead of when they are fully visible)- ole
-
-
-
</details>
[app …
> feat: Decrease visibility theshold to prefetch links earlier

- .secrets.baseline
- src/app/utils/PushNotification.tests.ts
- src/app/utils/PushNotification.ts
This PR resolves [PHIRE-1680] 
Fixes Android Braze notifications from navigating the user to the screen twice.
The reason that this was happening is that we use an outdated library and for some reason the [onNotification](https://github.com/artsy/eigen/blob/main/src/app/utils/PushNotification.ts#L255) event is getting called twice always.
We did a workaround a while ago to prevent double tracking but we didn't prevent double navigation.
This PR addresses this issue. 
> [!NOTE]  
> this is only happening on android since iOS handles notifications natively.
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/7fe4a456-7547-402c-83d0-74b74e554a7f" width="400" /> | <video src="https://github.com/user-attachments/assets/56bad87b-7ff4-46d …
> fix: double navigation on android notifications

- src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
This PR resolves [PBRW-549] 
Removes hard coded styles from conversation messages and instead fits to view port, I do not have a device the correct size but you could see how a tablet smaller then this would cause overflow. I think fitting to view port looks better generally but not clear on reason for the limit in the first place.
|---|---|---|
| Android | <img src="https://github.com/user-attachments/assets/1ce09655-f51f-4961-ae9d-fa9d6bdf8446" width="400" /> | <img src="https://github.com/user-attachments/assets/6f98d23f-1702-47b0-bb8a-d6d2b9672bc6" width="400" /> |
- fit messages to viewport in conversations - brian 
-
- 
-
</details> …
> fix: fit messages to viewport on tablets

- ios/Artsy/App/ARAppNotificationsDelegate.m
- ios/Artsy/Constants/ARAppConstants.h
- ios/Artsy/Constants/ARAppConstants.m
- src/app/utils/requestPushNotificationsPermission.ts
This PR resolves [PHIRE-1670] 
We are firing analytics events related to push permissions on every app launch, this PR changes this to only fire on the first time that user sees the dialog.
|Platform|Before|After|
|---|---|---|
|iOS|<video src="https://github.com/user-attachments/assets/35156030-97df-4d1a-9e1b-a19450be8110" width="400" />|<video src="https://github.com/user-attachments/assets/6899c0d5-2acc-4db6-b82d-656d2e402658" width="400" />|
|iOS|<video src="https://github.com/user-attachments/assets/08e952a2-0b95-4910-ae94-b1ed42f75aa8" width="400" />|<video src="https://github.com/user-attachments/assets/c51b82f3-9ec4-40dc-9f41-edf3e2d710b0" width="400" />|
- 
-
-
- improve push notification permission handling and tracking
</details> …
> fix: improve push notification permission handling and tracking

- src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
This PR fixes an issue affecting release builds on android. The issue happens mainly when the user taps on the create alert while having the keyboard closed.
-
-
- dismiss keyboard after tapping on create alert - mounir
-
</details>
> fix: dismiss keyboard after tapping on create alert

- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
This PR resolves [PBRW-558] 
This PR fixes an issue with artworks with edition sets, where the user can create an order for the artwork before an edition set is selected, which breaks in Exchange
The fix that I implemented here was to hide the commercial buttons if the artwork has _more than one_ edition sets and an edition set is not selected
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/cc9cbeba-eb40-4e7c-ad56-9563619bc877" width="400" /> | <video src="https://github.com/user-attachments/assets/52ee5075-282a-4e8c-9a89-a70b70bc5613" width="400" /> |
| iOS | <video src="https://github.com/user-attachments/assets/7ab059ef-36b1-4cf1-b319-2c5e1c71a921" width="400" /> | <video …
> fix(PBRW-558): Fix error on tapping Make Offer

- src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx
This PR adds a check to the Discover Daily swiper logic to avoid "Cannot read property 'internalID' of undefined" errors that appeared in our error logs.
-
-
-
- Added null-safety to swiper logic that was causing errors
</details>
> fix(DIA-1261): cannot read property internalID of undefined in Discover Daily

- src/app/utils/Sentinel.tsx
This PR resolves [ONYX-1656] 
This fixes the Sentinel component "Maximum update depth exceeded" error.
```
[1]  ERROR  Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```
Printing the rerenders with a simple `console.log` inside the component:
```tsx
let renderCount = 0
Sentinel => () => {
renderCount += 1
console.log("Render count:", renderCount)
...
return ...
}
```
**Before:**
https://github.com/user-attachments/assets/bb861492-27e1-448e-ae7e-2e761b45c652
**After:**
https://github.com/user-attachments/assets/359aa2fa-57c1-4d85-a8a7-34ff35d77dc9
- fix Sentinel component maximum …
> fix: Sentinel component "maximum update depth exceeded" error

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/Navigation/utils/useBottomTabsBadges.ts
This PR fixes the bottom navigation tabs badges post react-navigation upgrade.
#nochangelog
> fix: bottom tabs issues post navigation

- .circleci/config.yml
- .secrets.baseline
- src/app/store/AuthModel.ts
- src/app/store/__tests__/AuthModel.tests.ts
- src/app/utils/PushNotification.tests.ts
We have received reports of users that are unable to send themselves password reset emails from the new auth flow. I suspect that the request to send a password reset email is failing for these users because the `AuthModal` is holding on to (and reusing) expired XAPP tokens.
- Fixed a bug where some users couldn't send password reset emails
-
-
-
</details>
> fix(DIA-1173): some users cannot send password reset emails

- src/app/Scenes/Favorites/Favorites.tsx
Addresses a [Notion card](https://www.notion.so/artsy/In-the-designs-there-is-no-stickiness-of-the-header-component-can-we-remove-so-just-to-have-stand-1cfcab0764a080bbb6bbd2d57d22e10f?pvs=4): In the designs, there is no stickiness of the header component – can we remove so just to have standard scroll
Making the header scrollable requires a lot of refactoring and the end performance might not be what we expect. Let's try out the static header, imo it looks better than the sticky header as it reduces the noice from additional animation and makes the screen look cleaner
| Platform |  Video |
|---|---|
| Android | <video src="https://github.com/user-attachments/assets/415a6b55-4221-48e4-abce-b0f3b5cfa192" width="400" /> | <video src="xxx" width="400" /> |
| iOS | <video …
> fix: make the header of the Favorites tab static

- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryMoreWorksTab.tsx
This PR adds a sort order to the artworks listed in the "Other Works" tab of the bottom sheet in Discover Daily. This was necessary because we were seeing more sold or not-for-sale artworks appearing first.
|--------|------|
| ![before](https://github.com/user-attachments/assets/8b645f69-0f14-42c3-834b-36f6347b9a04) | ![after](https://github.com/user-attachments/assets/87de87a3-6408-4dc9-a94c-150ced425f5d) |
- Fixed sort order of artworks in Discover Daily other works tab
-
-
-
</details>
> fix: sort order of artworks in other works tab

- .secrets.baseline
- src/app/Components/Cards/CardWithMetaData.tsx
- src/app/Scenes/HomeView/Components/ActivityRail.tests.tsx
- src/app/Scenes/HomeView/Components/ActivityRail.tsx
- src/app/Scenes/HomeView/Components/HeroUnit.tests.tsx
- src/app/Scenes/HomeView/Components/HeroUnit.tsx
- src/app/Scenes/HomeView/Components/ShowsRail.tests.tsx
- src/app/Scenes/HomeView/Components/ShowsRail.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollectionsItem.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionActivity.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionArticlesCards.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCard.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionHeroUnits.tests.tsx
- src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionMarketingCollections.tests.tsx
This PR resolves [ONYX-1493] 
This PR converts a few more `Touchable`s to `RouterLink` on the home view (to enable prefetching) and improves the test coverage for the updated components.
- Home view prefetching fix and improved test coverage - ole
-
-
-
</details>
[ONYX-1493]: https://artsyproduct.atlassian.net/browse/ONYX-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: More Home view prefetching and better test coverage

- package.json
- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheet.tsx
- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
- src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx
- src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
- yarn.lock
This PR does a few things:
1. It deprecates the rewind button and some "plumbing" that supported it
2. It moves the close button to the left-hand side of the header and changes its icon to a chevron
3. It adds a share button to the right-hand side of the header with tracking events when it is tapped and when the user actually shares
4. It adds a tracking event when the bottom sheet is opened
|----|----------|
| https://github.com/user-attachments/assets/03cec319-72a2-4f26-8dca-9dd12f0a5b5e | https://github.com/user-attachments/assets/6b972f74-eb01-4f0f-b32d-80025b34fbf2 |
- Added the ability to share Discover Daily artworks
- Removed the rewind feature in Discover Daily
-
-
- Added additional tracking events to Discover Daily …
> feat(DIA-1252): allow users to share Discover Daily artworks

- src/app/Scenes/HomeView/Components/HomeHeader.tsx
- src/app/Scenes/HomeView/Components/PaymentFailureBanner.tsx
Noticed some new unable to loads in prod:
https://artsynet.sentry.io/issues/6016955555/events/934702bec8a64c029c4983aa722f7228?environment=production&project=5867225&referrer=alert-rule-issue-list
The payment failure banner did not have an error fallback resulting in unable to loads in the home screen. 
|---|---|---|
| Android | <video src="https://github.com/user-attachments/assets/46df7c32-bffc-4313-96b4-4f5817cedddc" width="400" /> | <video src="https://github.com/user-attachments/assets/4ac83d8e-d4ef-4edf-8ac7-51a4aad3ece3" width="400" /> |
- fix payment banner unable to loads - brian 
-
-
-
</details>
[app state …
> fix: wrap payment banner in error handling

- src/app/Navigation/routes.tsx
- src/app/Scenes/Favorites/Favorites.tsx
- src/app/Scenes/Favorites/FavoritesContextStore.tsx
This PR resolves [ONYX-1652] 
This PR makes the favorites tab header non sticky. The idea is as follows:
- On initial render, measure the `headerHeight`
- Whenever the user scrolls, translate the content down or up based on the scroll position. 
- **Here** the secret is to translate the **entire content of the screen**, instead of just the header. This way, the content and the header are **never out of sync** by design.
**What comes next?**
Bring the same approach (translating the entire content instead of just the header), to `StickySubHeader` and `AnimatedHeader` inside palette.
| Platform | Video |
|---|---|
| Android | <video src="https://github.com/user-attachments/assets/de914f32-28f6-4ec0-9a83-ab16927c6ee2" width="400" /> |
| iOS | <video …
> feat: make header favorites tab header non sticky

- src/app/Scenes/MyProfile/DarkModeSettings.tests.tsx
- src/app/Scenes/MyProfile/DarkModeSettings.tsx
Resolves https://www.notion.so/artsy/Dark-mode-toggles-don-t-work-when-you-tap-the-radio-buttons-1d7cab0764a080b5afb2da3bdc34d3b4?pvs=4
This fix makes the radio button pressable on the dark mode settings screen.
- Make dark mode settings radio button pressable - ole
-
-
-
</details>
> fix: Make dark mode settings radio button pressable

- src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
Fixes the tests in main eigen that were broken due to enabling the flag in echo.
Surprised that the `run-eigen-tests` test job didn't catch that but it was probably due to having `AREnableFavoritesTab` duplicate in echo for a bit with both false and true values.
#nochangelog
> fix(tests): after merging AREnableFavoritesTab

- ios/Podfile.lock
- package.json
- yarn.lock
Bumps `react-native-clipboard` to latest
#nochangelog
> build(deps): bump react-native-clipboard to latest version

- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
- src/app/Scenes/InfiniteDiscovery/Components/PaginationBars.tsx
- Adds support for viewing and navigating between multiple artwork images in Discover Daily cards
- Adds horizontal bars indicator showing current image position
- Adds left/right tap navigation while preserving double-tap to save
- Created a dedicated PaginationBars component for consistent image navigation UI
- Added tap gesture handling to navigate through multiple images when tapping left/right sides of artwork
- Preserved existing double-tap to save functionality in the middle portion of artwork
- Fixed touch handling to avoid conflicts with existing card swipe gestures
- Added haptic feedback for better user experience when changing images
https://github.com/user-attachments/assets/acd0d6f6-c85d-4524-894b-c1b61abacbd1
- Adds support for …
> feat(DIA-1249): Multiple Artwork Images in InfiniteDiscovery

- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/Scenes/HomeView/HomeView.tsx
This PR fixes an issue with tracking that came after https://github.com/artsy/eigen/pull/11727
The problem was that we record the home tracking event, regardless of not seeing the home view.  
https://github.com/user-attachments/assets/2e104f89-049f-4c3b-ace6-95755b22cf5e
-
-
-
- fix: removed additional triggered home view event - mounir, leo
</details>
> fix: removed additional triggered home view event

- package.json
- src/app/Scenes/Favorites/Favorites.tsx
- yarn.lock
* Depends on https://github.com/artsy/palette-mobile/pull/339 &  https://github.com/artsy/palette-mobile/pull/337
Fixes the color of the pill icon on the Favorite screen in dark mode.
**Dark Mode:**
| --- | --- |
| ![Simulator Screenshot - iPhone 16 - 2025-04-24 at 10 45 10](https://github.com/user-attachments/assets/84c14293-18b9-40e5-8337-1c7c5bc8c84b)| ![Simulator Screenshot - iPhone 16 - 2025-04-24 at 10 44 25](https://github.com/user-attachments/assets/ce795bfa-dabe-43ff-a55e-bb7906a5ae22)|
**Light Mode:**
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-04-24 at 10 44 18](https://github.com/user-attachments/assets/02fe4877-0888-4021-9ad6-09e1ceae73ae) |![Simulator Screenshot - iPhone 16 - 2025-04-24 at 10 44 …
> fix: Favorites screen dark mode pill icon color

- src/app/Navigation/routes.tsx
- src/app/Scenes/MyAccount/MyAccountEditPriceRange.tests.tsx
- src/app/Scenes/MyAccount/MyAccountEditPriceRange.tsx
- src/app/Scenes/MyProfile/Components/MyProfileScreenWrapper.tsx
- src/app/Scenes/MyProfile/DarkModeSettings.tsx
- src/app/Scenes/MyProfile/MyProfilePreferences.tsx
- src/app/Scenes/MyProfile/MyProfilePrivacy.tsx
- src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
- src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
- src/app/Scenes/MyProfile/MyProfileSettings.tsx
- src/app/Scenes/MyProfile/MyProfileTermsAndConditions.tsx
- src/app/Scenes/PrivacyRequest/PrivacyRequest.tsx
This PR resolves [ONYX-1642]
This PR updates the notifications screen to use the new UI.
| screen | screenshots |
| Notifications | <img width="597" alt="Screenshot 2025-04-25 at 10 53 12" src="https://github.com/user-attachments/assets/3509e75b-641f-449a-9c10-dc80ba582141" /> |
| Terms and Conditions screen | <img width="586" alt="Screenshot 2025-04-25 at 11 53 18" src="https://github.com/user-attachments/assets/88feb794-e54a-4fbb-98dd-4f12f7162a12" /> | 
| Terms and Conditions webview | <img width="592" alt="Screenshot 2025-04-25 at 11 53 24" src="https://github.com/user-attachments/assets/e68e7596-c093-4b6d-83d5-4d1934b1bca7" /> | 
| Supplementar auctions | <img width="596" alt="Screenshot 2025-04-25 at 11 53 33" …
> feat: update notifications screen to use new UI

- src/app/Components/MenuItem.tsx
This PR fixes the MenuItem layout when the font is too big because of accessibility.
Note: I didn't run this through design but I think this is better than broken text
**Before**
___
**After**
- fix menu item layout on large text - mounir
-
-
-
</details>
> fix: menu item layout on large text

- src/app/Scenes/Favorites/Components/FollowedArtists.tsx
- src/app/Scenes/Favorites/Components/FollowedGalleries.tsx
- src/app/Scenes/Favorites/Components/FollowedShows.tsx
- src/app/Scenes/Favorites/Favorites.tsx
this PR adds the follow option picker to the favorites tab.
- show content on empty follow option state - mounir
-
-
-
</details>
> chore: show content on empty follow option state

- src/app/Scenes/MyCollection/Components/MyCollectionArtistFiltersStickyTab.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtists.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
- src/app/Scenes/MyCollection/MyCollection.tsx
Resolves ONYX-1678[](https://artsyproduct.atlassian.net/browse/ONYX-1678)
This adds the Artist tab to the new My Collection screen.
| New | Old |
| --- | --- |
|  ![Simulator Screenshot - iPhone 16 - 2025-04-29 at 13 16 56](https://github.com/user-attachments/assets/de7dd2fc-9dc3-4339-af78-30b852ca9232)| ![Simulator Screenshot - iPhone 16 - 2025-04-29 at 13 18 08](https://github.com/user-attachments/assets/349d5508-f2b9-490d-9b26-904015896885)|
|![Screenshot_1746001329](https://github.com/user-attachments/assets/ee88c9a9-c50f-4c96-887d-9328b8e1d856) |![Screenshot_1746001391](https://github.com/user-attachments/assets/411174d1-335d-49ef-8a2f-81879b287c5c) | 
- New My Collection Artists tab (behind ff) - ole
-
-
-
</details>
Need help with …
> feat: New My Collection Artists tab

- src/app/Scenes/AuctionResult/AuctionResult.tsx
- src/app/Scenes/Inbox/Components/Conversations/Composer.tsx
- src/app/system/devTools/DevMenu/Components/ExperimentFlagItem.tsx
This PR resolves [PBRW-713] 
Dark Mode TextInput text color.
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-05-02 at 10 41 12](https://github.com/user-attachments/assets/6ba532b0-0d9d-48dd-afed-06d2ff8d6cc8) |  ![Simulator Screenshot - iPhone 16 - 2025-05-02 at 10 35 19](https://github.com/user-attachments/assets/aa7c7468-c693-46c3-90a0-ce826aed93a1)|
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-05-02 at 10 41 01](https://github.com/user-attachments/assets/a0a0d9a2-19db-4d4b-9483-f922e438143c)  | ![Simulator Screenshot - iPhone 16 - 2025-05-02 at 10 39 43](https://github.com/user-attachments/assets/1730e11d-8f2a-4b4b-832f-59bb9356ee31)|
- fix Dark Mode TextInput text color (e.g. Conversations) - ole
-
- …
> fix: Dark Mode TextInput text color

- src/app/Components/FullScreenLoadingImage.tsx
https://www.notion.so/artsy/Low-contrast-for-text-on-onboarding-loading-screen-header-1eacab0764a080b08cabc1f31330ee84?pvs=4
FullScreenLoadingImage text color in dark mode.
- fix: FullScreenLoadingImage text color in dark mode - ole
-
-
-
</details>
> fix: FullScreenLoadingImage text color in dark mode

- src/app/App.tsx
- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/Scenes/BottomTabs/bottomTabsConfig.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
- src/app/Scenes/InfiniteDiscovery/hooks/useInfiniteDiscoveryTracking.ts
- src/app/Scenes/Search/Search.tsx
- src/app/system/flags/experiments.ts
This PR sets up an A/B test that replaces the standard "Search" tab with a discovery-focused "Discover" tab for users in the test group.
- Set up "diamond_discover-tab" experiment with control and variant-a groups
- Rename "Search" tab to "Discover" for users in variant-a
- For variant-a users:
- Hide "Trending Artists" and "Artsy Collections" sections
- Show "Discover Something New" and "Explore by Category" sections (these will be hidden from Metaphysics with the same feature flag)
- Implement analytics tracking to measure experiment performance
| Control | Variant A |
|--------|----------|
| ![Screenshot_1745870220](https://github.com/user-attachments/assets/b4465def-03bb-46bd-8bac-44cef599751d) | ![Screenshot_1745870249](https://github.com/user-attachments/assets/7221eebd-b78a-4a91-8e1 …
> feat(DIA-1286): conduct A/B test on Discovery tab proposals

- src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx
This PR fixes an issue with the navigation pills not getting refreshed after signing up for bids.
https://github.com/user-attachments/assets/fd9281f5-9e27-4f19-ba4d-45eb03a8da03
- fix make sure the new active pills show up after refresh - mounir
-
-
-
</details>
> fix: make sure the new active pills show up after refresh

- app.json
Bumps version to 8.71.0 and triggers an iOS beta from main. Reason that the automatic one failed is that when nightly run the app wasn't approved yet
#nochangelog
> chore: prep for 8.71.0

- src/app/Scenes/Search/Search.tsx
This PR removes an unnecessary tracking event that was being fired when the Search screen was first rendered.
> fix: stop firing experiment_viewed event when search screen is rendered

- ios/Artsy/AppDelegate.h
- ios/Artsy/AppDelegate.mm
- ios/ArtsyTests/App_Tests/AppDelegate+ContinuationTests.m
- ios/ArtsyTests/App_Tests/AppDelegate+NotificationsTests.m
- ios/ArtsyTests/View_Controller_Tests/Web_Browsing/ARInternalMobileWebViewControllerTests.m
This PR resolves [PHIRE-1802] 
First raised here: https://github.com/artsy/eigen/pull/12079
This broke with the expo integration, likely the AppDelegate changed how it was instantiated breaking our sharedInstance (which to be fair is not a standard way to do things). The result was that our sharedInstance pointed to the wrong appDelegate which didn't have an instantiated window resulting in native screens not presenting and likely other more subtle and bad things. We don't really need the sharedInstance anyway because we can get the shared appdelegate from the sharedApplication method. 
This doesn't affect Android so leaving screenshots off!
|---|---|---|
| iOS | <video src="https://github.com/user-attachments/assets/69a0b91f-eb79-49c7-a23c-44d96a49c0d2" …
> fix: native screen presenter not finding window

- src/app/Scenes/Onboarding/Auth2/scenes/__tests__/ForgotPasswordStep.tests.tsx
I can't reproduce this locally but my best guess is the second button press can happen while the first press or UI transition is still in flight leading the 2nd not to be handled. This just explicitly waits for the button to be visible and enabled. 
#nochangelog #trivial
> chore(ci): attempt to make flaky test less flaky 

- fastlane/utility_fastlane.rb
Make the flag reminder message a little louder as suggested here: https://artsy.slack.com/archives/C02BAQ5K7/p1746813024602029?thread_ts=1746795170.434749&cid=C02BAQ5K7
Example:
#nochangelog #trivial
> chore(releases): make the flag message louder #trivial

- src/app/utils/Sentinel.tsx
This PR resolves [PBRW-759] 
We are using useFocusEffect in the Sentinel component used by RouterLink, useFocusEffect needs a navigation context to work and it doesn't have one in the AutomountedModal. 
I think we can just use useEffect here but defer to experts on the RouterLink 
This was changed here but not sure if it was required?: https://github.com/artsy/eigen/pull/10849/files
|---|---|---|
| Android | <img src="https://github.com/user-attachments/assets/6db4e979-b6db-4e17-8e49-d4927bad3888" width="400" /> | <img src="https://github.com/user-attachments/assets/e1dd060a-81dc-44eb-906b-3c99d4210932" width="400" /> |
| iOS | <img src="https://github.com/user-attachments/assets/ea37343c-984b-4112-bb79-e2909f325fd5" width="400" /> | <img …
> fix: unable to load in favorites tab - alerts

- src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
- src/app/Scenes/Search/Search.tsx
This PR removes the `overrideShouldBeDisplayed` prop that we added to home view section queries so that sections we wanted to hide from the Home screen could be rendered in the Search screen instead for the `diamond_discover-tab` experiment.
(We want to stop using it because instead of hiding these sections in Metaphysics, we will hide them in Eigen going forward.)
> fix(QA): stop using overrideShouldBeDisplayed for home view sections

- src/app/Providers.tsx
This PR resolves [PBRW-762] 
Memoize the theme to prevent navigating to home view when changing dark mode settings
| --- | --- |
| https://github.com/user-attachments/assets/933a7689-c9f9-4151-a7f1-93e566c68860 | https://github.com/user-attachments/assets/2ad74613-9460-402e-9a57-1a4a65857b1a | 
- Memoize the theme to prevent navigating to home view when changing dark mode settings
-
-
-
</details>
[PBRW-762]: https://artsyproduct.atlassian.net/browse/PBRW-762?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> fix: memoize the theme to prevent navigating to home view when changing dark mode settings

- src/app/App.tsx
- src/app/Scenes/HomeView/Components/HomeViewSectionCardsCard.tsx
- src/app/Scenes/HomeView/HomeView.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
- src/app/Scenes/HomeView/Sections/Section.tsx
- src/app/Scenes/HomeView/hooks/useHomeViewTracking.ts
This PR fixes two issues found with event tracking for the "diamond_discover-tab" experiment.
1. `experiment_viewed` event was not being fired when users logged-in or signed-up (it was only being fired on cold starts when the user was already logged-in).
2. `tapped_card_group` event was being fired with "home" as the context owner type instead of "search" for users in variant A
It also moves the responsibility of hiding home view components for the control group from Metaphysics to Eigen. This was done so that older versions of the app would continue serving those home view components.
-
-
-
- Fixed QA bugs with event tracking for diamond_discover-tab
</details>
[app …
> fix(QA): discover tab a/b test event tracking

- src/app/Scenes/Fair/Components/FairArtworks.tsx
- src/app/Scenes/Fair/Fair.tsx
Improving a bit the suspense situation in FairArtworks
|---|---|---|
| Android |  <video src="https://github.com/user-attachments/assets/ca84efb0-cdb2-47ff-94f0-f9fefe51045d" width="400" /> | <video src="https://github.com/user-attachments/assets/b99cd263-9f15-456b-b025-f8d3558350f4" width="400" /> |
The solution isn't perfect, but it's an improvement over before. I also tried wrapping the content in a separate <Tabs.Masonry />, but using two different <Tabs.Masonry /> components caused the suspended list to have a large top margin, creating excessive empty space that pushed the placeholder down, which didn't look great.
- suspense improvement on fairartworks
-
-
-
</details>
Need help with …
> fix(Fair): suspense improvement on fairartworks

- src/app/Components/LatestAuctionResultsRail.tsx
- src/app/Scenes/Sales/CurrentlyRunningAuctions.tsx
- src/app/Scenes/Sales/Sales.tests.tsx
- src/app/Scenes/Sales/Sales.tsx
- src/app/Scenes/Sales/UpcomingAuctions.tsx
This PR resolves [ONYX-1722]
Applies a few updates to the Auctions screen as part of the updates for auction-engaged users ([see Figma](https://www.figma.com/design/3LYkzfvfTPcYAIgzkaOM1C/Personalization?node-id=39-7842&m=dev))
- New header text and link to auctions guide
- Left-aligned images in **Latest Auction Results** rail
- Consistent spacing between rails, e.g. before **Upcoming Auctions** auctions 
<br>
| Before                                                                                                                                   | After (iOS)                                                                                                                             | After (Android) …
> feat(auctions): update Auctions home screen header and whitespace

- package.json
- scripts/deploys/which-build
Lil #FF to polish up and share something that I had been using myself this week.
When trying to identify which Eigen build to point stakeholders to for QA purposes (e.g. in our [Onyx QA scripts](https://www.notion.so/artsy/App-Auction-segment-personalization-1f2cab0764a080fd8a23f6f16b2d79eb?pvs=4#1f2cab0764a08062a685ea34101c2fd6)), it can be a little tedious and fiddly to find the right build number.
So this adds two convenient methods for automating that.
(h/t @brainbicycle for [inspo](https://artsy.slack.com/archives/C02BAQ5K7/p1646324958299619) a while back)
```sh
yarn which-build
```
```sh
yarn which-submission
```
Output is as follows:
| `yarn which-build` | `yarn which-submission` |
| <img alt="which-build" …
> feat(devx): add `which-build` script for tracing commits to beta or submission builds

- src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
- src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx
This PR resolves [MOPRAT-842] 
This PR updates the use of ArrowUpRight icon to be from Artsy Icons
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/0b4f7025-ba58-4581-9df4-2b64e1b68e39) | ![image](https://github.com/user-attachments/assets/d0a3edd9-c157-438f-9f7e-8d23c8f00216) |
| iOS | ![image](https://github.com/user-attachments/assets/65300f24-d170-4fc5-ac8c-820a13933e0f) | ![image](https://github.com/user-attachments/assets/964ca50e-e08f-4680-9560-079402702325) |
|---|---|---|
| Android | ![image](https://github.com/user-attachments/assets/627dce7a-d7f4-4a65-ab01-ebbb5912bc5b) | ![image](https://github.com/user-attachments/assets/cb71f45c-38f7-4a14-8498-4b647efd1dd5) |
| iOS | …
> chore(MOPRAT-842): Update ArrowUpRight icons

- .eslintrc.js
- eslint-local-rules.js
- src/app/Components/BrowseMoreRailCard.tsx
This PR resolves https://github.com/artsy/eigen/pull/12153/files#r2094585728
This adds an ESLint rule to disallow components from using `onPress` when wrapped with `RouterLink`. This is because the button's `onPress` won't be triggered, and `onPress` should be passed to `RouterLink` instead.
-
-
-
-
</details>
> chore: RouterLink onPress lint rule

- .eslintrc.js
- src/app/Navigation/routes.tsx
- src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
- src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
- src/app/system/navigation/RouterLink.tsx
This PR resolves [EMI-2444] 
This PR adds a new route (behind a feature flag) for the new Order Details screen
|---|---|---|
| Routing when FF is off | <video src="https://github.com/user-attachments/assets/4574399a-3b9e-4fc4-aa01-d69151a0691f" /> | <video src="https://github.com/user-attachments/assets/67c48b51-1e31-4afa-89d7-56f5038c95f5" /> |
| Routing when FF is on | <video src="https://github.com/user-attachments/assets/6d1985af-a55a-4ca2-a07b-a7b1a495dd8d" /> |  <video src="https://github.com/user-attachments/assets/04c0991b-4160-4bfb-a26b-ae918386b881" /> |
- Add route for the new Order Details screen
-
-
-
</details> …
> feat(EMI-2444): Add new route for the new Order Details screen

- src/app/store/AuthModel.ts
This PR adds calls to sentry when user verification fails during the auth flow. This is the verification that tells us whether an email address belongs to a user or not. I want to see how often this happens in production so that I can get a benchmark for any fixes that we make to the verification setup.
-
-
-
- Added sentry messages when user verification fails.
</details>
> chore(DIA-1307): capture sentry messages when verifyUser fails

- package.json
- yarn.lock
This PR resolves [PBRW-814] 
Bumps palette-mobile to fix checkbox issues
#nochangelog
[PBRW-814]: https://artsyproduct.atlassian.net/browse/PBRW-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build(deps): bump palette-mobile to fix checkbox issues

- src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingMarketingCollection.tests.tsx
- src/app/utils/hooks/useBackHandler.tests.ts
- src/app/utils/hooks/useBackHandler.ts
This PR resolves [PBRW-812] 
This PR fixes the broken back button behaviour on Android.
How did I identify the issue?
1. I wrapped all screens with a back button listener and saw the logged events
In our case, that's https://github.com/artsy/eigen/blob/34bd2d817e6ef78dbdc2304146884bce26fdccc4/src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx#L89
2. When I am on the search tab, I saw some console logs, but I didn't get any in other tabs. Which led me to believe that we are overriding the behaviour somewhere.
3. I looked into how we override the back button usually. I met our trusted `useBackHandler`. 
4. I commented it, things worked 🎉 
5. I looked into React navigation docs and identified that we should only handle the back button if the screen is focused, because previous screens …
> fix: broken back button behaviour on android

- src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
- src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx
- src/app/Scenes/MyBids/Components/BiddingStatuses.tsx
- src/app/Scenes/MyBids/Components/SaleInfo.tsx
- src/app/Scenes/MyBids/SaleInfo.tests.tsx
This PR resolves [MOPRAT-844],[MOPRAT-845],[MOPRAT-846],[MOPRAT-847],[MOPRAT-840],[MOPRAT-841]
Follow up to https://github.com/artsy/icons/pull/84, https://github.com/artsy/icons/pull/85, https://github.com/artsy/icons/pull/86, https://github.com/artsy/icons/pull/87
Updates imports for the following migrated icons:
- ArrowheadDownCircleFillIcon
- ArrowheadUpCircleFillIcon
- BoltFillIcon
- FairIcon
- FireIcon
- ArrowUpRightIcon
- BookmarkFillIcon
|Before|After|
|---|---|
| <img width="786" alt="Up-before" src="https://github.com/user-attachments/assets/513b2acf-52ee-4284-ba4d-5f4abe890f47" /> | <img width="786" alt="Up-after" src="https://github.com/user-attachments/assets/51087728-49f6-4af3-81d6-9f6dc91b1db3" /> |
| <img width="786" alt="Down-before" …
> refactor: import icons from @artsy/icons

- e2e/flows/signup.yml
- src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tests.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
This PR resolves [PHIRE-1501] 
- Increases hitslop on checkbox
- separate children from checkbox since they are both pressable
- updates the e2e tests accordingly to utilise the a11y label
|---|---|---|
| Android | <img src="https://github.com/user-attachments/assets/1b9389b3-4202-470d-85f9-4abcf2fb2278" width="400" /> | <img src="https://github.com/user-attachments/assets/f4b64ad8-c027-4e2a-9562-1191e4abe68e" width="400" /> |
| iOS | <img src="https://github.com/user-attachments/assets/f069009c-2226-4c7b-848f-cfc83e47595d" width="400" /> | <img src="https://github.com/user-attachments/assets/250a0f98-54d9-46b2-8485-849208e89529" width="400" /> |
-
-
-
- adjust checkbox a11y labels to work with maestro and improve …
> chore: adjust checkbox a11y labels to work with maestro and improve a11y

- docs/debugging_expo_updates.md
- ios/Artsy/Supporting/QA/ExpoQA.plist
- src/app/system/devTools/DevMenu/Components/ExpoUpdatesOptions.tsx
🤦 Missed this when we migrated from self hosted and only tested updates on the default channel. This should fix switching channels. 
- fix expo updates not applying after switching channels
-
-
-
</details>
> fix: expo updates not applying after switching channels #trivial

- .circleci/config.yml
Fixes failure in main due to fingerprint dep not being available.
Successful job:
https://app.circleci.com/pipelines/github/artsy/eigen/70377/workflows/09500dc8-7ea3-48bd-b96a-0179b8c37735/jobs/245395
#nochangelog
> fix: install node modules before determine-deployment-type

- src/app/Scenes/MyAccount/updateMyUserProfile.ts
- src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
- src/app/Scenes/MyProfile/__tests__/MyProfilePushNotifications.spec.ts
- src/app/Scenes/MyProfile/__tests__/MyProfilePushNotifications.tests.tsx
This PR resolves [ONYX-1724] 
This PR is a follow up to https://github.com/artsy/eigen/pull/12174.
The above PR fixes the issues reported in [ONYX-1724], except one, the **order updates notification**.
**Why was it broken?**
- The order updates notification value wasn't accurate.
- Why? I checked the value in Insomnia and it was updated properly, it turned out that the `receiveOrderNotification` was missing in the query
- Why didn't we notice this with typescript? because we had notifications types hard typed
- What did I do?
- I updated the type to reflect the type from GraphQL
- I added the missing values to the query
| <video src="https://github.com/user-attachments/assets/cff82e14-16d1-45ba-b5ac-f87cf2d60fa3" /> | <video …
> fix: profile notification updates

- .secrets.baseline
- src/app/Scenes/HomeView/Components/ShowsRail.tsx
- src/app/Scenes/HomeView/Components/__tests__/ShowsRail.tests.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
- src/app/Scenes/Shows/ShowsForYou.tsx
- src/app/store/config/features.ts
- chore: remove AREnableShowsForYouLocation feature flag and disableLocation prop
Remove AREnableShowsForYouLocation feature flag as location-based show recommendations have been fully rolled out. The disableLocation prop was only used in response to this feature flag state, so it has also been removed.
Changes:
- Remove AREnableShowsForYouLocation feature flag definition from features.ts
- Always enable location detection in ShowsForYou components
- Remove disableLocation prop from ShowsRailProps and ShowsRailContainerProps interfaces
- Simplify query variables to always set includeShowsNearIpBasedLocation: true when no location available
- Update useLocation hook to always be enabled (disabled: false)
- Remove conditional logic around enableShowsForYouLocation feature flag
- Remove test …
> chore: remove AREnableShowsForYouLocation feature flag

- package.json
- scripts/utils/assignPBRWTicketsToTeams.ts
This PR resolves [PHIRE-1854] 
Adds a script to assign team labels to tickets in PBRW board.
Run setup first and then
```bash
yarn setup:releases
```
```bash
yarn assign-team-labels-pbrw-tickets --dry-run
```
```bash
yarn assign-team-labels-pbrw-tickets
```
#nochangelog
[PHIRE-1854]: https://artsyproduct.atlassian.net/browse/PHIRE-1854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add script to assign PBRW tickets to teams based on ticket description

- docs/deploy_a_hotfix.md
- docs/deploy_to_expo_updates.md
Add login instructions to expo updates docs, need to be logged in to correct account for this to work.
#nochangelog
> chore: add login req to docs

- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
- src/app/store/config/features.ts
Remove AREnableAlertsFiltersSizeFiltering feature flag. Size filtering within alerts has been rolled out to all users and the feature flag is no longer needed.
- feat: cleanup alert size filtering feature flag
</details>
> feat: cleanup alert size filtering feature flag

- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingCuratedArtworks.tsx
This PR makes a small copy change to the onboarding step where users are shown the Curator's Picks collection.
A similar copy change was made on the Home feed Curator's Picks section by updating the text in Gravity's `SiteHeroUnit` model like so:
```ruby
shu = SiteHeroUnit.find 'curators-picks-emerging-app'
shu.update!(app_description: "Fresh, standout works handpicked by our chief curator.")
```
> fix(DIA-1364): curator's pick subtitle copy in onboarding

- src/app/store/GlobalStore.tsx
- src/app/system/relay/middlewares/metaphysicsMiddleware.ts
Co-authored-by: @MounirDhahri 
While pairing we noticed a confusing error that can result if you have a local MP override, without having an MP server running on localhost. 
(We even observed this after a full rebuild from Xcode — I was surprised that the build "remembered" the override, thus didn't suspect the real problem at first)
This change adds a clear dev-facing error message to make this easier to catch in the future.
| <img width="784" alt="before" src="https://github.com/user-attachments/assets/8daa7f51-1447-4fe1-b611-294e0e55d0d3" />  | <img width="784" alt="after" src="https://github.com/user-attachments/assets/975dd1ef-150c-4f75-a423-7e89d6fb4028" /> | 
-
-
-
- Helpful error message if local …
> feat(dx): add helpful error if local MP override fails

- bin/package.json
- fastlane/Fastfile
- fastlane/sentry_fastlane.rb
I realized today that we **do not** need to explicitly have the `@sentry/cli` as a dependency and pass it into the sentry plugins from fastlane anymore - it was optional since it exists inside the plugins themselves.
So this PR is getting rid of it to remove also the complexity of having it break due to versions and update it 😄  (today it failed on me locally and complained that it needs updating again lol, I won't miss it)
#nochangelog
> build(refactor): remove sentry cli from fastfile and sentry fastlane

- HACKS.md
- patches/@react-navigation+bottom-tabs+7.3.3.patch
- scripts/deploys/expo-updates/deploy-to-expo-updates
- src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
This PR allows us to animate the appearance of the bottom tab. This is unfortunately something that react-navigation doesn't support yet, it however is a behaviour that is available in most apps and is quick to implement on the native side.
This helps us making transition between screens smoother and makes our experiene closer to a native experience.
**Before**
<video src="https://github.com/user-attachments/assets/6be76ed5-cb1c-4455-9e0e-e91ad79f62a5"  width="400"></video>
___
**After**
| <video src="https://github.com/user-attachments/assets/fda4cf4e-58f0-43f4-b532-7e62383b2b06" /> | <video src="https://github.com/user-attachments/assets/7c555d00-d6ec-4f1a-8f7a-9cbedac01ea9" /> | 
- animate bottom tabs …
> chore: bottom tabs hiding animation

- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Scenes/Collect/Collect.tsx
- src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
This PR fixes an issue affecting masonry artwork grids in App. When a user selects a set of filters with no results, they get an error instead of the empty state. This usually works fine in most cases, except in the case where one changes the number of columns. 
We had a first go at fixing this [here](https://github.com/artsy/eigen/pull/10319) which did the trick for a long time. But we didn't notice back then is that it wouldn't be enough in case where the artworks are dynamic, which is the case for the first time within the Collect screen.
**Suggested Solution**
Instead of returning a single `Flashlist` handling the case of artworks and no artworks, we would return two separate Flashlists sharing all props, except the dynamic `numColumns`.   
**How's that different from what we have …
> fix: collect screen breaks on empty state

- .circleci/config.yml
- android/app/build.gradle
- ios/Artsy/Supporting/QA/ExpoQA.plist
This PR resolves [PHIRE-1880] 
Default to canary in dev builds to avoid needing to restart the app since that is the channel most devs will use for the time being. 
#trivial #nochangelog
[PHIRE-1880]: https://artsyproduct.atlassian.net/browse/PHIRE-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(releases): default to canary in dev builds #trivial

- src/app/Scenes/Search/useSearchQuery.tsx
This PR attempts to fix an issue that Claude Code noticed while I was debugging the Explore by Category component.
The refetch returned by that hook uses the `SearchScreenQuery` query, even when the `GlobalSearchOverlay` is using it, instead of using the same query that is passed to the hook (which is named `globalSearchInputOverlayQuery` in the case of `GlobalSearchOverlay`). 
-
-
-
- Pass the correct query to useSearchQuery refetch
</details>
> fix: pass the correct query to useSearchQuery refetch

- src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailBuyerProtection.tsx
- src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailMetadata.tsx
- src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailPriceBreakdown.tsx
- src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailBuyerProtection.tests.tsx
- src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailMetadata.tests.tsx
- src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailPriceBreakdown.tests.tsx
- src/app/Scenes/OrderHistory/OrderDetail/OrderDetail.tsx
This PR resolves [EMI-2489] 
> [!NOTE]
This PR adds the order summary to the new Order Detail screen
|---|---|---|
| Order Details | ![image](https://github.com/user-attachments/assets/c5dbfcff-eaca-4a62-88e8-1063f6d4cfbe) | ![image](https://github.com/user-attachments/assets/900750df-889f-4691-ab6d-6d0ef12e9f0d) |
| Long artist names | ![image](https://github.com/user-attachments/assets/a54c8edf-c44c-43f0-ba26-4082012c0da2) | ![image](https://github.com/user-attachments/assets/bbc410fa-51fb-4ab1-95ae-18a648ccc5f8) |
| Long artwork name | ![image](https://github.com/user-attachments/assets/03c83b07-eaed-4516-9723-9d48a11672c3) | ![image](https://github.com/user-attachments/assets/2e0590f0-0291-4371-bf …
> feat(EMI-2489): Add order summary in Order Details

- src/app/Navigation/utils/useBottomTabsBadges.ts
- src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
This PR resolves [ONYX-1776]
This follows up https://github.com/artsy/eigen/pull/11319 by converting all the activity dots from red to blue.
| <nobr>Platform</nobr> | Before | After |
|---|---|---|
| Android | <img height=400 alt="red" src="https://github.com/user-attachments/assets/f4214009-5a21-4c56-8aaf-985394f6ea5f" /> | <img height=400 alt="blue" src="https://github.com/user-attachments/assets/c76f8042-febf-4e07-a6d6-f06d529777af" /> |
| iOS | <img height=400 alt="red" src="https://github.com/user-attachments/assets/1120ae0e-180e-4525-b548-69c8780ea6a3" /> | <img  height=400 alt="blue" src="https://github.com/user-attachments/assets/30498682-9509-433f-8059-785271afa40b" /> |
- Convert activity indicator dots from red to blue
-
-
- …
> feat: convert activity dots to blue

- src/app/Components/Artist/ArtistHeaderNavRight.tsx
- src/app/Components/Artist/__tests__/ArtistHeaderNavRight.tests.tsx
- src/app/Components/Toast/ToastComponent.tsx
- src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
- src/app/Scenes/Artist/Artist.tsx
- src/app/Scenes/Collection/Collection.tsx
- src/app/store/config/features.ts
- src/app/system/relay/middlewares/cacheHeaderMiddleware.ts
- src/app/utils/queryPrefetching.ts
We are finally there!
This PR comes after two previous improvements to the artist screen 
1. Improve screen layout logic and decouple components https://github.com/artsy/eigen/pull/12370
2. decouple queries https://github.com/artsy/eigen/pull/12373
This PR comes as the cherry on the top of the previous improvements to allow us finally to take advantage of `@cacheable`. The goal is: **We don't want regular app usage to be interrupted by any skeletons. We want users to focus on buying art and not on skeletons**.
___
**Bonus:**
I added a cache hit visualizer to make it easy to tell if a query hit the cache or not
<details><summary>Screen Recording</summary>
<p>
https://github.com/user-attachments/assets/35400fc9-9077-4ee6-a2c6-527fabedb4ad
</p>
</details> 
___
**Before** …
> feat: make artist above the fold query cacheable

- .circleci/config.yml
Android betas failing due to missing assets, possibly a bad merge, will look but adding back for now.
#trivial #nochangelog
> fix: add back asset download

- src/app/Scenes/OrderHistory/__tests__/OrderHistoryRow.tests.tsx
This PR updates the Order History Row tests to include both states of the AREnableNewOrderDetails feature flag
#nochangelog
> chore: update Order History row tests

- scripts/ci/report-maestro-test-failure
This PR resolves [PHIRE-1877] 
Bumps the S3 presign screenshot url expiration for e2e tests from 1 day  to 15 days for easier debugging.
FYI the screenshots are already persisted for longer time than this so no further changes are needed
#nochangelog
[PHIRE-1877]: https://artsyproduct.atlassian.net/browse/PHIRE-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update S3 presign screenshot url expiration to 15 days in report-maestro-test-failure script

- scripts/utils/exportNotionTicketsToJira.ts
This PR resolves [PHIRE-1913] 
Updates the notion export script to add team labels directly rather than relying on components. 
Based on feedback that it was confusing which components bugs belonged to and devs generally know which teams surfaces belong to.  
Also updated the QA templates for Folio and Eigen to use this field.
Test bugs here:
https://artsyproduct.atlassian.net/browse/PBRW-999
https://artsyproduct.atlassian.net/browse/PBRW-1000
https://artsyproduct.atlassian.net/browse/PBRW-1001
-
-
-
- update notion script to use teams - brian
</details> …
> chore: update notion script to use team rather than components

- src/app/Components/Artist/ArtistAbout/ArtistCareerHighlights.tsx
- src/app/Components/Artist/ArtistAbout/__tests__/ArtistCareerHighlights.tests.tsx
This PR fixes a bug that was reported in the artist career highlights where "National Gallery of Art, Washington, D.C." was being formatted as "National Gallery of Art, Washington, and D.C." when it was the last item in the list of collecting institutions.
This was happening because in order to render a list of institutions, the template was concatenating the institution names separated by a comma, and replacing the last comma with ", and". When the National Gallery of Art in Washington, D.C. was the last (or only) institution in that list, it would incorrectly identify "D.C." as the last institution.
The solution was to replace the last comma with ", and" outside of the concatenation.
(This is a duplicate of artsy/force#15848)
| BEFORE | AFTER |
|---------|--------|
| <img width="1080" …
> fix(DIA-1411): National Gallery of Art, Washington, D.C.

- src/app/Navigation/utils/__tests__/useBottomTabsBadges.tests.ts
- src/app/Navigation/utils/useBottomTabsBadges.ts
- src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-1845] 
Removes the conditional logic added in https://github.com/artsy/eigen/pull/12428, and simply presents the blue version of the activity dots to everyone.
| <img height="400" alt="Simulator Screenshot - iPhone 16 - 2025-07-18 at 16 36 23" src="https://github.com/user-attachments/assets/6f4e30c4-3bca-4417-8cda-f6ff7f300b8e" /> | <img height="400" alt="Screenshot_1752871022" src="https://github.com/user-attachments/assets/ef486c6b-d06f-4d33-a97c-85ce34e10630" /> | 
-
-
-
- Remove Echo flagging for blue activity dot
</details>
[feature …
> chore: remove Echo flagging for blue activity dot

- src/app/Components/ShowCard.tsx
- src/app/Scenes/HomeView/Components/ShowsRail.tsx
- src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
This PR improves the shows rail performance in the home view 
| <video src="https://github.com/user-attachments/assets/77d90f61-1002-4be7-a0f2-e020b07b9cc1" /> | <video src="https://github.com/user-attachments/assets/7942938f-3021-4e99-b1af-ae3142300263" /> | 
- [x I have added a **changelog entry** below, or my changes do not require one.
-
-
-
- [HomeView Performance] do not re-render shows - mounir
</details>
> chore: [HomeView Performance] do not re-render shows

- src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
Currently, our rails use the `larger` artwork image as preview. This is of course the best quality we provide, but it meas that sometimes, if we have multiple artwork images that are 10 or 20 mb, we would have an artwork rail that is pretty heavy for RAM. Now imagine if we have 8 or 9 of this rail, the ram would pretty fast explode: This is what is exactly happening on our home view.
In this PR, I am still keeping the high quality image, but performing resize to make sure that we are getting a more optimised image from gemini.
Fwiw, this is what we had for a long time but it's something we missed after [this](https://github.com/artsy/eigen/pull/10857) migration
**Example: (I chose a random image and I can already notice the difference)** 
**Before:** …
> chore: [HomeView Performance] use optimised artwork images for rails

- src/app/Navigation/AuthenticatedRoutes/ScreenWrapper.tsx
This PR resolves [[PBRW-1029](https://artsyproduct.atlassian.net/browse/PBRW-1029)]
This PR fixes the broken padding on screens after the user navigates back from a screen to another.
Why was this broken?
It looks like for quite a while, the `blur` event has been unreliable in react-navigation native stacks and the community recommends instead relying on the focus event. In our case, that's totally fine.
| <video src="https://github.com/user-attachments/assets/f5c1c449-4d6d-4379-b02c-2a7852ea1ff1" /> | <video src="https://github.com/user-attachments/assets/caa51eb5-5219-42d5-83b6-d0c38854437f" /> | 
- broken bottom padding after navigating back - mounir
-
-
-
</details> …
> fix: broken bottom padding after navigating back

- src/app/Scenes/HomeView/hooks/useImpressionsTracking.ts
This PR improves the tracking logic inside the artworks rails to take as much heavy lifting from the JS thread to the UI thread. 
Because our home view usually has 8 to 10 artwork rails, re-renders in any of the shared props could lead to so many re-renders, making scrolling over artworks rails slow.
**What are the changes that I am suggesting here?**
Instead of saving the list of rendered items in React state, we want to use a [shared value](https://docs.swmansion.com/react-native-reanimated/docs/2.x/fundamentals/shared-values/#:~:text=Shared%20Values%20are%20among%20the,of%20reactiveness%2C%20and%20driving%20animations.) to save them.
To [ensure reactiveness with the value updates](https://docs.swmansion.com/react-native-reanimated/docs/2.x/fundamentals/shared-values/#reactiveness-with-s …
> chore: [HomeView Performance] impress useImpressions tracking logic

- src/app/utils/masonryHelpers/index.tsx
This PR resolves [ONYX-1862] 
This PR fixes an issue affecting artwork grids and leading to missing artworks. After some investigation, I believe this is affecting at least 4 other screens but potentially more
**1. Initial Query**
When a user initially opens an artwork screen we load 10 artworks
**2. Second Query: Pagination**
When the user reaches the end, we load 15 more artworks
The way relay does both 1 and 2 is by sending a query with `first` and `cursor` arguments . 
Inside MP, we convert `first` and `cursor` to gravity supported arguments, meaning `size`, `page` and `offset`.
Let's break down both steps
**1. Inital Query**
- We send to MP `first: 10` then `cursor:null` - meaning the first 10 artworks
- Based on the arguments we sent, we use `convertConnectionArgsToGravityArgs` …
> fix: bring back missing artworks from collection screen

- ios/Podfile
Change pod spec repo order so artsy takes precedence to avoid dep confusion attacks: 
https://github.com/artsy/eigen/issues/12584
#trivial 
-
-
-
- change spec repo order in Podfile to avoid dep confusion attacks - brian 
</details>
> fix: change spec repo order to avoid dep confusion attacks

- e2e/flows/deeplinks.yml
This PR resolves [PHIRE-2000] 
Adds a scroll to expected element just to delay. Theory is that this is flaky due to not fetching the universal link verifications in time but not 100% on that. Alternatively we can have another test run on the same sim before this one and it should be enough if that is the problem. 
#nochangelog
[PHIRE-2000]: https://artsyproduct.atlassian.net/browse/PHIRE-2000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add a scroll to delay deeplink test

- src/app/Scenes/Fair/Components/FairHeader.tsx
- src/app/Scenes/Fair/__tests__/FairHeader.tests.tsx
Part of a set of requests from Marketing to tweak the design of the fair experience to support the use of these surfaces for a persistent "online shop", sourcing works directly from various gallery partners.
Long-term, we intend to plan out the introduction of a separate "Shop" concept, which can borrow from some fair behavior (like sourcing directly from partners via CMS) but shed some of the time-specific requirements fairs currently have.
This PR resolves [ONYX-1873](https://artsyproduct.atlassian.net/browse/ONYX-187) 🔒 
|---|---|---|
| iOS | <img width="400" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-14 at 14 34 36" src="https://github.com/user-attachments/assets/29266a0c-75bf-44fd-a8fe-2285aa886d62" /> | <img width="400" …
> feat: hide fair date for specific Artsy Edition Shop instance

- .claude/settings.json
chore: fix typo when denying claude access to remote commands
> chore: fix typo when denying claude access to remote commands

- src/app/system/flags/Components/WrappedFlagProvider.tsx
- src/app/system/flags/Components/__tests__/WrappedFlagProvider.tests.tsx
- src/app/system/flags/hooks/__tests__/useUnleashInitializer.tests.ts
- src/app/system/flags/hooks/useUnleashInitializer.ts
This is meant as a conversation starter – not something on the critical path for feature development.
Reflecting on recent Unleash-backed A/B experiments, it would be nice to update the targeting for an experiment so that a certain group is always given the `experiment` variant. For example the members of a specific product team or all Artsy staff members (as identified via the `team` role).
We've recently built some handling into Metaphysics (https://github.com/artsy/metaphysics/pull/6297 and https://github.com/artsy/metaphysics/pull/6465) to support returning Home View content only when the client is requesting from a supported app version. It seems like we can do similar targeting for Unleash feature flags (including experiments), if we pass along an appVersion context field.
- …
> feat: add custom context fields to Unleash

- package.json
- yarn.lock
Reverts artsy/eigen#12711
Turns out this is not needed in order to integrate rozenite so will revert since the bump broke the segment braze integration.
#nochangelog
> chore(Revert): "build(deps): bump @segment/analytics-react-native-plugin-braze to latest"

- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
Fixes https://github.com/artsy/eigen/pull/12729#issuecomment-3291694059
This brings back the heart icon to the onboarding curators' picks artwork grid.
- Bring heart icon back to onboarding curators picks artwork grid - ole
-
-
-
</details>
> fix: Bring heart icon back to onboarding curators picks artwork grid

- .circleci/config.yml
- HACKS.md
- patches/react-native-reanimated+3.16.7.patch
This PR resolves [PHIRE-2297] 
This PR adds 16 KB page size support to reanimated 3.16.7. 
**Note:** This is not going to be needed once we upgrade to 3.17.* because it is already available there. We can remove the patch once [this](https://github.com/artsy/eigen/pull/12718) is merged
Props to https://github.com/software-mansion/react-native-reanimated/pull/7037 for the implementation.
-
-
-
- chore: add 16KB Page size support to reanimated 3.16.* - Mounir
</details>
[PHIRE-2297]: …
> chore: add 16KB Page size support to reanimated 3.16

- src/app/Components/Artist/ArtistInsights/MarketStats.tsx
- src/app/Components/Buttons/InfoButton.tsx
This PR resolves [PBRW-1206] 
| Before | After iOS 1 | After iOS 2 | After Android 1 (scrolling fixed too) | After Android 2 |
| --- | --- | --- | --- | --- | 
| <img width="250"  alt="image" src="https://github.com/user-attachments/assets/b6cd4213-97d0-44c1-9060-366939355261" /> | <img width="250"  alt="image" src="https://github.com/user-attachments/assets/37c6422c-e4ba-4efc-92de-0532c1c8711d" /> | <img width="250"  alt="image" src="https://github.com/user-attachments/assets/22eeab32-2756-4319-8050-0024f0924d1f" /> | <img width="250" alt="image" src="https://github.com/user-attachments/assets/c90e69ef-0e38-42a7-8747-6f818720bd92" /> | <img width="250"  alt="image" src="https://github.com/user-attachments/assets/6d6ded51-410c-4b3f-81e5-ed525e464e11" /> | …
> fix(PBRW-1206): add bottom padding for infoButton component

- src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetFooter.tsx
- src/app/utils/hooks/withSuspense.tsx
This PR fixes a bug where the commercial action buttons were not appearing in the footer of the Discover Daily "swipe up" bottom sheet.
The `FadeIn` component starts with `opacity: 0` (from `showing.value = 0`) and animates to `opacity: 1`. When this wraps the footer component, it creates a conflicting opacity animation with the footer's own reversedOpacityStyle opacity.
The footer's `InfiniteDiscoveryBottomSheetFooterQueryRenderer` is wrapped by `withSuspense`, so it gets the `FadeIn` treatment, which starts invisible and fades in - but this interferes with the footer's own visibility logic.
|-|-|
| <img width="1080" height="2340" alt="before" src="https://github.com/user-attachments/assets/ca5a3e04-340f-4712-a8fe-f81f8d8672a7" /> | <img width="1080" height="2340" …
> fix(hotfix): missing commercial actions in discover daily
