artsy/eigen

- src/app/Scenes/SellWithArtsy/Components/Testimonials.tsx
Fixed the reanimated crashes weirdness
- reanimated crashes - gkartalis
-
-
-
</details>
> fix: reanimated crashes fix pt2

- src/app/Scenes/PriceDatabase/PriceDatabase.tests.tsx
- src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx
- src/app/Scenes/PriceDatabase/components/SizesOptions.tsx
This PR fixes the database query params send when searching and adjusts the tests.
-
-
-
-
</details>
> fix: Price database query params

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
- src/app/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
- src/app/Scenes/Search/AutosuggestResults.tsx
Pass `is_p1_artist` to `saveCollectedArtwork` event.
-
-
-
-
</details>
> chore: Pass is_p1_artist to saveCollectedArtwork event

- src/app/Scenes/PriceDatabase/PriceDatabase.tsx
Validate Price Database form on mount.
-
-
-
-
</details>
> fix: Validate Price Database form on mount

- src/app/Scenes/PriceDatabase/PriceDatabase.tests.tsx
- src/app/Scenes/PriceDatabase/PriceDatabase.tsx
- src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx
This PR resolves [CX-3622] 
- add back button to the price database screen -daria
-
-
-
</details>
[CX-3622]: https://artsyproduct.atlassian.net/browse/CX-3622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add back button to the price database screen

- src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx
Use keyboardShouldPersistTaps always in price database.
-
-
-
-
</details>
> chore: Use keyboardShouldPersistTaps always in price database

- android/app/build.gradle
- fastlane/Fastfile
- package.json
- scripts/build-for-tests-android
> revert(build): enable hermes on android

- HACKS.md
- android/app/build.gradle
- android/app/proguard-rules.pro
- babel.config.js
- package.json
- src/app/utils/DevMenu.tsx
- yarn.lock
> revert(feat): enable hermes

- src/app/Components/ArtsyWebView.tsx
- src/app/routes.ts
Fixes an issue we've had for a while with double WebView loading and broken back button states.
What this does is immediately prevents the subsequent webview link from loading if it meets certain conditions, and will jump backwards in the stack. By the time the user has it the actual back button, the webview has stabilized at the place where it first departed from to launch the native view. 
https://user-images.githubusercontent.com/236943/232156389-00fd5820-157e-4195-b0f3-971822b158a0.mp4
-
-
-
-
</details>
[docs]: …
> fix(webview): Prevent double loads of pages, and fixes back button

- src/app/Scenes/Home/useHomeModules.ts
-
-
-
- update home screen feature flag dependencies array - mrsltun
</details>
> fix: Update home screen feature flag dependencies array

- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
This PR resolves [FX-4741] 
| <video src="https://user-images.githubusercontent.com/3513494/232483362-5cd542cd-ebdd-4610-afaf-dd6deea2ed0a.MP4" />  | <video src="https://user-images.githubusercontent.com/3513494/232483462-c9e4e5d3-d5ea-4a10-a0ce-a063528c9fd5.MP4" />  | 
- Ended auctions can accept bidding on and the end date gets extended - dimatretyak
-
-
-
</details>
[FX-4741]: https://artsyproduct.atlassian.net/browse/FX-4741?atlOrigin=eyJpIjoiNWRkNTljNz …
> fix(FX-4741): Ended auctions can accept bidding on and the end date gets extended

- src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
This PR fixes the issue of selecting an artist in the Sell With Artsy flow
| <video src="https://user-images.githubusercontent.com/20655703/232491409-98042416-0bd7-474e-81ce-3b3eed3f3be2.mp4" /> | <video src="https://user-images.githubusercontent.com/20655703/232491452-fad99639-553f-4dcc-8eb5-08f55e165659.mp4" /> |
- 
-
-
- fix artist selection issue in SWA flow - mrsltun
</details>
> fix: Select artist in SWA flow issue

- src/app/AppRegistry.tsx
Noticed that our app registry got a bit out of order so this alphabetizes things so that screens are easier to find through time. 
> chore(registry): Alphabetize AppRegistry definition

- .circleci/config.yml
This PR resolves [MOPLAT-685] 
Specifies updated macOS resource in our circle config, the old one is deprecated and this one is faster 🐎 
https://discuss.circleci.com/t/macos-resource-deprecation-update/46891
-
-
-
- Update macOS resource in circle - Brian 
</details>
[MOPLAT-685]: https://artsyproduct.atlassian.net/browse/MOPLAT-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: specify new mac resource in config

- scripts/deploy-beta-android
- scripts/deploy-beta-ios
This PR updates the curl function to check the CI status of the currently running deploy
-
-
-
-
</details>
> fix: Update running beta deploys check

- src/app/store/config/features.ts
This PR resolves [CX-3624] 
Turn off “Do more on Artsy” feature flag
Turn on “Meet you new art advisor” feature flag
-
-
-
-
</details>
[CX-3624]: https://artsyproduct.atlassian.net/browse/CX-3624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(CX-3624): Prepare feature flags for the release

- src/app/Scenes/Home/Components/MeetYourNewAdvisorRail.tests.tsx
- src/app/Scenes/Home/Components/MeetYourNewAdvisorRail.tsx
The url for artsy advisor was changed here, also removed the hardcoded staging string.
https://github.com/artsy/force/pull/12265
-
- Update artsy advisor url - Brian 
-
-
</details>
> fix: update url for advisor rail

- src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
Fix "New works for you" rail link.
-
-
-
-
</details>
> fix: New for you rail link

- src/app/store/config/features.ts
-
-
-
- add artwork lists feature flag - dimatretyak
</details>
> chore: add artwork lists feature flag

- src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
This PR resolves [GRO-1554]
Copy change: `Notable Works` -> `Featured Works` on an artist page rail.
_Note that this copy change doesn't include a refactor of the component since it will be removed during the upcoming artist page redesign._
[GRO-1554]: https://artsyproduct.atlassian.net/browse/GRO-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(GRO-1554): change artist page rail title to Featured Works

- src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotCascadingEndTimesBanner.tsx
- src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
- src/app/Scenes/Artwork/Components/CertificateAuthenticity.tests.tsx
- src/app/Scenes/Artwork/Components/CertificateAuthenticity.tsx
- src/app/Scenes/Inbox/Components/Conversations/Support.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/ArtworkSubmissionStatusFAQ.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionSellingWithartsyFAQ.tsx
- src/app/Scenes/SellWithArtsy/Components/FAQSWA.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
This PR resolves [NX-3493](https://artsyproduct.atlassian.net/browse/NX-3493)
Replaces Zendesk links with Salesforce links.
-
-
-
-
</details>
[NX-3493]: https://artsyproduct.atlassian.net/browse/NX-3493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(NX-3493): replace Zendesk with Salesforce links

- src/setupJest.ts
-
-
-
- mock bottom sheet - dimatretyak
</details>
> chore: small update for bottom sheet mock

- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Components/ArtworkLists/components/ArtworkListsBottomSheetBackdrop.tsx
- src/app/Components/ArtworkLists/components/AutomountedBottomSheetModal.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView.tests.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView.tsx
This PR resolves [FX-4753], [FX-4754], [FX-4757] 
https://user-images.githubusercontent.com/3513494/233634150-923f1f56-c8e7-4af4-89bb-b4b226fdc915.mp4
https://user-images.githubusercontent.com/3513494/233636551-2a39aff0-2404-4c3c-a3e7-e950d4fd3b97.mp4
-
-
-
- add bottom sheets for artwork lists - dimatretyak
</details>
[FX-4753]: https://artsyproduct.atlassian.net/browse/FX-4753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FX-4754]: …
> feat(FX-4753, FX-4754, FX-4757): add bottom sheets for artwork lists

- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Components/ArtworkLists/components/ArtworkListsBottomSheetSectionTitle.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView.tsx
- src/app/Components/BottomSheetInput.tsx
This PR resolves [FX-4757] 
https://user-images.githubusercontent.com/3513494/233679722-5d8b7905-d144-4905-b945-775583bed317.mp4
https://user-images.githubusercontent.com/3513494/233679812-78909cf3-a762-4323-8252-b6bb3ed0b397.mp4
-
-
-
- Create new list bottom sheet logic - dimatretyak
</details>
[FX-4757]: https://artsyproduct.atlassian.net/browse/FX-4757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FX-4757): Create new list bottom sheet logic

- src/app/store/config/features.ts
cc @olerichter00 
Enable impressions tracking for artworks in Home feed
#nochangelog
> chore: enable impressions tracking for artworks in home feed

- README.md
> fix: Update CI badge url

- src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
- src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
- src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tests.tsx
- src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/store/config/features.ts
This PR resolves [CX-3604] 
- Update the Auction Lots For You ending soon Home Rail cards
- Urgency Information on the rail cards
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/233346942-1346876d-d1a0-4a7e-8ba9-f8b40bf6479f.png"></td>
<td valign="top"><img src="https://user-images.githubusercontent.com/18648835/233346950-c7c39f97-212e-4a4b-8e9c-812e2a3b1be4.png"></td>
</tr>
</table>
- Urgency Info | New Auction Lots For You ending soon  - kizito
-
-
-
</details> …
> feat(CX-3604): Urgency Info | New Auction Lots For You ending soon 

- src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
fixes import madness on main
#nochangelog
> fix: useFeatureFlag import

- ios/Podfile
- ios/Podfile.lock
Removes this annoying warning that was showing every-time that we were opening flipper.
followed the solution from this issue: https://github.com/facebook/flipper/issues/3554
-
-
-
- removes flipper socket warning  warning on eigen - gkartalis
</details>
> fix: flipper warning on eigen

- src/app/store/config/features.ts
This PR resolves [CX-3634] 
Add my collection collected artists feature flag
#nochanges
[CX-3634]: https://artsyproduct.atlassian.net/browse/CX-3634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add collected artists feature flag

- .circleci/config.yml
- fastlane/Fastfile
- scripts/check-if-app-has-been-approved-for-release.sh
Now that we no longer release manually this script and workflow are not as necessary. Let me know if any concerns or we want to keep!
-
-
-
- Remove now unnecessary release check job - Brian 
</details>
> chore: remove release check no longer necessary

- src/app/Components/ShowCard.tests.tsx
- src/app/Components/ShowCard.tsx
This PR resolves [CX-3631] 
This PR updates the show rail card to match the new designs
**PS:** The logic for showing the city has been discussed in this slack thread: https://artsy.slack.com/archives/C01B2P6LJUU/p1682410963288209
https://user-images.githubusercontent.com/11945712/234539551-7a293254-4816-4aa8-817a-52333889354d.mov
- Adjust show rail cards design - mounir
-
-
-
</details>
[CX-3631]: https://artsyproduct.atlassian.net/browse/CX-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
> feat: update show rail card

- src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
- src/app/Components/ArtworkLists/components/ArtworkInfo.tsx
- src/app/Components/ArtworkLists/components/EntityPreview.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItemSelectedIcon.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtwork.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkHeader.tsx
- src/app/Components/ArtworkLists/views/constants.ts
This PR resolves [FX-4755] 
https://user-images.githubusercontent.com/3513494/234359108-6349fab9-c28f-4755-a6c2-e4623a6721c3.mp4
https://user-images.githubusercontent.com/3513494/234359533-6477234d-2926-40ac-84ff-b36394f5a976.mp4
-
-
-
- Select lists for this artwork view - dimatretyak
</details>
[FX-4755]: https://artsyproduct.atlassian.net/browse/FX-4755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FX-4755): Select lists for this artwork view

- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtwork.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useUpdateArtworkListsForArtwork.tests.ts
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useUpdateArtworkListsForArtwork.ts
This PR resolves [FX-4756] 
https://user-images.githubusercontent.com/3513494/234855215-1d9952b3-4ec1-42ab-8e83-4b2c4b817b59.mp4
https://user-images.githubusercontent.com/3513494/234858040-e06bc5d7-d41d-4b21-8738-d88b44240b9b.mp4
-
-
-
- Save updated artwork lists for artwork - dimatretyak
</details>
[FX-4756]: https://artsyproduct.atlassian.net/browse/FX-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FX-4756): Save updated artwork lists for artwork

- src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
- src/app/utils/animations/AnimateHeight.tsx
This PR resolves [CX-3588] 
Adjust the animation of the "Meet the Specialists" card as suggested [here](https://artsy.slack.com/archives/C2TQ4PT8R/p1682436586466039?thread_ts=1682431882.807419&cid=C2TQ4PT8R).
https://user-images.githubusercontent.com/4691889/234828761-29c459a3-662c-464f-95ef-71c3bfea9239.mp4
| --- | --- |
|https://user-images.githubusercontent.com/4691889/234829056-754a2f24-48b2-44c6-8c63-57e1aa677852.mp4| https://user-images.githubusercontent.com/4691889/234828761-29c459a3-662c-464f-95ef-71c3bfea9239.mp4|
-
-
-
-
</details> …
> fix: Adjust Meet the Specialists animation

- src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tests.tsx
- src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tsx
- src/app/store/config/features.ts
This PR resolves [CX-3661] 
- Correct Urgency Info text color
<p>
</p>
- Correct Urgency Info text color - kizito
-
-
-
</details>
[CX-3661]: https://artsyproduct.atlassian.net/browse/CX-3661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CX-3661): Correct Urgency Info text color

- src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
-
-
-
- restore haptic effect for "Save" button - dimatretyak
</details>
> chore: restore haptic effect for "Save" button

- android/app/src/main/AndroidManifest.xml
Noticed that we're missing tag deeplink from androidmanifest, this pr addresses that
-
-
- add missing tag deeplink to android - gkartalis
-
</details>
> fix: add missing tag deeplink to android

- package.json
- src/app/Scenes/Home/HomeContainer.tsx
- yarn.lock
Related:
- https://github.com/artsy/palette-mobile/pull/94
Running into some issues with crashes in production. There's been lots of minor issues pointing at button through time so we decided to pull the old palette button over to palette-mobile and point at that as a means to potentially mitigate. 
-
-
-
-
</details>
> feat(old-button): Point at old button

- ios/Podfile.lock
- package.json
- yarn.lock
Related: 
- https://github.com/artsy/eigen/pull/8603
Downgrades reanimated: https://artsynet.sentry.io/issues/4066445850/?project=5867225&referrer=issue-stream&stream_index=0
We believe this started happening with reanimated upgrade that came with the palette-button update.
- Downgrade reanimated to hopefully fix crashes - Brian, Chris 
-
-
-
</details>
> fix: downgrade reanimated

- src/app/Components/LoadFailureView.tsx
- src/app/Scenes/Home/Home.tsx
This PR resolves [MOPLAT-739] 
Adds a message in sentry for unable to load screen views so we can start getting a better sense of how often users are seeing these and possibly prioritize fixing them.
Here is an example:
https://artsynet.sentry.io/issues/4148567654/?project=5867225&query=Unable+to+load&referrer=issue-stream&statsPeriod=14d&stream_index=0
Pretty basic right now, active tab in the title error and user metadata in error extras, hopefully breadcrumbs can give us enough to go on otherwise. If we find it isn't enough can add more but open to ideas. 
- 
-
-
- track unable to load screen views - Brian 
</details> …
> chore(tracking): track unable to load

- src/app/Components/PageableScreensView/PageableLazyScreen.tests.tsx
- src/app/Components/PageableScreensView/PageableLazyScreen.tsx
- src/app/Components/PageableScreensView/PageableScreensContext.tests.tsx
- src/app/Components/PageableScreensView/PageableScreensContext.ts
- src/app/Components/PageableScreensView/PageableScreensView.tests.tsx
- src/app/Scenes/Artwork/Artwork.tsx
This PR resolves [MOPLAT-725]
We were noticing some slower performance issues with the pager enabled. Looking more closely, it appeared as though we were rebuilding the component tree (including the pager itself) whenever a new artwork was selected and / or swiped to. This fixes that via `useMemo`, as well as lazily executing the component render only when the component is made displayable. 
-
-
-
-
</details>
[MOPLAT-725]: …
> fix(artwork): Make pager more performant

- src/app/utils/Websockets/auctions/useArtworkBidding.tsx
Refactored `useArtworkBidding` to not break the rules of hooks (_hooks should not be called conditionally_) because it was creating random crashes (crashes were surfaced from the changes of [this pr](https://github.com/artsy/eigen/pull/8430))
- artwork bidding hook issues - gkartalis
-
-
-
</details>
> fix: artwork bidding hook issues

- package.json
- yarn.lock
Updates palette to latest with fixes for reanimated crashes
- Fix reanimated crashes - Brian, Chris, George 
-
-
-
</details>
> fix: update palette for reanimated crashes #trivial

- src/app/Components/AnimatableHeader/AnimatableHeaderLargeTitle.tsx
- src/app/Components/AnimatableHeader/AnimatableHeaderShadow.tsx
- src/app/Components/ArtworkLists/components/ArtworkListsBottomSheetBackdrop.tsx
- src/app/Components/SearchInput.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingWelcome.tsx
- src/app/Scenes/Onboarding/OnboardingWelcome.tsx
- src/app/utils/animations/useSkeletonAnimation.tsx
We are continuing to see crashes + red screens due to these functions, in theory this should not be necessary: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets/#using-hooks
But something seems to be broken with our setup. While we investigate it should be safe to mark these explicitly as workouts since that is what they should be anyway. 
- Once we figure out what is broken and fix it or upgrade to 3 we should be able to get rid of this
- Reanimated fixes once more - Brian 
-
-
-
</details> …
> fix: mark all reanimated hooks functions as worklets explicitly

- src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/GenericGrid.tsx
- src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ArtworkRail/LargeArtworkRail.tsx
- src/app/Components/ArtworkRail/SmallArtworkRail.tsx
- src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
- src/app/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
- src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
- src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
- src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
- src/app/Scenes/Home/Components/AuctionResultsRail.tsx
- src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
- src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/Home/useHomeModules.ts
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
- src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
- src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
- src/app/utils/mutations/useSaveArtwork.ts
- src/app/utils/refreshHelpers.tsx
- src/app/utils/track/ArtworkActions.ts
This PR resolves [CX-3612] 
- Fixes Artwork Save Tracking on Home Rails and Grids
https://user-images.githubusercontent.com/18648835/234883884-57d7243c-5f4e-4797-bdb3-21999d3448dc.mov
-
-
-
- Fix Artwork Save Tracking on Home Rails and Grids - kizito
</details>
[CX-3612]: https://artsyproduct.atlassian.net/browse/CX-3612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix(CX-3612): Fix Artwork Save Tracking on Home Rails and Grids

- src/app/Scenes/MyCollection/MyCollection.tsx
- src/app/Scenes/MyProfile/MyProfileHeader.tsx
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
This PR fixes safe area issues on my collection tab
**Before**
https://user-images.githubusercontent.com/11945712/236795706-8136ec96-5c93-4e18-9f6a-b1720d2f0c08.mov
**After**
https://user-images.githubusercontent.com/11945712/236795721-ba46ffc8-d303-448c-a076-3d4fc3caa03b.mov
- Fix safe area issues on my collection - mounir
-
-
-
</details>
> fix: solve safe area issues on my collection

- src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
- src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx
This PR resolves [CX-3687] 
Use standard header for Contact screen to avoid back button overlapping text.
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-05-08 at 11 58 48](https://user-images.githubusercontent.com/4691889/236795372-d785b3eb-f0c8-40ab-9eb8-dfd408ce202e.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-05-08 at 11 58 33](https://user-images.githubusercontent.com/4691889/236795361-a0b0a7b4-c550-487c-80ba-e42729cf6620.png)|
-
-
-
-
</details>
[CX-3687]: …
> fix: Use standard header for Contact screen to avoid back button overlapping text

- scripts/setup-fastlane-env
Noticed gems get installed every time I run the release scripts when they should only need to be installed once.
-
-
-
- Don't install gems unnecessary for fastlane scripts - Brian 
</details>
> chore: remove lockfile removal in script, prevent unnecessary installation #trivial

- src/app/Components/ArtworkRail/ArtworkRail.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
- src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
- src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
Remove the `trackingContextScreenOwnerType` prop since it is no longer required (see [this PR](https://github.com/artsy/eigen/pull/8636))
-
-
-
- remove unused `trackingContextScreenOwnerType` prop and code - dimatretyak
</details>
> refactor: remove unused `trackingContextScreenOwnerType` prop

- src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
Adjust SWA Meet the Specialist section job title font.
-
-
-
-
</details>
> fix: Adjust SWA Meet the Specialist section job title font

- package.json
- src/app/utils/DevMenu.tsx
- yarn.lock
Turns out `NativeModules.DevMenu` is not supported on Android so will add this tiny module to make it available on android as well
-
-
-
- fix RN devmenu from admin menu on android - gkartalis
</details>
> fix: enable devmenu on android

- src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
- src/app/Scenes/SellWithArtsy/utils/useSWALandingPageData.tsx
This PR resolves [CX-3695] 
Adjust Meet the Specialists filtering to not filter initially and show all specialists.
- Adjust SWA screen "Meet the Specialists" filtering to not filter initially and show all specialists - ole
-
-
-
</details>
[CX-3695]: https://artsyproduct.atlassian.net/browse/CX-3695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Adjust Meet the Specialists filtering

- ios/Artsy/App/ARAppActivityContinuationDelegate.m
- ios/Artsy/App/ARAppDelegate.mm
- ios/Artsy/Networking/ARNetworkConstants.h
- ios/Artsy/Networking/ARNetworkConstants.m
In certain scenarios our deeplinks were being handled on native side in others on the typescript side, this was due to use missing some native configuration for react native linking: https://reactnative.dev/docs/linking?syntax=ios
In some cases this was preventing navigation from happening resulting in users just landing on the home page. 
After adding this config we should be able to handle all deeplink events on the typescript side. 
- Marketing link redirects now live on both native side and typescript side, we can probably get rid of native side
- ignoreDebounce param was added because push links hitting navigate multiple times, maybe related? worth a look: https://github.com/artsy/eigen/pull/6562#discussion_r855550475 …
> fix: deeplinks not working on typescript side

- src/app/Scenes/ArtworkList/ArtworkList.tsx
- src/app/Scenes/ArtworkList/ArtworkListArtworksGridHeader.tsx
- src/app/Scenes/ArtworkList/ArtworkListEmptyState.tests.tsx
- src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
- src/app/Scenes/ArtworkList/ArtworkListTitle.tsx
This PR resolves [FX-4751] 
This PR implements artwork list's screen for empty states
|Default list screen Saved artwork with 0 artwork| Custom artwork list screen when saved artwork has more than 1 artwork|
|---|---|
|![image](https://github.com/artsy/eigen/assets/17421923/501bfaed-9443-4986-b710-0fe0f114cbf2)|![image](https://github.com/artsy/eigen/assets/17421923/53cf4694-7ce8-4bef-976a-bb7c97c296b5)|
- Artwork list with empty state - sam
-
-
-
</details>
[FX-4751]: …
> feat: artwork list empty state

- .secrets.baseline
- src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Providers.tsx
- src/app/Scenes/Artist/Artist.tests.tsx
- src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
- src/app/Scenes/Fair/FairArtworks.tests.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tests.tsx
- src/app/Scenes/Show/ShowArtworks.tests.tsx
- src/app/Scenes/Tag/Tag.tests.tsx
This PR resolves [FX-4763] 
https://github.com/artsy/eigen/assets/3513494/fb2ad0ca-eebb-456e-9434-3644204ec373
https://github.com/artsy/eigen/assets/3513494/2060ac44-f967-4324-bd5a-082c6a76133a
-
-
-
- propagate artwork lists to other surfaces - dimatretyak
</details>
[FX-4763]: https://artsyproduct.atlassian.net/browse/FX-4763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FX-4763): propagate artwork lists to other surfaces

- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
Removing the extra suspense that is used in a component that has a useLazyLoadQuery due to unpredictable crashes
- remove extra suspense from artquiz - gkartalis
-
-
-
</details>
> fix: remove extra suspense from artquiz

- src/app/Scenes/ArtworkLists/ArtworkLists.tsx
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
* https://github.com/artsy/eigen/pull/8636
* https://github.com/artsy/eigen/pull/8219
* https://github.com/artsy/eigen/pull/8391
* https://github.com/artsy/eigen/pull/8393
See [this comment](https://github.com/artsy/eigen/pull/8676/files#r1192470363)
| <video src="https://github.com/artsy/eigen/assets/3513494/bd36f016-9693-4fcd-8be2-0b66d78f3be3" />  | <video src="https://github.com/artsy/eigen/assets/3513494/30eb4e8c-c8fe-4509-970b-23242f108f91" /> | 
-
-
-
-
</details> …
> refactor: use the same relay env for MyCollection screens

- package.json
- yarn.lock
bump @testing-library/react-native from 12.0.1 to 12.1.2
-
-
-
- bump @testing-library/react-native from 12.0.1 to 12.1.2 - gkartalis
</details>
> build(deps): bump @testing-library/react-native from 12.0.1 to 12.1.2

- ios/Podfile.lock
- package.json
- yarn.lock
bump react-native-screens from 3.15.0 to 3.20.0
-
-
-
- bump react-native-screens from 3.15.0 to 3.20.0 - gkartalis
</details>
> build(deps): bump react-native-screens from 3.15.0 to 3.20.0

- src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
- src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
- src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tests.tsx
- src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tsx
This PR resolves [CX-3696] 
When an auction lot on the home page closes, we want to refresh the rail in order to eliminate closed lots 
- refresh auction lots rail when lots close - kizito
-
-
-
</details>
[CX-3696]: https://artsyproduct.atlassian.net/browse/CX-3696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(cx-3696): refresh auction lots rail when lots close

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
This PR resolves [CX-3637] 
- add "Add artist" title
- add border to the "Add Artist" button
- add margins to the avatar
-
-
-
-
</details>
[CX-3637]: https://artsyproduct.atlassian.net/browse/CX-3637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CX-3637): adjust the avatar add button design

- src/app/Components/ArtworkLists/components/ArtworkInfo.tsx
| <img width="505" alt="before" src="https://github.com/artsy/eigen/assets/3513494/b5a8e686-f5c7-4c1d-938f-dd1f0d86907c"> | <img width="505" alt="after" src="https://github.com/artsy/eigen/assets/3513494/69dbcbb4-7392-4e3b-8d84-1ab5f1ac1e2c"> | 
-
-
-
- format artwork description for artwork lists flow - dimatretyak
</details>
> chore: format artwork description for artwork lists flow

- src/app/Scenes/ArtworkLists/ArtworkLists.tsx
| <video src="https://github.com/artsy/eigen/assets/3513494/e6e4807f-3532-4e8d-b8ba-3750a2cbc402" /> | <video src="https://github.com/artsy/eigen/assets/3513494/f3dedaf5-fe21-4fdf-baa4-f8408ae9af7b" />  | 
-
-
-
- update pagination count for artwork lists - dimatretyak
</details>
> chore: update pagination count for artwork lists

- src/app/Components/MenuItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
This PR resolves [[comments on CX-3636](https://artsyproduct.atlassian.net/browse/CX-3636?focusedCommentId=57008)] 
- Use fixed height for the drawer instead of percentage (this will make sure that the content will be always visible regardless of the screen size)
- Adjust the `MenuItem` description text size to be `xs`
- Align the icon at the top instead of v-centerting it with the rest of the MenuItem.
- I didn't add a 2 pixels top padding to the icon to match the designs 100% because 2px is not part of our design system
| --- | --- |
|![Simulator Screenshot - iPhone 14 Pro - 2023-05-16 at 10 25 42](https://github.com/artsy/eigen/assets/11945712/e5afe16c-6c38-4812-909e-fd1624cccf5f) |![Simulator Screenshot - iPhone 14 Pro - …
> fix: address menu item UI review comments

- src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
- src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx
This PR resolves [CX-3703] 
https://github.com/artsy/eigen/assets/36167539/e77885d5-e3e8-4128-9f76-db8d2e42dbb3
- fix errors in the contact the specialist form -daria
-
-
-
</details>
[CX-3703]: https://artsyproduct.atlassian.net/browse/CX-3703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CX-3703): fix errors in the contact the specialist form

- fastlane/metadata/android/en-US/changelogs/default.txt
- fastlane/metadata/en-US/release_notes.txt
> chore: update release note 8.12.5

- src/app/Components/PartnerEntityHeader.tsx
- src/app/Scenes/Activity/Activity.tests.tsx
- src/app/Scenes/Artwork/Components/PartnerCard.tsx
> tests(sticky-tabs-2): sticky tab activity tests

- src/app/AppRegistry.tsx
- src/app/Scenes/Partner/Components/PartnerArtwork.tsx
- src/app/Scenes/Partner/Components/PartnerHeader.tsx
- src/app/Scenes/Partner/Components/PartnerOverview.tsx
- src/app/Scenes/Partner/Components/PartnerShows.tsx
- src/app/Scenes/Partner/Partner.tsx
- src/setupJest.tsx
Refactors Partner page:
- class components - functional components
- use collapsible tabs over sticky tabs
- lazy loading the tabs 
Before:
https://github.com/artsy/eigen/assets/21178754/0057c622-4f7d-4059-9370-cf4e03ce98fe
After:
https://github.com/artsy/eigen/assets/21178754/8e1aeea1-ffad-4dc2-a2a2-e5bfa4fe117d
- partner page sticky tabs refactor - gkartalis
-
-
-
</details>
> refactor(sticky-tabs-2): partner page

- src/app/Scenes/ArtworkList/ArtworkList.tsx
- src/app/Scenes/ArtworkList/ArtworkListEmptyState.tests.tsx
- src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
https://github.com/artsy/eigen/assets/3513494/b032d6dc-8bde-44d8-b145-30872cb15b07
https://github.com/artsy/eigen/assets/3513494/a07c9e1b-a073-4d43-8889-83e8c4435dc7
-
-
-
- support pull-to-refresh on empty artwork list view - dimatretyak
</details>
> feat: support pull-to-refresh on empty artwork list view

- ios/Podfile.lock
- src/app/AppRegistry.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtists.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtworks.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizLikedArtworks.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsEmptyTabs.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingArtists.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollections.tsx
This replaces our stickytabs on the ArtQuiz. 
https://github.com/artsy/eigen/assets/236943/a2b6582f-9d18-4335-baf3-5386c63bcc2f
> refactor(art-quiz): swap in new tabs

- src/app/AppRegistry.tsx
- src/app/Components/States/ZeroState.tsx
- src/app/Scenes/Favorites/FavoriteArtists.tsx
- src/app/Scenes/Favorites/FavoriteCategories.tsx
- src/app/Scenes/Favorites/FavoriteShows.tsx
- src/app/Scenes/Favorites/Favorites.tsx
- src/app/Scenes/MyProfile/MyProfileSettings.tsx
Related:
- https://github.com/artsy/eigen/pull/8679
Swaps in new tabs on Favorites screen: 
https://github.com/artsy/eigen/assets/236943/96ac3288-9660-4f57-a17b-4acbbe4f81c1
> refactor(sticky-tabs-2): Update Favorites with new tabs 

- src/app/Scenes/ArtQuiz/ArtQuizLoader.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tests.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
- src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
- src/app/Scenes/Onboarding/Onboarding.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
This PR resolves [GRO-1645] & [GRO-1609] 
- Adds padding between the Top Auction Lots header and artwork grid
- Updates copy throughout the art quiz
- Adds logic in art quiz results to switch header text based on the tab you're on, and a test to verify that behavior
-
-
-
-
</details>
[GRO-1645]: https://artsyproduct.atlassian.net/browse/GRO-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1609]: …
> fix(GRO-1645): add padding to results grid 

- .secrets.baseline
- src/app/Scenes/Home/Components/ShowsRail.tests.tsx
- src/app/Scenes/Home/Components/ShowsRail.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/store/config/features.ts
- src/app/utils/hooks/useLocationOrIpAddress.ts
This PR disables the "Shows for You" rail location feature flag and fixes the logic. The fix is need to prevent the rail from accessing the devices location if the feature flag is disabled.
-
-
-
-
</details>
> fix: Disable Shows for You location feature flag

- src/app/utils/hooks/useLocationOrIpAddress.ts
Change error message to console log.
https://github.com/artsy/eigen/pull/8665#discussion_r1196515283
-
-
-
-
</details>
> fix: Change error message to console log

- ios/Artsy.xcodeproj/project.pbxproj
We missed a change to this build phase, on my machine this was causing Xcode not to find node. 
https://react-native-community.github.io/upgrade-helper/?from=0.67.5&to=0.69.10#RnDiffApp-ios-RnDiffApp.xcodeproj-project.pbxproj
- [] I have tested my changes on **iOS** and **Android**.
-
-
-
- Missed react native build phase change in upgrade - Brian 
</details>
> fix: add missed build phase change

- src/app/Scenes/Home/Components/AuctionResultsRail.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/Home/useHomeModules.ts
- src/app/utils/extractNodes.ts
This change removes  `totalCount` from all `auctionResultsByFollowedArtists` home screen queries by using Relay's [`@relay(mask: false)` directive](https://relay.dev/docs/api-reference/graphql-and-directives/#relaymask-boolean) instead.
This should avoid the redundant COUNT operation on the backend described [here](https://artsy.slack.com/archives/C03D5MXDAN7/p1684250401554509?thread_ts=1684240515.683009&cid=C03D5MXDAN7).
-
-
-
-
</details>
> fix: Remove totalCount from auctionResultsByFollowedArtists home screen queries

- src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarouselContainer.tsx
- src/app/system/navigation/NavStack.tsx
This PR resolves [https://artsy.slack.com/archives/C01B2P6LJUU/p1680533362544499] 
This PR removes the wrong analytics event triggered on home after opening the app from a deep link.
https://github.com/artsy/eigen/assets/11945712/10fd16e4-387b-4493-98c4-5760ccceb811
-
-
-
- Remove myCollectionOnboarding wrong tracking event - mounir
</details>
> fix: home modules analytics events

- src/app/AppRegistry.tsx
- src/app/utils/DevMenu.tsx
This PR resolves [MOPLAT-784] 
Fixes android dev menu weirdness - happy to hear thoughts on this as I am not 100% what caused it, seems to be the always present modally option that we have on AppRegistry 🤔 but it doesn't affect other screens that we have this 
|Android|iOS|
|---|---|
|https://github.com/artsy/eigen/assets/21178754/7e8a0601-087d-45fe-9a28-74a8f3895247|https://github.com/artsy/eigen/assets/21178754/282f7afb-70f7-4214-9fa5-bd9c3da248d7| 
-
-
-
- dev menu weirdness on android - gkartalis
</details>
[docs]: …
> fix: dev menu weirdness on android

- .circleci/config.yml
Down sizes some of our resource classes to hopefully save some $$.
Not very scientific and a little hard to compare across jobs with our caching but timing looks comparable / acceptable. 
```
After:
build-test-js - 1m 16s - large - medium
check-code - 1m 26s - large - small
detect-secrets - 2m 16s - small - no change
test-js - 7m 10s - large - medium
type-check - 1m 37s - large - small
Before:
build-test-js - 5m 35s - must be caching in new build or something
check-code - 1m 9s 
detect-secrets - 1m 35s
test-js - 6m 43s
type-check - 1m 35s
```
-
-
-
-
</details> …
> build: use smaller images for test-js and other jobs

- .circleci/config.yml
CI failing due to out of memory issues in our test-js job after downsizing, will revert until we can fix. 
-
-
-
-
</details>
> fix: use large again for test js job

- android/app/build.gradle
I cannot reproduce this but we are seeing a lot of crashes in the latest Android release: 
https://artsy.slack.com/archives/C02BAQ5K7/p1684787249019729
The stack trace looks like this issue which maintainers say is fixed in 4.11.2:
https://github.com/segmentio/analytics-android/issues/726
-
-
- Fix segment crash - Brian 
-
</details>
> fix: specify fix version of segment for crash

- src/app/store/config/features.ts
Mark view in room ready for release. 
-
-
-
-
</details>
> chore: mark vir ready for release #trivial 

- android/app/build.gradle
Software 🤷 
https://github.com/segmentio/analytics-android/issues/835
-
-
- Point to fixed segment version - Brian 
-
</details>
> fix: point to really fixed segment version

- src/app/Components/Gene/GeneArtworks.tsx
- src/app/Components/Gene/GeneArtworksFilterHeader.tsx
Adjusted gene sticky filter header to use subTab component
https://github.com/artsy/eigen/assets/21178754/49743bfd-fe80-44c2-a9c4-55aab149df87
- Gene filter header adjustments - gkartalis
-
-
-
</details>
> refactor(sticky-tabs-2): Gene filter header

- src/app/Components/ArtworkLists/components/CreateOrEditArtworkListForm.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
- src/app/Scenes/ArtworkList/ManageArtworkListView.tsx
- src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
- src/app/Scenes/ArtworkList/views/EditArtworkListView/useEditArtworkList.ts
This PR resolves [FX-4793] 
| <video src="https://github.com/artsy/eigen/assets/3513494/a794e32c-c2db-40a7-b803-67a3d0e32a8c" /> | <video src="https://github.com/artsy/eigen/assets/3513494/4b947a03-d73a-4730-a1f0-269fc07c4f95" /> | 
-
-
-
- Ability to edit artwork list - dimatretyak
</details>
[FX-4793]: https://artsyproduct.atlassian.net/browse/FX-4793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FX-4793): Ability to edit artwork list

- src/app/store/config/features.ts
Echo PR: https://github.com/artsy/echo/pull/476
-
-
-
- mark `AREnableArtworkLists` as ready for release - dimatretyak
</details>
> chore: mark `AREnableArtworkLists` as ready for release

- app.json
-
-
-
- update app version to 8.13.0 - mrsltun
</details>
> chore: Update app version to 8.13.0

- docs/debugging.md
Add instructions for debugging on device on iOS.
-
-
-
- Update debugging.mb - Brian 
</details>
> chore: add instructions for debugging on device on iOS

- docs/getting_started.md
@dzucconi made me realize we haven't documented that most of us are using asdf at this point to get ruby, java and nodejs as a prerequisite for setting up the repo. 
-
-
-
- Add docs for asdf - Brian 
</details>
> chore(docs): add asdf and hombrew to prereqs

- src/app/Scenes/Home/Components/ShowsRail.tsx
- src/app/store/config/features.ts
Adds a location detection visualization toggle to debug location detection on the "Shows for You" home screen rail.
-
-
-
- Add location detection visualiser dev toggle - ole
</details>
> chore: Location detection visualiser dev toggle

- src/app/Scenes/ArtworkList/ArtworkList.tsx
- src/app/Scenes/ArtworkList/views/DeleteArtworkListView/DeleteArtworkListView.tsx
- src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
This PR resolves [FX-4795] 
https://github.com/artsy/eigen/assets/3513494/3053aa87-9b43-4863-ac48-bfa6c276fcfb
https://github.com/artsy/eigen/assets/3513494/98b009eb-b0ac-4d98-98c9-fabc37faf028
https://github.com/artsy/eigen/assets/3513494/f271b30f-8896-4d68-a302-06316498b733
-
-
-
- artwork list analytics (stage 1) - dimatretyak
</details>
[FX-4795]: https://artsyproduct.atlassian.net/browse/FX-4795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(FX-4795): artwork list analytics (stage 1)

- .secrets.baseline
- ios/Podfile.lock
- package.json
- src/app/Scenes/Home/Components/ShowsRail.tests.tsx
- src/app/utils/hooks/useLocationOrIpAddress.ts
- yarn.lock
This PR resolves [CX-3630] 
We need to update the way we retrieve the user's public IP address for the "Shows for You" rail on the home screen. The current implementation uses internal IP, which does not work with the geolocation service.
- Fix public IP for location on "Shows for You" rail on home screen - ole
-
-
-
</details>
[CX-3630]: https://artsyproduct.atlassian.net/browse/CX-3630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Get public IP for Shows for You rail location

- src/app/Components/ArtworkGrids/GenericGrid.tsx
- src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
- src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/ArtworkList/ArtworkList.tsx
- src/app/Scenes/Sale/Components/SaleArtworkListItem.tsx
- src/app/system/analytics/AnalyticsContext.tsx
This PR resolves [FX-4795] 
Related PR: https://github.com/artsy/eigen/pull/8763
-
-
-
- artwork list analytics (stage 2)  - dimatretyak
</details>
[FX-4795]: https://artsyproduct.atlassian.net/browse/FX-4795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(FX-4795): artwork list analytics (stage 2) 

- src/app/Components/ArtworkLists/useCheckIfArtworkListsEnabled.ts
- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
| FF Disabled | FF Enabled |
| ![1-2](https://github.com/artsy/eigen/assets/3513494/1458663b-986c-44c7-a55d-216c4a74516a) | ![1-2](https://github.com/artsy/eigen/assets/3513494/884c98dc-9886-4704-8b75-a774a1d2ac23) |
| FF Disabled | FF Enabled |
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-05-26 at 18 37 00](https://github.com/artsy/eigen/assets/3513494/56090564-988f-4abd-8c28-17fd6aa39035) | ![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-05-26 at 18 37 13](https://github.com/artsy/eigen/assets/3513494/a2f4e110-d82a-4a1e-ab2f-2228220f3747) |
-
-
-
- support soft launch of artwork lists for Artsy employe - dimatretyak …
> feat: support soft launch of artwork lists for Artsy employe

- src/app/Components/Pill/Pill.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview/ArtistKindPills.tsx
This PR resolves [CX-3722] 
Add badge style to the pill component and implement it on the artist preview modal in MyColleciton
- add badge style to the pill component and implement it on the artist preview modal in MyColleciton -daria
-
-
-
</details>
[CX-3722]: https://artsyproduct.atlassian.net/browse/CX-3722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CX-3722): add badge style to the pill component

- src/app/utils/hooks/useLocationOrIpAddress.ts
This PR resolves [CX-3630] 
Check location permission for Android to avoid the app crashing if the permission is not granted.
https://github.com/michalchudziak/react-native-geolocation/issues/97
- 
-
-
-
</details>
[CX-3630]: https://artsyproduct.atlassian.net/browse/CX-3630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Check location permission for Android

- .secrets.baseline
- src/app/Scenes/MyAccount/updateMyUserProfile.ts
- src/app/Scenes/MyCollection/MyCollection.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateScreen.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
- src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
- src/app/Scenes/MyCollection/mutations/deleteArtworkImage.ts
- src/app/Scenes/MyCollection/mutations/myCollectionCreateArtwork.ts
- src/app/Scenes/MyCollection/mutations/myCollectionDeleteArtwork.ts
- src/app/Scenes/MyCollection/mutations/myCollectionUpdateArtwork.ts
- src/app/Scenes/Search/AutosuggestResults.tests.tsx
- src/app/Scenes/Search/AutosuggestResults.tsx
- src/app/Scenes/Search/Search.tests.tsx
⚠️ THIS PR IS MERGING THE CHANGES TO 8.13.0 RELEASE CANDIDATE! ⚠️
Since the previous PR (#8777) didn't fix the issue with the insights tab not being updated, this PR updates the relay env across my collection
-
-
-
- update the relay env for my collection screens - mrsltun
</details>
> fix: update my collection relay env

- src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
This PR resolves [CX-3663] 
- Sort Auction lots ending for you soon by timely_at
- Sort Auction lots ending for you soon by timely_at - kizito
-
-
-
</details>
[CX-3663]: https://artsyproduct.atlassian.net/browse/CX-3663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CX-3663): Sort Auction lots ending for you soon by timely_at

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tests.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
- src/app/Scenes/Search/AutosuggestResults.tsx
This PR resolves [CX-3725] 
| Without search entry | With search entry | 
| --- | --- |
| ![1](https://github.com/artsy/eigen/assets/36167539/a1439480-82fa-478c-a384-8e0d4e296b61) | ![2](https://github.com/artsy/eigen/assets/36167539/542c6c1b-3aab-49be-9199-27fc148c9188) |
-
-
-
-
</details>
[CX-3725]: https://artsyproduct.atlassian.net/browse/CX-3725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CX-3725): add Create New Artist button to the artists list

- package.json
- yarn.lock
Relay config package is deprecated and embeded to relay 14 so no further need to keep the package here
-
-
-
- refactor(cleanup): relay config - gkartalis
</details>
> refactor(cleanup): relay config

- .circleci/config.yml
Follow-up to https://github.com/artsy/eigen/pull/8772 since it was merged to avoid failing ci checks due to not finding the deleted deprecated script.
Removes update-changelog job from CI
-
-
-
- remove update-changelog job from ci- gkartalis
</details>
> refactor(ci): remove update-changelog job

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistGridItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
This PR resolves [CX-3702] 
Fix issues raised by Pierluca in the comments: https://artsyproduct.atlassian.net/browse/CX-3702
The design was broken probably because of some other changes on the page
| --- | --- |
| ![simulator_screenshot_8136071C-2763-41A0-841B-357795041762](https://github.com/artsy/eigen/assets/36167539/07cb606f-8518-4dc1-9fcb-1488b2b697de) | ![simulator_screenshot_F5EAA522-C4DE-472A-911F-9D1037AA6A4C](https://github.com/artsy/eigen/assets/36167539/f887adf3-7840-4625-b1c7-26386443b767) |
-
-
-
-
</details> …
> fix(CX-3702): fix layout

- src/app/Scenes/Activity/Activity.tests.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tests.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtists.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
- src/app/Scenes/Favorites/FavoriteArtists.tsx
- src/app/Scenes/Partner/Components/PartnerShows.tsx
Addresses some remaining follow comments from @MounirDhahri in https://github.com/artsy/eigen/pull/8679. 
> chore(tabs): Address misc remaining feedback

- docs/troubleshooting.md
- scripts/setup-xcode-local-node.sh
Adds a section to troubleshooting around `node not found` compilation errors and a script to workaround the issue hopefully quickly. 
-
-
-
- docs for `node not found` issue - brian 
</details>
> chore(docs): node not found docs

- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Components/ArtworkLists/types.ts
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useSavePendingArtworkListsChanges.ts
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useUpdateArtworkListsForArtwork.ts
This PR resolves [FX-4797] 
| <video src="https://github.com/artsy/eigen/assets/3513494/e8f7266d-b36e-4241-9914-7fba44b96185" /> | <video src="https://github.com/artsy/eigen/assets/3513494/cb71b158-ed2b-4de0-aa16-6d85feed1161" /> | 
-
-
-
- Automatically persist any pending artwork lists changes in sheet - dimatretyak
</details>
[FX-4797]: https://artsyproduct.atlassian.net/browse/FX-4797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
> feat(FX-4797): Automatically persist any pending artwork lists changes in sheet

- src/app/Scenes/ArtworkList/views/DeleteArtworkListView/DeleteArtworkListView.tsx
This PR resolves [FX-4800] 
|Before|After|
|---|---|
|<img width="360" alt="image" src="https://github.com/artsy/eigen/assets/17421923/8ba56b34-58e8-4d4c-9d02-d10cd25e6f35">|<img width="363" alt="image" src="https://github.com/artsy/eigen/assets/17421923/1ba248f9-0228-4d86-8793-f7909506d02e">|
-
-
-
-
</details>
[FX-4800]: https://artsyproduct.atlassian.net/browse/FX-4800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: rename back button

- src/app/Scenes/MyCollection/MyCollection.tsx
#future-friday
`myCollectionAuctionResults` interface queries are pretty slow and they're making my collection queries fail often. We are currently triggering them as soon as the user opens the tab but only showing them after they add artwork with insights. This PR changes that and only queries for them when the user adds an artwork.
This PR in addition to [this change](https://github.com/artsy/eigen/pull/8820) will significantly impact the query duration. Once the latter PR will be merged, we won't anymore query for myCollectionAuctionResults. 
More context: [Slack Thread](https://artsy.slack.com/archives/C0HP61PUJ/p1683125133997649?thread_ts=1683111590.832159&cid=C0HP61PUJ)
-
-
-
- fetch auction results separately - mounir
</details>
Need …
> chore(my-collection): fetch auction results separately

- package.json
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
- src/setupJest.tsx
- yarn.lock
Related: 
- https://github.com/artsy/eigen/pull/8820
This adds support for the indicator in MyCollection. Not sure how this should behave, so just opening this PR as an example of how its used and should look. 
> feat(tabs): Add tab notification support to MyCollection

- src/app/Components/ArtworkLists/useCheckIfArtworkListsEnabled.ts
- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
-
-
-
- make artwork lists available for all users - dimatretyak
</details>
> chore: make artwork lists available for all users

- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Components/ArtworkLists/types.ts
- src/app/Components/ArtworkLists/useArtworkListsToast.ts
- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useSavePendingArtworkListsChanges.ts
- src/app/Components/Toast/ToastComponent.tsx
- src/app/Components/Toast/types.ts
Some discussion you can find [this Slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1685723980898399)
| Screenshot | Screenshot |
| ![iOS-1](https://github.com/artsy/eigen/assets/3513494/7f6784c8-f50f-4231-b0e7-809b6f431040) | ![iOS-2](https://github.com/artsy/eigen/assets/3513494/03abb059-96b4-4325-b8da-bcb1ba723e9c) | 
| ![iOS-3](https://github.com/artsy/eigen/assets/3513494/00c463f4-5408-4c0b-be07-512c6230d8ca) | ![iOS-4](https://github.com/artsy/eigen/assets/3513494/680dda40-cd9e-44fd-8284-dad8d6f22746) |
| ![iOS-5](https://github.com/artsy/eigen/assets/3513494/691d4c55-0063-4302-8f6f-977fc82dfbd1) | ![iOS-6](https://github.com/artsy/eigen/assets/3513494/c6e81331-c4aa-4cb4-80ea-772927e3855b) |
| …
> feat: add ability to display image in toasts for artwork lists flow

- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/utils/mutations/useSaveArtwork.ts
This PR resolves [FX-4798] 
| <video src="https://github.com/artsy/eigen/assets/3513494/a42954cd-56b2-4ae0-a79f-f759142277bb" /> | <video src="https://github.com/artsy/eigen/assets/3513494/84099a9a-4ff2-4bd3-aaf1-e8193c3fd327" /> | 
| <video src="https://github.com/artsy/eigen/assets/3513494/a00b85a3-0a35-4f83-8429-057c1ce4670b" /> | <video src="https://github.com/artsy/eigen/assets/3513494/25398007-4879-4a76-bc7c-bd8ee108a4d6" /> | 
-
-
-
- Try to reduce delay between save/unsave and toast message - dimatretyak
</details> …
> spike/feat(FX-4798): Try to reduce delay between save/unsave and toast message

- src/app/Components/Toast/ToastComponent.tsx
-
-
-
- add offset to toast cta - dimatretyak
</details>
> chore: add offset to toast cta

- HACKS.md
- patches/react-native-scrollable-tab-view+1.0.0.patch
This PR resolves [MOPLAT-811] 
Fixes `Tried to register two views with the same name RNCViewPager` crash that we found from playstore [pre-launch report](https://play.google.com/console/developers/6449739225222972501/app/4975007939329818983/pre-launch-report/overview?artifactId=4859817822073730743) and [sentry](https://artsynet.sentry.io/issues/4218775411/events/8b2928403d1c4d6daaa73bbb59cc8f6e/)
By looking into issues of `react-native-scrollable-tab-view` found [this solution](https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/1133#issuecomment-800745239) that worked.
The issue was preventing users to access inbox on android devices.
Replace `react-native-scrollable-tab-view` deprecated library with the new collapsible tabs from palette (might need design input due to …
> fix: patch react-native-scrollable-tab-view to fix android crashes

- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
| ![before](https://github.com/artsy/eigen/assets/3513494/5a1d3f30-d566-4aea-af46-bddafee72c88) | ![after](https://github.com/artsy/eigen/assets/3513494/9898545c-14c3-44f2-aa6b-48402cf501b8) | 
-
-
-
- display artwork list title in one line - dimatretyak
</details>
> chore: display artwork list title in one line

- src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
This PR resolves [CX-3770] 
This PR updates My Collection insights tab placeholder
|---|---|
| <img width="360px" src="https://github.com/artsy/eigen/assets/20655703/7bbff820-981d-470d-82a0-298db5ae622f" /> | <img width="360px" src="https://github.com/artsy/eigen/assets/20655703/1df5382e-2f5e-4911-b924-646cdadb9df7" /> |
- Update MyC Insights tab placeholder - mrsltun
-
-
-
</details>
[CX-3770]: https://artsyproduct.atlassian.net/browse/CX-3770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
> feat(CX-3770): Update My Collection insights tab placeholder

- package.json
- src/app/Providers.tsx
- yarn.lock
Related:
- https://github.com/artsy/palette-mobile/pull/114?t=1686338500707
Swaps in latest (major) palette-mobile breaking changes, around the screen tracking support..
> refactor(tabs): swap in ScreenScrollProvider

- .circleci/config.yml
Main type-check and tests failing due to cache node modules.
Aside, this orb seems to do the same thing we do ourselves in other jobs, that is cache and install node-modules we should probably do the same everywhere?
-
-
-
- fix node module caching failures in ci - Brian 
</details>
> fix: clear the node orb cache

- src/app/AppRegistry.tsx
- src/app/Components/ArticleCard.tsx
- src/app/Scenes/Articles/Articles.tsx
- src/app/Scenes/Articles/ArticlesList.tsx
This PR resolves 
- [MOPLAT-792]
- [MOPLAT-792]
This PR integrates our new Screen.AnimatedHeader into the /articles screen, as well as adding the date to the rail item. 
https://github.com/artsy/eigen/assets/236943/d19904d1-ef56-4305-809c-8633d7b54e86
-
-
-
-
</details>
[MOPLAT-792]: https://artsyproduct.atlassian.net/browse/MOPLAT-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-792]: …
> refactor(articles): Integrate new Screen.AnimatedHeader 

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
This PR increases the artists aril avatar size to md instead of sd. It comes as a request from Product and Design. 
- increase artists aril avatar size to md - mounir
-
-
-
</details>
> chore: increase artists aril avatar size to md

- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtworks.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizLikedArtworks.tsx
- src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
Fixes:
- https://www.notion.so/artsy/ArtQuiz-sticky-tabs-changing-tabs-does-not-move-the-underline-of-the-selected-tab-video-included-33385cd2c2344f919c56a099ee8a1d4d
This fixes an issue where the tab indicator doesn't work, which raises a bug with the `tabScrollEnabled` prop (which we don't need here)
-
-
-
-
</details>
> fix(art-quiz): fix tabs issue

- src/app/Scenes/Home/Components/ShowsRail.tsx
- src/app/utils/hooks/useLocation.ts
Use `includeShowsNearIpBasedLocation` istead of `ip` param in Shows rail.
---
**Related PRs:**
- https://github.com/artsy/metaphysics/pull/5079
- Use includeShowsNearIpBasedLocation param in Shows rail on home screen - ole
-
-
-
</details>
> feat: Use includeShowsNearIpBasedLocation in Shows rail

- .secrets.baseline
- src/app/Scenes/MyCollection/Components/MyCollectionArtworksKeywordStore.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
- src/app/Scenes/MyCollection/MyCollection.tests.tsx
- src/app/Scenes/MyCollection/MyCollection.tsx
- src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkUploadMessages.tsx
- src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
This PR resolves [CX-3785] 
Update my collection sticky tab logic
https://github.com/artsy/eigen/assets/11945712/4bc9a10e-fd93-435b-9dee-b8752af7c6db
- Update sticky parts logic inside my collection
-
-
-
</details>
[CX-3785]: https://artsyproduct.atlassian.net/browse/CX-3785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CX-3785): update my collection sticky tab logic

- src/app/utils/hooks/useLocation.ts
Ensure useLocation loading ends.
-
-
-
-
</details>
> fix: Ensure useLocation loading ends

- fastlane/metadata/android/en-US/changelogs/default.txt
- fastlane/metadata/en-US/release_notes.txt
Release notes for 8.14.0
Related slack threads:
[proposed notes](https://artsy.slack.com/archives/C02BAQ5K7/p1686673714514279) 
[refinements](https://artsy.slack.com/archives/C02BAQ5K7/p1686732705618169)
#nochangelog
> build(release-notes): 8.14.0

- src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
- src/app/Components/ArtworkFilter/components/ArtworkFilterViewOptions.tsx
- src/app/Components/ArtworkFilter/types.ts
- src/app/Components/Icons/GridViewIcon.tsx
- src/app/Components/Icons/ListViewIcon.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
- src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
This PR resolves [CX-3786] 
This PR updates changing the view options to be inside the sort and filter modal inside my collection
And it also updates the ListView and GridView icons to match the new design
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/3f1327d0-a07d-4f57-b0a9-93f4fb22a083" /> | <video src="https://github.com/artsy/eigen/assets/20655703/a47d87b8-7a7b-4563-8da5-c3e898c125c7" /> |
- Update MyC viewAs option to be inside Sort&Filter modal - mrsltun
-
-
-
</details>
[docs]: …
> feat(CX-3786): Move My Collection ViewAs options to Sort&Filter modal

- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
Show initials in partner list if image not available. We do the same on web.
-
-
-
-
</details>
> fix: Show initials in partner list if image not available

- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tests.tsx
- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
Adjust Galleries for You header.
| | |
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-06-15 at 13 09 34](https://github.com/artsy/eigen/assets/4691889/19c52a24-8664-4afb-9dd4-f3222e7c38b7) |![Simulator Screen Shot - iPhone 14 Pro - 2023-06-15 at 12 42 16](https://github.com/artsy/eigen/assets/4691889/e6a90e33-a616-48b5-82fd-1e0b4ce3b0ba) |
-
-
-
-
</details>
> fix: Adjust Galleries for You header

- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
Adjust Galleries for You params to not filter results by a location radius.
-
-
-
-
</details>
> fix: Adjust Galleries for You params

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPrevie.tsx
This PR resolves [CX-3803] 
This PR removes the 'remove artist' CTA when it is not possible to remove the artists
|---|---|
| ![image](https://github.com/artsy/eigen/assets/20655703/b80db45a-52bd-450e-a3e3-7de1457ced39) | ![image](https://github.com/artsy/eigen/assets/20655703/2f5b929c-46d2-4b48-aed8-49b01095ea08) |
- Remove "remove artist" CTA for collected artist when it's disabled - mrsltun
-
-
-
</details>
[CX-3803]: https://artsyproduct.atlassian.net/browse/CX-3803?atlOrigin=eyJpIjoiNWR …
> fix(CX-3803): remove 'remove artist' CTA when unable to remove artist

- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
We need to refetch the "Galleries For You" query if there are no results. This means that the user probably doesn't follow any artists that have artworks listed by a gallery.
In that case we refetch the query (once) without filtering for galleries listing artworks by artists the user follows
-
-
-
-
</details>
> fix: Refetch galleries For You if no results for followed artists

- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
Improve partner list item city list.
[Slack Thread for context](https://artsy.slack.com/archives/C01B2P6LJUU/p1686836351811769)
-
-
-
-
</details>
> fix: Improve partner list item city list

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
This PR resolves [CX-3802] 
This PR removes the Add Artist CTA in the collected artist rail
|---|---|
| ![image](https://github.com/artsy/eigen/assets/20655703/230f19e9-0d0b-43c3-9411-3d437d1b3641) | ![image](https://github.com/artsy/eigen/assets/20655703/abe313ac-4d22-4f1f-8fd1-8b3979205a69) |
- Remove Add Artist CTA from collected artist rail in my collection - mrsltun
-
-
-
</details>
[CX-3802]: https://artsyproduct.atlassian.net/browse/CX-3802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
> fix(CX-3802): Remove 'Add Artist' CTA in collected artist rail

- app.json
prepare for 8.15.0
#nochangelog
> chore: prepare for 8.15.0

- .secrets.baseline
- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tests.tsx
- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
- src/app/Scenes/GalleriesForYou/helpers.tests.tsx
- src/app/Scenes/GalleriesForYou/helpers.tsx
This PR resolves [CX-3809] 
Sort partner list cities by closeness to user location.
| --- | --- |
|![simulator_screenshot_7D453C3F-5FF9-4CE3-BD28-78E754C5914D](https://github.com/artsy/eigen/assets/4691889/449a07f6-1852-47f4-bd5a-89f4a47053bc) |![Simulator Screen Shot - iPhone 14 Pro - 2023-06-20 at 12 10 01](https://github.com/artsy/eigen/assets/4691889/57dd8a9c-86a8-49e3-b187-14a9d3000f5e) |
-
-
-
-
</details>
[CX-3809]: https://artsyproduct.atlassian.net/browse/CX-3809?atlOrigin=eyJpIjoi …
> feat: Sort partner list cities by closeness to user location

- src/app/Scenes/MyCollection/Components/MyCollectionArtistFiltersStickyTab.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionArtworkFiltersStickyTab.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tests.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
- src/app/utils/stringHelpers.tests.ts
- src/app/utils/stringHelpers.ts
This PR resolves [CX-3806] 
This PR adds the search input to the artists only view inside my collection
https://github.com/artsy/eigen/assets/11945712/6e61150b-7eff-404e-8e3f-37aa2befc266
- add artists filtering input to my collection -mounir
-
-
-
</details>
[CX-3806]: https://artsyproduct.atlassian.net/browse/CX-3806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CX-3806): add artists filtering input to my collection

- src/app/Components/ArtistListItem.tsx
- src/app/Components/Select/Select.tests.tsx
- src/app/Components/Select/Select.tsx
This PR resolves [CX-3704] 
Vertically center artist meta data in EntityHeader
| Before                                                                                                                                                | After                                                                                                                                                 |
|-------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![Simulator Screenshot - iPhone 14 Pro - 2023-06-20 at 15 08 …
> fix(CX-3704): vertically center artist meta data in EntityHeader

- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
- src/app/utils/hooks/useLocation.ts
Use IP coordinates in "Galleries for You" to show the correct gallery location.
This is using the coordinates that get exposed in https://github.com/artsy/metaphysics/pull/5096
- Use IP coordinates in Galleries for You - ole
-
-
-
</details>
> feat: Use IP coordinates in Galleries for You

- src/app/Scenes/Onboarding/ForgotPassword.tsx
This PR resolves [MOPLAT-390] 
Makes our reset email error message a little more polite :) 
- Reset password minor copy change - Brian 
-
-
-
</details>
[MOPLAT-390]: https://artsyproduct.atlassian.net/browse/MOPLAT-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add please to reset email message #trivial

- src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
Fix SWA WaysWeSell section spacing.
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-06-22 at 12 27 29](https://github.com/artsy/eigen/assets/4691889/66b3ea19-209c-400b-855f-8cdc303c556c) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-06-22 at 12 27 06](https://github.com/artsy/eigen/assets/4691889/246eabcd-7c75-4b53-873c-0b705d311507)|
- fix SWA WaysWeSell section spacing - ole
-
-
-
</details>
> fix: SWA WaysWeSell section spacing

- src/app/AppRegistry.tsx
- src/app/Components/ArtsyWebView.tsx
- src/app/Components/AuctionResultsList.tsx
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
- src/app/routes.ts
- src/app/store/config/EnvironmentModel.tsx
#future-friday
This PR comes as a follow-up on [Checkout funnel conversion drop](https://www.notion.so/artsy/Checkout-funnel-conversion-drop-in-Q1-2023-ea5ec3f93e7f419185f326de7148ff09).
I figured out that it might be a while before we go on building the checkout flow in native, if ever, so it might be a good idea to try out to do small improvements to our current checkout flow.
I made the following changes:
- Create a new modal Webview that can be used for other purposes if needed
- Fix broken bottom insets in the modal
- Make the modal full screen to keep the user focused on browsing (it was like this before, not sure when it was changed!)
**Before**
https://github.com/artsy/eigen/assets/11945712/c6db576a-33b9-4753-b203-726945134a16
**After** …
> chore: improve orders modal UX

- src/app/store/config/features.ts
mark long press as ready for release
-
-
-
- mark long press as ready for release - gkartalis
</details>
> feat: mark long press as ready for release

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/store/config/features.ts
This PR temporarily hides behind a feature flag the work that was done for [FX-4806] 
We agreed to temporarily hide the work done in https://github.com/artsy/eigen/pull/8835 since there are some not finished parts yet, and we do not feel comfortable releasing this feature without fully implementing the ticket (recent price ranges, histogram are missing)
- Hides behind the feature flag "Inline price control in create/edit alert - Sam" - Nikita
-
-
-
</details>
[FX-4806]: …
> Temporarily disable inline price control for create alerts flow

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Scenes/Artist/Artist.tests.tsx
This PR resolves [GRO-1735](https://artsyproduct.atlassian.net/browse/GRO-1735)
|  <img width="565" alt="GYb4UYn0" src="https://github.com/artsy/eigen/assets/112297/c330e7c5-c720-4668-a161-a885ef2daeba"> | <img width="565" alt="ijtbNwkT" src="https://github.com/artsy/eigen/assets/112297/d7c9bbdf-4404-45a2-b822-ed1b5549a8c5"> |
Remaing tabs to come will match.
- Redesigned empty state for artist artworks tab
-
-
-
</details>
[GRO-1735]: …
> feat(GRO-1735): new artist artworks tab empty state.

- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkEdit.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
I forgot to push my last commit here https://github.com/artsy/eigen/pull/8920/ to address the final comments raised by @olerichter00.
#nochanges
> chore: address missing review comments

- src/app/Components/ArtsyWebView.tsx
This PR fixes the back button behavior in Android in the checkout flow
⚠️ PS: I only tested on Android since the back button is Android specific ⚠️
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/7960c32f-d017-41c5-9620-1ef57f28bb05" /> | <video src="https://github.com/artsy/eigen/assets/20655703/8d1a6992-3472-4dab-9e33-e518efabc763" /> |
-
-
- Update back button behavior in checkout flow - mrsltun
-
</details>
> fix: Android back button behaviour in checkout flow

- src/app/Components/ArticleCard.tsx
- src/app/Components/HTML.tsx
- src/app/Scenes/Article/ArticleScreen.tsx
- src/app/Scenes/Article/Components/ArticleHero.tsx
- src/app/Scenes/Articles/ArticlesList.tsx
This PR resolves [MOPLAT-831]
Minor fixes for new native articles. There's [some questions out in slack here](https://artsy.slack.com/archives/C02NAJ2CGLW/p1687887154992539?thread_ts=1687873189.304179&cid=C02NAJ2CGLW), but nothing that should hold up this PR. 
[MOPLAT-831]: https://artsyproduct.atlassian.net/browse/MOPLAT-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(article): little fixes

- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAboutEmpty.tsx
- src/app/Scenes/Artist/Artist.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
This PR resolves [GRO-1737](https://artsyproduct.atlassian.net/browse/GRO-1737)
Adds an empty state; this wouldn't actually be seen currently but will be once we remove conditional tabs.
- Adds empty state for artist overview tab
-
-
-
</details>
[GRO-1737]: https://artsyproduct.atlassian.net/browse/GRO-1737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(artist): adds about tab empty state

- app.json
prepare for 8.16.0
#nochangelog
> chore: prepare for 8.16.0

- src/app/Scenes/Artist/Artist.tests.tsx
- src/app/Scenes/Artist/Artist.tsx
This PR resolves [GRO-1702](https://artsyproduct.atlassian.net/browse/GRO-1702)
Removes conditional rendering of artist tabs.
https://github.com/artsy/eigen/assets/112297/a95bbb68-655a-41c9-9687-a401e75e2398
- Removes conditional rendering of artist tabs
-
-
-
</details>
[GRO-1702]: https://artsyproduct.atlassian.net/browse/GRO-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(artist): removes conditional rendering of tabs

- README.md
Updates point people and retired projects to be up to date, if anyone else wants to be a point person just say let me know!
#no-changelog
> chore: update point people, retired projects

- src/app/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
Provide a more useful empty state design for the alerts section, guiding collectors towards creating their first alert.
Jira: [FX-4825](https://artsyproduct.atlassian.net/browse/FX-4825)
| ![Simulator Screenshot - iPhone 14 Pro - 2023-07-04 at 15 14 11](https://github.com/artsy/eigen/assets/123595/438fb4c7-3466-4068-8783-1d136c1cd554) | ![Simulator Screenshot - iPhone 14 Pro - 2023-07-04 at 15 08 33](https://github.com/artsy/eigen/assets/123595/95f9c123-a293-4284-b24d-7312d128a89b) |
- feat: update empty state for alerts
</details> …
> feat: update empty state for alerts

- src/app/Components/HTML.tsx
- src/app/store/config/features.ts
Mark native articles as ready for release https://github.com/artsy/echo/pull/490
- enable native articles - gkartalis
-
-
-
</details>
> feat: enable native articles

- src/app/Components/ShareSheet/ShareSheet.tsx
- src/app/Components/ShareSheet/helpers.ts
- src/app/Components/ShareSheet/types.ts
- src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
Fixes the image quality on instagram stories and downloaded images after Sarah Fenn reporting it was broken and kinda pixelated due to bad quality
|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/15f40162-7d92-48d1-ae2e-bfa8f402fcb0" />|<video src="https://github.com/artsy/eigen/assets/21178754/dc192edf-ad44-4cf1-a373-4b95a6e1c98f" />| 
-  low quality share images - gkartalis
-
-
-
</details>
> fix: low quality share images

- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkHeader.tsx
This PR resolves [ONYX-112]
I couldn't reproduce the issue mentioned in this [notion card](https://www.notion.so/artsy/1d1550bef11e4f538104def1aaecf012?v=3d80249da22b42cb824b63de83e9d02f&p=988ce323760246f5ac8a92a503417ad1&pm=s). But provided approach is bullet proof, imo 🤷 
-
-
-
- fix '-1 lists selected' appearing in artwork list sheet
</details>
[ONYX-112]: https://artsyproduct.atlassian.net/browse/ONYX-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(onyx-112): fixes '-1 lists selected' appearing in artwork list sheet

- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
This PR resolves [MOPLAT-823] 
Some minor changes to long press functionality:
- Show "Watch Lot" rather than "Save" for lots
- Move create alert to top of actions
-
- Minor changes to long press - Brian 
-
-
</details>
[MOPLAT-823]: https://artsyproduct.atlassian.net/browse/MOPLAT-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: long press feedback

- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
- src/app/Scenes/GalleriesForYou/helpers.tsx
Fixes partner coordinates being `null` issue on "Galleries for You" screen.
-
-
-
-
</details>
> fix: partner coordinates being null issue

- src/app/Components/ArticleCard.tsx
- src/app/routes.ts
- src/app/store/config/features.ts
This PR resolves [MOPLAT-828] 
Removes article ff, redirects to native view when pressing article deeplinks
FYI: didn't clean up the article webview since we still use it in some cases
https://github.com/artsy/eigen/assets/21178754/59743040-0ad9-4951-a7a9-62e80f54169c
- clean up article ff to release - gkartalis
-
-
-
</details>
[MOPLAT-828]: https://artsyproduct.atlassian.net/browse/MOPLAT-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: clean up article ff

- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
- src/app/store/config/features.ts
Refreshes the long press ff once again after addressing the [launch blocking feedback](https://github.com/artsy/eigen/pull/8964) 
related echo PR https://github.com/artsy/echo/pull/492
#nochangelog
> chore: refresh long press ff

- ios/Podfile.lock
- package.json
- yarn.lock
Bumps react native 69 to [latest version](https://github.com/facebook/react-native/releases/tag/v0.69.12) because they fixed the Oppo and 1Plus device crashes from `runAnimationStep`.
https://github.com/facebook/react-native/issues/35766
Also makes XCode 15 work with eigen.
⚠️ Had to run `cd ios && bundle exec pod update hermes-engine --no-repo-update` due to this react native issue: https://github.com/facebook/react-native/issues/36945 to make CI pass (TLDR; podfile.lock wasnt updating hermes correctly on podfile.lock) and update `podfile.lock` file (resulted in the last commit diff)
-
-
-
- bump react-native from 0.69.10 to 0.69.12 - gkartalis
</details> …
> build(deps): bump react-native from 0.69.10 to 0.69.12

- src/app/Components/Artist/Articles/Article.tsx
- src/app/Components/Artist/Articles/Articles.tests.tsx
- src/app/Components/Artist/Articles/Articles.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
- src/app/Components/MasonryStatic.tsx
This PR resolves [DIA-40] 
Changes the Editorial Rails in Artist -> About tab to the new design.
https://github.com/artsy/eigen/assets/15792853/d2c483e6-b1b3-460d-8edc-315ac1125984
- change the Editorial section in Artist/About tab - araujobarret
-
-
-
</details>
[DIA-40]: https://artsyproduct.atlassian.net/browse/DIA-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-40): change editorial in Artist/About tab

- src/app/Components/Artist/Articles/Article.tsx
- src/app/Components/Artist/Articles/Articles.tests.tsx
Clean up article flag as a followup to https://github.com/artsy/eigen/pull/8961 (fixes tests on main after this PR was merged)
#nochangelog
> chore: cleanup article flag

- src/app/Components/ArtsyWebView.tsx
- src/app/Scenes/Article/Components/ArticleWebViewScreen.tsx
- src/app/Scenes/Article/Components/__tests__/ArticleWebViewScreen.tests.tsx
- src/app/Scenes/Article/__tests__/ArticleScreen.tests.tsx
- src/app/routes.ts
Native article navigation issues that came out of [Sprintly mobile QA](https://www.notion.so/Articles-Searched-for-Banksy-articles-pressed-into-multiple-ones-and-some-are-not-displayed-more--b83bbeb6065d44319790c2faaa160f49).
Screenshots below, video on the comments 
iOS 
|withSafeArea||
|---|---|
|native|webview|
|<img width="444" alt="Screenshot 2023-07-10 at 17 59 54" src="https://github.com/artsy/eigen/assets/21178754/b447bb7a-835e-44ab-af4c-3dba141b4383">|<img width="442" alt="Screenshot 2023-07-10 at 17 57 56" src="https://github.com/artsy/eigen/assets/21178754/c32ec771-d060-471a-a5cf-c90fef637607">|
|<img width="452" alt="Screenshot 2023-07-10 at 18 00 14" src="https://github.com/artsy/eigen/assets/21178754/47186391-93f4-48ec-a5be-700171feff6a">|<img width="448" alt="Screenshot …
> fix: native article nav issues

- fastlane/metadata/android/en-US/changelogs/default.txt
- fastlane/metadata/en-US/release_notes.txt
-
-
-
- update release notes for 8.16.0 - mrsltun
</details>
> chore: Update release notes for app submission 8.16.0

- app.json
-
-
-
- Update app version to 8.17.0 - mrsltun
</details>
> chore: Prepare for 8.17.0

- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
- src/app/Components/Artist/RelatedArtistsRail.tests.tsx
- src/app/Components/Artist/RelatedArtistsRail.tsx
- src/app/Components/Artist/RelatedArtistsRailCell.tests.tsx
- src/app/Components/Artist/RelatedArtistsRailCell.tsx
- src/app/utils/mutations/useFollowArtist.ts
- src/app/utils/tests/setupTestWrapper.tsx
This PR resolves [DIA-3] 
- Replace the Related Artists section with the new design in the About tab section
- Small improvement in our setupTestWrapper exposing **mockResolveLastOperation** and **mockRejectLastOperation**
iPhone 14 Pro Max
https://github.com/artsy/eigen/assets/15792853/8e5e1d02-845f-4fa7-8d53-a257d45dc543
iPhone 8
iPad Pro (12.9)
cc @artsy/diamond-devs 
- replace related artists component in the artist about tab - araujobarret
-
-
-
</details>
[DIA-3]: …
> feat(DIA-3): replace related artists section

- scripts/changelog/generateChangelog.ts
This PR updates the generateChangelog script to include PRs with #nochangelog in the generated report
-
-
-
- update generateChangelog to include nochangelog tags - mrsltun
</details>
> fix(FF): Update generateChangelog script to include #nochangelog in the report

- src/app/Components/Bidding/Components/BidInfoRow.tsx
- src/app/Scenes/Partner/Components/PartnerFollowButton.tsx
- src/app/Scenes/Partner/Components/PartnerHeader.tsx
- src/app/Scenes/Partner/Components/PartnerLocationSection.tsx
- src/app/Scenes/Partner/Partner.tsx
This PR resolves [ONYX-51] 
| iOS | Skeleton |
| --- | --- |
| ![follow a gallery](https://github.com/artsy/eigen/assets/36167539/23cf5afb-8dfc-48e0-a8e8-4872b519f9e9) | ![Skeleton 1](https://github.com/artsy/eigen/assets/36167539/a3232d0d-ec59-4acc-b702-c912cc330df5) |
- add follow button to a gallery page, some class -> FC refactoring -daria
-
-
-
</details>
[ONYX-51]: https://artsyproduct.atlassian.net/browse/ONYX-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> feat(ONYX-51): add follow button to a gallery page; refactor class to FC

- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/methods/uploadArtwork.ts
This PR comes as a fix for broken my collection artwork upload and silently failing. 
**- Show Alert when the upload is broken**
**- Send the right attribution class**
| Before                                                                              | After                                                                               |
|-------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
| <video src="https://github.com/artsy/eigen/assets/11945712/231bc591-ba40-469f-9c6b-7cb225a0f16c" />  | <video src="https://github.com/artsy/eigen/assets/11945712/976a63f1-88fb-47f3-bf3d-33524ad644a0" />  |
**- Fix broken android padding**
| Before …
> fix: my collection artwork upload broken

- src/app/utils/hooks/useLocation.ts
This PR increases the location cache maximum age to 10 minutes to avoid unnecessary reloads on the "Shows for You" home screen rail. 
I have noticed that the location gets pre-fetched while scrolling, and this shouldn't be necessary so often because we don't need such a high level of accuracy.
-
-
-
-
</details>
> fix: Increase location cache max age to 10 minutes

- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/StickyBottomContent.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useSaveArtworkListsChanges.ts
This PR resolves [ONYX-124]
Do not auto-persist pending changes on artwork lists sheet dismissal.
https://github.com/artsy/eigen/assets/3934579/e77fbe61-f471-4fb0-a02c-9af0074bf5da
- Do not auto-persist pending changes on artwork lists sheet dismissal - Nikita
-
-
-
</details>
[ONYX-124]: https://artsyproduct.atlassian.net/browse/ONYX-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-124): Do not auto-persist pending changes on artwork lists sheet dismissal

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Components/TabsFlatlist.tsx
This PR resolves [DIA-63] 
This PR fixes the broken infinite scroll artwork grid in android.
https://github.com/artsy/eigen/assets/21178754/14475d80-aabd-41ff-bb7a-fdfe92f854b7
-
-
- broken infinite scroll artist artwork grid
-
</details>
[DIA-63]: https://artsyproduct.atlassian.net/browse/DIA-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: broken infinite scroll artist artwork grid

- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tests.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tsx
This PR resolves [DIA-4] 
This PR adds the related genes section in a Horizontal ScrollView, usually Flatlist is preferrable but the way the design is implemented it's not possible to achieve with it.
https://github.com/artsy/eigen/assets/15792853/9880e770-b336-46e8-93c5-b58c93d34826
iPad
cc @artsy/diamond-devs 
- add related genes section to the Artist about tab - araujobarret
-
-
-
</details>
[DIA-4]: https://artsyproduct.atlassian.net/browse/DIA-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> feat(DIA-4): add related genes to artist about tab

- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Components/ArtworkLists/types.ts
- src/app/Components/ArtworkLists/useArtworkListsToast.ts
- src/app/Components/Toast/ToastComponent.tsx
- src/app/Components/Toast/types.ts
- src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
This PR resolves [ONYX-123]
This PR repositions the toast to the bottom of the screen and adds support for dynamic positioning of the toast.
| 1 Toast shown                                                                                       | Mutliple toasts                                                                                                                                       |
|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| <Video src="https://github.com/artsy/eigen/assets/11945712/1abbbe14-807b-453a-a0af-cee42b07ab78" /> | ![Simulator Screenshot - iPhone 14 Pro - …
> feat(ONYX-123): Reposition default toast position to bottom position

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
- src/app/store/config/features.ts
This PR adds a Collected Artists Onboarding feature flag. This will allow disabling the onboarding until the work is finished.
-
-
-
- Collected Artists Onboarding feature flag - ole
</details>
> chore: Collected Artists Onboarding feature flag

- android/gradle.properties
This PR resolves [PHIRE-106] 
This PR resolves the following sentry issues:
- [First (after hermes)](https://artsynet.sentry.io/issues/4225202213/?environment=production&project=5867225&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=0) 
- [Second (pre-hermes)](https://artsynet.sentry.io/issues/3570220768/?environment=production&project=5867225&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=8)
Both are basically the same issue: `database or disk is full (code 13 SQLITE_FULL[13])`
The reason for that is that [@react-native-async-storage/async-storage](https://react-native-async-storage.github.io/async-storage/docs/advanced/db_size/#increase-limit) lib has a different implementation between the two platforms.
On iOS …
> fix: increase default storage capacity of async storage on Android

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistGridItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tests.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tests.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
- src/app/Scenes/MyCollection/State/MyCollectionTabsStore.tsx
This PR resolves [ONYX-155] 
This PR updates the collected artist rail and view to use `userInterestsConnection` instead of the deprecated `collectedArtistsConnection`. It also removes the artwork count in the list view.
- Use userInterestsConnection in collected artist rail and view - ole
-
-
-
</details>
[ONYX-155]: https://artsyproduct.atlassian.net/browse/ONYX-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Use userInterestsConnection in collected artist rail and view

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tests.tsx
Rename mockCollectedArtist to mockUserInterest in MyCollectionCollectedArtistsView.tests.tsx.
-
-
-
-
</details>
> chore: Rename mockCollectedArtist to mockUserInterest in MyCollectionCollectedArtistsView.tests.tsx

- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
- src/app/store/config/features.ts
This PR renames the `AREnableArtworkLists` to `AREnableArtworksLists`. Since `AREnableArtworkLists` was already marked as ready for release, we can't release the new updates without releasing the old code. I simply renamed it here and kept the old flag in Echo to make sure it's there when it's requested by old clients
Blocked by https://github.com/artsy/echo/pull/499 (the build will succeed once this is merged and deployed)
-
-
-
- rename AREnableArtworksLists ff - mounir
</details>
> chore: add AREnableArtworksLists ff

- src/app/Components/Artist/Articles/Articles.tsx
- src/app/Components/Artist/Biography.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
This PR adjusts some inconsistency around each section "View All" and adds `...` to the Read More truncated text.
@artsy/diamond-devs 
- styles changes in Artist About sections - araujobarret
-
-
-
</details>
> feat(ArtistAbout): fix styling in some links and read more on bio

- package.json
- src/app/Components/ArtistListItem.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tests.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
- yarn.lock
This PR resolves [ONYX-29] 
- add privacy icon to the artists list in MyC -daria
-
-
-
</details>
[ONYX-29]: https://artsyproduct.atlassian.net/browse/ONYX-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ONYX-29): add privacy icon to the artists list in MyC

- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
- Resolves [this bug](https://www.notion.so/artsy/Tappable-area-not-consistent-with-other-components-it-s-only-tappable-on-image-should-also-be-tex-1a0e4b623d2e400fa7b8772b28a06d7f?pvs=4)
The tappable area of the partner list item is not consistent with other components (it’s only tappable on image - should also be text).
-
-
-
-
</details>
> fix: Make text clickable in partner list item

- src/app/Scenes/Home/Components/HeroUnitsRail.tsx
This PR resolves [DIA-67] 
Looks like `Image` by default performs a resize in Gemini impacting the quality(check screenshots), the image becomes very blurry. This PR avoids the resize and improves the quality of the `HeroUnitsRail`.
|  **Before**  | **After**   |
|---|---|
|<img src="https://github.com/artsy/eigen/assets/15792853/deac7724-9acf-4b1b-9c1d-5bcdad039b79" width="320" /> | <img src="https://github.com/artsy/eigen/assets/15792853/b7aff953-5b0a-4203-95a6-ed6dfc0aed74" width="320" /> |
- improve hero rails image quality - araujobarret
-
-
-
</details> …
> fix(DIA-67): do not perform image resize in HeroRails

- src/app/Scenes/MyCollection/MyCollection.tsx
This PR resolves [ONYX-164] 
Fix loading skeleton for my collection tab when the ff is enabled
| grid view | list view |
| --- | --- |
| https://github.com/artsy/eigen/assets/36167539/91869f22-5c1e-48b2-85a9-9c1373a7b7bc | https://github.com/artsy/eigen/assets/36167539/8d481092-73f9-4a11-b3e8-b2b30ebe390d |
- fix loading skeleton for my collection tab when the ff is enabled -daria
-
-
-
</details>
[ONYX-164]: https://artsyproduct.atlassian.net/browse/ONYX-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
> fix(ONYX-164): fix loading skeleton for my collection tab when the ff is enabled

- src/app/Scenes/MyCollection/Components/MyCollectionArtistFiltersStickyTab.tsx
This PR resolves [ONYX-166] 
Make the search bar on my collection full screen when the user selected Artists pill
| --- | --- |
| ![simulator_screenshot_70AEA12A-064B-4A99-821E-F76DC53B2CFD](https://github.com/artsy/eigen/assets/36167539/9fe1eca2-de51-4e12-bfd5-5dbcf4006ff3) | ![simulator_screenshot_1B0A3910-8BD5-4F18-9BF9-CD050FC0B7C6](https://github.com/artsy/eigen/assets/36167539/15e0ab86-25b0-4684-a400-70e02a6a40c7) |
- make the search bar on my collection full screen when the user selected Artists pill -daria
-
-
-
</details> …
> fix(ONYX-166): Make the search bar on my collection full screen | Artist pill

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
This PR resolves [ONYX-168] 
Add privacy icon to the artist preview bottom sheet
- add privacy icon to the artist preview bottom sheet -daria
-
-
-
</details>
[ONYX-168]: https://artsyproduct.atlassian.net/browse/ONYX-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ONYX-168): add privacy icon to the artist preview bottom sheet

- android/gradle.properties
Reverts android flipper version bump that was making android build fail locally
#noChangelog
> chore: revert flipper android version bump

- src/app/Scenes/Home/Components/GalleriesForYouBanner.tsx
- [Context](https://www.notion.so/artsy/Should-be-a-gradient-on-top-of-the-image-4463d5e9991943beab32b160b2e58508?pvs=4)
Add gradient to "Galleries for You" home screen banner.
- add gradient to galleries for you banner - Ole
-
-
-
</details>
> fix: Add gradient to Galleries for You banner

- src/app/Scenes/Home/Components/ShowsRail.tsx
Add home screen Shows rail header tracking.
-
-
-
-
</details>
> fix: Add home screen Shows rail header tracking

- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
- src/app/store/config/features.ts
Partner list item initial placement.
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-07-27 at 15 16 31](https://github.com/artsy/eigen/assets/4691889/79117861-5020-440e-9917-27f4898648cd) |![Simulator Screen Shot - iPhone 14 Pro - 2023-07-27 at 15 16 48](https://github.com/artsy/eigen/assets/4691889/acc3a551-81f4-44fd-abbd-e176a8a0cf2d) |
-
-
-
-
</details>
> fix: Partner list item initial placement

- src/app/AppRegistry.tsx
- src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
- src/app/Components/Bidding/Screens/Registration.tsx
- src/app/Scenes/About/About.tests.tsx
- src/app/Scenes/About/About.tsx
- src/app/Scenes/Artwork/Components/ArtworkDetails.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
- src/app/Scenes/Artwork/Components/ArtworkLotDetails/ArtworkLotDetails.tsx
- src/app/Scenes/Artwork/Components/AuctionPrice.tsx
- src/app/Scenes/Artwork/Components/CertificateAuthenticity.tsx
- src/app/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tests.tsx
- src/app/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
- src/app/Scenes/ArtworkMedium/ArtworkMedium.tsx
- src/app/Scenes/AuctionBuyersPremium/AuctionBuyersPremium.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
- src/app/Scenes/PrivacyRequest/PrivacyRequest.tests.tsx
- src/app/Scenes/PrivacyRequest/PrivacyRequest.tsx
- src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
- src/app/routes.ts
- src/app/system/navigation/routes.tests.ts
This PR resolves [PHIRE-116] 
Removes unwanted insets from some modal surfaces and webviews and more specifically:
- Buyers premium inside sale artwork screen
- Auction FAQ inside sale artwork screen
- Conditions of sale - sale artwork screen
- Medium modal inside artwork screen
- Certificate of Authenticity artwork screen
- artwork classifications artwork screen
webviews like:
`profile > Settings > about`
- Conditions of sale 
- terms 
- privacy 
|------|------|
|![mediumb4](https://github.com/artsy/eigen/assets/21178754/e65e7aee-d345-46d5-85a9-a4f48bcb7a2b)|![medium](https://github.com/artsy/eigen/assets/21178754/fbdf7889-682a-4513-9c13-331bbe164554)|
|![coa-before](https://github.com/artsy/eigen/assets/21178754/5f8b756f-ca65-4f95-ba03-dd6e16bd00b4)|![coa](https://gith …
> fix(modals): remove extra insets in some surfaces

- src/app/store/config/features.ts
Enable AREnableShowsForYouLocation feature flag.
-
-
-
-
</details>
> chore: Enable AREnableShowsForYouLocation feature flag

- ios/Podfile.lock
- package.json
- yarn.lock
- Removes `@react-native-camera-roll/camera-roll` unused dependency.
- Also adds a comment on a react-native-dev-menu-android that is used but looks like it is not.
Used https://github.com/depcheck/depcheck to find unused packages by running `yarn global add depcheck && npx depcheck`and the output was something like this:
```sh
* @react-native-community/cameraroll
* @sentry/cli
* deprecated-react-native-prop-types
* events
* grapheme-splitter
* jsc-android
* react-native-dev-menu-android
* tsutils
* url
```
Didn't proceed with the rest because some of them are used for other purposes like:
- `@sentry/cli` - used in fastlane setup
- `deprecated-react-native-prop-types` - used for some patches for react native and deprecated deps
- `events` - used from navigation (maybe …
> build(deps): remove @react-native-camera-roll/camera-roll

- package.json
- yarn.lock
build(deps): bump @testing-library/react-native from 12.1.2 to 12.1.3
-
-
-
- bump @testing-library/react-native from 12.1.2 to 12.1.3 - gkartalis
</details>
> build(deps): bump @testing-library/react-native from 12.1.2 to 12.1.3

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
Fixes https://www.notion.so/artsy/It-s-possible-to-follow-a-personal-artist-I-don-t-think-that-makes-sense-e67d62c977114cdbb22477e1519459fd?pvs=4
Don't show the follow button for personal collected artists.
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-07-28 at 11 55 34](https://github.com/artsy/eigen/assets/4691889/9f294ddc-98d4-4fd5-8a58-2c0619a82685) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-07-28 at 11 54 21](https://github.com/artsy/eigen/assets/4691889/9e92438f-63d9-4677-8e92-624852adf028)|
-
-
-
-
</details> …
> fix: Dont show follow button for personal collected artists

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tsx
Fixes https://www.notion.so/artsy/Bottom-sheet-doesn-t-close-after-adding-artists-64f93e8cf0a64ab9942c1d42feaa2758?pvs=4
Close My Collection Bottom Sheet when tapping option.
-
-
-
-
</details>
> fix: Close My Collection Bottom Sheet when tapping option

- src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
This PR resolves [ONYX-185] 
This PR improves the loading logic when a user is adding artists to their collection.
- User dark modal spinner as we do for other surfaces
- Show green toast of success because the query is so fast 😄 (good problem to have)
https://github.com/artsy/eigen/assets/11945712/184add1b-b10e-49e2-b1d3-1a32e523639b
- improve loading behaviour add artists you collect - mounir
-
-
-
</details>
[ONYX-185]: https://artsyproduct.atlassian.net/browse/ONYX-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> chore: improve loading behaviour add artists you collect

- package.json
- yarn.lock
> Revert "chore(deps): update dep @artsy/palette-mobile from 11.2.10 to v11.2.11"

- src/app/Components/Pill/Pill.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
- src/app/Scenes/Search/SearchPills.tsx
This PR deprecates Pill implementation in Eigen and updates in 3 screens with the new `Pill` from Palette.
VIsual Changes:
- Saved Alert screen has no difference
- Create Alert screen has a difference, the border is lighter according to the DS when the element is not `disabled`
- Search Pills screen has a difference, the border is lighter according to the DS
| Before | After    |
| -------| -------|
|<video src="https://github.com/artsy/eigen/assets/15792853/6f7590fc-00d3-41f6-bf58-ce13de0b88d7"  />|              <video src="https://github.com/artsy/eigen/assets/15792853/28687fc6-d276-42c5-843e-b53ad876654a" />|
| <img src="https://github.com/artsy/eigen/assets/15792853/af1be672-4ef3-4fe5-96ca-aa7eeb296a22" /> | <img src="https://github.com/artsy/eigen/assets/15792853/6c7f301b-f109-4859-81 …
> refactor(Pill): deprecate Pill and use element from Palette

- src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
This PR resolves [ONYX-191] 
Fix padding in add artists you collect
#nochangelog
[ONYX-191]: https://artsyproduct.atlassian.net/browse/ONYX-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-191): padding in add artists you collect

- src/app/Scenes/MyCollection/MyCollection.tsx
- src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
This PR resolves [ONYX-182] 
https://github.com/artsy/eigen/assets/11945712/25cddd72-41dc-4e1b-8c5a-9abdfa2f0f68
- fix my collection filtering pills animation transition on android - mounir
-
-
-
</details>
[ONYX-182]: https://artsyproduct.atlassian.net/browse/ONYX-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-182): My collection pills animation transition on android

- .secrets.baseline
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
- src/app/Scenes/MyCollection/Screens/Insights/SelectArtist.tests.tsx
- src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx
- src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx
- src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
- src/app/Scenes/MyCollection/utils/filterArtistsByKeyword.ts
- src/app/store/config/features.ts
- src/app/utils/normalizeText.ts
This PR resolves [ONYX-142] 
Use `userinterestsConnection` instead of `collectedArtistsConnection` to make sure to include all artists the user collects (they are now represented by user interests).
-
-
-
-
</details>
[ONYX-142]: https://artsyproduct.atlassian.net/browse/ONYX-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Use `userinterestsConnection` instead of `collectedArtistsConnection`

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
This PR resolves [ONYX-175] 
When adding new artwork to MyColleciton, on the artwork grid we are showing a button "Go to Add Artwork Details". This button is not reachable and is removed on this PR 
| --- | --- |
| https://github.com/artsy/eigen/assets/36167539/8843880c-c1e3-498e-97cf-962e4fe9e2e4 | https://github.com/artsy/eigen/assets/36167539/d4a6c783-5c9f-4511-871d-0b6b1b3918b5 | 
- remove FooterComponent from the InfiniteScrollArtworksGridContainer -daria
-
-
-
</details>
[ONYX-175]: …
> fix(ONYX-175): remove FooterComponent from the InfiniteScrollArtworksGridContainer

- .secrets.baseline
- patches/react-native-credit-card-input+0.4.1.patch
This is a blocker to upgrade reanimated to v3 here, it's using old breaking changes from v2 that are incompatible to v3(reanimated).
Somebody might ask why removing it in favor of an upgrade, a simple answer, with the upgrade we unblock way better animations over all places rather than keeping this old component style and blocking the upgrade process.
Also, the component library is not maintained anymore, we might consider having something in-house rather than using this component from other places.
I also checked the mentioned [bug](https://utest-dl.s3.amazonaws.com/13083/27879/315960/null/bugAttachment/Bug5071486_1.mp4?AWSAccessKeyId=AKIAJ2UIWMJ2OMC3UCQQ&Expires=1937594726&Signature=IpRsV6PNLAlSDFN9J7A6obYajIU%3D) on Android and iOS to see if I broke something.
Android …
> chore(reanimated): Remove outdated animations from credit-card module patch

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
- src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
This PR resolves [PHIRE-115] 
Makes long press menu previews full width of screen
Fixes display for recently sold artworks
-
- Make long press previews full width, fix display for recently sold artworks - Brian 
-
-
</details>
[PHIRE-115]: https://artsyproduct.atlassian.net/browse/PHIRE-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: make long press menu preview full width

- src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
This PR includes two improvements.
- Higher quality partner images on the "Galleries for You" screen
- Decrease the image/item size for tablets to match other tablet sizes
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-08-01 at 16 36 54](https://github.com/artsy/eigen/assets/4691889/215c8fbc-a3ca-4aaa-a414-bfc0555a97a3) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-08-01 at 16 36 07](https://github.com/artsy/eigen/assets/4691889/757ce2bf-2680-471f-a031-d42807302112)|
- Increase Galleries for You image quality - ole
-
-
-
</details> …
> fix: Increase Galleries for You image quality

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
Adjust "Remove artist" copy to match the [design](https://www.figma.com/file/ARjzNu0OVYVcpeGjRgXkiY/Artists-Collected?type=design&node-id=3-28665&mode=design&t=6cvTJqWFubgirEWw-0).
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-08-01 at 17 00 31](https://github.com/artsy/eigen/assets/4691889/15e46ffb-fe92-4457-bd3e-3025a9a97323)|![Simulator Screen Shot - iPhone 14 Pro - 2023-08-01 at 17 02 08](https://github.com/artsy/eigen/assets/4691889/acb2ca81-1ba8-443f-9490-f362c6ca2109)|
Design:
-
-
-
-
</details> …
> fix: Adjust "Remove artist" copy

- ios/Podfile.lock
- package.json
- src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
- src/setupJest.tsx
- yarn.lock
This PR resolves [PHIRE-125] 
Upgrades reanimated in eigen + [palette](https://github.com/artsy/palette-mobile/pull/125) 
waiting first for the [palette PR ](https://github.com/artsy/palette-mobile/pull/125) to get merged to update the version here
⚠️ We will first trigger a beta from this PR and test it out and then merge to avoid reanimated crashes that we had in previous attempts
-
-
-
- build(deps): bump react-native-reanimated from 2.13 to 3.3.0 - gkartalis
</details>
[PHIRE-125]: …
> build(deps): bump react-native-reanimated from 2.13 to 3.3.0

- src/app/Scenes/MyCollection/mutations/createArtist.ts
- src/app/Scenes/MyCollection/mutations/createUserInterests.ts
- src/app/Scenes/MyCollection/mutations/updateUserInterest.ts
Type my collection mutations correctly.
-
-
-
-
</details>
> chore: Type my collection mutations correctly

- src/app/Components/ArtistListItem.tsx
This PR resolves [ONYX-186] 
Artist list item meta text.
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-08-02 at 13 48 22](https://github.com/artsy/eigen/assets/4691889/dbefcc28-89f2-4038-843a-4a51f3d61709) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-08-02 at 13 48 37](https://github.com/artsy/eigen/assets/4691889/91fdd54f-a646-438b-9ed1-51cc17f56823) |
- Fix Collected artists list item meta text padding - ole
-
-
-
</details>
[ONYX-186]: …
> fix: Artist list item meta text

- scripts/flip-table
When switching between branches due to reanimated had to clean all the caches and realized that `cleanBuildCache` breaks the script because:
```sh
FAILURE: Build failed with an exception.
* What went wrong:
Task 'cleanBuildCache' not found in root project 'Artsy'.
```
There is no need to do this extra step, `/.gradlew clean` is enough to clean the android build.
-
-
-
- flip_table script fix - gkartalis
</details>
> fix: remove unused android cleanBuildCache flag from flip-table

- src/app/Components/Input/MoneyInput/MoneyInput.tsx
Use the right `textVariant` type in `MoneyInput.tsx`. This was screaming when I tested with the new palette bump that's in the oven.
-
-
-
- small typings adjust in the MoneyInput component - araujobarret
</details>
> chore(palette): small typings adjust for palette newest version

- src/app/store/config/features.ts
This PR resolves [ONYX-193] 
This PR enables the two feature flags `ARShowCollectedArtistOnboarding` and `AREnableMyCollectionCollectedArtists`.
In case we decide not to release the feature in the next app release, we need to make sure to disable both feature flags before the release.
https://github.com/artsy/echo/pull/509 adds the feature flags to Echo
-
-
-
-
</details>
[ONYX-193]: https://artsyproduct.atlassian.net/browse/ONYX-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> chore: Enable ARShowCollectedArtistOnboarding and AREnableMyCollectionCollectedArtists

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
This PR resolves [ONYX-214] 
https://github.com/artsy/eigen/assets/36167539/0c243551-8ad9-4f64-b379-2d2a4a538e99
- add zero state for collected artsits search results -daria
-
-
-
</details>
[ONYX-214]: https://artsyproduct.atlassian.net/browse/ONYX-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ONYX-214): add zero state for collected artsits search results

- src/app/store/config/features.ts
Marks AREnableLongPressOnArtworkCards as readyForRelease 
-
-
-
- mark AREnableLongPressOnArtworkCards as readyForRelease - gkartalis
</details>
> chore: mark AREnableLongPressOnArtworkCards as readyForRelease

- docs/getting_started.md
Add android emulator wifi setup steps 
#noChangelog
> docs: add android emulator wifi section [skip ci]

- android/app/src/debug/java/net/artsy/app/ReactNativeFlipper.java
- docs/debugging.md
- ios/Artsy/App/ARAppDelegate.mm
- ios/Podfile.lock
- package.json
- scripts/build-for-tests-ios
- yarn.lock
Adds flipper performance monitor plugin.
How to install:
Search for `rn-perf-monitor` in the list flipper plugins.
Need to explicitly enable it afterwards under disabled plugins in flipper but looks like this:
-
-
-
- add flipper performance monitor plugin - gkartalis
</details>
> feat: add flipper performance monitor plugin

- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview/ArtistKindPills.tsx
This PR resolves [ONYX-221] 
| Before w/o pills | Before w pills | After w/o pills | After w pills | 
| ![simulator_screenshot_1D6BDD70-B459-48E3-917E-EA9A2E35C1C3](https://github.com/artsy/eigen/assets/36167539/1347eff2-050d-4827-8b1f-95990691edc2) | ![simulator_screenshot_BA431690-F6CB-4E01-A8C6-EF8F6EAF8987](https://github.com/artsy/eigen/assets/36167539/df2bc317-ab40-49d9-af39-55ac2fb201f7) | ![simulator_screenshot_E123C24E-3F5B-4B5F-BD1D-197AFDE454A6](https://github.com/artsy/eigen/assets/36167539/d2a27660-9384-424a-a4d8-5e4a212ef742) | ![simulator_screenshot_CFA07FE1-4CB7-44C4-B231-95D94979C5CF](https://github.com/artsy/eigen/assets/36167539/324b0cc8-b5ff-433b-88af-5d0da3184dbd)
- fix the margin on the artist …
> fix(ONYX-221): fix margin

- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
This PR prevents an unnecessary `requestLocation` query on "Galleries near You" screen. We don't need to request the location if the device's location is available.
-
-
-
- Prevent unnecessary requestLocation query on "Galleries near You" screen - ole
</details>
> fix: Prevent unnecessary requestLocation query on "Galleries near You" screen

- src/app/Scenes/MyCollection/MyCollection.tsx
This PR resolves [ONYX-224] 
Add refreshControl to the MyCollection empty state with artists and artworks
Test 1: opened emulator, opened staging app on the phone, removed artist on the phone, refreshed MyC on the emulator - the list of collected artists updated:
https://github.com/artsy/eigen/assets/36167539/29126d89-e381-42de-aa1f-52b0de56515f
Test 2: opened emulator, opened staging app on the phone, added artwork on the phone, refreshed MyC on the emulator - the list of collected artists and artworks updated:
https://github.com/artsy/eigen/assets/36167539/9ad15fff-efea-4ce4-bab4-0abc92a17b86
- add refreshControl to the MyC empty state -daria
-
-
-
</details>
[app …
> fix(ONYX-224): add refreshControl to the MyC empty state

- fastlane/metadata/android/en-US/changelogs/default.txt
- fastlane/metadata/en-US/release_notes.txt
Release notes 8.18.0
-
-
-
-
</details>
> chore: Release notes 8.18.0

- src/app/Components/ArtworkFilter/Filters/SortOptions.tsx
This PR resolves [ONYX-138] 
| --- | --- |
| https://github.com/artsy/eigen/assets/36167539/723991a9-215c-4e4e-9774-3a50db490979 | https://github.com/artsy/eigen/assets/36167539/bf338026-1f78-4a61-8310-5fad52e7adf0 |
- remove recommended filter from the show page -daria
-
-
-
</details>
[ONYX-138]: https://artsyproduct.atlassian.net/browse/ONYX-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-138): Remove "Recommended" artwork grid sort on show/booth pages

- app.json
-
-
-
- Update app version to 8.19.0 - mrsltun
</details>
> chore: Update app version to 8.19.0

- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkHeader.tsx
Align Save Artwork header text.
| --- | --- |
|![img_5428_720](https://github.com/artsy/eigen/assets/4691889/73266871-a9df-42ca-916d-71b039644c8b) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-08-15 at 14 58 02](https://github.com/artsy/eigen/assets/4691889/b627dade-1fba-47bc-883c-2c4046464010)|
- Align Save Artwork sheet header text - ole
-
-
-
</details>
> fix: Align Save Artwork header text

- .secrets.baseline
- src/app/Scenes/Home/Components/ModalCarouselComponents/ModalCarousel.tests.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tests.tsx
- src/app/Scenes/MyCollection/MyCollection.tests.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
My Collection artwork form test.
-
-
-
-
</details>
> fix: My Collection artwork form test

- src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
This PR makes the "My Collection" Add button clickable again when the tooltip is visible. For some reason, it wasn't clickable. This change moves the tooltip below the button to fix the issue.
- Make My Collection add button clickable with tooltip - ole
-
-
-
</details>
> fix: Make My Collection add button clickable with tooltip

- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
- src/app/utils/refreshHelpers.tsx
Update saved alerts list screen after creating alert.
-
-
-
-
</details>
> fix: Update saved alerts list screen after creating alert

- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
The selected filters (attributes) are not reflected in the "Create Alert" modal. This leads to alerts being saved without additional filters (like `medium`) and only the artist ID.
**Before:**
https://github.com/artsy/eigen/assets/4691889/e934ba85-a431-4416-a718-5f1debddd3d1
**After:**
https://github.com/artsy/eigen/assets/4691889/fed9e7e7-aee6-41b7-87a4-9bcd5090296e
-
-
-
-
</details>
> fix: Update Create Alert modal attributes correctly

- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-251] 
- Add a feature flag, visible in dev menu
- Add a "dummy" auction header alert CTA component
| FF on | FF off |
|---|---|
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-08-21 at 17 10 35](https://github.com/artsy/eigen/assets/3934579/d27292f6-4a34-4a80-9659-01fe8877a1b5) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-08-21 at 17 28 13](https://github.com/artsy/eigen/assets/3934579/e04ab3a3-f9fd-4bec-96ab-9b1606b22c3b) |
-
-
-
- add AREnableAuctionHeaderAlertCTA feature flag - @nickskalkin 
</details>
[docs]: …
> feat(onyx-251): create AREnableAuctionHeaderAlertCTA feature flag

- .secrets.baseline
- src/app/Scenes/MyCollection/MyCollection.tests.tsx
- src/app/system/navigation/navigate.tests.tsx
-
-
-
- add setSelectedTab test + fix MyC broken test - mrsltun
</details>
> fix(tests): Add setSelectedTab test + fix broken test

- ios/Artsy/App/ARAppActivityContinuationDelegate.m
We were redirecting marketing deeplinks on both native side and typescript side causing the double nav. This removes the redirecting from the native side and some old unnecessary code. 
https://github.com/artsy/eigen/assets/49686530/020326fd-2cfe-4026-93a8-e716e5ed7ab9
https://github.com/artsy/eigen/assets/49686530/b5a1fc7f-e196-48c0-bd5e-6ee68dc40df5
-
- Fixes marketing deeplinks navigating slowly + 2x - Brian 
-
-
</details>
> fix: remove double redirect from marketing deeplinks

- fastlane/metadata/android/en-US/changelogs/default.txt
- fastlane/metadata/en-US/release_notes.txt
Update release notes for version 8.19.0
-
-
-
- update release notes - araujobarret
</details>
> chore: update release notes for version 8.19.0

- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
This PR resolves [ONYX-263] 
When a user updates the rarity of an artwork, their changes get saved but it doesn't get reflected in the artwork page. This was happening because we were not querying for the displayed label -> It's what this PR adds
https://github.com/artsy/eigen/assets/11945712/2b9e25ed-106a-42e0-9db6-f139e94b36f1
- Fix non reflected rarity changes in my collection artwork page - mounir
-
-
-
</details>
[ONYX-263]: https://artsyproduct.atlassian.net/browse/ONYX-263?atlOrigin=eyJpIjoiNWRkNTljNzY …
> fix: reflect rarity changes after editing an artwork

- app.json
Bumps the app version to 8.20.0
-
-
-
-
</details>
> chore(version): bump version to 8.20.0

- ios/Podfile.lock
- package.json
- src/app/Components/Lists/AuctionResultListItem.tsx
- src/app/Scenes/AuctionResult/AuctionResult.tsx
- src/app/system/errorReporting/sentrySetup.ts
- src/app/system/navigation/ModalStack.tsx
- src/app/system/navigation/navigate.ts
- yarn.lock
Bumps sentry to v5.9.1 in order to unblock #9189 
- 
-
-
- bump sentry to v5: araujobarret
</details>
> chore(sentry): bump sentry to v5

- src/app/utils/DevMenu.tsx
`Alert.prompt` is an iOS only feature and not supported in Android so refactored slightly to be able to navigate quickly to pages via the dev menu in android as well.
Let me know if you have any better UI ideas but it works on both platforms now 🔥
|Android|iOS|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/ec6eae0c-72c1-49b7-ab99-416e09112868" width="200" />|<video src="https://github.com/artsy/eigen/assets/21178754/c24748bb-b670-4390-bfde-08dfb4f672f7" width="200" />|
-
-
-
- navigate to on dev menu to work on android - gkartalis
</details>
[feature …
> feat: refactor navigate to on dev menu to work on android

- src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
- src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
- src/app/Scenes/Artwork/helpers.ts
- src/app/Scenes/Artwork/utils/hasBiddingEnded.tsx
- src/app/Scenes/Artwork/utils/isLotClosed.tsx
This PR resolves [ONYX-273] 
Hide `Create Alert` CTA in the auction header if FF is enabled and the lot is closed or bidding has ended
|  ended/closed |  not ended/closed |
| --- | --- |
| ![simulator_screenshot_50FE75D7-4F79-4817-B0A5-9E17423ABE47](https://github.com/artsy/eigen/assets/36167539/a6ffdf06-f048-4aa6-a6f6-97fe1edc9440) | ![simulator_screenshot_E6CA9047-E702-4CFB-B31C-030E3370CC3C](https://github.com/artsy/eigen/assets/36167539/90240057-c967-4dad-b547-762b5e230de8) |
- hide Create Alert CTA in the auction header if FF is enabled and the lot is closed or bidding has ended -daria
-
-
-
</details> …
> feat(ONYX-273): hide Create Alert CTA in the auction header

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
**Current**
> Boost your chances of a positive response when you contact a gallery by
> sharing which artists you collect.
**Desired**
> Build relationships with galleries on Artsy by sharing the artists in your
> collection.
This PR resolves [ONYX-288](https://artsyproduct.atlassian.net/browse/ONYX-288)
- copy change for My Collection > Collected Artists onboarding - devon
-
-
-
</details>
[ONYX-288]: https://artsyproduct.atlassian.net/browse/ONYX-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
> feat: copy change for My Collection > Collected Artists onboarding

- src/app/Components/Artist/ArtistHeader.tests.tsx
- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Scenes/Artist/Artist.tsx
This PR resolves [DIA-106] 
Adds the Artist's Cover image to match the new Design of the page.
iPhone
https://github.com/artsy/eigen/assets/15792853/89a071d4-5ff2-44f2-bf5c-9a307364f7d1
iPad
- add artist cover image to the Artist screen - araujobarret
-
-
-
</details>
[DIA-106]: https://artsyproduct.atlassian.net/browse/DIA-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-106): add artist cover image to the artist screen

- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
- src/app/Components/Artist/ArtistAbout/ArtistCareerHighlights.tests.tsx
- src/app/Components/Artist/ArtistAbout/ArtistCareerHighlights.tsx
- src/app/Components/Artist/Biography.tsx
- src/app/Components/Expandable.tsx
This PR resolves [DIA-114] 
Adds Highlights and Achievements section. Some logic was copied from Force to keep 1:1 behavior consistent among the 2 platforms.
iPhone 14 Pro Max
https://github.com/artsy/eigen/assets/15792853/f31ecd8e-b35e-4f4f-9a1f-57d23438182d
iPad
- add highlights and achievements to artist about tab - araujobarret
-
-
-
</details>
[DIA-114]: https://artsyproduct.atlassian.net/browse/DIA-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-114): add highlights and achievements to artist about tab

- app.json
> chore: prep for 8.21.0

- docs/add_a_visual_clue.md
- docs/add_progressive_onboarding.md
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/StickyBottomContent.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tests.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tests.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
- src/app/Components/ProgressiveOnboarding/useDismissSavedArtwork.tests.tsx
- src/app/Components/ProgressiveOnboarding/useDismissSavedArtwork.ts
- src/app/Components/ProgressiveOnboarding/useDismissSavedHighlight.tests.tsx
- src/app/Components/ProgressiveOnboarding/useDismissSavedHighlight.ts
- src/app/Components/ProgressiveOnboarding/useOnSaveArtwork.ts
- src/app/Scenes/ArtworkLists/ArtworkLists.tsx
- src/app/Scenes/BottomTabs/BottomTabsButton.tsx
- src/app/Scenes/BottomTabs/BottomTabsModel.ts
- src/app/Scenes/Fair/Components/FairArtworks.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
- src/app/store/GlobalStoreModel.ts
- src/app/store/ProgressiveOnboardingModel.ts
- src/app/store/VisualClueModel.ts
- src/app/store/__tests__/migration.tests.ts
- src/app/store/migration.ts
- src/app/system/devTools/DevMenu/DevMenu.tsx
- src/app/utils/ElementInView.tsx
- src/app/utils/hooks/useVisualClue.ts
This PR resolves [DIA-69] 
Adds the progressive onboarding for saved artworks.
Adds a new store model Progressive Onboarding and instructions about how to use it + short intro in `docs/add_progressive_onboarding.md`.
User logged in 
https://github.com/artsy/eigen/assets/15792853/5487679c-6067-470f-b7f4-718adadb6048
User  signing up
https://github.com/artsy/eigen/assets/15792853/c91ce88c-e5a6-4d49-912a-7319161de208
- adds progressive onboarding for saved artworks - araujobarret
-
-
-
</details>
[DIA-69]: …
> feat(DIA-69): add progressive onboarding model for saved artworks

- src/app/Components/Artist/ArtistHeader.tests.tsx
- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Components/Artist/ArtistHeaderNavRight.tsx
- src/app/Components/Artist/useFollowArtist.ts
- src/app/Components/Button/FollowButton.tsx
- src/app/Providers.tsx
- src/app/Scenes/Artist/Artist.tests.tsx
- src/app/Scenes/Artist/Artist.tsx
This PR resolves [DIA-105]
- Uses the scroll offset enhancement from the tabs to hide the follow button when the title is shown in the header
- Small text changes in the artist name, origin
https://github.com/artsy/eigen/assets/15792853/82152727-b2ca-4e3d-976d-731740f5b0e5
Note: there is some flickering with the image, I checked the performance in general but looks more related to the relay after the data update. We can create a follow-up ticket to investigate it further if necessary.
- moves follow button to the Artist header navigation bar - araujobarrert
-
-
-
</details> …
> feat(DIA-105): Move follow button for artist and display count on button

- package.json
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
- yarn.lock
This PR resolves [DIA-126]
The images in the articles are not right scaled/cropped, it ended up having bad quality and cropping big parts of the image.
This PR fixes these issues by scaling it properly.
https://github.com/artsy/eigen/assets/15792853/f3f562b0-3ee1-462c-9382-53d7042b6731
- fix cropped/bad quality images in article screen - araujobarret
-
-
-
</details>
[DIA-126]: https://artsyproduct.atlassian.net/browse/DIA-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> fix(DIA-126): uses the right dimensions for the images in Articles

- src/app/store/config/features.ts
This PR resolves [PHIRE-226] 
mark ARUseNewErrorMiddleware as readyForRelease
#noChangelog
[PHIRE-226]: https://artsyproduct.atlassian.net/browse/PHIRE-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: mark ARUseNewErrorMiddleware as readyForRelease

- src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
This PR resolves [ONYX-303] 
This PR adds manage alerts button when a user did bid on an artwork but lost it. This is because we automatically create alerts when a user loses a bid.
- Add manage alerts button - mounir
-
-
-
</details>
[ONYX-303]: https://artsyproduct.atlassian.net/browse/ONYX-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add manage alerts button

- src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
- src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksExploreMoreButton.tsx
This PR resolves [ONYX-254]
Adds "Explore more" button to the end of Suggested artworks screen. The button leads to an artist's artworks page. Filter should be applied and match pills values.
<video src="https://github.com/artsy/eigen/assets/3934579/3780b15f-509c-415a-a542-30dd9f236b61" width="300px;" />
- Add "See more on Artsy" button to end of Suggested artworks screen - @nickskalkin 
-
-
-
</details>
[ONYX-254]: https://artsyproduct.atlassian.net/browse/ONYX-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
> feat(onyx-254): Add See more on Artsy button to end of Suggested artworks screen

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Scenes/Search/SearchArtworksGrid.tsx
- src/app/utils/masonryHelpers/index.ts
- src/setupJest.tsx
This PR resolves [PHIRE-217] 
⚠️ Nothing changes ui wise ⚠️ 
- replace searchArtworksGrid with MasonryFlashList - gkartalis
-
-
-
</details>
[PHIRE-217]: https://artsyproduct.atlassian.net/browse/PHIRE-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: replace searchArtworksGrid with MasonryFlashList

- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Scenes/Artist/Artist.tsx
That's a temporary fix, the real fix should be in palette-mobile to use the `BelowTitleHeaderComponent` as a ReactNode pattern.
Props to @MounirDhahri to pointing the quick fix super fast 🚀 
- 
-
-
- removes the extra re-render when following artist - araujobarret
</details>
> fix(Artist): useCallback to avoid extra re-renders

- src/app/system/devTools/DevMenu/DevMenu.tsx
Dev menu improvements:
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 14 - 2023-09-15 at 10 56 42](https://github.com/artsy/eigen/assets/21178754/c1b9480f-6e3f-4392-8a65-98ac2b5318c8)|![Simulator Screenshot - iPhone 14 - 2023-09-15 at 10 55 12](https://github.com/artsy/eigen/assets/21178754/2bb42831-806b-4302-b374-0f61c7ea20fb)|
|![simulator_screenshot_08A39CAC-B58D-4A1F-903F-D2F79890F9FA](https://github.com/artsy/eigen/assets/21178754/63e0bc70-c865-46a5-82fb-41c0d13eddb8)|![simulator_screenshot_82790ED7-F0DA-45B6-A8F0-D811C9245087](https://github.com/artsy/eigen/assets/21178754/82191e32-8458-4b47-9311-3523adec5175)|
-
-
-
- improve feedback on async devmenu toggles - gkartalis
</details>
Need help with …
> refactor: feedback on async devmenu toggles

- src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
This PR resolves [ONYX-273](https://artsyproduct.atlassian.net/browse/ONYX-273)
Refactored the check for displaying the Create Alert button in the header.
Added isInAuction to display the button depending if the artwork  in auction or not.
-
-
-
-
</details>
[ONYX-273]: https://artsyproduct.atlassian.net/browse/ONYX-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-273): refactor and add isInAuction for header create alert cta

- src/app/Components/Artist/Articles/Articles.tsx
This PR resolves [DIA-162] 
This PR fixes a misalignment in the section title on the artist screen
- fix misaligned view all button in articles rail - mounir
-
-
-
</details>
[DIA-162]: https://artsyproduct.atlassian.net/browse/DIA-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(DIA-162): misaligned view all button in articles rail

- src/app/Scenes/Activity/ActivityList.tsx
Safer number check in activity list to fix a crash we are seeing:
https://artsynet.sentry.io/issues/4469752934/?project=5867225
Paired in mobile practice!
- fix crash in activity list - mobile practice
-
-
-
</details>
> fix: crash in activity list

- scripts/flip-table
[future-friday (more like tuesday 😄 )] 
After running the `flip-table` script, I noticed that the `dist` folder got deleted and it affected the status of branch. This PR makes sure that we delete what's inside the folder without deleting the folder itself or the `.gitkeep` file.
-
-
-
- Keep dist folder after flipping table - mounir
</details>
> chore: keep dist folder after flip table

- package.json
- yarn.lock
Bumps rntl
-
-
-
- bump @testing-library/react-native from 12.1.3 to 12.3.0 - gkartalis
</details>
> build(deps): bump @testing-library/react-native from 12.1.3 to 12.3.0

- src/app/Scenes/Partner/Components/PartnerFollowButton.tests.tsx
- src/app/Scenes/Partner/Components/PartnerFollowButton.tsx
This PR resolves [DIA-131] 
OOPS
- add partner counts to partner follow button - egdbear
-
-
-
</details>
[DIA-131]: https://artsyproduct.atlassian.net/browse/DIA-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add partner counts to partner follow button

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
Make my collection artists sharing less defensive.
PS: I couldn't reproduce the error in the original ticket [ONYX-366]
- allow artists share modal dismissal - mounir
-
- 
-
</details>
[ONYX-366]: https://artsyproduct.atlassian.net/browse/ONYX-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: make my collection artists privacy modal less defensive

- src/app/Scenes/Artwork/Artwork.tests.tsx
The feature flag being enabled broke artwork tests. Injecting mocked flag fixes. 
-
-
-
- fix broken artwork tests - Brian 
</details>
> fix: disable the feature flag to fix the tests

- src/app/Components/ArticleCard.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/Cards/MediumCard.tsx
- src/app/Scenes/Home/HomeContainer.tsx
- src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
- src/app/Scenes/MyProfile/MyProfileSettings.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
- src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
- src/app/store/config/features.ts
- src/app/utils/queryPrefetching.ts
Removed some stale / unused feature flags, see also [echo PR](https://github.com/artsy/echo/pull/538) that marks ff as deprecated.
Feature flags removed:
-
-
-
- removes stale/unused feature flags - gkartalis
</details>
> refactor(cleanup): removes stale/unused feature flags

- src/app/store/config/features.ts
This PR resolves [ONYX-356]
[Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-356)
[Echo PR](https://github.com/artsy/echo/pull/539)
Add Single Activity Panel screen feature flag.
-
-
-
- add AREnableSingleActivityPanelScreen feature flag - @nickskalkin 
</details>
[ONYX-356]: https://artsyproduct.atlassian.net/browse/ONYX-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(onyx-356): add AREnableSingleActivityPanelScreen feature flag

- src/app/system/devTools/DevMenu/DevMenu.tsx
This PR brings some improvements to the Dev menu screen including:
- Quick red logout button at the top of the screen. The reason behind this addition is that toggling on **Dev Tools** then scrolling all the way down to the end of the screen for a menu that we often use is inconvenient. I kept it there as well in case someone likest to use it that way 🤷 
- Add alert to prompt if you really want to logout
- Hide Log out button if you are not logged in
- Adjust icon sizes to make sure they match (their sizes is really weird and figured out it doesn't make sense to make a palette size upgrade for a dev menu improvement in case it's being used somewhere else)
-
-
-
- minor dev menu improvements - mounir
</details> …
> chore: minor dev menu improvements

- app.json
> chore: prep for 8.22.0

- .secrets.baseline
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
- src/app/store/config/features.ts
Remove AREnableArtworksFromNonArtsyArtists ff.
-
-
-
-
</details>
> chore: Remove AREnableArtworksFromNonArtsyArtists ff

- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
- src/app/store/config/features.ts
Remove AREnableNewRequestPriceEstimateLogic ff.
-
-
-
-
</details>
> chore: Remove AREnableNewRequestPriceEstimateLogic ff

- src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
- src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
- src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
- src/app/Scenes/Inbox/Components/Conversations/PurchaseModal.tests.tsx
- src/app/store/config/features.ts
clean up AREnableConversationalBuyNow feature flag https://github.com/artsy/echo/pull/541
-
-
-
- clean up AREnableConversationalBuyNow - gkartalis
</details>
> refactor(cleanup): clean up AREnableConversationalBuyNow

- package.json
- yarn.lock
bump @gorhom/bottom-sheet from 4.4.5 to 4.5.1
-
-
-
-  bump @gorhom/bottom-sheet from 4.4.5 to 4.5.1 - gkartalis
</details>
> build(deps): bump @gorhom/bottom-sheet from 4.4.5 to 4.5.1

- app.json
- src/app/Scenes/Onboarding/OnboardingWelcome.tsx
- src/app/utils/jsonFiles.ts
This PR resolves [PHIRE-274] 
Replaces reanimated code with Moti to avoid issues like the bug ticket mentioned above.
First Launch iOS:
https://github.com/artsy/eigen/assets/21178754/7db8ad3b-4b00-48fa-87c4-d28c572a2c44
After Logout iOS:
https://github.com/artsy/eigen/assets/21178754/311d67b9-b611-4133-9a52-1f93ba69d3ec
- login/signup buttons do not show up - gkartalis
-
-
-
</details>
[PHIRE-274]: https://artsyproduct.atlassian.net/browse/PHIRE-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> fix: login/signup buttons do not show up

- scripts/codepush/deploy-or-notify.sh
Missing a yarn relay is causing code push deploys to fail. 
-
-
-
- Codepush follow-up - Brian 
</details>
> fix: add relay command to fix deploys

- fastlane/Fastfile
Make our releases not mandatory to avoid the update modal not being dismissible on iOS. 
-
-
-
- make codepush beta releases not mandatory - Brian
</details>
> fix(codepush): make releases not mandatory #trivial

- src/app/Scenes/Home/useHomeModules.ts
Adds enableLatestActivityRail feature flag to useMemo dependency array + a comment for not forgetting to do this in the future 
-
-
-
- add enableLatestActivityRail to useMemo dep array - gkartalis
</details>
> fix: add enableLatestActivityRail to useMemo dep array

- src/app/store/config/features.ts
Reverts artsy/eigen#9321
Some more internal context available [here in Slack](https://artsy.slack.com/archives/C05EQL4R5N0/p1695886204796149?thread_ts=1695831814.075859&cid=C05EQL4R5N0).
- revert: enable AREnableLatestActivityRail
</details>
> revert: enable AREnableLatestActivityRail

- app.json
chore: prep for new version
#nochangelog
> chore: prep for new version

- src/app/store/config/features.ts
Since the artist screen design changed, "# of Artists Alerts set" design didn't appeal to design anymore. We are setting the flag to false here until we get an alternative.
- 
-
-
- make artists alerts set not ready for release - mounir
</details>
> chore: disable artists alerts set

- src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
Since `[artistIDs]` needs to be an array of null values, this was leading to an error in _DEV_ since the value set will be null. I am adding a check to make sure that the value is there.
**I will merge this and create a build to make sure it makes it to the upcoming build**
-
-
-
- fix: make sure the artistID is not null in SavedSearchAlertsList - mounir
</details>
> fix: make sure the artistID is not null in SavedSearchAlertsList

- src/app/Components/SearchInput.tsx
This PR sets the max input size on the search input component to be 100 - this is also the limit that we have from the backend. I believe a more solid approach would be to get the limit from the backend but this would turn this little effort into a significantly bigger one and I don't believe we need that, 100 chars is already BIG!
https://github.com/artsy/eigen/assets/11945712/d183a7f9-4588-4bc2-87fa-badb2f1dd430
https://github.com/artsy/eigen/assets/11945712/3dc85e84-dc16-4083-999a-d2bd754bc10e
- set max input length on search input field - mounir
-
-
-
</details> …
> fix: set max input length on search

- src/app/Components/AutosuggestResults/AutosuggestResults.tests.tsx
- src/app/Components/AutosuggestResults/AutosuggestResults.tsx
- src/app/system/relay/middlewares/errorMiddleware.ts
This PR brings some improvement to the way we handle errors in the search screen inspired by @gkartalis comments on [Slack](https://artsy.slack.com/archives/C05EQL4R5N0/p1695978699044759). This includes:
- Using the new middleware for the search screen - this means that failure in the different rails, won't lead to the search tab failing
- Use better error messages when the search query fails 
- Only show the retry button once to retry the query, the goal behind that is to avoid having the user blocked in infinite cycle of refreshing
https://github.com/artsy/eigen/assets/11945712/6a49dc41-18f9-4b04-b1ed-7d76344bbf41
- better error handling on search screen - george, mounir
-
-
-
</details> …
> chore: better error handling on search screen

- package.json
- src/app/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx
- yarn.lock
[Cohesion PR](https://github.com/artsy/cohesion/pull/463)
Adds `lotsByArtistsYouFollow` pageview tracking on the `Lots By Artists You Follow` screen in the app.
Slack thread for more context -> [here](https://artsy.slack.com/archives/C03NF9TKR/p1695820375843259)
-
-
-
- add tracking on lotsByArtistsYouFollow screen - gkartalis
</details>
> fix: add tracking on lotsByArtistsYouFollow screen

- src/app/Components/Artist/ArtistHeader.tests.tsx
- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Scenes/Artist/Artist.tsx
This PR resolves [DIA-109] 
Adds represented by horizontal list to the Artist screen.
iOS
https://github.com/artsy/eigen/assets/15792853/cb8c422b-f543-44f2-ac2e-303e7193d193
Android
https://github.com/artsy/eigen/assets/15792853/b95dcb64-3c9b-4e3d-b78b-30e0eedff451
- add represented by rails to the artist screen - araujobarret
-
-
-
</details>
[DIA-109]: https://artsyproduct.atlassian.net/browse/DIA-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-109): add represented by section on Artist screen

- src/app/Components/Artist/ArtistAbout/ArtistAboutEmpty.tsx
Fixes alignment of empty state on artist about screen.
[Notion ticket](https://www.notion.so/artsy/Artist-screen-About-tab-Empty-state-is-alignment-is-not-perfect-fcb9c046ec4d4912b0cab5a1fa73cc67?pvs=4) 
|Before|After|
|---|---|
|![Screenshot 2023-10-04 at 12 38 21](https://github.com/artsy/eigen/assets/21178754/7d9397e0-300d-4ae7-b334-57115e618d5a)|![Screenshot_1696415776](https://github.com/artsy/eigen/assets/21178754/8ab52554-36e4-4f79-8d55-d47e8040535e)|
-
-
- artist about empty state alignment - gkartalis
-
</details> …
> fix: artist about empty state alignment

- fastlane/Fastfile
Don't wait on builds to process in App Store Connect, we are spending around 5-8min essentially idle time on macOS machines: https://app.circleci.com/pipelines/github/artsy/eigen/46391/workflows/f278442b-abb1-493e-9747-2c1f61263479/jobs/158182 
See `deploy if beta` job time from upload finished to time job finishes. 
There is a small downside in that builds will not be immediately available after the job completes, although typically should be ready about 5 min after. Recommend the App Store Connect app if devs want notifications on when builds are ready: https://apps.apple.com/us/app/app-store-connect/id1234793120 
-
-
-
- Don't wait until beta finishes processing -  Brian 
</details> …
> build(ci): don't wait for builds to finish processing #trivial

- .circleci/config.yml
- scripts/deploy-beta-android
- scripts/deploy-beta-ios
- use node orb rather than our custom stuff for installing node_modules, get caching automatically, seems like lately there have been lots of cache misses so hopefully this will fix it
- use small node executor rather than macOS for the nightly beta deploy, we are just pushing to a branch in this job so don't need anything special 
-
-
-
- use node orb in ci for installing deps, move nightly to smaller machine - brian 
</details>
> build(ci): use node orb to install deps

- src/app/system/relay/middlewares/errorMiddleware.ts
This PR resolves [PHIRE-308] 
Instant improvement that we get: In case any sale from myBids fails for any reason we don't see unable to load anymore that was the case and we report the error to sentry + datadog, before we were blocking the conversations 🤦‍♂️
-
-
-
- opt in InboxQuery to new error middleware - gkartalis
</details>
[PHIRE-308]: https://artsyproduct.atlassian.net/browse/PHIRE-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: opt in InboxQuery to new error middleware

- src/app/Components/Artist/ArtistHeader.tests.tsx
- src/app/Components/Artist/ArtistHeader.tsx
This PR resolves [DIA-181] 
- add artist representative tracking - araujobarret
-
-
-
</details>
[DIA-181]: https://artsyproduct.atlassian.net/browse/DIA-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-181): add tracking when tapping verified representative

- fastlane/Deliverfile
@gkartalis ran into this issue when promoting the iOS app:
https://github.com/fastlane/fastlane/issues/21544
Removing the key as mentioned in the issue fixes it. 
-
-
-
- fix fastlane delivery - Brian + George 
</details>
> fix: remove third party content key causing upload fails #trivial

- Gemfile.lock
bumps fastlane-plugin-firebase_app_distribution fastlane plugin
#nochangelog
> build(deps): bump fastlane-plugin-firebase_app_distribution

- src/app/Components/Artist/ArtistHeaderNavRight.tsx
- src/app/Scenes/Artist/Artist.tsx
- src/app/system/relay/middlewares/errorMiddleware.ts
This PR resolves [PHIRE-227] 
- Opt-in ArtistAboveTheFold and BelowTheFold queries to new middleware
- Adds `@principalField` directive on artist query
- Removes one `!` 
-
-
-
- opt in artist screen to new error middleware - gkartalis
</details>
[PHIRE-227]: https://artsyproduct.atlassian.net/browse/PHIRE-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: opt in artist screen to new error middleware

- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Some followups for the Artwork page:
- Add `@principalField` to Artwork page after the audit
- defensive code on inquiryModal that was previously breaking the Artwork page
-
-
-
-  unable to load followups on Artwork page - gkartalis
</details>
> refactor: unable to load followups on Artwork page

- src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Removes comment as a followup to https://github.com/artsy/eigen/pull/9386#discussion_r1347843758
#nochangelog
> chore: remove comment #trivial

- src/app/Components/ArtsyWebView.tests.tsx
- src/app/Components/ArtsyWebView.tsx
This PR related to [EMI-1396] 
This PR removes the custom progress bar we have since it doesn't work properly on Android, and the new version of `react-native-webview` package includes a progress bar that works on both platforms
>[!NOTE]
> The progress bar doesn't show up on the first load, which doesn't appear when we go to webview version of articles (check the videos)
| Screen (Platform) | Before | After |
|---|---|---|
| Checkout flow (Android) | <video src="https://github.com/artsy/eigen/assets/20655703/fa7f2fe3-bb21-4800-87f9-43ff84ee2748" /> | <video src="https://github.com/artsy/eigen/assets/20655703/6d9941e8-b81c-496c-8605-f9099592c78f" /> |
| Chekout flow (iOS) | <video src="https://github.com/artsy/eigen/assets/20655703/215463d9-c48b-4ecb-ab4d-cd1f31500b2a" /> | <video …
> fix: Update webview progress bar

- src/app/system/codepush.ts
Don't show the update dialog when in dev mode. That's annoying!
-
-
-
- Don't show codepush update dialog in dev - Brian 
</details>
> fix(codepush): don't show update dialog in dev

- src/app/Components/Artist/Articles/Article.tsx
- src/app/Components/Artist/Articles/Articles.tests.tsx
- src/app/Components/Artist/Articles/Articles.tsx
- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
- src/app/Components/Artist/ArtistShows/ArtistShow.tests.tsx
- src/app/Components/Artist/ArtistShows/ArtistShow.tsx
- src/app/Components/Artist/ArtistShows/VariableSizeShowsList.tests.tsx
- src/app/Components/Artist/ArtistShows/VariableSizeShowsList.tsx
- src/app/Components/Artist/RelatedArtistsRail.tests.tsx
- src/app/Components/Artist/RelatedArtistsRail.tsx
- src/app/Components/Artist/RelatedArtistsRailCell.tests.tsx
- src/app/Components/Artist/RelatedArtistsRailCell.tsx
- src/app/Scenes/ArtistShows/ArtistShows2.tests.tsx
- src/app/Scenes/ArtistShows/ArtistShows2.tsx
- src/app/utils/mutations/useFollowArtist.ts
This PR resolves [DIA-113] 
Investigating the artist screen in Force and comparing it to Eigen we noticed some events we track in Force are not tracked in Eigen, even though we have the mobile events in Cohesion.
This PR adds the missing events, summing up:
- adds `tappedArticleGroup` when tapping an article on the Artist screen
- adds `tappedArticleGroup` when tapping `View All` on the articles section on the Artist screen
- adds `tappedShowGroup` when tapping a show on the Artist screen
- adds `tappedArtistGroup` when tapping a related Artist on the Artist screen
- refactored `Show` to `ArtistShow` and to use relay hooks instead of `createFragmentContainer`
- add some missing events in the Artist screen - araujobarret
-
-
-
</details>
Need …
> feat(DIA-113): add missing track to some areas of artist screen

- docs/testing.md
Updates our testing docs
-
-
-
- updates testing docs - gkartalis
</details>
> docs: testing docs 

- ios/Podfile.lock
- package.json
- yarn.lock
Small bump to `react-native-webview` to latest.
Diff can be found [here](https://github.com/react-native-webview/react-native-webview/compare/v13.6.0...v13.6.2) for the two patch versions but I think it's better to release with the bump to prevent crashes 🔥
-
-
-
- minor bump to react-native-webview - gkartalis
</details>
> build(deps): bump react-native-webview to prevent android crashes

- fastlane/Fastfile
- fastlane/sentry_fastlane.rb
Sends a message to slack after submitting betas for review with a link to the sentry release for monitoring. 
Suggestion from @gkartalis to make monitoring release easier + let people know when builds are submitted for review!
-
-
-
- Add a slack message when submitting betas - Brian, George 
</details>
> build(feat): add a notification when submitting betas with sentry link

- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-346] 
Retire AREnablePriceEstimateRange ff.
-
-
-
-
</details>
[ONYX-346]: https://artsyproduct.atlassian.net/browse/ONYX-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Retire AREnablePriceEstimateRange ff

- src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
This PR brings a fix to the filters modal to make sure that we show the create alert modal on create alert button press.
https://github.com/artsy/eigen/assets/11945712/d04cacf6-6b1c-4013-8c0c-ed7394d69be5
- fix: show create alert on filters create alert press - mounir
-
-
-
</details>
> fix: show create alert on filters create alert press

- .circleci/config.yml
- .github/workflows/release-ios-app.yml
- docs/deploy_to_app_store.md
- scripts/release-ios-app
- scripts/release-ios-app-branch
Reverts artsy/eigen#9400 due to android beta delivery issues. Will re evaluate when Brian is back.
> Revert: "build(ci): workflow review"

- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionArtworkCaption.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionArtworkImage.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionCaption.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionArtworkCaption.tests.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionArtworkImage.tests.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionImageCollectionCaption.tests.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionImageCollectionImage.tests.tsx
This PR resolves [DIA-135] 
When receiving an Artwork type inside of `ArticleSectionImageCollectionFigure`  we were not displaying anything, now we display some captions like we do in Force and enabled navigation to the artwork by pressing on the image too.
This PR is a quick win to be released asap while we take this question to design to be properly worked on.
Before
https://github.com/artsy/eigen/assets/15792853/384e5b85-15a7-4f9e-9d08-7c94ff4dabef 
After
https://github.com/artsy/eigen/assets/15792853/19f2a387-d0d6-402b-8c3d-43fee937f268
- add captions and navigation to artworks inside articles - araujobarret
-
-
-
</details> …
> feat(DIA-135): add captions and navigation on artworks inside articles

- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/ActivityItemScreen.tsx
- src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
This PR resolves [ONYX-447] 
Align activity rail item styling to match activity screen.
**Before**
|![Screenshot 2023-10-13 at 12 18 09](https://github.com/artsy/eigen/assets/4691889/c1b57d7b-9a32-4c7e-ac0d-160450103900) |![Simulator Screen Shot - iPhone 14 Pro - 2023-10-13 at 12 11 39]
-----
**After**
- Align activity rail item styling to match activity screen. - ole
-
-
-
</details>
[ONYX-447]: https://artsyproduct.atlassian.net/browse/ONYX-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> fix: Align activity item styling

- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/Home/useHomeModules.ts
This PR resolves [ONYX-444] 
Home Activity Rail padding.
| --- | --- |
|![Screenshot 2023-10-13 at 12 04 10](https://github.com/artsy/eigen/assets/4691889/f417ab9f-5a54-4f97-878c-d0298e9183bf) | ![Screenshot 2023-10-13 at 12 04 00](https://github.com/artsy/eigen/assets/4691889/6964b2f1-7369-41f9-8779-753bb68d8cc0)|
- Fixed Home Activity Rail padding issue when no notifications are available - ole
-
-
-
</details>
[ONYX-444]: https://artsyproduct.atlassian.net/browse/ONYX-444?atlOrigin=eyJpI …
> fix: Home Activity Rail padding

- fastlane/Fastfile
The `skip_waiting_for_build_processing` param we added to save some time unfortunately breaks distributing to external testers. So we need to wait!
https://docs.fastlane.tools/actions/testflight/#parameters
-
-
-
- Fix distributing to external testers - Brian 
</details>
> build(fix): remove option breaking external distribution

- src/app/Components/PriceRange/PriceRangeContainer.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tsx
- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
This PR resolves [ONYX-372] 
Add price range filter to saved searches
https://github.com/artsy/eigen/assets/11945712/311b1d2e-2fbd-4aeb-9ed6-677093b849d3
- Add price range filter to saved searches - mounir
-
-
-
</details>
[ONYX-372]: https://artsyproduct.atlassian.net/browse/ONYX-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add price range filter to saved searches

- src/app/Scenes/Article/ArticleScreen.tsx
Replace artist -> article in articleScreen tracking
|Before|After|
|---|---|
|![IMG_0747](https://github.com/artsy/eigen/assets/21178754/39ced4a7-35d4-4639-802a-06c6b0836c26)|![IMG_F11908CEE6CD-1](https://github.com/artsy/eigen/assets/21178754/a7d600be-4fa0-4b0b-b2b0-3c8ef6eda425)|
- 
-
-
- replace artist with article ownertype - gkartalis
</details>
> fix: replace artist with article ownertype

- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
This PR resolves [ONYX-450] 
Add "Set Filters" button to the Alerts filters screen.
-
-
-
-
</details>
[ONYX-450]: https://artsyproduct.atlassian.net/browse/ONYX-450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add "Set Filters" button to Alerts filters screen

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
This PR adds ways to buy saved search filter
https://github.com/artsy/eigen/assets/11945712/efcc32ee-de34-4333-8d42-2b665f2c2872
- add ways to buy saved search filter - mounir
-
-
-
</details>
> feat: add ways to buy saved search filter

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tsx
- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
Colour to color.
-
-
-
-
</details>
> fix: Colour to color

- src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx
- src/app/Components/ArtworkFilter/Filters/ColorsSwatch.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tsx
[Slack Thread
](https://artsy.slack.com/archives/C05EQL4R5N0/p1697536649881829?thread_ts=1697536270.413889&cid=C05EQL4R5N0)
Change the color of the color swatch checkmark to white.
| --- | --- |
|![Simulator Screen Shot - iPhone 14 Pro - 2023-10-17 at 12 38 57](https://github.com/artsy/eigen/assets/4691889/c20cc769-b643-4147-b676-494928873aec) |![Simulator Screen Shot - iPhone 14 Pro - 2023-10-17 at 12 37 34](https://github.com/artsy/eigen/assets/4691889/01302a63-725e-40cf-8b13-87bbd8d11309) |
-
-
-
-
</details>
[docs]: …
> fix: Change color of color swatch checkmark to white

- src/app/AppRegistry.tsx
- src/app/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlertContent.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
- src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
This PR resolves [ONYX-452] 
This PR adds logic to allow editing filters in the saved searches context (editing flow). 
https://github.com/artsy/eigen/assets/11945712/93527459-e892-4354-a27d-03b8d2332518
- add filters logic to edited saved searches - mounir
-
-
-
</details>
[ONYX-452]: https://artsyproduct.atlassian.net/browse/ONYX-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ONYX-452): add filters logic to edited saved searches

- src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
[ONYX-455]
This PR fixes an issue where the artist id is getting removed after pressing on the clear all button.
https://github.com/artsy/eigen/assets/11945712/a5bc319b-420b-4b5c-b3e5-3d435d121980
- fix saved searches clear all button logic - mounir
-
-
-
</details>
[ONYX-455]: https://artsyproduct.atlassian.net/browse/ONYX-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: saved searches clear all button logic

- src/app/Components/ArtworkFilter/Filters/AttributionClassOptions.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
- src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
- src/app/Scenes/SavedSearchAlert/pillExtractors.ts
This PR resolves [ONYX-458] 
This PR removes unknown edition as a rarity option
- remove unknown edition as a rarity option for saved searches filtering - mounir
-
-
-
</details>
[ONYX-458]: https://artsyproduct.atlassian.net/browse/ONYX-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-458): remove uknown edition as a rarity option

- fastlane/utility_fastlane.rb
Removes the released flags from the message and tags teams for more visibility.
-
-
-
- Shorten flag message and tag teams - Brian 
</details>
> build(feat): shorten flag message and tag teams

- fastlane/Fastfile
> fix: update typo in promote_beta_android lane

- app.json
> chore: Update app version to 8.25.0

- .circleci/config.yml
Clear out iOS project directory to fix app build failures we were seeing.
-
-
-
- fix failing iOS builds - Brian 
</details>
> build(fix): disable quit early, try clearing project directory

- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
This PR resolves [ONXY-459] 
Allow users to scroll to delete alert button in edit alert flow
- allow users to scroll to delete alert button in edit alert flow - mounir
-
-
-
</details>
> chore: allow scroll to delete alert button

- ios/Podfile.lock
- package.json
- yarn.lock
bump react-native-screens from 3.23.0 to 3.26.0
-
-
-
- bump react-native-screens from 3.23.0 to 3.26.0 - gkartalis
</details>
> build(deps): bump react-native-screens from 3.23.0 to 3.26.0

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tsx
- src/app/utils/artworkMediumCategories.ts
- Rarity: "Unique" or "Limited Edition"
- Medium Type: Surface the same sorted list we use on [/collect][]
- Ways to Buy: Exclude "Contact Gallery"
[/collect]: https://www.artsy.net/collect
- feat: surface a more refined set of filter options for alerts - devon
-
-
-
</details>
> feat: surface a more refined set of filter options for alerts

- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/helpers.ts
This PR resolves [ONYX-461] 
Prompt for push notifications only once.
https://github.com/artsy/eigen/assets/11945712/87c51f24-7586-4712-806b-d8a9cfdb33a6
https://github.com/artsy/eigen/assets/11945712/f2dbf9ca-2cab-448d-bf82-91aa578e5161
- Prompt only once to enable push notifications on saved searches - mounir
-
-
-
</details>
[ONYX-461]: https://artsyproduct.atlassian.net/browse/ONYX-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-461): prompt for push notifications only once

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tsx
This PR resolves [ONYX-462] 
Show all mediums in case one medium is selected
https://github.com/artsy/eigen/assets/11945712/56ae6e4b-32b6-4a2a-aef6-5515c14bc165
- show all mediums in case one medium is selected - mounir
-
-
-
</details>
[ONYX-462]: https://artsyproduct.atlassian.net/browse/ONYX-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: show all mediums in case one medium is selected

- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
Some minor copy updates to the create/edit alert form based on recent Figma specs.
cc/ @MounirDhahri 
- feat(alerts): minor copy updates to create/edit alert form - devon
-
-
-
</details>
> feat(alerts): minor copy updates to create/edit alert form

- package.json
- yarn.lock
Bumps unleash-proxy-client
-
-
-
- Bump unleash-proxy-client - gkartalis
</details>
> build(deps): bump unleash-proxy-client from 2.4.3 to 3.1.0

- src/app/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
another one that has been bothering me for a while:
- fix inquiry toast padding - brian 
-
-
-
</details>
> fix: inquiry message toast padding #trivial

- src/app/Scenes/BottomTabs/BottomTabsButton.tsx
this one has been bothering me for a while :) 
- Fix inbox badge alignment - Brian 
-
-
-
</details>
> fix: specify lineHeight to fix badge alignment #trivial

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlertContent.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
- src/app/store/config/features.ts
This PR resolves [ONYX-434]
Add `details` text input to create/update alert UI
| Create form | Edit form |
|---|---|
| ![Simulator Screenshot - iPhone 15 Pro - 2023-10-24 at 11 52 19](https://github.com/artsy/eigen/assets/3934579/040c9e85-b611-40dc-900b-63a061e4cec6) | ![Simulator Screenshot - iPhone 15 Pro - 2023-10-24 at 11 53 40](https://github.com/artsy/eigen/assets/3934579/681123b1-c6e5-4c5f-b309-6e28cb497c37) |
-  Add 'details' text input to create/update alert UI - @nickskalkin 
-
-
-
</details> …
> feat(onyx-434): Add 'details' text input to create/update alert UI

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-272] 
Cleanup AREnableFallbackToGeneratedAlertNames feature flag related code
-
-
-
- cleanup AREnableFallbackToGeneratedAlertNames feature flag related code -daria
</details>
[ONYX-272]: https://artsyproduct.atlassian.net/browse/ONYX-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-272): cleanup ff related code

- src/app/AppRegistry.tsx
- src/app/Scenes/Article/Components/ArticleBody.tsx
- src/app/Scenes/Article/Components/ArticleSection.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionArtworkCaption.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageSet.tsx
- src/app/Scenes/Article/Components/Sections/ArticleSectionText.tsx
- src/app/Scenes/Article/Components/Sections/__tests__/ArticleSectionImageSet.tests.tsx
- src/app/Scenes/Article/Components/Sections/__tests__/ArticleSectionText.tests.tsx
- src/app/Scenes/Article/Components/__tests__/ArticleBody.tests.tsx
- src/app/Scenes/ArticleSlideShow/ArticleSlideShow.tsx
- src/app/Scenes/ArticleSlideShow/Components/ArticleSlideShow.tsx
- src/app/Scenes/ArticleSlideShow/Components/ArticleSlideShowCaption.tsx
- src/app/Scenes/ArticleSlideShow/Components/ArticleSlideShowImage.tsx
- src/app/Scenes/ArticleSlideShow/Components/__tests__/ArticleSlideShow.tests.tsx
- src/app/Scenes/ArticleSlideShow/Components/__tests__/ArticleSlideShowCaption.tests.tsx
- src/app/Scenes/ArticleSlideShow/Components/__tests__/ArticleSlideShowImage.tests.tsx
- src/app/routes.ts
- src/app/store/config/features.ts
This PR resolves [DIA-134] 
This PR adds the Slideshow route `article/:articleID/slideshow`. It's hidden under a feature flag but we might release it before the next release, we'll host some QA internally on Diamond.
We had no designs for Eigen but we based on the mobile view from Force to replicate it.
iPhone
https://github.com/artsy/eigen/assets/15792853/c20b8c00-98d4-4762-bb73-32676ad8142d
iPad
https://github.com/artsy/eigen/assets/15792853/3dc1ae9b-76bc-467f-b620-47fa05127f83
Android
https://github.com/artsy/eigen/assets/15792853/a41e6083-2edb-47df-9347-dd2a1cb98783
- feat: add article slideshow route and section elements - araujobarret
-
-
-
</details>
[app …
> feat(DIA-134): add article slideshow

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Scenes/Artist/Artist.tsx
- src/app/utils/hardware.ts
This PR resolves [DIA-203] 
Changes on the Artist page:
- Adjust the Artist's image size to a shorter one
- Adjust the font size of the Artist description
- Bring back the Artworks counter to the Artist's Artwork grid
Artist without verified representation
Artist with verified representation
- feat: artist screen changes including image ratio, artwork counter, font spacing, and spaces adjusts - araujobarret
-
-
-
</details>
[DIA-203]: https://artsyproduct.atlassian.net/browse/DIA-203?atlOrigin=eyJpIjoiNWRkNTl …
> feat(DIA-203): adjust Artist header image ratio and minor font and spacing values

- src/app/Components/ArtworkFilter/RecentPriceRanges.tsx
This PR resolves [ONYX-466] 
This filter hides the 0*+ range on recent price ranges because it's the default.
| --- | --- |
|![IMG_A6C3A9592439-1](https://github.com/artsy/eigen/assets/4691889/d7ec2629-de7f-48ef-badd-6904d1ab4fd0) | ![Simulator Screenshot - iPhone 15 Plus - 2023-10-25 at 13 47 18](https://github.com/artsy/eigen/assets/4691889/c5b28c3c-e7ea-421c-8e08-f367160621ad)|
- Hide default price range (0*+) in Create Alert form's Recent Price Ranges section - ole
-
-
-
</details> …
> fix: Hide default price range in Recent price ranges

- src/app/Components/ArtworkRail/ArtworkRail.tsx
This PR resolves [DIA-189] 
We used to show/hide some information from the Rails, but there are some product decisions around consistency and showing the Partner name in all Rails cells, so this PR makes it default.
Even if the decision is final I don't think we need to remove this prop, from time to time someone tries to innovate so 😓 
https://github.com/artsy/eigen/assets/15792853/6b86efd0-fd99-40a5-b4c1-15fa882f2947
- feat: show partner name in all artwork rails - araujobarret
-
-
-
</details>
[DIA-189]: …
> feat(DIA-189): show the Partner name in all rails' cells

- src/app/Components/MenuItem.tsx
Minor fix on the MenuItem component.
Noticed that when the version number is a bit longer it has a line break. Fixed that with `flexGrow={3}`
> [!IMPORTANT]
> IGNORE the `red10` color on the after screenshots! It was only used to demonstrate the changed surface on the after photos.
> Also didn't add before screenshots since nothing changed on those from before and after
|Before|After|
|---|---|
|![IMG_0813](https://github.com/artsy/eigen/assets/21178754/0636c0e6-cf1a-4224-8d17-d6a38cf7fd49)|![IMG_0808](https://github.com/artsy/eigen/assets/21178754/fa6b043a-ffac-464e-8e19-7ef249a9dc15)|
||![IMG_0809](https://github.com/artsy/eigen/assets/21178754/c8a800cf-54d7-4cdd-b952-6f46ce22ec11)| 
||![IMG_0807](https://github.com/artsy/eigen/assets/21178754/437d0cae-a4b6-4d41-9d34 …
> fix: broken app version menu item #trivial

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tsx
This PR resolves [ONYX-473] 
Remove animation from the Pills
Use font weight `bold` instead of `500` 
(**NOTE**: on Android the tittles stay not bold no mater what font-weight we use)
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 Pro Max - 2023-10-25 at 14 47 26](https://github.com/artsy/eigen/assets/36167539/ecf188bd-9f51-4e40-b7ba-9c383bbb88eb) | ![Screenshot_1698238037](https://github.com/artsy/eigen/assets/36167539/78293873-380d-4566-b2a6-cd1c4d926065) |
- UI improvements to the new Create Alert modal -daria
-
-
-
</details> …
> fix(ONYX-473): UI improvements to the new Create Alert modal

- ios/Podfile.lock
- package.json
- yarn.lock
Bumps react-native-shake
-
-
-
- bump react-native-shake from 5.3.2 to 5.5.2 - gkartalis
</details>
> build(deps): bump react-native-shake from 5.3.2 to 5.5.2

- src/app/store/config/features.ts
Enable home screen Activity rail feature flag.
- Enable home screen Activity rail feature flag - ole
-
-
-
</details>
> chore: Enable home screen Activity rail feature flag

- src/app/store/config/features.ts
Show the Article slideshow feature flag in the dev menu.
-
-
-
-
</details>
> chore(feature-flag): show article ff on dev menu

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- ios/Artsy.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- yarn.lock
This PR resolves [PHIRE-363] 
Updates RN to `0.70.14`
More info on what changed can be found here:
https://github.com/facebook/react-native/releases/tag/v0.70.14
- Make Hermes build properly with Xcode 15
- Update Xcode 15 patches to be more robust
- Fix Gemfile to set the max version of Active support to 7.0.8 
-
-
-
- bumps RN to latest patch version 0.70.14 - gkartalis
</details>
[PHIRE-363]: https://artsyproduct.atlassian.net/browse/PHIRE-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> build(deps): bump react-native from 0.70.13 to 0.70.14

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/store/config/features.ts
This PR set the alerts filters as ready for release and hides the size mentions since it's not ready yet.
- set alerts filters as ready for release - mounir
-
-
-
</details>
> chore: set alerts filters as ready for release

- dangerfile.ts
This PR updates the import of `changelogTemplateSections` in danger.ts to 
#nochangelog
> fix: Update changelogTemplateSections import in danger.ts

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
This PR resolves an issue where the size filter is breaking back to line.
#nochanges
> fix: line break when size filter is enabled

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Components/Artist/ArtistHeader.tests.tsx
- src/app/Components/Artist/ArtistHeader.tsx
- src/app/Components/ArtistListItem.tsx
- src/app/Scenes/Artist/Artist.tsx
- src/app/Scenes/Collection/Components/FeaturedArtists.tests.tsx
- src/app/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
This PR addresses one issue when navigating to a Partner with the verified Artist pill, from the Artist screen, would override the graphql property on Relay store `Artist#coverArtwork#image#url` to `undefined`. Thread [here](https://artsy.slack.com/archives/C05EEBNEF71/p1698412082704999).
Other changes:
- refactors the ArtistHeader to use Relay hooks
- ~removes the Artworks counter due to an overlapping bug(no quick fix there)~ fixed in https://github.com/artsy/eigen/pull/9504/commits/1c2bb975efa4915f52452f906767f65e3688c601
https://github.com/artsy/eigen/assets/15792853/e6c83d2f-403f-48c0-9d7d-5e9dd3dce09f
- fix: artist image in the artist screen disappears no more - araujobarret
-
-
-
</details>
Need help with something? Have a look at our …
> fix(ArtistHeader): fix Artist image disappearing

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- ios/Podfile.lock
- package.json
- yarn.lock
Reverts artsy/eigen#9488 till [this issue](https://github.com/facebook/react-native/issues/39944#issuecomment-1785365739) gets resolved.
Will be prob addressed by next release ~ it's already fixed
#nochangelog
> build(deps-REVERT): bump react-native from 0.70.13 to 0.70.14

- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
This PR resolves [ONYX-477] 
Discovered a buggy behaviour during the QA on October 27 ([Notion](https://www.notion.so/artsy/Your-alert-has-been-saved-screen-taping-on-an-artwork-to-save-doesn-t-open-the-artwork-lists-flow--62521f698bda4b9c8da755ead29ad8a8?pvs=4)) 
In the [slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1698669006183059) and Barney on a huddle decided to remove the heart icon from the Artworks grid for now
- remove the heart icon from the Artworks grid on the Alerts Confirmation screen - daria
-
-
-
</details> …
> fix(ONYX-477): add hideSaveIcon to the artworks grid

- src/app/Components/FancyModal/FancyModalHeader.tsx
- src/app/Components/PageWithSimpleHeader.tsx
- src/app/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlertContent.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
https://github.com/artsy/eigen/assets/11945712/2815740f-077b-41e7-96e6-2710a089eadf
- fix keyboard issues on edit alert screen - mounir, nikita
-
-
-
</details>
> fix: keyboard issues on edit alert screen

- src/app/AppRegistry.tsx
- src/app/utils/ArtsyKeyboardAvoidingView.tsx
- src/app/utils/hooks/useIsKeyboardFloating.ts
This PR disables the KeyboardAvoidingView when the keyboard is floating
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/0ddf73d2-8f7e-4fc0-b902-bc9002eaceb7" /> | <video src="https://github.com/artsy/eigen/assets/20655703/2724ec73-0f0e-4217-b49b-2e644aad36e8" /> |
- Disable keyboard avoiding view when keyboard is floating - mrsltun
-
-
-
</details>
> fix: Disable keyboard avoiding view when the keyboard is floating

- android/app/build.gradle
- app.json
> chore: prepare for 8.26.0

- src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
Fix typescript issue after upgrading to relay 16
#nochangelog
> fix: typescript issue on artworks list

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Scroll to artwork grid.
-
-
-
-
</details>
> fix: Scroll to artwork grid

- dangerfile.ts
This PR fixes the issue with danger's changelog message issue where it shows `- undefined (changes)`
-
-
-
- fix danger changelog message generator - mrsltun
</details>
> fix: Update danger change log message generator

- ios/Podfile.lock
- package.json
- yarn.lock
bumps sentry to latest
-
-
-
- bumps sentry to latest - gkartalis
</details>
> build(deps): bumps sentry to latest

- src/app/Components/GenericArtistSeriesRail.tsx
- src/app/Scenes/Home/Components/CollectionsRail.tsx
- src/app/Scenes/Home/Components/FairsRail.tsx
- src/app/Scenes/Home/Components/OldCollectionsRail.tsx
type castings from compact
-
-
-
- type castings from compact - gkartalis
</details>
> fix: type castings from compact

- package.json
- yarn.lock
bumps unleash-proxy-client from 3.1.0 to 3.1.1
-
-
-
-  bumps unleash-proxy-client from 3.1.0 to 3.1.1 - gkartalis
</details>
> build(deps): bumps unleash-proxy-client from 3.1.0 to 3.1.1

- src/app/Components/PriceRange/PriceRangeContainer.tsx
This PR resolves [ONYX-511] 
| Price Range screen | Create Alert modal |
| --- | --- | 
| ![simulator_screenshot_04036317-704B-4389-A320-3C6CDCFA644E](https://github.com/artsy/eigen/assets/36167539/8cf6d931-feb1-4a52-b67d-6b9b18993e74) | ![simulator_screenshot_10BE2C0F-677B-4737-8486-226C816388C1](https://github.com/artsy/eigen/assets/36167539/1b7fe3ad-15c4-4337-b861-563f8f67752f) |
- Move custom min/max inputs of Price Range filter below slider - daria
-
-
-
</details>
[ONYX-511]: …
> feat(ONYX-511): move custom inputs below

- ios/Artsy.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- ios/Artsy.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/Podfile.lock
- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
This PR resolves [ONYX-521)](https://artsyproduct.atlassian.net/browse/ONYX-521) 
Current: Price Range > Rarity > Medium
Desired: Medium > Rarity > Price Range
| ![Simulator Screenshot - iPhone 15 - 2023-11-09 at 19 45 23](https://github.com/artsy/eigen/assets/123595/ed6177de-43f4-4a3c-8518-c6fe5a11770e) | ![Simulator Screenshot - iPhone 15 - 2023-11-09 at 19 42 52](https://github.com/artsy/eigen/assets/123595/ff994188-155e-4040-ad74-5703a617fd92) |
- feat: reorder alert filters — devon
-
-
-
</details> …
> feat: reorder alert filters 

- docs/deploy_a_hotfix.md
- scripts/codepush/apply-fix.sh
- scripts/codepush/calculate-native-hash.sh
Adds an apply_fix script and updates the docs based on @damassi suggestion!
-
-
-
- update hotfix docs and add apply fix script - Brian 
</details>
> docs(codepush): add apply fix script

- src/app/Scenes/Activity/Activity.tsx
This PR resolves [ONYX-486](https://artsyproduct.atlassian.net/browse/ONYX-486) 
Wire up screen tracking for the activity panel.
| Recording |
|--------|
| <video src="https://github.com/artsy/eigen/assets/123595/6166140b-a796-408e-897d-3a7e787cda8c" /> | 
-
-
-
- chore(analytics): add screen tracking for activity panel — devon
</details>
cc/ @gkartalis — thanks for the recent example [here](https://github.com/artsy/eigen/pull/9360)!
[ONYX-486]: https://artsyproduct.atlassian.net/browse/ONYX-486?atlOrigin=eyJ …
> chore(analytics): add screen tracking for activity panel

- src/app/Components/ArtworkFilter/RecentPriceRanges.tsx
This PR resolves [ONYX-510](https://artsyproduct.atlassian.net/browse/ONYX-510) 
Aligns the pill design with other filter pills used in the alert flow.
| ![Simulator Screenshot - iPhone 15 - 2023-11-10 at 16 28 43](https://github.com/artsy/eigen/assets/123595/cad51945-bc13-4aaa-acf3-a9fb122a4645) | ![Simulator Screenshot - iPhone 15 - 2023-11-10 at 16 28 27](https://github.com/artsy/eigen/assets/123595/ddab3276-fd3c-440d-941b-e20b687b07b2) |
| ![Simulator Screenshot - iPhone 15 - 2023-11-10 at 16 28 47](https://github.com/artsy/eigen/assets/123595/492358d9-3db2-405c-8f0e-0861658cd2ec) | ![Simulator Screenshot - iPhone 15 - 2023-11-10 at 16 28 34](https://github.com/artsy/eigen/assets/123595/ca86ab3d-09e1-450d-94ae-29ef6340c392) | …
> feat: use Palette Pill implementation for recent price ranges 

- scripts/ci/build-for-tests-android
Noticed this was failing in main: https://app.circleci.com/pipelines/github/artsy/eigen/48062/workflows/bfed15d0-18f0-4f44-836f-5428304d31ac
-
-
-
- fix android test build - Brian 
</details>
> fix(ci): update path when using yarn in android

- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
This PR resolves [ONYX-532] 
Same idea as https://github.com/artsy/force/pull/13150 — needs an explicit request for `artistSeriesIDs` because of stitching.
|Before|After|
|---|---|
|![b4](https://github.com/artsy/eigen/assets/140521/b40cdfaf-aff9-4441-8b6a-3405ab6eba97)|![a4](https://github.com/artsy/eigen/assets/140521/0bca012c-0fe6-4210-a44d-ee375c5b4ef1)|
-
-
-
- Fix stitched request for artist series criteria in alerts management
</details>
[ONYX-532]: …
> fix(alerts): ensure artist series in previews/pills when managing alerts

- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
- src/app/Scenes/SavedSearchAlert/helpers.ts
- src/app/store/config/features.ts
- src/app/utils/tests/setupTestWrapper.tsx
This PR resolves [ONYX-517] 
https://github.com/artsy/eigen/assets/11945712/8e1c33b5-2546-4943-80d5-08224b4c702a
https://github.com/artsy/eigen/assets/11945712/58e41535-78cf-4da4-99e0-6caab1168b93
- add suggested filters to saved searches - mounir
-
-
-
</details>
[ONYX-517]: https://artsyproduct.atlassian.net/browse/ONYX-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add suggested filters to saved searches

- src/app/store/config/features.ts
- src/app/system/relay/middlewares/errorMiddleware.ts
This PR resolves [PHIRE-466] 
- Adds a new ff `ARUsePrincipalFieldErrorHandlerMiddleware` to be able to enable the new middleware for all the queries in the app and utilize it.
- Removes the old ff `ARUseNewErrorMiddleware` since it's been out for some months now and it is stable enough
- add ff to enable new relay middleware for all queries - gkartalis
-
-
-
</details>
[PHIRE-466]: https://artsyproduct.atlassian.net/browse/PHIRE-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> feat: add ff to enable new relay middleware for all queries

- app.json
Updates app version to 8.27.0
#nochangelog
> chore: Update app version to 8.27.0

- src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
This PR fixes [this sentry](https://artsynet.sentry.io/issues/4279046405/events/5fee9b79caac4cd7b19264c7382cb1eb/) deepZoom type error crash that doesn't have huge impact but why not 😅
-
-
-
- deepzoom crash type error - gkartalis
</details>
> fix: deepzoom crash type error

- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
This PR resolves [ONYX-509] 
- [Slack Thread with discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1700668472790669)
Add title to Clear Filters alert on Alert Filter screen.
- Add title to "Clear Filters" alert on Alert Filter screen - ole
-
-
-
</details>
[ONYX-509]: https://artsyproduct.atlassian.net/browse/ONYX-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add title to "Clear Filters" alert on Alert Filter screen

- package.json
- yarn.lock
This PR updates palette-mobile version to the latest one
-
-
-
-
</details>
> chore: update palette-mobile version

- src/app/Scenes/Search/Search.tsx
This PR adds common app behavior and focuses on the search input (and opens the keyboard) when double-tapping the bottom navigation search item.
https://github.com/artsy/eigen/assets/4691889/5a487207-3932-421e-9dcb-c42f26db8df0
- Focus search input when double-tapping bottom navigation Search item - ole
-
-
-
</details>
> feat: Focus search input when double-tapping bottom navigation Search item

- .eslintrc.js
- src/app/utils/queryPrefetching.ts
This PR comes inspired by @damassi https://github.com/artsy/force/pull/13182.
When migrating to relay 16, I needed to update all imports to come from `relay-runtime` already. 
-
-
-
- disable graphql relay runtime import
</details>
> chore: disable graphql relay runtime import

- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkLists.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtwork.tsx
- src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkHeader.tsx
This PR resolves [ONYX-121] 
Sort artwork lists by updated at desc.
- Note: Because we use the fetch policy 'network-only', the data is refreshed every time the modal opens.
- Sort artwork lists by updated at desc. - ole
-
-
-
</details>
[ONYX-121]: https://artsyproduct.atlassian.net/browse/ONYX-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Sort artwork lists by updated at desc

- .circleci/config.yml
- ios/Podfile.lock
- package.json
- yarn.lock
This PR resolves [PHIRE-435] 
Bumps sentry to latest - triggering beta to see if sourcemaps work correctly
-
-
-
-  bump @sentry/react-native from 5.9.1 to 5.14.1 - gkartalis
</details>
[PHIRE-435]: https://artsyproduct.atlassian.net/browse/PHIRE-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build(deps): bump @sentry/react-native from 5.9.1 to 5.14.1

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
- [Slack Thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1701210561396369)
Fixing the Alert form keyboard glitch in the create & edit alert flow by moving the `ArtsyKeyboardAvoidingView` container.
https://github.com/artsy/eigen/assets/4691889/2a3d9390-67b9-445f-a51a-f3560f75949d
- fix Alert form keyboard glitch - ole
-
-
-
</details>
> fix: Alert form keyboard glitch

- src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
- src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-337] 
This PR removes code related to **AREnableAndroidImagesGallery** feature flag. The feature has been rolled out for 10 months and it's been stable since then.
-
-
-
- retire enable android images gallery - mounir
</details>
[ONYX-337]: https://artsyproduct.atlassian.net/browse/ONYX-337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-337): retire enable android images gallery

- src/app/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
This PR resolves [ONYX-555] 
This PR fixes a bug that breaks matching artworks screen after creating an alert
**Before**
https://github.com/artsy/eigen/assets/11945712/7e0009b9-7e4d-41cb-a974-1251854f7868
**After**
https://github.com/artsy/eigen/assets/11945712/6b433d5e-36e8-4d9d-a237-d049d70a979f
- fix unable to load on see all matching artworks - mounir
-
-
-
</details>
[ONYX-555]: https://artsyproduct.atlassian.net/browse/ONYX-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> fix: unable to load on see all matching artworks

- src/app/store/config/features.ts
This PR resolves [PHIRE-497] 
As discussed in the #practice-mobile meeting:
Enables `ARUsePrincipalFieldErrorHandlerMiddleware` as ready for release to test it out ~ leave your feedback [here](https://www.notion.so/artsy/Mobile-QA-for-Unable-to-Load-c15071f48c324a818a673b3d53251262) before the release 
-
-
-
- enable ARUsePrincipalFieldErrorHandlerMiddleware - gkartalis
</details>
[PHIRE-497]: https://artsyproduct.atlassian.net/browse/PHIRE-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> feat: enable ARUsePrincipalFieldErrorHandlerMiddleware

- app.json
Prep for new version
#nochangelog
> chore: prep for new version 8.28.0

- android/gradle.properties
This PR resolves [PHIRE-510] 
Dropped max gradle memory to hopefully make android betas more reliable:
https://app.circleci.com/pipelines/github/artsy/eigen/48744/workflows/0274d0b4-b574-4f38-8360-63f276007d4b/jobs/167291
-
-
-
- update max memory for android gradle - Brian 
</details>
[PHIRE-510]: https://artsyproduct.atlassian.net/browse/PHIRE-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ci):  flaky android betas drop max memory

- src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselVimeoVideo.tests.tsx
- src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselVimeoVideo.tsx
This PR resolves [DIA-354] 
Videos in the Artwork screen image were not correctly loading, this PR fixes the query params extraction.
**Android**
https://github.com/artsy/eigen/assets/15792853/0cbf22d4-fa94-4b86-9155-a21f7f602254
- fix: vimeo broken link - araujobarret
-
-
-
</details>
[DIA-354]: https://artsyproduct.atlassian.net/browse/DIA-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(DIA-354): adds missing token to vimeo player

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
This PR fixes an issue with the keyboard on the create alert flow, this came after we wrapped our screen with keyboard avoiding logic that is not required
https://github.com/artsy/eigen/assets/11945712/2c41e5b1-df71-4409-b550-3d9cc3a0ff06
https://github.com/artsy/eigen/assets/11945712/47cd0d38-6b7a-416a-b4e6-93c41b9ff39e
- fix keyboard issue on create alert screen - mounir
-
-
-
</details>
> fix: keyboard issue on create alert screen

- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
[ONYX-580]
Update copy on create alert flow
-
-
-
-
</details>
[ONYX-580]: https://artsyproduct.atlassian.net/browse/ONYX-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-580): update copy on create alert flow

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
- src/app/Scenes/MyProfile/MyProfileSettings.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
- src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
This PR resolves [ONYX-565](https://artsyproduct.atlassian.net/browse/ONYX-565) 
feat: rename "Saved Alerts" to "Alerts"
- feat: rename "Saved Alerts" to "Alerts" — devon
-
-
-
</details>
[ONYX-565]: https://artsyproduct.atlassian.net/browse/ONYX-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: rename "Saved Alerts" to "Alerts"

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
- src/app/store/config/features.ts
[ONYX-334]
This PR retires AREnableMoneyFormattingInMyCollectionForm feature flag
#nochangelog
[ONYX-334]: https://artsyproduct.atlassian.net/browse/ONYX-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: retire AREnableMoneyFormattingInMyCollectionForm feature flag

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingMarketingCollection.tests.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-330] 
This PR retires `AREnableMyCollectionNotesField` feature flag. 
#nochangelog
[ONYX-330]: https://artsyproduct.atlassian.net/browse/ONYX-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: retire AREnableMyCollectionNotesField feature flag

- src/app/Components/BrowseMoreRailCard.tsx
- src/app/store/config/features.ts
This PR resolves [ONYX-333] 
This PR retires AREnableBrowseMoreArtworksCard feature flag.
#nochangelog
[ONYX-333]: https://artsyproduct.atlassian.net/browse/ONYX-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: retire AREnableBrowseMoreArtworksCard feature flag

- src/app/store/config/features.ts
Follow-up to https://github.com/artsy/echo/pull/574
- Marks `AREnableArtistSeriesFilter` as `readyForRelease: true`
- Points to `AREnableArtistSeriesFilter` Echo flag (which is `false` for now)
-
-
-
- marks Artist Series filtering/alerting as readyForRelease via Echo flag
</details>
> chore(artist series): prepare for release via Echo flag

- src/app/Components/ParentAwareScrollView.tsx
This PR resolves [PHIRE-520] 
Passes a ref to the deregister method, seems to be required now in latest react native. 
https://github.com/artsy/eigen/assets/49686530/acc05967-107b-45fa-a3b6-f245101fba2c
https://github.com/artsy/eigen/assets/49686530/678b31d2-a176-450f-a897-312c55cf2cde
-
-
-
-
</details>
[PHIRE-520]: https://artsyproduct.atlassian.net/browse/PHIRE-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: error on pressing back from collection page on Android

- docs/deploy_a_hotfix.md
- fastlane/Fastfile
- fastlane/sentry_fastlane.rb
Follow-ups from our first codepush release:
- updates docs to add prerequisite steps
- renames the sentry env var to be more consistent (also added to release vars)
- adds param to codepush step to avoid duplicate release errors
-
-
-
- follow-ups for hotfix process - Brian 
</details>
> chore: hotfix follow ups

- .vscode/settings.json
This PR uses VSCode new strings for Actions on Save
Link: https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
-
-
-
- update vs code setting actions on save - mounir
</details>
> chore: update vs code setting actions on save

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
This PR resolves [ONYX-568] 
This PR adds tracking to the suggested filters pills.
**Create Alert Flow**
https://github.com/artsy/eigen/assets/11945712/6ba10e08-f779-4d2b-a8cc-51d67f393e11
_The tracking event is hidden behind the modal_
**Edit Alert Flow**
https://github.com/artsy/eigen/assets/11945712/c51bb497-7947-4c4c-9404-613dae662155
#nochangelog
[ONYX-568]: https://artsyproduct.atlassian.net/browse/ONYX-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add suggested filters tracking

- src/app/AppRegistry.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tests.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouHeader.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/Search/UserPrefsModel.tsx
- src/app/store/__tests__/migration.tests.ts
- src/app/store/config/features.ts
- src/app/store/migration.ts
This PR resolves [ONYX-539] 
- Update the existing New Works For You screen header to match the new layout (the disappearing header)
- Support New Works For You feed
- Save the favorite option in the user store
**Rollout notes:**
- The feature is going to be hidden behind a feature flag
https://github.com/artsy/eigen/assets/11945712/d71912a4-5c27-4f87-93a7-a803a570e6a0
- Add New Works For You Feed - mounir
- Update New Works For You screen header - mounir
-
-
-
</details> …
> feat(ONYX-539): add new works for you feed

- app.json
This PR bumps Eigen's version 8.29.0.
-
-
-
- chore: bump Eigen's version - araujobarret
</details>
> chore: bump Eigen's version 8.29.0

- src/app/Scenes/Articles/Articles.tsx
- src/app/Scenes/Home/Home.tsx
This PR adds the `featured` arg to the `articlesConnection` to have only Articles written by Artsy Editorial.
https://github.com/artsy/eigen/assets/15792853/80e74826-a86c-4ef7-b539-104ecf0b0793
- fix: only feature articles to be shown on Artisy's Editorial sections - araujobarreto
-
-
-
</details>
> fix(Articles): only show featured articles in Artsy's editorial

- scripts/utils/flip-table-extreme
Lil fix, discovered while troubleshooting Eigen [over here](https://artsy.slack.com/archives/CP9P4KR35/p1702502007430869?thread_ts=1702499853.383379&cid=CP9P4KR35).
This script path needed updating in light of https://github.com/artsy/eigen/pull/9449.
-
-
-
- Update `flip-table-extreme` script with correct path
</details>
> fix(devx): update file path in flip-table-extreme

- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- Fix broken bottom padding on NWFY screen
- Fix Broken aspect ratio
https://github.com/artsy/eigen/assets/11945712/211688d1-7e76-431d-9a8e-b13ab8dbe01e
- Fix broken bottom padding on NWFY screen - mounir
- Fix Broken aspect ratio - mounir
-
-
-
</details>
> fix: broken bottom padding and aspect Ratio

- src/app/utils/useDeepLinks.ts
This PR resolves [PHIRE-527] 
We were setting the launch url even if we had successfully navigated so the next time the user launched the app they would be navigated to the same link again.
- fix double navigate from background deep link - Brian 
-
-
-
</details>
[PHIRE-527]: https://artsyproduct.atlassian.net/browse/PHIRE-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: double navigate from background deep link

- scripts/utils/doctor.js
Fixes the ruby expected version on the doctor script.
#nochangelog
> fix: ruby version on doctor #trivial

- src/app/Components/Bidding/Screens/CreditCardForm.tsx
This PR resolves [EMI-1622] by updating copy to match a change on web in [EMI-764]
#minor
#nochangelog
[EMI-1622]: https://artsyproduct.atlassian.net/browse/EMI-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMI-764]: https://artsyproduct.atlassian.net/browse/EMI-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chore: EMI-1622 - update auction registration credit card note

- app.json
> chore: prep for 8.30.0 #trivial

- app.json
Sorry @gkartalis I didn't see your pr and then updated the version number in app store connect to 8.29.1. I think we need to match to not break betas. 🙏 
#no-changelog
> chore: prep for 8.29.1

- src/app/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tsx
- src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
- src/app/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
- src/app/Components/ArtworkGrids/ArtworksFilterHeader.tests.tsx
- src/app/Components/ArtworkGrids/ArtworksFilterHeader.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFilters.tests.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFilters.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFinish.tests.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFinish.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveAlert.tests.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveAlert.tsx
- src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
- src/app/Components/ProgressiveOnboarding/useEnableProgressiveOnboarding.tsx
- src/app/Components/ProgressiveOnboarding/useSetActivePopover.ts
- src/app/Scenes/ArtworkList/ArtworkList.tests.tsx
- src/app/store/ProgressiveOnboardingModel.ts
- src/app/store/config/features.ts
- src/setupJest.tsx
This PR resolves [DIA-70] 
Adds the progressive onboarding for alerts, only enabled with the feature flag `AREnableProgressiveOnboardingAlerts` and after completing the saved artworks onboarding flow.
Android
https://github.com/artsy/eigen/assets/15792853/a77976fb-d265-4202-afdc-43f71cd479bb
iOS
https://github.com/artsy/eigen/assets/15792853/27ba569a-fb7e-40f0-a055-e9fb6eb7e116
- feat: add progressive onboarding for alerts(feature flag hidden) - araujobarret
-
-
-
</details>
[DIA-70]: …
> feat(DIA-70): Add progressive onboarding for alerts

- android/gradle.properties
- fastlane/Fastfile
Tweaks our gradle memory settings and passes suggested flags to clean task to hopefully make our android builds a little more stable. 
Bringing it down too much broke creating the release aar and too much runs out of memory on circle 🤷 hopefully this is a happy medium. 
-
-
-
- tweak memory settings for android ci - Brian 
</details>
> fix(ci): android memory issues

- src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tests.tsx
This PR resolves [PHIRE-546] 
Fixes CareerHighlights tests that were failing when pulling from main and running the tests
#nochangelog
[PHIRE-546]: https://artsyproduct.atlassian.net/browse/PHIRE-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: broken tests careerhighlights

- src/app/AppRegistry.tsx
- src/app/Scenes/Activity/ActivityItemScreen.tsx
- src/app/Scenes/Activity/components/AlertNotification.tsx
- src/app/Scenes/Activity/components/FollowNotification.tsx
This PR resolves [ONYX-613] 
This PR adds the structure for the new **Notification** screen. It utilizes the already existing (but not yet released) `ActivityItemScreen` component and makes some adjustments to accommodate various notification types.
- I have not renamed any files because we are still uncertain about the naming of the new routes ([discussion](https://artsyproduct.atlassian.net/browse/ONYX-612)).
-  The actual screens have not been implemented yet in this PR.
-  The change is behind a feature flag. When the feature flag is enabled, clicking on an item in the Activity rail will open the new screen.
| | | |
|![Simulator Screenshot - iPhone 15 Plus - 2024-01-03 at 16 49 22](https://github.com/artsy/eigen/assets/4691889/7aa9f2a8-eaf2-4c33-9f4f-2b87b32d2b8f) …
> feat: New notification screen structure

- src/app/Scenes/BottomTabs/BottomTabsModel.ts
- src/app/system/relay/middlewares/simpleLoggerMiddleware.ts
This PR resolves [PHIRE-548] 
Adjusting the `fetchNotificationsInfo failed` https://artsynet.sentry.io/issues/4594942792/events/936f079ddb4d4a6dbaca107f3e17bcb7 and `fetchCurrentUnreadConversationCount failed` messages to include the exception since it is not visible on sentry.
Also attempting to fix the serialization issue that we have on events like [this](https://artsynet.sentry.io/issues/4503101969/events/99004b28265d4f2cb7db524acc5b2039/) where we don't see the error and we see [Object] on the breadcrumbs
-
-
-
- adjust sentry alerts - gkartalis
</details> …
> refactor: adjust sentry alerts

- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/store/config/features.ts
- set new works for you screen as not ready for release
- show proper skeleton when the ff is not enabled
https://github.com/artsy/eigen/assets/11945712/3813bce6-2c67-4206-993b-836298d8ede8
-
-
-
- set new works for you screen as not ready for release - mounir
</details>
> chore: set new works for you screen as not ready for release

- src/app/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tsx
This PR resolves [DIA-381] 
Fixes the Progressive onboarding blocking the pointer events on the create alert button.
https://github.com/artsy/eigen/assets/15792853/35efe2c1-f014-40ba-9fd5-945d12e3c47f
- fix: unblock UI interactions on the create alert button - araujobarret
-
-
-
</details>
[DIA-381]: https://artsyproduct.atlassian.net/browse/DIA-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(DIA-381): progressive onboarding blocking create alert button on Artist screen

- src/app/Scenes/SavedSearchAlert/helpers.ts
Rename Saved Alert to Alert in error message.
- Rename "Saved Alert" to "Alert" in error message - ole
-
-
-
</details>
> feat: Rename Saved Alert to Alert in error message

- .circleci/config.yml
Refreshes `node_modules` cache after the patch update
#nochangelog
> fix: refresh node_modules cache

- src/app/Scenes/Activity/Activity.tests.tsx
- src/app/Scenes/Activity/Activity.tsx
- src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
- src/app/Scenes/Activity/hooks/useMarkAllNotificationsAsRead.ts
This PR resolves [ONYX-620] 
Add management action sheet to the Activity List screen
Hidden behind a feature flag
In this PR I also extract the _mark notifications as read_ functionality into a `markAllNotificationsAsRead()` hook. Having a hook seems to be more convenient.
| iOS | Android | Recording |
| --- | --- | --- | 
| ![simulator_screenshot_75586DCF-3DC2-4E8A-BB35-D5CB19CB205D](https://github.com/artsy/eigen/assets/36167539/f4200aa5-51a9-4f04-9d60-a20b439af700) | ![Screenshot_1704892101](https://github.com/artsy/eigen/assets/36167539/dea6ccf5-bbb5-452b-9058-8aff8235ab76) | <video src="https://github.com/artsy/eigen/assets/36167539/448b11d1-2889-42fd-84e6-d85786a45983"> |
- activity List: Implement management action sheet - daria
-
-
- …
> feat(ONYX-620): Activity List: Implement management action sheet

- README.md
This PR is an attempt to make our README.md simpler by following the same comment from @starsirius [here](https://github.com/artsy/volt/pull/7251#discussion_r1447217071)
#nochangelog
> chore: use refs for README.md 

- src/app/Components/ArtworkLists/ArtworkListsContext.tsx
- src/app/Components/ArtworkLists/useArtworkListsToast.ts
- src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
- src/app/Components/Toast/Toast.tests.tsx
- src/app/Components/Toast/ToastComponent.tsx
- src/app/Components/Toast/types.ts
- src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
This PR resolves [EMI-1603] 
> [!note]
> **Part** of the work on this PR is hidden behind the feature flag `AREnablePartnerOffer`
This PR updates the save artwork flow to match the one we have on Force, as well as styling the toasts in the same way
It also adds a description to the toast for the partner offer
|---|---|---|
| Demo for changes | <video src="https://github.com/artsy/eigen/assets/20655703/52876563-145b-4781-bdde-a73995e2d535" /> | <video src="https://github.com/artsy/eigen/assets/20655703/729a5950-ba81-4b7e-af96-06b8bd56f616" /> |
| New Description (behind AREnablePartnerOffer) | <img width="475" alt="image" src="https://github.com/artsy/eigen/assets/20655703/9b4140ff-0257-44a4-ab40-a755c9a43c9d"> | …
> feat(EMI-1603): Update Save Artwork flow to match the web

- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/store/config/features.ts
- src/app/utils/experiments/reporter.ts
This PR resolves [ONYX-651] 
This PR makes the follow changes:
- Add tracking to NWFY screen
- Add a dev toggle to force seeing the feed variant
**Note:** I created this branch from this [one](https://github.com/artsy/eigen/pull/9724) - this is why the big changes, they should be solved as soon as the other gets merged
https://github.com/artsy/eigen/assets/11945712/10a8ce5f-c66e-45e9-88bb-98c24e3111d3
- Implement tracking events for NWFY - mounir
-
-
-
</details>
[ONYX-651]: …
> feat(ONYX-651): Implement tracking events for NWFY

- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
- src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
- src/app/Scenes/Artwork/Components/ArtworkMessages.tsx
- src/app/Scenes/Artwork/Components/InstagramStoryViewShot.tsx
- src/app/Scenes/PartnerOffer/PartnerOfferContainer.tests.tsx
- src/app/Scenes/PartnerOffer/PartnerOfferContainer.tsx
This PR resolves [EMI-1606] 
This PR adds a new banner in the Artwork screen in case a partner offer is unavailable/sold/expired
|---|---|---|
| Expired Offer | <img width="466" alt="image" src="https://github.com/artsy/eigen/assets/20655703/2e2d2458-d107-4643-8c2e-0fc79c99c9f2"> | ![image](https://github.com/artsy/eigen/assets/20655703/6d44d7bf-0013-4160-b041-daecda08fd9d) |
| Unavailable/Sold offer | <img width="467" alt="image" src="https://github.com/artsy/eigen/assets/20655703/46960305-4353-4dfa-96c3-ad6a41ff7fac"> | ![image](https://github.com/artsy/eigen/assets/20655703/faf642b8-6626-4e18-8315-5360506f65a2) |
- Add conditional partner offer banners in Artwork Screen - mrsltun
-
-
-
</details>
Need help with …
> feat(EMI-1606): Add partner offer banners for unavailable/expired offers

- src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
This PR resolves [EMI-1644] 
This PR updates the help article link for the Partner Offers
- Update partner offer help article link - mrsltun
-
-
-
</details>
[EMI-1644]: https://artsyproduct.atlassian.net/browse/EMI-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(EMI-1644): Update partner offer help link

- src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
[Bug feedback in slack](https://artsy.slack.com/archives/C03N12SR0RK/p1705150496500229)
When user presses "Clear All" button it should make "Show Results" clickable, otherwise it is not possible to apply filters. This PR fixes it:
|---|---|
| <video src="https://github.com/artsy/eigen/assets/3934579/5188bfec-040c-4f6a-bd9a-48cb0a1de19c" /> | <video src="https://github.com/artsy/eigen/assets/3934579/47a90bcd-a5af-4134-b207-0d2d72eb577b" /> |
- bugfix: fixes Clear All button behaviour for price filter - @nickskalkin 
-
-
-
</details> …
> fix: fix reset price range filter

- src/app/Scenes/Activity/ActivityItemScreen.tsx
- src/app/Scenes/Activity/components/AlertNotification.tsx
- src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
- src/app/Scenes/Activity/components/FollowNotification.tsx
- src/app/Scenes/Activity/components/NotificationArtworkList.tsx
- src/app/Scenes/Activity/components/__tests__/AlertNotification.tests.tsx
- src/app/Scenes/Activity/components/__tests__/ArtworkPublishedNotification.tests.tsx
- src/app/Scenes/Activity/utils/getNotificationTitle.ts
This PR resolves [ONYX-614](https://artsyproduct.atlassian.net/browse/ONYX-614) & [ONYX-615] 
This PR implements the "Follows" ("Artworks Published"notification) & the "Alerts" (Alert Notification) notification 
screens.
Note 1: A number of things are still missing and are marked with a 'TODO:' comment. They will be implemented later.
Note 2: I apologize for adding both screens in one PR They are so similar that I thought it would be easier this way.
| Follow | Alert |
| --- | --- |
|![Simulator Screenshot - iPhone 15 Plus - 2024-01-15 at 12 15 07](https://github.com/artsy/eigen/assets/4691889/9ee7c51a-d47a-445f-9dfa-5c2379fd3298) |![Simulator Screenshot - iPhone 15 Plus - 2024-01-15 at 12 24 16](https://github.com/artsy/eigen/assets/4691889/92b40bb2-18dd-4ced-918b-44058fc5d7dd) |
| --- | …
> feat: Follow & Alert Notification Screen

- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Home/Components/ActivityIndicator.tsx
- src/app/Scenes/Home/Components/ActivityRail.tests.tsx
- src/app/Scenes/Home/Components/ActivityRail.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
- src/app/routes.ts
This PR resolves [ONYX-612](https://artsyproduct.atlassian.net/browse/ONYX-612)
This PR renames the following routes to align with Force:
- ` /activity` -> `/notifications`
- `/activity/:notificationID` -> `/ notifications/:notificationId`
[Slack Discussion about naming](https://artsy.slack.com/archives/C05EQL4R5N0/p1704898709397699)
- Rename `activity` routes to `notifications` - ole
-
-
-
</details>
[ONYX-612]: https://artsyproduct.atlassian.net/browse/ONYX-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …
> chore: Rename `activity` routes to `notifications`

- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/components/ExpiresInTimer.tsx
Add "no longer available" status that I forgot to add previously:
- add "not available" status to partner offer notifications - @nickskalkin 
-
-
-
</details>
> feat: add not available status to partner offer notifications

- package.json
Although `yarn jetifier` is already available in the install script, I believe there is no harm in adding it to `yarn android` as well. The reason behind that is that many of us mainly run `yarn install` when switching between branches because it's faster and native code updates are not required. The latter command isn't enough for android thus my addition. Let me know what you think about it.
-
-
-
- add yarn jetifier to yarn android - mounir
</details>
> chore: run jetifier before building android

- src/app/store/config/features.ts
This PR enable the new works for you screen for everyone. We QA'd the feature but we forgot to set the ff as ready for release 😿  sorry
#nochangelog
> chore: enable new works for you screen feed for everyone

- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/components/ExpiresInTimer.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
Adds timer to offer notifications:
#nochangelog
> add timer message to activity rail partner offer notifications

- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/components/ExpiresInTimer.tsx
- src/app/Scenes/Home/Components/ActivityRail.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
- src/app/Scenes/Home/Home.tsx
- [Slack Thread with context](https://artsy.slack.com/archives/C05EQL4R5N0/p1705941063872799?thread_ts=1705940935.779039&cid=C05EQL4R5N0)
Add partner offer notifications to the Activity rail.
- Add partner offer notifications to the Activity rail (behind ff) - ole
-
-
-
</details>
> feat: Add partner offer notifications to the Activity rail

- ios/Podfile.lock
- package.json
- yarn.lock
bump @testing-library/react-native to 12.4.3
-
-
-
- bump @testing-library/react-native to 12.4.3 - gkartalis
</details>
> build(deps): bump @testing-library/react-native to 12.4.3

- typings/global.d.ts
This PR adds a helper to make understanding objects/interfaces in VSCode easier.
Co-authored-by: @MrSltun & @gkartalis 
-
-
-
- add typescript prettify - Mounir, George, Sultan
</details>
> chore: add typescript prettify

- package.json
- src/app/Scenes/Activity/Activity.tsx
- src/app/Scenes/Activity/ActivityContainer.tsx
- src/app/Scenes/Activity/ActivityEmptyView.tsx
- src/app/Scenes/Activity/ActivityItem.tests.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/ActivityList.tsx
- src/app/Scenes/Activity/ActivityScreenStore.tsx
- src/app/Scenes/Activity/ActivityTabPlaceholder.tsx
- src/app/Scenes/Activity/NewActivityScreen.tsx
- src/app/Scenes/Activity/components/ExpiresInTimer.tsx
- src/app/Scenes/Activity/components/NewActivityHeader.tsx
- src/app/Scenes/Activity/types.ts
- src/app/Scenes/Activity/utils/getNotificationTypes.ts
- src/app/store/config/features.ts
- src/app/utils/useStickyScrollHeader.tsx
This PR resolves [ONYX-619] 
https://github.com/artsy/eigen/assets/11945712/a449218e-7053-4810-9011-c2018ecf4be8
Blocked by: https://github.com/artsy/palette-mobile/pull/176
- implement new activity screen filter pills - mounir
-
-
-
</details>
[ONYX-619]: https://artsyproduct.atlassian.net/browse/ONYX-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ONYX-619): implement filter pills

- .husky/post-checkout
This PR updates our Husky rules to invoke a new [hook](https://git-scm.com/docs/githooks) post-checkout. The goal from this work is to avoid the new to run `yarn relay` after switching branches. The latter causes always the red screen to show in app and it's annoying to need to open the terminal and run `yarn relay` manually.  (This happened for example today's morning while I was pairing with Nikita)
-
-
-
- invoke yarn relay post-checkout - mounir
</details>
> chore: invoke yarn relay post checkout

- app.json
> chore: Prepare for 8.32.0

- fastlane/utility_fastlane.rb
Realized recently that we display the same message (in different channels though) for both eigen and energy so I went ahead and made it a bit more specific to know immediately to which repo we are referring to.
Same thing in [energy ](https://github.com/artsy/energy/pull/835)
-
-
-
- make fastlane message for native code more descriptive - gkartalis
</details>
> build(codepush): make fastlane message for native code more descriptive

- package.json
- src/app/Scenes/MyProfile/MyProfileSettings.tsx
- yarn.lock
**JFDI:** This adds a recently viewed menu item to the settings tab. It also adds tracking to make sure we can tell how it's performing and if users are clicking on it.
https://github.com/artsy/eigen/assets/11945712/35d9df17-1318-4559-8af8-2c0a76a232aa
- Add recently-viewed menu item to setting screen - mounir
-
-
-
</details>
> feat: add recently-viewed menu item to settings [JFDI]

- .secrets.baseline
- src/app/AppRegistry.tsx
- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/RecentlyViewed/Components/RecentlyViewedArtworks.tsx
- src/app/Scenes/RecentlyViewed/Components/RecentlyViewedPlaceholder.tsx
- src/app/Scenes/RecentlyViewed/RecentlyViewed.tests.tsx
- src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
- src/app/Scenes/Search/UserPrefsModel.tsx
- src/app/store/__tests__/migration.tests.ts
- src/app/store/config/features.ts
- src/app/store/migration.ts
This PR resolves [ONYX-679]
This PR adds view as list on the recently viewed screen.
**What I suggest to pay attention to**
- I found a better way to support list/grid without need to make an additional request ;) I achieved that by tweaking the number of columns with Flashlist Masonry component. As a next step, I will use the same logic in the NWFY screen and save us one additional request 💪 
- This will also make it easier to support the same behaviour in other screens
https://github.com/artsy/eigen/assets/11945712/dcaf862e-1b0a-4f45-a6bb-3a4ee49b8496
https://github.com/artsy/eigen/assets/11945712/0fd5228c-763f-4774-9331-8215594af96d
- support lists on recently viewed screen - mounir
-
-
-
</details>
Need help with something? Have a look at …
> feat: support lists on recently viewed screen

- src/app/Scenes/Activity/components/AlertNotification.tsx
- src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/AlertNotification.tests.tsx
- src/app/Scenes/Activity/components/__tests__/ArtworkPublishedNotification.tests.tsx
- src/app/Scenes/Activity/utils/getNotificationTitle.ts
This PR resolves [ONYX-540] 
This PR does two things: 
- Updating the Notification screen to use the new `headline` field for the title.
- Updating the error messages.
- Update Notification screen title and error messages (behind ff) - ole
-
-
-
</details>
[ONYX-540]: https://artsyproduct.atlassian.net/browse/ONYX-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Use notification headline field as title and better errors

- .secrets.baseline
- src/app/AppRegistry.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/Components/NewWorksFromGalleriesYouFollow.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/Components/NewWorksFromGalleriesYouFollowPlaceholder.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tests.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
This PR resolves [ONYX-689] 
This PR adds support to list/grid view to new works from galleries you follow screen
Related PR to support dynamic title height https://github.com/artsy/palette-mobile/pull/178
https://github.com/artsy/eigen/assets/11945712/d0716348-0598-4633-9bb5-b74aca36a544
- support list/grid toggle on new works from galleries you follow - mounir
- fix: show grid icon on list view & list icon on grid view for toggles - mounir
-
-
-
</details>
[ONYX-689]: …
> feat(ONYX-689): support viewOption toggle on NWFGYF

- .circleci/config.yml
Refresh node_cache with @MrSltun 
#noChangelog
> chore: refresh cache

- ios/Podfile.lock
- package.json
- src/app/Components/Icons/GridViewIcon.tsx
- src/app/Components/Icons/ListViewIcon.tsx
- yarn.lock
bump react-native-svg from 9.13.3 to 14.1.0
-
-
-
- bump react-native-svg from 9.13.3 to 14.1.0 - gkartalis
</details>
> build(deps): bump react-native-svg from 9.13.3 to 14.1.0

- src/app/Components/ArtworkLists/useArtworkListsToast.ts
This PR updates the content of the Save Artwork toast to match the design
|---|---|
| ![image](https://github.com/artsy/eigen/assets/20655703/1a2833df-5c64-4830-b667-4c698c8c3eed) | ![image](https://github.com/artsy/eigen/assets/20655703/3bef3588-bf8b-484e-b290-fa7eb2a8e09c) |	
- Update Saves toast description (behind FF: AREnablePartnerOffer) - mrsltun
-
-
-
</details>
> fix: Update the content of the saves toast

- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
- src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
https://github.com/artsy/eigen/pull/9809#discussion_r1475787585
#nochangelog
-
-
-
- fix pluralisation logic for new works for you screen - nickskalkin
</details>
> fix: fix pluralisation logic for new works for you screen

- package.json
- src/app/system/relay/defaultEnvironment.ts
- src/app/system/relay/middlewares/cacheMiddleware.ts
- src/app/system/relay/middlewares/checkAuthenticationMiddleware.tests.ts
- src/app/system/relay/middlewares/checkAuthenticationMiddleware.ts
- src/app/system/relay/middlewares/errorMiddleware.tests.ts
- src/app/system/relay/middlewares/errorMiddleware.ts
- src/app/system/relay/middlewares/helpers.ts
- src/app/system/relay/middlewares/metaphysicsMiddleware.ts
- src/app/system/relay/middlewares/principalFieldErrorHandlerMiddleware.ts
- src/app/system/relay/middlewares/rateLimitMiddleware.tests.ts
- src/app/system/relay/middlewares/rateLimitMiddleware.ts
- src/app/system/relay/middlewares/simpleLoggerMiddleware.ts
- src/app/system/relay/middlewares/types.ts
- yarn.lock
Bumps `react-relay-network-modern` 
-
-
-
- bump react-relay-network-modern - gkartalis
</details>
> build(deps): bumps react-relay-network-modern

- src/app/Components/LoadFailureView.tsx
- src/app/Scenes/Activity/components/ActivityErrorScreen.tsx
- src/app/Scenes/Activity/components/AlertNotification.tsx
- src/app/Scenes/Activity/components/ArticleFeaturedArtistNotification.tsx
- src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
This PR resolves [ONYX-687] 
Need Barbey's approval
We don’t have a design for the error message screen
We could use the `LoadFailureViewcomponent` without the reload function:
- add notification page error message screen - daria
-
-
-
</details>
[ONYX-687]: https://artsyproduct.atlassian.net/browse/ONYX-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ONYX-687): add error screen

- src/app/Scenes/Activity/ActivityItemScreen.tsx
- src/app/Scenes/Activity/components/ViewingRoomPublishedNotification.tsx
- src/app/Scenes/Activity/components/ViewingRoomPublishedNotificationsList.tsx
- src/app/Scenes/Activity/components/__tests__/ViewingRoomPublishedNotification.tests.tsx
This PR resolves [ONYX-721] 
Implement viewing room notification page
The design is TBD with Barney
https://github.com/artsy/eigen/assets/36167539/5ebb3d5d-82b7-4544-a8ca-7cd4d486dc11
- implement viewing room notification page - daria
-
-
-
</details>
[ONYX-721]: https://artsyproduct.atlassian.net/browse/ONYX-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ONYX-721): implement viewing room notification page

- src/app/Scenes/Activity/ActivityEmptyView.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/ActivityList.tsx
This PR resolves [ONYX-719] 
This PR fixes jumpy `FlatList` and infinite loading on the ActivityList component
Weirdly enough removing the `flex={1}` property [here](https://github.com/artsy/eigen/commit/1efd2895478c7cd8dd0851def9f312319773cec2) was the solution 🙃 
In addition to the fix some refactoring has been made
Thanks @gkartalis for helping with this!
https://github.com/artsy/eigen/assets/36167539/28902d5d-bc49-455f-904d-0aadd388ef42
- fix jumpy FlatList and infinite loading on the ActivityList component - george & daria
-
-
-
</details> …
> fix(ONYX-719): infinite loading on the notifications list

- src/app/Scenes/PartnerOffer/PartnerOfferContainer.tests.tsx
- src/app/Scenes/PartnerOffer/PartnerOfferContainer.tsx
This PR updates the conditions in the Partner Offer Container to go back in case the mutation errors out with something other than `not_acquireable` or `expired_partner_offer`
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/c928ec2c-0631-43c7-b283-ce54c1c4dc77" /> | <video src="https://github.com/artsy/eigen/assets/20655703/c359255f-a421-4f1f-ac07-a4f7ed517263" /> |
- Update partner offer container mutation error logic - mrsltun
-
-
-
</details>
> fix: Update Partner Offer container mutation error logic

- src/app/store/config/features.ts
This PR marks `AREnablePartnerOffersNotificationSwitch` as ready for release since we are planning to release the feature soon
-
-
-
- mark AREnablePartnerOffersNotificationSwitch as ready for release - mrsltun
</details>
> chore: mark AREnablePartnerOffersNotificationSwitch as ReadyForRelease

- app.json
prep for next app version `8.33.0`
To be merged when ios app gets approved
#nochangelog
> chore: prep for next version

- src/app/Scenes/Activity/components/ExpiresInTimer.tsx
This PR resolves [EMI-1702] 
This PR updates the margins on the StopWatch icon in the partner offer component for the Latest Activity rail to prevent it from being slightly cut
|---|---|---|
| Active Offer | ![image](https://github.com/artsy/eigen/assets/20655703/bf1b125f-f76a-4721-a699-c14b8245199b) | ![image](https://github.com/artsy/eigen/assets/20655703/778f9dba-d1ce-4116-a82c-5845b6bb02ac) |
| Expired | ![image](https://github.com/artsy/eigen/assets/20655703/32820ef8-8559-48c5-b239-e51fb40956a9) | ![image](https://github.com/artsy/eigen/assets/20655703/cbf44ad5-dd91-409e-9cd4-f83dbd34f8aa) |
| Unavailable | ![image](https://github.com/artsy/eigen/assets/20655703/3fb38626-a854-4a96-826f-d93273a3065b) | ![image](https://github.com/artsy/eigen/assets/20655703/b41ddc1 …
> fix(EMI-1702): Update margins for partner offer StopWatch icon

- src/app/Components/Artist/Biography.tsx
This PR resolves [DIA-458] 
Changes the Artist bio to HTML and renders it within the right HTML element.
Before
https://github.com/artsy/eigen/assets/15792853/a6c9bf16-b153-47f6-b1c3-ab660ede2c4b
After
https://github.com/artsy/eigen/assets/15792853/6e4623bb-962d-40ed-81c9-993fa49f9966
- fix: display HTML within Artist bio content - araujobarret
-
-
-
</details>
[DIA-458]: https://artsyproduct.atlassian.net/browse/DIA-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> fix(DIA-458): use HTML element to render Artist bio

- src/app/Scenes/Activity/components/NewActivityHeader.tsx
- Related Force PR: https://github.com/artsy/force/pull/13485
Render Activity panel "Offers" filter conditionally.
- Render Activity panel "Offers" filter conditionally (behind feature flag) - ole
-
-
-
</details>
[ONYX-695]: https://artsyproduct.atlassian.net/browse/ONYX-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Render Activity panel "Offers" filter conditionally

- src/app/Components/Artist/Biography.tsx
This PR resolves [DIA-458] 
Changes the text variant of ArtistBio to `sm` instead of `sm-display`.
PS: no screenshot this time, made from Github VS code.
- fix: change artist bio variant to sm - araujobarret
-
-
-
</details>
[DIA-458]: https://artsyproduct.atlassian.net/browse/DIA-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ArtistBiography): use text variant sm

- src/app/Scenes/Activity/ActivityList.tsx
This PR resolves [ONYX-758] 
| --- | --- |
| https://github.com/artsy/eigen/assets/36167539/659a1a9d-62de-42cd-8ee2-48ba53dee91f | https://github.com/artsy/eigen/assets/36167539/3a7e7d46-1a9d-45c2-b23f-119ee7cf4622 |
- fix spinner on the activity screen - daria
-
-
-
</details>
[ONYX-758]: https://artsyproduct.atlassian.net/browse/ONYX-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-758): fix spinner on the activity screen

- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/components/PartnerOffeBadge.tsx
- src/app/store/config/features.ts
Correctly align Offer notification item text.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-02-21 at 11 18 47](https://github.com/artsy/eigen/assets/4691889/cb98e02b-d66d-409c-9d45-3f2fed646f5f) | ![Simulator Screenshot - iPhone 15 Pro - 2024-02-21 at 11 16 56](https://github.com/artsy/eigen/assets/4691889/ac103e40-b07d-48ab-926b-13cebcad73de)|
- Correctly align Offer notification item text - ole
-
-
-
</details>
> fix: Correctly align offer notification item text

- src/app/Scenes/Activity/ActivityList.tsx
This PR fixes an issue affecting the activity screen making images in tabs remain gray. 
https://github.com/artsy/eigen/assets/11945712/52defe9b-7d69-4fbd-a899-1cb00aa7b4a0
-
-
-
-
</details>
> fix: broken image after swtiching between tabs

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Components/ArtworkRail/ArtworkRailCard.tsx
- src/app/Scenes/Activity/ActivityEmptyView.tsx
- src/app/Scenes/Activity/ActivityItemScreen.tsx
- src/app/Scenes/Activity/components/AlertNotification.tsx
- src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
- src/app/Scenes/Activity/components/NewActivityHeader.tsx
- src/app/Scenes/Activity/components/NotificationArtworkList.tsx
- src/app/Scenes/Activity/components/__tests__/ArtworkPublishedNotification.tests.tsx
- src/app/Scenes/Activity/types.ts
This PR does some design updates the new Activity screen and the notification pages:
* Updating the Notification artwork list component, mainly to increase the image size and have consistency with the New Works for You screen that displays a similar artwork list.
* Adding the "Following" Activity panel filter pill (with empty message)
* Adding the "Edit Follows" button
* Design tweaks (spacing etc.)
| | | | 
|![Simulator Screenshot - iPhone 15 Pro - 2024-02-21 at 12 14 27](https://github.com/artsy/eigen/assets/4691889/5df322c0-3f95-4930-8f96-dc04f062316d) | ![Simulator Screenshot - iPhone 15 Pro - 2024-02-21 at 12 14 11](https://github.com/artsy/eigen/assets/4691889/dd4a9196-dda6-4426-b240-724c2afe1146) | ![Simulator Screenshot - iPhone 15 Pro - 2024-02-21 at 12 14 …
> fix: Activity panel and notification screen design tweaks

- package.json
- yarn.lock
This PR updates palette mobile version to 13.1.18.
-
-
-
-
</details>
> chore: update palette mobile version to 13.1.18

- package.json
- yarn.lock
> chore: update palette mobile version to 13.1.9

- src/app/Scenes/Activity/components/NewActivityHeader.tsx
This PR resolves [ONYX-764] 
Order and rename (Following -> Follows) filter pills to match the design
- Sort and rename filter pills to match the design (behind a ff) - daria
-
-
-
</details>
[ONYX-764]: https://artsyproduct.atlassian.net/browse/ONYX-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ONYX-764): sort and rename filter pills

- src/app/Components/Expandable.tsx
- src/app/system/devTools/DevMenu/CodePushOptions.tsx
Expand hitslop of codepush rows in dev menu
https://github.com/artsy/eigen/assets/11945712/13c29e16-46b8-4614-9fee-f8b851ac8aa3
- expand hitslop of codepush rows in dev menu - mounir
-
-
-
</details>
> chore: expand hitslop of codepush rows in dev menu

- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
- src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
> Revert "fix: swap view mode icons on the NWFY and similar screens"

- Gemfile.lock
Bumps fastlane deps 
#nochangelog
> build(deps): bump fastlane deps

- src/app/AppRegistry.tsx
Resolves https://www.notion.so/artsy/Remove-footer-when-in-the-activity-panel-52f3b1e84d18418ba79095184edf6a65?pvs=4
Remove Activity screen bottom tabs.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-02-23 at 12 49 29](https://github.com/artsy/eigen/assets/4691889/f68c2011-8d20-4324-bd15-62c34bdcbf2a) |![Simulator Screenshot - iPhone 15 Pro - 2024-02-23 at 12 43 46](https://github.com/artsy/eigen/assets/4691889/9b769d39-619d-4607-bd34-d7cd9fe013c0) |
- Remove Activity screen bottom tabs - ole
-
-
-
</details> …
> fix: Remove Activity screen bottom tabs

- src/app/Scenes/Activity/utils/getNotificationTypes.ts
Fix follows notification sorting
- fix follows notification sorting (behind a ff)- daria
-
-
-
</details>
> fix: follows notification sorting

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Components/Artist/ArtistArtworks/ArtistArtworksFilterHeader.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
This PR resolves [ONYX-467]
Clean up old feature flags that are marked as release in Echo:
- [AREnableAlertsFiltersArtistSeriesFiltering](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L169)
- [AREnableArtistSeriesSuggestion](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L168)
- [AREnableAlertDetailsInput](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L161)
- [AREnableAlertsSuggestedFilters](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L163C14-L163C44)
- [AREnableAlertsFilters](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L162)
-
-
-
- …
> chore(onyx-467): clean up alerts related feature flags

- docs/best_practices.md
This PR adds some of the best practices to improve lists performance on Eigen. Most of the items here do also apply for other project, I should may create a blog post about this.
**Context:** https://artsy.slack.com/archives/C02BAQ5K7/p1707489650981399
-
-
-
- Virtualized lists best practices - mounir
</details>
> chore: add VirtualizedList  best practices

- ios/Podfile.lock
- package.json
- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionImageCollectionImage.tests.tsx
- src/app/Scenes/Article/Components/__tests__/ArticleHero.tests.tsx
- src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tests.tsx
- yarn.lock
This PR comes as a follow-up on https://github.com/artsy/palette-mobile/pull/173 
Going to merge this to make sure no one's build breaks due to this missing
- 
-
-
- add react-native-blurhash as a dependency - mounir
</details>
> chore: add react-native-blurhash as a dependency

- src/app/store/config/features.ts
set saved search size filters ff as ready for release
- set saved search size filters ff as ready for release - mounir
-
-
-
</details>
> feat: set saved search size filters ff as ready for release

- src/app/store/config/features.ts
Set artworks feed view as ready for release. We didn't release this before to not break the A/B test. We can release it though next time
- set artworks feed view as ready for release - mounir
-
-
-
</details>
> chore: set artworks feed view as ready for release

- src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
Remove additional padding for View all works by button.
-
-
-
-
</details>
> fix: Remove additional padding for View all works by button

- src/app/Scenes/Activity/components/NewActivityHeader.tsx
Align Activity panel filter order with web.
-
-
-
-
</details>
> fix: Align Activity panel filter order with web

- src/app/Scenes/Activity/components/NotificationArtworkList.tsx
- src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
This PR resolves [ONYX-765] 
| Expired | Available | No longer available | 
| ![image](https://github.com/artsy/eigen/assets/36167539/270af124-5c96-417c-9982-f912af8a381a) | ![image](https://github.com/artsy/eigen/assets/36167539/5a1eafcf-632e-401f-9e5e-912aa15aa4a7) | ![image](https://github.com/artsy/eigen/assets/36167539/c39aafb1-8a72-425a-be28-ad1518e98f7a) |
- add CTAs to the offer notification screen (behind a ff) - daria
-
-
-
</details>
[ONYX-765]: …
> feat(ONYX-765): add CTAs to the offer notification screen

- src/app/Scenes/Activity/ActivityItem.tests.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
- src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
Remove publishedAt text for Offers in Activity list.
-
-
-
-
</details>
> fix: Remove publishedAt text for Offers in Activity list

- src/app/store/config/features.ts
Resolves [ONYX-781](https://artsyproduct.atlassian.net/browse/ONYX-781)
Getting ready for the new Activity panel release by enabling the feature flags. 
They are both still disabled in Echo echo echo...
- Release Activity panel redesign 🥳 - ole
-
-
-
</details>
[ONYX-781]: https://artsyproduct.atlassian.net/browse/ONYX-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ONYX-781): Mark new Activity panel feature flags as ready for release

- src/app/Scenes/Activity/ActivityTabPlaceholder.tsx
- src/app/Scenes/Activity/components/AlertNotification.tsx
- src/app/Scenes/Activity/components/__tests__/AlertNotification.tests.tsx
Rename Alert notification edit button.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-02-27 at 11 34 17](https://github.com/artsy/eigen/assets/4691889/69091c1d-eb1b-427a-9fa8-050e9f59c2ec) |![Simulator Screenshot - iPhone 15 Pro - 2024-02-27 at 11 34 53](https://github.com/artsy/eigen/assets/4691889/b474655c-3698-4649-b743-1d3220227f96) |
-
-
-
-
</details>
> fix: Rename Alert notification edit button

- src/app/Scenes/Activity/NewActivityScreen.tsx
This PR resolves [ONYX-799]
https://github.com/artsy/eigen/assets/11945712/266388e6-00d9-461a-af98-f39a3abc8d15
- [X ] I hid my changes behind a **[feature flag]**, or they don't need one.
- chore: switch tab on alerts or follows actionsheet tap - mounir
-
-
-
</details>
[ONYX-799]: https://artsyproduct.atlassian.net/browse/ONYX-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: switch tab on alerts or follows action sheet tap

- src/app/AppRegistry.tsx
- src/app/Scenes/Sales/Sales.tsx
Update the auctions screen to use the new screen layout
https://github.com/artsy/eigen/assets/11945712/edcacc8a-14df-44cd-bd11-bbd60d88be5b
- update auctions screen to use auctions screen - mounir
-
-
-
</details>
> chore: update auctions screen to use auctions screen

- ios/Podfile.lock
- package.json
- src/app/Components/ShareSheet/ShareSheet.tsx
- src/app/Components/ShareSheet/helpers.ts
- yarn.lock
This PR resolves [PHIRE-617] 
Adds logs to monitor why instagram crash is happening
Sentry crash [event](https://artsynet.sentry.io/issues/3010139098/events/b8ca513dcfb044718b6c5786f63befe7/)
[Slack thread](https://artsy.slack.com/archives/C03N12SR0RK/p1707828222235389)
> [!WARNING]  
> Wasn't really able to repro but the sentry event guided me to this solution. Will try to share a beta app with the ones affected to see if it is still an issue.
-
-
-
-  instagram share artwork story crash - gkartalis
</details>
[docs]: …
> fix: instagram share artwork story crash

- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/Home/useHomeModules.ts
| <Image src="https://github.com/artsy/eigen/assets/11945712/cba0b6a4-5657-494b-8ca4-9551b06f7abd" /> | <Image src="https://github.com/artsy/eigen/assets/11945712/08efd247-e690-4267-a747-b9d8214b5ea7" /> |
- Remove unnecessary hero units padding from home screen - mounir
-
-
-
</details>
> fix: remove unnecessary hero units padding on home screen

- src/app/AppRegistry.tsx
- src/app/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx
This PR updates the auction lots screen to use the new layout
https://github.com/artsy/eigen/assets/11945712/818cb201-7ba2-4f25-862c-6d0535fd965c
- update auction lots for you to use new screen layout - mounir
-
-
-
</details>
> feat: update auction lots for you to use new screen layout

- src/app/AppRegistry.tsx
- src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
Update similar to work you viewed to use new screen layout. 
| --- | --- |
| <Image width="400" src="https://github.com/artsy/eigen/assets/11945712/ce2d58d3-e4e0-4f08-a19e-4c0397943d94" /> | <Video width="400" src="https://github.com/artsy/eigen/assets/11945712/85712463-0385-45da-941e-dcfd53251160" /> |
**Note:** I will look at a later time at the text jump on first render, it is not a major issue currently
- update similar to work you viewed to use new screen layout - mounir
-
-
-
</details>
[docs]: …
> chore: update similar to work you viewed to use new screen layout

- src/app/Scenes/Activity/NewActivityScreen.tsx
This PR increases the hitslop of More Icon on the activity screen to offer a better UX
| --- | --- |
| <Video src="https://github.com/artsy/eigen/assets/11945712/9171db22-025a-49ef-8025-5c11f860fc5f" /> | <Video src="https://github.com/artsy/eigen/assets/11945712/e9f97c88-8c58-4dc5-af07-25797592c79b" /> |
- increase hitslop of more icon on activity screen - mounir
-
-
-
</details>
> chore: increase hitslop of more icon on activity screen

- src/app/Scenes/Activity/ActivityEmptyView.tsx
- src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
https://www.notion.so/artsy/Spelling-correction-on-empty-state-screens-Galeries-Galleries-5102f0b02e1145abbb82a0b10dab43bf?pvs=4
Rename copy galeries to galleries.
-
-
-
-
</details>
> fix: Rename copy galeries to galleries

- src/app/Scenes/Articles/Articles.tsx
- src/app/Scenes/Articles/ArticlesList.tsx
- src/app/Scenes/ArtistArticles/ArtistArticles.tsx
This PR migrates the articles screen to use the new screen component 
**video recorded after: d1e9e48**
https://github.com/artsy/eigen/assets/11945712/9f625640-81f6-475d-bfa1-3f9179f4b9ee
- Use new screen in articles screen - mounir
-
-
-
</details>
> chore: migrate articles to new screen

- src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
This PR fixes the broken animation on the artwork screen.
| --- | --- |
| <Video src="https://github.com/artsy/eigen/assets/11945712/52fdd8c6-2098-450a-a8a9-1d897d8b71bf" /> | <Video src="https://github.com/artsy/eigen/assets/11945712/c3aec797-b9f1-4c3e-8f27-55d6e9a0855c" /> | 
- Fix broken transition on create alert screen - mounir
-
-
-
</details>
> fix: create alert broken animation on artwork screen

- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
This PR resolves [ONYX-765] 
Add new Partner Offer notification screen subtitle copy.
- [Figma Design](https://www.figma.com/file/PO3rjpDV29YOFR8kLI4InJ/Activity-Panel-%26-Alerts-Management?node-id=1001%3A21829&mode=dev)
| | | |
|![Simulator Screenshot - iPhone 15 Pro - 2024-02-29 at 13 08 11](https://github.com/artsy/eigen/assets/4691889/952b0c08-83ed-40dc-bf11-ea0684acdb2c) |![Simulator Screenshot - iPhone 15 Pro - 2024-02-29 at 13 08 18](https://github.com/artsy/eigen/assets/4691889/2736e2b8-2335-45b0-a55e-e81d88df1a8f) |![Simulator Screenshot - iPhone 15 Pro - 2024-02-29 at 13 08 54](https://github.com/artsy/eigen/assets/4691889/e2356002-878b-482a-89d3-bb75a1b1ce99) |
- Add new Partner Offer notification screen subtitle …
> feat: Add new Partner Offer screen copy

- src/app/Scenes/Activity/utils/__tests__/formattedTimeLeft.tests.ts
- src/app/Scenes/Activity/utils/formattedTimeLeft.ts
This PR resolves [ONYX-765] 
Make partner offer notification timer **orange** when time until expiration is less than one hour.
- Make partner offer notification timer **orange** when time until expiration is less than one hour. - ole
-
-
-
</details>
[ONYX-765]: https://artsyproduct.atlassian.net/browse/ONYX-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Make partner offer notification timer orange when less than one hour

- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtworkError.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkError.tsx
This PR resolves [ONYX-678] 
This PR adds a 404 page when an artwork screen fails at loading.
**Note:** This PR makes me think, do we really need to do this only here? maybe our error boundary can be improved to **always** show recently viewed artworks.
https://github.com/artsy/eigen/assets/11945712/de3ffc8c-da77-443c-b8bf-9305aabb77ea
- add 404 page to artwork screen - mounir
-
-
-
</details>
[ONYX-678]: https://artsyproduct.atlassian.net/browse/ONYX-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
> feat: add 404 page to artwork

- src/app/Scenes/Artwork/Components/ArtworkError.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkError.tsx
Fix missing new works for you rail.
| --- | --- |
| <Image src="https://github.com/artsy/eigen/assets/11945712/eb89145f-9ed9-41bf-8516-150c3c82d415" /> | <Image src="https://github.com/artsy/eigen/assets/11945712/f0abbf49-a7e3-4f0b-a058-b5c699e6ecde" /> |
#nochangelog
> fix: missing new works for you rail on artwork page

- src/app/utils/googleMaps.tests.ts
- src/app/utils/googleMaps.ts
This PR resolves [ONYX-812]
The Sell With Artsy intake form was observed to be preventing users from submitting an artwork because of an invalid location, even when the location _appeared_ to be a valid result from Google.
This has to do with how we parse the response that we get from `https://maps.googleapis.com/maps/api/place/details`
After the fix, the previously failing **Sydney** example now works:
https://github.com/artsy/eigen/assets/140521/7968e187-fc99-4bd2-a28a-a2cbedb7a54d
- Improve reliability of Location input field - anandaroop
-
-
-
</details> …
> fix: parsing of Google Places API details request

- package.json
- src/app/Scenes/Activity/NewActivityScreen.tsx
- src/app/Scenes/Activity/components/AlertNotification.tsx
- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- yarn.lock
Resolves https://www.notion.so/artsy/Manage-saves-font-looks-broken-on-the-offer-page-update-font-size-according-to-design-and-center-bu-b344bd5a99f941fea5df5d4048679090?pvs=4
- Related palette-mobile PR: https://github.com/artsy/palette-mobile/pull/203
This pull request corrects the text alignment and centering in the screen header component.
See https://github.com/artsy/palette-mobile/pull/203
- Fix partner offer notification screen header right button alignment - ole
-
-
-
</details>
> fix: Screen header text alignement and centering

- ios/Artsy/App/ARAppDelegate.mm
- ios/Podfile
- ios/Podfile.lock
- package.json
- yarn.lock
This PR resolves [PHIRE-659] 
Bumps `react-native-fbsdk-next` from `11.0.0` to latest `12.1.4`
-
-
-
-  bump react-native-fbsdk-next - gkartalis
</details>
[PHIRE-659]: https://artsyproduct.atlassian.net/browse/PHIRE-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build(deps): bump react-native-fbsdk-next from 11.0.0 to 12.1.4

- src/app/Components/SwitchMenu.tsx
This PR resolves [Slack Thread](https://artsy.slack.com/archives/C9XJKPY9W/p1709637357917789) 🔐 
This PR updates the colors of the switches inside the Push Notifications settings screen
|---|---|---|
| Android | <img width="451" alt="image" src="https://github.com/artsy/eigen/assets/20655703/e73a90d8-1fc4-4e50-b666-7bfcbe311067"> | <img width="452" alt="image" src="https://github.com/artsy/eigen/assets/20655703/656a7010-b186-4ba6-8c1b-876e112be0a8"> |
| iOS | ![image](https://github.com/artsy/eigen/assets/20655703/d6591bb4-8c04-4f82-a484-4da58da34c99) | ![image](https://github.com/artsy/eigen/assets/20655703/25b7fa0a-9693-4ffe-ae4f-d8410dabf17d) |
- Update switch colors in Push Notifications settings screen - mrsltun
-
-
- …
> fix: Update Push Notifications screen switch colors

- package.json
- yarn.lock
bumps palette to latest
-
-
-
-  bumps palette to latest - gkartalis
</details>
> build(deps): bumps palette to latest

- app.json
#nochangelog
This PR prepares for 8.35.0
> chore: prepare for version 8.35.0

- src/app/Scenes/Activity/ActivityList.tsx
Remove notifications totalCount workaround.
- Remove Activity Panel filter pills notifications totalCount workaround for partner offer pill - ole
-
-
-
</details>
> chore: Remove notifications totalCount workaround

- src/app/Scenes/Activity/Activity.tests.tsx
- src/app/Scenes/Activity/ActivityItem.tests.tsx
- src/app/Scenes/Home/Components/ActivityRail.tests.tsx
Fix broken Activity panel tests after [enabling feature flags in Echo](https://github.com/artsy/echo/commit/5aff7180d42c85b777d735c23af6a5fcbd58d413).These tests need to be adjusted and reworked when removing the old code and the feature flags.
[Thanks @gkartalis ! 🙏 ](https://artsy.slack.com/archives/C05EQL4R5N0/p1710166922875159)
-
-
-
- Fix broken Activity panel tests after enabling feature flags - ole
</details>
> chore: Fix broken Activity panel tests after enabling feature flags

- src/app/Scenes/Activity/Activity.tests.tsx
- src/app/Scenes/Activity/ActivityItem.tests.tsx
Adjust activity-related tests for the new Activity Panel design by adding new tests, adjusting existing tests, and clearly separating tests for the old design from those for the new design.
-
-
-
- Adjust Activity related tests for new design - ole
</details>
> chore: Adjust Activity related tests for new design

- docs/add_a_new_screen.md
- src/app/AppRegistry.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchAlertsListPlaceholder.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
- src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
- src/app/system/navigation/navigate.tests.tsx
This PR resolves [ONYX-733] 
Small changes in the alerts screen:
- use StickySubHeader component
- alert title / subtitle in two lines
- gray separator
Demo:
<video src="https://github.com/artsy/eigen/assets/3934579/1f8a8d66-5259-4e04-8f5e-cc053139552f" width="400px;" />
- design changes in profile alerts list screen - @nickskalkin 
-
-
-
</details>
[ONYX-733]: https://artsyproduct.atlassian.net/browse/ONYX-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-733): design changes in alerts list screen

- src/app/store/config/features.ts
The list of feature flags in Eigen is getting so long it's becoming annoying 😄. This PR hides all feature flags that were released since more than 3 months. 
**Before**
https://github.com/artsy/eigen/assets/11945712/3191f2b5-0e71-4c61-9421-411ce896eec3
**After**
https://github.com/artsy/eigen/assets/11945712/cec87253-4d55-45da-b833-724384e4a7e4
-
-
-
- hide old released feature flags - mounir
</details>
> chore: hide old released feature flags

- src/app/Scenes/Collection/Components/CollectionHubsRails/OtherCollections/OtherCollectionsRail.tests.tsx
- src/app/Scenes/Collection/Components/CollectionHubsRails/OtherCollections/OtherCollectionsRail.tsx
- src/app/utils/track/SegmentTrackingProvider.ts
Both of the issues were reproduced and I confirmed that the solution fixes them 🥳
Fixes the following android crashes from sentry:
-
-
-
-
</details>
> fix: some android crashes

- src/app/utils/experiments/experiments.ts
- src/app/utils/experiments/hooks.ts
- src/app/utils/experiments/unleashClient.ts
Because we have no typesafety for `useExperimentVariant`, we ended up forgetting to add the experiments to `experiments.ts` file. This PR fixes that by bringing type safety to the hook and to the experiments object.
**Example**
-
-
-
- add type safety to experiments - mounir
</details>
> chore: add type safety to experiments

- src/app/Scenes/Artwork/Artwork.tests.tsx
- src/app/Scenes/Artwork/Components/ArtsyGuarantee.tsx
This PR updates the checkout copy on artwork screen as mentioned on [#product-bugs-and-feedback ](https://artsy.slack.com/archives/C03N12SR0RK/p1710279395397359)
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 14 Pro - 2024-03-13 at 10 12 57](https://github.com/artsy/eigen/assets/21178754/2d33a67f-3689-41be-9580-4ad13d22c05b)|![Simulator Screenshot - iPhone 14 Pro - 2024-03-13 at 10 13 02](https://github.com/artsy/eigen/assets/21178754/d6aa1421-9bed-49c3-9fac-ace9ae7d7e5b)|
- check out copy - gkartalis
-
-
- 
</details> …
> fix: check out copy

- src/app/system/devTools/DevMenu/Components/ExperimentFlagItem.tsx
This PR is an addition on top of https://github.com/artsy/eigen/pull/9960. It comes in order to show feedback when you the unleash flag URL, which i realized later I didn't push 😄 
https://github.com/artsy/eigen/assets/11945712/a08d595e-9f43-47d0-be1f-96c80ce65953
-
-
-
- allow for unleash URL copy from the dev menu - mounir
</details>
> chore: show feedback after copying URL to clipboard

- src/app/AppRegistry.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworks.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tests.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworksPills.tests.tsx
- src/app/Scenes/SavedSearchAlert/AlertArtworksPills.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
- src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
- src/app/routes.ts
- src/app/store/config/features.ts
This PR resolves [ONYX-736]
Implement "View Artworks" screen for alert matches.
Small demo:
<video src="https://github.com/artsy/eigen/assets/3934579/58a43c67-e9e3-43fc-a38c-b69dd4849c1d" width="400px;" />
- Implement "View Artworks" screen for alert matches - @nickskalkin 
-
-
-
</details>
[ONYX-736]: https://artsyproduct.atlassian.net/browse/ONYX-736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-736): view arworks screen for alert matches

- docs/a_b_testing_best_practices.md
- docs/add_an_experiment.md
- docs/best_practices.md
This PR resolves [ONYX-808] 
This PR is an effort to make it easier to set up successful A/b experiments in Eigen in the future. It comes as a follow-up on this [diagnosis](https://www.notion.so/artsy/A-B-Testing-in-Eigen-7b3d8804f46f4f11a81c6bbd53504c1a?p=d4e8307871844fb3be2eb05d519adece&pm=s) and these additions (https://github.com/artsy/eigen/pull/9959 and https://github.com/artsy/eigen/pull/9960 and https://github.com/artsy/eigen/pull/9963 and https://github.com/artsy/eigen/pull/9965)
-  Added A/b testing best practices doc
- Update `add_an_experiment` to ~**not rely on the variant**~ and instead **rely on the payload** for rendering the UI
- Add docs on how to add an override
-
-
-
- update a/b testing docs - mounir
</details>
Need help …
> chore: update a/b testing docs on eigen

- src/app/store/__tests__/migration.tests.ts
- src/app/store/config/ExperimentsModel.ts
- src/app/store/migration.ts
- src/app/system/devTools/DevMenu/Components/ExperimentFlagItem.tsx
- src/app/system/devTools/DevMenu/Components/Experiments.tsx
- src/app/utils/experiments/experiments.ts
- src/app/utils/experiments/hooks.ts
- src/app/utils/experiments/unleashClient.ts
This PR is an effort to improve our experiments infra and make testing different variants with different payloads easier. This PR adds the following:
- Custom variants overrides + custom payload overrides (two different entities because both can live separately)
https://github.com/artsy/eigen/assets/11945712/0bda209f-4425-4a63-90e4-9b3d67503de8
- Since the fields are case-sensitive, I added suggestions for the payload for each experiment for a better UX.
<Image src="https://github.com/artsy/eigen/assets/11945712/f91677e3-b58f-4d93-a7a9-db1ee344e1a1" width="200" />
- Allow users to reset all overrides in one go, thanks for the suggestion @olerichter00 
https://github.com/artsy/eigen/assets/11945712/328fcb95-a7b3-4350-9d40-1d947a200123 …
> feat: support experiments overrides for A/b tests

- src/app/system/devTools/DevMenu/Components/DevTools.tsx
This PR resolves [PHIRE-684] 
Adds copy Push notification token to clipboard dev menu helper
-
-
-
- add copy push notif to clipboard helper - gkartalis
</details>
[PHIRE-684]: https://artsyproduct.atlassian.net/browse/PHIRE-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(dev menu): add copy push notif to clipboard helper

- ios/Artsy/App/ARTArtsyNativeModule.m
- src/app/NativeModules/LegacyNativeModules.tsx
- src/app/system/devTools/DevMenu/Components/DevTools.tsx
- src/setupJest.tsx
Adds a little native method to fetch the push token on iOS since we store it differently. 
-
-
-
- fix push token copy on iOS in dev menu - Brian 
</details>
> fix(dev-menu): add a native module to fix push token copy on ios

- src/app/Scenes/SellWithArtsy/Components/Footer.tsx
- src/app/Scenes/SellWithArtsy/Components/Highlights.tsx
- src/app/Scenes/SellWithArtsy/Components/Testimonials.tsx
- src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
- src/app/Scenes/SellWithArtsy/index.tests.tsx
- src/app/store/config/features.ts
This PR removes both SWA landing screen feature flags (`AREnableSWALandingPageMeetTheSpecialist`, `AREnableSWALandingPageTestimonials`) and simplifies the spacing in the code. 
No visual changes are expected.
-
-
-
- Refactor SWA landing screen spacing - ole
</details>
> chore: Remove SWA landing screen feature flags and simplify spacing

- app.json
Prep for next 8.36.0 version
#nochangelog
> chore: prep for next 8.36.0

- HACKS.md
- patches/react-native-device-info+10.3.0.patch
This PR resolves [PHIRE-726] 
Adds a patch to remove calls to apis that require privacy manifest while this discussion is underway: https://github.com/react-native-device-info/react-native-device-info/issues/1622
Hopefully this is short lived and we can update soon 🙏 
-
-
-
- patch react-native-device info to avoid problem apis - Brian 
</details>
[PHIRE-726]: https://artsyproduct.atlassian.net/browse/PHIRE-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add patch to avoid required apis usage in device info

- src/app/AppRegistry.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotos.tsx
This PR resolves [ONYX-813] 
Hide bottom tabs when submitting an artwork to sell
In addition some necessary UI adjustments have been done
https://github.com/artsy/eigen/assets/36167539/f27a5949-f455-4c59-9b13-22e4a6e33224
- hide bottom tabs when submitting an artwork to sell - daria
-
-
-
</details>
[ONYX-813]: https://artsyproduct.atlassian.net/browse/ONYX-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ONYX-813): hide bottom tabs when submitting an artwork to sell

- jest.config.js
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
- src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
- src/setupJest.tsx
This PR resolves [ONYX-737]
Swipe to delete alerts:
<video src="https://github.com/artsy/eigen/assets/3934579/82e0e9e5-81f4-43c6-bbff-a45df9e38a28" width="400px" />
- Swipe-to-delete feature on alerts list screen - @nickskalkin 
-
-
-
</details>
[ONYX-737]: https://artsyproduct.atlassian.net/browse/ONYX-737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(onyx-737): swipe to delete alert

- src/app/Components/Bidding/Screens/Registration.tests.tsx
- src/app/Components/Bidding/Screens/Registration.tsx
- src/app/store/config/features.ts
This PR puts copy changes behind a feature flag. The copy changes are on a checkbox that users must click to register to bid for an auction. The content change involves clarifying which legal agreements the user is agreeing to.
|-------|------|
| ![Simulator Screenshot - iPhone 15 Pro - 2024-03-27 at 05 04 44](https://github.com/artsy/eigen/assets/44589599/4f1ae496-c91e-4742-92cf-2a9d6d35054d) | ![Simulator Screenshot - iPhone 15 Pro - 2024-03-27 at 05 05 00](https://github.com/artsy/eigen/assets/44589599/ed8f9712-0218-4d29-bcbc-826edb14eb9d) |
| ![Screenshot_1711550394](https://github.com/artsy/eigen/assets/44589599/f32ccbd3-c1b0-4174-b491-64bae555773f) | ![Screenshot_1711552153](https://github.com/artsy/eigen/assets/44589599/8fc82569-a82d-46cc-9946-589f3d19dfc3) | …
> chore: update conditions of sale copy when registering to bid (DIA-538)

- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
This PR resolves [EMI-1771] 
Like https://github.com/artsy/force/pull/13642 but for mobile. Get list price from the artwork instead of the partner offer. 
Fixes price display issues with hidden price, price ranges and edition sets
- Get list price from the artwork in notification panel - leamotta
-
-
-
</details>
https://github.com/artsy/eigen/assets/7518671/497ddd05-3c46-4e6d-b11c-3748275ea645
[EMI-1771]: https://artsyproduct.atlassian.net/browse/EMI-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(EMI-1771): refactor partner offer notification price

- docs/developing_a_feature.md
- [Slack Thread](https://artsy.slack.com/archives/C02BAQ5K7/p1712053999553239) 
Include development menu instructions for Android in the feature documentation.
-
-
-
- Include development menu instructions for Android in the feature documentation - ole
</details>
> chore: Include development menu instructions for Android in the feature documentation

- package.json
- yarn.lock
Bumps @testing-library/react-native from 12.4.3 to 12.4.5
#nochangelog
> build(deps): bumps @testing-library/react-native from 12.4.3 to 12.4.5

- src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
- src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
- src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
- src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
- src/app/Scenes/SavedSearchAlert/Components/Form.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tests.tsx
- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
- src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
- src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
- src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
- src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tests.tsx
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
- src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
- src/app/Scenes/SavedSearchAlert/useSavedSearchPills.ts
This PR resolves [ONYX-247]
Instead of taking pills from context/aggregations, take if directly from metaphysics using `previewSavedSearch` field (force does this already). There are no design changes, so I'm not attaching screenshots or video.
-
-
-
- Remove client-side rendering logic for alert pills, in favor of MP-backed labels/displayValue text - @nickskalkin 
</details>
[ONYX-247]: https://artsyproduct.atlassian.net/browse/ONYX-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
> refactor(onyx-247): Remove client-side rendering logic for alert pills, in favor of MP-backed labels/displayValue text

- ios/Podfile.lock
- src/app/AppRegistry.tsx
- src/app/Scenes/Article/ArticleScreen.tsx
- src/app/Scenes/Articles/ArticlesList.tsx
- src/app/Scenes/Articles/News/ArticlesCards.tsx
- src/app/Scenes/Articles/News/News.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/Home/useHomeModules.ts
- src/app/routes.ts
- src/app/store/config/features.ts
This PR resolves [DIA-470]  and [DIA-469]
Extracted and adapted from #9741. Now hidden under the feature flag for QA purposes.
iOS
https://github.com/artsy/eigen/assets/15792853/bfa68ef1-5c51-4456-9dd2-7668a7e1026f
Android
https://github.com/artsy/eigen/assets/15792853/8fb89500-2b84-4d18-9a93-beb9be0c8aff
- feat: enable news section in the home screen(hidden by ff) - araujobarret
-
-
-
</details>
[DIA-470]: https://artsyproduct.atlassian.net/browse/DIA-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> feat(DIA-470): Add news section

- docs/getting_started.md
Our docs point to the react native docs for android which tell you to install java via brew, but we want it installed via asdf, updating doc to reflect that. 
Tangential: these docs are pretty much repeated word for word in energy and are gonna get out of sync. People okay with just linking energy's docs here with a note to change eigen values for energy? 
#nochangelog
-
-
-
-
</details>
> docs: add a note about installing java dev kit with asdf #trivial

- app.json
> update app version

- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
This PR resolves [ONYX-875] 
Increase one-column artwork grid item spacing.
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-04-09 at 10 18 00](https://github.com/artsy/eigen/assets/4691889/f502b10c-abf5-44e4-8110-242f9664fcc8) |![Simulator Screenshot - iPhone 15 Pro - 2024-04-09 at 10 17 40](https://github.com/artsy/eigen/assets/4691889/4277bbb5-82b4-41f9-99fb-d1bad30d99f8) |
- Increase one-column artwork grid item spacing (e.g. NWFY, Follows, Alert notification) - ole
-
-
-
</details>
[docs]: …
> fix: Increase one-column artwork grid item spacing

- src/app/Scenes/About/About.tests.tsx
- src/app/Scenes/About/About.tsx
This PR updates the links on the About screen to match the new ones requested by our legal team.
|-------|------|
| ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-04-08 at 13 36 23](https://github.com/artsy/eigen/assets/44589599/f268bb11-aab4-439d-a958-bab187d8d1ac) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-04-08 at 13 35 56](https://github.com/artsy/eigen/assets/44589599/bf525ed8-0e3d-41bf-818d-146f056ea5d4) |
| ![Screenshot_1712595028](https://github.com/artsy/eigen/assets/44589599/3d5cd331-c02a-41a8-991d-04c1cb964f18) | ![Screenshot_1712594983](https://github.com/artsy/eigen/assets/44589599/88a111d4-b434-4e3a-82a7-b44d4a108fa8) |
#nochangelog
> feat: update about screen links (DIA-552)

- HACKS.md
- ios/Podfile
- ios/Podfile.lock
This PR updates the commit hash of the Expecta+Snapshots pod in Podfile.lock
It was done by:
1. Removing the `.git` from the link
```diff
- pod 'Expecta+Snapshots', git: 'https://github.com/artsy/ios-snapshot-test-case-expecta.git', branch: 'brian/support-specta-2'
+ pod 'Expecta+Snapshots', git: 'https://github.com/artsy/ios-snapshot-test-case-expecta', branch: 'brian/support-specta-2'
```
2. Installing the pods using `yarn install:all`
3. Adding the `.git` back to the link
4. Installing the pods again to generate a new Podfile.lock
-
-
-
- Update hash commit for Expecta+Snapshots pod - mrsltun
</details> …
> fix: Update Expecta+Snapshots commit hash in Podfile.lock

- src/app/store/config/features.ts
This PR resolves [EMI-1721] 
This PR marks the `AREnableArtworkListOfferability` feature flag as ready for release
-
-
-
- mark AREnableArtworkListOfferability as ready for release - mrsltun
</details>
[EMI-1721]: https://artsyproduct.atlassian.net/browse/EMI-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(EMI-1721): Mark AREnableArtworkListOfferability as ready for release

- src/app/Components/ArtworkLists/components/CreateOrEditArtworkListForm.tsx
- src/app/Scenes/ArtworkList/ArtworkListHeader.tsx
- src/app/Scenes/ArtworkList/types.ts
- src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
- src/app/Scenes/ArtworkList/views/EditArtworkListView/useEditArtworkList.ts
This PR resolves [EMI-1792] 
This PR adds the shareability toggle to the Edit List modal
|---|---|---|
| Updating list offer settings | <video src="https://github.com/artsy/eigen/assets/20655703/df303589-b572-48f0-87dd-da0352584e9b" /> | <video src="https://github.com/artsy/eigen/assets/20655703/7345ef09-c2a6-4134-8ca7-89ee18698f9d" /> |
- Add shareability toggle to Edit Saves List modal - mrsltun
-
-
-
</details>
[EMI-1792]: https://artsyproduct.atlassian.net/browse/EMI-1792?atlOrigin=eyJ …
> feat(EMI-1792): Add shareability toggle in Edit List modal

- src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/ArtworkListOfferSettingsView.tsx
- src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/components/ArtworkListOfferSettingsStickyBottomContent.tsx
This PR resolves [EMI-1784] 
This PR fixes the issue with the scrolling inside the Offer Settings modal
|---|---|---|
| Android | <video src="https://github.com/artsy/eigen/assets/20655703/a386f75f-b352-4bf1-8a74-d9a3740b8df0" /> | <video src="https://github.com/artsy/eigen/assets/20655703/919196ea-4ba7-4619-a977-4447d89749fb" /> |
| iOS | <video src="https://github.com/artsy/eigen/assets/20655703/9b1e52cc-f132-488f-9d17-98019fbc57f3" /> | <video src="https://github.com/artsy/eigen/assets/20655703/9fd99110-695d-42a8-a63c-a19bae98453e" /> |
- fix the scrolling issue in the offer settings modal - mrsltun
-
-
-
</details> …
> fix(EMI-1784): Fix scroll issue in Offer Settings modal

- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountEmail.tests.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountEmail.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tests.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountPassword.tests.tsx
- src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountPassword.tsx
- src/app/Scenes/Onboarding/OnboardingLogin.tsx
Removes value prop from onboarding inputs (they still work)
-
-
-
- remove value prop from onboarding inputs - gkartalis
</details>
> refactor: remove value prop from onboarding inputs

- HACKS.md
- ios/Podfile
- ios/Podfile.lock
Updates to use the official release of expecta+snapshots and removes the hacks entry.
My first pod release! 
-
-
-
- use official expecta+snapshots dep - Brian 
</details>
> chore(deps): use official expecta+snapshots release

- src/app/system/devTools/DevMenu/Components/FeatureFlags.tsx
This PR fixes the issue in the Feature Flag list in Dev Menu, where the search bar is overlapping with the list content on Android
|---|---|---|
| Android | <img width="469" alt="image" src="https://github.com/artsy/eigen/assets/20655703/a905475d-7c76-46a3-91f6-12a161e9812c"> | <img width="469" alt="image" src="https://github.com/artsy/eigen/assets/20655703/ef1f0760-1a55-4b08-9197-26b267a4c08e"> |
| iOS | ![image](https://github.com/artsy/eigen/assets/20655703/8ae46cff-ce44-40ba-8bda-5abcc9c50af4) | ![image](https://github.com/artsy/eigen/assets/20655703/aee42536-814f-4939-9b90-2d5bbad9a6fa) |
-
-
-
- fix feature flag list search bar issue in Dev Menu on Android - mrsltun
</details>
Need help with …
> fix: Feature Flag search bar issue in Dev Menu

- src/app/store/config/features.ts
This PR creates a new feature flag (`AREnablePartnerOfferV1Improvements`) for Partner Offer v1 Improvements
#nochangelog
> chore: Create AREnablePartnerOfferV1Improvements feature flag

- src/app/Scenes/Partner/Components/PartnerShowRailItem.tsx
Fixes the black image on current shows that was reported on [#product-bugs-and-feedback](https://artsy.slack.com/archives/C03N12SR0RK/p1713172293603249)
|Before|After|
|---|---|
|![simulator_screenshot_25B2516D-F329-4B27-987E-CD1EB4F10426](https://github.com/artsy/eigen/assets/21178754/611d3fab-979a-494b-afbd-63b727397b04)|![Simulator Screenshot - iPhone 14 Pro - 2024-04-15 at 17 37 21](https://github.com/artsy/eigen/assets/21178754/950b1f37-11e8-46f7-a961-4d165e9c0ddc)| 
- fixes PartnerShowRailitem image issues - gkartalis
-
-
-
</details> …
> fix: PartnerShowRailitem image issues

- package.json
- yarn.lock
Bumps sentry cli version from 2.30.2 to 2.31.0
-
-
-
- Bumps sentry cli version from 2.30.2 to 2.31.0 - gkartalis
</details>
> build(deps): @sentry/cli from 2.26.0 to 2.31.0

- src/app/Scenes/Activity/components/NotificationArtworkList.tsx
- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
This PR resolves [EMI-1798]
Add partner offer note in notification panel according to the [designs](https://www.figma.com/file/RHkhhJJwixhFPltqhH9ZkW/v1.5-Saves-Partner-Offers?node-id=3866%3A56653&mode=dev)
Just a check on android since I find it impossible to run on my machine setup
- Partner offer note added to notification panel - leamotta
-
-
-
</details>
[EMI-1798]: https://artsyproduct.atlassian.net/browse/EMI-1798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> feat(EMI-1798): add partner offer note in notification panel

- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
- src/app/Scenes/MyCollection/MyCollection.tsx
This PR resolves [ONYX-895] 
My Collection artist keyword search.
https://github.com/artsy/eigen/assets/4691889/91c47398-9448-4a58-b35d-ff402ac65e18
- Fix My Collection artist keyword search by fetching all artists when searching - ole
-
-
-
</details>
[ONYX-895]: https://artsyproduct.atlassian.net/browse/ONYX-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: My Collection artist keyword search

- src/app/Scenes/Activity/ActivityItem.tests.tsx
- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
This PR resolves [ONYX-780] 
This replaces the old notification preview images with the new images from `notification.previewImages`.
| | |
| --- | --- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-04-16 at 13 02 42](https://github.com/artsy/eigen/assets/4691889/9fd68399-d972-4fa0-bf8d-16ee0408340b) | ![Simulator Screenshot - iPhone 15 Pro - 2024-04-16 at 13 02 37](https://github.com/artsy/eigen/assets/4691889/f6b2edf7-cc11-49f1-bb5f-26ac4fa76ac8)|
- Use preview images from MP for "Latest Activity" rail and the Activity screen - ole
-
-
-
</details> …
> feat: GraphQL notification preview images

- src/app/Scenes/Activity/components/PartnerOffeBadge.tsx
Match partner offer notification badge with [designs](https://www.figma.com/file/RHkhhJJwixhFPltqhH9ZkW/v1.5-Saves-Partner-Offers?node-id=3866%3A56653&mode=dev)
- change style of partner offer notification badge - leamotta
-
-
-
</details>
> fix: change style of partner offer notification badge

- src/app/Scenes/Activity/components/PartnerOffeBadge.tsx
Follow up for #10090 addressing comments
- Round notification badge - leamotta
-
-
-
</details>
> fix: add border radius to notification badge

- src/app/Scenes/SellWithArtsy/Components/Testimonials.tsx
This PR resolves [APPL-892] 
Launch blocking issue for release
Hides testimonials section in SWA surface if empty, previously we were displaying the loading state in this case.
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 14 Pro - 2024-04-17 at 12 33 08](https://github.com/artsy/eigen/assets/21178754/180e6d51-e7a1-4f77-868c-e9a0a5964b9e)|![Simulator Screenshot - iPhone 14 Pro - 2024-04-17 at 12 33 00](https://github.com/artsy/eigen/assets/21178754/b565ca12-009a-45f4-a885-545670923bd6)|
- hide testimonials if empty - gkartalis
-
-
-
</details> …
> fix(SWA): hide testimonials if empty

- src/app/Scenes/ViewingRoom/Components/ViewingRoomHeader.tests.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/app/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
This PR resolves [PHIRE-791] 
Fixes some issues with viewing rooms:
- some images coming back with just aspect ratio were causing OpaqueImageView2 to break and not render anything
- absolute positioning of elements in header broke at some point so title, gallery name, countdown were not showing, maybe an upgrade
https://github.com/artsy/eigen/assets/49686530/ccc566dc-b2fb-477f-bf53-d3cc5fb01573
https://github.com/artsy/eigen/assets/49686530/8a04540a-4cef-44c1-b142-772e8b214044
- Fix viewing room rendering issues - Brian 
-
-
-
</details> …
> fix: viewing rooms title and images issues

- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkArticles.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/PriceEstimateRequested.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/PriceEstimateRequested.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/usePriceEstimateRequested.ts
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
This PR resolves [ONYX-865]
[Figma specs](https://www.figma.com/file/VQRDUwdkTUslF62khMhoGZ/O2-Collector-Supply-%E2%80%93-Quick-Tasks?type=design&node-id=4-9037&mode=design&t=3p9HDGQNk78VPBs7-0)
- "Submit for Sale" goes on top - "Request a Price Estimate" after auction results
- "Request a Price Estimate" is white (was black)
- Add these CTAs to the "About" tab
<video src="https://github.com/artsy/eigen/assets/3934579/2227b3ff-3a80-48d7-bdd2-b897d1ea84ef" width="300px" />
- reorganize CTAs on my collection artwork screen - @nickskalkin 
-
-
-
</details> …
> feat(onyx-865): Reorganize CTAs on My Collection Artwork screen

- src/app/Scenes/MyProfile/MyProfileHeader.tsx
Adds a11y label for the profile settings icon to be easily selected in e2e tests 
-
-
-
- add a11y label settings icon - gkartalis
</details>
> chore: add a11y label settings icon

- src/app/store/config/features.ts
This PR updates the newly added feature flag's name from `AREnablePartnerOfferV1Improvements` to `AREnablePartnerOfferOnArtworkScreen` to be more descriptive
The PR that introduced the new FF was not included in [the release candidate](https://github.com/artsy/eigen/commits/ios-8.37.0-2024.04.12.09) so I believe it's safe to change the name
-
-
-
- update feature flag name from AREnablePartnerOfferV1Improvements to AREnablePartnerOfferOnArtworkScreen - mrsltun
</details>
> chore: Update AREnablePartnerOfferV1Improvements FF to AREnablePartnerOfferOnArtworkScreen

- src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsHeader.tsx
This PR resolves [APPL-903] 
Fixes the alignment of the order details section.
|Before|After|
|---|---|
|Android||
|<img width="361" alt="Screenshot 2024-04-19 at 13 13 38" src="https://github.com/artsy/eigen/assets/21178754/19f68595-2718-4663-a142-a6ee44946db9">|<img width="363" alt="Screenshot 2024-04-19 at 13 13 14" src="https://github.com/artsy/eigen/assets/21178754/ff923fea-1cbc-4b6a-bd95-f2d9eaeac9d7">|
|iOS||
|<img width="359" alt="Screenshot 2024-04-19 at 13 13 32" src="https://github.com/artsy/eigen/assets/21178754/69580cf8-71bb-4f8f-87bf-6fa79df4f8b3">|<img width="352" alt="Screenshot 2024-04-19 at 13 13 21" src="https://github.com/artsy/eigen/assets/21178754/c6cdcfee-a2c8-4e85-9c82-7632e518ec26">|
- order details not aligned - …
> fix: order details not aligned

- src/app/Scenes/PrivacyRequest/PrivacyRequest.tsx
This PR resolves [APPL-887] 
Fixes alignment of Personal Data Request header
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone SE (3rd generation) - 2024-04-19 at 17 07 04](https://github.com/artsy/eigen/assets/21178754/0cc6d472-6d49-40ad-8180-13d97fd7b988)|![Simulator Screenshot - iPhone SE (3rd generation) - 2024-04-19 at 17 06 51](https://github.com/artsy/eigen/assets/21178754/f24f3a8e-fec0-4159-af41-4843cff2ec36)|
- Fixes alignment of Personal Data Request header - georian
-
-
-
</details> …
> fix: Personal Data Request header alignment

- src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreenAndroid.tsx
This PR resolves [APPL-905] 
Fixes back button not working on artwork modal
> [!IMPORTANT]  
> Gotcha from the rn docs:
> Warning for modal users: If your app shows an opened Modal, BackHandler will not publish any events ([see Modal docs](https://reactnative.dev/docs/modal#onrequestclose)).
> In these cases we should use the [onRequestClose](https://reactnative.dev/docs/modal#onrequestclose) prop from the modal!
-
-
-  back button not working on artwork modal - gkartalis brian
-
</details>
[APPL-905]: …
> fix(android): back button not working on artwork modal

- src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
This PR resolves [APPL-902] 
Artwork carousel inside articles was overflowing when the description is long.
|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/7382f560-af7d-4036-aec3-b8fd6c13b156" />|<video src="https://github.com/artsy/eigen/assets/21178754/983a9488-36f9-4873-a5a2-66df920a864a" />|
- artwork carousel overflowing when description is long - gkartalis brian
-
-
- 
</details>
[APPL-902]: https://artsyproduct.atlassian.net/browse/APPL-902?atlOrigin=eyJpIjoiNWRkNT …
> fix: artwork carousel overflowing when description is long

- ios/Artsy/Views/Notifications/ARNotificationView.m
This PR resolves [APPL-858] 
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
-
- Fix text being cut off in in app notifications - Brian 
-
-
</details>
[APPL-858]: https://artsyproduct.atlassian.net/browse/APPL-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: long push notification text cut off in in app view

- src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tsx
This PR resolves [APPL-873] 
Fixes color filters not clearing in the UI when tapping clear all in saved search.
<details>
<summary>
Before
</summary>
https://github.com/artsy/eigen/assets/49686530/e2c12c1b-7a3b-4690-9882-c6d2aa0ec510
</details>
<details>
<summary>
After
</summary>
https://github.com/artsy/eigen/assets/49686530/3aa52952-e4c3-4de9-bfe4-73cb0a10a2a3
</details>
- fix color filters not clearing in saved search - Brian 
-
-
-
</details>
[APPL-873]: …
> fix: colors not updating when clearing all

- src/app/Scenes/Artwork/Artwork.tsx
This PR adds the partner offer query to the Artwork screen, specifically in the `Artwork_me` query
This PR is a setup for the upcoming work on the artwork screen to be aware of partner offers, by updating the content of the artwork screen (artwork price, gallery note) if the current user has a partner offer on the artwork
-
-
-
- add partner offer query to the artwork screen - mrsltun
</details>
> feat: Add Partner Offer query to Artwork screen

- src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
- src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
- src/app/Scenes/Activity/components/NotificationArtworkList.tsx
- src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/NotificationCommercialButtons.tests.tsx
This PR resolves [EMI-1767] 
| Expired | Available |
| --- | --- |
| ![Screenshot 2024-04-17 at 18 18 14](https://github.com/artsy/eigen/assets/827596/ef2a2c9e-5231-4596-974e-04d54408d273) | ![Screenshot 2024-04-17 at 18 11 11](https://github.com/artsy/eigen/assets/827596/f48182ad-fb4f-479f-8c65-ee517c27f45f) |
- add a new CTA to the offer notification screen (behind a ff) - Kaz
-
-
-
</details>
[EMI-1767]: https://artsyproduct.atlassian.net/browse/EMI-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
> feat: show new CTA for partner offers on notification

- src/app/Scenes/Articles/Articles.tests.tsx
Attempt to reduce the flakiness of this test, not sure if it will make any difference but lets see
#nochangelog
> chore: attempt to reduce articles test flakiness

- src/app/AppRegistry.tsx
- src/app/Scenes/ArtworkLists/ArtworkLists.tsx
- src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
- src/app/Scenes/MyProfile/MyProfileHeader.tsx
- src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
- src/app/Scenes/SavedArtworks/SavedArtworks.tsx
- src/app/routes.ts
- src/app/store/config/features.ts
This PR resolves [DIA-558]
Adds the new Settings screen under the feature flag. Other changes:
- moves the saves tab to an independent screen
- Includes a small refactor in the test
https://github.com/artsy/eigen/assets/15792853/1a612fcb-1ac1-4f9b-8e37-e82c25dbf9cd
- feat: add new settings screen(hidden under ff) - araujobarret
-
-
-
</details>
[DIA-558]: https://artsyproduct.atlassian.net/browse/DIA-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-558): new settings screen

- src/app/Scenes/Activity/ActivityItem.tsx
- src/app/Scenes/Home/Components/ActivityRailItem.tsx
This allows the Activity panel and rail items to display without images. Without this fix, the app was crashing. with this fix a gray box is shown in case the image is missing.
Usually, all activities should have images. I just noticed this bug in staging where some data is missing.
- Prevent Activity panel from crashing when Activities miss images - ole
-
-
-
</details>
> fix: Prevent Activity panel from crashing when Activities miss images

- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
This PR resolves [EMI-1838]
#minor copy update 
[EMI-1838]: https://artsyproduct.atlassian.net/browse/EMI-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chore: Update copy

- src/app/Scenes/Artwork/Components/ArtworkPartnerOfferNote.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkPartnerOfferNote.tsx
This PR resolves [EMI-1842] 
The PR doesn't show the partner offer note on the artwork screen if the offer is no longer available.
- added check for the availability of a partner offer to determine if a partner offer shown - narikazu
-
-
-
</details>
[EMI-1842]: https://artsyproduct.atlassian.net/browse/EMI-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: do not show partner offer note if the offer is no longer available

- src/app/Scenes/Artwork/Artwork.tsx
This PR resolves [EMI-1752] 
This PR adds a check if a collector opened the app with a link from the email or notification,
To display the expired/unavailable banner in the artwork page by checking for `partner_offer_id` param in the url
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/8b422b68-48df-48d3-9732-4b9fb5411800" /> | <video src="https://github.com/artsy/eigen/assets/20655703/e5da6a72-0aca-46fe-b43a-2e28ee962154" /> |
- Added check for `partner_offer_id` in artwork URL to display expired/unavailable partner offer banner - mrsltun
-
-
-
</details> …
> feat(EMI-1752): Display banner for unavailable/expired offers on Artwork

- ios/Podfile.lock
- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
- src/app/Scenes/PartnerOffer/PartnerOfferContainer.tests.tsx
- src/app/Scenes/PartnerOffer/PartnerOfferContainer.tsx
This PR resolves [EMI-1846] 
This PR adds the "Purchase" title to the Partner Offer checkout modal
It also updates the podfile lock
|---|---|---|
| Android | ![image](https://github.com/artsy/eigen/assets/20655703/5dd4a0ee-9ee7-48c0-b25b-e30a3f4b83dc) | ![image](https://github.com/artsy/eigen/assets/20655703/1a790ed6-316d-4b43-8f8c-826bccdec9d4) |
| iOS | ![image](https://github.com/artsy/eigen/assets/20655703/92f26d8b-8411-487d-a5ed-dca2bf1e87b1) | ![image](https://github.com/artsy/eigen/assets/20655703/0348c1f3-2d9c-4fd1-9efc-9f94dc732d34) |	
- adds "Purchase" title to Partner Offer checkout modal - mrsltun
-
-
-
</details>
[app state …
> fix(EMI-1846): Pass "Purchase" title to partner offer checkout modal

- renovate.json
This PR resolves [PHIRE-846] 
Noticed that in some PRs like [this one](https://github.com/artsy/eigen/pull/10147) renovate ignores if the CI checks pass or not so opening a PR to test if it actually waits for the checks first before merging. (also replaced pvinis with me on the config)
-
-
-
- renovate config changes - gkartalis
</details>
[PHIRE-846]: https://artsyproduct.atlassian.net/browse/PHIRE-846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build(config): renovate config changes

- fastlane/Fastfile
This PR resolves [PHIRE-785] 
Bringing back the diff of https://github.com/artsy/eigen/pull/7913 
Allow releasing specific past versions on Android.
- On uploading a beta to the playstore we will also upload the signed aab to s3
- On promoting a beta to prod we will allow selection/download from s3 and then upload the selected build to the play store
We will need to test if it works as expected to be able to fetch latest 20 android builds from s3.
-
-
-
- ci select 20 Android last releases - gkartalis
</details>
[docs]: …
> build(ci): Android specific releases

- src/app/store/config/features.ts
This PR resolves [EMI-1796] 
This PR marks `AREnablePartnerOfferOnArtworkScreen` as ReadyForRelease in preparation to release the feature
-
-
-
- mark AREnablePartnerOfferOnArtworkScreen as ready for release - mrsltun
</details>
[EMI-1796]: https://artsyproduct.atlassian.net/browse/EMI-1796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(EMI-1796): Mark AREnablePartnerOfferOnArtworkScreen as ReadyForRelease

- src/app/Scenes/MyProfile/MyProfileSettings.tsx
This PR resolves [DIA-559] 
Reorganize the Settings screen links.
- feat: reorganise the settings screen(ff hidden) - araujobarret
-
-
-
</details>
[DIA-559]: https://artsyproduct.atlassian.net/browse/DIA-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DIA-559): reorg settings screen sections

- src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
- src/app/Scenes/SellWithArtsy/utils/useSWALandingPageData.tsx
This PR resolves [ONYX-929] 
Remove filters from the specialists list on the /sell page
[Slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1714080170749499)
The list of specialists was updated in s3
| --- | --- |
| ![image](https://github.com/artsy/eigen/assets/36167539/188639e5-7a3e-4bcd-9bf9-ee1f62bcf0d1) | ![image](https://github.com/artsy/eigen/assets/36167539/18fd9e27-d28c-4428-9893-bd1e58a58cf2) |
- remove filters from the list of specialist on the sell screen -daria
-
-
-
</details>
[docs]: …
> chore(ONYX-929): remove filters from the list of specialist on the sell screen

- .circleci/config.yml
Fix beta failures for android after image was updated. 
- downgrades android image back to previous version
- explicitly sets jdk version to 11 using android orb
-
-
-
- fix android beta failures, specify java version - Brian 
</details>
> fix(ci): try explicitly specifying java version

- src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
- src/app/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
This PR resolves [EMI-1815] 
Similar to https://github.com/artsy/force/pull/13811 but with less changes, as the checkout is only on web
- Send partner offer id when making an offer on a partner offered listing - leamotta
-
-
-
</details>
[EMI-1815]: https://artsyproduct.atlassian.net/browse/EMI-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(EMI-1815): allow countering a partner offer

- ios/Podfile.lock
- package.json
- yarn.lock
This PR resolves [PHIRE-734] 
Update react native blob util to latest version with a privacy manifest. 
-
-
-
- update react native blob util - Brian 
</details>
[PHIRE-734]: https://artsyproduct.atlassian.net/browse/PHIRE-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update react-native-blob util for privacy manifest

- src/app/Components/WorksForYouArtworks.tsx
- src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
- src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
- src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
- src/app/store/config/features.ts
- src/app/utils/experiments/experiments.ts
This PR changes removes the experiment related code for the NWFY screen (and similar screens) and allows everyone to toggle between feed vs grid
- allow all users to toggle between grid and list views on NWFY, recently viewed and galleries for you screens - mounir
-
-
-
</details>
> chore: allow all users to toggle between feed and list views

- package.json
- src/app/Components/Bidding/Screens/BillingAddress.tsx
- src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
- src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
- src/app/Scenes/Search/Search.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
- yarn.lock
This PR leverages [this work](https://github.com/artsy/palette-mobile/pull/225)  to render a non-broken placeholder on Android for inputs with a long placeholder
https://github.com/artsy/eigen/assets/11945712/861e15d8-a6f1-43ca-b324-64043e42e7e0
-
-
- fix long input placeholders on Android - mounir
-
</details>
> fix: long input placeholders on Android

- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityLegacy.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
This PR resolves [ONYX-923] 
Remove the force numeric keyboard from Edition size and Edition number fields
Use default keyboard type
| --- | --- |
| ![image](https://github.com/artsy/eigen/assets/36167539/12be4aa6-2aa6-4f81-8231-44de9e9bc96f) | ![image](https://github.com/artsy/eigen/assets/36167539/63e95cd0-87a3-4b02-a715-53a15ee08697) |
- remove the force numeric keyboard from Edition size and Edition number fields -daria
-
-
-
</details>
[ONYX-923]: …
> chore(ONYX-923): remove keyboard prop from edition text inputs

- app.json
Bumps Eigen's version to 8.39.0
-
-
-
- chore: version bump 8.39.0 - araujobarret
</details>
> chore(version): version bump

- fastlane/Fastfile
- Updates the s3 path to the newer path and moves to a variable
- Adds s3 upload that was missing from beta deploy
Draft until I test. 
-
-
-
- Fix android submission issues - brian 
</details>
> fix(releases): android submission issues

- src/app/Scenes/Artwork/Components/ShippingAndTaxes.tests.tsx
- src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx
This PR resolves [AMBER-670](https://artsyproduct.atlassian.net/browse/AMBER-670)
Adds tax info and shipping details to unlisted artwork page
Adds in tracking event when tapped
- Adds Shipping and Tax info section to private artwork experience - Jackie
-
-
- Adds tracking event for tapping on Tax info learn more - Jackie
</details>
[AMBER-670]: https://artsyproduct.atlassian.net/browse/AMBER-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(tracking): Render tax info and link to help center for unlisted works + tracking events

- package.json
- src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
- src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
- src/app/Scenes/SellWithArtsy/utils/TrackingEvent.ts
- yarn.lock
Address cohesion type errors to get on latest version of cohesion
It looks like PRs for cohesion from renovate have been failing for a bit
https://app.circleci.com/pipelines/github/artsy/eigen?branch=renovate%2Fartsy-cohesion-4.x
Attempting to fix and upgrade to use new functionality provided by version 1.180
-
-
-
- Upgrade cohesion library to latest version and address type errors
</details>
> Fix: Address cohesion type errors to get on latest version of cohesion

- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtsyGuarantee.tests.tsx
- src/app/Scenes/Artwork/Components/ArtsyGuarantee.tsx
- src/app/Scenes/Artwork/Components/ShippingAndTaxes.tests.tsx
- src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx
This PR resolves [AMBER-669](https://artsyproduct.atlassian.net/browse/AMBER-669)
Adds Artsy Guarantee componenet to private artworks screen + add tracking event on Learn more taps
- Display Artsy Guarantee to private artworks screen
-
-
- Add analytics tracking event to Artsy Guarantee learn more tap
</details>
[AMBER-669]: https://artsyproduct.atlassian.net/browse/AMBER-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(tracking): Render artsy guarantee component for private artworks + add tap event tracking

- src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
This PR resolves [AMBER-677](https://artsyproduct.atlassian.net/browse/AMBER-677) 
Fire generic tap event when `Read more` section of artwork details page is tapped
-
-
-
- Fire generic tap event when `Read more` section of artwork details page is tapped
</details>
[AMBER-677]: https://artsyproduct.atlassian.net/browse/AMBER-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(tracking): Add generic tap event for read more taps on artwork details

- src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tests.tsx
- src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tsx
- src/app/Components/Select/Components/SelectButton.tsx
- src/app/Components/Select/Select.tsx
- src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tests.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/testUtils.ts
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
- src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tests.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
This PR resolves [ONYX-816] 
This PR adds highlighting to invalid fields on the SWA flow. It also adds support to scrolling to the top of the `ScrollView` if there is an error.
**Scroll to the top if the form is untouched using the save button**
https://github.com/artsy/eigen/assets/11945712/069eb498-8240-4c41-8864-50963b0f1c2e
**Highlight wrong fields**
https://github.com/artsy/eigen/assets/11945712/d2bf1910-885b-4088-8e5f-d86b88eb500d
- highlight invalid fields on SWA flow - mounir
-
-
-
</details> …
> feat: highlight invalid fields on SWA flow

- .secrets.baseline
Bump detect-secrets baseline version
-
-
-
- bump detect-secrets baseline version - mounir
</details>
> chore: bump detect-secrets baseline version

- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
- scripts/deploys/create-android-apk
This PR resolves [PHIRE-851] 
Little quality of life script to create a universal apk for upload for testing instead of needing to find this in the play console.
```
yarn setup:releases
./scripts/deploys/create-android-apk
....noisy output
[15:33:15]: ------------------------------
[15:33:15]: --- Last 20 Android builds ---
[15:33:15]: ------------------------------
[15:33:15]: Which build would you like to select?: 
1. 1674645690.aab
2. 124.aab
3. 123.aab
?  1
[15:33:26]: Are you sure you would like to select 1674645690.aab? (y/n)
y
[15:33:27]: Continuing!
.....noisy output
Preparing apk to /Users/<user>/Code/eigen/1674645690.apk
````
-
-
-
- script for creating android apk - brian 
</details>
Need help with something? Have a look at our …
> build(tools): generate universal android apk script

- src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tests.tsx
- src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
This PR resolves [AMBER-672] 
This change adds exclusive access text to conversations for unlisted artworks.
</details>
#nochangelog
-
</details>
[AMBER-672]: https://artsyproduct.atlassian.net/browse/AMBER-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AMBER-672]: https://artsyproduct.atlassian.net/browse/AMBER-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Adding exclusive access text to conversations

- src/app/Scenes/Onboarding/OnboardingQuiz/Components/ArtistListItem.tsx
Came up during Sprintly QA. [Notion card](https://www.notion.so/artsy/Follow-button-loading-state-broken-in-onboarding-77802c8296144eadb466fc2dda1a6fdb?pvs=4)
Fixed the gallery part on another PR, this one fixes the Artists onboarding follow page.
|Before|After|
|---|---|
|<img width="602" alt="Screenshot 2024-05-10 at 16 45 33" src="https://github.com/artsy/eigen/assets/21178754/3fade11f-b250-4641-bebd-e447798c306b">|<video src="https://github.com/artsy/eigen/assets/21178754/494d8947-8df0-41a1-8dd2-7af75be24e4d" width="400" />|
- follow button onboarding artists - gkartalis 
-
-
- 
</details> …
> fix: follow button onboarding artists

- src/app/Scenes/Activity/components/__tests__/NotificationCommercialButtons.tests.tsx
- src/app/Scenes/Artwork/Artwork.tests.tsx
- src/app/Scenes/Artwork/Artwork.tsx
- src/app/Scenes/Artwork/Components/ArtworkPrice.tests.tsx
This PR fixes broken tests after releasing Partner Offers on Artwork screen
-
-
-
- fix tests after releasing PartnerOffer on Artwork Screen - mrsltun
</details>
> fix: Update tests after releasing the feature

- src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
- src/app/Scenes/MyProfile/MyProfileSettings.tsx
Hides settings subheader behind a ff.
Also refactors a tiny bit the `src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx` to not use the legacy test renderer
|Before|After|
|---|---|
|![b4](https://github.com/artsy/eigen/assets/21178754/ea34b05b-f013-405a-a460-aedf165df5b0)|![after](https://github.com/artsy/eigen/assets/21178754/71632fa2-87e1-4f3f-a53e-05fd0082b3bc)|
- hide settings subheader behind collector profile ff - gkartalis
-
-
-
</details>
> chore: hide settings behind ff

- .circleci/config.yml
- scripts/deploys/upload-betas-maestro-copilot
- scripts/maestro/build-android.sh
- scripts/maestro/build-ios.sh
This PR resolves [PHIRE-850] 
Automate uploads for maestro builds via a script, can be moved to be a ci job but since we don't want to trigger it yet maybe this is enough?
Happy to hear your thoughts.
-
-
-
- automate uploads for maestro copilot builds - gkartalis
</details>
[PHIRE-850]: https://artsyproduct.atlassian.net/browse/PHIRE-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: automate uploads for maestro copilot builds

- src/app/Scenes/Onboarding/OnboardingSocialLink.tsx
This PR resolves [PHIRE-897] 
Attempt to fix `Cannot convert undefined value to object` error in `navigation.replace(ForgotPassword)`.
My assumption is that for some reason navigation is not yet ready in some edge cases and added a safeguard around it.
Will test it with my android device probably tomorrow - Feel free to test it out if you own an android device.
What we are looking for:
- any crashes when pressing forgot password. 
-
-
- attempt to fix Cannot convert undefined value to object - gkartalis
-
</details>
[docs]: …
> fix: attempt to fix Cannot convert undefined value to object

- src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
- src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
This PR resolves [EMI-1875] 
This PR updates the subtitle of the partner offer notification when it's coming from an abandoned order
It also refactors the tests for `PartnerOfferCreatedNotification` and adds new tests for abandoned order offers
|---|---|---|
| Offer from Saves | <img width="524" alt="image" src="https://github.com/artsy/eigen/assets/20655703/0876e1bf-c8fc-4ea8-a59b-a40fac5a463f"> | <img width="524" alt="image" src="https://github.com/artsy/eigen/assets/20655703/d4680e04-b3a9-4e15-9352-d2017eb7c991"> |
| Offer from Abandoen Orders | <img width="524" alt="image" src="https://github.com/artsy/eigen/assets/20655703/84eae308-4f64-4b68-849c-ea292e61c0bc"> | <img width="524" alt="image" src="https://github.com/artsy/eigen/assets/20655703/0e4f2e96-f03c-4596-933 …
> feat(EMI-1875): Update Partner Offer Notification for offers for abandoned orders

- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
- src/app/Scenes/SellWithArtsy/utils/submissionModelState.tsx
- src/app/store/__tests__/migration.tests.ts
- src/app/store/migration.ts
This PR resolves [ONYX-966]
This PR fixes the broken validation on the sell page as well as removes some unnecessary fields
https://github.com/artsy/eigen/assets/11945712/fa528d60-fe1f-41f7-930a-d8f5150e0aa1
https://github.com/artsy/eigen/assets/11945712/7d6b4697-bf5a-464a-94d0-df2f89b6ffe8
https://github.com/artsy/eigen/assets/11945712/d77956aa-e8d0-4b61-af17-ba4b665f83b6
- fix broken validation on SWA flow - mounir
-
-
-
</details>
[ONYX-966]: https://artsyproduct.atlassian.net/browse/ONYX-966?atlOrigin=eyJ …
> fix: broken validation on SWA flow

- src/app/AppRegistry.tsx
- src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
- src/app/Scenes/Home/Home.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
- src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
- src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
- src/app/routes.ts
- src/app/system/navigation/routes.tests.ts
- src/app/utils/router.ts
This PR resolves [ONYX-948] 
This PR consolidates the different submit artwork routes in app to be using the same `url`. This will make it easier for us to track conversions and implement proper deep links.
**Bonus:**
I noticed that the sell tab route is `/sales` so I fixed that to be `/sell` like in web
**Starting the flow from the sell tab**
https://github.com/artsy/eigen/assets/11945712/21696d31-15ab-40c8-b797-445d3d9871dc
**Starting the flow from my collection**
https://github.com/artsy/eigen/assets/11945712/c233d776-2dd6-4f7b-af28-21c6085fa8ad
-
-
-
- consolidate sell routes in app - mounir
</details> …
> chore: consolidate sell routes in app

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
This PR resolves [ONYX-957] 
This PR updates the artwork dimensions screen to match the new designs in Figma
**Note:** I suggest removing spaces when reviewing this
<Img src="https://github.com/artsy/eigen/assets/11945712/653c232e-26d9-46bf-b88c-cca7792634db" width="400" />
-
-
-
-
</details>
[ONYX-957]: https://artsyproduct.atlassian.net/browse/ONYX-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update artwork dimensions screen in new submit artwork flow

- package.json
- yarn.lock
-
-
-
- update @sentry/cli from 2.31.0 to 2.31.2
</details>
> build(deps): @sentry/cli from 2.31.0 to 2.31.2

- app.json
This PR updates the app version to prepare for next release. #nochangelog
> chore: prepare for next release

- src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
- src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
This PR resolves [APPL-921] 
Fixes padding issues on Artwork screen - Artist series section.
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 14 Pro - 2024-05-17 at 15 29 26](https://github.com/artsy/eigen/assets/21178754/a80f2be9-a77f-45ab-831b-efcb120e13b7)|![Simulator Screenshot - iPhone 14 Pro - 2024-05-17 at 15 37 10](https://github.com/artsy/eigen/assets/21178754/a46d7f3a-4c39-47fd-ac50-4c2b45182b22)| 
Also screenshots for two other uses of the same component (remained unaffected):
|Artist Series|Artist About|
|---|---|
|![Simulator Screenshot - iPhone 14 Pro - 2024-05-17 at 15 33 51](https://github.com/artsy/eigen/assets/21178754/8e58b939-33d2-4358-b615-c8537ab0f4ac)|![Simulator Screenshot - iPhone 14 Pro - 2024-05-17 at 15 30 …
> fix: padding for artist series

- src/app/Components/Artist/RelatedArtistsRail.tsx
This PR resolves [APPL-930] 
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 14 Pro - 2024-05-17 at 15 18 49](https://github.com/artsy/eigen/assets/21178754/d5829563-6a9d-459e-a13b-ff0bd34aa52a)|![Simulator Screenshot - iPhone 14 Pro - 2024-05-17 at 15 18 46](https://github.com/artsy/eigen/assets/21178754/7b19af6e-189f-48bf-a4d2-bef18164f64d)|
- add ListFooterComponent to RelatedArtistsRail for padding - gkartalis
-
-
- 
</details>
[APPL-930]: …
> fix: add ListFooterComponent to RelatedArtistsRail for padding

- src/app/Components/ArtsyWebView.tsx
This PR resolves [APPL-565] 
This PR fixes the issue in Android when tapping an external URL inside the webview
Where the user gets redirected to the browser, but the webview goes to a blank page
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/a9310489-c1ac-4221-b945-c7c17cfd6577" /> | <video src="https://github.com/artsy/eigen/assets/20655703/c6c9f359-db9a-4b8f-a037-91cb68b1345c" /> |
-
-
- Fix the issue with the webview having a blank page after tapping an external URL - mrsltun
-
</details>
[docs]: …
> fix(APPL-565): Fix external url issue in Android webview

- src/app/Scenes/Onboarding/OnboardingLoginWithOTP.tsx
Small addition to the OTP screen: this will allow the OS to add autocomplete suggestion.
- add OTP auto-complete to Login - mounir
-
-
-
</details>
> chore: add OTP auto-complete to Login

- src/app/Components/ContextMenu/ContextMenuArtwork.tsx
- src/app/store/config/features.ts
Changes requested by [Barney](https://artsy.slack.com/archives/C05EQL4R5N0/p1715340751240539):
-  'Not interested' -> 'Hide'
- Remove Save / Watch lot from the menu
I've also rearranged the menu, Hide goes to the bottom. Also added Echo feature flag.
-
- Long press on "New Works for You" artwork opens context menu; user can permanently suppress an artwork recommendation - @nickskalkin 
-
-
</details>
> feat: fixes suppress artwork copy, rearrange context menu, enable feature flag

- package.json
- src/app/Scenes/Partner/Components/PartnerFollowButton.tsx
- yarn.lock
This PR resolves these two bugs that came out of the Mobile QA session.
[Follows on partners](https://www.notion.so/artsy/Follow-button-The-Museum-of-Modern-art-broken-layout-on-Android-also-displays-followers-but-it-s-11b208e539074bf5bfe4b9f366ac7a3b?pvs=4)
[Onboarding follow loading bug](https://www.notion.so/artsy/Follow-button-in-gallery-list-in-Onboarding-flow-is-broken-f0979e9ec5ba477193b3dd602493f4da?pvs=4) - fixed [here](https://github.com/artsy/palette-mobile/pull/229)
Fixes both issues - one is the palette bump, the other you can see it in the diff here
|After||
|---|---|
|<img width="365" alt="Screenshot 2024-05-27 at 11 28 45" src="https://github.com/artsy/eigen/assets/21178754/f8532a4c-d2c5-43f3-bfdd-00c14ad94dd9">|<img width="367" alt="Screenshot 2024-05-27 at 11 28 39" …
> fix: follow button

- android/app/src/main/AndroidManifest.xml
- src/app/Scenes/Artwork/Components/ArtworkConsignments.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkConsignments.tsx
- src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tests.tsx
- src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
- src/app/Scenes/BottomTabs/bottomTabsConfig.tsx
This PR fixes the consign route on artwork pages. The route was changed from `/sales` to `/sell`
https://github.com/artsy/eigen/assets/11945712/2f599c0b-0634-4b40-9c11-52625d6892ce
- fix consign route on artwork pages - mounir
-
-
-
</details>
> fix: consign route on artwork pages

- package.json
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tests.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
- src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosPhotoItem.tsx
- yarn.lock
This PR resolves [ONYX-954] 
This PR updates the upload photos step to match the new designs:
List of features that I needed to maintain
- Inline error message on top of the image (did my best without design input)
- Loading progress (same here, design didn't add examples for this, so I had to improvise)
- Upload/Delete
https://github.com/artsy/eigen/assets/11945712/165adc54-75d3-409d-abca-cdf9035348f4
- update upload photos step to match designs in new submission flow - mounir
-
-
-
</details>
[ONYX-954]: …
> feat: update upload photos step to match designs

- src/app/AppRegistry.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
This PR updates the transition between screens on android to match the one on iOS
https://github.com/artsy/eigen/assets/11945712/5a53e2cc-0dfa-468d-be9b-4f9a58630c4e
https://github.com/artsy/eigen/assets/11945712/77fd3243-09c9-4fae-964a-c1fd2f9d2e11
-
-
-
-
</details>
> chore: update transition spec on android

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddTitle.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtworkMyCollectionArtwork.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkStartFlow.tsx
This PR resolves [ONYX-998] 
Fix: white block on top of input
-
-
-
-
</details>
[ONYX-998]: https://artsyproduct.atlassian.net/browse/ONYX-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: white block on top of input

- src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
- src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkFormEdit.tsx
We should update the submission on "Save and Exit." If we don't run the mutation, the changes on the current screen won't be saved.
- Update submission on Save and Exit in new SWA flow (behind feature flag) - ole
-
-
-
</details>
> fix: Update submission on Save and Exit

- app.json
Version bump to 8.41.0
#nochangelog
> chore: 8.41.0 release candidate

- app.json
Prep for `8.42.0`
#nochangelog
> chore: prep for 8.42.0

- fastlane/monkey_patches/supply_custom_promote.rb
Fixes broken Android promotion, our custom script was appending release to existing releases rather than replacing them which resulted in errors like "Too many staged releases specified" or "Only one completed release allowed", this replaces broken with the same method from the default promote method from fastlane. 
-
-
-
- fix broken android promotion - brian, george
</details>
> fix: broken android promote

- src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
- src/app/Scenes/SellWithArtsy/index.tests.tsx
This PR resolves [ONYX-949] 
This fixes the flashing SWA landing page image by adding a loading skeleton to the screen. Before, we rendered the screen without the data as a placeholder, which led to flashing when the screen re-renders after loading the data.
- Fix flashing SWA landing page image by adding a placeholder skeleton - ole
-
-
-
</details>
[ONYX-949]: https://artsyproduct.atlassian.net/browse/ONYX-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix flashing SWA landing page image

- package.json
- yarn.lock
Bumps netinfo
-
-
-
- bump @react-native-community/netinfo from 9.3.11 to 11.3.2 - carlosdariageorge
</details>
> build(deps): bump @react-native-community/netinfo from 9.3.11 to 11.3.2

- src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx
This PR resolves [APPL-897] 
Fixes the onboarding crash that we also had on sentry [event here](https://artsynet.sentry.io/issues/3914611711/events/1eb32280d80b417fbec5b07bf4efd9f0/).
|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/aa1885f2-cf80-4c1e-ac33-4a2413d3a8c6" width="400" />|<video src="https://github.com/artsy/eigen/assets/21178754/1674f905-3282-4c8b-9413-2317d8485c46" width="400" />|
-
-
- onboarding crash android hardware back button - gkartalis
- 
</details> …
> fix: onboarding crash android hardware back button

- ios/Podfile.lock
- src/app/Components/CircularSpinner.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/Hooks/useOnboardingContext.tsx
- src/app/Scenes/Onboarding/OnboardingQuiz/config.ts
- src/app/utils/WorkflowEngine/WorkflowEngine.tsx
I believe this will resolve: https://artsynet.sentry.io/issues/4274297374/events/recommended/?project=5867225
We have a crash in the onboarding quiz, I could not reproduce it but could see that it crashes in the split() method in the WorkflowEngine when the object passed in is undefined, also saw in the logs in sentry that the next method was called 2x in quick succession. I couldn't reproduce this manually but adding code to call it twice in a row did crash in the same way.
This just makes our code around this a little more defensive by checking if current is an object before trying to apply the split() method.
https://github.com/artsy/eigen/assets/49686530/80fa486f-f94e-4b06-82ec-e1913c5dec9e
https://github.com/artsy/eigen/assets/49686530/50dc63aa-f2c7-4c76-822e-c275 …
> fix: onboarding crash ios
